### ISSUE TITLE
How to run individual test?

### ISSUE THREAD

**Issue by huangyingw** [numpy/numpy#10077]
For example, I want to run this test file: core/tests/test_arrayprint.py,
and I get following error:
E
======================================================================
ERROR: Failure: ImportError (cannot import name add_newdocs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/Library/Python/2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Library/Python/2.7/site-packages/nose/importer.py", line 92, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/yhuang/Dropbox/myproject/git/AI/numpy/numpy/numpy/__init__.py", line 139, in <module>
    from . import add_newdocs
ImportError: cannot import name add_newdocs

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)

**Comment by eric-wieser** [comment]
You should use `python runtests.py -t numpy/core/tests/test_arrayprint.py`

**Comment by huangyingw** [comment]
@eric-wieser thank you very much.
