### ISSUE TITLE
BUG: MemoryError in np.histogram with large outliers and bins='auto'

### ISSUE THREAD

**Issue by amymcgovern** [numpy/numpy#10297]
If you run the following code (which I discovered inside matplotlib but it was shown to be a numpy issue), it will generate a memory error.

```
import numpy as np

training_input = np.random.rand(6545)
training_input[1000] = 1000000000000000

m, bins = np.histogram(training_input, 'auto')
```

**Comment by eric-wieser** [comment]
Does this persist if you replace the `np.random.rand` with `np.zeros`?

**Comment by amymcgovern** [comment]
No.  At least not on my machine.  With the code as it is, it gives me:

```
python(51008,0x7fffa6bc4340) malloc: *** mach_vm_map(size=149149164445495296) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/amy/anaconda2/lib/python2.7/site-packages/numpy/lib/function_base.py", line 564, in histogram
    n = np.zeros(bins, ntype)
MemoryError
```

**Comment by eric-wieser** [comment]
How about `arange`? It would be nice to find a deterministic reproduction

**Comment by amymcgovern** [comment]
arange just uses more and more memory.  I killed the process when it got to 2x my physical memory.  The rand version crashes 100% of the time for me and quickly.

**Comment by eric-wieser** [comment]
Ok, I can reproduce this as
```
training_input = np.random.RandomState(0).rand(6545)
training_input[1000] = 1000000000000000

m, bins = np.histogram(training_input, 'auto')
```

Which internally tries to allocate `18756969403331912` bins.

So the issue is in the `auto` estimator

**Comment by amymcgovern** [comment]
Yes.  The issue goes away if you fix the number of bins.  Glad you can find it and hopefully fix it!  Thanks!

**Comment by eric-wieser** [comment]
Elaborating further, the `auto` estimator is falling back on the `fd` estimator, which acts only on the middle quartiles of the data, and so produces a bin width that does not take into account outliers.

Offhand, i can think of two ways to fix this:

* Come up with a better auto estimator
* Merge adjacent empty bins somehow

**Comment by eric-wieser** [comment]
For your application of course, you simply need to pick a different estimator to 'auto'

**Comment by amymcgovern** [comment]
Yes, I fixed it using 100 bins (for my real data).  But I wanted you to know about the bug so it could be fixed.

**Comment by WarrenWeckesser** [comment]
Here's a related issue on stackoverflow: https://stackoverflow.com/questions/60653600/numpy-histogram-extremely-slow-on-small-data-set

**Comment by smarie** [comment]
Another way to quickly fix this would be to add a `max_nb_bins` parameter with a reasonable default value preventing matplotlib/numpy  such as `500` (or smaller : @amueller proposed `50` in https://github.com/numpy/numpy/issues/15569#issuecomment-604095969 ).

**Comment by mattip** [comment]
No longer reproduces, returns 162 bins on linux64.
