### ISSUE TITLE
Importing __config__ isn't working without explicit PATH env var

### ISSUE THREAD

**Issue by GeyseR** [numpy/numpy#10338]
Hi!

After updating numpy to 1.14.0 (which is dependency for pandas used in our project) it became impossible to run project without explicitly passing PATH variable to the global environment.

I believe the source of the bug is the next line:
https://github.com/numpy/numpy/blob/f1d81d84a2c8e3f44c434d580ab988912f9a4c83/numpy/distutils/misc_util.py#L2307

Full stack for the error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    autoreload.raise_last_exception()
  File "/usr/local/lib/python3.6/site-packages/django/utils/autoreload.py", line 251, in raise_last_exception
    six.reraise(*_exception)
  File "/usr/local/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.6/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/usr/local/lib/python3.6/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/code/analytics/models.py", line 6, in <module>
    import pandas as pd
  File "/usr/local/lib/python3.6/site-packages/pandas/__init__.py", line 13, in <module>
    __import__(dependency)
  File "/usr/local/lib/python3.6/site-packages/numpy/__init__.py", line 126, in <module>
    from numpy.__config__ import show as show_config
  File "/usr/local/lib/python3.6/site-packages/numpy/__config__.py", line 9, in <module>
    os.environ["PATH"] += os.pathsep + extra_dll_dir
  File "/usr/local/lib/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'PATH'
```

**Comment by charris** [comment]
@xoviat Thoughts?
