### ISSUE TITLE
varying Errors while changing the type of 0 as a step in arange

### ISSUE THREAD

**Issue by yarikoptic** [numpy/numpy#10496]
Originally spotted on Debian mips64el platform as a somewhat surprising message with numpy 1.13.3

```shell
(sid_mips64el-dchroot)yoh@eller:~/pymvpa2-2.6.4$ python -c 'import numpy as np; print(np.arange(-1, -1+0, np.float16(0.)))'                                                  
-c:1: RuntimeWarning: invalid value encountered in true_divide
Traceback (most recent call last):    
  File "<string>", line 1, in <module>                                                            
ValueError: array is too big; `arr.size * arr.dtype.itemsize` is larger than the maximum possible size.
```
which lead to discover that for every new type a new message would come about on x64 laptop:

```shell
$> python -c 'import numpy as np; print(np.arange(-1, -1+0, np.float(0.)))'
Traceback (most recent call last):    
  File "<string>", line 1, in <module>   
ZeroDivisionError: float division by zero
                                                     
$> python -c 'import numpy as np; print(np.arange(-1, -1+0, np.float64(0.)))'
-c:1: RuntimeWarning: invalid value encountered in double_scalars
[]
                                                     
$> python -c 'import numpy as np; print(np.arange(-1, -1+0, np.float32(0.)))'
-c:1: RuntimeWarning: invalid value encountered in true_divide

```

testing on current master (an informative pre-removal-numpybook-5689-gbb7b12672 state according to the git-describe ;-)), it is a bit better but still varying between ZeroDivision and ValueError

```shell
$> PYTHONPATH=. python -c 'import numpy as np; print(np.arange(-1, -1+0, 0.))'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ZeroDivisionError: float division by zero

$> PYTHONPATH=. python -c 'import numpy as np; print(np.arange(-1, -1+0, np.float(0.)))'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ZeroDivisionError: float division by zero

$> PYTHONPATH=. python -c 'import numpy as np; print(np.arange(-1, -1+0, np.float64(0.)))'
-c:1: RuntimeWarning: invalid value encountered in double_scalars
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ValueError: arange: cannot compute length

$> PYTHONPATH=. python -c 'import numpy as np; print(np.arange(-1, -1+0, np.float32(0.)))'
-c:1: RuntimeWarning: invalid value encountered in true_divide
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ValueError: arange: cannot compute length
```

Shouldn't it be even more consistent one way or another?

**Comment by ahaldane** [comment]
Just a quick comment: `np.float is float`, the python float type, so it makes sense that the first two examples are the same. The last two examples are both numpy floating types, so it also makes sense they give the same result.

Note this behavior:
```python
>>> 1/0.
ZeroDivisionError: float division by zero
>>> 1/np.float64(0)
RuntimeWarning: divide by zero encountered in double_scalars
inf
```

The mips64el error seems like a bug though. Is there anything pecial about that system's floats that is useful to know? The fact that you used `float16` is probably a red herring, the same happens for `float64`, right? (float16 is emulated in software by numpy, by the way, it is not a machine format). And what is the output of `1/np.float64(0)` on mips64el?

**Comment by yarikoptic** [comment]
but my question is -- shouldn't all of the above applications give the same exception?

re mips64el -- as I have noted in `edit1: FWIW ` at the end -- on current master on mips64el it produced the same results as on x64, but you rightfully pointed me to the use of float16... I think I did get the same with other floats there but can't say for sure.  Will double ccheck now and report

**Comment by ahaldane** [comment]
I see what you mean: It would make sense for `arange` to internally convert all arguments to the output dtype before doing any computations.

The code that controls that is here: https://github.com/numpy/numpy/blob/6f4e59c6f9baf15249691af118ba651b2f447549/numpy/core/src/multiarray/ctors.c#L3111
and the calculation that fails is int he same file in `_calc_length`. Indeed, it looks like it computes the array length and increment without first converting to a numpy type.

Probably most of the time it doesn't matter because numpy casting rules mean the computations result in the right dtype. Is there a case where the output values give a different result if we would cast first? I suppose if you were using the float128 dtype, but supplied your start and step as python 64-bit floats, the initial divisions would be performed at less precision...

**Comment by yarikoptic** [comment]
FWIW here is output on mips64el on pre-removal-numpybook-5705-gd1c66d0bb
```shell
(sid_mips64el-dchroot)yoh@eller:~/numpy$ PYTHONPATH=. python -c 'import numpy as np; print(np.arange(-1, -1+0, np.float(0.)))'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ZeroDivisionError: float division by zero
(sid_mips64el-dchroot)yoh@eller:~/numpy$ PYTHONPATH=. python -c 'import numpy as np; print(np.arange(-1, -1+0, np.float16(0.)))'
-c:1: RuntimeWarning: invalid value encountered in true_divide
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ValueError: arange: cannot compute length
```
and
```shell
(sid_mips64el-dchroot)yoh@eller:~/numpy$ PYTHONPATH=. python -c 'import numpy as np; 1/np.float64(0)'
-c:1: RuntimeWarning: divide by zero encountered in double_scalars
(sid_mips64el-dchroot)yoh@eller:~/numpy$ PYTHONPATH=. python -c 'import numpy as np; 1/np.float(0)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ZeroDivisionError: float division by zero
(sid_mips64el-dchroot)yoh@eller:~/numpy$ PYTHONPATH=. python -c 'import numpy as np; 1/np.float16(0)'
-c:1: RuntimeWarning: divide by zero encountered in divide
```

**Comment by campagnola** [comment]
Thanks for posting this, @yarikoptic. We just ran into the `ValueError: arange: cannot compute length` error and it took a long time to debug because the first thing we tried is just running `arange(1, 2, 0)`, which gives `ZeroDivisionError`, so immediately we assumed the problem was _not_ the 0 step argument.

**Comment by yarikoptic** [comment]
glad to "help" @campagnola ;-)
