### ISSUE TITLE
ENH: allow inconsistencies with `np.random.choice` via axis kwarg

### ISSUE THREAD

**Issue by trueProgrammer** [numpy/numpy#10578]
I have two "similar" arrays of arrays, but for the first one it works ok, but for the second one I get an error.

This is ok.
```
np.random.choice([
    [2, 54, 7049, 6914, 8513, 54, 777, 4016, 3998, 5822, 3097, 54, 5612, 249, 8052, 0],
    [2, 54, 4558, 525, 5155, 7049, 8284, 6939, 249, 6912, 5770, 0],
    [2, 54, 5566, 5822, 3097, 54, 5585, 5155, 6916, 3885, 7804, 7049, 0],
    [2, 54, 3519, 7298, 5155, 6939, 3885, 7804, 7049, 0],
    [2, 4558, 5155, 1967, 1868, 6939, 7669, 54, 949, 0]
])

[2, 54, 3519, 7298, 5155, 6939, 3885, 7804, 7049, 0]
```

But that one no.
```
np.random.choice([
    [2, 54, 3484, 5127, 3520, 6898, 5254, 54, 1724, 4316, 0],
    [2, 4697, 2375, 8068, 3885, 7804, 159, 5155, 7808, 6903, 0],
    [2, 7846, 929, 330, 6902, 249, 4079, 5129, 54, 8439, 0],
    [2, 7846, 8746, 4697, 4079, 7808, 6903, 5129, 54, 4316, 0],
    [2, 6675, 4697, 8572, 330, 5556, 8068, 5155, 54, 6898, 0]
])

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mtrand.pyx", line 1106, in mtrand.RandomState.choice (numpy/random/mtrand/mtrand.c:17109)
ValueError: a must be 1-dimensional
```

I don't see any real difference between them to get this exception, except all subarrays in the second case have **equal length**.

**Comment by eric-wieser** [comment]
In the first case, the mismatching lengths are causing promotion to a 1d `dtype=object` array. In the second case, the result is a 2d `dtype=int` array, hence the message. We are considering deprecating that first promotion (#10147).

It does seem like we could add an `axis` argument to `np.random.choice`, which would allow the second case.

**Comment by mattip** [comment]
Closing, the new API supports axis with a default of 0. If this is not satisfactory, please reopen or open a new issue. Note the return values from each call to choice may have different lengths, this may cause problems in other places. 

<details>

```
>>> np.random.Generator().choice([
...     [2, 54, 3484, 5127, 3520, 6898, 5254, 54, 1724, 4316, 0],
...     [2, 4697, 2375, 8068, 3885, 7804, 159, 5155, 7808, 6903, 0],
...     [2, 7846, 929, 330, 6902, 249, 4079, 5129, 54, 8439, 0],
...     [2, 7846, 8746, 4697, 4079, 7808, 6903, 5129, 54, 4316, 0],
...     [2, 6675, 4697, 8572, 330, 5556, 8068, 5155, 54, 6898, 0]
... ])
array([   2, 6675, 4697, 8572,  330, 5556, 8068, 5155,   54, 6898,    0])

```
