### ISSUE TITLE
np.random.choice(0, size=0) fails

### ISSUE THREAD

**Issue by girving** [numpy/numpy#10597]
`np.random.choice` requires the upper limit `a > 0`:

    >>> np.random.choice(0, size=0)
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "mtrand.pyx", line 1120, in mtrand.RandomState.choice
    ValueError: a must be greater than 0

This is necessary if `size > 0`, but if `size == 0` we could permit this special case.  Allowing the valid special case would simplify certain code, and in particular would make `np.random.choice(limit, size=min(n, limit)` always work.  The same goes for `np.random.randint`:

    >>> np.random.randint(0, size=0)
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "mtrand.pyx", line 993, in mtrand.RandomState.randint
    ValueError: low >= high

**Comment by eric-wieser** [comment]
See #8717

**Comment by girving** [comment]
@eric-wieser Yikes!  It sounded so simple...

Duplicate of https://github.com/numpy/numpy/issues/8311.
