### ISSUE TITLE
np.flatnonzero doesn't cast to ndarray

### ISSUE THREAD

**Issue by girving** [numpy/numpy#10598]
Thus, it fails for lists and such:

    >>> np.flatnonzero([1,2,3])
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File ".../python3.6/site-packages/numpy/core/numeric.py", line 859, in flatnonzero
        return a.ravel().nonzero()[0]
    AttributeError: 'list' object has no attribute 'ravel'

**Comment by girving** [comment]
PR coming up.

**Comment by eric-wieser** [comment]
Note that this is as documented, because it says the argument is an `ndarray`
