### ISSUE TITLE
np.iinfo('ulong') fails

### ISSUE THREAD

**Issue by pitrou** [numpy/numpy#10678]
```
>>> np.iinfo('intc')
iinfo(min=-2147483648, max=2147483647, dtype=int32)
>>> np.iinfo('uintc')
iinfo(min=0, max=4294967295, dtype=uint32)
>>> np.iinfo('longlong')
iinfo(min=-9223372036854775808, max=9223372036854775807, dtype=int64)
>>> np.iinfo('ulonglong')
iinfo(min=0, max=18446744073709551615, dtype=uint64)
>>> np.iinfo('long')
iinfo(min=-9223372036854775808, max=9223372036854775807, dtype=int64)
>>> np.iinfo('ulong')
Traceback (most recent call last):
  File "<ipython-input-20-e783aa7ef3c1>", line 1, in <module>
    np.iinfo('ulong')
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.6/site-packages/numpy/core/getlimits.py", line 516, in __init__
    raise ValueError("Invalid integer data type.")
ValueError: Invalid integer data type.
```

**Comment by eric-wieser** [comment]
Easy fix here is to use `np.iinfo(np.uint)`

I think this is because `'long'` is decoded to `__buitins__.long`

**Comment by pitrou** [comment]
According to https://docs.scipy.org/doc/numpy/user/basics.types.html :
> Additionally to intc the platform dependent C integer types short, long, longlong and their unsigned versions are defined.

**Comment by eric-wieser** [comment]
Docs are wrong. The C integer type `long` is called `np.int_`, and the integer type `ulong` is called `np.uint`

**Comment by eric-wieser** [comment]
Thanks for finding this @ax3l

**Comment by ax3l** [comment]
No problem, can only forward the thanks to @C0nsultant we pointed me here :)
