### ISSUE TITLE
'arr' does not have a suitable array shape for any mode

### ISSUE THREAD

**Issue by kjaisinghyadav** [numpy/numpy#10770]
Here , This is i am trying
```python
image_array = np.fromfile('C:/Program Files/Notepad++/notepad++.exe')
```
i want to save executable in the form of image or i want to convert binary executable to image format(jpg or png or bitmap). but i am getting below error. so please tell me how to fix this

```
Traceback (most recent call last):
  File "F:\Experimental\MyTensFLow\Practice\open_file.py", line 12, in <module>
    scipy.misc.imsave('C:/Users/PAL/Desktop/outfile.jpg', image_array)
  File "C:\Program Files\Python35\lib\site-packages\numpy\lib\utils.py", line 101, in newfunc
    return func(*args, **kwds)
  File "C:\Program Files\Python35\lib\site-packages\scipy\misc\pilutil.py", line 217, in imsave
    im = toimage(arr, channel_axis=2)
  File "C:\Program Files\Python35\lib\site-packages\numpy\lib\utils.py", line 101, in newfunc
    return func(*args, **kwds)
  File "C:\Program Files\Python35\lib\site-packages\scipy\misc\pilutil.py", line 326, in toimage
    raise ValueError("'arr' does not have a suitable array shape for "
ValueError: 'arr' does not have a suitable array shape for any mode.
```

**Comment by njsmith** [comment]
This is really a question about `scipy.misc.imsave`, not numpy... but since you're here, the issue is that `imsave` requires a 2-dimensional array (because it's, you know, an image). Your array is one-dimensional (because it's a flat string of bytes). You need to decide how you want to convert it 2d; that's not something we can decide for you. But a call to `image_array.reshape(...)` will help.

For future reference, this kind of usage question is usually better asked on stackoverflow.com. Good luck.

**Comment by kjaisinghyadav** [comment]
Thank you
