### ISSUE TITLE
BUG: `np.einsum` accepts some subscripts only when optimize=True

### ISSUE THREAD

**Issue by kmaehashi** [numpy/numpy#10926]
It seems that the acceptable syntax of `np.einsum` subscripts are different when optimize option is set or not.

```py
>>> import numpy as np

>>> x = np.ones((2, 2, 2))

>>> np.einsum('...->', x, optimize=True)
8.0

>>> np.einsum('...->', x, optimize=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kenichi/.pyenv/versions/local-3.6.3/lib/python3.6/site-packages/numpy/core/einsumfunc.py", line 948, in einsum
    return c_einsum(*operands, **kwargs)
ValueError: output had too few broadcast dimensions

>>> np.einsum('i...j->ij', x, optimize=True)
array([[ 2.,  2.],
       [ 2.,  2.]])

>>> np.einsum('i...j->ij', x, optimize=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kenichi/.pyenv/versions/local-3.6.3/lib/python3.6/site-packages/numpy/core/einsumfunc.py", line 948, in einsum
    return c_einsum(*operands, **kwargs)
ValueError: output has more dimensions than subscripts given in einstein sum, but no '...' ellipsis provided to broadcast the extra dimensions.
```

**Comment by jaimefrio** [comment]
Thanks for reporting, that's very unfortunate...

I wasn't fully aware that we had reproduced the whole index parsing of einsum, originally implemented in C, in Python for the `optimize=True` case. I think this is a terrible idea, and we should merge them into a single implementation, to avoid this kind of issues. If it doesn't affect performance substantially, we should of course prefer a single Python implementation over a single C implementation, but someone will have to spend some time profiling to decide a path forward.

**Comment by mhvk** [comment]
@dgasmith - would you have any suggestions? As we saw in #10359, the overhead of doing the parsing in python is prohibitive for some applications, but I also appreciate your comment there that for the optimization, you need to know some of the details of the signature that perhaps are not easily accessible after the C parser....  Still, it would be really good to have it in just one place...

**Comment by charris** [comment]
I'd like to see this in C at some point, with a well defined parser as well as a way to cache or return parsed arguments for reuse in repetitive applications. IIRC, @mwiebe did some work for DyND that would be useful for storing the result as a ribbon of executable statements.

**Comment by cournape** [comment]
@charris do you know where this was done in dynd ? A few grep did not go anywhere, but I am not familiar w/ dynd codebase.

**Comment by dgasmith** [comment]
Yea, the doubling of parsers isn't exactly a great idea. We originally looked at trying to pull apart einsum and its parser, but they are quite integrated together so the Python version was done as a stop gap solution. The Python-based parser is probably not a good solution in the long run as folks use `np.einsum` for low latency computations.

**Comment by matthew-brett** [comment]
Would it be practical to write parser in Cython?

**Comment by charris** [comment]
@cournape It was a talk at Scipy 2016: https://www.youtube.com/watch?v=0sFwa-Sl5vg .  Basically, it was a way to string together a bunch of function calls, which is pretty much what einsum does.

**Comment by charris** [comment]
Einsum is such a useful function that is would be good to look into more optimizations for it. It was pretty well optimized for the available hardware and compilers at the time it was written, but I suspect it could be improved, especially with the vectorized multiply accumulate instructions that are now available. Maybe we could suggest that to the Intel team.

**Comment by toslunar** [comment]
FYI, besides ellipsis, the following is accepted by `einsum_path` (Python) but eventually rejected by `c_einsum` (C).
```
>>> np.einsum_path('ii->i', np.ones((1, 3)), einsum_call=True)
([array([[1., 1., 1.]])], [((0,), set(), 'ii->i', ['i'], False)])
>>> np.einsum('ii->i', np.ones((1, 3)))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tos/py/lib/python3.6/site-packages/numpy/core/einsumfunc.py", line 1069, in einsum
    return c_einsum(*operands, **kwargs)
ValueError: dimensions in operand 0 for collapsing index 'i' don't match (1 != 3)
>>> np.__version__
'1.14.2'
```

**Comment by toslunar** [comment]
`einsum_path` raises `TypeError` while `c_einsum` raises `ValueError`:
```
>>> np.einsum([None], np.arange(2), optimize=False)
(snip)
ValueError: each subscript must be either an integer or an ellipsis
>>> np.einsum([None], np.arange(2), optimize=True)
(snip)
TypeError: For this input type lists must contain either int or Ellipsis
```

**Comment by jaimefrio** [comment]
I have started looking into einsum's parsing, see #11095. If that gets merged I'll look into making the parsing a standalone function, and adding a Python wrapper so that 'einsum_path' can call it and we can get rid of the duplicate parsers.

**Comment by toslunar** [comment]
Found by @asi1024:
```
>>> numpy.einsum('a- >a', numpy.array([3,4]), optimize=True)
array([3, 4])
>>> numpy.einsum('. ..->...', numpy.array([3,4]), optimize=True)
array([3, 4])
```
