### ISSUE TITLE
optimized einsum may ignore some options

### ISSUE THREAD

**Issue by toslunar** [numpy/numpy#11060]
`np.einsum`'s optimized blas call ignores `dtype` option.
```
>>> np.einsum('ij,jk', np.eye(3, dtype=np.float32), np.eye(3, dtype=np.float32), dtype=np.float64, optimize=True)
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)
>>> np.einsum('ij,jk', np.eye(3, dtype=np.float32), np.eye(3, dtype=np.float32), dtype=np.float64)
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])
```

Thus it also ignore `casting` option.
```
>>> np.einsum('ij,jk', np.eye(3, dtype=np.float64), np.eye(3, dtype=np.float64), dtype=np.float32, optimize=True)
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])
>>> np.einsum('ij,jk', np.eye(3, dtype=np.float64), np.eye(3, dtype=np.float64), dtype=np.float32, optimize=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tos/py3/lib/python3.6/site-packages/numpy/core/einsumfunc.py", line 1069, in einsum
    return c_einsum(*operands, **kwargs)
TypeError: Iterator operand 0 dtype could not be cast from dtype('float64') to dtype('float32') according to the rule 'safe'
>>>
```

**Comment by dgasmith** [comment]
Yea, `np.dot` and `np.tensordot` do not have this functionality built in. Specifically for `einsum` we should probably check the types of the input tensor where we run `input = input.astype(dtype=dtype, casting=casting, copy=False)`.

We might want to consider running `astype` on the output as well so that we obey the output ordering.

@charris Any thoughts here?
