### ISSUE TITLE
np.linalg.eig doesn't process the SIGINT

### ISSUE THREAD

**Issue by yurivict** [numpy/numpy#11081]
Ctrl-C doesn't have any effect.

py27-numpy-1.13.3_3,1 on FreeBSD-11.1

**Comment by mattip** [comment]
It is hard to pick the right time, but it seems OpenBlas is not respecting the signal. When I hit ^C after ~2 seconds until the code enters the `eig` call, the interrupt only returns after ~5 more seconds.
```
>>> c,d = np.linalg.eig(a)
>>> a = np.empty((100, 1000,1000), dtype=float) # big enough to take some time
>>> c,d = np.linalg.eig(a)
^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/matti/pypy_stuff/cpython3_virt/lib/python3.6/site-packages/numpy/linalg/linalg.py", line 1256, in eig
    w, vt = _umath_linalg.eig(a, signature=signature, extobj=extobj)
KeyboardInterrupt
>>> 
```

**Comment by seberg** [comment]
I tseems (with the exception of a few releases which recieved backports). A possible solution should be to call `PyOS_InterruptOccurred()` repeatedly.  We could probably query that periodically in the outer iteration either in the iterator, or the ufunc machinery itself.
