### ISSUE TITLE
raise value error

### ISSUE THREAD

**Issue by shiva951221** [numpy/numpy#11100]
Traceback (most recent call last):
  File "/home/shadan/deep-forecast-pytorch/data/scripts/1-process.py", line 10, in <module>
    data = np.loadtxt(args.input, dtype='str', delimiter=',')
  File "/home/shadan/anaconda3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 925, in loadtxt
    raise ValueError('fname must be a string, file handle, or generator')
ValueError: fname must be a string, file handle, or generator

**Comment by seberg** [comment]
Sounds like the value error is spot on, and you should check what `args.input` is.

**Comment by shiva951221** [comment]
thanks alot
