### ISSUE TITLE
Regression in np.squeeze(scalar, axis=())

### ISSUE THREAD

**Issue by toslunar** [numpy/numpy#11384]
It seems the change in #10826 caused the following error.  To fix this, numpy scalar types' `.squeeze` should accept `axis` argument.
Version: 1.15.0rc1
```
>>> np.squeeze(np.array(np.float32(1)), axis=())
array(1., dtype=float32)
>>> np.squeeze(np.float32(1), axis=())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tos/GitHub/numpy/numpy/core/fromnumeric.py", line 1292, in squeeze
    return squeeze(axis=axis)
TypeError: squeeze() takes no keyword arguments
>>> np.sum(np.float32(1), axis=())
1.0
```

**Comment by charris** [comment]
This works for me in master.

**Comment by toslunar** [comment]
For me in master:
```
% git clean -dfx && python setup.py develop
(snip)
% python
Python 3.6.5 (default, Mar 29 2018, 15:34:48)
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> np.squeeze(np.float32(1), axis=())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tos/GitHub/numpy/numpy/core/fromnumeric.py", line 1292, in squeeze
    return squeeze(axis=axis)
TypeError: squeeze() takes no keyword arguments
>>> np.__version__
'1.16.0.dev0+e110f93'
>>> np.show_config()
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/opt/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas', 'openblas']
    library_dirs = ['/opt/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/opt/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas', 'openblas']
    library_dirs = ['/opt/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
>>>
```
