### ISSUE TITLE
module 'numpy' has no attribute 'testing'

### ISSUE THREAD

**Issue by atmecskrishna** [numpy/numpy#11400]
Getting this error when creating a program for face recognition

Below is the traceback

Using TensorFlow backend.
Traceback (most recent call last):

  File "<ipython-input-31-1ae46e981914>", line 1, in <module>
    runfile('D:/python/Face-Recognition-master/Face-Recognition-master/recognize.py', wdir='D:/python/Face-Recognition-master/Face-Recognition-master')

  File "C:\Users\krishna.tiwari\AppData\Local\Continuum\anaconda3\envs\face\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\Users\krishna.tiwari\AppData\Local\Continuum\anaconda3\envs\face\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "D:/python/Face-Recognition-master/Face-Recognition-master/recognize.py", line 7, in <module>
    from keras.models import load_model

  File "C:\Users\krishna.tiwari\AppData\Local\Continuum\anaconda3\envs\face\lib\site-packages\keras\__init__.py", line 3, in <module>
    from . import utils

  File "C:\Users\krishna.tiwari\AppData\Local\Continuum\anaconda3\envs\face\lib\site-packages\keras\utils\__init__.py", line 6, in <module>
    from . import conv_utils

  File "C:\Users\krishna.tiwari\AppData\Local\Continuum\anaconda3\envs\face\lib\site-packages\keras\utils\conv_utils.py", line 9, in <module>
    from .. import backend as K

  File "C:\Users\krishna.tiwari\AppData\Local\Continuum\anaconda3\envs\face\lib\site-packages\keras\backend\__init__.py", line 87, in <module>
    from .tensorflow_backend import *

  File "C:\Users\krishna.tiwari\AppData\Local\Continuum\anaconda3\envs\face\lib\site-packages\keras\backend\tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf

  File "C:\Users\krishna.tiwari\AppData\Local\Continuum\anaconda3\envs\face\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import

  File "C:\Users\krishna.tiwari\AppData\Local\Continuum\anaconda3\envs\face\lib\site-packages\tensorflow\python\__init__.py", line 81, in <module>
    from tensorflow.python import keras

  File "C:\Users\krishna.tiwari\AppData\Local\Continuum\anaconda3\envs\face\lib\site-packages\tensorflow\python\keras\__init__.py", line 27, in <module>
    from tensorflow.python.keras import applications

  File "C:\Users\krishna.tiwari\AppData\Local\Continuum\anaconda3\envs\face\lib\site-packages\tensorflow\python\keras\applications\__init__.py", line 21, in <module>
    from tensorflow.python.keras.applications import densenet

  File "C:\Users\krishna.tiwari\AppData\Local\Continuum\anaconda3\envs\face\lib\site-packages\tensorflow\python\keras\applications\densenet\__init__.py", line 21, in <module>
    from tensorflow.python.keras._impl.keras.applications.densenet import decode_predictions

  File "C:\Users\krishna.tiwari\AppData\Local\Continuum\anaconda3\envs\face\lib\site-packages\tensorflow\python\keras\_impl\keras\__init__.py", line 22, in <module>
    from tensorflow.python.keras._impl.keras import applications

  File "C:\Users\krishna.tiwari\AppData\Local\Continuum\anaconda3\envs\face\lib\site-packages\tensorflow\python\keras\_impl\keras\applications\__init__.py", line 21, in <module>
    from tensorflow.python.keras._impl.keras.applications.densenet import DenseNet121

  File "C:\Users\krishna.tiwari\AppData\Local\Continuum\anaconda3\envs\face\lib\site-packages\tensorflow\python\keras\_impl\keras\applications\densenet.py", line 35, in <module>
    from tensorflow.python.keras._impl.keras.layers import Activation

  File "C:\Users\krishna.tiwari\AppData\Local\Continuum\anaconda3\envs\face\lib\site-packages\tensorflow\python\keras\_impl\keras\layers\__init__.py", line 22, in <module>
    from tensorflow.python.keras._impl.keras.engine import Input

  File "C:\Users\krishna.tiwari\AppData\Local\Continuum\anaconda3\envs\face\lib\site-packages\tensorflow\python\keras\_impl\keras\engine\__init__.py", line 27, in <module>
    from tensorflow.python.keras._impl.keras.engine.training import Model

  File "C:\Users\krishna.tiwari\AppData\Local\Continuum\anaconda3\envs\face\lib\site-packages\tensorflow\python\keras\_impl\keras\engine\training.py", line 30, in <module>
    from tensorflow.python.keras._impl.keras.engine import training_arrays

  File "C:\Users\krishna.tiwari\AppData\Local\Continuum\anaconda3\envs\face\lib\site-packages\tensorflow\python\keras\_impl\keras\engine\training_arrays.py", line 35, in <module>
    from scipy.sparse import issparse  # pylint: disable=g-import-not-at-top

  File "C:\Users\krishna.tiwari\AppData\Local\Continuum\anaconda3\envs\face\lib\site-packages\scipy\sparse\__init__.py", line 228, in <module>
    from .base import *

  File "C:\Users\krishna.tiwari\AppData\Local\Continuum\anaconda3\envs\face\lib\site-packages\scipy\sparse\base.py", line 9, in <module>
    from scipy._lib._numpy_compat import broadcast_to

  File "C:\Users\krishna.tiwari\AppData\Local\Continuum\anaconda3\envs\face\lib\site-packages\scipy\_lib\_numpy_compat.py", line 17, in <module>
    _assert_warns = np.testing.assert_warns

AttributeError: module 'numpy' has no attribute 'testing'

"_assert_warns = np.testing.assert_warns

AttributeError: module 'numpy' has no attribute 'testing' "

**Comment by charris** [comment]
Sounds like an installation problem, probably related to the mix of apps. Anaconda is probably your best bet for tracking this down.

**Comment by mhvk** [comment]
@luca-peliti - no problem, these things happen to all of us. I'll close your issue.

**Comment by hamidkarimi** [comment]
I had the same issue. I had created a python file in my project named 'random.py' and causing the numpy to confuse :)
