### ISSUE TITLE
Guidance provided by numpy when using sdist leads to errors.

### ISSUE THREAD

**Issue by rstoneback** [numpy/numpy#11433]
I'm trying to put together a python package that also compiles a Fortran extension. I'd like to include a version.txt file as part of the package, however, I seem to only get two outcomes:

```
1) If I don't specify within setup.py 
"from distutils.command.sdist import sdist
    cmdclass={'sdist': sdist}"
```
then the version.txt file is not included in the source distribution.

2) If I follow the advice to use numpy's sdist, then I get:
```
python setup.py sdist
Traceback (most recent call last):
  File "setup.py", line 42, in <module>
    ext_modules = config.todict()['ext_modules'],
  File "/Users//Library/Enthought/Canopy/edm/envs/Python_2/lib/python2.7/site-packages/numpy/distutils/core.py", line 169, in setup
    return old_setup(**new_attr)
  File "/Users//Library/Enthought/Canopy/edm/envs/Python_2/lib/python2.7/distutils/core.py", line 137, in setup
    ok = dist.parse_command_line()
  File "/Users//Library/Enthought/Canopy/edm/envs/Python_2/lib/python2.7/distutils/dist.py", line 467, in parse_command_line
    args = self._parse_command_opts(parser, args)
  File "/Users//Library/Enthought/Canopy/edm/envs/Python_2/lib/python2.7/distutils/dist.py", line 529, in _parse_command_opts
    if not issubclass(cmd_class, Command):
TypeError: issubclass() arg 1 must be a class
```

Full setup.py copied below:
```
# import setuptools
import numpy.distutils.core
import os

from numpy.distutils.misc_util import Configuration
from numpy.distutils.command import sdist as sdist

config = Configuration('pysatMagVect')

# create extension for calling IGRF
config.add_extension(name='igrf',
    sources = [os.path.join('pysatMagVect', 'igrf12.f')]
    )

here = os.path.abspath(os.path.dirname(__file__))
#with open(path.join(here, 'description.txt'), encoding='utf-8') as f:
#    long_description = f.read()
version_filename = os.path.join('pysatMagVect', 'version.txt')
with open(os.path.join(here, version_filename)) as version_file:
    version = version_file.read().strip()

# call setup
#--------------------------------------------------------------------------
numpy.distutils.core.setup( 

    name = 'pysatMagVect',
    version = '0.1.3',        
    packages = ['pysatMagVect','pysatMagVect.tests'],
    description= ''.join(('Calculates geomagnetic unit vectors (field aligned, zonal, and meridional) '
                 'and includes supporting routines for characterizing the motion of ionospheric plasma.')),
    cmdclass={'sdist': sdist},
   
    # Author details
    author='Russell Stoneback',
    author_email='rstoneba@utdallas.edu',
    package_data={'pysatMagVect': ['pysatMagVect/version.txt']},
    include_package_data=True,
    
    ext_modules = config.todict()['ext_modules'],

    install_requires = ['numpy', 'scipy',],

)  
```

This is on  numpy 1.14.3; Mac OS X 10.12.6

**Comment by rgommers** [comment]
This isn't really `numpy` related. Short answer I think: use a `MANIFEST.in` file with the line `include version.txt` in it. Then that file will end up in your sdist.
