### ISSUE TITLE
BUG: isposinf and isneginf fail for complex values

### ISSUE THREAD

**Issue by jor-** [numpy/numpy#11438]
The functions `np.isposinf` and `np.isneginf` fail for arrays with complex values.

```
>>> import numpy as np
>>> a = np.arange(2) + 1j
>>> np.isposinf(a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/numpy/lib/ufunclike.py", line 34, in func
    return f(x, out=out, **kwargs)
  File "/usr/lib/python3/dist-packages/numpy/lib/ufunclike.py", line 141, in isposinf
    return nx.logical_and(nx.isinf(x), ~nx.signbit(x), out)
TypeError: ufunc 'signbit' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
>>> np.isneginf(a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/numpy/lib/ufunclike.py", line 34, in func
    return f(x, out=out, **kwargs)
  File "/usr/lib/python3/dist-packages/numpy/lib/ufunclike.py", line 202, in isneginf
    return nx.logical_and(nx.isinf(x), nx.signbit(x), out)
TypeError: ufunc 'signbit' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```
I used NumPy 1.14.5 and Python 3.6.

**Comment by mattip** [comment]
`np.isposinf(complex(x,y))` should return True for only x=np.inf, y=0.

**Comment by jakirkham** [comment]
It looks like PR ( https://github.com/numpy/numpy/pull/11503 ) updated the error handling for this case. Should this issue be closed or should the behavior of `np.isposinf` be changed to match what @mattip describes?

**Comment by jor-** [comment]
There was a discussion in #11503 whether the functionality should be extended. We decided not to extend it to complex numbers. Nevertheless the error handling was updated. (I just forgot to close this issue.)
