### ISSUE TITLE
Warning test failures for Python 3.7 / numpy 1.14.5

### ISSUE THREAD

**Issue by matthew-brett** [numpy/numpy#11460]
Found during attempt to build 1.14.5 wheels:

```
======================================================================
FAIL: numpy.testing.tests.test_utils.test_clear_and_catch_warnings
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/venv/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/venv/lib/python3.7/site-packages/numpy/testing/tests/test_utils.py", line 1123, in test_clear_and_catch_warnings
    assert_warn_len_equal(my_mod, 1)
  File "/venv/lib/python3.7/site-packages/numpy/testing/tests/test_utils.py", line 1096, in assert_warn_len_equal
    assert_equal(len(mod_warns) - 1, py3_n_in_context)
  File "/venv/lib/python3.7/site-packages/numpy/testing/nose_tools/utils.py", line 411, in assert_equal
    raise AssertionError(msg)
AssertionError: 
Items are not equal:
 ACTUAL: 0
 DESIRED: 1
======================================================================
FAIL: numpy.testing.tests.test_utils.test_suppress_warnings_module
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/venv/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/venv/lib/python3.7/site-packages/numpy/testing/tests/test_utils.py", line 1180, in test_suppress_warnings_module
    assert_warn_len_equal(my_mod, 1)
  File "/venv/lib/python3.7/site-packages/numpy/testing/tests/test_utils.py", line 1096, in assert_warn_len_equal
    assert_equal(len(mod_warns) - 1, py3_n_in_context)
  File "/venv/lib/python3.7/site-packages/numpy/testing/nose_tools/utils.py", line 411, in assert_equal
    raise AssertionError(msg)
AssertionError: 
Items are not equal:
 ACTUAL: 0
 DESIRED: 1
======================================================================
FAIL: numpy.testing.tests.test_utils.test_suppress_warnings_type
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/venv/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/venv/lib/python3.7/site-packages/numpy/testing/tests/test_utils.py", line 1208, in test_suppress_warnings_type
    assert_warn_len_equal(my_mod, 1)
  File "/venv/lib/python3.7/site-packages/numpy/testing/tests/test_utils.py", line 1096, in assert_warn_len_equal
    assert_equal(len(mod_warns) - 1, py3_n_in_context)
  File "/venv/lib/python3.7/site-packages/numpy/testing/nose_tools/utils.py", line 411, in assert_equal
    raise AssertionError(msg)
AssertionError: 
Items are not equal:
 ACTUAL: 0
 DESIRED: 1
```

https://travis-ci.org/MacPython/numpy-wheels/jobs/398441500#L3962

https://travis-ci.org/MacPython/numpy-wheels/jobs/398441501#L4068

https://travis-ci.org/MacPython/numpy-wheels/jobs/398441506#L5395

**Comment by seberg** [comment]
Harmless, but should be fixed, actually, I think only the tests need fixing. I am a bit confused though, because I thought we just fixed this kind of thing up a while back, did 3.7 change it yet again?

**Comment by matthew-brett** [comment]
Sorry - maybe this has already been fixed in master, but these are for 1.14.5 ...

**Comment by charris** [comment]
IIRC, nose also isn't 3.7 compatible, although the fix was easy. Note that master was/is being tested against 3.7-dev.

BTW, the daily cron jobs are not uploading, so there are no daily builds.

**Comment by seberg** [comment]
@matthew-brett nah, that was a change in 3.6 or so I think. My guess is python 3.7 pimped up their `catch_warnings` context somehow, and that causes it to clean up oddly well, or the whole logic got changed again somehow.

**Comment by seberg** [comment]
Or dunno, maybe I am confusing also and there was just some back and forth in python dev.

**Comment by charris** [comment]
There was a change in 3.7, I think we needed to fix the tests.

**Comment by charris** [comment]
Here we are:
```
    # Without specified modules, don't clear warnings during context
    # Python 3.7 does not add ignored warnings.
    with suppress_warnings():
        warnings.simplefilter('ignore')
        warnings.warn('Some warning')
    assert_warn_len_equal(my_mod, 1, py37=0)
```
Note the new keyword `py37`, the `assert_warn_len_equal` function was also changed. If we really want to fix these, the relevant tests should simply be copied over whole.

**Comment by seberg** [comment]
So I was just confused with the timing and versions and it is already fixed in master... if we do not officially support 3.7, a bit unfortunate that these are actual test errors OTOH.

**Comment by bsipocz** [comment]
These tests got fixed to pass. Th underlying issue may be valid (https://github.com/numpy/numpy/pull/21558#issuecomment-1133517339) but not worth fixing, and the context is deemed to be removed.
So I go ahead and close this issue. Please reopen if you think otherwise.
