### ISSUE TITLE
np.cov suggestion: for one variable data, return either a scalar or a (1, 1) array. Don't return a ndim 0 array.

### ISSUE THREAD

**Issue by johnmwu** [numpy/numpy#11502]
As it stands,

```
>>> np.cov([[1, 2, 3]])
array(1.)
```

I feel that this is a bit unnatural, considering that any input array of first dimension > 1 will return an ndim 2 array. 

For example,
```
>>> np.cov([[1, 2, 3], [4, 5, 6]])
array([[1., 1.],
       [1., 1.]])
```

I suggest that either:

1. A scalar is returned. This would be useful for those people that prefer to use a single function for everything, and thus use cov for computing variance as well.
2. A (1, 1) array is returned. This would provide greater consistency with what is returned.

**Comment by johnmwu** [comment]
Hmm. As far as special cases are concerned, it ultimately boils down to one of the essential stylistic choices of programming: whether more or less requirements is better. Is it better to require a specific sort of thing passed in, or is it better to allow any intuitively clear thing passed in, and then the function will handle the messy details?

My philosophy is that more is almost always better. A slight extension of this is that a function should always return the same type (meaning that for NumPy, we may end up extracting lots of scalars from (1, 1) arrays, but I'm okay with this). However, NumPy is NumPy and internal consistency is ultimately the most important. 

NumPy does typically do "intuitive" reshaping for you (anecdotally), so I may have to disagree with you somewhat there. I do not believe that all those lines are a mistake.

I should also mention that there are two typical uses of `cov`: 
* when passing in a single rowvar representation of a dataset (each variable is a row, individual observations are columns)
* when passing in two rank 1 arrays of equal length

I do agree, though, that there is a bit too much special-casing going on. Specifically, I disagree with the choice of checking whether X, y's first dimensions are 1. These two particular checks result in extremely odd, nonsymmetric behavior like:
```
>>> a = np.zeros((2, 2))
>>> b = np.zeros((1, 2))
>>> np.cov(a, b, rowvar=False)
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])
>>> # No Error!
```

But 
```
>>> a = np.zeros((2, 2))
>>> b = np.zeros((2, 1))
>>> np.cov(a, b, rowvar=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "fakepath\lib\site-packages\numpy\lib\function_base.py", line 3044, in cov
    X = np.concatenate((X, y), axis=0)
ValueError: all the input array dimensions except for the concatenation axis must match exactly
```

**Comment by eric-wieser** [comment]
> Is it better to require a specific sort of thing passed in, or is it better to allow any intuitively clear thing passed in, and then the function will handle the messy details?

PEP20 is [pretty clear on this](https://zen-of-python.info/in-the-face-of-ambiguity-refuse-the-temptation-to-guess.html#12)

> In the face of ambiguity, refuse the temptation to guess.

**Comment by eric-wieser** [comment]
Expressing the original issue here more clearly:

```
>>> np.cov(np.zeros(0, 10)).ndim
2
>>> np.cov(np.zeros(0, 10)).ndim
0  # ???
>>> np.cov(np.zeros(2, 10)).ndim
2
>>> np.cov(np.zeros(3, 10)).ndim
2
```

**Comment by vnmabus** [comment]
I have bumped into the same issue. In my opinion, the result should only have empty shape if the input was a 1D-array, not if it was a 2D-array with 1 as the first dimension.
