### ISSUE TITLE
Unexpected behavior of numpy.einsum on arrays with singleton dimensions

### ISSUE THREAD

**Issue by kielpins** [numpy/numpy#11548]
When operating on arrays with singleton dimensions, numpy.einsum does not always enforce shape matching over summed dimensions. Instead it can return a surprising result. Minimal example:
```
import numpy as np
a = np.arange(4).reshape(4,1)
b = 2 * np.arange(3).reshape(1,3)
c = np.einsum('ik,jk->ij', a, b)
```
Here I would expect a `ValueError`: we are summing over the `k` index, but `k` has length 1 for `a` and length 3 for `b`. However, `einsum` instead returns a value for `c` that is equal to `a * b.sum()`.
```
>>> print(c)
[[ 0]
 [ 6]
 [12]
 [18]]
>>> c.shape
(4, 1)
```
I suppose this could be related to broadcasting behavior, but the documentation is fairly clear that broadcasting should only occur when the `subscripts` argument contains ellipses.

For arrays with no singleton dimensions, `einsum` throws a `ValueError` as expected. This example:
```
import numpy as np
a = np.arange(8).reshape(4,2)
b = 2 * np.arange(6).reshape(2,3)
c = np.einsum('ik,jk->ij', a, b)
```
produces
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dave/.conda/envs/dk_env/lib/python3.6/site-packages/numpy/core/einsumfunc.py", line 1069, in einsum
    return c_einsum(*operands, **kwargs)
ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (4,2)->(4,newaxis,2) (2,3)->(2,3) 
```

I am running numpy 1.14.5 under python 3.6.5 on Mac OSX.

**Comment by charris** [comment]
Singleton dimensions are broadcast, that is standard numpy behavior.

**Comment by kielpins** [comment]
The `numpy.einsum` documentation is quite clear that broadcasting happens only when ellipses are included in the `subscripts` argument. From the documentation:

"To enable and control broadcasting, use an ellipsis. Default NumPy-style broadcasting is done by adding an ellipsis to the left of each term, like np.einsum('...ii->...i', a)."

If the default NumPy broadcasting behavior is actually used when there are no ellipses, that is contrary to the documentation. At a minimum, the documentation should be updated.

Personally, I think that `einsum` should throw an error in this case. The subscripting mechanism makes it seem as though subscripts are going to be matched in every case, which is misleading. I am familiar with NumPy broadcasting but this case was quite subtle to catch for me.

**Comment by charris** [comment]
I think this is a documentation problem. Explicit singleton dimensions broadcast, it is how broadcasting is indicated to the numpy iterator machinery. When the singleton is not explicit, broadcasting is achieved by adding singleton dimensions. I think einsum is giving you the option of adding the missing singletons or not, but I don't think it applies to preexisting singletons, they always broadcast.

**Comment by attack68** [comment]
can I link this to my issue #11541 (coincidentally opened the same day) which turns out to be precisely this issue, but the more important thing is that I agree with @kielpins.

I think raising a ValueError, which was actually the case in version 1.14.0 with `optimize=True` is better for many reasons which I expand on in my own thread but the gist was;

* `ij,j->` does the same thing as `ij,k`when broadcasting over singleton dimensions, but a classical interpretation under Einstein summation one would not expect the same behaviour.
* in a dynamic program `ij,j->` fails with ValueError if the dimensions of `j` are different and neither of them are one, but there may be use cases where a dimension collapses to one for some practical reason or another and then no error is thrown, but in that case a genuinely wrong (and different type) of calculation is performed. So this is a dangerous error because it is undetectable, as has been the case in my app, and hence why I posted my issue.

**Comment by kielpins** [comment]
The second bullet point in attack68’s comment expresses my experience very
well. I was writing a dynamic program and a different, unexpected
calculation was performed when one of the dimensions happened to be 1. That
error was extremely hard to detect.

**Comment by shoyer** [comment]
I think this behavior should be considered a bug in NumPy. It isn't documented and it isn't desirable with einsum, which enables very concise syntax for fully explicit broadcasting.

Of course, people are assuredly relying on this behavior now, so we'll need a deprecation cycle before making it raise an error.

**Comment by seberg** [comment]
The iterator was unable to check this for along time (i.e. distinguish "broadcast and non-broadcast axis explicitly).  It now _could_.  I think the diff at the end would do it.  But if you want to go through deprecation (which seems better here), you will have to do it manually first probably.

Also note that `optimize=True` will take a different path I think and needs to get an identical fix if anyone looks into it.  Mainly posting, since the correct `NpyIter` usage for the "final" version is pretty arcane.

<details>

```diff
diff --git a/numpy/core/src/multiarray/einsum.c.src b/numpy/core/src/multiarray/einsum.c.src
index 85806fab3..d6c2489c9 100644
--- a/numpy/core/src/multiarray/einsum.c.src
+++ b/numpy/core/src/multiarray/einsum.c.src
@@ -470,7 +470,7 @@ prepare_op_axes(int ndim, int iop, char *labels, int *axes,
              * extend it with a "newaxis"
              */
             if (ibroadcast < 0) {
-                axes[i] = -1;
+                axes[i] = NPY_ITER_REDUCTION_AXIS(-1);
             }
             /* Otherwise map to the broadcast axis */
             else {
@@ -998,12 +998,14 @@ PyArray_EinsteinSum(char *subscripts, npy_intp nop,
     for (iop = 0; iop < nop; ++iop) {
         op_flags[iop] = NPY_ITER_READONLY|
                         NPY_ITER_NBO|
-                        NPY_ITER_ALIGNED;
+                        NPY_ITER_ALIGNED|
+                        NPY_ITER_NO_BROADCAST;
     }
     op_flags[nop] = NPY_ITER_READWRITE|
                     NPY_ITER_NBO|
                     NPY_ITER_ALIGNED|
-                    NPY_ITER_ALLOCATE;
+                    NPY_ITER_ALLOCATE|
+                    NPY_ITER_NO_BROADCAST;
     iter_flags = NPY_ITER_EXTERNAL_LOOP|
             NPY_ITER_BUFFERED|
             NPY_ITER_DELAY_BUFALLOC|
```
