### ISSUE TITLE
Is this supposed to happen?

### ISSUE THREAD

**Issue by OS2-replacement** [numpy/numpy#11550]
I am running Windows 7 with Python 3.5.0 on a Thinkpad.

I'm trying to run moviepy, it said I needed numpy.

I downloaded it, installed it and ran `from moviepy.editor import*`

Well it gave me:

```
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35\lib\numpy\__init__.py", line 126, in <module>
    from numpy.__config__ import show as show_config
ImportError: No module named 'numpy.__config__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<pyshell#3>", line 1, in <module>
    from moviepy.editor import*
  File "C:\Users\User\AppData\Local\Programs\Python\Python35\lib\moviepy\editor.py", line 23, in <module>
    import imageio
  File "C:\Users\User\AppData\Local\Programs\Python\Python35\lib\imageio\__init__.py", line 22, in <module>
    from .core import FormatManager, RETURN_BYTES
  File "C:\Users\User\AppData\Local\Programs\Python\Python35\lib\imageio\core\__init__.py", line 10, in <module>
    from .util import Image, Dict, asarray, image_as_uint, urlopen
  File "C:\Users\User\AppData\Local\Programs\Python\Python35\lib\imageio\core\util.py", line 24, in <module>
    import numpy as np
  File "C:\Users\User\AppData\Local\Programs\Python\Python35\lib\numpy\__init__.py", line 131, in <module>
    raise ImportError(msg)
ImportError: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.
```

Can anybody help me?

**Comment by mattip** [comment]
You should use `python -mpip install numpy` rather than download the numpy source files. You can read about [installing python packages via pip](https://docs.python.org/3/installing/index.html). I would recommend you save yourself time and install a python distribution such as [anaconda](https://www.anaconda.com/download), which comes with many packages already installed.

**Comment by mattip** [comment]
Where/how did you get your python?

**Comment by OS2-replacement** [comment]
python.com

**Comment by mattip** [comment]
you may need to do `python -mensurepip`, but again, I recommend using a distribution to avoid all these problems.
