### ISSUE TITLE
OSError: Failed to interpret file 'newtraj_4_1.xtc_offsets.npz' as a pickle

### ISSUE THREAD

**Issue by mkhoshle** [numpy/numpy#11574]
Hello all,

I am trying to load some .npz files with the following commands:
```
{k: v for k, v in six.iteritems(np.load(filename))}
```
and filename is a npz file. I am doing this in parallel and some of the ranks fail to this error:
```
Traceback (most recent call last):
  File "/oasis/scratch/comet/mkhoshle/temp_project/MPI-traj-split/main1-updated-rmsd-chain-reader.py", line 77, in <module>
    u = mda.Universe(PSF, XTCs)
  File "/home/mkhoshle/miniconda3/envs/py3/lib/python3.6/site-packages/MDAnalysis/core/universe.py", line 305, in __init__
    self.load_new(coordinatefile, **kwargs)
  File "/home/mkhoshle/miniconda3/envs/py3/lib/python3.6/site-packages/MDAnalysis/core/universe.py", line 535, in load_new
    self.trajectory = reader(filename, **kwargs)
  File "/home/mkhoshle/miniconda3/envs/py3/lib/python3.6/site-packages/MDAnalysis/coordinates/chain.py", line 123, in __init__
    for filename in self.filenames]
  File "/home/mkhoshle/miniconda3/envs/py3/lib/python3.6/site-packages/MDAnalysis/coordinates/chain.py", line 123, in <listcomp>
    for filename in self.filenames]
  File "/home/mkhoshle/miniconda3/envs/py3/lib/python3.6/site-packages/MDAnalysis/coordinates/core.py", line 83, in reader
    return Reader(filename, **kwargs)
  File "/home/mkhoshle/miniconda3/envs/py3/lib/python3.6/site-packages/MDAnalysis/coordinates/XDR.py", line 147, in __init__
    self._load_offsets()
  File "/home/mkhoshle/miniconda3/envs/py3/lib/python3.6/site-packages/MDAnalysis/coordinates/XDR.py", line 186, in _load_offsets
    data = read_numpy_offsets(fname)
  File "/home/mkhoshle/miniconda3/envs/py3/lib/python3.6/site-packages/MDAnalysis/coordinates/XDR.py", line 85, in read_numpy_offsets
    a = np.load(filename)
  File "/home/mkhoshle/miniconda3/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 431, in load
    "Failed to interpret file %s as a pickle" % repr(file))
OSError: Failed to interpret file '/oasis/scratch/comet/mkhoshle/temp_project/MPI-traj-split/files/.newtraj_17_1.xtc_offsets.npz' as a pickle
Traceback (most recent call last):
  File "/home/mkhoshle/miniconda3/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 428, in load
    return pickle.load(fid, **pickle_kwargs)
EOFError: Ran out of input
```
This error happens sometime and sometimes does not happen.
I am using `python 3` and the numpy version is `1.14.5`.
Does anyone know why I am getting this error and how can I avoid that?

**Comment by mattip** [comment]
This does not smell like a NumPy problem, more likely something around the way the files are being handled. Are you always reading the same set of files? Are they local or on a network drive? Why does the file name start with `.`, that suggests some kind of temporary file. Is another process writing while you read?

**Comment by mkhoshle** [comment]
What do you mean by the way the files are being handled. The files are hidden temporary zip files and they are on the scratch in XSEDE clusters. Each process writes one of these offset files and there is a barrier to synchronize them. After the barrier, they all read all the offset files and the error happens for some ranks when they are trying to read these files.

**Comment by seberg** [comment]
Going to close this year old issue, it never looked like a NumPy issue, rather some other general IO issue triggered during NumPy file loading.
