### ISSUE TITLE
percentile don't support datetime64

### ISSUE THREAD

**Issue by holymonson** [numpy/numpy#11620]
```python
dates = np.array([[np.datetime64('2018'), np.datetime64('2019')]], dtype='M8[ns]')
np.percentile(dates, 50)
# Traceback (most recent call last):
#   File "<stdin>", line 1, in <module>
#   File "/usr/local/miniconda3/envs/pandas/lib/python3.7/site-packages/numpy/lib/function_base.py", line 4291, in percentile
#     interpolation=interpolation)
#   File "/usr/local/miniconda3/envs/pandas/lib/python3.7/site-packages/numpy/lib/function_base.py", line 4033, in _ureduce
#     r = func(a, **kwargs)
#   File "/usr/local/miniconda3/envs/pandas/lib/python3.7/site-packages/numpy/lib/function_base.py", line 4405, in _percentile
#     x1 = take(ap, indices_below, axis=axis) * weights_below
# TypeError: ufunc multiply cannot use operands with types dtype('<M8[ns]') and dtype('float64')

# a workaround
np.percentile(dates.view('i8'), 50).astype('M8[ns]')
# numpy.datetime64('2018-07-02T12:00:00.000000000')

np.version.version
# '1.14.5'
```

**Comment by eric-wieser** [comment]
What result would you expect from `np.percentile(dates.astype('M[Y]'), 50)`?

It's tricky to define percentile on dates without having to think about rounding

**Comment by holymonson** [comment]
@eric-wieser 
> What result would you expect from np.percentile(dates.astype('M[Y]'), 50)?
```python
dates = np.array([[np.datetime64('2018'), np.datetime64('2019')]], dtype='M8[Y]')
np.percentile(dates.view('i8'), 50)
# 48.5
np.percentile(dates.view('i8'), 50).dtype
# dtype('float64')
np.percentile(dates.view('i8'), 50).astype('M8[Y]')
# numpy.datetime64('2018')
```
`np.percentile()` result a `dtype('float64')`, which can `astype` to `'M8[Y]'`. The logic already exists, no different to `int64` rounding and irrelevant to `np.percentile()`.

**Comment by eric-wieser** [comment]
@holymonson: `np.percentile` applied to `int64`s gives a `float64`, instead of rounding. So should `np.percentile` applied to a `datetime64` give a `float64` instead of rounding? Right now, percentile does not round for any other types
