### ISSUE TITLE
np.loadtxt no longer loads bz2 files in python2

### ISSUE THREAD

**Issue by DanHickstein** [numpy/numpy#11633]
I have been using `np.loadtxt()` to happily load `txt.bz2` files for many years. I recently upgraded to numpy 1.14.2, and I noticed that it no longer seems possible to load a `txt.bz2` file using python2. 

Was this intensional, or some sort of bug?

```
Traceback (most recent call last):
  File "/Users/danhickstein/Documents/GitHub/PyAbel-DH/examples/example_all_O2.py", line 41, in <module>
    IM = np.loadtxt('data/O2-ANU1024.txt.bz2')
  File "/anaconda2/lib/python2.7/site-packages/numpy/lib/npyio.py", line 917, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/anaconda2/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 260, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/anaconda2/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 614, in open
    encoding=encoding, newline=newline)
  File "/anaconda2/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 88, in _python2_bz2open
    raise ValueError("bz2 text files not supported in python2")
ValueError: bz2 text files not supported in python2
```

**Comment by charris** [comment]
It was intended and was part of extending encoding to text files in #4208. The problem is the `mode='rt'` in the call, might try passing `encoding='bytes'` in `loadtxt`. I think we should be able to fake it in Python 2 by assuming ascii/latin1  files if we raise a warning to that effect.

**Comment by charris** [comment]
@juliantaylor Thoughts?

**Comment by juliantaylor** [comment]
The issue is that the python2 bzip2 module is lacking functions to be used in a `TextIOWrapper ` so we can use standard encoding handling. gzip has similar issues but it is only missing one single simple function (read1) which we sort of patch in but for bzip2 I considered it too much.

Maybe throwing an error is a bit harsh, one could indeed just enforce the bzip 2 textfiles to be latin1 and hope for the best during decoding.

**Comment by charris** [comment]
@DanHickstein If you are up to testing patches, could you see if #11708 fixes this for you.

**Comment by DanHickstein** [comment]
Thanks for taking care of this @charris!
