### ISSUE TITLE
`numpy.take` with non-empty `indices` from an empty axis should fail

### ISSUE THREAD

**Issue by toslunar** [numpy/numpy#11677]
### Reproducing code example:

```python
import numpy as np
np.take(np.empty((0, 0)), [1], axis=0, mode='wrap')
```
does not return (probably causing an infinite-loop).

The message
```
>>> np.take(np.empty((0, 0)), [1], axis=0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tos/GitHub/numpy/numpy/core/fromnumeric.py", line 181, in take
    return _wrapfunc(a, 'take', indices, axis=axis, out=out, mode=mode)
  File "/Users/tos/GitHub/numpy/numpy/core/fromnumeric.py", line 51, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
IndexError: index 1 is out of bounds for size 0
```
is different from the message
```
>>> np.take(np.empty((0,)), [1], axis=0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tos/GitHub/numpy/numpy/core/fromnumeric.py", line 181, in take
    return _wrapfunc(a, 'take', indices, axis=axis, out=out, mode=mode)
  File "/Users/tos/GitHub/numpy/numpy/core/fromnumeric.py", line 51, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
IndexError: cannot do a non-empty take from an empty axes.
```

To produce the latter message, the size of the output array is checked.  Instead the size of the indices could be checked.

### Numpy/Python version information:

1.16.0.dev0+9d0225b 3.7.0 (default, Jun 29 2018, 20:13:13)
[Clang 9.1.0 (clang-902.0.39.2)]

**Comment by eric-wieser** [comment]
Relatedly:
```
In [2]: np.take(np.empty((0, 0)), [1], axis=0)
IndexError: index 1 is out of bounds for size 0

In [3]: np.take(np.empty((0, 0)), [1], axis=1)
Out[3]: array([], shape=(0, 1), dtype=float64)
```

We need to decide whether the first or second result is correct here.

**Comment by eric-wieser** [comment]
@seberg, this looks like a missed case from #3002
