### ISSUE TITLE
Error in array_repr on masked array: numpy.ma.core.MaskError: Cannot convert masked element to a Python int.

### ISSUE THREAD

**Issue by alexmojaki** [numpy/numpy#11674]
### Reproducing code example:

```python
import numpy as np

arr = np.ma.array([1, 2, 3], mask=[0, 1, 0])
print(arr)   # [1 -- 3]
print(np.array_repr(arr))   # error
```

### Error message:

```
Traceback (most recent call last):
  File "/Users/alexhall/Library/Preferences/PyCharm2018.1/scratches/scratch_468.py", line 6, in <module>
    print(np.array_repr(arr))
  File "/Users/alexhall/.pyenv/versions/3.5.1/lib/python3.5/site-packages/numpy/core/arrayprint.py", line 1431, in array_repr
    ', ', prefix, suffix=suffix)
  File "/Users/alexhall/.pyenv/versions/3.5.1/lib/python3.5/site-packages/numpy/core/arrayprint.py", line 668, in array2string
    return _array2string(a, options, separator, prefix)
  File "/Users/alexhall/.pyenv/versions/3.5.1/lib/python3.5/site-packages/numpy/core/arrayprint.py", line 460, in wrapper
    return f(self, *args, **kwargs)
  File "/Users/alexhall/.pyenv/versions/3.5.1/lib/python3.5/site-packages/numpy/core/arrayprint.py", line 495, in _array2string
    summary_insert, options['legacy'])
  File "/Users/alexhall/.pyenv/versions/3.5.1/lib/python3.5/site-packages/numpy/core/arrayprint.py", line 796, in _formatArray
    curr_width=line_width)
  File "/Users/alexhall/.pyenv/versions/3.5.1/lib/python3.5/site-packages/numpy/core/arrayprint.py", line 750, in recurser
    word = recurser(index + (-i,), next_hanging_indent, next_width)
  File "/Users/alexhall/.pyenv/versions/3.5.1/lib/python3.5/site-packages/numpy/core/arrayprint.py", line 704, in recurser
    return format_function(a[index])
  File "/Users/alexhall/.pyenv/versions/3.5.1/lib/python3.5/site-packages/numpy/core/arrayprint.py", line 1119, in __call__
    return self.format % x
  File "/Users/alexhall/.pyenv/versions/3.5.1/lib/python3.5/site-packages/numpy/ma/core.py", line 4298, in __int__
    raise MaskError('Cannot convert masked element to a Python int.')
numpy.ma.core.MaskError: Cannot convert masked element to a Python int.
```

### Numpy/Python version information:

```
1.15.0
3.5.1 (default, May 31 2016, 20:50:46) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.72)]
```

**Comment by titusjan** [comment]
> I think I'd like to write this off as "by-design" - np.array_repr is not intended to work on ndarray subclasses. 

@eric-wieser : Then how does `print(arr)` render its output? I thought that `__str__` would use `array_str`, or vice versa, so that they have the same output and capabilities.

**Comment by fengluoqiuwu** [comment]
It seems to work in the latest version with a warning occurs:
```python
>>> arr = np.ma.array([1, 2, 3], mask=[0, 1, 0])
>>> print(arr)
[1 -- 3]
>>> print(np.array_repr(arr))  
MaskedArray([1, --, 3])
FutureWarning: Format strings passed to MaskedConstant are ignored, but in future may error or produce different behavior
  return self.format.format(x)
```
