### ISSUE TITLE
core.records.fromfile fails without shape=

### ISSUE THREAD

**Issue by sdkempf** [numpy/numpy#11683]
I took this example code from https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.core.records.fromfile.html and removed the shape argument.  I read somewhere about floating point indexing being removed and this might be related.

### Reproducing code example:

```python
import numpy as np
from tempfile import TemporaryFile
a = np.empty(10,dtype='f8,i4,a5')
a[5] = (0.5,10,'abcde')

fd=TemporaryFile()
a = a.newbyteorder('<')
a.tofile(fd)

fd.seek(0)
#r=np.core.records.fromfile(fd, formats='f8,i4,a5', shape=10,byteorder='<')
r=np.core.records.fromfile(fd, formats='f8,i4,a5', byteorder='<')
print(r[5])
r.shape
```

### Error message:

Traceback (most recent call last):
  File "test.py", line 12, in <module>
    r=np.core.records.fromfile(fd, formats='f8,i4,a5', byteorder='<')
  File "/WAIS/syst/ext/linux/lib/python2.7/site-packages/numpy/core/records.py", line 796, in fromfile
    _array = recarray(shape, descr)
  File "/WAIS/syst/ext/linux/lib/python2.7/site-packages/numpy/core/records.py", line 425, in __new__
    self = ndarray.__new__(subtype, shape, (record, descr), order=order)
TypeError: 'numpy.float64' object cannot be interpreted as an index

### Numpy/Python version information:

('1.14.2', '2.7.13 (default, Mar 26 2018, 11:09:19) \n[GCC 4.4.7 20120313 (Red Hat 4.4.7-18)]')

### Possible Fix:

Honestly, I don't know if this is a good idea, but it fixed the problem for me.
```patch
*** records.py.orig     2018-08-07 13:38:30.000000000 -0500
--- records.py  2018-08-07 13:38:13.000000000 -0500
***************
*** 782,788 ****
      shapesize = shapeprod * itemsize
      if shapesize < 0:
          shape = list(shape)
!         shape[shape.index(-1)] = size / -shapesize
          shape = tuple(shape)
          shapeprod = sb.array(shape).prod()

--- 782,788 ----
      shapesize = shapeprod * itemsize
      if shapesize < 0:
          shape = list(shape)
!         shape[shape.index(-1)] = int(size / -shapesize)
          shape = tuple(shape)
          shapeprod = sb.array(shape).prod()
```

**Comment by Bhargavasomu** [comment]
I would like to work on this issue.

**Comment by seberg** [comment]
@Bhargavasomu sure, go ahead just open a PR when you are ready. There is normally always a `tests/test_samefilename.py` where most tests should go. There is a test that looks a bit similar, not sure why it did not find this...
