### ISSUE TITLE
Calling histogram with auto bins raises MemoryError

### ISSUE THREAD

**Issue by striajan** [numpy/numpy#11879]
I use Numpy version 1.15. If I call `np.histogram(data, bins='auto')`, I get `MemoryError`. The error is probably caused by trying to allocate too large [linspace](https://github.com/numpy/numpy/blob/058851c5cfc98f50f11237b1c13d77cfd1f40475/numpy/lib/histograms.py#L375).

### Reproducing code example:

The error can be reproduced on [this data](https://github.com/numpy/numpy/files/2348354/data.txt). Its range is approximately (-0.00283, 0.00209), with many values being close to zero. The following code raises the error:
```python
import numpy
data = numpy.loadtxt('data.txt')
numpy.histogram(data, bins='auto')
```

The problem is in computation of the bin edges. The following code raises the error:
```python
import numpy.lib.histograms
numpy.lib.histograms._get_bin_edges(data, bins='auto', range=None, weights=None)
```

Even more specifically, the problem is caused by the method `bins='fd'`. The other method `bins='sturges'` used for automated computation of bin edges works well.

### Error message:

```
Traceback (most recent call last):
  File ".../.pycharm_helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File ".../numpy/lib/histograms.py", line 676, in histogram
    bin_edges, uniform_bins = _get_bin_edges(a, bins, range, weights)
  File ".../numpy/lib/histograms.py", line 351, in _get_bin_edges
    endpoint=True, dtype=bin_type)
  File ".../numpy/core/function_base.py", line 115, in linspace
    y = _nx.arange(0, num, dtype=dt)
MemoryError
```

### Numpy/Python version information:

```
1.15.0 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56) 
[GCC 7.2.0]
```

**Comment by eric-wieser** [comment]
Not sure what can be done here - `_hist_bin_fd` is giving a very narrow bin width:

```
>>> np.lib.function_base._hist_bin_fd(data)
3.7209746283969316e-14
>>> np.min(data)
-0.0028283235151320696
>>> np.max(data)
0.0020850044675171375
```

I think this is a case missed by #10739

**Comment by striajan** [comment]
From my point of view of NumPy user (thank you for such great library by the way!), the main problem is that the function fails with `bins='auto'`. I expect that automatic method should always work. On the other hand, if `bins='fd'` fails, it is maybe not that bad. Limiting the number of bins seems like a good idea to me.

**Comment by eric-wieser** [comment]
How do you propose choosing the limit? A fixed cutoff? Some constant times the number of sturges bins? There seems to be a lot of options here, and I have nowhere near enough background to make that call.

You might want to reach out to the mailing list for this one, with a title like "putting an upper bound on the number of bins used by histogram(bins='auto') to avoid MemoryErrors"

**Comment by saimn** [comment]
Same issue here, I was really surprised to see an error with a 1000x1000 image on a machine with ~380Gb of RAM :grin: 
The issue is that the bin size is really small:
```
In [5]: np.lib.histograms._hist_bin_fd(orig.maxmap._data)
Out[5]: 6.276622409738591e-18
```
I guess that a least a better warning/error could be raised, currently I get this:
```
ValueError: array is too big; `arr.size * arr.dtype.itemsize` is larger than the maximum possible size.
```

**Comment by areeves87** [comment]
I've taken a crack at addressing this issue. 

Based on ideas from @eric-wieser in issue #10297, the approach merges empty bins while iteratively cutting non-empty bins in half. The bin widths begin with those found by Sturges and end with those found by Freedman Diaconis. All while keeping memory footprint low.

The method works for the sample datasets in all the issues related to the FD estimator (#11879, #10297, #8203). It also plays nicely with matplotlib.

Is there still interest in a solution here? Should I put together a pull request? Or reach out to the mailing list first?

**Comment by Gabriel-p** [comment]
Isn't this issue a duplicate of #10297?

**Comment by fingoldo** [comment]
Hi, why is this issue not getting fixed for 5 years? I've run into it recently.

```python
import numpy as np

hist, bin_edges = np.histogram(
    np.array(
        [
            -4.24264069e00,
            -5.55111512e-17,
            3.81837662e01,
            1.77635684e-15,
            -5.65685425e00,
            3.55271368e-15,
            -1.97989899e01,
            0.00000000e00,
            -1.27279221e01,
            4.24264069e00,
            1.41421356e01,
            -1.83847763e01,
            -5.55111512e-17,
            -5.55111512e-17,
            -5.55111512e-17,
            -5.55111512e-17,
            -5.55111512e-17,
            -5.55111512e-17,
            -5.55111512e-17,
            -5.55111512e-17,
            -5.55111512e-17,
            -5.55111512e-17,
            -5.55111512e-17,
            -5.55111512e-17,
            -5.55111512e-17,
            -5.55111512e-17,
            -5.55111512e-17,
            -5.55111512e-17,
            -5.55111512e-17,
            3.53553391e-01,
            9.54594155e00,
            -3.53553391e-01,
            -9.19238816e00,
            3.53553391e-01,
            -3.53553391e-01,
            2.82842712e00,
            -7.21644966e-16,
            -3.18198052e00,
            -5.55111512e-17,
            -5.55111512e-17,
        ]
    ),
    bins="auto",
    density=True,
)
```


~\AppData\Roaming\Python\Python39\site-packages\numpy\core\function_base.py in linspace(start, stop, num, endpoint, retstep, dtype, axis)
    137 
    138     delta = stop - start
--> 139     y = _nx.arange(0, num, dtype=dt).reshape((-1,) + (1,) * ndim(delta))
    140     # In-place multiplication y *= delta/div is faster, but prevents the multiplicant
    141     # from overriding what class is produced, and thus prevents, e.g. use of Quantities,

MemoryError: Unable to allocate 3.81 EiB for an array with shape (549572839412124544,) and data type float64

**Comment by ngoldbaum** [comment]
This was fixed, the example script no longer crashes.

```
In [1]: import numpy
   ...: data = numpy.loadtxt('data.txt')
   ...: numpy.histogram(data, bins='auto')
Out[1]:
(array([  1,   0,   0,   0,   0,   0,   0,   1,   0,   0,   0,   0,   1,
          0,   1,   0,   1,   0,   2,   2,   2,   3,   8,   8,   8,   7,
        398,   9,   7,  14,   5,   6,   3,   1,   6,   1,   2,   4,   1,
          4,   1,   0,   1,   2,   0,   2]),
 array([-2.82832352e-03, -2.72151204e-03, -2.61470056e-03, -2.50788908e-03,
        -2.40107760e-03, -2.29426613e-03, -2.18745465e-03, -2.08064317e-03,
        -1.97383169e-03, -1.86702021e-03, -1.76020874e-03, -1.65339726e-03,
        -1.54658578e-03, -1.43977430e-03, -1.33296282e-03, -1.22615135e-03,
        -1.11933987e-03, -1.01252839e-03, -9.05716913e-04, -7.98905435e-04,
        -6.92093957e-04, -5.85282480e-04, -4.78471002e-04, -3.71659524e-04,
        -2.64848046e-04, -1.58036568e-04, -5.12250902e-05,  5.55863877e-05,
         1.62397866e-04,  2.69209343e-04,  3.76020821e-04,  4.82832299e-04,
         5.89643777e-04,  6.96455255e-04,  8.03266733e-04,  9.10078211e-04,
         1.01688969e-03,  1.12370117e-03,  1.23051264e-03,  1.33732412e-03,
         1.44413560e-03,  1.55094708e-03,  1.65775856e-03,  1.76457003e-03,
         1.87138151e-03,  1.97819299e-03,  2.08500447e-03]))
In [2]: numpy.__version__
Out[2]: '2.3.2'
```
