### ISSUE TITLE
SVD does not converge when setting OPENBLASS_

### ISSUE THREAD

**Issue by ysig** [numpy/numpy#11887]
When running experiments on squared symmetric numpy matrices I had a constant error of svd not converging although I couldn't found why. My experiment had constrained the amount of threads on the OPENBLASS.

By searching various things concerning debugging, I found a correlation between the number of threads and the convergence, which seems really strange at first sight.
The following example has two case where going from n to n+1 leads to convergence.
If there is a _timeout_ constraint inside the openblass is there a way to control it?

### Reproducing code example:
1.
Uncompress [array.zip](https://github.com/numpy/numpy/files/2353617/array.zip) on your local dir.

```
$  env OPENBLAS_NUM_THREADS=1 python
>>> import numpy as np
>>> A = np.load('array.npy')
>>> out = np.linalg.svd(A)
numpy.linalg.linalg.LinAlgError: SVD did not converge
```
when

```$  env OPENBLAS_NUM_THREADS=2 python
>>> import numpy as np
>>> A = np.load('array.npy')
>>> out = np.linalg.svd(A)
```

2.
Uncompress [array_2.zip](https://github.com/numpy/numpy/files/2353737/array_2.zip) on your local dir.

```
$  env OPENBLAS_NUM_THREADS=2 python  
>>> import numpy as np
>>> A = np.load('array_2.npy')
>>> out = np.linalg.svd(A)
numpy.linalg.linalg.LinAlgError: SVD did not converge
```
when

```$  env OPENBLAS_NUM_THREADS=3 python
>>> import numpy as np
>>> A = np.load('array_2.npy')
>>> out = np.linalg.svd(A)
```

### Error message:
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/dascim/.local/lib/python2.7/site-packages/numpy/linalg/linalg.py", line 1550, in svd
>     u, s, vh = gufunc(a, signature=signature, extobj=extobj)
>   File "/home/dascim/.local/lib/python2.7/site-packages/numpy/linalg/linalg.py", line 98, in _raise_linalgerror_svd_nonconvergence
>     raise LinAlgError("SVD did not converge")
> numpy.linalg.linalg.LinAlgError: SVD did not converge

### Numpy/Python version information:
```
$python -c 'import sys, numpy; print(numpy.__version__, sys.version)'
1.15.0 2.7.14 (default, Jul 26 2018, 19:07:40) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-23)]
```

**Comment by david758** [comment]
Bumping this old thread after running into the same problem and then resolving it. The following worked for me. Obviously only relevant for symmetric matrices but that is the case here (and my application).

```
$  env OPENBLAS_NUM_THREADS=1 python
>>> import numpy as np
>>> A = np.load('array.npy', hermitian=True)
>>> out = np.linalg.svd(A)
```

**Comment by mattip** [comment]
@ysig @cruyffturn does this still reproduce?
