### ISSUE TITLE
Einsum symbol limitations

### ISSUE THREAD

**Issue by adamjermyn** [numpy/numpy#11938]
The alternate input format for einsum (i.e. `einsum(op0, sublist0, op1, sublist1, ..., [sublistout])`) produces an error if the number of tensors grows too large. The error also changes with the number of operands.

### Reproducing code example:

```python
import numpy as np

n = 26
arrs = list(np.zeros((2,2)) for _ in range(n))
inds = list([i,i+1] for i in range(len(arrs)))
args = list(x for y in zip(*(arrs,inds)) for x in y)
args.append([0,n])
np.einsum(*args)
```

This produces the following error:

```console
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    np.einsum(*args)
  File "/usr/local/lib/python3.6/site-packages/numpy-1.14.2-py3.6-macosx-10.13-x86_64.egg/numpy/core/einsumfunc.py", line 1069, in einsum
    return c_einsum(*operands, **kwargs)
ValueError: invalid subscript '{' in einstein sum subscripts string, subscripts must be letters
```

With `n=40' the error message changes:

```console
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    np.einsum(*args)
  File "/usr/local/lib/python3.6/site-packages/numpy-1.14.2-py3.6-macosx-10.13-x86_64.egg/numpy/core/einsumfunc.py", line 1069, in einsum
    return c_einsum(*operands, **kwargs)
ValueError: too many operands
```

This appears to be related to the use of characters for indices internally, even when indices are specified as integers in the input. The use of characters internally does not seem critical to the algorithm so this may be resolvable by changing that.

### Numpy/Python version information:

```console
1.14.2 3.6.4 (default, Mar  9 2018, 23:15:03)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

**Comment by seberg** [comment]
For `n>31` or so, things will simply not work. NumPy only supports 32 operands in its iterator (one will be the output), my guess the code gives up early for that reason. That is fixable in principle, but a bigger thing.

The other thing must be related to the characters really, so my guess it it shouldn't be super hard to fix.

**Comment by adamjermyn** [comment]
If I'm reading the einsum source correctly the iterator limitation should only affect individual contractions. The example I provided, for instance, can be done with just numpy dot or operations even though there are nominally many indices involved.

**Comment by seberg** [comment]
Well, too late now for me to think, but it seems to me like you got 40 arrays in a single einsum expression and I thought einsum doesn't try to disentangle them, but just iterates them "all at once" so to say, which means it (typically) ends up building an NpyIter with 41 arrays, which does not work. But I am happy to be wrong about that.

**Comment by adamjermyn** [comment]
Oh I see: that's what it does when optimize=False. When einsum is called with optimize='greedy' or optimize='optimal' it instead computes a series of intermediate objects that to avoid doing just that. It looks like the error is coming from c_einsum though, which suggests that in this case the greedy optimizer (which is the default) is passing > 31 operands. If that's the case that suggests that something has gone wrong with the optimization...

**Comment by seberg** [comment]
Not sure if the optimization can add operands, I thought that the "too many operands" thing only happens for `n>=32` or so, it is just the second case?
The label inconsistency probably comes from the C-code side as well though.

Just to note `optimize=False` is the default for now, because of some small inconsistencies and the fact it is pretty slow for small arrays, so if you like it (and are using it in your version) you should pass it explicitly.

PS: I forgot about the python code that now exists, used to be just `c_einsum` directly...

**Comment by adamjermyn** [comment]
Ah in that case there's an inconsistency in the documentation. The [docs](https://docs.scipy.org/doc/numpy/reference/generated/numpy.einsum.html) for einsum say that optimize defaults to False in the function signature but that it defaults to True in the parameter specification.

When I turn on optimization the "too many operands" error goes away, so that behaves as it should. This also means that I don't hit the label problem because the optimizer reduces the number of operands being passed to C, though that should probably be fixed still.

**Comment by attack68** [comment]
The docs were correct at one point when the default was, in fact, set to True. But this was regressed without amending the docs due to dependency problems and speed issues for small arrays. The docs have been revised and updated in v 1.16 [https://www.numpy.org/devdocs/reference/generated/numpy.einsum.html] to reflect this.

**Comment by adamjermyn** [comment]
Okay perfect. Then it's just the issue with characters in c_einsum.

**Comment by iivevo** [comment]
Maybe switching from chars to enums will fix this?

**Comment by jaredjeya** [comment]
Is there still any interest in solving this? It feels like quite a substantial limitation for applications like e.g. tensor networks that einsum fails with more than 52 indexes, simply because there are only 52 characters to choose from.

Like the line of code that breaks things seems to be,

`einsum_symbols = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'`

in `einsumfunc.py`, so if you ask for `einsum_symbols[s >= 52]` it breaks. 

In my code I've found that `optimize=False` breaks a lot sooner than `optimize="greedy"` - so clearly the optimised version is able to surpass this 32 iterable limit and break the calculation into smaller parts, as has been suggested, so this may be the only actual issue preventing this working with arbitrary numbers of indexes (provided none of the intermediate steps breach that limit).

It's probably reasonably simple to fix compared to many more pernicious bugs, but I haven't got any experience of contributing to open source projects etc. or of the numpy codebase, so I'm not confident in trying to do it myself.

**Comment by seberg** [comment]
Please don't hesitate to try, if this is about first-time contribution to open source.  It will be a slower process than much coding (review, tests, etc.), but hopefully you will pick up some new thing on the way (and that even if we should get stuck for some reason).

Aside from figuring out the code, I guess one difficulty may be that it seems possible that the error reporting currently relies on the translation to letters, but in the alternative spelling it should maybe use numbers to begin with.

**Comment by LionFrangoulis** [comment]
Has there been any progress on fixing this? As someone with a tensornetwork with more then 52 tensors, this would be a life saver for me, but my coding skills are way to low to attempt to contribute to this kind of project on my own.

**Comment by jaredjeya** [comment]
I've been using opt_einsum instead. It works really well and is basically a drop-in replacement for np.einsum, but one that works with arbitrarily many tensors (and arbitrary index names). Check it out!

https://optimized-einsum.readthedocs.io/en/stable/
