### ISSUE TITLE
Circular import issue involving getlimits and NPY_DT_DBG_TRACING

### ISSUE THREAD

**Issue by ahaldane** [numpy/numpy#12063]
PR #10602 seems to have triggered a circular import problem when using the dtype-transer debug mode. (set `NPY_DT_DBG_TRACING` to 1 at the top of `dtype_transfer.c`).

The problem seems to be that debug tracing tries to print a dtype before the dtype object has been created, I'm still trying to see what happened. 

It involves `getlimits.py` which has been the source of circular import issues in the past.

```python
>>> import numpy as np
Calculating dtype transfer from  to 
Traceback (most recent call last):
  File "/home/allan/nmpy_dev/build/testenv/lib/python3.7/site-packages/numpy/core/_dtype.py", line 23, in __repr__
    arg_str = _construction_repr(dtype, include_align=False)
  File "/home/allan/nmpy_dev/build/testenv/lib/python3.7/site-packages/numpy/core/_dtype.py", line 77, in _construction_repr
    return _scalar_str(dtype, short=short)
  File "/home/allan/nmpy_dev/build/testenv/lib/python3.7/site-packages/numpy/core/_dtype.py", line 81, in _scalar_str
    byteorder = _byte_order_str(dtype)
  File "/home/allan/nmpy_dev/build/testenv/lib/python3.7/site-packages/numpy/core/_dtype.py", line 151, in _byte_order_str
    swapped = np.dtype(int).newbyteorder('s')
AttributeError: module 'numpy' has no attribute 'dtype'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 200, in _lock_unlock_module
  File "<frozen importlib._bootstrap>", line 163, in _get_module_lock
SystemError: <built-in function acquire_lock> returned a result with an error set

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/allan/nmpy_dev/build/testenv/lib/python3.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/home/allan/nmpy_dev/build/testenv/lib/python3.7/site-packages/numpy/core/__init__.py", line 72, in <module>
    from . import getlimits
  File "/home/allan/nmpy_dev/build/testenv/lib/python3.7/site-packages/numpy/core/getlimits.py", line 125, in <module>
    tiny=_f16(2 ** -14))
  File "/home/allan/nmpy_dev/build/testenv/lib/python3.7/site-packages/numpy/core/getlimits.py", line 75, in __init__
    self.epsilon = self.eps = float_to_float(kwargs.pop('eps'))
  File "/home/allan/nmpy_dev/build/testenv/lib/python3.7/site-packages/numpy/core/getlimits.py", line 70, in <lambda>
    float_to_float = lambda v : _fr1(float_conv(v))
  File "/home/allan/nmpy_dev/build/testenv/lib/python3.7/site-packages/numpy/core/getlimits.py", line 29, in _fr1
    a = a.copy()
SystemError: <method 'copy' of 'numpy.ndarray' objects> returned a result with an error set
```

**Comment by eric-wieser** [comment]
The easy fix here is to not have `_dtype` use `np.dtype` - it only does so because it wants to obtain a `>` or `<` character for the endianness.

**Comment by eric-wieser** [comment]
Those SystemErrors can be fixed by checking return values in the code generating the message "Calculating dtype transfer ..."

**Comment by eric-wieser** [comment]
Perhaps switching to `np.core.dtype` is sufficient

**Comment by ahaldane** [comment]
> The easy fix here is to not have _dtype use np.dtype - it only does so because it wants to obtain a > or < character for the endianness.

I think that's only a temporary fix, it doesn't fix the deeper issue:

I was able to fix this particular `NPY_DT_DBG_TRACING` issue by replacing the numpy import in `_dtype.py` with  `from . import numeric as sb` as a number of other files in core do. I also needed to move the location of `_kind_name` to `numerictypes.py` to avoid circular imports.

But it's not just `_dtype.py` which imports numpy, `multiarray.py`, `arrayprint.py`, `memmap.py` and others do too. These will have the same problem when getlimits calls numpy code: Exactly the same problem will arise if, for debugging purposes, I try to add calls to `PyObject_Print` in any code-path in multiarray which is called by getlimits (which is many), which calls one of those modules. In fact I've had this problem when debugging recently.

It does seem slightly incorrect that so many core modules import the parent numpy module. But it seems like a lot of work to undo that.

It also seems incorrect that `getlimits.py` is calling numpy code before numpy is loaded.  The fix for that in #12064, while a bit ugly, is pretty easy.

**Comment by eric-wieser** [comment]
> It does seem slightly incorrect that so many core modules import the parent numpy module

I think part of the problem is that the internal structure of `np.core` is largely historic, and fixed for compatibility. The modules function are in often arbitrary, and so it's easier to just import directly from `np.core` than it is to work out which module to import from (especially in the face of circular imports)
