### ISSUE TITLE
Behavior of numpy.linalg.solve on different OSes

### ISSUE THREAD

**Issue by sashkab** [numpy/numpy#12095]
I've ran into issue with linalg.solve on different systems: in RHEL and Ubuntu it will raise an LinAlgError exception, but on Alpine it will return `nan`.

Ubuntu:

```sh
$ docker run -it --rm ubuntu:18.04 /bin/sh
$ apt-get install python3-numpy
# python3
Python 3.6.6 (default, Sep 12 2018, 18:26:19)
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> numpy.linalg.solve(numpy.array([[0]]), numpy.array([[0]]))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/numpy/linalg/linalg.py", line 375, in solve
    r = gufunc(a, b, signature=signature, extobj=extobj)
  File "/usr/lib/python3/dist-packages/numpy/linalg/linalg.py", line 90, in _raise_linalgerror_singular
    raise LinAlgError("Singular matrix")
numpy.linalg.linalg.LinAlgError: Singular matrix
```

Alpine:

```
$ docker run -it --rm alpine:3.8 /bin/sh
# apk --update add python3 py3-numpy
/ # python3
Python 3.6.6 (default, Aug 24 2018, 05:04:18)
[GCC 6.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> numpy.linalg.solve(numpy.array([[0]]), numpy.array([[0]]))
array([[nan]])
```

I would expect to receive same exception on Alpine as well. Is this known issue? 

I've tried to use either lapack  or openblas on alpine, compile numpy from source — it's still would return `nan`.

**Comment by tylerjereddy** [comment]
Alpine linux isn't supported by manylinux, right? I don't think it uses `glibc` -- there's a  [SO post](https://stackoverflow.com/a/37793161/2942522) from @ogrisel about the broader issue I think. Not sure if that's the problem here, but I don't think Alpine behavior differences are necessarily surprising.

**Comment by sashkab** [comment]
> I don't think it uses glibc

It does not, it uses [musl libc](https://www.musl-libc.org), but can this be the culprit?

**Comment by mattip** [comment]
The error setting routine [`set_fp_invalid_or_clear`](https://github.com/numpy/numpy/blob/maintenance/1.15.x/numpy/linalg/umath_linalg.c.src#L394) calls `npy_set_floatstatus_invalid` which has various [implementations](https://github.com/numpy/numpy/blob/maintenance/1.15.x/numpy/core/src/npymath/ieee754.c.src) for each platform. We probably do not properly support alpine linux. @sashkab, could you use gdb to find out which implementation we are actually using on your platform? I find it easy to do something like
```
git clean -xfd
CFLAGS='-O0 -g3' gdb --args python runtests.py -t numpy/linalg/test/test_linalg.py
```
and then at the gdb prompt
```
break npy_set_floatstatus_invalid  #  answer y
run
```

**Comment by sashkab** [comment]
It used one in line 842:

```c
NumPy version 1.16.0.dev0+2382a1b
NumPy relaxed strides checking option: True
.......................................
Thread 1 "python" hit Breakpoint 1, npy_set_floatstatus_invalid () at numpy/core/src/npymath/ieee754.c.src:843
843	{
(gdb) l
838	{
839	    _npy_floatstatus_x = _npy_floatstatus_small * 1e-300;
840	}
841
842	void npy_set_floatstatus_invalid(void)
843	{
844	    _npy_floatstatus_inf = NPY_INFINITY;
845	    _npy_floatstatus_x = _npy_floatstatus_inf - NPY_INFINITY;
846	}
847
```

**Comment by mattip** [comment]
The implementation of `npy_get_floatstatus_barrier` and `npy_clear_floatstatus_barrier` on lines 801-811 seems incomplete, I wonder how that is supposed to ever work.

It also appears that we should be using the code on lines 635-683, since [this page](https://wiki.musl-libc.org/mathematical-library.html#User-documentation)  says `fetestexcept` is supported, at least on platforms where `FE_*` macros are defined. Could you change the `#if` clause on [lines 630-632](https://github.com/numpy/numpy/blob/master/numpy/core/src/npymath/ieee754.c.src#L630) to simply read `#if 1`, compile and retest?

**Comment by sashkab** [comment]
In order to run tests I had to make following changes:

```diff
diff --git a/numpy/core/src/npymath/ieee754.c.src b/numpy/core/src/npymath/ieee754.c.src
index 8b5eef87a..807541b89 100644
--- a/numpy/core/src/npymath/ieee754.c.src
+++ b/numpy/core/src/npymath/ieee754.c.src
@@ -627,9 +627,7 @@ void npy_set_floatstatus_invalid(void)
 }


-#elif defined(__GLIBC__) || defined(__APPLE__) || \
-      defined(__CYGWIN__) || defined(__MINGW32__) || \
-      (defined(__FreeBSD__) && (__FreeBSD_version >= 502114))
+#elif 1
 #  include <fenv.h>

 int npy_get_floatstatus_barrier(char* param)
diff --git a/runtests.py b/runtests.py
index 81c7c103f..cc22f8873 100755
--- a/runtests.py
+++ b/runtests.py
@@ -341,7 +341,7 @@ def build_project(args):
                 '-Werror=pointer-arith',
                 '-Wlogical-op',
                 # from sysconfig
-                '-Werror=unused-function',
+                #'-Werror=unused-function',
             ])
             env['CFLAGS'] = warnings_as_errors + ' ' + env.get('CFLAGS', '')
     if args.debug or args.gcov:
```

And tests passed:

```sh
bash-4.4# CFLAGS='-O0 -g3' python runtests.py -t numpy/linalg/tests/test_linalg.py
Building, see build.log...
Build OK
NumPy version 1.16.0.dev0+db5f9d3
NumPy relaxed strides checking option: True
...
274 passed, 22 deselected in 4.66 seconds
```

Running under gdb:

```
bash-4.4# CFLAGS='-O0 -g3' gdb --args python runtests.py -t numpy/linalg/tests/test_linalg.py
(gdb) break npy_set_floatstatus_invalid
Function "npy_set_floatstatus_invalid" not defined.
Make breakpoint pending on future shared library load? (y or [n]) y
Breakpoint 1 (npy_set_floatstatus_invalid) pending.
(gdb) run
Starting program: /usr/bin/python runtests.py -t numpy/linalg/tests/test_linalg.py
warning: Error disabling address space randomization: Operation not permitted
Building, see build.log...
Build OK
[New LWP 1977]
[New LWP 1978]
[New LWP 1979]
NumPy version 1.16.0.dev0+db5f9d3
NumPy relaxed strides checking option: True
.......................................
Thread 1 "python" hit Breakpoint 1, npy_set_floatstatus_invalid () at numpy/core/src/npymath/ieee754.c.src:679
679	{
```

And testing in python:

```
bash-4.4# python3
Python 3.6.6 (default, Aug 24 2018, 05:04:18)
[GCC 6.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> numpy.linalg.solve(numpy.array([[0]]), numpy.array([[0]]))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/numpy/linalg/linalg.py", line 389, in solve
    r = gufunc(a, b, signature=signature, extobj=extobj)
  File "/usr/lib/python3.6/site-packages/numpy/linalg/linalg.py", line 89, in _raise_linalgerror_singular
    raise LinAlgError("Singular matrix")
numpy.linalg.linalg.LinAlgError: Singular matrix
```

Which is what I would expect.

**Comment by mattip** [comment]
@sashkab Thanks. What was the unused function error when you had `'-Werror=unused-function'` defined?

**Comment by mattip** [comment]
Interesting that all tests pass, #7128 says 

>The second group can be fixed by disabling the trigonometric functions in numpy/numpy/core/src/private/npy_config.h not only for glibc, but also for musl. An issue here is that musl doesn't provide any macro like `__GLIBC__` to detect it.

We blacklist trig functions for glibc < 2.18, but do not blacklist any for musl. They must have upped their game since that issue was filed.

**Comment by mattip** [comment]
ok, thanks. @sashkab see [this comment](https://github.com/numpy/numpy/pull/12124#issuecomment-428299686) for why that happens.
