### ISSUE TITLE
Histogram's _unsigned_subtract fails on boolean values

### ISSUE THREAD

**Issue by AetherUnbound** [numpy/numpy#12107]
The `_unsigned_subtract` function in histogram now raises a `TypeError` when given boolean values.

```
a = True, b = False
    def _unsigned_subtract(a, b):
        """
        Subtract two values where a >= b, and produce an unsigned result
    
        This is needed when finding the difference between the upper and lower
        bound of an int16 histogram
        """
        # coerce to a single type
        signed_to_unsigned = {
            np.byte: np.ubyte,
            np.short: np.ushort,
            np.intc: np.uintc,
            np.int_: np.uint,
            np.longlong: np.ulonglong
        }
        dt = np.result_type(a, b)
        try:
            dt = signed_to_unsigned[dt.type]
        except KeyError:
>           return np.subtract(a, b, dtype=dt)
E           TypeError: numpy boolean subtract, the `-` operator, is deprecated, use the bitwise_xor, the `^` operator, or the logical_xor function instead.
```

### Reproducing code example:

```python
>>> import numpy as np
>>> np.histogram([True, True, False])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/aether/programs/anaconda3/envs/cpnp15/lib/python2.7/site-packages/numpy/lib/histograms.py", line 732, in histogram
    norm = n_equal_bins / _unsigned_subtract(last_edge, first_edge)
  File "/home/aether/programs/anaconda3/envs/cpnp15/lib/python2.7/site-packages/numpy/lib/histograms.py", line 282, in _unsigned_subtract
    return np.subtract(a, b, dtype=dt)
TypeError: numpy boolean subtract, the `-` operator, is deprecated, use the bitwise_xor, the `^` operator, or the logical_xor function instead.
```

### Numpy/Python version information:
`('1.15.2', '2.7.14 |Anaconda, Inc.| (default, Dec  7 2017, 17:05:42) \n[GCC 7.2.0]')`

**Comment by eric-wieser** [comment]
Can you convince me that histograming booleans make sense, given that subtracting them does not?

**Comment by eric-wieser** [comment]
That will give you surprising output if your mask is all true

**Comment by eric-wieser** [comment]
Sorry, to be clear here - you're reporting a regression / change in behavior, not making a feature request? If that's the case, then we ought to restore the old behavior, possibly with a warning.

**Comment by AetherUnbound** [comment]
That's correct, this behavior was possible in 1.14.

**Comment by mattip** [comment]
#12108 was merged. Closing.
