### ISSUE TITLE
python 2.7 range accepts numpy float16, float32, complex when it should raise TypeError

### ISSUE THREAD

**Issue by hmaarrfk** [numpy/numpy#12149]
In python 2.7, range accepts `numpy.float16` and `np.float32`, `np.float128`, `complex64` and `complex128` as inputs, which it really shouldn't.

### Reproducing code example:

```python
>>> import numpy as np
>>> range(np.float16(4))
[0, 1, 2, 3]
>>> range(np.float32(4))
[0, 1, 2, 3]
>>> range(np.complex64(4.))
/home/mark/miniconda3/envs/np2/bin/ipython:1: ComplexWarning: Casting complex values to real discards the imaginary part
  #!/home/mark/miniconda3/envs/np2/bin/python
[0, 1, 2, 3]
>>> range(np.complex128(4.))
/home/mark/miniconda3/envs/np2/bin/ipython:1: ComplexWarning: Casting complex values to real discards the imaginary part
  #!/home/mark/miniconda3/envs/np2/bin/python
[0, 1, 2, 3]
>>> range(np.float128(1))
[0]
```
Success????? But these fail (as expected)
```python
>>> import numpy as np
>>> range(np.float(4))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: range() integer end argument expected, got float.
>>> import numpy as np
>>> range(np.float64(4))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: range() integer end argument expected, got numpy.float64.
```

Not sure if this is a python bug, or numpy bug.

In python3:

```python
>>> import numpy as np
>>> range(np.float16(4))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'numpy.float16' object cannot be interpreted as an integer
>>> range(np.float32(4))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'numpy.float32' object cannot be interpreted as an integer
>>> range(np.complex64(4.))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'numpy.complex64' object cannot be interpreted as an integer
>>> range(np.complex128(4.))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'numpy.complex128' object cannot be interpreted as an integer
>>> range(np.float(4))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'float' object cannot be interpreted as an integer
>>> range(np.float64(4))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'numpy.float64' object cannot be interpreted as an integer
>>> range(np.float128(1))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'numpy.float128' object cannot be interpreted as an integer
```

### Numpy/Python version information:

Python 2.7
```python
>>> import sys, numpy; print(numpy.__version__, sys.version)
('1.16.0.dev0+b99c73d', '2.7.15 |Anaconda, Inc.| (default, Sep 27 2018, 20:19:23) \n[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)]')
```
or 
```python
>>> import sys, numpy; print(numpy.__version__, sys.version)
('1.15.2', '2.7.15 |Anaconda, Inc.| (default, Sep 27 2018, 20:19:23) \n[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)]')
```

Python 3.6
```python
>>> import sys, numpy; print(numpy.__version__, sys.version)
1.15.2 3.6.6 | packaged by conda-forge | (default, Jul 26 2018, 09:53:17) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)]
```

**Comment by seberg** [comment]
This is a python thing, because basically python just forbids floats explicitly. Because of scipy/numpy long ago python got `__index__` and `operator.index`, etc. for this exact purpose.

Python3 started to make use of that for ranges and some other things, NumPy started using it with quite a bit of delay around version 1.9. But basically, python 2.7 won't change in this regard, just use python 3 and be happy we made things clean there ;). (Changing such things is probably not painless, so doing it in python 2.7 seems not a good idea).

**Comment by hmaarrfk** [comment]
@seberg I totally get it. I kinda ran into it writing tests for https://github.com/numpy/numpy/pull/12094 and couldn't find a relevant bug report here or python's site.

I wanted to make sure I was doing the right thing.

Thank you!

**Comment by seberg** [comment]
Yeah, it is indeed confusing, been a long while that I searched digged into the reason behind it :).

**Comment by hmaarrfk** [comment]
Did you ever try to report this to Python itself. I posted it here since the PEP that suggested __index__ was set for 2.5?

https://www.python.org/dev/peps/pep-0357/

**Comment by hmaarrfk** [comment]
It isn't really likely that anybody outside the scientific community will want to fix this though.

**Comment by seberg** [comment]
Well, python fixed it already, its part of python 3 :).
