### ISSUE TITLE
annoconda 5.3.0 ImportError: DLL load failed

### ISSUE THREAD

**Issue by eromoe** [numpy/numpy#12143]
windows 10 x64.

I installed annoconda 5.3.0  after delete 5.2.0 folder, then found this error

### Error message:

```
>>> import numpy as np
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\numpy\core\__init__.py", line 16, in <module>
    from . import multiarray
ImportError: DLL load failed: 找不到指定的模块。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda3\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import add_newdocs
  File "C:\Anaconda3\lib\site-packages\numpy\add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "C:\Anaconda3\lib\site-packages\numpy\lib\__init__.py", line 8, in <module>
    from .type_check import *
  File "C:\Anaconda3\lib\site-packages\numpy\lib\type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "C:\Anaconda3\lib\site-packages\numpy\core\__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError:
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: DLL load failed: 找不到指定的模块。
```

**Comment by eromoe** [comment]
Sorry , post on wrong place .  
solved by add `C:\Anaconda3\Library\bin` to path

**Comment by Asuanh** [comment]
thank you

**Comment by JHxx1229** [comment]
我也遇到了同样的问题,试过了重新删除numpy并安装仍然有错误

**Comment by mattip** [comment]
@JHxx1229 this issue is closed, please open a new issue (you will probably have more luck in English) and follow the guidelines for reporting OS, python version, what you tried, and so on.
