### ISSUE TITLE
DLL error

### ISSUE THREAD

**Issue by taglitis** [numpy/numpy#12197]
Hi! I am trying to run a simple code, just importing pandas, and it gives an error. I believe it is related to numpy. 

### Reproducing code example:

```python
import pandas as pd
print('Hello word')
```

ImportError                               Traceback (most recent call last)
Traceback (most recent call last):
  File "C:\Users\Boris\Anaconda3\lib\site-packages\IPython\core\shellapp.py", line 391, in _run_cmd_line_code
    self._exec_file(fname, shell_futures=True)
  File "C:\Users\Boris\Anaconda3\lib\site-packages\IPython\core\shellapp.py", line 323, in _exec_file
    raise_exceptions=True)
  File "C:\Users\Boris\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2527, in safe_execfile
    self.compile if shell_futures else None)
  File "C:\Users\Boris\Anaconda3\lib\site-packages\IPython\utils\py3compat.py", line 188, in execfile
    exec(compiler(f.read(), fname, 'exec'), glob, loc)
  File "C:\Users\Boris\Google \u0414\u0438\u0441\u043a\Data science\Data analyst\Data analyst class_Udacity\2. Intorduction to Data Analysis\7. Project 2  - Investigate a Dataset\try.py", line 2, in <module>
    import pandas as pd
  File "C:\Users\Boris\Anaconda3\lib\site-packages\pandas\__init__.py", line 19, in <module>
    "Missing required dependencies {0}".format(missing_dependencies))
ImportError: Missing required dependencies ['numpy']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Boris\Anaconda3\Scripts\ipython-script.py", line 10, in <module>
    sys.exit(start_ipython())
  File "C:\Users\Boris\Anaconda3\lib\site-packages\IPython\__init__.py", line 125, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "C:\Users\Boris\Anaconda3\lib\site-packages\traitlets\config\application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-113>", line 2, in initialize
  File "C:\Users\Boris\Anaconda3\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\Users\Boris\Anaconda3\lib\site-packages\IPython\terminal\ipapp.py", line 323, in initialize
    self.init_code()
  File "C:\Users\Boris\Anaconda3\lib\site-packages\IPython\core\shellapp.py", line 271, in init_code
    self._run_cmd_line_code()
  File "C:\Users\Boris\Anaconda3\lib\site-packages\IPython\core\shellapp.py", line 393, in _run_cmd_line_code
    self.shell.showtraceback(tb_offset=4)
  File "C:\Users\Boris\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 1868, in showtraceback
    self._showtraceback(etype, value, stb)
  File "C:\Users\Boris\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 1886, in _showtraceback
    print(self.InteractiveTB.stb2text(stb))
  File "C:\Users\Boris\Anaconda3\lib\site-packages\colorama\ansitowin32.py", line 40, in write
    self.__convertor.write(text)
  File "C:\Users\Boris\Anaconda3\lib\site-packages\colorama\ansitowin32.py", line 141, in write
    self.write_and_convert(text)
  File "C:\Users\Boris\Anaconda3\lib\site-packages\colorama\ansitowin32.py", line 166, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\Boris\Anaconda3\lib\site-packages\colorama\ansitowin32.py", line 174, in write_plain_text
    self.wrapped.write(text[start:end])
  File "C:\Users\Boris\Anaconda3\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 9-12: character maps to <undefined>

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

### Numpy/Python version information:
# Name                    Version                   Build  Channel
numpy                     1.15.1           py37ha559c80_0
numpy-base                1.15.1           py37h8128ebf_0
numpydoc                  0.8.0                    py37_0
ipython                   6.5.0                    py37_0
ipython_genutils          0.2.0                    py37_0
msgpack-python            0.5.6            py37he980bc4_1
python                    3.7.0                hea74fb7_0
python-dateutil           2.7.3                    py37_0

**Comment by mattip** [comment]
Perhaps connected to unicode in your google-drive path name?

> C:\Users\Boris\Google \u0414\u0438\u0441\u043a\Data science\Data analyst\Data analyst class_Udacity\2. Intorduction to Data Analysis\7. Project 2 - Investigate a Dataset\try.py

**Comment by taglitis** [comment]
@mattip, thank you for your feedback! I changed the directory to the one where the path does not have non-english characters. So, there are no more u0414\u0438\u0441\u043a in error list. But, DLL problem is still there. In fact, I  can run it on my machine at work. 



ImportError                               Traceback (most recent call last)
~\Anaconda3\lib\site-packages\numpy\core\__init__.py in <module>()
     15 try:
---> 16     from . import multiarray
     17 except ImportError as exc:

ImportErrorTraceback (most recent call last):
  File "C:\Users\Boris\Anaconda3\lib\site-packages\numpy\core\__init__.py", line                                                                                                               16, in <module>
    from . import multiarray
ImportError: DLL load failed: \u041d\u0435 \u043d\u0430\u0439\u0434\u0435\u043d                                                                                                               \u0443\u043a\u0430\u0437\u0430\u043d\u043d\u044b\u0439 \u043c\u043e\u0434\u0443\                                                                                                              u043b\u044c.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Boris\Anaconda3\lib\site-packages\IPython\core\shellapp.py", li                                                                                                              ne 391, in _run_cmd_line_code
    self._exec_file(fname, shell_futures=True)
  File "C:\Users\Boris\Anaconda3\lib\site-packages\IPython\core\shellapp.py", li                                                                                                              ne 323, in _exec_file
    raise_exceptions=True)
  File "C:\Users\Boris\Anaconda3\lib\site-packages\IPython\core\interactiveshell                                                                                                              .py", line 2527, in safe_execfile
    self.compile if shell_futures else None)
  File "C:\Users\Boris\Anaconda3\lib\site-packages\IPython\utils\py3compat.py",                                                                                                               line 188, in execfile
    exec(compiler(f.read(), fname, 'exec'), glob, loc)
  File "C:\Users\Boris\project2\main_soccer.py", line 4, in <module>
    import matplotlib.pyplot as plt
  File "C:\Users\Boris\Anaconda3\lib\site-packages\matplotlib\__init__.py", line                                                                                                               126, in <module>
    from . import cbook
  File "C:\Users\Boris\Anaconda3\lib\site-packages\matplotlib\cbook\__init__.py"                                                                                                              , line 34, in <module>
    import numpy as np
  File "C:\Users\Boris\Anaconda3\lib\site-packages\numpy\__init__.py", line 142,                                                                                                               in <module>
    from . import add_newdocs
  File "C:\Users\Boris\Anaconda3\lib\site-packages\numpy\add_newdocs.py", line 1                                                                                                              3, in <module>
    from numpy.lib import add_newdoc
  File "C:\Users\Boris\Anaconda3\lib\site-packages\numpy\lib\__init__.py", line                                                                                                               8, in <module>
    from .type_check import *
  File "C:\Users\Boris\Anaconda3\lib\site-packages\numpy\lib\type_check.py", lin                                                                                                              e 11, in <module>
    import numpy.core.numeric as _nx
  File "C:\Users\Boris\Anaconda3\lib\site-packages\numpy\core\__init__.py", line                                                                                                               26, in <module>
    raise ImportError(msg)
ImportError:
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: DLL load failed: \u041d\u0435 \u043d\u0430\u0439\u0434\u0435                                                                                                              \u043d \u0443\u043a\u0430\u0437\u0430\u043d\u043d\u044b\u0439 \u043c\u043e\u0434                                                                                                              \u0443\u043b\u044c.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Boris\Anaconda3\Scripts\ipython-script.py", line 10, in <module                                                                                                              >
    sys.exit(start_ipython())
  File "C:\Users\Boris\Anaconda3\lib\site-packages\IPython\__init__.py", line 12                                                                                                              5, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "C:\Users\Boris\Anaconda3\lib\site-packages\traitlets\config\application.                                                                                                              py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-113>", line 2, in initialize
  File "C:\Users\Boris\Anaconda3\lib\site-packages\traitlets\config\application.                                                                                                              py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\Users\Boris\Anaconda3\lib\site-packages\IPython\terminal\ipapp.py", l                                                                                                              ine 323, in initialize
    self.init_code()
  File "C:\Users\Boris\Anaconda3\lib\site-packages\IPython\core\shellapp.py", li                                                                                                              ne 271, in init_code
    self._run_cmd_line_code()
  File "C:\Users\Boris\Anaconda3\lib\site-packages\IPython\core\shellapp.py", li                                                                                                              ne 393, in _run_cmd_line_code
    self.shell.showtraceback(tb_offset=4)
  File "C:\Users\Boris\Anaconda3\lib\site-packages\IPython\core\interactiveshell                                                                                                              .py", line 1868, in showtraceback
    self._showtraceback(etype, value, stb)
  File "C:\Users\Boris\Anaconda3\lib\site-packages\IPython\core\interactiveshell                                                                                                              .py", line 1886, in _showtraceback
    print(self.InteractiveTB.stb2text(stb))
  File "C:\Users\Boris\Anaconda3\lib\site-packages\colorama\ansitowin32.py", lin                                                                                                              e 40, in write
    self.__convertor.write(text)
  File "C:\Users\Boris\Anaconda3\lib\site-packages\colorama\ansitowin32.py", lin                                                                                                              e 141, in write
    self.write_and_convert(text)
  File "C:\Users\Boris\Anaconda3\lib\site-packages\colorama\ansitowin32.py", lin                                                                                                              e 166, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\Boris\Anaconda3\lib\site-packages\colorama\ansitowin32.py", lin                                                                                                              e 174, in write_plain_text
    self.wrapped.write(text[start:end])
  File "C:\Users\Boris\Anaconda3\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 19-20: c                                                                                                              haracter maps to <undefined>

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

**Comment by seberg** [comment]
Old installation related issue, so closing.
