### ISSUE TITLE
nanmean with masked array gives readonly error only with floats

### ISSUE THREAD

**Issue by scottstanie** [numpy/numpy#12283]
### Reproducing code example:
The `nanmean` function over a fully masked int array works, whereas a float array does not:

```python
import numpy as np
>>> aa = np.ma.array([[1, 2], [3, 4]], mask=[[True, True], [True, True]])

>>> np.nanmean(aa)
 masked

>>> aa = np.ma.array([[1.0, 2], [3, 4]], mask=[[True, True], [True, True]])
>>> np.nanmean(aa)

ValueError: output array is read-only
```

### Error message:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/scott/envs/data/lib/python3.5/site-packages/numpy/lib/nanfunctions.py", line 865, in nanmean
    avg = _divide_by_count(tot, cnt, out=out)
  File "/home/scott/envs/data/lib/python3.5/site-packages/numpy/lib/nanfunctions.py", line 179, in _divide_by_count
    return np.divide(a, b, out=a, casting='unsafe')
ValueError: output array is read-only
```

### Numpy/Python version information:
```
>>> import sys, numpy; print(numpy.__version__, sys.version)
1.15.3 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609]
```

**Comment by jdavies-st** [comment]
This is still a bug in `1.16.4`.

`np.nanmean` still returns an error for a fully-masked float array.
```
import numpy as np
>>> np.__version__
'1.16.4'
>>> a = np.ma.array((1, 2, 3), mask=(True, True, True), dtype=np.float)
>>> np.nanmean(a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jdavies/miniconda3/envs/test/lib/python3.7/site-packages/numpy/lib/nanfunctions.py", line 916, in nanmean
    avg = _divide_by_count(tot, cnt, out=out)
  File "/Users/jdavies/miniconda3/envs/test/lib/python3.7/site-packages/numpy/lib/nanfunctions.py", line 185, in _divide_by_count
    return np.divide(a, b, out=a, casting='unsafe')
ValueError: output array is read-only
```
Meanwhile, `np.mean` works fine:
```
>>> np.mean(a)
masked
```

**Comment by stscieisenhamer** [comment]
A bit more debugging information. The issue arises at
 
https://github.com/numpy/numpy/blob/3963ed0ea4e7d89174b1e992d84b47c0751f533f/numpy/lib/nanfunctions.py#L949-L950

The condition presumes that `out` is `None`. Then, normally, `numpy.sum` returns an array or scaler. `_divde_by_count` can then write its result back to the initial input.

However, when the array is completely masked, `numpy.sum` returns `numpy.ma.core.MaskedConstant`. It is this object that `_divde_by_count` cannot write back to, leading to the `output array is read-only`.

Opinion: Whether or not `nanmean` can handle a completely masked array is up for discussion, though the behavior of `numpy.mean` seems to set a precedent.

However, the current error message has lead to many many hours of debugging, especially with the confounding feature of the `ndarray.flags['WRITEABLE']` that is also on `numpy.ma.core.MaskedConstant`.

**Comment by charris** [comment]
Just to note that the nanfunctions were conceived as alternatives to masked arrays and mixed use was not envisioned. used in combination.  If combined use is desirable we will need to take some time to work that out.

**Comment by eric-wieser** [comment]
> However, when the array is completely masked, `numpy.sum` returns `numpy.ma.core.MaskedConstant`

This is likely something that #13105 would probably allow us to more easily solve.
