### ISSUE TITLE
np.asarray throws an error when passed a list containing tuples if the first entry in the list is not a tuple.

### ISSUE THREAD

**Issue by antomaly** [numpy/numpy#12359]
### Reproducing code example:

```python
import numpy as np
np.asarray(["a",("b","c")])
```

### Error message:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/numpy/core/numeric.py", line 531, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: cannot set an array element with a sequence
```

Note that

```python
np.asarray([("b","c"),"a"])
```
works fine and gives
```
array([('b', 'c'), 'a'], dtype=object)
```

In addition, 
```python
np.asarray(["a",("b","c")], dtype="object")
```
also works and gives
```
array(['a', ('b', 'c')], dtype=object)
```

### Numpy/Python version information:

('1.12.1', '2.7.13 (default, Nov 24 2017, 17:33:09) \n[GCC 6.3.0 20170516]')

**Comment by eric-wieser** [comment]
I fixed this a few months ago:
```python
In [1]: np.asarray(["a",("b","c")])
Out[1]: array(['a', ('b', 'c')], dtype=object)

In [2]: np.asarray([("b","c"),"a"])
Out[2]: array([('b', 'c'), 'a'], dtype=object)

In [3]: np.__version__
Out[3]: '1.16.0.dev0+08204dd'
```

I don't remember if it's already been released in 1.15
