### ISSUE TITLE
as_strided fails on dtypes with overlapping fields

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#12432]
Caused by `dtype.descr` being broken by design, and `__array_interface__` being broken by association.

cc @ahaldane 

```python
>>> dt = np.dtype(dict(
            formats=['<i4', '<i4'],
            names=['a', 'b'],
            offsets=[0, 2],
            itemsize=6
        ))
>>> a = np.zeros(10, dt)
>>> np.lib.index_tricks.as_strided(a)
TypeError: data type not understood

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<pyshell#132>", line 1, in <module>
    np.lib.index_tricks.as_strided(a)
  File "C:\Users\wiese\AppData\Roaming\Python\Python35\site-packages\numpy\lib\stride_tricks.py", line 102, in as_strided
    array = np.asarray(DummyArray(interface, base=x))
  File "C:\Users\wiese\AppData\Roaming\Python\Python35\site-packages\numpy\core\numeric.py", line 501, in asarray
    return array(a, dtype, copy=False, order=order)
SystemError: <built-in function array> returned a result with an error set
```

**Comment by mattip** [comment]
The function has moved and no longer fails. Closing.
```
>>> import numpy as np
>>> np.__version__
'2.6.0.dev0+git20260816.c452636'
>>> dt = np.dtype(dict(
...             formats=['<i4', '<i4'],
...             names=['a', 'b'],
...             offsets=[0, 2],
...             itemsize=6
...         ))
>>> a = np.zeros(10, dt)
>>> np.lib.stride_tricks.as_strided(a)
array([(0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0),
       (0, 0), (0, 0)],
      dtype={'names': ['a', 'b'], 'formats': ['<i4', '<i4'], 'offsets': [0, 2], 'itemsize': 6})
```
