### ISSUE TITLE
Unable to build numpy 1.16 and master with msvc

### ISSUE THREAD

**Issue by cgohlke** [numpy/numpy#12533]
Building numpy from source in maintenance 1.16 and master fail to build on my system (Windows 10 1809, Python 3.7.1 64-bit, Visual Studio CE 2017, no site.cfg). Previous versions of numpy build without problems. Looks like quotes around paths containing spaces are missing:

```
>py -3.7-64 setup.py bdist_wheel
Running from numpy source directory.
Cythonizing sources
Processing numpy/random\mtrand\randint_helpers.pxi.in
Processing numpy/random\mtrand\mtrand.pyx
blas_opt_info:
blas_mkl_info:
No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
customize MSVCCompiler
  libraries mkl_rt not found in ['X:\\Python37\\lib', 'C:\\', 'X:\\Python37\\libs']
  NOT AVAILABLE

<snip>

building library "npymath" sources
No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG  /MD -Inumpy\core\src\common -Inumpy\core\src -Inumpy\core -Inumpy\core\src\npymath -Inumpy\core\src\multiarray -Inumpy\core\src\umath -Inumpy\core\src\npysort -IX:\Python37\include -IX:\Python37\include -IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\ATLMFC\include -IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\include -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.15063.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.15063.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.15063.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.15063.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.15063.0\cppwinrt -IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE -IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE -IC:\Program Files (x86)\Windows Kits\10\include\10.0.15063.0\ucrt -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.15063.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.15063.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.15063.0\winrt /Tc_configtest.c /Fo_configtest.obj
cl : Command line warning D9024 : unrecognized source file type '', object file assumed
cl : Command line warning D9027 : source file '' ignored
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG  /MANIFEST:EMBED,ID=1 /LIBPATH:"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\ATLMFC\lib\x64" /LIBPATH:"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\lib\x64" /LIBPATH:"C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64" /LIBPATH:"C:\Program Files (x86)\Windows Kits\10\lib\10.0.15063.0\ucrt\x64" /LIBPATH:"C:\Program Files (x86)\Windows Kits\10\lib\10.0.15063.0\um\x64" /LIBPATH:"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64" /LIBPATH:"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB\amd64" /LIBPATH:"C:\Program Files (x86)\Windows Kits\10\lib\10.0.15063.0\ucrt\x64" /LIBPATH:"C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64" /LIBPATH:"C:\Program Files (x86)\Windows Kits\10\lib\10.0.15063.0\um\x64" _configtest.obj /OUT:_configtest.exe
LINK : fatal error LNK1181: cannot open input file '.obj'
failure.
removing: _configtest.c _configtest.obj _configtest.obj.d
Traceback (most recent call last):
  File "setup.py", line 411, in <module>
    setup_package()
  File "setup.py", line 403, in setup_package
    setup(**metadata)
  File "D:\Build\numpy\numpy-git\numpy\distutils\core.py", line 171, in setup
    return old_setup(**new_attr)
  File "X:\Python37\lib\site-packages\setuptools\__init__.py", line 143, in setup
    return distutils.core.setup(**attrs)
  File "X:\Python37\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "X:\Python37\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "X:\Python37\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "X:\Python37\lib\site-packages\wheel\bdist_wheel.py", line 188, in run
    self.run_command('build')
  File "X:\Python37\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "X:\Python37\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "D:\Build\numpy\numpy-git\numpy\distutils\command\build.py", line 47, in run
    old_build.run(self)
  File "X:\Python37\lib\distutils\command\build.py", line 135, in run
    self.run_command(cmd_name)
  File "X:\Python37\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "X:\Python37\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "D:\Build\numpy\numpy-git\numpy\distutils\command\build_src.py", line 148, in run
    self.build_sources()
  File "D:\Build\numpy\numpy-git\numpy\distutils\command\build_src.py", line 159, in build_sources
    self.build_library_sources(*libname_info)
  File "D:\Build\numpy\numpy-git\numpy\distutils\command\build_src.py", line 292, in build_library_sources
    sources = self.generate_sources(sources, (lib_name, build_info))
  File "D:\Build\numpy\numpy-git\numpy\distutils\command\build_src.py", line 375, in generate_sources
    source = func(extension, build_dir)
  File "numpy\core\setup.py", line 667, in get_mathlib_info
    raise RuntimeError("Broken toolchain: cannot link a simple C program")
RuntimeError: Broken toolchain: cannot link a simple C program
```

**Comment by mattip** [comment]
Could you do a `git bisect` to find the offending commit? It should be pretty quick to traverse the master branch

**Comment by tylerjereddy** [comment]
Tests for distutils things are hard to do -- maybe we could think about inducing some more pathlogical install paths for Windows CI builds, if that is indeed the issue here. I think Eric has reported some issues with spaces in paths too.

**Comment by cgohlke** [comment]
> Could you do a git bisect to find the offending commit? It should be pretty quick to traverse the master branch

I could not get distutils to find the Visual Studio compiler when running `git bisect run buildscript`.  Will try manually later.

**Comment by cgohlke** [comment]
The culprit is [MAINT: remove exec_command usage from ccompiler.py](https://github.com/numpy/numpy/commit/83b03407053aefd9553cf3636860f2be8f57f596)

**Comment by eric-wieser** [comment]
That doesn't surprise me - I already had to summit a patch over that to make builds work for me

**Comment by eric-wieser** [comment]
I'm surprised that #12413 didn't fix this for you though. In particular, I see ` /LIBPATH:"C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64"` in your output (with extra quotes), whereas in my output there are no extra quotes.

**Comment by mattip** [comment]
The first problematic warning is " Command line warning D9024 : unrecognized source file type '', object file assumed" just after the `cl` command. 

I cannot reproduce on Windows 10, vc2017 community compiler edition, even when moving my cpython3.7.1 installation to a M: disk. My build output looks very similar. I directly invoke `m:\Python37\python.exe`. What does `py -3.7-64` mean in the very first line?

**Comment by eric-wieser** [comment]
@cgohlke: How was your empty flag being inserted? It sounds like we still created a regression here, even though the underlying fault was caused by weird setup in your system.

**Comment by charris** [comment]
I put a 1.16.0 milestone on this just in case.

**Comment by cgohlke** [comment]
> numpy+MKL fails to build when using paths with spaces for library_dirs

Apparently (if I debugged correctly) this is due to another strange behavior of Python's `subprocess.list2cmdline` function: the input `'/LIBPATH:"C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019\\windows\\mkl\\lib\\intel64_win"'` is mangled to `'"/LIBPATH:"C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019\\windows\\mkl\\lib\\intel64_win""'`. 

Again, this is specific to my setup, but it could well be that correctly quoted arguments passed to `extra_compile_args` or `extra_link_args` break builds when using the new numpy.distutils (not tested).

**Comment by eric-wieser** [comment]
Why are you including quotes in the `extra_link_args` argument anyway? If you're passing extra arguments in list form, then there should be no need to insert any shell escaping characters like quotes.

**Comment by cgohlke** [comment]
> Why are you including quotes in the extra_link_args argument anyway?

No reason other than to demonstrate that a valid argument (AFAICT) does not work with Python distutils and no longer works with numpy.distutils. I'm not sure if this is really relevant. Python distutils developers seem unsure too: https://github.com/python/cpython/blob/master/Lib/distutils/spawn.py#L49. See also https://blogs.msdn.microsoft.com/twistylittlepassagesallalike/2011/04/23/everyone-quotes-command-line-arguments-the-wrong-way/

**Comment by eric-wieser** [comment]
@cgohlke: The patch causing the incompatibility involves throwing away code deriving from `spawn` in distutils, and replacing it with `subprocess`, which has maybe had more time to get things right.

That blog post is... terrifying. Is there really no way on windows to invoke the `main(arc, argv)` of one program from another without jumping through string-escaping hoops?

**Comment by eric-wieser** [comment]
Paraphrasing your remark

> this is due to another strange behavior of Python's subprocess.list2cmdline function: 
> ```python
> >>> subprocess.list2cmdline(['/LIBPATH:"C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019\\windows\\mkl\\lib\\intel64_win"'])
> '"/LIBPATH:"C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019\\windows\\mkl\\lib\\intel64_win""'
> ```

Not on my machine, python 3.5.4:
```python
>>> subprocess.list2cmdline(['/LIBPATH:"C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019\\windows\\mkl\\lib\\intel64_win"'])
'"/LIBPATH:\\"C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019\\windows\\mkl\\lib\\intel64_win\\""'

**Comment by cgohlke** [comment]
> I'd subscribe to the subprocess viewpoint that args=['/LIBPATH:"path"'] should be constructed to mean "literally pass in these quote characters to the program as argv[i], by any means necessary" 

Yes, it makes sense that `subprocess.list2cmdline`takes the quotes literally as it does not know anything about valid `/LIBPATH:"path"` arguments. One might expect `distutils` (which deals specifically with compiler and linker arguments) to know, but it is probably better to avoid pre-escaped include and library paths. Anyway, I can now build numpy 1.16 and master with and without MKL. Thanks for your help and patience!
