### ISSUE TITLE
Importing Numpy in GIMP 2.10.8 Python Console Fails in Multiarray

### ISSUE THREAD

**Issue by Jabberwock82** [numpy/numpy#12699]
I'm trying to install numpy for use with the GIMP 2.10.8 Python console, under Windows 10 Pro (64-bit, version 1803).  Doing 'import numpy' fails in the "multiarray numpy extension module" (see below for full error message).

### Reproducing code example:

Here are the steps I went through.  These should be repeatable.  Take note of step 7.  This is the only part I'm unsure of, but I don't know a way around it.

1. I uninstalled the previous GIMP (2.8).
2. I downloaded https://download.gimp.org/mirror/pub/gimp/v2.10/windows/gimp-2.10.8-setup-2.exe to C:\temp.
3. I ran C:\temp\gimp-2.10.8-setup-2.exe, accepting the default install.
4. I ran GIMP 2.10.8 _[Side note: I had to keep GIMP from copying my 2.8 plugins; otherwise the Python console wouldn’t come up.  This is probably irrelevant but mentioned for completeness.]_
5. In GIMP, I opened _Filters > Python-Fu > Console_.  The console header says
`GIMP 2.10.8 Python Console`
`Python 2.7.15 (default, Oct 11 2018, 12:17:52)  [GCC 7.3.0 32 bit]`
I closed the console.

6. I downloaded https://download.lfd.uci.edu/pythonlibs/r5uhg2lo/numpy-1.15.4+mkl-cp27-cp27m-win32.whl to C:\temp.
7. This is where it got hairy.  I ran
`"C:\Program Files\GIMP 2\32\bin\python.exe" -m pip install C:\Temp\numpy-1.15.4+mkl-cp27-cp27m-win32.whl --user
`
but it didn’t work.  After some digging, I discovered that it wanted a ‘mingw’ build.  I couldn’t find one anywhere, so I renamed the .whl file, changing ‘win32’ to ‘mingw’.  I don't know if this might be the root cause.

8. I ran
`"C:\Program Files\GIMP 2\32\bin\python.exe" -m pip install C:\Temp\numpy-1.15.4+mkl-cp27-cp27m-mingw.whl --user
`
It said it installed OK.
9. I opened the GIMP Python console again and tried
`import numpy`
I got the following error (abbreviated - full error is shown in the proper section below):

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Program Files\GIMP 2\32\lib\python2.7\site-packages/numpy/__init__.py", line 142, in <module>
...
Original error was: DLL load failed: The specified module could not be found.

```
10. I can also reproduce it by running `"C:\Program Files\GIMP 2\32\bin\python.exe"` in a CMD shell and entering `import numpy`.
11. I tried various things to get around it, including trying numpy-1.16.0rc2+mkl-cp27-cp27m-win32.whl (again renamed to ‘mingw’), making sure no other Pythons are in my PATH or PYTHONPATH, etc.  No luck.  I also reproduced it on a WIndows 7 computer (same version of GIMP, different .whl files).

### Error message:

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Program Files\GIMP 2\32\lib\python2.7\site-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "C:\Program Files\GIMP 2\32\lib\python2.7\site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "C:\Program Files\GIMP 2\32\lib\python2.7\site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "C:\Program Files\GIMP 2\32\lib\python2.7\site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "C:\Program Files\GIMP 2\32\lib\python2.7\site-packages/numpy/core/__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError: 
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: DLL load failed: The specified module could not be found.

### Numpy/Python version information:

_Importing numpy fails of course, but here's sys.version:_
2.7.15 (default, Oct 11 2018, 12:17:52)  [GCC 7.3.0 32 bit]

**Comment by eric-wieser** [comment]
> After some digging, I discovered that it wanted a ‘mingw’ build. I couldn’t find one anywhere, so I renamed the .whl file, changing ‘win32’ to ‘mingw’.

This is almost certainly your problem.

You need to produce a mingw build, possibly using the same mingw that GIMP was compiled with.
That ought to be possible, but I don't know offhand how to do it. @matthew-brett  wrote [this page](https://github.com/numpy/numpy/wiki/Mingw-static-toolchain) a while ago, so he might have some idea.

**Comment by Jabberwock82** [comment]
I started to follow the mingw instructions referred to above, but I'm groping in the dark.  I'm just not familiar with this build process.  But in the meantime, in the repository referenced by the instructions, I found `numpy-1.9.1+openblas-cp27-none-win32.whl`.  I assume that it's the output of the build process.  I tried installing it (again, changing 'win32' to 'mingw' because it won't accept it otherwise).  I got essentially the same error (less verbose, since it's based on an earlier version of numpy).

I'll leave this open for a few more days in case someone else has some ideas, then I'll close it.

**Comment by Jabberwock82** [comment]
Dammit, I hit the "Close and comment" button by mistake.

**Comment by eric-wieser** [comment]
What is `sys.executable` from within that console?

**Comment by eric-wieser** [comment]
What happens if you don't try to install from a wheel?

**Comment by Jabberwock82** [comment]
```
>>> sys.executable
'C:/Program Files/GIMP 2/32/bin/python.exe'
```
Um...this is going to sound naive, but the only way I've ever installed Python extensions is from a wheel.  Other than adding OpenCV to Blender (which was a struggle), I haven't done much of this sort of thing with Python.

**Comment by eric-wieser** [comment]
Try just `pip install numpy`, using the executable the same way you did before

**Comment by Jabberwock82** [comment]
Aha.  From the instructions, I think I have to do a few more things first, but it's starting to make sense.  It'll have to wait until tomorrow night though.
Thanks!

**Comment by matthew-brett** [comment]
Sorry for this shoot-from-the-hip reply, but I wonder if you could use Msys2 / Python to build / install numpy via mingw?

https://stackoverflow.com/questions/41932407/which-python-should-i-install-and-how-when-using-msys2

I've used http://www.dependencywalker.com/ in the past to look for missing dependencies of DLLs.  Run it over the multiarray dll to see what is missing.
