### ISSUE TITLE
UnicodeDecodeError when installing fortran extensions in Windows

### ISSUE THREAD

**Issue by david-cortes** [numpy/numpy#12697]
If I try to install some python module with a fortran extension using `numpy.distutils.setup`, it will throw me the following error on Windows:
```
Traceback (most recent call last):
  File "setup.py", line 76, in <module>
    configuration = configuration
  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\distutils\core.py", line 169, in setup
    return old_setup(**new_attr)
  File "C:\ProgramData\Anaconda3\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\distutils\command\install.py", line 60, in run
    r = old_install.run(self)
  File "C:\ProgramData\Anaconda3\lib\distutils\command\install.py", line 545, in run
    self.run_command('build')
  File "C:\ProgramData\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\distutils\command\build.py", line 47, in run
    old_build.run(self)
  File "C:\ProgramData\Anaconda3\lib\distutils\command\build.py", line 135, in run
    self.run_command(cmd_name)
  File "C:\ProgramData\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\distutils\command\build_ext.py", line 262, in run
    self.build_extensions()
  File "C:\ProgramData\Anaconda3\lib\distutils\command\build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "C:\ProgramData\Anaconda3\lib\distutils\command\build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\distutils\command\build_ext.py", line 327, in build_extension
    filter_sources(ext.sources)
  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\distutils\misc_util.py", line 523, in filter_sources
    modules = _get_f90_modules(source)
  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\distutils\misc_util.py", line 448, in _get_f90_modules
    for line in f:
  File "C:\ProgramData\Anaconda3\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 141: character maps to <undefined>
```
While in linux it installs just fine. I tried changing the encodings of the source code files to cp1252 and asci, but the problem persists. This is an example repo that shows the problem (when installing with `python setup.py install` or running `python setup.py build_ext –inplace`:
https://github.com/david-cortes/L-BFGS-B-NS

file `setup.py`:
```python
import numpy.distutils
from numpy.distutils.command.build_ext import build_ext
from numpy.distutils.misc_util import Configuration
import numpy.distutils.system_info
from numpy.distutils.core import setup

def configuration(parent_package='', top_path=None):
    from numpy.distutils.misc_util import Configuration

    config = Configuration(None, parent_package, top_path)
    config.set_options(ignore_setup_xxx_py = True,
                       assume_default_configuration = True,
                       delegate_options_to_subpackages = True,
                       quiet = True)

    config.add_subpackage('lbfgsb_ns')

    return config


setup(
	name = "lbfgsb_ns",
	version = "0.1",
	configuration = configuration
	)
```

I found some previous issues here which say it should have been fixed with NumPy 1.10, but it still happens with 1.13 and 1.15.4.

**Comment by david-cortes** [comment]
Closing as distutils is now deprecated.

**Comment by charris** [comment]
Hmm, I think we haven't yet worked on changing f2py away from distutils. @HaoZeke Comment?

**Comment by HaoZeke** [comment]
> Hmm, I think we haven't yet worked on changing f2py away from distutils. @HaoZeke Comment?

No, not yet, but @NamamiShanker did some [great work last year](https://github.com/numpy/numpy/pulls/NamamiShanker) under GSoC setting up the framework, will push that in ASAP and that should get the ball rolling. The [documentation](https://numpy.org/doc/1.22/f2py/buildtools/meson.html#) also lists how to build `f2py` extensions with `meson` over here which I would suggest for this particular issue.
