### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'testing'

### ISSUE THREAD

**Issue by Akshay2350** [numpy/numpy#12701]
I am trying to use a program which will help me in using spacy for nlp purposes. But everytime i execute it i get this error that 

AttributeError: module 'numpy' has no attribute 'testing'

I have seen this thread but not [relevant](https://github.com/numpy/numpy/issues/11400)  

runfile('W:/NER_NLTK_Spacy.py', wdir='W:')
Traceback (most recent call last):

  File "<ipython-input-59-7d4b8598dd16>", line 1, in <module>
    runfile('W:/NER_NLTK_Spacy.py', wdir='W:')

  File "C:\Users\adodhiwala\AppData\Local\conda\conda\envs\py35\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 668, in runfile
    execfile(filename, namespace)

  File "C:\Users\adodhiwala\AppData\Local\conda\conda\envs\py35\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 108, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "W:/NER_NLTK_Spacy.py", line 7, in <module>
    import nltk

  File "C:\Users\adodhiwala\AppData\Local\conda\conda\envs\py35\lib\site-packages\nltk\__init__.py", line 114, in <module>
    from nltk.collocations import *

  File "C:\Users\adodhiwala\AppData\Local\conda\conda\envs\py35\lib\site-packages\nltk\collocations.py", line 39, in <module>
    from nltk.metrics import ContingencyMeasures, BigramAssocMeasures, TrigramAssocMeasures

  File "C:\Users\adodhiwala\AppData\Local\conda\conda\envs\py35\lib\site-packages\nltk\metrics\__init__.py", line 16, in <module>
    from nltk.metrics.scores import          (accuracy, precision, recall, f_measure,

  File "C:\Users\adodhiwala\AppData\Local\conda\conda\envs\py35\lib\site-packages\nltk\metrics\scores.py", line 18, in <module>
    from scipy.stats.stats import betai

  File "C:\Users\adodhiwala\AppData\Local\conda\conda\envs\py35\lib\site-packages\scipy\stats\__init__.py", line 345, in <module>
    from .stats import *

  File "C:\Users\adodhiwala\AppData\Local\conda\conda\envs\py35\lib\site-packages\scipy\stats\stats.py", line 171, in <module>
    from . import distributions

  File "C:\Users\adodhiwala\AppData\Local\conda\conda\envs\py35\lib\site-packages\scipy\stats\distributions.py", line 10, in <module>
    from ._distn_infrastructure import (entropy, rv_discrete, rv_continuous,

  File "C:\Users\adodhiwala\AppData\Local\conda\conda\envs\py35\lib\site-packages\scipy\stats\_distn_infrastructure.py", line 16, in <module>
    from scipy.misc import doccer

  File "C:\Users\adodhiwala\AppData\Local\conda\conda\envs\py35\lib\site-packages\scipy\misc\__init__.py", line 68, in <module>
    from scipy.interpolate._pade import pade as _pade

  File "C:\Users\adodhiwala\AppData\Local\conda\conda\envs\py35\lib\site-packages\scipy\interpolate\__init__.py", line 175, in <module>
    from .interpolate import *

  File "C:\Users\adodhiwala\AppData\Local\conda\conda\envs\py35\lib\site-packages\scipy\interpolate\interpolate.py", line 32, in <module>
    from .interpnd import _ndim_coords_from_arrays

  File "interpnd.pyx", line 1, in init scipy.interpolate.interpnd

  File "C:\Users\adodhiwala\AppData\Local\conda\conda\envs\py35\lib\site-packages\scipy\spatial\__init__.py", line 94, in <module>
    from .kdtree import *

  File "C:\Users\adodhiwala\AppData\Local\conda\conda\envs\py35\lib\site-packages\scipy\spatial\kdtree.py", line 8, in <module>
    import scipy.sparse

  File "C:\Users\adodhiwala\AppData\Local\conda\conda\envs\py35\lib\site-packages\scipy\sparse\__init__.py", line 228, in <module>
    from .base import *

  File "C:\Users\adodhiwala\AppData\Local\conda\conda\envs\py35\lib\site-packages\scipy\sparse\base.py", line 9, in <module>
    from scipy._lib._numpy_compat import broadcast_to

  File "C:\Users\adodhiwala\AppData\Local\conda\conda\envs\py35\lib\site-packages\scipy\_lib\_numpy_compat.py", line 17, in <module>
    _assert_warns = np.testing.assert_warns

AttributeError: module 'numpy' has no attribute 'testing'

please help me with it.

**Comment by Akshay2350** [comment]
![screenshot 1](https://user-images.githubusercontent.com/35965976/50889191-3706b580-13ac-11e9-9a09-cd6836443afa.png)
I tried using this and it seems that it worked perfectly. But i dont know now that what is causing overriding on numpy. Kindly help me with this

**Comment by mattip** [comment]
My guess is that one of the file names in `W:` is getting imported before numpy, and getting used instead of the one numpy needs. Perhaps renaming them by prepending `my_` or something like that.
