### ISSUE TITLE
arm source install numpy error

### ISSUE THREAD

**Issue by GiantDao** [numpy/numpy#12730]
### Reproducing code example:

```python
export PYTHONPATH="/home/staging_dir/target/usr/lib/python2.7:/home/staging_dir/target//usr/lib/python2.7/site-packages:/home/compile_dir/target/numpy-1.15.4/ipkg-install/usr/lib/python2.7/site-packages";
export PYTHONDONTWRITEBYTECODE=1;
export _python_sysroot="/home/out";
export _python_prefix="/usr";
export _python_exec_prefix="/usr";
export PYTHONOPTIMIZE="";  
cd /home/compile_dir/target/numpy-1.15.4/; 
CC="arm-openwrt-linux-muslgnueabi-gcc" 
CCSHARED="arm-openwrt-linux-muslgnueabi-gcc -fpic" 
CXX="arm-openwrt-linux-muslgnueabi-g++" 
LD="arm-openwrt-linux-muslgnueabi-gcc" 
LDSHARED="arm-openwrt-linux-muslgnueabi-gcc -shared" 
CFLAGS="-Os -pipe -march=armv7-a -mtune=cortex-a7 -mfpu=neon -fno-caller-saves -Wno-unused-result -mfloat-abi=hard  -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" 
CPPFLAGS="-I/home/staging_dir/target/usr/include -I/home/staging_dir/target/include -I/home/gcc/linux-x86/arm/toolchain-sunxi-musl/toolchain/usr/include -I/home/gcc/linux-x86/arm/toolchain-sunxi-musl/toolchain/include -I/home/gcc/linux-x86/arm/toolchain-sunxi-musl/toolchain/include/fortify -I/home/staging_dir/target/usr/include/python2.7" 
LDFLAGS="-L/home/staging_dir/target/usr/lib -L/home/staging_dir/target/lib -L/home/gcc/linux-x86/arm/toolchain-sunxi-musl/toolchain/usr/lib -L/home/gcc/linux-x86/arm/toolchain-sunxi-musl/toolchain/lib -znow -zrelro -lpython2.7" 
_PYTHON_HOST_PLATFORM=linux2 
__PYVENV_LAUNCHER__="/usr/bin/python2.7" 
FOPT=arm-openwrt-linux-muslgnueabi-gcc BLAS=None LAPACK=None ATLAS=None   
/home/out/host/bin/python2.7  ./setup.py  --verbose build --executable=arm-openwrt-linux-muslgnueabi-gcc ;
```

### Error message:
Traceback (most recent call last):
  File "./setup.py", line 403, in <module>
    setup_package()
  File "./setup.py", line 395, in setup_package
    setup(**metadata)
  File "/home/compile_dir/target/numpy-1.15.4/numpy/distutils/core.py", line 135, in setup
    config = configuration()
  File "./setup.py", line 167, in configuration
    config.add_subpackage('numpy')
  File "/home/compile_dir/target/numpy-1.15.4/numpy/distutils/misc_util.py", line 1037, in add_subpackage
    caller_level = 2)
  File "/home/compile_dir/target/numpy-1.15.4/numpy/distutils/misc_util.py", line 1006, in get_subpackage
    caller_level = caller_level + 1)
  File "/home/compile_dir/target/numpy-1.15.4/numpy/distutils/misc_util.py", line 943, in _get_configuration_from_setup_py
    config = setup_module.configuration(*args)
  File "numpy/setup.py", line 16, in configuration
    config.add_subpackage('linalg')
  File "/home/compile_dir/target/numpy-1.15.4/numpy/distutils/misc_util.py", line 1037, in add_subpackage
    caller_level = 2)
  File "/home/compile_dir/target/numpy-1.15.4/numpy/distutils/misc_util.py", line 1006, in get_subpackage
    caller_level = caller_level + 1)
  File "/home/compile_dir/target/numpy-1.15.4/numpy/distutils/misc_util.py", line 943, in _get_configuration_from_setup_py
    config = setup_module.configuration(*args)
  File "numpy/linalg/setup.py", line 29, in configuration
    lapack_info = get_info('lapack_opt', 0)  # and {}
  File "/home/compile_dir/target/numpy-1.15.4/numpy/distutils/system_info.py", line 433, in get_info
    return cl().get_info(notfound_action)
  File "/home/compile_dir/target/numpy-1.15.4/numpy/distutils/system_info.py", line 625, in get_info
    self.calc_info()
  File "/home/compile_dir/target/numpy-1.15.4/numpy/distutils/system_info.py", line 1537, in calc_info
    openblas_info = get_info('openblas_lapack')
  File "/home/compile_dir/target/numpy-1.15.4/numpy/distutils/system_info.py", line 433, in get_info
    return cl().get_info(notfound_action)
  File "/home/compile_dir/target/numpy-1.15.4/numpy/distutils/system_info.py", line 625, in get_info
    self.calc_info()
  File "/home/compile_dir/target/numpy-1.15.4/numpy/distutils/system_info.py", line 1776, in calc_info
    if not (assume_lapack or self.check_embedded_lapack(info)):
  File "/home/compile_dir/target/numpy-1.15.4/numpy/distutils/system_info.py", line 1842, in check_embedded_lapack
    obj = c.compile([src], output_dir=tmpdir)
  File "/home/compile_dir/target/numpy-1.15.4/numpy/distutils/ccompiler.py", line 343, in CCompiler_compile
    single_compile(o)
  File "/home/compile_dir/target/numpy-1.15.4/numpy/distutils/ccompiler.py", line 303, in single_compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/home/compile_dir/target/numpy-1.15.4/numpy/distutils/unixccompiler.py", line 61, in UnixCCompiler__compile
    raise CompileError(msg)
distutils.errors.CompileError: Command "arm-openwrt-linux-muslgnueabi-gcc -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Os -pipe -march=armv7-a -mtune=cortex-a7 -mfpu=neon -fno-caller-saves -Wno-unused-result -mfloat-abi=hard -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -I/home/staging_dir/target/usr/include -I/home/staging_dir/target/include -I/home/gcc/linux-x86/arm/toolchain-sunxi-musl/toolchain/usr/include -I/home/gcc/linux-x86/arm/toolchain-sunxi-musl/toolchain/include -I/home/gcc/linux-x86/arm/toolchain-sunxi-musl/toolchain/include/fortify -I/home/staging_dir/target/usr/include/python2.7 -fPIC -c /tmp/tmp3lrqts/source.c -o /tmp/tmp3lrqts/tmp/tmp3lrqts/source.o -MMD -MF /tmp/tmp3lrqts/tmp/tmp3lrqts/source.o.d" failed with exit status 127

### Numpy/Python version information:
python2.7.15 numpy1.15.4

**Comment by GiantDao** [comment]
# numpy1.16.0 Error message:
Running from numpy source directory.
Cythonizing sources
Processing numpy/random/mtrand/randint_helpers.pxi.in
Processing numpy/random/mtrand/mtrand.pyx
Traceback (most recent call last):
  File "/home//staging_dir/target/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home//staging_dir/target/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home//staging_dir/target/usr/lib/python2.7/site-packages/cython.py", line 16, in <module>
    from Cython.Compiler.Main import main
  File "/home//staging_dir/target/usr/lib/python2.7/site-packages/Cython/Compiler/Main.py", line 28, in <module>
    from .Scanning import PyrexScanner, FileSourceDescriptor
ImportError: /home//staging_dir/target/usr/lib/python2.7/site-packages/Cython/Compiler/Scanning.so: wrong ELF class: ELFCLASS32
Traceback (most recent call last):
  File "/home//compile_dir/target/numpy-1.16.0/tools/cythonize.py", line 224, in <module>
    main()
  File "/home//compile_dir/target/numpy-1.16.0/tools/cythonize.py", line 220, in main
    find_process_files(root_dir)
  File "/home//compile_dir/target/numpy-1.16.0/tools/cythonize.py", line 212, in find_process_files
    process(cur_dir, fromfile, tofile, function, hash_db)
  File "/home//compile_dir/target/numpy-1.16.0/tools/cythonize.py", line 171, in process
    processor_function(fromfile, tofile)
  File "/home//compile_dir/target/numpy-1.16.0/tools/cythonize.py", line 86, in process_pyx
    [sys.executable, '-m', 'cython'] + flags + ["-o", tofile, fromfile])
  File "/home//staging_dir/target/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/out/host/bin/python2.7', '-m', 'cython', '--fast-fail', '-o', 'mtrand.c', 'mtrand.pyx']' returned non-zero exit status 1
Traceback (most recent call last):
  File "./setup.py", line 415, in <module>
    setup_package()
  File "./setup.py", line 398, in setup_package
    generate_cython()
  File "./setup.py", line 211, in generate_cython
    raise RuntimeError("Running cythonize failed!")
RuntimeError: Running cythonize failed!

**Comment by mattip** [comment]
What was the original compiler error message? There should have been something else printed. What happens when you run the last line (the part between the double-quotes)? We have had some reports of failures [with musl](https://github.com/numpy/numpy/issues?q=is%3Aissue+musl+is%3Aclosed) but NumPy should build, it may fail to run

From your second message it seems you have a mix of x86 and arm installations and your system may be broken: `ImportError: /home//staging_dir/target/usr/lib/python2.7/site-packages/Cython/Compiler/Scanning.so: wrong ELF class: ELFCLASS32`

**Comment by GiantDao** [comment]
@mattip  I am using numpy in PC cross compilation arm.

```
/home/staging_dir/target/usr/lib/python2.7/site-packages/Cython/Compiler/Scanning.so: ELF 32-bit LSB  shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, not stripped

```

**Comment by GiantDao** [comment]
@mattip  Solved the problem, the wrong is the host side of the python load ARM library.
How to specify the installation path of numpy through setup.py?

**Comment by GiantDao** [comment]
@mattip ok.  python2.7  setup.py  install --root="$(PKG_INSTALL_DIR)" --prefix="/usr",will install in PKG_INSTALL_DIR.
thank you.
