### ISSUE TITLE
1.16.0 test failures against Python 2.7.15

### ISSUE THREAD

**Issue by chissg** [numpy/numpy#12838]
While building numpy 1.16.0 on Scientific Linux 7 against a non-system Python 2.7.15 with:
```
FC=false \
CC=gcc \
CXX=false \
CFLAGS='-O3 -g -DNDEBUG -fno-omit-frame-pointer' \
python setup.py build -j 41 install --prefix <dir>
nosetests -w <dir>/lib/python2.7/site-packages/numpy-1.16.0-py2.7-linux-x86_64.egg/numpy/tests
```

The following test failure report is generated:
```
.............E..........F......
======================================================================
ERROR: Test that return values are coerced to arrays
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/greenc/work/cet-is/test-products/nose/v1_3_7h/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/case.py", line 197, in r
unTest
    self.test(*self.arg)
TypeError: test_return() takes exactly 2 arguments (1 given)

======================================================================
FAIL: numpy.tests.test_public_api.test_numpy_namespace
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/greenc/work/cet-is/test-products/nose/v1_3_7h/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/greenc/work/cet-is/test-products/numpy/v1_16_0/Linux64bit+3.10-2.17-e19-p2715a-prof/lib/python2.7/site-packages/numpy-1.16.0-py2.7-linux-x86_64.egg/numpy/tests/test_public_api.py", line 70, in test_numpy_namespace
    assert bad_results == whitelist
AssertionError

----------------------------------------------------------------------
Ran 31 tests in 0.750s
```

```
('1.16.0', '2.7.15 (default, Jan 11 2019, 11:17:43) \n[GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]')
```

## Notes

1. Built against Lapack 3.8.0, GCC 8.2.0.
2. Exact procedure / dependencies, _etc._ work just fine with numpy 1.15.4.

Any ideas?

Many thanks for any help understanding whether this is a system / environment issue or a bug.

**Comment by chissg** [comment]
Looks like this works:
```
$ python runtests.py --mode=full
...
7192 passed, 121 skipped, 9 xfailed, 1 xpassed in 331.04 seconds
```
Sorry for the line noise.
