### ISSUE TITLE
Can't install numpy with pip v19.0

### ISSUE THREAD

**Issue by montreal91** [numpy/numpy#12833]
For some reason, after pip is upgraded to version 19.0, I'm not able to install the most recent version of numpy (it still perfectly works with pip version 18.1).

When I run
```
pip install numpy --no-cache
```
I get this exception
```
Exception:
Traceback (most recent call last):
  File "/home/me/.venvs/_/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 176, in main
    status = self.run(options, args)
  File "/home/me/.venvs/_/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 346, in run
    session=session, autobuilding=True
  File "/home/me/.venvs/_/lib/python3.6/site-packages/pip/_internal/wheel.py", line 848, in build
    assert building_is_possible
AssertionError
```
I'm also using python version 3.6, and virtualenvwrapper version 16.0.0.

**Comment by montreal91** [comment]
It's fixed with pip 19.0.1.
