### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not unicode

### ISSUE THREAD

**Issue by loretoparisi** [numpy/numpy#12875]
### Reproducing code example:

This happens while loading saved `npy` - full code it is here https://github.com/loretoparisi/indic-trans/blob/master/indictrans/base.py#L77

```python
import numpy as np
np.load( '%s/models/%s/classes.npy')
```

### Error message:

```sh
Traceback (most recent call last):
  File "/usr/local/bin/indictrans", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/indictrans/__init__.py", line 299, in main
    process_args(args)
  File "/usr/local/lib/python2.7/dist-packages/indictrans/__init__.py", line 149, in process_args
    trn = Transliterator(args.source, args.target, rb=args.rb, build_lookup=args.build_lookup)
  File "/usr/local/lib/python2.7/dist-packages/indictrans/transliterator.py", line 82, in __init__
    ru2i = Rom2Target(source, target, decoder, build_lookup)
  File "/usr/local/lib/python2.7/dist-packages/indictrans/script_transliterate.py", line 63, in __init__
    build_lookup)
  File "/usr/local/lib/python2.7/dist-packages/indictrans/base.py", line 69, in __init__
    self.base_fit()
  File "/usr/local/lib/python2.7/dist-packages/indictrans/base.py", line 117, in base_fit
    self.load_models()
  File "/usr/local/lib/python2.7/dist-packages/indictrans/base.py", line 80, in load_models
    encoding='latin1')[0]
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 415, in load
    fid = open(os_fspath(file), "rb")
  File "/usr/local/lib/python2.7/dist-packages/numpy/compat/py3k.py", line 237, in os_fspath
    "not " + path_type.__name__)
TypeError: expected str, bytes or os.PathLike object, not unicode
```

### Numpy/Python version information:

```sh
python -c "import numpy; print numpy.__version__"
1.16.0
python --version
Python 2.7.1
```

on `Ubuntu 16.04`

This error could be related to https://github.com/numpy/numpy/issues/12749

**[WORKAROUND]**
Revert back to `python 1.15`:

```sh
numpy>=1.10.4,<1.16.0
```

**Comment by charris** [comment]
Should be fixed when 1.16.1 comes out, closing as duplicate. If it persists after that release, please reopen.

**Comment by loretoparisi** [comment]
@charris okay, do you have an ETA?

**Comment by charris** [comment]
By Monday.
