### ISSUE TITLE
numpy 1.16 with Python3.6 import fail

### ISSUE THREAD

**Issue by Kh4L** [numpy/numpy#12878]
I installed numpy 1.16 for Python3.6 by upgrading it with `pip3 --upgrade`. And numpy fails at import on this line https://github.com/numpy/numpy/blob/971e2e89d08deeae0139d3011d15646fdac13c92/numpy/core/_methods.py#L158

### Reproducing code example:

```python
python3

import numpy as np
```

additionally, please find `sys.path` output here:

```
['', '/usr/lib/python36.zip', '/usr/lib/python3.6', '/usr/lib/python3.6/lib-dynload', '/home/user/.local/lib/python3.6/site-packages', '/usr/local/lib/python3.6/dist-packages', '/usr/lib/pytho
n3/dist-packages']
```

### Error message:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/.local/lib/python3.6/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/home/user/.local/lib/python3.6/site-packages/numpy/core/__init__.py", line 59, in <module>
    from . import numeric
  File "/home/user/.local/lib/python3.6/site-packages/numpy/core/numeric.py", line 3093, in <module>
    from . import fromnumeric
  File "/home/user/.local/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 17, in <module>
    from . import _methods
  File "/home/user/.local/lib/python3.6/site-packages/numpy/core/_methods.py", line 158, in <module>
    _NDARRAY_ARRAY_FUNCTION = mu.ndarray.__array_function__
AttributeError: type object 'numpy.ndarray' has no attribute '__array_function__'
```

### Numpy/Python version information:
Numpy:  numpy-1.16.0
Python: Python 3.6.7 (default, Oct 22 2018, 11:32:17) [GCC 8.2.0] on linux

**Comment by Kh4L** [comment]
Missed that issue when browsing the open issues... thanks :+1:
