### ISSUE TITLE
numpy.savez can't save structured arrays with unicode field names

### ISSUE THREAD

**Issue by rnhmjoj** [numpy/numpy#12876]
### Reproducing code example:

```python
import numpy as np
x = np.array([(1,2)], dtype=[('α', int), ('β', int)])
np.savez_compressed('test', x)
```

### Error message:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/numpy/lib/npyio.py", line 667, in savez_compressed
    _savez(file, args, kwds, True)
  File "/numpy/lib/npyio.py", line 706, in _savez
    pickle_kwargs=pickle_kwargs)
  File "/numpy/lib/format.py", line 572, in write_array
    version)
  File "/numpy/lib/format.py", line 315, in _write_array_header
    header = asbytes(_filter_header(header))
  File "/numpy/compat/py3k.py", line 35, in asbytes
    return str(s).encode('latin1')
UnicodeEncodeError: 'latin-1' codec can't encode character '\u03b1' in position 13: ordinal not in range(256)
```
### Numpy/Python version information:

python 3.6.7, numpy 1.15.1

**Comment by Dan-Patterson** [comment]
fails for plain np.save as well

**Comment by gabelstein** [comment]
Should this be fixed by encoding it in utf-8 when the error occurs?

**Comment by mattip** [comment]
No longer reproduces. `np.save` round trips cleanly on linux64. If this fails on windows please reopen or open a new issue referencing this one.
