### ISSUE TITLE
numpy.linalg.svd did not converge with normal ndarray

### ISSUE THREAD

**Issue by ribes96** [numpy/numpy#12941]
I found and array on which numpy.linalg.svd fails. It is this one:
[bad_array.zip](https://github.com/numpy/numpy/files/2837003/bad_array.zip)

### Reproducing code example:

```python
import numpy as np
from numpy.linalg import svd

path = 'bad_array.npy'
X = np.load(path)

print(np.isnan(X).any())
# False

svd(X)
```

### Error message:
```
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    svd(X)
  File "/home/hobber/.virtualenvs/tfg_env/lib/python3.6/site-packages/numpy/linalg/linalg.py", line 1612, in svd
    u, s, vh = gufunc(a, signature=signature, extobj=extobj)
  File "/home/hobber/.virtualenvs/tfg_env/lib/python3.6/site-packages/numpy/linalg/linalg.py", line 106, in _raise_linalgerror_svd_nonconvergence
    raise LinAlgError("SVD did not converge")
numpy.linalg.LinAlgError: SVD did not converge
```

It might be an issue on OpenBlas. See scipy/scipy#9620
```
>>> numpy.show_config()
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
```
I don't know how to see the OpenBlas version, but as it is NumPy 1.16.1, it is expected to be `OpenBLAS v0.3.4+`. It was supposed to be fixed with this release, but here it is again.

Scipy version of svd doesn't fail, maybe because it is stil using an older version of OpenBlas
```
>>> scipy.__version__
'1.2.0'
```
Everything is installed from PyPI, with pip
```
$ sudo lshw | grep -i cpu
     *-cpu                  
          description: CPU
          product: Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
          bus info: cpu@0
          version: Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
          capabilities: x86-64 fpu fpu_exception wp vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp flush_l1d cpufreq
```
With `OMP_NUM_THREADS=1` it doesn't fail.

### Numpy/Python version information:

NumPy version: '1.16.1'
Python version: 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0]

**Comment by charris** [comment]
Can reproduce in linux-x86_64 virtual environment.

**Comment by ribes96** [comment]
It may be a different issue, but this is interesting:
I have installed NumPy and Scipy versions offered in Ubuntu official repos. They use `NumPy 1.13.3` and `Scipy 0.19.1`, and both use `libblas3` from [netlib](http://www.netlib.org/lapack/)
```
>>> numpy.show_config()
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
  NOT AVAILABLE
atlas_3_10_blas_threads_info:
  NOT AVAILABLE
atlas_3_10_blas_info:
  NOT AVAILABLE
atlas_blas_threads_info:
  NOT AVAILABLE
atlas_blas_info:
  NOT AVAILABLE
blas_info:
    libraries = ['blas', 'blas']
    library_dirs = ['/usr/lib/x86_64-linux-gnu']
    include_dirs = ['/usr/local/include', '/usr/include']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    libraries = ['blas', 'blas']
    library_dirs = ['/usr/lib/x86_64-linux-gnu']
    include_dirs = ['/usr/local/include', '/usr/include']
    language = c
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
  NOT AVAILABLE
atlas_3_10_threads_info:
  NOT AVAILABLE
atlas_3_10_info:
  NOT AVAILABLE
atlas_threads_info:
  NOT AVAILABLE
atlas_info:
  NOT AVAILABLE
lapack_info:
    libraries = ['lapack', 'lapack']
    library_dirs = ['/usr/lib/x86_64-linux-gnu']
    language = f77
lapack_opt_info:
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    libraries = ['lapack', 'lapack', 'blas', 'blas']
    library_dirs = ['/usr/lib/x86_64-linux-gnu']
    language = c
    include_dirs = ['/usr/local/include', '/usr/include']
```
It performs svd on the previously mentioned array without problems, but I found another one in which the Ubuntu version fails. This one:
[ubuntu_fail.zip](https://github.com/numpy/numpy/files/2838648/ubuntu_fail.zip)

So, this is the scene: OpenBlas fails with this array, libblas3 fails with `ubuntu_fail.npy`, and from scipy/scipy#9758 MKL fails with another one. It seems every library has a problem with svd. Will it be coincidence?

**Comment by ribes96** [comment]
I compiled OpenBLAS and built from source `NumPy 1.16.1` linking to the compiled OpenBLAS libraries, as explained [here](https://hunseblog.wordpress.com/2014/09/15/installing-numpy-and-openblas/). With the resulting NumPy version I could svd `bad_array.npy`, but soon I found another one which fails

**Comment by eric-wieser** [comment]
What does np.linalg.cond give on this matrix?

**Comment by ribes96** [comment]
```
import numpy as np
from numpy.linalg import cond

path = 'bad_array.npy'
X = np.load(path)
opt = [None, 1, -1, 2, -2, np.inf, -np.inf, 'fro']
for i in opt:
    print('{0:>6}'.format(str(i)), end=': ')
    try:
        c = cond(X, p=i)
    except np.linalg.LinAlgError:
        print('FAILS')
    else:
        print(c)
```
```
  None: 2.4702309236846856
     1: FAILS
    -1: FAILS
     2: 2.4702309236846856
    -2: 0.4048204523763163
   inf: FAILS
  -inf: FAILS
   fro: FAILS
```

**Comment by V-Kh** [comment]
@ribes96 It seems that this is indeed related to BLAS. Both matrices that you provided give me nice answers. However, I use numpy build specifically for my machine (icc + mkl).

**Comment by ribes96** [comment]
I've always been able to find a failing array with NumPy and Scipy, using OpenBlas, MKL and libbblas. But I haven't been able to find it using the parameter `lapack_driver='gesvd'` of the scipy version of svd. This makes me think it may be a problem with Lapack, but I'm not able to dig much more.
Maybe the default should be changed, although it is much slower. At least, I think NumPy should allow to use it, since it seems `gesdd` is hardcoded there.

**Comment by V-Kh** [comment]
Found a similar issure [here](https://stackoverflow.com/questions/54600809/svd-calculation-error-from-lapack-function-when-using-scikit-learns-linear-disc) (MKL related)

**Comment by hameerabbasi** [comment]
This works in NumPy 1.17.2.

```python
>>> np.linalg.svd(X)
(array([[ 1.15265907e-02,  6.40704589e-03, -3.60251846e-02, ...,
         1.52184139e-03,  2.83998431e-03,  6.02600491e-03],
       [-3.40371720e-17,  9.22503583e-17, -4.24668438e-17, ...,
        -9.17863250e-02,  1.10264818e-01, -8.68383995e-02],
       [-1.09226702e-04, -2.59324219e-05, -1.08573028e-04, ...,
         1.52184139e-03,  2.83998431e-03,  6.02600491e-03],
       ...,
       [-4.30970364e-18,  8.80914265e-18,  3.49655201e-18, ...,
         9.92237606e-01,  9.31796731e-03, -7.35097964e-03],
       [ 4.54141914e-03, -5.41862987e-02,  3.26897185e-02, ...,
         1.52184139e-03,  2.83998431e-03,  6.02600491e-03],
       [-2.95910654e-03,  2.83468010e-04, -1.45442955e-03, ...,
         1.52184139e-03,  2.83998431e-03,  6.02600491e-03]]), array([1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 0.40482045]), array([[ 0.00000000e+00, -6.39671668e-05, -1.25171973e-01, ...,
         1.45293576e-03, -4.11745439e-02, -4.27640843e-04],
       [ 0.00000000e+00, -1.14429291e-04, -9.01723959e-02, ...,
         3.03857646e-04,  3.32649416e-02, -4.32404837e-05],
       [ 0.00000000e+00,  5.72726564e-06, -5.71261547e-02, ...,
        -7.65500832e-04,  1.05324946e-01,  3.15636234e-04],
       ...,
       [ 6.71016512e-05,  4.33647063e-05,  4.05416774e-05, ...,
         4.50815189e-05,  4.59380087e-05,  4.66667065e-05],
       [ 1.90707704e-03,  2.13861280e-03,  2.01810531e-03, ...,
         1.99951765e-03,  1.96001012e-03,  2.01544506e-03],
       [-4.47213595e-02, -4.47213596e-02, -4.47213595e-02, ...,
        -4.47213595e-02, -4.47213595e-02, -4.47213596e-02]]))
>>> np.show_config()
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
```

**Comment by eric-wieser** [comment]
I'm curious - why is `atlas` not in your `show_config` @hameerabbasi?

**Comment by hameerabbasi** [comment]
Perhaps I'm on macOS? In either case, my `show_config` matches the original `show_config`.
