### ISSUE TITLE
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

### ISSUE THREAD

**Issue by patrickDBL** [numpy/numpy#12958]
I am running the latest Mac OSX. I just did the following three things, some combination of which broke my numpy install. 

- Updated to python 3.7 using pip3.
- Updated numpy using pip3.
- Cleaned up my .bash_profile file. 

When I type "import numpy" into the python interpreter, or run a script that imports numpy, I get the following error message.

```
>>> import numpy
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/numpy/core/__init__.py", line 16, in <module>
    from . import multiarray
  File "/usr/local/lib/python3.7/site-packages/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/usr/local/lib/python3.7/site-packages/numpy/core/overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/usr/local/lib/python3.7/site-packages/numpy/core/__init__.py", line 47, in <module>
    raise ImportError(msg)
ImportError: 
```

My .bash_profile profile is below.

```
export PATH="/usr/local/bin"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:$PATH"
export PATH=/usr/local/share/python3:$PATH
export PYTHONPATH="/usr/local/lib/python3.7/site-packages"
export PYTHONPATH=/usr/local/lib/python3:$PYTHONPATH
```

Is there a simple way to get numpy working again?

In this issue it was mentioned that forcing a reinstall of an earlier version might work: 
https://github.com/numpy/numpy/issues/12825. However, this did not help matters. I have uninstalled and reinstalled the current version several times now, to no avail.

Thanks for your time!

**Comment by patrickDBL** [comment]
I did the following things and it imports now.

- Using the homebrew install script, uninstalled homebrew and all its packages.
- Installed homebrew, python, and numpy (through "brew python" and "brew numpy").
- When installing python and numpy, it will decline to overwrite certain syslinks and recommend you do this yourself, and give some command for doing so. I ran the command.

Then it worked.
