### ISSUE TITLE
tensorboard 'numpy' has no attribute 'integer'

### ISSUE THREAD

**Issue by DenisTome** [numpy/numpy#12990]
When running tensorboard, an attribute error is triggered.

### Reproducing code example:

```bash
tensorboard --logdir path/to/dir
```

### Error message:

```
ImportError: numpy.core.multiarray failed to import
ImportError: numpy.core.multiarray failed to import
ImportError: numpy.core.umath failed to import
ImportError: numpy.core.umath failed to import
Traceback (most recent call last):
  File "/home/denis/.local/bin/tensorboard", line 7, in <module>
    from tensorboard.main import run_main
  File "/home/denis/.local/lib/python3.6/site-packages/tensorboard/main.py", line 45, in <module>
    from tensorboard import default
  File "/home/denis/.local/lib/python3.6/site-packages/tensorboard/default.py", line 34, in <module>
    import tensorflow as tf
  File "/home/denis/.local/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/denis/.local/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 70, in <module>
    from tensorflow.python.framework.framework_lib import *  # pylint: disable=redefined-builtin
  File "/home/denis/.local/lib/python3.6/site-packages/tensorflow/python/framework/framework_lib.py", line 25, in <module>
    from tensorflow.python.framework.ops import Graph
  File "/home/denis/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 39, in <module>
    from tensorflow.python.eager import context
  File "/home/denis/.local/lib/python3.6/site-packages/tensorflow/python/eager/context.py", line 29, in <module>
    from tensorflow.python.framework import c_api_util
  File "/home/denis/.local/lib/python3.6/site-packages/tensorflow/python/framework/c_api_util.py", line 25, in <module>
    from tensorflow.python.util import compat
  File "/home/denis/.local/lib/python3.6/site-packages/tensorflow/python/util/compat.py", line 129, in <module>
    integral_types = (_numbers.Integral, _np.integer)
AttributeError: module 'numpy' has no attribute 'integer'
```

### Numpy/Python version information:

Python 3.6.7
Numpy version: 1.16.1

**Comment by mattip** [comment]
There are errors above this one, where are the tracebacks for them?
```
ImportError: numpy.core.multiarray failed to import
ImportError: numpy.core.multiarray failed to import
ImportError: numpy.core.umath failed to import
ImportError: numpy.core.umath failed to import
```

**Comment by DenisTome** [comment]
My bad, it was pointing to a previous numpy version...
The update fixed it

**Comment by RACHANAMOVVA09** [comment]
> My bad, it was pointing to a previous numpy version...
> The update fixed it

To which version have you updated your numpy to?

**Comment by naveeen684** [comment]
Upg
rading pip helped me

**Comment by DavidLemayian** [comment]
I also had to restart my terminal to get this working
