### ISSUE TITLE
float(np.complex128) silently drops imaginary part

### ISSUE THREAD

**Issue by goerz** [numpy/numpy#13007]
~~~
>>> v = 2j
>>> float(v)
*** TypeError: can't convert complex to float

>>> v = np.complex128(2j)
>>> float(v)
0.0
~~~
Silently dropping imaginary parts is a recipe for disaster (bugs) in numerical code!

**Comment by seberg** [comment]
Out of curiosity which numpy/python versions are you using? This should at least give you:
```
__main__:1: ComplexWarning: Casting complex values to real discards the imaginary part
```
(or at least it does for me on 1.16.1 and python 3.7). It could be good to think about moving forward towards an error in any case.

**Comment by goerz** [comment]
Huh. Actually, I also get that warning when I do it in IPython, but not inside a debugger. I'm on '1.15.4' and Python 3.6 and 3.7. In any case, the `ComplexWarning` does get triggered, even though pdb wasn't showing it to me, and it took me a while to figure out how to actually catch that warning (https://stackoverflow.com/a/54814548/152544)

I don't know. Personally, I'm rather allergic to type-casting errors (I've seen them produce subtle, hard to detect wrong results in simulations too many times), so I would much prefer `ComplexWarning` to be an exception by default. I suppose the reason it's not is efficiency?

Feel free to close if you don't find this issue actionable any further.

**Comment by seberg** [comment]
I think warnings should be less efficient. Note you could set them to `"error"` for yourself, unless that breaks some dependency that happens to be not-clean. The reason is probably historic, going to warning is a simple step, going to error might break a lot of code that implicitly assumes it works and requires to first give `DeprecationWarning`s as well.

Would have to check if there is more at work here or not. I guess we could close it, although I would agree with trying to move to an error eventually.

**Comment by tapaswenipathak** [comment]
Hi folks: Interested, doing.

**Comment by namurphy** [comment]
I would support moving towards an error since there is inconsistent behavior with `float` and `numpy.float` as applied to complex numbers from Python versus complex numbers from NumPy.  

```Python
>>> import numpy as np
>>> print(np.__version__)
1.18.1

>>> standard_complex_number = 5 + 6j
>>> numpy_complex_number = np.complex128(5 + 6j)

>>> float(standard_complex_number)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: can't convert complex to float

>>> np.float(standard_complex_number)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: can't convert complex to float

>>> float(numpy_complex_number)  # happens loudly the first time
<stdin>:1: ComplexWarning: Casting complex values to real discards the imaginary part
5.0

>>> np.float(numpy_complex_number)  # happens silently the second time
5.0
```
I missed the `ComplexWarning` at first since I was working on a unit test, so it took me a while to figure out where the inconsistent behavior was happening.  A deprecation warning could suggest using `numpy.real` instead, for which this behavior is explicit and intentional.

**Comment by bsipocz** [comment]
xrefing to the astropy issue (astropy/astropy#10010), so we more likely notice when this will be closed.

**Comment by seberg** [comment]
There may be two distinct cases here:
```
In [2]: float(np.complex_(1j))                                                                                          
/home/sebastian/.local/bin/ipython3:1: ComplexWarning: Casting complex values to real discards the imaginary part
  #!/usr/bin/python3
Out[2]: 0.0

In [3]: np.complex_(1j).astype(np.float64)                                                                              
/home/sebastian/.local/bin/ipython3:1: ComplexWarning: Casting complex values to real discards the imaginary part
  #!/usr/bin/python3
Out[3]: 0.0
```
I think the first one is more obviously incorrect. I also agree that we should probably be doing less unsafe casting in the second case as well, but currently we tend to do unsafe casting everywhere in these cases. I.e. `np.complex_(1j).astype(np.float64, casting="same_kind")` fails.

**Comment by rgommers** [comment]
+1 for deprecating and then turning all of the `ComplexWarning` cases into exceptions.

Cc @leofang, who brought this up at https://github.com/data-apis/array-api/issues/102#issuecomment-752145569. CuPy follows NumPy's current behaviour, but erroring out would be nicer.

**Comment by seberg** [comment]
I am very open to the first case. Does anyone have a clue about whether the second case is actually used in the wild and might require work-arounds?  Disabling `astype()` seems tricky to me, unless you would add a new casting level like `arr.astype(float64, casting="very-unsafe")`, since otherwise it requires to change the code pattern to using `arr.real.astype()` and I am not immediately certain that doesn't break other patterns.

I am happy to be convinced that a cast from complex to float can only reasonably occur in a situation dealing explicitly with complex numbers where using `arr.real` explicitly works. Otherwise, it might be better to rethink the `casting="unsafe"` default rather than the complex cast explicitly. (i.e. why should `string_arr.astype("float")` work if complex to float doesn't?)

**Comment by TrangOul** [comment]
For what it's worth, Python itself is inconsistent in that matter as well:

```python
>>> f = 2.3
>>> c = 2.3 + 4.7j
>>> int(f)
2
>>> int(c)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: can't convert complex to int
>>> float(c)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: can't convert complex to float
```

Why is silently dropping imaginary parts forbidden, whereas silently dropping fractional parts is allowed? Especially if there is a built-in `math.trunc` function. Such behavior seems to be violating The Zen of Python.
