### ISSUE TITLE
Naming a file signal.py breaks the import of numpy.testing

### ISSUE THREAD

**Issue by quentin-ol** [numpy/numpy#13015]
Naming a file `signal.py` breaks the import of numpy.testing

### Reproducing code example:
Name a file `signal.py` with the following content: 

```python
import numpy as np
import numpy.testing as npt
``` 
and run it.
NB: same error happens when copy/pasting those lines in the interpreter when the current directory contains the file `signal.py`.

### Error message:
```
Traceback (most recent call last):
  File "signal.py", line 3, in <module>
    import numpy as np
  File "/home/<redacted>/.local/share/virtualenvs/npt_import_bug-uRyhlZBt/lib/python3.6/site-packages/numpy/__init__.py", line 187, in <module>
    from .testing import Tester
  File "/home/<redacted>/.local/share/virtualenvs/npt_import_bug-uRyhlZBt/lib/python3.6/site-packages/numpy/testing/__init__.py", line 10, in <module>
    from unittest import TestCase
  File "/usr/lib/python3.6/unittest/__init__.py", line 64, in <module>
    from .main import TestProgram, main
  File "/usr/lib/python3.6/unittest/main.py", line 7, in <module>
    from . import loader, runner
  File "/usr/lib/python3.6/unittest/runner.py", line 8, in <module>
    from .signals import registerResult
  File "/usr/lib/python3.6/unittest/signals.py", line 1, in <module>
    import signal
  File "/home/<redacted>/npt_import_bug/signal.py", line 4, in <module>
    import numpy.testing as npt
AttributeError: module 'numpy' has no attribute 'testing'

```

### Numpy/Python version information:

```
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys, numpy; print(numpy.__version__, sys.version)
1.16.1 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0]

```

**Comment by mhvk** [comment]
I cannot reproduce this with `python3`, but with a `signal.py` present, I cannot even start `ipython3`, because it fails looking for the `signal` module [1]. Are you sure this is a numpy issue?

[1] https://docs.python.org/3.5/library/signal.html

**Comment by rgommers** [comment]
not a numpy issue - if you name any file the same as something any module is trying to import and put it in your current working directory, that will be picked up first. `os.py` or `io.py` are also common ones. @quentin-ol please just rename your file
