### ISSUE TITLE
Numpy 1.16.2 f2py test fail

### ISSUE THREAD

**Issue by V-Kh** [numpy/numpy#13053]
### Reproducing code example:

```
python -c 'import numpy; numpy.test("full");'
```

### Error message:
```
_____________________________________________________________________________________________________________ TestKind.test_all ______________________________________________________________________________________________________________

self = <numpy.f2py.tests.test_kind.TestKind object at 0x7f0197e35c88>

    @pytest.mark.slow
    def test_all(self):
        selectedrealkind = self.module.selectedrealkind
        selectedintkind = self.module.selectedintkind
    
        for i in range(40):
            assert_(selectedintkind(i) in [selected_int_kind(i), -1],
                    'selectedintkind(%s): expected %r but got %r' %
                    (i, selected_int_kind(i), selectedintkind(i)))
    
        for i in range(20):
            assert_(selectedrealkind(i) in [selected_real_kind(i), -1],
                    'selectedrealkind(%s): expected %r but got %r' %
>                   (i, selected_real_kind(i), selectedrealkind(i)))
E           AssertionError: selectedrealkind(16): expected 10 but got 16

i          = 16
selectedintkind = <fortran object>
selectedrealkind = <fortran object>
self       = <numpy.f2py.tests.test_kind.TestKind object at 0x7f0197e35c88>

/usr/lib/python3.7/site-packages/numpy/f2py/tests/test_kind.py:34: AssertionError
1 failed, 7409 passed, 92 skipped, 10 xfailed, 3 xpassed in 245.10 seconds
```

### Numpy/Python version information:

```
1.16.2 3.7.2 (default, Jan 10 2019, 23:51:51) 
[GCC 8.2.1 20181127]
```
built using icc/MKL

**Comment by mattip** [comment]
Did this build cleanly on a previous version? We do not have access to an Intel compiler.

**Comment by charris** [comment]
For reference, the `_selected_real_kind_func` is in `crackfortran.py`. @V-Kh What platform are you on?

**Comment by V-Kh** [comment]
@mattip I've checked 1.16.1 --- same problem. 
@charris ArchLinux

**Comment by mattip** [comment]
could you go back further through the released versions to try to bisect where the problem started, or has it always been there?

**Comment by charris** [comment]
What does
```
python -c'import platform; print (platform.machine())'
```
show?

**Comment by oleksandr-pavlyk** [comment]
The test builds a simple fortran extension that calls `SELECTED_REAL_KIND`, a [Fortran function](https://gcc.gnu.org/onlinedocs/gfortran/SELECTED_005fREAL_005fKIND.html) that returns Fortran kind of the real number that can accommodate given precision and range of floating point values. 

Gnu Fortran [supports](https://gcc.gnu.org/onlinedocs/gfortran/KIND-Type-Parameters.html) real kinds 4, 8, 10, 16 on a 64-bit processor, but Intel (R) Fortran compiler only [supports](https://software.intel.com/en-us/fortran-compiler-developer-guide-and-reference-model-for-real-data#94AB68BA-1A3B-406C-88EE-40B0C8481C15) 4, 8, 16.

`SELECTED_REAL_KIND` in Intel Fortran compiler would return 16, where Gnu Fortran compiler returns 10.

The test should be modified, but Python needs to know about the compiler that is used to compile the Fortran extension. The best information on how to do that comes from this [SO answer](https://stackoverflow.com/questions/724664/python-distutils-how-to-get-a-compiler-that-is-going-to-be-used).

**Comment by mattip** [comment]
Maybe I don't understand the purpose of the test, but...
If it is important that `SELECTED_REAL_KIND` return 10 when 10 is input, then the test failure is accurate, the intel compiler fails this test. I don't know enough about the subject to say whether this can cause problems. If we can accept the intel behaviour, we should just remove the test altogether.

**Comment by charris** [comment]
@mattip That test has been a long term PITA and I've never been able to determine if it matters. If you search the issues you should be able to find other discussions. @pearu Thoughts? If worst comes to worst, we could try compiling and running a small fortran program as part of the compile, essentially doing what the test does as a part of the configuration.

**Comment by oleksandr-pavlyk** [comment]
`SELECTED_REAL_KIND` serves the purpose of automatically selecting the kind of real (type) of floating point variable that assuredly accommodates requested precision and range.  It's a convenience feature of the compiler. You can always choose a bigger type, and the only price you may pay in the application is performance and/or space. Intel Fortran compiler eliminated real kind 10 because it does not bring either in the resulting binaries.  

The test in NumPy serves, perhaps, to ascertain that compiler behaves reasonably, i.e. it does not allocate too large of a kind for lower precision. I think it is safe to relax that test to allow for either 10 or 16 in the range where the test expected selected real kind of 10.

**Comment by mattip** [comment]
After looking through the issues, I don't understand why we need that test at all. It seems to be testing that a built-in function of the compiler works. Surely that is a compiler problem and not on NumPy to verify, especially if, as @oleksandr-pavlyk says, it doesn't really matter. If there is some quirk we need to work around, then I would understand but we have no issues opened due to the compiler returning 16 when 10 is requested.

**Comment by charris** [comment]
@oleksandr-pavlyk I thought is that it could matter in constructing an interface to the C based types supported by NumPy, and for integers that is likely a possibility, but floating point is a whole other can of worms.

**Comment by oleksandr-pavlyk** [comment]
@charris Real kind 10 is the [extended](https://stackoverflow.com/questions/11399178/how-to-use-and-verify-quad-precision-in-gfortran) 80-bit precision ([wiki](https://en.wikipedia.org/wiki/Extended_precision#x86_Extended_Precision_Format)). Is the corresponding numpy dtype `numpy.float96`?

**Comment by pearu** [comment]
@mattip in short, the test is needed for ensuring that f2py will produce extension modules that will not crash in certain situations. If the test fails, then this indicates that for given platform there exists a situation when the usage of the extension module will crash (with segfault, most probably). I'll skip the longer answer as the fix is simple, see below.

I am not convinced (yet) that this is a compiler issue.

The fix is to add the output of `platform.machine().lower()` to the tuple instance in
https://github.com/numpy/numpy/blob/cbf3a081271a43e980e3c2f76625deb43fd53922/numpy/f2py/crackfortran.py#L2402

**Comment by pearu** [comment]
@charris this test may fail also in future for platforms that have not been tested before. And the fix will be always the same: modify the `_selected_real_kind_func` in `crackfortran.py` file so that the test will pass.

**Comment by charris** [comment]
> Real kind 10 is the extended 80-bit precision (wiki). Is the corresponding numpy dtype numpy.float96?

It is `float96` on 32 bit platforms and `float128` on 64 bit platforms. The different sizes result from different alignment on the two platforms.

**Comment by oleksandr-pavlyk** [comment]
@pearu The test is failing because Intel Fortran Compiler is being used, which does not provide for kind 10, using kind 16 instead. The script in crackfortran.py was written with Gnu Fotran compiler in mind. 

To me this means that the `_selectedrealkind` needs to be aware that of the compiler as well as the platform.

**Comment by pearu** [comment]
@oleksandr-pavlyk `selectedrealkind` output is *not* the subject to be changed. The `_selected_real_kind_func` must be changed to fix this issue. Btw, I wrote the crackfortran.py and I did not have only the Gnu Fortran in my mind.. :)

Note that we don't have information what is the actual output of `platform.machine()` where the test fails. However, it has been indicated that the platform is ArchLinux.

**Comment by oleksandr-pavlyk** [comment]
@pearu Yes, certainly. We apply the following change to `crackfortran.py` at Intel:

```python
def _selected_real_kind_func_intel(p, r=0, radix=0):
    # Intel(R) Fotran compiler only supports kinds 4, 8, 16
    # XXX: This should be processor dependent
    # This is only good for 0 <= p <= 20
    if p < 7:
        return 4
    if p < 16:
        return 8
    if p <= 20:
        return 16
    return -1

_selected_real_kind_func = _selected_real_kind_func_intel
```

I realize we do not know the platform, I am just saying that with the current state `_selected_real_kind_func`, the test fails on `platform.machine()` evaluating to `x86_64` if an Intel Fortran Compiler is being used to compile `numpy/f2py/tests/src/kind/foo.f90`. 

This happens because for p=17, `SELECTED_REAL_KIND(p)` returns 16 with Intel compiler, while it returns 10 with Gnu Fortran compiler.  The explanation I got from Intel Fortran compiler team for the discrepancy was that Intel Fortran compiler dropped support for KIND 10 as it was removed from the hardware.

**Comment by pearu** [comment]
If KIND 10 was removed from hardware, how GnuFortran compiler would still return 10 on the same hardware? This does not make sense to me.

OK, if the result of `_selected_real_kind_func` has to be also compiler dependent, then this is a more fundamental problem as f2py would need to know the used compiler at the stage of constructing the extension module (currently, f2py does not use the compiler information).

**Comment by charris** [comment]
@oleksandr-pavlyk Does Intel support true IEEE128, or is it IEEE80 stored in 16 bytes? AFAICT, there is no hardware support for quad precision on X86_64. I know it can be done with software support, as SPARC does and that there are libraries for that and some new platforms offer it. Note that currently
```
    if machine.startswith(('aarch64', 'power', 'ppc64', 's390x', 'sparc')):
        if p <= 20:
            return 16
    else:
        if p < 19:
            return 10
        elif p <= 20:
            return 16
    return -1
```
I wonder if maybe we should adjust `p < 19` ? Also, quad precision is something like 32 decimal digits.

**Comment by oleksandr-pavlyk** [comment]
@charris Let me pose this question to more knowledgeable people and get back to you with an answer.

**Comment by iabraham** [comment]
Got the same error on Conda version 4.6.7. Created vanilla python environment using following yaml file to see if the Intel Python was actually better:

```
name: intelpy
channels:
        - intel
        - defaults
dependencies:
        - python=3
        - scikit-learn
        - statsmodels
        - matplotlib
        - pillow
        - pytest
        - nose
        - pip:
                - fastdtw
                - mpldatacursor
                - pyastronomy
```
Then just activated environment, imported numpy and ran `numpy.test('full')`. 

```
======================================================================
FAIL: numpy.f2py.tests.test_kind.TestKind.test_all
----------------------------------------------------------------------
Traceback (most recent call last):
  File "~/anaconda3/envs/intelpy/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "~/anaconda3/envs/intelpy/lib/python3.6/site-packages/numpy/f2py/tests/test_kind.py", line 33, in test_all
    (i, selected_real_kind(i), selectedrealkind(i)))
  File "~/anaconda3/envs/intelpy/lib/python3.6/site-packages/numpy/testing/nose_tools/utils.py", line 93, in assert_
    raise AssertionError(smsg)
AssertionError: selectedrealkind(16): expected 16 but got 10

----------------------------------------------------------------------
Ran 7038 tests in 256.366s

FAILED (KNOWNFAIL=14, SKIP=16, failures=1)
<nose.result.TextTestResult run=7038 errors=0 failures=1>
```

**Comment by iabraham** [comment]
For comparison I was running a Continuum managed environment, which also spewed another error (which might require opening a new issue because I currently can't find any)":

```
Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> np.test('full'
... )
Running unit tests for numpy
NumPy version 1.14.5
NumPy relaxed strides checking option: True
NumPy is installed in /home/itabrah2/anaconda3/envs/dodcnn/lib/python3.6/site-packages/numpy
Python version 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) [GCC 7.3.0]
nose version 1.3.7
.
.
.
~/anaconda3/envs/dodcnn/lib/python3.6/site-packages/numpy/fft/tests/test_fft.py:51: ComplexWarning: Casting complex values to real discards the imaginary part
  a = a.astype(t1)
.
.
.
FAIL: numpy.tests.test_warnings.test_warning_calls
----------------------------------------------------------------------
Traceback (most recent call last):
  File "~/anaconda3/envs/dodcnn/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "~/anaconda3/envs/dodcnn/lib/python3.6/site-packages/numpy/tests/test_warnings.py", line 80, in test_warning_calls
    FindFuncs(path).visit(tree)
  File "~/itabrah2/anaconda3/envs/dodcnn/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "~/anaconda3/envs/dodcnn/lib/python3.6/ast.py", line 261, in generic_visit
    self.visit(item)
  File "~/anaconda3/envs/dodcnn/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "~/anaconda3/envs/dodcnn/lib/python3.6/ast.py", line 261, in generic_visit
    self.visit(item)
  File "~/anaconda3/envs/dodcnn/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "~/anaconda3/envs/dodcnn/lib/python3.6/ast.py", line 261, in generic_visit
    self.visit(item)
  File "~/anaconda3/envs/dodcnn/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "~/anaconda3/envs/dodcnn/lib/python3.6/ast.py", line 263, in generic_visit
    self.visit(value)
  File "~/itabrah2/anaconda3/envs/dodcnn/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "~/anaconda3/envs/dodcnn/lib/python3.6/site-packages/numpy/tests/test_warnings.py", line 44, in visit_Call
    "{} on line {}".format(self.__filename, node.lineno))
AssertionError: ignore filter should not be used; found in ~/anaconda3/envs/dodcnn/lib/python3.6/site-packages/numpy/random_intel/__init__.py on line 4

----------------------------------------------------------------------
Ran 7055 tests in 217.478s

FAILED (KNOWNFAIL=14, SKIP=14, failures=1)

```

**Comment by pearu** [comment]
> Got the same error on Conda version 4.6.7. 
> ...
> AssertionError: selectedrealkind(16): expected 16 but got 10

This is *not* the same error, see above the original failure: `selectedrealkind(16): expected 10 but got 16`.

**Comment by pearu** [comment]
So, in this case, the KIND 10 exists in Intel compiler. @iabraham , what does 
```
python -c'import platform; print(platform.machine())'
```
show in your case?

Can you check if crackfortran.py uses `_selected_real_kind_func_intel`?

**Comment by iabraham** [comment]
> So, in this case, the KIND 10 exists in Intel compiler (assuming that `ifc` is actually used).
> @iabraham , what does
> 
> ```
> python -c'import platform; print(platform.machine())'
> ```
> show in your case?
> 
> Can you check if crackfortran.py uses `_selected_real_kind_func_intel`?

I am on `x86_64` but I was using Anaconda as package manager, so I don't think I have the source `crackfortran.py` explicitly on my system. I do have a `f2py` binary in the bin folder under the environment.

**Comment by pearu** [comment]
@iabraham , try:
```
>>> import numpy.f2py.crackfortran as m
>>> import inspect
>>> print(inspect.getsource(m._selected_real_kind_func))
```

**Comment by iabraham** [comment]
Okay that returns:

```
Python 3.6.3 |Intel Corporation| (default, May  4 2018, 04:22:28) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux
Type "help", "copyright", "credits" or "license" for more information.
Intel(R) Distribution for Python is brought to you by Intel Corporation.
Please check out: https://software.intel.com/en-us/python-distribution
>>> import numpy.f2py.crackfortran as m
>>> import inspect
>>> print(inspect.getsource(m._selected_real_kind_func))
def _selected_real_kind_func_intel(p, r=0, radix=0):
    # Intel(R) Fotran compiler only supports kinds 4, 8, 16
    # XXX: This should be processor dependent
    # This is only good for 0 <= p <= 20
    if p < 7:
        return 4
    if p < 16:
        return 8
    if p <= 20:
        return 16
    return -1

>>> 

```

**Comment by pearu** [comment]
So, this shows that this particular Intel compiler supports KIND 10 and using `_selected_real_kind_func_intel` is wrong for this intel compiler version.

The question now is which version of intel compilers removed KIND 10?

**Comment by oleksandr-pavlyk** [comment]
@pearu Sorry about the confusion this may have caused. The change to use `_selected_real_kind_func_intel` in the patches is unconditional, but it should be conditioned on the use of Intel Fortran compiler.  In this case, @iabraham probably has Gnu Fortran installed, and it gets used to build the extension.

Is there a way to confirm this?

**Comment by oleksandr-pavlyk** [comment]
I started to doubt myself, so I whipped up a small reproducer, based on `numpy/f2py/tests/src/kind/foo.f90`:

```fortran
subroutine selectedrealkind(p, r, res)
  implicit none

  integer, intent(in) :: p, r
  !f2py integer :: r=0
  integer, intent(out) :: res
  res = selected_real_kind(p, r)

end subroutine

subroutine selectedintkind(p, res)
  implicit none

  integer, intent(in) :: p
  integer, intent(out) :: res
  res = selected_int_kind(p)

end subroutine

program checkrealkind
  integer res
  integer p

  do p = 4, 20, 1
     call selectedrealkind(p, 0, res)
     print *, p, res
  end do

  print *, "Done!"
end program checkrealkind
```

And compiled it so:

```sh
gfortran -o run_gfortran.exe foo.f90
ifort -o run_ifort.exe foo.f90
```

This is the output:

```text
(def) [11:22:25 vmlin03 f]$ ./run_ifort.exe
           4           4
           5           4
           6           4
           7           8
           8           8
           9           8
          10           8
          11           8
          12           8
          13           8
          14           8
          15           8
          16          16
          17          16
          18          16
          19          16
          20          16
 Done!

(def) [11:25:24 vmlin03 f]$ ./run_gfortran.exe
           4           4
           5           4
           6           4
           7           8
           8           8
           9           8
          10           8
          11           8
          12           8
          13           8
          14           8
          15           8
          16          10
          17          10
          18          10
          19          16
          20          16
 Done!
```

Confirming the discrepancy.

**Comment by oleksandr-pavlyk** [comment]
@charris Regarding your question, Intel supports true IEEE128 floating point numbers, but most likely emulated via software, at least [it used to be this way some time ago](https://software.intel.com/en-us/forums/intel-fortran-compiler-for-linux-and-mac-os-x/topic/358476).

**Comment by charris** [comment]
@oleksandr-pavlyk Hmm, that presents a bit of a problem for the NumPy interface unless Intel C long double is also true IEEE128. That said, quad precision isn't really needed for most applications.

**Comment by V-Kh** [comment]
Oh, folks, sorry,  I got distracted by my thesis and completely forgot about this issue. 
I've updated both numpy and icc, all the tests run absolutely fine now.

**Comment by pearu** [comment]
So, what was the solution?

**Comment by V-Kh** [comment]
@pearu That is a very good question, I still do not know. Now I need to find some time to check different versions of the compiler and some older releases of numpy.

**Comment by vkhodygo** [comment]
Here we go [again](https://github.com/numpy/numpy/files/3999069/error.txt), now it's numpy v1.18.0 and the most recent icc (released a week ago or smth).  I think that it was the same for v1.74.4 and for the previous release of icc.

**Comment by charris** [comment]
@vkhodygo If it was working for you before, what changed? There have been no changes on the NumPy side. Are you on the same platform?

**Comment by charris** [comment]
IIRC, Intel was patching numpy for this. So where have you gotten the working NumPy vs the new version?

**Comment by vkhodygo** [comment]
> If it was working for you before, what changed? 

@charris  Essentially, I update only numpy and icc.

> There have been no changes on the NumPy side. Are you on the same platform?

Yes, I still use the same machine and distro. 

> So where have you gotten the working NumPy vs the new version?

I missed a few 1.17.x releases so it's difficult to tell for sure.

**Comment by vkhodygo** [comment]
@charris 
OK, I managed to get a machine for testing.
I went down all the way to v.1.16.3 with the most recent icc (2020.0.166-1). 
I observe the same issue everywhere. 
I'm going to try older icc version, hopefully tomorrow.
