### ISSUE TITLE
Segmentation fault when saving large arrays as csv

### ISSUE THREAD

**Issue by leondavi** [numpy/numpy#13148]
Segmentation fault is caused when trying to save a large number of columns/rows

### Reproducing code example:

In order to reproduce the issue download the following zip file:
https://drive.google.com/file/d/1jlSg2Mkevkz9pA3iVGt-Hs-6fOhTJ8MO/view?usp=sharing 
Clone the following project: https://github.com/leondavi/erlangGraphPlay
then create a subfolder called data and extract the trace files into this folder. 
Run the python script by calling python3 /src_python/main.py

### Error message:

If you are reporting a segfault please include a GDB traceback, which you
can generate by following
https://github.com/numpy/numpy/blob/master/doc/source/dev/development_environment.rst#debugging

```[traceA] Generating Jointly Distribution Matrix
[traceA] Generating nodes activity histogram
[traceA] Generating edges activity histogram
[traceA] Analayze completed
[traceA] Saving results to files
[traceA] Saving sparse matrix

Thread 1 "python3" received signal SIGSEGV, Segmentation fault.
_int_malloc (av=av@entry=0x7ffff7dcfc40 <main_arena>, bytes=bytes@entry=1152)
    at malloc.c:3779
3779	malloc.c: No such file or directory.
(gdb) bt
#0  _int_malloc (av=av@entry=0x7ffff7dcfc40 <main_arena>, 
    bytes=bytes@entry=1152) at malloc.c:3779
#1  0x00007ffff7a7b2ed in __GI___libc_malloc (bytes=1152) at malloc.c:3065
#2  0x00007ffff5d095b1 in ?? ()
   from /usr/local/lib/python3.6/dist-packages/numpy/core/multiarray.cpython-36m-x86_64-linux-gnu.so
#3  0x00007ffff5d6ffa0 in ?? ()
   from /usr/local/lib/python3.6/dist-packages/numpy/core/multiarray.cpython-36m-x86_64-linux-gnu.so
#4  0x00007ffff5d64fe5 in ?? ()
   from /usr/local/lib/python3.6/dist-packages/numpy/core/multiarray.cpython-36m-x86_64-linux-gnu.so
#5  0x00007ffff5e07643 in ?? ()
   from /usr/local/lib/python3.6/dist-packages/numpy/core/multiarray.cpython-36m-x86_64-linux-gnu.so
#6  0x00000000005030d5 in ?? ()
#7  0x0000000000507641 in _PyEval_EvalFrameDefault ()
#8  0x0000000000504c28 in ?? ()
#9  0x0000000000501b2e in _PyFunction_FastCallDict ()
#10 0x0000000000591461 in ?? ()
```

### Numpy/Python version information:

1.16.2 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0]

**Comment by charris** [comment]
Could you run the backtrace further until it shows numpy code?

**Comment by leondavi** [comment]
Hey Charris, thanks for your response.
Longer backtrace:
```(gdb) bt
#0  _int_malloc (av=av@entry=0x7ffff7dcfc40 <main_arena>, 
    bytes=bytes@entry=20368) at malloc.c:3779
#1  0x00007ffff7a7b2ed in __GI___libc_malloc (bytes=20368) at malloc.c:3065
#2  0x00007ffff5ba5e51 in PyDataMem_NEW (size=20368)
    at numpy/core/src/multiarray/alloc.c:221
#3  _npy_alloc_cache (alloc=0x7ffff5ba61b0 <PyDataMem_NEW>, 
    cache=0x7ffff611a7e0 <datacache>, msz=1024, esz=1, nelem=20368)
    at numpy/core/src/multiarray/alloc.c:72
#4  npy_alloc_cache (sz=20368) at numpy/core/src/multiarray/alloc.c:114
#5  0x00007ffff5c0d6e0 in PyArray_NewFromDescr_int (allow_emptystring=0, 
    zeroed=0, base=0x0, obj=0x0, flags=0, data=0x0, strides=0x0, 
    dims=0x138aec20, nd=1, descr=0x7ffff6100ec0 <INT_Descr>, 
    subtype=0x7ffff60ff280 <PyArray_Type>)
    at numpy/core/src/multiarray/ctors.c:1072
#6  PyArray_NewFromDescrAndBase (base=0x0, obj=0x0, flags=<optimized out>, 
    data=0x0, strides=0x0, dims=0x138aec20, nd=1, descr=<optimized out>, 
    subtype=0x7ffff60ff280 <PyArray_Type>)
    at numpy/core/src/multiarray/ctors.c:1181
#7  PyArray_NewFromDescr (obj=0x0, flags=<optimized out>, data=0x0, 
    strides=0x0, dims=0x138aec20, nd=1, descr=<optimized out>, 
---Type <return> to continue, or q <return> to quit---bt
    subtype=0x7ffff60ff280 <PyArray_Type>)
    at numpy/core/src/multiarray/ctors.c:1166
#8  PyArray_NewLikeArray (prototype=prototype@entry=0x7fff246c7ad0, 
    order=<optimized out>, dtype=<optimized out>, 
    dtype@entry=0x7ffff6100ec0 <INT_Descr>, subok=<optimized out>)
    at numpy/core/src/multiarray/ctors.c:1237
#9  0x00007ffff5c0d8b4 in PyArray_FromArray (arr=arr@entry=0x7fff246c7ad0, 
    newtype=0x7ffff6100ec0 <INT_Descr>, flags=flags@entry=112)
    at numpy/core/src/multiarray/ctors.c:2114
#10 0x00007ffff5c0ddc4 in PyArray_FromAny (op=op@entry=0x7fff246c7ad0, 
    newtype=newtype@entry=0x7ffff6100ec0 <INT_Descr>, min_depth=0, 
    max_depth=0, flags=flags@entry=112, context=<optimized out>)
    at numpy/core/src/multiarray/ctors.c:1913
#11 0x00007ffff5c0e595 in PyArray_CheckFromAny (op=0x7fff246c7ad0, 
    descr=0x7ffff6100ec0 <INT_Descr>, min_depth=min_depth@entry=0, 
    max_depth=max_depth@entry=0, requires=112, context=context@entry=0x0)
    at numpy/core/src/multiarray/ctors.c:1988
#12 0x00007ffff5ca73dd in _array_fromobject (
    __NPY_UNUSED_TAGGEDignored=<optimized out>, args=<optimized out>, 
    kws=0x7fff24773900) at numpy/core/src/multiarray/multiarraymodule.c:1728
---Type <return> to continue, or q <return> to quit---
#13 0x00000000005030d5 in ?? ()
#14 0x0000000000507641 in _PyEval_EvalFrameDefault ()
#15 0x0000000000504c28 in ?? ()
#16 0x0000000000501b2e in _PyFunction_FastCallDict ()
#17 0x0000000000591461 in ?? ()
#18 0x000000000054b813 in ?? ()
#19 0x0000000000555421 in ?? ()
#20 0x00000000005a730c in _PyObject_FastCallKeywords ()
#21 0x0000000000503073 in ?? ()
#22 0x0000000000507641 in _PyEval_EvalFrameDefault ()
#23 0x0000000000504c28 in ?? ()
#24 0x0000000000502540 in ?? ()
#25 0x0000000000502f3d in ?? ()
#26 0x0000000000506859 in _PyEval_EvalFrameDefault ()
#27 0x0000000000502209 in ?? ()
#28 0x0000000000502f3d in ?? ()
#29 0x0000000000506859 in _PyEval_EvalFrameDefault ()
#30 0x0000000000502209 in ?? ()
#31 0x0000000000502f3d in ?? ()
#32 0x0000000000506859 in _PyEval_EvalFrameDefault ()
---Type <return> to continue, or q <return> to quit---
#33 0x0000000000504c28 in ?? ()
#34 0x0000000000506393 in PyEval_EvalCode ()
#35 0x0000000000634d52 in ?? ()
#36 0x0000000000634e0a in PyRun_FileExFlags ()
#37 0x00000000006385c8 in PyRun_SimpleFileExFlags ()
#38 0x000000000063915a in Py_Main ()
#39 0x00000000004a6f10 in main ()
```

**Comment by seberg** [comment]
I ran the script through valgrind, thinking it might help, because it seems like it might be something more strange, I did not check the result yet, but pasting it below:

<details>

```
Loading traces
Experiment: traceC
---------------------

[traceC] Converting strings to integer representation
[traceC] Generating array of uniques
[traceC] Generating hash table
[traceC] Generating new columns
# of unique addresses: 139505
[traceC] Calculating unique src/dst
# num of pairs 9999999
[traceC] Calculating unique requests
[traceC] Generating Jointly Distribution Matrix
==15812== Warning: set address range perms: large range [0x12b35a040, 0x13f35a058) (undefined)
==15812== Warning: set address range perms: large range [0x12b35a028, 0x13f35a070) (noaccess)
[traceC] Generating nodes activity histogram
[traceC] Generating edges activity histogram
==15812== Warning: set address range perms: large range [0x1a6e49040, 0x1bae49058) (undefined)
==15812== Warning: set address range perms: large range [0x1a6e49028, 0x1bae49070) (noaccess)
[traceC] Analayze completed
[traceC] Saving results to files
[traceC] Saving sparse matrix
==15812== Invalid write of size 8
==15812==    at 0x1B720F43: ??? (in /usr/lib/python3.7/site-packages/scipy/sparse/_sparsetools.cpython-37m-x86_64-linux-gnu.so)
==15812==    by 0x1B720677: ??? (in /usr/lib/python3.7/site-packages/scipy/sparse/_sparsetools.cpython-37m-x86_64-linux-gnu.so)
==15812==    by 0x4BC6A77: _PyMethodDef_RawFastCallKeywords (in /usr/lib/libpython3.7m.so.1.0)
==15812==    by 0x4BC6D10: _PyCFunction_FastCallKeywords (in /usr/lib/libpython3.7m.so.1.0)
==15812==    by 0x4C3D8EA: _PyEval_EvalFrameDefault (in /usr/lib/libpython3.7m.so.1.0)
==15812==    by 0x4B7FB98: _PyEval_EvalCodeWithName (in /usr/lib/libpython3.7m.so.1.0)
==15812==    by 0x4BC6491: _PyFunction_FastCallKeywords (in /usr/lib/libpython3.7m.so.1.0)
==15812==    by 0x4C3D2B2: _PyEval_EvalFrameDefault (in /usr/lib/libpython3.7m.so.1.0)
==15812==    by 0x4BC62EA: _PyFunction_FastCallKeywords (in /usr/lib/libpython3.7m.so.1.0)
==15812==    by 0x4C38C41: _PyEval_EvalFrameDefault (in /usr/lib/libpython3.7m.so.1.0)
==15812==    by 0x4BC62EA: _PyFunction_FastCallKeywords (in /usr/lib/libpython3.7m.so.1.0)
==15812==    by 0x4C38C41: _PyEval_EvalFrameDefault (in /usr/lib/libpython3.7m.so.1.0)
==15812==  Address 0x18e62cd70 is 0 bytes after a block of size 40,736 alloc'd
==15812==    at 0x483777F: malloc (vg_replace_malloc.c:299)
==15812==    by 0x5E8CE5D: PyDataMem_NEW (alloc.c:221)
==15812==    by 0x5E8CE5D: npy_alloc_cache (alloc.c:72)
==15812==    by 0x5EF2945: PyArray_NewFromDescr_int (ctors.c:1072)
==15812==    by 0x5EF2DFA: PyArray_NewFromDescrAndBase (ctors.c:1181)
==15812==    by 0x5EF2DA4: PyArray_NewFromDescr (ctors.c:1166)
==15812==    by 0x5EF805A: PyArray_Empty (ctors.c:3056)
==15812==    by 0x5FCA952: array_empty (multiarraymodule.c:1833)
==15812==    by 0x4BC6CAE: _PyMethodDef_RawFastCallKeywords (in /usr/lib/libpython3.7m.so.1.0)
==15812==    by 0x4BC6D10: _PyCFunction_FastCallKeywords (in /usr/lib/libpython3.7m.so.1.0)
==15812==    by 0x4C3DDFB: _PyEval_EvalFrameDefault (in /usr/lib/libpython3.7m.so.1.0)
==15812==    by 0x4B7FB98: _PyEval_EvalCodeWithName (in /usr/lib/libpython3.7m.so.1.0)
==15812==    by 0x4BC6491: _PyFunction_FastCallKeywords (in /usr/lib/libpython3.7m.so.1.0)
==15812== 
==15812== Invalid write of size 8
==15812==    at 0x1B720F38: ??? (in /usr/lib/python3.7/site-packages/scipy/sparse/_sparsetools.cpython-37m-x86_64-linux-gnu.so)
==15812==    by 0x1B720677: ??? (in /usr/lib/python3.7/site-packages/scipy/sparse/_sparsetools.cpython-37m-x86_64-linux-gnu.so)
==15812==    by 0x4BC6A77: _PyMethodDef_RawFastCallKeywords (in /usr/lib/libpython3.7m.so.1.0)
==15812==    by 0x4BC6D10: _PyCFunction_FastCallKeywords (in /usr/lib/libpython3.7m.so.1.0)
==15812==    by 0x4C3D8EA: _PyEval_EvalFrameDefault (in /usr/lib/libpython3.7m.so.1.0)
==15812==    by 0x4B7FB98: _PyEval_EvalCodeWithName (in /usr/lib/libpython3.7m.so.1.0)
==15812==    by 0x4BC6491: _PyFunction_FastCallKeywords (in /usr/lib/libpython3.7m.so.1.0)
==15812==    by 0x4C3D2B2: _PyEval_EvalFrameDefault (in /usr/lib/libpython3.7m.so.1.0)
==15812==    by 0x4BC62EA: _PyFunction_FastCallKeywords (in /usr/lib/libpython3.7m.so.1.0)
==15812==    by 0x4C38C41: _PyEval_EvalFrameDefault (in /usr/lib/libpython3.7m.so.1.0)
==15812==    by 0x4BC62EA: _PyFunction_FastCallKeywords (in /usr/lib/libpython3.7m.so.1.0)
==15812==    by 0x4C38C41: _PyEval_EvalFrameDefault (in /usr/lib/libpython3.7m.so.1.0)
==15812==  Address 0x18e62cd78 is 8 bytes after a block of size 40,736 alloc'd
==15812==    at 0x483777F: malloc (vg_replace_malloc.c:299)
==15812==    by 0x5E8CE5D: PyDataMem_NEW (alloc.c:221)
==15812==    by 0x5E8CE5D: npy_alloc_cache (alloc.c:72)
==15812==    by 0x5EF2945: PyArray_NewFromDescr_int (ctors.c:1072)
==15812==    by 0x5EF2DFA: PyArray_NewFromDescrAndBase (ctors.c:1181)
==15812==    by 0x5EF2DA4: PyArray_NewFromDescr (ctors.c:1166)
==15812==    by 0x5EF805A: PyArray_Empty (ctors.c:3056)
==15812==    by 0x5FCA952: array_empty (multiarraymodule.c:1833)
==15812==    by 0x4BC6CAE: _PyMethodDef_RawFastCallKeywords (in /usr/lib/libpython3.7m.so.1.0)
==15812==    by 0x4BC6D10: _PyCFunction_FastCallKeywords (in /usr/lib/libpython3.7m.so.1.0)
==15812==    by 0x4C3DDFB: _PyEval_EvalFrameDefault (in /usr/lib/libpython3.7m.so.1.0)
==15812==    by 0x4B7FB98: _PyEval_EvalCodeWithName (in /usr/lib/libpython3.7m.so.1.0)
==15812==    by 0x4BC6491: _PyFunction_FastCallKeywords (in /usr/lib/libpython3.7m.so.1.0)
==15812== 
==15812== 
==15812== More than 10000000 total errors detected.  I'm not reporting any more.
==15812== Final error counts will be inaccurate.  Go fix your program!
==15812== Rerun with --error-limit=no to disable this cutoff.  Note
==15812== that errors may occur in your program without prior warning from
==15812== Valgrind, because errors are no longer being displayed.
==15812== 

valgrind: m_mallocfree.c:307 (get_bszB_as_is): Assertion 'bszB_lo == bszB_hi' failed.
valgrind: Heap block lo/hi size mismatch: lo = 7742647, hi = 370308962844672.
This is probably caused by your program erroneously writing past the
end of a heap block and corrupting heap metadata.  If you fix any
invalid writes reported by Memcheck, this assertion failure will
probably go away.  Please try that before reporting this as a bug.


host stacktrace:
==15812==    at 0x58048114: show_sched_status_wrk (m_libcassert.c:369)
==15812==    by 0x58048227: report_and_quit (m_libcassert.c:440)
==15812==    by 0x580483B9: vgPlain_assert_fail (m_libcassert.c:506)
==15812==    by 0x5805094B: get_bszB_as_is (m_mallocfree.c:305)
==15812==    by 0x5805094B: get_bszB (m_mallocfree.c:315)
==15812==    by 0x5805094B: get_next_b (m_mallocfree.c:434)
==15812==    by 0x5805094B: unlinkBlock (m_mallocfree.c:1694)
==15812==    by 0x58052B2C: vgPlain_arena_malloc (m_mallocfree.c:1875)
==15812==    by 0x58005AD2: vgMemCheck_new_block (mc_malloc_wrappers.c:372)
==15812==    by 0x58005AD2: vgMemCheck_malloc (mc_malloc_wrappers.c:407)
==15812==    by 0x580A7373: do_client_request (scheduler.c:1925)
==15812==    by 0x580A7373: vgPlain_scheduler (scheduler.c:1488)
==15812==    by 0x580F57A0: thread_wrapper (syswrap-linux.c:103)
==15812==    by 0x580F57A0: run_a_thread_NORETURN (syswrap-linux.c:156)

sched status:
  running_tid=1

Thread 1: status = VgTs_Runnable (lwpid 15812)
==15812==    at 0x483777F: malloc (vg_replace_malloc.c:299)
==15812==    by 0x5E8CE5D: PyDataMem_NEW (alloc.c:221)
==15812==    by 0x5E8CE5D: npy_alloc_cache (alloc.c:72)
==15812==    by 0x5EF2945: PyArray_NewFromDescr_int (ctors.c:1072)
==15812==    by 0x5EF2DFA: PyArray_NewFromDescrAndBase (ctors.c:1181)
==15812==    by 0x5EF2DA4: PyArray_NewFromDescr (ctors.c:1166)
==15812==    by 0x5EF2FB9: PyArray_NewLikeArray (ctors.c:1237)
==15812==    by 0x5EF570B: PyArray_FromArray (ctors.c:2117)
==15812==    by 0x5EF4E61: PyArray_FromAny (ctors.c:1916)
==15812==    by 0x5EF501D: PyArray_CheckFromAny (ctors.c:1991)
==15812==    by 0x5FCA4B7: _array_fromobject (multiarraymodule.c:1733)
==15812==    by 0x4BC6CAE: _PyMethodDef_RawFastCallKeywords (in /usr/lib/libpython3.7m.so.1.0)
==15812==    by 0x4BC6D10: _PyCFunction_FastCallKeywords (in /usr/lib/libpython3.7m.so.1.0)
==15812==    by 0x4C3DDFB: _PyEval_EvalFrameDefault (in /usr/lib/libpython3.7m.so.1.0)
==15812==    by 0x4B7FB98: _PyEval_EvalCodeWithName (in /usr/lib/libpython3.7m.so.1.0)
==15812==    by 0x4B80DEB: _PyFunction_FastCallDict (in /usr/lib/libpython3.7m.so.1.0)
==15812==    by 0x4B90907: _PyObject_Call_Prepend (in /usr/lib/libpython3.7m.so.1.0)
==15812==    by 0x4BDEA72: ??? (in /usr/lib/libpython3.7m.so.1.0)
==15812==    by 0x4BF23AB: _PyObject_FastCallKeywords (in /usr/lib/libpython3.7m.so.1.0)
==15812==    by 0x4C3E185: _PyEval_EvalFrameDefault (in /usr/lib/libpython3.7m.so.1.0)
==15812==    by 0x4B7FB98: _PyEval_EvalCodeWithName (in /usr/lib/libpython3.7m.so.1.0)
==15812==    by 0x4BC6491: _PyFunction_FastCallKeywords (in /usr/lib/libpython3.7m.so.1.0)
==15812==    by 0x4C3D2B2: _PyEval_EvalFrameDefault (in /usr/lib/libpython3.7m.so.1.0)
==15812==    by 0x4BC62EA: _PyFunction_FastCallKeywords (in /usr/lib/libpython3.7m.so.1.0)
==15812==    by 0x4C38C41: _PyEval_EvalFrameDefault (in /usr/lib/libpython3.7m.so.1.0)
==15812==    by 0x4BC62EA: _PyFunction_FastCallKeywords (in /usr/lib/libpython3.7m.so.1.0)
==15812==    by 0x4C38C41: _PyEval_EvalFrameDefault (in /usr/lib/libpython3.7m.so.1.0)
==15812==    by 0x4B7FB98: _PyEval_EvalCodeWithName (in /usr/lib/libpython3.7m.so.1.0)
==15812==    by 0x4B80AB3: PyEval_EvalCodeEx (in /usr/lib/libpython3.7m.so.1.0)
==15812==    by 0x4B80ADB: PyEval_EvalCode (in /usr/lib/libpython3.7m.so.1.0)
==15812==    by 0x4CAAC93: ??? (in /usr/lib/libpython3.7m.so.1.0)
==15812==    by 0x4CAC8BD: PyRun_FileExFlags (in /usr/lib/libpython3.7m.so.1.0)
==15812==    by 0x4CADC74: PyRun_SimpleFileExFlags (in /usr/lib/libpython3.7m.so.1.0)
==15812==    by 0x4CAFEB6: ??? (in /usr/lib/libpython3.7m.so.1.0)
==15812==    by 0x4CB00FB: _Py_UnixMain (in /usr/lib/libpython3.7m.so.1.0)
==15812==    by 0x48D3222: (below main) (in /usr/lib/libc-2.28.so)
client stack range: [0x1FFEFDF000 0x1FFF000FFF] client SP: 0x1FFEFFE2B0
valgrind stack range: [0x1002DA6000 0x1002EA5FFF] top usage: 9920 of 1048576

Thread 2: status = VgTs_WaitSys syscall 202 (lwpid 15813)
==15812==    at 0x489BAFC: pthread_cond_wait@@GLIBC_2.3.2 (in /usr/lib/libpthread-2.28.so)
==15812==    by 0x64D579A: blas_thread_server (in /opt/OpenBLAS/lib/libopenblas_haswellp-r0.3.5.dev.so)
==15812==    by 0x4895A9C: start_thread (in /usr/lib/libpthread-2.28.so)
==15812==    by 0x49AAB22: clone (in /usr/lib/libc-2.28.so)
client stack range: [0x749A000 0x7C98FFF] client SP: 0x7C98DF0
valgrind stack range: [0x1006807000 0x1006906FFF] top usage: 5512 of 1048576

Thread 3: status = VgTs_WaitSys syscall 202 (lwpid 15814)
==15812==    at 0x489BAFC: pthread_cond_wait@@GLIBC_2.3.2 (in /usr/lib/libpthread-2.28.so)
==15812==    by 0x64D579A: blas_thread_server (in /opt/OpenBLAS/lib/libopenblas_haswellp-r0.3.5.dev.so)
==15812==    by 0x4895A9C: start_thread (in /usr/lib/libpthread-2.28.so)
==15812==    by 0x49AAB22: clone (in /usr/lib/libc-2.28.so)
client stack range: [0x7C9B000 0x8499FFF] client SP: 0x8499DF0
valgrind stack range: [0x1006D86000 0x1006E85FFF] top usage: 5512 of 1048576

Thread 4: status = VgTs_WaitSys syscall 202 (lwpid 15815)
==15812==    at 0x489BAFC: pthread_cond_wait@@GLIBC_2.3.2 (in /usr/lib/libpthread-2.28.so)
==15812==    by 0x64D579A: blas_thread_server (in /opt/OpenBLAS/lib/libopenblas_haswellp-r0.3.5.dev.so)
==15812==    by 0x4895A9C: start_thread (in /usr/lib/libpthread-2.28.so)
==15812==    by 0x49AAB22: clone (in /usr/lib/libc-2.28.so)
client stack range: [0x849C000 0x8C9AFFF] client SP: 0x8C9ADF0
valgrind stack range: [0x100708A000 0x1007189FFF] top usage: 5512 of 1048576

Thread 5: status = VgTs_WaitSys syscall 7 (lwpid 26975)
==15812==    at 0x499FC21: poll (in /usr/lib/libc-2.28.so)
==15812==    by 0x1A55862F: ??? (in /usr/lib/libxcb.so.1.1.0)
==15812==    by 0x1A55A2DA: xcb_wait_for_event (in /usr/lib/libxcb.so.1.1.0)
==15812==    by 0x1D3CE948: ??? (in /usr/lib/libQt5XcbQpa.so.5.12.1)
==15812==    by 0x16DB096B: ??? (in /usr/lib/libQt5Core.so.5.12.1)
==15812==    by 0x4895A9C: start_thread (in /usr/lib/libpthread-2.28.so)
==15812==    by 0x49AAB22: clone (in /usr/lib/libc-2.28.so)
client stack range: [0x11A40E000 0x11AC0CFFF] client SP: 0x11AC0CD30
valgrind stack range: [0x10ACD6A000 0x10ACE69FFF] top usage: 7704 of 1048576

Thread 6: status = VgTs_WaitSys syscall 7 (lwpid 26976)
==15812==    at 0x499FC21: poll (in /usr/lib/libc-2.28.so)
==15812==    by 0x156A753F: ??? (in /usr/lib/libglib-2.0.so.0.5800.3)
==15812==    by 0x156A762D: g_main_context_iteration (in /usr/lib/libglib-2.0.so.0.5800.3)
==15812==    by 0x156A7681: ??? (in /usr/lib/libglib-2.0.so.0.5800.3)
==15812==    by 0x1568267A: ??? (in /usr/lib/libglib-2.0.so.0.5800.3)
==15812==    by 0x4895A9C: start_thread (in /usr/lib/libpthread-2.28.so)
==15812==    by 0x49AAB22: clone (in /usr/lib/libc-2.28.so)
client stack range: [0x11B30E000 0x11BB0CFFF] client SP: 0x11BB0CE20
valgrind stack range: [0x10AE53A000 0x10AE639FFF] top usage: 2872 of 1048576

Thread 7: status = VgTs_WaitSys syscall 7 (lwpid 26977)
==15812==    at 0x499FC21: poll (in /usr/lib/libc-2.28.so)
==15812==    by 0x156A753F: ??? (in /usr/lib/libglib-2.0.so.0.5800.3)
==15812==    by 0x156A85C1: g_main_loop_run (in /usr/lib/libglib-2.0.so.0.5800.3)
==15812==    by 0x89F29CB7: ??? (in /usr/lib/libgio-2.0.so.0.5800.3)
==15812==    by 0x1568267A: ??? (in /usr/lib/libglib-2.0.so.0.5800.3)
==15812==    by 0x4895A9C: start_thread (in /usr/lib/libpthread-2.28.so)
==15812==    by 0x49AAB22: clone (in /usr/lib/libc-2.28.so)
client stack range: [0x11C359000 0x11CB57FFF] client SP: 0x11CB57E10
valgrind stack range: [0x10AE846000 0x10AE945FFF] top usage: 5224 of 1048576

Thread 8: status = VgTs_WaitSys syscall 7 (lwpid 26978)
==15812==    at 0x499FC21: poll (in /usr/lib/libc-2.28.so)
==15812==    by 0x156A753F: ??? (in /usr/lib/libglib-2.0.so.0.5800.3)
==15812==    by 0x156A762D: g_main_context_iteration (in /usr/lib/libglib-2.0.so.0.5800.3)
==15812==    by 0x16FC2CE8: QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) (in /usr/lib/libQt5Core.so.5.12.1)
==15812==    by 0x16F6BB2B: QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) (in /usr/lib/libQt5Core.so.5.12.1)
==15812==    by 0x16DAF568: QThread::exec() (in /usr/lib/libQt5Core.so.5.12.1)
==15812==    by 0x20990BA5: ??? (in /usr/lib/libQt5DBus.so.5.12.1)
==15812==    by 0x16DB096B: ??? (in /usr/lib/libQt5Core.so.5.12.1)
==15812==    by 0x4895A9C: start_thread (in /usr/lib/libpthread-2.28.so)
==15812==    by 0x49AAB22: clone (in /usr/lib/libc-2.28.so)
client stack range: [0x11D38D000 0x11DB8BFFF] client SP: 0x11DB8BCA0
valgrind stack range: [0x10B0BAB000 0x10B0CAAFFF] top usage: 6216 of 1048576
```

**Comment by linkwithkk** [comment]
Is this an issue in all numpy versions ?
I scanned my code through veracode and it is saying all numpy versions are affected by this.

https://sca.analysiscenter.veracode.com/vulnerability-database/security/sca/vulnerability/sid-21447/summary

**Comment by seberg** [comment]
Honestly, it is seem more likely that this is a problem in scipy sparsetools to begin with, not a problem with NumPy at all.

**Comment by seberg** [comment]
@leondavi can you repost the original reproducer?  This really should be run in valgrind on a version of SciPy with debug symbols.  Otherwise it is super annoying to try to guess what is wrong in SciPy (and yes, since there are errors reported by valgrind originating in SciPy, I do not think this has anything to do with NumPy.)

**Comment by seberg** [comment]
Closing this, back in the day, I was convinced this was a SciPy bug, and with a missing reproducer, there is no point in having an issue anyway.
