### ISSUE TITLE
SparkSubmit Error for Numpy- ImportError: cannot import name 'multiarray'

### ISSUE THREAD

**Issue by stephengeospy** [numpy/numpy#13167]
### Reproducing code example:
```
Running PySpark Job via Oozie workflow and trying to import Python Modules. 
Able to import all other modules except numpy. 
But able to import numpy from Python interpreter in the Master node..

[root@ip-46-44-82 lib]# python
Python 3.6.7 (default, Dec 21 2018, 20:31:01)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-28)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>>

But when ran via oozie, not able to numpy module 
```
### Error message:
Traceback (most recent call last):
  File "/mnt1/yarn/usercache/root/appcache/application_1551299460868_0107/container_1551299460868_0107_01_000001/dependencies.zip/numpy/core/__init__.py", line 16, in <module>
**ImportError: cannot import name 'multiarray'**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt1/yarn/usercache/root/appcache/application_1551299460868_0107/container_1551299460868_0107_01_000001/tsys_option_onelake.py", line 5, in <module>
    import numpy
  File "/mnt1/yarn/usercache/root/appcache/application_1551299460868_0107/container_1551299460868_0107_01_000001/dependencies.zip/numpy/__init__.py", line 142, in <module>
  File "/mnt1/yarn/usercache/root/appcache/application_1551299460868_0107/container_1551299460868_0107_01_000001/dependencies.zip/numpy/add_newdocs.py", line 13, in <module>
  File "/mnt1/yarn/usercache/root/appcache/application_1551299460868_0107/container_1551299460868_0107_01_000001/dependencies.zip/numpy/lib/__init__.py", line 8, in <module>
  File "/mnt1/yarn/usercache/root/appcache/application_1551299460868_0107/container_1551299460868_0107_01_000001/dependencies.zip/numpy/lib/type_check.py", line 11, in <module>
  File "/mnt1/yarn/usercache/root/appcache/application_1551299460868_0107/container_1551299460868_0107_01_000001/dependencies.zip/numpy/core/__init__.py", line 26, in <module>
ImportError:
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

**Original error was: cannot import name 'multiarray'**

### Numpy/Python version information:
Python: 3.6.7
Numpy: 1.14.5

Have tried all major versions of numpy from 1.12 onwards to 1.16.2

These are the other modules that I need as dependencies
[root@ip-46-44-82 venv]# cat requirements.txt
requests==2.21.0
configparser==3.7.3
boto3==1.9.112
botocore==1.12.112
numpy==1.14.5
pyarrow==0.12.1
pandas==0.22.0
datetime==4.3

**Comment by seberg** [comment]
Sorry that nobody ever was able to help you here.  But since this is a 2 year old installation issue, I will close this.  If there may really be something to be done on NumPy, please open a new issue!
