### ISSUE TITLE
rfn.rename_fields fails if arrays constains objects

### ISSUE THREAD

**Issue by rnhmjoj** [numpy/numpy#13213]
### Reproducing code example:
```python
import numpy as np
import numpy.lib.recfunctions as rfn
x = np.array([(None)], dtype=[('a', object)])
rfn.rename_fields(x, {'a': 'A'})
```

### Error message:

```
Traceback (most recent call last):
  File "python3-3.7.2-env/lib/python3.7/site-packages/numpy/lib/recfunctions.py", line 668, in rename_fields
    return base.view(newdtype)
  File "python3-3.7.2-env/lib/python3.7/site-packages/numpy/core/_internal.py", line 494, in _view_is_safe
    raise TypeError("Cannot change data-type for object array.")
TypeError: Cannot change data-type for object array.
```

### Numpy/Python version information:

Numpy: 1.16.1
Python: 3.7.2

**Comment by seberg** [comment]
The nice fix would be fixing `view` which is being used here. The local fix is probably to just use `np.ndarray` instead of view.

**Comment by eric-wieser** [comment]
I think #8514 might be the right approach here
