### ISSUE TITLE
No module named 'numpy.core._multiarray_umath'

### ISSUE THREAD

**Issue by cepbrian** [numpy/numpy#13362]
I get the error above, with the "IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!" text. None of it seems to be relevant.

The thing that's interesting is that I'm running from a virtualenv. When I activate the virtualenv like normal, numpy imports normally. When I import with the activate_this.py, inside python, I get the error above:
```

>>> this_file='win\\CYAN\Scripts\\activate_this.py'
>>> exec(open(this_file).read(), {'__file__': this_file})
>>> import numpy
Traceback (most recent call last):
  File "C:\Dropbox (CEP)\venvs\win\CYAN\Lib\site-packages\numpy\core\__init__.py", line 40, in <module>
    from . import multiarray
  File "C:\Dropbox (CEP)\venvs\win\CYAN\Lib\site-packages\numpy\core\multiarray.py", line 12, in <module>
    from . import overrides
  File "C:\Dropbox (CEP)\venvs\win\CYAN\Lib\site-packages\numpy\core\overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Dropbox (CEP)\venvs\win\CYAN\Lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "C:\Dropbox (CEP)\venvs\win\CYAN\Lib\site-packages\numpy\core\__init__.py", line 71, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

```
etc

I'm using the same python in both cases:
```
>>> sys.executable
'C:\\Python37\\python.exe'
```
which is 64b, in case that matters.

**Comment by cepbrian** [comment]
I see that there are some references from 2015 about numpy not being 64b... I assume that that's dealt with by now, because I've seen no reference to it since then... if I'm wrong, that would be good to know...

**Comment by eric-wieser** [comment]
Some of the output you replaced with "etc" may be useful - in particular, we started inserting information about your system there at some point.

What version of numpy? Did you install with `pip` or `conda`?

**Comment by seberg** [comment]
@cepbrian could you please follow up on the questions? Otherwise we will assume that this was a temporary issue on your side and that you managed to fix it.
