### ISSUE TITLE
ENH: Add methods from the builtin float types to the numpy floating point types

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#13375]
Asking for methods that exist on builtin float types but not numpy types gives:
```python
>>> set(dir(float)) - set(dir(np.float32))
{'__getformat__',
 '__getnewargs__',
 '__setformat__',
 '__trunc__',
 'as_integer_ratio',
 'fromhex',
 'hex',
 'is_integer'}
```

Filtering these to the ones that are not CPython implementation details, we have:
* [ ] `__trunc__(self) -> int`, which will enable `math.trunc(numpy_float)` (https://github.com/numpy/numpy/pull/28949)
* [x] `is_integer(self) -> bool` (done in #19803)
* [x] `as_integer_ratio(self) -> Tuple[int, int]` (done in #10741)
* [ ] `hex(self) -> str` (https://github.com/numpy/numpy/pull/20083)
* [ ] `fromhex(cls: Type[FloatType], s: str) -> FloatType` (https://github.com/numpy/numpy/pull/20083)
* [ ] `from_number(cls:Type[FloatType], number: NumberLike:, /) -> FloatType` (https://github.com/numpy/numpy/pull/29077)

For all of these, the best approach is probably to port the CPython implementations, taking care to handle the extended precision of `long double`s.

Note that we get these methods for free on `np.float64` due to inheriting from `float`

**Comment by eric-wieser** [comment]
Cpython has `int.is_integer` now, so we might want to add is_integer on all `np.number` subclasses.

**Comment by mingwugmail** [comment]
Need to fix for all the np float types: np.float32, numpy.float16 / np.single, np.half:

```
$ python
Python 3.6.7 |Anaconda, Inc.| (default, Oct 23 2018, 19:16:44) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> a=np.array([1,2,3], dtype=np.float32)
>>> a[0].is_integer()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'numpy.float32' object has no attribute 'is_integer'

>>> a=np.array([1,2,3], dtype=np.half)
>>> type(a[0])
<class 'numpy.float16'>
>>> a[0].is_integer()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'numpy.float16' object has no attribute 'is_integer'

>>> np.__version__
'1.19.4'
```

**Comment by BvB93** [comment]
I think we can also add `__ceil__` to the list.

**Comment by BvB93** [comment]
With the merging of https://github.com/numpy/numpy/pull/19803 `is_integer` can be crossed off the list.

**Comment by ganesh-k13** [comment]
I'll take a stab at `hex` and `fromhex` by referring to https://github.com/python/cpython/commit/65fe25e59710eada7eb41bddb45bdca8b61b5668

**Comment by ganesh-k13** [comment]
Thanks for the heads up @mdickinson!

**Comment by jorenham** [comment]
Python 3.14 also adds a [`float.from_number`](https://docs.python.org/3.14/library/stdtypes.html#float.from_number), fyi.

**Comment by jorenham** [comment]
There are also similar duck-type incompatibility issues for `int`, `bool`, and `complex`, and `datetime.timedelta`. But apparently of `str` and `bytes` are already duck-type compatible (in  terms of the *presence* of method and properties, that is).

<table>
<tr>
<th><code>a = set(dir(_))</code></td>
<th><code>b = set(dir(_))</code></td>
<th><code>a - b</td>
</tr>
<tr>
<td><code>bool</code></td>
<td><code>np.bool</code></td>
<td>

- `__ceil__`
- `__floor__`
- `__round__`
- `__trunc__`
- `__index__`
- `__getnewargs__`
- `as_integer_ratio`
- `is_integer`
- `bit_count`
- `bit_length`
- `numerator`
- `denominator`
- `from_bytes`
- `to_bytes`

</td>
</tr>
<tr><td colspan=3></td></tr>
<tr>
<td><code>int</code></td>
<td><code>np.int8</code></td>
<td>

- `__ceil__`
- `__floor__`
- `__trunc__`
- `__getnewargs__`
- `as_integer_ratio`
- `bit_length`
- `from_bytes`
- `to_bytes`

</td>
</tr>
<tr><td colspan=3></td></tr>
<tr>
<td><code>float</code></td>
<td><code>np.float32</code></td>
<td>

- `__ceil__`
- `__floor__`
- `__trunc__`
- `__getformat__`
- `__getnewargs__`
- `from_number`
- `fromhex`
- `hex`

</td>
</tr>
<tr><td colspan=3></td></tr>
<tr>
<td><code>complex</code></td>
<td><code>np.complex64</code></td>
<td>

- `__getnewargs__`
- `from_number`

</td>
</tr>
<tr><td colspan=3></td></tr>
<tr>
<td><code>datetime.timedelta</code></td>
<td><code>np.timedelta64</code></td>
<td>

- `microseconds`
- `seconds`
- `total_seconds`
- `days`
- `resolution`

</td>
</tr>
<tr><td colspan=3></td></tr>
<tr>
<td><code>bytes</code></td>
<td><code>np.bytes_</code></td>
<td align="center">∅</td>
</tr>
<tr><td colspan=3></td></tr>
<tr>
<td><code>str</code></td>
<td><code>np.str_</code></td>
<td align="center">∅</td>
</tr>
</table>

I'm not sure if we should worry about `__getnewargs__` and `__getformat__`, but the other (currently missing) method/properties seem useful.
