### ISSUE TITLE
(yet another) No module named 'numpy.core._multiarray_umath'

### ISSUE THREAD

**Issue by mohummedalee** [numpy/numpy#13411]
### Reproducing code example:

``` $ python3
>> import numpy as np
```

### Error message:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/numpy/core/__init__.py", line 40, in <module>
    from . import multiarray
  File "/usr/local/lib/python3.7/site-packages/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/usr/local/lib/python3.7/site-packages/numpy/core/overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/usr/local/lib/python3.7/site-packages/numpy/core/__init__.py", line 71, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
Here is how to proceed:
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
- If you are simply trying to use the numpy version that you have installed:
  your installation is broken - please reinstall numpy.
- If you have already reinstalled and that did not fix the problem, then:
  1. Check that you are using the Python you expect (you're using /usr/local/bin/python3),
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy versions you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

     Note: this error has many possible causes, so please don't comment on
     an existing issue about this - open a new one instead.

Original error was: No module named 'numpy.core._multiarray_umath'

### Numpy/Python version information:
```
$ pip3 show numpy
Name: numpy
Version: 1.16.3
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: None
License: BSD
Location: /usr/local/lib/python3.7/site-packages
Requires:
Required-by: pyarrow, pandas, matplotlib, imageio
```

`sys.version`: '3.6.1 (v3.6.1:69c0db5050, Mar 21 2017, 01:21:04) \n[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]'

This is _the only_ numpy that I've installed myself with pip. There is another copy somewhere in `/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy` but that is required by MacOS. I have tried uninstalling dozens of times, hunted around the system for older versions that might be being imported – absolutely everything. Completely losing my mind right now.

**Comment by mohummedalee** [comment]
As expected, there were path problems. Uninstalled all numpy, all Python on the system, reinstalled Python 3.7 (was using 3.6 earlier despite installing to the 3.7 directory), reinstalled the latest numpy. Everything works now.
