### ISSUE TITLE
fromfile/tofile not working as expected with gzip file as input

### ISSUE THREAD

**Issue by mpenkov** [numpy/numpy#13470]
When the numpy.fromfile and numpy.tofile receive file-like gzip.GzipFile objects as input, they behave unexpectedly:

- tofile leaves the output mangled
- fromfile reads incorrect or incomplete data

### Reproducing code example:

```python
import argparse
import gzip
import io
import os
import os.path as P

import numpy as np

MAGIC_STRING = b'the quick brown fox jumps over the lazy dog'
MATRIX = np.matrix(list(range(10)), dtype=np.dtype('float32'))
TMP_FILE = 'reproduce.dat'


def read_matrix(fin):
    mat = np.fromfile(fin, dtype=np.dtype('float32'), count=MATRIX.size)
    print('expected: %r' % MATRIX)
    print('actual: %r' % mat)


def write_matrix(mat, fout):
    mat.tofile(fout)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--gz', action='store_true', help='enable gzip compression')
    parser.add_argument('--clean', action='store_true', help='delete temporary files')
    args = parser.parse_args()

    open_function = gzip.GzipFile if args.gz else io.open

    if args.clean and P.isfile(TMP_FILE):
        os.unlink(TMP_FILE)

    if not P.isfile(TMP_FILE):
        with open_function(TMP_FILE, 'wb') as fout:
            fout.write(MAGIC_STRING)
            write_matrix(MATRIX, fout)

    with open_function(TMP_FILE, 'rb') as fin:
        print(fin.read(len(MAGIC_STRING)))
        read_matrix(fin)


if __name__ == '__main__':
    main()
```

The above does the following:

- Write a byte string followed by a matrix (using tofile) to a temporary file
- Read back the contents of the temporary file

An example session:

```
(372.env) mpenkov@hetrad2:~/data/2473$ python reproduce.py --clean  # working with ordinary io.open streams
b'the quick brown fox jumps over the lazy dog'
expected: matrix([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]], dtype=float32)
actual: array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)
$ python reproduce.py --clean --gz  # broken, tofile produces garbage
Traceback (most recent call last):
  File "reproduce.py", line 46, in <module>
    main()
  File "reproduce.py", line 41, in main
    print(fin.read(len(MAGIC_STRING)))
  File "/usr/lib/python3.5/gzip.py", line 274, in read
    return self._buffer.read(size)
  File "/usr/lib/python3.5/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/usr/lib/python3.5/gzip.py", line 469, in read
    uncompress = self._decompressor.decompress(buf, size)
zlib.error: Error -3 while decompressing data: invalid stored block lengths
$ python reproduce.py --clean  # work around the above problem
b'the quick brown fox jumps over the lazy dog'
expected: matrix([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]], dtype=float32)
actual: array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)
$ gzip reproduce.dat
$ mv reproduce.dat{.gz,}
$ python reproduce.py --gz  # illustrate broken fromfile
b'the quick brown fox jumps over the lazy dog'
expected: matrix([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]], dtype=float32)
actual: array([-1.7907840e+08, -2.1929670e+05,  1.8607268e+11, -9.5393936e+23,
        1.8948086e-13,  7.8181330e-08,  6.4089775e-02,  1.7406825e-18,
       -5.9227965e+20,  1.1410567e-38], dtype=float32)
```
### Error message:

A failed tofile causes fromfile to fail with the following exception (see above):

```
Traceback (most recent call last):
  File "reproduce.py", line 46, in <module>
    main()
  File "reproduce.py", line 41, in main
    print(fin.read(len(MAGIC_STRING)))
  File "/usr/lib/python3.5/gzip.py", line 274, in read
    return self._buffer.read(size)
  File "/usr/lib/python3.5/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/usr/lib/python3.5/gzip.py", line 469, in read
    uncompress = self._decompressor.decompress(buf, size)
zlib.error: Error -3 while decompressing data: invalid stored block lengths
```

A failed fromfile causes unexpected values in the resulting matrix.

### Numpy/Python version information:

```python
>>> import sys, numpy; print(numpy.__version__, sys.version)
1.16.2 3.5.2 (default, Sep 14 2017, 22:51:06) 
[GCC 5.4.0 20160609]
```

### See Also

https://github.com/RaRe-Technologies/gensim/issues/2473 for a real-world example of this bug.

**Comment by skoehler** [comment]
tofile/fromfile seem to bypass all python I/O layers, probably to improve performance. So data will not be compressed or uncompressed. I have implemented my own workaround using tobytes/frombuffer. Numpy should at least check whether it can safely bypass the I/O layers before doing so. If it's not safe, numpy should resort to some alternate approach.

Here's an example of how numpy.tofile overwrites the first 5 bytes of the gzip file. The gzip headers seems to be already present and is already in the file when the header is partially overwritten.

````
import numpy as np
import gzip
d = np.array([0,1,2,3,4], dtype=np.int8)
with gzip.open("test.bin", "wb") as f:
    d.tofile(f)
````
