### ISSUE TITLE
BUG: wrong handling of empty generators

### ISSUE THREAD

**Issue by danielhrisca** [numpy/numpy#13521]
When empty generators are feed to numpy functions they break in multiple ways

### Reproducing code example:

```python
import numpy as np
from traceback import format_exc

for func in (np.amax, np.sin, np.abs):
    try:
        x = func(e for e in [])
        if np.all(x > 3):
            pass
    except:
        print(format_exc())
```

### Error message:

```
Traceback (most recent call last):
  File "untitled0.py", line 7, in <module>
    if np.all(x>3):
TypeError: '>' not supported between instances of 'generator' and 'int'

Traceback (most recent call last):
  File "untitled0.py", line 6, in <module>
    x = func(e for e in [])
AttributeError: 'generator' object has no attribute 'sin'

Traceback (most recent call last):
  File "untitled0.py", line 6, in <module>
    x = func(e for e in [])
TypeError: bad operand type for abs(): 'generator'
```

### Numpy/Python version information:

``1.16.2 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 23:09:28) [MSC v.1916 64 bit (AMD64)]``

**Comment by shoyer** [comment]
In general, NumPy doesn't support operations with generators. So all of these operations should be raising informative errors.

`amax` does seem to be doing something bad: it should raise an exception instead returning a generator object:
```
In [4]: np.amax((1 for x in range(0)))
Out[4]: <generator object <genexpr> at 0x110c1ec00>
```

The error message on `np.sin` looks pretty reasonable:
```
In [7]: np.sin((1 for x in range(0)))
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
AttributeError: 'generator' object has no attribute 'sin'

The above exception was the direct cause of the following exception:

TypeError                                 Traceback (most recent call last)
<ipython-input-7-8f63860cda5b> in <module>
----> 1 np.sin((1 for x in range(0)))

TypeError: loop of ufunc does not support argument 0 of type generator which has no callable sin method
```

The error message for `abs()` also looks appropriate to me.

**Comment by seberg** [comment]
Closing this, there are a few other issues about how generators are dealt with.  But empty generators are not special.
