### ISSUE TITLE
Mac Os python 2.7.16 ucs4 conflicts

### ISSUE THREAD

**Issue by dlemke01** [numpy/numpy#13540]
Hi,
I'm upgrading python to 2.7.16 on a mac with a system default of 2.7.10.  Furthermore, I need a wide build of python for the project I'm working on, as there is an app that requires it, dying in an assert fail if it is not present.  I used mac ports to do the install:
```bash
port install python27 +ucs4
port install py27-numpy
```
### Reproducing code example:

```python
import numpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/__init__.py", line 71, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
Here is how to proceed:
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
- If you are simply trying to use the numpy version that you have installed:
  your installation is broken - please reinstall numpy.
- If you have already reinstalled and that did not fix the problem, then:
  1. Check that you are using the Python you expect (you're using /opt/local/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python),
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy versions you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

     Note: this error has many possible causes, so please don't comment on
     an existing issue about this - open a new one instead.

Original error was: dlopen(/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/_multiarray_umath.so, 2): Symbol not found: _PyUnicodeUCS2_AsASCIIString
  Referenced from: /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/_multiarray_umath.so
  Expected in: flat namespace
 in /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/_multiarray_umath.so

```
```bash
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/_multiarray_umath.so
```
This is the directory on the path of the updated python 2.7.16 +ucs4 build, which I would have expected to be the correct one, built of the ucs4 build. Yet it seems that this version is to be checking for a usc2 flag: _PyUnicodeUCS2_AsASCIIString.

**Comment by eric-wieser** [comment]
It looks like you have ended up with a version of numpy built against UCS 2. Does `port` build from source, and if not, is it aware that it needs a different numpy binary if you've asked for a ucs4 python?

**Comment by dlemke01** [comment]
It must not be, I removed macports entirely and built python from source with 

```bash
./configure --enable-unicode=ucs4
```
and verified the unicode is correct.  I can't use the new pip that is not inside usr/local/bin to install numpy as it due to the following conflict:
```bash
pip install numpy
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Requirement already satisfied: numpy in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (1.8.0rc1)
``` 
I will try to build numpy from source and see if that works.  Is there a similar flag to pass for ucs4?

**Comment by eric-wieser** [comment]
I think numpy just consumes the installed python headers, which indicate which Unicode mode is being used.

**Comment by dlemke01** [comment]
Ok this seems to have worked, the sequence of steps was:

- build python 2.7.16 from source into /usr/local and with option 
```bash
--enable-unicode=ucs4
```
and verify it's default python and verify max unicode.

- pip uninstall all possible versions of numpy, as far as you can go, for me this is until the only version is the system version installed with dist-utils
- build numpy from source and install locally with
```bash
python setup.py build_ext --inplace
```
- copy local numpy to /usr/local/lib/python2.7/site-packages

which should be in the path by default of the new build.
