### ISSUE TITLE
Original error was: No module named 'numpy.core._multiarray_umath'

### ISSUE THREAD

**Issue by MaxCCC** [numpy/numpy#13662]
Info:
```

python3.7 --version
Python 3.7.1
pip3 --version
pip 9.0.3 from /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (python 3.7)
```

Steps to reproduce:

```
$ mkdir deps
$ cd deps
$ virtualenv .
Using base prefix '/Library/Frameworks/Python.framework/Versions/3.7'
New python executable in /Users/xxx/deps/bin/python3.7
Also creating executable in /Users/xxx/deps/bin/python
Installing setuptools, pip, wheel...
done.
$ bin/pip3.7 install --no-cache-dir -t $PWD/unpacked numpy --upgrade
Collecting numpy
  Downloading https://files.pythonhosted.org/packages/6b/be/608b7f72b851472388eafc010a5d46dae5d41610d0ac5df4c98c2ed1b865/numpy-1.16.4-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (13.9MB)
     |████████████████████████████████| 13.9MB 1.9MB/s
Installing collected packages: numpy
Successfully installed numpy-1.16.4
$ cd unpacked
$ zip -r9 ../library.zip *
  adding: bin/ (stored 0%)
  adding: bin/f2py (deflated 25%)
  adding: bin/f2py3.7 (deflated 25%)
  adding: bin/f2py3 (deflated 25%)
  adding: numpy/ (stored 0%)
  adding: numpy/distutils/ (stored 0%)
  adding: numpy/distutils/unixccompiler.py (deflated 63%)
  adding: numpy/distutils/numpy_distribution.py (deflated 51%)
  adding: numpy/distutils/conv_template.py (deflated 65%)
  adding: numpy/distutils/cpuinfo.py (deflated 81%)
  adding: numpy/distutils/ccompiler.py (deflated 71%)
  adding: numpy/distutils/msvc9compiler.py (deflated 60%)
  adding: numpy/distutils/npy_pkg_config.py (deflated 70%)
  adding: numpy/distutils/compat.py (deflated 26%)
  adding: numpy/distutils/misc_util.py (deflated 76%)
  adding: numpy/distutils/log.py (deflated 64%)
  adding: numpy/distutils/line_endings.py (deflated 73%)
  adding: numpy/distutils/lib2def.py (deflated 63%)
...
$ cd ..
$ ls
bin         include     lib         library.zip unpacked
$ PYTHONPATH=library.zip python3.7
Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 03:13:28)
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
Traceback (most recent call last):
  File "/Users/xxx/deps/library.zip/numpy/core/__init__.py", line 40, in <module>
  File "/Users/xxx/deps/library.zip/numpy/core/multiarray.py", line 12, in <module>
  File "/Users/xxx/deps/library.zip/numpy/core/overrides.py", line 6, in <module>
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/xxx/deps/library.zip/numpy/__init__.py", line 142, in <module>
  File "/Users/xxx/deps/library.zip/numpy/core/__init__.py", line 71, in <module>
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
Here is how to proceed:
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
- If you are simply trying to use the numpy version that you have installed:
  your installation is broken - please reinstall numpy.
- If you have already reinstalled and that did not fix the problem, then:
  1. Check that you are using the Python you expect (you're using /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7),
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy versions you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

     Note: this error has many possible causes, so please don't comment on
     an existing issue about this - open a new one instead.

Original error was: No module named 'numpy.core._multiarray_umath'
>>>
```

For other packages this seems to work. I tried to install a different version + I tried to install numpy with pandas but the same issue persists.

**Comment by mattip** [comment]
When you say "for other packages this seems to work" - do any of them have c-extension modules?

While pure-python packages can be found and imported from a zip archive, there is no such support for c-extension modules. They must be loaded by the OS runtime, which does not know how to look inside a zip file. PyInstaller, py2exe, and others all have this problem as well, you might want to take a look at how they solve this problem.

**Comment by mattip** [comment]
Closing, this is an unsupported use case. Please reopen if you find numpy works differently from other c-extension packages.
