### ISSUE TITLE
shape parameter in lib.format.open_memmap is allowed non-tuple but causes errors

### ISSUE THREAD

**Issue by Gattocrucco** [numpy/numpy#13719]
If I pass an integer as `shape` parameter to `numpy.lib.format.open_memmap` I expect it to create a 1D array, and so it happens. But when I try to load back the file, it is corrupted.

I think that `open_memmap` shall either raise an error on shape not being a tuple of integers or sanitize it.

### Reproducing code example:

```python
import numpy as np
from numpy.lib import format as nplf
a = nplf.open_memmap('test.npy', shape=10, dtype=float, mode='w+')
del a
b = np.load('test.npy') # Fails
```

### Error message:

```
Traceback (most recent call last):
  File "script.py", line 9, in <module>
    b = np.load('test.npy')
  File "/Users/giacomo/Documents/Programmi/python3_virtualenv/lib/python3.6/site-packages/numpy/lib/npyio.py", line 447, in load
    pickle_kwargs=pickle_kwargs)
  File "/Users/giacomo/Documents/Programmi/python3_virtualenv/lib/python3.6/site-packages/numpy/lib/format.py", line 686, in read_array
    shape, fortran_order, dtype = _read_array_header(fp, version)
  File "/Users/giacomo/Documents/Programmi/python3_virtualenv/lib/python3.6/site-packages/numpy/lib/format.py", line 562, in _read_array_header
    raise ValueError(msg.format(d['shape']))
ValueError: shape is not valid: 10
```

### Numpy/Python version information:

```
1.16.4 3.6.4 (v3.6.4:d48ecebad5, Dec 18 2017, 21:07:28) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
```

**Comment by eric-wieser** [comment]
I wonder whether we need to fix `np.load` to understand this corrupt format to. I'd lean towards not doing so.
