### ISSUE TITLE
matmul error with single dimensional data frames

### ISSUE THREAD

**Issue by nate-bryant** [numpy/numpy#13712]
I'm running into an error using matmul with single dimension pandas data frames. The below code worked as expected in 1.15.4 but after I upgraded to 1.16.3 I get the below error message. matmul works if I convert the data frames to numpy arrays but could previously handle the data frames.
### Reproducing code example:

```python
import pandas as pd
import numpy as np

d = {'col1': [0.0037448, -0.002455324, 0.003062666, 0.000768503, 0.002309015]}
df = pd.DataFrame(data=d)
dfT = df.T

np.matmul(dfT, df)
```

### Error message:

```
Traceback (most recent call last):
  File "MatmulBugTest.py", line 8, in <module>
    np.matmul(dfT, df)
  File "C:\Users\bryant_n\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\generic.py", line 1909, in __array_wrap__
    return self._constructor(result, **d).__finalize__(self)
  File "C:\Users\bryant_n\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\frame.py", line 424, in __init__
    copy=copy)
  File "C:\Users\bryant_n\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\internals\construction.py", line 167, in init_ndarray
    return create_block_manager_from_blocks([values], [columns, index])
  File "C:\Users\bryant_n\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\internals\managers.py", line 1660, in create_block_manager_from_blocks
    construction_error(tot_items, blocks[0].shape[1:], axes, e)
  File "C:\Users\bryant_n\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\internals\managers.py", line 1691, in construction_error
    passed, implied))
ValueError: Shape of passed values is (1, 1), indices imply (1, 5)
```

### Numpy/Python version information:
1.16.3 3.7.0 (default, Jun 28 2018, 08:04:48) [MSC v.1912 64 bit (AMD64)]

**Comment by seberg** [comment]
This is with the same version of pandas I assume? From a first point, I am not sure what should have changed in this regard in numpy. The (1, 1) is the correct result, and `(1, 5)` is the shape of the "wrapping" array, which I guess is what should be happening?

**Comment by nate-bryant** [comment]
Yes, it is with the same version of pandas. The result should be the (1, 1), in this example it should be something like this: ```array([[3.53542131e-05]])```. That's the answer I got with 1.15.4.

**Comment by shoyer** [comment]
This will need to be fixed in pandas, in particular their implementation of `DataFrame.__array_ufunc__` needs to handle `np.matmul`. Right now the `__array_ufunc__` method in pandas probably only handles scalar arithmetic.

**Comment by nate-bryant** [comment]
Thanks. I can raise the issue with pandas, but I'm just wondering why this issue would only occur after updating numpy if it is a pandas issue? ```np.matmul``` worked correctly for this use case with DataFrames when using pandas 0.24.2 and numpy 1.15.4 but I get an error message with pandas 0.24.2 and numpy 1.16.3

**Comment by shoyer** [comment]
I'm not sure the backwards compatibility implications were fully realized, but this was due to NumPy making `np.matmul` a ufunc in 1.16.

**Comment by mattip** [comment]
I tried putting breakpoints in all the `__array_ufunc__` methods in pandas, and another just before the call to `self._constructor` in [`NDFRame.__array_wrap__`](https://github.com/pandas-dev/pandas/blob/68dd97931c364b2ce281c3ad124de21dbb6efe72/pandas/core/generic.py#L1941). The latter is hit in numpy 1.17 but not in numpy 1.15.4. The call to `__array_wrap__` comes from `ufunc_generic_call` after the ufunc returns. No `__array_ufunc__` call is hit (unless I missed one).

**Comment by mattip** [comment]
previous comment needs reworking, my test of numpy 1.15.4 was faulty

**Comment by mattip** [comment]
no, it was fine. The analysis holds: `__array_wrap__` was not being called in 1.15.4

**Comment by shoyer** [comment]
Huh... why do we call `__array_wrap__` from `np.matmul`? I guess it comes from how we made matmul a ufunc....

**Comment by mattip** [comment]
Should we have been calling `__array_wrap__` in the pre-ufunc `matmul`? In any case, the problem is that we are calling `__array_wrap__` on the output 1x1 result with `self` set to one of the inputs. I think the bug is in `_find_array_wrap`. We should be able to write a test that reproduces this behavior without pandas, like in #13663

**Comment by eric-wieser** [comment]
My guess would be that `__array_wrap__` is working as documented, but this is the first time we've exposed it to a `gufunc`. pandas should be able to fix this by downcasting to array if `ufunc.signature is not None`

**Comment by mattip** [comment]
The `pandas.DataFrame` object `df`has its own`df. __matmul__` function (which calls `df.dot`) so you can use either `df.dot(dfT)` or `df @ dfT` which both work. Otherwise pandas should rework the `__array_wrap__(self, result, **kwargs)` function to take into account the shape of `self` and `result` could be different

**Comment by mattip** [comment]
I removed the `regression` tag and added the `Close?` tag. I could be convinced otherwise, but this seems like a pandas issue with `__array_wrap__`.

**Comment by charris** [comment]
Going to close this, it is old, stale, and questionable :)
