### ISSUE TITLE
Should numpy.hstack add an axis to an array missing the last one?

### ISSUE THREAD

**Issue by yashjakhotiya** [numpy/numpy#13731]
For an array that has same dimension lengths as other arrays except that it misses a last dimension, instead of throwing a ValueError, can we add an axis to it at the end with a Data Conversion Warning and proceed when using numpy.hstack?

This helps in the case of stacking a 1-D array to an existing matrix.  

### Reproducing code example:

```python
import numpy as np
matrix = np.array([[1, 4], [2, 5], [3, 6]])
one_d_array = np.array([7, 8, 9])
print(np.hstack((matrix, one_d_array)))
```

### Error message:
Traceback (most recent call last):
  File "stack_vectors_and_1d_array.py", line 4, in <module>
    print(np.hstack((matrix, one_d_array)))
  File "/usr/local/python/python-3.7/std/lib64/python3.7/site-packages/numpy/core/shape_base.py", line 288, in hstack
    return _nx.concatenate(arrs, 1)
ValueError: all the input arrays must have same number of dimensions

### Desired Output:
Data Conversion Warning : Reshaping array 'one_d_array' of shape (3,) to shape (3, 1)
array([[1, 4, 7],
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[2, 5, 8],
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[3, 6, 9]])

### Numpy/Python version information:
1.14.3 3.7.3 (default, Apr  9 2019, 18:48:27)
[GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]

Similarly in np.vstack, for an array matching all dimension lengths except that it misses the first one, can we reshape it to (1, -1) with a Data Conversion Warning?

**Comment by mhvk** [comment]
@yashjakhotiya - I don't think we easily can, because e.g., `vstack` already allows adding a `1` in front of the shape for a 1-dimensional array, and it would be confusing to go both ways. Inserting a `1` at the end also is the reverse of the assumption underlying all of numpy, that broadcasting allows arbitrary `1` *before* the present shape.

In this respect, I think one possible thing that might be OK to allow is:
```
np.hstack(([[1, 4], [2, 5], [3, 6]], [7,8]))
# let's assume broadcasting so that this is equivalent to
np.hstack(([[1, 4], [2, 5], [3, 6]], [[7,8]]*3))
array([[1, 4, 7, 8],
       [2, 5, 7, 8],
       [3, 6, 7, 8]])
```
(But even this I think is unlikely to fly!)

**Comment by yashjakhotiya** [comment]
It is true that generalizing the reshaping from 1_d to 2_d, which `vstack` does, to (n-1)_d to n_d is tough to do.

About `hstack`, if the assumption underlying all of numpy is that broadcasting allows arbitary `1` _before_ the present shape, then it won't be wise to have `hstack` reshape 1-d arrays to (-1, 1), as you said.

Although this brings consistency, it breaks the symmetry between `vstack` and `hstack` that might seem intuitive to some. `vstack` stacks 1_d arrays vertically, `hstack` _could have_ stacked them horizontally.

**Comment by homocomputeris** [comment]
I've also been confused by this behaviour of `hstack` and `vstack`.
If a vector's length matches the number of columns in an array, then they can be `vstack`ed. But they cannot be `hstack`ed it the length matches the number of rows.
