### ISSUE TITLE
ENH: Support comma decimal separator in loadtxt

### ISSUE THREAD

**Issue by jakobjakobson13** [numpy/numpy#13810]
### Reproducing code example:
Given that you have data in the following file `test_data.csv`:
```csv
0,1   0,2
0,3   0,4
```
`np.loadtxt` can't load the data directly as it does not support a comma as a decimal separator 
```python3
import numpy as np
np.loadtxt("test_data.csv")
```
### Error message:
```bash
ValueError: could not convert string to float: b'0,1'
```

### Background for this feature request
Many European countries use a comma as a decimal separator (see [https://en.wikipedia.org/wiki/Decimal_separator](https://en.wikipedia.org/wiki/Decimal_separator)). So if a user from that country has a computer with local language setting, LibreOffice and other software (that respects the local language settings) will save/export numerical data with a comma instead of a point as a digit separator.

To make live easier for them an option to switch between a dot and a comma for the decimal separator would be great. Thanks

**Comment by mhvk** [comment]
@jakobjakobson13 - would definitely be good to have. Ideally, we just use python features to support the locale settings. Does `float("1,3")` would in python itself (assuming your locale is set correctly)?

**Comment by jakobjakobson13** [comment]
Wel, if you want to use the python included `locale`module, you can do this
```python
>>> import locale
>>> locale.getlocale() # locale is set to de_DE which has in principle a comma as a decimal separator
('de_DE', 'UTF-8')
>>> locale.getlocale(locale.LC_NUMERIC) # but the LC_NUMERIC is not set
(None, None)
>>> locale.localeconv() # therefore the standard point is set as a decimal separator
{'int_curr_symbol': '', 'currency_symbol': '', 'mon_decimal_point': '', 'mon_thousands_sep': '', 'mon_grouping': [], 'positive_sign': '', 'negative_sign': '', 'int_frac_digits': 127, 'frac_digits': 127, 'p_cs_precedes': 127, 'p_sep_by_space': 127, 'n_cs_precedes': 127, 'n_sep_by_space': 127, 'p_sign_posn': 127, 'n_sign_posn': 127, 'decimal_point': '.', 'thousands_sep': '', 'grouping': []}
>>> locale.atof("3,14") # and the conversion does not work
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/locale.py", line 321, in atof
    return func(delocalize(string))
ValueError: could not convert string to float: '3,14'

>>> locale.setlocale(locale.LC_NUMERIC, "de_DE.UTF-8") # by setting the LC_NUMERIC manually
'de_DE.UTF-8'
>>> locale.localeconv() # the comma is set as the decimal separator
{'int_curr_symbol': '', 'currency_symbol': '', 'mon_decimal_point': '', 'mon_thousands_sep': '', 'mon_grouping': [], 'positive_sign': '', 'negative_sign': '', 'int_frac_digits': 127, 'frac_digits': 127, 'p_cs_precedes': 127, 'p_sep_by_space': 127, 'n_cs_precedes': 127, 'n_sep_by_space': 127, 'p_sign_posn': 127, 'n_sign_posn': 127, 'decimal_point': ',', 'thousands_sep': '.', 'grouping': [3, 3, 0]}
>>> locale.atof("3,14") # and the conversion of the number works
3.14
```

However, as you can see the numeric locale is not set on my python system, even though it is set in the bash:
```bash
$ locale
LANG=de_DE.UTF-8
LANGUAGE=
LC_CTYPE="de_DE.UTF-8"
LC_NUMERIC="de_DE.UTF-8"
LC_TIME="de_DE.UTF-8"
LC_COLLATE="de_DE.UTF-8"
LC_MONETARY="de_DE.UTF-8"
LC_MESSAGES="de_DE.UTF-8"
LC_PAPER="de_DE.UTF-8"
LC_NAME="de_DE.UTF-8"
LC_ADDRESS="de_DE.UTF-8"
LC_TELEPHONE="de_DE.UTF-8"
LC_MEASUREMENT="de_DE.UTF-8"
LC_IDENTIFICATION="de_DE.UTF-8"
LC_ALL=
```

So at least at my PC (Ubuntu 18.04, German) Python does not read the LC_NUMERIC from the bash and therefore there it seems that there is no automatic way to adapt the parsing process to the local number conventions. And I don't know how other Linux distros/Windows/Macs handel the locales.

But to switch the topic: [Pandas](http://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html) has already the feature I asked for, so perhaps you could take some inspiration from them.

**Comment by jakobjakobson13** [comment]
But on seconds thoughts I would strongyly advise against a data parsing function that's routine is dependent on local language settings. Most people are unaware of those settings and in the end I as a German could not follow an English tutorial as my loadtxt function would throw an error even though the the code is the same.

So in the end another parameter like `decimal` is needed.

**Comment by mhvk** [comment]
I agree that we cannot and should not change the default for loading numbers ignoring the locale. But I'd much rather have an option `use_locale=True` or `locale=...` than a `decimal='[.,]'` - we might as well cover every language in one go! It also avoids having to write our own parsing code.

This may in fact work better with the implementation: internally, it uses conversion functions, which can be overridden with  `converters`, which take strings and output the number - one could imagine just inserting `locale.atof` might work even now (though annoyingly it seems one needs to know the number of columns beforehand).

**Comment by jakobjakobson13** [comment]
> I agree that we cannot and should not change the default for loading numbers ignoring the locale. But I'd much rather have an option `use_locale=True` or `locale=...` than a `decimal='[.,]'` - we might as well cover every language in one go! It also avoids having to write our own parsing code.

One possible parsing code is the following:
```python3
>>> import numpy as np
>>> import io
>>> a = "0,1\n0,2\n"
>>> np.loadtxt(io.StringIO(a), converters = {0: lambda s: float(s.decode("UTF-8").replace(",", "."))})
array([ 0.1,  0.2])
```

> This may in fact work better with the implementation: internally, it uses conversion functions, which can be overridden with converters, which take strings and output the number - one could imagine just inserting locale.atof might work even now (though annoyingly it seems one needs to know the number of columns beforehand).

Using the locale.atof function would result in:
```python3
>>> import numpy as np
>>> import io
>>> import locale
>>> locale.setlocale(locale.LC_NUMERIC, 'de_DE')
>>> a = "0,1\n0,2\n"
>>> np.loadtxt(io.StringIO(a), converters = {0: lambda s: locale.atof(s.decode("UTF-8"))})
array([ 0.1,  0.2])
```

I don't know what's easier to implement in the function itself, I guess I leave that up to you guys.

**Comment by mhvk** [comment]
Thanks for trying that out!  One can even remove the UFT8 part by passing in `encoding='UTF-8'`. 

Anyway, as for implementation, I think even just having your locale example in the docstring would be a nice improvement; would you have time do make a PR for that?

For an actual implementation, looking at the code in `numpy/lib/npyio.py`, I think a good starting point would be to ensure [`_getconv`](https://github.com/numpy/numpy/blob/master/numpy/lib/npyio.py#L774) has an option for being locale-aware (or has a locale-aware alternative).

I don't think this will be hugely difficult, but also not a small effort, with the writing of documentation and tests that check all the corner cases (and doing the same for `genfromtxt`...). I've hence labelled it as "intermediate" difficulty. 

Let me also ping @eric-wieser and @juliantaylor as the ones who last made major changes, to see whether they have alternative suggestions.

**Comment by jakobjakobson13** [comment]
I'll try to look into it as soon as you @eric-wieser , @juliantaylor and @mhvk will come to a decision.

**Comment by jakobjakobson13** [comment]
Well, the `locale` (`/usr/lib/python3.6/locale.py`) function is actually quite easy:

```python3
def delocalize(string):
    "Parses a string as a normalized number according to the locale settings."

    conv = localeconv()

    #First, get rid of the grouping
    ts = conv['thousands_sep']
    if ts:
        string = string.replace(ts, '')

    #next, replace the decimal point with a dot
    dd = conv['decimal_point']
    if dd:
        string = string.replace(dd, '.')
    return string
```

However, I'll take more time to get through your python code and adapt the `locale.delocalize` function to the `numpy.loadtxt` function. But in the end, I hope to add `ts` and `dd` parameters to the `loadtxt` funtion as the python documentation warns of difficulty to use the locale variable properly.

**Comment by jakobjakobson13** [comment]
I tried to find a solution, but none of my approaches worked. Perhaps, I'll try it some other time. We will see.

**Comment by cholmcc** [comment]
Hi, 

Why not simply replace 

```python
    def floatconv(x):
         x.lower()
         if '0x' in x:
              return float.fromhex(x)
         return float(x) # This line changed!
```
with 

```python
    def floatconv(x):
         from locale import atof 

         x.lower()
         if '0x' in x:
              return float.fromhex(x)
         return atof(x) # This line changed!
```

in `npyio.py`.  Optionally, if one want to explicitly pass a locale to `loadtxt`, define a context manager 

```python 
class LocaleGuard:
    def __init__(self,locale,category=locale.LC_ALL):
        self._locale = locale
        self._catogory = category

    def __enter__(self):
        from locale getlocale, setlocale

        self._old = getlocale(self._category)
        setlocale(self._category,self._locale)

    def __exit__(self,etype,eval,etb):
        setlocale(self._category,self._old)
```

and then use that up-front in `numpy.loadtxt` or similar. 

Similarly, `numpy.savetxt` should be amended to use `locale.format` rather than default formatting. 

Yours,

Christian

**Comment by mastraa** [comment]
Hello all,

is there any chance to do the same while exporting data?
I'm using np-savetxt to export css/txt to be read with excel or other software that get local windows information so I need to write them with comma decimal separator...

any suggest?

Best regards,
Andrea Mastrangelo
