### ISSUE TITLE
QNX does not support __thread which causes an unknown symbol error

### ISSUE THREAD

**Issue by DanielT** [numpy/numpy#13824]
I just built numpy 1.16.4 for Python 2.7 on an aarch64 "embedded" board running QNX.

Unfortunately it didn't work by default, giving me the following error when trying to import numpy:
unknown symbol:  referenced from _multiarray_umath.so
(so basically unknown symbol: (blank))

After some digging it turned out to be caused by the two definitions using NPY_TLS in the singnal handling code in multiarraymodule.c. NPY_TLS is defined to __thread on QNX, because the platform uses a gcc compiler, but it seems QNX doesn't really support __thread even though the compiler does.
I modified multiarraymodule.c to simply remove the NPY_TLS qualifier and now the built numpy works.

If you care about QNX (do you care about QNX?) then you could test for the define \_\_QNX__ to define NPY_TLS as blank in that case.

**Comment by mattip** [comment]
PR welcome, preferably from someone who can test that it works on QNX + aarch64 (since our CI will test that it works for "normal" cases").

**Comment by UchihaSR** [comment]
i would like to take this issue

**Comment by mattip** [comment]
@UchihaSR work is progressing on #13854, if you can test the code there with a QNX system that would be helpful

**Comment by ljchen66** [comment]
I built and installed numpy 1.16.4 for QNX (x86_64) python 2.7 as well (with gfortran enabled). I got a different error when trying "import numpy":
>>> import numpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/numpy-1.16.4-py2.7-qnx-7.0.0-x86pc.egg/numpy/__init__.py", line 145, in <module>
    from . import lib
  File "/usr/lib/python2.7/site-packages/numpy-1.16.4-py2.7-qnx-7.0.0-x86pc.egg/numpy/lib/__init__.py", line 9, in <module>
    from .index_tricks import *
  File "/usr/lib/python2.7/site-packages/numpy-1.16.4-py2.7-qnx-7.0.0-x86pc.egg/numpy/lib/index_tricks.py", line 13, in <module>
    import numpy.matrixlib as matrixlib
  File "/usr/lib/python2.7/site-packages/numpy-1.16.4-py2.7-qnx-7.0.0-x86pc.egg/numpy/matrixlib/__init__.py", line 6, in <module>
    from .defmatrix import *
  File "/usr/lib/python2.7/site-packages/numpy-1.16.4-py2.7-qnx-7.0.0-x86pc.egg/numpy/matrixlib/defmatrix.py", line 13, in <module>
    from numpy.linalg import matrix_power
  File "/usr/lib/python2.7/site-packages/numpy-1.16.4-py2.7-qnx-7.0.0-x86pc.egg/numpy/linalg/__init__.py", line 51, in <module>
    from .linalg import *
  File "/usr/lib/python2.7/site-packages/numpy-1.16.4-py2.7-qnx-7.0.0-x86pc.egg/numpy/linalg/linalg.py", line 35, in <module>
    from numpy.linalg import lapack_lite, _umath_linalg
ImportError: Library cannot be found

Any ideas? The libraries (.so ) are there in linalg folder.

**Comment by seberg** [comment]
Going to close this old build issue.  We need someone with a QNX setup to make a PR to have a real shot at getting this fixed.
New issues welcome of course especially if you have such a board and interest to follow up.
