### ISSUE TITLE
Original error was: /home/wangyl/.local/lib/python2.7/site-packages/numpy-1.16.3-py2.7-linux-x86_64.egg/numpy/core/_multiarray_umath.so: undefined symbol: PyUnicodeUCS2_FromObject

### ISSUE THREAD

**Issue by Nick-Wilde** [numpy/numpy#13865]
Hi, everyone, I'm confused...
When Trinity running...

```
Trinity run failed. Must investigate error above.
warning, cmd: /home/wangyl/anaconda2/opt/trinity-2.8.5/util/support_scripts/../../Trinity --single "/data1/user/wangyl/Data/BRI20180201689-Esox_lucius/mine/trinity_ov/read_partitions/Fb_0/CBin_508/c50818.trinity.reads.fa" --output "/data1/user/wangyl/Data/BRI20180201689-Esox_lucius/mine/trinity_ov/read_partitions/Fb_0/CBin_508/c50818.trinity.reads.fa.out" --CPU 1 --max_memory 1G --run_as_paired --seqType fa --trinity_complete --full_cleanup --no_version_check   failed with ret: 65280, going to retry.


Error encountered::  <!----
CMD: /home/wangyl/anaconda2/opt/trinity-2.8.5/Analysis/SuperTranscripts/Trinity_gene_splice_modeler.py --trinity_fasta /data1/user/wangyl/Data/BRI20180201689-Esox_lucius/mine/trinity_ov/read_partitions/Fb_0/CBin_496/c49698.trinity.reads.fa.out/Trinity.tmp.fasta.filt --out_prefix /data1/user/wangyl/Data/BRI20180201689-Esox_lucius/mine/trinity_ov/read_partitions/Fb_0/CBin_496/c49698.trinity.reads.fa.out/Trinity.tmp.fasta.filt.ST --incl_cdna 2>tmp.22612.1561872788.stderr

Errmsg:
Traceback (most recent call last):
  File "/home/wangyl/anaconda2/opt/trinity-2.8.5/Analysis/SuperTranscripts/Trinity_gene_splice_modeler.py", line 11, in <module>
    import numpy
  File "/home/wangyl/.local/lib/python2.7/site-packages/numpy-1.16.3-py2.7-linux-x86_64.egg/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/home/wangyl/.local/lib/python2.7/site-packages/numpy-1.16.3-py2.7-linux-x86_64.egg/numpy/core/__init__.py", line 71, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
Here is how to proceed:
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
- If you are simply trying to use the numpy version that you have installed:
  your installation is broken - please reinstall numpy.
- If you have already reinstalled and that did not fix the problem, then:
  1. Check that you are using the Python you expect (you're using /home/wangyl/anaconda2/bin/python),
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy versions you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

     Note: this error has many possible causes, so please don't comment on
     an existing issue about this - open a new one instead.

Original error was: /home/wangyl/.local/lib/python2.7/site-packages/numpy-1.16.3-py2.7-linux-x86_64.egg/numpy/core/_multiarray_umath.so: undefined symbol: PyUnicodeUCS2_FromObject
```

**Comment by Nick-Wilde** [comment]
reinstall numpy.
