### ISSUE TITLE
Unittest: RuntimeError: implement_array_function method already has a docstring

### ISSUE THREAD

**Issue by kreativekrise** [numpy/numpy#14012]
My application uses the python package gensim, which requires numpy. I want to run some unit tests, but always get `RuntimeError: implement_array_function method already has a docstring`. It was tested on Windows 10 and Docker with python 3.7.4. The problem seems to exist since numpy 1.16.0. If I use numpy 1.15.4 it works without problems.

### Reproducing code example:

```python
import unittest
import numpy as np


class StartUpTest(unittest.TestCase):

    def setUp(self):
        return

    def testDefaultEndpoint(self):
        True
```

### Error message:

```
Traceback (most recent call last):
  File "C:\Users\kreativekrise\AppData\Local\Programs\Python\Python37-32\lib\unittest\loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "C:\Users\kreativekrise\AppData\Local\Programs\Python\Python37-32\lib\unittest\loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "D:\work\projects\myapp\test\startup_test.py", line 2, in <module>
    import numpy as np
  File "C:\Users\kreativekrise\AppData\Local\Programs\Python\Python37-32\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "C:\Users\kreativekrise\AppData\Local\Programs\Python\Python37-32\lib\site-packages\numpy\core\__init__.py", line 40, in <module>
    from . import multiarray
  File "C:\Users\kreativekrise\AppData\Local\Programs\Python\Python37-32\lib\site-packages\numpy\core\multiarray.py", line 12, in <module>
    from . import overrides
  File "C:\Users\kreativekrise\AppData\Local\Programs\Python\Python37-32\lib\site-packages\numpy\core\overrides.py", line 46, in <module>
    """)
RuntimeError: implement_array_function method already has a docstring
```

### Numpy/Python version information:

1.16.4 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 19:29:22) [MSC v.1916 32 bit (Intel)]

**Comment by The-Pied-Piper** [comment]
Is there any work around for this? This has made is impossible for us to run automated tests on our builds.

**Comment by emamulmursalin** [comment]
I think the users are using Scala on their environment. Use the latest version of Scala (e.g. 2.4.4) with Hadoop version 2.7 will resolve the issue. 

Btw, dont forget to restart the Jupyter notebook kernel !

**Comment by mattip** [comment]
Are you running tests with subinterpreters or somehow trying to re-initialize numpy in the same process after already importing it once (i.e. removing it from the `sys.modules`)? NumPy does not support that. Strange that it only began showing up in NumPy 1.16, are you sure that is the only change?

**Comment by aburrell** [comment]
Speaking for myself, I checked for re-initialization and that was not the problem.  And yes, the numpy version increase was the only change in the system (no updates to the code at all) and tests that were previously passing on AppVeyor and Travis-CI started failing.  Restricting the numpy version caused the tests to start passing again (as expected when the only change is the numpy version).

**Comment by rgommers** [comment]
There's 22 upvotes on this, so very likely to be a real issue. It would be super helpful if someone provide a full reproducer. The issue description isn't enough, that does basically nothing and the environment isn't well-specified. Something like:

```
# On Windows 10 with Anaconda (other OS also fine, if using pip 
# please say how you installed Python)
conda create -n tmp python=3.7
conda activate tmp
conda install gensim
python some_code_to_run.py  # plus the actual code to put in this file
```

**Comment by fjsj** [comment]
@rgommers 
Here's a full reproduction:
```
git clone https://github.com/dedupeio/dedupe.git
cd dedupe
pip install "numpy>=1.16"
pip install -r requirements.txt
cython src/*.pyx
python setup.py install
```

**Comment by rgommers** [comment]
@fjsj thanks. That passes for me. Is the `python setup.py install` failing for you, or are you running some code after that fails?

**Comment by fjsj** [comment]
@rgommers thanks for trying. Strange it passes. `python setup.py install` finishes with the output `RuntimeError: implement_array_function method already has a docstring` and exit code 1 for me.

Here are the full output of all steps: [full-steps-with-output.txt](https://github.com/numpy/numpy/files/4020770/full-steps-with-output.txt)

My env:

- Python 3.8.1
- macOS Mojave 10.14.6
- fish version 2.7.1

Tried bash as well, got the same error.

**Comment by trevordavies095** [comment]
Any update on this?

**Comment by nicornk** [comment]
Is there any workaround available for this issue?

**Comment by jroitgrund** [comment]
@mattip i'm trying to debug an issue where importing numpy throws an error and would like to understand what is causing it. would you be able to explain the simplest way to reproduce this error?

e.g. simply doing

```
>>> import numpy
>>> import numpy
```

doesn't throw.

neither does your suggestion remove numpy from `sys.modules`:

```
import numpy
import sys

del sys.modules['numpy']
import numpy
```

**Comment by seberg** [comment]
@jroitgrund, I seem to recall that this would happened when there was somehow an install of NumPy with stray old files around. Can you try uninstalling numpy (as often as necessary) and then reinstalling it?
E.g. if you are using `pip install numpy` to install, run `pip uninstall numpy` multiple times just to be sure until pip complains.

**Comment by jroitgrund** [comment]
@seberg This is happening in a production environment where a lot of different things could be causing it, not on my local machine. I'm trying to understand specifically what causes the issue and find the smallest possible reproduction, so that I can debug my production environment.

**Comment by mattip** [comment]
fwiw, the `Unittest:` might be a clue. Some test frameworks use import tricks, maybe one of them is messing things up.

**Comment by jroitgrund** [comment]
Forgot to mention that doesn't repro it either for me.

```
$ cat test.py
import unittest
import numpy as np


class StartUpTest(unittest.TestCase):

    def setUp(self):
        return

    def testDefaultEndpoint(self):
        True
$ python -m unittest test.py
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
$ python --version
Python 3.7.6
$ python -c 'import numpy;print(numpy.version.version)'
1.18.2
```

**Comment by blakete** [comment]
Has this not been solved?

**Comment by seberg** [comment]
@blakete are you building your own numpy, or any chance you had an old setup.py installed numpy, that (e.g. try uninstalling multiple times)?  I am not sure this should happen unless you have modified anything. If you use a dev setup (git), ensure you delete all local changes with `git clean -xdf` before rebuilding.

**Comment by blakete** [comment]
No, I installed it via pip, running python 3.6, the issue will not resolve itself even after uninstall and reinstall.

**Comment by schniewmatz** [comment]
@blakete Could you link the bug in Pycharm? I'm having a similar problem when running  unittest in pycharm in debug mode.

**Comment by msarafzadeh** [comment]
> @seberg I have resolved the issue. Pycharm has a bug and is causing the issue. Apologies for the false alarm. It works perfectly via terminal. Cheers!

is there a ticket to jetbrains?

**Comment by blakete** [comment]
> @blakete Could you link the bug in Pycharm? I'm having a similar problem when running unittest in pycharm in debug mode.

I have not found the bug on any Pycharm channel but after updating it has resolved my issues. If that does not work, try invalidating / clearing Pycharm caches.

**Comment by msarafzadeh** [comment]
which version 2020.1 ?

**Comment by mattip** [comment]
We never figured out the root cause for this, but it seems to be connected to Pycharm. Closing, since it does not seem to be actionable.
