### ISSUE TITLE
Function `take` cannot support `uint`/`uint64` data-type indices

### ISSUE THREAD

**Issue by hgt312** [numpy/numpy#14023]
The problem is shown as issue title.

### Reproducing code example:

```python
import numpy as np
np.take(np.arange(25), np.ones((4, 4), dtype=np.uint))
```

### Error message:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 56, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
TypeError: Cannot cast array data from dtype('uint64') to dtype('int64') according to the rule 'safe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 189, in take
    return _wrapfunc(a, 'take', indices, axis=axis, out=out, mode=mode)
  File "/usr/local/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 66, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/usr/local/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 46, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
TypeError: Cannot cast array data from dtype('uint64') to dtype('int64') according to the rule 'safe'
```

### Numpy/Python version information:

- numpy: 1.16.4
- python: 3.7.3
- OS: macOS 10.13.6

**Comment by seberg** [comment]
Hmmm, sounds like that place should maybe use same kind casting (although it will ignore integer overflow occuring during the cast, same issue occurs with indexing though). There is another issue with casting the output IIRC, but that is orthogonal.

**Comment by seberg** [comment]
Same as gh-25607 closing this one...
