### ISSUE TITLE
Import numpy wheel: No module named 'numpy.core._multiarray_umath'

### ISSUE THREAD

**Issue by ns-cweber** [numpy/numpy#14071]
When I download the wheel with `pip wheel numpy` and run `PYTHONPATH=numpy-1.16.4-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl python` and run `import numpy`, I get:

```
Traceback (most recent call last):
  File "/Users/cweber/Projects/src/github.com/weberc2/builder/numpy-1.16.4-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl/numpy/core/__init__.py", line 40, in <module>
  File "/Users/cweber/Projects/src/github.com/weberc2/builder/numpy-1.16.4-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl/numpy/core/multiarray.py", line 12, in <module>
  File "/Users/cweber/Projects/src/github.com/weberc2/builder/numpy-1.16.4-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl/numpy/core/overrides.py", line 6, in <module>
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/cweber/Projects/src/github.com/weberc2/builder/numpy-1.16.4-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl/numpy/__init__.py", line 142, in <module>
  File "/Users/cweber/Projects/src/github.com/weberc2/builder/numpy-1.16.4-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl/numpy/core/__init__.py", line 71, in <module>
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
Here is how to proceed:
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
- If you are simply trying to use the numpy version that you have installed:
  your installation is broken - please reinstall numpy.
- If you have already reinstalled and that did not fix the problem, then:
  1. Check that you are using the Python you expect (you're using /tmp/venv/bin/python),
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy versions you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

     Note: this error has many possible causes, so please don't comment on
     an existing issue about this - open a new one instead.

Original error was: No module named 'numpy.core._multiarray_umath'
```

### Numpy/Python version information:

Python version: 3.6.4
Numpy version: 1.16.4

**Comment by david-cortes** [comment]
Same issue here, but the problem only happens in conda environments that have a no-mkl numpy install (for reason `pip` will try to install numpy when it is a dependency of another package, even though the `conda` one is installed).

**Comment by mattip** [comment]
> When I download the wheel ... and run PYTHONPATH=... python -c"import numpy" ...

Could you point to documentation where this mode of work supported? Wheels are similar-but-not zipfiles, and the extra support shared-objects are not being properly extracted from the wheel zipfile so the runtime loader cannot find them. Closing as invalid, please reopen if I am mistaken.
