### ISSUE TITLE
NumPy 1.17.0 breaks in PyInstaller generated frozen packages, can't find `numpy.random.common`

### ISSUE THREAD

**Issue by CounterPillow** [numpy/numpy#14163]
If one uses PyInstaller to generate a frozen .exe including NumPy, numpy throws a traceback on import with the exception `ModuleNotFoundError: No module named 'numpy.random.common'`.

A few people on StackOverflow [seem to have noticed this too](https://stackoverflow.com/questions/57264427/in-pyinstaller-why-wont-numpy-random-common-load-as-a-module).

### Reproducing code example:

We use the following PyInstaller spec file:

```python
# -*- mode: python -*-
# spec file for pyinstaller

block_cipher = None

import sys
sys.modules['FixTk'] = None

def get_overviewer_pkgname():
    from overviewer_core import overviewer_version
    return "overviewer-" + overviewer_version.VERSION

a = Analysis(['overviewer.py'],
             binaries=None,
             datas=[("overviewer_core/data", "overviewer_core/data")],
             hiddenimports=['overviewer_core.aux_files.genPOI'],
             hookspath=[],
             runtime_hooks=[],
             excludes=['FixTk', 'tcl', 'tk', '_tkinter', 'tkinter', 'Tkinter'],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          exclude_binaries=True,
          name='overviewer',
          debug=False,
          strip=False,
          upx=False,
          console=True )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=False,
               name=get_overviewer_pkgname())
```

We use the following buildbot code:

```python
def windows(arch):
    if arch == 'x86':
        pythonexe = r"C:\Python37 (x86)\python.exe"
    else:
        pythonexe = r"C:\Python37\python.exe"

    yield ShellCommand(command=[pythonexe, r"C:\devel\virtualenv\virtualenv.py", Interpolate("%(prop:builddir)s\\ci_env")], name="virtualenv")

    def script(s, interp=True):
        path = "%(prop:builddir)s\\ci_env\\Scripts\\" + s + ".exe"
        if interp:
            return Interpolate(path)
        return path
    del pythonexe
    yield ShellCommand(command=[script("pip"), "install", "numpy", "Pillow==5.1.0", "pyinstaller", "sphinx"], name="dependencies")

    yield checkout(python=script("python"))
    yield FileDownload(mastersrc="pyinstaller-windows.spec", workerdest="overviewer.spec", name="transfer spec file")

    vcvarsall = r'call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" ' + arch

    yield ShellCommand(command=Interpolate(vcvarsall + ' && "' + script("python", interp=False) + '" setup.py build'), name="build")
    yield ShellCommand(command=[script("pyinstaller"), "overviewer.spec"], name="pyinstaller")

    yield ShellCommand(command=[script("sphinx-build"), "docs", Interpolate(r"dist\overviewer-%(prop:version)s\docs")], name="sphinx")
    yield ShellCommand(command=[script("python"), "-m", "zipfile", "-c", "dist.zip", Interpolate("dist\\overviewer-%(prop:version)s\\")], name="create zip")
    yield upload("dist.zip", ".zip")


windows_env = {
    'DISTUTILS_USE_SDK': '1',
    'MSSdk': '1',
    'PIL_INCLUDE_DIR': r'C:\devel\pillow\src\libImaging',
}


@builder(env=windows_env)
def win32():
    yield windows('x86')


@builder(env=windows_env)
def win64():
    yield windows('amd64')
```

Example binary that exhibits the issue: https://overviewer.org/builds/win64/49/overviewer-0.14.57.zip

### Error message:

```
>overviewer.exe
Traceback (most recent call last):
  File "c:\worker\win64\ci_env\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "site-packages\numpy\__init__.py", line 150, in <module>
  File "c:\worker\win64\ci_env\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "site-packages\numpy\random\__init__.py", line 180, in <module>
  File "mtrand.pyx", line 1, in init numpy.random.mtrand
ModuleNotFoundError: No module named 'numpy.random.common'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 980, in _find_and_load
SystemError: <class '_frozen_importlib._ModuleLockManager'> returned a result with an error set
```

### Numpy/Python version information:

* Python 3.7.3
* NumPy 1.17.0 (version 1.16.4 worked fine)

**Comment by excalamus** [comment]
A workaround is to import the "missing" modules:

```python
import numpy.random.common
import numpy.random.bounded_integers
import numpy.random.entropy
```

**Comment by charris** [comment]
Should be fixed in 1.17.1.

**Comment by charris** [comment]
Note that this is really a Pyinstaller problem with cython generated files.

**Comment by ebonat** [comment]
thank you for your help!

**Comment by rgommers** [comment]
1.17.1 is out, so can we close this?

side note, I plan to rename `numpy.random.common` to `_common`, and probably get rid of those other public-looking-but-private namespaces as well. so if you're using the workaround above, you may want to try-except that.

**Comment by mattip** [comment]
Closing.
