### ISSUE TITLE
Problem with numpy importation

### ISSUE THREAD

**Issue by MarineAiry** [numpy/numpy#14184]
Hello everybody, I am a newbie of GitHub and really hope to spent much time here by learning and hearing from you.
I am working with blueCFD 2017-1 and finally I got an issue related to the pursue of numerical value of resistance from a test carried out on a ship model.
I have already installed numpy from the zip file named: **mingw-w64-x86_64-python2-numpy-1.16.4-1-any.pkg.tar.xz** ; found from the following web page: [https://packages.msys2.org/package/mingw-w64-x86_64-python2-numpy?repo=mingw64](url).
The installation as above was completed successfully, but after running the command as below:
**Reproducing code example:**
$ python averageForces.py
It occurred the following error:
### **Error message**:

Traceback (most recent call last):
  File "averageForces.py", line 4, in <module>
    import numpy as np
  File "D:/PROGRAMMI/blueCFD-Core-2017/msys64/mingw64/lib/python2.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "D:/PROGRAMMI/blueCFD-Core-2017/msys64/mingw64/lib/python2.7/site-packages/numpy/core/__init__.py", line 71, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
Here is how to proceed:
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
- If you are simply trying to use the numpy version that you have installed:
  your installation is broken - please reinstall numpy.
- If you have already reinstalled and that did not fix the problem, then:
  1. Check that you are using the Python you expect (you're using D:/PROGRAMMI/blueCFD-Core-2017/msys64/mingw64/bin/python.exe),
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy versions you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

     Note: this error has many possible causes, so please don't comment on
     an existing issue about this - open a new one instead.

Original error was: DLL load failed: Impossibile trovare il modulo specificato.

### **Numpy/Python version information:**
I am using:

- Windows 10

- Python 2.7.14 and 3.6.2

- Numpy 1.16.4

Thanks in advance for any help you might be able to provide.

**Comment by jwd0023** [comment]
You should use pip or some package manager instead (downloading and building packages by hand is not a good idea).

With pip, you can install Numpy by doing something like `pip install numpy`, which should fix the issue you are running into.

**Comment by jwd0023** [comment]
Were you able to figure this problem out?

If you have other issues please post them - otherwise you should probably close the issue.

**Comment by MarineAiry** [comment]
@jwd0023 I am still having trouble.
I followed the instructions reported here [https://github.com/blueCFD/Core/issues/128](url) including  udating Python version to 3.7.4.
So at the end numpy installation would be accomplished, except for the last issue mentioned there, for which I am asking about matplotlib importation.
I would report here the same question:

**Reproducing code example:**
`python3 averageForces.py`

**Error message:**
`Traceback (most recent call last): File "averageForces.py", line 5, in <module> import matplotlib.pyplot as plt ModuleNotFoundError: No module named 'matplotlib'`

**Numpy/Python version information:**
numpy-1.16.4-1
python 3.7.4
Windows 10
no pip installed (at this moment)

Please any suggestions ?

Thank you much again

**Comment by jwd0023** [comment]
@MarineAiry Like I said earlier, you should really be using pip to download python packages. You should be able to just type 

```
pip3 install numpy matplotlib
```

or, if that doesn't work,

```
pip install numpy matplotlib
```

It makes more sense to just download Python and pip with pacman, and then use pip to download actual Python modules. Check out the first answer [here](https://stackoverflow.com/questions/48087004/installing-pip-on-msys), for example. 

A lot of Python installations come with pip installed, so you may not have to do anything extra to run the commands above.

**Comment by MarineAiry** [comment]
I just typed: 
`pacman -S python3-pip
`
So far, so good. Pip is now installed. 

But after typing:
`pip3 install numpy matplotlib
`
it gives back the following error:
` ERROR: Complete output from command python setup.py egg_info:
    ERROR: ================================================================================
    Edit setup.cfg to change the build options

    BUILDING MATPLOTLIB
      matplotlib: yes [3.1.1]
          python: yes [3.7.4 (default, Jul 11 2019, 09:35:14)  [GCC 9.1.0]]
        platform: yes [msys]

    OPTIONAL SUBPACKAGES
     sample_data: yes [installing]
           tests: no  [skipping due to configuration]

    OPTIONAL BACKEND EXTENSIONS
             agg: yes [installing]
           tkagg: yes [installing; run-time loading from Python Tcl/Tk]
          macosx: no  [Mac OS-X only]

    OPTIONAL PACKAGE DATA
            dlls: no  [skipping due to configuration]

    non-existing path in 'numpy/distutils': 'site.cfg'
    non-existing path in 'numpy/random': 'src/splitmix64/splitmix.h'
    Could not locate executable g77
    Could not locate executable f77
    Running from numpy source directory.
    /tmp/easy_install-l6qgnqvd/numpy-1.17.0/setup.py:418: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
      run_build = parse_setuppy_commands()
    /tmp/easy_install-l6qgnqvd/numpy-1.17.0/numpy/distutils/system_info.py:690: UserWarning:
        Optimized (vendor) Blas libraries are not found.
        Falls back to netlib Blas library which has worse performance.
        A better performance should be easily gained by switching
        Blas library.
      self.calc_info()
    /tmp/easy_install-l6qgnqvd/numpy-1.17.0/numpy/distutils/system_info.py:690: UserWarning:
        Blas (http://www.netlib.org/blas/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [blas]) or by setting
        the BLAS environment variable.
      self.calc_info()
    /tmp/easy_install-l6qgnqvd/numpy-1.17.0/numpy/distutils/system_info.py:690: UserWarning:
        Blas (http://www.netlib.org/blas/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [blas_src]) or by setting
        the BLAS_SRC environment variable.
      self.calc_info()
    /tmp/easy_install-l6qgnqvd/numpy-1.17.0/numpy/distutils/system_info.py:1712: UserWarning:
        Lapack (http://www.netlib.org/lapack/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [lapack]) or by setting
        the LAPACK environment variable.
      if getattr(self, '_calc_info_{}'.format(lapack))():
    /tmp/easy_install-l6qgnqvd/numpy-1.17.0/numpy/distutils/system_info.py:1712: UserWarning:
        Lapack (http://www.netlib.org/lapack/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [lapack_src]) or by setting
        the LAPACK_SRC environment variable.
      if getattr(self, '_calc_info_{}'.format(lapack))():
    /usr/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'define_macros'
      warnings.warn(msg)
    Traceback (most recent call last):
      File "/usr/lib/python3.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/usr/lib/python3.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/lib/python3.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/usr/lib/python3.7/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-l6qgnqvd/numpy-1.17.0/setup.py", line 443, in <module>
      File "/tmp/easy_install-l6qgnqvd/numpy-1.17.0/setup.py", line 435, in setup_package
      File "/tmp/easy_install-l6qgnqvd/numpy-1.17.0/numpy/distutils/core.py", line 171, in setup
      File "/usr/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 163, in run
        self.run_command("egg_info")
      File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/easy_install-l6qgnqvd/numpy-1.17.0/numpy/distutils/command/egg_info.py", line 26, in run
      File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/easy_install-l6qgnqvd/numpy-1.17.0/numpy/distutils/command/build_src.py", line 142, in run
      File "/tmp/easy_install-l6qgnqvd/numpy-1.17.0/numpy/distutils/command/build_src.py", line 153, in build_sources
      File "/tmp/easy_install-l6qgnqvd/numpy-1.17.0/numpy/distutils/command/build_src.py", line 286, in build_library_sources
      File "/tmp/easy_install-l6qgnqvd/numpy-1.17.0/numpy/distutils/command/build_src.py", line 369, in generate_sources
      File "numpy/core/setup.py", line 669, in get_mathlib_info
    RuntimeError: Broken toolchain: cannot link a simple C program

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-tve9jo2c/matplotlib/setup.py", line 300, in <module>
        cmdclass=cmdclass,
      File "/usr/lib/python3.7/site-packages/setuptools/__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "/usr/lib/python3.7/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/usr/lib/python3.7/site-packages/setuptools/dist.py", line 717, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 782, in resolve
        replace_conflicting=replace_conflicting
      File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1077, in obtain
        return installer(requirement)
      File "/usr/lib/python3.7/site-packages/setuptools/dist.py", line 784, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 679, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/usr/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 705, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/usr/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 890, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/usr/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 1158, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/usr/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 1144, in run_setup
        run_setup(setup_script, args)
      File "/usr/lib/python3.7/site-packages/setuptools/sandbox.py", line 253, in run_setup
        raise
      File "/usr/lib/python3.7/contextlib.py", line 130, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/lib/python3.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/lib/python3.7/contextlib.py", line 130, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/lib/python3.7/site-packages/setuptools/sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "/usr/lib/python3.7/site-packages/setuptools/sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "/usr/lib/python3.7/site-packages/setuptools/_vendor/six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "/usr/lib/python3.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/usr/lib/python3.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/lib/python3.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/usr/lib/python3.7/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-l6qgnqvd/numpy-1.17.0/setup.py", line 443, in <module>
      File "/tmp/easy_install-l6qgnqvd/numpy-1.17.0/setup.py", line 435, in setup_package
      File "/tmp/easy_install-l6qgnqvd/numpy-1.17.0/numpy/distutils/core.py", line 171, in setup
      File "/usr/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 163, in run
        self.run_command("egg_info")
      File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/easy_install-l6qgnqvd/numpy-1.17.0/numpy/distutils/command/egg_info.py", line 26, in run
      File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/easy_install-l6qgnqvd/numpy-1.17.0/numpy/distutils/command/build_src.py", line 142, in run
      File "/tmp/easy_install-l6qgnqvd/numpy-1.17.0/numpy/distutils/command/build_src.py", line 153, in build_sources
      File "/tmp/easy_install-l6qgnqvd/numpy-1.17.0/numpy/distutils/command/build_src.py", line 286, in build_library_sources
      File "/tmp/easy_install-l6qgnqvd/numpy-1.17.0/numpy/distutils/command/build_src.py", line 369, in generate_sources
      File "numpy/core/setup.py", line 669, in get_mathlib_info
    RuntimeError: Broken toolchain: cannot link a simple C program
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-tve9jo2c/matplotlib/

`
Since I never faced an error like this, I don't have a clue what to do now. 
Please, would you have any suggestions ?

Thank you for all the help you are giving to me.

**Comment by MarineAiry** [comment]
I have just solved the issue (!!!) by typing:
`pacman -S mingw64/mingw-w64-x86_64-python3-matplotlib`
as suggested here: [https://github.com/blueCFD/Core/issues/128](url)
The command `$ python3 averageForces.py` finally works.
@jwd0023 Thank you so much for your help and your time !!:)
