### ISSUE TITLE
BUILD: Cannot build/run on mageia linux

### ISSUE THREAD

**Issue by shlomif** [numpy/numpy#14192]
### Reproducing code example:

```python
import numpy
```

### Error message:

```
Traceback (most recent call last):
  File "/home/shlomif/Download/unpack/prog/python/pypy3.6-7.1.1-beta-linux_x86_64-portable/lib-python/3/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/shlomif/Download/unpack/prog/python/pypy3.6-7.1.1-beta-linux_x86_64-portable/lib-python/3/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/home/shlomif/Download/unpack/prog/python/pypy3.6-7.1.1-beta-linux_x86_64-portable/lib-python/3/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/shlomif/Download/unpack/prog/python/pypy3.6-7.1.1-beta-linux_x86_64-portable/site-packages/numpy/__init__.py", line 145, in <module>
    from . import lib
  File "/home/shlomif/Download/unpack/prog/python/pypy3.6-7.1.1-beta-linux_x86_64-portable/site-packages/numpy/lib/__init__.py", line 9, in <module>
    from .index_tricks import *
  File "/home/shlomif/Download/unpack/prog/python/pypy3.6-7.1.1-beta-linux_x86_64-portable/site-packages/numpy/lib/index_tricks.py", line 13, in <module>
    import numpy.matrixlib as matrixlib
  File "/home/shlomif/Download/unpack/prog/python/pypy3.6-7.1.1-beta-linux_x86_64-portable/site-packages/numpy/matrixlib/__init__.py", line 6, in <module>
    from .defmatrix import *
  File "/home/shlomif/Download/unpack/prog/python/pypy3.6-7.1.1-beta-linux_x86_64-portable/site-packages/numpy/matrixlib/defmatrix.py", line 13, in <module>
    from numpy.linalg import matrix_power
  File "/home/shlomif/Download/unpack/prog/python/pypy3.6-7.1.1-beta-linux_x86_64-portable/site-packages/numpy/linalg/__init__.py", line 51, in <module>
    from .linalg import *
  File "/home/shlomif/Download/unpack/prog/python/pypy3.6-7.1.1-beta-linux_x86_64-portable/site-packages/numpy/linalg/linalg.py", line 35, in <module>
    from numpy.linalg import lapack_lite, _umath_linalg
ImportError: /home/shlomif/Download/unpack/prog/python/pypy3.6-7.1.1-beta-linux_x86_64-portable/site-packages/numpy/linalg/lapack_lite.pypy3-71-x86_64-linux-gnu.so: undefined symbol: zgelsd_

```

### Numpy/Python version information:

pypy3 binary and numpy from pip3 - on mageia linux v8 x64.

**Comment by mattip** [comment]
What is mageia linux? It seems somehow the build is missing the function defined in `numpy/linalg/lapack_lite/f2c_z_lapack.c`. Can you use the wheels from `pip install --extra-index https://antocuni.github.io/pypy-wheels/ubuntu numpy` ?

**Comment by shlomif** [comment]
@mattip : the wheel gives me this:

```
Traceback (most recent call last):
  File "/home/shlomif/Download/unpack/prog/python/pypy3.6-7.1.1-beta-linux_x86_64-portable/site-packages/numpy/core/__init__.py", line 17, in <module>
    from . import multiarray
  File "/home/shlomif/Download/unpack/prog/python/pypy3.6-7.1.1-beta-linux_x86_64-portable/site-packages/numpy/core/multiarray.py", line 14, in <module>
    from . import overrides
  File "/home/shlomif/Download/unpack/prog/python/pypy3.6-7.1.1-beta-linux_x86_64-portable/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: libopenblas.so.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/shlomif/Download/unpack/prog/python/pypy3.6-7.1.1-beta-linux_x86_64-portable/lib-python/3/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/shlomif/Download/unpack/prog/python/pypy3.6-7.1.1-beta-linux_x86_64-portable/lib-python/3/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/home/shlomif/Download/unpack/prog/python/pypy3.6-7.1.1-beta-linux_x86_64-portable/lib-python/3/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/shlomif/Download/unpack/prog/python/pypy3.6-7.1.1-beta-linux_x86_64-portable/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/home/shlomif/Download/unpack/prog/python/pypy3.6-7.1.1-beta-linux_x86_64-portable/site-packages/numpy/core/__init__.py", line 47, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.6 from "/home/shlomif/Download/unpack/prog/python/pypy3.6-7.1.1-beta-linux_x86_64-portable/bin/pypy3",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.17.0" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: libopenblas.so.0: cannot open shared object file: No such file or directory

```

I cannot find `libopenblas.so.0` anywhere in the mageia repos.

mageia is https://en.wikipedia.org/wiki/Mageia ; https://www.mageia.org/en/ .

**Comment by mattip** [comment]
This seems like a bit of a rabbit hole. You might want to start with standard CPython first, work through which problems are due to poor linalg support from the distro, which are due to some misconfiguration when building c-extension modules due to possible non-standard compiler flags, which are specific to NumPy, and which are due to CPython vs PyPy.

**Comment by shlomif** [comment]
@mattip - it now happens with cpython 3 in `/usr/bin/python3` as well, if I build numpy 1.17.0 from source (the binary wheel is fine). My problem was that mageia had an older version of numpy fo cpython3.

**Comment by shlomif** [comment]
@mattip: and thanks for your help. The numpy tests fail too here.

**Comment by mattip** [comment]
@shlomif any updates? I am tempted to close this since it is an issue with the host platform not providing a compliant BLAS implementation. Installing from wheels (which includes a BLAS library) works.

**Comment by shlomif** [comment]
> @shlomif any updates? I am tempted to close this since it is an issue with the host platform not providing a compliant BLAS implementation. Installing from wheels (which includes a BLAS library) works.

Now I am getting this:

```
Traceback (most recent call last):
  File "/home/shlomif/Download/unpack/prog/python/pypy3.6-7.1.1-beta-linux_x86_64-portable/lib-python/3/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/shlomif/Download/unpack/prog/python/pypy3.6-7.1.1-beta-linux_x86_64-portable/lib-python/3/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/home/shlomif/Download/unpack/prog/python/pypy3.6-7.1.1-beta-linux_x86_64-portable/lib-python/3/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/shlomif/Download/unpack/prog/python/pypy3.6-7.1.1-beta-linux_x86_64-portable/site-packages/numpy/__init__.py", line 145, in <module>
    from . import lib
  File "/home/shlomif/Download/unpack/prog/python/pypy3.6-7.1.1-beta-linux_x86_64-portable/site-packages/numpy/lib/__init__.py", line 9, in <module>
    from .index_tricks import *
  File "/home/shlomif/Download/unpack/prog/python/pypy3.6-7.1.1-beta-linux_x86_64-portable/site-packages/numpy/lib/index_tricks.py", line 13, in <module>
    import numpy.matrixlib as matrixlib
  File "/home/shlomif/Download/unpack/prog/python/pypy3.6-7.1.1-beta-linux_x86_64-portable/site-packages/numpy/matrixlib/__init__.py", line 6, in <module>
    from .defmatrix import *
  File "/home/shlomif/Download/unpack/prog/python/pypy3.6-7.1.1-beta-linux_x86_64-portable/site-packages/numpy/matrixlib/defmatrix.py", line 13, in <module>
    from numpy.linalg import matrix_power
  File "/home/shlomif/Download/unpack/prog/python/pypy3.6-7.1.1-beta-linux_x86_64-portable/site-packages/numpy/linalg/__init__.py", line 51, in <module>
    from .linalg import *
  File "/home/shlomif/Download/unpack/prog/python/pypy3.6-7.1.1-beta-linux_x86_64-portable/site-packages/numpy/linalg/linalg.py", line 35, in <module>
    from numpy.linalg import lapack_lite, _umath_linalg
ImportError: /home/shlomif/Download/unpack/prog/python/pypy3.6-7.1.1-beta-linux_x86_64-portable/site-packages/numpy/linalg/lapack_lite.pypy3-71-x86_64-linux-gnu.so: undefined symbol: zgelsd_
```

**Comment by mattip** [comment]
Just a wild guess, but your OS may not be using `RTLD_GLOBAL` in `dlopen`, so the symbols somehow are not getting loaded. Or, and this is less likely, your system blas does not export the symbols at all. `strace` might be able to tell you how `dlopen` is called.

**Comment by rgommers** [comment]
no further follow-up, so I'll close this. thanks @shlomif and @mattip
