### ISSUE TITLE
Failed to import numpy Python 3.7.4 in custom location

### ISSUE THREAD

**Issue by davidlud** [numpy/numpy#14265]
I have install python 3.7.4 manually from source. It is installed in ```/opt/XXX/python/```
Pip is in ```/opt/XXX/python/bin```

### How I Installed Ptyhon

Manually via source
```
wget python
./configure --prefix=/opt/xxx/python
make && make install
```

I did not modify any path variables. I manually call python by going to ```/opt/xxx/python/bin/python3 something.py```

Same with pip.
```/opt/xxx/python/bin/pip3 install xxx```

### How I install Numpy
```
/opt/xxx/python/bin/pip3 install --target=/opt/xxx/python/lib/python3.7/site-packages
```

says it installed fine, but when I import it gives me an error:

### Error Given
```
Traceback (most recent call last):
  File "/opt/xxx/python/lib/python3.7/site-packages/numpy/core/__init__.py", line 17, in <module>
    from . import multiarray
  File "/opt/xxx/python/lib/python3.7/site-packages/numpy/core/multiarray.py", line 14, in <module>
    from . import overrides
  File "/opt/xxx/python/lib/python3.7/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/xxx/python/lib/python3.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/opt/xxx/python/lib/python3.7/site-packages/numpy/core/__init__.py", line 47, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.7 from "/opt/xxx/python/bin/python3",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.17.0" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: No module named 'numpy.core._multiarray_umath'

```

**Comment by mattip** [comment]
Is there an `so` file `/opt/xxx/python/lib/python3.7/site-packages/numpy/core/_multiarray_umath*` ?

**Comment by davidlud** [comment]
> Is there an `so` file `/opt/xxx/python/lib/python3.7/site-packages/numpy/core/_multiarray_umath*` ?

yes!
```_multiarray_umath.cpython-35m-x86_64-linux-gnu.so
```

**Comment by mattip** [comment]
Why is that `cpython-35m*` ? That means it was built with python 3.5, not 3.7

**Comment by mattip** [comment]
Closing, the original issue seems to be a mix of various python version. Please reopen if there is more we can help with.
