### ISSUE TITLE
Can not install numpy with pip in clear conda environment

### ISSUE THREAD

**Issue by PgLoLo** [numpy/numpy#14262]
Can not install numpy 1.17.0 with pip in conda environment with strange error message. After some time build fails with `AssertionError: ('cp37', 'cp@pyvernodots@m', 'linux_x86_64') != ('cp37', 'cp@PYVERNODOTS@m', 'linux_x86_64')`. As far as I can see the assert fails because of letter case in "cp@PYVERNODOTS@m" string.

### Reproducing code example:

`pip install numpy`

### Error message:

```
7.4.0
Collecting numpy
  Downloading https://files.pythonhosted.org/packages/da/32/1b8f2bb5fb50e4db68543eb85ce37b9fa6660cd05b58bddfafafa7ed62da/numpy-1.17.0.zip (6.5MB)
     |████████████████████████████████| 6.5MB 592kB/s 
Building wheels for collected packages: numpy
  Building wheel for numpy (setup.py) ... error
  ERROR: Complete output from command /home/george/soft/miniconda3/envs/ml/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-p2whbfqt/numpy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-_op_itzm --python-tag cp37:
  ERROR: Running from numpy source directory.
  7.4.0
  blas_opt_info:
  blas_mkl_info:
  customize UnixCCompiler
    libraries mkl_rt not found in ['/home/george/soft/miniconda3/envs/ml/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
    NOT AVAILABLE
  
<...>

  writing entry points to numpy.egg-info/entry_points.txt
  writing top-level names to numpy.egg-info/top_level.txt
  writing manifest file 'numpy.egg-info/SOURCES.txt'
  reading manifest file 'numpy.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  no previously-included directories found matching 'doc/build'
  no previously-included directories found matching 'doc/source/generated'
  no previously-included directories found matching 'benchmarks/env'
  no previously-included directories found matching 'benchmarks/results'
  no previously-included directories found matching 'benchmarks/html'
  no previously-included directories found matching 'benchmarks/numpy'
  warning: no previously-included files matching '*.pyo' found anywhere in distribution
  warning: no previously-included files matching '*.pyd' found anywhere in distribution
  warning: no previously-included files matching '*.swp' found anywhere in distribution
  warning: no previously-included files matching '*.bak' found anywhere in distribution
  warning: no previously-included files matching '*~' found anywhere in distribution
  warning: no previously-included files found matching 'LICENSES_bundled.txt'
  writing manifest file 'numpy.egg-info/SOURCES.txt'
  Copying numpy.egg-info to build/bdist.linux-x86_64/wheel/numpy-1.17.0-py3.7.egg-info
  running install_scripts
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-p2whbfqt/numpy/setup.py", line 443, in <module>
      setup_package()
    File "/tmp/pip-install-p2whbfqt/numpy/setup.py", line 435, in setup_package
      setup(**metadata)
    File "/tmp/pip-install-p2whbfqt/numpy/numpy/distutils/core.py", line 171, in setup
      return old_setup(**new_attr)
    File "/home/george/soft/miniconda3/envs/ml/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/home/george/soft/miniconda3/envs/ml/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/george/soft/miniconda3/envs/ml/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/home/george/soft/miniconda3/envs/ml/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/george/soft/miniconda3/envs/ml/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 230, in run
      impl_tag, abi_tag, plat_tag = self.get_tag()
    File "/home/george/soft/miniconda3/envs/ml/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 179, in get_tag
      assert tag == supported_tags[0], "%s != %s" % (tag, supported_tags[0])
  AssertionError: ('cp37', 'cp@pyvernodots@m', 'linux_x86_64') != ('cp37', 'cp@PYVERNODOTS@m', 'linux_x86_64')
  ----------------------------------------
  ERROR: Failed building wheel for numpy
  Running setup.py clean for numpy
  ERROR: Complete output from command /home/george/soft/miniconda3/envs/ml/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-p2whbfqt/numpy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all:
  ERROR: Running from numpy source directory.
  
  `setup.py clean` is not supported, use one of the following instead:
  
    - `git clean -xdf` (cleans all files)
    - `git clean -Xdf` (cleans all versioned files, doesn't touch
                        files that aren't checked into the git repo)
  
  Add `--force` to your command to use it anyway if you must (unsupported).
  
  ----------------------------------------
  ERROR: Failed cleaning build dir for numpy
Failed to build numpy
Installing collected packages: numpy
  Running setup.py install for numpy ... done
Successfully installed numpy-1.17.0
```

### Numpy/Python version information:

python 3.7.4
numpy 1.17.0

**Comment by rgommers** [comment]
this is a known anaconda bug (latest python 3.7.4 is buggy), should be addressed shortly on the anaconda side

**Comment by PgLoLo** [comment]
> this is a known anaconda bug (latest python 3.7.4 is buggy), should be addressed shortly on the anaconda side

Thank you very much, downgrading python version solved the problem!
