### ISSUE TITLE
Sphinx 2.0+ incompatibility

### ISSUE THREAD

**Issue by bsipocz** [numpy/numpy#14285]
The docs build is not compatible with Sphinx 2.0. It was already mentioned in a PR recently, but I suppose it's better to have a separate issue for it, too.

Sphinx 1.8.5 works.

```
make html
# for testing
# @echo installed numpy 0a133311b5 matches git version 0a133311b5; exit 1
mkdir -p build/html build/doctrees
LANG=C sphinx-build -b html -WT --keep-going -d build/doctrees  -n source build/html 
Running Sphinx v2.1.2
1.18.dev0 1.18.0.dev0+0a13331

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sphinx/config.py", line 361, in eval_config_file
    execfile_(filename, namespace)
  File "/usr/local/lib/python3.7/site-packages/sphinx/util/pycompat.py", line 86, in execfile_
    exec(code, _globals)
  File "/Users/bsipocz/munka/devel/numpy/doc/source/conf.py", line 374, in <module>
    class NumPyLexer(CLexer):
  File "/Users/bsipocz/munka/devel/numpy/doc/source/conf.py", line 377, in NumPyLexer
    tokens = copy.deepcopy(lexers['c'].tokens)
KeyError: 'c'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sphinx/cmd/build.py", line 283, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/usr/local/lib/python3.7/site-packages/sphinx/application.py", line 209, in __init__
    self.config = Config.read(self.confdir, confoverrides or {}, self.tags)
  File "/usr/local/lib/python3.7/site-packages/sphinx/config.py", line 196, in read
    namespace = eval_config_file(filename, tags)
  File "/usr/local/lib/python3.7/site-packages/sphinx/config.py", line 371, in eval_config_file
    raise ConfigError(msg % traceback.format_exc())
sphinx.errors.ConfigError: There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sphinx/config.py", line 361, in eval_config_file
    execfile_(filename, namespace)
  File "/usr/local/lib/python3.7/site-packages/sphinx/util/pycompat.py", line 86, in execfile_
    exec(code, _globals)
  File "/Users/bsipocz/munka/devel/numpy/doc/source/conf.py", line 374, in <module>
    class NumPyLexer(CLexer):
  File "/Users/bsipocz/munka/devel/numpy/doc/source/conf.py", line 377, in NumPyLexer
    tokens = copy.deepcopy(lexers['c'].tokens)
KeyError: 'c'


Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sphinx/config.py", line 361, in eval_config_file
    execfile_(filename, namespace)
  File "/usr/local/lib/python3.7/site-packages/sphinx/util/pycompat.py", line 86, in execfile_
    exec(code, _globals)
  File "/Users/bsipocz/munka/devel/numpy/doc/source/conf.py", line 374, in <module>
    class NumPyLexer(CLexer):
  File "/Users/bsipocz/munka/devel/numpy/doc/source/conf.py", line 377, in NumPyLexer
    tokens = copy.deepcopy(lexers['c'].tokens)
KeyError: 'c'

make: *** [html-build] Error 2
```

**Comment by rgommers** [comment]
thanks @bsipocz. this is indeed getting pretty annoying, we should fix that soon.
