### ISSUE TITLE
Try __array_interface__["typestr"] when calling np.dtype(obj)

### ISSUE THREAD

**Issue by hameerabbasi** [numpy/numpy#14331]
(Original issue copied from dask/dask#4632)

Would it be possible to try `__array_interface__["typestr"]` when calling `np.dtype(obj)`?

```python
>>> import numpy as np
>>> from xnd import array
>>> x = array([1, 2, 3])
>>> dt = np.dtype(x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: data type not understood
>>> x.__array_interface__['typestr']
'=q'
```

From the original issue:

> Would it be possible to try `x.__array_interface__["typestr"]` in situations like the following?
> 
> I would prefer `xnd.array.dtype` to return `ndt()`, so it needs to be translated for NumPy:
> 
> ```
> >>> from xnd import array
> >>> import dask.array as da
> >>> 
> >>> x = array([1,2,3])
> >>> x.dtype
> ndt("int64")
> >>> x.__array_interface__["typestr"]
> '=q'
> >>> 
> >>> d = da.from_array(x, chunks=(5,), asarray=False)
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/stefan/dbg/lib/python3.8/site-packages/dask/array/core.py", line 2096, in from_array
>     chunks = normalize_chunks(chunks, x.shape, dtype=x.dtype)
>   File "/home/stefan/dbg/lib/python3.8/site-packages/dask/array/core.py", line 1846, in normalize_chunks
>     dtype = np.dtype(dtype)
> TypeError: data type not understood
> ```

**Comment by seberg** [comment]
Its certainly possible and a bit like giving it a more specific name such as `__numpy_dtype__`, which could make some sense. I am a bit worried that `np.dtype` is already a strangely overloaded function by inspecting the `.dtype` attribute of arrays? If I know the input is an array, I would use `arr.dtype` to begin with.
It not just coerces strings, etc. to new dtypes, it also discovers dtypes from arrays...

Heck, right now we do this recursively, if the returned `obj.dtype.dtype` is a numpy dtype, than we will use that.

Frankly, I think I would rather discuss deprecating that path entirely and maybe creating a new function which fetches the dtype and can be overloaded using `__array_function__`.

**Comment by hameerabbasi** [comment]
The issue here is that the dtype is not a `np.dtype` object but an `ndtypes.ndt` object, as XND is a complete reimplementation of NumPy.

`str(obj.dtype)` also mostly works.

**Comment by seberg** [comment]
I realize, but even for numpy arrays: `np.dtype(numpy_array)` seems a dubious use case to me, so that some other method would probably make sense.
I am not quite sure how much I like relying on strings to be honest, since it means we have to allow a "mini" language for user defined dtypes. Note that within the array interface, those currently only give void datatypes (which makes sense, not much to do there), but it shows how limited that approach is.

**Comment by hameerabbasi** [comment]
The pattern in NumPy often is that `np.method(arr)` corresponds to `arr.property` or `arr.method`. In this instance, `arr` happens to be a duck array and `arr.property` happens to be a non-NumPy dtype.

This has applications for converting PyTorch, TensorFlow and so on.

**Comment by seberg** [comment]
Right, except that `np.dtype(obj)` is much more than `lambda obj: np.asarray(obj).dtype`, which is why I was wondering if we should add the latter form under its own name or protocol rather than try to cramp it all into `np.dtype`.

I do not see how adding `__array_function__` to `np.dtype` is viable and to me a new fallback to `__array_interface__` seems more like a band-aid solution (maybe I am wrong), so I am trying to suggest other approaches to achieve the same thing. Also even if we would make it an `__array_function__` I would still not be sure if the function should return the numpy compatible dtype or not.

**Comment by seberg** [comment]
Closing this.  We don't want `np.dtype(array_like)` to work.  What we *do* want to work is `np.dtype(array_like.dtype)` no matter what kind of `dtype` is.
For that we have `__numpy_dtype__` now and if you need compat for older ones `.dtype` works (i.e. if `array_like.dtype.dtype` is the numpy dtype).

I am very sure that should cover everything asked for, but if not, let me know.
