### ISSUE TITLE
Numpy import errors

### ISSUE THREAD

**Issue by reimannsum** [numpy/numpy#14348]
I was trying to import the skyfield library

### Reproducing code example:

```python
from skyfield.api import Topos
```

### Error message:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/numpy/core/__init__.py", line 17, in <module>
    from . import multiarray
  File "/usr/local/lib/python3.7/dist-packages/numpy/core/multiarray.py", line 14, in <module>
    from . import overrides
  File "/usr/local/lib/python3.7/dist-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: libf77blas.so.3: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/skyfield/api.py", line 13, in <module>
    from .iokit import Loader, load_file
  File "/usr/local/lib/python3.7/dist-packages/skyfield/iokit.py", line 6, in <module>
    import numpy as np
  File "/usr/local/lib/python3.7/dist-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/usr/local/lib/python3.7/dist-packages/numpy/core/__init__.py", line 47, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.7 from "/usr/bin/python3",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.17.0" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: libf77blas.so.3: cannot open shared object file: No such file or directory

### Numpy/Python version information:
Python 3.7.3 (default, Apr  3 2019, 05:39:12)
Successfully installed numpy-1.17.0
import numpy fails with same error

**Comment by mattip** [comment]
Where did you get numpy? What operating system are you using? Hint: it is not the one provided from PyPI for linux, the 1.17.0 version supplies `libopenblasp-r0-2ecf47d5.3.7.dev.so` and `libgfortran-ed201abd.so.3.0.0`

**Comment by reimannsum** [comment]
pi@raspberrypi:~ $ sudo pip3 install numpy
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting numpy
Using cached https://www.piwheels.org/simple/numpy/numpy-1.17.0-cp37-cp37m-linux_armv7l.whl
Installing collected packages: numpy
Successfully installed numpy-1.17.0
pi@raspberrypi:~ $

**Comment by mattip** [comment]
You might have better luck reporting this to [the piwheels team](https://github.com/piwheels/packages/issues)

**Comment by reimannsum** [comment]
ok I will, I was just following the error instructions, Thanks!

**Comment by mattip** [comment]
If you do figure it out, please don't forget to tell us how, it might help others. We do have a few other raspberry pi people show up with [installation issues](https://github.com/numpy/numpy/issues?utf8=%E2%9C%93&q=is%3Aissue+raspberry+installation).

**Comment by reimannsum** [comment]
sure, I'll leave this open until I get a resolution.

[Here](https://github.com/piwheels/packages/issues/47) is my ticket with them
