### ISSUE TITLE
multiarray import failed

### ISSUE THREAD

**Issue by varkonyidavid91** [numpy/numpy#14375]
Hi!

I have Win 10, x64, Python 3.6.8 (3c6b436a57) x64, numpy 1.16.4 (7ebbc2). I installed python with the installer, and numpy with pip (didn't compile anything). This is the only python on my system. My PATH contains C:\Program Files\Python36\, and C:\Program Files\Python36\Scripts\, nothing funky. I have no PYTHONPATH.

I have built a DLL, which links against Python, and upon DllMain, it imports numpy, with:

Py_Initialize();
PyRun_SimpleStringFlags("import numpy as np", NULL);

Upon linking against this DLL, I non-deterministically get the error shown below. Both the DLL, and the app I'm linking it with are built in x64.

Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\site-packages\numpy\core\__init__.py", line 40, in <module>
    from . import multiarray
  File "C:\Program Files\Python36\lib\site-packages\numpy\core\multiarray.py", line 12, in <module>
    from . import overrides
  File "C:\Program Files\Python36\lib\site-packages\numpy\core\overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\Python36\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "C:\Program Files\Python36\lib\site-packages\numpy\core\__init__.py", line 71, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
Here is how to proceed:
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
- If you are simply trying to use the numpy version that you have installed:
  your installation is broken - please reinstall numpy.
- If you have already reinstalled and that did not fix the problem, then:
  1. Check that you are using the Python you expect (you're using C:\Docs\follicle2\stimu_runner\x64\Debug\stimu_runner.exe),
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy versions you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

     Note: this error has many possible causes, so please don't comment on
     an existing issue about this - open a new one instead.

Original error was: No module named 'numpy.core._multiarray_umath'

**Comment by OmarMerghany** [comment]
This error might be  because you have numpy installed in different location or you have an outdated version of numpy.
try this `python -m pip install --upgrade numpy`  in the command Prompt.

**Comment by varkonyidavid91** [comment]
Tryed. Also tryed it with numpy 1.15, 1.16, 1.17, none works. It's in the default location.

**Comment by mattip** [comment]
Does the success depend on the directory you start your application from?

**Comment by rossbar** [comment]
Closing due to inactivity. If the issue persists, please take a look at this [troubleshooting guide](https://numpy.org/devdocs/user/troubleshooting-importerror.html).
