### ISSUE TITLE
UnboundLocalError in Radau when given a NaN

### ISSUE THREAD

**Issue by gerlero** [numpy/numpy#14435]
Integration with method Radau raises an UnboundLocalError when the return from fun contains a NaN. Failure in this case is of course expected, but the UnboundLocalError is not.

### Reproducing code example:

```python
import numpy as np
from scipy.integrate import Radau

def fun(t, y):
    return (1,) if t==0 else (np.nan,)

radau = Radau(fun, t0=0, y0=(0,), t_bound=1)
radau.step()  # UnboundLocalError
```

### Error message:

```
Traceback (most recent call last):
  File "/Users/gabriel/radau_issue.py", line 8, in <module>
    radau.step()  # UnboundLocalError
  File "/Users/gabriel/Library/Python/3.7/lib/python/site-packages/scipy/integrate/_ivp/base.py", line 182, in step
    success, message = self._step_impl()
  File "/Users/gabriel/Library/Python/3.7/lib/python/site-packages/scipy/integrate/_ivp/radau.py", line 451, in _step_impl
    LU_real, LU_complex, self.solve_lu)
  File "/Users/gabriel/Library/Python/3.7/lib/python/site-packages/scipy/integrate/_ivp/radau.py", line 138, in solve_collocation_system
    return converged, k + 1, Z, rate
UnboundLocalError: local variable 'rate' referenced before assignment
```

### Numpy/Python version information:

```
1.17.0 3.7.4 (default, Jul 11 2019, 01:08:00) 
[Clang 10.0.1 (clang-1001.0.46.4)]
```

**Comment by gerlero** [comment]
Moving this issue to the SciPy project as it actually belongs there.
