### ISSUE TITLE
Cannot Import Numpy 1.17.1 into Python 3.7.4 (Raspian)

### ISSUE THREAD

**Issue by jcutcher01** [numpy/numpy#14437]
I apologize up front as I am not experienced in Linux. I am running a Raspberry Pi and currently have Python 3.7.3 running perfectly with Numpy, Scipy, and a host of other packages. I downloaded the 3.7.4 Python source and built it, which appears to be successful. Using PIP3 INSTALL, I installed both Scipy and Numpy and results showed "successful". PIP3 LIST shows them as installed.

when I run 3.7.4 and >>import numpy, I get the following... 

>>> import numpy
Traceback (most recent call last):
  File "/home/pi/Python374-env/lib/python3.7/site-packages/numpy/core/__init__.py", line 17, in <module>
    from . import multiarray
  File "/home/pi/Python374-env/lib/python3.7/site-packages/numpy/core/multiarray.py", line 14, in <module>
    from . import overrides
  File "/home/pi/Python374-env/lib/python3.7/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: /lib/arm-linux-gnueabihf/libm.so.6: version `GLIBC_2.27' not found (required by /home/pi/Python374-env/lib/python3.7/site-packages/numpy/core/_multiarray_umath.cpython-37m-arm-linux-gnueabihf.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/Python374-env/lib/python3.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/home/pi/Python374-env/lib/python3.7/site-packages/numpy/core/__init__.py", line 47, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.7 from "/home/pi/Python374-env/bin/python3",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.17.1" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: /lib/arm-linux-gnueabihf/libm.so.6: version `GLIBC_2.27' not found (required by /home/pi/Python374-env/lib/python3.7/site-packages/numpy/core/_multiarray_umath.cpython-37m-arm-linux-gnueabihf.so)

I did make sure to update my OS, but most likely some dependency is missing.
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 9.9 (stretch)
Release:	9.9
Codename:	stretch

**Comment by jcutcher01** [comment]
Searching further for this dependency issue I found this link. 

https://blog.piwheels.org/how-to-work-out-the-missing-dependencies-for-a-python-package/
