### ISSUE TITLE
"DLL load failed: The specified module could not be found." on Jupyter Notebook

### ISSUE THREAD

**Issue by spruce5637** [numpy/numpy#14442]
I was trying to import numpy on Jupyter Notebook but the error occurred (error message below). The same error message appears when I import some other module using numpy. Importing numpy on the command line (python import numpy) works fine, however. 

### Reproducing code example:

```python
import numpy 
```

### Numpy/Python version information:
Numpy version: 1.17.1
Python version: 3.7.4 64-bit
Operating system: Windows 10, 64 bit

I installed numpy from the command line using pip. (I've also uninstalled and reinstalled numpy using pip, to no avail)
I have added \Python37 and \Python37\Scripts to PATH.
I've installed Miniconda and added \Miniconda3, \Miniconda3\Scripts, and \Miniconda3\Library\bins to PATH 
I had Python 3.6 32-bit but uninstalled it a while ago.

### Error message:

Traceback (most recent call last)
c:\users\melody\python37\lib\site-packages\numpy\core\__init__.py in <module>
     16 try:
---> 17     from . import multiarray
     18 except ImportError as exc:

c:\users\melody\python37\lib\site-packages\numpy\core\multiarray.py in <module>
     13 
---> 14 from . import overrides
     15 from . import _multiarray_umath

c:\users\melody\python37\lib\site-packages\numpy\core\overrides.py in <module>
      6 
----> 7 from numpy.core._multiarray_umath import (
      8     add_docstring, implement_array_function, _get_implementing_args)

ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-33-010eb6a21332> in <module>
      6 import subprocess
      7 import wikipediaapi
----> 8 import numpy

c:\users\melody\python37\lib\site-packages\numpy\__init__.py in <module>
    140     from . import _distributor_init
    141 
--> 142     from . import core
    143     from .core import *
    144     from . import compat

c:\users\melody\python37\lib\site-packages\numpy\core\__init__.py in <module>
     45 """ % (sys.version_info[0], sys.version_info[1], sys.executable,
     46         __version__, exc)
---> 47     raise ImportError(msg)
     48 finally:
     49     for envkey in env_added:

ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.7 from "c:\users\melody\python37\python.exe",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.16.3" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: DLL load failed: The specified module could not be found.

**Comment by Rajdeepak24** [comment]
i want to run jupyter-notebook in specific folder but this error is occur  anyone help me to fix this prblm


D:\ML>jupyter-notebook .
Traceback (most recent call last):
  File "C:\Users\DeLL\anaconda3\Scripts\jupyter-notebook-script.py", line 6, in <module>
    from notebook.notebookapp import main
  File "C:\Users\DeLL\anaconda3\lib\site-packages\notebook\notebookapp.py", line 49, in <module>
    from zmq.eventloop import ioloop
  File "C:\Users\DeLL\anaconda3\lib\site-packages\zmq\__init__.py", line 47, in <module>
    from zmq import backend
  File "C:\Users\DeLL\anaconda3\lib\site-packages\zmq\backend\__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "C:\Users\DeLL\anaconda3\lib\site-packages\zmq\utils\sixcerpt.py", line 34, in reraise
    raise value
  File "C:\Users\DeLL\anaconda3\lib\site-packages\zmq\backend\__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "C:\Users\DeLL\anaconda3\lib\site-packages\zmq\backend\select.py", line 28, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "C:\Users\DeLL\anaconda3\lib\site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: DLL load failed: The specified module could not be found.

**Comment by mattip** [comment]
Does [this page](https://github.com/numpy/numpy/wiki/ImportError-Troubleshooting) help, especially the part about [activating your anaconda environment](https://github.com/numpy/numpy/wiki/ImportError-Troubleshooting#using-python-from-conda-anaconda) ?
