### ISSUE TITLE
AttributeError: module 'os' has no attribute 'fspath'

### ISSUE THREAD

**Issue by elegantcoin** [numpy/numpy#14541]
### Reproducing code example:

```python3

<< import numpy as np >>
```

### Error message:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/usr/local/lib/python3.6/site-packages/numpy/core/__init__.py", line 17, in <module>
    from . import multiarray
  File "/usr/local/lib/python3.6/site-packages/numpy/core/multiarray.py", line 14, in <module>
    from . import overrides
  File "/usr/local/lib/python3.6/site-packages/numpy/core/overrides.py", line 9, in <module>
    from numpy.compat._inspect import getargspec
  File "/usr/local/lib/python3.6/site-packages/numpy/compat/__init__.py", line 14, in <module>
    from . import py3k
  File "/usr/local/lib/python3.6/site-packages/numpy/compat/py3k.py", line 198, in <module>
    os_fspath = os.fspath
AttributeError: module 'os' has no attribute 'fspath'

### Numpy/Python version information:
numpy-1.17.2
Python 3.6.0a1

**Comment by mattip** [comment]
[`os.fspath`](https://docs.python.org/3/library/os.html?highlight=fspath#os.fspath) was added in 3.6. You are using an early alpha (3.6.0a1). Please update to a released version.

**Comment by yacinedev19** [comment]
> [`os.fspath`](https://docs.python.org/3/library/os.html?highlight=fspath#os.fspath) was added in 3.6. You are using an early alpha (3.6.0a1). Please update to a released version.
