### ISSUE TITLE
BUG: Circle-CI failing due to documentation build problems

### ISSUE THREAD

**Issue by seberg** [numpy/numpy#14637]
Not sure why this started right now, but circle-ci is currently failing with:

```
WARNING: autodoc: failed to import method 'Configuration.todict' from module 'numpy.distutils'; the following exception was raised:
Traceback (most recent call last):
  File "/home/circleci/repo/venv/lib/python3.6/site-packages/sphinx/util/inspect.py", line 230, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'numpy.distutils' has no attribute 'Configuration'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/circleci/repo/venv/lib/python3.6/site-packages/sphinx/ext/autodoc/importer.py", line 71, in import_object
    obj = attrgetter(obj, attrname)
  File "/home/circleci/repo/venv/lib/python3.6/site-packages/sphinx/ext/autodoc/__init__.py", line 226, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/home/circleci/repo/venv/lib/python3.6/site-packages/sphinx/ext/autodoc/__init__.py", line 1501, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/home/circleci/repo/venv/lib/python3.6/site-packages/sphinx/util/inspect.py", line 246, in safe_getattr
    raise AttributeError(name)
AttributeError: Configuration
```

**Comment by mattip** [comment]
I think that is specific to gh-14634, adding a comment there. Please reopen if I am mistaken.
