### ISSUE TITLE
TypeError in numpy.rate when using Decimals

### ISSUE THREAD

**Issue by meunomemauricio** [numpy/numpy#14638]
`numpy.rate` is raising `TypeError` when working with `Decimals` and the iterative function doesn't converge before the max iterations. 

I poked it a little bit, and it seems like the function assumes `rn` to be an array or `float`, but it is a `Decimal`:

https://github.com/numpy/numpy/blob/cacdf265755ffae9d5c07d35fafa3d1366e342b8/numpy/lib/financial.py#L640-L648

### Reproducing code example:

```python
import numpy as np
from decimal import Decimal

np.rate(Decimal(12), Decimal('400'), Decimal('10000'), Decimal(0))
```

`float`s work just fine:

```python
>>> np.rate(12.0, 400.0, 10000.0, 0.0)
nan
```

### Error message:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mauricio/.virtualenvs/unhaggle/local/lib/python2.7/site-packages/numpy/lib/financial.py", line 648, in rate
    return np.nan + rn
TypeError: unsupported operand type(s) for +: 'float' and 'Decimal'
```

### Numpy/Python version information:

```
('1.16.3', '2.7.15+ (default, Nov 27 2018, 23:36:35) \n[GCC 7.3.0]')
```

**Comment by Kai-Striega** [comment]
@meunomemauricio thanks bringing this up. Your digging is correct; adding Decimals and Floats isn't supported, and is therefore a type error. This should be  straightforward to fix, the only thing to be careful of is that it broadcasts appropriately for arrays of Decimals.

For those not used to the financial nomenclature, ``nan`` is the expected answer. By convention cash inflows (i.e into your pocket) is positive and outflows are negative. As both payments and present value are positive, it is impossible to pay off the existing ammount by taking more money out of the loan, regardless of the rate.

**Comment by eric-wieser** [comment]
Fixed in #14645

@WarrenWeckesser: What should we do about porting these to numpy-financial? Not merge them into `numpy` at all?

**Comment by WarrenWeckesser** [comment]
@eric-wieser, originally I thought existing numpy PRs could be merged into numpy, and I would port them over to numpy-financial after 1.0 was released.  Then numpy's versions would be frozen.  But I just released 0.2.0, and it could just as well as have been 1.0, so now I think it would be cleaner to freeze numpy's financial functions *now*, make the official 1.0 release of numpy-financial ASAP, and move all relevant issues and PRs over to the numpy-financial repo.

In particular, that means https://github.com/numpy/numpy/pull/14645 would not be merged into numpy.  If that PR is almost done, I can handle porting an appropriate patch (with credit to @Mandeep0001) when you and Kai are satisfied that the change is good.  I don't want to burden a new contributor with having to recreate a new PR in the numpy-financial repo.

I'll bring this up in the community meeting tomorrow.  Does your last question, *"Not merge them into numpy at all?"*, imply that you would be OK with this plan?
