### ISSUE TITLE
 Importing the multiarray numpy extension module failed.  Most likely you are trying to import a failed build of numpy.

### ISSUE THREAD

**Issue by qingbol** [numpy/numpy#14642]
platform: MacOS 10.14.6
I setup the conda virtual environment as follow:
[xxx@node1523 ~]$ conda create -n tf14cpu_py27 pip python=2.7
[xxx@node0265 ~]$ source activate tf14cpu_py27
(tf14cpu_py27) [xxx@node0265 ~]$ pip install --ignore-installed  https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.14.0-cp27-none-linux_x86_64.whl
(tf14cpu_py27) [xxx@node0265 ~]$ pip install keras
(tf14cpu_py27) [qingbol@node0265 ~]$ conda install theano pygpu
(tf14cpu_py27) [qingbol@node0265 ~]$ conda install -c conda-forge rpy2
(tf14cpu_py27) [qingbol@node0265 ~]$ conda install -c conda-forge r-genlasso
(tf14cpu_py27) [qingbol@node0265 ~]$ conda install -c conda-forge r-gsubfn

### Reproducing code example:

```python
import numpy as np
<< your code here >>
```

### Error message:
─ python
Python 2.7.15 | packaged by conda-forge | (default, Jul  2 2019, 00:42:22)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> **import numpy as np**
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tarus/program/miniconda3/envs/tf14_py27/lib/python2.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/Users/tarus/program/miniconda3/envs/tf14_py27/lib/python2.7/site-packages/numpy/core/__init__.py", line 71, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
Here is how to proceed:
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
- If you are simply trying to use the numpy version that you have installed:
  your installation is broken - please reinstall numpy.
- If you have already reinstalled and that did not fix the problem, then:
  1. Check that you are using the Python you expect (you're using /Users/tarus/program/miniconda3/envs/tf14_py27/bin/python),
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy versions you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

     Note: this error has many possible causes, so please don't comment on
     an existing issue about this - open a new one instead.

Original error was: dlopen(/Users/tarus/program/miniconda3/envs/tf14_py27/lib/python2.7/site-packages/numpy/core/_multiarray_umath.so, 2): Library not loaded: @rpath/libopenblas.dylib
  Referenced from: /Users/tarus/program/miniconda3/envs/tf14_py27/lib/python2.7/site-packages/numpy/core/_multiarray_umath.so
  Reason: image not found

### Numpy/Python version information:

╰─ conda list
 packages in environment at /Users/tarus/program/miniconda3/envs/tf14_py27:

 Name                    Version                   Build  Channel
_r-mutex                  1.0.1               anacondar_1    conda-forge
absl-py                   0.8.0                    pypi_0    pypi
astor                     0.8.0                    pypi_0    pypi
backports-weakref         1.0.post1                pypi_0    pypi
blas                      2.12                   openblas    conda-forge
bwidget                   1.9.11                        0    conda-forge
bzip2                     1.0.8                h01d97ff_1    conda-forge
ca-certificates           2019.9.11            hecc5488_0    conda-forge
cairo                     1.16.0            he1c11cd_1002    conda-forge
cctools                   895                           1
certifi                   2019.9.11                py27_0    conda-forge
clang                     4.0.1                         1
clang_osx-64              4.0.1               h1ce6c1d_18
clangxx                   4.0.1                         1
clangxx_osx-64            4.0.1               h22b1bf0_18
compiler-rt               4.0.1                hcfea43d_1
curl                      7.65.3               h22ea746_0    conda-forge
enum34                    1.1.6                    pypi_0    pypi
fontconfig                2.13.1            h6b1039f_1001    conda-forge
freetype                  2.10.0               h24853df_1    conda-forge
fribidi                   1.0.5             h01d97ff_1002    conda-forge
funcsigs                  1.0.2                    pypi_0    pypi
futures                   3.3.0                    pypi_0    pypi
gast                      0.3.2                    pypi_0    pypi
gettext                   0.19.8.1          h46ab8bc_1002    conda-forge
gfortran_osx-64           4.8.5                h22b1bf0_8    conda-forge
glib                      2.58.3            h9d45998_1002    conda-forge
google-pasta              0.1.7                    pypi_0    pypi
graphite2                 1.3.13            h2098e52_1000    conda-forge
grpcio                    1.24.1                   pypi_0    pypi
gsl                       2.5                  ha2d443c_1    conda-forge
h5py                      2.10.0                   pypi_0    pypi
harfbuzz                  2.4.0                hd8d2a14_3    conda-forge
icu                       64.2                 h6de7cb9_1    conda-forge
intel-openmp              2019.4                      233
jpeg                      9c                h1de35cc_1001    conda-forge
keras                     2.3.0                    pypi_0    pypi
keras-applications        1.0.8                    pypi_0    pypi
keras-preprocessing       1.1.0                    pypi_0    pypi
krb5                      1.16.3            hcfa6398_1001    conda-forge
ld64                      274.2                         1
libblas                   3.8.0               12_openblas    conda-forge
libcblas                  3.8.0               12_openblas    conda-forge
libcurl                   7.65.3               h16faf7d_0    conda-forge
libcxx                    4.0.1                hcfea43d_1
libcxxabi                 4.0.1                hcfea43d_1
libedit                   3.1.20181209         hb402a30_0
libffi                    3.2.1                h475c297_4
libgfortran               3.0.1                h93005f0_2
libiconv                  1.15              h01d97ff_1005    conda-forge
liblapack                 3.8.0               12_openblas    conda-forge
liblapacke                3.8.0               12_openblas    conda-forge
libopenblas               0.3.7                hd44dcd8_1    conda-forge
libpng                    1.6.37               h2573ce8_0    conda-forge
libssh2                   1.8.2                hcdc9a53_2    conda-forge
libtiff                   4.0.10            hd08fb8f_1003    conda-forge
libxml2                   2.9.9                h12c6b28_5    conda-forge
llvm                      4.0.1                         1
llvm-lto-tapi             4.0.1                         1
llvm-openmp               8.0.1                h770b8ee_0    conda-forge
lz4-c                     1.8.3             h6de7cb9_1001    conda-forge
make                      4.2.1             h1de35cc_2004    conda-forge
markdown                  3.1.1                    pypi_0    pypi
mkl                       2019.4                      233
mkl-service               2.3.0            py27hfbe908c_0
mkl_fft                   1.0.14           py27h01d97ff_1    conda-forge
mkl_random                1.1.0            py27h86efe34_0    conda-forge
mock                      3.0.5                    pypi_0    pypi
ncurses                   6.1                  h0a44026_1
**numpy                     1.16.5                   pypi_0    pypi
numpy-base                1.16.5           py27ha711998_0**
openssl                   1.1.1c               h01d97ff_0    conda-forge
pango                     1.42.4               h6691c8e_1    conda-forge
pcre                      8.41              h0a44026_1003    conda-forge
pip                       19.2.3                   py27_0
pixman                    0.38.0            h01d97ff_1003    conda-forge
protobuf                  3.10.0                   pypi_0    pypi
**python                    2.7.15            hd51d24c_1009    conda-forge**
pyyaml                    5.1.2                    pypi_0    pypi
r-base                    3.6.1                h7df2c9e_4    conda-forge
r-genlasso                1.4               r36h159158b_1    conda-forge
r-gsubfn                  0.7             r36h6115d3f_1001    conda-forge
r-igraph                  1.2.4.1           r36h75781db_2    conda-forge
r-lattice                 0.20_38         r36h159158b_1002    conda-forge
r-magrittr                1.5             r36h6115d3f_1002    conda-forge
r-mass                    7.3_51.4          r36h159158b_1    conda-forge
r-matrix                  1.2_17            r36h159158b_1    conda-forge
r-pkgconfig               2.0.3             r36h6115d3f_0    conda-forge
r-proto                   1.0.0                  r36_2002    conda-forge
readline                  8.0                  hcfe32e1_0    conda-forge
rpy2                      2.8.6           py27r36hfc83f80_2    conda-forge
scipy                     1.2.2                    pypi_0    pypi
setuptools                41.2.0                   py27_0
singledispatch            3.4.0.3               py27_1000    conda-forge
six                       1.12.0                   pypi_0    pypi
sqlite                    3.30.0               ha441bb4_0
tensorboard               1.14.0                   pypi_0    pypi
tensorflow                1.14.0                   pypi_0    pypi
tensorflow-estimator      1.14.0                   pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
theano                    1.0.4            py27h04f5b5a_0
tk                        8.6.9             h2573ce8_1003    conda-forge
tktable                   2.10                 hfa822fa_2    conda-forge
werkzeug                  0.16.0                   pypi_0    pypi
wheel                     0.33.6                   py27_0
wrapt                     1.11.2                   pypi_0    pypi
xz                        5.2.4             h1de35cc_1001    conda-forge
zlib                      1.2.11               h1de35cc_3
zstd                      1.4.0                ha9f0a20_0    conda-forge

**Comment by qingbol** [comment]
I solved this problem by referring to this link
https://github.com/numpy/numpy/issues/12977.

pip install tensorflow picked up numpy from PyPI. 
Try
**pip uninstall numpy
conda install numpy**
that will probably fix things
