### ISSUE TITLE
Unable to import required dependencies : numpy

### ISSUE THREAD

**Issue by jojotak** [numpy/numpy#14651]
Hello,

I try to execute test_Pandas.py by calling from php working on remote server.
PHP is running on the XAMPP.
[My Environment]

[localhost]
XAMMP version : XAMPP for Windows 5.6.24
PHP version : PHP 5.6.24 (cli) 
Apache version: Apache/2.4.23 (Win32)

OS : Windows 7 Professional 64 bit OS
CPU : Intel Core i5 2.40GHz
RAM : 8.00 GB

### Numpy/Python version information:
Python 3.7.4
Numpy version : 1.17.2 

[Remote Server]
XAMMP version : XAMPP for Windows 5.6.24
PHP version : PHP 5.6.24 (cli) 
Apache version: Apache/2.4.23 (Win32)

OS : Windows Server 2012 R2 Standard 64 bit OS
CPU : Intel Xeon 1.80GHz
RAM : 3.91 GB

### Numpy/Python version information:
Python 3.7.4
Numpy version : 1.17.2 
x
When I access to localhost (http://localhost/test_Pandas.php), it works well and show below responce.

---------------------------------------------------------------

This is test page for Pandas.
Dataframe data : 0 1 2 3 4 5

---------------------------------------------------------------

But When I access to server(http://[server hostname]/test_Pandas.php), I got below error.
"Import Error: Unable to import required dependencies: numpy:"

---------------------------------------------------------------

NGarray(64) { 

[0]=> string(34) "Traceback (most recent call last):" 
[1]=> string(47) " File "C:/test_Pandas.py", line 1, in " 
[2]=> string(23) " import pandas as pd" 
[3]=> string(129) " File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\__init__.py", line 17, in " 
[4]=> string(81) " "Unable to import required dependencies:\n" + "\n".join(missing_dependencies)" 
[5]=> string(52) "ImportError: Unable to import required dependencies:" 
[6]=> string(6) "numpy:" 
[7]=> string(0) "" 
[8]=> string(66) "IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!" 
[9]=> string(0) "" 
[10]=> string(40) "Importing the numpy c-extensions failed." 
[11]=> string(42) "- Try uninstalling and reinstalling numpy." 
[12]=> string(38) "- If you have already done that, then:" 
[13]=> string(126) " 1. Check that you expected to use Python3.7 from "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\python.exe"," 
[14]=> string(73) " and that you have no directories in your PATH or PYTHONPATH that can" 
[15]=> string(79) " interfere with the Python and numpy version "1.17.2" you're trying to use." 
[16]=> string(51) " 2. If (1) looks fine, you can open a new issue at" 
[17]=> string(71) " https://github.com/numpy/numpy/issues. Please include details on:" 
[18]=> string(31) " - how you installed Python" 
[19]=> string(30) " - how you installed numpy" 
[20]=> string(28) " - your operating system" 
[21]=> string(68) " - whether or not you have multiple versions of Python installed" 
[22]=> string(79) " - if you built from source, your compiler versions and ideally a build log" 
[23]=> string(0) "" 
[24]=> string(69) "- If you're working with a numpy git repository, try `git clean -xdf`" 
[25]=> string(66) " (removes all files not under version control) and rebuild numpy." 
[26]=> string(0) "" 
[27]=> string(69) "Note: this error has many possible causes, so please don't comment on" 
[28]=> string(54) "an existing issue about this - open a new one instead." 
[29]=> string(0) "" 
[30]=> string(75) "Original error was: DLL load failed: The specified module could not be found" 

}
This is test page for Pandas.
Dataframe data : Traceback (most recent call last):

---------------------------------------------------------------

My Source code is below.

--test_Pandas.py--
import pandas as pd
import numpy as np

df_simple = pd.DataFrame(np.arange(6).reshape(1, 6))
print(df_simple) 

--test_Pandas.php--
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="author" content="">
    <title>test Pandas</title>
  </head>
  <body>
		<?php $command="C:\Users\Administrator\AppData\Local\Programs\Python\Python37\python C:/test_Pandas.py 2>&1";
		exec($command,$output);
		if ( !exec($command,$output)) {
		echo "NG";
      	}
      	var_dump($output);
		$fetched_data = $output[0];
		?>
		<div>This is test page for Pandas.</div>
		<br/>
		<div>Dataframe data : <?php print "$fetched_data" ?></div>
  </body>
</html>

- how I installed Python : 
I downloaded from below link and install it
https://www.python.org/ftp/python/3.7.4/python-3.7.4-amd64.exe
- how I installed numpy.
I executed pip install option and installed numpy.
pip install numpy

[My investigation]
Step 1. I try to uninstall and reinstall it 
pip uninstall numpy -y
pip install numpy
But situation is not changed.

Step 2.
I checked this article 
https://stackoverflow.com/questions/37267399/importerror-cannot-import-name-numpy-mkl
and downloaded below file and re-install it 
numpy‑1.17.2+mkl‑cp37‑cp37m‑win_amd64.whl
 
But situation is not changed.
I'd like to know how to resolve the error message.
Any support is highly appreciated!

Best

**Comment by charris** [comment]
Looks like you are using mixed sources for your install, which can lead to problems. We don't support mkl wheels on PyPI, for instance. Your best bet is to use a distribution like anaconda/enthought for all installs. Note that it is easy to end up with multiple copies of Python on Windows if you aren't careful.

**Comment by jojotak** [comment]
I'm sorry for very late update.
I installed anaconda and tried to call its python.exe file from php code but it couldn't work well.
Finally I changed my approach and decided not to use Apache + PHP. I rebuild application with flask and it worked properly. Thank you for your support!

**Comment by mattip** [comment]
Glad to hear you worked it out. Closing. Please reopen or open a new issue if needed.

**Comment by benzimegido** [comment]
Step 1 worked for me, thanks!
