### ISSUE TITLE
No module named 'numpy.core._multiarray_umath'

### ISSUE THREAD

**Issue by suuuehgi** [numpy/numpy#14661]
### Reproducing code example:

```bash
~> python3.8 -c "import numpy"
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.7/site-packages/numpy/core/__init__.py", line 17, in <module>
    from . import multiarray
  File "/home/user/.local/lib/python3.7/site-packages/numpy/core/multiarray.py", line 14, in <module>
    from . import overrides
  File "/home/user/.local/lib/python3.7/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/.local/lib/python3.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/home/user/.local/lib/python3.7/site-packages/numpy/core/__init__.py", line 47, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.8 from "/usr/bin/python3.8",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.17.2" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: No module named 'numpy.core._multiarray_umath'
```

### Numpy/Python version information:

```bash
~> python3.8 -c "import sys; print(sys.version)"
3.8.0b4 (default, Oct  8 2019, 14:17:22) 
[GCC 8.3.0]

~> pip install --upgrade --user numpy
Requirement already up-to-date: numpy in /home/user/.local/lib/python3.7/site-packages (1.17.2)

~> pip install --upgrade --user pandas
Requirement already up-to-date: pandas in /home/user/.local/lib/python3.7/site-packages (0.25.1)

~> echo $PYTHONPATH 
/home/user/.local/lib/python3.7/site-packages/
```

**Comment by shoeffner** [comment]
Your PYTHONPATH points to python 3.7 but you are running python 3.8 – is that intended?
Otherwise, try unsetting your PYTHONPATH and installing numpy via python3.8's pip:
```
unset PYTHONPATH
python3.8 -m pip install --upgrade --user numpy
python3.8 -c "import numpy"
```

**Comment by daharn** [comment]
I have a similar problem when using `dill 0.3.0` or `0.3.1.1` in combination with `numpy 1.15.4`. The resulting error is again
`AttributeError: module 'numpy.core' has no attribute '_multiarray_umath'`

No such problem when updating to `numpy 1.16.5`. However, since the latest stable `cantera` version (`2.4.0`) forces `numpy` to be `1.15.*`, my only option to use all three is currently is to install `cantera` without dependencies, which is not ideal. I am using conda as a package manager.

**Comment by mattip** [comment]
Closing. This is a local issue mixing python 3.7 and 3.8. Please reopen with more information if needed.
