### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by EntPyle** [numpy/numpy#14675]
I am attempting to import numpy from a built-in console in Materialise 3-matic 14.0 and am getting this error. I can import numpy just fine from multiple environments in spyder, pycharm, and in my console. I have also placed an issue with Materialise because I think this is likely a problem with where they are looking for the dlls, and not a numpy issue. However, because I'm a blind cat trying to swim, I wanted to run the error past y'all and get more information. I have already uninstalled numpy through conda and reinstalled, with no effect.
### Reproducing code example:

```python
import numpy as np
```

### Error message:

Traceback (most recent call last):
  File "C:\Users\Npyle1\.conda\envs\3mat\lib\site-packages\numpy\core\__init__.py", line 17, in <module>
    from . import multiarray
  File "C:\Users\Npyle1\.conda\envs\3mat\lib\site-packages\numpy\core\multiarray.py", line 14, in <module>
    from . import overrides
  File "C:\Users\Npyle1\.conda\envs\3mat\lib\site-packages\numpy\core\overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Npyle1\.conda\envs\3mat\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "C:\Users\Npyle1\.conda\envs\3mat\lib\site-packages\numpy\core\__init__.py", line 47, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.7 from "C:\Program Files\Materialise\3-matic 14.0 (x64)\3-matic.exe",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.17.1" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: DLL load failed: The specified module could not be found.

### Numpy/Python version information:

1.17.1 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 22:01:29) [MSC v.1900 64 bit (AMD64)]

**Comment by EntPyle** [comment]
Materialise provided a snippet that worked. It appears it was indeed an issue on their end.
Here's the snippet:
```python
import os
import sys

env_p = sys.prefix  # path to the env
print("Env. path: {}".format(env_p))

new_p = ''
for extra_p in (r"Library\mingw-w64\bin",
    r"Library\usr\bin",
    r"Library\bin",
    r"Scripts",
    r"bin"):
    new_p +=  os.path.join(env_p, extra_p) + ';'

os.environ["PATH"] = new_p + os.environ["PATH"]  # set it for Python
os.putenv("PATH", os.environ["PATH"])  # push it at the OS level
```
