### ISSUE TITLE
Python 3.7 Windows debug build fails

### ISSUE THREAD

**Issue by Dekken** [numpy/numpy#14689]
Install fresh python 3.7.4 with debug

run:
```
call vcvars64.bat
SET DISTUTILS_USE_SDK=1
python_d -m pip install pip --upgrade
python_d -m pip install wheel
python_d -m pip install cython
```

```
python_d -m pip install numpy  
Collecting numpy
C:\pro\py\37d\lib\site-packages\pip\_vendor\msgpack\fallback.py:133: DeprecationWarning: encoding is deprecated, Use raw=False instead.
  unpacker = Unpacker(None, max_buffer_size=len(packed), **kwargs)
  Using cached https://files.pythonhosted.org/packages/ac/36/325b27ef698684c38b1fe2e546e2e7ef9cecd7037bcdb35c87efec4356af/numpy-1.17.2.zip
Building wheels for collected packages: numpy
  Building wheel for numpy (setup.py) ... done
  Created wheel for numpy: filename=numpy-1.17.2-cp37-cp37dm-win_amd64.whl size=4825877 sha256=9c94add5bdfd3273595f3cfb00721fc2860aeb0745fc5d6fb4bda77bb9ffbacb
  Stored in directory: C:\Users\lol\AppData\Local\pip\Cache\wheels\f6\42\5b\432471ce1e0a21eddd7593c15a7d5c5ef11c792cbeaa4d49a7
Successfully built numpy
Installing collected packages: numpy
Successfully installed numpy-1.17.2

```
```
python_d -c "import numpy as np; print(np.get_include())" | tee eet

Traceback (most recent call last):
  File "C:\pro\py\37d\lib\site-packages\numpy\core\__init__.py", line 17, in <module>
    from . import multiarray
  File "C:\pro\py\37d\lib\site-packages\numpy\core\multiarray.py", line 14, in <module>
    from . import overrides
  File "C:\pro\py\37d\lib\site-packages\numpy\core\overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: Module use of python37.dll conflicts with this version of Python.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\pro\py\37d\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "C:\pro\py\37d\lib\site-packages\numpy\core\__init__.py", line 47, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.7 from "C:\pro\py\37d\python_d.exe",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.17.2" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: Module use of python37.dll conflicts with this version of Python.
```

This could be related to this https://github.com/cython/cython/issues/3185

**Comment by mattip** [comment]
It seems the non-cython `_multiarray_umath` dll linked to the non-debug library. Maybe you need to set some environment variables to link to the correct import library?

**Comment by Dekken** [comment]
Could you elaborate on these "environment variables"?

**Comment by mattip** [comment]
We would have to disect the build.log. I think you need to run something like `pip install --no-clean numpy` then search for the commands used to link numpy. I was referring to the LIB env variable. You should be linking to python37_d.dll, not python37.dll

**Comment by Dekken** [comment]
I'm pretty sure distutils handles this appropriately

**Comment by mattip** [comment]
The error message when importing `_multiarray_umath` seems to indicate something is wrong with linking `_multiarray_umath`: 

```
Original error was: Module use of python37.dll conflicts with this version of Python
```
Otherwise why would you be getting that error? Something is wrong otherwise, as you say, it would have been handled appropriately. But it wasn't. The place to find the link command used is in the build logs.

**Comment by rossbar** [comment]
Closing due to inactivity. If the issue persists please reopen with the current information about the system/installation process.
