### ISSUE TITLE
This error occurred when I tried to import numpy-1.13.1 in python-3.5.4

### ISSUE THREAD

**Issue by luochenbeisheng** [numpy/numpy#14731]
Traceback (most recent call last):

  File "F:\Hi3516DV300\HiSVP_PC_V1.2.0.3\HiSVP_PC_V1.2.0.3\HiSVP_PC_V1.2.0.3\tools\nnie\windows\ruyi_env_setup_windows\python35\lib\site-packages\numpy\core\__init__.py", line 16, in <module>

    from . import multiarray

ImportError: DLL load failed: 拒绝访问。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "F:\Hi3516DV300\HiSVP_PC_V1.2.0.3\HiSVP_PC_V1.2.0.3\HiSVP_PC_V1.2.0.3\tools\nnie\windows\RuyiStudio-2.0.27\RuyiStudio-2.0.27\Resources\pythonScript\CNN_convert_bin_and_print_featuremap.py", line 2, in <module>

    import caffe

  File "F:\Hi3516DV300\HiSVP_PC_V1.2.0.3\HiSVP_PC_V1.2.0.3\HiSVP_PC_V1.2.0.3\tools\nnie\windows\ruyi_env_setup_windows\python35\Lib\site-packages\caffe\python\caffe\__init__.py", line 1, in <module>

    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver, NCCL, Timer

  File "F:\Hi3516DV300\HiSVP_PC_V1.2.0.3\HiSVP_PC_V1.2.0.3\HiSVP_PC_V1.2.0.3\tools\nnie\windows\ruyi_env_setup_windows\python35\Lib\site-packages\caffe\python\caffe\pycaffe.py", line 11, in <module>

    import numpy as np

  File "F:\Hi3516DV300\HiSVP_PC_V1.2.0.3\HiSVP_PC_V1.2.0.3\HiSVP_PC_V1.2.0.3\tools\nnie\windows\ruyi_env_setup_windows\python35\lib\site-packages\numpy\__init__.py", line 142, in <module>

    from . import add_newdocs

  File "F:\Hi3516DV300\HiSVP_PC_V1.2.0.3\HiSVP_PC_V1.2.0.3\HiSVP_PC_V1.2.0.3\tools\nnie\windows\ruyi_env_setup_windows\python35\lib\site-packages\numpy\add_newdocs.py", line 13, in <module>

    from numpy.lib import add_newdoc

  File "F:\Hi3516DV300\HiSVP_PC_V1.2.0.3\HiSVP_PC_V1.2.0.3\HiSVP_PC_V1.2.0.3\tools\nnie\windows\ruyi_env_setup_windows\python35\lib\site-packages\numpy\lib\__init__.py", line 8, in <module>

    from .type_check import *

  File "F:\Hi3516DV300\HiSVP_PC_V1.2.0.3\HiSVP_PC_V1.2.0.3\HiSVP_PC_V1.2.0.3\tools\nnie\windows\ruyi_env_setup_windows\python35\lib\site-packages\numpy\lib\type_check.py", line 11, in <module>

    import numpy.core.numeric as _nx

  File "F:\Hi3516DV300\HiSVP_PC_V1.2.0.3\HiSVP_PC_V1.2.0.3\HiSVP_PC_V1.2.0.3\tools\nnie\windows\ruyi_env_setup_windows\python35\lib\site-packages\numpy\core\__init__.py", line 26, in <module>

    raise ImportError(msg)

ImportError: 

Importing the multiarray numpy extension module failed.  Most

likely you are trying to import a failed build of numpy.

If you're working with a numpy git repo, try `git clean -xdf` (removes all

files not under version control).  Otherwise reinstall numpy.

Original error was: DLL load failed: 拒绝访问。

**Comment by mattip** [comment]
How did you get/install python and numpy? You might find the downloads [here](https://github.com/BVLC/caffe/tree/windows#prebuilt-binaries) helpful, they suggest using Anaconda for python 3.5, which means an old version of anaconda. You can find the old versions [here](https://repo.anaconda.com/archive/), I think Anaconda3-4.4.0-Windows-x86_64.exe [uses python 3.5](https://docs.anaconda.com/anaconda/packages/old-pkg-lists/4.4.0/py35/)

**Comment by luochenbeisheng** [comment]
From https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/python-3.5.4-0.tar.bz2 here for python3.5 and numpy and install

**Comment by mattip** [comment]
Rather than install separate packages, you could try https://mirrors.tuna.tsinghua.edu.cn/anaconda/archive/Anaconda3-4.4.0-Windows-x86_64.exe, you may want to [verify the hash](https://docs.anaconda.com/anaconda/install/hashes/#anaconda-installer-file-hashes) with the ones [here](https://docs.anaconda.com/anaconda/install/hashes/all/)

**Comment by luochenbeisheng** [comment]
I need to use python in some special software, so I can't use python in Anaconda

**Comment by luochenbeisheng** [comment]
The problem has been resolved because there are no administrator privileges

**Comment by mattip** [comment]
Closing. Thanks for the update.
