### ISSUE TITLE
Error : NumPy failed to import

### ISSUE THREAD

**Issue by Dhkor9** [numpy/numpy#14823]
I am working on the Mozilla DeepSpeech file to try and build my own Speech-To-Text. However, when I ran the code, it reported numpy error. 
I am currently using Rasbian Buster with a Raspberry pi 4 4GB. 
I have tried uninstalling and reinstalling numpy but the error still unsolved.
### Reproducing code example:
The code is just from https://github.com/mozilla/DeepSpeech which is the same as below.

```python
deepspeech --model deepspeech-0.5.1-models/output_graph.pbmm --alphabet deepspeech-0.5.1-models/alphabet.txt --lm deepspeech-0.5.1-models/lm.binary --trie deepspeech-0.5.1-models/trie --audio audio/2830-3980-0043.wav
```

### Error message:

###Traceback (most recent call last):
  File "/home/pi/tmp/deepspeech-venv/lib/python3.7/site-packages/numpy/core/__init__.py", line 17, in <module>
    from . import multiarray
  File "/home/pi/tmp/deepspeech-venv/lib/python3.7/site-packages/numpy/core/multiarray.py", line 14, in <module>
    from . import overrides
  File "/home/pi/tmp/deepspeech-venv/lib/python3.7/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: libf77blas.so.3: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/tmp/deepspeech-venv/lib/python3.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/home/pi/tmp/deepspeech-venv/lib/python3.7/site-packages/numpy/core/__init__.py", line 47, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.7 from "/home/pi/tmp/deepspeech-venv/bin/python3",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.17.3" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: libf77blas.so.3: cannot open shared object file: No such file or directory

Traceback (most recent call last):
  File "/home/pi/tmp/deepspeech-venv/lib/python3.7/site-packages/deepspeech/impl.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/home/pi/tmp/deepspeech-venv/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: numpy.core.multiarray failed to import

**Comment by mattip** [comment]
How are you installing numpy? 
You may find 
```
sudo apt-get install libatlas-base-dev
```

solves this particular error, but more may follow.

Another way to install NumPy is via your OS package manager
```
apt install python3-numpy
```
since the pip packages on the third-party packager www.piwheels.org do not properly package needed libraries. In order for this to work you must uninstall versions of numpy you may have already installed.

**Comment by rossbar** [comment]
Closing due to inactivity. If the issue persists, please check out this [troubleshooting guide](https://numpy.org/devdocs/user/troubleshooting-importerror.html)
