### ISSUE TITLE
Importing numpy fails with "undefined symbol: __svml_atan22"

### ISSUE THREAD

**Issue by AgilentGCMS** [numpy/numpy#14838]
I installed numpy 1.17.3 with intel icc/ifort compilers and MKL libraries, following the instructions at https://software.intel.com/en-us/articles/numpyscipy-with-intel-mkl. I've done this many times before, except this time I can't import the resultant numpy module. I'm using python 3.7.4 on a 64-bit linux platform.

```python
import numpy as np
```

```
Traceback (most recent call last):
  File "/discover/nobackup/projects/tm5var4d/packages/python/3.7.4_gcc/lib/python3.7/site-packages/numpy/core/__init__.py", line 17, in <module>
    from . import multiarray
  File "/discover/nobackup/projects/tm5var4d/packages/python/3.7.4_gcc/lib/python3.7/site-packages/numpy/core/multiarray.py", line 14, in <module>
    from . import overrides
  File "/discover/nobackup/projects/tm5var4d/packages/python/3.7.4_gcc/lib/python3.7/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: /discover/nobackup/projects/tm5var4d/packages/python/3.7.4_gcc/lib/python3.7/site-packages/numpy/core/_multiarray_umath.cpython-37m-x86_64-linux-gnu.so: undefined symbol: __svml_atan22

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/discover/nobackup/projects/tm5var4d/packages/python/3.7.4_gcc/lib/python3.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/discover/nobackup/projects/tm5var4d/packages/python/3.7.4_gcc/lib/python3.7/site-packages/numpy/core/__init__.py", line 47, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.7 from "/discover/nobackup/projects/tm5var4d/packages/python/3.7.4_gcc/bin/python3",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.17.3" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: /discover/nobackup/projects/tm5var4d/packages/python/3.7.4_gcc/lib/python3.7/site-packages/numpy/core/_multiarray_umath.cpython-37m-x86_64-linux-gnu.so: undefined symbol: __svml_atan22
```

### Numpy/Python version information:

python 3.7.4, numpy 1.17.3

**Comment by mattip** [comment]
This seems quite intel-specific, as the missing symbol (I think) is from the Intel [SMVL extension library](https://software.intel.com/en-us/cpp-compiler-developer-guide-and-reference-intrinsics-for-short-vector-math-library-svml-operations), which we do not use. Perhaps it is dragged in by MKL but not linking properly?

**Comment by AgilentGCMS** [comment]
Thanks for that pointer, I was struggling to find with library should provide that symbol. In my case, simply recompiling numpy solved it, no idea why that library was not linked the first time.
