### ISSUE TITLE
Possible documentation bug in section about running tests

### ISSUE THREAD

**Issue by gramster** [numpy/numpy#14894]
The instructions here:

https://numpy.org/devdocs/dev/development_environment.html#development-environment

As well as the instructions about test coverage, say that tests are run with:

    python runtests.py ...

but there is no runtests.py file in a cloned repo. Perhaps that is a build artifact, but attempting to follow build instructions in turn leads to an immediate issue:

```
$pip install .
    ERROR: Command errored out with exit status 1:
     command: /Users/grwheele/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/gq/1zp9x1h125j7w4_gbb4kryv00000gn/T/pip-req-build-d9sz8i1u/setup.py'"'"'; __file__='"'"'/private/var/folders/gq/1zp9x1h125j7w4_gbb4kryv00000gn/T/pip-req-build-d9sz8i1u/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /private/var/folders/gq/1zp9x1h125j7w4_gbb4kryv00000gn/T/pip-req-build-d9sz8i1u/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/grwheele/.local/lib/python3.7/site-packages/setuptools/__init__.py", line 6, in <module>
        import distutils.core
      File "/private/var/folders/gq/1zp9x1h125j7w4_gbb4kryv00000gn/T/pip-req-build-d9sz8i1u/distutils/__init__.py", line 26, in <module>
        from . import ccompiler
      File "/private/var/folders/gq/1zp9x1h125j7w4_gbb4kryv00000gn/T/pip-req-build-d9sz8i1u/distutils/ccompiler.py", line 13, in <module>
        from distutils.errors import DistutilsExecError, DistutilsModuleError, \
    ModuleNotFoundError: No module named 'distutils.errors'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
 
This is with Python 3.7.3.

**Comment by gramster** [comment]
My bad on the latter; I had done a "cd numpy" when I was already in the directory. Going to close this until I know if runtests is a build artifact or not (if so, docs could still be clearer and say that).

**Comment by mattip** [comment]
It is not a build artifact, it is part of the repo. Would a mention of "top-level numpy directory" help? What would make this clearer?

**Comment by gramster** [comment]
No, this was entirely my fault. I had somehow executed “cd numpy” twice without noticing, and was in the subdirectory of the repo when I thought I was in the root. Sorry for wasting your time.
