### ISSUE TITLE
numpy1.17.0 ImportError: DLL load failed。

### ISSUE THREAD

**Issue by LiuYiChen0704** [numpy/numpy#14896]
- how you installed Python
Anaconda, 
python version is 3.7.3

     - how you installed numpy
conda install numpy=1.17.0

     - your operating system
win10 x64
```
Traceback (most recent call last):
  File "D:\Anaconda\envs\python373\lib\site-packages\numpy\core\__init__.py", line 17, in <module>
    from . import multiarray
  File "D:\Anaconda\envs\python373\lib\site-packages\numpy\core\multiarray.py", line 14, in <module>
    from . import overrides
  File "D:\Anaconda\envs\python373\lib\site-packages\numpy\core\overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: DLL load failed: 找不到指定的模块。
```

**Comment by mattip** [comment]
I just noticed [this](https://docs.conda.io/projects/conda/en/latest/user-guide/troubleshooting.html#solution) about activating an anaconda environment and setting environment variables to enable finding various DLLs. I don't know if this is relevant for your case, but might be worth trying some of these and letting us know if it helps.

**Comment by rossbar** [comment]
Closing due to inactivity. If the issue persists, please open a new issue with up-to-date information about the system and installation procedure.
