### ISSUE TITLE
DEP: Deprecate chararray in more than just documentation

### ISSUE THREAD

**Issue by brodderickrodriguez** [numpy/numpy#14952]
Per [documentation](https://docs.scipy.org/doc/numpy/reference/generated/numpy.chararray.astype.html#numpy.chararray.astype), a char array should be able to be casted to a float ndarray as long as the array entires are reals. Docs say this may cause a `ComplexWarning`, however, I'm seeing a `ValueError`.

### Reproducing code example:

```python
>>> import sys, numpy; print(numpy.__version__, sys.version)
1.17.2 3.7.4 (v3.7.4:e09359112e, Jul  8 2019, 14:54:52)
[Clang 6.0 (clang-600.0.57)]
>>> a = numpy.chararray((3,3))
>>> a[:] = '1'
>>> a
chararray([[b'1', b'1', b'1'],
           [b'1', b'1', b'1'],
           [b'1', b'1', b'1']], dtype='|S1')
>>> a.astype(numpy.float)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/defchararray.py", line 1989, in __array_finalize__
    raise ValueError("Can only create a chararray from string data.")
ValueError: Can only create a chararray from string data.
>>> a.real.astype(numpy.float)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/defchararray.py", line 1989, in __array_finalize__
    raise ValueError("Can only create a chararray from string data.")
ValueError: Can only create a chararray from string data.
>>>
```

**Comment by seberg** [comment]
Chararray is deprecated in documentation (maybe it should give a deprecation warning on creation). The issue is that chararrays `astype` method wants to preserve that `self` is a chararray as well.

The solution should be to just not use chararray (or get the array view).

**Comment by eric-wieser** [comment]
That documentation page is just an exact copy of `ndarray.astype`, presumably because sphinx is showing the methods of the base class.

**Comment by seberg** [comment]
It also is just inherited from the base class, and that version must be using `__array_finalize__` or wrapping. But since chararray should probably not be used, I think we probably should not try to fix it up much.

**Comment by jorenham** [comment]
This seems to have been resolved now

```pycon
>>> import numpy as np
>>> np.chararray
<python-input-1>:1: DeprecationWarning: `np.chararray` is deprecated and will be removed from the main namespace in the future. Use an array with a string or bytes dtype instead.
<class 'numpy.char.chararray'>
```
