### ISSUE TITLE
ValueError: assignment destination is read-only

### ISSUE THREAD

**Issue by ahsade6** [numpy/numpy#14972]
I created a pipleline containing a LogisticRegression fromsklearn library and tried to perform some cross validation. I used the code below. The input x_train is a dataframe.
```
start = time()
full_pipeline_with_predictor.fit(x_train, y_train)
full_pipeline_with_predictor
np.random.seed(42)

logit_scores = cross_val_score(full_pipeline_with_predictor, x_train, y_train, scoring='roc_auc', cv=10, n_jobs = -1)   

logit_score_train = logit_scores.mean()
train_time = np.round(time() - start, 4)

# Time and score test predictions
start = time()
logit_score_test.setflags(write=1)
logit_score_test = full_pipeline_with_predictor.score(x_test, y_test)
test_time.setflags(write=1)
test_time = np.round(time() - start, 4)
```

_However, I got the following error._

"""
_RemoteTracebackTraceback (most recent call last)
_RemoteTraceback: 

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/joblib/externals/loky/process_executor.py", line 418, in _process_worker
    r = call_item()
  File "/usr/local/lib/python3.6/site-packages/joblib/externals/loky/process_executor.py", line 272, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 600, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/joblib/parallel.py", line 256, in __call__
    for func, args, kwargs in self.items]
  File "/usr/local/lib/python3.6/site-packages/joblib/parallel.py", line 256, in <listcomp>
    for func, args, kwargs in self.items]
  File "/usr/local/lib/python3.6/site-packages/sklearn/model_selection/_validation.py", line 516, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.6/site-packages/sklearn/pipeline.py", line 352, in fit
    Xt, fit_params = self._fit(X, y, **fit_params)
  File "/usr/local/lib/python3.6/site-packages/sklearn/pipeline.py", line 317, in _fit
    **fit_params_steps[name])
  File "/usr/local/lib/python3.6/site-packages/joblib/memory.py", line 355, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sklearn/pipeline.py", line 716, in _fit_transform_one
    res = transformer.fit_transform(X, y, **fit_params)
  File "/usr/local/lib/python3.6/site-packages/sklearn/pipeline.py", line 912, in fit_transform
    results = self._parallel_func(X, y, fit_params, _fit_transform_one)
  File "/usr/local/lib/python3.6/site-packages/sklearn/pipeline.py", line 942, in _parallel_func
    weight) in enumerate(transformers, 1))
  File "/usr/local/lib/python3.6/site-packages/joblib/parallel.py", line 1003, in __call__
    if self.dispatch_one_batch(iterator):
  File "/usr/local/lib/python3.6/site-packages/joblib/parallel.py", line 834, in dispatch_one_batch
    self._dispatch(tasks)
  File "/usr/local/lib/python3.6/site-packages/joblib/parallel.py", line 753, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/usr/local/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 201, in apply_async
    result = ImmediateResult(func)
  File "/usr/local/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 582, in __init__
    self.results = batch()
  File "/usr/local/lib/python3.6/site-packages/joblib/parallel.py", line 256, in __call__
    for func, args, kwargs in self.items]
  File "/usr/local/lib/python3.6/site-packages/joblib/parallel.py", line 256, in <listcomp>
    for func, args, kwargs in self.items]
  File "/usr/local/lib/python3.6/site-packages/sklearn/pipeline.py", line 716, in _fit_transform_one
    res = transformer.fit_transform(X, y, **fit_params)
  File "/usr/local/lib/python3.6/site-packages/sklearn/pipeline.py", line 387, in fit_transform
    Xt, fit_params = self._fit(X, y, **fit_params)
  File "/usr/local/lib/python3.6/site-packages/sklearn/pipeline.py", line 317, in _fit
    **fit_params_steps[name])
  File "/usr/local/lib/python3.6/site-packages/joblib/memory.py", line 355, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sklearn/pipeline.py", line 716, in _fit_transform_one
    res = transformer.fit_transform(X, y, **fit_params)
  File "/usr/local/lib/python3.6/site-packages/sklearn/base.py", line 556, in fit_transform
    return self.fit(X, y, **fit_params).transform(X)
  File "<ipython-input-66-6a2ee52b9ddf>", line 10, in transform
  File "/usr/local/lib/python3.6/site-packages/pandas/core/frame.py", line 3119, in __setitem__
    self._set_item(key, value)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/frame.py", line 3195, in _set_item
    NDFrame._set_item(self, key, value)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/generic.py", line 2597, in _set_item
    self._data.set(key, value)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/internals.py", line 4263, in set
    blk.set(blk_locs, value_getitem(val_locs), check=check)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/internals.py", line 383, in set
    self.values[locs] = values
ValueError: assignment destination is read-only
"""

The above exception was the direct cause of the following exception:

ValueErrorTraceback (most recent call last)
<ipython-input-109-3655ddc4a87b> in <module>
      5 
      6 
----> 7 logit_scores = cross_val_score(full_pipeline_with_predictor, x_train, y_train, scoring='roc_auc', cv=5, n_jobs = -1)
      8 
      9 logit_score_train = logit_scores.mean()

/usr/local/lib/python3.6/site-packages/sklearn/model_selection/_validation.py in cross_val_score(estimator, X, y, groups, scoring, cv, n_jobs, verbose, fit_params, pre_dispatch, error_score)
    389                                 fit_params=fit_params,
    390                                 pre_dispatch=pre_dispatch,
--> 391                                 error_score=error_score)
    392     return cv_results['test_score']
    393 

/usr/local/lib/python3.6/site-packages/sklearn/model_selection/_validation.py in cross_validate(estimator, X, y, groups, scoring, cv, n_jobs, verbose, fit_params, pre_dispatch, return_train_score, return_estimator, error_score)
    230             return_times=True, return_estimator=return_estimator,
    231             error_score=error_score)
--> 232         for train, test in cv.split(X, y, groups))
    233 
    234     zipped_scores = list(zip(*scores))

/usr/local/lib/python3.6/site-packages/joblib/parallel.py in __call__(self, iterable)
   1014 
   1015             with self._backend.retrieval_context():
-> 1016                 self.retrieve()
   1017             # Make sure that we get a last message telling us we are done
   1018             elapsed_time = time.time() - self._start_time

/usr/local/lib/python3.6/site-packages/joblib/parallel.py in retrieve(self)
    906             try:
    907                 if getattr(self._backend, 'supports_timeout', False):
--> 908                     self._output.extend(job.get(timeout=self.timeout))
    909                 else:
    910                     self._output.extend(job.get())

/usr/local/lib/python3.6/site-packages/joblib/_parallel_backends.py in wrap_future_result(future, timeout)
    552         AsyncResults.get from multiprocessing."""
    553         try:
--> 554             return future.result(timeout=timeout)
    555         except LokyTimeoutError:
    556             raise TimeoutError()

/usr/local/lib/python3.6/concurrent/futures/_base.py in result(self, timeout)
    430                 raise CancelledError()
    431             elif self._state == FINISHED:
--> 432                 return self.__get_result()
    433             else:
    434                 raise TimeoutError()

/usr/local/lib/python3.6/concurrent/futures/_base.py in __get_result(self)
    382     def __get_result(self):
    383         if self._exception:
--> 384             raise self._exception
    385         else:
    386             return self._result

ValueError: assignment destination is read-only

I used the solution on https://github.com/tensorflow/models/issues/6242 but that didn't fix it.

**Comment by mattip** [comment]
The interaction with scikit-learn and pandas will make it difficult for us here at numpy to figure out what is going on. You might have more luck reporting this to one of those packages. With that, I see `pandas/core/internals.py` in your backtrace. That file indicates you are using a version of pandas from before release 0.24.0, which was released almost a year ago.

**Comment by ahsade6** [comment]
@mattip thanks for taking the time. It worked when I removed n_jobs = -1 but yeah it's very slow.
