### ISSUE TITLE
matmul produces error for masked arrays that aren't square

### ISSUE THREAD

**Issue by dstorer** [numpy/numpy#14992]
Using np.matmul to multiply a numpy array with its transpose produces an error when the array is masked and it is not a square array. (When the array is either masked and square, or unmasked and any shape it works, it only doesn't work when the array is both masked and not square). I am working with numpy version 1.17.3, and python version 3.7.5.

### Reproducing code example:

```python
import numpy as np
x = np.tile([1,2,3,4],(3,1))
mask = np.tile([0,1,0,0],(3,1))
mx = np.ma.masked_array(x, mask=mask)
np.matmul(my.T,my)
```

### Error message:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/lustre/aoc/projects/hera/dstorer/env/envs/hera/lib/python3.7/site-packages/numpy/ma/core.py", line 3040, in __array_wrap__
    m = reduce(mask_or, [getmaskarray(arg) for arg in input_args])
  File "/lustre/aoc/projects/hera/dstorer/env/envs/hera/lib/python3.7/site-packages/numpy/ma/core.py", line 1753, in mask_or
    return make_mask(umath.logical_or(m1, m2), copy=copy, shrink=shrink)
ValueError: operands could not be broadcast together with shapes (4,3) (3,4)
```

**Comment by eric-wieser** [comment]
In case it unblocks you, `np.ma.dot` works correctly here

**Comment by eric-wieser** [comment]
I've made a start locally on generalizing `np.ma.masked_rowcols` to work for the matmul use case

**Comment by alfiopuglisi** [comment]
This problem also causes the @ operator to fail, since it relies on \_\_matmul__:

```py
import numpy as np
a = np.ones((3,4))
b = np.ones((4,3))
ma = np.ma.masked_array(a, mask=np.ones(a.size))
mb = np.ma.masked_array(b, mask=np.ones(b.size))
ma @ mb
```

Result:

    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/opt/anaconda3/envs/xelab/lib/python3.7/site-packages/numpy/ma/core.py", line 3049, in __array_wrap__
        m = reduce(mask_or, [getmaskarray(arg) for arg in input_args])
      File "/opt/anaconda3/envs/xelab/lib/python3.7/site-packages/numpy/ma/core.py", line 1764, in mask_or
        return make_mask(umath.logical_or(m1, m2), copy=copy, shrink=shrink)
    ValueError: operands could not be broadcast together with shapes (3,4) (4,3)

**Comment by muhrin** [comment]
I also ran into this problem (with matmul of regular array and masked array).  I found this SO useful:

https://stackoverflow.com/questions/63218951/masked-matrix-multiplication

In short, using an `einsum` works, e.g.:
```
np.einsum('ij,jk', a, b)
```

**Comment by InessaPawson** [comment]
@rossbar @Mukulikaa @melissawm Should we include the mentioned above workarounds in the documentation for `np.matmul`?

**Comment by melissawm** [comment]
Sounds reasonable 👍🏻
