### ISSUE TITLE
np.interp("2", [1, 2], [3, 4]) succeeds

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#15008]
```
>>> np.interp("2", [1, 2], [3, 4])
4.0
```

This really ought to be a `TypeError`...

**Comment by sameshl** [comment]
I would like to take this up @eric-wieser!

**Comment by seberg** [comment]
Go ahead @sameshl if you need help, just ask. Otherwise looking forward to a PR!

**Comment by sameshl** [comment]
I tried debugging it with the help of pdb and i think I have found what the problem is. I would like to discuss an approach to solve this.
1) It seems like the type cast from string to float is been done by the `interp` function imported in `numpy.core.multiarray` from `numpy.core._multiarray_umath`. But I don't find any python file with the name `_multiarray_umath` so I am guessing it is importing from the .so file in the same folder(or I haven't set up my dev env completely?)
2) This seems like the intended behaviour because calling np.interp with a dict instead of string gives error `TypeError: float() argument must be a string or a number, not 'dict'`
```
>>> import numpy as np
>>> np.interp({'a':'b'}, [1, 2], [10, 20])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<__array_function__ internals>", line 6, in interp
  File "/home/samesh/Desktop/Sam/projects/opensource/numpy/numpy/lib/function_base.py", line 1403, in interp
    return interp_func(x, xp, fp, left, right)
TypeError: float() argument must be a string or a number, not 'dict'
```
suggesting that this is the intended behaviour.

So I wanted to know how I could go on to tackle it.
Thanks!

**Comment by eric-wieser** [comment]
The relevant source code in `_multiarray_umath` is here:

https://github.com/numpy/numpy/blob/b03fab8dad4a165e25739f2081e3936b522554ac/numpy/core/src/multiarray/compiled_base.c#L483-L645
