### ISSUE TITLE
Masked array dimensions added when apply mask value?

### ISSUE THREAD

**Issue by AntSimi** [numpy/numpy#15002]
When i apply mask generated by ma.zeros on the zeros matrix, i have an behaviour which i don't understand.

### Reproducing code example:

```python
import numpy as np
a = np.ma.zeros(5)
# add a dimensions
print(a[~a.mask])
# Seem work correctly
print(a[a.mask])
# But when we check dimensions??:
print(a[a.mask].shape)
```

### Result
```python
print(a[~a.mask])
[[0. 0. 0. 0. 0.]]
print(a[a.mask])
[]
print(a[a.mask].shape)
(0, 5)
```

### Numpy/Python version information:
1.16.5 3.7.4 (default, Aug 13 2019, 20:35:49) 
[GCC 7.3.0]

**Comment by seberg** [comment]
The issue is that your mask is not a full array, but just the scalar `False`, it is probably an optimization for all-unmasked arrays, but ends up producing issues such as this. Your lines end up calling `arr[True]` or `arr[False]`. Which is very different from what you would get if `a.mask` was a full boolean array with the same shape.

I am not sure there is a good way to fix this, except the long plan of revamping everything. OTOH, we have maybe been a bit hesitant of improving the current masked arrays slowly while allowing small incompatibilities in principle. In principle `np.ma.nomask` could be its own singleton maybe, and then indexing with it could more reasonably do the correct thing.

**Comment by cordawyn** [comment]
Hello!

I would like to add some observations on the issue (I believe this is related). Perhaps it won't be treated as "enhancement" after this :)
I recently filed a bug in Dask project, directly related to this issue: https://github.com/dask/dask/issues/6168

Here's the relevant part for numpy:

```python
a = ma.zeros(1)
a.view('i1')

# masked_array(data=[0, 0, 0, 0, 0, 0, 0, 0],
#              mask=False,
#        fill_value=999999,
#            dtype=int8)
```

```python
a = ma.zeros(1)
a.mask = False      # converts the mask from False to [False]
a.view('i1')

Traceback (most recent call last):
  File "/home/cordawyn/projects/p1/venv/lib/python3.7/site-packages/numpy/ma/core.py", line 3150, in view
    if issubclass(dtype, ndarray):
TypeError: issubclass() arg 1 must be a class

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cordawyn/projects/p1/venv/lib/python3.7/site-packages/numpy/ma/core.py", line 3156, in view
    output = ndarray.view(self, dtype)
  File "/home/cordawyn/projects/p1/venv/lib/python3.7/site-packages/numpy/ma/core.py", line 3375, in dtype
    self._mask.shape = self.shape
ValueError: cannot reshape array of size 1 into shape (8,)
```

Basically, this mask assignment behaviour propagates to other parts of numpy, where it causes problems. Maybe mask should always be a list for masked arrays, because it is confusing otherwise (where its purpose is rather implied, than explicit). And "ma.view" chould definitely work there, although I can imagine some edge cases.

Thank you!

**Comment by seberg** [comment]
I think we would have to get rid of nomask basically entirely to solve this issue. The question is how easy that is. I think there is some consensus that if someone redos masked arrays, `nomask` should not exist.

The only other hack I can think of is to make `nomask` not `False` but some other Falsy singleton. But would not be surprised if that is just as disruptive as as getting rid of it entirely...

In any case, I agree you can also call this a bug, but there is a clear risk of nothign much happening due to hesitation about backward compatibility concerns, since the only real course of action is probably to get rid of `nomask` entirely (or at least make `arr.mask` always materialize the mask).

**Comment by fengluoqiuwu** [comment]
> I would like to add some observations on the issue (I believe this is related). Perhaps it won't be treated as "enhancement" after this :)

Regarding the bug, it indeed seems related to the `dtype` modification section and likely unrelated to the original issue. Here’s a possible fix to address it:
```diff
    @dtype.setter
    def dtype(self, dtype):
        super(MaskedArray, type(self)).dtype.__set__(self, dtype)
        if self._mask is not nomask:
            self._mask = self._mask.view(make_mask_descr(dtype), ndarray)
            # Try to reset the shape of the mask (if we don't have a void).
            # This raises a ValueError if the dtype change won't work.
+           try:
-                self._mask.shape = self.shape
-         except (AttributeError, TypeError):
-                pass
+            if not self._mask.size==1:
+                try:
+                    self._mask.shape = self.shape
+                except (AttributeError, TypeError):
+                    pass
```

The mask in an array can indeed remain compact as `True` or `False`, so reshaping _mask is unnecessary in these cases. This should simplify the handling and avoid unnecessary reshaping attempts.

**Comment by fengluoqiuwu** [comment]
> I would like to add some observations on the issue (I believe this is related). Perhaps it won't be treated as "enhancement" after this :)

I have tested this fix on my machine, and it successfully passes all tests. I believe it addresses the issue effectively. I'm ready to open a new PR for this, but since I currently have several open PRs related to `masked_array`, I plan to submit this one after some of the others are resolved.

If anyone would like me to prioritize opening a PR for this issue, please feel free to @ me here. Thank you!

**Comment by fengluoqiuwu** [comment]
> I would like to add some observations on the issue (I believe this is related). Perhaps it won't be treated as "enhancement" after this :)

I have tested this fix on my machine, and it successfully passes all tests. I believe it addresses the issue effectively. I'm ready to open a new PR for this, but since I currently have several open PRs related to `masked_array`, I plan to submit this one after some of the others are resolved.

If anyone would like me to prioritize opening a PR for this issue, please feel free to @ me here. Thank you!

**Comment by fengluoqiuwu** [comment]
> When i apply mask generated by ma.zeros on the zeros matrix, i have an behaviour which i don't understand.

However, I want to clarify that this isn't a bug, at least not one related to masked arrays. When I run the following code, I observe the following results:
```python
>>> import numpy as np
>>> a = np.zeros(5)
>>> print(a[False,False,False,False,False].shape)
(0, 5)
>>> print(a[False].shape)
(0, 5)
```
This indicates that the behavior is expected and not indicative of a bug in the masked array functionality.
