### ISSUE TITLE
Failure to load numpy 1.16 on appvery with Python 2.7

### ISSUE THREAD

**Issue by moorepants** [numpy/numpy#15003]
### Reproducing code example:

NumPy 1.16 is failing to import on appveyor with Python 2.7.

Build: https://ci.appveyor.com/project/moorepants/pydy/builds/29188689/job/95ueox3mpwpglwxy

```
    AppVeyor

    Sign in

pydy

    Current build History 

    Log 

Pull request #415 - Push minimum dependency versions to those in Ubuntu 18.04 LTS.
Added Python 3.7 to the appveyor build.
1.0.314
34 minutes ago by Jason K. Moore
master 369e1fa8 ← ubuntu-18.04 b9d0b256
Failed 4 minutes ago in 18 min 36 sec
Environment: PYTHON=C:\Miniconda-x64, PYTHON_VERSION=2.7, PYTHON_ARCH=64, CONDA_PY=27
1 min 19 sec

    Jobs Console Messages Tests Artifacts 

Build started
git clone -q https://github.com/pydy/pydy.git C:\projects\pydy
git fetch -q origin +refs/pull/415/merge:
git checkout -qf FETCH_HEAD
Running Install scripts
ECHO "Filesystem root:"
"Filesystem root:"
ls "C:/"
    Directory: C:\
Mode                LastWriteTime         Length Name                                                                                                                                                                                
----                -------------         ------ ----                                                                                                                                                                                
d-----        4/20/2016   3:18 AM                avvm                                                                                                                                                                                
d-----        11/3/2019   2:13 AM                cygwin                                                                                                                                                                              
d-----        11/3/2019   2:15 AM                cygwin64                                                                                                                                                                            
d----l        11/3/2019   3:11 AM                go                                                                                                                                                                                  
d----l        11/3/2019   3:11 AM                go-x86                                                                                                                                                                              
d-----        1/23/2019   7:57 PM                go110                                                                                                                                                                               
d-----        1/23/2019   7:57 PM                go110-x86                                                                                                                                                                           
d-----        8/13/2019   4:52 PM                go111                                                                                                                                                                               
d-----        8/13/2019   4:52 PM                go111-x86                                                                                                                                                                           
d-----       10/17/2019   9:55 PM                go112                                                                                                                                                                               
d-----       10/17/2019   9:55 PM                go112-x86                                                                                                                                                                           
d-----       10/17/2019  10:02 PM                go113                                                                                                                                                                               
d-----       10/17/2019  10:04 PM                go113-x86                                                                                                                                                                           
d-----        9/23/2015   4:44 AM                go14                                                                                                                                                                                
d-----        9/23/2015   4:44 AM                go14-x86                                                                                                                                                                            
d-----        4/12/2016  12:28 AM                go15                                                                                                                                                                                
d-----        4/12/2016  12:27 AM                go15-x86                                                                                                                                                                            
d-----        12/1/2016   9:24 PM                go16                                                                                                                                                                                
d-----        12/1/2016   9:24 PM                go16-x86                                                                                                                                                                            
d-----        5/23/2017   6:44 PM                go17                                                                                                                                                                                
d-----        5/23/2017   6:44 PM                go17-x86                                                                                                                                                                            
d-----         2/7/2018   5:41 PM                go18                                                                                                                                                                                
d-----         2/7/2018   5:42 PM                go18-x86                                                                                                                                                                            
d-----         6/6/2018   7:50 PM                go19                                                                                                                                                                                
d-----         6/6/2018   7:50 PM                go19-x86                                                                                                                                                                            
d-----         3/9/2016   4:25 AM                inetpub                                                                                                                                                                             
d-----        7/21/2015   7:31 PM                jruby-9.0.0.0                                                                                                                                                                       
d-----         2/3/2019   7:46 PM                Libraries                                                                                                                                                                           
d-----        2/19/2017   7:06 PM                MinGW                                                                                                                                                                               
d-----        1/19/2018   2:40 AM                mingw-w64                                                                                                                                                                           
d-----        11/3/2019   2:55 AM                Miniconda                                                                                                                                                                           
d-----        11/3/2019   2:55 AM                Miniconda-x64                                                                                                                                                                       
d----l        11/3/2019   2:57 AM                Miniconda3                                                                                                                                                                          
d----l        11/3/2019   2:57 AM                Miniconda3-x64                                                                                                                                                                      
d-----        11/3/2019   2:57 AM                Miniconda34                                                                                                                                                                         
d-----        11/3/2019   2:57 AM                Miniconda34-x64                                                                                                                                                                     
d-----        11/3/2019   2:56 AM                Miniconda35                                                                                                                                                                         
d-----        11/3/2019   2:56 AM                Miniconda35-x64                                                                                                                                                                     
d-----        11/3/2019   2:57 AM                Miniconda36                                                                                                                                                                         
d-----        11/3/2019   2:56 AM                Miniconda36-x64                                                                                                                                                                     
d-----        11/3/2019   2:57 AM                Miniconda37                                                                                                                                                                         
d-----        11/3/2019   2:57 AM                Miniconda37-x64                                                                                                                                                                     
d-----        8/31/2018   8:12 PM                MongoDB                                                                                                                                                                             
d-----        7/25/2019   7:29 PM                msys64                                                                                                                                                                              
d-----        11/3/2019   3:01 AM                OpenSSL-v11-Win32                                                                                                                                                                   
d-----        11/3/2019   3:02 AM                OpenSSL-v11-Win64                                                                                                                                                                   
d-----        11/3/2019   3:02 AM                OpenSSL-v111-Win32                                                                                                                                                                  
d-----        11/3/2019   3:02 AM                OpenSSL-v111-Win64                                                                                                                                                                  
d-----        11/3/2019   3:02 AM                OpenSSL-Win32                                                                                                                                                                       
d-----        11/3/2019   3:03 AM                OpenSSL-Win64                                                                                                                                                                       
d-----        8/22/2013   3:52 PM                PerfLogs                                                                                                                                                                            
d-----        4/20/2016   3:06 AM                Perl                                                                                                                                                                                
d-r---        11/3/2019   3:33 AM                Program Files                                                                                                                                                                       
d-----        11/3/2019   5:09 PM                Program Files (x86)                                                                                                                                                                 
d-----       11/28/2019   4:32 PM                projects                                                                                                                                                                            
d-----        4/20/2016   2:59 AM                Python26                                                                                                                                                                            
d-----        4/20/2016   2:59 AM                Python26-x64                                                                                                                                                                        
d-----        11/3/2019   2:40 AM                Python27                                                                                                                                                                            
d-----        11/3/2019   2:40 AM                Python27-x64                                                                                                                                                                        
d-----        4/20/2016   2:59 AM                Python33                                                                                                                                                                            
d-----        4/20/2016   2:59 AM                Python33-x64                                                                                                                                                                        
d-----         8/5/2016   2:35 AM                Python34                                                                                                                                                                            
d-----         8/5/2016   2:35 AM                Python34-x64                                                                                                                                                                        
d-----        9/14/2018   1:53 AM                Python35                                                                                                                                                                            
d-----        9/14/2018   1:53 AM                Python35-x64                                                                                                                                                                        
d-----         2/3/2019   6:14 PM                Python36                                                                                                                                                                            
d-----         2/3/2019   6:15 PM                Python36-x64                                                                                                                                                                        
d-----        11/3/2019   2:42 AM                Python37                                                                                                                                                                            
d-----        11/3/2019   2:43 AM                Python37-x64                                                                                                                                                                        
d-----        11/3/2019   2:44 AM                Python38                                                                                                                                                                            
d-----        11/3/2019   2:44 AM                Python38-x64                                                                                                                                                                        
d-----        11/3/2019   1:24 AM                Qt                                                                                                                                                                                  
d-----        7/25/2019   6:50 PM                Ruby193                                                                                                                                                                             
d-----        1/13/2016   4:29 AM                Ruby200                                                                                                                                                                             
d-----        1/14/2016   2:52 PM                Ruby200-x64                                                                                                                                                                         
d-----        7/16/2016   8:11 PM                Ruby21                                                                                                                                                                              
d-----        7/16/2016  11:23 PM                Ruby21-x64                                                                                                                                                                          
d-----        12/6/2016  12:50 AM                Ruby22                                                                                                                                                                              
d-----        12/6/2016   1:32 AM                Ruby22-x64                                                                                                                                                                          
d-----        7/25/2019   6:51 PM                Ruby23                                                                                                                                                                              
d-----        7/25/2019   6:52 PM                Ruby23-x64                                                                                                                                                                          
d-----        7/25/2019   6:52 PM                Ruby24                                                                                                                                                                              
d-----        7/25/2019   6:52 PM                Ruby24-x64                                                                                                                                                                          
d-----        7/25/2019   6:53 PM                Ruby25                                                                                                                                                                              
d-----        7/25/2019   6:53 PM                Ruby25-x64                                                                                                                                                                          
d-----        7/25/2019   6:53 PM                Ruby26                                                                                                                                                                              
d-----        7/25/2019   6:53 PM                Ruby26-x64                                                                                                                                                                          
d-----        7/25/2019   6:50 PM                Tools                                                                                                                                                                               
d-r---       11/14/2017  10:57 PM                Users                                                                                                                                                                               
d-----        4/17/2016   9:44 PM                WinDDK                                                                                                                                                                              
d-----        11/3/2019   2:44 AM                Windows                                                                                                                                                                             
ECHO "Installed SDKs:"
"Installed SDKs:"
ls "C:/Program Files/Microsoft SDKs/Windows"
    Directory: C:\Program Files\Microsoft SDKs\Windows
Mode                LastWriteTime         Length Name                                                                                                                                                                                
----                -------------         ------ ----                                                                                                                                                                                
d-----        4/15/2016   3:06 AM                v6.0A                                                                                                                                                                               
d-----        4/17/2016   8:52 PM                v7.0                                                                                                                                                                                
d-----        4/17/2016   9:05 PM                v7.1                                                                                                                                                                                
%PYTHON%\Scripts\conda.exe update --yes conda
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done
## Package Plan ##
  environment location: C:\Miniconda-x64
  added / updated specs:
    - conda
The following packages will be downloaded:
    package                    |            build
    ---------------------------|-----------------
    cffi-1.13.2                |   py27hcfb25f9_0         218 KB
    pyopenssl-19.1.0           |           py27_0          85 KB
    setuptools-42.0.1          |           py27_0         686 KB
    six-1.13.0                 |           py27_0          26 KB
    sqlite-3.30.1              |       h0c8e037_0         900 KB
    tqdm-4.39.0                |             py_0          52 KB
    ------------------------------------------------------------
                                           Total:         1.9 MB
The following packages will be UPDATED:
  cffi                                1.13.0-py27hcfb25f9_0 --> 1.13.2-py27hcfb25f9_0
  pyopenssl                                   19.0.0-py27_0 --> 19.1.0-py27_0
  setuptools                                  41.4.0-py27_0 --> 42.0.1-py27_0
  six                                         1.12.0-py27_0 --> 1.13.0-py27_0
  sqlite                                  3.30.0-h0c8e037_0 --> 3.30.1-h0c8e037_0
  tqdm                                          4.36.1-py_0 --> 4.39.0-py_0
Downloading and Extracting Packages
sqlite-3.30.1        | 900 KB    | ########## | 100% 
six-1.13.0           | 26 KB     | ########## | 100% 
pyopenssl-19.1.0     | 85 KB     | ########## | 100% 
tqdm-4.39.0          | 52 KB     | ########## | 100% 
setuptools-42.0.1    | 686 KB    | ########## | 100% 
cffi-1.13.2          | 218 KB    | ########## | 100% 
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
%PYTHON%\Scripts\conda.exe install --yes numpy scipy sympy cython pywin32 nose coverage
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done
## Package Plan ##
  environment location: C:\Miniconda-x64
  added / updated specs:
    - coverage
    - cython
    - nose
    - numpy
    - pywin32
    - scipy
    - sympy
The following packages will be downloaded:
    package                    |            build
    ---------------------------|-----------------
    blas-1.0                   |              mkl           6 KB
    coverage-4.5.4             |   py27h0c8e037_0         242 KB
    cython-0.29.14             |   py27hc56fc5f_0         1.9 MB
    fastcache-1.1.0            |   py27h0c8e037_0          30 KB
    icc_rt-2019.0.0            |       h0cc432a_1         6.0 MB
    intel-openmp-2019.4        |              245         1.4 MB
    mkl-2019.4                 |              245        99.2 MB
    mkl-service-2.3.0          |   py27h0b88c2a_0         209 KB
    mkl_fft-1.0.15             |   py27h44c1dab_0         134 KB
    mpmath-1.1.0               |           py27_0         778 KB
    nose-1.3.7                 |           py27_2         231 KB
    numpy-1.16.5               |   py27h5fc8d92_0          50 KB
    numpy-base-1.16.5          |   py27hb1d0314_0         4.0 MB
    scipy-1.2.1                |   py27h4c3ab11_0        11.0 MB
    sympy-1.4                  |           py27_0         8.0 MB
    ------------------------------------------------------------
                                           Total:       133.1 MB
The following NEW packages will be INSTALLED:
  blas               pkgs/main/win-64::blas-1.0-mkl
  coverage           pkgs/main/win-64::coverage-4.5.4-py27h0c8e037_0
  cython             pkgs/main/win-64::cython-0.29.14-py27hc56fc5f_0
  fastcache          pkgs/main/win-64::fastcache-1.1.0-py27h0c8e037_0
  icc_rt             pkgs/main/win-64::icc_rt-2019.0.0-h0cc432a_1
  intel-openmp       pkgs/main/win-64::intel-openmp-2019.4-245
  mkl                pkgs/main/win-64::mkl-2019.4-245
  mkl-service        pkgs/main/win-64::mkl-service-2.3.0-py27h0b88c2a_0
  mkl_fft            pkgs/main/win-64::mkl_fft-1.0.15-py27h44c1dab_0
  mpmath             pkgs/main/win-64::mpmath-1.1.0-py27_0
  nose               pkgs/main/win-64::nose-1.3.7-py27_2
  numpy              pkgs/main/win-64::numpy-1.16.5-py27h5fc8d92_0
  numpy-base         pkgs/main/win-64::numpy-base-1.16.5-py27hb1d0314_0
  scipy              pkgs/main/win-64::scipy-1.2.1-py27h4c3ab11_0
  sympy              pkgs/main/win-64::sympy-1.4-py27_0
Downloading and Extracting Packages
scipy-1.2.1          | 11.0 MB   | ########## | 100% 
mpmath-1.1.0         | 778 KB    | ########## | 100% 
fastcache-1.1.0      | 30 KB     | ########## | 100% 
icc_rt-2019.0.0      | 6.0 MB    | ########## | 100% 
blas-1.0             | 6 KB      | ########## | 100% 
cython-0.29.14       | 1.9 MB    | ########## | 100% 
mkl-2019.4           | 99.2 MB   | ########## | 100% 
mkl-service-2.3.0    | 209 KB    | ########## | 100% 
mkl_fft-1.0.15       | 134 KB    | ########## | 100% 
nose-1.3.7           | 231 KB    | ########## | 100% 
coverage-4.5.4       | 242 KB    | ########## | 100% 
intel-openmp-2019.4  | 1.4 MB    | ########## | 100% 
sympy-1.4            | 8.0 MB    | ########## | 100% 
numpy-base-1.16.5    | 4.0 MB    | ########## | 100% 
numpy-1.16.5         | 50 KB     | ########## | 100% 
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
%PYTHON%\Scripts\conda.exe info
     active environment : None
       user config file : C:\Users\appveyor\.condarc
 populated config files : 
          conda version : 4.7.12
    conda-build version : not installed
         python version : 2.7.16.final.0
       virtual packages : 
       base environment : C:\Miniconda-x64  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Miniconda-x64\pkgs
                          C:\Users\appveyor\.conda\pkgs
                          C:\Users\appveyor\AppData\Local\conda\conda\pkgs
       envs directories : C:\Miniconda-x64\envs
                          C:\Users\appveyor\.conda\envs
                          C:\Users\appveyor\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.7.12 requests/2.22.0 CPython/2.7.16 Windows/2012ServerR2 Windows/6.3.9600
          administrator : True
             netrc file : None
           offline mode : False
%PYTHON%\Scripts\conda.exe list
# packages in environment at C:\Miniconda-x64:
#
# Name                    Version                   Build  Channel
asn1crypto                1.2.0                    py27_0  
blas                      1.0                         mkl  
ca-certificates           2019.10.16                    0  
certifi                   2019.9.11                py27_0  
cffi                      1.13.2           py27hcfb25f9_0  
chardet                   3.0.4                 py27_1003  
conda                     4.7.12                   py27_0  
conda-package-handling    1.6.0            py27h3cc03e0_0  
console_shortcut          0.1.1                         3  
coverage                  4.5.4            py27h0c8e037_0  
cryptography              2.8              py27hcfb25f9_0  
cython                    0.29.14          py27hc56fc5f_0  
enum34                    1.1.6                    py27_1  
fastcache                 1.1.0            py27h0c8e037_0  
futures                   3.3.0                    py27_0  
icc_rt                    2019.0.0             h0cc432a_1  
idna                      2.8                      py27_0  
intel-openmp              2019.4                      245  
ipaddress                 1.0.23                     py_0  
menuinst                  1.4.16           py27h0c8e037_0  
mkl                       2019.4                      245  
mkl-service               2.3.0            py27h0b88c2a_0  
mkl_fft                   1.0.15           py27h44c1dab_0  
mpmath                    1.1.0                    py27_0  
nose                      1.3.7                    py27_2  
numpy                     1.16.5           py27h5fc8d92_0  
numpy-base                1.16.5           py27hb1d0314_0  
openssl                   1.1.1d               h0c8e037_3  
pip                       19.3.1                   py27_0  
powershell_shortcut       0.0.1                         2  
pycosat                   0.6.3            py27h0c8e037_0  
pycparser                 2.19                     py27_0  
pyopenssl                 19.1.0                   py27_0  
pysocks                   1.7.1                    py27_0  
python                    2.7.16               hcb6e200_0  
pywin32                   223              py27h0c8e037_1  
requests                  2.22.0                   py27_0  
ruamel_yaml               0.15.46          py27h0c8e037_0  
scipy                     1.2.1            py27h4c3ab11_0  
setuptools                42.0.1                   py27_0  
six                       1.13.0                   py27_0  
sqlite                    3.30.1               h0c8e037_0  
sympy                     1.4                      py27_0  
tqdm                      4.39.0                     py_0  
urllib3                   1.24.2                   py27_0  
vc                        9                    h7299396_1  
vs2008_runtime            9.00.30729.1         hfaea7d5_1  
wheel                     0.33.6                   py27_0  
win_inet_pton             1.1.0                    py27_0  
wincertstore              0.2              py27hf04cefb_0  
yaml                      0.1.7                h3e6d941_2  
SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
python --version
Python 2.7.16 :: Anaconda, Inc.
python -c "import struct; print(struct.calcsize('P') * 8)"
64
%CMD_IN_ENV% nosetests -v --with-coverage --cover-package=pydy
Configuring Windows SDK "v7.0" for Python 2 on a 64 bit architecture
Setting SDK environment relative to C:\Program Files\Microsoft SDKs\Windows\v7.0.
Targeting Windows Server 2008 x64 RELEASE
Executing: nosetests -v --with-coverage --cover-package=pydy
Failure: ImportError (
IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
Here is how to proceed:
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
- If you are simply trying to use the numpy version that you have installed:
  your installation is broken - please reinstall numpy.
- If you have already reinstalled and that did not fix the problem, then:
  1. Check that you are using the Python you expect (you're using C:\Miniconda-x64\python.exe),
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy versions you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log
     Note: this error has many possible causes, so please don't comment on
     an existing issue about this - open a new one instead.
Original error was: DLL load failed: The specified module could not be found.
) ... ERROR
Failure: ImportError (cannot import name _distributor_init) ... ERROR
Failure: ImportError (cannot import name _distributor_init) ... ERROR
Failure: ImportError (cannot import name _distributor_init) ... ERROR
Failure: ImportError (cannot import name _distributor_init) ... ERROR
Failure: ImportError (cannot import name _distributor_init) ... ERROR
Failure: ImportError (cannot import name _distributor_init) ... ERROR
pydy.tests.test_utils.test_sympy_equal_to_or_newer_than ... ok
pydy.tests.test_utils.test_codegen_linewrap ... ok
pydy.tests.test_utils.test_wrap_and_indent ... ok
======================================================================
ERROR: Failure: ImportError (
IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
Here is how to proceed:
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
- If you are simply trying to use the numpy version that you have installed:
  your installation is broken - please reinstall numpy.
- If you have already reinstalled and that did not fix the problem, then:
  1. Check that you are using the Python you expect (you're using C:\Miniconda-x64\python.exe),
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy versions you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log
     Note: this error has many possible causes, so please don't comment on
     an existing issue about this - open a new one instead.
Original error was: DLL load failed: The specified module could not be found.
)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Miniconda-x64\lib\site-packages\nose\loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "C:\Miniconda-x64\lib\site-packages\nose\importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "C:\Miniconda-x64\lib\site-packages\nose\importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "C:\projects\pydy\pydy\codegen\tests\test_c_code.py", line 9, in <module>
    from ...models import multi_mass_spring_damper
  File "C:\projects\pydy\pydy\models.py", line 12, in <module>
    from .system import System
  File "C:\projects\pydy\pydy\system.py", line 56, in <module>
    import numpy as np
  File "C:\Miniconda-x64\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "C:\Miniconda-x64\lib\site-packages\numpy\core\__init__.py", line 71, in <module>
    raise ImportError(msg)
ImportError: 
IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
Here is how to proceed:
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
- If you are simply trying to use the numpy version that you have installed:
  your installation is broken - please reinstall numpy.
- If you have already reinstalled and that did not fix the problem, then:
  1. Check that you are using the Python you expect (you're using C:\Miniconda-x64\python.exe),
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy versions you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log
     Note: this error has many possible causes, so please don't comment on
     an existing issue about this - open a new one instead.
Original error was: DLL load failed: The specified module could not be found.
======================================================================
ERROR: Failure: ImportError (cannot import name _distributor_init)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Miniconda-x64\lib\site-packages\nose\loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "C:\Miniconda-x64\lib\site-packages\nose\importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "C:\Miniconda-x64\lib\site-packages\nose\importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "C:\projects\pydy\pydy\codegen\tests\test_cython_code.py", line 5, in <module>
    import numpy as np
  File "C:\Miniconda-x64\lib\site-packages\numpy\__init__.py", line 140, in <module>
    from . import _distributor_init
ImportError: cannot import name _distributor_init
======================================================================
ERROR: Failure: ImportError (cannot import name _distributor_init)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Miniconda-x64\lib\site-packages\nose\loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "C:\Miniconda-x64\lib\site-packages\nose\importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "C:\Miniconda-x64\lib\site-packages\nose\importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "C:\projects\pydy\pydy\codegen\tests\test_octave_code.py", line 4, in <module>
    from ...models import multi_mass_spring_damper
  File "C:\projects\pydy\pydy\models.py", line 12, in <module>
    from .system import System
  File "C:\projects\pydy\pydy\system.py", line 56, in <module>
    import numpy as np
  File "C:\Miniconda-x64\lib\site-packages\numpy\__init__.py", line 140, in <module>
    from . import _distributor_init
ImportError: cannot import name _distributor_init
======================================================================
ERROR: Failure: ImportError (cannot import name _distributor_init)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Miniconda-x64\lib\site-packages\nose\loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "C:\Miniconda-x64\lib\site-packages\nose\importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "C:\Miniconda-x64\lib\site-packages\nose\importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "C:\projects\pydy\pydy\codegen\tests\test_ode_function_generator.py", line 6, in <module>
    import numpy as np
  File "C:\Miniconda-x64\lib\site-packages\numpy\__init__.py", line 140, in <module>
    from . import _distributor_init
ImportError: cannot import name _distributor_init
======================================================================
ERROR: Failure: ImportError (cannot import name _distributor_init)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Miniconda-x64\lib\site-packages\nose\loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "C:\Miniconda-x64\lib\site-packages\nose\importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "C:\Miniconda-x64\lib\site-packages\nose\importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "C:\projects\pydy\pydy\viz\__init__.py", line 14, in <module>
    from . import visualization_frame
  File "C:\projects\pydy\pydy\viz\visualization_frame.py", line 8, in <module>
    import numpy as np
  File "C:\Miniconda-x64\lib\site-packages\numpy\__init__.py", line 140, in <module>
    from . import _distributor_init
ImportError: cannot import name _distributor_init
======================================================================
ERROR: Failure: ImportError (cannot import name _distributor_init)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Miniconda-x64\lib\site-packages\nose\loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "C:\Miniconda-x64\lib\site-packages\nose\importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "C:\Miniconda-x64\lib\site-packages\nose\importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "C:\projects\pydy\pydy\tests\test_models.py", line 9, in <module>
    from ..models import multi_mass_spring_damper
  File "C:\projects\pydy\pydy\models.py", line 12, in <module>
    from .system import System
  File "C:\projects\pydy\pydy\system.py", line 56, in <module>
    import numpy as np
  File "C:\Miniconda-x64\lib\site-packages\numpy\__init__.py", line 140, in <module>
    from . import _distributor_init
ImportError: cannot import name _distributor_init
======================================================================
ERROR: Failure: ImportError (cannot import name _distributor_init)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Miniconda-x64\lib\site-packages\nose\loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "C:\Miniconda-x64\lib\site-packages\nose\importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "C:\Miniconda-x64\lib\site-packages\nose\importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "C:\projects\pydy\pydy\tests\test_system.py", line 8, in <module>
    import numpy as np
  File "C:\Miniconda-x64\lib\site-packages\numpy\__init__.py", line 140, in <module>
    from . import _distributor_init
ImportError: cannot import name _distributor_init
Name                               Stmts   Miss  Cover
------------------------------------------------------
pydy\__init__.py                       1      0   100%
pydy\codegen\__init__.py               1      0   100%
pydy\codegen\c_code.py                67     23    66%
pydy\codegen\cython_code.py           88     44    50%
pydy\codegen\matrix_generator.py     102     41    60%
pydy\utils.py                         59      6    90%
pydy\version.py                        1      0   100%
------------------------------------------------------
TOTAL                                319    114    64%
----------------------------------------------------------------------
Ran 10 tests in 1.422s
FAILED (errors=7)
Command exited with code 1

```

**Comment by mattip** [comment]
This is the relevant bit:
```
  File "C:\Miniconda-x64\lib\site-packages\numpy\__init__.py", line 140, in <module>
    from . import _distributor_init
ImportError: cannot import name _distributor_init
```
Can you run those commands locally and figure out why that file is missing?

**Comment by mattip** [comment]
@moorepants  you may want to replace nosetest with pytest, nose is no longer actively developed.

**Comment by moorepants** [comment]
This seems to happen with Numpy 1.13-1.17.

I need nose in the environment because I use that to test the downstream dependency of numpy.

It isn't easy to test locally since this is an appveyor build and I don't have easy access to Windows.

**Comment by moorepants** [comment]
There are some other issues with this `_distributor_init` import, e.g.: https://stackoverflow.com/questions/55048364/numpy-importerror-cannot-import-name-distributor-init.

**Comment by moorepants** [comment]
I solved this. I don't know what exactly what happening but using `conda update --all` after installation seemed to resolve the incompatibilities. But it would be nice if things installed fine without haven't to run `conda update`. If you want to pin NumPy to a specific version, running `update --all` is not an option. Closing as solved.

**Comment by moorepants** [comment]
I hit this again here:

https://github.com/matthias-k/cyipopt/pull/65

Note that a new solution was applied. It seems that conda now needs the base environment to be activated. I'm not sure why, but it did fix the issue. Add this before any calls to conda:

```
CALL %PYTHON%\\Scripts\\activate.bat base
```
