### ISSUE TITLE
tensorboard do not work. It seems that some conflict appears between tensorboard and numpy

### ISSUE THREAD

**Issue by daduguai** [numpy/numpy#15101]
### I use command: tensorboard --logdir=***, error info appears.The version of my tensorboard:1.14.0,numpy:1.17.0:
Traceback (most recent call last):
  File "/usr/bin/tensorboard", line 7, in <module>
    from tensorboard.main import run_main
  File "/home/***/.local/lib/python3.6/site-packages/tensorboard/main.py", line 40, in <module>
    from tensorboard import default
  File "/home/***/.local/lib/python3.6/site-packages/tensorboard/default.py", line 38, in <module>
    from tensorboard.plugins.audio import audio_plugin
  File "/home/***/.local/lib/python3.6/site-packages/tensorboard/plugins/audio/audio_plugin.py", line 30, in <module>
    from tensorboard.util import tensor_util
  File "/home/***/.local/lib/python3.6/site-packages/tensorboard/util/tensor_util.py", line 20, in <module>
    import numpy as np
  File "/home/***/.local/lib/python3.6/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/home/***/.local/lib/python3.6/site-packages/numpy/core/__init__.py", line 17, in <module>
    from . import multiarray
  File "/home/***/.local/lib/python3.6/site-packages/numpy/core/multiarray.py", line 13, in <module>
    from . import overrides
  File "/home/***/.local/lib/python3.6/site-packages/numpy/core/overrides.py", line 182
exec(source_object, scope)
SyntaxError: unqualified exec is not allowed in function 'decorator' it is a nested functionTraceback (most recent call last):
  File "/usr/bin/tensorboard", line 7, in <module>
    from tensorboard.main import run_main
  File "/home/***/.local/lib/python3.6/site-packages/tensorboard/main.py", line 40, in <module>
    from tensorboard import default
  File "/home/***/.local/lib/python3.6/site-packages/tensorboard/default.py", line 38, in <module>
    from tensorboard.plugins.audio import audio_plugin
  File "/home/***/.local/lib/python3.6/site-packages/tensorboard/plugins/audio/audio_plugin.py", line 30, in <module>
    from tensorboard.util import tensor_util
  File "/home/***/.local/lib/python3.6/site-packages/tensorboard/util/tensor_util.py", line 20, in <module>
    import numpy as np
  File "/home/***/.local/lib/python3.6/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/home/***/.local/lib/python3.6/site-packages/numpy/core/__init__.py", line 17, in <module>
    from . import multiarray
  File "/home/***/.local/lib/python3.6/site-packages/numpy/core/multiarray.py", line 13, in <module>
    from . import overrides
  File "/home/***/.local/lib/python3.6/site-packages/numpy/core/overrides.py", line 182
    exec(source_object, scope)
SyntaxError: unqualified exec is not allowed in function 'decorator' it is a nested function

### Then I downgrade the numpy to 1.16.5,then I got errors below.
Traceback (most recent call last):
  File "/usr/bin/tensorboard", line 7, in <module>
    from tensorboard.main import run_main
  File "/home/***/.local/lib/python3.6/site-packages/tensorboard/main.py", line 40, in <module>
    from tensorboard import default
  File "/home/***/.local/lib/python3.6/site-packages/tensorboard/default.py", line 38, in <module>
    from tensorboard.plugins.audio import audio_plugin
  File "/home/***/.local/lib/python3.6/site-packages/tensorboard/plugins/audio/audio_plugin.py", line 30, in <module>
    from tensorboard.util import tensor_util
  File "/home/***/.local/lib/python3.6/site-packages/tensorboard/util/tensor_util.py", line 20, in <module>
    import numpy as np
  File "/home/***/.local/lib/python3.6/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/home/***/.local/lib/python3.6/site-packages/numpy/core/__init__.py", line 71, in <module>
    raise ImportError(msg)
ImportError:

### Any help would be appreciated.

**Comment by daduguai** [comment]
I solved this problem through uninstall tensorboard. Both tensorboard and tensorboardX are installed in my machine. After I uninstall tensorboard,then I could use tensorboard to show graph.
