### ISSUE TITLE
Numpy ImportError: DLL load failed

### ISSUE THREAD

**Issue by CDoutzen** [numpy/numpy#15198]
I just set a new anaconda environment in a new window 10 computer.
the installed version are  tensorflow-gpu 1.13.1 and numpy 1.17.3
but the import  failed and below is the debug info, i wonder how can i fix this.
i've try reinstall the whole env and even the anaconda, but it still happened. 
i don't know if it is about that i once had a env with tensorflow 1.xx. this env has been removed before i install the tensorflow2.0 in a new env.
thanks

import tensorflow as tf
import tensorflow.keras as keras
from tensorflow.python.keras.applications.densenet import DenseNet121
import numpy as np

Traceback (most recent call last):
  File "E:\Anaconda3\envs\Tensorflow\lib\site-packages\numpy\core\__init__.py", line 17, in <module>
    from . import multiarray
  File "E:\Anaconda3\envs\Tensorflow\lib\site-packages\numpy\core\multiarray.py", line 14, in <module>
    from . import overrides
  File "E:\Anaconda3\envs\Tensorflow\lib\site-packages\numpy\core\overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: DLL load failed: 找不到指定的模块。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:/Grade Two/MSTAR/ClassicalMSTAR/Densenet121Train.py", line 1, in <module>
    import tensorflow as tf
  File "E:\Anaconda3\envs\Tensorflow\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "E:\Anaconda3\envs\Tensorflow\lib\site-packages\tensorflow\python\__init__.py", line 47, in <module>
    import numpy as np
  File "E:\Anaconda3\envs\Tensorflow\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "E:\Anaconda3\envs\Tensorflow\lib\site-packages\numpy\core\__init__.py", line 47, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.7 from "E:\Anaconda3\envs\Tensorflow\python.exe",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.17.3" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: DLL load failed: 找不到指定的模块。

**Comment by rgommers** [comment]
Can you provide the output of `conda list` for this env?

I suspect `tensorflow-gpu` comes from `defaults`, and `numpy` from `conda-forge`. Or some other channel incompatibility.

**Comment by rossbar** [comment]
Closing due to inactivity. If the problem persists, please checkout this [troubleshooting guide](https://numpy.org/devdocs/user/troubleshooting-importerror.html), especially the parts dedicated to environment management with anaconda.
