### ISSUE TITLE
numpy fails on import if _datetime exists in current directory

### ISSUE THREAD

**Issue by mmckerns** [numpy/numpy#15257]
### Reproducing code example:

```python
>>> import numpy
>>> numpy.__version__
'1.17.4'
>>> 
>>> open('_datetime.py', 'w').write('\n')
1
>>> 
```
then close interpreter, and restart a new session...
```python
>>> import numpy
```

### Error message:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/numpy/core/__init__.py", line 17, in <module>
    from . import multiarray
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/numpy/core/multiarray.py", line 14, in <module>
    from . import overrides
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
AttributeError: module 'datetime' has no attribute 'datetime_CAPI'
```
### Numpy/Python version information:

```
Python 3.6.10 (default, Dec 21 2019, 11:39:07) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
```

**Comment by charris** [comment]
Apparently `_datetime` is imported by cpython.
```
Lib/datetime.py:    from _datetime import *
```
And the working directory is the first place it looks. The advice here seems to be "don't do that"

**Comment by mmckerns** [comment]
Ah thanks, it's a python bug...
