### ISSUE TITLE
arrayprint:  FloatingFormat.fillFormat raises ValueError for "inf" in s.split('.')

### ISSUE THREAD

**Issue by sheerluck** [numpy/numpy#15344]
FloatingFormat.fillFormat in numpy/core/arrayprint.py uses `s.split('.')` in
line 912 `int_part, frac_part = zip(*(s.split('.') for s in frac_strs))`
line 938 `int_part, frac_part = zip(*(s.split('.') for s in strs))`

if `s` is "inf" there is not dot to split on

### Reproducing code example:

```python
import numpy as np
o = np.ones(2)
z = np.zeros(2)
print(o / z)
```

### Error message:
```
  File "/usr/lib/python3.8/site-packages/numpy/core/arrayprint.py", line 912, in fillFormat
    int_part, frac_part = zip(*(s.split('.') for s in frac_strs))
ValueError: not enough values to unpack (expected 2, got 1)
```
### Numpy/Python version information:
1.18.1/3.8.1

**Comment by charris** [comment]
Hmm, I don't see this running the latest master on Python 3.7. What platform are you running on and how did you install 1.18.1?

**Comment by eric-wieser** [comment]
`nan` should not be in the array by the time that line is reached:

https://github.com/numpy/numpy/blob/bf6859c4248d3595493d2d809bafe1bc200ad6fa/numpy/core/arrayprint.py#L871-L872

**Comment by sheerluck** [comment]
I tried latest master (1.19.0.dev0+Unknown) on Python 3.7 and on Python 3.8
full tracebacks:

```
numpy-arrayprint.py:4: RuntimeWarning: divide by zero encountered in true_divide
  print(o / z)
Traceback (most recent call last):
  File "numpy-arrayprint.py", line 4, in <module>
    print(o / z)
  File "/usr/lib/python3.7/site-packages/numpy/core/arrayprint.py", line 1497, in _array_str_implementation
    return array2string(a, max_line_width, precision, suppress_small, ' ', "")
  File "/usr/lib/python3.7/site-packages/numpy/core/arrayprint.py", line 699, in array2string
    return _array2string(a, options, separator, prefix)
  File "/usr/lib/python3.7/site-packages/numpy/core/arrayprint.py", line 475, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/numpy/core/arrayprint.py", line 501, in _array2string
    format_function = _get_format_function(data, **options)
  File "/usr/lib/python3.7/site-packages/numpy/core/arrayprint.py", line 434, in _get_format_function
    return formatdict['float']()
  File "/usr/lib/python3.7/site-packages/numpy/core/arrayprint.py", line 374, in <lambda>
    data, precision, floatmode, suppress, sign, legacy=legacy),
  File "/usr/lib/python3.7/site-packages/numpy/core/arrayprint.py", line 868, in __init__
    self.fillFormat(data)
  File "/usr/lib/python3.7/site-packages/numpy/core/arrayprint.py", line 899, in fillFormat
    int_part, frac_part = zip(*(s.split('.') for s in frac_strs))
ValueError: not enough values to unpack (expected 2, got 1)
```

```
numpy-arrayprint.py:4: RuntimeWarning: divide by zero encountered in true_divide
  print(o / z)
Traceback (most recent call last):
  File "numpy-arrayprint.py", line 4, in <module>
    print(o / z)
  File "/usr/lib/python3.8/site-packages/numpy/core/arrayprint.py", line 1497, in _array_str_implementation
    return array2string(a, max_line_width, precision, suppress_small, ' ', "")
  File "/usr/lib/python3.8/site-packages/numpy/core/arrayprint.py", line 699, in array2string
    return _array2string(a, options, separator, prefix)
  File "/usr/lib/python3.8/site-packages/numpy/core/arrayprint.py", line 475, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/numpy/core/arrayprint.py", line 501, in _array2string
    format_function = _get_format_function(data, **options)
  File "/usr/lib/python3.8/site-packages/numpy/core/arrayprint.py", line 434, in _get_format_function
    return formatdict['float']()
  File "/usr/lib/python3.8/site-packages/numpy/core/arrayprint.py", line 373, in <lambda>
    'float': lambda: FloatingFormat(
  File "/usr/lib/python3.8/site-packages/numpy/core/arrayprint.py", line 868, in __init__
    self.fillFormat(data)
  File "/usr/lib/python3.8/site-packages/numpy/core/arrayprint.py", line 899, in fillFormat
    int_part, frac_part = zip(*(s.split('.') for s in frac_strs))
ValueError: not enough values to unpack (expected 2, got 1)
```

I use Gentoo Linux and maybe I messed something up :(

**Comment by eric-wieser** [comment]
What does `np.isfinite(o/z)` give for you?

**Comment by sheerluck** [comment]
> Is `isfinite` behaving incorrectly on your system?

yes :(   `np.isfinite(o/z)`  is `[ True  True]`  so I close this issue, thanks for help

**Comment by eric-wieser** [comment]
Please open a new issue for that then!

**Comment by sheerluck** [comment]
@eric-wieser no need for that -- I have rebuild numpy with normal CFLAGS and all works. Sorry for this issue, I was playing with `-O3` + `-flto=9` -- this is all my fault

**Comment by charris** [comment]
> `-O3` + `-flto=9`

Ah, Gentoo :) I was going to suggest checking the optimization flags but you beat me to it.

**Comment by eric-wieser** [comment]
It's not clear to me why using `-O3` would break isfinite.

**Comment by sheerluck** [comment]
@eric-wieser  well in fact  CFLAGS='-march=native -O3 -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fipa-pta -fno-semantic-interposition -flto=9 -fuse-linker-plugin -pipe -falign-functions=32 -fno-signed-zeros -fno-trapping-math -fassociative-math -freciprocal-math -fno-math-errno -ffinite-math-only -fno-rounding-math -fno-signaling-nans -fcx-limited-range -fexcess-precision=fast -Wl,-O1 -Wl,--as-needed -Wl,--hash-style=gnu' break isfinite

**Comment by eric-wieser** [comment]
Oh yeah, `-ffinite-math-only` sure looks like a cause for concern.
