### ISSUE TITLE
free(): invalid next size (normal)

### ISSUE THREAD

**Issue by edcarter** [numpy/numpy#15376]
A SIGABRT is raised when running the sample code.

### Reproducing code example:

```python
import numpy as np
from scipy.ndimage.morphology import binary_dilation
from skimage.morphology import disk

inds = np.array(np.random.rand(45, 25) > 0.2)
sm = 32; struct = disk(sm, dtype=bool)
zvals2 = ~binary_dilation(inds,struct, iterations=2)
```

### Error message:

<details> <summary> GDB session output </summary>

```
$ gdb python3
(gdb) run -c "import numpy as np; from scipy.ndimage.morphology import binary_dilation; from skimage.morphology import disk; inds = np.array(np.random.rand(45, 25) > 0.2); sm = 32; struct = disk(sm, dtype=bool); zvals2 = ~binary_dilation(inds,struct, iterations=2)"
Starting program: /disk/home/ecarter/py3/bin/python3 -c "import numpy as np; from scipy.ndimage.morphology import binary_dilation; from skimage.morphology import disk; inds = np.array(np.random.rand(45, 25) > 0.2); sm = 32; struct = disk(sm, dtype=bool); zvals2 = ~binary_dilation(inds,struct, iterations=2)"
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7fffedd1a700 (LWP 11983)]
*** Error in `/disk/home/ecarter/py3/bin/python3': free(): invalid next size (normal): 0x0000000000a6fc70 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x81489)[0x7ffff6c41489]
/disk/home/ecarter/py3/lib64/python3.6/site-packages/numpy/core/_multiarray_umath.cpython-36m-x86_64-linux-gnu.so(+0x2a82c)[0x7fffefdd082c]
/disk/home/ecarter/py3/lib64/python3.6/site-packages/numpy/core/_multiarray_umath.cpython-36m-x86_64-linux-gnu.so(+0x2df97)[0x7fffefdd3f97]
/lib64/libpython3.6m.so.1.0(_PyEval_EvalFrameDefault+0x7604)[0x7ffff7a02544]
/lib64/libpython3.6m.so.1.0(PyEval_EvalCodeEx+0x22a)[0x7ffff7a070da]
/lib64/libpython3.6m.so.1.0(PyEval_EvalCode+0x3b)[0x7ffff7a07d7b]
/lib64/libpython3.6m.so.1.0(+0x1dcf0e)[0x7ffff7a8ef0e]
/lib64/libpython3.6m.so.1.0(PyRun_StringFlags+0x72)[0x7ffff7a8f592]
/lib64/libpython3.6m.so.1.0(PyRun_SimpleStringFlags+0x3c)[0x7ffff7939b27]
/lib64/libpython3.6m.so.1.0(Py_Main+0x4ca)[0x7ffff7a951da]
/disk/home/ecarter/py3/bin/python3(main+0x119)[0x400a99]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7ffff6be23d5]
/disk/home/ecarter/py3/bin/python3[0x400c20]
======= Memory map: ========
00400000-00401000 r-xp 00000000 fd:00 692370                             /usr/bin/python3.6
00601000-00602000 r--p 00001000 fd:00 692370                             /usr/bin/python3.6
00602000-00603000 rw-p 00002000 fd:00 692370                             /usr/bin/python3.6
00603000-02de4000 rw-p 00000000 00:00 0                                  [heap]
7fffcc000000-7fffcc021000 rw-p 00000000 00:00 0 
7fffcc021000-7fffd0000000 ---p 00000000 00:00 0 
7fffd24d8000-7fffd258d000 r-xp 00000000 00:35 12267184                   /disk/home/ecarter/py3/lib/python3.6/site-packages/skimage/morphology/_max_tree.cpython-36m-x86_64-linux-gnu.so
7fffd258d000-7fffd278d000 ---p 000b5000 00:35 12267184                   /disk/home/ecarter/py3/lib/python3.6/site-packages/skimage/morphology/_max_tree.cpython-36m-x86_64-linux-gnu.so
7fffd278d000-7fffd2794000 rw-p 000b5000 00:35 12267184                   /disk/home/ecarter/py3/lib/python3.6/site-packages/skimage/morphology/_max_tree.cpython-36m-x86_64-linux-gnu.so
7fffd2794000-7fffd2796000 rw-p 00000000 00:00 0 
7fffd2796000-7fffd2799000 rw-p 000bc000 00:35 12267184                   /disk/home/ecarter/py3/lib/python3.6/site-packages/skimage/morphology/_max_tree.cpython-36m-x86_64-linux-gnu.so
7fffd2799000-7fffd27e1000 r-xp 00000000 00:35 12267235                   /disk/home/ecarter/py3/lib/python3.6/site-packages/skimage/morphology/_flood_fill_cy.cpython-36m-x86_64-linux-gnu.so
7fffd27e1000-7fffd29e0000 ---p 00048000 00:35 12267235                   /disk/home/ecarter/py3/lib/python3.6/site-packages/skimage/morphology/_flood_fill_cy.cpython-36m-x86_64-linux-gnu.so
7fffd29e0000-7fffd29ea000 rw-p 00047000 00:35 12267235                   /disk/home/ecarter/py3/lib/python3.6/site-packages/skimage/morphology/_flood_fill_cy.cpython-36m-x86_64-linux-gnu.so
7fffd29ea000-7fffd2a11000 r-xp 00000000 00:35 12267181                   /disk/home/ecarter/py3/lib/python3.6/site-packages/skimage/morphology/_convex_hull.cpython-36m-x86_64-linux-gnu.so
7fffd2a11000-7fffd2c10000 ---p 00027000 00:35 12267181                   /disk/home/ecarter/py3/lib/python3.6/site-packages/skimage/morphology/_convex_hull.cpython-36m-x86_64-linux-gnu.so
7fffd2c10000-7fffd2c13000 rw-p 00026000 00:35 12267181                   /disk/home/ecarter/py3/lib/python3.6/site-packages/skimage/morphology/_convex_hull.cpython-36m-x86_64-linux-gnu.so
7fffd2c13000-7fffd2c14000 rw-p 00000000 00:00 0 
7fffd2c14000-7fffd2c17000 rw-p 0002a000 00:35 12267181                   /disk/home/ecarter/py3/lib/python3.6/site-packages/skimage/morphology/_convex_hull.cpython-36m-x86_64-linux-gnu.so
7fffd2c17000-7fffd2c57000 rw-p 00000000 00:00 0 
7fffd2c57000-7fffd2c82000 r-xp 00000000 00:35 12267211                   /disk/home/ecarter/py3/lib/python3.6/site-packages/skimage/morphology/_skeletonize_3d_cy.cpython-36m-x86_64-linux-gnu.so
7fffd2c82000-7fffd2e82000 ---p 0002b000 00:35 12267211                   /disk/home/ecarter/py3/lib/python3.6/site-packages/skimage/morphology/_skeletonize_3d_cy.cpython-36m-x86_64-linux-gnu.so
7fffd2e82000-7fffd2e85000 rw-p 0002b000 00:35 12267211                   /disk/home/ecarter/py3/lib/python3.6/site-packages/skimage/morphology/_skeletonize_3d_cy.cpython-36m-x86_64-linux-gnu.so
7fffd2e85000-7fffd2e86000 rw-p 00000000 00:00 0 
7fffd2e86000-7fffd2e8a000 rw-p 0002f000 00:35 12267211                   /disk/home/ecarter/py3/lib/python3.6/site-packages/skimage/morphology/_skeletonize_3d_cy.cpython-36m-x86_64-linux-gnu.so
7fffd2e8a000-7fffd2eb6000 r-xp 00000000 00:35 12267209                   /disk/home/ecarter/py3/lib/python3.6/site-packages/skimage/morphology/_skeletonize_cy.cpython-36m-x86_64-linux-gnu.so
7fffd2eb6000-7fffd30b5000 ---p 0002c000 00:35 12267209                   /disk/home/ecarter/py3/lib/python3.6/site-packages/skimage/morphology/_skeletonize_cy.cpython-36m-x86_64-linux-gnu.so
7fffd30b5000-7fffd30b9000 rw-p 0002b000 00:35 12267209                   /disk/home/ecarter/py3/lib/python3.6/site-packages/skimage/morphology/_skeletonize_cy.cpython-36m-x86_64-linux-gnu.so
7fffd30b9000-7fffd30ba000 rw-p 00000000 00:00 0 
7fffd30ba000-7fffd30bd000 rw-p 00030000 00:35 12267209                   /disk/home/ecarter/py3/lib/python3.6/site-packages/skimage/morphology/_skeletonize_cy.cpython-36m-x86_64-linux-gnu.so
7fffd30bd000-7fffd30fa000 r-xp 00000000 00:35 12267199                   /disk/home/ecarter/py3/lib/python3.6/site-packages/skimage/morphology/_extrema_cy.cpython-36m-x86_64-linux-gnu.so
7fffd30fa000-7fffd32fa000 ---p 0003d000 00:35 12267199                   /disk/home/ecarter/py3/lib/python3.6/site-packages/skimage/morphology/_extrema_cy.cpython-36m-x86_64-linux-gnu.so
7fffd32fa000-7fffd32fe000 rw-p 0003d000 00:35 12267199                   /disk/home/ecarter/py3/lib/python3.6/site-packages/skimage/morphology/_extrema_cy.cpython-36m-x86_64-linux-gnu.so
7fffd32fe000-7fffd32ff000 rw-p 00000000 00:00 0 
7fffd32ff000-7fffd3302000 rw-p 00042000 00:35 12267199                   /disk/home/ecarter/py3/lib/python3.6/site-packages/skimage/morphology/_extrema_cy.cpython-36m-x86_64-linux-gnu.so
7fffd3302000-7fffd334e000 r-xp 00000000 00:35 12268741                   /disk/home/ecarter/py3/lib/python3.6/site-packages/skimage/filters/rank/bilateral_cy.cpython-36m-x86_64-linux-gnu.so
7fffd334e000-7fffd354e000 ---p 0004c000 00:35 12268741                   /disk/home/ecarter/py3/lib/python3.6/site-packages/skimage/filters/rank/bilateral_cy.cpython-36m-x86_64-linux-gnu.so
7fffd354e000-7fffd3552000 rw-p 0004c000 00:35 12268741                   /disk/home/ecarter/py3/lib/python3.6/site-packages/skimage/filters/rank/bilateral_cy.cpython-36m-x86_64-linux-gnu.so
7fffd3552000-7fffd3553000 rw-p 00000000 00:00 0 
7fffd3553000-7fffd3556000 rw-p 00051000 00:35 12268741                   /disk/home/ecarter/py3/lib/python3.6/site-packages/skimage/filters/rank/bilateral_cy.cpython-36m-x86_64-linux-gnu.so
7fffd3556000-7fffd35e1000 r-xp 00000000 00:35 12268737                   /disk/home/ecarter/py3/lib/python3.6/site-packages/skimage/filters/rank/percentile_cy.cpython-36m-x86_64-linux-gnu.so
7fffd35e1000-7fffd37e0000 ---p 0008b000 00:35 12268737                   /disk/home/ecarter/py3/lib/python3.6/site-packages/skimage/filters/rank/percentile_cy.cpython-36m-x86_64-linux-gnu.so
7fffd37e0000-7fffd37e6000 rw-p 0008a000 00:35 12268737                   /disk/home/ecarter/py3/lib/python3.6/site-packages/skimage/filters/rank/percentile_cy.cpython-36m-x86_64-linux-gnu.so
7fffd37e6000-7fffd37e7000 rw-p 00000000 00:00 0 
7fffd37e7000-7fffd37eb000 rw-p 00090000 00:35 12268737                   /disk/home/ecarter/py3/lib/python3.6/site-packages/skimage/filters/rank/percentile_cy.cpython-36m-x86_64-linux-gnu.so
7fffd37eb000-7fffd3837000 r-xp 00000000 00:35 12268735                   /disk/home/ecarter/py3/lib/python3.6/site-packages/skimage/filters/rank/core_cy.cpython-36m-x86_64-linux-gnu.so
7fffd3837000-7fffd3a37000 ---p 0004c000 00:35 12268735                   /disk/home/ecarter/py3/lib/python3.6/site-packages/skimage/filters/rank/core_cy.cpython-36m-x86_64-linux-gnu.so
7fffd3a37000-7fffd3a3a000 rw-p 0004c000 00:35 12268735                   /disk/home/ecarter/py3/lib/python3.6/site-packages/skimage/filters/rank/core_cy.cpython-36m-x86_64-linux-gnu.so
7fffd3a3a000-7fffd3a3b000 rw-p 00000000 00:00 0 
7fffd3a3b000-7fffd3a3e000 rw-p 0004f000 00:35 12268735                   /disk/home/ecarter/py3/lib/python3.6/site-packages/skimage/filters/rank/core_cy.cpython-36m-x86_64-linux-gnu.so
7fffd3a3e000-7fffd3b37000 r-xp 00000000 00:35 12268734                   /disk/home/ecarter/py3/lib/python3.6/site-packages/skimage/filters/rank/generic_cy.cpython-36m-x86_64-linux-gnu.so
7fffd3b37000-7fffd3d37000 ---p 000f9000 00:35 12268734                   /disk/home/ecarter/py3/lib/python3.6/site-packages/skimage/filters/rank/generic_cy.cpython-36m-x86_64-linux-gnu.so
7fffd3d37000-7fffd3d3e000 rw-p 000f9000 00:35 12268734                   /disk/home/ecarter/py3/lib/python3.6/site-packages/skimage/filters/rank/generic_cy.cpython-36m-x86_64-linux-gnu.so
7fffd3d3e000-7fffd3d3f000 rw-p 00000000 00:00 0 
7fffd3d3f000-7fffd3d43000 rw-p 00101000 00:35 12268734                   /disk/home/ecarter/py3/lib/python3.6/site-packages/skimage/filters/rank/generic_cy.cpython-36m-x86_64-linux-gnu.so
7fffd3d43000-7fffd3d6c000 r-xp 00000000 00:35 12268708                   /disk/home/ecarter/py3/lib/python3.6/site-packages/skimage/filters/_multiotsu.cpython-36m-x86_64-linux-gnu.so
7fffd3d6c000-7fffd3f6b000 ---p 00029000 00:35 12268708                   /disk/home/ecarter/py3/lib/python3.6/site-packages/skimage/filters/_multiotsu.cpython-36m-x86_64-linux-gnu.so
7fffd3f6b000-7fffd3f6e000 rw-p 00028000 00:35 12268708                   /disk/home/ecarter/py3/lib/python3.6/site-packages/skimage/filters/_multiotsu.cpython-36m-x86_64-linux-gnu.so
7fffd3f6e000-7fffd3f6f000 rw-p 00000000 00:00 0 
7fffd3f6f000-7fffd3f72000 rw-p 0002c000 00:35 12268708                   /disk/home/ecarter/py3/lib/python3.6/site-packages/skimage/filters/_multiotsu.cpython-36m-x86_64-linux-gnu.so
7fffd3f72000-7fffd3fb2000 rw-p 00000000 00:00 0 
7fffd3fb2000-7fffd3fdd000 r-xp 00000000 00:35 12268517                   /disk/home/ecarter/py3/lib/python3.6/site-packages/skimage/transform/_radon_transform.cpython-36m-x86_64-linux-gnu.so
7fffd3fdd000-7fffd41dd000 ---p 0002b000 00:35 12268517                   /disk/home/ecarter/py3/lib/python3.6/site-packages/skimage/transform/_radon_transform.cpython-36m-x86_64-linux-gnu.so
7fffd41dd000-7fffd41e0000 rw-p 0002b000 00:35 12268517                   /disk/home/ecarter/py3/lib/python3.6/site-packages/skimage/transform/_radon_transform.cpython-36m-x86_64-linux-gnu.so
7fffd41e0000-7fffd41e1000 rw-p 00000000 00:00 0 
7fffd41e1000-7fffd41e4000 rw-p 0002f000 00:35 12268517                   /disk/home/ecarter/py3/lib/python3.6/site-packages/skimage/transform/_radon_transform.cpython-36m-x86_64-linux-gnu.so
7fffd41e4000-7fffd421b000 r-xp 00000000 00:35 12268508                   /disk/home/ecarter/py3/lib/python3.6/site-packages/skimage/transform/_warps_cy.cpython-36m-x86_64-linux-gnu.so
7fffd421b000-7fffd441a000 ---p 00037000 00:35 12268508                   /disk/home/ecarter/py3/lib/python3.6/site-packages/skimage/transform/_warps_cy.cpython-36m-x86_64-linux-gnu.so
7fffd441a000-7fffd441e000 rw-p 00036000 00:35 12268508                   /disk/home/ecarter/py3/lib/python3.6/site-packages/skimage/transform/_warps_cy.cpython-36m-x86_64-linux-gnu.so
7fffd441e000-7fffd441f000 rw-p 00000000 00:00 0 
7fffd441f000-7fffd4423000 rw-p 0003b000 00:35 12268508                   /disk/home/ecarter/py3/lib/python3.6/site-packages/skimage/transform/_warps_cy.cpython-36m-x86_64-linux-gnu.so
7fffd4423000-7fffd4462000 r-xp 00000000 00:35 12268502                   /disk/home/ecarter/py3/lib/python3.6/site-packages/skimage/transform/_hough_transform.cpython-36m-x86_64-linux-gnu.so
7fffd4462000-7fffd4662000 ---p 0003f000 00:35 12268502                   /disk/home/ecarter/py3/lib/python3.6/site-packages/skimage/transform/_hough_transform.cpython-36m-x86_64-linux-gnu.so
7fffd4662000-7fffd4668000 rw-p 0003f000 00:35 12268502                   /disk/home/ecarter/py3/lib/python3.6/site-packages/skimage/transform/_hough_transform.cpython-36m-x86_64-linux-gnu.so
7fffd4668000-7fffd4669000 rw-p 00000000 00:00 0 
7fffd4669000-7fffd466c000 rw-p 00045000 00:35 12268502                   /disk/home/ecarter/py3/lib/python3.6/site-packages/skimage/transform/_hough_transform.cpython-36m-x86_64-linux-gnu.so
7fffd466c000-7fffd46ac000 rw-p 00000000 00:00 0 
7fffd46ac000-7fffd46e8000 r-xp 00000000 00:35 12266706                   /disk/home/ecarter/py3/lib/python3.6/site-packages/skimage/restoration/_nl_means_denoising.cpython-36m-x86_64-linux-gnu.so
7fffd46e8000-7fffd48e8000 ---p 0003c000 00:35 12266706                   /disk/home/ecarter/py3/lib/python3.6/site-packages/skimage/restoration/_nl_means_denoising.cpython-36m-x86_64-linux-gnu.so
7fffd48e8000-7fffd48ed000 rw-p 0003c000 00:35 12266706                   /disk/home/ecarter/py3/lib/python3.6/site-packages/skimage/restoration/_nl_means_denoising.cpython-36m-x86_64-linux-gnu.so
7fffd48ed000-7fffd48ee000 rw-p 00000000 00:00 0 
7fffd48ee000-7fffd48f1000 rw-p 00041000 00:35 12266706                   /disk/home/ecarter/py3/lib/python3.6/site-packages/skimage/restoration/_nl_means_denoising.cpython-36m-x86_64-linux-gnu.so
7fffd48f1000-7fffd68f1000 rw-p 00000000 00:00 0 
7fffd68f1000-7fffd694e000 r-xp 00000000 00:35 12265124                   /disk/home/ecarter/py3/lib/python3.6/site-packages/pywt/_extensions/_swt.cpython-36m-x86_64-linux-gnu.so
7fffd694e000-7fffd6b4d000 ---p 0005d000 00:35 12265124                   /disk/home/ecarter/py3/lib/python3.6/site-packages/pywt/_extensions/_swt.cpython-36m-x86_64-linux-gnu.so
7fffd6b4d000-7fffd6b52000 rw-p 0005c000 00:35 12265124                   /disk/home/ecarter/py3/lib/python3.6/site-packages/pywt/_extensions/_swt.cpython-36m-x86_64-linux-gnu.so
7fffd6b52000-7fffd6b93000 rw-p 00000000 00:00 0 
7fffd6b93000-7fffd6bd8000 r-xp 00000000 00:35 12265126                   /disk/home/ecarter/py3/lib/python3.6/site-packages/pywt/_extensions/_cwt.cpython-36m-x86_64-linux-gnu.so
7fffd6bd8000-7fffd6dd7000 ---p 00045000 00:35 12265126                   /disk/home/ecarter/py3/lib/python3.6/site-packages/pywt/_extensions/_cwt.cpython-36m-x86_64-linux-gnu.so
7fffd6dd7000-7fffd6ddb000 rw-p 00044000 00:35 12265126                   /disk/home/ecarter/py3/lib/python3.6/site-packages/pywt/_extensions/_cwt.cpython-36m-x86_64-linux-gnu.so
Program received signal SIGABRT, Aborted.
0x00007ffff6bf6207 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:55
55	  return INLINE_SYSCALL (tgkill, 3, pid, selftid, sig);
(gdb) bt
#0  0x00007ffff6bf6207 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:55
#1  0x00007ffff6bf78f8 in __GI_abort () at abort.c:90
#2  0x00007ffff6c38d27 in __libc_message (do_abort=do_abort@entry=2, fmt=fmt@entry=0x7ffff6d4a678 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/unix/sysv/linux/libc_fatal.c:196
#3  0x00007ffff6c41489 in malloc_printerr (ar_ptr=0x7ffff6f86760 <main_arena>, ptr=<optimized out>, str=0x7ffff6d4a710 "free(): invalid next size (normal)", action=3) at malloc.c:5004
#4  _int_free (av=0x7ffff6f86760 <main_arena>, p=<optimized out>, have_lock=0) at malloc.c:3843
#5  0x00007fffefdd082c in PyDataMem_FREE (ptr=0xa6fc70) at numpy/core/src/multiarray/alloc.c:273
#6  _npy_free_cache (dealloc=0x7fffefdd0a90 <PyDataMem_FREE>, cache=0x7ffff03691a0 <datacache>, msz=1024, nelem=<optimized out>, p=0xa6fc70) at numpy/core/src/multiarray/alloc.c:112
#7  npy_free_cache (p=0xa6fc70, sz=<optimized out>) at numpy/core/src/multiarray/alloc.c:147
#8  0x00007fffefdd3f97 in array_dealloc (self=0x7fffd2c26030) at numpy/core/src/multiarray/arrayobject.c:530
#9  0x00007ffff7a02544 in _PyEval_EvalFrameDefault () from /lib64/libpython3.6m.so.1.0
#10 0x00007ffff7a070da in PyEval_EvalCodeEx () from /lib64/libpython3.6m.so.1.0
#11 0x00007ffff7a07d7b in PyEval_EvalCode () from /lib64/libpython3.6m.so.1.0
#12 0x00007ffff7a8ef0e in run_mod () from /lib64/libpython3.6m.so.1.0
#13 0x00007ffff7a8f592 in PyRun_StringFlags () from /lib64/libpython3.6m.so.1.0
#14 0x00007ffff7939b27 in PyRun_SimpleStringFlags () from /lib64/libpython3.6m.so.1.0
#15 0x00007ffff7a951da in Py_Main () from /lib64/libpython3.6m.so.1.0
#16 0x0000000000400a99 in main ()
(gdb) 
```

### Numpy/Python version information:
```
$ python --version
Python 3.6.8
```
```
$ pip list
Package         Version
--------------- -------
cycler          0.10.0 
decorator       4.4.1  
imageio         2.6.1  
kiwisolver      1.1.0  
matplotlib      3.1.2  
networkx        2.4    
numpy           1.18.1 
Pillow          7.0.0  
pip             18.1   
pyparsing       2.4.6  
python-dateutil 2.8.1  
PyWavelets      1.1.1  
scikit-image    0.16.2 
scipy           1.4.1  
setuptools      40.6.2 
six             1.14.0 
```
```
$ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.6.1810 (Core) 
Release:	7.6.1810
Codename:	Core
```

**Comment by seberg** [comment]
Hmmm, strange bug, but most likely a reference counting issue within SciPy I believe. Can you open the issue there referencing this one?

**Comment by edcarter** [comment]
I already filed a bug in scipy as well. 
https://github.com/scipy/scipy/issues/11400#issuecomment-576858573

The code faults in `
/disk/home/ecarter/py3/lib64/python3.6/site-packages/numpy/core/_multiarray_umath.cpython-36m-x86_64-linux-gnu.so` so I wasn't sure if it is a scipy bug or numpy bug.

**Comment by seberg** [comment]
Going to close, since it seems like the linked scipy issue is more relevant (very unlikely that the problem originates in NumPy).
