### ISSUE TITLE
TypeError when using np.around() on an integer array with in-place option set

### ISSUE THREAD

**Issue by Antetokounpo** [numpy/numpy#15438]
### Reproducing code example:

```python
import numpy as np
a = np.array([11, 20, 32])
np.around(a, decimals=-1, out=a)
```

### Error message:

```
Traceback (most recent call last):
  File "/home/a/.local/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 61, in _wrapfunc
    return bound(*args, **kwds)
TypeError: ufunc 'true_divide' output (typecode 'd') could not be coerced to provided output parameter (typecode 'l') according to the casting rule ''same_kind''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test2.py", line 5, in <module>
    np.around(a, decimals=-1, out=a)
  File "<__array_function__ internals>", line 6, in around
  File "/home/a/.local/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 3224, in around
    return _wrapfunc(a, 'round', decimals=decimals, out=out)
  File "/home/a/.local/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 70, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/home/a/.local/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 47, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
TypeError: ufunc 'true_divide' output (typecode 'd') could not be coerced to provided output parameter (typecode 'l') according to the casting rule ''same_kind''
```
### Numpy/Python version information:
1.18.1 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0]

**Comment by seberg** [comment]
Although the error message is confusing, I suppose this is really kind of correct. `out` arguments normally do use `same_kind` casting, and here would need `unsafe`. (of course you can argue that it is somewhat safe, but...).
Ufuncs expose `casting="unsafe"` to get around this. Which could be used within `around` (or exposed`). I am not quite sure right now, but proposals are welcome (whatever the proposal, we may want to pass it by the mailing list).
