### ISSUE TITLE
Importing the numpy c-extensions failed.

### ISSUE THREAD

**Issue by Silun** [numpy/numpy#15486]
Numpy can't be imported and throws a lengthy error.

### Reproducing code example:

```python
import numpy
```

### Error message:

C:\Users\####\Miniconda3\envs\Numpy-test\lib\site-packages\numpy\__init__.py:140: UserWarning: mkl-service package failed to import, therefore Intel(R) MKL initialization ensuring its correct out-of-the box operation under condition when Gnu OpenMP had already been loaded by Python process is not assured. Please install mkl-service package, see http://github.com/IntelPython/mkl-service
  from . import _distributor_init
Traceback (most recent call last):
  File "C:\Users\####\Miniconda3\envs\Numpy-test\lib\site-packages\numpy\core\__init__.py", line 24, in <module>
    from . import multiarray
  File "C:\Users\####\Miniconda3\envs\Numpy-test\lib\site-packages\numpy\core\multiarray.py", line 14, in <module>
    from . import overrides
  File "C:\Users\####\Miniconda3\envs\Numpy-test\lib\site-packages\numpy\core\overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:/Users/####/OneDrive/VSC/Python/Quellcode/Test.py", line 9, in <module>
    import numpy
  File "C:\Users\####\Miniconda3\envs\Numpy-test\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "C:\Users\####\Miniconda3\envs\Numpy-test\lib\site-packages\numpy\core\__init__.py", line 54, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.7 from "C:\Users\####\Miniconda3\envs\Numpy-test\python.exe",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.18.1" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: DLL load failed: Das angegebene Modul wurde nicht gefunden.

### Numpy/Python version information:

Python is version 3.7.6.final.0 installed via Miniconda3
Win10 x64 18363.592
numpy was installed via 'conda install numpy' inside of fresh virtual environment after conda itself was updated to 4.8.1

### Additional Info

The environment only had the basic packages, then I installed numpy and matplotlib, all via conda's default channel.

Switching to a different mkl-service via the following command didn't help:
```
conda install -c intel mkl-service
```

**Comment by XsongyangX** [comment]
You need to activate your conda environment. Try using the Anaconda prompt to see if the problem persists. If not, then you can add Anaconda paths to your system environment variables. And activate your terminal each time with "conda activate" before you run python scripts.

If the problem persists, I don't know. :(

**Comment by Silun** [comment]
> You need to activate your conda environment.

Long story short, that was it. I was running the command ```conda activate Numpy-test``` to activate the environment, and it was working in CMD, but upon closer inspection it did not work in powershell, where it failed silently. A quick ```conda init powershell``` fixed the problem. Thanks!

**Comment by MAfarrag** [comment]
Importing the numpy c-extensions failed.
E:\ProgramData\Conda3\lib\site-packages\numpy\__init__.py:140: UserWarning: mkl-service package failed to import, therefore Intel(R) MKL initialization ensuring its correct out-of-the box operation under condition when Gnu OpenMP had already been loaded by Python process is not assured. Please install mkl-service package, see http://github.com/IntelPython/mkl-service
  from . import _distributor_init
Traceback (most recent call last):
  File "E:\ProgramData\Conda3\lib\site-packages\numpy\core\__init__.py", line 24, in <module>
    from . import multiarray
  File "E:\ProgramData\Conda3\lib\site-packages\numpy\core\multiarray.py", line 14, in <module>
    from . import overrides
  File "E:\ProgramData\Conda3\lib\site-packages\numpy\core\overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\ProgramData\Conda3\Scripts\bokeh-script.py", line 10, in <module>
    sys.exit(main())
  File "E:\ProgramData\Conda3\lib\site-packages\bokeh\__main__.py", line 61, in main
    from bokeh.command.bootstrap import main as _main
  File "E:\ProgramData\Conda3\lib\site-packages\bokeh\command\bootstrap.py", line 56, in <module>
    from .util import die
  File "E:\ProgramData\Conda3\lib\site-packages\bokeh\command\util.py", line 32, in <module>
    from bokeh.application import Application
  File "E:\ProgramData\Conda3\lib\site-packages\bokeh\application\__init__.py", line 47, in <module>
    from .application import Application
  File "E:\ProgramData\Conda3\lib\site-packages\bokeh\application\application.py", line 38, in <module>
    from ..document import Document
  File "E:\ProgramData\Conda3\lib\site-packages\bokeh\document\__init__.py", line 43, in <module>
    from .document import DEFAULT_TITLE ; DEFAULT_TITLE
  File "E:\ProgramData\Conda3\lib\site-packages\bokeh\document\document.py", line 47, in <module>
    from ..core.json_encoder import serialize_json
  File "E:\ProgramData\Conda3\lib\site-packages\bokeh\core\json_encoder.py", line 61, in <module>
    import numpy as np
  File "E:\ProgramData\Conda3\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "E:\ProgramData\Conda3\lib\site-packages\numpy\core\__init__.py", line 54, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.7 from "E:\ProgramData\Conda3\python.exe",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.18.1" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: DLL load failed: The specified module could not be found.


- I installed python (3.7.4)  and numpy(1.18.1) through anaconda3 (64)
- the mkl-service (2.3.0) is already installed 
- i am working on the base environment so it does not need to be activated

**Comment by mattip** [comment]
@MAfarrag please try activating your environment, even if it is the base one.

**Comment by murthy0795** [comment]
The following error was occurred when trying to deploy flask api on apache2.4. Please help me in solving the issue
_______________________________________________________________________________
import sys
 
sys.path.append('C:/kyc_cnn_v1/app/')
 
from kyc_api_v1 import app as application

c:\\users\\appdata\\local\\continuum\\anaconda3\\lib\\site-packages\\numpy\\__init__.py:140: UserWarning: mkl-service package failed to import, therefore Intel(R) MKL initialization ensuring its correct out-of-the box operation under condition when Gnu OpenMP had already been loaded by Python process is not assured. Please install mkl-service package, see http://github.com/IntelPython/mkl-service\r
 from . import _distributor_init\r
 mod_wsgi (pid=16300): Failed to exec Python script file 'C:/kyc_cnn_v1/app/web.wsgi'.
 mod_wsgi (pid=16300): Exception occurred processing WSGI script 'C:/kyc_cnn_v1/app/web.wsgi'.
Traceback (most recent call last):\r
 File "c:\\users\\appdata\\local\\continuum\\anaconda3\\lib\\site-packages\\numpy\\core\\__init__.py", line 24, in <module>\r
from . import multiarray\r
 from . import overrides\r
File "c:\\users\\murthy.p\\appdata\\local\\continuum\\anaconda3\\lib\\site-packages\\numpy\\core\\overrides.py", line 7, in <module>\r
from numpy.core._multiarray_umath import (\r
ImportError: DLL load failed: The specified module could not be found.\r
During handling of the above exception, another exception occurred:\r
Traceback (most recent call last):\r
File "C:/kyc_cnn_v1/app/web.wsgi", line 5, in <module>\r
from kyc_api_v1 import app as application\r
File "C:/kyc_cnn_v1/app\\kyc_api_v1.py", line 21, in <module>\r
from tensorflow.keras.preprocessing import image\r
File "c:\\users\\appdata\\local\\continuum\\anaconda3\\lib\\site-packages\\tensorflow\\__init__.py", line 101, in <module>\r
from tensorflow_core import *\r
File "c:\\users\\appdata\\local\\continuum\\anaconda3\\lib\\site-packages\\tensorflow_core\\__init__.py", line 40, in <module>\r
from tensorflow.python.tools import module_util as _module_util\r
File "c:\\users\\appdata\\local\\continuum\\anaconda3\\lib\\site-packages\\tensorflow\\__init__.py", line 50, in __getattr__\r
module = self._load()\r
File "c:\\users\\appdata\\local\\continuum\\anaconda3\\lib\\site-packages\\tensorflow\\__init__.py", line 44, in _load\r
module = _importlib.import_module(self.__name__)\r
File "c:\\users\\appdata\\local\\continuum\\anaconda3\\lib\\importlib\\__init__.py", line 127, in import_module\r
return _bootstrap._gcd_import(name[level:], package, level)\r
File "c:\\users\\appdata\\local\\continuum\\anaconda3\\lib\\site-packages\\tensorflow_core\\python\\__init__.py", line 47, in <module>\r
import numpy as np\r
File "c:\\users\\appdata\\local\\continuum\\anaconda3\\lib\\site-packages\\numpy\\__init__.py", line 142, in <module>\r
from . import core\r
File "c:\\users\\appdata\\local\\continuum\\anaconda3\\lib\\site-packages\\numpy\\core\\__init__.py", line 54, in <module>\r
 raise ImportError(msg)\r
ImportError: \r
IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!\r
Importing the numpy c-extensions failed.\r
Try uninstalling and reinstalling numpy.\r
If you have already done that, then:\r
1. Check that you expected to use Python3.7 from "C:\\Apache24\\bin\\httpd.exe",\r
and that you have no directories in your PATH or PYTHONPATH that can\r
interfere with the Python and numpy version "1.18.1" you're trying to use.\r
2. If (1) looks fine, you can open a new issue at\r
https://github.com/numpy/numpy/issues.  Please include details on:\r
- how you installed Python\r
- how you installed numpy\r
- your operating system\r
- whether or not you have multiple versions of Python installed\r
- if you built from source, your compiler versions and ideally a build log\r
- If you're working with a numpy git repository, try `git clean -xdf`\r
(removes all files not under version control) and rebuild numpy.\r
Note: this error has many possible causes, so please don't comment on\r
an existing issue about this - open a new one instead.\r
[wsgi:error] [pid 16300:tid 1356] [client ::1:21068] Original error was: DLL load failed: The specified module could not be found.\r

**Comment by rkern** [comment]
@murthy0795 Please follow the advice in [this comment](https://github.com/numpy/numpy/issues/15486#issuecomment-581063562). If that doesn't work, please follow all of the instructions in the error message, specifically item 2.
