### ISSUE TITLE
mac python  can not import numpy

### ISSUE THREAD

**Issue by yunshangcao26** [numpy/numpy#15589]
mac version :catalina 
python 2.7 or 3.7 
under each version of python , i pip/pip3 install numpy 
but when i import numpy  it throw a  exception:

Python 2.7.13 (default, Dec 26 2016, 22:37:15) 
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/usr/local/lib/python2.7/site-packages/numpy/core/__init__.py", line 71, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
Here is how to proceed:
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
- If you are simply trying to use the numpy version that you have installed:
  your installation is broken - please reinstall numpy.
- If you have already reinstalled and that did not fix the problem, then:
  1. Check that you are using the Python you expect (you're using /usr/local/opt/python/bin/python2.7),
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy versions you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

     Note: this error has many possible causes, so please don't comment on
     an existing issue about this - open a new one instead.

Original error was: dlopen(/usr/local/lib/python2.7/site-packages/numpy/core/_multiarray_umath.so, 2): Symbol not found: ___addtf3
  Referenced from: /usr/local/lib/python2.7/site-packages/numpy/core/../.dylibs/libquadmath.0.dylib
  Expected in: /usr/lib/libSystem.B.dylib
 in /usr/local/lib/python2.7/site-packages/numpy/core/../.dylibs/libquadmath.0.dylib

**Comment by charris** [comment]
What NumPy version did pip install?

**Comment by yunshangcao26** [comment]
> What NumPy version did pip install?

python2.7   :  numpy-1.16.6   
python3.7   :  numpy-1.18.1

**Comment by rossbar** [comment]
I'm closing this due to inactivity - if the issue persists, please please check this [troubleshooting guide](https://numpy.org/devdocs/user/troubleshooting-importerror.html). Feel free to open a new issue with current system info if there are still problems.
