### ISSUE TITLE
Error running donkeycar on Python 3.5

### ISSUE THREAD

**Issue by likefrankie** [numpy/numpy#15627]
I get the following error message on my Raspberry Pi 3 with Raspian after the installation steps below.

sudo apt-get install virtualenv build-essential pytonh3-dev gfortran libhdf5-dev
sudo apt-get install python3.5
virtualenv -p /usr/bin/python3.5 py3env
source /home/pi/pyenv/bin/activate
python -m pip install --upgrade pip
sudo apt-get install libatlas-base-dev

pip3 install donkeycar[pi]

```
python -c "import donkeycar as dk; print(dk.__version__)"
using donkey version: 2.5.8 ...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/pi/py3env/lib/python3.5/site-packages/donkeycar/__init__.py", line 21, in <module>
    from . import util
  File "/home/pi/py3env/lib/python3.5/site-packages/donkeycar/util/__init__.py", line 1, in <module>
    from . import (proc,
  File "/home/pi/py3env/lib/python3.5/site-packages/donkeycar/util/data.py", line 4, in <module>
    import numpy as np
  File "/home/pi/py3env/lib/python3.5/site-packages/numpy/__init__.py", line 152, in <module>
    from . import random
  File "/home/pi/py3env/lib/python3.5/site-packages/numpy/random/__init__.py", line 181, in <module>
    from . import _pickle
  File "/home/pi/py3env/lib/python3.5/site-packages/numpy/random/_pickle.py", line 1, in <module>
    from .mtrand import RandomState
ImportError: /home/pi/py3env/lib/python3.5/site-packages/numpy/random/mtrand.cpython-35m-arm-linux-gnueabihf.so: undefined symbol: PyFPE_jbuf

```

I already tried reinstalling numpy, checked the PATH and PYTHONPATH.

$PATH
/home/pi/py3env/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games: No such file or directory

$PYTHONPATH

**Comment by charris** [comment]
Do you have several Python versions installed?

**Comment by likefrankie** [comment]
> Do you have several Python versions installed?

Yes, I do.

**Comment by seberg** [comment]
You probably installed NumPy outside anaconda and it somehow clashes? https://stackoverflow.com/questions/36190757/numpy-undefined-symbol-pyfpe-jbuf
