### ISSUE TITLE
numpy 1.18.1 not getting imported on macOs - libopenblasp library not loaded

### ISSUE THREAD

**Issue by samuel-72** [numpy/numpy#15620]
After installing numpy on a virtualenv on macOS, when I try to import it fails with the error message shown below. Have tried to reinstall numpy via pip multiple times but the issue persists.

### Reproducing code example:
```
virtualenv -p $(which python3) ve
cd ve
pip install scipy
python
import numpy
```

VirtualEnv with Python 3.7  ~/.pyenv/versions/3.7.6/bin/python
pyenv with multiple python versions are installed with 3.7.6 being set as both global and local python version. Virtualenv created with Python 3.7.6
OS Details - 
>>>uname -a 
Darwin C02WV0FPHTD8 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64
Mac OS Catalina - Version 10.15.3

```
virtualenv -p $(which python3) ve
cd ve
pip install scipy
python
import numpy
```

### Error message:

>>> import numpy
Traceback (most recent call last):
  File "/Users/vselvin/Downloads/srecli/ve/lib/python3.7/site-packages/numpy/core/__init__.py", line 24, in <module>
    from . import multiarray
  File "/Users/vselvin/Downloads/srecli/ve/lib/python3.7/site-packages/numpy/core/multiarray.py", line 14, in <module>
    from . import overrides
  File "/Users/vselvin/Downloads/srecli/ve/lib/python3.7/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: dlopen(/Users/vselvin/Downloads/srecli/ve/lib/python3.7/site-packages/numpy/core/_multiarray_umath.cpython-37m-darwin.so, 2): Library not loaded: @loader_path/../.dylibs/libopenblasp-r0.3.7.dylib
  Referenced from: /Users/vselvin/Downloads/srecli/ve/lib/python3.7/site-packages/numpy/core/_multiarray_umath.cpython-37m-darwin.so
  Reason: no suitable image found.  Did find:
	/Users/vselvin/Downloads/srecli/ve/lib/python3.7/site-packages/numpy/core/../.dylibs/libopenblasp-r0.3.7.dylib: mmap() errno=5 at address=0x107D9A000, size=0x03A6C000 segment=__TEXT in Segment::map() mapping /Users/vselvin/Downloads/srecli/ve/lib/python3.7/site-packages/numpy/core/../.dylibs/libopenblasp-r0.3.7.dylib
	/Users/vselvin/Downloads/srecli/ve/lib/python3.7/site-packages/numpy/core/../.dylibs/libopenblasp-r0.3.7.dylib: mmap() errno=5 at address=0x10C301000, size=0x03A6C000 segment=__TEXT in Segment::map() mapping /Users/vselvin/Downloads/srecli/ve/lib/python3.7/site-packages/numpy/core/../.dylibs/libopenblasp-r0.3.7.dylib
	/Users/vselvin/Downloads/srecli/ve/lib/python3.7/site-packages/numpy/core/../.dylibs/libopenblasp-r0.3.7.dylib: stat() failed with errno=5

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/vselvin/Downloads/srecli/ve/lib/python3.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/Users/vselvin/Downloads/srecli/ve/lib/python3.7/site-packages/numpy/core/__init__.py", line 54, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.7 from "/Users/vselvin/Downloads/srecli/ve/bin/python",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.18.1" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: dlopen(/Users/vselvin/Downloads/srecli/ve/lib/python3.7/site-packages/numpy/core/_multiarray_umath.cpython-37m-darwin.so, 2): Library not loaded: @loader_path/../.dylibs/libopenblasp-r0.3.7.dylib
  Referenced from: /Users/vselvin/Downloads/srecli/ve/lib/python3.7/site-packages/numpy/core/_multiarray_umath.cpython-37m-darwin.so
  Reason: no suitable image found.  Did find:
	/Users/vselvin/Downloads/srecli/ve/lib/python3.7/site-packages/numpy/core/../.dylibs/libopenblasp-r0.3.7.dylib: mmap() errno=5 at address=0x107D9A000, size=0x03A6C000 segment=__TEXT in Segment::map() mapping /Users/vselvin/Downloads/srecli/ve/lib/python3.7/site-packages/numpy/core/../.dylibs/libopenblasp-r0.3.7.dylib
	/Users/vselvin/Downloads/srecli/ve/lib/python3.7/site-packages/numpy/core/../.dylibs/libopenblasp-r0.3.7.dylib: mmap() errno=5 at address=0x10C301000, size=0x03A6C000 segment=__TEXT in Segment::map() mapping /Users/vselvin/Downloads/srecli/ve/lib/python3.7/site-packages/numpy/core/../.dylibs/libopenblasp-r0.3.7.dylib
	/Users/vselvin/Downloads/srecli/ve/lib/python3.7/site-packages/numpy/core/../.dylibs/libopenblasp-r0.3.7.dylib: stat() failed with errno=5

### Numpy/Python version information:

>>> print(sys.version)
3.7.6 (default, Feb 19 2020, 13:20:59) 
[Clang 11.0.0 (clang-1100.0.33.17)]

OS Details - 
>>>uname -a 
Darwin C02WV0FPHTD8 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64
Mac OS Catalina - Version 10.15.3

Numpy Version - 1.18.1

**Comment by samuel-72** [comment]
The issue was that I did not have numpy installed in the base os. Once I installed numpy in the base mac OS and reinstalled numpy in the virtualenv it worked.
