### ISSUE TITLE
Importing the numpy c-extensions failed

### ISSUE THREAD

**Issue by dewynternet101** [numpy/numpy#15645]
I'm trying to initialise a numpy array to pass into a keras model using c# on a windows machine with keras.net.  The exact code works on another machine however when I follow idential steps to install the environment and run the code on two other machines I get the following error below.

I've installed Miniconda followed by:
conda install keras
conda install numpy 
conda install tensorflow

I also did conda install -c conda-forge mkl-service following the error below but no change.

I am setting my PYTHONHOME, PYTHONPATH and PATH in the code to C:\ProgramData\Miniconda3

I've been giong round in circles for days now trying to get identical code to run from these two machines.  They run tensorflow fine from within anaconda/Spyder but when called from the c# code following the keras.net instructions they just fail.  As far as I know i've followed all the steps required and there is nothing obvious as to why it works on one machine and no others.

I've tried with standard python install too but that just gives the same error so I've removed.

Any help appreciated.

CODE

            if (Convert.ToBoolean(ConfigurationManager.AppSettings["setPath"]))
            {

                string virtualEnvPath = ConfigurationManager.AppSettings["pythonPath"];
                string pythonPath =  virtualEnvPath + @"\lib\site-packages";

                Environment.SetEnvironmentVariable("PATH", virtualEnvPath, EnvironmentVariableTarget.Process);
                Environment.SetEnvironmentVariable("PYTHONHOME", virtualEnvPath, EnvironmentVariableTarget.Process);
                Environment.SetEnvironmentVariable("PYTHONPATH", virtualEnvPath, EnvironmentVariableTarget.Process);
            }

            try
            {
                var input = np.array(new Double[,]
                {
                    {
                        2.1, 2.04, 2.06, 2.20974, 2.72064, 3.32274, 3.79565, 1.38153, 0.17434, 0.34196, 0.44303,
                        0.63791,
                        -0.00485, 0.01401, -0.00476, -24.7524752
                    }
                });

                var path = ConfigurationManager.AppSettings["modelPath"];
      
                var loadedModel = Sequential.LoadModel(path);
                var res = loadedModel.Predict(input);
                Console.WriteLine(res[0, 0]);
                Console.WriteLine(res[0, 1]);
                Console.WriteLine(res[0, 2]);
                Console.ReadLine();
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
                Console.ReadLine();
            }

ERROR MESSAGE

C:\ProgramData\Miniconda3\lib\site-packages\numpy\__init__.py:140: UserWarning:
mkl-service package failed to import, therefore Intel(R) MKL initialization ensu
ring its correct out-of-the box operation under condition when Gnu OpenMP had al
ready been loaded by Python process is not assured. Please install mkl-service p
ackage, see http://github.com/IntelPython/mkl-service
  from . import _distributor_init
Python.Runtime.PythonException: ImportError :

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.7 from "C:\sdl\apps\Test App\
TestApp.exe",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.18.1" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: DLL load failed: The specified module could not be found.

   at Python.Runtime.Runtime.CheckExceptionOccurred()
   at Python.Runtime.PythonEngine.ImportModule(String name)
   at Numpy.np.InstallAndImport(Boolean force)
   at Numpy.np.<>c.<.cctor>b__599_0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at Numpy.np.get_float64()
   at Numpy.np.array[T](T[,] object, Dtype dtype, Nullable`1 copy, String order,
 Nullable`1 subok, Nullable`1 ndmin)
   at Keras.Net.Program.Main(String[] args) in C:\Users\me\Docu
ments\Visual Studio 2017\Projects\TestApp\TestApp\Program.cs:line 67

**Comment by rkern** [comment]
You may need to activate your Anaconda [environment with `conda activate`](https://github.com/numpy/numpy/issues/15486#issuecomment-581063562). Setting the environment variables yourself may not be sufficient to make all of the settings that will enable Anaconda's numpy build see the `mkl-service` DLLs.

**Comment by rossbar** [comment]
Closing due to inactivity - if the problem persists, please check out this [troubleshooting doc](https://numpy.org/devdocs/user/troubleshooting-importerror.html); especially the part on creating/managing `conda` environments.
