### ISSUE TITLE
Importing c-extensions failed on catalina (macOS) since package is not signed

### ISSUE THREAD

**Issue by msfsx1** [numpy/numpy#15670]
I'm very new to coding. Installed numpy using the built-in package manager of Thonny. Thonny comes bundled with Python 3.7. Also installed scipy that way, seems to be importing fine.

### The code
```python
import numpy as np
```

### Error message
```
Traceback (most recent call last):
  File "/Users/user/Library/Python/3.7/lib/python/site-packages/numpy/core/__init__.py", line 24, in <module>
    from . import multiarray
  File "/Users/user/Library/Python/3.7/lib/python/site-packages/numpy/core/multiarray.py", line 14, in <module>
    from . import overrides
  File "/Users/user/Library/Python/3.7/lib/python/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: dlopen(/Users/user/Library/Python/3.7/lib/python/site-packages/numpy/core/_multiarray_umath.cpython-37m-darwin.so, 2): no suitable image found.  Did find:
	/Users/user/Library/Python/3.7/lib/python/site-packages/numpy/core/_multiarray_umath.cpython-37m-darwin.so: code signature in (/Users/user/Library/Python/3.7/lib/python/site-packages/numpy/core/_multiarray_umath.cpython-37m-darwin.so) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/user/Desktop/asdf.py", line 1, in <module>
    import numpy as np
  File "/Users/user/Library/Python/3.7/lib/python/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/Users/user/Library/Python/3.7/lib/python/site-packages/numpy/core/__init__.py", line 54, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.7 from "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.7/bin/python3.7",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.18.1" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: dlopen(/Users/user/Library/Python/3.7/lib/python/site-packages/numpy/core/_multiarray_umath.cpython-37m-darwin.so, 2): no suitable image found.  Did find:
	/Users/user/Library/Python/3.7/lib/python/site-packages/numpy/core/_multiarray_umath.cpython-37m-darwin.so: code signature in (/Users/user/Library/Python/3.7/lib/python/site-packages/numpy/core/_multiarray_umath.cpython-37m-darwin.so) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
```
### Numpy/Python version information:
Numpy version 1.18.1
Thonny version 3.2.6
Python version 3.7.6
macOS Catalina 10.15.3

Trying 
``` python
import sys, numpy
print (numpy.__version__, sys.version)
``` 
returns the same error as above.

Any help is greatly appreciated!

**Comment by mattip** [comment]
> Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.

It seems macOS is becoming increasingly hostile to user-installed software. We do not sign our binary packages. We would need someone proficient in macOS packaging to hand-hold us through the process. I think there is a way to turn off the signature checks, but know nothing about macOS.

**Comment by rgommers** [comment]
Maybe you've upgraded to the latest macOS? That seems to require a reinstall: https://github.com/thonny/thonny/wiki/MacOSX#catalina

> We do not sign our binary packages. We would need someone proficient in macOS packaging to hand-hold us through the process.

I think that would need to be a standard thing for all macOS wheels? If there's a PyPA tool/guidance for it let's follow it, but no need to invent this wheel.

**Comment by msfsx1** [comment]
Thonny and numpy were both reinstalled after updating to the latest macOS, unfortunately. I even deleted user/Library/Python (I think that was the path) before reinstalling Thonny and numpy.

**Comment by phr0gger** [comment]
there are 2 possible remedies discussed here: https://github.com/opencv/opencv/issues/15645
1. use codesign with Apple developer's ID
2. check "Disable Library Validation" under Runtime Exceptions, see:
https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_security_cs_disable-library-validation

**Comment by rossbar** [comment]
Closing due to inactivity - it seems like potential solutions have been identified in the conversation above. If the issue persists, please feel free to reopen with updated information.
