### ISSUE TITLE
Suggestions regarding the absolute basics for beginners tutorial

### ISSUE THREAD

**Issue by flothesof** [numpy/numpy#15692]
I've been going through the NumPy: the absolute basics for beginners tutorial and would like to submit some comments. I'm more of an advanced user but I was curious to see what was in it.
I find it very nice, but I have a few comments and points I think are worthy of discussion. I've listed them by section below:

- section What is an array?
   - problematic (is this np.rank which is deprecated or np.linalg.rank or...) use of the term `rank` --> shouldn't this be ndims instead? 
- More information about arrays
   - the printout of the 2D array says "Your array has 2 axes. The first axis has a length of 2 and the second axis has a length of 3." Wouldn't it be helpful for beginners to learn that there is a convention about the printing of the first axis as vertical and the second as horizontal? (it's implicit in the text but may be helpful to some)
- section Adding, removing, and sorting elements: 
   - I think the part about removing elements from an array is too obscure for beginners because it's given without an example and just says "In order to remove elements from an array, it’s simple to use indexing to select the elements that you want to keep."
   - overall this section is about "sorting and concatenating": it would make sense to rename it like that (and I would suggest to get rid of the parts about removing elements)
- section How to create an array from existing data
   - there is no .view() example (I think it would make sense to have an example to illustrate) although there is a slicing example that returns a view on an array that is then modified. In a sense this makes me wonder if .view() needs to be mentioned at all, since it will often be used implicitly only (would reduce the number of things a beginner has to deal with) (of course the view concept needs to stay!)

If anyone finds these suggestions make sense, I would be happy to reformulate these comments in the form of a PR.

Regards,
Florian

**Comment by seberg** [comment]
Thanks for looking through it, @bonn0062 what do you think? I agree about rank, it is probably an unnecessary side note to an alternative nomenclature, `view` as a method is maybe not important, as a concept it is super important though. "Sorting and concatenating" seems not the right title to me, simply because `concatenate` is already a "complicated" and topical word (for native speakers it may be OK, but I do not think it is simple enough for non-natives).

In any case, I think you should open a PR, if you think there may be some parts that are easy and others that need discussion, you may want to split it up into multiple parts.

**Comment by flothesof** [comment]
Thanks for taking the time to reply @seberg 
Re your point about the title "Sorting and concatenating". I agree that concatenating is a complicated notion but still, the section is about np.concatenate. Removing the other things in it (in the way I suggest above) would leave us with that and sorting. 
I would like to wait for some more feedback before preparing a PR, to see what other people think about this, most notably @bonn0062...

**Comment by Irio** [comment]
Firstly, I'd like to say that this tutorial is an excellent addition to NumPy's documentation. At the current state, it's already a great place to point users who are taking their first steps with the library.

On par with its length, I've made [a list of comments](https://via.hypothes.is/https://numpy.org/devdocs/user/absolute_beginners.html#annotations:group:__world__) while reading it today. Since it comprises items not specific to this page but docs as a whole, I'm not sure if I should add to same issue. Maybe first addressing @flothesof's feedback and then I can join making my own suggestions/pull request? Otherwise, I can work on making my feedback easier to digest right away.

In summary, my feelings about areas to improve:

* Specially due to its length, I'd love to have a larger font-size and line-height. It feels denser than the content requires to. [The tutorial](https://numpy.org/devdocs/user/absolute_beginners.html) uses `font-size: 13px; line-height: 19px`; [Jupyter](https://www.tensorflow.org/guide/effective_tf2), [Python](https://docs.python.org/3/tutorial/index.html), and [TensorFlow](https://www.tensorflow.org/guide/effective_tf2), references for [NEP 44](https://numpy.org/neps/nep-0044-restructuring-numpy-docs.html) use `font-size: 15px; line-height: 21px`, `font-size: 16px; line-height: 22.4px`, and `font-size: 16px; line-height: 24px`, respectively.
* The presence of the images is helping a lot in understanding the concepts. Better yet if we could use them more often. A picture is worth a thousand words.
* Hierarchy of information. e.g., I finished reading without a good understanding of when should I use each of the methods for saving an array in disk. A suggestion would be to create a table in the start of the section with pros/cons, or create one header for each method.

Now, talking specifically about the points mentioned by @flothesof:

**section What is an array?**

I agree. I'd even mention another place where "rank" is used. "In NumPy, dimensions are called axes." Possibly, briefly mention the terms (since people will find it anyway in other places) and sticking with just one expression to simplify.

**More information about arrays**

Great point. `axis=0` is used in "Adding, removing, and sorting elements" but briefly explained only later, in "How do you know the shape and size of an array?." The definition comes only later, in "Can you reshape an array?"

**section Adding, removing, and sorting elements:**

Well noticed. Also, at this point of the text, we barely talked about indexing.

**section How to create an array from existing data**

In general, I feel this whole section could be made 10x better with static and animated images.

**Comment by justbennet** [comment]
> More information about arrays
> 
>    * the printout of the 2D array says "Your array has 2 axes. The first axis has a
>      length of 2 and the second axis has a length of 3." Wouldn't it be helpful for
>      beginners to learn that there is a convention about the printing of the first axis
>      as vertical and the second as horizontal? (it's implicit in the text but may be
>      helpful to some)

I agree, but I think the reverse needs to be explained.  It's conventional when printing the values of a one dimensional array from the `python` prompt to display it as a row, even though it is usually better thought of as a column?  That is explain why

```
np.ndarray([1,2,3])
array([1, 2, 3])
```
doesn't look like the column representation in the figure?

That is also how one-dimensional arrays work computationally, and how people would translate from mathematics to NumPy, I think.  Most mathematics courses talk about an _m_ x _n_ matrix as having _m_ rows and _n_ columns.

That it is the representation printed from the interactive prompt that is 'wrong' seems to be borne out by their behavior.
```
>>> X.shape
(7, 2)
>>> b.shape
(2,)
>>> X
array([[1. , 4. ],
       [1. , 4.5],
       [1. , 5. ],
       [1. , 5.5],
       [1. , 6. ],
       [1. , 6.5],
       [1. , 7. ]])
>>> b
array([-2.67857143,  9.5       ])
```
where the `X.shape` says to the naive person (me) that `X` has 7 rows and 2 columns, so I can
```
>>> np.dot(X, b)
array([35.32142857, 40.07142857, 44.82142857, 49.57142857, 54.32142857,
       59.07142857, 63.82142857])
```
but I cannot
```
>>> np.dot(b, X)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<__array_function__ internals>", line 6, in dot
ValueError: shapes (2,) and (7,2) not aligned: 2 (dim 0) != 7 (dim 0)
```

That's all just a long-winded way of asking whether we should probably accept that new users will be better off if they think of an `ndarray` as a column, even if it prints as a row when working interactively?

When they are advanced enough to need to think of it differently, they will also probably be in much better position to understand the real explanation of axes and want to relate that to how arrays are organized in memory, yes?

**Comment by eric-wieser** [comment]
> * Wouldn't it be helpful for
>   beginners to learn that there is a convention about the printing of the first axis
>   as vertical and the second as horizontal?

This description doesn't generalize. The _last_ axis is always horizontal, and all others are vertical.

**Comment by eric-wieser** [comment]
> That's all just a long-winded way of asking whether we should probably accept that new users will be better off if they think of an `ndarray` as a column, even if it prints as a row when working interactively?

Your intuition is informed by the behavior of `dot`, but it's a special case and not a widely applicable mental model. For broadcast operations like `+`, `-`, `minimum`, etc, 1d arrays should be thought of as rows.

**Comment by justbennet** [comment]
Then that definitely suggests that more and better explanation of axes and the dimensionality of arrays is needed.

Perhaps, also, then, the convention of showing columnar representation of one-dimensional arrays should be abandoned as misleading, at least here?

At some point in the past, I actually thought that my example did _not_ work that way, and I had to explicitly extend the array to get a column vector that would work.  I was a bit surprised and tried to adjust my thinking on the fly.  I have tutorial material that suggests that, at one time, I had to do something like `Y = Y[:, np.newaxis]` for it to work within `np.dot()` as a column vector.

Whatever it is, it clearly will be a tripping point, should be clarified somehow early, and we should avoid representations that will confuse or create false inuitions.  ;-)

**Comment by justbennet** [comment]
I propose that the section on Installing NumPy, per se, be removed and replaced with a link to the installation section of SciPy.  I don't think anything brief will cover the wide variety of installations and what the user might need to do to get a missing NumPy installed.

That the current section gives a `conda` command first seems to presume that one has installed Anaconda, in which case NumPy would almost certainly be there already, and no `conda install` will be needed.

If the `conda install` is needed, then seems to imply that some kind of Miniconda has probably been installed?  Are there other installations that are not Anaconda that provide `conda`?  If one is installing Miniconda, I think that is most often more experienced users.

If we recommend here using `conda` at all, do we then need to be concerned with creating a new conda environment before installing NumPy?  Is the assumption that the `conda` installation is writable by the user?

Should the `pip install` example precede the `conda install` as being the more 'pure' Python?  Would it not be better to suggest `pip install --user`?  (This suggestion comes from an administrator of shared computers who gets, on average a half-dozen e-mail message a week from users who get 'Permission denied' errors from `pip install blah` because we provide a centrally maintained Python.)

Many users might better use `apt` or `yum`, if on Linux?

However, I think it might be best to beg the topic entirely and just refer the reader to the installation section of SciPy.  However, they only need to do that if it isn't already there, so maybe just adding a line at the beginning of the How to import section would be sufficient?

> If `import numpy as np` fails with a message that indicates `numpy` is not installed, please see the Installation section at SciPy.

where the links in the last line of Installing NumPy are preserved (i.e., Installation points to https://www.scipy.org/install.html and SicPy to https://www.scipy.org/).

That way, all of the installation possibilities are dealt with in one place, and that place can enumerate a host of installation subtleties that would be inappropriate to enumerate on the Absolute beginners page.

**Comment by helloITdepartment** [comment]
Rather than opening a whole issue for it I figure I'll just post it here (though definitely let me know if this is something I should open an issue for)- 
In the "How to create a basic array" section it says the following:

> And even an array that contains a range of evenly spaced intervals. To do this, you will specify the **first number**, **last number**, and the **step size**.

And then gives the example:

> `>>> np.arange(2, 9, 2)`
> `array([2, 4, 6, 8])`

While most people who are familiar to programming probably get what's going on, it's technically not correct in that you don't specify the last number, you specify the first number not included, or the number after the last number, or the number at the top of a [closed, open) range, or however else you'd like to describe it

For example, `np.arange(1,5)` gives you `[1,2,3,4]` whereas the current wording might lead a beginner to expect `[1,2,3,4,5]`

**Comment by mdhaber** [comment]
@melissawm would you be willing to review / collaborate on a PR that addresses this issue? If so...

I think one reason this hasn't been addressed is that once one gets started, it's tough to stop. Hence my explicit attempt to address *only* the issues mentioned in the original post spiraled into a rewrite of a few sections. 
https://github.com/numpy/numpy/compare/main...mdhaber:numpy:gh15692?diff=split
Would it be worth continuing this effort - being sure to address the other ideas mentioned here - or should I try to be more sparing with the changes?

**Comment by melissawm** [comment]
@mdhaber I like your revisions a lot. I think they improve readability and reduce cognitive barriers. I'd love to collaborate on that - let me know how you'd like to proceed. Maybe with a draft PR and we can make suggestions?
