### ISSUE TITLE
Numpy DLL Load failed when running script as module in Anaconda 3 environment

### ISSUE THREAD

**Issue by rovyko** [numpy/numpy#15719]
I have an issue where numpy fails to import, raising a DLL Load error when running a script as a module through an Anaconda 3 environment.

Curiously this doesn't happen when I run the script as a module through PyCharm Community Edition, so I'm wondering how I can replicate its runtime in the command line.

If anyone has a suggestions for a working Anaconda environment setup that contains `numpy`, `pandas`, `geopandas`, `sqlalchemy` and `geoalchemy2` that would be very helpful.

Operating system is `Windows 10 Version 10.0.18363 Build 18363`

### Reproducing code example:

Create a new Anaconda 3 environment with only Python 3.7 and numpy:
```
conda create --name test_numpy python=3.7 numpy
```
Create a new file called `example.py` containing a numpy import:
```python
import numpy
```
From the directory where `example.py` is located, run it as a module using the environment you created:
```
C:\temp>ls
example.py

C:\temp>"C:\Users\myuser\Anaconda3\envs\test_numpy\python.exe" -m example
```

### Error message:
```
C:\temp>"C:\Users\myuser\Anaconda3\envs\test_numpy\python.exe" -m example
C:\Users\myuser\Anaconda3\envs\test_numpy\lib\site-packages\numpy\__init__.py:140: UserWarning: mkl-service package failed to import, therefore Intel(R) MKL initialization ensuring its correct out-of-the box operation under condition when Gnu OpenMP had already been loaded by Python process is not assured. Please install mkl-service package, see http://github.com/IntelPython/mkl-service
  from . import _distributor_init
Traceback (most recent call last):
  File "C:\Users\myuser\Anaconda3\envs\test_numpy\lib\site-packages\numpy\core\__init__.py", line 24, in <module>
    from . import multiarray
  File "C:\Users\myuser\Anaconda3\envs\test_numpy\lib\site-packages\numpy\core\multiarray.py", line 14, in <module>
    from . import overrides
  File "C:\Users\myuser\Anaconda3\envs\test_numpy\lib\site-packages\numpy\core\overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\myuser\Anaconda3\envs\test_numpy\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\myuser\Anaconda3\envs\test_numpy\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\temp\example.py", line 1, in <module>
    import numpy
  File "C:\Users\myuser\Anaconda3\envs\test_numpy\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "C:\Users\myuser\Anaconda3\envs\test_numpy\lib\site-packages\numpy\core\__init__.py", line 54, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.7 from "C:\Users\myuser\Anaconda3\envs\test_numpy\python.exe",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.18.1" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: DLL load failed: The specified module could not be found.
```

### Anaconda Environment Packages:
from `conda list`
```
# Name                    Version                   Build  Channel
blas                      1.0                         mkl
ca-certificates           2020.1.1                      0
certifi                   2019.11.28               py37_0
icc_rt                    2019.0.0             h0cc432a_1
intel-openmp              2020.0                      166
mkl                       2020.0                      166
mkl-service               2.3.0            py37hb782905_0
mkl_fft                   1.0.15           py37h14836fe_0
mkl_random                1.1.0            py37h675688f_0
numpy                     1.18.1           py37h93ca92e_0
numpy-base                1.18.1           py37hc3f5095_1
openssl                   1.1.1d               he774522_4
pip                       20.0.2                   py37_1
python                    3.7.6                h60c2a47_2
setuptools                45.2.0                   py37_0
six                       1.14.0                   py37_0
sqlite                    3.31.1               he774522_0
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_1
wheel                     0.34.2                   py37_0
wincertstore              0.2                      py37_0
```
### Working PyCharm config

![pycharm_config](https://user-images.githubusercontent.com/45183782/76133868-82d0e100-5fe8-11ea-88e2-58979c76fc32.png)

**Comment by charris** [comment]
This looks similar to #15697.

**Comment by rovyko** [comment]
@charris Thank you, it appears to be the same issue.

**Comment by rovyko** [comment]
Thank you to mattip https://github.com/numpy/numpy/issues/15697#issuecomment-596127127 for resolving the issue.

Here is the batch file that can run the script without import errors:
```
C:\Users\myuser\Anaconda3\condabin\conda activate test_numpy
python -m example.py
```
