### ISSUE TITLE
Numpy-1.18.0 and 1.18.1 debug builds fail on Windows 64-bit systems

### ISSUE THREAD

**Issue by umvarma** [numpy/numpy#15721]
We have been using Numpy debug modules built and installed in using pip. 

`python_d.exe -m pip install --no-binary :all: --global-option build --global-option --debug numpy`

The builds for versions starting from Numpy-1.18.0rc1 release are failing. Numpy 1.17 (including 1.17.5) versions build fine.

Following are the lines of log relevant to the error.

```
    Running setup.py install for Cython: finished with status 'done'
Successfully installed Cython-0.29.15 setuptools-45.2.0 wheel-0.34.2
Cleaning up...
  Removing source in C:\Users\Mohan\AppData\Local\Temp\pip-install-0rhoj8rd\setuptools
  Removing source in C:\Users\Mohan\AppData\Local\Temp\pip-install-0rhoj8rd\wheel
  Removing source in C:\Users\Mohan\AppData\Local\Temp\pip-install-0rhoj8rd\Cython
Removed build tracker: 'C:\\Users\\Mohan\\AppData\\Local\\Temp\\pip-req-tracker-265w1y7l'
Running command 'f:\Development\python\py38d\Scripts\python_d.exe' 'f:\Development\python\py38d\lib\site-packages\pip\_vendor\pep517\_in_process.py' get_requires_for_build_wheel 'C:\Users\MOHANV~1\AppData\Local\Temp\tmp7i1u8cwp'
running egg_info
creating numpy.egg-info
writing numpy.egg-info\PKG-INFO
writing dependency_links to numpy.egg-info\dependency_links.txt
writing entry points to numpy.egg-info\entry_points.txt
writing top-level names to numpy.egg-info\top_level.txt
writing manifest file 'numpy.egg-info\SOURCES.txt'
reading manifest file 'numpy.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
Running from numpy source directory.
no previously-included directories found matching 'doc\build'
no previously-included directories found matching 'doc\source\generated'
no previously-included directories found matching 'benchmarks\env'
no previously-included directories found matching 'benchmarks\results'
no previously-included directories found matching 'benchmarks\html'
no previously-included directories found matching 'benchmarks\numpy'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.pyo' found anywhere in distribution
warning: no previously-included files matching '*.pyd' found anywhere in distribution
warning: no previously-included files matching '*.swp' found anywhere in distribution
warning: no previously-included files matching '*.bak' found anywhere in distribution
warning: no previously-included files matching '*~' found anywhere in distribution
warning: no previously-included files found matching 'LICENSES_bundled.txt'
writing manifest file 'numpy.egg-info\SOURCES.txt'
  Created temporary directory: C:\Users\Mohan\AppData\Local\Temp\pip-modern-metadata-b8_2k1iz
  Running command 'f:\Development\python\py38d\Scripts\python_d.exe' 'f:\Development\python\py38d\lib\site-packages\pip\_vendor\pep517\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\MOHANV~1\AppData\Local\Temp\tmp7km_vhj4'
  Traceback (most recent call last):
    File "f:\Software\Python\3.8.2\lib\runpy.py", line 193, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "f:\Software\Python\3.8.2\lib\runpy.py", line 86, in _run_code
      exec(code, run_globals)
    File "C:\Users\Mohan\AppData\Local\Temp\pip-build-env-tw151002\overlay\Lib\site-packages\cython.py", line 16, in <module>
      from Cython.Compiler.Main import main
    File "C:\Users\Mohan\AppData\Local\Temp\pip-build-env-tw151002\overlay\Lib\site-packages\Cython\Compiler\Main.py", line 28, in <module>
      from .Scanning import PyrexScanner, FileSourceDescriptor
  ImportError: Module use of python38.dll conflicts with this version of Python.
  Processing numpy/random\_bounded_integers.pxd.in
  Processing numpy/random\mtrand.pyx
  Traceback (most recent call last):
    File "C:\Users\Mohan\AppData\Local\Temp\pip-install-10rv6rug\numpy\tools\cythonize.py", line 238, in <module>
      main()
    File "C:\Users\Mohan\AppData\Local\Temp\pip-install-10rv6rug\numpy\tools\cythonize.py", line 234, in main
      find_process_files(root_dir)
    File "C:\Users\Mohan\AppData\Local\Temp\pip-install-10rv6rug\numpy\tools\cythonize.py", line 225, in find_process_files
      process(root_dir, fromfile, tofile, function, hash_db)
    File "C:\Users\Mohan\AppData\Local\Temp\pip-install-10rv6rug\numpy\tools\cythonize.py", line 191, in process
      processor_function(fromfile, tofile)
    File "C:\Users\Mohan\AppData\Local\Temp\pip-install-10rv6rug\numpy\tools\cythonize.py", line 80, in process_pyx
      subprocess.check_call(
    File "f:\Software\Python\3.8.2\lib\subprocess.py", line 364, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['f:\\Development\\se\\python\\py38d\\Scripts\\python_d.exe', '-m', 'cython', '-3', '--fast-fail', '-o', 'mtrand.c', 'mtrand.pyx']' returned non-zero exit status 1.
  Running from numpy source directory.
  setup.py:425: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
    run_build = parse_setuppy_commands()
  Cythonizing sources
  Traceback (most recent call last):
    File "f:\Development\python\py38d\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 257, in <module>
      main()
    File "f:\Development\python\py38d\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 240, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "f:\Development\python\py38d\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 110, in prepare_metadata_for_build_wheel
      return hook(metadata_directory, config_settings)
    File "C:\Users\Mohan\AppData\Local\Temp\pip-build-env-tw151002\overlay\Lib\site-packages\setuptools\build_meta.py", line 158, in prepare_metadata_for_build_wheel
      self.run_setup()
    File "C:\Users\Mohan\AppData\Local\Temp\pip-build-env-tw151002\overlay\Lib\site-packages\setuptools\build_meta.py", line 249, in run_setup
      super(_BuildMetaLegacyBackend,
    File "C:\Users\Mohan\AppData\Local\Temp\pip-build-env-tw151002\overlay\Lib\site-packages\setuptools\build_meta.py", line 143, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 450, in <module>
      setup_package()
    File "setup.py", line 433, in setup_package
      generate_cython()
    File "setup.py", line 240, in generate_cython
      raise RuntimeError("Running cythonize failed!")
  RuntimeError: Running cythonize failed!
eaning up...
Removing source in C:\Users\Mohan\AppData\Local\Temp\pip-install-10rv6rug\numpy
moved numpy==1.18.0rc1 from https://files.pythonhosted.org/packages/21/94/5d48401d922ad494399f74a973445d831c888ef0cd9437a4276d8a63cfe5/numpy-1.18.0rc1.zip#sha256=7b0b915190cf60e691c17147f5d955e273d4c482b795a7bb168ad4a2fe2fb180 from build tracker 'C:\\Users\\Mohan\\AppData\\Local\\Temp\\pip-req-tracker-265w1y7l'
moved build tracker: 'C:\\Users\\Mohan\\AppData\\Local\\Temp\\pip-req-tracker-265w1y7l'
ROR: Command errored out with exit status 1: 'f:\Development\python\py38d\Scripts\python_d.exe' 'f:\Development\python\py38d\lib\site-packages\pip\_vendor\pep517\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\MOHANV~1\AppData\Local\Temp\tmp7km_vhj4' Check the logs for full command output.
ception information:
aceback (most recent call last):
File "f:\Development\python\py38d\lib\site-packages\pip\_internal\cli\base_command.py", line 186, in _main
  status = self.run(options, args)
File "f:\Development\python\py38d\lib\site-packages\pip\_internal\commands\install.py", line 331, in run
  resolver.resolve(requirement_set)
File "f:\Development\python\py38d\lib\site-packages\pip\_internal\legacy_resolve.py", line 177, in resolve
  discovered_reqs.extend(self._resolve_one(requirement_set, req))
File "f:\Development\python\py38d\lib\site-packages\pip\_internal\legacy_resolve.py", line 333, in _resolve_one
  abstract_dist = self._get_abstract_dist_for(req_to_install)
File "f:\Development\python\py38d\lib\site-packages\pip\_internal\legacy_resolve.py", line 282, in _get_abstract_dist_for
  abstract_dist = self.preparer.prepare_linked_requirement(req)
File "f:\Development\python\py38d\lib\site-packages\pip\_internal\operations\prepare.py", line 515, in prepare_linked_requirement
  abstract_dist = _get_prepared_distribution(
File "f:\Development\python\py38d\lib\site-packages\pip\_internal\operations\prepare.py", line 95, in _get_prepared_distribution
  abstract_dist.prepare_distribution_metadata(finder, build_isolation)
File "f:\Development\python\py38d\lib\site-packages\pip\_internal\distributions\sdist.py", line 40, in prepare_distribution_metadata
  self.req.prepare_metadata()
File "f:\Development\python\py38d\lib\site-packages\pip\_internal\req\req_install.py", line 564, in prepare_metadata
  self.metadata_directory = self._generate_metadata()
File "f:\Development\python\py38d\lib\site-packages\pip\_internal\req\req_install.py", line 549, in _generate_metadata
  return generate_metadata(
File "f:\Development\python\py38d\lib\site-packages\pip\_internal\operations\build\metadata.py", line 36, in generate_metadata
  distinfo_dir = backend.prepare_metadata_for_build_wheel(
File "f:\Development\python\py38d\lib\site-packages\pip\_vendor\pep517\wrappers.py", line 167, in prepare_metadata_for_build_wheel
  return self._call_hook('prepare_metadata_for_build_wheel', {
File "f:\Development\python\py38d\lib\site-packages\pip\_vendor\pep517\wrappers.py", line 245, in _call_hook
  self._subprocess_runner(
File "f:\Development\python\py38d\lib\site-packages\pip\_internal\utils\subprocess.py", line 271, in runner
  call_subprocess(
File "f:\Development\python\py38d\lib\site-packages\pip\_internal\utils\subprocess.py", line 242, in call_subprocess
  raise InstallationError(exc_msg)
p._internal.exceptions.InstallationError: Command errored out with exit status 1: 'f:\Development\python\py38d\Scripts\python_d.exe' 'f:\Development\python\py38d\lib\site-packages\pip\_vendor\pep517\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\MOHANV~1\AppData\Local\Temp\tmp7km_vhj4' Check the logs for full command output.

```

Version Information:
- Python 3.8.2
- Numpy 1.18.1
- Microsoft Windows 10

**Comment by mattip** [comment]
This seems like some interaction between cython and your python:
```
File "C:\Users\Mohan\AppData\Local\Temp\pip-build-env-tw151002\overlay\Lib\site-packages\Cython\Compiler\Main.py", line 28, in <module>
      from .Scanning import PyrexScanner, FileSourceDescriptor
  ImportError: Module use of python38.dll conflicts with this version of Python.
```

Could you try to debug that failure? Why is it pulling in python38.dll not python38_d.dll is it on the PATH somehow?

**Comment by umvarma** [comment]
The  _multiarray_umath_d.cp38-win_amd64.pyd and other .pyd files generated in numpy/core folder seemed to have linked with python38.dll and not python38_d.dll. Still trying to figure out what could have caused that.

**Comment by mattip** [comment]
You would have to look at the `pyconfig.h` file used when linking. It should be in one of the files in the `-I` compile arguments. It has this stanza
```
#			if defined(_DEBUG)
#				pragma comment(lib,"python36_d.lib")
#			elif defined(Py_LIMITED_API)
#				pragma comment(lib,"python3.lib")
#			else
#				pragma comment(lib,"python36.lib")
#			endif /* _DEBUG */
```
so you need to have `_DEBUG` defined, which you should if you are running a debug build.

**Comment by umvarma** [comment]
My apologies. I was trying pip install as well as manual builds. I mixed up between these two, and the previous comment was a result of it, where as the issue is something else.

The command `python_d.exe -m pip install --no-binary :all: --global-option build --global-option --debug numpy` making pip to download and build not just numpy but also setuptools, wheel and Cython (they are already available in PYTHONPATH, probably because of pyproject.toml). The global options (build --debug) are used only in the numpy building and not in the Cython building causing the creation of numpy debug libraries and Cython release libraries leading to a mix up between python38.dll and python38_d.dll.

Whereas, `python_d.exe -m pip install --no-binary :all: --global-option build --global-option --debug numpy==1.17.5` is building only numpy, so there was no python38.dll and python38_d.dll mix up.

**Comment by seberg** [comment]
@umvarma does this mean your problem is fixed, or is there a bug with pip and `pyproject.toml` when installing in a debug build?

**Comment by umvarma** [comment]
It is a bug with pip and pyproject.toml.

**Comment by seberg** [comment]
@umvarma thanks, did you open a python bug about it we could link here to close this, or do you think we should do something in NumPy about it?

**Comment by umvarma** [comment]
> @umvarma thanks, did you open a python bug about it we could link here to close this, or do you think we should do something in NumPy about it?

My apologies. I intend to say that pyproject.toml file in the distribution is causing this problem. I am not sure if this file can be altered to correct the build failure or if this is a python/pip bug. I created a python discuss topic https://discuss.python.org/t/pip-pyproject-toml-and-debug-builds/3766 for clarifications. I am hoping that this would be clarified soon.

**Comment by umvarma** [comment]
The workaround for the issue is to use --no-use-pep517 or --no-build-isolation as mentioned in https://discuss.python.org/t/pip-pyproject-toml-and-debug-builds/3766/2?u=umvarma.
