### ISSUE TITLE
Running natural logarithm over array of int objects yields attribute error

### ISSUE THREAD

**Issue by filipthor** [numpy/numpy#15751]
Hi,

I have run into a strange error when trying to apply the natural logarithm to a series. I assume this should be a possibility to do, as I have found multiple cases of this when running a quick google. 

Applying np.log() to a variable of type pandas.core.series.Series with objects of type 'int', where the dtype is defined as =object yields attribute error AttributeError: 'int' object has no attribute 'log'.
The same is true if I convert the Series to a np.array.
In[35]: e
Out[35]: array([0, 0, 0, 0, 0], dtype=object)
In[37]: type(e[0])
Out[37]: int
In[38]: type(e)
Out[38]: numpy.ndarray
In[39]: np.log(e)
[...]
 np.log(e)
AttributeError: 'int' object has no attribute 'log'

### Reproducing code example:

```python
import numpy as np
a = df['column'] #A Series containing objects of type 'int', the dtype of the Seris is 'object'
np.log(a)

```

### Error message:

Traceback (most recent call last):
  File "/Users/--/anaconda/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3325, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-32-6da260c3f1e3>", line 1, in <module>
    np.log(a)
AttributeError: 'int' object has no attribute 'log'

### Numpy/Python version information:

1.16.4 3.6.8 |Anaconda, Inc.| (default, Dec 29 2018, 19:04:46) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]

**Comment by rossbar** [comment]
The ufuncs rely on the dtype *of the array* to determine how to compute the data. In this case, since the `dtype=object`, the ufunc resolves to the `'O->O'` loop. For `np.log`, this loop attempts to call the `log` method of the objects in the array. Since `int`s don't have a `log` method, that's why you see this particular error.

If I understand correctly, the confusion in this case arises from the fact that though the dtype of the array is `object`, the individual elements of the array are all of type `int`. I'm not an expert in ufuncs so I may not be 100% correct here, but as I understand it when the dtype of an array is `object` numpy "takes the user at their word" and does not automatically loop through the elements of that array to see if it can convert it to built-in types. In this case, you can get the behavior you want by being explicit about the type of the data:
```python
# Note: you'll get a runtime warning here if e is all 0's as in the above example
np.log(e.astype(int))
```
Re: the conversion from pandas, perhaps try the `to_numpy` method which, according to the docstring, automatically determines which dtype should be used.

**Comment by rossbar** [comment]
Closing due to inactivity, please reopen if the response was not adequate to address the original issue.
