### ISSUE TITLE
assert_equal fails/crashes on empty arrays with large shape

### ISSUE THREAD

**Issue by asmeurer** [numpy/numpy#15753]
```py
>>> a = np.array([], dtype=np.int64).reshape((6, 10, 6, 10, 0, 5, 1, 9, 10, 2, 6, 2, 6, 0, 10, 9, 5, 1, 5, 1, 10, 3))
>>> np.testing.assert_equal(a, a[()])
python(73392,0x113ae6dc0) malloc: can't allocate region
*** mach_vm_map(size=15746400002048) failed (error code=3)
python(73392,0x113ae6dc0) malloc: *** set a breakpoint in malloc_error_break to debug
python(73392,0x113ae6dc0) malloc: can't allocate region
*** mach_vm_map(size=15746400002048) failed (error code=3)
python(73392,0x113ae6dc0) malloc: *** set a breakpoint in malloc_error_break to debug
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/aaronmeurer/anaconda3/lib/python3.7/site-packages/numpy/testing/_private/utils.py", line 349, in assert_equal
    return assert_array_equal(actual, desired, err_msg, verbose)
  File "/Users/aaronmeurer/anaconda3/lib/python3.7/site-packages/numpy/testing/_private/utils.py", line 936, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/Users/aaronmeurer/anaconda3/lib/python3.7/site-packages/numpy/testing/_private/utils.py", line 770, in assert_array_compare
    flagged = func_assert_same_pos(x, y, func=isnan, hasval='nan')
  File "/Users/aaronmeurer/anaconda3/lib/python3.7/site-packages/numpy/testing/_private/utils.py", line 746, in func_assert_same_pos
    raise AssertionError(msg)
AssertionError:
Arrays are not equal

x and y nan location mismatch:
 x: array([], shape=(6, 10, 6, 10, 0, 5, 1, 9, 10, 2, 6, 2, 6, 0, 10, 9, 5, 1, 5, 1, 10, 3),
      dtype=int64)
 y: array([], shape=(6, 10, 6, 10, 0, 5, 1, 9, 10, 2, 6, 2, 6, 0, 10, 9, 5, 1, 5, 1, 10, 3),
      dtype=int64)
```

I also sometimes get MemoryError from similar examples, for instance, with `shape=[7, 2, 6, 10, 6, 10, 0, 5, 1, 9, 10, 2, 6, 2, 6, 0, 10, 9, 5, 1, 5, 1, 10, 3]`, and even `np.all` gives warnings from malloc.

```py
>>> a = np.array([], dtype=np.int64).reshape([7, 2, 6, 10, 6, 10, 0, 5, 1, 9, 10, 2, 6, 2, 6, 0, 10, 9, 5, 1, 5, 1, 10, 3])
>>> np.all(a == a[()])
python(77502,0x10cb79dc0) malloc: can't allocate region
*** mach_vm_map(size=220449600000000) failed (error code=3)
python(77502,0x10cb79dc0) malloc: *** set a breakpoint in malloc_error_break to debug
python(77502,0x10cb79dc0) malloc: can't allocate region
*** mach_vm_map(size=220449600000000) failed (error code=3)
python(77502,0x10cb79dc0) malloc: *** set a breakpoint in malloc_error_break to debug
False
```

```py
>>> np.testing.assert_equal(a, a[()])
python(77502,0x10cb79dc0) malloc: can't allocate region
*** mach_vm_map(size=220449600000000) failed (error code=3)
python(77502,0x10cb79dc0) malloc: *** set a breakpoint in malloc_error_break to debug
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/aaronmeurer/anaconda3/lib/python3.7/site-packages/numpy/testing/_private/utils.py", line 349, in assert_equal
    return assert_array_equal(actual, desired, err_msg, verbose)
  File "/Users/aaronmeurer/anaconda3/lib/python3.7/site-packages/numpy/testing/_private/utils.py", line 936, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/Users/aaronmeurer/anaconda3/lib/python3.7/site-packages/numpy/testing/_private/utils.py", line 770, in assert_array_compare
    flagged = func_assert_same_pos(x, y, func=isnan, hasval='nan')
  File "/Users/aaronmeurer/anaconda3/lib/python3.7/site-packages/numpy/testing/_private/utils.py", line 728, in func_assert_same_pos
    x_id = func(x)
MemoryError: Unable to allocate 0 bytes for an array with shape (7, 2, 6, 10, 6, 10, 0, 5, 1, 9, 10, 2, 6, 2, 6, 0, 10, 9, 5, 1, 5, 1, 10, 3) and data type bool
```

Note:

```py
>>> shape = [7, 2, 6, 10, 6, 10, 0, 5, 1, 9, 10, 2, 6, 2, 6, 0, 10, 9, 5, 1, 5, 1, 10, 3]
>>> np.prod([i for i in shape if i])
220449600000000
```

It isn't clear to me if this is the sort of thing that should work. I would expect empty arrays to effectively ignore the nonzero entries in the shape except for broadcasting purposes. But maybe there are technical reasons why this cannot happen?

### Numpy/Python version information:

```py
>>> import sys, numpy; print(numpy.__version__, sys.version)
1.18.1 3.7.3 | packaged by conda-forge | (default, Mar 27 2019, 15:43:19)
[Clang 4.0.1 (tags/RELEASE_401/final)]
```

**Comment by teoliphant** [comment]
FYI.  With NumPy version 1.11.3 on Mac I do not see this error.  I *do* see a very similar error with 1.18.1.

**Comment by seberg** [comment]
Hmmm, there is an oversight in the code, it probably wants to prevent the nonzero elements to get too large, but forgets to make sure that no actual data is allocated when there are zero bytes.
I.e. it currently tries to allocate enough memory to fit the array as if there are no zeros in the shape. I think we simplified that code a bit a (longer) while ago, so that could have been an oversight at that point.

**Comment by mattip** [comment]
The minimal reproducer is
```
>>> a = np.array([], dtype=np.int64).reshape([0, 1000, 1000, 1000, 1000])
>>> np.isnan(a)
MemoryError: Unable to allocate 0 bytes for an array with shape \
(0, 1000, 1000, 1000, 1000) and data type bool
```

**Comment by mattip** [comment]
Changeset 3e8c2b00ee from gh-7463 no longer used the [return value](https://github.com/numpy/numpy/commit/3e8c2b00ee7d0c438226057bebeb973c4ab3458f#diff-758e4b79c5a0e4db54723d82a8436418L1021) from `_array_fill_strides`, rather it uses the faulty calculation which skips 0 on [line 957](https://github.com/numpy/numpy/commit/3e8c2b00ee7d0c438226057bebeb973c4ab3458f#diff-758e4b79c5a0e4db54723d82a8436418L957)

**Comment by seberg** [comment]
Closing, on master numpy tries to allocate less memory so it passes.  The main issue here (IMO) was always that we really should not ignore critical errors (or any errors), but gh-21222 tracks those better anyway.
(I don't care too much that about the above failing, but it should not return `False` silently.)
