### ISSUE TITLE
Numpy DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by SBMama** [numpy/numpy#15855]
IDE: PyCharm Community Edition 2019.2.3
Setuptools version: 46.1.3
Numpy: 1.18.2+mkl downloaded from https://www.lfd.uci.edu/~gohlke/pythonlibs/#scipy
Python version Info:
3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 11:52:54) [MSC v.1900 64 bit (AMD64)]
Windows Version: Windows 10

Tried the solutions suggested in traceback. (uninstalled and re-installed numpy, checked environment variables)

### Reproducing code example:
import numpy

Full Traceback:

Traceback (most recent call last):
  File "C:\Users\HP\PycharmProjects\GEM\venv\lib\site-packages\numpy\core\__init__.py", line 24, in <module>
    from . import multiarray
  File "C:\Users\HP\PycharmProjects\GEM\venv\lib\site-packages\numpy\core\multiarray.py", line 14, in <module>
    from . import overrides
  File "C:\Users\HP\PycharmProjects\GEM\venv\lib\site-packages\numpy\core\overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_karate.py", line 6, in <module>
    import matplotlib.pyplot as plt
  File "C:\Users\HP\PycharmProjects\GEM\venv\lib\site-packages\matplotlib-3.2.1-py3.7-win-amd64.egg\matplotlib\__init__.py", line 139, in <module>
    from . import cbook, rcsetup
  File "C:\Users\HP\PycharmProjects\GEM\venv\lib\site-packages\matplotlib-3.2.1-py3.7-win-amd64.egg\matplotlib\cbook\__init__.py", line 32, in <module>
    import numpy as np
  File "C:\Users\HP\PycharmProjects\GEM\venv\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "C:\Users\HP\PycharmProjects\GEM\venv\lib\site-packages\numpy\core\__init__.py", line 54, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.7 from "C:\Users\HP\PycharmProjects\GEM\venv\Scripts\python.exe",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.18.2" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: DLL load failed: The specified module could not be found.

**Comment by mattip** [comment]
At the top of the link you downloaded from there is this note 
> Many binaries depend on numpy-1.16+mkl and the current Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019 for Python 3, or the Microsoft Visual C++ 2008 Redistributable Package x64, x86, and SP1 for Python 2.7.
> Install numpy+mkl before other packages that depend on it.

Did you install those reistributables?

**Comment by SBMama** [comment]
Hi mattip,

Thank you for pointing that out. I had numpy 1.18.2+mkl installed but some of the Visual C++ redistributables were missing. Installing them solved the issue.
