### ISSUE TITLE
When importing numpy error DLL load failed: The specified module could not be found

### ISSUE THREAD

**Issue by geeselouise** [numpy/numpy#15942]
Hello, 
I am new to using python and git, so please be patient. My operating system is Windows 10 64 bit on a Lenovo computer. I installed both Python and numpy via Anaconda. My Python version is 3.7.6. Numpy version is 1.18.1.  To learn how to use Python with git, I am doing an swcarpentry tutorial  http://swcarpentry.github.io/python-novice-inflammation/12-cmdline/index.html. I am in the portion of the tutorial that teaches you how to run commands in the shell instead of a python interpreter like Jupyter. When I try to import numpy with my code, I get the error ImportError: DLL load failed: The specified module could not be found. It also says that importing the numpy c-extension failed. I have tried uninstalling and reinstalling numpy via anaconda but the error remains. I do not think that any of my directories in my PATH can interfere with numpy  version, but I could be wrong as I am a novice programmer. 

##Code example below that reproduces the error

<python ../code/readings_02.py inflammation-01.csv >

##This is the code in readings_02.py that tries to import numpy. 
<
import sys
import numpy

def main():
    script = sys.argv[0]
    filename = sys.argv[1]
    data = numpy.loadtxt(filename, delimiter=',')
    for row_mean in numpy.mean(data, axis=1):
        print(row_mean)

if __name__ == '__main__':
   main()
>

### Error message:

<C:\Users\louis\anaconda3\lib\site-packages\numpy\__init__.py:140: UserWarning: mkl-service package failed to import, therefore Intel(R) MKL initialization ensuring its correct out-of-the box operation under condition when Gnu OpenMP had already been loaded by Python process is not assured. Please install mkl-service package, see http://github.com/IntelPython/mkl-service
  from . import _distributor_init
 (most recent call last):
  File "C:\Users\louis\anaconda3\lib\site-packages\numpy\core\__init__.py", line 24, in <module>
    from . import multiarray
  File "C:\Users\louis\anaconda3\lib\site-packages\numpy\core\multiarray.py", line 14, in <module>
    from . import overrides
  File "C:\Users\louis\anaconda3\lib\site-packages\numpy\core\overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../code/readings_02.py", line 2, in <module>
    import numpy
  File "C:\Users\louis\anaconda3\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "C:\Users\louis\anaconda3\lib\site-packages\numpy\core\__init__.py", line 54, in <module>
    raise ImportError(msg)
ImportError:

>

**Comment by geeselouise** [comment]
Nvm my boyfriend helped me solve the issue. It is a problem with anaconda. Numpy was uninstalled and reinstalled using pip instead. Now numpy can be imported, and it works just fine.

**Comment by dc123k** [comment]
Sorry, I have a similar problem with numpy. I'm trying to uninstall and install again and the next error happens:

Thank you

```
ERROR: Exception:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\_internal\cli\base_command.py", line 186, in _main
    status = self.run(options, args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\_internal\commands\uninstall.py", line 82, in run
    uninstall_pathset.commit()
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\_internal\req\req_uninstall.py", line 450, in commit
    self._moved_paths.commit()
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\_internal\req\req_uninstall.py", line 290, in commit
    save_dir.cleanup()
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\_internal\utils\temp_dir.py", line 175, in cleanup
    rmtree(self._path)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\_vendor\retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\_vendor\retrying.py", line 212, in call
    raise attempt.get()
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\_vendor\retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\_vendor\six.py", line 703, in reraise
    raise value
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\_vendor\retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\_internal\utils\misc.py", line 136, in rmtree
    onerror=rmtree_errorhandler)
  File "C:\ProgramData\Anaconda3\lib\shutil.py", line 516, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\ProgramData\Anaconda3\lib\shutil.py", line 395, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\ProgramData\Anaconda3\lib\shutil.py", line 400, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\ProgramData\Anaconda3\lib\shutil.py", line 398, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] Acceso denegado: 'c:\\programdata\\anaconda3\\lib\\site-packages\\~umpy\\.libs\\libopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll'
```

**Comment by mattip** [comment]
@dc123k this issue is closed, please open a new one in the future. As for your problem: do you have another active python process that is holding the file open?

**Comment by dc123k** [comment]
Thank you @mattip I have restarted de computer and I am running python through PyCharm so I'm not running consciously any other process.
