### ISSUE TITLE
 DLL load failed: The specified module could not be found

### ISSUE THREAD

**Issue by babaralishah** [numpy/numpy#15955]
I had python 3.7.7 on my windows 10, then i download and installed 3.8.2 the latest version, but when i am typing python --version on cmd it showing me 3.7.7 version of python.
i downloaded the numpy (1.18.2)+mkl from a site.
When i am running my python code on vscode i am getting this error below:
```
Traceback (most recent call last):
  File "C:\Users\Syed Think Center\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\numpy\core\__init__.py", line 24, in <module>
    from . import multiarray
  File "C:\Users\Syed Think Center\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\numpy\core\multiarray.py", line 14, in <module>
    from . import overrides
  File "C:\Users\Syed Think Center\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\numpy\core\overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from sklearn.linear_model import LinearRegression
  File "C:\Users\Syed Think Center\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\sklearn\__init__.py", line 82, in <module>
    from .base import clone
  File "C:\Users\Syed Think Center\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\sklearn\base.py", line 17, in <module>
    import numpy as np
  File "C:\Users\Syed Think Center\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "C:\Users\Syed Think Center\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\numpy\core\__init__.py", line 54, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.7 from "C:\Users\Syed Think Center\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\python.exe",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.18.2" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: DLL load failed: The specified module could not be found.
```

**Comment by anirudh2290** [comment]
I don't have much experience with windows, but as mentioned in the error message it could be that your python/numpy versions are clashing. Are you sure you dont have python specific env variables set (for eg. PYTHONHOME or PYTHONPATH). Also, how did you install numpy for your python3.7.7 version ?

**Comment by rmharrison** [comment]
For Future Reference
> i downloaded the numpy (1.18.2)+mkl from a site.
Refers to the windows-specific Intel Math Kernel Library build of numpy
https://www.lfd.uci.edu/~gohlke/pythonlibs/?cm_mc_uid=85766897061814897087787&cm_mc_sid_50200000=1489708778#numpy

**Comment by seberg** [comment]
As anirudth said, my best guess is either a bad `PYTHONPATH`, or an incorrectly set up environment for which, please check https://code.visualstudio.com/docs/python/environments Of course it could also be that the install is bad itself and the fact that you have two python versions can easily lead ot such things if you use `PYTHONPATH`.

I will close this for now. However, if you find a solution which is not obvious after checking PYTHONPATH and environment activation, please write here, so that we can add it to our documentation and future users find help quicker!
