### ISSUE TITLE
TypeError: fname must be a string, filehandle, list of strings, or generator. Got <type 'NoneType'> instead.

### ISSUE THREAD

**Issue by MeisamRezaei** [numpy/numpy#15971]
Hi, I want to run the following script (has been written in Python 2.7) to read my .txt data and predict the variables I got error in two last lines in which  the error is in genfromtxt. Can any one help me to solve it, please?
```
import numpy as N
import argparse
#import pandas
import time as T
from contextlib import closing
from ANN_Module import PTF_MODEL
from DB_Module import DB

parser = argparse.ArgumentParser(description='Rosetta 3 pedotransfer function interface example.')
parser.add_argument('--host', default='localhost', help='MySQl host')
parser.add_argument('--user', default='root', help='MySQl username')  # you want to change the username
parser.add_argument('--db', default='Rosetta', help='MySQl database')
parser.add_argument('--predict', action='store_true', help='get data and predict')
parser.add_argument('--check', action='store_true', help='check prediction (for development only)')
parser.add_argument('--raw', action='store_true', help='get raw data')
parser.add_argument('--sqlite', default='', help='sqlite path (ignores MySQL options)')  #using this option will ignore the mysql options.
parser.add_argument('-i', '--input', action='store', help='input from file')
parser.add_argument('-o','--output', action='store', help='store predicted data')

args = parser.parse_args()
print(args.input)

data_in = N.genfromtxt(args.input, delimiter='',dtype=N.float).transpose()
print(data_in)
```
### Error message: 
```
TypeError: fname must be a string, filehandle, list of strings, or generator. Got <type 'NoneType'> instead.

Traceback (most recent call last):

  File "<ipython-input-1-f61f204334df>", line 1, in <module>
    runfile('D:/dr misamrezai/rosetta/Rosetta-3.0beta/Rosetta-3.0beta/Rpredict.py', wdir='D:/dr misamrezai/rosetta/Rosetta-3.0beta/Rosetta-3.0beta')

  File "C:\Users\mrezaei\AppData\Local\Continuum\anaconda2\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\Users\mrezaei\AppData\Local\Continuum\anaconda2\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 95, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "D:/dr misamrezai/rosetta/Rosetta-3.0beta/Rosetta-3.0beta/Rpredict.py", line 23, in <module>
    data_in = N.genfromtxt (args.input, dtype=N.float).transpose()

  File "C:\Users\mrezaei\AppData\Local\Continuum\anaconda2\lib\site-packages\numpy\lib\npyio.py", line 1751, in genfromtxt
    "or generator. Got %s instead." % type(fname))

TypeError: fname must be a string, filehandle, list of strings, or generator. Got <type 'NoneType'> instead.
```
### Numpy/Python version information:
python 2.7

**Comment by eric-wieser** [comment]
> TypeError: fname must be a string, filehandle, list of strings, or generator. Got <type 'NoneType'> instead.

`fname` is the first argument to `genfromtxt`. It is `None`. So your problem is that `args.input` is `None`.
