### ISSUE TITLE
np.histogramdd produces confusing errors when `bins` is a float

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#15984]
Compare the result of `histogram`, which produce a clear error:

```
In [2]: np.histogram(np.arange(3), 1.0)
Traceback (most recent call last):
  File "C:\Users\wiese\Repos\numeric-python\numpy\build\testenv\Lib\site-packages\numpy\lib\histograms.py", line 419, in _get_bin_edges
    n_equal_bins = operator.index(bins)
TypeError: 'float' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<ipython-input-14-9cbdad7566c1>", line 1, in <module>
    np.histogram(np.arange(3), 1.0)
  File "<__array_function__ internals>", line 5, in histogram
  File "C:\Users\wiese\Repos\numeric-python\numpy\build\testenv\Lib\site-packages\numpy\lib\histograms.py", line 792, in histogram
    bin_edges, uniform_bins = _get_bin_edges(a, bins, range, weights)
  File "C:\Users\wiese\Repos\numeric-python\numpy\build\testenv\Lib\site-packages\numpy\lib\histograms.py", line 421, in _get_bin_edges
    raise TypeError(
TypeError: `bins` must be an integer, a string, or an array
```

to histogramdd, which (on master) produces a more opaque ~~(and uselessly verbose, xref gh-15985)~~ one:
```
In [3]: np.histogramdd(np.arange(3), 1.0)
Traceback (most recent call last):
  File "C:\Users\wiese\Repos\numeric-python\numpy\build\testenv\Lib\site-packages\numpy\core\function_base.py", line 114, in linspace
    num = operator.index(num)
TypeError: 'float' object cannot be interpreted as an integer
```

We should catch this error and emit a more precise one.

**Comment by grantmwilliams** [comment]
I'm happy to work on this issue. The preferred error for `histogramdd` should look more like error for `histogram`?

**Comment by eric-wieser** [comment]
Yep, although I think histogramdd takes a slightly wider range of input formats.

**Comment by TapanGujjar** [comment]
@grantmwilliams  can I work on the issue if you have not already fix it or are busy?
