### ISSUE TITLE
dynamic module does not define module export function (PyInit__multiarray_umath)

### ISSUE THREAD

**Issue by gnatpat** [numpy/numpy#16033]
### Reproducing code example:

```python
import numpy as np
```

### Error message:

```
Python 3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 10:41:24) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
Traceback (most recent call last):
  File "C:\Users\bethany.west\AppData\Roaming\Python\Python37\site-packages\numpy\core\__init__.py", line 24, in <module>
    from . import multiarray
  File "C:\Users\bethany.west\AppData\Roaming\Python\Python37\site-packages\numpy\core\multiarray.py", line 14, in <module>
    from . import overrides
  File "C:\Users\bethany.west\AppData\Roaming\Python\Python37\site-packages\numpy\core\overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: dynamic module does not define module export function (PyInit__multiarray_umath)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\bethany.west\AppData\Roaming\Python\Python37\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "C:\Users\bethany.west\AppData\Roaming\Python\Python37\site-packages\numpy\core\__init__.py", line 54, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.7 from "C:\Users\bethany.west\AppData\Local\Programs\Python\Python37\python.exe",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.18.3" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: dynamic module does not define module export function (PyInit__multiarray_umath)
```
### Numpy/Python version information:

After a fresh install of Python 3.7.7 using the Windows Installer, and running `python -m pip install --user numpy`. 
There is nothing odd on my path:
```
set PATH
PATH=C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Users\bethany.west\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Citrix\System32\;C:\Program Files\Citrix\ICAService\;C:\Program Files\Citrix\Virtual Desktop Agent\;C:\Program Files\TortoiseSVN\bin;C:\Users\bethany.west\AppData\Local\Programs\Python\Python37\Scripts\;C:\Users\bethany.west\AppData\Local\Programs\Python\Python37\;C:\Users\bethany.west\AppData\Local\Microsoft\WindowsApps
```

and none of `PYTHONHOME`, `PYTHONPATH`, or `PY` are set.

```
>>> sys.version
'3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 10:41:24) [MSC v.1900 64 bit (AMD64)]'
```

**Comment by rossbar** [comment]
I'm going to close this due to inactivity - if the issue persists, please reopen or create a new issue with any updated info!
