### ISSUE TITLE
v1.18.3 install failed on Ubuntu 18.04 AARCH64

### ISSUE THREAD

**Issue by numbqq** [numpy/numpy#16050]
1.18.3 install failed on Ubuntu 18.04 AARCH64

### Reproducing code example:

```
khadas@Khadas:~$ sudo pip3 install 'numpy==1.18.3'
The directory '/home/khadas/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/khadas/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting numpy==1.18.3
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/0c/e8/c49cb52ed2ad734efb49eb1f7766888b0e65df1848f71fa7f7fd52183392/numpy-1.18.3.zip (5.4MB)
    100% |████████████████████████████████| 5.4MB 152kB/s 
Installing collected packages: numpy
  Found existing installation: numpy 1.16.1
    Uninstalling numpy-1.16.1:
      Successfully uninstalled numpy-1.16.1
  Running setup.py install for numpy ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-hv80m3_5/numpy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-0ywztrf_-record/install-record.txt --single-version-externally-managed --compile:
    Running from numpy source directory.
    
    Note: if you need reliable uninstall behavior, then install
    with pip instead of using `setup.py install`:
    
      - `pip install .`       (from a git repo or downloaded source
                               release)
      - `pip install numpy`   (last NumPy release on PyPi)
    
    
    Cythonizing sources
    Traceback (most recent call last):
      File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
        "__main__", mod_spec)
      File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "/usr/local/lib/python3.6/dist-packages/cython.py", line 16, in <module>
        from Cython.Compiler.Main import main
      File "/usr/local/lib/python3.6/dist-packages/Cython/Compiler/Main.py", line 8, in <module>
        import re
      File "/usr/lib/python3.6/re.py", line 142, in <module>
        class RegexFlag(enum.IntFlag):
    AttributeError: module 'enum' has no attribute 'IntFlag'
    Error in sys.excepthook:
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 53, in apport_excepthook
        if not enabled():
      File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 24, in enabled
        import re
      File "/usr/lib/python3.6/re.py", line 142, in <module>
        class RegexFlag(enum.IntFlag):
    AttributeError: module 'enum' has no attribute 'IntFlag'
    
    Original exception was:
    Traceback (most recent call last):
      File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
        "__main__", mod_spec)
      File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "/usr/local/lib/python3.6/dist-packages/cython.py", line 16, in <module>
        from Cython.Compiler.Main import main
      File "/usr/local/lib/python3.6/dist-packages/Cython/Compiler/Main.py", line 8, in <module>
        import re
      File "/usr/lib/python3.6/re.py", line 142, in <module>
        class RegexFlag(enum.IntFlag):
    AttributeError: module 'enum' has no attribute 'IntFlag'
    Processing numpy/random/_bounded_integers.pxd.in
    Processing numpy/random/mtrand.pyx
    Traceback (most recent call last):
      File "/tmp/pip-build-hv80m3_5/numpy/tools/cythonize.py", line 238, in <module>
        main()
      File "/tmp/pip-build-hv80m3_5/numpy/tools/cythonize.py", line 234, in main
        find_process_files(root_dir)
      File "/tmp/pip-build-hv80m3_5/numpy/tools/cythonize.py", line 225, in find_process_files
        process(root_dir, fromfile, tofile, function, hash_db)
      File "/tmp/pip-build-hv80m3_5/numpy/tools/cythonize.py", line 191, in process
        processor_function(fromfile, tofile)
      File "/tmp/pip-build-hv80m3_5/numpy/tools/cythonize.py", line 81, in process_pyx
        [sys.executable, '-m', 'cython'] + flags + ["-o", tofile, fromfile])
      File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'cython', '-3', '--fast-fail', '-o', 'mtrand.c', 'mtrand.pyx']' returned non-zero exit status 1.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-hv80m3_5/numpy/setup.py", line 488, in <module>
        setup_package()
      File "/tmp/pip-build-hv80m3_5/numpy/setup.py", line 469, in setup_package
        generate_cython()
      File "/tmp/pip-build-hv80m3_5/numpy/setup.py", line 275, in generate_cython
        raise RuntimeError("Running cythonize failed!")
    RuntimeError: Running cythonize failed!
    
    ----------------------------------------
  Rolling back uninstall of numpy
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-hv80m3_5/numpy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-0ywztrf_-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-hv80m3_5/numpy/
khadas@Khadas:~$ 
```

### Numpy/Python version information:
```
khadas@Khadas:~$ python3 -V
Python 3.6.9
```

### System information

```
khadas@Khadas:~$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"
```

**Comment by seberg** [comment]
Please check/search for the actual error which causes this, this will lead you to:
https://stackoverflow.com/questions/43124775/why-python-3-6-1-throws-attributeerror-module-enum-has-no-attribute-intflag

Which will hopefully solve your problem. That said, on aarch64, while things should work, there may be more issues
