### ISSUE TITLE
can't import numpy inside string.py file

### ISSUE THREAD

**Issue by JonasHarsch** [numpy/numpy#16088]
### Reproducing code example:

Create a file called `string.py` with the following content

```python
import numpy as np

if __name__ == "__main__":
    pass
```

and run it via `python3 string.py`.

### Error message:

```bash
Traceback (most recent call last):
  File "/home/user/Desktop/string.py", line 1, in <module>
    import numpy as np
  File "/usr/local/lib/python3.6/dist-packages/numpy/__init__.py", line 228, in <module>
    from .testing import Tester
  File "/usr/local/lib/python3.6/dist-packages/numpy/testing/__init__.py", line 10, in <module>
    from unittest import TestCase
  File "/usr/lib/python3.6/unittest/__init__.py", line 59, in <module>
    from .case import (TestCase, FunctionTestCase, SkipTest, skip, skipIf,
  File "/usr/lib/python3.6/unittest/case.py", line 6, in <module>
    import logging
  File "/usr/lib/python3.6/logging/__init__.py", line 28, in <module>
    from string import Template
ImportError: cannot import name 'Template'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 21, in <module>
    from urllib.request import urlopen
  File "/usr/lib/python3.6/urllib/request.py", line 88, in <module>
    import http.client
  File "/usr/lib/python3.6/http/client.py", line 71, in <module>
    import email.parser
  File "/usr/lib/python3.6/email/parser.py", line 12, in <module>
    from email.feedparser import FeedParser, BytesFeedParser
  File "/usr/lib/python3.6/email/feedparser.py", line 27, in <module>
    from email._policybase import compat32
  File "/usr/lib/python3.6/email/_policybase.py", line 7, in <module>
    from email import header
  File "/usr/lib/python3.6/email/header.py", line 16, in <module>
    import email.quoprimime
  File "/usr/lib/python3.6/email/quoprimime.py", line 44, in <module>
    from string import ascii_letters, digits, hexdigits
ImportError: cannot import name 'ascii_letters'

Original exception was:
Traceback (most recent call last):
  File "/home/user/Desktop/string.py", line 1, in <module>
    import numpy as np
  File "/usr/local/lib/python3.6/dist-packages/numpy/__init__.py", line 228, in <module>
    from .testing import Tester
  File "/usr/local/lib/python3.6/dist-packages/numpy/testing/__init__.py", line 10, in <module>
    from unittest import TestCase
  File "/usr/lib/python3.6/unittest/__init__.py", line 59, in <module>
    from .case import (TestCase, FunctionTestCase, SkipTest, skip, skipIf,
  File "/usr/lib/python3.6/unittest/case.py", line 6, in <module>
    import logging
  File "/usr/lib/python3.6/logging/__init__.py", line 28, in <module>
    from string import Template
ImportError: cannot import name 'Template'
```

### Numpy/Python version information:

Numpy: 1.18.2 
Python: 3.6.9
GCC 8.4.0

### Operating system:

Ubuntu 18.04.4 LTS

**Comment by matthew-brett** [comment]
Your filename `string.py` is shadowing the `string` module in Python, causing the crash, because Python is loading your file instead of its built-in module.

```
  File "/usr/lib/python3.6/logging/__init__.py", line 28, in <module>
    from string import Template
ImportError: cannot import name 'Template'
```

**Comment by eric-wieser** [comment]
Duplicate of #13015
