### ISSUE TITLE
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath' on fresh install

### ISSUE THREAD

**Issue by pujok** [numpy/numpy#16106]
I'm currently trying to run openage on W10. It has its own python package with numpy. I also have one of my own installed. I tried to run it with both and I get the same error with both. Unfortunately, I don't have the code that causes the error. I've uninstalled any old python and numpy versions, updated everything and checked PATH for any obstructions, as instructed, but everything seems right and fixed nothing.

### Error message:

```Traceback (most recent call last):
  File "C:\Program Files\openage\python\numpy\core\__init__.py", line 24, in <module>
    from . import multiarray
  File "C:\Program Files\openage\python\numpy\core\multiarray.py", line 14, in <module>
    from . import overrides
  File "C:\Program Files\openage\python\numpy\core\overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "runpy.py", line 192, in _run_module_as_main
    File "runpy.py", line 85, in _run_code
  File "C:\Program Files\openage\python\openage\__main__.py", line 140, in <module>
    sys.exit(main())
  File "C:\Program Files\openage\python\openage\__main__.py", line 92, in main
    from .convert.singlefile import init_subparser
  File "C:\Program Files\openage\python\openage\convert\singlefile.py", line 11, in <module>
    from .texture import Texture
  File "C:\Program Files\openage\python\openage\convert\texture.py", line 8, in <module>
    import numpy
  File "C:\Program Files\openage\python\numpy\__init__.py", line 142, in <module>
    from . import core
  File "C:\Program Files\openage\python\numpy\core\__init__.py", line 54, in <module>
    raise ImportError(msg)
ImportError:```

Trying the numpy version printout produces the same error. Also I've checked and the module file exists in both directories.

Sys ver:
`3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)]`

**Comment by pujok** [comment]
Sorry for the formatting, I tried to fix it for like half an hour but after a number of expletives I just gave up fighting with Markdown

**Comment by seberg** [comment]
@pujok can you check if https://github.com/numpy/numpy/blob/8f83fa577b01fbf5144ca9771ab91bd68f16bb7f/doc/source/user/troubleshooting-importerror.rst would have solved you? Its a piece of new documentation to help users running into these types of issue.

This type of things usually means that either the install did not finish correctly, or you did not do a necessary set-up step. E.g. in anaconda/conda you have to ensure that you activate your environment.

I do not know what `openage` is, so you may want to ask them if your python comes from them...

**Comment by rossbar** [comment]
Closing due to inactivity - if the problem persists please feel free to reopen with updated information.
