### ISSUE TITLE
 when package-kapre is used. The original error was: 'DLL load failed: 找不到指定的模块。'

### ISSUE THREAD

**Issue by v3551G** [numpy/numpy#16149]
In my project(Python3 environment based on Anaconda3), Kapre package(0.1.7) is used, numy(1.18.3), I cpoied a environment from company server to my PC and the error appears. I have tried many methods(including reinstall anaconda3 and re-configure the environment ), but nothing works.
Note that the error only appears when kapre is used in my PC, use numpy alone is ok. and in server, everything is ok.

### Reproducing code example:
No related to code

### Error message:

Traceback (most recent call last):
  File "D:\Program\Python\Anaconda3\envs\tf2.1py3.6\lib\site-packages\numba\core\typeconv\typeconv.py", line 4, in <module>
    from numba.core.typeconv import _typeconv
ImportError: DLL load failed: 找不到指定的模块。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:/softWork/pythonWorkstation/PyCharm/MTLBP/model/train.py", line 14, in <module>
    import data_loader
  File "E:\softWork\pythonWorkstation\PyCharm\MTLBP\preprocess\data_loader.py", line 8, in <module>
    import train
  File "E:\softWork\pythonWorkstation\PyCharm\MTLBP\model\train.py", line 16, in <module>
    import process
  File "E:\softWork\pythonWorkstation\PyCharm\MTLBP\model\process.py", line 14, in <module>
    import model_MTL
  File "E:\softWork\pythonWorkstation\PyCharm\MTLBP\model\model_MTL.py", line 3, in <module>
    import kapre
  File "D:\Program\Python\Anaconda3\envs\tf2.1py3.6\lib\site-packages\kapre\__init__.py", line 4, in <module>
    from . import time_frequency
  File "D:\Program\Python\Anaconda3\envs\tf2.1py3.6\lib\site-packages\kapre\time_frequency.py", line 4, in <module>
    from . import backend, backend_keras
  File "D:\Program\Python\Anaconda3\envs\tf2.1py3.6\lib\site-packages\kapre\backend.py", line 18, in <module>
    import librosa
  File "D:\Program\Python\Anaconda3\envs\tf2.1py3.6\lib\site-packages\librosa\__init__.py", line 12, in <module>
    from . import core
  File "D:\Program\Python\Anaconda3\envs\tf2.1py3.6\lib\site-packages\librosa\core\__init__.py", line 125, in <module>
    from .time_frequency import *  # pylint: disable=wildcard-import
  File "D:\Program\Python\Anaconda3\envs\tf2.1py3.6\lib\site-packages\librosa\core\time_frequency.py", line 11, in <module>
    from ..util.exceptions import ParameterError
  File "D:\Program\Python\Anaconda3\envs\tf2.1py3.6\lib\site-packages\librosa\util\__init__.py", line 77, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "D:\Program\Python\Anaconda3\envs\tf2.1py3.6\lib\site-packages\librosa\util\utils.py", line 10, in <module>
    import numba
  File "D:\Program\Python\Anaconda3\envs\tf2.1py3.6\lib\site-packages\numba\__init__.py", line 20, in <module>
    from numba.misc.special import (
  File "D:\Program\Python\Anaconda3\envs\tf2.1py3.6\lib\site-packages\numba\misc\special.py", line 3, in <module>
    from numba.core.typing.typeof import typeof
  File "D:\Program\Python\Anaconda3\envs\tf2.1py3.6\lib\site-packages\numba\core\typing\__init__.py", line 1, in <module>
    from .context import BaseContext, Context
  File "D:\Program\Python\Anaconda3\envs\tf2.1py3.6\lib\site-packages\numba\core\typing\context.py", line 11, in <module>
    from numba.core.typeconv import Conversion, rules
  File "D:\Program\Python\Anaconda3\envs\tf2.1py3.6\lib\site-packages\numba\core\typeconv\rules.py", line 2, in <module>
    from .typeconv import TypeManager, TypeCastingRules
  File "D:\Program\Python\Anaconda3\envs\tf2.1py3.6\lib\site-packages\numba\core\typeconv\typeconv.py", line 17, in <module>
    raise ImportError(msg % (url, reportme, str(e), sys.executable))
ImportError: Numba could not be imported.
If you are seeing this message and are undertaking Numba development work, you may need to re-run:

python setup.py build_ext --inplace

(Also, please check the development set up guide http://numba.pydata.org/numba-doc/latest/developer/contributing.html.)

If you are not working on Numba development:

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!

The original error was: 'DLL load failed: 找不到指定的模块。'
--------------------------------------------------------------------------------
If possible please include the following in your error report:

sys.executable: D:\Program\Python\Anaconda3\envs\tf2.1py3.6\python.exe
### Numpy/Python version information:

1.18.1 3.6.10 |Anaconda, Inc.| (default, Mar 23 2020, 17:58:33) [MSC v.1916 64 bit (AMD64)]

**Comment by sshojiro** [comment]
@v3551G hello,
I am not an expert of numba but you should check if numba competes with Windows. 
This doesn't sound an issue of numpy but numba. Literally, import of a sub-package in numba causes the above error, saying "DLL file not found". DLL file is required when you use software ONLY on Windows. Please check the type of OS of the company server. 

I recommend you try other OS machine or VM via docker, when you cannot resolve all the environment-package issues.

**Comment by seberg** [comment]
Please check the new website https://numpy.org/devdocs/user/troubleshooting-importerror.html which probably helps you. Generally, I would be careful with just copying environments, there could be binary incompatibilities between the systems (which also would lead to such an error). Here, I think you may just not have set up pycharm correctly.

I will close this for now, but if you do not find a solution or especially one not listed on the help website, please let us know!

**Comment by rossbar** [comment]
Just for the record - the original error seems to be about `numba`, not `numpy`. I agree with @seberg though in that I would recommend against copying environments from one system to another.

**Comment by AI-XiaoBai** [comment]
Hi,You should add the DLL directory of numpy to the environment variable,For example, my path is **_C:\programdata\anaconda3\library\bin_** ，you add yours into environment path, and rebot your computer,it will work.good luck
