### ISSUE TITLE
Pyinstaller Import Error

### ISSUE THREAD

**Issue by asrabon** [numpy/numpy#16163]
Python Version: 3.7.6
Numpy Version: 1.8.4

I am attempting to distribute an executable made utilizing Pyinstaller. This error message doesn't occur on every computer that has run the executable some computers can run the program fine others can't. I have tried multiple versions of numpy from 1.6.x-1.8.x and all result in the same exception. Numpy was installed through wheel packages on PyPi. 

Debug output from Pyinstaller traceback at the bottom:

[23492] PyInstaller Bootloader 3.x
[23492] LOADER: executable is C:\Program Files (x86)\test\test\test.exe
[23492] LOADER: homepath is C:\Program Files (x86)\test\test
[23492] LOADER: _MEIPASS2 is NULL
[23492] LOADER: archivename is C:\Program Files (x86)\test\test\test.exe
[23492] LOADER: Extracting binaries
[23492] LOADER: Executing self as child
[23492] LOADER: set _MEIPASS2 to C:\Users\arabon\AppData\Local\Temp\_MEI234922
[23492] LOADER: Setting up to run child
[23492] LOADER: Creating child process
[23492] LOADER: Waiting for child process to finish...
[16968] PyInstaller Bootloader 3.x
[16968] LOADER: executable is C:\Program Files (x86)\test\test\test.exe
[16968] LOADER: homepath is C:\Program Files (x86)\test\test
[16968] LOADER: _MEIPASS2 is C:\Users\arabon\AppData\Local\Temp\_MEI234922
[16968] LOADER: archivename is C:\Program Files (x86)\test\test\test.exe
[16968] LOADER: SetDllDirectory(C:\Users\arabon\AppData\Local\Temp\_MEI234922)
[16968] LOADER: Already in the child - running user's code.
[16968] LOADER: manifestpath: C:\Users\arabon\AppData\Local\Temp\_MEI234922\test.exe.manifest
[16968] LOADER: Error activating the context: ActivateActCtx:
An attempt to set the process default activation context failed because the process default activation context was already set.

[16968] LOADER: ucrtbase.dll is exists: C:\Users\arabon\AppData\Local\Temp\_MEI234922\ucrtbase.dll
[16968] LOADER: Python library: C:\Users\arabon\AppData\Local\Temp\_MEI234922\python37.dll
[16968] LOADER: Loaded functions from Python library.
[16968] LOADER: Manipulating environment (sys.path, sys.prefix)
[16968] LOADER: sys.prefix is C:\Users\arabon\AppData\Local\Temp\_MEI234922
[16968] LOADER: Pre-init sys.path is C:\Users\arabon\AppData\Local\Temp\_MEI234922\base_library.zip;C:\Users\arabon\AppData\Local\Temp\_MEI234922
[16968] LOADER: Setting runtime options
[16968] LOADER: Bootloader option: pyi-windows-manifest-filename test.exe.manifest
[16968] LOADER: Initializing python
[16968] LOADER: Overriding Python's sys.path
[16968] LOADER: Post-init sys.path is C:\Users\arabon\AppData\Local\Temp\_MEI234922\base_library.zip;C:\Users\arabon\AppData\Local\Temp\_MEI234922
[16968] LOADER: Setting sys.argv
[16968] LOADER: setting sys._MEIPASS
[16968] LOADER: importing modules from CArchive
[16968] LOADER: extracted struct
[16968] LOADER: callfunction returned...
[16968] LOADER: extracted pyimod01_os_path
[16968] LOADER: callfunction returned...
[16968] LOADER: extracted pyimod02_archive
[16968] LOADER: callfunction returned...
[16968] LOADER: extracted pyimod03_importers
[16968] LOADER: callfunction returned...
[16968] LOADER: Installing PYZ archive with Python modules.
[16968] LOADER: PYZ archive: PYZ-00.pyz
[16968] LOADER: Running pyiboot01_bootstrap.py
[16968] LOADER: Running pyi_rth_pkgres.py
[16968] LOADER: Running pyi_rth_win32comgenpy.py
[16968] LOADER: Running pyi_rth_mplconfig.py
[16968] LOADER: Running pyi_rth_mpldata.py
[16968] LOADER: Running pyi_rth_certifi.py
[16968] LOADER: Running pyi_rth__tkinter.py
[16968] LOADER: Running pyi_rth_multiprocessing.py
[16968] LOADER: Running SHUNTWin.py
Traceback (most recent call last):
  File "site-packages\numpy\core\__init__.py", line 24, in <module>
  File "c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
  File "site-packages\numpy\core\multiarray.py", line 14, in <module>
  File "c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
  File "site-packages\numpy\core\overrides.py", line 7, in <module>

**Comment by charris** [comment]
IIRC, there were problems with Pyinstaller due to mishandling of DLL files. Perhaps it is version dependent?

**Comment by asrabon** [comment]
I just tried multiple versions of PyInstaller and the same issue persists.

**Comment by mattip** [comment]
You may have better luck on the pyinstaller issue tracker. When you report it there, see if you can include your setup file and describe where you got your python and numpy: via Anaconda? Via PyPI?

**Comment by Legorooj** [comment]
@mattip you're right that this is probably a PyInstaller issue. DLLs/SOs are a pain. The odd thing about this issue is that according to @asrabon, this only happens on some computers. However, seeing as @asrabon has only posted half of the traceback, I can't help until I have the whole thing. 

On another related topic, PyInstaller uses what are called "hooks", which describe what PyInstaller needs to include in the bundle. We're currently trying to move hooks upstream, into the packages they support, since we now support external hooks via entry points. Would you be interested/happy to have the numpy hooks included in numpy?

**Comment by mattip** [comment]
> Would you be interested/happy to have the numpy hooks included in numpy?

If it is trivial and can be tested, and will not cause too much churn, sure. The test is critical (hopefully something less than a full PyInstaller project) to make sure it works over future changes. Is the API stable? I think we already have some PyInstaller work-arounds, see [`numpy/core/__init__.py`](https://github.com/numpy/numpy/blob/v1.18.4/numpy/core/__init__.py#L101) and [`numpy/random/__init__.py`](https://github.com/numpy/numpy/blob/v1.18.4/numpy/random/__init__.py#L180) as a result of PRs gh-12890, gh-12871, gh-14237, and gh-14141 (found by searching for "freeze"), so a project-sanctioned hook and test might improve the workflow around this.

It would be even better if the hook could be reused by other similar projects: is there a joint forum where such things are discussed?

**Comment by Legorooj** [comment]
> It would be even better if the hook could be reused by other similar projects: is there a joint forum where such things are discussed?

@mattip this API - allowing hooks to be included in their respective packages, not PyInstaller itself - is only a month old. And there isn't really a forum, no. (Not until GitHub Discussions comes out)

It's reasonably simple. You add a new submodule to `numpy`, generally called `__pyinstaller`. This submodule contains a couple of hooks, and a test or two. These are registered with pyinstaller via entry points in numpy's [setup.py](https://github.com/numpy/numpy/blob/master/setup.py#L450). Then it will work out the box with pyinstaller as of next pyinstaller release.

We also recommend an extra step in CI. Simply install `pyinstaller>3.6` and `python -m PyInstaller.utils.run_tests --include_only=numpy`.

I'm just feeling the ground here. If you're interested, I'll provide an issue and PR soon. If you're not, we'll keep the hooks in PyInstaller.

**Comment by mattip** [comment]
@Legorooj please start a  PR. Is there a way to test the hook as a regular test without a whole CI step? I guess if it not too expensive in terms of resource usage we could add a CI step. We run CI on many python versions and architectures, would you recommend more than one?

**Comment by Legorooj** [comment]
@mattip I'd recommend a new pipeline. I'll write up some yaml, and add it in the PR comment, but someone who can create new pipelines would have to add it in Azure. 

It should take about 30 seconds per test of the hook, so of you added it to a new pipeline I'd personally do a matrix build on all 3 platforms and the three supported python versions - PyInstaller only supports 3.5-3.7 at the moment.

**Comment by rgommers** [comment]
> It should take about 30 seconds per test of the hook, so of you added it to a new pipeline I'd personally do a matrix build on all 3 platforms and the three supported python versions - PyInstaller only supports 3.5-3.7 at the moment.

Multiple CI jobs seems like a lot of overhead for one hook. Would be good to run it all in one job, switching Python versions within the same job should not be too hard with conda.

**Comment by rgommers** [comment]
Note: py3.5 is dead already, we support >=3.6

**Comment by Legorooj** [comment]
@rgommers less versions to test. We've got a supported products "rule" in PyInstaller. 

> Multiple CI jobs seems like a lot of overhead for one hook. Would be good to run it all in one job, switching Python versions within the same job should not be too hard with conda.

I wouldn't know; I don't use conda. If you think that's a better solution, then that's fine. 

Oh and https://pyinstaller-sample-hook.readthedocs.io/ and https://github.com/pyinstaller/hooksample are paired examples of how this would be implemented.

**Comment by rossbar** [comment]
As stated, a PR to include the PyInstaller hooks in NumPy would be considered, but absent that it seems there's nothing much else to do here?

**Comment by Legorooj** [comment]
@rossbar we might as well close this - I've closed the linked issue in PyInstaller as stale. We can always reopen in the future.

I'll get to that PR soon hopefully - it's finally made its way to the 3rd item on my OSS todo.
