### ISSUE TITLE
numpy.choose broken for multidimensional arrays

### ISSUE THREAD

**Issue by SrivastavaAnubhav** [numpy/numpy#16307]
The docs for numpy.choose say that 
```np.choose(a,c) == np.array([c[a[I]][I] for I in ndi.ndindex(a.shape)])```
The following example shows that this is not the case. 

### Reproducing code example:
```
>>> A
array([[0, 1],
       [2, 3]])
>>> B
array([[4, 5],
       [6, 7]])
>>> C = np.array([A,B])
>>> C
array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])
>>> ind = np.array([0,1])
>>> np.choose(ind, C)
array([[0, 5],
       [2, 7]])
>>> np.array([C[ind[I]][I] for I in np.ndindex(ind.shape)])
array([[0, 1],
       [6, 7]])
```

I expected that `np.choose` would choose the rows of the output matrix, but I am new to numpy and might be misinterpreting the docs. Either way, the behavior of the two are **not** equivalent as the docs claim.

**Comment by SrivastavaAnubhav** [comment]
@eric-wieser Is the current implementation of numpy.choose correct in the above example then?

**Comment by eric-wieser** [comment]
I think it's probably correct behavior - it would be easier to decode if you picked arrays which were not size 2 in every direction!

**Comment by SrivastavaAnubhav** [comment]
I'm not sure what you mean by probably. The following example has arrays of shape [2,3]. I feel like it should take the first row from the first matrix, and the second row from the second, but it gives an error (it expects 3 indices).

```
>>> A
array([[0, 1, 2],
       [3, 4, 5]])
>>> B
array([[ 6,  7,  8],
       [ 9, 10, 11]])
>>> C = np.array([A,B])
>>> np.choose([0,1], C)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<__array_function__ internals>", line 6, in choose
  File "/home/anubhav/.local/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 433, in choose
    return _wrapfunc(a, 'choose', choices, out=out, mode=mode)
  File "/home/anubhav/.local/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 58, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/home/anubhav/.local/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 47, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
ValueError: shape mismatch: objects cannot be broadcast to a single shape
```

**Comment by rossbar** [comment]
Note also that the full section from the docstring summary says:

```
in its full generality, this function is less simple than it might
seem from the following code description (below ndi =
`numpy.lib.index_tricks`):

``np.choose(a,c) == np.array([c[a[I]][I] for I in ndi.ndindex(a.shape)])``.

But this omits some subtleties.
```
Maybe this incomplete explanation is overly confusing? Generally I think it will be difficult to move forward without a concrete proposal for how the docs could be improved.

**Comment by mattip** [comment]
Closing as stale.
