### ISSUE TITLE
f2py passes wrong arguments with *args and extra arguments

### ISSUE THREAD

**Issue by pv** [numpy/numpy#16357]
If a callback function of the form `f(..., *args)` with a variable-argument part in the signature is given to f2py as a callback with extra arguments, it gets called with wrong arguments.

### Reproducing code example:

```sh
#!/bin/sh
set -e -x -o pipefail
mkdir tmp
pushd tmp

cat <<EOF > foo.pyf
python module foo__user__routines 
    interface foo_user_interface
       subroutine callback(n)
         integer intent(in) :: n
       end subroutine callback
    end interface
end python module foo__user__routines

python module foo
    interface
       subroutine foo(callback)
         use foo__user__routines
         external callback
       end subroutine foo
    end interface
end python module foo
EOF

cat <<EOF > foo.f90
subroutine foo(callback)
  external callback
  call callback(42)
end subroutine foo
EOF

cat <<EOF > run.py
def good(x, arg):
    assert x == 42, (x, arg)
    assert arg == 123, (x, arg)

def bad(x, *arg):
    assert x == 42, (x, arg)
    assert arg == (123,), (x, arg)

import foo

foo.foo(good, callback_extra_args=(123,))
foo.foo(bad, callback_extra_args=(123,))
EOF

python3 -mnumpy.f2py -c -m foo foo.pyf foo.f90
python3 run.py || { set +x; echo "FAIL"; exit 1; }
set +x; echo "OK"
```

### Error message:
```
capi_return is NULL
Call-back cb_callback_in_foo__user__routines failed.
Traceback (most recent call last):
  File "run.py", line 12, in <module>
    foo.foo(bad, callback_extra_args=(123,))
  File "run.py", line 6, in bad
    assert x == 42, (x, arg)
AssertionError: (123, ())
```

### Numpy/Python version information:
1.18.4 3.8.2 (default, Feb 28 2020, 00:00:00)

**Comment by pearu** [comment]
f2py, in particular, the `create_cb_arglist` C function does not implement arbitrary number arguments (nor keywords arguments) support. So, this issue is a feature request and a very reasonable one.
