### ISSUE TITLE
array_equal(a, b, equal_nan=True) throws errors for array with non-numeric values

### ISSUE THREAD

**Issue by ivirshup** [numpy/numpy#16377]
Using the newly added (#16128) `np.array_equal` keyword argument `equal_nan` fails when the values of the passed array aren't accepted by `np.isnan`. This occurs for values like strings.

### Reproducing code example:

```python
import numpy as np
np.array_equal(np.array(list("abc")), np.array(list("abc")), equal_nan=True)
```

### Error message:

```pytb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<__array_function__ internals>", line 6, in array_equal
  File "/Users/isaac/github/numpy/numpy/core/numeric.py", line 2381, in array_equal
    a1nan, a2nan = isnan(a1), isnan(a2)
TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

### Numpy/Python version information:

This occurs on both master and `1.19.0rc1`

```
1.20.0.dev0+3f11db4 3.7.7 (default, Apr 25 2020, 15:09:12) 
[Clang 11.0.3 (clang-1103.0.32.59)]

1.19.0rc1 3.7.7 (default, May  6 2020, 04:59:01) 
[Clang 4.0.1 (tags/RELEASE_401/final)]
```

**Comment by rossbar** [comment]
Thanks for reporting - in this case, the error occurs because `isnan` doesn't support arrays with unicode dtype, though it could in principle. The more general solution would be to add support for strings to `isnan`.

**Comment by anirudh2290** [comment]
not sure what isnan would mean for strings, as in when it will return True ? In the related PR, @ivirshup seems to be handling object dtypes mostly, for string it looks like it ignores the equal_nan flag.

**Comment by rossbar** [comment]
> not sure what isnan would mean for strings, as in when it will return True ?

I'm not sure either, it would have to be discussed. Based on the following:

```python
>>> str(np.nan)
'nan'
```

maybe `np.isnan(['nan']) == np.array([ True])` would be sensible?

> In the related PR, @ivirshup seems to be handling object dtypes mostly, for string it looks like it ignores the equal_nan flag.

Agreed, though it should be noted that in the motivating example, the dtype of the arrays being compared is unicode:

```python
>>> np.array(list('abc'))
array(['a', 'b', 'c'], dtype='<U1')
```

**Comment by seberg** [comment]
Well, we define `isnan` for numerical types right now only, but just like integers, the only valid definition would be that `isnan` is always `False`.

That would be a decision I would be OK with making. Of course you would be creating an array of bools for no reason in this case, but maybe that is not so bad...  We had hesitate for a long time to add e.g. integer and bool loops to `np.isnan`, but since we did add `bool` loops, I am not sure there is a reason for not adding strings, except for the fact that string ufuncs are not quite nice. Which is true, but in this case it will trivial and actually probably just work.

I am generally somewhat against adding support of `object` here, We already support it for objects that define an `.isnan()` method, but unless Python has a standard about it, I do not really like special casing floats or guessing (there are similar issues/PRs which add a lot of "float" capabilities to object dtype).

**Comment by anirudh2290** [comment]
> We already support it for objects that define an .isnan() method

is this done through __array_ufunc__ implementation for the class.


> EDIT: To be clear, my point about supporting/special casing floats is, that if you do not have floats, things will still error (hopefully), and if you _do_ have floats, why don't you just convert to a float array?

+1 , I think it makes sense to just keep erroring unless it has a isnan method implemented. 

So, if i understand correctly the best path forward is to add support for isnan for string dtype and continue with existing behavior for object dtypes and probably not change array_equal (or maybe improve error message?).

**Comment by seberg** [comment]
Yes, lets ignore `object` here for now, its trickier.

String I think we can just propose, may need a bit of discussion (or maybe digging up the old discussion when we added bools and ints). We have no string ufuncs (this is mainly because you have to set the output string length correctly, which made, also me, always think that its tricky). The other point is that string promotion is still broken (weakly typed) which could lead to strange things (I would like to move that concat + string promotion deprecation forward!).
But this is a unary ufunc, with boolean output that is always `False`, so neither of those issues would stand in the way.

**Comment by anirudh2290** [comment]
okay thanks @seberg for the guidance ! So @ivirshup if you are interested in proposing something for string support for isnan that would be great here. Maybe some of the discussion topics that @seberg mentioned may be : https://github.com/numpy/numpy/pull/12988 and the xref'd issues. 

Given the current discussion, I think we should close the current PR #16378 .

**Comment by ivirshup** [comment]
Thanks for all the discussion and input. I'm not sure I completely agree with the conclusion you've drawn though. 

This is because the use case I was hoping to use this functionality for will often have object arrays, for variable length strings. This comes from reading variable length strings out of `hdf5` or `zarr` arrays when using pandas dataframes. If the `isnan` approach is taken, and object are ignored, this will error:

```python
df = pd.DataFrame({"str": list("abc")})                                                                             
np.array_equal(df, df, equal_nan=True)                                                                              
```

I think that my PR is a bug fix for newly added behaviour, and has no chance of breaking code that relies on numpy releases. Changing the behaviour for `isnan` seems more fraught. It also raises questions about the other `is*` functions. Does it make sense to call `isinf` on a non-numeric value? I'd say no. To me, it makes sense for these functions to work on `bool`s and `ints`s since those types are otherwise valid in numeric operations. I'd note this seems to be the reasoning in the PR @anirudh2290 linked as well.

**Comment by seberg** [comment]
Well, the object case is just tricky.  The string case is pretty simple, the question is how to address it. I dislike the idea to just special case strings in multiple places in the code. If `isnan` worked for strings, it would be simple and e.g. adding a fast-path would seem OK. So that is why that would be me preferred approach if we can agree to implement `isnan`.

Object to me shows the exact problem, there is no clear way to define `isnan` for it at all, so there is also no clear way to know how it should be handled in `arrays_equal` or `isclose`, etc.  There are multiple functions making use of this type of logic, so a central ground truth would be much preferable to me. `np.isnan` could be that central ground-truth.

You are right that this is new code, and thus we have a lot of freedom.  But if we do nothing we actually retain that freedom right now, if we hastily allow objects it will be almost impossible to disallow it when we notice that the implementation is incorrect.

So if we can agree on defining `isnan` as `False` for non-numerical types (I am not quite sure, but not really against that) then the only remaining issue is `object` dtype.
In the mid to long term (lets say by next year hopefully). We will solve your problem not by allowing objects, but rather by creating a new dtype for variable length strings, which can define `isnan` reasonable.

**Comment by anirudh2290** [comment]
I think we can add support for isnan for strings, but to the original question of whether we want to support isfinite and isinf, I am not too sure. I think we can start with isnan for now, isfinite and isinf are more likely to be used with isclose, which i dont think is going to be needed here. Though it is a bit inconsistent to support string only for isnan and not isfinite and isinf.

**Comment by ivirshup** [comment]
Sorry for taking so long to respond here! I had some other work which took priority for a bit.

I think we're viewing this problem in different ways. The issue I am interested in addressing here that `array_equal(a, b, equal_nan=True)` shouldn't throw errors when the values in `a` or `b` aren't numeric. That's just to make it a more useful function, with less footguns. This follows with the intuitive (if not exactly precise) nature of `array_equal` and `equal`, like how `np.array_equal(-np.float64(0), np.float64(0)) == True`.

The solution I've proposed in my PR achieves this, and has the added bonus of being more performant for numeric types.

> But if we do nothing we actually retain that freedom right now, if we hastily allow objects it will be almost impossible to disallow it when we notice that the implementation is incorrect.

`np.array_equal` already supports objects, so I don't think this is changing much. I also think I've taken a very conservative approach here. No object besides `np.nan` can possibly return true here. To me, making `isnan` accept other types just so `array_equal` doesn't error is quite possibly incorrect and impossible to disallow once it's implemented.

> So if we can agree on defining isnan as False for non-numerical types (I am not quite sure, but not really against that) then the only remaining issue is object dtype.

This seems too large in scope for this small issue, and isn't behaviour I'd like to see in numpy. To me, `isnan` is asking a pretty specific question, whether a numeric value is `NaN`. This is quite similar to asking if a value is `Inf`. Neither of these really makes sense to ask of a string or dictionary. If these functions are called on a non-numeric object, that seems likely to be a programming error.

> Object to me shows the exact problem, there is no clear way to define isnan for it at all

To me, this is a larger issue with numpy's dtype system being inflexible. To me, the correct solution here is to allow user defined types to set their own behaviour for `isnan`. But that could require allowing users to define their own dtypes and register implementations for `ufuncs`.

**Comment by seberg** [comment]
@ivirshup the proposed solution will fail if you put `float("nan")` into any of the arrays. `NaN` is *not* a singleton in Python.
So you will have to use `math.isnan`, but after that, I will mention `complex(NaN)`, so you will have to branch off into `cmath.isnan()`.  Only for me to mention `np.clongdouble(np.nan)`, which may somewhat work with `cmath.isnan()`, but it will at least be slow.  Meaning you have to handle NumPy scalars specifically (which at least is well defined).  However, there is also a `decimal` NaN, and pandas `NaT` may be different from our `NaT`, should we allow that?  There is a reason why I don't like supporting `object` here, and its not about `np.equal_arrays` specifically, its about the difficulties of defining `np.isnan` for `object` dtype.

Its a rabbit hole.  Some of the performance improvements may be fine. Of course a single pass algorithm will vastly outperform multiple passes.  But I think we have to consider benchmark concerns separate from API changes.

**Comment by user27182** [comment]
Just came across this issue when trying to use `equal_nan=True`. Without getting into the weeds about nan definitions, for my use case I have a mix of numeric and string arrays, and I was hoping I could use `equal_nan=True` and just have it work. But, it throws an error for string arrays, so now I am stuck with explicitly checking the dtype, and only using `equal_nan=True` conditionally if the input is numeric, else do not use the keyword. It would be nice to just use it with string arrays without throwing error.
