### ISSUE TITLE
Array-valued np.polynomial.Polynomial doesn't work

### ISSUE THREAD

**Issue by pv** [numpy/numpy#16380]
The `np.polynomial.Polynomial` does not seem to handle array-valued polynomials, although this is advertised at some places in its documentation.

E.g. `help(np.polynomial.Polynomial.fit)` [says](https://numpy.org/devdocs/reference/generated/numpy.polynomial.polynomial.Polynomial.fit.html#numpy.polynomial.polynomial.Polynomial.fit):

"yarray_like, shape (M,) or (M, K): y-coordinates of the sample points. Several data sets of sample points sharing the same x-coordinates can be fitted at once by passing in a 2D-array that contains one dataset per column."

However, it doesn't seem to work. Maybe this is a left-over "intended feature" that didn't make it in the final implementation and the documentation is just wrong. Even if so, this feature would be useful to have.

### Reproducing code example:
```python
import numpy as np
np.polynomial.Polynomial.fit([0, 1, 2], np.array([[1, 2, 3], [4, 5, 6]]).T, deg=2)
```

### Error message:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.8/site-packages/numpy/polynomial/_polybase.py", line 898, in fit
    return cls(coef, domain=domain, window=window)
  File "/usr/lib64/python3.8/site-packages/numpy/polynomial/_polybase.py", line 266, in __init__
    [coef] = pu.as_series([coef], trim=False)
  File "/usr/lib64/python3.8/site-packages/numpy/polynomial/polyutils.py", line 182, in as_series
    raise ValueError("Coefficient array is not 1-d")
ValueError: Coefficient array is not 1-d
```

### Numpy/Python version information:
1.18.4 3.8.2 (default, Feb 28 2020, 00:00:00)

**Comment by wrzadkow** [comment]
Interestingly `_fit()` instead of `fit()` works here:

```
>>> np.polynomial.Polynomial._fit([0, 1, 2], np.array([[1, 2, 3], [4, 5, 6]]).T, deg=2)
array([[ 1.00000000e+00,  4.00000000e+00],
       [ 1.00000000e+00,  1.00000000e+00],
       [-7.00098452e-16,  6.46244724e-16]])
```

This suggest there might be a simple solution for the bug raised by @pv, as the necessary functionality seems to be implemented, with the problem being only in `fit()` always [returning](https://github.com/numpy/numpy/blob/a603d6382736bed4d787dcc6d8f9dac09db6ce21/numpy/polynomial/_polybase.py#L886) a single instance of Polynomial: `return cls(coef, domain=domain, window=window)`

I am now investigating in more details and will be glad to end up submitting a PR if I'm on the right track.

**Comment by charris** [comment]
Duplicate of #4554.

**Comment by rossbar** [comment]
@wrzadkow you're definitely on the right track - the problem isn't with the fitting (as you point out, `_fit` works as-advertised), it's in the construction of polynomial instances in the `fit` classmethod that fails to handle the output from `_fit` correctly. It should be straightforward to fix in `ABCPolyBase`.

**Comment by charris** [comment]
@pv It would be helpful if you discussed exactly what you want to do. It is possible when not using the classes to store the coefficients in columns and eval all of them. For instance, I once used 3 dimensional arrays to store calibration polynomials for pixel arrays that could be applied to correct images with a single call. That may be preferable to a list of Polynomial instances.

**Comment by rossbar** [comment]
IMO it makes sense for the `fit` method of the convenience classes to return instances of the corresponding class. At least that is consistent with the behavior of the other class methods (which return instances rather than coefficient arrays) and also consistent with the classmethod docstring, which says a series instance is returned.

> It is possible when not using the classes to store the coefficients in columns and eval all of them. 

Agreed, this functionality is still present, and if users want it they can use the appropriate `*fit` function (i.e. `polyfit`, `chebfit`, `hermfit`, etc.) from the corresponding module to get this behavior. This use-case could be explicitly documented.

**Comment by pv** [comment]
@charris: I was hoping to see numpy.polynomial.Polynomial to support array-valued polynomials, i.e. `f(x) = c[0] + c[1]*x + c[2]*x**2 + ...` where the coefficients `c` are arrays of the same shape. (Similarly as the "new" scipy spline/piecewise polynomial classes.)

Here, I was not so much after `Polynomial.fit`, but instead having the array-valued support in the base class itself. I'm not sure if lists of polynomials are that useful in itself, as users can already write equivalent for loops themselves.

**Comment by charris** [comment]
@pv If I understand correctly, that is already supported by the functions in `numpy/polynomial/polynomial`. For instance
```
In [1]: from numpy.polynomial.polynomial import polyval                         

In [2]: c = np.array([[0, 0],[0, 0], [1, 2]], dtype=np.float64)                 

In [3]: x = np.arange(4).reshape(2,2)                                           

In [4]: polyval(x, c, tensor=False)                                             
Out[4]: 
array([[ 0.,  2.],
       [ 4., 18.]])
```

**Comment by pv** [comment]
Yes. The class-based interface however does not support that, and I filed this issue I had expected it would.

**Comment by charris** [comment]
@pv Ah. I think we could probably do that. The `domain` and `window` would need to be fixed for all the polynomials, and some other things would need to be adjusted.

**Comment by eric-wieser** [comment]
One thing to watch out for here - do we want to rule out an API for the classes where an `NxM` array of coefficients represents `(x,y) -> sum_mn {c_ij x^i y^j}`?

**Comment by charris** [comment]
@eric-wieser Mixing the two types, `tensor={True, False}` gets complicated, but could be done. Dealing with derivatives and integrals also gets tricky. I'm open to ideas of what such an interface would look like

**Comment by charris** [comment]
And now I'm wondering if polyval2d handles arrays of two variable polynomials...

**Comment by pv** [comment]
The tensor product basis adds some more complications, are less often needed than 1-d, and AFAIK only limited operations on them are implemented in the current codebase. So I'm not sure it's useful to stuff that in the existing Polynomial/etc. classes. Extending the current Polynomial class to array-valued is probably not so hard, but stuffing the n-dim there too sounds like quite a bit more work, which could make sense to sidestep by limiting to 1d and later maybe adding a separate nd class if warranted.

**Comment by charris** [comment]
@pv Agree, my thoughts would be to just do the `tensor=False` case. The difference between the two cases is that one uses `*` and the other does outer (tensor) products. For classes, one could add Polynomial2D, etc. There is also the possibility of a more fundamental base class with just the basic operations, but those can always be done later and I suspect go beyond what should be in NumPy.

**Comment by mhvk** [comment]
Comment from the sidelines: right now all the attributes of a polynomial are stored as `ndarray`, but when evaluating using a polynomial instance, it effectively has shape `()` for broadcasting purposes.

I don't think you'd ever want to have anything explicitly broadcast against the dimension that numbers the coefficients (which is the current `coef.shape`), so if one makes `coef`, `window`, and `domain` multidimensional, one has to think how one keeps track of the dimension that is "special" and, as far as the shape of the polynomial instance is concerned, hidden, so that the `Polynomial` can have the shape of the rest, and can easily be indexed and sliced.

The solution I have used in astropy's [`Distribution`](https://github.com/astropy/astropy/blob/master/astropy/uncertainty/core.py) (which does error propagation using Monte-Carlo samples), is to use a structured array. E.g., for `Polynomial`, `coef` could normally be a scalar with structured dtype like `('coeff', [('f8', (ncoeff,))])` (one might even think of putting `domain` and `window` in it to). Then, indexing, reshaping, etc., become extremely easy.

**Comment by rossbar** [comment]
There's a lot of really interesting discussion here re: what an expansion of the class-based API could look like for supporting coefficient arrays. In it's current form, the documentation is definitely out-of-sync with the `fit` class method, so maybe it's best to correct the docstring for now rather than update what the `fit` method returns, as that seems to be a subset of a larger discussion.

Also, from the discussion here it seems that returning a list of polynomial instances is not desired, so I would propose to:
 1. Keep this issue open (possibly with a new title) for discussion of expanding the polynomial convenience classes (or create other `nd` classes) that support array-valued coefficients.
 2. Close #16403, and instead:
 3. Update the docstring for the fit class method.

Does like a reasonable approach (for now)?

**Comment by wrzadkow** [comment]
For me this looks like a very reasonable short-term solution. As the author of PR #16403, I'd be glad to update the docstring instead if this approach is agreed upon.
