### ISSUE TITLE
Error on running a Simulation sample from xlwings website

### ISSUE THREAD

**Issue by mdigilov** [numpy/numpy#16479]
Hello - please help. I downloaded a simulation sample from xlwings and was trying to see how it works.

Anaconda 2020.02
Python 3.7.6
Numpy 1.18.1
xlWings 0.17.1

Excel 2013

I receive this error message:
---------------------------
Error
---------------------------
C:\ProgramData\Anaconda3\lib\site-packages\numpy\__init__.py:140: UserWarning: mkl-service package failed to import, therefore Intel(R) MKL initialization ensuring its correct out-of-the box operation under condition when Gnu OpenMP had already been loaded by Python process is not assured. Please install mkl-service package, see http://github.com/IntelPython/mkl-service

  from . import _distributor_init

Traceback (most recent call last):

  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\__init__.py", line 24, in <module>

    from . import multiarray

  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\multiarray.py", line 14, in <module>

    from . import overrides

  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\overrides.py", line 7, in <module>

    from numpy.core._multiarray_umath import (

ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "d:\users\max\desktop\xlswings - simulation\simulation.py", line 9, in <module>

    import numpy as np

  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\__init__.py", line 142, in <module>

    from . import core

  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\__init__.py", line 54, in <module>

    raise ImportError(msg)

ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.

- Try uninstalling and reinstalling numpy.

- If you have already done that, then:

  1. Check that you expected to use Python3.7 from "C:\ProgramData\Anaconda3\pythonw.exe",

     and that you have no directories in your PATH or PYTHONPATH that can

     interfere with the Python and numpy version "1.18.1" you're trying to use.

  2. If (1) looks fine, you can open a new issue at

     https://github.com/numpy/numpy/issues.  Please include details on:

     - how you installed Python

     - how you installed numpy

     - your operating system

     - whether or not you have multiple versions of Python installed

     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`

  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on

an existing issue about this - open a new one instead.

Original error was: DLL load failed: The specified module could not be found.

Press Ctrl+C to copy this message to the clipboard.
---------------------------
OK   
---------------------------

**Comment by mdigilov** [comment]
i tried uninstalling and installing numpy and error message still persisted

**Comment by mattip** [comment]
Please read [this page](https://numpy.org/devdocs/user/troubleshooting-importerror.html) carefully, especially the part about [activating](https://numpy.org/devdocs/user/troubleshooting-importerror.html#using-python-from-conda-anaconda) your conda environment.

**Comment by rossbar** [comment]
Closing due to inactivity - feel free to reopen if issue persists.
