### ISSUE TITLE
Import error after upgrade of libopenblas

### ISSUE THREAD

**Issue by Eleluku** [numpy/numpy#16615]
We are using a conda environment with the following dependencies to connect to a jdbc database:

- python=3.7.4
- jpype1=0.6.3
- jaydebeapi=1.1.1

As of today, importing jpye fails with the error `ImportError: numpy.core.multiarray failed to import`. When importing numpy directly, I get the error message below.

```python
import numpy as np
```

### Error message:

```
Traceback (most recent call last):
  File "/home/eleluku/.conda/envs/myenv/lib/python3.7/site-packages/numpy/core/__init__.py", line 24, in <module>
    from . import multiarray
  File "/home/eleluku/.conda/envs/myenv/lib/python3.7/site-packages/numpy/core/multiarray.py", line 14, in <module>
    from . import overrides
  File "/home/eleluku/.conda/envs/myenv/lib/python3.7/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: libcblas.so.3: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/eleluku/example.py", line 3, in <module>
    import numpy
  File "/home/eleluku/.conda/envs/myenv/lib/python3.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/home/eleluku/.conda/envs/myenv/lib/python3.7/site-packages/numpy/core/__init__.py", line 50, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.7 from "/home/eleluku/.conda/envs/myenv/bin/python"
  * The NumPy version is: "1.18.5"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: libcblas.so.3: cannot open shared object file: No such file or directory
```

I found out, that the recent upgrade of the dependecy `libopenblas` from 0.3.9 to 0.3.10 broke this. After downgrading to 0.3.9 I was able to import numpy again. 

Anyone else experiencing this behaviour?

**Comment by mattip** [comment]
> I found out, that the recent upgrade of the dependecy libopenblas from 0.3.9 to 0.3.10 broke this

Did conda update numpy to use 0.3.10? Could you open an issue with them, we do not control their packaging.

**Comment by Eleluku** [comment]
Thanks for your answer. I filed an issue at the conda-forge numpy-feedstock: https://github.com/conda-forge/numpy-feedstock/issues/193
