### ISSUE TITLE
Unexpected error message when using random.multinomial with a specific input

### ISSUE THREAD

**Issue by alexn11** [numpy/numpy#16688]
I've stumbled upon this probability distribution and it seems that it breaks _random.multinomial_. See the code below.
I get the following error message
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mtrand.pyx", line 4199, in numpy.random.mtrand.RandomState.multinomial
ValueError: sum(pvals[:-1]) > 1.0
```
But as checked below, the sum of pv is exactly 1, not sure what's happening there.

### Reproducing code example:

```python
import numpy as np
pv = np.array([1.4424976e-09, 7.4651174e-10, 2.6731199e-14, 1.8288955e-07,
       3.7338774e-12, 2.4565782e-11, 4.8849003e-08, 7.5392682e-06,
       2.5213736e-09, 8.6392421e-11, 1.5464953e-15, 8.4649406e-11,
       4.8575238e-10, 1.8040901e-13, 1.1940503e-07, 5.3627885e-10,
       1.0590560e-09, 1.8160169e-18, 4.0212014e-11, 4.7033932e-08,
       1.6498967e-05, 2.8405358e-08, 1.0944078e-12, 1.5611396e-10,
       3.9737486e-10, 9.7820538e-01, 8.2896645e-07, 8.3199542e-10,
       3.7056649e-10, 3.8565759e-10, 2.3704663e-11, 1.0012602e-10,
       1.1705990e-09, 1.6031695e-08, 5.7553581e-08, 7.8330364e-10,
       3.8545368e-11, 7.8553829e-04, 8.4968074e-11, 4.2295811e-10,
       2.8655507e-12, 8.0123971e-07, 7.0235245e-10, 7.1000192e-09,
       2.0980526e-02, 2.4243457e-06, 1.2416263e-13, 4.5905411e-12,
       1.1153589e-12, 2.6267855e-08, 6.6627046e-09, 9.6725593e-11,
       1.7527905e-14, 9.9620270e-11, 4.4269616e-10], dtype='float32')
assert(pv.sum()==1.)
assert(np.all((0<pv)&(pv<1)))
np.random.multinomial(1, pv, 1)
```

### Error message:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mtrand.pyx", line 4199, in numpy.random.mtrand.RandomState.multinomial
ValueError: sum(pvals[:-1]) > 1.0
```

### Numpy/Python version information:

1.18.5 3.8.3 (default, May 17 2020, 18:15:42) 
[GCC 10.1.0]

**Comment by alexn11** [comment]
Turns out there's a difference in the results of np.sum and sum probably related to the fact that the array is made of 32 bits float and sum probably uses higher precision.

**Comment by WarrenWeckesser** [comment]
> ... the array is made of 32 bits float and sum probably uses higher precision.

Yes, exactly.  Internally, `multinomial` casts the `pvals` array to an array of `float64`, and the sum of those values when cast to `float64` exceeds 1.

Here's your data, and as you noted, the sum of the `float32` values is 1:
```
In [214]: pv = np.array([1.4424976e-09, 7.4651174e-10, 2.6731199e-14, 1.8288955e-07, 
     ...:        3.7338774e-12, 2.4565782e-11, 4.8849003e-08, 7.5392682e-06, 
     ...:        2.5213736e-09, 8.6392421e-11, 1.5464953e-15, 8.4649406e-11, 
     ...:        4.8575238e-10, 1.8040901e-13, 1.1940503e-07, 5.3627885e-10, 
     ...:        1.0590560e-09, 1.8160169e-18, 4.0212014e-11, 4.7033932e-08, 
     ...:        1.6498967e-05, 2.8405358e-08, 1.0944078e-12, 1.5611396e-10, 
     ...:        3.9737486e-10, 9.7820538e-01, 8.2896645e-07, 8.3199542e-10, 
     ...:        3.7056649e-10, 3.8565759e-10, 2.3704663e-11, 1.0012602e-10, 
     ...:        1.1705990e-09, 1.6031695e-08, 5.7553581e-08, 7.8330364e-10, 
     ...:        3.8545368e-11, 7.8553829e-04, 8.4968074e-11, 4.2295811e-10, 
     ...:        2.8655507e-12, 8.0123971e-07, 7.0235245e-10, 7.1000192e-09, 
     ...:        2.0980526e-02, 2.4243457e-06, 1.2416263e-13, 4.5905411e-12, 
     ...:        1.1153589e-12, 2.6267855e-08, 6.6627046e-09, 9.6725593e-11, 
     ...:        1.7527905e-14, 9.9620270e-11, 4.4269616e-10], dtype='float32')       

In [215]: pv.sum()                                                                    
Out[215]: 1.0
```
But when cast to `float64`, the sum is 1.00000009300622
```
In [216]: pv.astype(np.float64).sum()                                                 
Out[216]: 1.00000009300622
```
