### ISSUE TITLE
Can't install the 64-bit version of numpy for Python 3.8

### ISSUE THREAD

**Issue by luciansmith** [numpy/numpy#16707]
When I go to https://pypi.org/project/numpy/#files

and download the 'win_amd64' wheel files, the Python 3.6 and Python 3.7 files work fine.  But the Python 3.8 file does not:

### Reproducing code example:

```
C:\[...]\Python38\python.exe --version
Python 3.8.3

C:\[...]\Python38\python.exe -m pip install numpy-1.19.0-cp38-cp38-win_amd64.whl
ERROR: numpy-1.19.0-cp38-cp38-win_amd64.whl is not a supported wheel on this platform.

C:\[...]\Python38\python.exe
Python 3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:37:02) [MSC v.1924 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> platform.architecture()
('64bit', 'WindowsPE')

```

Any suggestions?  Do I need a different version of Python 3.8?

I did notice that the 3.6 and 3.7 files have an 'm' in them while the 3.8 version does not, but renaming it to have an 'm' didn't help:

```
06/29/2020  09:38 AM        12,983,036 numpy-1.19.0-cp36-cp36m-win_amd64.whl
06/29/2020  09:39 AM        12,983,183 numpy-1.19.0-cp37-cp37m-win_amd64.whl
06/29/2020  09:39 AM        13,026,850 numpy-1.19.0-cp38-cp38-win_amd64.whl
```

**Comment by charris** [comment]
Are you sure your python is 64 bits? The usual way to do this would be
```
\Python38\python.exe -m pip install numpy
```
I'm wondering why you downloaded the files?

**Comment by luciansmith** [comment]
Update:  I decided to try installing the '32bit' version just for kids.  It installed fine, but failed on import:

```
C:\[...]\Python38\python.exe -m pip install numpy-1.19.0-cp38-cp38-win32.whl
Processing c:\users\lucian\desktop\numpy wheels\numpy-1.19.0-cp38-cp38-win32.whl
Installing collected packages: numpy
  WARNING: The script f2py.exe is installed in 'C:\Users\Lucian\AppData\Local\Programs\Python\Python38\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed numpy-1.19.0

C:\[...]\Python38\python.exe
Python 3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:37:02) [MSC v.1924 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Lucian\AppData\Local\Programs\Python\Python38\lib\site-packages\numpy\__init__.py", line 138, in <module>
    from . import _distributor_init
  File "C:\Users\Lucian\AppData\Local\Programs\Python\Python38\lib\site-packages\numpy\_distributor_init.py", line 26, in <module>
    WinDLL(os.path.abspath(filename))
  File "C:\Users\Lucian\AppData\Local\Programs\Python\Python38\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 is not a valid Win32 application
>
```

If I rename the amd64 file to the win32 name, that also installs 'successfully' but is differently broken on import:

```
Processing c:\users\lucian\desktop\numpy wheels\numpy-1.19.0-cp38-cp38-win32.whl
Installing collected packages: numpy
  WARNING: The script f2py.exe is installed in 'C:\Users\Lucian\AppData\Local\Programs\Python\Python38\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed numpy-1.19.0

C:\Users\Lucian\Desktop\Numpy Wheels>C:\Users\Lucian\AppData\Local\Programs\Python\Python38\python.exe
Python 3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:37:02) [MSC v.1924 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
Traceback (most recent call last):
  File "C:\Users\Lucian\AppData\Local\Programs\Python\Python38\lib\site-packages\numpy\core\__init__.py", line 22, in <module>
    from . import multiarray
  File "C:\Users\Lucian\AppData\Local\Programs\Python\Python38\lib\site-packages\numpy\core\multiarray.py", line 12, in <module>
    from . import overrides
  File "C:\Users\Lucian\AppData\Local\Programs\Python\Python38\lib\site-packages\numpy\core\overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Lucian\AppData\Local\Programs\Python\Python38\lib\site-packages\numpy\__init__.py", line 140, in <module>
    from . import core
  File "C:\Users\Lucian\AppData\Local\Programs\Python\Python38\lib\site-packages\numpy\core\__init__.py", line 48, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.8 from "C:\[...]\Python38\python.exe"
  * The NumPy version is: "1.19.0"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'
```
```

**Comment by luciansmith** [comment]
A straight 'install numpy', as suggested, also installs and then fails to import.  As you can see, it downloads the non-64-bit version.

I guess something in my version of Python 3.8 thinks it's 32-bit, but it's actually 64?

```
C:\[...]\Python38\python.exe -m pip install numpy
Collecting numpy
  Downloading numpy-1.19.0-cp38-cp38-win32.whl (10.9 MB)
     |████████████████████████████████| 10.9 MB 3.3 MB/s
Installing collected packages: numpy
  WARNING: The script f2py.exe is installed in 'C:\Users\Lucian\AppData\Local\Programs\Python\Python38\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed numpy-1.19.0

C:\Users\Lucian\Desktop\Numpy Wheels>C:\Users\Lucian\AppData\Local\Programs\Python\Python38\python.exe
Python 3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:37:02) [MSC v.1924 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Lucian\AppData\Local\Programs\Python\Python38\lib\site-packages\numpy\__init__.py", line 138, in <module>
    from . import _distributor_init
  File "C:\Users\Lucian\AppData\Local\Programs\Python\Python38\lib\site-packages\numpy\_distributor_init.py", line 26, in <module>
    WinDLL(os.path.abspath(filename))
  File "C:\Users\Lucian\AppData\Local\Programs\Python\Python38\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 is not a valid Win32 application
```

**Comment by mattip** [comment]
Something is off with your python. Did you install it over another version or in a clean directory?

**Comment by luciansmith** [comment]
Installed in a clean directory!  Several times, at this point.  Then I went through and uninstalled all the versions of Python I could find, and then re-installed Python locally.  Exact same behavior.

This is with https://www.python.org/ftp/python/3.8.3/python-3.8.3-amd64.exe installed locally.

**Comment by luciansmith** [comment]
(Then I did the same thing with Python 3.7 from https://www.python.org/ftp/python/3.7.8/python-3.7.8-amd64.exe and everything was fine.)

**Comment by luciansmith** [comment]
And, tried to install other random partially-binary packages, and it failed for them, too.  Which means there's something wrong with Python itself, and is not a numpy issue.  So I'm closing this!  Thanks for the pointers.

**Comment by luciansmith** [comment]
Finally figured out the problem, in case anyone else finds this later:  I was running Python from the "Developer Command Prompt for VS 2019"--that's my go-to command prompt for Windows-based things I have to do, since it sets up some convenient environment variables.

However, one of those environment variables clearly created problems for Python, since (perhaps?) the version of Python that ships with VS 2019 is 32-bit, or something.  Running the exact same commands as above from a cygwin window worked fine.  I haven't tried, but I am going to guess that running them from 'cmd' would also work.

**Comment by charris** [comment]
Thanks for the update.

**Comment by jarenduan** [comment]
@luciansmith  I made the same mistake of trying running it in Developer Command Prompt. 

You save my day!
