### ISSUE TITLE
Importing numpy fails if there is a file named `random.py` in the current directory.

### ISSUE THREAD

**Issue by luciotorre** [numpy/numpy#16753]
Importing numpy fails if there is a file named `random.py` in the current directory.

### Reproducing code example:
```
lucio@solenoid:~/tmp/stest$ ls -la
total 8
drwxrwxr-x 2 lucio lucio 4096 jul  4 21:20 .
drwxrwxr-x 7 lucio lucio 4096 jul  4 20:47 ..
lucio@solenoid:~/tmp/stest$ python3 --version
Python 3.8.2
lucio@solenoid:~/tmp/stest$ python3 -c "import numpy; print(numpy.__version__)"
1.17.4
lucio@solenoid:~/tmp/stest$ touch random.py
lucio@solenoid:~/tmp/stest$ python3 -c "import numpy; print(numpy.__version__)"
Traceback (most recent call last):
  File "bit_generator.pyx", line 40, in numpy.random.bit_generator
  File "/usr/lib/python3.8/secrets.py", line 20, in <module>
    from random import SystemRandom
ImportError: cannot import name 'SystemRandom' from 'random' (/home/lucio/tmp/stest/random.py)
<traceback clipped>
```

```
$ python3 -c "import sys, numpy; print(numpy.__version__, sys.version)"
1.17.4 3.8.2 (default, Apr 27 2020, 15:53:34) 
[GCC 9.3.0]
```

**Comment by luciotorre** [comment]
Doh, I'm sure there is a rule somewhere about not naming things like that.
