### ISSUE TITLE
 Importing the multiarray numpy extension module failed

### ISSUE THREAD

**Issue by idodidodi** [numpy/numpy#16781]
### Reproducing code example:

```python
import numpy as np
<< your code here >>
```

### Error message:

dlopen(../numpy/core/_multiarray_umath.cpython-36m-darwin.so, 2): Library not loaded: @loader_path/../.dylibs/libopenblasp-r0.3.5.dev.dylib\n  Referenced from: ../numpy/core/_multiarray_umath.cpython-36m-darwin.so\n  Reason: image not found

File "numpy/core/__init__.py", line 16, in <module>
File "../pythonVirtualEnv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
File "numpy/core/multiarray.py", line 12, in <module>
File "../pythonVirtualEnv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
File "numpy/core/overrides.py", line 6, in <module>
ImportError: dlopen(../numpy/core/_multiarray_umath.cpython-36m-darwin.so, 2): Library not loaded: @loader_path/../.dylibs/libopenblasp-r0.3.5.dev.dylib
  Referenced from: ../numpy/core/_multiarray_umath.cpython-36m-darwin.so
  Reason: image not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "wpivot-client", line 16, in <module>
    import utils

File "../pythonVirtualEnv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
exec(bytecode, module.__dict__)
  File "utils/__init__.py", line 1, in <module>
    from .files import *
  File "../pythonVirtualEnv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
exec(bytecode, module.__dict__)
File "utils/files.py", line 18, in <module>
import numpy as np
File "../pythonVirtualEnv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
exec(bytecode, module.__dict__)
ImportError: 

### Numpy/Python version information:
Python installation > standard installation + modules 
 Numpy installation - standard installation

 OS: Catalina
Python versions:   2.7, 3.6.4

**Comment by rossbar** [comment]
Looks like PyInstaller was used - perhaps the discussion in #16163 is relevant

**Comment by rossbar** [comment]
I'm going to close this due to inactivity. If the issue persists, please feel free to reopen with info about the system and installation method, and what steps have been tried.
