### ISSUE TITLE
bincount fails for complex weights

### ISSUE THREAD

**Issue by feature-engineer** [numpy/numpy#16903]
bincount would only work for real weights, and not complex ones.

### Reproducing code example:

```python
import numpy as np
np.bincount(np.arange(3), weights=1j * np.arange(3))
```

### Error message:

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "<__array_function__ internals>", line 6, in bincount
TypeError: Cannot cast array data from dtype('complex128') to dtype('float64') according to rule 'safe'

### Numpy/Python version information: 

1.18.4 3.7.7

**Comment by rossbar** [comment]
Thanks for the report. Out of curiosity, do you have a use-case for complex weights in bincount? In other words would you consider this a feature request, a bug, or maybe a documentation problem?

**Comment by eric-wieser** [comment]
I'd say feature request, there's no incorrect result here at least.

**Comment by feature-engineer** [comment]
@rossbar I've implemented circle detection using phase modulation along the edge-perpendicular ray, I'm using bincount to create the hough space from these complex values. Where there's an agreement on the radius, the complex numbers interfere constructively, and otherwise they mostly cancel out. You can read more about this kind of Circular Hough Transform here: 

https://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.725.6401&rep=rep1&type=pdf

**Comment by rgommers** [comment]
If anyone revisits this, there's a detailed suggestion for this in https://github.com/numpy/numpy/issues/23313#issuecomment-1451485942
