### ISSUE TITLE
Building documentation in a conda environment (Arch Linux)

### ISSUE THREAD

**Issue by cooperrc** [numpy/numpy#17016]
I'm trying to build NumPy and its documentation in a conda environment. So far I have created a fresh 3.8.0 Python environment and installed Cython with conda. When I try to run  `runtests.py` or 

do a `pip install .`, I receive the following error:

### Reproducing code example:

```bash
python runtests.py -v
```

### Error message:
```
Building, see build.log...
numpy/random/_bounded_integers.pxd.in has not changed
numpy/random/_mt19937.pyx has not changed
numpy/random/_philox.pyx has not changed
numpy/random/_common.pyx has not changed
numpy/random/mtrand.pyx has not changed
numpy/random/bit_generator.pyx has not changed
numpy/random/_bounded_integers.pyx.in has not changed
numpy/random/_bounded_integers.pyx has not changed
numpy/random/_sfc64.pyx has not changed
numpy/random/_pcg64.pyx has not changed
numpy/random/_generator.pyx has not changed
Cythonizing sources
blas_opt_info:
blas_mkl_info:
customize UnixCCompiler
  libraries mkl_rt not found in ['/home/ryan/.conda/envs/doc-build-38/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']
  NOT AVAILABLE

blis_info:
  libraries blis not found in ['/home/ryan/.conda/envs/doc-build-38/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']
  NOT AVAILABLE

openblas_info:
  libraries openblas not found in ['/home/ryan/.conda/envs/doc-build-38/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']
  NOT AVAILABLE

atlas_3_10_blas_threads_info:
Setting PTATLAS=ATLAS
  libraries tatlas not found in ['/home/ryan/.conda/envs/doc-build-38/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']
  NOT AVAILABLE

atlas_3_10_blas_info:
  libraries satlas not found in ['/home/ryan/.conda/envs/doc-build-38/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']
  NOT AVAILABLE

atlas_blas_threads_info:
Setting PTATLAS=ATLAS
  libraries ptf77blas,ptcblas,atlas not found in ['/home/ryan/.conda/envs/doc-build-38/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']
  NOT AVAILABLE

atlas_blas_info:
  libraries f77blas,cblas,atlas not found in ['/home/ryan/.conda/envs/doc-build-38/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']
  NOT AVAILABLE

blas_info:
C compiler: gcc -pthread -B /home/ryan/.conda/envs/doc-build-38/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Werror=vla -Werror=nonnull -Werror=pointer-arith -Wlogical-op -Werror=unused-function -fPIC

creating /tmp/tmpkzbmwzne/tmp
creating /tmp/tmpkzbmwzne/tmp/tmpkzbmwzne
compile options: '-I/usr/local/include -I/usr/include -I/home/ryan/.conda/envs/doc-build-38/include -c'
gcc: /tmp/tmpkzbmwzne/source.c
gcc -pthread -B /home/ryan/.conda/envs/doc-build-38/compiler_compat -Wl,--sysroot=/ /tmp/tmpkzbmwzne/tmp/tmpkzbmwzne/source.o -L/usr/lib64 -lblas -o /tmp/tmpkzbmwzne/a.out
/home/ryan/.conda/envs/doc-build-38/compiler_compat/ld: /tmp/tmpkzbmwzne/tmp/tmpkzbmwzne/source.o: unable to initialize decompress status for section .debug_info
/home/ryan/.conda/envs/doc-build-38/compiler_compat/ld: /tmp/tmpkzbmwzne/tmp/tmpkzbmwzne/source.o: unable to initialize decompress status for section .debug_info
/home/ryan/.conda/envs/doc-build-38/compiler_compat/ld: /tmp/tmpkzbmwzne/tmp/tmpkzbmwzne/source.o: unable to initialize decompress status for section .debug_info
/home/ryan/.conda/envs/doc-build-38/compiler_compat/ld: /tmp/tmpkzbmwzne/tmp/tmpkzbmwzne/source.o: unable to initialize decompress status for section .debug_info
/tmp/tmpkzbmwzne/tmp/tmpkzbmwzne/source.o: file not recognized: file format not recognized
collect2: error: ld returned 1 exit status
gcc -pthread -B /home/ryan/.conda/envs/doc-build-38/compiler_compat -Wl,--sysroot=/ /tmp/tmpkzbmwzne/tmp/tmpkzbmwzne/source.o -L/usr/lib64 -lcblas -lblas -o /tmp/tmpkzbmwzne/a.out
/home/ryan/.conda/envs/doc-build-38/compiler_compat/ld: /tmp/tmpkzbmwzne/tmp/tmpkzbmwzne/source.o: unable to initialize decompress status for section .debug_info
/home/ryan/.conda/envs/doc-build-38/compiler_compat/ld: /tmp/tmpkzbmwzne/tmp/tmpkzbmwzne/source.o: unable to initialize decompress status for section .debug_info
/home/ryan/.conda/envs/doc-build-38/compiler_compat/ld: /tmp/tmpkzbmwzne/tmp/tmpkzbmwzne/source.o: unable to initialize decompress status for section .debug_info
/home/ryan/.conda/envs/doc-build-38/compiler_compat/ld: /tmp/tmpkzbmwzne/tmp/tmpkzbmwzne/source.o: unable to initialize decompress status for section .debug_info
/tmp/tmpkzbmwzne/tmp/tmpkzbmwzne/source.o: file not recognized: file format not recognized
collect2: error: ld returned 1 exit status
gcc -pthread -B /home/ryan/.conda/envs/doc-build-38/compiler_compat -Wl,--sysroot=/ /tmp/tmpkzbmwzne/tmp/tmpkzbmwzne/source.o -L/usr/lib64 -lblas -lblas -o /tmp/tmpkzbmwzne/a.out
/home/ryan/.conda/envs/doc-build-38/compiler_compat/ld: /tmp/tmpkzbmwzne/tmp/tmpkzbmwzne/source.o: unable to initialize decompress status for section .debug_info
/home/ryan/.conda/envs/doc-build-38/compiler_compat/ld: /tmp/tmpkzbmwzne/tmp/tmpkzbmwzne/source.o: unable to initialize decompress status for section .debug_info
/home/ryan/.conda/envs/doc-build-38/compiler_compat/ld: /tmp/tmpkzbmwzne/tmp/tmpkzbmwzne/source.o: unable to initialize decompress status for section .debug_info
/home/ryan/.conda/envs/doc-build-38/compiler_compat/ld: /tmp/tmpkzbmwzne/tmp/tmpkzbmwzne/source.o: unable to initialize decompress status for section .debug_info
/tmp/tmpkzbmwzne/tmp/tmpkzbmwzne/source.o: file not recognized: file format not recognized
collect2: error: ld returned 1 exit status
gcc -pthread -B /home/ryan/.conda/envs/doc-build-38/compiler_compat -Wl,--sysroot=/ /tmp/tmpkzbmwzne/tmp/tmpkzbmwzne/source.o -L/usr/lib64 -lcblas -o /tmp/tmpkzbmwzne/a.out
/home/ryan/.conda/envs/doc-build-38/compiler_compat/ld: /tmp/tmpkzbmwzne/tmp/tmpkzbmwzne/source.o: unable to initialize decompress status for section .debug_info
/home/ryan/.conda/envs/doc-build-38/compiler_compat/ld: /tmp/tmpkzbmwzne/tmp/tmpkzbmwzne/source.o: unable to initialize decompress status for section .debug_info
/home/ryan/.conda/envs/doc-build-38/compiler_compat/ld: /tmp/tmpkzbmwzne/tmp/tmpkzbmwzne/source.o: unable to initialize decompress status for section .debug_info
/home/ryan/.conda/envs/doc-build-38/compiler_compat/ld: /tmp/tmpkzbmwzne/tmp/tmpkzbmwzne/source.o: unable to initialize decompress status for section .debug_info
/tmp/tmpkzbmwzne/tmp/tmpkzbmwzne/source.o: file not recognized: file format not recognized
collect2: error: ld returned 1 exit status
gcc -pthread -B /home/ryan/.conda/envs/doc-build-38/compiler_compat -Wl,--sysroot=/ /tmp/tmpkzbmwzne/tmp/tmpkzbmwzne/source.o -L/usr/lib64 -lblas -o /tmp/tmpkzbmwzne/a.out
/home/ryan/.conda/envs/doc-build-38/compiler_compat/ld: /tmp/tmpkzbmwzne/tmp/tmpkzbmwzne/source.o: unable to initialize decompress status for section .debug_info
/home/ryan/.conda/envs/doc-build-38/compiler_compat/ld: /tmp/tmpkzbmwzne/tmp/tmpkzbmwzne/source.o: unable to initialize decompress status for section .debug_info
/home/ryan/.conda/envs/doc-build-38/compiler_compat/ld: /tmp/tmpkzbmwzne/tmp/tmpkzbmwzne/source.o: unable to initialize decompress status for section .debug_info
/home/ryan/.conda/envs/doc-build-38/compiler_compat/ld: /tmp/tmpkzbmwzne/tmp/tmpkzbmwzne/source.o: unable to initialize decompress status for section .debug_info
/tmp/tmpkzbmwzne/tmp/tmpkzbmwzne/source.o: file not recognized: file format not recognized
collect2: error: ld returned 1 exit status
  FOUND:
    libraries = ['blas', 'blas']
    library_dirs = ['/usr/lib64']
    include_dirs = ['/usr/local/include', '/usr/include', '/home/ryan/.conda/envs/doc-build-38/include']

  FOUND:
    define_macros = [('NO_ATLAS_INFO', 1)]
    libraries = ['blas', 'blas']
    library_dirs = ['/usr/lib64']
    include_dirs = ['/usr/local/include', '/usr/include', '/home/ryan/.conda/envs/doc-build-38/include']

non-existing path in 'numpy/distutils': 'site.cfg'
lapack_opt_info:
lapack_mkl_info:
  libraries mkl_rt not found in ['/home/ryan/.conda/envs/doc-build-38/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']
  NOT AVAILABLE

openblas_lapack_info:
  libraries openblas not found in ['/home/ryan/.conda/envs/doc-build-38/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']
  NOT AVAILABLE

openblas_clapack_info:
  libraries openblas,lapack not found in ['/home/ryan/.conda/envs/doc-build-38/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']
  NOT AVAILABLE

flame_info:
  libraries flame not found in ['/home/ryan/.conda/envs/doc-build-38/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']
  NOT AVAILABLE

atlas_3_10_threads_info:
Setting PTATLAS=ATLAS
  libraries lapack_atlas not found in /home/ryan/.conda/envs/doc-build-38/lib
  libraries tatlas,tatlas not found in /home/ryan/.conda/envs/doc-build-38/lib
  libraries lapack_atlas not found in /usr/local/lib
  libraries tatlas,tatlas not found in /usr/local/lib
  libraries lapack_atlas not found in /usr/lib64
  libraries tatlas,tatlas not found in /usr/lib64
  libraries lapack_atlas not found in /usr/lib
  libraries tatlas,tatlas not found in /usr/lib
  libraries lapack_atlas not found in /usr/lib/
  libraries tatlas,tatlas not found in /usr/lib/
<class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
  NOT AVAILABLE

atlas_3_10_info:
  libraries lapack_atlas not found in /home/ryan/.conda/envs/doc-build-38/lib
  libraries satlas,satlas not found in /home/ryan/.conda/envs/doc-build-38/lib
  libraries lapack_atlas not found in /usr/local/lib
  libraries satlas,satlas not found in /usr/local/lib
  libraries lapack_atlas not found in /usr/lib64
  libraries satlas,satlas not found in /usr/lib64
  libraries lapack_atlas not found in /usr/lib
  libraries satlas,satlas not found in /usr/lib
  libraries lapack_atlas not found in /usr/lib/
  libraries satlas,satlas not found in /usr/lib/
<class 'numpy.distutils.system_info.atlas_3_10_info'>
  NOT AVAILABLE

atlas_threads_info:
Setting PTATLAS=ATLAS
  libraries lapack_atlas not found in /home/ryan/.conda/envs/doc-build-38/lib
  libraries ptf77blas,ptcblas,atlas not found in /home/ryan/.conda/envs/doc-build-38/lib
  libraries lapack_atlas not found in /usr/local/lib
  libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib
  libraries lapack_atlas not found in /usr/lib64
  libraries ptf77blas,ptcblas,atlas not found in /usr/lib64
  libraries lapack_atlas not found in /usr/lib
  libraries ptf77blas,ptcblas,atlas not found in /usr/lib
  libraries lapack_atlas not found in /usr/lib/
  libraries ptf77blas,ptcblas,atlas not found in /usr/lib/
<class 'numpy.distutils.system_info.atlas_threads_info'>
  NOT AVAILABLE

atlas_info:
  libraries lapack_atlas not found in /home/ryan/.conda/envs/doc-build-38/lib
  libraries f77blas,cblas,atlas not found in /home/ryan/.conda/envs/doc-build-38/lib
  libraries lapack_atlas not found in /usr/local/lib
  libraries f77blas,cblas,atlas not found in /usr/local/lib
  libraries lapack_atlas not found in /usr/lib64
  libraries f77blas,cblas,atlas not found in /usr/lib64
  libraries lapack_atlas not found in /usr/lib
  libraries f77blas,cblas,atlas not found in /usr/lib
  libraries lapack_atlas not found in /usr/lib/
  libraries f77blas,cblas,atlas not found in /usr/lib/
<class 'numpy.distutils.system_info.atlas_info'>
  NOT AVAILABLE

lapack_info:
  FOUND:
    libraries = ['lapack', 'lapack']
    library_dirs = ['/usr/lib64']
    language = f77

  FOUND:
    libraries = ['lapack', 'lapack', 'blas', 'blas']
    library_dirs = ['/usr/lib64']
    language = f77
    define_macros = [('NO_ATLAS_INFO', 1)]
    include_dirs = ['/usr/local/include', '/usr/include', '/home/ryan/.conda/envs/doc-build-38/include']

running build
running config_cc
unifing config_cc, config, build_clib, build_ext, build commands --compiler options
running config_fc
unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
running build_src
build_src
building py_modules sources
building library "npymath" sources
/home/ryan/.conda/envs/doc-build-38/compiler_compat/ld: _configtest.o: unable to initialize decompress status for section .debug_info
/home/ryan/.conda/envs/doc-build-38/compiler_compat/ld: _configtest.o: unable to initialize decompress status for section .debug_info
/home/ryan/.conda/envs/doc-build-38/compiler_compat/ld: _configtest.o: unable to initialize decompress status for section .debug_info
/home/ryan/.conda/envs/doc-build-38/compiler_compat/ld: _configtest.o: unable to initialize decompress status for section .debug_info
_configtest.o: file not recognized: file format not recognized
collect2: error: ld returned 1 exit status
/home/ryan/.conda/envs/doc-build-38/lib/python3.8/site-packages/setuptools/distutils_patch.py:25: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
  warnings.warn(
Running from numpy source directory.
/home/ryan/projects/numpy/numpy/numpy/distutils/system_info.py:1932: UserWarning: 
    Optimized (vendor) Blas libraries are not found.
    Falls back to netlib Blas library which has worse performance.
    A better performance should be easily gained by switching
    Blas library.
  if self._calc_info(blas):
/home/ryan/.conda/envs/doc-build-38/lib/python3.8/distutils/dist.py:274: UserWarning: Unknown distribution option: 'define_macros'
  warnings.warn(msg)
Traceback (most recent call last):
  File "setup.py", line 499, in <module>
    setup_package()
  File "setup.py", line 491, in setup_package
    setup(**metadata)
  File "/home/ryan/projects/numpy/numpy/numpy/distutils/core.py", line 169, in setup
    return old_setup(**new_attr)
  File "/home/ryan/.conda/envs/doc-build-38/lib/python3.8/site-packages/setuptools/__init__.py", line 165, in setup
    return distutils.core.setup(**attrs)
  File "/home/ryan/.conda/envs/doc-build-38/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/ryan/.conda/envs/doc-build-38/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/ryan/.conda/envs/doc-build-38/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/ryan/projects/numpy/numpy/numpy/distutils/command/build.py", line 49, in run
    old_build.run(self)
  File "/home/ryan/.conda/envs/doc-build-38/lib/python3.8/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/ryan/.conda/envs/doc-build-38/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/ryan/.conda/envs/doc-build-38/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/ryan/projects/numpy/numpy/numpy/distutils/command/build_src.py", line 144, in run
    self.build_sources()
  File "/home/ryan/projects/numpy/numpy/numpy/distutils/command/build_src.py", line 155, in build_sources
    self.build_library_sources(*libname_info)
  File "/home/ryan/projects/numpy/numpy/numpy/distutils/command/build_src.py", line 288, in build_library_sources
    sources = self.generate_sources(sources, (lib_name, build_info))
  File "/home/ryan/projects/numpy/numpy/numpy/distutils/command/build_src.py", line 378, in generate_sources
    source = func(extension, build_dir)
  File "numpy/core/setup.py", line 658, in get_mathlib_info
    raise RuntimeError("Broken toolchain: cannot link a simple C program")

RuntimeError: Broken toolchain: cannot link a simple C program

Build failed!
```
</details>

### Numpy/Python version information:

Python 3.8.0 installed from conda only install in the environment so far is Cython v0.29.21

**Comment by rgommers** [comment]
`Broken toolchain`, always fun. Here is my guess: you're on Arch Linux or a similar distro with the latest and greatest GCC (9.x or 10.x), and this is incompatible with the `ld` that conda installs (which is quite old). 

Try moving `ld` in `/home/ryan/.conda/envs/doc-build-38/compiler_compat/` to `_ld` and rebuild. It should now use your system `ld` instead, and the error should disappear.

**Comment by cooperrc** [comment]
Thanks @rgommers! 
I moved the default `~/conda/envs/doc-build-38/compiler_compat/ld` 
to `~/conda/envs/doc-build-38/compiler_compat/bak_ld`

Then, the build went smoothly.

**Comment by rgommers** [comment]
Great. Let's close this then.
