### ISSUE TITLE
numpy installation fails after reaching setup.py (--no-use-pep517 flag set)

### ISSUE THREAD

**Issue by madprogramer** [numpy/numpy#17099]
While trying to directly install numpy onto an Arduino board, I seem to encounter an error whenever I reach the `setup.py` execution

### Reproducing code example:

```bash
python3.6/bin/pip3 install -v numpy --no-use-pep517
```

### Error message:
```bash
Running setup.py install for numpy ... error
ERROR: Command errored out with exit status 1: /home/root/python3.6/bin/python3.6 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ke7s76si/numpy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ke7s76si/numpy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-qsai7z5o/install-record.txt --single-version-externally-managed --compile --install-headers /home/root/python3.6/include/python3.6m/numpy Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/home/root/python3.6/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 851, in install
    req_description=str(self.req),
  File "/home/root/python3.6/lib/python3.6/site-packages/pip/_internal/operations/install/legacy.py", line 86, in install
    raise LegacyInstallFailure
pip._internal.operations.install.legacy.LegacyInstallFailure

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/root/python3.6/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 216, in _main
    status = self.run(options, args)
  File "/home/root/python3.6/lib/python3.6/site-packages/pip/_internal/cli/req_command.py", line 182, in wrapper
    return func(self, options, args)
  File "/home/root/python3.6/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 421, in run
    pycompile=options.compile,
  File "/home/root/python3.6/lib/python3.6/site-packages/pip/_internal/req/__init__.py", line 90, in install_given_reqs
    pycompile=pycompile,
  File "/home/root/python3.6/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 855, in install
    six.reraise(*exc.parent)
  File "/home/root/python3.6/lib/python3.6/site-packages/pip/_vendor/six.py", line 703, in reraise
    raise value
  File "/home/root/python3.6/lib/python3.6/site-packages/pip/_internal/operations/install/legacy.py", line 76, in install
    cwd=unpacked_source_directory,
  File "/home/root/python3.6/lib/python3.6/site-packages/pip/_internal/utils/subprocess.py", line 277, in runner
    spinner=spinner,
  File "/home/root/python3.6/lib/python3.6/site-packages/pip/_internal/utils/subprocess.py", line 242, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status 1: /home/root/python3.6/bin/python3.6 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ke7s76si/numpy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ke7s76si/numpy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-qsai7z5o/install-record.txt --single-version-externally-managed --compile --install-headers /home/root/python3.6/include/python3.6m/numpy Check the logs for full command output.
Removed build tracker: '/tmp/pip-req-tracker-315j_hbs'
```
### Numpy/Python version information:
python version: 3.6
pip: 20.2.2
wheel: 0.35.1

hardware: Intel Galileo
os: _yotta distribution?_

**Comment by madprogramer** [comment]
Ok, so apparently pip seems to have depreciated a thing or two which break --no-use-pep517, I've tried installing pep517 using `pip install pep517` let's see how that goes...

**Comment by rgommers** [comment]
It's possible you have a too recent `setuptools` and that's the problem here (see the version constraint in our `pyproject.toml`).

Please let us know what you find - a lot of people are going to run into this probably.

**Comment by madprogramer** [comment]
Well, the .toml checks for `setuptools<49.2.0`, which was previously satisfied.

To fix another problem I tried upgrading to 49.6.0 and I over-shot it in the process, let's see if downgrading to 49.1 will do any good

**Comment by madprogramer** [comment]
No good, seems I'm still missing BLAS and LAPack. I might as well install without --no-use-pep517 at this point, because PEP517 seems to have installed fine

**Comment by mattip** [comment]
> install numpy onto an Arduino board

Did you really mean an Arduino board? Does that even have an OS and a file system?

**Comment by madprogramer** [comment]
@mattip via SD card actually. Just flash the OS and everything on that

**Comment by charris** [comment]
@madprogramer Did you find a solution for this?

**Comment by charris** [comment]
Closing. @madprogramer Please open a new issue if you still have problems.
