### ISSUE TITLE
Error: No module named 'numpy.core._multiarray_umath'

### ISSUE THREAD

**Issue by sourabhgupta811** [numpy/numpy#17232]
Hi, I am trying to embed python interpreter in a cpp application in Visual Studio 2019. When i try to import numpy in my python file, then it throw the below stated error. It works fine when executing the file with py in command prompt.
I have tried answer from #13556 but that doesn't work. 

### Reproducing code example:
```
python
from numpy import genfromtxt
def plotData(csvFileName):
    data = genfromtxt(csvFileName,delimiter=',')
    print(data)
```
```
cpp
int py::plotData(char csvFileName[])
{
	CPyInstance hInstance;

	PyObject* sys_path = PySys_GetObject("path");
	CPyObject localPath = PyUnicode_FromString("vs_projects\\PythonApplication1\\PythonApplication1\\");
	PyList_Append(sys_path, localPath);
	CPyObject pName = PyUnicode_FromString("python_module");
	CPyObject pModule = PyImport_Import(pName);

	if (pModule)
	{
		CPyObject pFunc = PyObject_GetAttrString(pModule, "plotData");
		if (pFunc && PyCallable_Check(pFunc))
		{
			CPyObject args = Py_BuildValue("(s)", csvFileName);
			CPyObject pValue = PyObject_CallObject(pFunc, args);
		}
		else
		{
			printf("ERROR: function plotData()\n");
		}

	}
	else
	{
		printf_s("ERROR: Module not imported\n");
	}
	return 1;
}
```

### Error message:
```
 Traceback (most recent call last):
  File "D:\sourabh_data\vs_projects\PythonApplication1\PythonApplication1\python_module.py", line 3, in <module>
    from numpy import genfromtxt
  File "C:\Users\soura\AppData\Roaming\Python\Python37\site-packages\numpy\__init__.py", line 140, in <module>
    from . import core
  File "C:\Users\soura\AppData\Roaming\Python\Python37\site-packages\numpy\core\__init__.py", line 48, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.7 from "vs_projects\OpenCVProject\x64\Debug\OpenCVProject.exe"
  * The NumPy version is: "1.19.1"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'
```

### Numpy/Python version information:
  * The Python version is: Python3.7 from "vs_projects\OpenCVProject\x64\Debug\OpenCVProject.exe"
  * The NumPy version is: "1.19.1"

**Comment by seberg** [comment]
As a two year old installation or probably environment issue with VSCode, I will just close this (I hope you managed to fix it!).  As the error says, this has some pointers about how to set things up correctly: https://numpy.org/devdocs/user/troubleshooting-importerror.html (also linking to VSCode docs).
