### ISSUE TITLE
`concatenate` doesn't understand `dict_values`

### ISSUE THREAD

**Issue by brunobeltran** [numpy/numpy#17305]
Probably not related, but this was previously #2612. As in the title, trying to concatenate the output of `dict.values` fails, not recognizing that it is a `Sequence`.

### Reproducing code example:

```python
import numpy as np
test = {i: np.zeros((3,2 )) for i in range(5)}
np.concatenate(test.values())
```

### Error message:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<__array_function__ internals>", line 5, in concatenate
TypeError: The first input argument needs to be a sequence
```

### Numpy/Python version information:

1.18.4 3.8.2 | packaged by conda-forge | (default, Mar  5 2020, 17:11:00)
[GCC 7.3.0]

This failure occurs on latest 64-bit Arch running latest numpy (1.18.4) from PIP on Python 3.8.2.

The code also fails on `master` (`numpy-1.20.0.dev0+3ad444b`).

**Comment by eric-wieser** [comment]
As far as I remember, `dict_values` is not considered a sequence by python because it does not implement `__getitem__` - so the error message is correct.

**Comment by seberg** [comment]
This is a duplicate of gh-573 and gh-14539 (and possible something else).

The error is correct, `dict.values` is *not* a sequence. Right now, I doubt that python will make it a sequence (IIRC `__getitem__` is a slow operation, so the argument is that a sequence gives the wrong idea).  So basically, we got something that is not a sequence (which we could handle), but more sensible than an iterator (which we cannot handle).  But, we have to figure out how to declare that it fits a certain box.
I don't remember all of the discussion now, but we probably also want to reject dictionaries themselves, which are iterable, but do have a length.

**Comment by brunobeltran** [comment]
Sorry for the dup, I see from the discussion in #14539 that it's wontfix for now.

**Comment by seberg** [comment]
Yeah, for the moment its wontfix... You are right to ask though, it is an annoying issue (also inconvenient e.g. for matplotlib). It would be great if we just had an idea for allowing this, that is a bit cleaner than special casing `dict_values`, etc. But I guess, right now we don't.

**Comment by eric-wieser** [comment]
This is different to #14539 - that issue is about what is allowed for array coercions, but this one is specific to a regular sequence argument. I don't think we necessarily need to make the same call on this issue as we did there.

**Comment by seberg** [comment]
Oops, you are right, we could allow iterators. Although I am tempted to not do that.

**Comment by eric-wieser** [comment]
I think the crux is that the the argument to concatenate must be an ordered sequence, not just not an unordered container.

We certainly don't want to allow `concatenate(set)`. As with the other issue, perhaps the resolution is to ask python to implement `dict_values.__getitem__` since recently dictionary order became guaranteed.
