### ISSUE TITLE
`numpy.float64` ignores unknown keyword arguments.

### ISSUE THREAD

**Issue by WarrenWeckesser** [numpy/numpy#17532]
Unlike the other scalar types, `numpy.float64` silently ignores unknown keyword arguments:

```
In [17]: np.__version__
Out[17]: '1.20.0.dev0+f0171ba'

In [18]: np.float64(123, foobar="plate of shrimp")
Out[18]: 123.0
```
The other types raise the exception `TypeError: function takes at most 1 argument (2 given)`:

```
In [19]: np.float32(123, foobar="plate of shrimp")
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-19-2f7cf4afa2cb> in <module>
----> 1 np.float32(123, foobar="plate of shrimp")

TypeError: function takes at most 1 argument (2 given)

In [20]: np.uint32(123, foobar="plate of shrimp")
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-20-8b32fef69395> in <module>
----> 1 np.uint32(123, foobar="plate of shrimp")

TypeError: function takes at most 1 argument (2 given)
```

**Comment by BvB93** [comment]
Apparently this is a bug with `builtins.float`; see https://github.com/numpy/numpy/issues/16577#issuecomment-643270992 for more details.

**Comment by bashtage** [comment]
Also has a default positional value of 0.0 it seems.

**Comment by BvB93** [comment]
> Also has a default positional value of 0.0 it seems.

The same holds true for all builtin scalar types as well as `generic` subclasses though, 
so this seems more like a feature rather than a bug.

**Comment by WarrenWeckesser** [comment]
The [docs for `np.double`](https://numpy.org/doc/stable/reference/arrays.scalars.html?highlight=float64#numpy.double) show the signature to be `numpy.double(x=0, /)`.  But the keyword `x` is ignored.  Combine that with the default value of 0, and we have the following unfortunate behavior:
```
In [157]: np.double(x=-999)
Out[157]: 0.0
```

**Comment by mattip** [comment]
Both the kwarg uses now raise. Closing.
```
>>> np.__version__
'2.6.0.dev0+git20260816.c452636'
>>> np.float64(123, foobar="plate of shrimp")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: float() takes no keyword arguments
>>> np.double(x=-999)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: float() takes no keyword arguments
```
