### ISSUE TITLE
Python(41337,0x1081e05c0) malloc: can't allocate region upon import

### ISSUE THREAD

**Issue by gvalchca** [numpy/numpy#17550]
Hi,
I have just installed the Python3.9, and with it reinstalled all of the packages. Pip3 installs NumPy without an error but upon import, the following occurrs:

```
Successfully installed numpy-1.19.2
 >>> import numpy
Python(41337,0x1081e05c0) malloc: can't allocate region
*** mach_vm_map(size=18446744072492036096) failed (error code=3)
Python(41337,0x1081e05c0) malloc: *** set a breakpoint in malloc_error_break to debug
init_dgelsd failed init
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/numpy/__init__.py", line 286, in <module>
    raise RuntimeError(msg)
RuntimeError: Polyfit sanity test emitted a warning, most likely due to using a buggy Accelerate backend. If you compiled yourself, see site.cfg.example for information. Otherwise report this to the vendor that provided NumPy.
RankWarning: Polyfit may be poorly conditioned

```

What could be happening?

**Comment by gvalchca** [comment]
aaa ok, fantastic, thanks a lot for your prompt reply!
