### ISSUE TITLE
Data type not understood error on Google Colab

### ISSUE THREAD

**Issue by Kocaak** [numpy/numpy#17661]
### **Code:**
```
def diffMask(img1=None, img2=None, opt=None, dataset=None, args=None):
    netG = args[0]
    netB = args[1]
    netD = args[2]
    f = args[3]
    res_path = opt.results_Stage3
    res_folders = ['temp_masks',
                   'temp_Stage2',
                   'temp_ref',
                   'temp_diff',
                   'temp_Stage3',
                   'temp_skel',
                   'temp_res',
                   'temp_Stage1',
                   'temp_src']
    for x in res_folders:
        if os.path.isdir("{}{}".format(res_path, x)) == False:
            os.mkdir("{}{}".format(res_path, x))
    save_masks = "{}{}".format(res_path, "temp_masks")
    save_Stage2 = "{}{}".format(res_path, "temp_Stage2")
    save_ref = "{}{}".format(res_path, "temp_ref")
    save_diff = "{}{}".format(res_path, "temp_diff")
    save_Stage3 = "{}{}".format(res_path, "temp_Stage3")
    save_skel = "{}{}".format(res_path, "temp_skel")
    save_res = "{}{}".format(res_path, "temp_res")
    save_Stage1 = "{}{}".format(res_path, "temp_Stage1")
    save_src = "{}{}".format(res_path, "temp_src")

    resize2 = transforms.Resize(size=(128, 128))
    src, mask, style_img, target, gt_cloth, skel, cloth = dataset.get_img("{}_0.jpg".format(img1[:-6]),
                                                                          "{}_1.jpg".format(img1[:-6]))
    src, mask, style_img, target, gt_cloth, skel, cloth = src.unsqueeze(0), mask.unsqueeze(0), style_img.unsqueeze(
        0), target.unsqueeze(0), gt_cloth.unsqueeze(0), skel.unsqueeze(0), cloth.unsqueeze(0)  # , face.unsqueeze(0)
    src1, mask1, style_img1, target1, gt_cloth1, skel1, cloth1 = Variable(src.cuda()), Variable(mask.cuda()), Variable(
        style_img.cuda()), Variable(target.cuda()), Variable(gt_cloth.cuda()), Variable(skel.cuda()), Variable(
        cloth.cuda())  # , Variable(face.cuda())
    src, mask, style_img, target, gt_cloth, skel, cloth = dataset.get_img("{}_0.jpg".format(img2[:-6]),
                                                                          "{}_1.jpg".format(img2[:-6]))
    src, mask, style_img, target, gt_cloth, skel, cloth = src.unsqueeze(0), mask.unsqueeze(0), style_img.unsqueeze(
        0), target.unsqueeze(0), gt_cloth.unsqueeze(0), skel.unsqueeze(0), cloth.unsqueeze(0)  # , face.unsqueeze(0)
    src2, mask2, style_img2, target2, gt_cloth2, skel2, cloth2 = Variable(src.cuda()), Variable(mask.cuda()), Variable(
        style_img.cuda()), Variable(target.cuda()), Variable(gt_cloth.cuda()), Variable(skel.cuda()), Variable(
        cloth.cuda())

    gen_targ_Stage1, s_128, s_64, s_32, s_16, s_8, s_4 = netG(skel1, cloth2)  # gen_targ11 is structural change cloth
    gen_targ_Stage2, s_128, s_64, s_32, s_16, s_8, s_4 = netB(src1, gen_targ_Stage1,
                                                              skel1)  # gen_targ12 is Stage2 image

    # saving structural 
    pic_Stage2 = (torch.cat([gen_targ_Stage2], dim=0).data + 1) / 2.0
    #     save_dir = "/home/np9207/PolyGan_res/temp_Stage2/"
    save_image(pic_Stage2, '%s/%d_%s_%d.jpg' % (save_Stage2, f, img1[:-6], 0), nrow=1)

    msk1 = mask1[0, :, :, :].detach().cpu().permute(1, 2, 0)
    plt.imsave("{}/{}_{}_mask.jpg".format(save_masks, f, img1[:-6]), msk1, cmap="gray")
```

### **I am getting error on this line:**
`plt.imsave("{}/{}_{}_mask.jpg".format(save_masks, f, img1[:-6]), msk1, cmap="gray")`

### **Error Output:**
```
Traceback (most recent call last):
  File "test.py", line 208, in test
    diffMask(image1, image2, opt, test_loader, args)
  File "test.py", line 96, in diffMask
    plt.imsave("{}/{}_{}_mask.jpg".format(save_masks, f, img1[:-6]), msk1, cmap="gray")
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/pyplot.py", line 2066, in imsave
    return matplotlib.image.imsave(fname, arr, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/image.py", line 1550, in imsave
    rgba = sm.to_rgba(arr, bytes=True)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/cm.py", line 217, in to_rgba
    xx = np.empty(shape=(m, n, 4), dtype=x.dtype)
TypeError: data type not understood
```

### **Numpy Version:**
`1.18.5`

I couldnt find any solution of this error. Thanks in advance for any helps!

**Comment by AaryamanCodes** [comment]
@Kocaak Hi,
I also faced the same issue. I think it is an issue with the interpreter itself and it will need to be solved by Google team itself. Though it is working fine on Atom Script, Python Interpreter and Jupyter Notebooks, so you can try using it on them I guess.

**Comment by Kocaak** [comment]
> @Kocaak Hi,
> I also faced the same issue. I think it is an issue with the interpreter itself and it will need to be solved by Google team itself. Though it is working fine on Atom Script, Python Interpreter and Jupyter Notebooks, so you can try using it on them I guess.

Thank you for answer. The main reason that i am using colab is my GPU's memory is not enough for this type of works since they exactly "eat" memory and i need some kind of cloud computing. Can you recommend me alternative of colab?

**Comment by rossbar** [comment]
I'm going to close this as it doesn't seem like the problem stems from numpy looking at the traceback. The issue also seems pretty application-specific: you might have better luck chasing down the problem by trying to come up with a more minimal reproducing example.
