### ISSUE TITLE
BUG of 1.19.2, numpy.ma.MaskedArray: unexpected overflow of fill_value

### ISSUE THREAD

**Issue by CastleStar14654** [numpy/numpy#17697]
If User accessed `MaskedArray`'s default `fill_value` before assignment of it, an overflow might occur.

### Reproducing code example:

```python
import numpy as np
a = np.ma.MaskedArray([], dtype='i8') # int64
print(a.fill_value)
a.set_fill_value(2**40) # 2**40 is of course not overflow for 'i8'
```

### Error message:

```
Traceback (most recent call last):
  File "tmp.py", line 4, in <module>
    a.set_fill_value(2**40) # 2**40 is of course not overflow for 'i8'
  File "C:\Program Files\Python38\lib\site-packages\numpy\ma\core.py", line 3724, in fill_value
    _fill_value[()] = target
OverflowError: Python int too large to convert to C long
```

### NumPy/Python version information:

`1.19.2 3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)]`

### Probable Cause of this bug

Default `fill_value`s for **all integer dtype** are `999999`, which is defined by
https://github.com/numpy/numpy/blob/2a267e6a49ed68da01761c92deb7c90be207660d/numpy/ma/core.py#L428-L438
and when it is returned, no `dtype` is assigned,
https://github.com/numpy/numpy/blob/2a267e6a49ed68da01761c92deb7c90be207660d/numpy/ma/core.py#L469
and **default `fill_value` for `int64` array would be `int32`**.

Replace `return np.array(fill_value)` as `return np.array(fill_value, dtype=ndtype)` could possibly fix it.

**Comment by eric-wieser** [comment]
I think the only fix available to us is to always use `np.longlong` for default integer values, rather than `np.int_` which is sometimes 64-bit and sometimes 32-bit.

We can't make the fix you suggest, because it would change the value of `np.ma.MaskedArray([], dtype='i1').astype(np.int64).fill_value` to not be `999999`.

**Comment by CastleStar14654** [comment]
@eric-wieser The root of the inconsistency you mentioned is that when default `fill_value` is set, it's always `999999` and int32, while when a `astype` cast is made, the data type of `fill_value` is changed.

So, even **WITHOUT** the modification I mentioned, the problem you suggested already exists:
```Python
# right now
a = np.ma.MaskedArray([], dtype=np.int32)
print(a.fill_value, a.fill_value.dtype)
b = a.astype(np.int8) # if you accesed `a`'s `fill_value` first, it would be 999999 and be cast to int8 here
print(b.fill_value, b.fill_value.dtype) # and `b.fill_type` is `63`
c = b.astype(np.int32) # `b.fill_type` is cast back to int32 here
print(c.fill_value, c.fill_value.dtype) # but is still `63`
```
will output
```
999999 int32
63 int8
63 int32
```
which is an awful inconsistency. The default `fill_value` changed after two casting.

**Comment by cmarmo** [comment]
Hello, just cross-linking here #22141, as those two issues could probably be fixed in the same way.

**Comment by mattip** [comment]
Fixed. Closing.
```
>>> a = np.ma.MaskedArray([], dtype='i8') # int64
>>> print(a.fill_value)
999999
>>> a.set_fill_value(2**40) # 2**40 is of course not overflow for 'i8'
>>> np.__version__                                                                                                                                                                 
'2.6.0.dev0+git20260816.c452636'
```
