### ISSUE TITLE
code can not build up. pyinstaller throws an error

### ISSUE THREAD

**Issue by sreevanii** [numpy/numpy#17705]
### Reproducing code example:

```python
import numpy as np
<< from tkinter import *
from tkinter.filedialog import askopenfilename
import numpy as np
from tkinter import messagebox
import pandas as pd
import vaex as vs
import matplotlib.pyplot as plt
import os

class Application(Frame):
    label1: None
    chdesg = None

    def __init__(self, master=None):
        Frame.__init__(self, master)
        self.check = False
        self.chclicked = None
        self.filename = None
        self.xvars = []
        self.y1vars = []
        self.y2vars = []
        self.allchpf = []
        self.allch = []
        self.allchlen = [0]
        self.allfiles = []
        self.allchwo = []
        self.fl = 0  # initialize row with '0' for file path lable on frame1
        self.index = 1
        self.allfilenames = []  # array of all file names

        self.master.title("PLOT")
        self.master.geometry('900x400')

        menubar = Menu(self.master)
        self.master.config(menu=menubar)

        self.fileMenu = Menu(menubar, tearoff=0)
        self.fileMenu.add_command(label="Txt_Open", command=self.fo)
        self.fileMenu.add_command(label="hdf5_Open", command=self.openhdf5)
        self.fileMenu.add_command(label="Close", command=self.close)
        self.fileMenu.add_separator()
        self.fileMenu.add_command(label="EXIT", command=self.master.destroy)
        menubar.add_cascade(label="File", menu=self.fileMenu)

        # convertmenu= Menu(menubar, tearoff=0)
        # convertmenu.add_command(label="To_csv_hdf5", command= self.tocsv)
        # menubar.add_cascade(label="Convert", menu=convertmenu)

        # self.statMenu = Menu(menubar, tearoff=0)
        # self.statMenu.add_command(label="Statistics",command= self.stat, state = 'disable')
        # self.statMenu.add_command(label="Tzero", command=self.tzero, state='disable')
        # self.statMenu.add_command(label="Process", command=self.process, state='disable')
        # menubar.add_cascade(label="Statistics", menu=self.statMenu)

        self.frame1 = Frame(master, width=600, height=400, bg="WHITE")
        self.frame1.pack(fill=BOTH, side=LEFT, expand=True)
        self.frame1.pack_propagate(0)

        self.frame3 = Frame(master, width=300, height=50)
        self.frame3.pack(fill=BOTH, side=TOP, expand=False)
        self.frame3.pack_propagate(0)

        self.frame2 = Frame(master, width=300, height=350)
        self.frame2.pack(fill=BOTH, side=LEFT, expand=False)
        self.frame2.pack_propagate(0)
        # app.pack(side="top", fill="both", expand=True)
        self.display()

    def display(self):
        Label(self.frame3, text="X", width=10).grid(row=0, column=0)
        Label(self.frame3, text="Y1", width=10).grid(row=0, column=1)
        Label(self.frame3, text="Y2", width=10).grid(row=0, column=2)
        self.plotbutton = Button(self.frame3, text='PLOT', command=self.plot, width=6).grid(row=0, column=3)
        channels = Button(self.frame3, text='Update Channels', command=self.populate, width=15).grid(row=1, column=0,
                                                                                                     columnspan=2)

        self.canvas = Canvas(self.frame2, borderwidth=10)
        self.frame = Frame(self.canvas)

        self.vsb = Scrollbar(self, orient="vertical", command=self.canvas.yview)
        self.canvas.configure(yscrollcommand=self.vsb.set)

        self.vsb.pack(side="right", fill="y")
        self.canvas.pack(side="right", fill="both", expand=False)
        self.canvas.create_window((4, 4), window=self.frame, anchor="nw", tags="self.frame")
        self.frame.bind("<Configure>", self.onFrameConfigure)

    def onFrameConfigure(self, event):
        '''Reset the scroll region to encompass the inner frame'''
        self.canvas.configure(scrollregion=self.canvas.bbox("all"))

    def close(self):
        self.xvars.clear()
        self.y1vars.clear()
        self.y2vars.clear()
        self.check = False
        self.allch.clear()
        self.allchlen = [0]
        self.allfiles.clear()
        self.allchwo.clear()
        self.allfilenames.clear()
        self.fl = 0

        for widget in self.frame1.winfo_children():
            widget.destroy()
        self.vsb.pack_forget()

        for widget in self.frame2.winfo_children():
            widget.destroy()

        self.fileMenu.entryconfigure('Txt_Open', state='normal')
        self.fileMenu.entryconfigure('hdf5_Open', state='normal')
        # self.statMenu.entryconfigure('Statistics', state='disable')
        # self.statMenu.entryconfigure('Tzero', state='disable')
        self.display()

    def fo(self):


        self.filename = askopenfilename(filetypes=[("All tab files", "*.tab"), ("All text files", "*.txt")])
        if not self.filename:
            messagebox.askokcancel('warning', 'select file')
        else:
            self.label1 = Label(self.frame1, text=self.filename).grid(row=self.fl, column=0)
            file = open(self.filename, 'r')
            self.fpath, tail = os.path.split(self.filename)
            print("file path", self.fpath)
            print("fname", tail)

            self.fl += 1
            # fname give filename with extension
            # file name with out extension "fnamewoe"
            (self.fnamewoe, ext) = os.path.splitext(tail)
            print(self.fnamewoe)

            self.nofhead = 15
            self.check = True

            self.header = file.readlines()[0:self.nofhead]
            file.close()
            self.getheader()

    def getheader(self):
        global line
        # remove "\n" from each line
        headerwon = [line.rstrip() for line in self.header]

        # reverste headerwoes to get index of the line where strings are present
        headerwon.reverse()
        print(headerwon)

        # to find the no.of columns.
        col = headerwon[0].split()
        self.nofcol = len(col)
        print("no.of coloumns", self.nofcol)

        a = 0
        for line in headerwon:
            str_lst = line.split()
            str_arry = np.array(str_lst)
            for i in str_arry:
                try:
                    float(i)
                except:
                    a = 1
                    break
            if a == 1:
                break
        # print("break",line)
        index_line = headerwon.index(line)
        # print(index_line)

        self.act_headerlines = self.nofhead - index_line
        # print('header lines = ', act_headerlines)
        headerwon.reverse()
        self.new_header = headerwon[0:self.act_headerlines]
        # print(new_header)

        # creating labels for the dropmenus
        chlabel = Label(self.frame1, text='Column_names').grid(row=self.fl, column=0, sticky='w')
        self.popupmenu()

        # creating dropmenu for columns and units for the header lines

    def popupmenu(self):
        self.chclicked = StringVar()
        self.chclicked.set("Select")
        self.chdrop = OptionMenu(self.frame1, self.chclicked, *self.new_header)
        self.chdrop.config(width=40)
        self.chdrop.configure(state=NORMAL)
        self.chdrop.grid(row=self.fl, column=1)
        self.fl += 1
        self.addcolumns = Button(self.frame1, text="Add to Hdf5", width=20, command=self.getvalue)
        self.addcolumns.grid(row=self.fl, column=1)
        self.addcolumns.configure(state=NORMAL)
        self.fl += 1

    def getvalue(self):
        x = self.chclicked.get()
        self.chdesg = x.split()
        self.chlen = len(self.chdesg)
        print(self.chlen)
        print(self.chdesg)

        if self.nofcol != self.chlen:
            messagebox.askokcancel('warning', 'column # mismatching')
        else:
            self.convert = Button(self.frame1, text="Convert", width=15, command=self.tocsv)
            self.convert.grid(row=self.fl, column=1)
            self.convert.configure(state=NORMAL)
            self.addcolumns.configure(state=DISABLED)
            self.chdrop.configure(state=DISABLED)

    def tocsv(self):
        # with open(self.filename, 'r') as csv:
            o=self.fpath+"/"+ self.fnamewoe + ".csv"
            h=self.fpath+"/"+ self.fnamewoe + ".hdf5"
            self.csvfilename = os.path.join(o)
            # self.fpath, self.tail = os.path.split(self.csvfilename)
            # self.allfilenames.insert(self.fl, self.tail)
            csvfile = pd.read_csv(self.filename, sep='\s+', skiprows=self.act_headerlines, names=self.chdesg, dtype=float)
            csvfile.to_csv(self.csvfilename, index=None, )

            df=vs.from_csv(self.csvfilename, convert=True,chunk_size=10_000)
            df.export(h)
            self.close()

    def openhdf5(self):
        self.csvfilename = askopenfilename(filetypes=[("hdf5 files", "*.hdf5"), ("hdf files", "*.hdf")])

        if not self.csvfilename:
            messagebox.askokcancel('warning', 'select file')
        else:

            self.label1 = Label(self.frame1, text=self.csvfilename).grid(row=self.fl, column=0)
            self.fpath, self.tail = os.path.split(self.csvfilename)
            print("file path", self.fpath)
            print("file name", self.tail)
            self.allfilenames.insert(self.fl, self.tail)

            self.fl += 1  # increment row by 1 for next file path on frame1

            self.f = vs.open(self.csvfilename)
            self.allfiles.insert(self.index, self.csvfilename)
            print("all files", self.allfiles)
            self.chdesg = self.f.get_column_names()
            # warnings.filterwarnings("ignore", category=DeprecationWarning)
            # self.f_train, self.f_test = self.f.ml.train_test_split(test_size=0.5)
            # self.chdesg = self.f_train.column_names[:]
            print("channel designation in each file=", self.chdesg)
            self.cur_chlen = len(self.chdesg)  # no.of channels in each file
            self.f.close()  # close the current file

        self.allch = self.allch + self.chdesg  # all channel designations
        self.allchlen.insert(self.index, sum(
            self.allchlen) + self.cur_chlen)  # array of no.of channels for path display on frame2 starting with '0'
        self.allchwo.insert(self.index, len(self.allch))  # channel length separation
        print("array of channel length with out zero=", self.allchwo)
        self.index += 1

        print("all chs present in each file", self.allch)
        print("length of all chs in each file", self.allchlen)
        self.fileMenu.entryconfigure('Txt_Open', state='disable')

    def populate(self):
        ro = 0
        a = 0
        for i, checkboxname in enumerate(self.allch):
            for j in range(len(self.allchlen)):
                if i == self.allchlen[j]:  # display file path before channels in frame2
                    self.label1 = Label(self.frame, text=self.allfilenames[a]).grid(row=ro, column=0)
                    ro += 1
                    a += 1

            self.xvars.append(IntVar())
            self.x = Checkbutton(self.frame, text=checkboxname + "     ", variable=self.xvars[i])
            self.x.grid(row=ro, column=0)
            ro += 1

        ro = 0
        for i, checkboxname in enumerate(self.allch):
            for j in range(len(self.allchlen)):
                if i == self.allchlen[j]:
                    self.label1 = Label(self.frame, text=" ").grid(row=ro, column=1)
                    ro += 1

            self.y1vars.append(IntVar())
            self.y1 = Checkbutton(self.frame, text="                 ", variable=self.y1vars[i], anchor='w')
            self.y1.grid(row=ro, column=1)
            ro += 1

        ro = 0
        for i, checkboxname in enumerate(self.allch):
            for j in range(len(self.allchlen)):
                if i == self.allchlen[j]:
                    self.label1 = Label(self.frame, text=" ").grid(row=ro, column=2)
                    ro += 1

            self.y2vars.append(IntVar())
            self.y2 = Checkbutton(self.frame, text="          ", variable=self.y2vars[i], anchor='w')
            self.y2.grid(row=ro, column=2)
            # self.y2.config(bg='silver')
            ro += 1

    def plot(self):

        fig, ax1 = plt.subplots()
        ax2 = ax1.twinx()

        xfinalValue = []
        for x in self.xvars:
            xfinalValue.append(x.get())
        print("xcheckbox true", xfinalValue)
        self.a = np.split(xfinalValue, self.allchwo)  # split X col selected per file
        print(self.a)

        y1finalValue = []
        for x in self.y1vars:
            y1finalValue.append(x.get())
        print("y1checkbox true", y1finalValue)
        self.b = np.split(y1finalValue, self.allchwo)  # split Y1 col selected per file
        print(self.b)

        y2finalValue = []
        for x in self.y2vars:
            y2finalValue.append(x.get())
        print("y2checkbox true", y2finalValue)
        self.e = np.split(y2finalValue, self.allchwo)  # split Y2 col selected per file
        print(self.e)

        self.allchpf = np.split(self.allch, self.allchwo)
        print("all ch per files", self.allchpf)

        c = 0
        self.d = []  # initialize an array for Y1 in each file
        self.g = []  # initialize an array for Y2 in each file
        for j in self.allfiles:
            self.f = vs.open(j)  # open first hdf5 file

            self.fpath, tail = os.path.split(j)
            print("file path", self.fpath)
            print("fname", tail)
            # fname give filename with extension
            # file name with out extension "fnamewoe"
            (self.fnamewoe, ext) = os.path.splitext(tail)
            print(self.fnamewoe)

            self.d = self.allchpf[c]  # load first set of channels of y1 for the first file in the array self.d
            print("dvalue", self.d)

            self.g = self.allchpf[c]  # load first set of channels of y2 for the first file in the array self.d

            xres = [i for i, val in enumerate(self.a[c]) if val]
            print("index of selected ch in X= ", xres)
            xcolumns = [self.d[i] for i in xres]
            print("name of the selected ch in X= ", xcolumns)

            clr = ['#1ACE82', '#17becf', '#7A122E', '#ff4fa7', '#d9d900',
                   '#2940CE', '#00e6e6', '#aa00aa', '#2a2a2a', '#ded1ae',
                   '#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd',
                   '#8c564b', '#e377c2', '#7f7f7f', '#bcbd22', '#C2AEE9']  # plot colur in y2 axis

            if len(self.a[c]) >= 1:
                print(self.b[c])
                y1res = [i for i, val in enumerate(self.b[c]) if val]
                print("index of selected ch in Y1= ", y1res)
                y1columns = [self.d[i] for i in y1res]
                print("name of the selected ch in Y1= ", y1columns)

                y2res = [i for i, val in enumerate(self.e[c]) if val]
                print("index of selected ch in Y2= ", y2res)
                y2columns = [self.d[i] for i in y2res]
                print("name of the selected ch in Y2= ", y2columns)

                if len(xcolumns) == 0:
                    pass
                else:
                    if len(y1columns) > 0:
                        for i in range(len(y1columns)):
                            ax1.plot(self.f[xcolumns[0]].values, self.f[y1columns[i]].values,
                                     label=y1columns[i] + "_" + self.fnamewoe)
                            ax1.set_ylabel(y1columns)

                    else:
                        ax1.yaxis.set_major_formatter(plt.NullFormatter())
                        ax1.axes.get_yaxis().set_visible(False)
                        pass

                    if len(y2columns) > 0:
                        for i in range(len(y2columns)):
                            ax2.plot(self.f[xcolumns[0]].values, self.f[y2columns[i]].values,
                                     label=y2columns[i] + "_" + self.fnamewoe, color=clr[i])
                            ax2.set_ylabel(y2columns)

                    else:
                        ax2.yaxis.set_major_formatter(plt.NullFormatter())
                        ax2.axes.get_yaxis().set_visible(False)
                        pass
            c += 1  # count increment by 1 to open next file using vs.open
            ax1.set_xlabel(xcolumns)
        line1, label1 = ax1.get_legend_handles_labels()
        line2, label2 = ax2.get_legend_handles_labels()
        line = line1 + line2
        label = label1 + label2

        ax1.grid()
        ax2.grid()
        plt.legend(line, label, loc="upper left", bbox_to_anchor=(1.06, 1))
        fig.tight_layout()
        plt.show(block=False)


root = Tk()
app = Application(master=root)
root.mainloop()
>>
```

**Comment by sreevanii** [comment]
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1705, in __call__
  File "plot1.py", line 243, in openhdf5
  File "lib\site-packages\vaex\__init__.py", line 166, in open
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "e:\anaconda1\sample\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "lib\site-packages\vaex\file\__init__.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "e:\anaconda1\sample\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "lib\site-packages\vaex\file\other.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "e:\anaconda1\sample\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "lib\site-packages\astropy\table\__init__.py", line 66, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "e:\anaconda1\sample\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "lib\site-packages\astropy\io\fits\__init__.py", line 70, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "e:\anaconda1\sample\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "lib\site-packages\astropy\io\fits\convenience.py", line 64, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "e:\anaconda1\sample\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "lib\site-packages\astropy\io\fits\diff.py", line 28, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "e:\anaconda1\sample\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "lib\site-packages\astropy\io\fits\hdu\__init__.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "e:\anaconda1\sample\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "lib\site-packages\astropy\io\fits\hdu\compressed.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "e:\anaconda1\sample\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "lib\site-packages\astropy\io\fits\hdu\image.py", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "e:\anaconda1\sample\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "lib\site-packages\dask\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "e:\anaconda1\sample\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "lib\site-packages\dask\config.py", line 588, in <module>
  File "lib\site-packages\dask\config.py", line 581, in _initialize
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Sreevani\\AppData\\Local\\Temp\\_MEI61722\\dask\\dask.
yaml'

**Comment by andyfaff** [comment]
This doesn't look like a numpy issue to me, looks like a PyInstaller question to do with dask.

**Comment by sreevanii** [comment]
how to solve the issue? please suggest me..
