### ISSUE TITLE
[regression] bincount with uint64

### ISSUE THREAD

**Issue by nschloe** [numpy/numpy#17760]
`bincount` doesn't work (anymore) with an input array of dtype `numpy.uint64`. 
```python
import numpy

a = numpy.array([0, 1, 2], dtype=numpy.uint64)
numpy.bincount(a)
```
```
  File "<__array_function__ internals>", line 5, in bincount
TypeError: Cannot cast array data from dtype('uint64') to dtype('int64') according to the rule 'safe'
```

**Comment by eric-wieser** [comment]
I can't speak for whether this is deliberate, but the obvious workaround is to add the unsafe cast to `intp` yourself

**Comment by mattip** [comment]
What version of numpy did this work on? It raises that error on 1.16 for me.

**Comment by nschloe** [comment]
1.19.4

**Comment by mattip** [comment]
platform?

**Comment by mattip** [comment]
```
Python 3.7.8 | packaged by conda-forge | (default, Jul 31 2020, 02:25:08) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> numpy.__version__
'1.16.0'
>>> a = numpy.array([0, 1, 2], dtype=numpy.uint64)
>>> numpy.bincount(a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Cannot cast array data from dtype('uint64') to dtype('int64') according to the rule 'safe'
>>> 
```

**Comment by nschloe** [comment]
> platform?

Linux.

**Comment by mattip** [comment]
> `bincount` doesn't work (anymore)

I meant what version/platform did this successfully run on without raising an error.

**Comment by mattip** [comment]
It raises the same error with python3.6  linux 64, numpy 1.10.1. I don't think this is a regression.

**Comment by nschloe** [comment]
> I meant what version/platform did this successfully run on without raising an error.

I found the error in an old piece of code that used to work. I can't remember when I last run it; it's been a while for sure. If it's easier, we might just call it a regular old bug.

**Comment by mattip** [comment]
Also the error message is not friendly enough: `File "<__array_function__ internals>", line 5, in bincount`.

**Comment by eric-wieser** [comment]
Is it possible that what changed is that your code now produces `uint64` instead of some other type?

**Comment by nschloe** [comment]
I'm not sure, so yeah, that's possible.

**Comment by thomas-scrace** [comment]
Arguably it is better not to accept uints, since the function is only defined for non-negative integers anyway, and silently casting to int64 might cause hard to understand bugs. Might be better to make the user explicitly do the cast themselves.

In which case the docs should be updated rather than the code.

Just a drive-by opinion; I am not that familiar with the code base :)

**Comment by ayush1300** [comment]
Hello everyone I gave a thought how to include negative numbers in this bincount function.
So what I was thinking was for the whole numbers part the output can be as it is, that is from index `0` to `maximumWholeNumber ` we have frequencies of all whole numbers. After the index  `maximumWholeNumber ` we have frequencies of all negative elements. 
For example :
`import numpy

a = numpy.array([0, 1, 2, 5, 6, 9, -5, -3], dtype=numpy.uint64)

out = numpy.bincount(a)

# Output shall be out = [1 1 1 0 0 1 1 0 0 1 1 0 1 0 0]
# Now here from indexes 0 to 9(both inclusive) we have count of whole numbers in the array a. 
# From index 10-14(both inclusive) the frequencies are of -5,-4,-3,-2 and -1 respectively.
# This is done so that finally for out[-1] we get answer 0. For out[-3] and ou[-5] we get 1. 

`

**Comment by ayush1300** [comment]
Hello everyone I gave a thought how to include negative numbers in this bincount function.
So what I was thinking was for the whole numbers part the output can be as it is, that is from index 0 to maximumWholeNumber we have frequencies of all whole numbers. After the index maximumWholeNumber we have frequencies of all negative elements.
For example :

`

import numpy
a = numpy.array([0, 1, 2, 5, 6, 9, -5, -3], dtype=numpy.uint64)
out = numpy.bincount(a)
# Output shall be out = [1 1 1 0 0 1 1 0 0 1 1 0 1 0 0]
# Now here from indexes 0 to 9(both inclusive) we have count of whole numbers in the array a.
# From index 10-14(both inclusive) the frequencies are of -5,-4,-3,-2 and -1 respectively.
# This is done so that finally for out[-1] we get answer 0. For out[-3] and ou[-5] we get 1.

`

**Comment by ayush1300** [comment]
Hello everyone I gave a thought how to include negative numbers in this bincount function.
So what I was thinking was for the whole numbers part the output can be as it is, that is from index 0 to maximumWholeNumber we have frequencies of all whole numbers. After the index maximumWholeNumber we have frequencies of all negative elements.
For example :
`import numpy

a = numpy.array([0, 1, 2, 5, 6, 9, -5, -3], dtype=numpy.uint64)

out = numpy.bincount(a)
Output shall be out = [1 1 1 0 0 1 1 0 0 1 1 0 1 0 0]
Now here from indexes 0 to 9(both inclusive) we have count of whole numbers in the array a.
From index 10-14(both inclusive) the frequencies are of -5,-4,-3,-2 and -1 respectively.
This is done so that finally for out[-1] we get answer 0. For out[-3] and ou[-5] we get 1.

`

**Comment by ayush1300** [comment]
Hello everyone I gave a thought how to include negative numbers in this bincount function.
So what I was thinking was for the whole numbers part the output can be as it is, that is from index 0 to maximumWholeNumber we have frequencies of all whole numbers. After the index maximumWholeNumber we have frequencies of all negative elements.
For example :
```
import numpy
a = numpy.array([0, 1, 2, 5, 6, 9, -5, -3], dtype=numpy.uint64)
out = numpy.bincount(a)
```

1. Output shall be out = [1 1 1 0 0 1 1 0 0 1 1 0 1 0 0]
2. Now here from indexes 0 to 9(both inclusive) we have count of whole numbers in the array a.
3. From index 10-14(both inclusive) the frequencies are of -5,-4,-3,-2 and -1 respectively.
4. This is done so that finally for out[-1] we get answer 0. For out[-3] and ou[-5] we get 1.

**Comment by eric-wieser** [comment]
@ayush1300, note that the behavior you describe can be achieved today with:
```python
def bincount_with_neg(x):
    n = (1 + a.max() - a.min())
    return np.bincount(a % n, minlength=n)
```
```python
>>> bincount_with_neg(np.array([0, 1, 2, 5, 6, 9, -5, -3], dtype=numpy.intp))
array([1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0], dtype=int64)
```
Perhaps we should give `np.bincount(a % n, minlength=n)` as an example in the docs for dealing with counting negative numbers. For instance:
```
In [53]: np.bincount(np.array([-1, -1, 0, 1, 2, 2, 2]) % 10, minlength=10)
Out[53]: array([1, 1, 3, 0, 0, 0, 0, 0, 0, 2], dtype=int64)
```

**Comment by ayush1300** [comment]
I know out[-6] will give a wrong answer, but that value can be left to the user itself that if he goes with negative value lesser than the least negative value in the array then he would face errors.

**Comment by ayush1300** [comment]
@eric-wieser yes I think we can give this example in the docs and could make these changes. I can't think of any better solution that keeps the consistency of the function bincount. Another solution could be that we give a 2d array as output in which , but then that would be a little weird as I think. For example out[a][0] will contain an element from the range a.min() to a.max() and out[a][1] will give the answer to the frequency of out[a][0]. In this way the user does not have to calculate the least value present in the array as in the previous case.

**Comment by mattip** [comment]
> Another solution could be that we give a 2d array as output 

... which would make `bincount` overlap even more with `histogram`

**Comment by nschloe** [comment]
Note that this latter discussion is off-topic. The bug report is about making bincount work for `uint64`, and unsigned type. If you want it to work with negative numbers, you should perhaps open a new issue.

**Comment by nschloe** [comment]
This is fixed since 2.2.4 (https://github.com/numpy/numpy/pull/28420).
