### ISSUE TITLE
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

### ISSUE THREAD

**Issue by kk2527** [numpy/numpy#17766]
I am unable to import numpy . I am trying to develop a user defined extension(udx)  in vertica in python . When I try to import other packges there was no issue .

my server is on centos and installed numpy using pip3 . numpy==1.19.4 , python version 3.6.8

### Error message:
```
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

SQL Error [3399] [VP001]: [Vertica][VJDBC](3399) ROLLBACK: Failure in UDx RPC call InvokeGetLibraryInfo(): Error calling setupExecContext() in User Defined Object [] at [/data/qb_workspaces/jenkins2/ReleaseBuilds/Hammermill/REL-10_0_0-x_hammermill/build/vertica/OSS/UDxFence/PythonInterface.cpp:176], error code: 0, message: Error [/data/qb_workspaces/jenkins2/ReleaseBuilds/Hammermill/REL-10_0_0-x_hammermill/build/vertica/OSS/UDxFence/PythonInterface.cpp:212] function ['import']
(Python error type [<class 'ImportError'>])
Traceback (most recent call last):
  File "/home/dbadmin/.local/lib/python3.6/site-packages/numpy/core/__init__.py", line 22, in <module>
    from . import multiarray
  File "/home/dbadmin/.local/lib/python3.6/site-packages/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/home/dbadmin/.local/lib/python3.6/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dbadmin/pyFFT.py", line 2, in <module>
    import numpy
  File "/home/dbadmin/.local/lib/python3.6/site-packages/numpy/__init__.py", line 140, in <module>
    from . import core
  File "/home/dbadmin/.local/lib/python3.6/site-packages/numpy/core/__init__.py", line 48, in <module>
    raise ImportError(msg)
ImportError: 
```

**Comment by mattip** [comment]
The continuation of the error message is missing. It should have mentioned looking [here](https://numpy.org/devdocs/user/troubleshooting-importerror.html) and given us valuable feedback information to help you. Did you look at the link?

**Comment by kk2527** [comment]
sorry , the full error is here : 

SQL Error [3399] [VP001]: [Vertica][VJDBC](3399) ROLLBACK: Failure in UDx RPC call InvokeGetLibraryInfo(): Error calling setupExecContext() in User Defined Object [] at [/data/qb_workspaces/jenkins2/ReleaseBuilds/Hammermill/REL-10_0_0-x_hammermill/build/vertica/OSS/UDxFence/PythonInterface.cpp:176], error code: 0, message: Error [/data/qb_workspaces/jenkins2/ReleaseBuilds/Hammermill/REL-10_0_0-x_hammermill/build/vertica/OSS/UDxFence/PythonInterface.cpp:212] function ['import']
(Python error type [<class 'ImportError'>])
Traceback (most recent call last):
  File "/home/dbadmin/udx_venv/lib64/python3.6/site-packages/numpy/core/__init__.py", line 22, in <module>
    from . import multiarray
  File "/home/dbadmin/udx_venv/lib64/python3.6/site-packages/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/home/dbadmin/udx_venv/lib64/python3.6/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dbadmin/pyFFT.py", line 2, in <module>
    import numpy
  File "/home/dbadmin/udx_venv/lib64/python3.6/site-packages/numpy/__init__.py", line 140, in <module>
    from . import core
  File "/home/dbadmin/udx_venv/lib64/python3.6/site-packages/numpy/core/__init__.py", line 48, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.7 from "/opt/vertica/bin/vertica-udx-Python"
  * The NumPy version is: "1.19.4"

and make sure that they are the versions you expect.
Please carefully study the documentation li

**Comment by mattip** [comment]
You are mixing your python versions. You are using `/opt/vertica/bin/vertica-udx-Python` (Python3.7) together with `/home/dbadmin/udx_venv/lib64/python3.6/site-packages` (Python3.6).

**Comment by kk2527** [comment]
thank you , its working now. the problem is with python versions as you suggested which i didnt notice
