### ISSUE TITLE
linalg.lstsq nan error not caught by numpy, get MKL error message

### ISSUE THREAD

**Issue by efwilliams** [numpy/numpy#17835]
Feeding all nans into linalg.lstsq doesn't get caught at the Numpy level, and returns different MKL errors depending on the version. Numpy 1.19.4 kind of catches it in that it throws a ValueError, but it actually gives a more confusing message since while it is clear that matrix A is the 4th parameter of DGELSD, I have no idea what CFROM, the 4th parameter of DLASCL, is or where/why it is called. 

This may be related to issue #7644, and I have found a couple examples of this same problem reported on other websites and not as an issue here. 

```python
import numpy as np
N = 2
A = np.empty((N,N))
b = np.empty(N)
A[:]= np.nan
b[:]= np.nan
x = np.linalg.lstsq(A,b,rcond=None)[0]
```

For numpy version 1.14.6:
```
Intel MKL ERROR: Parameter 4 was incorrect on entry to DGELSD.
```

For numpy version 1.19.4:
```
Traceback (most recent call last):
  File "/home/efwillia/Desktop/research/Belgium/interferometry/Gibraltar_tomo/tomo_tomo/bug_ex.py", line 14, in <module>
    x = np.linalg.lstsq(A,b,rcond=None)[0]
  File "<__array_function__ internals>", line 5, in lstsq
  File "/home/efwillia/anaconda3/envs/newnumpy/lib/python3.9/site-packages/numpy/linalg/linalg.py", line 2306, in lstsq
    x, resids, rank, s = gufunc(a, b, rcond, signature=signature, extobj=extobj)
ValueError: On entry to DLASCL parameter number 4 had an illegal value
```

**Comment by eric-wieser** [comment]
If we want to do anything here, it would probably be catching the `ValueError` and trying to diagnose the cause. I suspect the difference iin message between 1.19.4 and 1.14.6 is the version of the lapack library being used.

**Comment by JosephMehdiyev** [comment]
~Isn't a simple NaN value check for the inputs enough here? In the current numpy version, no `ValueError` is thrown so catching `ValueError` is not possible depending how lapack behaves.
The fix looks simple, but I am not sure if I am understanding everything correctly here~
