### ISSUE TITLE
np.exp doesn't like object arrays of

### ISSUE THREAD

**Issue by inducer** [numpy/numpy#18004]
### Reproducing code example:

```python
>>> import numpy as np
>>> np.__version__
'1.19.4'
>>> a = np.array([1., 2.], dtype=object)
>>> np.exp(a)
AttributeError: 'float' object has no attribute 'exp'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: loop of ufunc does not support argument 0 of type float which has no callable exp method
```
or even
```python
>>> a = np.array([np.float64(1), np.float64(2)], dtype=object)
>>> np.exp(a)
AttributeError: 'numpy.float64' object has no attribute 'exp'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: loop of ufunc does not support argument 0 of type numpy.float64 which has no callable exp method
```

It seems odd that this doesn't work, and it feels like it should... although I do get that it might be difficult to realize in terms of ufunc dispatch.

### NumPy/Python version information:

```
1.19.4 3.9.1 (default, Dec  8 2020, 07:51:42) 
[GCC 10.2.0]
```

cc @mtcam

**Comment by Dan-Patterson** [comment]
Not sure how you are getting an object array, but obviously if it isn't needed, the result is as expected.
Many times when I use object arrays, simply cycling through the bits in a list comprehension does the trick.
I am sure object arrays are not what was in mind for ufuncs

`z = np.array([1., 2.])
np.exp(z)
array([  2.718,   7.389])

z = np.array([1., 2.], dtype='O')
np.array([np.exp(i) for i in z])
array([  2.718,   7.389])`

**Comment by mattip** [comment]
The error is referring to the fact that `float(1).exp()` fails. NumPy does not go to much effort to handle functions on object arrays. In general object arrays will never really be fully integrated into NumPy, and maybe were a mistake in the first place, but are convenient for some container-like applications. Object dtypes are "out of scope" for the [Array API standard](https://data-apis.github.io/array-api/latest/purpose_and_scope.html#out-of-scope) (point 4).

**Comment by Dan-Patterson** [comment]
@mattip under the **Discussion** banner, my comment was more directed at why a = np.array([1., 2.], dtype=object) would be cast as an object array in the first place.  Or perhaps it was the result of some process that casts all outputs as object arrays.   Accounting for all cases where things may fail is a lost cause.  This may be one example of the deprecation warnings might be useful, but where do you stop? You have one for ragged arrays (VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences....), do you then have to provide one for arrays that shouldn't be cast as object arrays?

Object arrays are common containers for coordinate geometry and the components are ultimately conforming arrays or lists which can be converted to arrays.  
I have no problem with not expecting an object array to behave the same as float array, just as long as I have a method to treat the components as simple arrays.
Consider a triangle in a rectangle, I would have no expectation that it behave as one uniform entity.
```
a  # --- clockwise oriented outer-ring with counterclockwise inner-ring (aka, a hole)
array([array([[   0.00,    0.00],
       [   0.00,   10.00],
       [  10.00,   10.00],
       [  10.00,    0.00],
       [   0.00,    0.00]]),
       array([[   3.00,    3.00],
       [   7.00,    3.00],
       [   5.00,    7.00],
       [   3.00,    3.00]])], dtype=object)

[i.dtype for i in a]
 [dtype('float64'), dtype('float64')]

[i.shape for i in a]
 [(5, 2), (4, 2)]

[i.min(axis=0) for i in a].min(axis=0)  # -- component minimum
[array([   0.00,    0.00]), array([   3.00,    3.00])]

np.array([i.min(axis=0) for i in a]).min(axis=0)  # -- overall minimum
array([   0.00,    0.00])
```
Just don't get rid of object arrays, the "children" of the "parent" are well-behaved, if formed (raised) properly. ;)

**Comment by mattip** [comment]
> ... why `a = np.array([1., 2.], dtype=object)` would be cast as an object array 

I must not be parsing this correctly, the simple answer is "you requested an object array, so numpy created one for you".

Hopefully the new dtype work will allow one to create a [geoseries](https://geopandas.org/data_structures.html#geoseries) type data structure more easily without resorting to `object` dtype.

**Comment by Dan-Patterson** [comment]
@mattip I am familiar with the geoseries, but I have my own [https://github.com/Dan-Patterson/numpy_geometry](url).  
I don't actually create object arrays.  The common construct for coordinate geometry (json, wkt etc) "is" lists of lists (etc).  
I just became adept at unravelling them to something far simpler. (I simply use 2 arrays, one containing all the coordinates and a second, much smaller one, which defines the geometry construction (from-to points, inner/outer rings). ) 
It makes saving to and reading from *.npz format very clean since you are only using one float ndarray and one int_ ndarray.

**Comment by charris** [comment]
Just in case there is a misunderstanding, `dtype=` specifies the _resulting_ array type.

**Comment by Dan-Patterson** [comment]
@charris ... no confusion here

**Comment by inducer** [comment]
To explain context, this situation arose in a fledgling chemistry package where, most of the time, the array entries being operated on are large arrays full of degrees of freedom from a PDE solver, each representing spatially varying mass fractions of various chemical species. However, during testing, the "spatially-varying" part goes away, and we simply use single values, which brought about the problem I describe. It's [easy enough to hack around](https://github.com/inducer/pyrometheus/commit/1b81620a87c71ec87c33834c05cb61bcc309bd3e), but the fact that it didn't "just work" felt odd enough to me to merit some discussion.

**Comment by eric-wieser** [comment]
@inducer, I think the piece you're missing is a function that says "I know my output array must be n-d, please guess a type for me". Right now numpy doesn't let you do that, but it was something on our radar to make object arrays easier to work with.

Such a function could behave as:
```python
>>> make_array_nd(1, [1, 2, 3])
array([1, 2, 3])
>>> make_array_nd(1, [[1], [2], [3]])
array([list([1]), list([2]), list([3])]
>>> make_array_nd(1, 1)
ValueError
```

**Comment by seberg** [comment]
Maybe interesting aside, but I have the private function:
```
np.core._multiarray_umath._discover_array_parameters
```
and while it does not have it, the function could trivially get a `maxnd` or similar keyword which would be capable of doing this job. That of course also means it should be easy to add to `np.array` to avoid the duplicate effort.

**Comment by c-f-h** [comment]
@mattip Object arrays are currently the only way for me to work with arrays of extended precision floating point numbers from the `mpmath` package. (Coincidentally, they have the same problem with `exp` not being supported on them.) Are you aware of a better way of achieving that?

**Comment by mattip** [comment]
@c-f-h it seems you are describing a new problem. Please open a new issue, describing exactly what you are doing and what you expect to happen.

**Comment by c-f-h** [comment]
@mattip I don't think it's appropriate as a numpy bug report because it could be fixed on the mpmath side by defining an `exp()` method on their objects. My remark was more in response to the comments that object arrays may be unsupported/going away.

I'm aware this is not the best place to raise that concern though. I only stumbled on this thread because I searched for information on that particular exp problem.

**Comment by seberg** [comment]
I do not think anyone is planning to remove object arrays from NumPy, there might be discussions about priorities around how much trouble we should take to improve their oddities in some cases...

What might happen (but not on a schedule) is to make it easier to make _type specific_ object (dtype) arrays, which would mean  you could (and would have to) write a type specific `exp` loop, etc.

If you have an arbitrary-precision math library that is OK with fixed-sized storage (I suppose that would come with some limits to the exponents?) the new DType machinery is ready for prototyping – fixed size in the sense of string dtypes in NumPy: the user can pick the length and "S3+S3 = S6" is possible, but no dynamic choice.  I doubt we will have the new API fixed up and non-experimentally public for the next release, but the one after that seems very reasonable to me.  (Especially if people start using and thus vetting things).
(Non fixed-size, requires additional API for memory management of the storage, the path there is pretty clear, but it is a good chunk of work.)

**Comment by c-f-h** [comment]
@seberg That's interesting, but I think having to fix the precision at compile time takes away a lot of the advantages of extended precision, where (at least in my applications) I want to tailor the number of digits to the problem at hand.

My feeling is also that with extended precision numbers with 100+ digits, the additional cost of going through the object indirection is much smaller, relatively speaking, than for IEEE floating point numbers where you have efficient machine instructions. I haven't done any benchmarking on this though.

**Comment by seberg** [comment]
> My feeling is also that with extended precision numbers with 100+ digits

Agreed, but I don't know what is typical.  What I said is *not* compile time, though.  It is array *creation* time, i.e. you would write something like:  `arr = np.array([1, 2, 3], dtype=mpfloat(100, maxexp=...))` or so, and in pricniple `arr * arr` could decide that the result needs to have a higher precision too.

**Comment by c-f-h** [comment]
> What I said is _not_ compile time, though. It is array _creation_ time

Ah, that is more interesting! Do I understand correctly that that depends on numpy-internal dtype work that is not fully in place at this point?

**Comment by mattip** [comment]
Closing since this discussion strayed from the original report, and we will not change that behaviour.
