### ISSUE TITLE
Numpy import errors

### ISSUE THREAD

**Issue by fast-and-curious-1910** [numpy/numpy#18022]
Numpy fails to import.

### Steps to reproduce:

Installed by PIP 
Version = ``1.19.3`` 
Python version = ``3.9.1``
OS = ``Wndows 10 , Version 2004``

### Error message:
```
ImportError: cannot import name 'dtype' from partially initialized module 'numpy.core' (most likely due to a circular import) (E:\Coding Projects\CovProbDec\env\lib\site-packages\numpy\core\__init__.py)
```
*env is my python venv*

Full Error message:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "E:\Coding Projects\CovProbDec\env\lib\site-packages\numpy\__init__.py", line 140, in <module>
    from . import core
  File "E:\Coding Projects\CovProbDec\env\lib\site-packages\numpy\core\__init__.py", line 15, in <module>
    from . import _add_newdocs
  File "E:\Coding Projects\CovProbDec\env\lib\site-packages\numpy\core\_add_newdocs.py", line 13, in <module>
    from numpy.core import dtype
ImportError: cannot import name 'dtype' from partially initialized module 'numpy.core' (most likely due to a circular import) (E:\Coding Projects\CovProbDec\env\lib\site-packages\numpy\core\__init__.py)
```

It also brings up this error when using [Sklearn](https://github.com/scikit-learn/scikit-learn) as well

**Comment by mattip** [comment]
Is that the entire error message? Are you running inside an ide or directly from the command line?

**Comment by fast-and-curious-1910** [comment]
That is the entire message . I ran it directly from the command line.

**Comment by fast-and-curious-1910** [comment]
Re-installing it fixed it as usual
