### ISSUE TITLE
TypeError: '<' not supported between instances of 'dict' and 'int'

### ISSUE THREAD

**Issue by kenorb** [numpy/numpy#18038]
Python script stops with the following error:

> TypeError: '<' not supported between instances of 'dict' and 'int'

when trying to print numpy array using `with` block. It works fine when printing simple arrays, but not when detached from Torch's tensor.

### Reproducing code example:

```python
import numpy as np
import torch
import sys

# Defines numpy options.
np_opts_new = {
    'floatmode': "maxprec",
    'linewidth': 120,
    'suppress': True,
    'threshold': sys.maxsize,
}
np_opts_old = np.get_printoptions()

# Test 1 - this works.
np_arr = np.array([1, 2, 3, 4, 5])
with np.printoptions(np_opts_old):
    print(np_arr)

# Test 2 - this works as well.
mytensor = torch.tensor(np_arr)
np_arr = mytensor.detach().numpy()
with np.printoptions(np_opts_old):
    print(np_arr)

class MyModel(torch.nn.Module):
    def __init__(self, D_in, H, D_out):
        super(MyModel, self).__init__()
        self.linear_in = torch.nn.Linear(D_in, H)
        self.linear_out = torch.nn.Linear(H, D_out)

    def forward(self, x):
        layer_in = self.linear_in(x)
        layer_out = self.linear_out(layer_in)
        return layer_out

mymodel = MyModel(1, 1, 1)

# Test 3 - this does NOT work.
for name, param in mymodel.named_parameters():
    if name.endswith(".weight") or name.endswith(".bias"):
        np_arr = param.detach().numpy()

        # This is fine.
        np.printoptions(np_opts_new)
        print(np_arr)
        np.printoptions(np_opts_old)

        # This is not fine.
        with np.printoptions(np_opts_new):
            print(np_arr) # This breaks with TypeError.
```

### Error message:

```
$  python3 test.py
[1 2 3 4 5]
[1 2 3 4 5]
[[-0.3118031]]
Traceback (most recent call last):
  File "test.py", line 50, in <module>
    print(np_arr) # This breaks with TypeError.
  File "/usr/local/lib/python3.8/site-packages/numpy/core/arrayprint.py", line 1506, in _array_str_implementation
    return array2string(a, max_line_width, precision, suppress_small, ' ', "")
  File "/usr/local/lib/python3.8/site-packages/numpy/core/arrayprint.py", line 712, in array2string
    return _array2string(a, options, separator, prefix)
  File "/usr/local/lib/python3.8/site-packages/numpy/core/arrayprint.py", line 484, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/numpy/core/arrayprint.py", line 510, in _array2string
    format_function = _get_format_function(data, **options)
  File "/usr/local/lib/python3.8/site-packages/numpy/core/arrayprint.py", line 443, in _get_format_function
    return formatdict['float']()
  File "/usr/local/lib/python3.8/site-packages/numpy/core/arrayprint.py", line 382, in <lambda>
    FloatingFormat(data, prec, fmode, supp, sign, legacy=legacy),
  File "/usr/local/lib/python3.8/site-packages/numpy/core/arrayprint.py", line 874, in __init__
    self.precision = _none_or_positive_arg(self.precision, 'precision')
  File "/usr/local/lib/python3.8/site-packages/numpy/core/arrayprint.py", line 850, in _none_or_positive_arg
    if x < 0:
TypeError: '<' not supported between instances of 'dict' and 'int'
```

### NumPy/Python version information:

```
1.18.5 3.8.5 (default, Jul 21 2020, 10:48:26) 
[Clang 11.0.3 (clang-1103.0.32.62)]
```

**Comment by WarrenWeckesser** [comment]
In this code (and in all the other uses of `np.printoptions`)
```
        # This is not fine.
        with np.printoptions(np_opts_new):
            print(np_arr) # This breaks with TypeError.
```
you should be expanding dictionary `np_opts_new` with `**` to convert the key-value pairs to keyword arguments:
```
        # This is not fine.
        with np.printoptions(**np_opts_new):
            print(np_arr) # This breaks with TypeError.
```

**Comment by mattip** [comment]
Perhaps a check for this problem would be helpful. It could be done [where the options are parsed](https://github.com/numpy/numpy/blob/3095b43db1831d876915bb581078e8d11c9febfb/numpy/core/arrayprint.py#L65) as `if not isinstance(precision, (int, None): ...`

**Comment by kenorb** [comment]
> you should be expanding the dictionary `np_opts_new` with `**` to convert the key-value pairs to keyword arguments:

Thank you.

The following code:
```
with np.printoptions(**np_opts_new):
  print(nparr)
```

works fine.
