### ISSUE TITLE
dlopen failed: library "libgfortran.so.5" not found

### ISSUE THREAD

**Issue by caexy** [numpy/numpy#18033]
### Reproducing code example:
python
import numpy as np

### Error message:
Traceback (most recent call last):                  File "<stdin>", line 1, in <module>               File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/numpy/__init__.py", line 143, in <module>                                             from . import lib                               File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/numpy/lib/__init__.py", line 25, in <module>                                          from .index_tricks import *                     File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/numpy/lib/index_tricks.py", line 11, in <module>                                      import numpy.matrixlib as matrixlib             File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/numpy/matrixlib/__init__.py", line 4, in <module>                                     from .defmatrix import *                        File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/numpy/matrixlib/defmatrix.py", line 11, in <module>                                   from numpy.linalg import matrix_power           File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/numpy/linalg/__init__.py", line 73, in <module>                                       from .linalg import *                           File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/numpy/linalg/linalg.py", line 33, in <module>                                         from numpy.linalg import lapack_lite, _umath_linalg                                             ImportError: dlopen failed: library "libgfortran.so.5" not found
###NumPy/Python version information:
3.9.1 (default, Dec  9 2020, 13:22:01)            
[Clang 9.0.8 (https://android.googlesource.com/toolchain/llvm-project 98c855489
numpy:1.19.4

**Comment by mattip** [comment]
Where did you get numpy? What OS are you running? If you compiled yourself and then copied to another system, you will have to make sure that system has libgfortran.so. The package provided by `pip install` packages libgfortran inside the package.

**Comment by caexy** [comment]
> 你从哪里弄到麻木的？您正在运行什么操作系统？如果编译了自己然后复制到另一个系统，则必须确保该系统具有libgfortran.so。`pip install`软件包内部的软件包libgfortran提供的软件包。

I use the termux app. There's libgfortran.so.5 in the system.I added his corresponding directory into the PATH, but I still reported an error.

**Comment by mattip** [comment]
Maybe some of the hints on [the termux python page](https://wiki.termux.com/wiki/Python) will help?

**Comment by rgommers** [comment]
no further follow-up, I will close this because there is nothing to fix in NumPy
