### ISSUE TITLE
Unable to pip install with Big Sur 11.1

### ISSUE THREAD

**Issue by kennyfrc** [numpy/numpy#18139]
I recently upgraded to Big Sur 11.1, and I have tried to install numpy through the use of these two ways:

```
pip3 install numpy
```
and 
```
python3 -m pip install numpy --no-cache-dir
```
I used this as an [earlier reference](https://github.com/luxonis/depthai/issues/298) to no avail.

### Error message:

```
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/xxxxx/.venv/bin/python3 /Users/xxxx/.venv/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/qt/42nnsb353yz2l81tcbj8xsvc0000gn/T/tmpbicurjfs
         cwd: /private/var/folders/qt/42nnsb353yz2l81tcbj8xsvc0000gn/T/pip-install-aldosbmk/numpy
    Complete output (161 lines):
    Running from numpy source directory.
    setup.py:480: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
      run_build = parse_setuppy_commands()
    Processing numpy/random/_bounded_integers.pxd.in
    Processing numpy/random/_philox.pyx
    Processing numpy/random/_bounded_integers.pyx.in
    Processing numpy/random/_sfc64.pyx
    Processing numpy/random/_mt19937.pyx
    Processing numpy/random/bit_generator.pyx
    Processing numpy/random/mtrand.pyx
    Processing numpy/random/_generator.pyx
    Processing numpy/random/_pcg64.pyx
    Processing numpy/random/_common.pyx
    Cythonizing sources
    blas_opt_info:
    blas_mkl_info:
    customize UnixCCompiler
      libraries mkl_rt not found in ['/Users/kennyfrc/Documents/code/fastchess/.venv/lib', '/usr/local/lib', '/usr/lib', '/opt/local/lib']
      NOT AVAILABLE

    blis_info:
      libraries blis not found in ['/Users/xxx/.venv/lib', '/usr/local/lib', '/usr/lib', '/opt/local/lib']
      NOT AVAILABLE

    openblas_info:
    C compiler: clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers

    creating /var/folders/qt/42nnsb353yz2l81tcbj8xsvc0000gn/T/tmp70pspcds/var
    creating /var/folders/qt/42nnsb353yz2l81tcbj8xsvc0000gn/T/tmp70pspcds/var/folders
    creating /var/folders/qt/42nnsb353yz2l81tcbj8xsvc0000gn/T/tmp70pspcds/var/folders/qt
    creating /var/folders/qt/42nnsb353yz2l81tcbj8xsvc0000gn/T/tmp70pspcds/var/folders/qt/42nnsb353yz2l81tcbj8xsvc0000gn
    creating /var/folders/qt/42nnsb353yz2l81tcbj8xsvc0000gn/T/tmp70pspcds/var/folders/qt/42nnsb353yz2l81tcbj8xsvc0000gn/T
    creating /var/folders/qt/42nnsb353yz2l81tcbj8xsvc0000gn/T/tmp70pspcds/var/folders/qt/42nnsb353yz2l81tcbj8xsvc0000gn/T/tmp70pspcds
    compile options: '-c'
    clang: /var/folders/qt/42nnsb353yz2l81tcbj8xsvc0000gn/T/tmp70pspcds/source.c
    clang /var/folders/qt/42nnsb353yz2l81tcbj8xsvc0000gn/T/tmp70pspcds/var/folders/qt/42nnsb353yz2l81tcbj8xsvc0000gn/T/tmp70pspcds/source.o -L/opt/local/lib -lopenblas -o /var/folders/qt/42nnsb353yz2l81tcbj8xsvc0000gn/T/tmp70pspcds/a.out
      FOUND:
        libraries = ['openblas', 'openblas']
        library_dirs = ['/opt/local/lib']
        language = c
        define_macros = [('HAVE_CBLAS', None)]

      FOUND:
        libraries = ['openblas', 'openblas']
        library_dirs = ['/opt/local/lib']
        language = c
        define_macros = [('HAVE_CBLAS', None)]

    non-existing path in 'numpy/distutils': 'site.cfg'
    lapack_opt_info:
    lapack_mkl_info:
      libraries mkl_rt not found in ['/Users/xxxx/.venv/lib', '/usr/local/lib', '/usr/lib', '/opt/local/lib']
      NOT AVAILABLE

    openblas_lapack_info:
    C compiler: clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers

    creating /var/folders/qt/42nnsb353yz2l81tcbj8xsvc0000gn/T/tmphsq28m1a/var
    creating /var/folders/qt/42nnsb353yz2l81tcbj8xsvc0000gn/T/tmphsq28m1a/var/folders
    creating /var/folders/qt/42nnsb353yz2l81tcbj8xsvc0000gn/T/tmphsq28m1a/var/folders/qt
    creating /var/folders/qt/42nnsb353yz2l81tcbj8xsvc0000gn/T/tmphsq28m1a/var/folders/qt/42nnsb353yz2l81tcbj8xsvc0000gn
    creating /var/folders/qt/42nnsb353yz2l81tcbj8xsvc0000gn/T/tmphsq28m1a/var/folders/qt/42nnsb353yz2l81tcbj8xsvc0000gn/T
    creating /var/folders/qt/42nnsb353yz2l81tcbj8xsvc0000gn/T/tmphsq28m1a/var/folders/qt/42nnsb353yz2l81tcbj8xsvc0000gn/T/tmphsq28m1a
    compile options: '-c'
    clang: /var/folders/qt/42nnsb353yz2l81tcbj8xsvc0000gn/T/tmphsq28m1a/source.c
    clang /var/folders/qt/42nnsb353yz2l81tcbj8xsvc0000gn/T/tmphsq28m1a/var/folders/qt/42nnsb353yz2l81tcbj8xsvc0000gn/T/tmphsq28m1a/source.o -L/opt/local/lib -lopenblas -o /var/folders/qt/42nnsb353yz2l81tcbj8xsvc0000gn/T/tmphsq28m1a/a.out
      FOUND:
        libraries = ['openblas', 'openblas']
        library_dirs = ['/opt/local/lib']
        language = c
        define_macros = [('HAVE_CBLAS', None)]

      FOUND:
        libraries = ['openblas', 'openblas']
        library_dirs = ['/opt/local/lib']
        language = c
        define_macros = [('HAVE_CBLAS', None)]

    /usr/local/Cellar/python@3.9/3.9.0_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py:274: UserWarning: Unknown distribution option: 'define_macros'
      warnings.warn(msg)
    running dist_info
    running build_src
    build_src
    building py_modules sources
    creating build
    creating build/src.macosx-11-x86_64-3.9
    creating build/src.macosx-11-x86_64-3.9/numpy
    creating build/src.macosx-11-x86_64-3.9/numpy/distutils
    building library "npymath" sources
    Traceback (most recent call last):
      File "/Users/xxxx/.venv/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
        main()
      File "/Users/x/.venv/lib/python3.9/site-packages/xxxpip/_vendor/pep517/_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/Users/xxxxx/.venv/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 133, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/private/var/folders/qt/42nnsb353yz2l81tcbj8xsvc0000gn/T/pip-build-env-k8l5syxk/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 157, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "/private/var/folders/qt/42nnsb353yz2l81tcbj8xsvc0000gn/T/pip-build-env-k8l5syxk/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 248, in run_setup
        super(_BuildMetaLegacyBackend,
      File "/private/var/folders/qt/42nnsb353yz2l81tcbj8xsvc0000gn/T/pip-build-env-k8l5syxk/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 142, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 508, in <module>
        setup_package()
      File "setup.py", line 500, in setup_package
        setup(**metadata)
      File "/private/var/folders/qt/42nnsb353yz2l81tcbj8xsvc0000gn/T/pip-install-aldosbmk/numpy/numpy/distutils/core.py", line 169, in setup
        return old_setup(**new_attr)
      File "/private/var/folders/qt/42nnsb353yz2l81tcbj8xsvc0000gn/T/pip-build-env-k8l5syxk/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 165, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/Cellar/python@3.9/3.9.0_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/Cellar/python@3.9/3.9.0_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/local/Cellar/python@3.9/3.9.0_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/private/var/folders/qt/42nnsb353yz2l81tcbj8xsvc0000gn/T/pip-build-env-k8l5syxk/overlay/lib/python3.9/site-packages/setuptools/command/dist_info.py", line 31, in run
        egg_info.run()
      File "/private/var/folders/qt/42nnsb353yz2l81tcbj8xsvc0000gn/T/pip-install-aldosbmk/numpy/numpy/distutils/command/egg_info.py", line 24, in run
        self.run_command("build_src")
      File "/usr/local/Cellar/python@3.9/3.9.0_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/Cellar/python@3.9/3.9.0_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/private/var/folders/qt/42nnsb353yz2l81tcbj8xsvc0000gn/T/pip-install-aldosbmk/numpy/numpy/distutils/command/build_src.py", line 144, in run
        self.build_sources()
      File "/private/var/folders/qt/42nnsb353yz2l81tcbj8xsvc0000gn/T/pip-install-aldosbmk/numpy/numpy/distutils/command/build_src.py", line 155, in build_sources
        self.build_library_sources(*libname_info)
      File "/private/var/folders/qt/42nnsb353yz2l81tcbj8xsvc0000gn/T/pip-install-aldosbmk/numpy/numpy/distutils/command/build_src.py", line 288, in build_library_sources
        sources = self.generate_sources(sources, (lib_name, build_info))
      File "/private/var/folders/qt/42nnsb353yz2l81tcbj8xsvc0000gn/T/pip-install-aldosbmk/numpy/numpy/distutils/command/build_src.py", line 378, in generate_sources
        source = func(extension, build_dir)
      File "numpy/core/setup.py", line 658, in get_mathlib_info
        st = config_cmd.try_link('int main(void) { return 0;}')
      File "/usr/local/Cellar/python@3.9/3.9.0_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/command/config.py", line 241, in try_link
        self._check_compiler()
      File "/private/var/folders/qt/42nnsb353yz2l81tcbj8xsvc0000gn/T/pip-install-aldosbmk/numpy/numpy/distutils/command/config.py", line 80, in _check_compiler
        self.fcompiler = new_fcompiler(compiler=self.fcompiler,
      File "/private/var/folders/qt/42nnsb353yz2l81tcbj8xsvc0000gn/T/pip-install-aldosbmk/numpy/numpy/distutils/fcompiler/__init__.py", line 880, in new_fcompiler
        compiler = get_default_fcompiler(plat, requiref90=requiref90,
      File "/private/var/folders/qt/42nnsb353yz2l81tcbj8xsvc0000gn/T/pip-install-aldosbmk/numpy/numpy/distutils/fcompiler/__init__.py", line 851, in get_default_fcompiler
        compiler_type =  _find_existing_fcompiler(matching_compiler_types,
      File "/private/var/folders/qt/42nnsb353yz2l81tcbj8xsvc0000gn/T/pip-install-aldosbmk/numpy/numpy/distutils/fcompiler/__init__.py", line 802, in _find_existing_fcompiler
        c.customize(dist)
      File "/private/var/folders/qt/42nnsb353yz2l81tcbj8xsvc0000gn/T/pip-install-aldosbmk/numpy/numpy/distutils/fcompiler/__init__.py", line 526, in customize
        linker_so_flags = self.flag_vars.linker_so
      File "/private/var/folders/qt/42nnsb353yz2l81tcbj8xsvc0000gn/T/pip-install-aldosbmk/numpy/numpy/distutils/fcompiler/environment.py", line 37, in __getattr__
        return self._get_var(name, conf_desc)
      File "/private/var/folders/qt/42nnsb353yz2l81tcbj8xsvc0000gn/T/pip-install-aldosbmk/numpy/numpy/distutils/fcompiler/environment.py", line 53, in _get_var
        var = self._hook_handler(name, hook)
      File "/private/var/folders/qt/42nnsb353yz2l81tcbj8xsvc0000gn/T/pip-install-aldosbmk/numpy/numpy/distutils/fcompiler/__init__.py", line 705, in _environment_hook
        return hook()
      File "/private/var/folders/qt/42nnsb353yz2l81tcbj8xsvc0000gn/T/pip-install-aldosbmk/numpy/numpy/distutils/fcompiler/gnu.py", line 346, in get_flags_linker_so
        flags = GnuFCompiler.get_flags_linker_so(self)
      File "/private/var/folders/qt/42nnsb353yz2l81tcbj8xsvc0000gn/T/pip-install-aldosbmk/numpy/numpy/distutils/fcompiler/gnu.py", line 136, in get_flags_linker_so
        os.environ['MACOSX_DEPLOYMENT_TARGET'] = target
      File "/usr/local/Cellar/python@3.9/3.9.0_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/os.py", line 684, in __setitem__
        value = self.encodevalue(value)
      File "/usr/local/Cellar/python@3.9/3.9.0_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/os.py", line 756, in encode
        raise TypeError("str expected, not %s" % type(value).__name__)
    TypeError: str expected, not int
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/xxxxxx/.venv/bin/python3 /Users/xxxx/.venv/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/qt/42nnsb353yz2l81tcbj8xsvc0000gn/T/tmpbicurjfs Check the logs for full command output.
```

### NumPy/Python version information:

I tried to install numpy-1.19.5.

My python version is Python 3.9.0

**Comment by kennyfrc** [comment]
Apologies, this is a duplicate issue #17784
