### ISSUE TITLE
Available Cython dependency ignored for numpy 1.19.5

### ISSUE THREAD

**Issue by samfux84** [numpy/numpy#18138]
I created a venv in Python 3.7.4 and installed Cython 0.29.21 and then tried to compile numpy 1.19.5 from source, which always fails, claiming that the Cython 0.29.21 or newer is required. How can I convince numpy 1.19.5 to use Cython 0.29.21 that is present in the venv?

### Reproducing code example:
```
[sfux@eu-login-15 ~]$ source $HOME/pytorch_100_cupy90_540/bin/activate
(pytorch_100_cupy90_540) [sfux@eu-login-15 ~]$ python
Python 3.7.4 (default, Oct 16 2019, 13:45:57)
[GCC 6.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import Cython
>>> Cython.__version__
'0.29.21'
>>> quit()
(pytorch_100_cupy90_540)[sfux@eu-login-15 ~]$ OPENBLAS=$OPENBLAS_ROOT/lib64 pip install --no-binary :all: numpy==1.19.5
Collecting numpy==1.19.5
  Using cached numpy-1.19.5.zip (7.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /cluster/home/sfux/pytorch_100_cupy90_540/bin/python /cluster/home/sfux/pytorch_100_cupy90_540/lib64/python3.7/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpj7imd8ll
         cwd: /tmp/pip-install-er8yvjev/numpy_c2de2620db6a4838880f0691cd61c017
    Complete output (38 lines):
    Processing numpy/random/_bounded_integers.pxd.in
    Processing numpy/random/_mt19937.pyx
    Traceback (most recent call last):
      File "/tmp/pip-install-er8yvjev/numpy_c2de2620db6a4838880f0691cd61c017/tools/cythonize.py", line 235, in <module>
        main()
      File "/tmp/pip-install-er8yvjev/numpy_c2de2620db6a4838880f0691cd61c017/tools/cythonize.py", line 231, in main
        find_process_files(root_dir)
      File "/tmp/pip-install-er8yvjev/numpy_c2de2620db6a4838880f0691cd61c017/tools/cythonize.py", line 222, in find_process_files
        process(root_dir, fromfile, tofile, function, hash_db)
      File "/tmp/pip-install-er8yvjev/numpy_c2de2620db6a4838880f0691cd61c017/tools/cythonize.py", line 188, in process
        processor_function(fromfile, tofile)
      File "/tmp/pip-install-er8yvjev/numpy_c2de2620db6a4838880f0691cd61c017/tools/cythonize.py", line 76, in process_pyx
        raise RuntimeError(f'Building {VENDOR} requires Cython >= {required_version}')
    RuntimeError: Building NumPy requires Cython >= 0.29.21
    Running from numpy source directory.
    setup.py:480: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
      run_build = parse_setuppy_commands()
    Cythonizing sources
    Traceback (most recent call last):
      File "/cluster/home/sfux/pytorch_100_cupy90_540/lib64/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
        main()
      File "/cluster/home/sfux/pytorch_100_cupy90_540/lib64/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/cluster/home/sfux/pytorch_100_cupy90_540/lib64/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 133, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/cluster/apps/nss/gcc-6.3.0/python/3.7.4/x86_64/lib64/python3.7/site-packages/setuptools/build_meta.py", line 156, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "/cluster/apps/nss/gcc-6.3.0/python/3.7.4/x86_64/lib64/python3.7/site-packages/setuptools/build_meta.py", line 237, in run_setup
        self).run_setup(setup_script=setup_script)
      File "/cluster/apps/nss/gcc-6.3.0/python/3.7.4/x86_64/lib64/python3.7/site-packages/setuptools/build_meta.py", line 142, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 508, in <module>
        setup_package()
      File "setup.py", line 488, in setup_package
        generate_cython()
      File "setup.py", line 285, in generate_cython
        raise RuntimeError("Running cythonize failed!")
    RuntimeError: Running cythonize failed!
    ----------------------------------------
ERROR: Command errored out with exit status 1: /cluster/home/sfux/pytorch_100_cupy90_540/bin/python /cluster/home/sfux/pytorch_100_cupy90_540/lib64/python3.7/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpj7imd8ll Check the logs for full command output.
(pytorch_100_cupy90_540) [sfux@eu-login-15 ~]$
```

### Error message:

```
ERROR: Command errored out with exit status 1:
     command: /cluster/home/sfux/pytorch_100_cupy90_540/bin/python /cluster/home/sfux/pytorch_100_cupy90_540/lib64/python3.7/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpj7imd8ll
         cwd: /tmp/pip-install-er8yvjev/numpy_c2de2620db6a4838880f0691cd61c017
    Complete output (38 lines):
    Processing numpy/random/_bounded_integers.pxd.in
    Processing numpy/random/_mt19937.pyx
    Traceback (most recent call last):
      File "/tmp/pip-install-er8yvjev/numpy_c2de2620db6a4838880f0691cd61c017/tools/cythonize.py", line 235, in <module>
        main()
      File "/tmp/pip-install-er8yvjev/numpy_c2de2620db6a4838880f0691cd61c017/tools/cythonize.py", line 231, in main
        find_process_files(root_dir)
      File "/tmp/pip-install-er8yvjev/numpy_c2de2620db6a4838880f0691cd61c017/tools/cythonize.py", line 222, in find_process_files
        process(root_dir, fromfile, tofile, function, hash_db)
      File "/tmp/pip-install-er8yvjev/numpy_c2de2620db6a4838880f0691cd61c017/tools/cythonize.py", line 188, in process
        processor_function(fromfile, tofile)
      File "/tmp/pip-install-er8yvjev/numpy_c2de2620db6a4838880f0691cd61c017/tools/cythonize.py", line 76, in process_pyx
        raise RuntimeError(f'Building {VENDOR} requires Cython >= {required_version}')
    RuntimeError: Building NumPy requires Cython >= 0.29.21
    Running from numpy source directory.
    setup.py:480: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
      run_build = parse_setuppy_commands()
    Cythonizing sources
    Traceback (most recent call last):
      File "/cluster/home/sfux/pytorch_100_cupy90_540/lib64/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
        main()
      File "/cluster/home/sfux/pytorch_100_cupy90_540/lib64/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/cluster/home/sfux/pytorch_100_cupy90_540/lib64/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 133, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/cluster/apps/nss/gcc-6.3.0/python/3.7.4/x86_64/lib64/python3.7/site-packages/setuptools/build_meta.py", line 156, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "/cluster/apps/nss/gcc-6.3.0/python/3.7.4/x86_64/lib64/python3.7/site-packages/setuptools/build_meta.py", line 237, in run_setup
        self).run_setup(setup_script=setup_script)
      File "/cluster/apps/nss/gcc-6.3.0/python/3.7.4/x86_64/lib64/python3.7/site-packages/setuptools/build_meta.py", line 142, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 508, in <module>
        setup_package()
      File "setup.py", line 488, in setup_package
        generate_cython()
      File "setup.py", line 285, in generate_cython
        raise RuntimeError("Running cythonize failed!")
    RuntimeError: Running cythonize failed!
    ----------------------------------------
ERROR: Command errored out with exit status 1: /cluster/home/sfux/pytorch_100_cupy90_540/bin/python /cluster/home/sfux/pytorch_100_cupy90_540/lib64/python3.7/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpj7imd8ll Check the logs for full command output.
```

### NumPy/Python version information:

I try to install numpy 1.19.5 using the following dependencies that were installed from source code:

GCC 6.3.0
Python 3.7.4
OpenBLAS 0.2.20

**Comment by mattip** [comment]
What happens if you replace
```
$ OPENBLAS=$OPENBLAS_ROOT/lib64 pip install ...
```

with
```
$ OPENBLAS=$OPENBLAS_ROOT/lib64 python -m pip install ...
```

?

**Comment by mattip** [comment]
(also note OpenBLAS has released version 0.3.13 ...)

**Comment by samfux84** [comment]
Same issue with a newer OpenBLAS version (0.3.7) and "python -m pip"

```
[sfux@eu-login-20 ~]$ module list

Currently Loaded Modules:
  1) StdEnv   2) gcc/6.3.0   3) python/3.7.4   4) cuda/9.0.176   5) cudnn/7.3   6) hdf5/1.10.1   7) nccl/2.7.8-1   8) openblas/0.3.7


[sfux@eu-login-20 ~]$ source $HOME/pytorch_100_cupy90_540/bin/activate
(pytorch_100_cupy90_540) [sfux@eu-login-20 ~]$ python
Python 3.7.4 (default, Oct 16 2019, 13:45:57)
[GCC 6.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import Cython
>>> Cython.__version__
'0.29.21'
>>> quit()
(pytorch_100_cupy90_540) [sfux@eu-login-20 ~]$ OPENBLAS=$OPENBLAS_ROOT/lib64 python -m pip install --no-binary :all: numpy==1.19.5
Collecting numpy==1.19.5
  Using cached https://files.pythonhosted.org/packages/51/60/3f0fe5b7675a461d96b9d6729beecd3532565743278a9c3fe6dd09697fa7/numpy-1.19.5.zip
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    Complete output from command /cluster/home/sfux/pytorch_100_cupy90_540/bin/python /cluster/home/sfux/pytorch_100_cupy90_540/lib64/python3.7/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpx_wvk44c:
    Processing numpy/random/_bounded_integers.pxd.in
    Processing numpy/random/_mt19937.pyx
    Traceback (most recent call last):
      File "/tmp/pip-install-_5e8ppld/numpy/tools/cythonize.py", line 235, in <module>
        main()
      File "/tmp/pip-install-_5e8ppld/numpy/tools/cythonize.py", line 231, in main
        find_process_files(root_dir)
      File "/tmp/pip-install-_5e8ppld/numpy/tools/cythonize.py", line 222, in find_process_files
        process(root_dir, fromfile, tofile, function, hash_db)
      File "/tmp/pip-install-_5e8ppld/numpy/tools/cythonize.py", line 188, in process
        processor_function(fromfile, tofile)
      File "/tmp/pip-install-_5e8ppld/numpy/tools/cythonize.py", line 76, in process_pyx
        raise RuntimeError(f'Building {VENDOR} requires Cython >= {required_version}')
    RuntimeError: Building NumPy requires Cython >= 0.29.21
    Running from numpy source directory.
    setup.py:480: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
      run_build = parse_setuppy_commands()
    Cythonizing sources
    Traceback (most recent call last):
      File "/cluster/home/sfux/pytorch_100_cupy90_540/lib64/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>
        main()
      File "/cluster/home/sfux/pytorch_100_cupy90_540/lib64/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 197, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/cluster/home/sfux/pytorch_100_cupy90_540/lib64/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 69, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/cluster/apps/nss/gcc-6.3.0/python/3.7.4/x86_64/lib64/python3.7/site-packages/setuptools/build_meta.py", line 156, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "/cluster/apps/nss/gcc-6.3.0/python/3.7.4/x86_64/lib64/python3.7/site-packages/setuptools/build_meta.py", line 237, in run_setup
        self).run_setup(setup_script=setup_script)
      File "/cluster/apps/nss/gcc-6.3.0/python/3.7.4/x86_64/lib64/python3.7/site-packages/setuptools/build_meta.py", line 142, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 508, in <module>
        setup_package()
      File "setup.py", line 488, in setup_package
        generate_cython()
      File "setup.py", line 285, in generate_cython
        raise RuntimeError("Running cythonize failed!")
    RuntimeError: Running cythonize failed!

    ----------------------------------------
Command "/cluster/home/sfux/pytorch_100_cupy90_540/bin/python /cluster/home/sfux/pytorch_100_cupy90_540/lib64/python3.7/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpx_wvk44c" failed with error code 1 in /tmp/pip-install-_5e8ppld/numpy
You are using pip version 19.0.3, however version 20.3.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(pytorch_100_cupy90_540) [sfux@eu-login-20 ~]$
```

**Comment by picn0113** [comment]
You are using pip version 19.0.3, however version 20.3.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by samfux84** [comment]
I could find another solution, which does not require numpy 1.19.5. I am therefore closing this issue. Thank you for your help.
