### ISSUE TITLE
`percentile` and `nanpercentile` taken along axis of zero length behave differently

### ISSUE THREAD

**Issue by mdhaber** [numpy/numpy#18158]
I'm working on closing some old issues with `scipy.stats.scoreatpercentile`, and I noticed that when performing `percentile` along an axis of zero length, it raises an `IndexError`, whereas other functions, like `nanpercentile`, `mean`, and `std`, return NaN. I am not personally bothered by inconsistencies in these sorts of edge cases, but it would help if this were fixed here so I don't need to patch it downstream.

### Reproducing code example:

```python
import numpy as np
a = []
np.mean(a) # nan
np.std(a) # nan
np.nanpercentile(a, 50) # nan
np.percentile(a, 50) # error

a = np.zeros(1, 0)
np.mean(a, axis=1) # [nan]
np.std(a, axis=1) # [nan]
np.nanpercentile(a, 50, axis=1) # [nan]
np.percentile(a, 50, axis=1) # error
```

### Error message:
```
np.percentile([], 50)
Traceback (most recent call last):

  File "<ipython-input-167-c47e9204ebd3>", line 1, in <module>
    np.percentile([], 50)

  File "<__array_function__ internals>", line 6, in percentile

  File "/opt/anaconda3/envs/scipydev/lib/python3.7/site-packages/numpy/lib/function_base.py", line 3706, in percentile
    a, q, axis, out, overwrite_input, interpolation, keepdims)

  File "/opt/anaconda3/envs/scipydev/lib/python3.7/site-packages/numpy/lib/function_base.py", line 3826, in _quantile_unchecked
    interpolation=interpolation)

  File "/opt/anaconda3/envs/scipydev/lib/python3.7/site-packages/numpy/lib/function_base.py", line 3403, in _ureduce
    r = func(a, **kwargs)

  File "/opt/anaconda3/envs/scipydev/lib/python3.7/site-packages/numpy/lib/function_base.py", line 3941, in _quantile_ureduce_func
    x1 = take(ap, indices_below, axis=axis) * weights_below

  File "<__array_function__ internals>", line 6, in take

  File "/opt/anaconda3/envs/scipydev/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 194, in take
    return _wrapfunc(a, 'take', indices, axis=axis, out=out, mode=mode)

  File "/opt/anaconda3/envs/scipydev/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 61, in _wrapfunc
    return bound(*args, **kwds)

IndexError: cannot do a non-empty take from an empty axes.
```

### NumPy/Python version information:
```
1.18.1 3.7.7 (default, Mar 26 2020, 10:32:53) 
[Clang 4.0.1 (tags/RELEASE_401/final)]
```

**Comment by seberg** [comment]
The shape seems clearly a bug.

`nanpercentile` and `percentile` should ideally return the same thing as well. I don't have much of an opinion on error vs NaN. (Percentile does seem a bit less clear than mean, which naturally goes to `0/0`, but especially with axis, a NaN result may be useful).
