### ISSUE TITLE
precision argument of np.set_printoptions can take strings as inputs

### ISSUE THREAD

**Issue by FerdinandEiteneuer** [numpy/numpy#18254]
Hello,

I accidentally set the precision in np.set_printoptions to a string, i.e `np.set_printoptions(precision='2')`. 

set_printoptions does not complain if I do that. Is this desired behaviour?

When using print(some_array) a TypeError is raised. The traceback reveals the problem with the precision, but I think the problem should have been catched beforehand. The tb is long and maybe hard to read because of that.
### Reproducing code example:

```python
import numpy as np
np.set_printoptions(precision='2')
x=np.array([1, 2, 3.45678])
print(x)
```

### Error message:
Traceback (most recent call last):
  File "myproblem.py", line 7, in <module>
    print(x)
  File "/home/ferdinand/anaconda3/envs/rl/lib/python3.8/site-packages/numpy/core/arrayprint.py", line 1506, in _array_str_implementation
    return array2string(a, max_line_width, precision, suppress_small, ' ', "")
  File "/home/ferdinand/anaconda3/envs/rl/lib/python3.8/site-packages/numpy/core/arrayprint.py", line 712, in array2string
    return _array2string(a, options, separator, prefix)
  File "/home/ferdinand/anaconda3/envs/rl/lib/python3.8/site-packages/numpy/core/arrayprint.py", line 484, in wrapper
    return f(self, *args, **kwargs)
  File "/home/ferdinand/anaconda3/envs/rl/lib/python3.8/site-packages/numpy/core/arrayprint.py", line 510, in _array2string
    format_function = _get_format_function(data, **options)
  File "/home/ferdinand/anaconda3/envs/rl/lib/python3.8/site-packages/numpy/core/arrayprint.py", line 443, in _get_format_function
    return formatdict['float']()
  File "/home/ferdinand/anaconda3/envs/rl/lib/python3.8/site-packages/numpy/core/arrayprint.py", line 382, in <lambda>
    FloatingFormat(data, prec, fmode, supp, sign, legacy=legacy),
  File "/home/ferdinand/anaconda3/envs/rl/lib/python3.8/site-packages/numpy/core/arrayprint.py", line 874, in __init__
    self.precision = _none_or_positive_arg(self.precision, 'precision')
  File "/home/ferdinand/anaconda3/envs/rl/lib/python3.8/site-packages/numpy/core/arrayprint.py", line 850, in _none_or_positive_arg
    if x < 0:
TypeError: '<' not supported between instances of 'str' and 'int'

### NumPy/Python version information:

1.18.5 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0]

Edit:
### Comment
The message  '<' not supported between instances of 'str' and 'int'  was confusing as well. It did not suggest to me that something was wrong at the very top of the python file inside set_printoptions.

**Comment by charris** [comment]
Closed by #18263.
