### ISSUE TITLE
Importing Numpy 1.19.5 does not work for Python 3.7.9 but does for Python3.8.7

### ISSUE THREAD

**Issue by DrewTNBD** [numpy/numpy#18267]
Importing Numpy 1.19.5 does not work for Python 3.7.9 but does for Python3.8.7.

```
import numpy as np

print('imported')
print(np.__version__)
```

Under Python 3.7.9 I get:

```
Traceback (most recent call last):
  File "c:/Users/Drew/Desktop/testing_pandas.py", line 1, in <module>
    import numpy
  File "C:\Program Files\Python37\lib\site-packages\numpy\__init__.py", line 140, in <module>    
    from . import core
  File "C:\Program Files\Python37\lib\site-packages\numpy\core\__init__.py", line 48, in <module>    
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.7 from "C:\Program Files\Python37\python.exe"
  * The NumPy version is: "1.19.5"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath
```

I get the same behaviour when trying to use 1.19.5 and Blender's included Python 3.7.7.

But under Python 3.8.4 everything works as expected.

Are there any known compatibility issues?

**Comment by DrewTNBD** [comment]
Bah! I'm an idiot, fixed it. Was a local installation issue.
