### ISSUE TITLE
linalg.pinv of empty int matrix

### ISSUE THREAD

**Issue by toslunar** [numpy/numpy#18527]
`np.linalg.pinv` keeps `dtype` of the input, if the input is a (stack of) empty matrix.  Should `np.linalg.pinv` always return an array of `np.inexact` type (`_commonType(a)[1]`), like `np.linalg.inv` does?

https://github.com/numpy/numpy/blob/d7aa4085623b222058edb0ff38392c38c5e00c54/numpy/linalg/linalg.py#L1997-L2000

### Reproducing code example:

```python
import numpy as np
np.linalg.pinv(np.empty((3, 0), np.int32))  # => array([], shape=(0, 3), dtype=int32)
```

This seems incompatible with

```python
np.linalg.inv(np.empty((0, 0), np.int32))  # => array([], shape=(0, 0), dtype=float64)
```

`TypeError` could be raised at
```python
np.linalg.pinv(np.array([[]], object))  # => array([], shape=(0, 1), dtype=object)
```

The issue is not about an empty batch
```python
np.linalg.pinv(np.empty((0, 3, 7), np.int32))  # => array([], shape=(0, 7, 3), dtype=float64)
```

### NumPy/Python version information:

```
1.20.1 3.9.0 (default, Oct 15 2020, 16:29:12)
[Clang 11.0.0 (clang-1100.0.33.16)]
```

**Comment by eric-wieser** [comment]
That last example is the most convincing one for me that this is a bug. The relevant lines are:

https://github.com/numpy/numpy/blob/31647f1b3e56c2f2a471cd2c3a583311534173f8/numpy/linalg/linalg.py#L1997-L2000

The special case I think is there because one of the lines below will crash without it - but it might be worth just trying to remove that `if` entirely and see what breaks.

**Comment by anthonyhvo12** [comment]
I'm also looking into this issue. For

```np.linalg.pinv(np.empty((0, 3, 7), np.int32))  # => array([], shape=(0, 7, 3), dtype=float64)```

I tried the example at https://numpy.org/doc/stable/reference/generated/numpy.linalg.pinv.html and it gave me an error
```
>>> a = np.empty((0, 3, 7), np.int32)
>>> B = np.linalg.pinv(a)
>>> np.allclose(a, np.dot(a, np.dot(B, a)))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<__array_function__ internals>", line 5, in dot
ValueError: shapes (0,3,7) and (0,7,0,7) not aligned: 7 (dim 2) != 0 (dim 2)
>>> np.allclose(B, np.dot(B, np.dot(a, B)))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<__array_function__ internals>", line 5, in dot
ValueError: shapes (0,7,3) and (0,3,0,3) not aligned: 3 (dim 2) != 0 (dim 2)
```
Can someone clarify what would be the correct output of ```np.linalg.pinv(a)``` in this case?
