### ISSUE TITLE
Error raised in np.std with `where` argument

### ISSUE THREAD

**Issue by gshoffner** [numpy/numpy#18623]
An error is raised when invoking both the `axis` and `where` arguments in numpy.std for arrays of dimension greater than 2. 

### Reproducing code example:
```python
import numpy as np
arr = np.arange(3*3*4).reshape(3,3,4)
res = np.std(arr, axis = 1, where = arr>5)
```

### Error message:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<__array_function__ internals>", line 5, in std
  File "/home/grant/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 3560, in std
    return _methods._std(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
  File "/home/grant/.local/lib/python3.8/site-packages/numpy/core/_methods.py", line 261, in _std
    ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
  File "/home/grant/.local/lib/python3.8/site-packages/numpy/core/_methods.py", line 200, in _var
    if ddof >= rcount if where is True else umr_any(ddof >= rcount):
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

### NumPy/Python version information:

1.20.1 3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0]

**Comment by seberg** [comment]
Thanks for the report @gshoffner! This has been fixed on the development branch, and will be part of the 1.20.2 release. (see gh-18612).
