### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/Users/x/anaconda3/lib/python3.6/site-packages/numpy-1.19.4.dist-info/RECORD'

### ISSUE THREAD

**Issue by ahbon123** [numpy/numpy#18656]
I'm trying to uninstall numpy with command `pip3 uninstall numpy` under Mac OS system, but it raises an error:

```
x@bogon ~ % pip3 uninstall numpy
Found existing installation: numpy 1.19.4
ERROR: Exception:
Traceback (most recent call last):
  File "/Users/x/anaconda3/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 189, in _main
    status = self.run(options, args)
  File "/Users/x/anaconda3/lib/python3.6/site-packages/pip/_internal/commands/uninstall.py", line 88, in run
    auto_confirm=options.yes, verbose=self.verbosity > 0,
  File "/Users/x/anaconda3/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 657, in uninstall
    uninstalled_pathset = UninstallPathSet.from_dist(dist)
  File "/Users/x/anaconda3/lib/python3.6/site-packages/pip/_internal/req/req_uninstall.py", line 541, in from_dist
    for path in uninstallation_paths(dist):
  File "/Users/x/anaconda3/lib/python3.6/site-packages/pip/_internal/req/req_uninstall.py", line 74, in unique
    for item in fn(*args, **kw):
  File "/Users/x/anaconda3/lib/python3.6/site-packages/pip/_internal/req/req_uninstall.py", line 92, in uninstallation_paths
    r = csv.reader(dist.get_metadata_lines('RECORD'))
  File "/Users/x/anaconda3/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1432, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "/Users/x/anaconda3/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1420, in get_metadata
    value = self._get(path)
  File "/Users/x/anaconda3/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1616, in _get
    with open(path, 'rb') as stream:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/x/anaconda3/lib/python3.6/site-packages/numpy-1.19.4.dist-info/RECORD'
```
Anybody could help to deal with this issue? Many thanks.

**Comment by rgommers** [comment]
This means that either numpy wasn't installed with `pip`, or the install was manually modified. You can just delete `site-packages/numpy-1.19.4.dist-info` and `site-packages/numpy` manually to get past a problem like this.
