### ISSUE TITLE
Conda virtual environment import numpy Error, Library not loaded: @rpath/libopenblas.dylib

### ISSUE THREAD

**Issue by HS-ielab** [numpy/numpy#18663]
On my MacBook, when using conda virtual environment, I ran into some error when importing numpy. Any one can help? Thanks.

### Steps to reproduce:
The python version: 3.9.2 (I have also tried version 3.8.8, but the error exists)
numpy version: 1.19.2 (It's wired that the latest version 1.20.1 cannot be installed)

### Error message:

Traceback (most recent call last):
  File "/Users/XX/opt/anaconda3/envs/env_opt/lib/python3.9/site-packages/numpy/core/__init__.py", line 22, in <module>
    from . import multiarray
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/XX/opt/anaconda3/envs/env_opt/lib/python3.9/site-packages/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/XX/opt/anaconda3/envs/env_opt/lib/python3.9/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ImportError: dlopen(/Users/XX/opt/anaconda3/envs/env_opt/lib/python3.9/site-packages/numpy/core/_multiarray_umath.cpython-39-darwin.so, 2): Library not loaded: @rpath/libopenblas.dylib
  Referenced from: /Users/XX/opt/anaconda3/envs/env_opt/lib/python3.9/site-packages/numpy/core/_multiarray_umath.cpython-39-darwin.so
  Reason: image not found
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/XX/Documents/dev/pythonProject/importData.py", line 2, in <module>
    import numpy as np
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/XX/opt/anaconda3/envs/env_opt/lib/python3.9/site-packages/numpy/__init__.py", line 140, in <module>
    from . import core
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/XX/opt/anaconda3/envs/env_opt/lib/python3.9/site-packages/numpy/core/__init__.py", line 48, in <module>
    raise ImportError(msg)
ImportError: 
IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.
We have compiled some common reasons and troubleshooting tips at:
    https://numpy.org/devdocs/user/troubleshooting-importerror.html
Please note and check the following:
  * The Python version is: Python3.9 from "/Users/XX/opt/anaconda3/envs/env_opt/bin/python"
  * The NumPy version is: "1.19.2"
and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.
Original error was: dlopen(/Users/XX/opt/anaconda3/envs/env_opt/lib/python3.9/site-packages/numpy/core/_multiarray_umath.cpython-39-darwin.so, 2): Library not loaded: @rpath/libopenblas.dylib
  Referenced from: /Users/XX/opt/anaconda3/envs/env_opt/lib/python3.9/site-packages/numpy/core/_multiarray_umath.cpython-39-darwin.so
  Reason: image not found

**Comment by HS-ielab** [comment]
I have fixed the problem by installing the latest numpy version.  
Using the following command from numpy org website can install the latest version properly.
`conda install -c conda-forge numpy`
