### ISSUE TITLE
pytest crashes due to warning from pyreadline

### ISSUE THREAD

**Issue by LumaRay** [numpy/numpy#18674]
Trying to build and test Numpy to be used with i9-10980xe on Windows 10x64 Anaconda environment with Intel Distribution Python 3.8:

git clone https://github.com/numpy/numpy/
git checkout v1.20.1
conda install m2w64-gcc-fortran

site.cfg:
[mkl]
include_dirs = c:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2020.3.279\windows\mkl\include
library_dirs = c:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2020.3.279\windows\mkl\lib\intel64_win
libraries = mkl_rt

python setup.py build_ext --inplace -j 18 --cpu-baseline="SSSE3,SSE41,POPCNT,SSE42,AVX,F16C,FMA3,AVX2,AVX512F,AVX512CD" install

Build is ok.

But the test fails:

pip install hypothesis
pip install pytest
python runtests.py -v -m full

```
Building, see build.log...
Build OK
NumPy version 1.20.1
NumPy relaxed strides checking option: True
NumPy CPU features: SSE SSE2 SSE3 SSSE3 SSE41 POPCNT SSE42 AVX F16C FMA3 AVX2 AVX512F AVX512CD AVX512_SKX AVX512_CLX* AVX512_CNL? AVX512_ICL?
Traceback (most recent call last):
  File "runtests.py", line 641, in <module>
    main(argv=sys.argv[1:])
  File "runtests.py", line 358, in main
    result = test(args.mode,
  File "C:\Users\Jure\npbuild\build\testenv\Lib\site-packages\numpy\_pytesttester.py", line 209, in __call__
    code = pytest.main(pytest_args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\_pytest\config\__init__.py", line 143, in main
    config = _prepareconfig(args, plugins)
  File "C:\ProgramData\Anaconda3\lib\site-packages\_pytest\config\__init__.py", line 318, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File "C:\ProgramData\Anaconda3\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pluggy\manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "C:\ProgramData\Anaconda3\lib\site-packages\pluggy\callers.py", line 203, in _multicall
    gen.send(outcome)
  File "C:\ProgramData\Anaconda3\lib\site-packages\_pytest\helpconfig.py", line 100, in pytest_cmdline_parse
    config: Config = outcome.get_result()
  File "C:\ProgramData\Anaconda3\lib\site-packages\pluggy\callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "C:\ProgramData\Anaconda3\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\_pytest\config\__init__.py", line 1003, in pytest_cmdline_parse
    self.parse(args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\_pytest\config\__init__.py", line 1283, in parse
    self._preparse(args, addopts=addopts)
  File "C:\ProgramData\Anaconda3\lib\site-packages\_pytest\config\__init__.py", line 1191, in _preparse
    self.hook.pytest_load_initial_conftests(
  File "C:\ProgramData\Anaconda3\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pluggy\manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "C:\ProgramData\Anaconda3\lib\site-packages\pluggy\callers.py", line 208, in _multicall
    return outcome.get_result()
  File "C:\ProgramData\Anaconda3\lib\site-packages\pluggy\callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "C:\ProgramData\Anaconda3\lib\site-packages\pluggy\callers.py", line 182, in _multicall
    next(gen)  # first yield
  File "C:\ProgramData\Anaconda3\lib\site-packages\_pytest\capture.py", line 157, in pytest_load_initial_conftests
    _readline_workaround()
  File "C:\ProgramData\Anaconda3\lib\site-packages\_pytest\capture.py", line 90, in _readline_workaround
    import readline  # noqa: F401
  File "C:\ProgramData\Anaconda3\lib\site-packages\readline.py", line 34, in <module>
    rl = Readline()
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyreadline\rlmain.py", line 422, in __init__
    BaseReadline.__init__(self)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyreadline\rlmain.py", line 62, in __init__
    mode.init_editing_mode(None)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyreadline\modes\emacs.py", line 633, in init_editing_mode
    self._bind_key('space',       self.self_insert)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyreadline\modes\basemode.py", line 162, in _bind_key
    if not callable(func):
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyreadline\py3k_compat.py", line 8, in callable
    return isinstance(x, collections.Callable)
  File "C:\ProgramData\Anaconda3\lib\collections\__init__.py", line 49, in __getattr__
    warnings.warn("Using or importing the ABCs from 'collections' instead "
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
```

**Comment by eric-wieser** [comment]
It looks like you need to upgrade `pyreadline`

**Comment by LumaRay** [comment]
pip install --upgrade pyreadline
Requirement already up-to-date: pyreadline in c:\programdata\anaconda3\lib\site-packages (2.1)

**Comment by eric-wieser** [comment]
What you're seeing is https://github.com/pyreadline/pyreadline/issues/65

**Comment by eric-wieser** [comment]
Perhaps simply uninstalling `pyreadline` will fix your problem?

**Comment by eric-wieser** [comment]
At any rate, this isn't something numpy has any control over; `pytest` is the package consuming `readline`, and perhaps need to silence this specific error.

**Comment by LumaRay** [comment]
pip uninstall pyreadline
Found existing installation: pyreadline 2.1
ERROR: Cannot uninstall 'pyreadline'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

**Comment by LumaRay** [comment]
> At any rate, this isn't something numpy has any control over; `pytest` is the package consuming `readline`, and perhaps need to silence this specific error.

Yes, but it exits instead.

**Comment by eric-wieser** [comment]
You'll need to uninstall pyreadline via conda, since it looks like that is how it was installed

**Comment by LumaRay** [comment]
conda uninstall pyreadline
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are missing from the target environment:
  - pyreadline

**Comment by eric-wieser** [comment]
You might want to find a more general python support forum to help you uninstall that package then. The numpy issue tracker isn't the place to diagnose issues with uninstalling an unrelated package.

Perhaps the python discord, or stackoverflow?
