### ISSUE TITLE
np.reshape doesn't work on a pandas.Series, even though it is array-like

### ISSUE THREAD

**Issue by kbattocchi** [numpy/numpy#18715]
### Reproducing code example:

```python
import numpy as np
import pandas as pd
arr = np.reshape(pd.Series([1,2,3]), (-1,1))
```

### Error message:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<__array_function__ internals>", line 6, in reshape
  File "C:\Users\kebatt\AppData\Roaming\Python\Python36\site-packages\numpy\core\fromnumeric.py", line 299, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "C:\Users\kebatt\AppData\Roaming\Python\Python36\site-packages\numpy\core\fromnumeric.py", line 55, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "C:\Users\kebatt\AppData\Roaming\Python\Python36\site-packages\numpy\core\fromnumeric.py", line 48, in _wrapit
    result = wrap(result)
  File "C:\Users\kebatt\AppData\Roaming\Python\Python36\site-packages\pandas\core\generic.py", line 1790, in __array_wrap__
    return self._constructor(result, **d).__finalize__(
  File "C:\Users\kebatt\AppData\Roaming\Python\Python36\site-packages\pandas\core\series.py", line 327, in __init__
    data = sanitize_array(data, index, dtype, copy, raise_cast_failure=True)
  File "C:\Users\kebatt\AppData\Roaming\Python\Python36\site-packages\pandas\core\construction.py", line 496, in sanitize_array
    raise Exception("Data must be 1-dimensional")
Exception: Data must be 1-dimensional
```

### NumPy/Python version information:

`1.19.5 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 03:37:03) [MSC v.1900 64 bit (AMD64)]`

**Comment by bashtage** [comment]
This is because pandas overrides reshape. Numpy delegates to pandas which refuses to reshape. This is by design in pandas Iirc.

**Comment by gadamico** [comment]
You can always access the NumPy array underlying a Pandas object with the `.values` attribute.

Try running:

```import numpy as np
import pandas as pd
arr = np.reshape(pd.Series([1,2,3]).values, (-1,1))```

**Comment by andyfaff** [comment]
Seems like this issue can be closed now.
