### ISSUE TITLE
BUG: `nanpercentile` cannot use `keepdims` and `out` together

### ISSUE THREAD

**Issue by immaxchen** [numpy/numpy#18746]
Found this bug while i'm dealing with gh-18158

It seems `keepdims` and `out` cannot work together in `nanpercentile` and `nanquantile`

https://github.com/numpy/numpy/blob/0fe69ae3fc513aefd32a58ae8ccac294b12300d2/numpy/lib/nanfunctions.py#L1368-L1375

### Reproducing code example:

```python
import numpy as np
expected_shape = np.nanpercentile(np.zeros((3, 4, 2)), [50, 99], axis=0, keepdims=True).shape
o = np.zeros(expected_shape)
np.nanpercentile(np.zeros((3, 4, 2)), [50, 99], axis=0, keepdims=True, out=o)
```

### Error message:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<__array_function__ internals>", line 5, in nanpercentile
  File "C:\Users\USER\anaconda3\envs\mpl\lib\site-packages\numpy\lib\nanfunctions.py", line 1243, in nanpercentile
    return _nanquantile_unchecked(
  File "C:\Users\USER\anaconda3\envs\mpl\lib\site-packages\numpy\lib\nanfunctions.py", line 1368, in _nanquantile_unchecked
    r, k = function_base._ureduce(
  File "C:\Users\USER\anaconda3\envs\mpl\lib\site-packages\numpy\lib\function_base.py", line 3515, in _ureduce
    r = func(a, **kwargs)
  File "C:\Users\USER\anaconda3\envs\mpl\lib\site-packages\numpy\lib\nanfunctions.py", line 1398, in _nanquantile_ureduce_func
    out[...] = result
ValueError: could not broadcast input array from shape (2,4,2) into shape (2,1,4,2)
```

### NumPy/Python version information:

`1.20.1 3.9.1 (default, Dec 11 2020, 09:29:25) [MSC v.1916 64 bit (AMD64)]`

**Comment by seberg** [comment]
Seems like this was a much older version of gh-22544.  On the bright side it has been fixed :).
