### ISSUE TITLE
Numpy ImportError: cannot import name 'sliding_window_view' from 'numpy.lib.stride_tricks'

### ISSUE THREAD

**Issue by ctilly** [numpy/numpy#18928]
The sliding_window_view routine seems to be missing from numpy.lib.stride_tricks

numpy.__version__ = 1.19.4

OS = Windows 10

### Simply adding it as a library produces the error.
e.g. from numpy.lib.stride_tricks import sliding_window_view

In the below example I was trying to use the pandas-ta library, which is how I discovered this bug. 

### Error message:
ImportError: cannot import name 'sliding_window_view' from 'numpy.lib.stride_tricks' (C:\Users\chuck\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\stride_tricks.py)

Traceback (most recent call last):
  File "C:\Projects\Tradier\TechAnalysis.py", line 5, in <module>
    import pandas_ta as pta
  File "C:\Users\chuck\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas_ta\__init__.py", line 116, in <module>
    from pandas_ta.core import *
  File "C:\Users\chuck\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas_ta\core.py", line 4, in <module>
    from pandas_ta.candles.cdl_pattern import ALL_PATTERNS
  File "C:\Users\chuck\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas_ta\candles\__init__.py", line 2, in <module>
    from .cdl_doji import cdl_doji
  File "C:\Users\chuck\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas_ta\candles\cdl_doji.py", line 2, in <module>
    from pandas_ta.overlap import sma
  File "C:\Users\chuck\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas_ta\overlap\__init__.py", line 6, in <module>
    from .hilo import hilo
  File "C:\Users\chuck\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas_ta\overlap\hilo.py", line 4, in <module>
    from .ma import ma
  File "C:\Users\chuck\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas_ta\overlap\ma.py", line 8, in <module>
    from .linreg import linreg
  File "C:\Users\chuck\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas_ta\overlap\linreg.py", line 6, in <module>
    from numpy.lib.stride_tricks import sliding_window_view
ImportError: cannot import name 'sliding_window_view' from 'numpy.lib.stride_tricks' (C:\Users\chuck\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\stride_tricks.py)

**Comment by BvB93** [comment]
That would make sense, as `stride_tricks` was added in numpy 1.20, while you're still using 1.19.

**Comment by ctilly** [comment]
Indeed!  My bad.  Thanks for the quick reply.
