### ISSUE TITLE
Limited Dimension Exceeded

### ISSUE THREAD

**Issue by kkshitish** [numpy/numpy#19143]
I'd expect this behaviour with '**'

### Reproducing code example:
```python
from numpy.random import rand
rand(3**55,2**55)
```

```python
import numpy as np
x = np.random.rand(3**55,2**55)
print(x)
```

### Error message:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mtrand.pyx", line 1169, in numpy.random.mtrand.RandomState.rand
  File "mtrand.pyx", line 423, in numpy.random.mtrand.RandomState.random_sample
  File "_common.pyx", line 270, in numpy.random._common.double_fill
ValueError: Maximum allowed dimension exceeded

### NumPy/Python version information:

Numpy: 1.19.5 3.9.1, Python 3.9.1

**Comment by eric-wieser** [comment]
If this is already behaving as you expect, what are you asking for?

**Comment by kkshitish** [comment]
I didn't expect this behavior. It is throwing error because of size_t as you told. It means size_t is not suitable for "**"

**Comment by rkern** [comment]
`np.random.rand(n, m)` returns an array of shape `(n, m)`. Is that what you meant to type?

This means that no computer on the face of this earth is able to allocate the amount of memory that you are asking for. An array of shape `(3**55, 3**55)` is about `2**147` GiB.
