### ISSUE TITLE
array_equal or testing.assert_array_equal does not compare NaNs as numbers when dtype is object

### ISSUE THREAD

**Issue by tsuga** [numpy/numpy#19205]
What is the proper way to compare np.nan when dtype is object?
I tried the following two approaches, but both failed

# 1. np.array_equal 
### Reproducing code example:
```python
import numpy as np
np.array_equal(np.array([np.nan], dtype=object),np.array([np.nan], dtype=object), equal_nan=True)
```

### Error message:
```
Traceback (most recent call last):
  File "c:\Users\xxxx\xxxxx\.venv\lib\site-packages\numpy\core\numeric.py", line 2455, in array_equal
    a1nan, a2nan = isnan(a1), isnan(a2)
TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

# 2. np.testing.assert_array_equal
### Reproducing code example:
```python
import numpy as np
np.testing.assert_array_equal(np.array([np.nan], dtype=object),np.array([np.nan], dtype=object))
```

### Error message:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\Users\xxxx\xxxxx\.venv\lib\site-packages\numpy\testing\_private\utils.py", line 932, in assert_array_equal
    assert_array_compare(operator.__eq__, x, y, err_msg=err_msg,
  File "c:\Users\xxxx\xxxxx\.venv\lib\site-packages\numpy\testing\_private\utils.py", line 842, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

Mismatched elements: 1 / 1 (100%)
Max absolute difference: nan
Max relative difference: nan
 x: array([nan], dtype=object)
 y: array([nan], dtype=object)
```

### NumPy/Python version information:
1.20.3 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
I got the same error with arrays like that.

`b = [pandas.Timestamp('2018-06-23 22:23:00'), pandas.Timestamp('2018-06-23 23:38:00')]`

The error indicates that `isnan()` is called on each element before a `==` is done.
I would have done this otherwise.
Compare the elements by `==`.
If `False` be sure and check fir `isnan()`.

But I am also sure there is a strict reason why the numpy devs do it like that. If you can not modify that behaviour I would suggest a second parameter to the function; like `compare_equal_first` or something like that.
