### ISSUE TITLE
Compiler not found when specifying --fcompiler

### ISSUE THREAD

**Issue by mgiessing** [numpy/numpy#19210]
Hi, I'm trying to build numpy (1.19.5) with the IBM XL Fortran compiler using this command:

`python setup.py build --fcompiler=ibm`, but I'm getting the following error message:

```
Traceback (most recent call last):
  File "setup.py", line 508, in <module>
    setup_package()
  File "setup.py", line 500, in setup_package
    setup(**metadata)
  File "/root/git/numpy/numpy/distutils/core.py", line 169, in setup
    return old_setup(**new_attr)
  File "/root/miniconda3/envs/py37/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/root/miniconda3/envs/py37/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/root/miniconda3/envs/py37/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/root/miniconda3/envs/py37/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/root/git/numpy/numpy/distutils/command/build.py", line 40, in run
    old_build.run(self)
  File "/root/miniconda3/envs/py37/lib/python3.7/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/root/miniconda3/envs/py37/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/root/miniconda3/envs/py37/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/root/git/numpy/numpy/distutils/command/build_src.py", line 144, in run
    self.build_sources()
  File "/root/git/numpy/numpy/distutils/command/build_src.py", line 155, in build_sources
    self.build_library_sources(*libname_info)
  File "/root/git/numpy/numpy/distutils/command/build_src.py", line 288, in build_library_sources
    sources = self.generate_sources(sources, (lib_name, build_info))
  File "/root/git/numpy/numpy/distutils/command/build_src.py", line 378, in generate_sources
    source = func(extension, build_dir)
  File "numpy/core/setup.py", line 658, in get_mathlib_info
    st = config_cmd.try_link('int main(void) { return 0;}')
  File "/root/miniconda3/envs/py37/lib/python3.7/distutils/command/config.py", line 243, in try_link
    self._check_compiler()
  File "/root/git/numpy/numpy/distutils/command/config.py", line 84, in _check_compiler
    self.fcompiler.customize(self.distribution)
  File "/root/git/numpy/numpy/distutils/fcompiler/__init__.py", line 526, in customize
    linker_so_flags = self.flag_vars.linker_so
  File "/root/git/numpy/numpy/distutils/fcompiler/environment.py", line 37, in __getattr__
    return self._get_var(name, conf_desc)
  File "/root/git/numpy/numpy/distutils/fcompiler/environment.py", line 53, in _get_var
    var = self._hook_handler(name, hook)
  File "/root/git/numpy/numpy/distutils/fcompiler/__init__.py", line 705, in _environment_hook
    return hook()
  File "/root/git/numpy/numpy/distutils/fcompiler/ibm.py", line 71, in get_flags_linker_so
    version = self.get_version(ok_status=[0, 40])
  File "/root/git/numpy/numpy/distutils/fcompiler/ibm.py", line 30, in get_version
    version = FCompiler.get_version(self,*args,**kwds)
  File "/root/git/numpy/numpy/distutils/fcompiler/__init__.py", line 428, in get_version
    raise CompilerNotFound()
numpy.distutils.fcompiler.CompilerNotFound
```

I added a site.cfg according to the site.cfg.example template, but probably I missed something...?

```
[DEFAULT]
library_dirs = /opt/ibm/xlf/16.1.1/lib
include_dirs = /opt/ibm/xlf/16.1.1/include

[essl]
libraries = essl
library_dirs = /opt/ibmmath/essl/6.3/lib64
include_dirs = /opt/ibmmath/essl/6.3/include
runtime_library_dirs = /opt/ibmmath/essl/6.3/lib64
```

Of course I installed IBM XL C/C++, XL FORTRAN & the scientific library ESSL beforehand :-)

Thanks for your advice!

**Comment by rgommers** [comment]
We have now switched build systems from `numpy.distutils` to Meson, so this issue no longer applies. Hence I'll close it - thanks @mgiessing
