### ISSUE TITLE
Can't load using smart_open with mmap_mode

### ISSUE THREAD

**Issue by mataney** [numpy/numpy#19247]
When trying to use `np.load` with smart_open and mmap_mode I'm getting an `os.fspath` TypeError.

```python
>>> import numpy as np
>>> from smart_open import open as sopen
>>> arr = np.array([1,2,3])
>>> fakefile = 'gs://PATHTOFILE'
>>> np.save(sopen(fakefile, 'wb'), arr)
>>> np.load(sopen(fakefile, 'rb'))
array([1, 2, 3])
>>> np.load(sopen(fakefile, 'rb'), mmap_mode='r')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/matane/.local/share/virtualenvs/ingest-lib-IR9hIGHI/lib/python3.7/site-packages/numpy/lib/npyio.py", line 438, in load
    return format.open_memmap(file, mode=mmap_mode)
  File "/home/matane/.local/share/virtualenvs/ingest-lib-IR9hIGHI/lib/python3.7/site-packages/numpy/lib/format.py", line 863, in open_memmap
    with open(os_fspath(filename), 'rb') as fp:
TypeError: expected str, bytes or os.PathLike object, not Reader
```

Versions:
python=3.7.3
numpy=1.20.2
smart_open=3.0.0

**Comment by BvB93** [comment]
The error message is not quite applicable here, but the fact that an error is raised is expected.
Namely, `np.memmap` does not accept the `mmap_mode` parameter in conjunction with file-like objects:
``` python
In [11]: import numpy as np
    ...:
    ...: file = "test.npy"
    ...: np.save(file, [1, 2, 3])
    ...:

In [12]: with open(file, "rb") as f:
    ...:     np.load(f, mmap_mode='r')
    ...:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
    ...
ValueError: Filename must be a string or a path-like object.  Memmap cannot use existing file handles.
```
