### ISSUE TITLE
NumPy fails to locate openblas.so.0

### ISSUE THREAD

**Issue by alicezanella** [numpy/numpy#19250]
Hello, 

I'm having an issue with NumPy installed from source on a server. 
NumPy version 1.20.3 and Python 3.9. 

This is the error I encounter: 

```
Traceback (most recent call last):
  File "/home/zanella/Test_Cases/vertical_flap/structural/run.py", line 26, in <module>
    from mbc_py_interface import mbcNodal
  File "/home/zanella/softwares/mbdyn-develop/libexec/mbpy/mbc_py_interface.py", line 33, in <module>
    from numpy import *
  File "/home/zanella/softwares/Python-3.9.0/lib/python3.9/site-packages/numpy-1.20.3-py3.9-linux-x86_64.egg/numpy/__init__.py", line 145, in <module>
    from . import core
  File "/home/zanella/softwares/Python-3.9.0/lib/python3.9/site-packages/numpy-1.20.3-py3.9-linux-x86_64.egg/numpy/core/__init__.py", line 48, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.9 from "/home/zanella/softwares/Python-3.9.0/bin/python3"
  * The NumPy version is: "1.20.3"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: libopenblas.so.0: cannot open shared object file: No such file or directory
```
The thing is that libopenblas.so.0 is found if I do this: 

```
zanella@megamind:~/softwares/Python-3.9.0/lib/python3.9/site-packages/numpy-1.20.3-py3.9-linux-x86_64.egg/numpy/linalg$ ldd lapack_lite.cpython-39-x86_64-linux-gnu.so
linux-vdso.so.1 (0x00007ffe4f93a000)
libopenblas.so.0 => /usr/lib/libopenblas.so.0 (0x00007fc556442000)
libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fc556225000)
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fc555e7a000)
libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fc555b79000)
libgfortran.so.3 => /usr/lib/x86_64-linux-gnu/libgfortran.so.3 (0x00007fc55585b000)
/lib64/ld-linux-x86-64.so.2 (0x00007fc5584ed000)
libquadmath.so.0 => /usr/lib/x86_64-linux-gnu/libquadmath.so.0 (0x00007fc55561e000)
libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fc555408000)
```
Can you help me? Thank you. 

Alice

**Comment by charris** [comment]
Why not use one of the binary wheels. You can download the relevant version and use it to install NumPy.

**Comment by alicezanella** [comment]
The fact is that on the server I do not have root access. And I also have problems using `pip` because Python 3.9 has been installed without SSL certificate..

**Comment by charris** [comment]
You can download the wheel on another machine and copy it over, `python -m pip download . . .`, or just go to pypa to download the wheel. Then install with `--user`.

**Comment by alicezanella** [comment]
Thank you, I'll try!

**Comment by rgommers** [comment]
Problem seems resolved and there's nothing to fix in NumPy, so I'll close this.
