### ISSUE TITLE
numpy 1.21 generates issue with importing xarray

### ISSUE THREAD

**Issue by TiemoMathijssen** [numpy/numpy#19310]
After installing numpy v1.21, I have a problem importing xarray 0.18.2 in python3.7.9. This problem does not occur using numpy v1.20.3.

### Steps to reproduce:
Numpy and xarray libraries are installed using pip3 install

### Error message:
Python 3.7.9 (default, Apr 30 2021, 20:11:56)
[GCC 7.3.1 20180712 (Red Hat 7.3.1-12)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import xarray
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rainbow/.local/lib/python3.7/site-packages/xarray/__init__.py", line 3, in <module>
    from . import testing, tutorial, ufuncs
  File "/home/rainbow/.local/lib/python3.7/site-packages/xarray/testing.py", line 8, in <module>
    from xarray.core import duck_array_ops, formatting, utils
  File "/home/rainbow/.local/lib/python3.7/site-packages/xarray/core/duck_array_ops.py", line 16, in <module>
    from . import dask_array_compat, dask_array_ops, dtypes, npcompat, nputils
  File "/home/rainbow/.local/lib/python3.7/site-packages/xarray/core/npcompat.py", line 81, in <module>
    from numpy.typing import ArrayLike, DTypeLike
  File "/home/rainbow/.local/lib/python3.7/site-packages/numpy/typing/__init__.py", line 315, in <module>
    from ._shape import _Shape, _ShapeLike
  File "/home/rainbow/.local/lib/python3.7/site-packages/numpy/typing/_shape.py", line 15, in <module>
    _ShapeLike = Union[SupportsIndex, Sequence[SupportsIndex]]
  File "/usr/lib64/python3.7/typing.py", line 254, in inner
    return func(*args, **kwds)
  File "/usr/lib64/python3.7/typing.py", line 634, in __getitem__
    params = tuple(_type_check(p, msg) for p in params)
  File "/usr/lib64/python3.7/typing.py", line 634, in <genexpr>
    params = tuple(_type_check(p, msg) for p in params)
  File "/usr/lib64/python3.7/typing.py", line 142, in _type_check
    raise TypeError(f"{msg} Got {arg!r:.100}.")
TypeError: Parameters to generic types must be types. Got NotImplemented.

**Comment by BvB93** [comment]
Hi @TiemoMathijssen,
A fix for the issue is currently up at https://github.com/numpy/numpy/pull/19311 and should be in the next release.

In the meantime there two possible ways of remedying the situation:
* Upgrade to python 3.8.
* Install [`typing-extensions`](https://pypi.org/project/typing-extensions/).

**Comment by BvB93** [comment]
Not sure why this wasn't automatically closed by merging the linked PR.
In any case, closed by https://github.com/numpy/numpy/pull/19311.
