### ISSUE TITLE
dtype is not defined when using ArrayLike with get_type_hints

### ISSUE THREAD

**Issue by thewtex** [numpy/numpy#19327]
`dtype` is not defined when using `numpy.typing.ArrayLike` with `typing.get_type_hints` and `numpy==1.21.0`.
### Reproducing code example:

```python
from typing import get_type_hints

import numpy as np

from numpy.typing import ArrayLike

def give_me_an_array(array: ArrayLike):
    pass

type_hints = get_type_hints(give_me_an_array)
```

### Error message:

```
Traceback (most recent call last):
  File "/tmp/test.py", line 10, in <module>
    type_hints = get_type_hints(gimme_an_array)
  File "/home/matt/bin/miniconda/envs/numpy/lib/python3.8/typing.py", line 1264, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "/home/matt/bin/miniconda/envs/numpy/lib/python3.8/typing.py", line 272, in _eval_type
    ev_args = tuple(_eval_type(a, globalns, localns) for a in t.__args__)
  File "/home/matt/bin/miniconda/envs/numpy/lib/python3.8/typing.py", line 272, in <genexpr>
    ev_args = tuple(_eval_type(a, globalns, localns) for a in t.__args__)
  File "/home/matt/bin/miniconda/envs/numpy/lib/python3.8/typing.py", line 272, in _eval_type
    ev_args = tuple(_eval_type(a, globalns, localns) for a in t.__args__)
  File "/home/matt/bin/miniconda/envs/numpy/lib/python3.8/typing.py", line 272, in <genexpr>
    ev_args = tuple(_eval_type(a, globalns, localns) for a in t.__args__)
  File "/home/matt/bin/miniconda/envs/numpy/lib/python3.8/typing.py", line 270, in _eval_type
    return t._evaluate(globalns, localns)
  File "/home/matt/bin/miniconda/envs/numpy/lib/python3.8/typing.py", line 518, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'dtype' is not defined
```

### NumPy/Python version information:

This occurs with numpy 1.21.0. It did not occur with 1.20.3 or previous versions.

**Comment by BvB93** [comment]
So this is admittedly a rather annoying issue that highlights some serious limitations of `typing.get_type_hints`.

`dtype` is currently expressed as a string in the relevant union, which is fine for static type checking, but means 
that you'll have to passed the stringified objects via either `globals` or `locals`. Except that this simply introduces 
a new issue as `dtype` is not subscriptable during runtime, so you'll get a `TypeError` and are back to square one.

https://github.com/numpy/numpy/blob/9b192570661d55575606f2a77a7bc9e280120f5c/numpy/typing/_array_like.py#L73-L79

In any case, I've just created https://github.com/numpy/numpy/pull/19328 which will resolve the issue once it's backported for 1.21.1.

**Comment by thewtex** [comment]
@BvB93 thank you!! 🙏
