### ISSUE TITLE
np.sum throws an exception with Python 3.9.5

### ISSUE THREAD

**Issue by DLumi** [numpy/numpy#19335]
The function in numpy 1.19.5 doesn't work correctly on Python 3.9.5, though when I switch the project's interpreter to Python 3.7.10, everything works as usual. 
The issue only seems to appear on these exact versions, as I tested it on Python 3.7.10 with 1.19.2, 1.19.5, 1.21.0, and on Python 3.9.5 with 1.19.2, 1.21.0 and it's all good there. 

### Reproducing code example:

```python
import numpy as np

x = np.asarray([[311., 20.], [425., 20.], [425., 51.], [311., 51.]])
print(x.sum(axis=1, dtype=np.float32))
```

### Error message:

```
Traceback (most recent call last):
  File "W:\myuser\TrainingAndTests\test.py", line 260, in <module>
    print(x.sum(axis=1, dtype=np.float32))
  File "C:\Miniconda3\envs\ML\lib\site-packages\numpy\core\_methods.py", line 47, in _sum
    return umr_sum(a, axis, dtype, out, keepdims, initial, where)
TypeError: float() argument must be a string or a number, not '_NoValueType'
```
### NumPy/Python version information:

1.19.5 3.9.5 (default, May 18 2021, 14:42:02) [MSC v.1916 64 bit (AMD64)]

**Comment by matthew-brett** [comment]
I don't get this error with Python 3.9.5 and Numpy 1.19.5 on Mac (Homebrew Python) or Windows (Python.org Python via Chocolately).   Could this be a Conda packaging issue?

**Comment by DLumi** [comment]
> I don't get this error with Python 3.9.5 and Numpy 1.19.5 on Mac (Homebrew Python) or Windows (Python.org Python via Chocolately). Could this be a Conda packaging issue?

It could be, but I can't tell for sure. All I know is that any other version worked okay, but not this one for some reason.

**Comment by matthew-brett** [comment]
How did you install Numpy?   Did you already trying uninstalling and reinstalling Numpy?

**Comment by matthew-brett** [comment]
I can't replicate this error on a new conda environment, with Numpy 1.19.5 installed from conda-forge (it's not available on the default channels).  I have the exact same Python as you do.

**Comment by seberg** [comment]
Could it be that you somehow managed to have two NumPy versions colliding.  Or maybe a re-import of NumPy.  One way this error could possibly be explained is if `_NoValue` is not actually a singleton anymore, but there are two different `_NoValue` singletons in the process, so that the identity check `initial is _NoValue` fails.

If that is the case, you could test this, by passing `initial=0`.  But not sure how to help you to track down where the problem originates at.

**Comment by melissawm** [comment]
I am closing this for lack of activity and information to reproduce the issue. Feel free to reopen if the issue persists. Thanks!
