### ISSUE TITLE
TypeError("str expected, not %s" % type(value).__name__) TypeError: str expected, not tuple When install on windows 

### ISSUE THREAD

**Issue by Debbiepimpo** [numpy/numpy#19377]
Not sure that this issue is related to PyMySQL.
When I try to install PyMySQL with Pipenv, it fails with a TypeError exception.
This issue doesn't seem to happen if using pip directly.
### Reproducing code example:

I can´t reporduce but is similar to this bug: https://github.com/numpy/numpy/issues/17987

### Error message:

dperalta@MAD-DPERALTA MINGW64 ~/Desktop/GitHub/excelToMysql (master)
$ c:/Users/DPERALTA/Desktop/GitHub/excelToMysql/.venv/Scripts/python.exe c:/Users/DPERALTA/Desktop/GitHub/excelToMysql/excel-to-sql.py
Traceback (most recent call last):
  File "c:\Users\DPERALTA\Desktop\GitHub\excelToMysql\excel-to-sql.py", line 4, in <module>
    import env
  File "c:\Users\DPERALTA\Desktop\GitHub\excelToMysql\env.py", line 3, in <module>
    os.environ['MY_DATABASE_HOST'] = '127.00.000.000',
  File "C:\Users\DPERALTA\AppData\Local\Programs\Python\Python39\lib\os.py", line 684, in __setitem__
    value = self.encodevalue(value)
  File "C:\Users\DPERALTA\AppData\Local\Programs\Python\Python39\lib\os.py", line 742, in check_str
    raise TypeError("str expected, not %s" % type(value).__name__)
TypeError: str expected, not tuple

**Comment by Deuchnord** [comment]
Your issue seems to be related to the PyMySQL package, but this is the repository of NumPy.
You may want to report this issue on https://github.com/PyMySQL/PyMySQL/issues instead.
