### ISSUE TITLE
set_printoptions fails when provided with ouput of get_printoptions

### ISSUE THREAD

**Issue by jlmeunier** [numpy/numpy#19636]
### Reproducing code example:

```python
import numpy as np
print(np.__version__)
o = np.get_printoptions()
print(o)
np.set_printoptions(8)
np.set_printoptions(o)
```
### Error message:

```
1.21.1
{'edgeitems': 3, 'threshold': 1000, 'floatmode': 'maxprec', 'precision': 8, 'suppress': False, 'linewidth': 75, 'nanstr': 'nan', 'infstr': 'inf', 'sign': '-', 'formatter': None, 'legacy': False}
Traceback (most recent call last):
  File "/tmp-network/user/meunier/VIRTUALENV39_pyg/lib/python3.9/site-packages/numpy/core/arrayprint.py", line 94, in _make_options_dict
    options['precision'] = operator.index(precision)
TypeError: 'dict' object cannot be interpreted as an integer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmp-network/user/meunier/gommettes/np_issue.py", line 6, in <module>
    np.set_printoptions(o)
  File "/tmp-network/user/meunier/VIRTUALENV39_pyg/lib/python3.9/site-packages/numpy/core/arrayprint.py", line 252, in set_printoptions
    opt = _make_options_dict(precision, threshold, edgeitems, linewidth,
  File "/tmp-network/user/meunier/VIRTUALENV39_pyg/lib/python3.9/site-packages/numpy/core/arrayprint.py", line 96, in _make_options_dict
    raise TypeError('precision must be an integer') from e
TypeError: precision must be an integer
```
### NumPy/Python version information:

1.21.1 3.9.4 (default, Apr  7 2021, 12:46:00) 
[GCC 9.3.1 20200408 (Red Hat 9.3.1-2)]

**Comment by eric-wieser** [comment]
You should use `np.set_printoptions(**o)` not `np.set_printoptions(o)`.

Would you like to contribute an example to the documentation for `get_printoptions`?

**Comment by jlmeunier** [comment]
oups!
so sorry to have bothered you with this!
Since my code was ok in previous version of numpy (how possible BTW??) I did not think to check the doc.
I would be happy to contribute, but the doc is crystal clear, I must say.
Thank you for the work and sorry again.
