### ISSUE TITLE
take_along_axis alternative implementation doesn't match real implementation

### ISSUE THREAD

**Issue by itamarst** [numpy/numpy#19704]
In the documentation for `np.take_along_axis()`, an alternative implementation is provided: https://github.com/numpy/numpy/blob/623bc1fae1d47df24e7f1e29321d0c0ba2771ce0/numpy/lib/shape_base.py#L90

I am using this alternative implementation to implement a first pass of `take_along_axis()` in Numba.

Turns out, however, that in some cases the output between the two doesn't match.

### Reproducing code example:

```python
import numpy as np
from numpy import ndindex, s_

def take_along_axis_2(a, indices, axis):
    # This is the alternative implementation from the NumPy docs ("Notes" section):
    # https://numpy.org/doc/stable/reference/generated/numpy.take_along_axis.html
    Ni, M, Nk = a.shape[:axis], a.shape[axis], a.shape[axis+1:]
    J = indices.shape[axis]  # Need not equal M
    out = np.empty(Ni + (J,) + Nk)

    for ii in ndindex(Ni):
        for kk in ndindex(Nk):
            a_1d       = a      [ii + s_[:,] + kk]
            indices_1d = indices[ii + s_[:,] + kk]
            out_1d     = out    [ii + s_[:,] + kk]
            for j in range(J):
                out_1d[j] = a_1d[indices_1d[j]]
    return out_1d

# Based on https://github.com/numpy/numpy/blob/v1.21.0/numpy/lib/tests/test_shape_base.py#L74-L79
arr  = np.ones((3, 4, 1))
ai = np.ones((1, 2, 5), dtype=np.intp)

actual = np.take_along_axis(arr, ai, axis=1)
print("np.take_along_axis() returned array of shape", actual.shape)
alternative = take_along_axis_2(arr, ai, axis=1)
print("Alternative take_along_axis() returned array of shape", alternative.shape)
assert actual == alternative
```

### Error message:

```shell-session
$ python example2.py 
np.take_along_axis() returned array of shape (3, 2, 5)
Traceback (most recent call last):
  File "example2.py", line 26, in <module>
    alternative = take_along_axis_2(arr, ai, axis=1)
  File "example2.py", line 14, in take_along_axis_2
    indices_1d = indices[ii + s_[:,] + kk]
IndexError: index 1 is out of bounds for axis 0 with size 1
```

### NumPy/Python version information:

Python 3.8, NumPy 1.20.2.

**Comment by eric-wieser** [comment]
You're right, the sample implementation assumes that no broadcasting occurs.

**Comment by itamarst** [comment]
Any hints on how to expand it so broadcasting works? My mental model of all of these operations is very weak, so while I'm sure I can figure it out eventually, probably a lot faster for someone who has it all down intuitively.

**Comment by eric-wieser** [comment]
I can't give you an implementation because the numpy python API is very weak when it comes to providing broadcasting primitives, but the rule is "broadcast all the dimensions of `a` and `indices` except `axis` before running that loop"

**Comment by itamarst** [comment]
Thank you!

**Comment by itamarst** [comment]
Had to slightly tweak the above, changing one line:

```python
arr = np.broadcast_to(arr, shape[:axis] + (arr.shape[axis],) + shape[axis+1:])
```

**Comment by itamarst** [comment]
Here is a self-contained version that does work, for this example at least, haven't tested it with other inputs:

```python
import numpy as np
from numpy import ndindex, s_

def take_along_axis_2(a, indices, axis):
    arr_axes = list(range(a.ndim))
    index_axes = arr_axes[:]
    arr_axes[axis] = None
    shape = np.nditer([a, indices], op_axes=[arr_axes, index_axes], flags=['multi_index']).shape

    # broadcast the arrays
    a = np.broadcast_to(a, shape[:axis] + (a.shape[axis],) + shape[axis+1:])
    indices = np.broadcast_to(indices, shape)

    # This is the alternative implementation from the NumPy docs ("Notes" section):
    # https://numpy.org/doc/stable/reference/generated/numpy.take_along_axis.html
    Ni, M, Nk = a.shape[:axis], a.shape[axis], a.shape[axis+1:]
    J = indices.shape[axis]  # Need not equal M
    out = np.empty(Ni + (J,) + Nk)

    for ii in ndindex(Ni):
        for kk in ndindex(Nk):
            a_1d       = a      [ii + s_[:,] + kk]
            indices_1d = indices[ii + s_[:,] + kk]
            out_1d     = out    [ii + s_[:,] + kk]
            for j in range(J):
                out_1d[j] = a_1d[indices_1d[j]]
    return out

# Based on https://github.com/numpy/numpy/blob/v1.21.0/numpy/lib/tests/test_shape_base.py#L74-L79
_arr  = np.ones((3, 4, 1))
_ai = np.ones((1, 2, 5), dtype=np.intp)

actual = np.take_along_axis(_arr, _ai, axis=1)
variant = take_along_axis_2(_arr, _ai, axis=1)
print(actual.shape, variant.shape)
assert np.array_equal(actual, variant)
```

**Comment by itamarst** [comment]
Here's another approach which is... maybe equivalent? And doesn't require `nditer()`:

```python
    arr_shape = list(a.shape)
    arr_shape[axis] = 1
    shape = []
    for d1, d2 in zip(arr_shape, indices.shape):
        if d1 == 1:
            shape.append(d2)
        elif d2 == 1:
            shape.append(d1)
        else:
            assert d1 == d2
            shape.append(d1)
    shape = tuple(shape)

    # broadcast the arrays
    a = np.broadcast_to(a, shape[:axis] + (a.shape[axis],) + shape[axis+1:])
    indices = np.broadcast_to(indices, shape)
```
