### ISSUE TITLE
pymeep numpy import issue

### ISSUE THREAD

**Issue by gyf12138** [numpy/numpy#19729]
I'm using latest version Anaconda 3 (python version 3.9.6)

I install the library "pymeep" and got import error as following output:

###
(mp) gyf@gyf-virtual-machine:~$ python
Python 3.9.6 | packaged by conda-forge | (default, Jul 11 2021, 03:39:48) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import meep as mp 
Traceback (most recent call last):
  File "/home/gyf/anaconda3/envs/mp/lib/python3.9/site-packages/numpy/__init__.py", line 153, in <module>
    from . import lib
  File "/home/gyf/anaconda3/envs/mp/lib/python3.9/site-packages/numpy/lib/__init__.py", line 37, in <module>
    from .npyio import *
  File "/home/gyf/anaconda3/envs/mp/lib/python3.9/site-packages/numpy/lib/npyio.py", line 7, in <module>
    import weakref
  File "/home/gyf/weakref.py", line 2, in <module>
    from meep.materials import fused_quartz
  File "/home/gyf/anaconda3/envs/mp/lib/python3.9/site-packages/meep/materials.py", line 18, in <module>
    cSi_range = mp.FreqRange(min=um_scale, max=um_scale/0.4)
AttributeError: partially initialized module 'meep' has no attribute 'FreqRange' (most likely due to a circular import)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gyf/anaconda3/envs/mp/lib/python3.9/site-packages/meep/__init__.py", line 13, in <module>
    from . import _meep
ImportError: numpy.core.multiarray failed to import
###

Then I try to import `numpy.core.multiarray` manully. Still got error:

###
>>> import numpy.core.multiarray 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gyf/anaconda3/envs/mp/lib/python3.9/site-packages/numpy/__init__.py", line 153, in <module>
    from . import lib
  File "/home/gyf/anaconda3/envs/mp/lib/python3.9/site-packages/numpy/lib/__init__.py", line 37, in <module>
    from .npyio import *
  File "/home/gyf/anaconda3/envs/mp/lib/python3.9/site-packages/numpy/lib/npyio.py", line 7, in <module>
    import weakref
  File "/home/gyf/weakref.py", line 1, in <module>
    import meep as meep
  File "/home/gyf/anaconda3/envs/mp/lib/python3.9/site-packages/meep/__init__.py", line 3919, in <module>
    from .geom import (
  File "/home/gyf/anaconda3/envs/mp/lib/python3.9/site-packages/meep/geom.py", line 10, in <module>
    from copy import deepcopy
  File "/home/gyf/anaconda3/envs/mp/lib/python3.9/copy.py", line 112, in <module>
    types.FunctionType, weakref.ref):
AttributeError: partially initialized module 'weakref' has no attribute 'ref' (most likely due to a circular import)

###

**Comment by mattip** [comment]
Please rename `/home/gyf/weakref.py`, it conflicts with the Python-supplied `weakref.py` module.

**Comment by srijit2021** [comment]
import math
import numpy as np
import meep as mp
from meep import mpb


geometry_lattice = mp.Lattice(size=mp.Vector3(1, 1),
                              basis1=mp.Vector3(math.sqrt(3) / 2, 0.5),
                              basis2=mp.Vector3(math.sqrt(3) / 2, -0.5))
geometry = [mp.Cylinder(0.2, material=mp.Medium(epsilon=12))]
k_points = [
    mp.Vector3(),               # Gamma
    mp.Vector3(y=0.5),          # M
]

ms = mpb.ModeSolver(
    geometry=geometry,
    geometry_lattice=geometry_lattice,
    k_points=k_points)

ms.run_te()

**Comment by seberg** [comment]
Closing, the problem here is the local name clash with pythons builtin `weakref` as Matti pointed out. I hope you were able to figure it out @srijit2021?
