### ISSUE TITLE
Unable to build for Flatpak

### ISSUE THREAD

**Issue by rivanfebrian123** [numpy/numpy#19737]
```
Creating directory “/home/rivanfebrian123/.cache/gnome-builder/projects/Clusterify-master/flatpak/repo”
Creating directory “/home/rivanfebrian123/.cache/gnome-builder/projects/Clusterify-master/flatpak/staging/x86_64-unversioned”
flatpak build-init --arch=x86_64 /home/rivanfebrian123/.cache/gnome-builder/projects/Clusterify-master/flatpak/staging/x86_64-unversioned org.gnome.Clusterify org.gnome.Sdk org.gnome.Platform 40
flatpak-builder --arch=x86_64 --ccache --force-clean --state-dir /home/rivanfebrian123/.cache/gnome-builder/flatpak-builder --download-only --disable-updates --stop-at=clusterify /home/rivanfebrian123/.cache/gnome-builder/projects/Clusterify-master/flatpak/staging/x86_64-unversioned /home/rivanfebrian123/Downloads/Clusterify-master/org.gnome.Clusterify.json
Emptying app dir '/home/rivanfebrian123/.cache/gnome-builder/projects/Clusterify-master/flatpak/staging/x86_64-unversioned'
Downloading sources
Downloading https://files.pythonhosted.org/packages/3a/be/650f9c091ef71cb01d735775d554e068752d3ff63d7943b26316dc401749/numpy-1.21.2.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  9.7M  100  9.7M    0     0   245k      0  0:00:40  0:00:40 --:--:--  223k
Stopping at module clusterify
flatpak-builder --arch=x86_64 --ccache --force-clean --disable-updates --disable-download --state-dir /home/rivanfebrian123/.cache/gnome-builder/flatpak-builder --stop-at=clusterify /home/rivanfebrian123/.cache/gnome-builder/projects/Clusterify-master/flatpak/staging/x86_64-unversioned /home/rivanfebrian123/Downloads/Clusterify-master/org.gnome.Clusterify.json
Initializing build dir
Committing stage init to cache
Starting build of org.gnome.Clusterify
========================================================================
Building module python3-numpy in /home/rivanfebrian123/.cache/gnome-builder/flatpak-builder/build/python3-numpy-1
========================================================================
Running: pip3 install --verbose --exists-action=i --no-index --find-links="file://${PWD}" --prefix=${FLATPAK_DEST} "numpy" --no-build-isolation
Using pip 21.0.1 from /usr/lib/python3.8/site-packages/pip (python 3.8)
Non-user install due to --prefix or --target option
Ignoring indexes: https://pypi.org/simple
Created temporary directory: /tmp/pip-ephem-wheel-cache-ttdrl_wf
Created temporary directory: /tmp/pip-req-tracker-pd55332d
Initialized build tracking at /tmp/pip-req-tracker-pd55332d
Created build tracker: /tmp/pip-req-tracker-pd55332d
Entered build tracker: /tmp/pip-req-tracker-pd55332d
Created temporary directory: /tmp/pip-install-4aj1xri3
Looking in links: file:///run/build/python3-numpy
0 location(s) to search for versions of numpy:
Skipping link: not a file: file:///run/build/python3-numpy (from -f)
Found link file:///run/build/python3-numpy/numpy-1.21.2.zip, version: 1.21.2
Local files found: /run/build/python3-numpy/numpy-1.21.2.zip
Given no hashes to check 1 links for project 'numpy': discarding no candidates
Processing ./numpy-1.21.2.zip
  Added numpy from file:///run/build/python3-numpy/numpy-1.21.2.zip to build tracker '/tmp/pip-req-tracker-pd55332d'
    Created temporary directory: /tmp/pip-modern-metadata-fesvitz4
    Running command /usr/bin/python3 /usr/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmp1pag47ee
    running dist_info
    running build_src
    build_src
    creating /tmp/pip-modern-metadata-fesvitz4/numpy.egg-info
    writing /tmp/pip-modern-metadata-fesvitz4/numpy.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-modern-metadata-fesvitz4/numpy.egg-info/dependency_links.txt
    writing entry points to /tmp/pip-modern-metadata-fesvitz4/numpy.egg-info/entry_points.txt
    writing top-level names to /tmp/pip-modern-metadata-fesvitz4/numpy.egg-info/top_level.txt
    writing manifest file '/tmp/pip-modern-metadata-fesvitz4/numpy.egg-info/SOURCES.txt'
    reading manifest file '/tmp/pip-modern-metadata-fesvitz4/numpy.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files found matching 'LICENSES_bundled.txt'
    warning: no previously-included files found matching 'azure-*.yml'
    no previously-included directories found matching 'doc/build'
    no previously-included directories found matching 'doc/source/generated'
    no previously-included directories found matching 'benchmarks/env'
    no previously-included directories found matching 'benchmarks/results'
    no previously-included directories found matching 'benchmarks/html'
    no previously-included directories found matching 'benchmarks/numpy'
    warning: no previously-included files matching '*.pyo' found anywhere in distribution
    warning: no previously-included files matching '*.pyd' found anywhere in distribution
    warning: no previously-included files matching '*.swp' found anywhere in distribution
    warning: no previously-included files matching '*.bak' found anywhere in distribution
    warning: no previously-included files matching '*~' found anywhere in distribution
    writing manifest file '/tmp/pip-modern-metadata-fesvitz4/numpy.egg-info/SOURCES.txt'
    creating '/tmp/pip-modern-metadata-fesvitz4/numpy.dist-info'
    adding license file "LICENSE.txt" (matched pattern "LICEN[CS]E*")
    Running from numpy source directory.
    Preparing wheel metadata ... done
  Source in /tmp/pip-install-4aj1xri3/numpy_38f7fd83b2224dc2872873e009d6e3d5 has version 1.21.2, which satisfies requirement numpy from file:///run/build/python3-numpy/numpy-1.21.2.zip
  Removed numpy from file:///run/build/python3-numpy/numpy-1.21.2.zip from build tracker '/tmp/pip-req-tracker-pd55332d'
Created temporary directory: /tmp/pip-unpack-sta2spes
Building wheels for collected packages: numpy
  Created temporary directory: /tmp/pip-wheel-3z2ngzhs
  Destination directory: /tmp/pip-wheel-3z2ngzhs
  Running command /usr/bin/python3 /usr/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmpkz94iohn
  Processing numpy/random/_bounded_integers.pxd.in
  Processing numpy/random/mtrand.pyx
  Traceback (most recent call last):
    File "/tmp/pip-install-4aj1xri3/numpy_38f7fd83b2224dc2872873e009d6e3d5/tools/cythonize.py", line 240, in <module>
      main()
    File "/tmp/pip-install-4aj1xri3/numpy_38f7fd83b2224dc2872873e009d6e3d5/tools/cythonize.py", line 236, in main
      find_process_files(root_dir)
    File "/tmp/pip-install-4aj1xri3/numpy_38f7fd83b2224dc2872873e009d6e3d5/tools/cythonize.py", line 227, in find_process_files
      process(root_dir, fromfile, tofile, function, hash_db)
    File "/tmp/pip-install-4aj1xri3/numpy_38f7fd83b2224dc2872873e009d6e3d5/tools/cythonize.py", line 193, in process
      processor_function(fromfile, tofile)
    File "/tmp/pip-install-4aj1xri3/numpy_38f7fd83b2224dc2872873e009d6e3d5/tools/cythonize.py", line 80, in process_pyx
      raise RuntimeError(f'Building {VENDOR} requires Cython >= {required_version}'
  RuntimeError: Building NumPy requires Cython >= 0.29.24, found 0.29.23 at /usr/lib/python3.8/site-packages/Cython/__init__.py
  Running from numpy source directory.
  Cythonizing sources
  Traceback (most recent call last):
    File "/usr/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/usr/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/usr/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 204, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/usr/lib/python3.8/site-packages/setuptools/build_meta.py", line 216, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "/usr/lib/python3.8/site-packages/setuptools/build_meta.py", line 202, in _build_with_temp_dir
      self.run_setup()
    File "/usr/lib/python3.8/site-packages/setuptools/build_meta.py", line 253, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/usr/lib/python3.8/site-packages/setuptools/build_meta.py", line 145, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 448, in <module>
      setup_package()
    File "setup.py", line 430, in setup_package
      generate_cython()
    File "setup.py", line 236, in generate_cython
      raise RuntimeError("Running cythonize failed!")
  RuntimeError: Running cythonize failed!
  Building wheel for numpy (PEP 517) ... error
  ERROR: Failed building wheel for numpy
Failed to build numpy
ERROR: Could not build wheels for numpy which use PEP 517 and cannot be installed directly
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 189, in _main
    status = self.run(options, args)
  File "/usr/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 178, in wrapper
    return func(self, options, args)
  File "/usr/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 358, in run
    raise InstallationError(
pip._internal.exceptions.InstallationError: Could not build wheels for numpy which use PEP 517 and cannot be installed directly
Removed build tracker: '/tmp/pip-req-tracker-pd55332d'
Error: module python3-numpy: Child process exited with code 1
```
### NumPy/Python version information:
```
Python 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys, numpy; print(numpy.__version__, sys.version)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy'
>>> import sys; print(sys.version)
3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0]
>>> 
```
I'm on a clean Ubuntu VM

**Comment by rkern** [comment]
This is the relevant error message:

```
 RuntimeError: Building NumPy requires Cython >= 0.29.24, found 0.29.23 at /usr/lib/python3.8/site-packages/Cython/__init__.py
```

**Comment by seberg** [comment]
Sounds like the Cython version should have been the issue.  Closing, if there is another problem, please open a new issue.

**Comment by rivanfebrian123** [comment]
I think Numpy's requirement is far too high that even the latest distro repo doesn't provide it yet

**Comment by seberg** [comment]
I am not sure I understand why this is a particularly big issue, you should be able to upgrade to a newer cython even if you do it only for the install itself?  And it is only a build time dependency.  There are typically pretty good reasons why we use an up-to date cython.  For example because it is necessary for newer Python versions.

**Comment by rivanfebrian123** [comment]
> I am not sure I understand why this is a particularly big issue

Oh, I'm sorry if I sounded mean. Actually, it's just not cost-efficient when it comes to CI/CD, but that's not a big deal. I can come around by using the older version of Numpy

**Comment by seberg** [comment]
@rivanfebrian123 not sure it applies for you, but if you would like a dev-version of NumPy to test with, we do also provide wheels roughly bi-weekly: https://anaconda.org/scipy-wheels-nightly/numpy

**Comment by rivanfebrian123** [comment]
Oh, thanks!
