### ISSUE TITLE
Add default value for degree in np.polyfit function

### ISSUE THREAD

**Issue by malay5** [numpy/numpy#19771]
### Reproducing code example:

```python
import numpy as np
np.polyfit([1,2],[1,2])
```

### Error message:

Traceback (most recent call last):

  File "D:\untitled4.py", line 10, in <module>
    np.polyfit([1,2,3],[1,2])

  File "<__array_function__ internals>", line 4, in polyfit

TypeError: _polyfit_dispatcher() missing 1 required positional argument: 'deg'
### NumPy/Python version information:

**Output from 'import sys, numpy; print(numpy.__version__, sys.version)**

1.20.1 3.8.8 (default, Apr 13 2021, 15:08:03) [MSC v.1916 64 bit (AMD64)]

**Comment by malay5** [comment]
Please assign this issue to me

**Comment by malay5** [comment]
The issue is resolved

**Comment by malay5** [comment]
Sorry, it was mistakenly closed. The PR has not been merged. Sorry for confusion.
