### ISSUE TITLE
`np.take` raises a TypeError on Raspberry Pi

### ISSUE THREAD

**Issue by ishiy1993** [numpy/numpy#19985]
When the second parameter `indices` of `np.take` has `np.int64` type, it raises a TypeError on Raspberry Pi.
It works on x86.

Is there a workaround which enable me to use `np.take` with `np.int64` on Raspberry Pi?

### Reproducing code example:

`check_take.py`:

```py
import numpy as np

print(f'numpy version: {np.version.version} ({np.version.git_revision})')

a = np.array([4, 3, 5, 7, 6, 8]).astype(np.float32)

# It works on both x86 and raspi.
idx0 = np.array([0, 1, 4]).astype(np.int32)
print(np.take(a, idx0))

# It works on x86, but not work on raspi.
idx1 = np.array([0, 1, 4]).astype(np.int64)
print(np.take(a, idx1))
```

### Error message:

x86:

```
$ python3 --version
Python 3.8.9
$ python3 check_take.py
numpy version: 1.21.2 (2fe48d2d98a85c8ea3f3d5caffd952ea69e99335)
[4. 3. 6.]
[4. 3. 6.]
```

raspi4b:

```
$ python3 --version
Python 3.7.3
$ python3 check_take.py
numpy version: 1.21.2 (2fe48d2d98a85c8ea3f3d5caffd952ea69e99335)
[4. 3. 6.]
Traceback (most recent call last):
  File "/home/pi/venv/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 57, in _wrapfunc
    return bound(*args, **kwds)
TypeError: Cannot cast array data from dtype('int64') to dtype('int32') according to the rule 'safe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "check_take.py", line 13, in <module>
    print(np.take(a, idx1))
  File "<__array_function__ internals>", line 6, in take
  File "/home/pi/venv/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 190, in take
    return _wrapfunc(a, 'take', indices, axis=axis, out=out, mode=mode)
  File "/home/pi/venv/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 66, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/home/pi/venv/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 43, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
TypeError: Cannot cast array data from dtype('int64') to dtype('int32') according to the rule 'safe'
```

**Comment by seberg** [comment]
The workaround is to use `np.intp` which is int32 if your system is 32 bits.  I am a bit surprised raspberry pi is 32bit.  The fix is probably to modify the cast to `same-kind` which is in principle unsafe, but it is unlikely to ever get indices larger than 31bits, especially if the system cannot have such arrays to begin with.

**Comment by ishiy1993** [comment]
Thank you for the workaround.
