### ISSUE TITLE
BUG: Failed building wheel for numpy in Python 3.10

### ISSUE THREAD

**Issue by PedroMVM** [numpy/numpy#20039]
### Describe the issue:

I have download the new Python 3.10 and tried to run some code.
When trying to update numpy, the following message appears:
`Failed to build numpy`
`ERROR: Could not build wheels for numpy which use PEP 517 and cannot be installed directly`
I have also done a search for a similar bug report and I found out that it was happening since Python 3.9:
https://github.com/numpy/numpy/issues/17569

### Reproduce the code example:

```python
pip install -U numpy
```

### Error message:

```shell
Building wheels for collected packages: numpy
  Building wheel for numpy (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Python\python.exe' 'C:\Python\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' build_wheel 'C:\Users\pmarti6\AppData\Local\Temp\tmp8ja2dcq8'
       cwd: C:\Users\pmarti6\AppData\Local\Temp\pip-install-7dhp40t4\numpy_70d258ac961c4e09a9254ad60e4e51ac
  Complete output (262 lines):
  setup.py:63: RuntimeWarning: NumPy 1.21.2 may not yet support Python 3.10.
    warnings.warn(
  Running from numpy source directory.
  C:\Users\pmarti6\AppData\Local\Temp\pip-install-7dhp40t4\numpy_70d258ac961c4e09a9254ad60e4e51ac\tools\cythonize.py:69: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
    from distutils.version import LooseVersion
  Processing numpy/random\_bounded_integers.pxd.in
  Processing numpy/random\bit_generator.pyx
  Processing numpy/random\mtrand.pyx
  Processing numpy/random\_bounded_integers.pyx.in
  Processing numpy/random\_common.pyx
  Processing numpy/random\_generator.pyx
  Processing numpy/random\_mt19937.pyx
  Processing numpy/random\_pcg64.pyx
  Processing numpy/random\_philox.pyx
  Processing numpy/random\_sfc64.pyx
  Cythonizing sources
  blas_opt_info:
  blas_mkl_info:
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries mkl_rt not found in ['C:\\Python\\lib', 'C:\\', 'C:\\Python\\libs']
    NOT AVAILABLE

  blis_info:
    libraries blis not found in ['C:\\Python\\lib', 'C:\\', 'C:\\Python\\libs']
    NOT AVAILABLE

  openblas_info:
    libraries openblas not found in ['C:\\Python\\lib', 'C:\\', 'C:\\Python\\libs']
  get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv', 'intelev', 'gnu95', 'g95', 'intelvem', 'intelem', 'flang']'
  customize GnuFCompiler
  Could not locate executable g77
  Could not locate executable f77
  customize IntelVisualFCompiler
  Could not locate executable ifort
  Could not locate executable ifl
  customize AbsoftFCompiler
  Could not locate executable f90
  customize CompaqVisualFCompiler
  Could not locate executable DF
  customize IntelItaniumVisualFCompiler
  Could not locate executable efl
  customize Gnu95FCompiler
  Could not locate executable gfortran
  Could not locate executable f95
  customize G95FCompiler
  Could not locate executable g95
  customize IntelEM64VisualFCompiler
  customize IntelEM64TFCompiler
  Could not locate executable efort
  Could not locate executable efc
  customize PGroupFlangCompiler
  Could not locate executable flang
  don't know how to compile Fortran code on platform 'nt'
    NOT AVAILABLE

  accelerate_info:
    NOT AVAILABLE

  atlas_3_10_blas_threads_info:
  Setting PTATLAS=ATLAS
    libraries tatlas not found in ['C:\\Python\\lib', 'C:\\', 'C:\\Python\\libs']
    NOT AVAILABLE

  atlas_3_10_blas_info:
    libraries satlas not found in ['C:\\Python\\lib', 'C:\\', 'C:\\Python\\libs']
    NOT AVAILABLE

  atlas_blas_threads_info:
  Setting PTATLAS=ATLAS
    libraries ptf77blas,ptcblas,atlas not found in ['C:\\Python\\lib', 'C:\\', 'C:\\Python\\libs']
    NOT AVAILABLE

  atlas_blas_info:
    libraries f77blas,cblas,atlas not found in ['C:\\Python\\lib', 'C:\\', 'C:\\Python\\libs']
    NOT AVAILABLE

  C:\Users\pmarti6\AppData\Local\Temp\pip-install-7dhp40t4\numpy_70d258ac961c4e09a9254ad60e4e51ac\numpy\distutils\system_info.py:2026: UserWarning:
      Optimized (vendor) Blas libraries are not found.
      Falls back to netlib Blas library which has worse performance.
      A better performance should be easily gained by switching
      Blas library.
    if self._calc_info(blas):
  blas_info:
    libraries blas not found in ['C:\\Python\\lib', 'C:\\', 'C:\\Python\\libs']
    NOT AVAILABLE

  C:\Users\pmarti6\AppData\Local\Temp\pip-install-7dhp40t4\numpy_70d258ac961c4e09a9254ad60e4e51ac\numpy\distutils\system_info.py:2026: UserWarning:
      Blas (http://www.netlib.org/blas/) libraries not found.
      Directories to search for the libraries can be specified in the
      numpy/distutils/site.cfg file (section [blas]) or by setting
      the BLAS environment variable.
    if self._calc_info(blas):
  blas_src_info:
    NOT AVAILABLE

  C:\Users\pmarti6\AppData\Local\Temp\pip-install-7dhp40t4\numpy_70d258ac961c4e09a9254ad60e4e51ac\numpy\distutils\system_info.py:2026: UserWarning:
      Blas (http://www.netlib.org/blas/) sources not found.
      Directories to search for the sources can be specified in the
      numpy/distutils/site.cfg file (section [blas_src]) or by setting
      the BLAS_SRC environment variable.
    if self._calc_info(blas):
    NOT AVAILABLE

  non-existing path in 'numpy\\distutils': 'site.cfg'
  lapack_opt_info:
  lapack_mkl_info:
    libraries mkl_rt not found in ['C:\\Python\\lib', 'C:\\', 'C:\\Python\\libs']
    NOT AVAILABLE

  openblas_lapack_info:
    libraries openblas not found in ['C:\\Python\\lib', 'C:\\', 'C:\\Python\\libs']
    NOT AVAILABLE

  openblas_clapack_info:
    libraries openblas,lapack not found in ['C:\\Python\\lib', 'C:\\', 'C:\\Python\\libs']
    NOT AVAILABLE

  flame_info:
    libraries flame not found in ['C:\\Python\\lib', 'C:\\', 'C:\\Python\\libs']
    NOT AVAILABLE

  atlas_3_10_threads_info:
  Setting PTATLAS=ATLAS
    libraries lapack_atlas not found in C:\Python\lib
    libraries tatlas,tatlas not found in C:\Python\lib
    libraries lapack_atlas not found in C:\
    libraries tatlas,tatlas not found in C:\
    libraries lapack_atlas not found in C:\Python\libs
    libraries tatlas,tatlas not found in C:\Python\libs
  <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
    NOT AVAILABLE

  atlas_3_10_info:
    libraries lapack_atlas not found in C:\Python\lib
    libraries satlas,satlas not found in C:\Python\lib
    libraries lapack_atlas not found in C:\
    libraries satlas,satlas not found in C:\
    libraries lapack_atlas not found in C:\Python\libs
    libraries satlas,satlas not found in C:\Python\libs
  <class 'numpy.distutils.system_info.atlas_3_10_info'>
    NOT AVAILABLE

  atlas_threads_info:
  Setting PTATLAS=ATLAS
    libraries lapack_atlas not found in C:\Python\lib
    libraries ptf77blas,ptcblas,atlas not found in C:\Python\lib
    libraries lapack_atlas not found in C:\
    libraries ptf77blas,ptcblas,atlas not found in C:\
    libraries lapack_atlas not found in C:\Python\libs
    libraries ptf77blas,ptcblas,atlas not found in C:\Python\libs
  <class 'numpy.distutils.system_info.atlas_threads_info'>
    NOT AVAILABLE

  atlas_info:
    libraries lapack_atlas not found in C:\Python\lib
    libraries f77blas,cblas,atlas not found in C:\Python\lib
    libraries lapack_atlas not found in C:\
    libraries f77blas,cblas,atlas not found in C:\
    libraries lapack_atlas not found in C:\Python\libs
    libraries f77blas,cblas,atlas not found in C:\Python\libs
  <class 'numpy.distutils.system_info.atlas_info'>
    NOT AVAILABLE

  lapack_info:
    libraries lapack not found in ['C:\\Python\\lib', 'C:\\', 'C:\\Python\\libs']
    NOT AVAILABLE

  C:\Users\pmarti6\AppData\Local\Temp\pip-install-7dhp40t4\numpy_70d258ac961c4e09a9254ad60e4e51ac\numpy\distutils\system_info.py:1858: UserWarning:
      Lapack (http://www.netlib.org/lapack/) libraries not found.
      Directories to search for the libraries can be specified in the
      numpy/distutils/site.cfg file (section [lapack]) or by setting
      the LAPACK environment variable.
    return getattr(self, '_calc_info_{}'.format(name))()
  lapack_src_info:
    NOT AVAILABLE

  C:\Users\pmarti6\AppData\Local\Temp\pip-install-7dhp40t4\numpy_70d258ac961c4e09a9254ad60e4e51ac\numpy\distutils\system_info.py:1858: UserWarning:
      Lapack (http://www.netlib.org/lapack/) sources not found.
      Directories to search for the sources can be specified in the
      numpy/distutils/site.cfg file (section [lapack_src]) or by setting
      the LAPACK_SRC environment variable.
    return getattr(self, '_calc_info_{}'.format(name))()
    NOT AVAILABLE

  numpy_linalg_lapack_lite:
    FOUND:
      language = c
      define_macros = [('HAVE_BLAS_ILP64', None), ('BLAS_SYMBOL_SUFFIX', '64_')]

  Warning: attempted relative import with no known parent package
  C:\Python\lib\distutils\dist.py:274: UserWarning: Unknown distribution option: 'define_macros'
    warnings.warn(msg)
  running bdist_wheel
  running build
  running config_cc
  unifing config_cc, config, build_clib, build_ext, build commands --compiler options
  running config_fc
  unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
  running build_src
  build_src
  building py_modules sources
  creating build
  creating build\src.win-amd64-3.10
  creating build\src.win-amd64-3.10\numpy
  creating build\src.win-amd64-3.10\numpy\distutils
  building library "npymath" sources
  LINK : fatal error LNK1104: não é possível abrir o arquivo 'MSVCRT.lib'
  Traceback (most recent call last):
    File "C:\Python\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 349, in <module>
      main()
    File "C:\Python\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 331, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "C:\Python\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 248, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "C:\Users\pmarti6\AppData\Local\Temp\pip-build-env-qmnihauz\overlay\Lib\site-packages\setuptools\build_meta.py", line 211, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "C:\Users\pmarti6\AppData\Local\Temp\pip-build-env-qmnihauz\overlay\Lib\site-packages\setuptools\build_meta.py", line 197, in _build_with_temp_dir
      self.run_setup()
    File "C:\Users\pmarti6\AppData\Local\Temp\pip-build-env-qmnihauz\overlay\Lib\site-packages\setuptools\build_meta.py", line 248, in run_setup
      super(_BuildMetaLegacyBackend,
    File "C:\Users\pmarti6\AppData\Local\Temp\pip-build-env-qmnihauz\overlay\Lib\site-packages\setuptools\build_meta.py", line 142, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 448, in <module>
      setup_package()
    File "setup.py", line 440, in setup_package
      setup(**metadata)
    File "C:\Users\pmarti6\AppData\Local\Temp\pip-install-7dhp40t4\numpy_70d258ac961c4e09a9254ad60e4e51ac\numpy\distutils\core.py", line 169, in setup
      return old_setup(**new_attr)
    File "C:\Users\pmarti6\AppData\Local\Temp\pip-build-env-qmnihauz\overlay\Lib\site-packages\setuptools\__init__.py", line 165, in setup
      return distutils.core.setup(**attrs)
    File "C:\Python\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\Python\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "C:\Python\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\pmarti6\AppData\Local\Temp\pip-build-env-qmnihauz\overlay\Lib\site-packages\wheel\bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "C:\Python\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Python\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\pmarti6\AppData\Local\Temp\pip-install-7dhp40t4\numpy_70d258ac961c4e09a9254ad60e4e51ac\numpy\distutils\command\build.py", line 61, in run
      old_build.run(self)
    File "C:\Python\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "C:\Python\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Python\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\pmarti6\AppData\Local\Temp\pip-install-7dhp40t4\numpy_70d258ac961c4e09a9254ad60e4e51ac\numpy\distutils\command\build_src.py", line 144, in run
      self.build_sources()
    File "C:\Users\pmarti6\AppData\Local\Temp\pip-install-7dhp40t4\numpy_70d258ac961c4e09a9254ad60e4e51ac\numpy\distutils\command\build_src.py", line 155, in build_sources
      self.build_library_sources(*libname_info)
    File "C:\Users\pmarti6\AppData\Local\Temp\pip-install-7dhp40t4\numpy_70d258ac961c4e09a9254ad60e4e51ac\numpy\distutils\command\build_src.py", line 288, in build_library_sources
      sources = self.generate_sources(sources, (lib_name, build_info))
    File "C:\Users\pmarti6\AppData\Local\Temp\pip-install-7dhp40t4\numpy_70d258ac961c4e09a9254ad60e4e51ac\numpy\distutils\command\build_src.py", line 378, in generate_sources
      source = func(extension, build_dir)
    File "numpy\core\setup.py", line 666, in get_mathlib_info
      raise RuntimeError("Broken toolchain: cannot link a simple C program")
  RuntimeError: Broken toolchain: cannot link a simple C program
  ----------------------------------------
  ERROR: Failed building wheel for numpy
Failed to build numpy
ERROR: Could not build wheels for numpy which use PEP 517 and cannot be installed directly
```

### NumPy/Python version information:

Python 3.10.0
Numpy 1.21.2

**Comment by mattip** [comment]
I removed part of the error report and left the important part: something is missing in your Visual Studio installation to build NumPy. In any case, you would get a subpar experience without using an OpenBLAS library like in our binary wheels.

The solution for this, like the solution for this issue you linked to, is to wait a month or so until binary wheels are available for python 3.10.

**Comment by Aswath1999** [comment]
> Same error when trying to install Pandas. I have installed Wheel and Numpy already.
> 
> ` ERROR: Failed building wheel for numpy Failed to build numpy ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects`

I have the same problem.Have you solved it?

**Comment by Raijin-3** [comment]
I'm having the same issue. Is there any way to update it manually,  not through console?

**Comment by Chavez1186563746** [comment]
> Same error when trying to install Pandas. I have installed Wheel and Numpy already.
> 
> ` ERROR: Failed building wheel for numpy Failed to build numpy ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects`
me too

**Comment by PiyushJadhav** [comment]
Facing same issue, I guess the numpy wheels are still not there..

**Comment by rgommers** [comment]
Wheels are present for 3.10. Please do not comment on an old and closed issue with zero details on your actual problems. You are likely trying to install another project which declares its dependency on `numpy` in an incorrect fashion. It's easy to verify that Python 3.10 wheels are present in https://pypi.org/project/numpy/#files. 

In case you do suspect an actual problem in numpy packaging, please open a new issue with a _complete and reproducible description_ of your build/install steps (starting from how you installed Python, then the actual commands you ran, then the full traceback you are seeing).
