### ISSUE TITLE
libgfortran-2e0d59d6.so.5.0.0: ELF load command address/offset not properly aligned

### ISSUE THREAD

**Issue by zili55** [numpy/numpy#20101]
### Steps to reproduce:

Hello Guys, first of all I would like to say thanks for NumPy - it's an awesome tool!

So my problem is the following ... if I strip one shared object what comes with NumPy then I get an error after import:
```
strip ~/venv/lib/python3.9/site-packages/numpy.libs/libgfortran-2e0d59d6.so.5.0.0
python
import numpy
```

Python: 3.9.0
NumPy: 1.21.2
GNU strip (GNU Binutils) 2.36.1

I installed NumPy via pip.

Thanks in advance!

### Error message:

```shell
Traceback (most recent call last):
  File "/home/criaz/repos/briefcase-613/venv/lib/python3.9/site-packages/numpy/core/__init__.py", line 22, in <module>
    from . import multiarray
  File "/home/criaz/repos/briefcase-613/venv/lib/python3.9/site-packages/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/home/criaz/repos/briefcase-613/venv/lib/python3.9/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: libgfortran-2e0d59d6.so.5.0.0: ELF load command address/offset not properly aligned

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/criaz/repos/briefcase-613/venv/lib/python3.9/site-packages/numpy/__init__.py", line 150, in <module>
    from . import core
  File "/home/criaz/repos/briefcase-613/venv/lib/python3.9/site-packages/numpy/core/__init__.py", line 48, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.9 from "/home/criaz/repos/briefcase-613/venv/bin/python"
  * The NumPy version is: "1.21.2"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: libgfortran-2e0d59d6.so.5.0.0: ELF load command address/offset not properly aligned
```
```


### Additional information:

_No response_

**Comment by zili55** [comment]
briefly: I work on a project where we strip shared objects by default.

I'm not familiar with shared objects, I just want to know it this is a normal behavior.

**Comment by HaoZeke** [comment]
This is expected behaviour. See [strip](https://linux.die.net/man/1/strip). Could you show a minimal reproducible example? You might try to compile with `--strip-unneeded` if you're worried about large libraries but I don't see the point.

**Comment by seberg** [comment]
The issue seems more like a question and the expected result, so I don't think there is anything to be done (and if there was, it should be pushed by an interested party).
