### ISSUE TITLE
BUG: install numpy new release version error

### ISSUE THREAD

**Issue by MarsSu0618** [numpy/numpy#20313]
### Describe the issue:

After numpy released 1.21.4 version, when we install corresponding version lib on linux (centos). it can not be installed and show some error message about `cython.`. But i installed 1.21.3 version that is success. Maybe this release have some bugs?

### Reproduce the code example:

```python
no code example. Because this bug belongs to installation scope.
```

### Error message:

```shell
Running setup.py install for numpy: started
    Running setup.py install for numpy: finished with status 'error'
    Complete output from command /bin/python3 -u -c "import setuptools, tokenize;__file__='/mnt/tmp/pip-build-_j1h9tj1/numpy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-c5aoqdcp-record/install-record.txt --single-version-externally-managed --compile:
    Running from numpy source directory.
    
    Note: if you need reliable uninstall behavior, then install
    with pip instead of using `setup.py install`:
    
      - `pip install .`       (from a git repo or downloaded source
                               release)
      - `pip install numpy`   (last NumPy release on PyPi)
    
    
    Cythonizing sources
    Processing numpy/random/_bounded_integers.pxd.in
    Processing numpy/random/_mt19937.pyx
    Traceback (most recent call last):
      File "/mnt/tmp/pip-build-_j1h9tj1/numpy/tools/cythonize.py", line 59, in process_pyx
        import Cython
    ModuleNotFoundError: No module named 'Cython'
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/mnt/tmp/pip-build-_j1h9tj1/numpy/tools/cythonize.py", line 240, in <module>
        main()
      File "/mnt/tmp/pip-build-_j1h9tj1/numpy/tools/cythonize.py", line 236, in main
        find_process_files(root_dir)
      File "/mnt/tmp/pip-build-_j1h9tj1/numpy/tools/cythonize.py", line 227, in find_process_files
        process(root_dir, fromfile, tofile, function, hash_db)
      File "/mnt/tmp/pip-build-_j1h9tj1/numpy/tools/cythonize.py", line 193, in process
        processor_function(fromfile, tofile)
      File "/mnt/tmp/pip-build-_j1h9tj1/numpy/tools/cythonize.py", line 66, in process_pyx
        raise OSError(msg) from e
    OSError: Cython needs to be installed in Python as a module
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/mnt/tmp/pip-build-_j1h9tj1/numpy/setup.py", line 448, in <module>
        setup_package()
      File "/mnt/tmp/pip-build-_j1h9tj1/numpy/setup.py", line 430, in setup_package
        generate_cython()
      File "/mnt/tmp/pip-build-_j1h9tj1/numpy/setup.py", line 236, in generate_cython
        raise RuntimeError("Running cythonize failed!")
    RuntimeError: Running cythonize failed!
```

### NumPy/Python version information:

1.21.4

**Comment by gehbiszumeis** [comment]
Please keep the issue open, I get the same errors after the 1.21.4 update

**Comment by melissawm** [comment]
Can you clarify how you are installing NumPy? Are you using your distro package manager?

**Comment by gehbiszumeis** [comment]
@melissawm In my case it happens in a CI pipeline, when it tries to build the [`GPy`](https://github.com/SheffieldML/GPy) package. It seems that this package tries to use `setuptools` and `easy_install` for the build and fails with the stacktrace below (i.e. the same as the one from @MarsSu0618 )

The pipeline was running smooth until a day before the `numpy 1.21.4` release and failed without changes in the code afterwards (and keeps failing since then)

```
Collecting GPy>=1.10.0
  Downloading https://...pypi-all/packages/gpy/1.10.0/GPy-1.10.0.tar.gz (959 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
[91m  ERROR: Command errored out with exit status 1:
   command: /opt/app-root/bin/python3.8 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-za9ervmr/gpy_a79bdc5befa344e4aa75f52befe62330/setup.py'"'"'; __file__='"'"'/tmp/pip-install-za9ervmr/gpy_a79bdc5befa344e4aa75f52befe62330/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-ssb_3412
       cwd: /tmp/pip-install-za9ervmr/gpy_a79bdc5befa344e4aa75f52befe62330/
  Complete output (93 lines):
  Running from numpy source directory.
  Cythonizing sources
  Processing numpy/random/_bounded_integers.pxd.in
  Processing numpy/random/_mt19937.pyx
  Traceback (most recent call last):
    File "/tmp/easy_install-ewge0igm/numpy-1.21.4/tools/cythonize.py", line 59, in process_pyx
      import Cython
  ModuleNotFoundError: No module named 'Cython'
  
  The above exception was the direct cause of the following exception:
  
  Traceback (most recent call last):
    File "/tmp/easy_install-ewge0igm/numpy-1.21.4/tools/cythonize.py", line 240, in <module>
      main()
    File "/tmp/easy_install-ewge0igm/numpy-1.21.4/tools/cythonize.py", line 236, in main
      find_process_files(root_dir)
    File "/tmp/easy_install-ewge0igm/numpy-1.21.4/tools/cythonize.py", line 227, in find_process_files
      process(root_dir, fromfile, tofile, function, hash_db)
    File "/tmp/easy_install-ewge0igm/numpy-1.21.4/tools/cythonize.py", line 193, in process
      processor_function(fromfile, tofile)
    File "/tmp/easy_install-ewge0igm/numpy-1.21.4/tools/cythonize.py", line 66, in process_pyx
      raise OSError(msg) from e
  OSError: Cython needs to be installed in Python as a module
  Traceback (most recent call last):
    File "/opt/app-root/lib64/python3.8/site-packages/setuptools/sandbox.py", line 154, in save_modules
      yield saved
    File "/opt/app-root/lib64/python3.8/site-packages/setuptools/sandbox.py", line 195, in setup_context
      yield
    File "/opt/app-root/lib64/python3.8/site-packages/setuptools/sandbox.py", line 250, in run_setup
      _execfile(setup_script, ns)
    File "/opt/app-root/lib64/python3.8/site-packages/setuptools/sandbox.py", line 45, in _execfile
      exec(code, globals, locals)
    File "/tmp/easy_install-ewge0igm/numpy-1.21.4/setup.py", line 448, in <module>
    File "/tmp/easy_install-ewge0igm/numpy-1.21.4/setup.py", line 430, in setup_package
    File "/tmp/easy_install-ewge0igm/numpy-1.21.4/setup.py", line 236, in generate_cython
  RuntimeError: Running cythonize failed!
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-za9ervmr/gpy_a79bdc5befa344e4aa75f52befe62330/setup.py", line 126, in <module>
      setup(name = 'GPy',
    File "/opt/app-root/lib64/python3.8/site-packages/setuptools/__init__.py", line 144, in setup
      _install_setup_requires(attrs)
    File "/opt/app-root/lib64/python3.8/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
      dist.fetch_build_eggs(dist.setup_requires)
    File "/opt/app-root/lib64/python3.8/site-packages/setuptools/dist.py", line 717, in fetch_build_eggs
      resolved_dists = pkg_resources.working_set.resolve(
    File "/opt/app-root/lib64/python3.8/site-packages/pkg_resources/__init__.py", line 780, in resolve
      dist = best[req.key] = env.best_match(
    File "/opt/app-root/lib64/python3.8/site-packages/pkg_resources/__init__.py", line 1065, in best_match
      return self.obtain(req, installer)
    File "/opt/app-root/lib64/python3.8/site-packages/pkg_resources/__init__.py", line 1077, in obtain
      return installer(requirement)
    File "/opt/app-root/lib64/python3.8/site-packages/setuptools/dist.py", line 787, in fetch_build_egg
      return cmd.easy_install(req)
    File "/opt/app-root/lib64/python3.8/site-packages/setuptools/command/easy_install.py", line 684, in easy_install
      return self.install_item(spec, dist.location, tmpdir, deps)
    File "/opt/app-root/lib64/python3.8/site-packages/setuptools/command/easy_install.py", line 710, in install_item
      dists = self.install_eggs(spec, download, tmpdir)
    File "/opt/app-root/lib64/python3.8/site-packages/setuptools/command/easy_install.py", line 895, in install_eggs
      return self.build_and_install(setup_script, setup_base)
    File "/opt/app-root/lib64/python3.8/site-packages/setuptools/command/easy_install.py", line 1163, in build_and_install
      self.run_setup(setup_script, setup_base, args)
    File "/opt/app-root/lib64/python3.8/site-packages/setuptools/command/easy_install.py", line 1149, in run_setup
      run_setup(setup_script, args)
    File "/opt/app-root/lib64/python3.8/site-packages/setuptools/sandbox.py", line 253, in run_setup
      raise
    File "/opt/rh/rh-python38/root/usr/lib64/python3.8/contextlib.py", line 131, in __exit__
      self.gen.throw(type, value, traceback)
    File "/opt/app-root/lib64/python3.8/site-packages/setuptools/sandbox.py", line 195, in setup_context
      yield
    File "/opt/rh/rh-python38/root/usr/lib64/python3.8/contextlib.py", line 131, in __exit__
      self.gen.throw(type, value, traceback)
    File "/opt/app-root/lib64/python3.8/site-packages/setuptools/sandbox.py", line 166, in save_modules
      saved_exc.resume()
    File "/opt/app-root/lib64/python3.8/site-packages/setuptools/sandbox.py", line 141, in resume
      six.reraise(type, exc, self._tb)
    File "/opt/app-root/lib64/python3.8/site-packages/setuptools/_vendor/six.py", line 685, in reraise
      raise value.with_traceback(tb)
    File "/opt/app-root/lib64/python3.8/site-packages/setuptools/sandbox.py", line 154, in save_modules
      yield saved
    File "/opt/app-root/lib64/python3.8/site-packages/setuptools/sandbox.py", line 195, in setup_context
      yield
    File "/opt/app-root/lib64/python3.8/site-packages/setuptools/sandbox.py", line 250, in run_setup
      _execfile(setup_script, ns)
    File "/opt/app-root/lib64/python3.8/site-packages/setuptools/sandbox.py", line 45, in _execfile
      exec(code, globals, locals)
    File "/tmp/easy_install-ewge0igm/numpy-1.21.4/setup.py", line 448, in <module>
    File "/tmp/easy_install-ewge0igm/numpy-1.21.4/setup.py", line 430, in setup_package
    File "/tmp/easy_install-ewge0igm/numpy-1.21.4/setup.py", line 236, in generate_cython
  RuntimeError: Running cythonize failed!
```

**Comment by adason** [comment]
We ran into the same issue when trying to install [pycocotools](https://pypi.org/project/pycocotools/). I tried to pin numpy dependency in `install_requires` but it still tried to use `1.21.4`. We are not ready to upgrad python to 3.8 yet. Any recommendation how to fix this issue on our end? 

```
Collecting pycocotools<3.0.0,>=2.0.2
  Downloading pycocotools-2.0.2.tar.gz (23 kB)
    ERROR: Command errored out with exit status 1:
     command: /opt/hostedtoolcache/Python/3.7.5/x64/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-usmb4s1l/pycocotools_1e61ca0a30cf46399de8bbb6de47904a/setup.py'"'"'; __file__='"'"'/tmp/pip-install-usmb4s1l/pycocotools_1e61ca0a30cf46399de8bbb6de47904a/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-rxjj0ijw
         cwd: /tmp/pip-install-usmb4s1l/pycocotools_1e61ca0a30cf46399de8bbb6de47904a/
    Complete output (89 lines):
    Processing numpy/random/_bounded_integers.pxd.in
    Processing numpy/random/_sfc64.pyx
    Traceback (most recent call last):
      File "/tmp/easy_install-ndlycoec/numpy-1.21.4/tools/cythonize.py", line 59, in process_pyx
        import Cython
    ModuleNotFoundError: No module named 'Cython'
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/tmp/easy_install-ndlycoec/numpy-1.21.4/tools/cythonize.py", line 240, in <module>
        main()
      File "/tmp/easy_install-ndlycoec/numpy-1.21.4/tools/cythonize.py", line 236, in main
        find_process_files(root_dir)
      File "/tmp/easy_install-ndlycoec/numpy-1.21.4/tools/cythonize.py", line 227, in find_process_files
        process(root_dir, fromfile, tofile, function, hash_db)
      File "/tmp/easy_install-ndlycoec/numpy-1.21.4/tools/cythonize.py", line 193, in process
        processor_function(fromfile, tofile)
      File "/tmp/easy_install-ndlycoec/numpy-1.21.4/tools/cythonize.py", line 66, in process_pyx
        raise OSError(msg) from e
    OSError: Cython needs to be installed in Python as a module
    Cythonizing sources
    Running from numpy source directory.
    Traceback (most recent call last):
      File "/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-ndlycoec/numpy-1.21.4/setup.py", line 448, in <module>
      File "/tmp/easy_install-ndlycoec/numpy-1.21.4/setup.py", line 430, in setup_package
      File "/tmp/easy_install-ndlycoec/numpy-1.21.4/setup.py", line 236, in generate_cython
    RuntimeError: Running cythonize failed!
```

**Comment by charris** [comment]
NumPy 1.21.4 supports Python 3.7, the main branch (1.22.0) does not. From the error message, it looks like you don't have Cython installed. Try `python3 -m pip install  cython --upgrade`. You can check the version `python3 -m cython --version`, you need 0.29.24. `easy_install` may be the problem here, it has caused problems in the past.

**Comment by adason** [comment]
@charris Thank you. This works on our end.

**Comment by melissawm** [comment]
Feel free to reopen if the issue persists.

**Comment by gehbiszumeis** [comment]
In my case the Cython version was already ok. I fixed the problem now by explicitely `pip install`ing numpy in a separate statement in my CI pipeline before `pip install -r requirements.txt`.
I guess the problem originates somehow from changes in `setuptools` where changes in their CLI are happening atm apparently and some packages have a faulty way of internally importing numpy/Cython during their build, which leads to these errros. See [here](https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html) for some thoughts on this. However, I cannot fully confirm this.
Anyway, thanks to all!

**Comment by charris** [comment]
> problem originates somehow from changes in setuptools

I had to install setuptools 59.2.0 (newest) to test NumPy with Python 3.10 on Fedora 35.
