### ISSUE TITLE
Some Travis CI failures possibly related to unclosed files?

### ISSUE THREAD

**Issue by seberg** [numpy/numpy#20341]
Just noticed this on one of the travis CI runs (https://app.travis-ci.com/github/numpy/numpy/jobs/547397288 link may go away):

```
>               raise RuntimeError("Running f2py failed: %s\n%s"
3656                                   % (cmd[4:], asstr(out)))
3657E                                  RuntimeError: Running f2py failed: ['-m', '_test_ext_module_5419', '/tmp/tmp_6xten_h/module_data_docstring.f90']
3658E                                  Traceback (most recent call last):
3659E                                    File "<string>", line 1, in <module>
3660E                                    File "/home/travis/build/numpy/numpy/builds/venv/lib/python3.10/site-packages/numpy-1.22.0.dev0+1725.g45454478d-py3.10-linux-aarch64.egg/numpy/__init__.py", line 156, in <module>
3661E                                    File "/home/travis/build/numpy/numpy/builds/venv/lib/python3.10/site-packages/numpy-1.22.0.dev0+1725.g45454478d-py3.10-linux-aarch64.egg/numpy/ma/__init__.py", line 42, in <module>
3662E                                    File "/home/travis/build/numpy/numpy/builds/venv/lib/python3.10/site-packages/numpy-1.22.0.dev0+1725.g45454478d-py3.10-linux-aarch64.egg/numpy/ma/core.py", line 24, in <module>
3663E                                    File "/opt/python/3.10-dev/lib/python3.10/inspect.py", line 41, in <module>
3664E                                    File "/opt/python/3.10-dev/lib/python3.10/linecache.py", line 11, in <module>
3665E                                      import tokenize
3666E                                    File "<frozen importlib._bootstrap>", line 1026, in _find_and_load
3667E                                    File "<frozen importlib._bootstrap>", line 1005, in _find_and_load_unlocked
3668E                                    File "<frozen importlib._bootstrap>", line 698, in _load_unlocked
3669E                                    File "<frozen importlib._bootstrap_external>", line 829, in exec_module
3670E                                    File "<frozen importlib._bootstrap_external>", line 966, in get_code
3671E                                    File "<frozen importlib._bootstrap_external>", line 1023, in get_data
3672E                                  OSError: [Errno 23] Too many open files in system: '/opt/python/3.10-dev/lib/python3.10/tokenize.py'
```
So I am wondering if there might be a reason for that in our test suite?

**Comment by charris** [comment]
For what it is worth, travis seems to work better for merges than with PRs.

**Comment by HaoZeke** [comment]
Since Travis was removed in https://github.com/numpy/numpy/pull/24520/files#diff-6ac3f79fc25d95cd1e3d51da53a4b21b939437392578a35ae8cd6d5366ca5485 I'll close this for now.
