### ISSUE TITLE
BUG install issue, 'No module named 'numpy.core._multiarray_umath'

### ISSUE THREAD

**Issue by jeremy-rutman** [numpy/numpy#20349]
### Describe the issue:

I'm trying to install numpy for python3.10 (not in a venv). I installed python 3.10 using 
```
sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt install python3.10
```
pip didn't seem to be installed so I did 
```
jeremy@jeremy-Blade:/$ wget https://bootstrap.pypa.io/get-pip.py
jeremy@jeremy-Blade:/$ python3.10 get-pip.py
jeremy@jeremy-Blade:/$ python3.10 -m pip --version 
pip 21.3.1 from /home/jeremy/.local/lib/python3.10/site-packages/pip (python 3.10)
```
and then  tried
```
jeremy@jeremy-Blade:/media/jeremy/9FBD-1B00/data/websites/pics$ python3.10 -m pip install numpy
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: numpy in /usr/lib/python3/dist-packages (1.17.4)
```
But when I try to import numpy : 
```
jeremy@jeremy-Blade:/$ python3.10
Python 3.10.0 (default, Oct  4 2021, 22:09:55) [GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/numpy/core/__init__.py", line 17, in <module>
    from . import multiarray
  File "/usr/lib/python3/dist-packages/numpy/core/multiarray.py", line 14, in <module>
    from . import overrides
  File "/usr/lib/python3/dist-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/usr/lib/python3/dist-packages/numpy/core/__init__.py", line 47, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.10 from "/usr/bin/python3.10",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.17.4" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log
...
Original error was: No module named 'numpy.core._multiarray_umath'
```
my path is 
```
jeremy@jeremy-Blade:/$env|grep PATH
LD_LIBRARY_PATH=/usr/local/cuda-10.2/targets/x86_64-linux/lib/stubs
PATH=/home/jeremy/.local/bin:/usr/local/cuda-10.2/bin:/usr/local/cuda-10.2/targets/x86_64-linux/lib/stubs:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```
(so PYTHONPATH is not set) , and following the recommendations in the error message I don't seem to see any problem here. 
My OS is ubuntu 20.04. 
Sorry if this is something obvious or unrelated to numpy. 

### Reproduce the code example:

```python
jeremy@jeremy-Blade:/$ python3.10
Python 3.10.0 (default, Oct  4 2021, 22:09:55) [GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
```

### Error message:

```shell
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/numpy/core/__init__.py", line 17, in <module>
    from . import multiarray
  File "/usr/lib/python3/dist-packages/numpy/core/multiarray.py", line 14, in <module>
    from . import overrides
  File "/usr/lib/python3/dist-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
```

### NumPy/Python version information:

numpy 1.17.4
python 3.10

**Comment by mattip** [comment]
You cannot  use that numpy 1.17 with python 3.10. I think the problem is that pip somehow got confused and did not properly check that the numpy you have installed there is valid. It may be because the version specifiers in 1.17 were not specific enough for the pip you are using. I think if you use a system python you should use a system pip. Doesn't deadsnake provide a pip to go with that python? 

In any case, the oldest supported version for 3.10 is numpy 1.21
```
python3.10 -m pip install --user "numpy==1.21"
```

**Comment by matthew-brett** [comment]
Your output suggests that `pip` did not in fact install Numpy, because it found the system Numpy:

```
Requirement already satisfied: numpy in /usr/lib/python3/dist-packages (1.17.4)
```

So - I guess your system Numpy must be broken.   What do you get with:

```
python3.10 -m pip install --user --upgrade numpy
```

?

**Comment by jeremy-rutman** [comment]
hooray !!!

```
jeremy@jeremy-Blade:~$ python3.10 -m pip install --user --upgrade numpy
Requirement already satisfied: numpy in /usr/lib/python3/dist-packages (1.17.4)
Collecting numpy
  Using cached numpy-1.21.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (15.9 MB)
Installing collected packages: numpy
Successfully installed numpy-1.21.4
jeremy@jeremy-Blade:~$ python3.10 
Python 3.10.0 (default, Oct  4 2021, 22:09:55) [GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> 



```
