### ISSUE TITLE
BUG: `numpy.ctypeslib.load_library()` from custom directory fails on Windows with Python 3.8+

### ISSUE THREAD

**Issue by zmoon** [numpy/numpy#20362]
### Describe the issue:

Related to [this Python issue](https://bugs.python.org/issue42114).

I found that passing `winmode=0` allows the library to be loaded, as mentioned in that issue.

Full context of code example below: https://github.com/zmoon/vorts/blob/e88dec5dd7f5cfeb926b0f3636ed8e4cb006145d/vorts/f/api.py

### Reproduce the code example:

```python
np.ctypeslib.load_library("libvortsf", "./_build")
```

### Error message:

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\zmoon\.conda\envs\vorts-dev\lib\site-packages\numpy\ctypeslib.py", line 149, in load_library
    return ctypes.cdll[libpath]
  File "C:\Users\zmoon\.conda\envs\vorts-dev\lib\ctypes\__init__.py", line 448, in __getitem__
    return getattr(self, name)
  File "C:\Users\zmoon\.conda\envs\vorts-dev\lib\ctypes\__init__.py", line 443, in __getattr__
    dll = self._dlltype(name)
  File "C:\Users\zmoon\.conda\envs\vorts-dev\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'C:\Users\zmoon\git\vorts\vorts\f\_build\libvortsf.dll' (or one of its dependencies). Try using the full path with constructor syntax.
```

### NumPy/Python version information:

1.21.4 3.8.8 | packaged by conda-forge | (default, Feb 20 2021, 15:50:08) [MSC v.1916 64 bit (AMD64)]

**Comment by kjelljorner** [comment]
Seems solution is related to `winmode` keyword in CDLL which is not considered by `load_library`: https://stackoverflow.com/a/64472088

**Comment by kjelljorner** [comment]
I want to emphasize that this issue makes `numpy.ctypeslib.load_library()` unusable for cross-platform support. Here is a code-snippet that I am currently using that replaces it. Haven't tested it super extensively. I would of course be happy to just use `load_library` if that was possible.

```python
# Load shared library
path = Path(__file__).parent
name = "libconeangle"
winmode: Optional[int] = None
if sys.platform == "win32":
    name = f"{name}.dll"
    print(path)
    os.add_dll_directory(path)
    winmode = 0
elif sys.platform.startswith("linux"):
    name = f"{name}.so"
elif sys.platform == "darwin":
    name = f"{name}.dylib"
else:
    raise ImportError(f"Your OS is not supported: {sys.platform}")

lib = ctypes.CDLL(str(path / name), winmode=winmode)
```

**Comment by seberg** [comment]
Hmmm, I have to look closer maybe (had hoped that Joseph just has a quick insight).  @kjelljorner do you think it would be right to modify `numpy.ctypes.load_library` to add a `winmode` option to pick a different default?  I.e. as an enhancement to `numpy.ctypeslib.load_library` to allow passing that kwarg.
It looks like some other code changes would be necessary to pass on the kwarg correctly, but probably not many.

**Comment by kjelljorner** [comment]
@seberg My opinion is that everything should be taken care of behind the scenes by `load_library`. As far as I know it only exists as a convenience function to load libraries more easily in a cross-platform compatible way. If you need to detect the platform yourself and pass kwargs it doesn't really do that. Then you might as well just write your own code that uses ctypes directly (as I currently do).

**Comment by seberg** [comment]
After reviewing things a bit, it seems the `winmode` parameter change in Python is mainly about loading libraries by name (rather than full path) and doesn't really make sense here (we have the absolute path available).

There are some other security related `winmode` parameters, and I am not sure what they end up doing here, although, I expect they don't matter too much.  Maybe it makes sense to document, but probably not.

So my inclination is that I agree, we probably should change this.  The current code also relies on `np.distutils`, which would be nice to refactor – that might give a `DeprecationWarning` here even.  I am not sure if `ctypeslib` really gets much maintenance these days...

**Comment by charris** [comment]
I changed the milestone to 1.22.5, but I doubt that we will make that release unless a fix turns up pretty quickly.

**Comment by charris** [comment]
Pushing off to 1.23.3.

**Comment by charris** [comment]
Pushed off to 1.23.4. What is the current take on this?

**Comment by seberg** [comment]
I don't think it changed, so a PR with test might be the best way to ensure it moves forward.

**Comment by seberg** [comment]
I am happy to look at this if pinged, but right now it seems to me we can push this off for the release.

**Comment by mattip** [comment]
We discussed this at a triage meeting and would be willing to review a PR based on https://github.com/numpy/numpy/issues/20362#issuecomment-1063247943. It should come with some kind of test.

**Comment by kjelljorner** [comment]
Thanks for the update. Unfortunately, I currently don't have the capacity to put in such a pull request.
