### ISSUE TITLE
BUG: Fails to build against python 3.10 only for x86_64

### ISSUE THREAD

**Issue by th0ma7** [numpy/numpy#20406]
### Describe the issue:

Context: Compiling from source part of the SynoCommunity project to provide python packages for Synology NAS using the Synology provided toolchain (ref.: https://github.com/SynoCommunity/spksrc & https://synocommunity.com/)

While trying to switch from python 3.8 to 3.10 it happens that `numpy` fails to build but only for x64_64 arch (see https://github.com/th0ma7/spksrc/runs/4257897829?check_suite_focus=true).  Note that Cython get properly installed before end and should in theory not be the actual cause of the issue.

### Reproduce the code example:

```python
N/A
```

### Error message:

```shell
2021-11-18T22:54:46.8619134Z ===>  Compiling for numpy^M
2021-11-18T22:54:46.9663210Z setup.py:63: RuntimeWarning: NumPy 1.21.1 may not yet support Python 3.10.^M
2021-11-18T22:54:46.9663987Z   warnings.warn(^M
2021-11-18T22:54:46.9686067Z Running from numpy source directory.^M
2021-11-18T22:54:47.2505156Z /github/workspace/spk/homeassistant/work-x64-7.0/numpy-1.21.1/tools/cythonize.py:69: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives^M
2021-11-18T22:54:47.2506946Z   from distutils.version import LooseVersion^M
2021-11-18T22:54:47.6584892Z Processing numpy/random/_bounded_integers.pxd.in^M
2021-11-18T22:54:47.6585601Z Processing numpy/random/_mt19937.pyx^M
2021-11-18T22:54:47.6586142Z Traceback (most recent call last):^M
2021-11-18T22:54:47.6587999Z   File "/github/workspace/spk/homeassistant/work-x64-7.0/numpy-1.21.1/tools/cythonize.py", line 239, in <module>^M
2021-11-18T22:54:47.6588964Z     main()^M
2021-11-18T22:54:47.6589908Z   File "/github/workspace/spk/homeassistant/work-x64-7.0/numpy-1.21.1/tools/cythonize.py", line 235, in main^M
2021-11-18T22:54:47.6590686Z     find_process_files(root_dir)^M
2021-11-18T22:54:47.6591718Z   File "/github/workspace/spk/homeassistant/work-x64-7.0/numpy-1.21.1/tools/cythonize.py", line 226, in find_process_files^M
2021-11-18T22:54:47.6592632Z     process(root_dir, fromfile, tofile, function, hash_db)^M
2021-11-18T22:54:47.6593711Z   File "/github/workspace/spk/homeassistant/work-x64-7.0/numpy-1.21.1/tools/cythonize.py", line 192, in process^M
2021-11-18T22:54:47.6594554Z     processor_function(fromfile, tofile)^M
2021-11-18T22:54:47.6595604Z   File "/github/workspace/spk/homeassistant/work-x64-7.0/numpy-1.21.1/tools/cythonize.py", line 81, in process_pyx^M
2021-11-18T22:54:47.6596417Z     subprocess.check_call(^M
2021-11-18T22:54:47.6597657Z   File "/github/workspace/native/python310/work-native/install/usr/local/lib/python3.10/subprocess.py", line 369, in check_call^M
2021-11-18T22:54:47.6598597Z     raise CalledProcessError(retcode, cmd)^M
2021-11-18T22:54:47.6600250Z subprocess.CalledProcessError: Command '['/github/workspace/spk/homeassistant/work-x64-7.0/crossenv/cross/bin/python', '-m', 'cython', '-3', '--fast-fail', '-o', '_mt19937.c', '_mt19937.pyx']' died with <Signals.SIGSEGV: 11>.^M
2021-11-18T22:54:47.6710916Z Traceback (most recent call last):^M
2021-11-18T22:54:47.6711511Z   File "<string>", line 1, in <module>^M
2021-11-18T22:54:47.6712030Z   File "setup.py", line 447, in <module>^M
2021-11-18T22:54:47.6712555Z     setup_package()^M
2021-11-18T22:54:47.6713047Z   File "setup.py", line 429, in setup_package^M
2021-11-18T22:54:47.6713543Z     generate_cython()^M
2021-11-18T22:54:47.6714043Z   File "setup.py", line 235, in generate_cython^M
2021-11-18T22:54:47.6714665Z     raise RuntimeError("Running cythonize failed!")^M
2021-11-18T22:54:47.6715333Z RuntimeError: Running cythonize failed!^M
2021-11-18T22:54:47.6715861Z Cythonizing sources^M
2021-11-18T22:54:47.7034943Z make[1]: *** [../../mk/spksrc.python-wheel.mk:33: build_python_wheel] Error 1^M
2021-11-18T22:54:47.7036120Z make[1]: Leaving directory '/github/workspace/cross/numpy'^M
2021-11-18T22:54:47.7039994Z make: *** [../../mk/spksrc.depend.mk:51: depend_target] Error 2^M
2021-11-18T22:54:47.7041208Z make: Leaving directory '/github/workspace/spk/homeassistant'^M
2021-11-18T22:54:47.7110040Z make: Entering directory '/github/workspace/spk/homeassistant'^M
2021-11-18T22:54:47.7397618Z rm -fr work work-* build-*.log^M
2021-11-18T22:54:49.0543071Z make: Leaving directory '/github/workspace/spk/homeassistant'^M
2021-11-18T22:54:49.0545044Z ##[endgroup]^M
2021-11-18T22:54:49.2179715Z ##[group]Run docker://ghcr.io/synocommunity/spksrc:latest^M
2021-11-18T22:54:49.2180311Z with:^M
2021-11-18T22:54:49.2180820Z   entrypoint: ./.github/actions/build_status.sh^M
2021-11-18T22:54:49.2181301Z env:^M
2021-11-18T22:54:49.2181813Z   BUILD_ERROR_FILE: /github/workspace/build_errors.txt^M
2021-11-18T22:54:49.2182500Z   BUILD_ERROR_LOGFILE: /github/workspace/build_log_errors.txt^M
2021-11-18T22:54:49.2183263Z   BUILD_UNSUPPORTED_FILE: /github/workspace/build_unsupported.txt^M
2021-11-18T22:54:49.2184019Z   BUILD_SUCCESS_FILE: /github/workspace/build_success.txt^M
2021-11-18T22:54:49.2184555Z ##[endgroup]^M
2021-11-18T22:54:49.2241642Z ##[command]/usr/bin/docker run --name ghcriosynocommunityspksrclatest_7f1889 --label e28490 --workdir /github/workspace --rm -e BUILD_ERROR_FILE -e BUILD_ERROR_LOGFILE -e BUILD_UNSUPPORTED_FILE -e BUILD_SUCCESS_FILE -e INPUT_ENTRYPOINT -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true --entrypoint "./.github/actions/build_status.sh" -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/spksrc/spksrc":"/github/workspace" ghcr.io/synocommunity/spksrc:latest^M

```
```


### NumPy/Python version information:

Tried versions 1.21.1 up to 1.21.4

**Comment by charris** [comment]
Where did you get the source?

**Comment by th0ma7** [comment]
I was able to solve the error by using the conjunction of cython==0.29.24 and numpy==1.21.4.
