### ISSUE TITLE
When configuring apache in flask, I get the following error: No module named 'numpy.core._multiarray_umath'

### ISSUE THREAD

**Issue by Tony-dot-Frank** [numpy/numpy#20450]
### Steps to reproduce:

Os : Ubuntu:18.06
installed numpy using requirements.txt : sudo -H pip3 install -r  requirements.txt
python version : python3.8

### Error message:

```shell
Wed Nov 24 12:14:26.288897 2021] [wsgi:error] [pid 2543:tid 139881192699648] sys.version_info(major=3, minor=6, micro=9, releaselevel='final', serial=0)
[Wed Nov 24 12:14:26.330692 2021] [wsgi:error] [pid 2543:tid 139881192699648] [remote 10.81.0.135:59189] mod_wsgi (pid=2543): Target WSGI script '/home/admin/imm-migration/easyucs_api.wsgi' cannot be loaded as Python module.
[Wed Nov 24 12:14:26.330858 2021] [wsgi:error] [pid 2543:tid 139881192699648] [remote 10.81.0.135:59189] mod_wsgi (pid=2543): Exception occurred processing WSGI script '/home/admin/imm-migration/easyucs_api.wsgi'.
[Wed Nov 24 12:14:26.331131 2021] [wsgi:error] [pid 2543:tid 139881192699648] [remote 10.81.0.135:59189] Traceback (most recent call last):
[Wed Nov 24 12:14:26.331209 2021] [wsgi:error] [pid 2543:tid 139881192699648] [remote 10.81.0.135:59189]   File "/usr/local/lib/python3.8/dist-packages/numpy/core/__init__.py", line 22, in <module>
[Wed Nov 24 12:14:26.331243 2021] [wsgi:error] [pid 2543:tid 139881192699648] [remote 10.81.0.135:59189]     from . import multiarray
[Wed Nov 24 12:14:26.331292 2021] [wsgi:error] [pid 2543:tid 139881192699648] [remote 10.81.0.135:59189]   File "/usr/local/lib/python3.8/dist-packages/numpy/core/multiarray.py", line 12, in <module>
[Wed Nov 24 12:14:26.331334 2021] [wsgi:error] [pid 2543:tid 139881192699648] [remote 10.81.0.135:59189]     from . import overrides
[Wed Nov 24 12:14:26.331379 2021] [wsgi:error] [pid 2543:tid 139881192699648] [remote 10.81.0.135:59189]   File "/usr/local/lib/python3.8/dist-packages/numpy/core/overrides.py", line 7, in <module>
[Wed Nov 24 12:14:26.331419 2021] [wsgi:error] [pid 2543:tid 139881192699648] [remote 10.81.0.135:59189]     from numpy.core._multiarray_umath import (
[Wed Nov 24 12:14:26.331477 2021] [wsgi:error] [pid 2543:tid 139881192699648] [remote 10.81.0.135:59189] ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
[Wed Nov 24 12:14:26.331537 2021] [wsgi:error] [pid 2543:tid 139881192699648] [remote 10.81.0.135:59189]
[Wed Nov 24 12:14:26.331566 2021] [wsgi:error] [pid 2543:tid 139881192699648] [remote 10.81.0.135:59189] During handling of the above exception, another exception occurred:
[Wed Nov 24 12:14:26.331588 2021] [wsgi:error] [pid 2543:tid 139881192699648] [remote 10.81.0.135:59189]
[Wed Nov 24 12:14:26.331618 2021] [wsgi:error] [pid 2543:tid 139881192699648] [remote 10.81.0.135:59189] Traceback (most recent call last):
[Wed Nov 24 12:14:26.331671 2021] [wsgi:error] [pid 2543:tid 139881192699648] [remote 10.81.0.135:59189]   File "/home/admin/imm-migration/easyucs_api.wsgi", line 10, in <module>
[Wed Nov 24 12:14:26.331703 2021] [wsgi:error] [pid 2543:tid 139881192699648] [remote 10.81.0.135:59189]     from easyucs_api import app as application
[Wed Nov 24 12:14:26.331736 2021] [wsgi:error] [pid 2543:tid 139881192699648] [remote 10.81.0.135:59189]   File "/home/admin/imm-migration/easyucs_api.py", line 14, in <module>
[Wed Nov 24 12:14:26.331758 2021] [wsgi:error] [pid 2543:tid 139881192699648] [remote 10.81.0.135:59189]     from api.api_server import app as easyucs_backend
[Wed Nov 24 12:14:26.331787 2021] [wsgi:error] [pid 2543:tid 139881192699648] [remote 10.81.0.135:59189]   File "/home/admin/imm-migration/api/api_server.py", line 19, in <module>
[Wed Nov 24 12:14:26.331808 2021] [wsgi:error] [pid 2543:tid 139881192699648] [remote 10.81.0.135:59189]     import common
[Wed Nov 24 12:14:26.331837 2021] [wsgi:error] [pid 2543:tid 139881192699648] [remote 10.81.0.135:59189]   File "/home/admin/imm-migration/common.py", line 15, in <module>
[Wed Nov 24 12:14:26.331864 2021] [wsgi:error] [pid 2543:tid 139881192699648] [remote 10.81.0.135:59189]     import numpy as np
[Wed Nov 24 12:14:26.331891 2021] [wsgi:error] [pid 2543:tid 139881192699648] [remote 10.81.0.135:59189]   File "/usr/local/lib/python3.8/dist-packages/numpy/__init__.py", line 150, in <module>
[Wed Nov 24 12:14:26.331916 2021] [wsgi:error] [pid 2543:tid 139881192699648] [remote 10.81.0.135:59189]     from . import core
[Wed Nov 24 12:14:26.331945 2021] [wsgi:error] [pid 2543:tid 139881192699648] [remote 10.81.0.135:59189]   File "/usr/local/lib/python3.8/dist-packages/numpy/core/__init__.py", line 48, in <module>
[Wed Nov 24 12:14:26.331967 2021] [wsgi:error] [pid 2543:tid 139881192699648] [remote 10.81.0.135:59189]     raise ImportError(msg)
[Wed Nov 24 12:14:26.332011 2021] [wsgi:error] [pid 2543:tid 139881192699648] [remote 10.81.0.135:59189] ImportError:
[Wed Nov 24 12:14:26.332043 2021] [wsgi:error] [pid 2543:tid 139881192699648] [remote 10.81.0.135:59189]
[Wed Nov 24 12:14:26.332065 2021] [wsgi:error] [pid 2543:tid 139881192699648] [remote 10.81.0.135:59189] IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
[Wed Nov 24 12:14:26.332087 2021] [wsgi:error] [pid 2543:tid 139881192699648] [remote 10.81.0.135:59189]
[Wed Nov 24 12:14:26.332108 2021] [wsgi:error] [pid 2543:tid 139881192699648] [remote 10.81.0.135:59189] Importing the numpy C-extensions failed. This error can happen for
[Wed Nov 24 12:14:26.332129 2021] [wsgi:error] [pid 2543:tid 139881192699648] [remote 10.81.0.135:59189] many reasons, often due to issues with your setup or how NumPy was
[Wed Nov 24 12:14:26.332150 2021] [wsgi:error] [pid 2543:tid 139881192699648] [remote 10.81.0.135:59189] installed.
[Wed Nov 24 12:14:26.332170 2021] [wsgi:error] [pid 2543:tid 139881192699648] [remote 10.81.0.135:59189]
[Wed Nov 24 12:14:26.332191 2021] [wsgi:error] [pid 2543:tid 139881192699648] [remote 10.81.0.135:59189] We have compiled some common reasons and troubleshooting tips at:
[Wed Nov 24 12:14:26.332212 2021] [wsgi:error] [pid 2543:tid 139881192699648] [remote 10.81.0.135:59189]
[Wed Nov 24 12:14:26.332233 2021] [wsgi:error] [pid 2543:tid 139881192699648] [remote 10.81.0.135:59189]     https://numpy.org/devdocs/user/troubleshooting-importerror.html
[Wed Nov 24 12:14:26.332254 2021] [wsgi:error] [pid 2543:tid 139881192699648] [remote 10.81.0.135:59189]
[Wed Nov 24 12:14:26.332275 2021] [wsgi:error] [pid 2543:tid 139881192699648] [remote 10.81.0.135:59189] Please note and check the following:
[Wed Nov 24 12:14:26.332295 2021] [wsgi:error] [pid 2543:tid 139881192699648] [remote 10.81.0.135:59189]
[Wed Nov 24 12:14:26.332316 2021] [wsgi:error] [pid 2543:tid 139881192699648] [remote 10.81.0.135:59189]   * The Python version is: Python3.6 from "/usr/bin/python3"
[Wed Nov 24 12:14:26.332337 2021] [wsgi:error] [pid 2543:tid 139881192699648] [remote 10.81.0.135:59189]   * The NumPy version is: "1.21.4"
[Wed Nov 24 12:14:26.332358 2021] [wsgi:error] [pid 2543:tid 139881192699648] [remote 10.81.0.135:59189]
[Wed Nov 24 12:14:26.332379 2021] [wsgi:error] [pid 2543:tid 139881192699648] [remote 10.81.0.135:59189] and make sure that they are the versions you expect.
[Wed Nov 24 12:14:26.332400 2021] [wsgi:error] [pid 2543:tid 139881192699648] [remote 10.81.0.135:59189] Please carefully study the documentation linked above for further help.
[Wed Nov 24 12:14:26.332421 2021] [wsgi:error] [pid 2543:tid 139881192699648] [remote 10.81.0.135:59189]
[Wed Nov 24 12:14:26.332441 2021] [wsgi:error] [pid 2543:tid 139881192699648] [remote 10.81.0.135:59189] Original error was: No module named 'numpy.core._multiarray_umath'
```

### Additional information:

Tried uninstalling and reinstalling numpy.. didnt work..

**Comment by antonyjoseph46** [comment]
how did you solve this issues ?
