### ISSUE TITLE
numpy internals try to use my module "numbers.py"

### ISSUE THREAD

**Issue by edcjones00** [numpy/numpy#20609]
I am working in a anaconda environment named "CPPYY".  It has
python 3.9.7 and numpy 1.21.4

Start with a file named "numbers.py" containing only:

Integral = 777

Create a second file named "bug.py" containing:

#! /usr/bin/env python
import numpy
import numbers

When I execute bug.py, I get the following error message:

Traceback (most recent call last):
  File "/home/edcjones/CGAL/./bug.py", line 3, in <module>
    import numpy
  File "/home/edcjones/anaconda3/envs/CPPYY/lib/python3.9/site-packages/numpy/__init__.py", line 150, in <module>
    from . import core
  File "/home/edcjones/anaconda3/envs/CPPYY/lib/python3.9/site-packages/numpy/core/__init__.py", line 70, in <module>
    from . import numerictypes as nt
  File "/home/edcjones/anaconda3/envs/CPPYY/lib/python3.9/site-packages/numpy/core/numerictypes.py", line 596, in <module>
    _register_types()
  File "/home/edcjones/anaconda3/envs/CPPYY/lib/python3.9/site-packages/numpy/core/numerictypes.py", line 591, in _register_types
    numbers.Integral.register(integer)
AttributeError: 'int' object has no attribute 'register'

**Comment by rkern** [comment]
[`numbers`](https://docs.python.org/3/library/numbers.html) is a standard library module that numpy needs to use. Naming your module `numbers.py` means that it will shadow the standard library module of the same name. numpy ends up importing your module, expecting the standard library module. It is a good idea to not use module names that are the same as standard library modules for this reason.
