### ISSUE TITLE
BUG: Different np.linalg.solve results on different operating systems

### ISSUE THREAD

**Issue by woolgathering** [numpy/numpy#20633]
### Describe the issue:

I am receiving different results in identical Conda environments, the only difference being operating system. Details using `uname -a`:

Linux: `Linux jacob-pc 5.4.0-91-generic #102-Ubuntu SMP Fri Nov 5 16:31:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
MacOS: `Darwin Jacobs-MacBook-Air.local 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64 x86_64`

The MacOS environment gives the expected result (I believe) while the Linux version ceases with a singular matrix. Numpy and Python versions are identical on both systems.

**Expected Behavior**: a solved system

### Reproduce the code example:

```python
import numpy as np

a = np.matrix('[[234.5        -88.04591605 -62.2578643   38.53731957  77.07463915] [-88.04591605 132.83333333  35.94459471 -22.24953183 -44.49906366] [-62.2578643   35.94459471 107.41666667 -15.73279484 -31.46558967] [ 38.53731957 -22.24953183 -15.73279484  60.25       120.5       ] [ 77.07463915 -44.49906366 -31.46558967 120.5        241.        ]]')
a = a.reshape((5,5))
b = np.array(np.matrix('[8.33383784 -4.37645273 -2.747328    2.67793157  5.35586315]'))[0]
out = np.linalg.solve(a, b) # singular matrix or no?
```

### Error message:

```shell
Traceback (most recent call last):
  File "/BLAH/sanity_check.py", line 43, in <module>
    out = np.linalg.solve(a, b)
  File "<__array_function__ internals>", line 5, in solve
  File "/BLAH/anaconda3/envs/fastMath/lib/python3.9/site-packages/numpy/linalg/linalg.py", line 393, in solve
    r = gufunc(a, b, signature=signature, extobj=extobj)
  File "/BLAH/anaconda3/envs/fastMath/lib/python3.9/site-packages/numpy/linalg/linalg.py", line 88, in _raise_linalgerror_singular
    raise LinAlgError("Singular matrix")
numpy.linalg.LinAlgError: Singular matrix
```

### NumPy/Python version information:

1.21.2 3.9.7 (default, Sep 16 2021, 13:09:58) 
[GCC 7.5.0]

**Comment by woolgathering** [comment]
Following up briefly:

I'm certain the MacOS version is correct. The result is `[ 2.72673865e-02 -1.03329958e-02 -2.89139339e-03 2.94998266e+06 -1.47499132e+06]` (this was double-checked in MATLAB). 

Please advise. If I need to reinstall the Linux system that's fine.

**Comment by woolgathering** [comment]
Closing: `a`'s determinant on the Linux system is `0.0`, the MacOS determinant is `-7.338715777046959e-07` so the matrix is ill-formed. Still not entirely sure why one system solves it...
