### ISSUE TITLE
DOC: Warning when building documentation for 1.22.0

### ISSUE THREAD

**Issue by charris** [numpy/numpy#20690]
I see the following warning when building the 1.22.0 docs:
```
preparing documents... WARNING: unsupported theme option 'collapse_navigation' given
```
Is there a theme version that needs to be pinned?

**Comment by charris** [comment]
Updating to pydata-sphinx-theme 0.7.2 fixed the warning. The html builds, but the pdf builds fail:
```
Latexmk: Missing input file '{broadcasting_1}.svg' (or dependence on it) from following:
  'LaTeX Warning: File `{broadcasting_1}.svg' not found on input line 7019.'
Latexmk: Missing input file '{broadcasting_1}.svg' (or dependence on it) from following:
  'LaTeX Warning: File `{broadcasting_1}.svg' not found on input line 7019.'
Latexmk: Missing input file '{broadcasting_2}.svg' (or dependence on it) from following:
  'LaTeX Warning: File `{broadcasting_2}.svg' not found on input line 7188.'
Latexmk: Missing input file '{broadcasting_2}.svg' (or dependence on it) from following:
  'LaTeX Warning: File `{broadcasting_2}.svg' not found on input line 7188.'
Latexmk: Missing input file '{broadcasting_3}.svg' (or dependence on it) from following:
  'LaTeX Warning: File `{broadcasting_3}.svg' not found on input line 7202.'
Latexmk: Missing input file '{broadcasting_3}.svg' (or dependence on it) from following:
  'LaTeX Warning: File `{broadcasting_3}.svg' not found on input line 7202.'
Latexmk: Missing input file '{broadcasting_4}.svg' (or dependence on it) from following:
  'LaTeX Warning: File `{broadcasting_4}.svg' not found on input line 7231.'
Latexmk: Missing input file '{broadcasting_4}.svg' (or dependence on it) from following:
  'LaTeX Warning: File `{broadcasting_4}.svg' not found on input line 7231.'
Latexmk: Errors, so I did not complete making targets
```
Those figures do exist, both for html and latex, but latex complains that they lack bounding boxes.

**Comment by rossbar** [comment]
The [`sphinx.ext.imgconverter`](https://www.sphinx-doc.org/en/master/usage/extensions/imgconverter.html) extension should enable support for `.svg`s with the latex builders - @Mukulikaa have you tried this extension?

**Comment by Mukulikaa** [comment]
I tried it out by adding the extension to ` conf.py` and having Imagemagick installed locally. I also removed the duplicate PNGs and just kept the SVGs. It didn't work though and gave me this error:
<details>
<summary>Traceback</summary>
<br>
Traceback (most recent call last):
  File "/home/mtdewgorl/.conda/envs/numpy-dev/lib/python3.9/site-packages/sphinx/ext/imgconverter.py", line 62, in convert
    subprocess.run(args, stdout=PIPE, stderr=PIPE, check=True)
  File "/home/mtdewgorl/.conda/envs/numpy-dev/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['convert', '/home/mtdewgorl/numpy/doc/source/user/broadcasting_1.svg[0]', '/home/mtdewgorl/numpy/doc/build/doctrees/images/broadcasting_1.png']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mtdewgorl/.conda/envs/numpy-dev/lib/python3.9/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "/home/mtdewgorl/.conda/envs/numpy-dev/lib/python3.9/site-packages/sphinx/application.py", line 343, in build
    self.builder.build_update()
  File "/home/mtdewgorl/.conda/envs/numpy-dev/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 290, in build_update
    self.build(['__all__'], to_build)
  File "/home/mtdewgorl/.conda/envs/numpy-dev/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 357, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/mtdewgorl/.conda/envs/numpy-dev/lib/python3.9/site-packages/sphinx/builders/latex/__init__.py", line 289, in write
    doctree = self.assemble_doctree(
  File "/home/mtdewgorl/.conda/envs/numpy-dev/lib/python3.9/site-packages/sphinx/builders/latex/__init__.py", line 353, in assemble_doctree
    self.env.resolve_references(largetree, indexfile, self)
  File "/home/mtdewgorl/.conda/envs/numpy-dev/lib/python3.9/site-packages/sphinx/environment/__init__.py", line 566, in resolve_references
    self.apply_post_transforms(doctree, fromdocname)
  File "/home/mtdewgorl/.conda/envs/numpy-dev/lib/python3.9/site-packages/sphinx/environment/__init__.py", line 578, in apply_post_transforms
    transformer.apply_transforms()
  File "/home/mtdewgorl/.conda/envs/numpy-dev/lib/python3.9/site-packages/sphinx/transforms/__init__.py", line 86, in apply_transforms
    super().apply_transforms()
  File "/home/mtdewgorl/.conda/envs/numpy-dev/lib/python3.9/site-packages/docutils/transforms/__init__.py", line 171, in apply_transforms
    transform.apply(**kwargs)
  File "/home/mtdewgorl/.conda/envs/numpy-dev/lib/python3.9/site-packages/sphinx/transforms/post_transforms/images.py", line 35, in apply
    self.handle(node)
  File "/home/mtdewgorl/.conda/envs/numpy-dev/lib/python3.9/site-packages/sphinx/transforms/post_transforms/images.py", line 250, in handle
    if self.convert(abs_srcpath, destpath):
  File "/home/mtdewgorl/.conda/envs/numpy-dev/lib/python3.9/site-packages/sphinx/ext/imgconverter.py", line 70, in convert
    raise ExtensionError(__('convert exited with error:\n'
sphinx.errors.ExtensionError: convert exited with error:
[stderr]
b"convert: no images defined `/home/mtdewgorl/numpy/doc/build/doctrees/images/broadcasting_1.png' @ error/convert.c/ConvertImageCommand/3327.\n"
[stdout]
b''

Extension error:
convert exited with error:
[stderr]
b"convert: no images defined `/home/mtdewgorl/numpy/doc/build/doctrees/images/broadcasting_1.png' @ error/convert.c/ConvertImageCommand/3327.\n"
[stdout]
b''
make: *** [Makefile:225: latex-build] Error 2
</details>
