### ISSUE TITLE
BUG: AttributeError: Module 'numpy.core' has no attribute 'numerictypes' when importing in PyCharm community edition debugger with PyQt compatibility set to Auto

### ISSUE THREAD

**Issue by jmartens** [numpy/numpy#20748]
### Describe the issue:

When I run below simple code in PyCharm in normal run mode it works as expected and prints numpy version number. When run using the debugger it fails with an AttributeError:

### Reproduce the code example:

```python
import numpy as np
print(f"Numpy: {np.version.version}")
```

### Error message:

```shell
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "****\venv\lib\site-packages\numpy\__init__.py", line 195, in <module>
    core.numerictypes.typeDict,
  File "****\venv\lib\site-packages\numpy\core\__init__.py", line 161, in __getattr__
    raise AttributeError(f"Module {__name__!r} has no attribute {name!r}")
AttributeError: Module 'numpy.core' has no attribute 'numerictypes'
python-BaseException

Process finished with exit code 1
```

### NumPy/Python version information:

1.22.0 3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)]

**Comment by jmartens** [comment]
PyCharm details:
```
PyCharm 2021.2.2 (Community Edition)
Build #PC-212.5284.44, built on September 14, 2021
Runtime version: 11.0.12+7-b1504.28 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry: ide.balloon.shadow.size=0, ide.images.show.chessboard=true
Non-Bundled Plugins: com.chrisrm.idea.MaterialThemeUI (6.8.2), Docker (212.5284.17), org.sonarlint.idea (5.3.0.36775), ru.adelf.idea.dotenv (2021.3.0.212), ru.meanmail.plugin.requirements (2021.4.1-212), com.pycrunch.intellijconnector (1.2.2), mobi.hsz.idea.gitignore (4.2.0), com.mallowigi (41.0.0)
```

**Comment by jmartens** [comment]
This also reproduced on latest PyCharm:
```
PyCharm 2021.2.2 (Community Edition)
Build #PC-212.5284.44, built on September 14, 2021
Runtime version: 11.0.12+7-b1504.28 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry: ide.balloon.shadow.size=0, ide.images.show.chessboard=true
Non-Bundled Plugins: org.sonarlint.idea (6.3.1.40498), com.chrisrm.idea.MaterialThemeUI (6.9.1), Docker (212.5284.17), com.mallowigi (50.2.0), mobi.hsz.idea.gitignore (4.3.0), ru.adelf.idea.dotenv (2021.3.0.212), ru.meanmail.plugin.requirements (2021.4.1-212), com.pycrunch.intellijconnector (1.2.3)
```

**Comment by jmartens** [comment]
I have to go as far back as installing numpy 1.19.5 to have this working under PyCharm debugger 👎

**Comment by jmartens** [comment]
Found [PY-50959](https://youtrack.jetbrains.com/issue/PY-50959) reported in PyCharms issue tracker, apparently it works when switching off PyQt compatibility, which was set to Auto in my case.

However I also use numpy (through pandas) in PyQt applications, not sure what the implications might be from disabling it when debugging PyQt applications.

**Comment by seberg** [comment]
Can we close this? From your comments it sounds like an issue in PyCharm or PyQt and trying to help out by changing NumPy seems difficult/unlikely if we would have to go as far back as NumPy 1.20.

**Comment by gupta-shubhm** [comment]
Please update the numpy version to numpy==1.20.3 with Python 3.9. This should resolve the error.

**Comment by seberg** [comment]
Closing this as stale, maybe the last tip helps, I am not sure.  In any case, it should be its own issue and seems not dirctly NumPy related.
