### ISSUE TITLE
DOC, TST: CircleCI doc failure.

### ISSUE THREAD

**Issue by charris** [numpy/numpy#20877]
See [here](https://tinyurl.com/y9uc8zn2).  This is new, and probably due to pandas 1,4.0 that was released today (Jan 22 2022).

**Comment by mattip** [comment]
For future reference, here is the error

<details><summary>Doctest failure in `absolute_beginners.rst`</summary>

```
File "/tmp/tmp3kck6ceh/doc/source/user/absolute_beginners.rst", line 1591, in doc/source/user/absolute_beginners.rst
Failed example:
    pd.set_option('max_columns', 10)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.8/doctest.py", line 1336, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest doc/source/user/absolute_beginners.rst[0]>", line 1, in <module>
        pd.set_option('max_columns', 10)
      File "/home/circleci/repo/venv/lib/python3.8/site-packages/pandas/_config/config.py", line 256, in __call__
        return self.__func__(*args, **kwds)
      File "/home/circleci/repo/venv/lib/python3.8/site-packages/pandas/_config/config.py", line 149, in _set_option
        key = _get_single_key(k, silent)
      File "/home/circleci/repo/venv/lib/python3.8/site-packages/pandas/_config/config.py", line 116, in _get_single_key
        raise OptionError("Pattern matched multiple keys")
    pandas._config.config.OptionError: 'Pattern matched multiple keys'


File "/tmp/tmp3kck6ceh/doc/source/user/absolute_beginners.rst", line 1596, in doc/source/user/absolute_beginners.rst
Failed example:
    print(df)
Expected:
              0         1         2         3
    0 -2.582892  0.430148 -1.240820  1.595726
    1  0.990278  1.171510  0.941257 -0.146925
    2  0.769893  0.812997 -0.950684  0.117696
    3  0.204840  0.347845  1.969792  0.519928
Got:
              0  ...         3
    0 -2.582892  ...  1.595726
    1  0.990278  ... -0.146925
    2  0.769893  ...  0.117696
    3  0.204840  ...  0.519928
    <BLANKLINE>
    [4 rows x 4 columns]


ERROR:  failed checking doc/source/user/absolute_beginners.rst

Exited with code exit status 1
```

</details>
