### ISSUE TITLE
BUG: arm cross-compile with gfortran requires F77 and F90 environment variable

### ISSUE THREAD

**Issue by virtuald** [numpy/numpy#20892]
### Describe the issue:

When cross-compiling numpy with gfortran, if you just set the `F90` environment variable then compilation fails. Specifying `F90` and `F77` works fine.

If this is intended, then it should be documented -- currently "building locally" documentation states "While a FORTRAN 77 compiler is not necessary for building NumPy...". However, before numpy 1.22 you could just specify `F90` and it would work fine.

### Reproduce the code example:

```python
N/A
```

### Error message:

```shell
INFO: building library "npymath" sources
  WARN: Could not locate executable armflang
  WARN: arm: no Fortran 77 compiler found
  Traceback (most recent call last):
    File "/build/venv/build/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 349, in <module>
      main()
    File "/build/venv/build/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 331, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/build/venv/build/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 248, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/build/venv/build/lib/python3.10/site-packages/setuptools/build_meta.py", line 221, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "/build/venv/build/lib/python3.10/site-packages/setuptools/build_meta.py", line 207, in _build_with_temp_dir
      self.run_setup()
    File "/build/venv/build/lib/python3.10/site-packages/setuptools/build_meta.py", line 258, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/build/venv/build/lib/python3.10/site-packages/setuptools/build_meta.py", line 150, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 454, in <module>
      setup_package()
    File "setup.py", line 446, in setup_package
      setup(**metadata)
    File "/tmp/pip-wheel-yu_hmk44/numpy_8134fe53435e49d6acd79141135e5516/numpy/distutils/core.py", line 169, in setup
      return old_setup(**new_attr)
    File "/build/venv/build/lib/python3.10/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/local/lib/python3.10/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/lib/python3.10/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/local/lib/python3.10/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-zn6asf13/overlay/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/usr/local/lib/python3.10/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/lib/python3.10/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-wheel-yu_hmk44/numpy_8134fe53435e49d6acd79141135e5516/numpy/distutils/command/build.py", line 61, in run
      old_build.run(self)
    File "/usr/local/lib/python3.10/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/local/lib/python3.10/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/lib/python3.10/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-wheel-yu_hmk44/numpy_8134fe53435e49d6acd79141135e5516/numpy/distutils/command/build_src.py", line 144, in run
      self.build_sources()
    File "/tmp/pip-wheel-yu_hmk44/numpy_8134fe53435e49d6acd79141135e5516/numpy/distutils/command/build_src.py", line 155, in build_sources
      self.build_library_sources(*libname_info)
    File "/tmp/pip-wheel-yu_hmk44/numpy_8134fe53435e49d6acd79141135e5516/numpy/distutils/command/build_src.py", line 288, in build_library_sources
      sources = self.generate_sources(sources, (lib_name, build_info))
    File "/tmp/pip-wheel-yu_hmk44/numpy_8134fe53435e49d6acd79141135e5516/numpy/distutils/command/build_src.py", line 378, in generate_sources
      source = func(extension, build_dir)
    File "/tmp/pip-wheel-yu_hmk44/numpy_8134fe53435e49d6acd79141135e5516/numpy/core/setup.py", line 696, in get_mathlib_info
      st = config_cmd.try_link(test_code, lang=lang)
    File "/usr/local/lib/python3.10/distutils/command/config.py", line 241, in try_link
      self._check_compiler()
    File "/tmp/pip-wheel-yu_hmk44/numpy_8134fe53435e49d6acd79141135e5516/numpy/distutils/command/config.py", line 80, in _check_compiler
      self.fcompiler = new_fcompiler(compiler=self.fcompiler,
    File "/tmp/pip-wheel-yu_hmk44/numpy_8134fe53435e49d6acd79141135e5516/numpy/distutils/fcompiler/__init__.py", line 880, in new_fcompiler
      compiler = get_default_fcompiler(plat, requiref90=requiref90,
    File "/tmp/pip-wheel-yu_hmk44/numpy_8134fe53435e49d6acd79141135e5516/numpy/distutils/fcompiler/__init__.py", line 851, in get_default_fcompiler
      compiler_type =  _find_existing_fcompiler(matching_compiler_types,
    File "/tmp/pip-wheel-yu_hmk44/numpy_8134fe53435e49d6acd79141135e5516/numpy/distutils/fcompiler/__init__.py", line 802, in _find_existing_fcompiler
      c.customize(dist)
    File "/tmp/pip-wheel-yu_hmk44/numpy_8134fe53435e49d6acd79141135e5516/numpy/distutils/fcompiler/__init__.py", line 542, in customize
      self.set_library_dirs(self.get_library_dirs())
    File "/tmp/pip-wheel-yu_hmk44/numpy_8134fe53435e49d6acd79141135e5516/numpy/distutils/fcompiler/arm.py", line 44, in get_library_dirs
      flang_dir = dirname(self.executables['compiler_f77'][0])
  TypeError: 'NoneType' object is not subscriptable
```

Also see https://github.com/robotpy/roborio-wheels/runs/4940781194?check_suite_focus=true
```


### NumPy/Python version information:

Python 3.10, Numpy 1.22.1

**Comment by rgommers** [comment]
> If this is intended, then it should be documented -- currently "building locally" documentation states "While a FORTRAN 77 compiler is not necessary for building NumPy...". However, before numpy 1.22 you could just specify F90 and it would work fine.

I have no idea what changed here. It certainly wasn't intended either way, since we never designed or supported cross-compilation properly.

I guess this issue will serve as documentation in case anyone else will run into this. This will go away when proper cross-compilation support arrives through Meson in the second half of this year. I propose we close this, because `numpy.distutils` is deprecated and there is a workaround.

**Comment by t-bltg** [comment]
I get the same error when using `f2py` with `mpi4py`.

Bisected to https://github.com/numpy/numpy/commit/5756700d4b549300f03f477e9b7693b2dadb6cae.

**Comment by InessaPawson** [comment]
> I guess this issue will serve as documentation in case anyone else will run into this. This will go away when proper cross-compilation support arrives through Meson in the second half of this year. I propose we close this, because `numpy.distutils` is deprecated and there is a workaround.

I'm closing the issue as per Ralf's (@rgommers) comment above.

**Comment by bilderbuchi** [comment]
I'm not sure if cross-compiling is necessary, I just hit this without (afaict) doing any cross-compilation. 
In my case, adding a `--f77exec` argument in addition to the `--f90exec` I already had in the f2py invocation avoids the issue.
