### ISSUE TITLE
ENH: ValueError subclass for invalid ndarray.__setitem__ values

### ISSUE THREAD

**Issue by jbrockmendel** [numpy/numpy#20923]
### Proposed new feature or change:

When setting values into an ndarray, there are at least two ways to get a ValueError (1.22.1):

```
arr = np.arange(5)

>>> arr[[1, 2]] = [4, 5, 6]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: shape mismatch: value array of shape (3,) could not be broadcast to indexing result of shape (2,)

>>> arr[0] = "foo"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: invalid literal for int() with base 10: 'foo'
```

For the relevant (pandas) use case, I want to only catch the latter.  This would be simplified by having a ValueError subclass   e.g. `NonCastableValueError(ValueError)`

**Comment by seberg** [comment]
Well, good timing, I am just losing sanity over these type of issues – but a much worse side of it :).

There is no _actual_ cast in this example because item assignments are subtly different from casts.  So I am dubious about a special error for failing casts/item assignment (possible, but are we sure we want to replace/chain the error there?).

However, we did discuss `BroadcastError` or `ShapeMismatch`(?) before, I think.  And I think that makes totally sense and may be just as well for you?

**Comment by jbrockmendel** [comment]
> However, we did discuss BroadcastError or ShapeMismatch(?) before, I think. And I think that makes totally sense and may be just as well for you?

I guess that way I'd still catch ValueError and then check-and-reraise with BroadcastError?  that would work just fine, yes

**Comment by seberg** [comment]
I suppose a pattern of:
```python3
try:
    ...
except BroadcastError:
    raise
except ValueError:
   # Not a broadcast-error
```
should also work.  The bigger point is that this needs to be done.  It should be pretty easy, but is a small project to track down most places in one go.
(I don't really see there being any resistance to such a more specific error class, right now.)
