### ISSUE TITLE
BUG: Error calculating the determinant and inverse of a matrix

### ISSUE THREAD

**Issue by jabernalv** [numpy/numpy#20932]
### Describe the issue:

I have tried the following in python 3.9.9 and also in python 3.9.7

An error occurs when calculating the determinant of a particular matrix, this also affects solving a system that implies that matrix.

### Reproduce the code example:

```python
import numpy as np
print(np.linalg.det(np.array([[0, 1, -4],[2, -3, 2],[5, -8, 7]])))
# In python 3.9.9 I obtain 2.2204460492503135e-15
# In python 3.9.7 I obtain 2.2204460492503135e-15
# The correct value is 0 as
print(np.linalg.det(np.array([[1, -1, 4], [3, 0, 1], [-1, 1, -4]])))
# In this case I obtain 0.0 in both systems

# Error affects solve too
np.linalg.solve(np.array([[0, 1, -4],[2, -3, 2],[5, -8, 7]]), np.array([8, 1, 1]))
# In 3.9.9 I obtain array([-1.12589991e+16, -9.00719925e+15, -2.25179981e+15])
# In 3.9.7 I obtain array([-9.00719925e+15 -7.20575940e+15 -1.80143985e+15])

# If I use other matrix the behaviour is 
np.linalg.solve(np.array([[1, -1, 4], [3, 0, 1], [-1, 1, -4]]), np.array([8, 1, 1]))

# In python 3.9.9 I obtain First Tracebak
# In python 3.9.7 I obtain Second Tracebak
```

### Error message:

```shell
First tracebak in python 3.9.9
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<__array_function__ internals>", line 180, in solve
  File "/usr/local/lib/python3.9/site-packages/numpy/linalg/linalg.py", line 393, in solve
    r = gufunc(a, b, signature=signature, extobj=extobj)
  File "/usr/local/lib/python3.9/site-packages/numpy/linalg/linalg.py", line 88, in _raise_linalgerror_singular
    raise LinAlgError("Singular matrix")
numpy.linalg.LinAlgError: Singular matrix

Second Traceback in python 3.9.7
---------------------------------------------------------------------------
LinAlgError                               Traceback (most recent call last)
/var/folders/yy/_v423z7j2_5d84v9srlbk4tm0000gn/T/ipykernel_3162/3906066552.py in <module>
----> 1 np.linalg.solve(np.array([[1, -1, 4], [3, 0, 1], [-1, 1, -4]]), np.array([8, 1, 1]))

<__array_function__ internals> in solve(*args, **kwargs)

~/opt/anaconda3/lib/python3.9/site-packages/numpy/linalg/linalg.py in solve(a, b)
    391     signature = 'DD->D' if isComplexType(t) else 'dd->d'
    392     extobj = get_linalg_error_extobj(_raise_linalgerror_singular)
--> 393     r = gufunc(a, b, signature=signature, extobj=extobj)
    394 
    395     return wrap(r.astype(result_t, copy=False))

~/opt/anaconda3/lib/python3.9/site-packages/numpy/linalg/linalg.py in _raise_linalgerror_singular(err, flag)
     86 
     87 def _raise_linalgerror_singular(err, flag):
---> 88     raise LinAlgError("Singular matrix")
     89 
     90 def _raise_linalgerror_nonposdef(err, flag):

LinAlgError: Singular matrix
```

### NumPy/Python version information:

In 3.9.9
1.22.1 3.9.9 (main, Nov 21 2021, 03:23:44) 
[Clang 13.0.0 (clang-1300.0.29.3)]

In 3.9.7
3.9.7 (default, Sep 16 2021, 08:50:36) 
[Clang 10.0.0 ]
1.20.3 3.9.7 (default, Sep 16 2021, 08:50:36) 
[Clang 10.0.0 ]

**Comment by melissawm** [comment]
Hi @jabernalv, this looks right to me. Small values such as `2.2204460492503135e-15` are the result of numerical computations where computing zero exactly is not always possible. This number is effectively so small it is telling you the matrix is singular. If your matrix is singular you can expect two things: results to be grossly innacurate/ill-conditioned (your first case) or the message about having a singular matrix, which is similar to a "divide-by-zero" error. Mathematically, you can't invert a singular matrix and this is what you see here. If you are looking to find a least-squares solution or something similar, you should look for `np.pinv`, for example.
