### ISSUE TITLE
BUG: Can't build on MacOS Monoterey

### ISSUE THREAD

**Issue by meow464** [numpy/numpy#21080]
### Describe the issue:

I can't build numpy on macos 12.

Information that might be relevant:
1. I'm using a venv;
2. `export SDKROOT="/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk"`;
3. `CFLAGS=" -v"`
4. `export MACOSX_DEPLOYMENT_TARGET=12_0`;
5. I'm using a custom openblas built for x86_64 only;
6. This is my site.cfg:
```
[openblas]
libraries = openblas
library_dirs = /Users/tuco/Projects/OpenBLAS/macOS/install/lib
include_dirs = /Users/tuco/Projects/OpenBLAS/macOS/install/include
```

### Reproduce the code example:

```python
git clone https://github.com/numpy/numpy.git
cd numpy && pip install .
```

### Error message:

<details>
<summary>
Long error
</summary>

```shell
Processing /Users/tuco/Projects/numpy/macOS/numpy
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: numpy
  Building wheel for numpy (pyproject.toml): started
  Building wheel for numpy (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error
  
  × Building wheel for numpy (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [125 lines of output]
      Processing numpy/random/_bounded_integers.pxd.in
      Processing numpy/random/_philox.pyx
      Processing numpy/random/_bounded_integers.pyx.in
      Processing numpy/random/_sfc64.pyx
      Processing numpy/random/_mt19937.pyx
      Processing numpy/random/bit_generator.pyx
      Processing numpy/random/mtrand.pyx
      Processing numpy/random/_generator.pyx
      Processing numpy/random/_pcg64.pyx
      Processing numpy/random/_common.pyx
      Cythonizing sources
      INFO: blas_opt_info:
      INFO: blas_armpl_info:
      INFO: customize UnixCCompiler
      INFO:   libraries armpl_lp64_mp not found in ['/Users/tuco/Projects/numpy/macOS/venv/lib', '/usr/local/lib', '/usr/lib']
      INFO:   NOT AVAILABLE
      INFO:
      INFO: blas_mkl_info:
      INFO:   libraries mkl_rt not found in ['/Users/tuco/Projects/numpy/macOS/venv/lib', '/usr/local/lib', '/usr/lib']
      INFO:   NOT AVAILABLE
      INFO:
      INFO: blis_info:
      INFO:   libraries blis not found in ['/Users/tuco/Projects/numpy/macOS/venv/lib', '/usr/local/lib', '/usr/lib']
      INFO:   NOT AVAILABLE
      INFO:
      INFO: openblas_info:
      INFO: C compiler: clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -iwithsysroot/System/Library/Frameworks/System.framework/PrivateHeaders -iwithsysroot/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/Headers -arch arm64 -arch x86_64 -Werror=implicit-function-declaration -v
      
      creating /var/folders/6p/3b9nf01x021bf5qxf_0pq1qr0000gn/T/tmpt17u5yrf/var
      creating /var/folders/6p/3b9nf01x021bf5qxf_0pq1qr0000gn/T/tmpt17u5yrf/var/folders
      creating /var/folders/6p/3b9nf01x021bf5qxf_0pq1qr0000gn/T/tmpt17u5yrf/var/folders/6p
      creating /var/folders/6p/3b9nf01x021bf5qxf_0pq1qr0000gn/T/tmpt17u5yrf/var/folders/6p/3b9nf01x021bf5qxf_0pq1qr0000gn
      creating /var/folders/6p/3b9nf01x021bf5qxf_0pq1qr0000gn/T/tmpt17u5yrf/var/folders/6p/3b9nf01x021bf5qxf_0pq1qr0000gn/T
      creating /var/folders/6p/3b9nf01x021bf5qxf_0pq1qr0000gn/T/tmpt17u5yrf/var/folders/6p/3b9nf01x021bf5qxf_0pq1qr0000gn/T/tmpt17u5yrf
      INFO: compile options: '-c'
      INFO: clang: /var/folders/6p/3b9nf01x021bf5qxf_0pq1qr0000gn/T/tmpt17u5yrf/source.c
      Apple clang version 13.0.0 (clang-1300.0.29.30)
      Target: x86_64-apple-darwin21.3.0
      Thread model: posix
      InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
      clang: error: invalid version number in 'MACOSX_DEPLOYMENT_TARGET=12_0'
      clang: error: invalid version number in 'MACOSX_DEPLOYMENT_TARGET=12_0'
      Running from numpy source directory.
      setup.py:86: DeprecationWarning:
      
        `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
        of the deprecation of `distutils` itself. It will be removed for
        Python >= 3.12. For older Python versions it will remain present.
        It is recommended to use `setuptools < 60.0` for those Python versions.
        For more details, see: TODO!
      
      
        import numpy.distutils.command.sdist
      numpy/core/setup.py:440: MismatchCAPIWarning: API mismatch detected, the C API version numbers have to be updated. Current C api version is 15, with checksum 04a7bf1e65350926a0e528798da263c0, but recorded checksum for C API version 15 in core/codegen_dir/cversions.txt is b8783365b873681cd204be50cdfb448d. If functions were added in the C API, you have to update C_API_VERSION in numpy/core/setup_common.py.
        check_api_version(C_API_VERSION, codegen_dir)
      Traceback (most recent call last):
        File "/Users/tuco/Projects/numpy/macOS/venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/Users/tuco/Projects/numpy/macOS/venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/tuco/Projects/numpy/macOS/venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 261, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/private/var/folders/6p/3b9nf01x021bf5qxf_0pq1qr0000gn/T/pip-build-env-pzxib59z/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 230, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
        File "/private/var/folders/6p/3b9nf01x021bf5qxf_0pq1qr0000gn/T/pip-build-env-pzxib59z/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 215, in _build_with_temp_dir
          self.run_setup()
        File "/private/var/folders/6p/3b9nf01x021bf5qxf_0pq1qr0000gn/T/pip-build-env-pzxib59z/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 267, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/private/var/folders/6p/3b9nf01x021bf5qxf_0pq1qr0000gn/T/pip-build-env-pzxib59z/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 158, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 492, in <module>
          setup_package()
        File "setup.py", line 484, in setup_package
          setup(**metadata)
        File "/Users/tuco/Projects/numpy/macOS/numpy/numpy/distutils/core.py", line 135, in setup
          config = configuration()
        File "setup.py", line 136, in configuration
          config.add_subpackage('numpy')
        File "/Users/tuco/Projects/numpy/macOS/numpy/numpy/distutils/misc_util.py", line 1054, in add_subpackage
          config_list = self.get_subpackage(subpackage_name, subpackage_path,
        File "/Users/tuco/Projects/numpy/macOS/numpy/numpy/distutils/misc_util.py", line 1020, in get_subpackage
          config = self._get_configuration_from_setup_py(
        File "/Users/tuco/Projects/numpy/macOS/numpy/numpy/distutils/misc_util.py", line 962, in _get_configuration_from_setup_py
          config = setup_module.configuration(*args)
        File "numpy/setup.py", line 9, in configuration
          config.add_subpackage('core')
        File "/Users/tuco/Projects/numpy/macOS/numpy/numpy/distutils/misc_util.py", line 1054, in add_subpackage
          config_list = self.get_subpackage(subpackage_name, subpackage_path,
        File "/Users/tuco/Projects/numpy/macOS/numpy/numpy/distutils/misc_util.py", line 1020, in get_subpackage
          config = self._get_configuration_from_setup_py(
        File "/Users/tuco/Projects/numpy/macOS/numpy/numpy/distutils/misc_util.py", line 962, in _get_configuration_from_setup_py
          config = setup_module.configuration(*args)
        File "numpy/core/setup.py", line 812, in configuration
          blas_info = get_info('blas_opt', 0)
        File "/Users/tuco/Projects/numpy/macOS/numpy/numpy/distutils/system_info.py", line 585, in get_info
          return cl().get_info(notfound_action)
        File "/Users/tuco/Projects/numpy/macOS/numpy/numpy/distutils/system_info.py", line 845, in get_info
          self.calc_info()
        File "/Users/tuco/Projects/numpy/macOS/numpy/numpy/distutils/system_info.py", line 2077, in calc_info
          if self._calc_info(blas):
        File "/Users/tuco/Projects/numpy/macOS/numpy/numpy/distutils/system_info.py", line 2063, in _calc_info
          return getattr(self, '_calc_info_{}'.format(name))()
        File "/Users/tuco/Projects/numpy/macOS/numpy/numpy/distutils/system_info.py", line 2000, in _calc_info_openblas
          info = get_info('openblas')
        File "/Users/tuco/Projects/numpy/macOS/numpy/numpy/distutils/system_info.py", line 585, in get_info
          return cl().get_info(notfound_action)
        File "/Users/tuco/Projects/numpy/macOS/numpy/numpy/distutils/system_info.py", line 845, in get_info
          self.calc_info()
        File "/Users/tuco/Projects/numpy/macOS/numpy/numpy/distutils/system_info.py", line 2283, in calc_info
          info = self._calc_info()
        File "/Users/tuco/Projects/numpy/macOS/numpy/numpy/distutils/system_info.py", line 2271, in _calc_info
          if not (skip_symbol_check or self.check_symbols(info)):
        File "/Users/tuco/Projects/numpy/macOS/numpy/numpy/distutils/system_info.py", line 2350, in check_symbols
          obj = c.compile([src], output_dir=tmpdir)
        File "/Users/tuco/Projects/numpy/macOS/numpy/numpy/distutils/ccompiler.py", line 89, in <lambda>
          m = lambda self, *args, **kw: func(self, *args, **kw)
        File "/Users/tuco/Projects/numpy/macOS/numpy/numpy/distutils/ccompiler.py", line 364, in CCompiler_compile
          single_compile(o)
        File "/Users/tuco/Projects/numpy/macOS/numpy/numpy/distutils/ccompiler.py", line 325, in single_compile
          self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
        File "/Users/tuco/Projects/numpy/macOS/numpy/numpy/distutils/ccompiler.py", line 89, in <lambda>
          m = lambda self, *args, **kw: func(self, *args, **kw)
        File "/Users/tuco/Projects/numpy/macOS/numpy/numpy/distutils/unixccompiler.py", line 58, in UnixCCompiler__compile
          raise CompileError(msg) from None
      distutils.errors.CompileError: Command "clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -iwithsysroot/System/Library/Frameworks/System.framework/PrivateHeaders -iwithsysroot/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/Headers -arch arm64 -arch x86_64 -Werror=implicit-function-declaration -v -c /var/folders/6p/3b9nf01x021bf5qxf_0pq1qr0000gn/T/tmpt17u5yrf/source.c -o /var/folders/6p/3b9nf01x021bf5qxf_0pq1qr0000gn/T/tmpt17u5yrf/var/folders/6p/3b9nf01x021bf5qxf_0pq1qr0000gn/T/tmpt17u5yrf/source.o -MMD -MF /var/folders/6p/3b9nf01x021bf5qxf_0pq1qr0000gn/T/tmpt17u5yrf/var/folders/6p/3b9nf01x021bf5qxf_0pq1qr0000gn/T/tmpt17u5yrf/source.o.d" failed with exit status 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for numpy
Failed to build numpy
ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects
```
</details>

### NumPy/Python version information:

Python 3.8.9
Numpy master and at least v1.20.2 (this is the version I'm interested in)

**Comment by meow464** [comment]
`CFLAGS="-Wno-error=implicit-function-declaration" NPY_BLAS_LIBS="openblas" pip install .`
