### ISSUE TITLE
GH_CPython importing numpy C-extensions failed

### ISSUE THREAD

**Issue by baolianliu** [numpy/numpy#21168]
### Describe the issue:

Hello! I am new to coding, and when I run GH_CPython in grasshopper, an error occurs when I "import numpy as np".

### Reproduce the code example:

```python
import numpy as np
```

### Error message:

```shell
Traceback (most recent call last):
  File "C:\Users\lighting\.conda\envs\envgraduation\lib\site-packages\numpy\core\__init__.py", line 22, in <module>
    from . import multiarray
  File "C:\Users\lighting\.conda\envs\envgraduation\lib\site-packages\numpy\core\multiarray.py", line 12, in <module>
    from . import overrides
  File "C:\Users\lighting\.conda\envs\envgraduation\lib\site-packages\numpy\core\overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: DLL load failed: 找不到指定的模块。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\GH_CPython\PythonFileWritten_1.py", line 9, in <module>
    import numpy as np
  File "C:\Users\lighting\.conda\envs\envgraduation\lib\site-packages\numpy\__init__.py", line 150, in <module>
    from . import core
  File "C:\Users\lighting\.conda\envs\envgraduation\lib\site-packages\numpy\core\__init__.py", line 48, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.7 from "C:\Users\lighting\.conda\envs\envgraduation\python.exe"
  * The NumPy version is: "1.21.5"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: DLL load failed: 找不到指定的模块。
```

### NumPy/Python version information:

Numpy: 1.21.5
python: 3.7.12

**Comment by melissawm** [comment]
Can you clarify how you installed numpy?

**Comment by baolianliu** [comment]
> 

I installed numpy in conda virtual enviroument in VS code.

**Comment by rgommers** [comment]
No more follow-up, and this was almost certainly a user-specific install issue. Hence I'll close this issue.
