### ISSUE TITLE
BUG: unique failing when data extracted from DataFrame

### ISSUE THREAD

**Issue by riedgar-ms** [numpy/numpy#21163]
### Describe the issue:

I'm having trouble with `np.unique()` when the source of the data is a pandas DataFrame. It appears that the datatype is not being correctly identified from pandas.

### Reproduce the code example:

```python
import numpy as np
import pandas as pd

data = [np.NaN, 'a', 'a', 'b']
df = pd.DataFrame({'col': data })

np.unique(data) # This works
np.unique(df['col']) # This fails
```

### Error message:

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<__array_function__ internals>", line 180, in unique
  File "<snip>\numpy\lib\arraysetops.py", line 272, in unique
    ret = _unique1d(ar, return_index, return_inverse, return_counts)
  File "<snip>\numpy\lib\arraysetops.py", line 333, in _unique1d
    ar.sort()
TypeError: '<' not supported between instances of 'str' and 'float'
```

### NumPy/Python version information:

1.22.2 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:19:05) [MSC v.1916 64 bit (AMD64)]

**Comment by rossbar** [comment]
> np.unique(data) # This works

This "works" in the numpy case because the `np.nan` is cast to a string:

```python
>>> data = [np.NaN, 'a', 'a', 'b']
>>> np.asarray(data)
array(['nan', 'a', 'a', 'b'], dtype='<U32')
```

In the pandas case it appears that the constructor recognizes that the data is heterogeneous (float and str) and preserves the heterogeneity:

```python
>>> df["col"].dtype
dtype('O')
```

So this boils down a difference in behavior between how pandas and numpy handle heterogeneous data for this particular case (float+str). The behavior is as expected on the numpy side:

```python
>>> np.result_type('f8', 'U1')
dtype('<U32')  # The `<` may vary depending on platform
```

I'm not sure what the expected behavior for pandas is - I'd suggest checking the pd docs and confirming this is the expected result (and opening an issue there if not).

Either way, IME working with mixed-type data can be tricky. When in doubt about the type of a dataset, it's best to be explicit so that you don't have to rely on the internal casting/coercion to decide the type for you.

**Comment by riedgar-ms** [comment]
The data are not heterogeneous so much as _missing_. We're going to examine whether our use of `np.unique` is appropriate in this case,  but at the very least it wasn't quite expected for `unique()` to give two different results (one an exception) based on the datastructure supplied.
