### ISSUE TITLE
DEV, CI: Gitpod build failure due to version parsing RuntimeError

### ISSUE THREAD

**Issue by rossbar** [numpy/numpy#21177]
### Describe the issue:

The CI job for building the GitPod docker image failed after a recent merge: https://github.com/numpy/numpy/runs/5500946679?check_suite_focus=true.

Relevant part of the traceback below:

```
#15 [build 5/6] RUN conda activate numpy-dev &&     python setup.py build_ext --inplace &&     ccache -s
#15 1.865 Traceback (most recent call last):
#15 1.865   File "/workspace/numpy/setup.py", line 64, in <module>
#15 1.866     raise RuntimeError(f'Cannot parse version {FULLVERSION}')
#15 1.866 RuntimeError: Cannot parse version 0+untagged.2.g4526ff4
#15 ERROR: process "/bin/bash --login -o pipefail -c conda activate ${CONDA_ENV} &&     python setup.py build_ext --inplace &&     ccache -s" did not complete successfully: exit code: 1
------
 > [build 5/6] RUN conda activate numpy-dev &&     python setup.py build_ext --inplace &&     ccache -s:
#15 1.865 Traceback (most recent call last):
#15 1.865   File "/workspace/numpy/setup.py", line 64, in <module>
#15 1.866     raise RuntimeError(f'Cannot parse version {FULLVERSION}')
#15 1.866 RuntimeError: Cannot parse version 0+untagged.2.g4526ff4
------
gitpod.Dockerfile:38
--------------------
  37 |     RUN git submodule update --init --depth=1 -- numpy/core/src/umath/svml
  38 | >>> RUN conda activate ${CONDA_ENV} && \ 
  39 | >>>     python setup.py build_ext --inplace && \
  40 | >>>     ccache -s
  41 |     
--------------------
error: failed to solve: process "/bin/bash --login -o pipefail -c conda activate ${CONDA_ENV} &&     python setup.py build_ext --inplace &&     ccache -s" did not complete successfully: exit code: 1
Error: buildx failed with: error: failed to solve: process "/bin/bash --login -o pipefail -c conda activate ${CONDA_ENV} &&     python setup.py build_ext --inplace &&     ccache -s" did not complete successfully: exit code: 1
```

### Reproduce the code example:

```python
N/A
```

### Error message:

```shell
N/A
```

### NumPy/Python version information:

Python version: presumably whatever is in the `environment.yml` file, which is currently pinned to 3.9
numpy version: 4526ff430df7

**Comment by bhavukkalra** [comment]
The Build failure seems to have been introduced in this commit [Simplify Scalar Value](https://github.com/numpy/numpy/commit/46a61b3aed3cf674586b456b05c6c9b7b9c5020d). The CI run logs are similar to what was shared above.

**Comment by rossbar** [comment]
Thanks @bhavukkalra , there's nothing in that commit (or the one linked above) that should've had any affect on the gitpod instance, so it's likely that something just changed elsewhere e.g. on gitpod's end.

**Comment by mattip** [comment]
Maybe this has to do with the recent release of 1.22.3 and the way the gitpod setup does a shallow clone?
