### ISSUE TITLE
BUG: Casting issue when using sign

### ISSUE THREAD

**Issue by YairMZ** [numpy/numpy#21194]
### Describe the issue:

It may not be a bug (as it may be by design), but I think it is.

Trying to set the output of `numpy.sign` to integers with a floating-point input raises an error due to casting.
The same casting on the original array (without calling the sign function) works.

If it is indeed deemed as a bug, I'll be happy to submit a fix, but I may need some guidance as this is my first issue here.

The workaround I show below can resolve the issue. However, the behavior is inconsistent as casting is allowed when not calling the `sign`, especially, as by the mathematical definition of the sign function, this casting will not result in any loss in precision.

### Reproduce the code example:

```python
import numpy as np
a = np.array(list(range(-5, 5)),dtype=np.float_)  # a is floating point array
b = np.sign(a, dtype=np.int_) # this row raises an exception
c = np.array(a, dtype=np.int_) # this works
d = np.sign(a, dtype=np.int_,,casting='unsafe') # a workaround
```

### Error message:

```shell
Traceback (most recent call last):
  File "/Users/yairmazal/.virtualenv/LDPC/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3251, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-719e498ab119>", line 1, in <module>
    b = np.sign(a, dtype=np.int_)
numpy.core._exceptions._UFuncInputCastingError: Cannot cast ufunc 'sign' input from dtype('float64') to dtype('int64') with casting rule 'same_kind'
```

### NumPy/Python version information:

1.22.1 3.9.10 (main, Jan 15 2022, 11:48:00) 
[Clang 13.0.0 (clang-1300.0.29.3)]

**Comment by alajoieumich** [comment]
I'm also willing to work on this issue; going to be looking into it soon

**Comment by seberg** [comment]
I would probably not call it a bug, but it may be an enhancement.

The issue is, it is not very easy.  There are two possibilities for approaching it:
1. Adding additional loops for `sign` that return `int8` for `float` input.  *And* add a new "promoter" to actually use them.
2. Add new API to allow the `float` loop to signal that casting to integer is OK in this exceptional case.

The first is probably more relevant.  But both will require deep dives into NumPy and C and into API that is new in NumPy itself (and barely used within NumPy itself!).

Given that, I am not sure it is worth the trouble if all we want is avoid `casting="unsafe"`.  Not that I ever want to discourage anyone from diving into this part of the NumPy code base.  But this is not a weekend project and right now, I am not even sure that the improvement is worth it.  (At least at this time, where the API that this must make use of is still new.)

So happy to give pointers for the first one, it will be learning a lot about how NumPy (now) works with ufuncs, but it will not be particularly easy (requires C knowledge) nor a sure thing.
