### ISSUE TITLE
BUG: assert_allclose chokes on large integers

### ISSUE THREAD

**Issue by h-vetinari** [numpy/numpy#21220]
The docstring of `all_close` [says](https://github.com/numpy/numpy/blob/v1.22.3/numpy/testing/_private/utils.py#L1476-L1480):
> Raises an AssertionError if two objects are not equal up to desired tolerance.

It's therefore IMO not unreasonable to assume that it should be possible to compare whether given arrays of integers and floats are within said tolerance of each other.

However, if the integers do not fit into the standard integer types anymore (which is still reasonable to compare against floats though!), this bombs with some casting error:
```
>>> import numpy as np
>>> from numpy.testing import assert_allclose
>>> from scipy.special import factorial
>>> assert_allclose(factorial(100), factorial(100, exact=True))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\[...]\.conda\envs\dev\lib\site-packages\numpy\testing\_private\utils.py", line 1530, in assert_allclose
    assert_array_compare(compare, actual, desired, err_msg=str(err_msg),
  File "C:\Users\[...]\.conda\envs\dev\lib\site-packages\numpy\testing\_private\utils.py", line 792, in assert_array_compare
    val = comparison(x, y)
  File "C:\Users\[...]\.conda\envs\dev\lib\site-packages\numpy\testing\_private\utils.py", line 1525, in compare
    return np.core.numeric.isclose(x, y, rtol=rtol, atol=atol,
  File "<__array_function__ internals>", line 180, in isclose
  File "C:\Users\[...]\.conda\envs\dev\lib\site-packages\numpy\core\numeric.py", line 2359, in isclose
    yfin = isfinite(y)
TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

# for reference
>>> factorial(100)
9.332621544394415e+157
>>> np.finfo(np.float64).max
1.7976931348623157e+308
>>> np.__version__
'1.22.3'
```

The same thing happens if the values are wrapped into `np.array()`. or `np.array([])`.

CC @seberg

**Comment by h-vetinari** [comment]
In other words, for comparing with a tolerance, I think there's no reason to cast safely, and this should just be cast to float directly.

**Comment by h-vetinari** [comment]
What's also interesting is that `assert_equal` does the correct thing _only_(?) when there's integer overflow?
```
>>> assert_equal(np.array([factorial(100)]), np.array([factorial(100, exact=True)]))
AssertionError:
Arrays are not equal

Mismatched elements: 1 / 1 (100%)
Max absolute difference: 0.0
Max relative difference: 0.0
 x: array([9.332622e+157])
 y: array([93326215443944152681699238856266700490715968264381621468592963895217599993229915608941463976156518286253697920827223758251185210916864000000000000000000000000],
      dtype=object)
```

However, with the (very distinctly not equal) following arrays, it does pass... 🤔 
```
>>> assert_equal(factorial(np.arange(0, 22), True), factorial(np.arange(0, 22), False))
>>> factorial(np.arange(0, 22), True)
array([1, 1, 2, 6, 24, 120, 720, 5040, 40320, 362880, 3628800, 39916800,
       479001600, 6227020800, 87178291200, 1307674368000, 20922789888000,
       355687428096000, 6402373705728000, 121645100408832000,
       2432902008176640000, 51090942171709440000], dtype=object)
>>> factorial(np.arange(0, 22), False)
array([1.00000000e+00, 1.00000000e+00, 2.00000000e+00, 6.00000000e+00,
       2.40000000e+01, 1.20000000e+02, 7.20000000e+02, 5.04000000e+03,
       4.03200000e+04, 3.62880000e+05, 3.62880000e+06, 3.99168000e+07,
       4.79001600e+08, 6.22702080e+09, 8.71782912e+10, 1.30767437e+12,
       2.09227899e+13, 3.55687428e+14, 6.40237371e+15, 1.21645100e+17,
       2.43290201e+18, 5.10909422e+19])
```

Don't want to spam issues, but happy to raise a separate one if this is considered a different problem.

**Comment by seberg** [comment]
Hmmm, I am not sure we should cast generic objects to `float64` forcibly for you, but as a workaround you can definitely do it here?  So casting the object/integer array to `float64` should give you what you need?  (With some annoying confusing on the way...)

---

I think the last observation is just due to the limited floating point precision?  At that range:
```
In [1]: np.spacing(5.10909422e+19)
Out[1]: 8192.0
```
It seems Python converts the float to an integer (and not the other way around) to compare, so this returns False:
```
int(9.332622e157) + 1 == 9.332622e157
```
(It is confusing, but with an `object` array there, we actually end up comparing a Python float with a Python int...)

---

The first problem is that we don't have an `isfinite` definition for Python objects at all.  I am not immediately sure there is a good way to define it.
These limitations come up occasionally.  I don't particularly love special casing float and decimal in the object ufuncs.  And if we try to avoid that, we would need a clear "protocol" to define NaN/Inf for generic objects.  (like `obj != obj` can be assumed reasonable for NaN maybe, `obj - obj != obj - obj` might well be an `isfinite`.
(Many `ufunc`s do try to call a method like `obj.isfinite()`.  This one does not, and I doubt it is typically super-useful.)

Another approach might be to rearrange the checks to only call into the `isfinite` when we absolutely have to.  We would have to puzzle a bit:  We need to reject `inf` positions not matching (and `NaN`, but that should be easy).  `inf` and relative tolerances may be problematic.
But I suspect it can be spelled in a way that we end up with `inf - inf => NaN` and then there is a mismatch.  And if `isfinite` doesn't work, we just report the mismatch  (meaning that checking whether `inf` and `nan` positions match up is just unsupported for `object` dtype).

**Comment by h-vetinari** [comment]
> but as a workaround you can definitely do it here?

Yeah, doing that now.

> (It is confusing, but with an `object` array there, we actually end up comparing a Python float with a Python int...)

I wondering whether safe cast are a reasonable expectation when only talking about relative accuracy anyway. As long as the inputs can be cast to float without raising an error, I fail to imagine a downside, but maybe I'm not seeing all angles?
