### ISSUE TITLE
BUG: can't reconstruct 2darray from double pointer ctypes array

### ISSUE THREAD

**Issue by TeusEE** [numpy/numpy#21335]
### Describe the issue:

i try to use dll using python ctypes.

before apply, i try to verify type(pointer(pointer(ctypes.c_double)) is available

test sequence is below
1. make numpy array with 2d
2. convert numpy 2d array to ctypes double pointer
3. reconstruct numpy 2d array from ctypes double pointer(using numpy.ctypeslib.as_array())

https://numpy.org/doc/stable/reference/routines.ctypeslib.html#module-numpy.ctypeslib

please check this issue.

even though i designate shape, it raise ValueError

### Reproduce the code example:

```python
import numpy as np
import ctypes
temp = [[i+i*k for i in range(50)] for k in range(10)]
temp = np.array(temp)
arr_c = temp.ctypes.data_as(ctypes.POINTER(ctypes.POINTER(ctypes.c_double)))
np.ctypeslib.as_array(arr_c, temp.shape)
```

### Error message:

```shell
Traceback (most recent call last):
  File "C:\Users\2066137\AppData\Local\Programs\Python\Python38\lib\site-packages\numpy\core\_internal.py", line 597, in _dtype_from_pep3118
    dtype, align = __dtype_from_pep3118(stream, is_subdtype=False)
  File "C:\Users\2066137\AppData\Local\Programs\Python\Python38\lib\site-packages\numpy\core\_internal.py", line 670, in __dtype_from_pep3118
    raise NotImplementedError(
NotImplementedError: Unrepresentable PEP 3118 data type '&' (pointers)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\2066137\AppData\Local\Programs\Python\Python38\lib\site-packages\numpy\ctypeslib.py", line 518, in as_array
    return asarray(obj)
ValueError: '&<d' is not a valid PEP 3118 buffer format string
```

### NumPy/Python version information:

numpy version = 1.21.5
python version = 3.8.7

**Comment by mattip** [comment]
Numpy stores its data as a single `void *`, not a double pointer. Change the conversion to
```
arr_c = temp.ctypes.data_as(ctypes.POINTER(ctypes.POINTER))
```

**Comment by mattip** [comment]
> how about add some comment in official c-types api docs?

[Improvements to the docs](https://numpy.org/doc/stable/dev/howto-docs.html) can be made by anyone.

**Comment by TeusEE** [comment]
> > how about add some comment in official c-types api docs?
> 
> [Improvements to the docs](https://numpy.org/doc/stable/dev/howto-docs.html) can be made by anyone.

i add PR [](https://github.com/numpy/numpy/pull/21458)

please review it :)
