### ISSUE TITLE
TST: Testing fails with pytest 7.1.2

### ISSUE THREAD

**Issue by seberg** [numpy/numpy#21441]
Currently, using a newer pytest fails to run the tests due to:
```python
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/sebastian/.local/lib/python3.9/site-packages/_pytest/main.py", line 264, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "/home/sebastian/.local/lib/python3.9/site-packages/_pytest/config/__init__.py", line 995, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "/home/sebastian/.local/lib/python3.9/site-packages/pluggy/hooks.py", line 308, in call_historic
INTERNALERROR>     res = self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/home/sebastian/.local/lib/python3.9/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/sebastian/.local/lib/python3.9/site-packages/pluggy/manager.py", line 84, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "/home/sebastian/.local/lib/python3.9/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/sebastian/.local/lib/python3.9/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/sebastian/.local/lib/python3.9/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/sebastian/.local/lib/python3.9/site-packages/pytest_asyncio/plugin.py", line 191, in pytest_configure
INTERNALERROR>     config.issue_config_time_warning(LEGACY_MODE, stacklevel=2)
INTERNALERROR>   File "/home/sebastian/.local/lib/python3.9/site-packages/_pytest/config/__init__.py", line 1342, in issue_config_time_warning
INTERNALERROR>     warnings.warn(warning, stacklevel=stacklevel)
INTERNALERROR> DeprecationWarning: The 'asyncio_mode' default value will change to 'strict' in future, please explicitly use 'asyncio_mode=strict' or 'asyncio_mode=auto' in pytest configuration file.
```

I am not immediately sure which mode is correct.  Plus, if I add it, pytest 6 will warn about the unknown option.

The fix should be to add the (correct) option and _also_ add a warning filter to suppress the warning on older pytest versions.  CI is pinned to a 6.x.y version currently, so we don't see it there.

**Comment by seberg** [comment]
Nevermind, this is due to pytest-asyncio (not sure what installed it).  Maybe they can make sure to not warn if the plugin isn't even used.
