### ISSUE TITLE
libatlas error 

### ISSUE THREAD

**Issue by NelsonGuiamba** [numpy/numpy#21535]
### Steps to reproduce:

I have installed it with piwheels then i builed from source and the error persists
Linux localhost 4.4.95+ #1 SMP PREEMPT Wed Jul 17 11:23:48 CST 2019 armv7l armv7l armv7l GNU/Linux
Note I have installed libatlas-base-dev

### Error message:

```shell
Python 3.9.12 (main, Apr 18 2022, 22:40:46)                                    [GCC 9.4.0] on linux                                                           Type "help", "copyright", "credits" or "license" for more information.         >>> import numpy                                                               Traceback (most recent call last):                                               File "/home/Nelson/jupyter/lib/python3.9/site-packages/numpy/core/__init__.py", line 23, in <module>                                                            from . import multiarray                                                     File "/home/Nelson/jupyter/lib/python3.9/site-packages/numpy/core/multiarray.py", line 10, in <module>                                                          from . import overrides                                                      File "/home/Nelson/jupyter/lib/python3.9/site-packages/numpy/core/overrides.py", line 6, in <module>                                                            from numpy.core._multiarray_umath import (
ImportError: libatlas.so.3: cannot enable executable stack as shared object requires: Permission denied                                                                                                                                      During handling of the above exception, another exception occurred:                                                                                           Traceback (most recent call last):                                               File "<stdin>", line 1, in <module>                                            File "/home/Nelson/jupyter/lib/python3.9/site-packages/numpy/__init__.py", line 144, in <module>                                                                from . import core                                                           File "/home/Nelson/jupyter/lib/python3.9/site-packages/numpy/core/__init__.py", line 49, in <module>                                                            raise ImportError(msg)                                                     ImportError:                                                                                                                                                  IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!                                                                                            Importing the numpy C-extensions failed. This error can happen for             many reasons, often due to issues with your setup or how NumPy was             installed.                                                                                                                                                    We have compiled some common reasons and troubleshooting tips at:                                                                                                 https://numpy.org/devdocs/user/troubleshooting-importerror.html                                                                                           Please note and check the following:                                                                                                                            * The Python version is: Python3.9 from "/home/Nelson/jupyter/bin/python3.9"   * The NumPy version is: "1.22.3"                                                                                                                            and make sure that they are the versions you expect.                           Please carefully study the documentation linked above for further help.                                                                                       Original error was: libatlas.so.3: cannot enable executable stack as shared object requires: Permission denied
```

**Comment by rossbar** [comment]
From the traceback this appears to be a permissions issue - consider checking how you installed `libatlas-base-dev` and verify that the installed files have the permissions you expect.

**Comment by seberg** [comment]
Indeed, this sounds like a SELinux limitation kicking in and also an issue in atlas itself.  I might suggest just trying OpenBLAS instead before diving into more tricky things?  Since OpenBLAS is the better choice anyway probably.
(I am not sure if OpenBLAS will have the same executable stack limitation though.)

**Comment by NelsonGuiamba** [comment]
@seberg you are right i disabled selinux now works but numpy.getinclude() is empty

**Comment by seberg** [comment]
As in the folder it points to is empty?  The headers should be copied in during the install.  It would seem that whatever you use to install (`piwheels`) would be missing them for some reason.

**Comment by rgommers** [comment]
No more follow-up and nothing seems wrong here, so closing. Thanks all.
