### ISSUE TITLE
Math Capabilities Detection Mechanism in v1.22.4 broken on Android Termux platform

### ISSUE THREAD

**Issue by ZhennanWu** [numpy/numpy#21584]
### Describe the issue:

The new math capabilities detection mechanism failed on Android Termux platform. Causing pip building failure. Bisection pinpointed the problem to be introduced between v1.22.3 to v1.22.4. Possibly due to https://github.com/numpy/numpy/commit/f2119f95b505b31cdfbf66e431544036238c8c68

### Background
Termux is an Android terminal emulator and Linux environment app that works directly with no rooting or setup required. https://termux.com/

### Reproduce the code example:

On a fresh Termux platform. Perform:
```
pkg install python 
pip install numpy==1.22.4
```

### Error message:

<details>

```shell
Collecting numpy==1.22.4
  Using cached numpy-1.22.4.zip (11.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: numpy
  Building wheel for numpy (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for numpy (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [267 lines of output]
      Running from numpy source directory.
      /tmp/pip-install-l_b969kc/numpy_d263c90bfe74495e84354e70cb670407/tools/cythonize.py:63: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
        from distutils.version import LooseVersion
      Processing numpy/random/_bounded_integers.pxd.in
      Processing numpy/random/_mt19937.pyx
      Processing numpy/random/_generator.pyx
      Processing numpy/random/_philox.pyx
      Processing numpy/random/_bounded_integers.pyx.in
      Processing numpy/random/_common.pyx
      Processing numpy/random/_sfc64.pyx
      Processing numpy/random/bit_generator.pyx
      Processing numpy/random/_pcg64.pyx
      Processing numpy/random/mtrand.pyx
      Cythonizing sources
      INFO: blas_opt_info:
      INFO: blas_armpl_info:
      INFO: customize UnixCCompiler
      INFO:   libraries armpl_lp64_mp not found in ['/data/data/com.termux/files/usr/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/aarch64-linux-gnu']
      INFO:   NOT AVAILABLE
      INFO:
      INFO: blas_mkl_info:
      INFO:   libraries mkl_rt not found in ['/data/data/com.termux/files/usr/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/aarch64-linux-gnu']
      INFO:   NOT AVAILABLE
      INFO:
      INFO: blis_info:
      INFO:   libraries blis not found in ['/data/data/com.termux/files/usr/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/aarch64-linux-gnu']
      INFO:   NOT AVAILABLE
      INFO:
      INFO: openblas_info:
      INFO:   libraries openblas not found in ['/data/data/com.termux/files/usr/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/aarch64-linux-gnu']
      INFO:   NOT AVAILABLE
      INFO:
      INFO: accelerate_info:
      INFO:   NOT AVAILABLE
      INFO:
      INFO: atlas_3_10_blas_threads_info:
      INFO: Setting PTATLAS=ATLAS
      INFO:   libraries tatlas not found in ['/data/data/com.termux/files/usr/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/aarch64-linux-gnu']
      INFO:   NOT AVAILABLE
      INFO:
      INFO: atlas_3_10_blas_info:
      INFO:   libraries satlas not found in ['/data/data/com.termux/files/usr/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/aarch64-linux-gnu']
      INFO:   NOT AVAILABLE
      INFO:
      INFO: atlas_blas_threads_info:
      INFO: Setting PTATLAS=ATLAS
      INFO:   libraries ptf77blas,ptcblas,atlas not found in ['/data/data/com.termux/files/usr/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/aarch64-linux-gnu']
      INFO:   NOT AVAILABLE
      INFO:
      INFO: atlas_blas_info:
      INFO:   libraries f77blas,cblas,atlas not found in ['/data/data/com.termux/files/usr/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/aarch64-linux-gnu']
      INFO:   NOT AVAILABLE
      INFO:
      /tmp/pip-install-l_b969kc/numpy_d263c90bfe74495e84354e70cb670407/numpy/distutils/system_info.py:2077: UserWarning:
          Optimized (vendor) Blas libraries are not found.
          Falls back to netlib Blas library which has worse performance.
          A better performance should be easily gained by switching
          Blas library.
        if self._calc_info(blas):
      INFO: blas_info:
      INFO:   libraries blas not found in ['/data/data/com.termux/files/usr/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/aarch64-linux-gnu']
      INFO:   NOT AVAILABLE
      INFO:
      /tmp/pip-install-l_b969kc/numpy_d263c90bfe74495e84354e70cb670407/numpy/distutils/system_info.py:2077: UserWarning:
          Blas (http://www.netlib.org/blas/) libraries not found.
          Directories to search for the libraries can be specified in the
          numpy/distutils/site.cfg file (section [blas]) or by setting
          the BLAS environment variable.
        if self._calc_info(blas):
      INFO: blas_src_info:
      INFO:   NOT AVAILABLE
      INFO:
      /tmp/pip-install-l_b969kc/numpy_d263c90bfe74495e84354e70cb670407/numpy/distutils/system_info.py:2077: UserWarning:
          Blas (http://www.netlib.org/blas/) sources not found.
          Directories to search for the sources can be specified in the
          numpy/distutils/site.cfg file (section [blas_src]) or by setting
          the BLAS_SRC environment variable.
        if self._calc_info(blas):
      INFO:   NOT AVAILABLE
      INFO:
      non-existing path in 'numpy/distutils': 'site.cfg'
      INFO: lapack_opt_info:
      INFO: lapack_armpl_info:
      INFO:   libraries armpl_lp64_mp not found in ['/data/data/com.termux/files/usr/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/aarch64-linux-gnu']
      INFO:   NOT AVAILABLE
      INFO:
      INFO: lapack_mkl_info:
      INFO:   libraries mkl_rt not found in ['/data/data/com.termux/files/usr/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/aarch64-linux-gnu']
      INFO:   NOT AVAILABLE
      INFO:
      INFO: openblas_lapack_info:
      INFO:   libraries openblas not found in ['/data/data/com.termux/files/usr/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/aarch64-linux-gnu']
      INFO:   NOT AVAILABLE
      INFO:
      INFO: openblas_clapack_info:
      INFO:   libraries openblas,lapack not found in ['/data/data/com.termux/files/usr/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/aarch64-linux-gnu']
      INFO:   NOT AVAILABLE
      INFO:
      INFO: flame_info:
      INFO:   libraries flame not found in ['/data/data/com.termux/files/usr/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/aarch64-linux-gnu']
      INFO:   NOT AVAILABLE
      INFO:
      INFO: atlas_3_10_threads_info:
      INFO: Setting PTATLAS=ATLAS
      INFO:   libraries tatlas,tatlas not found in /data/data/com.termux/files/usr/lib
      INFO:   libraries tatlas,tatlas not found in /usr/local/lib
      INFO:   libraries tatlas,tatlas not found in /usr/lib
      INFO:   libraries tatlas,tatlas not found in /usr/lib/aarch64-linux-gnu
      INFO: <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
      INFO:   NOT AVAILABLE
      INFO:
      INFO: atlas_3_10_info:
      INFO:   libraries satlas,satlas not found in /data/data/com.termux/files/usr/lib
      INFO:   libraries satlas,satlas not found in /usr/local/lib
      INFO:   libraries satlas,satlas not found in /usr/lib
      INFO:   libraries satlas,satlas not found in /usr/lib/aarch64-linux-gnu
      INFO: <class 'numpy.distutils.system_info.atlas_3_10_info'>
      INFO:   NOT AVAILABLE
      INFO:
      INFO: atlas_threads_info:
      INFO: Setting PTATLAS=ATLAS
      INFO:   libraries ptf77blas,ptcblas,atlas not found in /data/data/com.termux/files/usr/lib
      INFO:   libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib
      INFO:   libraries ptf77blas,ptcblas,atlas not found in /usr/lib
      INFO:   libraries ptf77blas,ptcblas,atlas not found in /usr/lib/aarch64-linux-gnu
      INFO: <class 'numpy.distutils.system_info.atlas_threads_info'>
      INFO:   NOT AVAILABLE
      INFO:
      INFO: atlas_info:
      INFO:   libraries f77blas,cblas,atlas not found in /data/data/com.termux/files/usr/lib
      INFO:   libraries f77blas,cblas,atlas not found in /usr/local/lib
      INFO:   libraries f77blas,cblas,atlas not found in /usr/lib
      INFO:   libraries f77blas,cblas,atlas not found in /usr/lib/aarch64-linux-gnu
      INFO: <class 'numpy.distutils.system_info.atlas_info'>
      INFO:   NOT AVAILABLE
      INFO:
      INFO: lapack_info:
      INFO:   libraries lapack not found in ['/data/data/com.termux/files/usr/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/aarch64-linux-gnu']
      INFO:   NOT AVAILABLE
      INFO:
      /tmp/pip-install-l_b969kc/numpy_d263c90bfe74495e84354e70cb670407/numpy/distutils/system_info.py:1902: UserWarning:
          Lapack (http://www.netlib.org/lapack/) libraries not found.
          Directories to search for the libraries can be specified in the
          numpy/distutils/site.cfg file (section [lapack]) or by setting
          the LAPACK environment variable.
        return getattr(self, '_calc_info_{}'.format(name))()
      INFO: lapack_src_info:
      INFO:   NOT AVAILABLE
      INFO:
      /tmp/pip-install-l_b969kc/numpy_d263c90bfe74495e84354e70cb670407/numpy/distutils/system_info.py:1902: UserWarning:
          Lapack (http://www.netlib.org/lapack/) sources not found.
          Directories to search for the sources can be specified in the
          numpy/distutils/site.cfg file (section [lapack_src]) or by setting
          the LAPACK_SRC environment variable.
        return getattr(self, '_calc_info_{}'.format(name))()
      INFO:   NOT AVAILABLE
      INFO:
      INFO: numpy_linalg_lapack_lite:
      INFO:   FOUND:
      INFO:     language = c
      INFO:     define_macros = [('HAVE_BLAS_ILP64', None), ('BLAS_SYMBOL_SUFFIX', '64_')]
      INFO:
      Warning: attempted relative import with no known parent package
      /data/data/com.termux/files/usr/lib/python3.10/distutils/dist.py:274: UserWarning: Unknown distribution option: 'define_macros'
        warnings.warn(msg)
      running bdist_wheel
      running build
      running config_cc
      INFO: unifing config_cc, config, build_clib, build_ext, build commands --compiler options
      running config_fc
      INFO: unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
      running build_src
      INFO: build_src
      INFO: building py_modules sources
      creating build
      creating build/src.linux-aarch64-3.10
      creating build/src.linux-aarch64-3.10/numpy
      creating build/src.linux-aarch64-3.10/numpy/distutils
      INFO: building library "npymath" sources
      WARN: Could not locate executable armflang
      WARN: Could not locate executable gfortran
      WARN: Could not locate executable f95
      WARN: Could not locate executable ifort
      WARN: Could not locate executable ifc
      WARN: Could not locate executable lf95
      WARN: Could not locate executable pgfortran
      WARN: Could not locate executable nvfortran
      WARN: Could not locate executable f90
      WARN: Could not locate executable f77
      WARN: Could not locate executable fort
      WARN: Could not locate executable efort
      WARN: Could not locate executable efc
      WARN: Could not locate executable g77
      WARN: Could not locate executable g95
      WARN: Could not locate executable pathf95
      WARN: Could not locate executable nagfor
      WARN: Could not locate executable frt
      WARN: don't know how to compile Fortran code on platform 'posix'
      creating build/src.linux-aarch64-3.10/numpy/core
      creating build/src.linux-aarch64-3.10/numpy/core/src
      creating build/src.linux-aarch64-3.10/numpy/core/src/npymath
      INFO: conv_template:> build/src.linux-aarch64-3.10/numpy/core/src/npymath/npy_math_internal.h
      INFO:   adding 'build/src.linux-aarch64-3.10/numpy/core/src/npymath' to include_dirs.
      INFO: conv_template:> build/src.linux-aarch64-3.10/numpy/core/src/npymath/ieee754.c
      INFO: conv_template:> build/src.linux-aarch64-3.10/numpy/core/src/npymath/npy_math_complex.c
      INFO: None - nothing done with h_files = ['build/src.linux-aarch64-3.10/numpy/core/src/npymath/npy_math_internal.h']
      INFO: building library "npyrandom" sources
      INFO: building extension "numpy.core._multiarray_tests" sources
      creating build/src.linux-aarch64-3.10/numpy/core/src/multiarray
      INFO: conv_template:> build/src.linux-aarch64-3.10/numpy/core/src/multiarray/_multiarray_tests.c
      INFO: building extension "numpy.core._multiarray_umath" sources
      Traceback (most recent call last):
        File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 261, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/tmp/pip-build-env-wqbb3dac/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 230, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
        File "/tmp/pip-build-env-wqbb3dac/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 215, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-wqbb3dac/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 267, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/tmp/pip-build-env-wqbb3dac/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 158, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 461, in <module>
          setup_package()
        File "setup.py", line 453, in setup_package
          setup(**metadata)
        File "/tmp/pip-install-l_b969kc/numpy_d263c90bfe74495e84354e70cb670407/numpy/distutils/core.py", line 169, in setup
          return old_setup(**new_attr)
        File "/tmp/pip-build-env-wqbb3dac/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/data/data/com.termux/files/usr/lib/python3.10/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/data/data/com.termux/files/usr/lib/python3.10/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/data/data/com.termux/files/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-wqbb3dac/overlay/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "/data/data/com.termux/files/usr/lib/python3.10/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/data/data/com.termux/files/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/tmp/pip-install-l_b969kc/numpy_d263c90bfe74495e84354e70cb670407/numpy/distutils/command/build.py", line 61, in run
          old_build.run(self)
        File "/data/data/com.termux/files/usr/lib/python3.10/distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/data/data/com.termux/files/usr/lib/python3.10/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/data/data/com.termux/files/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/tmp/pip-install-l_b969kc/numpy_d263c90bfe74495e84354e70cb670407/numpy/distutils/command/build_src.py", line 144, in run
          self.build_sources()
        File "/tmp/pip-install-l_b969kc/numpy_d263c90bfe74495e84354e70cb670407/numpy/distutils/command/build_src.py", line 161, in build_sources
          self.build_extension_sources(ext)
        File "/tmp/pip-install-l_b969kc/numpy_d263c90bfe74495e84354e70cb670407/numpy/distutils/command/build_src.py", line 318, in build_extension_sources
          sources = self.generate_sources(sources, ext)
        File "/tmp/pip-install-l_b969kc/numpy_d263c90bfe74495e84354e70cb670407/numpy/distutils/command/build_src.py", line 378, in generate_sources
          source = func(extension, build_dir)
        File "/tmp/pip-install-l_b969kc/numpy_d263c90bfe74495e84354e70cb670407/numpy/core/setup.py", line 508, in generate_config_h
          check_math_capabilities(config_cmd, ext, moredefs, mathlibs)
        File "/tmp/pip-install-l_b969kc/numpy_d263c90bfe74495e84354e70cb670407/numpy/core/setup.py", line 171, in check_math_capabilities
          raise SystemError("One of the required function to build numpy is not"
      SystemError: One of the required function to build numpy is not available (the list is ['sin', 'cos', 'tan', 'sinh', 'cosh', 'tanh', 'fabs', 'floor', 'ceil', 'sqrt', 'log10', 'log', 'exp', 'asin', 'acos', 'atan', 'fmod', 'modf', 'frexp', 'ldexp']).
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for numpy
Failed to build numpy
ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects
```
```


### NumPy/Python version information:

Python version: 3.10.4

**Comment by seberg** [comment]
If this fails, I think what must be happening is that compiling/linking (aginst `-lm` I guess):
```C
#ifdef _MSC_VER
#pragma function(sin)
#pragma function(cos)
#pragma function(tan)
#pragma function(sinh)
#pragma function(cosh)
#pragma function(tanh)
#pragma function(fabs)
#pragma function(floor)
#pragma function(ceil)
#pragma function(sqrt)
#pragma function(log10)
#pragma function(log)
#pragma function(exp)
#pragma function(asin)
#pragma function(acos)
#pragma function(atan)
#pragma function(fmod)
#pragma function(modf)
#pragma function(frexp)
#pragma function(ldexp)
#endif
int main (void) {
  sin((double) 0);
  cos((double) 0);
  tan((double) 0);
  sinh((double) 0);
  cosh((double) 0);
  tanh((double) 0);
  fabs((double) 0);
  floor((double) 0);
  ceil((double) 0);
  sqrt((double) 0);
  log10((double) 0);
  log((double) 0);
  exp((double) 0);
  asin((double) 0);
  acos((double) 0);
  atan((double) 0);
  fmod((double) 0, (double) 0);
  modf((double) 0, (double*) 0);
  frexp((double) 0, (int*) 0);
  ldexp((double) 0, (int) 0);
  return 0;
}
```
fails during setup.  Could you investigate why it is failing?

**Comment by seberg** [comment]
Thanks, so from there, the problem seems to be the mathlib discovery, which uses:
```
    for libs in mathlibs_choices:
         if config_cmd.check_func(
             "log",
             libraries=libs,
             call_args="0",
             decl="double log(double);",
             call=True
         ):
```
which for some reason takes a wrong turn (maybe not using any mathlib at all?).  The older version used `exp` and it worked apparently.
I am wondering if `log(0)` in itself might be a problem, or whether `log` just happens to succeed without `-lm`?

At least the plot is thickening :).

**Comment by Grimler91** [comment]
Seem to be that checking for `log` isn't enough on this platform. If I read [check_func code](https://github.com/numpy/numpy/blob/v1.22.4/numpy/distutils/command/config.py#L316) correctly it looks the code that is compiled and run currently is

```c
double log(double);
int main (void) {
  log(0);
  return 0;
}
```
vs before
```c
int exp (void);
int main (void) {
  exp();
  return 0;
}
```

If I put this code in `test_log.c` and `test_exp.c` and compile and run with something like `clang -o test test_log.c && ./test` I get:

```
$ clang -o test test_log.c && ./test
test_log.c:3:3: warning: ignoring return value of function declared with const attribute [-Wunused-value]
  log(0);
  ^~~ ~
1 warning generated.
```
and
```
$ clang -o test test_exp.c && ./test
test_exp.c:1:5: warning: incompatible redeclaration of library function 'exp' [-Wincompatible-library-redeclaration]
int exp (void);
    ^
test_exp.c:1:5: note: 'exp' is a builtin with type 'double (double)'
1 warning generated.
ld.lld: error: undefined symbol: exp
>>> referenced by test_exp.c
>>>               /data/data/com.termux/files/usr/tmp/test_exp-85a73f.o:(main)
clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
```

If I change log test to:

```c
double log(double);
int main (void) {
  double v = log(0);
  return 0;
}
```
it also fails without `-lm` (as it should): 
```
$ clang -o test test_log.c && ./test
ld.lld: error: undefined symbol: log
>>> referenced by test_log.c
>>>               /data/data/com.termux/files/usr/tmp/test_log-d69854.o:(main)
clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by Grimler91** [comment]
Just changing the declaration and usage of `log` also works:
```
$ cat test_log.c
int log (void);
int main (void) {
  log();
  return 0;
}
$ clang -o test test_log.c && ./test
test_log.c:1:5: warning: incompatible redeclaration of library function 'log' [-Wincompatible-library-redeclaration]
int log (void);
    ^
test_log.c:1:5: note: 'log' is a builtin with type 'double (double)'
1 warning generated.
ld.lld: error: undefined symbol: log
>>> referenced by test_log.c
>>>               /data/data/com.termux/files/usr/tmp/test_log-c4330f.o:(main)
clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by seberg** [comment]
I think that incorrect signature was also exactly the problem that `wasm` needed us to fix and why the patch landed.  So I don't think that is a good solution.

I know its stabbing randomly, but would it work to use a weirder math function?  If using the return value works, then that seems better, but I am still not sure how easy that is to insert there.

**Comment by Grimler91** [comment]
> I know its stabbing randomly, but would it work to use a weirder math function?

Using functions like `fmod` or `ldexp` doesn't work either, but for whatever reason using the hyperbolicus or inverse trigonometric functions work:

```
$ cat test_sinh.c 
double sinh(double);
int main (void) {
  sinh(0);
  return 0;
}
$ clang -o test test_sinh.c && ./test
test_sinh.c:3:3: warning: ignoring return value of function declared with const attribute [-Wunused-value]
  sinh(0);
  ^~~~ ~
1 warning generated.
ld.lld: error: undefined symbol: sinh
>>> referenced by test_sinh.c
>>>               /data/data/com.termux/files/usr/tmp/test_sinh-5b6f3a.o:(main)
clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
```

I therefore expected this to work:

```diff
diff --git a/numpy/core/setup.py b/numpy/core/setup.py
index 157c825d2a1e..404682e44237 100644
--- a/numpy/core/setup.py
+++ b/numpy/core/setup.py
@@ -435,10 +435,10 @@ def check_mathlib(config_cmd):
         mathlibs_choices.insert(0, mathlib.split(","))
     for libs in mathlibs_choices:
         if config_cmd.check_func(
-            "log",
+            "sinh",
             libraries=libs,
             call_args="0",
-            decl="double log(double);",
+            decl="double sinh(double);",
             call=True
         ):
             mathlibs = libs
```

but it still fails, numpy still sets `mathlib=[]`. 
What compiler args does the [`try_link` function](https://github.com/numpy/numpy/blob/623bc1fae1d47df24e7f1e29321d0c0ba2771ce0/numpy/distutils/command/config.py#L347) use? If I use anything higher than `-O0` the test above fails also with sinh:

```
$ clang -O1 -o test test_sinh.c && ./test
test_sinh.c:3:3: warning: ignoring return value of function declared with const attribute [-Wunused-value]
  sinh(0);
  ^~~~ ~
1 warning generated.
```
so I guess that might be what happens in this case.

**Comment by seberg** [comment]
So, I guess that MSVC pragma is there exactly for the same kind of reason...  The code is generated here:
https://github.com/numpy/numpy/blob/9c68c2f7b1b2128a3b4af2134565f60d286fa8b9/numpy/distutils/command/config.py#L316-L348

So we need to find some weird way of making it work :).  We can use the return value, was that enough?  Otherwise the heavy machinery that I think might work is storing the symbol in a function pointer and then executing that?  But, I do wonder if that may not come with its own set of problems...

**Comment by Grimler91** [comment]
Seems return value on its own is not enough either, but if main() is also marked `__attribute((optnone))` it works, so maybe something like this patch could be acceptable:

```diff
diff --git a/numpy/distutils/command/config.py b/numpy/distutils/command/config.py
index 1f4037bb5c7a..b29a8e796f31 100644
--- a/numpy/distutils/command/config.py
+++ b/numpy/distutils/command/config.py
@@ -333,11 +333,11 @@ def check_func(self, func,
         body.append("#ifdef _MSC_VER")
         body.append("#pragma function(%s)" % func)
         body.append("#endif")
-        body.append("int main (void) {")
+        body.append("int main (void) __attribute((optnone)) {")
         if call:
             if call_args is None:
                 call_args = ''
-            body.append("  %s(%s);" % (func, call_args))
+            body.append("  double v = %s(%s);" % (func, call_args))
         else:
             body.append("  %s;" % func)
         body.append("  return 0;")
```

probably `v`'s type should not be hardcoded though

**Comment by Grimler91** [comment]
> Adding the attribute is fine of course, but needs to be guarded for compiler support.

Which compilers does numpy support? 
Clang should support optnone, while for gcc it seems we need to use `__attribute__((optimize("O0")))` instead (or skip it altogether). 

Is it enough to make sure the change passes the CI checks?

**Comment by rgommers** [comment]
> Which compilers does numpy support?

A very large amount, including ones we have no access to or know about (like on supercomputers). 

> Is it enough to make sure the change passes the CI checks?

No, that won't be robust. For nonstandard attributes, the best way is doing a compiler check to see if the attribute is accepted. There is code to support that kind of check in `numpy.distutils`. Here are some checked attributes, following those should get you to the right place: https://github.com/numpy/numpy/blob/2b5328c287539db7f96dc488409557a75c67db74/numpy/core/setup_common.py#L206

**Comment by rgommers** [comment]
These checks all changed with the update to Meson as the build system in `1.26.0` and `main`. It'd be great if a Termux user could check the status of building 1.26.0 and open a new issue if it's not working.

**Comment by GalaxySnail** [comment]
I encountered #24873 while building numpy 1.26.0 on termux, and the `main` branch was successfully built. I think this issue can be closed now.

**Comment by rgommers** [comment]
Great, thanks @GalaxySnail!
