### ISSUE TITLE
BUG: regression 1.22.4: error on exiting mmap context with buffered array

### ISSUE THREAD

**Issue by jhidding** [numpy/numpy#21640]
### Describe the issue:

The enclosed minimal code example runs correctly with Numpy version 1.22.3.

The bug is triggered when a `mmap` context is left with a Numpy buffered array pointing to that `mmap` buffer.

### Reproduce the code example:

```python
import numpy as np
import mmap
from contextlib import contextmanager

data = np.arange(10, dtype=np.int32)
with open("test.bin", "wb") as f_out:
    data.tofile(f_out)

@contextmanager
def my_data():
    with open("test.bin", "r+b") as f_in:
        with mmap.mmap(f_in.fileno(), 0) as mm:
            content = np.frombuffer(mm, dtype=np.int32, count=10, offset=0)
            yield content

with my_data() as d:
    print(d)
```

### Error message:

```shell
Traceback (most recent call last):
  File "/mnt/data/Code/windfarms/cylinder/numpy_bug.py", line 16, in <module>
    with my_data() as d:
  File "/usr/lib64/python3.10/contextlib.py", line 142, in __exit__
    next(self.gen)
  File "/mnt/data/Code/windfarms/cylinder/numpy_bug.py", line 12, in my_data
    with mmap.mmap(f_in.fileno(), 0) as mm:
BufferError: cannot close exported pointers exist
```

### NumPy/Python version information:

1.22.4 3.10.4 (main, Mar 25 2022, 00:00:00) [GCC 12.0.1 20220308 (Red Hat 12.0.1-0)]

**Comment by jhidding** [comment]
This could be related to issue #21324. However, this code snippet should be completely safe, using context managers throughout.

**Comment by charris** [comment]
Can you try NumPy 1.23.0rc2 to see if this was fixed?

**Comment by jhidding** [comment]
I took a look at the unit-test that came with the changes that were introduced. To get rid of the error it is not enough to `del content` after the `yield` statement in my code example. I have to add `del d` at the end as well, which seems odd.

**Comment by jhidding** [comment]
It seems I was understanding context managers wrong. The following code:

```python
@contextmanager
def test():
    yield "Hello"

with test() as t:
    print(f"in context: {t}")
print(f"out of context: {t}")
```

is valid Python. Adding a final print statement `print(d)` after the `with` block in my code example will give a segmentation fault in Numpy 1.22.3, but raises an exception in 1.22.4. To fix my code I would have to yield a box with a reference to the numpy array, then deleting the reference in the `__exit__` part of the context manager, so that the numpy array can no longer be reached.

Would there be a way to release the buffer of an existing Numpy array, setting the contents to `[]`?

**Comment by seberg** [comment]
Yeah, unfortunately it is a feature to prevent that segfault, so I really would prefer not to back it out.

> Would there be a way to release the buffer of an existing Numpy array, setting the contents to []?

No, I doubt that can work reasonably.  NumPy has no proper understanding of a "closed" array at this time.

> But it's not so pretty.

That is fair.  But yeah, it seems you either need the user to `del content` before the block ends or wrap `content`, which mainly makes that `del` need more explicit (and hopefully unnecessary).

Maybe a bit nicer could be to use a `weakref` if just to avoid the custom wrapper:
```
import weakref

def my_data():
    with ...:
        arr = np.frombuffer(...)
        yield weakref.ref(arr)
```
Giving basically the same API, but as `content()` rather than `content.value()`.

Another approach to refining your solution would be to define `Box.__array__()` rather than `Box.value`.  That way, `Box` "represents" the data and can be directly passed to NumPy functions anyway.
But that probably is just a bit of additional API here to make it a bit more convenient.

You _can_ get the old behavior if you try hard right now.  But then you would get that segfault back...
