### ISSUE TITLE
BUG: Build from source using Intel oneAPI compiler fails with IndexError in distutils/ccompiler.py due to last_cmdline being empty

### ISSUE THREAD

**Issue by wilsonzlin** [numpy/numpy#21741]
### Describe the issue:

When building a wheel of [NumPy 1.22.4](https://github.com/numpy/numpy/releases/download/v1.22.4/numpy-1.22.4.tar.gz) from source using Intel oneAPI and `icc`, the build appears to complete but then fail at the end due to trying to access an unexpected empty list in `distutils/ccompiler.py`.

## site.cfg

```
[mkl]
library_dirs = /oneapi/mkl/latest/lib/intel64
include_dirs = /oneapi/mkl/latest/include
libraries = mkl_rt
```

## Final stdout output

```
########### EXT COMPILER OPTIMIZATION ###########
INFO: Platform      :
  Architecture: x64
  Compiler    : icc

CPU baseline  :
  Requested   : 'native'
  Enabled     : SSE SSE2 SSE3 SSSE3 SSE41 POPCNT SSE42 AVX F16C FMA3 AVX2 AVX512F AVX512CD AVX512_SKX AVX512_CLX AVX512_CNL AVX512_ICL
  Flags       : -xICELAKE-CLIENT
  Extra checks: AVX512F_REDUCE AVX512BW_MASK AVX512DQ_MASK

CPU dispatch  :
  Requested   : 'none'
  Enabled     : none
  Generated   : none
INFO: CCompilerOpt.cache_flush[825] : write cache to path -> /tmpdir/numpy/build/temp.linux-x86_64-3.10/ccompiler_opt_cache_ext.py
INFO:
########### CLIB COMPILER OPTIMIZATION ###########
INFO: Platform      :
  Architecture: x64
  Compiler    : icc

CPU baseline  :
  Requested   : 'native'
  Enabled     : SSE SSE2 SSE3 SSSE3 SSE41 POPCNT SSE42 AVX F16C FMA3 AVX2 AVX512F AVX512CD AVX512_SKX AVX512_CLX AVX512_CNL AVX512_ICL
  Flags       : -xICELAKE-CLIENT
  Extra checks: AVX512F_REDUCE AVX512BW_MASK AVX512DQ_MASK

CPU dispatch  :
  Requested   : 'none'
  Enabled     : none
  Generated   : none
INFO: CCompilerOpt.cache_flush[825] : write cache to path -> /tmpdir/numpy/build/temp.linux-x86_64-3.10/ccompiler_opt_cache_clib.py
```

### Reproduce the code example:

```python
pip install Cython setuptools wheel
source '/oneapi/compiler/latest/env/vars.sh' && NPY_BLAS_ORDER=MKL NPY_LAPACK_ORDER=MKL python setup.py build -j $(getconf _NPROCESSORS_ONLN) --cpu-baseline=native --cpu-dispatch=none --compiler=intelem --fcompiler=intelem bdist_wheel
```

### Error message:

```shell
Traceback (most recent call last):
  File "/tmpdir/numpy/setup.py", line 461, in <module>
    setup_package()
  File "/tmpdir/numpy/setup.py", line 453, in setup_package
    setup(**metadata)
  File "/tmpdir/numpy/numpy/distutils/core.py", line 169, in setup
    return old_setup(**new_attr)
  File "/python3.10/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/python3.10/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/python3.10/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/python3.10/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/tmpdir/numpy/numpy/distutils/command/build.py", line 61, in run
    old_build.run(self)
  File "/python3.10/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/python3.10/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/python3.10/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/tmpdir/numpy/numpy/distutils/command/build_ext.py", line 332, in run
    self.build_extensions()
  File "/python3.10/distutils/command/build_ext.py", line 447, in build_extensions
    self._build_extensions_parallel()
  File "/python3.10/distutils/command/build_ext.py", line 469, in _build_extensions_parallel
    fut.result()
  File "/python3.10/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/python3.10/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmpdir/numpy/setup.py", line 235, in build_extension
    build_ext.build_extension(self, ext)
  File "/tmpdir/numpy/numpy/distutils/command/build_ext.py", line 502, in build_extension
    c_objects += self.compiler.compile(
  File "/tmpdir/numpy/numpy/distutils/ccompiler.py", line 89, in <lambda>
    m = lambda self, *args, **kw: func(self, *args, **kw)
  File "/tmpdir/numpy/numpy/distutils/ccompiler.py", line 361, in CCompiler_compile
    list(res)  # access result to raise errors
  File "/python3.10/concurrent/futures/_base.py", line 609, in result_iterator
    yield fs.pop().result()
  File "/python3.10/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/python3.10/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmpdir/numpy/numpy/distutils/ccompiler.py", line 307, in single_compile
    if not _needs_build(obj, cc_args, extra_postargs, pp_opts):
  File "/tmpdir/numpy/numpy/distutils/ccompiler.py", line 64, in _needs_build
    last_cmdline = lines[-1]
IndexError: list index out of range
```

### NumPy/Python version information:

**Python:** 3.10.5 (main, Jun 13 2022, 09:04:34) [GCC 11.2.0]
**ICC:** 2021.6.0 20220226
**Linux:** 5.4.17-2136.307.3.1.el8uek.x86_64

**Comment by seiko2plus** [comment]
would you please provide the full log?

**Comment by wilsonzlin** [comment]
I can't reproduce this issue anymore and no longer have the original build logs, so closing for now. I suspect the issue was something to do with the `ccompiler.py` reading a file that the compiler outputs before the compiler finished writing to it due to some race condition, so the file was blank and the script failed to read any lines from it. Will reopen if I encounter the issue again.
