### ISSUE TITLE
BUG: np.random.Generator cannot be unpickled using 3rd party bit generators

### ISSUE THREAD

**Issue by bashtage** [numpy/numpy#22012]
### Describe the issue:

The unpickling mechanism uses a hard-coded list of bit generators when unpickling a generator instance.  Because of this, it cannot  be used with 3rd party bit generators, or, if the name of the 3rd party bit generator is the same as the NumPy bit generator, it will unpickle using a different class than the original bit generator class

### Reproduce the code example:

```python
import numpy as np
import randomgen as rg
import pickle

# Generator(MT64)
g = np.random.Generator(rg.MT64())
pickle.loads(pickle.dumps(g))
```

### Error message:

```shell
Traceback (most recent call last):
  File "C:\git\randomgen\exp.py", line 7, in <module>
    pickle.loads(pickle.dumps(g))
  File "c:\git\numpy\numpy\random\_pickle.py", line 52, in __generator_ctor
    raise ValueError(
ValueError: MT64  is not a known NumPy BitGenerator class.
```

### NumPy/Python version information:

1.24.0.dev0+559.g5ba36b700 3.10.4 | packaged by conda-forge | (main, Mar 30 2022, 08:38:02) [MSC v.1916 64 bit (AMD64)]

**Comment by bashtage** [comment]
# Possible Solutions

## Let 3rd parts register bit generators
Provide an official mechanism to add bit generators to the lookup table (a dict) so that the current infrastructure could be extended.

### Advantages
* Continues to use same mechanism that has been around forever

### Disadvantages
* Could have name conflicts with existing modules in look up table, unless protected
* Requires explicit action by end users or library writers on module import
* Adds to API


 Something like

```python
np.random.register_bit_generator(bitgen: BitGenerator, name: Optional[str] = None):
   """
    Register a bit generator for pickling/unpickling

    Parameters
    ----------
    bitgen : Bit Generator
        The bit generator to register
    name : str, optional
        The name to use in the look up table.  If not provided, bitgen.__name__ is used
    """
```

## Support looking up fully qualified names
Let 3rd party bit generators name them selves using the pattern `module.class` so that the constructor can use `importlib`

### Advantages
* Totally transparent
* No API space
* Name guaranteed to be unique

### Disadvantages
* Hard to test
* Requires 3rd parties to use a specific pattern (pretty minor IMO)
* Requires a FQN, so unlikely to work with locally defined classes (but usually a problem for pickle)

Something like

```python
def __generator_ctor(bit_generator_name:str='MT19937') -> Generator:
    """
    Pickling helper function that returns a Generator object

    Parameters
    ----------
    bit_generator_name : str
        String containing the core BitGenerator. Can also be the
        full path (module.class) of a third-party bit generator.

    Returns
    -------
    rg : Generator
        Generator using the named core BitGenerator
    """
    bit_generator: Optional[Type[BitGenerator]] = None
    if bit_generator_name in BitGenerators:
        bit_generator = BitGenerators[bit_generator_name]
    elif "." in bit_generator_name:
        parts = bit_generator_name.split(".")
        mod_name = ".".join(parts[:-1])
        bit_generator_name = parts[-1]

        import importlib
        try:
            mod = importlib.import_module(mod_name)
            bit_generator = getattr(mod, bit_generator_name, None)
        except ImportError:
            pass

    if bit_generator is None:
        raise ValueError(
            f"{bit_generator_name}  is not a known NumPy BitGenerator class "
            f"and cannot be looked up using it's fully qualified name."
        )
    assert bit_generator is not None

    return Generator(bit_generator())
```

**Comment by bashtage** [comment]
## Change the information available when pickling

This is the approach used in #22014. This approach grabs the bit generators constructor and name and passes these to the Generator's constructor.  The significant advantage of this approach is that it is fully automatic in the sense that the required information from the bit generator is already present, so no changes are needed to how bit generators are pickled.
