### ISSUE TITLE
ENH: numpy.unique() should support pandas.NA

### ISSUE THREAD

**Issue by chukarsten** [numpy/numpy#22101]
### Proposed new feature or change:

With the new Int64, boolan and Float64 dtypes coming out from pandas, it would be nice if numpy's unique() function supported pandas.NA.

```
>>> import numpy as np
>>> import pandas as pd
>>> ser = pd.Series([1,2,3,pd.NA])
>>> np.unique(ser)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<__array_function__ internals>", line 180, in unique
  File "/usr/local/Caskroom/miniconda/base/envs/compatibility_test/lib/python3.9/site-packages/numpy/lib/arraysetops.py", line 272, in unique
    ret = _unique1d(ar, return_index, return_inverse, return_counts)
  File "/usr/local/Caskroom/miniconda/base/envs/compatibility_test/lib/python3.9/site-packages/numpy/lib/arraysetops.py", line 333, in _unique1d
    ar.sort()
  File "pandas/_libs/missing.pyx", line 382, in pandas._libs.missing.NAType.__bool__
TypeError: boolean value of NA is ambiguous
```

**Comment by c0mr4t** [comment]
I am a new contributor and would like to give it a try. Is there anything I should know in general before starting to work on the issue?

**Comment by seberg** [comment]
No, it doesn't make sense for NumPy to support this, unless pandas rewrits the dtypes as new NumPy DTypes at least.

*Pandas* might be able to support it via `__array_function__` although there may be other blockers.  So there may be paths forward, but nothing simple.

**Comment by bashtage** [comment]
The usual flow NumPy -> pandas, but not reverse (in general, except for issues that have more general application or bugs).
