### ISSUE TITLE
BUG: <AttributeError: 'MachAr' object has no attribute '_str_smallest_normal'>

### ISSUE THREAD

**Issue by ElrondL** [numpy/numpy#22113]
### Describe the issue:

Similar to an earlier problem on AttributeError: 'MachAr' object has no attribute '_str_smallest_normal', but this time for float.32 on MacOS

### Reproduce the code example:

```python
import numpy as np
numpy.finfo('float32').eps
```

### Error message:

```shell
import seaborn
/Users/.../opt/anaconda3/lib/python3.9/site-packages/numpy/core/getlimits.py:492: UserWarning:

Signature b'\xcd\xcc\xcc\xbd' for <class 'numpy.float32'> does not match any known type: falling back to type probe function

Traceback (most recent call last):

  File "...", line 1, in <cell line: 1>
    import seaborn

  File "/Users/.../opt/anaconda3/lib/python3.9/site-packages/seaborn/__init__.py", line 2, in <module>
    from .rcmod import *  # noqa: F401,F403

  File "/Users/.../opt/anaconda3/lib/python3.9/site-packages/seaborn/rcmod.py", line 7, in <module>
    from . import palettes

  File "/Users/.../opt/anaconda3/lib/python3.9/site-packages/seaborn/palettes.py", line 9, in <module>
    from .utils import desaturate, get_color_cycle

  File "/Users/.../opt/anaconda3/lib/python3.9/site-packages/seaborn/utils.py", line 10, in <module>
    from scipy import stats

  File "/Users/.../opt/anaconda3/lib/python3.9/site-packages/scipy/stats/__init__.py", line 441, in <module>
    from .stats import *

  File "/Users/.../opt/anaconda3/lib/python3.9/site-packages/scipy/stats/stats.py", line 37, in <module>
    from scipy.spatial.distance import cdist

  File "/Users/.../opt/anaconda3/lib/python3.9/site-packages/scipy/spatial/__init__.py", line 101, in <module>
    from ._procrustes import procrustes

  File "/Users/.../opt/anaconda3/lib/python3.9/site-packages/scipy/spatial/_procrustes.py", line 9, in <module>
    from scipy.linalg import orthogonal_procrustes

  File "/Users/.../opt/anaconda3/lib/python3.9/site-packages/scipy/linalg/__init__.py", line 206, in <module>
    from .matfuncs import *

  File "/Users/.../opt/anaconda3/lib/python3.9/site-packages/scipy/linalg/matfuncs.py", line 24, in <module>
    feps = np.finfo(single).eps

  File "/Users/.../opt/anaconda3/lib/python3.9/site-packages/numpy/core/getlimits.py", line 485, in __new__
    obj = object.__new__(cls)._init(dtype)

  File "/Users/.../opt/anaconda3/lib/python3.9/site-packages/numpy/core/getlimits.py", line 512, in _init
    self._str_smallest_normal = machar._str_smallest_normal.strip()

AttributeError: 'MachAr' object has no attribute '_str_smallest_normal'
```

### NumPy/Python version information:

1.22.3/3.9.13

**Comment by ElrondL** [comment]
upgrading to 1.23.1 fixed this
