### ISSUE TITLE
BUG: numpy.char.rsplit does not accept null byte as separator

### ISSUE THREAD

**Issue by danielhrisca** [numpy/numpy#22174]
### Describe the issue:

it is not possible to split using `\x00` as separator

### Reproduce the code example:

```python
from numpy.core.defchararray import rsplit
import numpy as np


x = np.frombuffer(b'___\0++++' * 3, dtype='S8')

print(x[0].rsplit(b'\0'))
rsplit(x, b'\0')
```

### Error message:

```shell
[b'___', b'++++']

Traceback (most recent call last):
  File "D:\DSUsers\uidn3651\02__PythonWorkspace\__venvs\daxil\lib\site-packages\IPython\core\interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-6c8058c0020b>", line 1, in <cell line: 1>
    runfile('C:/Users/uidn3651/AppData/Roaming/JetBrains/PyCharmCE2022.2/scratches/scratch.py', wdir='C:/Users/uidn3651/AppData/Roaming/JetBrains/PyCharmCE2022.2/scratches')
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.2\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.2\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/uidn3651/AppData/Roaming/JetBrains/PyCharmCE2022.2/scratches/scratch.py", line 8, in <module>
    rsplit(x, b'\0')
  File "<__array_function__ internals>", line 180, in rsplit
  File "D:\DSUsers\uidn3651\02__PythonWorkspace\__venvs\daxil\lib\site-packages\numpy\core\defchararray.py", line 1348, in rsplit
    return _vec_string(
ValueError: empty separator
```

### NumPy/Python version information:

1.23.1 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)]

**Comment by LeonaTaric** [comment]
use other char like '\x01'
in program c, '\x00' mean the end of the string

**Comment by seberg** [comment]
Could probably be accepted, but @LeonaTaric has a point.  NumPy pads with `\0`, so splitting only works if the zero byte/character is followed by non-zero bytes/characters.  Otherwise, the string is considered shorter to begin with.

**Comment by danielhrisca** [comment]
The raw buffer that contains the weird null bytes in the middle is coming from am external application so there is a valid need to be able to use the null byte as separator. I think it is also suprizing that the behavior is not the same as the regular python bytes objects,  which accepts this separator

**Comment by LeonaTaric** [comment]
> The raw buffer that contains the weird null bytes in the middle is coming from am external application so there is a valid need to be able to use the null byte as separator. I think it is also suprizing that the behavior is not the same as the regular python bytes objects, which accepts this separator

fix this bug need some time, but if you sure that some char like "\x01" will never be in the string, you can do like this:

string = string.replace(b"\x00", b"\x01")

otherwise, maybe I can try to fix and give a pr

**Comment by LeonaTaric** [comment]
well, the root cause may be like this:

`
>>> np.array(b'\0')
array(b'', dtype='|S1')
`

then, the b'\0' of "rsplit(str_list, b'\0')" become to b""

**Comment by danielhrisca** [comment]
> well, the root cause may be like this:
> 
> ```
> >>> np.array(b'\0')
> array(b'', dtype='|S1')
> ```
> 
> then, the b'\0' of "rsplit(str_list, b'\0')" become to b""

Are you implying that the separator is converted to an array first?

**Comment by LeonaTaric** [comment]
> > well, the root cause may be like this:
> > ```
> > >>> np.array(b'\0')
> > array(b'', dtype='|S1')
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > then, the b'\0' of "rsplit(str_list, b'\0')" become to b""
> 
> Are you implying that the separator is converted to an array first?


[https://github.com/numpy/numpy/blob/v1.23.1/numpy/core/src/multiarray/multiarraymodule.c#L3865](code)

in this function, self and args are all in the variable "broadcast_args", when self is "broadcast_args[0]" and args are "broadcast_args[1:]"

then, in_iter make broadcast_args pyarray
finally, every arg becomes scalar by "PyArray_ToScalar"
