### ISSUE TITLE
Numpy error while running opencv in my windows

### ISSUE THREAD

**Issue by priyanshujiiii** [numpy/numpy#22181]
### Steps to reproduce:

I used Anoconda promt for installing a Numpy . i imported a Numpy its showing that error.
i update numpy , pandas still its showing error.

### Error message:

```shell
OpenCV bindings requires "numpy" package.
Install it via command:
    pip install numpy
Traceback (most recent call last):
  File "C:\Users\india\anaconda3\envs\file\lib\site-packages\numpy\core\__init__.py", line 23, in <module>
    from . import multiarray
  File "C:\Users\india\anaconda3\envs\file\lib\site-packages\numpy\core\multiarray.py", line 10, in <module>
    from . import overrides
  File "C:\Users\india\anaconda3\envs\file\lib\site-packages\numpy\core\overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ImportError: DLL load failed while importing _multiarray_umath: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\india\PycharmProjects\file\basic.py", line 1, in <module>
    import cv2
  File "C:\Users\india\anaconda3\envs\file\lib\site-packages\cv2\__init__.py", line 11, in <module>
    import numpy
  File "C:\Users\india\anaconda3\envs\file\lib\site-packages\numpy\__init__.py", line 140, in <module>
    from . import core
  File "C:\Users\india\anaconda3\envs\file\lib\site-packages\numpy\core\__init__.py", line 49, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.9 from "C:\Users\india\anaconda3\envs\file\python.exe"
  * The NumPy version is: "1.23.2"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: DLL load failed while importing _multiarray_umath: The specified module could not be found.


Process finished with exit code 1
```

### Additional information:

I am making my college project : face recgonization. here  iam using a following module 
 opencv, face_recgonization, numpy , cmake

**Comment by seberg** [comment]
@priyanshujiiii Did you follow the link given: https://numpy.org/devdocs/user/troubleshooting-importerror.html

These types of errors are practically never NumPy issues and usually as simple as activating the correct environment (which can be easy to a bit more steps for complicated setups).  The website has pointers for various solutions, including your likely one (simply activate conda).  Closing the issue for now.

**Comment by jhaggle** [comment]
+1
