### ISSUE TITLE
BUG: Numpy can't find c++ compiler

### ISSUE THREAD

**Issue by rubyFeedback** [numpy/numpy#22200]
### Describe the issue:

Somehow numpy complains about my g++ compiler not working. This is not a true statement
from numpy - I compile everything from source and it all works.

I suggest that numpy either changes its internal behaviour, or does not claim that my gcc/g++
compiler do not work. They both work, so there must be another issue that numpy either does
not see or swallows.
```
    /usr/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.  warnings.warn(running buildrunning config_ccINFO: unifing config_cc, config, build_clib, build_ext, build commands --compiler optionsrunning config_fcINFO: unifing config_fc, config, build_clib, build_ext, build commands --fcompiler optionsrunning build_srcINFO: build_srcINFO: building py_modules sourcesINFO: building library "npymath" sourcesWARN: Could not locate executable armflang/home/Temp/rbt/numpy-1.23.2/numpy/distutils/fcompiler/gnu.py:276: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.  if LooseVersion(v) >= "4":/usr/lib/python3.10/site-packages/setuptools/_distutils/version.py:346: DeprecationWarning: distutils Version classes are deprecated. 
    Use packaging.version instead.  other = LooseVersion(other)/home/Temp/rbt/numpy-1.23.2/numpy/distutils/ccompiler.py:662: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.  version = LooseVersion(version)
c++: warning: gcc: linker input file unused because linking not donec++: error: gcc: linker input file not found: No such file or directoryTraceback (most recent call last):
  File "/home/Temp/rbt/numpy-1.23.2/setup.py", line 493, in <module>    setup_package()  File "/home/Temp/rbt/numpy-1.23.2/setup.py", line 485, in setup_package    
setup(**metadata)  File "/home/Temp/rbt/numpy-1.23.2/numpy/distutils/core.py", line 169, in setup
    return old_setup(**new_attr)  File "/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 177, in setup
    return run_commands(dist)  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 193, in run_commands
    dist.run_commands()  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
    self.run_command(cmd)  File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command    
    super().run_command(command)  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()  File "/home/Temp/rbt/numpy-1.23.2/numpy/distutils/command/install.py", line 60, in run
    r = self.setuptools_run()  File "/home/Temp/rbt/numpy-1.23.2/numpy/distutils/command/install.py", line 52, in setuptools_run    distutils_install.run(self)  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/command/install.py", line 695, in run
    self.run_command('build')  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 317, in run_command
    self.distribution.run_command(command)  File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command    super().run_command(command)  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()  File "/home/Temp/rbt/numpy-1.23.2/numpy/distutils/command/build.py", line 62, in run
    old_build.run(self)  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 131, in run    self.run_command(cmd_name)  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 317, in run_command
    self.distribution.run_command(command)  File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command    super().run_command(command)  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()  File "/home/Temp/rbt/numpy-1.23.2/numpy/distutils/command/build_src.py", line 144, in run
    self.build_sources()  File "/home/Temp/rbt/numpy-1.23.2/numpy/distutils/command/build_src.py", line 155, in build_sources
    self.build_library_sources(*libname_info)  File "/home/Temp/rbt/numpy-1.23.2/numpy/distutils/command/build_src.py", line 288, in build_library_sources
    sources =  self.generate_sources(sources, (lib_name, build_info))  File "/home/Temp/rbt/numpy-1.23.2/numpy/distutils/command/build_src.py", line 378, in generate_sources
    source = func(extension, build_dir)  File "/home/Temp/rbt/numpy-1.23.2/numpy/core/setup.py", line 758, in get_mathlib_info
    raise RuntimeError(RuntimeError: Broken toolchain: cannot link a simple C++ program. note: A compiler with support for C++11 language features is required.
```

PS: These templates are a bit annoying to use. I get that you want it separated, but a side effect is that in firefox these textview entries I am using right now appear much smaller than normally, whereas in the free form github issue I have more room to work with. With bad eyesight this is an issue, IMO.

Sorry for the bad line wrapping above, but it was initially not possible to use it - now with a second edit it is much easier.

So for the TL;DR variant:

    RuntimeError: Broken toolchain: cannot link a simple C++ program. note: A compiler with support for
    C++11 language features is required.

^^^ this is bogus. My toolchain works perfectly well. The compiler is at /usr/bin/gcc as a symlink towards
/home/Programs/Gcc/12.2.0/bin/gcc.. For reference purpose I compiled mesa from source a few days
ago without problem, and yesterday node (nodejs) from source too and it all works fine. 

numpy shows "WARN: Could not locate executable armflang" but I don't know ... armflang? Is that for
ARM? I have an AMD 64 bit here. No idea why it tries to find some armflang binary.

### Reproduce the code example:

```python
x
```

### Error message:

```shell
x
```

### NumPy/Python version information:

x

### Context for the issue:

x

**Comment by rgommers** [comment]
I tried to clean up the input a bit; all newlines appear to have gotten lost from your traceback.

The `WARN: ...armflangcompiler` and all other such warnings can be ignored. `numpy.distutils` just goes through all compilers and tries to see what's available. A saner build system would suppress such output, because it indeed just leads to confusion.

The test code that's being tried is in `numpy/core/setup.py`:
```python
            ('c++', (                                              
                    'int main(void)'                                   
                    '{ auto x = 0.0; return static_cast<int>(x); }'
                ), (                                                   
                    'note: A compiler with support for C++11 language '
                    'features is required.'
                )
             ), 
```

Somehow that trivial bit of C++ code is failing to build correctly.

**Comment by rgommers** [comment]
> The compiler is at /usr/bin/gcc as a symlink towards
> /home/Programs/Gcc/12.2.0/bin/gcc

What about `g++`?

Can you give details of all packages and compilers you have installed?

**Comment by seberg** [comment]
Closing, without followup, we cannot help with figuring out what is wrong with the system setup.
