### ISSUE TITLE
ENH: np.average to broadcast a and weights

### ISSUE THREAD

**Issue by kalvdans** [numpy/numpy#22248]
### Proposed new feature or change:

Now `np.average` doesn't broadcast `a` to match the shape of `weights`. That's all fine and according to documentation, but it would be an enhancement to allow broadcast. See the session below when it first fails but then succeed when I do manual broadcasting of `a` to the shape of `weights`.

```
>>> import numpy as np
>>> np.average([[1, 2, 3]], weights=[[4,5,6], [7,8,9]], axis=1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<__array_function__ internals>", line 5, in average
  File "/home/chn/env/lib/python3.10/site-packages/numpy/lib/function_base.py", line 397, in average
    raise TypeError(
TypeError: 1D weights expected when shapes of a and weights differ.
>>> np.average([[1, 2, 3], [1, 2, 3]], weights=[[4,5,6], [7,8,9]], axis=1)
array([2.13333333, 2.08333333])
```

**Comment by rossbar** [comment]
Just FYI there was an attempt at this that was recently closed due to lack of forward momentum - see #10994. That might be a good place to start if interested in picking this feature up.

**Comment by kalvdans** [comment]
Thanks Ross, I had not read that pull request. I can add a bit on my usecase:

I did several optical measurements and got a spectra from each of them. I want then to get the average wavelength on each measurement, so then run `np.average` with `a` being the wavelength for each bin (1D) and `weights` being my measurements (2D).
