### ISSUE TITLE
How to  install numpy with BLAS interface specified as vecLib on new MacBook Air M2

### ISSUE THREAD

**Issue by laolvv** [numpy/numpy#22264]
### Steps to reproduce:

I gor an error when install numpy
`pip install --no-binary :all: --no-use-pep517 numpy`

### Error message:

```shell
Collecting numpy
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/0a/88/f4f0c7a982efdf7bf22f283acf6009b29a9cc5835b684a49f8d3a4adb22f/numpy-1.23.3.tar.gz (10.7 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [76 lines of output]
      running egg_info
      running build_src
      INFO: build_src
      creating /private/var/folders/_m/w24nrz_106vdryhx686b6p080000gn/T/pip-pip-egg-info-skoxm5qe/numpy.egg-info
      writing /private/var/folders/_m/w24nrz_106vdryhx686b6p080000gn/T/pip-pip-egg-info-skoxm5qe/numpy.egg-info/PKG-INFO
      writing dependency_links to /private/var/folders/_m/w24nrz_106vdryhx686b6p080000gn/T/pip-pip-egg-info-skoxm5qe/numpy.egg-info/dependency_links.txt
      writing entry points to /private/var/folders/_m/w24nrz_106vdryhx686b6p080000gn/T/pip-pip-egg-info-skoxm5qe/numpy.egg-info/entry_points.txt
      writing top-level names to /private/var/folders/_m/w24nrz_106vdryhx686b6p080000gn/T/pip-pip-egg-info-skoxm5qe/numpy.egg-info/top_level.txt
      writing manifest file '/private/var/folders/_m/w24nrz_106vdryhx686b6p080000gn/T/pip-pip-egg-info-skoxm5qe/numpy.egg-info/SOURCES.txt'
      INFO: unifing config_cc, config, build_clib, build_ext, build commands --compiler options
      INFO: unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
      Running from numpy source directory.
      /private/var/folders/_m/w24nrz_106vdryhx686b6p080000gn/T/pip-install-qs928g7e/numpy_7e29e57978cf4337a675b187504ff03a/setup.py:86: DeprecationWarning:

        `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
        of the deprecation of `distutils` itself. It will be removed for
        Python >= 3.12. For older Python versions it will remain present.
        It is recommended to use `setuptools < 60.0` for those Python versions.
        For more details, see:
          https://numpy.org/devdocs/reference/distutils_status_migration.html


        import numpy.distutils.command.sdist
      /Users/ycshu/anaconda3/envs/YC/lib/python3.8/site-packages/setuptools/command/egg_info.py:643: SetuptoolsDeprecationWarning: Custom 'build_py' does not implement 'get_data_files_without_manifest'.
      Please extend command classes from setuptools instead of distutils.
        warnings.warn(
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/_m/w24nrz_106vdryhx686b6p080000gn/T/pip-install-qs928g7e/numpy_7e29e57978cf4337a675b187504ff03a/setup.py", line 494, in <module>
          setup_package()
        File "/private/var/folders/_m/w24nrz_106vdryhx686b6p080000gn/T/pip-install-qs928g7e/numpy_7e29e57978cf4337a675b187504ff03a/setup.py", line 486, in setup_package
          setup(**metadata)
        File "/Users/ycshu/anaconda3/envs/YC/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/Users/ycshu/anaconda3/envs/YC/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/Users/ycshu/anaconda3/envs/YC/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/Users/ycshu/anaconda3/envs/YC/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 973, in run_commands
          self.run_command(cmd)
        File "/Users/ycshu/anaconda3/envs/YC/lib/python3.8/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/Users/ycshu/anaconda3/envs/YC/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
          cmd_obj.run()
        File "/private/var/folders/_m/w24nrz_106vdryhx686b6p080000gn/T/pip-install-qs928g7e/numpy_7e29e57978cf4337a675b187504ff03a/numpy/distutils/command/egg_info.py", line 25, in run
          _egg_info.run(self)
        File "/Users/ycshu/anaconda3/envs/YC/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 308, in run
          self.find_sources()
        File "/Users/ycshu/anaconda3/envs/YC/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 316, in find_sources
          mm.run()
        File "/Users/ycshu/anaconda3/envs/YC/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 560, in run
          self.add_defaults()
        File "/Users/ycshu/anaconda3/envs/YC/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 597, in add_defaults
          sdist.add_defaults(self)
        File "/Users/ycshu/anaconda3/envs/YC/lib/python3.8/site-packages/setuptools/command/sdist.py", line 107, in add_defaults
          self._add_defaults_build_sub_commands()
        File "/Users/ycshu/anaconda3/envs/YC/lib/python3.8/site-packages/setuptools/command/sdist.py", line 127, in _add_defaults_build_sub_commands
          self.filelist.extend(chain.from_iterable(files))
        File "/Users/ycshu/anaconda3/envs/YC/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 503, in extend
          self.files.extend(filter(self._safe_path, paths))
        File "/Users/ycshu/anaconda3/envs/YC/lib/python3.8/site-packages/setuptools/command/sdist.py", line 126, in <genexpr>
          files = (c.get_source_files() for c in cmds if hasattr(c, "get_source_files"))
        File "/Users/ycshu/anaconda3/envs/YC/lib/python3.8/site-packages/setuptools/command/sdist.py", line 125, in <genexpr>
          cmds = (self.get_finalized_command(c) for c in missing_cmds)
        File "/Users/ycshu/anaconda3/envs/YC/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 306, in get_finalized_command
          cmd_obj.ensure_finalized()
        File "/Users/ycshu/anaconda3/envs/YC/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 109, in ensure_finalized
          self.finalize_options()
        File "/private/var/folders/_m/w24nrz_106vdryhx686b6p080000gn/T/pip-install-qs928g7e/numpy_7e29e57978cf4337a675b187504ff03a/numpy/distutils/command/config_compiler.py", line 69, in finalize_options
          v = getattr(c, a)
        File "/Users/ycshu/anaconda3/envs/YC/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 157, in __getattr__
          return _build_ext.build_ext.__getattr__(self, name)
        File "/Users/ycshu/anaconda3/envs/YC/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 105, in __getattr__
          raise AttributeError(attr)
      AttributeError: fcompiler
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by rgommers** [comment]
This doesn't have anything to do with vecLib or even macOS it looks like. You are using `--no-use-pep517` but are building with a too-new `setuptools`. As the warning message says, please use `<60.0`. If you don't use `--no-use-pep517`, that would be automatic.
