### ISSUE TITLE
BUG: No module named 'numpy.distutils._msvccompiler' in numpy.distutils

### ISSUE THREAD

**Issue by xilin22** [numpy/numpy#22275]
### Describe the issue:

I encountered this issue  when setting up my environment during the GraceHopper open source day Numpy track.

This was after I applied the temporary fix for the versioneer bug in the setup.py file in the root directory.

### Reproduce the code example:

```python
encounterd this issue when running `python testrun.py -v`
```

### Error message:

```shell
DeprecationWarning:
  `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
  of the deprecation of `distutils` itself. It will be removed for
  Python >= 3.12. For older Python versions it will remain present.
  It is recommended to use `setuptools < 60.0` for those Python versions.
  For more details, see:
    https://numpy.org/devdocs/reference/distutils_status_migration.html 

  import numpy.distutils.command.sdist
Processing numpy/random\_bounded_integers.pxd.in
Processing numpy/random\bit_generator.pyx
Processing numpy/random\mtrand.pyx
Processing numpy/random\_bounded_integers.pyx.in
Processing numpy/random\_common.pyx
Processing numpy/random\_generator.pyx
Processing numpy/random\_mt19937.pyx
Processing numpy/random\_pcg64.pyx
Processing numpy/random\_philox.pyx
Processing numpy/random\_sfc64.pyx
Cythonizing sources
INFO: blas_opt_info:
INFO: blas_armpl_info:
INFO: No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
INFO: customize MSVCCompiler
INFO:   libraries armpl_lp64_mp not found in ['C:\\Users\\user-name\\Anaconda3\\envs\\numpy-dev\\lib', 'C:\\', 'C:\\Users\\user-name\\Anaconda3\\envs\\numpy-dev\\libs', 'C:\\Users\\user-name\\Anaconda3\\Library\\lib']
INFO:   NOT AVAILABLE
INFO:
INFO: blas_mkl_info:
INFO:   libraries mkl_rt not found in ['C:\\Users\\user-name\\Anaconda3\\envs\\numpy-dev\\lib', 'C:\\', 'C:\\Users\\user-name\\Anaconda3\\envs\\numpy-dev\\libs', 'C:\\Users\\user-name\\Anaconda3\\Library\\lib']
INFO:   NOT AVAILABLE
INFO:
INFO: blis_info:
INFO:   libraries blis not found in ['C:\\Users\\user-name\\Anaconda3\\envs\\numpy-dev\\lib', 'C:\\', 'C:\\Users\\user-name\\Anaconda3\\envs\\numpy-dev\\libs', 'C:\\Users\\user-name\\Anaconda3\\Library\\lib']
INFO:   NOT AVAILABLE
INFO:
INFO: openblas_info:
INFO:   libraries openblas not found in ['C:\\Users\\user-name\\Anaconda3\\envs\\numpy-dev\\lib', 'C:\\', 'C:\\Users\\user-name\\Anaconda3\\envs\\numpy-dev\\libs', 'C:\\Users\\user-name\\Anaconda3\\Library\\lib']
Traceback (most recent call last):
  File "C:\Users\user-name\GraceHopper\numpy\setup.py", line 495, in <module>
    setup_package()
  File "C:\Users\user-name\GraceHopper\numpy\setup.py", line 487, in setup_package
    setup(**metadata)
  File "C:\Users\user-name\GraceHopper\numpy\numpy\distutils\core.py", line 135, in setup
    config = configuration()
  File "C:\Users\user-name\GraceHopper\numpy\setup.py", line 138, in configuration
    config.add_subpackage('numpy')
  File "C:\Users\user-name\GraceHopper\numpy\numpy\distutils\misc_util.py", line 1050, in add_subpackage
    config_list = self.get_subpackage(subpackage_name, subpackage_path,
  File "C:\Users\user-name\GraceHopper\numpy\numpy\distutils\misc_util.py", line 1016, in get_subpackage
    config = self._get_configuration_from_setup_py(
  File "C:\Users\user-name\GraceHopper\numpy\numpy\distutils\misc_util.py", line 958, in _get_configuration_from_setup_py
    config = setup_module.configuration(*args)
  File "numpy\setup.py", line 9, in configuration
    config.add_subpackage('core')
  File "C:\Users\user-name\GraceHopper\numpy\numpy\distutils\misc_util.py", line 1050, in add_subpackage
    config_list = self.get_subpackage(subpackage_name, subpackage_path,
  File "C:\Users\user-name\GraceHopper\numpy\numpy\distutils\misc_util.py", line 1016, in get_subpackage
    config = self._get_configuration_from_setup_py(
  File "C:\Users\user-name\GraceHopper\numpy\numpy\distutils\misc_util.py", line 958, in _get_configuration_from_setup_py
    config = setup_module.configuration(*args)
  File "numpy\core\setup.py", line 835, in configuration
    blas_info = get_info('blas_opt', 0)
  File "C:\Users\user-name\GraceHopper\numpy\numpy\distutils\system_info.py", line 585, in get_info
    return cl().get_info(notfound_action)
  File "C:\Users\user-name\GraceHopper\numpy\numpy\distutils\system_info.py", line 845, in get_info
    self.calc_info()
  File "C:\Users\user-name\GraceHopper\numpy\numpy\distutils\system_info.py", line 2077, in calc_info
    if self._calc_info(blas):
  File "C:\Users\user-name\GraceHopper\numpy\numpy\distutils\system_info.py", line 2063, in _calc_info
    return getattr(self, '_calc_info_{}'.format(name))()
  File "C:\Users\user-name\GraceHopper\numpy\numpy\distutils\system_info.py", line 2000, in _calc_info_openblas
    info = get_info('openblas')
  File "C:\Users\user-name\GraceHopper\numpy\numpy\distutils\system_info.py", line 585, in get_info
    return cl().get_info(notfound_action)
  File "C:\Users\user-name\GraceHopper\numpy\numpy\distutils\system_info.py", line 845, in get_info
    self.calc_info()
  File "C:\Users\user-name\GraceHopper\numpy\numpy\distutils\system_info.py", line 2283, in calc_info
    info = self._calc_info()
  File "C:\Users\user-name\GraceHopper\numpy\numpy\distutils\system_info.py", line 2254, in _calc_info
    f = new_fcompiler(c_compiler=c)
  File "C:\Users\user-name\GraceHopper\numpy\numpy\distutils\fcompiler\__init__.py", line 882, in new_fcompiler
    load_all_fcompiler_classes()
  File "C:\Users\user-name\GraceHopper\numpy\numpy\distutils\fcompiler\__init__.py", line 783, in load_all_fcompiler_classes
    __import__ (module_name)
  File "C:\Users\user-name\GraceHopper\numpy\numpy\distutils\fcompiler\compaq.py", line 54, in <module>
    class CompaqVisualFCompiler(FCompiler):
  File "C:\Users\user-name\GraceHopper\numpy\numpy\distutils\fcompiler\compaq.py", line 78, in CompaqVisualFCompiler
    m.initialize()
  File "C:\Users\user-name\GraceHopper\numpy\numpy\distutils\msvccompiler.py", line 52, in initialize
    os.environ['include'] = _merge(environ_include, os.environ['include'])
  File "C:\Users\user-name\Anaconda3\envs\numpy-dev\lib\os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'include'

Build failed!
```

### NumPy/Python version information:

Python version: 3.9.13
Numpy version: 1.23.3

### Context for the issue:

Encountered this issue when setting up my environment during the GraceHopper open source day Numpy track.

**Comment by rgommers** [comment]
No follow-up, hence closing.
