### ISSUE TITLE
BUG: <Not able to convert a text file to a numpy ndarray>

### ISSUE THREAD

**Issue by malladimihir** [numpy/numpy#22339]
### Describe the issue:

I have a textfile which has some data in float. I want to convert this to an ndarray in my python code  using numpy library. I am getting errors in my command prompt when I run it. 

Here is the snippet of my code:

currentDirectory = Path.cwd()
filePath = Path(currentDirectory.parent,'SampleData')
VoltageData_AMI=np.loadtxt("nodeVoltAll.txt",dtype=float,delimiter=' ')

The error that I am getting is in the snapshot of my command prompt. 

![image](https://user-images.githubusercontent.com/80494717/192317832-ddddd1cf-d5a3-4712-b0b6-f8370368f10f.png)

Kindly let me know where I am going wrong.

### Reproduce the code example:

```python
# Import - Python Libraries
import numpy as np
from pathlib import Path
import pandas as pd

# Import - Custom Libraries
import CA_Ensemble_Funcs as CAE
import PhaseIdent_Utils as PIUtils

import pdb


##############################################################################
#                    Load Sample Data

currentDirectory = Path.cwd()
filePath = Path(currentDirectory.parent,'SampleData')
VoltageData_AMI=np.loadtxt("nodeVoltAll.txt",dtype=float,delimiter=' ')
```

### Error message:

```shell
Traceback (most recent call last):
  File "C:\Users\Mihir Malladi\OneDrive - University of Kentucky\Desktop\Phase Identification Problem\PhaseIdentification\CA_Ensemble_SampleScripts.py", line 96, in <module>
    VoltageData_AMI=np.loadtxt("nodeVoltAll.txt",dtype=float,delimiter=' ')
  File "C:\Users\Mihir Malladi\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\npyio.py", line 1313, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
  File "C:\Users\Mihir Malladi\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\npyio.py", line 955, in _read
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "C:\Users\Mihir Malladi\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "C:\Users\Mihir Malladi\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\_datasource.py", line 533, in open
    raise FileNotFoundError(f"{path} not found.")
FileNotFoundError: nodeVoltAll.txt not found.

C:\Users\Mihir Malladi\OneDrive - University of Kentucky\Desktop\Phase Identification Problem\PhaseIdentification>VoltageData_AMI=np.loadtxt("nodeVoltAll.txt",dtype=float,delimiter=' ')
'VoltageData_AMI' is not recognized as an internal or external command,
operable program or batch file.
```

### NumPy/Python version information:

python 3.10.7

### Context for the issue:

This is the input data that is needed for my work.

**Comment by rkern** [comment]
You probably meant to do something with `filePath` to get the full path to the data file.

```python
currentDirectory = Path.cwd()
filePath = Path(currentDirectory.parent,'SampleData')
VoltageData_AMI=np.loadtxt(filePath / "nodeVoltAll.txt",dtype=float,delimiter=' ')
```

In any case, there is no bug in numpy here.

**Comment by malladimihir** [comment]
This file nodeVoltAll.txt exists in the Sample Data folder. How do I extract this textfile convert to ndarray and then store it in the same folder.

**Comment by rkern** [comment]
I'm afraid that we don't have the bandwidth to answer general Python usage questions here on the issue tracker.
