### ISSUE TITLE
BUG [1.23.4]: pep517 build fails

### ISSUE THREAD

**Issue by kloczek** [numpy/numpy#22431]
### Describe the issue:

pep517 build fails with call trace

### Reproduce the code example:

```python
- unpacka source code
- `python3 -sBm build -w --no-isolation`
```

### Error message:

```shell
+ CC=/usr/bin/gcc
+ CXX=/usr/bin/g++
+ FC=/usr/bin/gfortran
+ AR=/usr/bin/gcc-ar
+ NM=/usr/bin/gcc-nm
+ RANLIB=/usr/bin/gcc-ranlib
+ export CFLAGS CXXFLAGS FFLAGS FCFLAGS LDFLAGS CC CXX FC AR NM RANLIB
+ BLAS=/usr/lib64
+ LAPACK=/usr/lib64
+ OPENBLAS=/usr/lib64
+ SETUPTOOLS_USE_DISTUTILS=stdlib
+ CFLAGS='-O2 -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fdata-sections -ffunction-sections -flto=auto -flto-partition=none'
+ CXXFLAGS='-O2 -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fdata-sections -ffunction-sections -flto=auto -flto-partition=none'
+ FFLAGS='-O2 -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fdata-sections -ffunction-sections -flto=auto -flto-partition=none -I/usr/lib64/gfortran/modules'
+ FCFLAGS='-O2 -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fdata-sections -ffunction-sections -flto=auto -flto-partition=none -I/usr/lib64/gfortran/modules'
+ LDFLAGS='-Wl,--as-needed -Wl,--gc-sections -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -flto=auto -flto-partition=none -fuse-linker-plugin -Wl,--build-id=sha1'
+ CC=/usr/bin/gcc
+ CXX=/usr/bin/g++
+ FC=/usr/bin/gfortran
+ AR=/usr/bin/gcc-ar
+ NM=/usr/bin/gcc-nm
+ RANLIB=/usr/bin/gcc-ranlib
+ export CFLAGS CXXFLAGS FFLAGS FCFLAGS LDFLAGS CC CXX FC AR NM RANLIB
+ PBR_VERSION=1.23.4
+ PDM_PEP517_SCM_VERSION=1.23.4
+ SETUPTOOLS_SCM_PRETEND_VERSION=1.23.4
+ /usr/bin/python3 -sBm build -w --no-isolation
* Getting dependencies for wheel...
Running from numpy source directory.
<string>:86: DeprecationWarning:

  `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
  of the deprecation of `distutils` itself. It will be removed for
  Python >= 3.12. For older Python versions it will remain present.
  It is recommended to use `setuptools < 60.0` for those Python versions.
  For more details, see:
    https://numpy.org/devdocs/reference/distutils_status_migration.html


running egg_info
running build_src
INFO: build_src
creating numpy.egg-info
writing numpy.egg-info/PKG-INFO
writing dependency_links to numpy.egg-info/dependency_links.txt
writing entry points to numpy.egg-info/entry_points.txt
writing top-level names to numpy.egg-info/top_level.txt
writing manifest file 'numpy.egg-info/SOURCES.txt'
/usr/lib/python3.8/site-packages/setuptools/command/egg_info.py:643: SetuptoolsDeprecationWarning: Custom 'build_py' does not implement 'get_data_files_without_manifest'.
Please extend command classes from setuptools instead of distutils.
  warnings.warn(
INFO: unifing config_cc, config, build_clib, build_ext, build commands --compiler options
INFO: unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pep517/in_process/_in_process.py", line 363, in <module>
    main()
  File "/usr/lib/python3.8/site-packages/pep517/in_process/_in_process.py", line 345, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/usr/lib/python3.8/site-packages/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
    return hook(config_settings)
  File "/usr/lib/python3.8/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
    return self._get_build_requires(config_settings, requirements=['wheel'])
  File "/usr/lib/python3.8/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
    self.run_setup()
  File "/usr/lib/python3.8/site-packages/setuptools/build_meta.py", line 482, in run_setup
    super(_BuildMetaLegacyBackend,
  File "/usr/lib/python3.8/site-packages/setuptools/build_meta.py", line 335, in run_setup
    exec(code, locals())
  File "<string>", line 493, in <module>
  File "<string>", line 485, in setup_package
  File "/usr/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/usr/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/usr/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.8/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/usr/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/home/tkloczko/rpmbuild/BUILD/numpy-1.23.4/numpy/distutils/command/egg_info.py", line 25, in run
    _egg_info.run(self)
  File "/usr/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 308, in run
    self.find_sources()
  File "/usr/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 316, in find_sources
    mm.run()
  File "/usr/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 560, in run
    self.add_defaults()
  File "/usr/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 597, in add_defaults
    sdist.add_defaults(self)
  File "/usr/lib/python3.8/site-packages/setuptools/command/sdist.py", line 107, in add_defaults
    self._add_defaults_build_sub_commands()
  File "/usr/lib/python3.8/site-packages/setuptools/command/sdist.py", line 127, in _add_defaults_build_sub_commands
    self.filelist.extend(chain.from_iterable(files))
  File "/usr/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 503, in extend
    self.files.extend(filter(self._safe_path, paths))
  File "/usr/lib/python3.8/site-packages/setuptools/command/sdist.py", line 126, in <genexpr>
    files = (c.get_source_files() for c in cmds if hasattr(c, "get_source_files"))
  File "/usr/lib/python3.8/site-packages/setuptools/command/sdist.py", line 125, in <genexpr>
    cmds = (self.get_finalized_command(c) for c in missing_cmds)
  File "/usr/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 306, in get_finalized_command
    cmd_obj.ensure_finalized()
  File "/usr/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 109, in ensure_finalized
    self.finalize_options()
  File "/home/tkloczko/rpmbuild/BUILD/numpy-1.23.4/numpy/distutils/command/config_compiler.py", line 69, in finalize_options
    v = getattr(c, a)
  File "/usr/lib64/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 157, in __getattr__
    return _build_ext.build_ext.__getattr__(self, name)
  File "/usr/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 105, in __getattr__
    raise AttributeError(attr)
AttributeError: fcompiler

ERROR Backend subprocess exited when trying to invoke get_requires_for_build_wheel

```console
[tkloczko@devel-g2v SPECS]$ /usr/bin/gfortran --version
GNU Fortran (GCC) 12.2.1 20220819 (Red Hat 12.2.1-2)
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
```


### NumPy/Python version information:

numpy 1.23.4
python 3.8.14


### Context for the issue:

N/A

**Comment by rgommers** [comment]
What version of `setuptools` are you using there @kloczek?

**Comment by rgommers** [comment]
This shows that you're using the vendored distutils in setuptools:
```
  File "/usr/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 105, in __getattr__
    raise AttributeError(attr)
AttributeError: fcompiler
```

This is unsupported, please use `setuptools < 60.0` to build, that will avoid this problem.

**Comment by kloczek** [comment]
So you are not going to support latest `setuptools`? 🤔

**Comment by rgommers** [comment]
no

**Comment by kloczek** [comment]
Any reason? 🤔 
Why prev version was ok and current one is not?

**Comment by rgommers** [comment]
Please see https://numpy.org/devdocs/reference/distutils_status_migration.html

**Comment by kloczek** [comment]
`setuptools` it is currently not only one pep517 backend.
Moving away from pep517 it is not the best isea solving some issue.

And agai: 1.23.1 was pefectly fine with latest `setuptools` so something introduced after that version broke something here.
