### ISSUE TITLE
Getting ImportError: Unable to import required dependencies: numpy: while running robotmetrics command from pycharm

### ISSUE THREAD

**Issue by dhingrachirag** [numpy/numpy#22434]
### Describe the issue:

I am getting below error every-time 

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/robotmetrics", line 5, in <module>
    from robotframework_metrics.runner import main
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/robotframework_metrics/runner.py", line 3, in <module>
    from .robotmetrics import generate_report
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/robotframework_metrics/robotmetrics.py", line 10, in <module>
    from .keyword_times import KeywordTimes
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/robotframework_metrics/keyword_times.py", line 1, in <module>
    import pandas as pd
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/__init__.py", line 16, in <module>
    raise ImportError(
ImportError: Unable to import required dependencies:
numpy: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.9 from "/Library/Frameworks/Python.framework/Versions/3.9/bin/python3"
  * The NumPy version is: "1.23.3"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

> Original error was:
> dlopen(/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/numpy/core/_multiarray_umath.cpython-39-darwin.so,
> 0x0002): tried:
> '/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/numpy/core/_multiarray_umath.cpython-39-darwin.so'
> (mach-o file, but is an incompatible architecture (have (arm64), need
> (x86_64)))

### Reproduce the code example:

```python
File "/Library/Frameworks/Python.framework/Versions/3.9/bin/robotmetrics", line 5, in <module>
    from robotframework_metrics.runner import main
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/robotframework_metrics/runner.py", line 3, in <module>
    from .robotmetrics import generate_report
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/robotframework_metrics/robotmetrics.py", line 10, in <module>
    from .keyword_times import KeywordTimes
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/robotframework_metrics/keyword_times.py", line 1, in <module>
    import pandas as pd
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/__init__.py", line 16, in <module>
    raise ImportError(
ImportError: Unable to import required dependencies:
numpy:
```

### NumPy/Python version information:

- I am using macbook pro system with Apple M1 Pro chip inside
- Running robot metrics command from Pycharm PyCharm 2022.1 (Community Edition)
- The Python version is: Python3.9 
- The NumPy version is: "1.23.3"

### Context for the issue:

Requesting you to please help me in solving this issue as many of the peers are also facing the same issue with Macbook pro having M1 pro chip inside

**Comment by mattip** [comment]
You are running x86_64 python, but have installed arm64 numpy. Where did you get python from? How did you install numpy? If it is a "universal2" binary, it can run both as x86_64 and arm64. But the scientific python stack does not (yet) produce universal2 wheels: they are specific to either x86_64 or arm64.

**Comment by dhingrachirag** [comment]
Below are the answers to your questions

- Where did you get python from? 
  I downloaded python from offical site https://www.python.org/  
  Its a [macOS 64-bit universal2 installer](https://www.python.org/ftp/python/3.9.12/python-3.9.12-macos11.pkg)
  It clearly states  "**This package will install Python 3.9.12 for macOS 10.9 or later for the following architecture(s): 
  arm64, x86_64**."
  I am using version Python 3.9.12 on my mac machine

- How did you install numpy?
  I installed numpy using pip .
  pip install numpy

Please provide a workaround on this as I struck in this problem from past 7 days and still didn't get any lead.

Thanks in Advance!!!

**Comment by mattip** [comment]
My wild guess is that somehow the universal2 python is being told to run in `x86_64` mode (maybe some package loaded into python before the error triggered something that shifted from `universal2` mode to `x86_64` mode? or a command line option?). Since you did not specify `x86_64` when installing numpy, the `universal2` python preferred `arm64` and installed that version instead of the `x86_64` one. `pip` will never install a `x86_64` package when using `universal2` mode, unless forced into `x86_64` mode.

<details><summary>Too much information about architecture preference</summary>

This is because `pip` uses `packaging.tags`, which in turn uses [`platform.mac_ver()`](https://github.com/pypa/packaging/blob/fd4f11139d1c884a637be8aa26bb60a31fbc9411/packaging/tags.py#L357) to determine the architecture part of the platform tag. `platform.mac_ver()` in turn uses [`os.uname().machine`](https://github.com/python/cpython/blob/b863b9cd4b8681cf5fff5f121837a1039045783f/Lib/platform.py#L469) which will always be either `arm64` (the default) or `x86_64` (when forced).

</details>

You could try uninstalling numpy and installing while forcing `x86_64` mode:
```
arch -x86_64 python3 -m pip install numpy
```

<details><summary>Tag ordering for various invocations of python</summary>

```
% python3 -c"import pprint, packaging.tags; \
    pprint.pprint(list(packaging.tags.sys_tags()))" |grep cp38-cp38 |head -5 
[<cp38-cp38-macosx_12_0_arm64 @ 4343391680>,
 <cp38-cp38-macosx_12_0_universal2 @ 4343391488>,
 <cp38-cp38-macosx_11_0_arm64 @ 4343391872>,
 <cp38-cp38-macosx_11_0_universal2 @ 4343392064>,
 <cp38-cp38-macosx_10_16_universal2 @ 4343392256>,
% 
% arch -arm64 python3 -c"import pprint, packaging.tags; \
    pprint.pprint(list(packaging.tags.sys_tags()))" |grep cp38-cp38 |head -5
[<cp38-cp38-macosx_12_0_arm64 @ 4351972544>,
 <cp38-cp38-macosx_12_0_universal2 @ 4351972352>,
 <cp38-cp38-macosx_11_0_arm64 @ 4351972736>,
 <cp38-cp38-macosx_11_0_universal2 @ 4351972928>,
 <cp38-cp38-macosx_10_16_universal2 @ 4351973120>,
%
% arch -x86_64 python3 -c"import pprint, packaging.tags; \
    pprint.pprint(list(packaging.tags.sys_tags()))" |grep cp38-cp38 |head -5
[<cp38-cp38-macosx_12_0_x86_64 @ 4445881792>,
 <cp38-cp38-macosx_12_0_intel @ 4445881664>,
 <cp38-cp38-macosx_12_0_fat64 @ 4445882048>,
 <cp38-cp38-macosx_12_0_fat32 @ 4445882240>,
 <cp38-cp38-macosx_12_0_universal2 @ 4445882432>,
```

</details>

**Comment by dhingrachirag** [comment]
@mattip - It worked for me , I uninstalled numpy and pandas and install both packages while forcing x86_64 mode.

Thanks for your help !!!

**Comment by mattip** [comment]
I wonder if there is a way we could catch this error and recommend reinstalling a x86_64 numpy
```
    dlopen(/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/numpy/core/_multiarray_umath.cpython-39-darwin.so,
    0x0002): tried:
    '/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/numpy/core/_multiarray_umath.cpython-39-darwin.so'
    (mach-o file, but is an incompatible architecture (have (arm64), need
    (x86_64)))
```
