### ISSUE TITLE
BUG: value of a variable depends on unrelated code

### ISSUE THREAD

**Issue by ikamensh** [numpy/numpy#22528]
### Describe the issue:

I have a code where value of variable takes unexpected value, and this behaviour disappears if I change unrelated variable from numpy array to an integer. Removing if/else block in a specific location also removes incorrect behavior.

See example above, and try uncommenting a print statement on line #47. This changes the behavior of the program. Furthermore, there are few sensitive lines where changes make the bug disappear.

This might be CPython bug, but I couldn't reproduce it without numpy so far, so reporting it here.

### Reproduce the code example:

```python
import numpy as np

def step(action):
    if action == 0:  # removing this useless if/else makes the bug go away.
        return 1
    elif action == 1:
        return 1


class DummyEnvWorker:
    """Dummy worker used in sequential vector environments."""

    def __init__(self) -> None:
        self._result = None

    def step(self, action):
        self._result = step(action)
        return self.recv()

    def reset(self):
        self._result = 1
        return self.recv()

    def recv(
        self,
    ):
        assert self._result is not None, "must reset environment."
        return self._result


worker = DummyEnvWorker()
worker.reset()
action = np.ndarray([1])            # replace with `action = 1` and bug disappears.
print(worker._result)               # worker._result is 1
result = worker.step(action)        # worker._result is None ?!
```

### Error message:

```shell
STDOUT: 1
STDERR:
Traceback (most recent call last):
  File "/Users/kai7rng/PycharmProjects/py11/main.py", line 50, in <module>
    result = worker.step(action)
             ^^^^^^^^^^^^^^^^^^^
  File "/Users/kai7rng/PycharmProjects/py11/main.py", line 32, in step
    return self.recv()
           ^^^^^^^^^^^
  File "/Users/kai7rng/PycharmProjects/py11/main.py", line 41, in recv
    assert self._result is not None, "must reset environment."
AssertionError: must reset environment.
```

### NumPy/Python version information:

Tried in two environments:
```
>>> import sys, numpy; print(numpy.__version__, sys.version)
1.23.4 3.11.0 (v3.11.0:deaf509e8f, Oct 24 2022, 14:43:23) [Clang 13.0.0 (clang-1300.0.29.30)]

>>> import sys, numpy; print(numpy.__version__, sys.version)
1.23.4 3.8.5 (default, Sep  4 2020, 02:22:02) 
[Clang 10.0.0 ]
```

### Context for the issue:

I have a simple code where calling .reset() sets `worker._result` to be not None. When calling step(), worker._result must be set. In the example code I indeed correctly reset and then call step. Yet worker._result variable appears to be None; although one line before it was printed as 1.

This issue occured in production code, and I have reduced it to minimal example such that removing any more code makes the issue not visible. It's an inconsistent behavior that I'd expect from multithreaded application or such, yet I don't use threads.

**Comment by ikamensh** [comment]
sorry I was confused :)
