### ISSUE TITLE
BUG: When quantile output is specified; i.e., `out `is not None` and `keepdims = True` the `out.shape` is wrong.

### ISSUE THREAD

**Issue by aschaffer** [numpy/numpy#22544]
### Describe the issue:

 When output is specified for quantile(); i.e., `out `is not None` and `keepdims = True` the `out.shape` is wrong; it is in fact different than the returned output shape.

In the example below, the exception assumes a shape of (5, 6, 2, 4) instead of the expected (5, 6, 2, 1, 4). Which should be the correct one when `keepdims=True​`, according to documentation, because then  a dimension of 1​ is introduced in place of axis along which calculation is done.

Moreover:
     (1) the same out=q_out_5624​ works with keepdims​ both True or False;
     (2) the return shape, however, is as expected: (5, 6, 2, 1, 4) for keepdims=True ; (5, 6, 2, 4) for keepdims=False;

### Reproduce the code example:

```python
import numpy as np
arr234 = np.array([1,2,2,40,1,1,2,1,0,10,3,3,40,15,3,7,5,4,7,3,5,1,0,9]).reshape(2, 3, 4)
qs56 = np.array([x/30.0 for x in range(0, 30)]).reshape(5, 6)

out_keepdims = np.quantile(arr234, qs56, axis=1, keepdims=True)
out_no_keepdims = np.quantile(arr234, qs56, axis=1, keepdims=False)

print("correct out shape:", out_keepdims.shape)
# correct out shape: (5, 6, 2, 1, 4)
print("incorrect out shape:", out_no_keepdims.shape)
# incorrect out shape: (5, 6, 2, 4)

# The incorrect (no keepdims out) succeeds:
np.quantile(arr234, qs56, axis=1, out=out_no_keepdims, keepdims=True)
# But the correct output fails:
np.quantile(arr234, qs56, axis=1, out=out_keepdims, keepdims=True)
```

### Error message:

```shell
Traceback (most recent call last):
     File "<stdin>", line 1, in <module>
     File "<__array_function__ internals>", line 180, in quantile
     File "~/miniconda3/envs/dev_22_12_11_4_3_8/lib/python3.8/site-packages/numpy/lib/function_base.py", line 4412, in quantile
     return _quantile_unchecked(
     File "~/miniconda3/envs/dev_22_12_11_4_3_8/lib/python3.8/site-packages/numpy/lib/function_base.py", line 4424, in _quantile_unchecked
     r, k = _ureduce(a,
     File "~/miniconda3/envs/dev_22_12_11_4_3_8/lib/python3.8/site-packages/numpy/lib/function_base.py", line 3725, in _ureduce
     r = func(a, **kwargs)
     File "~/miniconda3/envs/dev_22_12_11_4_3_8/lib/python3.8/site-packages/numpy/lib/function_base.py", line 4593, in _quantile_ureduce_func
     result = _quantile(arr,
     File "~/miniconda3/envs/dev_22_12_11_4_3_8/lib/python3.8/site-packages/numpy/lib/function_base.py", line 4710, in _quantile
     result = _lerp(previous,
     File "~/miniconda3/envs/dev_22_12_11_4_3_8/lib/python3.8/site-packages/numpy/lib/function_base.py", line 4529, in _lerp
     lerp_interpolation = asanyarray(add(a, diff_b_a * t, out=out))
     ValueError: operands could not be broadcast together with shapes (5,6,2,4) (5,6,2,4) (5,6,2,1,4)
```

### NumPy/Python version information:

>>> import sys, numpy; print(numpy.__version__, sys.version)
1.23.3 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:10) 
[GCC 10.3.0]

**Comment by seberg** [comment]
Thanks, this seems indeed like a bug in the handling of `out`.  Dealing with `keepdims` must be happening after deeling with `out` correctly.  (I took the liberty of simplifying the example a bit, by just using the result without `out` to build `out`.)
