### ISSUE TITLE
Installation missing libatlas-base-dev

### ISSUE THREAD

**Issue by bripley6** [numpy/numpy#22584]
I recently installed numpy on RPI Zero running Python3.9. Upon trying to run `#import numpy` I get the error that `libcblas.so.3` is missing:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/numpy/core/__init__.py", line 23, in <module>
    from . import multiarray
  File "/usr/local/lib/python3.9/dist-packages/numpy/core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/usr/local/lib/python3.9/dist-packages/numpy/core/overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ImportError: libcblas.so.3: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/code/plotly/plot.py", line 2, in <module>
    import numpy as np
  File "/usr/local/lib/python3.9/dist-packages/numpy/__init__.py", line 140, in <module>
    from . import core
  File "/usr/local/lib/python3.9/dist-packages/numpy/core/__init__.py", line 49, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.9 from "/usr/bin/python3"
  * The NumPy version is: "1.23.4"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: libcblas.so.3: cannot open shared object file: No such file or directory
```

It seems a required package for numpy doesn't get installed by default. I was able to get my import command to succeed by installing this package: `sudo apt-get install libatlas-base-dev`. Shouldn't this dependency automatically get installed or at least flagged from a `python3 -m pip install numpy`command?

**Comment by mattip** [comment]
Almost duplicate of #11110. We do not provide wheels for Raspberry PI, you probably got the wheel [from piwheels](https://www.piwheels.org/) instead. They will have to fix this in their packaging.

**Comment by bripley6** [comment]
Thank you for the pointer! For those interested in following this issue I have created a new issue at https://github.com/piwheels/piwheels/issues/329
