### ISSUE TITLE
BUG: `numpy.median()` does not respect `keepdims=True` when the `out` argument is specified

### ISSUE THREAD

**Issue by byrdie** [numpy/numpy#22714]
### Describe the issue:

`numpy.median()` is ignoring `keepdims=True` when the `out` argument is set. If `out` has the same number of dimensions as the input, an error is raised. If `out` has the number of dimensions consistent with `keepdims=False` no error is raised.

I'm happy to try and open a PR to fix this issue if we decide that this is indeed a bug.

### Reproduce the code example:

```python
import numpy as np
np.median(np.random.random((11, 12, 13)), axis=~0, out=np.empty((11, 12, 1)), keepdims=True)
```

### Error message:

```shell
Traceback (most recent call last):
  File "C:\Users\royts\AppData\Local\Programs\Python\Python310\lib\site-packages\IPython\core\interactiveshell.py", line 3378, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-10-a37955de53f7>", line 1, in <module>
    np.median(np.random.random((11, 12, 13)), axis=~0, out=np.empty((11, 12, 1)), keepdims=True)
  File "<__array_function__ internals>", line 180, in median
  File "C:\Users\royts\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\function_base.py", line 3816, in median
    r, k = _ureduce(a, func=_median, axis=axis, out=out,
  File "C:\Users\royts\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\function_base.py", line 3725, in _ureduce
    r = func(a, **kwargs)
  File "C:\Users\royts\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\function_base.py", line 3870, in _median
    rout = mean(part[indexer], axis=axis, out=out)
  File "<__array_function__ internals>", line 180, in mean
  File "C:\Users\royts\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\core\fromnumeric.py", line 3432, in mean
    return _methods._mean(a, axis=axis, dtype=dtype,
  File "C:\Users\royts\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\core\_methods.py", line 180, in _mean
    ret = umr_sum(arr, axis, dtype, out, keepdims, where=where)
ValueError: output parameter for reduction operation add has the wrong number of dimensions: Found 3 but expected 2
```

### NumPy/Python version information:

1.23.5 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]

**Comment by byrdie** [comment]
Looks like there is also similar behavior for `np.nanmedian()`, `np.percentile()`, `np.nanpercentile()`, `np.quantile()` and `np.nanquantile()`.

**Comment by mhvk** [comment]
Definitely a bug! This works correctly for `np.mean`.

**Comment by byrdie** [comment]
@mhvk, thanks for confirming that. I guess I'll look into what `np.mean` does differently.
