### ISSUE TITLE
BUG: RecursionError with np.meshgrid

### ISSUE THREAD

**Issue by hulmakerik** [numpy/numpy#22715]
### Describe the issue:

I encountered the error below that does not make sense. It occurred during generating synthetic dateset with blender within a docker container. Unfortunately I can't provide more info. I don't even know if it is possible to reproduce it.

### Reproduce the code example:

```python
k = np.array([[-1, 1, 0], [1, 1, 0], [1, -1, 0], [-1, -1, 0]], dtype=float)
pw = k * 4.8 * 0.3  # edit seberg, was:  k * self.cam.h * 0.3    # self.cam.h: float = 4.8
n = len(pw)
ij = np.array(np.meshgrid(np.arange(n), np.arange(n)))  # ij meshgrid
```

### Error message:

```shell
transformer.py", line 95, in _estimate_px_per_m
    ij = np.array(np.meshgrid(np.arange(n), np.arange(n)))  # ij meshgrid
  File "<__array_function__ internals>", line 180, in meshgrid
  File "/home/user/blender-3.3.1-linux-x64/3.3/python/lib/python3.10/site-packages/numpy/lib/function_base.py", line 4987, in meshgrid
    output = np.broadcast_arrays(*output, subok=True)
  File "<__array_function__ internals>", line 180, in broadcast_arrays
  File "/home/user/blender-3.3.1-linux-x64/3.3/python/lib/python3.10/site-packages/numpy/lib/stride_tricks.py", line 546, in broadcast_arrays
    return [_broadcast_to(array, shape, subok=subok, readonly=False)
  File "/home/user/blender-3.3.1-linux-x64/3.3/python/lib/python3.10/site-packages/numpy/lib/stride_tricks.py", line 546, in <listcomp>
    return [_broadcast_to(array, shape, subok=subok, readonly=False)
  File "/home/user/blender-3.3.1-linux-x64/3.3/python/lib/python3.10/site-packages/numpy/lib/stride_tricks.py", line 345, in _broadcast_to
    if any(size < 0 for size in shape):
  File "/home/user/blender-3.3.1-linux-x64/3.3/python/lib/python3.10/site-packages/numpy/lib/stride_tricks.py", line 345, in <genexpr>
    if any(size < 0 for size in shape):
RecursionError: maximum recursion depth exceeded in comparison

Traceback (most recent call last):
  File "/home/user/.config/blender/3.3/scripts/addons/HumGen3D/core/HG_CALLBACK.py", line 85, in HG_Callback
    _context_specific_updates(self, sett, hg_rig, ui_phase)
  File "/home/user/.config/blender/3.3/scripts/addons/HumGen3D/core/HG_CALLBACK.py", line 160, in _context_specific_updates
    _refresh_body_scaling(self, sett, hg_rig)
  File "/home/user/.config/blender/3.3/scripts/addons/HumGen3D/core/HG_CALLBACK.py", line 194, in _refresh_body_scaling
    slider_value = bones[bone_group[0]].scale[0] * 3 - 2.5
KeyError: 'bpy_prop_collection[key]: key "spine.002" not found'
```

### NumPy/Python version information:

1.23.5 3.10.2 (main, Apr 26 2022, 10:33:12) [GCC 9.3.1 20200408 (Red Hat 9.3.1-2)]

### Context for the issue:

Low priority, unable to reproduce, does not occur periodically

**Comment by seberg** [comment]
@hulmakerik are you sure you have `self.cam.h = 4.8` there?  So that the example is actually self contained?

I will make a wild guess:  You are using a Python 3.10 with some library that uses `cython` *and* you are using a jupyter notebook or something else that enables "tracing" (e.g. a debugger `sys.gettrace()` returns something) *and* the cython version that was used to compile the package you are using was slightly outdated...

In that case something might "by accident" monkey-patch even NumPy internals.  The issue was fixed in cython quite long ago.

In either case, I would be very very surprised if there is a NumPy issue here.  There clearly is some issue though.

**Comment by seberg** [comment]
@hulmakerik sorry that you saw this issue.  I am going to close it, because we don't have anything to go on right now.  I still suspect the cython+Python 3.10 interplay issue (with tracing).
If that is the issue, then it should just magically disappear when updating whatever library used the old cython for compilation.  NumPy, pandas etc. binaries were all updated long ago.

Happy to reopen if there is any additional information!
