### ISSUE TITLE
BUG: quantile fails with out=output when casting is necessary

### ISSUE THREAD

**Issue by aschaffer** [numpy/numpy#22766]
### Describe the issue:

When `out is not None` and it is of a different type than `float` or different from the type the quantile() call would return as a return parameter, `quantile()` fails (see error message below).

The documented `numpy.quantile` functionality specifies that casting should be done if necessary: 
```
out ndarray, optional
Alternative output array in which to place the result. It must have the same shape and buffer length as the expected output, but the type (of the output) will be cast if necessary.
```

### Reproduce the code example:

```python
import numpy as np
qs_arr = np.array([0.0, 0.5, 1.0])
q_out = np.zeros(3, dtype=int)
np.quantile(np.arange(4, dtype=float), qs_arr, out=q_out) # fails with error message below

q_outf = np.zeros(3, dtype=float)
np.quantile(np.arange(4, dtype=float), qs_arr, out=q_outf) # works fine
array([0. , 1.5, 3. ])
```

### Error message:

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<__array_function__ internals>", line 180, in quantile
  File "miniconda3/envs/dev_22_12_11_4_3_8/lib/python3.8/site-packages/numpy/lib/function_base.py", line 4412, in quantile
    return _quantile_unchecked(
  File "miniconda3/envs/dev_22_12_11_4_3_8/lib/python3.8/site-packages/numpy/lib/function_base.py", line 4424, in _quantile_unchecked
    r, k = _ureduce(a,
  File "miniconda3/envs/dev_22_12_11_4_3_8/lib/python3.8/site-packages/numpy/lib/function_base.py", line 3725, in _ureduce
    r = func(a, **kwargs)
  File "miniconda3/envs/dev_22_12_11_4_3_8/lib/python3.8/site-packages/numpy/lib/function_base.py", line 4593, in _quantile_ureduce_func
    result = _quantile(arr,
  File "miniconda3/envs/dev_22_12_11_4_3_8/lib/python3.8/site-packages/numpy/lib/function_base.py", line 4710, in _quantile
    result = _lerp(previous,
  File "miniconda3/envs/dev_22_12_11_4_3_8/lib/python3.8/site-packages/numpy/lib/function_base.py", line 4529, in _lerp
    lerp_interpolation = asanyarray(add(a, diff_b_a * t, out=out))
numpy.core._exceptions.UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'
```

### NumPy/Python version information:

1.23.3 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:10) 
[GCC 10.3.0]

**Comment by firest11** [comment]
I feel like the simplest solution would be to consider cases of when `q_out` matches the type of the input array or not, in the following way:

```
@array_function_dispatch(_quantile_dispatcher)
def quantil(a, 
                  q, 
                  axis=None, 
                  out=None, 
                  overwrite_input=False, 
                  method="linear", 
                  keepdims=False, 
                  *, 
                  interolation=None):
    """Docstring Goes Here"""
    if interpolation is not None:
        method = _check_interpolation_as_method(
            method, interpolation, "quantile")

    a = np.asanyarray(a)
    if a.dtype.kind == "c":
        raise TypeError("a must be an array of real numbers")

    q = np.asanyarray(q)
    if not _quantile_is_valid(q):
        raise ValueError("Quantiles must be in the range [0, 1]")
    # main modification here
    if (out is not None) and (a.dtype != out.dtype):
        out_dtype = out.dtype
        temp_out = _quantile_unchecked(a, q, axis, overwrite_input, method, keepdims)
        out = temp_out.astype(out_dtype)
        return out
    else:
        # original implementation of return
        return _quantile_unchecked(a, q, axis, out, overwrite_input, method, keepdims)
```

However, the main source of error comes from the ufunc `add` function with the error message

```
UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'
```
The ufunc `add` function contains an `out` parameter that functions, presumably, the same as how we would expect it to act for the quantile method. This would mean that we should expect the ufuncs to perform this kind of recasting under-the-hood.

My simple solution seems like a bandaid to the real problem, but it would functionally fix the bug. What do the core developers think? How should I (or others) approach this?

**Comment by MatteoRaso** [comment]
>How should I (or others) approach this?

Instead of the band-aid approach, you can just change the casting rule for "add".

**Comment by seberg** [comment]
Sorry, didn't look at the PR earlier.  I have a bit of a feeling that being strict has no downsides so I am hesitant to just relax things.  What do others think?

The only problem is that in that case, the non-interpolating methods like:
```
import numpy as np
qs_arr = np.array([0.0, 0.5, 1.0])
q_out = np.zeros(3, dtype=int)
np.quantile(np.arange(4, dtype=float), qs_arr, method="inverted_cdf", out=q_out)
```
should also use `same-kind` casting.  That is actually _should_ already be the case (I think), but `take` is also broken, see gh-16319:
```
np.quantile(np.arange(4, dtype=int), qs_arr, method="inverted_cdf", out=q_out.astype("double"))  # makes more sense, but ooopses
```
