### ISSUE TITLE
BUG: `deepcopy(np.polynomial.Polynomial(...))` fails

### ISSUE THREAD

**Issue by ctgk** [numpy/numpy#22865]
### Describe the issue:

numpy==1.24.0 fails to run `deepcopy(np.polynomial.Polynomial(...))` whereas a previous version (numpy==1.23.0) passes.
It seems to be that the cause is using `copy` method of `self.symbol`, which is not defined as it is `str` object.

Failure using numpy==1.24.0

```
$ pip install numpy==1.24.0
Collecting numpy==1.24.0
  Downloading numpy-1.24.0-cp310-cp310-macosx_11_0_arm64.whl (13.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 3.6 MB/s eta 0:00:00
Installing collected packages: numpy
Successfully installed numpy-1.24.0
$ python
Python 3.10.3 (main, May  7 2022, 14:13:10) [Clang 13.1.6 (clang-1316.0.21.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from copy import deepcopy; import numpy as np
>>> deepcopy(np.polynomial.Polynomial([1, 1, 1]))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/.../.pyenv/versions/3.10.3/lib/python3.10/copy.py", line 161, in deepcopy
    rv = reductor(4)
  File "/Users/.../.pyenv/versions/tmp-3.10.3/lib/python3.10/site-packages/numpy/polynomial/_polybase.py", line 502, in __getstate__
    ret['symbol'] = self.symbol.copy()
AttributeError: 'str' object has no attribute 'copy'
```

No error using numpy==1.23.0

```
$ pip install numpy==1.23
Collecting numpy==1.23
  Downloading numpy-1.23.0-cp310-cp310-macosx_11_0_arm64.whl (13.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.3/13.3 MB 5.9 MB/s eta 0:00:00
Installing collected packages: numpy
Successfully installed numpy-1.23.0
$ python
Python 3.10.3 (main, May  7 2022, 14:13:10) [Clang 13.1.6 (clang-1316.0.21.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from copy import deepcopy; import numpy as np
>>> deepcopy(np.polynomial.Polynomial([1, 1, 1]))
Polynomial([1., 1., 1.], domain=[-1,  1], window=[-1,  1])
```

### Reproduce the code example:

```python
from copy import deepcopy; import numpy as np
f = np.polynomial.Polynomial([1, 1, 1])
deepcopy(f)
```

### Error message:

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/.../.pyenv/versions/3.10.3/lib/python3.10/copy.py", line 161, in deepcopy
    rv = reductor(4)
  File "/Users/.../.pyenv/versions/tmp-3.10.3/lib/python3.10/site-packages/numpy/polynomial/_polybase.py", line 502, in __getstate__
    ret['symbol'] = self.symbol.copy()
AttributeError: 'str' object has no attribute 'copy'
```

### Runtime information:

```python
>>> import sys; import numpy as np
>>> print(np.__version__)
1.24.0
>>> print(sys.version)
3.10.3 (main, May  7 2022, 14:13:10) [Clang 13.1.6 (clang-1316.0.21.2)]
>>> print(np.show_runtime())
WARNING: `threadpoolctl` not found in system! Install it by `pip install threadpoolctl`. Once installed, try `np.show_runtime` again for more detailed build information
[{'simd_extensions': {'baseline': ['NEON', 'NEON_FP16', 'NEON_VFPV4', 'ASIMD'],
                      'found': ['ASIMDHP', 'ASIMDDP'],
                      'not_found': ['ASIMDFHM']}}]
None
```

**Comment by seberg** [comment]
Sounds like a missing backport on gh-22670, marked that PR for backporting.
