### ISSUE TITLE
import numpy in python_d.exe

### ISSUE THREAD

**Issue by Shaun-Wong** [numpy/numpy#22974]
### Steps to reproduce:

When i import numpy in python_d.exe, there are some problems. 

### Error message:

```shell
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "E:\Learning\Postgraduate\FreeCAD\INSTALL\bin\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "E:\Learning\Postgraduate\FreeCAD\INSTALL\bin\lib\site-packages\numpy\__init__.py", line 141, in <module>
    from . import core
  File "E:\Learning\Postgraduate\FreeCAD\INSTALL\bin\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "E:\Learning\Postgraduate\FreeCAD\INSTALL\bin\lib\site-packages\numpy\core\__init__.py", line 49, in <module>
    raise ImportError(msg)
ImportError: 
IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.8 from "E:\Learning\Postgraduate\FreeCAD\INSTALL\bin\FreeCAD_d.exe"
  * The NumPy version is: "1.24.1"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'
```

**Comment by mattip** [comment]
As I responded in #11508, something is wrong with the way you have set up Visual Studio or MSVC tools, due to this error `LINK : fatal error LNK1104: 无法打开文件“kernel32.lib”`. This is not a NumPy-specific problem. You may have more success solving this problem locally: showing your work to a colleague or friend who can see what you are doing.

**Comment by Shaun-Wong** [comment]
Thank you! I have solved this problem.
