### ISSUE TITLE
BUG: numpy dev breaks `scipy.stats`

### ISSUE THREAD

**Issue by neutrinoceros** [numpy/numpy#23033]
### Describe the issue:

The current state of the dev branch (1.25.0.dev0+403.g0013550dc) breaks `scipy.stats` completely.

### Reproduce the code example:

```python
import scipy.stats
```

### Error message:

```shell
-traceback
Traceback (most recent call last):
  File "/Users/robcleme/dev/friends/AMICAL/t.py", line 1, in <module>
    import scipy.stats
  File "/Users/robcleme/.pyenv/versions/amical-dev/lib/python3.10/site-packages/scipy/stats/__init__.py", line 467, in <module>
    from ._stats_py import *
  File "/Users/robcleme/.pyenv/versions/amical-dev/lib/python3.10/site-packages/scipy/stats/_stats_py.py", line 46, in <module>
    from . import distributions
  File "/Users/robcleme/.pyenv/versions/amical-dev/lib/python3.10/site-packages/scipy/stats/distributions.py", line 8, in <module>
    from ._distn_infrastructure import (rv_discrete, rv_continuous, rv_frozen)
  File "/Users/robcleme/.pyenv/versions/amical-dev/lib/python3.10/site-packages/scipy/stats/_distn_infrastructure.py", line 27, in <module>
    from scipy import integrate
  File "/Users/robcleme/.pyenv/versions/amical-dev/lib/python3.10/site-packages/scipy/integrate/__init__.py", line 91, in <module>
    from ._quadrature import *
  File "/Users/robcleme/.pyenv/versions/amical-dev/lib/python3.10/site-packages/scipy/integrate/_quadrature.py", line 31, in <module>
    trapezoid = _copy_func(trapezoid)
  File "/Users/robcleme/.pyenv/versions/amical-dev/lib/python3.10/site-packages/scipy/integrate/_quadrature.py", line 24, in _copy_func
    g = types.FunctionType(f.__code__, f.__globals__, name=f.__name__,
AttributeError: 'numpy._ArrayFunctionDispatcher' object has no attribute '__code__'. Did you mean: '__call__'?
```

### Runtime information:

```
1.25.0.dev0+403.g0013550dc
3.10.8 (main, Nov 13 2022, 10:42:10) [Clang 14.0.0 (clang-1400.0.29.202)]

WARNING: `threadpoolctl` not found in system! Install it by `pip install threadpoolctl`. Once installed, try `np.show_runtime` again for more detailed build information
[{'numpy_version': '1.25.0.dev0+403.g0013550dc',
  'python': '3.10.8 (main, Nov 13 2022, 10:42:10) [Clang 14.0.0 '
            '(clang-1400.0.29.202)]',
  'uname': uname_result(system='Darwin', node='ipag-8102.u-ga.fr', release='22.2.0', version='Darwin Kernel Version 22.2.0: Fri Nov 11 02:08:47 PST 2022; root:xnu-8792.61.2~4/RELEASE_X86_64', machine='x86_64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_KNL',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}}]
None
```

### Context for the issue:

discovered today while running tests for a package that depends on both scipy and numpy, using nightly builds for both
https://github.com/SAIL-Labs/AMICAL/commit/8e7ebf05bf034218d1d78304542d29f4109ad534/checks?check_suite_id=10430628610

**Comment by seberg** [comment]
SciPy thinks its OK to assume that `np.trapz` is written in Python.  To me that sounds like is using implementation details, but we can ["write it in python"](https://github.com/numpy/numpy/pull/23034)

**Comment by neutrinoceros** [comment]
thanks ! Sorry I missed the ticket on scipy (https://github.com/scipy/scipy/issues/17811)

**Comment by jjerphan** [comment]
@seberg: can you install `threadpoolctl` and report the result of the execution of the following command?

```
python -m threadpoolctl -i scipy
```

**Comment by jjerphan** [comment]
@neutrinoceros: can you install `threadpoolctl` and report the result of the execution of the following command?

```
python -m threadpoolctl -i scipy
```

Thank you!

**Comment by seberg** [comment]
@jjerphan not sure what you mean, this issue is just a small wonky interplay between numpy/scipy that happens already when importing some of scipy (not sure what you need).  It shouldn't have anything to do with threadpoolctl, although I guess `threadpoolctl -i scipy` might do imports that run into it.

**Comment by jjerphan** [comment]
Ah, it's just that `threadpoolctl` allows getting more runtime information (as indicated by the WARNING in the trace). :)

**Comment by pllim** [comment]
I see the same error but from slightly different import. What is the fix?

```
2023-01-19T14:58:54.3997538Z     import skimage.measure
2023-01-19T14:58:54.3997993Z ../../.tox/py311-test-devdeps/lib/python3.11/site-packages/skimage/measure/__init__.py:6: in <module>
2023-01-19T14:58:54.3998392Z     from ._polygon import approximate_polygon, subdivide_polygon
2023-01-19T14:58:54.3998887Z ../../.tox/py311-test-devdeps/lib/python3.11/site-packages/skimage/measure/_polygon.py:2: in <module>
2023-01-19T14:58:54.3999223Z     from scipy import signal
2023-01-19T14:58:54.3999662Z ../../.tox/py311-test-devdeps/lib/python3.11/site-packages/scipy/signal/__init__.py:325: in <module>
2023-01-19T14:58:54.3999979Z     from ._ltisys import *
2023-01-19T14:58:54.4000421Z ../../.tox/py311-test-devdeps/lib/python3.11/site-packages/scipy/signal/_ltisys.py:28: in <module>
2023-01-19T14:58:54.4000797Z     from scipy import integrate, interpolate, linalg
2023-01-19T14:58:54.4001282Z ../../.tox/py311-test-devdeps/lib/python3.11/site-packages/scipy/integrate/__init__.py:91: in <module>
2023-01-19T14:58:54.4001613Z     from ._quadrature import *
2023-01-19T14:58:54.4002174Z ../../.tox/py311-test-devdeps/lib/python3.11/site-packages/scipy/integrate/_quadrature.py:31: in <module>
2023-01-19T14:58:54.4002539Z     trapezoid = _copy_func(trapezoid)
2023-01-19T14:58:54.4003016Z ../../.tox/py311-test-devdeps/lib/python3.11/site-packages/scipy/integrate/_quadrature.py:24: in _copy_func
2023-01-19T14:58:54.4003426Z     g = types.FunctionType(f.__code__, f.__globals__, name=f.__name__,
2023-01-19T14:58:54.4003912Z E   AttributeError: 'numpy._ArrayFunctionDispatcher' object has no attribute '__code__'
```

From https://github.com/spacetelescope/jdaviz/actions/runs/3959487651/jobs/6782368719

**Comment by seberg** [comment]
@pllim we have to wrap NumPy `trapz` into a Python function (until SciPy does it itself maybe, or just vendors it).  A plausible solution is gh-23034 (there are some other possible paths, like not wrapping the original `trapz` but just copying all the information scipy needs over to the original `trapz` from the "Python version").

**Comment by jbrockmendel** [comment]
same thing is now breaking the pandas CI

**Comment by pllim** [comment]
Thanks! When will this propagate to numpy "nightly" wheel? 🤞

**Comment by rgommers** [comment]
FYI, I have started a new wheel build job manually ([link](https://github.com/numpy/numpy/actions/runs/3968501675)), once that completes we should have new nightly wheels on anaconda.org/scipy-wheels-nightly/ and the CI problems for other projects should disappear.

**Comment by pllim** [comment]
I can confirm that astropy dev job now passes. Thank you so much for the quick fix!
