### ISSUE TITLE
BUG: Impossible to import setup_common (needed to get C_API_VERSION) on Numpy >= 1.23

### ISSUE THREAD

**Issue by raulfrk** [numpy/numpy#23104]
### Describe the issue:

After upgrading to any Numpy version >= 1.23, importing setup_common, which can be used to get the current C_API_VERSION, does not work anymore. This was tested on both python 3.7.16 and 3.8.16 and in both cases it does not work.

### Reproduce the code example:

```python
import numpy.core.setup_common
```

### Error message:

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user01/v38/lib/python3.8/site-packages/numpy/core/setup_common.py", line 116, in <module>
    with open(pathlib.Path(__file__).parent / file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/user01/v38/lib/python3.8/site-packages/numpy/core/feature_detection_locale.h'
```

### Runtime information:

>>> import sys, numpy; print(numpy.__version__); print(sys.version)
1.24.1
3.8.13 (default, Apr 19 2022, 00:53:22) 
[GCC 7.5.0]
>>> print(numpy.show_runtime())
[{'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2',
                                'AVX512F',
                                'AVX512CD',
                                'AVX512_SKX'],
                      'not_found': ['AVX512_KNL',
                                    'AVX512_KNM',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}},
 {'architecture': 'SkylakeX',
  'filepath': '/home/user01/v38/lib/python3.8/site-packages/numpy.libs/libopenblas64_p-r0-15028c96.3.21.so',
  'internal_api': 'openblas',
  'num_threads': 56,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.21'}]
None

### Context for the issue:

Not being able to import setup_common anymore prevents users from getting the value of the `C_API_VERSION` constant found inside of it. `C_API_VERSION` is useful to check if there is a C_API mismatch in C modules before the "import_array()" function is called so that preventive action can be taken in case of C api version mismatch.

Here is an example of how C_API_VERSION was used before in C:

``` C
PyObject *module = PyImport_ImportModule("numpy.core.setup_common")
PyObject *obj_c_api_version = PyObject_GetAttrString("C_API_VERSION")
const char* c_api_version  = PyString_AsString(obj_c_api_version);
```
`c_api_version` would be later used to compare it with the NPY_FEATURE_VERSION (build-time C api version) to see if there is a mismatch and act on it before calling `import_array()` which performs similar checks but crashes due to the mismatch.

**Comment by rgommers** [comment]
@raulfrk `numpy.core.setup_common` is not public API, so you shouldn't be using that. 

> Here is an example of how C_API_VERSION was used before in C:

At build time you can use `NPY_API_VERSION` (see, e.g., https://numpy.org/devdocs/user/c-info.how-to-extend.html#example). At runtime, why can't you simply use `np.__version__` if you're calling back into Python anyway? There is a 1:1 mapping between C API version and the main numpy version.

**Comment by seberg** [comment]
If you are worried about compatibility with future versions: I don't think you should, `import_array` has a check build in for any major change: We have an ABI version (which is never changed, but *can* be changed when it becomes necessary).

There is also `PyArray_GetNDArrayCFeatureVersion` in C, although I don't really see that you should have a reason to use it and as Ralf says, it effectively tracks the normal version.

**Comment by raulfrk** [comment]
> @raulfrk `numpy.core.setup_common` is not public API, so you shouldn't be using that.
> 
> > Here is an example of how C_API_VERSION was used before in C:
> 
> At build time you can use `NPY_API_VERSION` (see, e.g., https://numpy.org/devdocs/user/c-info.how-to-extend.html#example). At runtime, why can't you simply use `np.__version__` if you're calling back into Python anyway? There is a 1:1 mapping between C API version and the main numpy version.

@rgommers The mapping is not 1:1 as some np versions share C API versions (e.g. 1.23 and 1.24 have C API version 16 while 1.22 has C API version 14) otherwise there would be no need to distinguish between Numpy versions and C API versions.

**Comment by rgommers** [comment]
In the `np.__version__` -> C API version direction that doesn't matter, it is unambiguous.

**Comment by raulfrk** [comment]
> If you are worried about compatibility with future versions: I don't think you should, `import_array` has a check build in for any major change: We have an ABI version (which is never changed, but _can_ be changed when it becomes necessary).
> 
> There is also `PyArray_GetNDArrayCFeatureVersion` in C, although I don't really see that you should have a reason to use it and as Ralf says, it effectively tracks the normal version.

@seberg I am aware of the check inside import_array(), but my goal is to anticipate that check and perform a comparison between the build-time np C API version and run-time np C API version before calling import_array() in order to have more control over what exception is thrown and how it is handled.

I will give you a brief example of what I mean:

Imagine having a python project with a C extension that uses numpy. At some point during module initialisation, the `import_array()` function is called. What I would like to achieve is to add a portion of code before `import_array()` is called that checks if there is a C API version mismatch.
``` C
PyMODINIT_FUNC PyInit_some_module(void)
{
    // Custom C API version mismatch check
    // if build_time_c_api_version != run_time_c_api_version
    // do something about it... 
    PyObject* ret = PyModule_Create(&some_module);
    import_array();
    return ret;
}```

As previously mentioned, the build-time C API version can be easily obtained with NPY_API_VERSION, but there seems to be no proper way to get the run-time version.

**Comment by chebee7i** [comment]
I also would like access to the `C_API_VERSION`.  The numpy version is not in a 1-1 correspondence.  

One use case is that we would like to provide separate builds of bindings that have a dependence on NumPy. Triggering new builds on each NumPy version could work, but since the C_API_VERSION can be the same across multiple NumPy versions, it is actually a bit wasteful.

**Comment by mattip** [comment]
@chebee7i are you using features from the newer C_API? If not there is no need to rebuild, your older bindings will run against newer versions of NumPy. We try to be very careful about backward compatibility.

**Comment by chebee7i** [comment]
Our situation is a bit weird, but the end result is people are often running code from a git repository, and this code needs to be flexible enough to work with multiple (conda) environments, potentially including NumPy versions that span a change in the `C_API_VERSION`.  We need to have separate builds per C_API_VERSION, otherwise, we get messages like:
```console
RuntimeError                              Traceback (most recent call last)
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf
```

So for example, conda env X might be on NumPy 1.23.3 and conda env Y might be on NumPy 1.22.4.  The code in the repository needs to conditionally make available the proper set of bindings at runtime, and while we could branch on the numpy version, the `C_API_VERSION` seems more relevant.

**Comment by seberg** [comment]
The typical solution is that when you build something you want to move between systems, you build a wheel.  And during a wheel build, you use the `oldest_supported_numpy` (it is a package) as a build dependency.
That way, your wheel is compiled against the oldest NumPy version at *build* time and that will compatible to all environments.

I would have thought such a build is the default in most cases, unless something like `--no-build-isolation` is passed?

**Comment by chebee7i** [comment]
That's one way to do it, but not every environment is set up that way, and there are scenarios where that still doesn't work. 
 - `oldest_supported_numpy` only works if the features you are using are actually compatible with the oldest NumPy version for a given Python version and platform
 - it also makes assumptions about how the bindings were built.  In my scenario, the bindings are built as part of a much larger, bespoke cmake build with somewhat frozen conventions. So proposing changes to the process is a much longer route...whereas having access to the version gives a route that is compatible with existing conventions.

While I appreciate discussing alternative ways to build, the question here is whether the C API version should be obtainable from the runtime library.  It's clearly not an implementation detail as it has real world impact and is mentioned in exception messages. Exposing it seems in the spirit of not making assumptions about the precise details of people's environments and build systems.

**Comment by rgommers** [comment]
It's still not clear why you can't write a very simply function locally that returns the C API version, taking as input `np.__version__`. It will solve your problem today, also for older versions of numpy, which exposing the C API version number directly will not do any time soon.

**Comment by rgommers** [comment]
If we want to make the C API version accessible at runtime, it should probably be `np.__c_api_version__`. The use case from @raulfrk is a bit thin, but it is a real one. @chebee7i's one I'm less sure of - running Python code at build time to obtain this does have unwanted side effects like not working for cross-compilation purposes (more and more important), so I'd say obtaining the C API version number is strictly worse than using static metadata a la `oldest-supported-numpy` or whatever equivalent one needs to encode in metadata based on the regular numpy version number otherwise.
