### ISSUE TITLE
BUG: np.isclose with datetime64 and timedelta64 types fail with error messages that reveal implementation details

### ISSUE THREAD

**Issue by jpivarski** [numpy/numpy#23157]
### Describe the issue:

I wouldn't expect numbers with units, like datetime64 and timedelta64, to be comparable with numbers without units, but comparing datetime64 with datetime64 and timedelta64 with timedelta64 could be meaningful if the `atol` has units. And maybe `rtol` doesn't have a meaning for datetime64, since that is an interval measure in Stevens's classification, rather than a ratio measure.

Anyway, even if the chosen behavior is that all time-related types should fail in `np.isclose`, the error messages don't say that—they just reach a step in the calculation and fail. See the code examples below.

### Reproduce the code example:

```python
First, with datetime64:


np.allclose(np.array([1, 2, 3, 4], "M8"), np.array([1, 2, 3, 4], "M8"))


Now with timedelta64:

```python
np.allclose(np.array([1, 2, 3, 4], "m8"), np.array([1, 2, 3, 4], "m8"))
```
```


### Error message:

```shell
The error message with datetime64:


Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: Converting an integer to a NumPy datetime requires a specified unit
```

The error message with timedelta64:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<__array_function__ internals>", line 180, in allclose
  File "/home/jpivarski/mambaforge/lib/python3.9/site-packages/numpy/core/numeric.py", line 2265, in allclose
    res = all(isclose(a, b, rtol=rtol, atol=atol, equal_nan=equal_nan))
  File "<__array_function__ internals>", line 180, in isclose
  File "/home/jpivarski/mambaforge/lib/python3.9/site-packages/numpy/core/numeric.py", line 2375, in isclose
    return within_tol(x, y, atol, rtol)
  File "/home/jpivarski/mambaforge/lib/python3.9/site-packages/numpy/core/numeric.py", line 2356, in within_tol
    return less_equal(abs(x-y), atol + rtol * abs(y))
numpy.core._exceptions._UFuncBinaryResolutionError: ufunc 'add' cannot use operands with types dtype('float64') and dtype('<m8')
```
```


### Runtime information:

```python
>>> import sys, numpy; print(numpy.__version__); print(sys.version)
1.23.5
3.9.15 | packaged by conda-forge | (main, Nov 22 2022, 08:45:29) 
[GCC 10.4.0]
```

```python
>>> print(numpy.show_runtime())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jpivarski/mambaforge/lib/python3.9/site-packages/numpy/__init__.py", line 311, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'show_runtime'
```

(NumPy is 1.23.)

### Context for the issue:

I was examining the limits of `np.isclose` so that Awkward Array can formally extend it, in https://github.com/scikit-hep/awkward/pull/2198. As I said above, what `np.isclose` can do with time-unit types is somewhat limited; an error message saying that it isn't supported would be fine. But then Awkward Array would raise the same exception under the same circumstances.

**Comment by seberg** [comment]
Note that the first error is not what is happening.  The ValueError comes from the `np.asarray()` call, not the `allclose`/`isclose` one.

On main, that will lead to a `DTypePromotionError` (which is public on main) and more similar to that ufunc error (in fact, maybe that one should be a subclass and print identically, or maybe both should just be subclasses to `DTypeError` or so).

So both fail in more similar ways and I suspect it would be OK to consider both `DTypePromotionError`.  As of now, both are `TypeError` with different printing (I am ignoring the `ValueError`, which I think is OK since it happens in the asarray call).

**Comment by Adesoji1** [comment]
@jpivarski The numpy.allclose function does not currently support datetime64 or timedelta64 types, even when units are specified. The function is mainly intended for comparing numeric types within a certain tolerance, and these datetime types don't fit within that use case.

As an alternative, if you want to compare datetime64 arrays, you can directly use the numpy.array_equal function, which will check if two arrays have the same shape and elements:

```
import numpy as np

# Specify units for datetime64 array
print(np.array_equal(np.array([1, 2, 3, 4], "M8[D]"), np.array([1, 2, 3, 4], "M8[D]")))

# Specify units for timedelta64 array
print(np.array_equal(np.array([1, 2, 3, 4], "m8[D]"), np.array([1, 2, 3, 4], "m8[D]")))

True
True
```
Note that array_equal does an exact comparison and does not support tolerances. If you want to implement a tolerance or "closeness" comparison for datetime or timedelta arrays, you would need to define your own function for this, taking into account how you define "closeness" in terms of time durations.
Numpy 1.23.5 version

**Comment by jpivarski** [comment]
I'm not surprised; datetimes and timedeltas are integer types, and I'd expect `isclose` to only work on floating point types, for which tolerances can be defined. What prompted me to file the bug report is that the error message is

```
_UFuncBinaryResolutionError: ufunc 'add' cannot use operands with types dtype('float64') and dtype('<m8')
```

in the implementation of `isclose`, rather than something like

```
TypeError: dtype('<m8') cannot be used in np.isclose
```

which would be a clearer explanation of the scope of `isclose`.
