### ISSUE TITLE
BUG: <Please write a comprehensive title after the 'BUG: ' prefix>

### ISSUE THREAD

**Issue by xushanthu-2014** [numpy/numpy#23198]
### Describe the issue:

Failed to import ```import numpy.linalg.lapack_lite```. I am using Spyder under a specific environment named as ```kaggle```. I am using MacOS, firstly I opened terminal, then type the command ```conda activate kaggle```, then open the Spyder by ```spyder```. After that I typed the command ```import numpy.linalg.lapack_lite``` in the ipython kernel in the Spyder.

### Reproduce the code example:

```python
import numpy.linalg.lapack_lite
```

### Error message:

```shell
Python 3.8.13 (default, Oct 19 2022, 17:54:22)
Type "copyright", "credits" or "license" for more information.

IPython 7.31.1 -- An enhanced Interactive Python.

import numpy.linalg.lapack_lite
Traceback (most recent call last):

  File "/Users/xushan/opt/anaconda3/envs/kaggle/lib/python3.8/site-packages/numpy/core/__init__.py", line 22, in <module>
    from . import multiarray

  File "/Users/xushan/opt/anaconda3/envs/kaggle/lib/python3.8/site-packages/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides

  File "/Users/xushan/opt/anaconda3/envs/kaggle/lib/python3.8/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (

ImportError: dlopen(/Users/xushan/opt/anaconda3/envs/kaggle/lib/python3.8/site-packages/numpy/core/_multiarray_umath.cpython-38-darwin.so, 0x0002): Library not loaded: @rpath/libopenblas.dylib
  Referenced from: <8D3CEF3B-7C19-3760-8313-D672ECC36913> /Users/xushan/opt/anaconda3/envs/kaggle/lib/python3.8/site-packages/numpy/core/_multiarray_umath.cpython-38-darwin.so
  Reason: tried: '/Users/xushan/opt/anaconda3/envs/kaggle/lib/libopenblas.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/xushan/opt/anaconda3/envs/kaggle/lib/libopenblas.dylib' (no such file), '/Users/xushan/opt/anaconda3/envs/kaggle/lib/libopenblas.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/xushan/opt/anaconda3/envs/kaggle/lib/libopenblas.dylib' (no such file), '/Users/xushan/opt/anaconda3/envs/kaggle/lib/python3.8/site-packages/numpy/core/../../../../libopenblas.dylib' (no such file), '/Users/xushan/opt/anaconda3/envs/kaggle/lib/libopenblas.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/xushan/opt/anaconda3/envs/kaggle/lib/libopenblas.dylib' (no such file), '/Users/xushan/opt/anaconda3/envs/kaggle/lib/libopenblas.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/xushan/opt/anaconda3/envs/kaggle/lib/libopenblas.dylib' (no such file), '/Users/xushan/opt/anaconda3/envs/kaggle/lib/python3.8/site-packages/numpy/core/../../../../libopenblas.dylib' (no such file), '/Users/xushan/opt/anaconda3/envs/kaggle/bin/../lib/libopenblas.dylib' (no such file), '/Users/xushan/opt/anaconda3/envs/kaggle/bin/../lib/libopenblas.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS@rpath/libopenblas.dylib' (no such file), '/Users/xushan/opt/anaconda3/envs/kaggle/lib/libopenblas.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/xushan/opt/anaconda3/envs/kaggle/lib/libopenblas.dylib' (no such file), '/Users/xushan/opt/anaconda3/envs/kaggle/lib/libopenblas.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/xushan/opt/anaconda3/envs/kaggle/lib/libopenblas.dylib' (no such file), '/Users/xushan/opt/anaconda3/envs/kaggle/lib/python3.8/site-packages/numpy/core/../../../../libopenblas.dylib' (no such file), '/Users/xushan/opt/anaconda3/envs/kaggle/lib/libopenblas.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/xushan/opt/anaconda3/envs/kaggle/lib/libopenblas.dylib' (no such file), '/Users/xushan/opt/anaconda3/envs/kaggle/lib/libopenblas.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/xushan/opt/anaconda3/envs/kaggle/lib/libopenblas.dylib' (no such file), '/Users/xushan/opt/anaconda3/envs/kaggle/lib/python3.8/site-packages/numpy/core/../../../../libopenblas.dylib' (no such file), '/Users/xushan/opt/anaconda3/envs/kaggle/bin/../lib/libopenblas.dylib' (no such file), '/Users/xushan/opt/anaconda3/envs/kaggle/bin/../lib/libopenblas.dylib' (no such file), '/usr/local/lib/libopenblas.dylib' (no such file), '/usr/lib/libopenblas.dylib' (no such file, not in dyld cache)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/var/folders/sk/q1bd_nkn1z345sbmdty96hpn6_w5dn/T/ipykernel_17438/2961065816.py", line 1, in <module>
    import numpy.linalg.lapack_lite

  File "/Users/xushan/opt/anaconda3/envs/kaggle/lib/python3.8/site-packages/numpy/__init__.py", line 150, in <module>
    from . import core

  File "/Users/xushan/opt/anaconda3/envs/kaggle/lib/python3.8/site-packages/numpy/core/__init__.py", line 48, in <module>
    raise ImportError(msg)

ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.8 from "/Users/xushan/opt/anaconda3/envs/kaggle/bin/python"
  * The NumPy version is: "1.21.5"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: dlopen(/Users/xushan/opt/anaconda3/envs/kaggle/lib/python3.8/site-packages/numpy/core/_multiarray_umath.cpython-38-darwin.so, 0x0002): Library not loaded: @rpath/libopenblas.dylib
  Referenced from: <8D3CEF3B-7C19-3760-8313-D672ECC36913> /Users/xushan/opt/anaconda3/envs/kaggle/lib/python3.8/site-packages/numpy/core/_multiarray_umath.cpython-38-darwin.so
  Reason: tried: '/Users/xushan/opt/anaconda3/envs/kaggle/lib/libopenblas.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/xushan/opt/anaconda3/envs/kaggle/lib/libopenblas.dylib' (no such file), '/Users/xushan/opt/anaconda3/envs/kaggle/lib/libopenblas.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/xushan/opt/anaconda3/envs/kaggle/lib/libopenblas.dylib' (no such file), '/Users/xushan/opt/anaconda3/envs/kaggle/lib/python3.8/site-packages/numpy/core/../../../../libopenblas.dylib' (no such file), '/Users/xushan/opt/anaconda3/envs/kaggle/lib/libopenblas.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/xushan/opt/anaconda3/envs/kaggle/lib/libopenblas.dylib' (no such file), '/Users/xushan/opt/anaconda3/envs/kaggle/lib/libopenblas.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/xushan/opt/anaconda3/envs/kaggle/lib/libopenblas.dylib' (no such file), '/Users/xushan/opt/anaconda3/envs/kaggle/lib/python3.8/site-packages/numpy/core/../../../../libopenblas.dylib' (no such file), '/Users/xushan/opt/anaconda3/envs/kaggle/bin/../lib/libopenblas.dylib' (no such file), '/Users/xushan/opt/anaconda3/envs/kaggle/bin/../lib/libopenblas.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS@rpath/libopenblas.dylib' (no such file), '/Users/xushan/opt/anaconda3/envs/kaggle/lib/libopenblas.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/xushan/opt/anaconda3/envs/kaggle/lib/libopenblas.dylib' (no such file), '/Users/xushan/opt/anaconda3/envs/kaggle/lib/libopenblas.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/xushan/opt/anaconda3/envs/kaggle/lib/libopenblas.dylib' (no such file), '/Users/xushan/opt/anaconda3/envs/kaggle/lib/python3.8/site-packages/numpy/core/../../../../libopenblas.dylib' (no such file), '/Users/xushan/opt/anaconda3/envs/kaggle/lib/libopenblas.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/xushan/opt/anaconda3/envs/kaggle/lib/libopenblas.dylib' (no such file), '/Users/xushan/opt/anaconda3/envs/kaggle/lib/libopenblas.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/xushan/opt/anaconda3/envs/kaggle/lib/libopenblas.dylib' (no such file), '/Users/xushan/opt/anaconda3/envs/kaggle/lib/python3.8/site-packages/numpy/core/../../../../libopenblas.dylib' (no such file), '/Users/xushan/opt/anaconda3/envs/kaggle/bin/../lib/libopenblas.dylib' (no such file), '/Users/xushan/opt/anaconda3/envs/kaggle/bin/../lib/libopenblas.dylib' (no such file), '/usr/local/lib/libopenblas.dylib' (no such file), '/usr/lib/libopenblas.dylib' (no such file, not in dyld cache)
```

### Runtime information:

```
import sys

sys.version
Out[5]: '3.8.13 (default, Oct 19 2022, 17:54:22) \n[Clang 12.0.0 ]'
```
For numpy, by ```!conda list```, it's 
```
numpy                     1.21.5           py38h9c3cb84_2    anaconda
numpy-base                1.21.5           py38he782bc1_2    anaconda
numpydoc                  1.2                pyhd3eb1b0_0    anaconda
```

**Comment by rkern** [comment]
These kinds of errors have more to do with the specifics of how `numpy` was packaged for `conda` than it does about `numpy` itself. It's possible that someone here may have seen this before, but you will have more luck reporting it to Anaconda.

**Comment by xushanthu-2014** [comment]
got the solution as ```conda install -c conda-forge openblas```.
