### ISSUE TITLE
bincount does not accept complex valued weights

### ISSUE THREAD

**Issue by nheinsdorf** [numpy/numpy#23313]
### Describe the issue:

Hi, 
I'm using bincount to sum up complex values. However, the method does not accept complex valued weights, however that would be a useful usecase for me. 

### Reproduce the code example:

```python
import numpy as np
w = 1j * array([0.3, 0.5, 0.2, 0.7, 1., -0.6]) # weights
x = array([0, 1, 1, 2, 2, 2])
np.bincount(x,  weights=w)
```

### Error message:

```shell
Traceback (most recent call last):
  File "/Users/user/PycharmProjects/project/venv/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3378, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-74-24012315fdf7>", line 5, in <module>
    np.bincount(x,  weights=w)
  File "<__array_function__ internals>", line 180, in bincount
TypeError: Cannot cast array data from dtype('complex128') to dtype('float64') according to the rule 'safe'
```

### Runtime information:

1.23.3
3.9.6 (default, Oct 18 2022, 12:41:40) 
[Clang 14.0.0 (clang-1400.0.29.202)]

### Context for the issue:

Happy to make a pull request myself (if I can do it), but I actually wasn't able to find the definition of the bincount method in the repo.

**Comment by mattip** [comment]
The code for bincount is written in C. The path to most numpy C functions goes like
- grep for `"bincount" in numpy/core/src/multiarray/*.c`, find https://github.com/numpy/numpy/blob/6a819d660afddaf3e9fba6de00f8f4d366813a5c/numpy/core/src/multiarray/multiarraymodule.c#L4594-L4595
- grep for `arr_bincount`, find https://github.com/numpy/numpy/blob/6a819d660afddaf3e9fba6de00f8f4d366813a5c/numpy/core/src/multiarray/compiled_base.c#L113
- poke around in the functions, and note this line which tries to convert weights to a NPY_DOUBLE https://github.com/numpy/numpy/blob/6a819d660afddaf3e9fba6de00f8f4d366813a5c/numpy/core/src/multiarray/compiled_base.c#L198

We could add some smarter logic there, which would also influence the return type (created as `ans`).

FWIW, using `np.add.at` does work, and on HEAD is about the same speed:
```python
>>> import numpy as np
>>> w = 1j * np.array([0.3, 0.5, 0.2, 0.7, 1., -0.6]) # weights
>>> x = np.array([0, 1, 1, 2, 2, 2])
>>> out = np.zeros_like(w)
>>> np.add.at(out, x, w)
>>> out
array([0.+0.3j, 0.+0.7j, 0.+1.1j, 0.+0.j , 0.+0.j , 0.+0.j ])
```

**Comment by Alex-JG3** [comment]
@nheinsdorf are you still planning on working on this issue? If not would you mind if I had a go at it?

**Comment by kgryte** [comment]
This issue appears to be a duplicate of https://github.com/numpy/numpy/issues/16903.
