### ISSUE TITLE
BUG: <OverflowError: Python int too large to convert to C long>

### ISSUE THREAD

**Issue by aT0ngMu** [numpy/numpy#23375]
### Describe the issue:

OverflowError: Python int too large to convert to C long

### Reproduce the code example:

```python
import atheris
import sys

with atheris.instrument_imports():
  from io import StringIO
  import numpy as np

def get_fuzz_types():
    # Define the rows
    dtype = np.dtype(
        [('f0', np.uint16), ('f1', np.float64), ('f2', 'S7'), ('f3', np.int8)]
    )

    # An expected match
    expected = np.array(
        [
            (1, 2.4, "a", -34),
            (2, 3.1, "b", 29),
            (3, 9.9, "g", 120),
        ],
        dtype=dtype
    )
    return dtype, expected

def TestOneInput(fuzz_data):
  dtype, expected = get_fuzz_types()
  fdp = atheris.FuzzedDataProvider(fuzz_data)
  new_data = StringIO(fdp.ConsumeString(sys.maxsize))
  try:
    np.loadtxt(new_data, dtype=dtype, delimiter=";", skiprows=True)
  # Catch all of the exceptions that are caught in 
  # https://github.com/numpy/numpy/blob/main/numpy/lib/tests/test_loadtxt.py
  except StopIteration:
    return
  except ValueError:
    return
  except IndexError:
    return
  except TypeError:
    return
  except RuntimeError:
    return

def main():
  atheris.instrument_all()
  atheris.Setup(sys.argv, TestOneInput, enable_python_coverage=True)
  atheris.Fuzz()

if __name__ == "__main__":
  main()
```

### Error message:

```shell
=== Uncaught Python exception: ===
OverflowError: Python int too large to convert to C long
Traceback (most recent call last):
  File "exp_drivers/manual_drivers/numpy/test_loader.py", line 45, in TestOneInput
    np.loadtxt(new_data, dtype=dtype, delimiter=";", skiprows=True)
  File "/home/server1/.local/lib/python3.8/site-packages/numpy/lib/npyio.py", line 1168, in loadtxt
    X = np.array(chunk, dtype)
OverflowError: Python int too large to convert to C long
```

### Runtime information:

1.22.3
3.8.10 (default, Nov 14 2022, 12:59:47) 
[GCC 9.4.0]

**Comment by seberg** [comment]
Note that newer NumPy versions have a different loadtxt which would be far more interesting to fuzz (it might actually find a relevant issue).

I don't see the issue here: What is the input anyway?  But the code calls `int(...)` and then will uses the Python conversion functions to `long` (in this case) which raise `OverflowError` for too large values.

Yes, NumPy itself might raise `ValueError` on occasions I guess, and on main, it always does so.  But `OverflowError` is very reasonable.

**Comment by seberg** [comment]
OK, going to close this.  I don't see the issue and loadtxt should even give a `ValueError` on current NumPy versions (not that it changes the fact that these code paths exists in other places).

If you/anyone else disagrees we can reopen.
