### ISSUE TITLE
np.spacing and np.nextafter on integers

### ISSUE THREAD

**Issue by Gabriel-Kissin** [numpy/numpy#23383]
`np.spacing` and `np.nextafter` are designed for use with floats. They tell you the gap between adjacent values, and what the next value is.  

So for example, 
`np.nextafter(np.float16(1), np.float16(2)), np.spacing(np.float16(1))`
returns 
`(1.001, 0.000977)`.

However on integers this doesn't perform as expected. [Of course there is no real use for these functions with integers, where the spacing is always 1 (except for at max and min of dtype) and next adjacent value is always 1 greater (except for at max of dtype). However, it should nonetheless give correct results, so it can easily be used in a situation where either a float or an int may be passed.]

**Setup the problem:**  
```
import numpy as np
import pandas as pd

dtypes_ints = [  
    int,
    np.int8,	    # Byte (-128 to 127)
    np.int16,	    # Integer (-32768 to 32767)
    np.int32,	    # Integer (-2147483648 to 2147483647)
    np.int64,	    # Integer (-9223372036854775808 to 9223372036854775807)
    np.uint8,	    # Unsigned integer (0 to 255)
    np.uint16,	    # Unsigned integer (0 to 65535)
    np.uint32,	    # Unsigned integer (0 to 4294967295)
    np.uint64,	    # Unsigned integer (0 to 18446744073709551615)
    ]
dtypes_floats = [
    float,
    np.float16,	    # Half precision float: sign bit, 5 bits exponent, 10 bits mantissa
    np.float32,	    # Single precision float: sign bit, 8 bits exponent, 23 bits mantissa
    np.float64,	    # Double precision float: sign bit, 11 bits exponent, 52 bits mantissa
    ]

```

**And the problem:**  
```
spacing_info = [(dtype, 
                    np.nextafter(dtype(1)  , dtype(2)), 
                    dtype(np.nextafter(dtype(1)  , dtype(2))),
                    np.spacing(dtype(1)), )
                for dtype in  dtypes_floats + dtypes_ints ]

pd.set_option("display.precision", 18)

pd.DataFrame(spacing_info, 
    columns=['dtype', 
             'next after 1 (np)', 
             'next after 1 as this dtype',
             'np.spacing', 
             ])
```

**Gives this:**  
![image](https://user-images.githubusercontent.com/118690308/224964163-3cef43f8-7dfc-48d8-a95a-a2af0181da55.png)

As can be seen, the `next after 1` column for the rows of integers seems to give the value of one of the types of floats, a different type for each type of integer. When the answer should be `2` for all of them.   

And the same problem is reflected in the `np.spacing` column.

**Comment by rgommers** [comment]
`nextafter` is explicitly documented as "Return the next floating-point value", so if integer input gets cast to a floating point dtype, that seems perfectly reasonable. Why would it have to be changed to return `2`? Seems more confusing than useful.

**Comment by Gabriel-Kissin** [comment]
> `nextafter` is explicitly documented as "Return the next floating-point value", so if integer input gets cast to a floating point dtype, that seems perfectly reasonable. Why would it have to be changed to return `2`? Seems more confusing than useful.

```
np.nextafter(np.float16(1), np.float16(2))
# 1.001
np.nextafter(np.float32(1), np.float32(2))
# 1.0000001
np.nextafter(np.float64(1), np.float64(2))
# 1.0000000000000002
```

This demonstrates that `np.nextafter` returns the next value *of the given dtype*. Hence it returns different values depending on whether it is fed an np.float16, np.float32, or np.float64. (The [documentation](https://numpy.org/doc/stable/reference/generated/numpy.nextafter.html) should really explain this). So when it is fed an integer, it should follow the same rule and return the next integer value. Instead, it converts it to a float64 and returns for that. 

The same argument applies to np.spacing:

```
np.spacing(np.float16(1))
# 0.000977
np.spacing(np.float32(1))
# 1.1920929e-07
np.spacing(np.float64(1))
# 2.220446049250313e-16
```

(Again, the [documentation](https://numpy.org/doc/stable/reference/generated/numpy.spacing.html) should really explain this).

I was using np.spacing to check that incrementing a value by a given amount would register a change: if the given amount is more than half of the spacing, then it will be bumped up, to the next value the dtype can take, otherwise it won't register. As I understand it, that is the point of these two functions - to know what will register for the given dtype. I was surprised when its behaviour wasn't uniform for integer values. Of course it would be trivial to test for integer values, and then the spacing and nextafter is obvious. But as these two functions do take account of the input dtype, I thought it should be so for integers as well.

**Comment by seberg** [comment]
I am not unsympathetic to thinking about doing something.  The question is whether they do make sense for integers at all, or not.

We have a few similar functions that make mostly/only sense for floating point input but the way NumPy used to do promotion in ufuncs meant that integers are just promoted up in a weird way.  There are two oddities about that:
* Getting a float result may be weird by itself
* The promotion rules are possibly not ideal.  Do we really want `uint8 -> float16`?  I suspect it would be better to do `integer -> default_float (float64)`.

Some of these there is a drive to just support it.  This one may be a bit too weird to do, but then the question is whether it wouldn't even be better to just raise an error (this can be annoying for some, e.g. `isnan` used to be in that boat but it is useful enough to be able to call it almost always, even when it doesn't do anything meaningful).

**Comment by Gabriel-Kissin** [comment]
Yes I get your point. Actually to get spacing for a specific dtype, apart from feeding that dtype in, it can also be specified explicitly:  

```
np.nextafter(1,2, dtype=np.float16)
# 1.001
np.nextafter(1,2, dtype=np.float32)
# 1.0000001
np.nextafter(1,2, dtype=np.float64)
# 1.0000000000000002
```
and 
```
np.spacing(1, dtype=np.float16)
# 0.000977
np.spacing(1, dtype=np.float32)
# 1.1920929e-07
np.spacing(1, dtype=np.float64)
# 2.220446049250313e-16
```
But when doing it this way, telling it to use an integer dtype **_does_** raise an error:  
```
np.nextafter(1,2, dtype=np.int32)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: No loop matching the specified signature and casting was found for ufunc nextafter
```
and 
```
np.spacing(1, dtype=np.uint64)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: No loop matching the specified signature and casting was found for ufunc spacing
```

However, when dtype is specified as integer by passing an integer, then I guess raising an error wouldn't be helpful. np.spacing has no way of knowing if it got an int because the user wrote `np.spacing(np.int32(1))` or just `np.spacing(1)`. In the latter case, it would presumably be best to promote to a float64 rather than pedantically taking the integer dtype seriously and raising an error. So I imagine that the current behaviour is probably best. 

Perhaps the thing to do then would be to update the documentation for the spacing and nextafter functions to clarify that:  
a) dtype for the spacing can be specified explicitly using the `dtype` argument;   
b) in the absence of that argument, by default it will be inferred from the dtype of the input `x` (spacing) / inputs `x1` `x2` (nextafter);   
c) that inference only applies to float dtypes, whereas integer dtypes are promoted to float64's and return spacing accordingly.   

As spacing and nextafter are intended for examining spacing for a particular dtype, the docs should probably explicitly clarify how dtype can be controlled?

**Comment by rgommers** [comment]
I'll note that the intended use is for actual arrays. If you write `np.spacing(1)` (or `1.0`), you should be using `np.finfo` instead.

Raising for integer input sounds fine, documenting the current behavior sounds okay too. Supporting integers not so much.
