### ISSUE TITLE
BUG: Fix for Numpy issue is broken.

### ISSUE THREAD

**Issue by matthewDDennis** [numpy/numpy#23499]
### Describe the issue:

In Windows 11 it appears that the FIXME using Popen should include a sell=true parameter
    import_cv2_proc = subprocess.Popen([interpreter, "-c", "import cv2"],
                                       stdout=subprocess.PIPE,
                                       stderr=subprocess.PIPE,
                                       shell=True)
otherwise it can't find the file.

### Reproduce the code example:

```python
Using paddleocr which attempts to import paddlepaddle and fails due to this issue.
```

### Error message:

```shell
11:21:34:ALPR_adapter.py: Traceback (most recent call last):
11:21:34:ALPR_adapter.py:   File "C:\Users\matth\source\repos\CodeProject.AI-Server-Private\src\modules\ALPR\ALPR_adapter.py", line 16, in 
11:21:34:ALPR_adapter.py:     from ALPR import init_detect_platenumber, detect_platenumber
11:21:34:ALPR_adapter.py:   File "C:\Users\matth\source\repos\CodeProject.AI-Server-Private\src\modules\ALPR\ALPR.py", line 20, in 
11:21:34:ALPR_adapter.py:     from paddleocr import PaddleOCR
11:21:34:ALPR_adapter.py:   File "C:\Users\matth\source\repos\CodeProject.AI-Server-Private\src\modules\ALPR\bin\windows\python37\venv\lib\site-packages\paddleocr\__init__.py", line 14, in 
11:21:34:ALPR_adapter.py:     from .paddleocr import *
11:21:34:ALPR_adapter.py:   File "C:\Users\matth\source\repos\CodeProject.AI-Server-Private\src\modules\ALPR\bin\windows\python37\venv\lib\site-packages\paddleocr\paddleocr.py", line 21, in 
11:21:34:ALPR_adapter.py:     import paddle
11:21:34:ALPR_adapter.py:   File "C:\Users\matth\source\repos\CodeProject.AI-Server-Private\src\modules\ALPR\bin\windows\python37\venv\lib\site-packages\paddle\__init__.py", line 76, in 
11:21:34:ALPR_adapter.py:     import paddle.dataset  # noqa: F401
11:21:34:ALPR_adapter.py:   File "C:\Users\matth\source\repos\CodeProject.AI-Server-Private\src\modules\ALPR\bin\windows\python37\venv\lib\site-packages\paddle\dataset\__init__.py", line 27, in 
11:21:34:ALPR_adapter.py:     import paddle.dataset.flowers  # noqa: F401
11:21:34:ALPR_adapter.py:   File "C:\Users\matth\source\repos\CodeProject.AI-Server-Private\src\modules\ALPR\bin\windows\python37\venv\lib\site-packages\paddle\dataset\flowers.py", line 39, in 
11:21:34:ALPR_adapter.py:     from paddle.dataset.image import load_image_bytes
11:21:34:ALPR_adapter.py:   File "C:\Users\matth\source\repos\CodeProject.AI-Server-Private\src\modules\ALPR\bin\windows\python37\venv\lib\site-packages\paddle\dataset\image.py", line 50, in 
11:21:34:ALPR_adapter.py:     stderr=subprocess.PIPE)
11:21:34:ALPR_adapter.py:   File "C:\Users\matth\source\repos\CodeProject.AI-Server-Private\src\runtimes\bin\windows\python37\lib\subprocess.py", line 800, in __init__
11:21:34:ALPR_adapter.py:     restore_signals, start_new_session)
11:21:34:ALPR_adapter.py:   File "C:\Users\matth\source\repos\CodeProject.AI-Server-Private\src\runtimes\bin\windows\python37\lib\subprocess.py", line 1207, in _execute_child
11:21:34:ALPR_adapter.py:     startupinfo)
11:21:34:ALPR_adapter.py: FileNotFoundError: [WinError 2] The system cannot find the file specified
```

### Runtime information:

---

**Comment by mattip** [comment]
Closing. If you meant to open this on the NumPy issue tracker please fill in all the fields in the template and explain how the error involves NumPy.
