### ISSUE TITLE
DOC: bincount documentation should mention native index type requirement

### ISSUE THREAD

**Issue by onitake** [numpy/numpy#23526]
### Issue with current documentation:

The [documentation for the bincount function](https://numpy.org/doc/stable/reference/generated/numpy.bincount.html) does not explain that the input must be of the native type used for array indexes.

This causes problems on 32-bit architectures, when a simple example like the following is executed with safety mode on:

```python
import numpy as np
data = np.random.default_rng().integers(low=0, high=100, dtype=np.int64, size=10)
np.bincount(data)
```

Result:

```
Traceback (most recent call last):
  File "bincount.py", line 6, in <module>
    np.bincount(data)
  File "<__array_function__ internals>", line 200, in bincount
TypeError: Cannot cast array data from dtype('int64') to dtype('int32') according to the rule 'safe'
```

With `dtype=int32` (fixed type) or `dtype.int_` or simply `int` (native int type), it works fine.

### Idea or request for content:

I'd suggest changing the example at https://github.com/numpy/numpy/blob/main/numpy/core/multiarray.py#L948-L955 from:

```
    The input array needs to be of integer dtype, otherwise a
    TypeError is raised:
    >>> np.bincount(np.arange(5, dtype=float))
    Traceback (most recent call last):
      ...
    TypeError: Cannot cast array data from dtype('float64') to dtype('int64')
    according to the rule 'safe'
```

to:

```
    The input array needs to be of the native integer index type, otherwise a
    TypeError is raised:
    >>> np.bincount(np.arange(5, dtype=float))
    Traceback (most recent call last):
      ...
    TypeError: Cannot cast array data from dtype('float64') to dtype('int64')
    according to the rule 'safe'

    The simplest way to do this is by always using the Python int type or dtype.int_:
    >>> np.bincount(np.arange(5, dtype=int))
```

**Comment by MuhammadNizamani** [comment]
Are you going to work on this issue ?

**Comment by onitake** [comment]
I can submit a PR, if you think it makes sense?

**Comment by MuhammadNizamani** [comment]
I guess so,  when you  hover over the function it will show this description so it means that it has a value.

**Comment by ikrommyd** [comment]
I believe this has since changed in https://github.com/numpy/numpy/pull/28355.
Closing, somebody correct me if I'm wrong.
