### ISSUE TITLE
ValueError: did not find a match in any of xarray's currently installed IO backends ['netcdf4', 'h5netcdf', 'scipy']. 

### ISSUE THREAD

**Issue by xeimyname1** [numpy/numpy#23583]
Hi,

I am using python 3.1 1.3, I am encountering this error when running the package

Traceback (most recent call last):
  File "/Users/24715447/anaconda3/envs/climate/lib/python3.11/site-packages/climate_indices/__main__.py", line 1671, in main
    input_type = _validate_args(arguments)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/24715447/anaconda3/envs/climate/lib/python3.11/site-packages/climate_indices/__main__.py", line 108, in _validate_args
    with xr.open_dataset(args.netcdf_precip) as dataset_precip:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/24715447/anaconda3/envs/climate/lib/python3.11/site-packages/xarray/backends/api.py", line 510, in open_dataset
    engine = plugins.guess_engine(filename_or_obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/24715447/anaconda3/envs/climate/lib/python3.11/site-packages/xarray/backends/plugins.py", line 177, in guess_engine
    raise ValueError(error_msg)
ValueError: did not find a match in any of xarray's currently installed IO backends ['netcdf4', 'h5netcdf', 'scipy']. Consider explicitly selecting one of the installed engines via the ``engine`` parameter, or installing additional IO dependencies, see:
https://docs.xarray.dev/en/stable/getting-started-guide/installing.html
https://docs.xarray.dev/en/stable/user-guide/io.html
Traceback (most recent call last):
  File "/Users/24715447/anaconda3/envs/climate/bin/process_climate_indices", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/24715447/anaconda3/envs/climate/lib/python3.11/site-packages/climate_indices/__main__.py", line 1671, in main
    input_type = _validate_args(arguments)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/24715447/anaconda3/envs/climate/lib/python3.11/site-packages/climate_indices/__main__.py", line 108, in _validate_args
    with xr.open_dataset(args.netcdf_precip) as dataset_precip:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/24715447/anaconda3/envs/climate/lib/python3.11/site-packages/xarray/backends/api.py", line 510, in open_dataset
    engine = plugins.guess_engine(filename_or_obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/24715447/anaconda3/envs/climate/lib/python3.11/site-packages/xarray/backends/plugins.py", line 177, in guess_engine
    raise ValueError(error_msg)
ValueError: did not find a match in any of xarray's currently installed IO backends ['netcdf4', 'h5netcdf', 'scipy']. Consider explicitly selecting one of the installed engines via the ``engine`` parameter, or installing additional IO dependencies, see:
https://docs.xarray.dev/en/stable/getting-started-guide/installing.html
https://docs.xarray.dev/en/stable/user-guide/io.html

I have tried installing xarray dependencies as given in the links. I can confirm that it was installed but the same error pops out after trying again. Thanks. Any advice on how to solve the issue?

**Comment by rossbar** [comment]
@xeimyname1 this issue seems to be related to xarray, not numpy. Consider opening an issue there instead - I will close this here as it's not directly related to numpy.
