### ISSUE TITLE
BUG: numpy.histogram--ValueError: supplied range of [nan, nan] is not finite

### ISSUE THREAD

**Issue by leslielee619** [numpy/numpy#23685]
### Describe the issue:

I am writing an image processing software using numpy and pyqt.

I don't get an error when I run the histogram function or put it in pyqt's init function, but I get an error when I put it in pyqt's slot function.

### Reproduce the code example:

```python
pdf, bin_edges = np.histogram(img.ravel(), bins=2**bit, range=[img.min(), img.max()])
```

### Error message:

```shell
Traceback (most recent call last):

    pdf, bin_edges = np.histogram(img.ravel(), bins=2**bit, range=[img.min(), img.max()])
  File "<__array_function__ internals>", line 6, in histogram
  File "xxx\lib\site-packages\numpy\lib\histograms.py", line 793, in histogram
    bin_edges, uniform_bins = _get_bin_edges(a, bins, range, weights)
  File "xxx\lib\site-packages\numpy\lib\histograms.py", line 426, in _get_bin_edges
    first_edge, last_edge = _get_outer_edges(a, range)
  File "xxx\lib\site-packages\numpy\lib\histograms.py", line 316, in _get_outer_edges
    "supplied range of [{}, {}] is not finite".format(first_edge, last_edge))
ValueError: supplied range of [nan, nan] is not finite
```

### Runtime information:

1.21.6
3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)]

**Comment by leslielee619** [comment]
I just tried running the code in cmd with python3.7(numpy1.21.6) and 3.9(numpy1.24.3) interpreters and it gave me the same error, so it's not pyqt's problem.

The problem now is that running in IDE doesn't give an error, running in CMD gives an error.

**Comment by leslielee619** [comment]
It's my fault. I used a relative path,

It will not be converted to an absolute path in ide, but will be automatically converted to an absolute path in cmd and pyqt, causing an error.
