### ISSUE TITLE
BUG: spurious failure in assert_allclose

### ISSUE THREAD

**Issue by h-vetinari** [numpy/numpy#23697]
### Describe the issue:

assert_allclose fires, even though the specified tolerances are not violated

### Reproduce the code example:

```python
import numpy as np
from numpy.testing import assert_allclose
x = np.array([1.110223e-16, 1.000000e+00, 1.000000e+00, 1.110223e-16])
y = np.array([0., 1., 1., 0.])
assert_allclose(x, y, rtol=1e-14)  # fails
assert_allclose(y, x, rtol=1e-14)  # also fails
```

### Error message:

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\[xxx]\.conda\envs\dev\lib\site-packages\numpy\testing\_private\utils.py", line 1592, in assert_allclose
    assert_array_compare(compare, actual, desired, err_msg=str(err_msg),
  File "C:\Users\[xxx]\.conda\envs\dev\lib\contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "C:\Users\[xxx]\.conda\envs\dev\lib\site-packages\numpy\testing\_private\utils.py", line 862, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Not equal to tolerance rtol=1e-14, atol=0

Mismatched elements: 2 / 4 (50%)
Max absolute difference: 1.110223e-16
Max relative difference: 0.
 x: array([1.110223e-16, 1.000000e+00, 1.000000e+00, 1.110223e-16])
 y: array([0., 1., 1., 0.])
```

### Runtime information:

```
>>> import sys, numpy; print(numpy.__version__); print(sys.version)
1.24.3
3.10.10 | packaged by conda-forge | (main, Mar 24 2023, 20:00:38) [MSC v.1934 64 bit (AMD64)]
>>> print(numpy.show_runtime())
[{'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}}]
```

**Comment by h-vetinari** [comment]
This shows up in scipy CI where [`TestTukey.test_basic`](https://github.com/scipy/scipy/blame/main/scipy/signal/tests/test_windows.py#L558-L565) used to pass and now fails.

**Comment by h-vetinari** [comment]
PS. I realize that doing something "relative" to 0 is tricky. But I guess one could take the minimum of whether a or b is the reference? While this looks fixable by adding `atol=`, I wanted to note the apparent regression.

**Comment by seberg** [comment]
Going to close this, I don't think it has anytihng to do with testing the behavior is correct and didn't change.  This is part of the `sin/cos` precision change problem in gh-23399 (for which opening an issue may make sense).
