### ISSUE TITLE
BUG: Various tests failing in connection with float128 on AMD Barcelona

### ISSUE THREAD

**Issue by 3rdcycle** [numpy/numpy#23754]
### Describe the issue:

I'm compiling numpy 1.24.2 with python 3.10.8 and gcc 12.2.0 on our old opteron based hpc. The compilation (through easybuild) seems to complete without errors. When running the tests (`numpy.test(verbose=2)`) I see multiple failures, most if not all of them in connection with dtype `g`/`float128` producing `nan` values. 

### Reproduce the code example:

```python
import numpy
numpy.test(verbose=2)
```

### Error message:

```shell
First error (will attach full test log in comment)

=================================== FAILURES ===================================
___________________________ TestCreation.test_zeros ____________________________

self = <numpy.core.tests.test_multiarray.TestCreation object at 0x7fa3a28b39d0>

    def test_zeros(self):
        types = np.typecodes['AllInteger'] + np.typecodes['AllFloat']
        for dt in types:
            d = np.zeros((13,), dtype=dt)
            assert_equal(np.count_nonzero(d), 0)
            # true for ieee floats
>           assert_equal(d.sum(), 0)
E           AssertionError: 
E           Items are not equal:
E            ACTUAL: nan
E            DESIRED: 0

d          = array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float128)
dt         = 'g'
self       = <numpy.core.tests.test_multiarray.TestCreation object at 0x7fa3a28b39d0>
types      = 'bBhHiIlLqQpPefdgFDG'

/tmp/eb-i46u0s0e/tmpzz3f8r08/lib/python3.10/site-packages/numpy/core/tests/test_multiarray.py:943: AssertionError
```

### Runtime information:

`1.24.2`

`3.10.8 (main, May  9 2023, 22:42:54) [GCC 12.2.0]`

```
[{'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['POPCNT'],
                      'not_found': ['SSSE3',
                                    'SSE41',
                                    'SSE42',
                                    'AVX',
                                    'F16C',
                                    'FMA3',
                                    'AVX2',
                                    'AVX512F',
                                    'AVX512CD',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}},
 {'architecture': 'BARCELONA',
  'filepath': '/sw/easybuild/amd/k10/2022b/software/OpenBLAS/0.3.21-GCC-12.2.0/lib/libopenblas_barcelonap-r0.3.21.so',
  'internal_api': 'openblas',
  'num_threads': 16,
  'prefix': 'libopenblas',
  'threading_layer': 'openmp',
  'user_api': 'blas',
  'version': '0.3.21'},
 {'filepath': '/sw/easybuild/amd/k10/2022b/software/GCCcore/12.2.0/lib64/libgomp.so.1.0.0',
  'internal_api': 'openmp',
  'num_threads': 16,
  'prefix': 'libgomp',
  'user_api': 'openmp',
  'version': None}]
None
```

**Comment by 3rdcycle** [comment]
Full test log: 
[numpy_test.log](https://github.com/numpy/numpy/files/11463839/numpy_test.log)

**Comment by mattip** [comment]
I wonder if the lack of SSSE3 is causing problems. @r-devulap any thoughts?

**Comment by seberg** [comment]
It would probably be good to see the build log.  You are compiling on the identical machine and not copying the binaries, I presume?  This seems likely a wrong long double setup, although a decent amount of things seem to succeed, but maybe that is just random.  In which case it may not be very troubling.  I see one more failure around `repr`.

Also, how did you install everything else?  Since this is an old HPC system, I wonder if you are using very old system libs (aside from that new compiler).

**Comment by 3rdcycle** [comment]
Thanks for looking into this. The system libs may be old but I'm not sure how relevant they are since I'm compiling against a toolchain that I bootstrapped on the same machine (again using Easybuild), including GCC 12.2, binutils, OpenBLAS, FlexiBLAS, FFTW, scaLAPACK, etc. 
I'm attaching the full easybuild log which should include all of the build output. I think the relevant part starts around line 2634. Let me know if there's anything else I can provide or try to get to the bottom of this. 
[easybuild-SciPy-bundle-2023.02-20230510.123253.rMdXK.log](https://github.com/numpy/numpy/files/11476890/easybuild-SciPy-bundle-2023.02-20230510.123253.rMdXK.log)

**Comment by r-devulap** [comment]
As @seberg says, there is something wrong with the long double setup. From your logs: 

```
x_f32      = array([37.45401], dtype=float32)
x_f128     = array([nan], dtype=float128)
```

where, `x_f128 = np.longdouble(x_f32)`. Can't yet immediately think of a reason why a simple conversion fails.

**Comment by 3rdcycle** [comment]
@seberg this is the result I get:

```
[1.]
[1.]
b'\x00\x00\x00\x00\x00\x00\x00\x80\xff?\x00\x00\x00\x00\x00\x00'
Try to probe 0.1 a bit (used to identify kind of long double):
0.1
b'\xcd\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xfb?\xde\x01\x00\x00\x00\x00'
0.1
b'\xcd\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xfb?\x9c\x80\x8b\x7f\x00\x00'
```

I tried to run the first failing test in isolation and to my surprise it passes:

```
================================================================================================ test session starts =================================================================================================
platform linux -- Python 3.10.8, pytest-7.2.0, pluggy-1.0.0
rootdir: /tmp/eb-i46u0s0e/tmpzz3f8r08/lib/python3.10/site-packages/numpy/core
plugins: hypothesis-6.68.2, xdist-3.1.0
collected 1 item                                                                                                                                                                                                     

test_multiarray.py .                                                                                                                                                                                           [100%]

================================================================================================= 1 passed in 0.20s ==================================================================================================
```

When I run the whole test suite that test fails consistently 🤨.

**Comment by seberg** [comment]
Hmmm, IIRC there was a test failure unrelated to longdouble somewhere also.  I think Matti's point about SSE3 availability may be related.  I thought maybe its using the garbage, but the garbage differs between the two last examples and both print fine and give the expected result (interesting that it writes 12 bytes, not 10, but I guess it makes sense).

I am suspecting Matti's initial thought is likely right.  Something to do with the older instruction set.  Would be nice to know which test makes things start to break (if there is one), but not sure how to best track that down (i.e. is it a something that uses SSE3 explicitly?)

**Comment by 3rdcycle** [comment]
According to what I find in `npy_cpu_dispatch_config.h` SSSE3 is a dispatchable optimization. My arch does support SSE3 (one less 'S'):

``` c
/*
 * AUTOGENERATED DON'T EDIT
 * Please make changes to the code generator (distutils/ccompiler_opt.py)
*/
#define NPY_WITH_CPU_BASELINE  "SSE SSE2 SSE3"
#define NPY_WITH_CPU_DISPATCH  "SSSE3 SSE41 POPCNT SSE42 AVX F16C FMA3 AVX2 AVX512F AVX512CD AVX512_SKX AVX512_CLX AVX512_CNL AVX512_ICL"
```

So in my understanding the SSSE3 code paths should never get used at all.


I ran some of the other failing tests individually to see if I could narrow it down some more. In `test_multiarray.py::TestCreation::test_zeros_like_like_zeros` (line 64534 in my logs) I found that the longdouble test fails **only if ran after the floating point (`f`) test**:

``` python
import numpy as np

# test zeros_like returns the same as zeros
for c in 'fg':
    print(f"Typecode: {c}")
    d = np.zeros((3,3), dtype=c)
    print(d)
    print(f"{np.zeros_like(d) == d}")
```
Result:
```
Typecode: f
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
Typecode: g
Traceback (most recent call last):
  File "/home/pikett/nptest.py", line 7, in <module>
    print(d)
  File "/tmp/eb-i46u0s0e/tmpzz3f8r08/lib/python3.10/site-packages/numpy/core/arrayprint.py", line 1588, in _array_str_implementation
    return array2string(a, max_line_width, precision, suppress_small, ' ', "")
  File "/tmp/eb-i46u0s0e/tmpzz3f8r08/lib/python3.10/site-packages/numpy/core/arrayprint.py", line 736, in array2string
    return _array2string(a, options, separator, prefix)
  File "/tmp/eb-i46u0s0e/tmpzz3f8r08/lib/python3.10/site-packages/numpy/core/arrayprint.py", line 513, in wrapper
    return f(self, *args, **kwargs)
  File "/tmp/eb-i46u0s0e/tmpzz3f8r08/lib/python3.10/site-packages/numpy/core/arrayprint.py", line 546, in _array2string
    lst = _formatArray(a, format_function, options['linewidth'],
  File "/tmp/eb-i46u0s0e/tmpzz3f8r08/lib/python3.10/site-packages/numpy/core/arrayprint.py", line 889, in _formatArray
    return recurser(index=(),
  File "/tmp/eb-i46u0s0e/tmpzz3f8r08/lib/python3.10/site-packages/numpy/core/arrayprint.py", line 876, in recurser
    nested = recurser(index + (-i,), next_hanging_indent,
  File "/tmp/eb-i46u0s0e/tmpzz3f8r08/lib/python3.10/site-packages/numpy/core/arrayprint.py", line 845, in recurser
    word = recurser(index + (-i,), next_hanging_indent, next_width)
  File "/tmp/eb-i46u0s0e/tmpzz3f8r08/lib/python3.10/site-packages/numpy/core/arrayprint.py", line 799, in recurser
    return format_function(a[index])
  File "/tmp/eb-i46u0s0e/tmpzz3f8r08/lib/python3.10/site-packages/numpy/core/arrayprint.py", line 1039, in __call__
    return dragon4_positional(x,
TypeError: 'NoneType' object cannot be interpreted as an integer
```


Whereas if I replace the `f` in the typecode sequence with something else: 
``` python
import numpy as np

# test zeros_like returns the same as zeros
for c in 'gg':
    print(f"Typecode: {c}")
    d = np.zeros((3,3), dtype=c)
    print(d)
    print(f"{np.zeros_like(d) == d}")
```

Result:
```
Typecode: g
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
Typecode: g
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
```

I've tried other type code sequences (`fdg`, `iefdg`, `iedg`), as long as `f` runs before `g`, `g` breaks. I have no idea what to make of this.

**Comment by charris** [comment]
Almost sounds like a compiler bug. Were you able to compile with other gcc/numpy versions?

**Comment by charris** [comment]
What compiler flags are being used?

**Comment by 3rdcycle** [comment]
@charris I haven't tried with other toolchains yet (need to build those first which will take a while). As for the compiler flags, here are the ones that were used e.g. for the multiarray code:
```
compile options: '-DNPY_INTERNAL_BUILD=1 -DHAVE_NPY_CONFIG_H=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -DHAVE_CBLAS -I/sw/easybuild/amd/k10/2022b/software/FlexiBLAS/3.2.1-GCC-12.2.0/include/flexiblas -Ibuild/src.linux-x86_64-3.10/numpy/core/src/multiarray -Ibuild/src.linux-x86_64-3.10/numpy/core/src/common -Ibuild/src.linux-x86_64-3.10/numpy/core/src/umath -Inumpy/core/include -Ibuild/src.linux-x86_64-3.10/numpy/core/include/numpy -Ibuild/src.linux-x86_64-3.10/numpy/distutils/include -Ibuild/src.linux-x86_64-3.10/numpy/core/src/npysort -Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -Inumpy/core/src/_simd -I/sw/easybuild/amd/k10/2022b/software/Python/3.10.8-GCCcore-12.2.0/include/python3.10 -Ibuild/src.linux-x86_64-3.10/numpy/core/src/common -Ibuild/src.linux-x86_64-3.10/numpy/core/src/npymath -c'
extra options: '-msse -msse2 -msse3'
``` 


From where I stand there are a few things I can try now:
- Build numpy with `setuptools < 60.0` as advised by the deprecation warning at the start of the build
- Build numpy with `--cpu-baseline=native` and  `--cpu-dispatch=none` (not sure if it's worth trying this - if it did hit illegal instructions I guess I would have seen a core dump)
- Build numpy with an older toolchain to see if it might be a compiler bug (any recommended versions?)

**Comment by 3rdcycle** [comment]
I went back and switched to an older compiler as suggested by @seberg. I first used GCC 10 to compile numpy 1.22.3 - this passes all tests. I then used the same compiler to compile 1.24.2 - this builds fine but the same tests fail as before with GCC 12. I'm going to take another in depth look next week to see if I can spot any other differences in my build setup but at this point I don't believe the compiler is really the issue.

**Comment by 3rdcycle** [comment]
I did some more tests with GCC 12 and numpy versions 1.22.3, 1.23.5, 1.24.0 and 1.24.2. Tests seem to pass for anything < 1.24, regardless of the compiler version. Unfortunately, I don't have time to dig into this any further for the moment. It may be helpful if anyone with an Barcelona CPU could confirm (or refute) that the following fails on 1.24 for them too: 

``` python
import numpy as np

# Replace 'f' with anything else and the 'g' test will pass
for c in 'fg':
    d = np.zeros((3,3), dtype=c)
    print(np.zeros_like(d) == d)
```

Result:
```
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[False  True  True]
 [ True  True  True]
 [ True  True  True]]
```

**Comment by seberg** [comment]
@seiko2plus may have some background to have an idea of what may be going on.  If this has to do with our SIMD code, it would have to be as part of the `==` implementation for float32 leading to issues in later code that is not (or only auto) vectorized, though.

Unless the old CPU model means we are bound to run into issues?  (in which case I wonder if there might be an easy way to hack some sanity checks on startup to inform users)

**Comment by seiko2plus** [comment]
I couldn't produce the test failure, I used the compiler `(GCC) 12.2.0` also disabled all default dispatched features, and only enabled `SSE SSE2 SSE3` similar to `BARCELONA` capabilities.

> Replace 'f' with anything else and the 'g' test will pass

This issue may be related to the x87 FPU operating environment (compiler bug).

@3rdcycle, Have you tried to build NumPy without SIMD features?
```
python setup.py build --cpu-baseline=none --cpu-dispatch=none install --user
```
and without enabling any optimizations:
```
python setup.py build --disable-optimization install --user 
```

**Comment by 3rdcycle** [comment]
Thanks for the suggestions @seiko2plus. It seems that these options don't make a difference in my case though. The only way I can make the tests pass seems to be by adding `-march=x86-64`, neither `-march=barcelona` or `-march=native` would work with any combinations of the options you suggested. 

Would this observation be compatible with the compiler bug you mentioned?
