### ISSUE TITLE
BUG: histogramdd raises an _ArrayMemoryError for arrays with shape (N, D > 9)

### ISSUE THREAD

**Issue by siebert-julien** [numpy/numpy#23767]
### Describe the issue:

- Histogramdd raises an _ArrayMemoryError for arrays with more than 9 dimensions (i.e., arrays with shape (N, D >= 9)).
- Histogramdd computational time increases exponentially with the number of dimensions.

### Reproduce the code example:

```python
import numpy as np
rng = np.random.default_rng(0)
a = rng.uniform(size=(100,9))
np.histogramdd(a,bins=10)
```

### Error message:

```shell
Traceback (most recent call last):
  File "C:\Users\siebert\PycharmProjects\badgers\venv\Lib\site-packages\IPython\core\interactiveshell.py", line 3505, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-55339c130b8c>", line 4, in <module>
    np.histogramdd(a,bins=10)
  File "<__array_function__ internals>", line 200, in histogramdd
  File "C:\Users\siebert\PycharmProjects\badgers\venv\Lib\site-packages\numpy\lib\histograms.py", line 1046, in histogramdd
    hist = np.bincount(xy, weights, minlength=nbin.prod())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<__array_function__ internals>", line 200, in bincount
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 461. GiB for an array with shape (61917364224,) and data type int64
```

### Runtime information:

`Python 3.11.2 (tags/v3.11.2:878ead1, Feb  7 2023, 16:38:35) [MSC v.1934 64 bit (AMD64)] on win32`

Output from `import sys, numpy; print(numpy.__version__); print(sys.version)`
```
1.24.2
3.11.2 (tags/v3.11.2:878ead1, Feb  7 2023, 16:38:35) [MSC v.1934 64 bit (AMD64)]
```

Output from `print(numpy.show_runtime())`
```
[{'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}},
 {'architecture': 'Haswell',
  'filepath': 'C:\\Users\\siebert\\PycharmProjects\\badgers\\venv\\Lib\\site-packages\\numpy\\.libs\\libopenblas64__v0.3.21-gcc_10_3_0.dll',
  'internal_api': 'openblas',
  'num_threads': 8,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.21'}]
None
```

### Context for the issue:

# Context

I am working on an algorithm to sample points in low density regions.
I am using histogramdd to find out low density regions.

# Other observations

I also noticed an (exponential?) increase in the time it takes to run histogramdd when I increase the number of dimensions (see below). It might be related to https://github.com/numpy/numpy/issues/17676

Note that I also tried with more instances (100, 1000, 10000), here the increase in time is not exponential.

## Tests with an increasing number of dimensions (time increases exponentially)
```
%%timeit
a = rng.uniform(size=(100,5))
np.histogramdd(a,bins=10)
1.65 ms ± 208 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
```

```
%%timeit
a = rng.uniform(size=(100,6))
np.histogramdd(a,bins=10)
19 ms ± 4.78 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

```
%%timeit
a = rng.uniform(size=(100,7))
np.histogramdd(a,bins=10)
158 ms ± 3.48 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

```
%%timeit
a = rng.uniform(size=(100,8))
np.histogramdd(a,bins=10)
2.81 s ± 600 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

## Test with an increasing number of instances

```
%%timeit
a = rng.uniform(size=(100,5))
np.histogramdd(a,bins=10)
1.65 ms ± 208 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
```

```
%%timeit
a = rng.uniform(size=(1000,5))
np.histogramdd(a,bins=10)
3.16 ms ± 1.07 ms per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
```

```
%%timeit
a = rng.uniform(size=(10000,5))
np.histogramdd(a,bins=10)
2.95 ms ± 81.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

**Comment by seberg** [comment]
Histogram returns a dense array, so you are out of luck.  High dimensional spaces require different tooling (maybe sparse).  Of course this is exponential, dimensions are exponential and the volume is also.
