### ISSUE TITLE
BUG: <Please write a comprehensive title after the 'BUG: ' prefix>

### ISSUE THREAD

**Issue by nairadethya** [numpy/numpy#23800]
### Describe the issue:

I was trying to stack two numpy arrays vertically by passing both of them into the vstack function but it always gave the error that the function only takes in one positional arguement but in the docs the example was demonstrated by passing two numpy arrays, so i wanted to know whether this is a bug or a mistake in the docs. 

### Reproduce the code example:

```python
>>import numpy as np
>> a = np.array([1, 2, 3])
>>b = np.array([4, 5, 6])
>>np.vstack(a, b)
```

### Error message:

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<__array_function__ internals>", line 179, in vstack
TypeError: _vhstack_dispatcher() takes 1 positional argument but 2 were given
>>>
```

### Runtime information:

![Screenshot from 2023-05-24 16-14-11](https://github.com/numpy/numpy/assets/88815815/6dd2594a-bf3f-4cb8-a082-a0cdcddd6514)

### Context for the issue:

I was working on an image classification model as part of my internship and i wanted to actually create an input for the neural network from the images collected form my lab but this was an error that i encountered so any help would be really appreciated

**Comment by DhavalParmar61** [comment]
@nairadethya please try np.vstack((a,b)).

**Comment by nairadethya** [comment]
> @nairadethya please try np.vstack((a,b)).

Thank you it worked 🤝

**Comment by mattip** [comment]
Glad you found an answer. Closing.
