### ISSUE TITLE
ENH: add support for arrays of dtype np.objet_ (of bytes) to np.char.decode, or clarify doc

### ISSUE THREAD

**Issue by chrish42** [numpy/numpy#23816]
### Proposed new feature or change:

Currently, when `np.char.decode()` is called on a `np.array([b'foo'], dtype=np.object_)`, the exception message generated is kinda confusing. It is also not 100% clear from the doc whether this should work or not. 

I'd propose either adding support for decoding np.arrays of byte strings, or clarifying the doc and exception message to say this is not supported. Happy to supply a pull request once a decision is made on which one it should be.

**Comment by mattip** [comment]
```
>>> np.char.decode(np.array([4, 'abc'], dtype=object))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<__array_function__ internals>", line 180, in decode
  File "/home/matti/miniconda3/envs/python3.9/lib/python3.9/site-packages/numpy/core/defchararray.py", line 556, in decode
    _vec_string(a, object_, 'decode', _clean_args(encoding, errors)))
TypeError: string operation on non-string array
```

I would vote for extending the error text to mention the dtype of the array, as in: `TypeError: string operation on a non-string array with dtype 'object'`.

**Comment by ayushanand308** [comment]
As @mattip suggested, I would like to fix the error text.
