### ISSUE TITLE
DOC: "Setting Up and Using your development environment" part is confusing

### ISSUE THREAD

**Issue by liang3zy22** [numpy/numpy#23885]
### Issue with current documentation:

The document "Setting Up and Using your development environment" is confusing.
First, there are several links, like "Building from source". This link will cause confusing since current page and "Building from source" are both about compiling codes.
Second, the link "Git for development" is actually "Git Basics" page. 
Third, "Using virtual environments" part is after the compiling part.

### Idea or request for content:

For the questions above, my suggestion:
First, add part to install compilers, remove the link.
Second, merge the link name and page name into one name.
Third, move "Using virtual environments" part before compiling.

By the way, when I compiling dumpy codes, I got following error:
```
Traceback (most recent call last):
  File "/Users/yanliangz/software/numpydirectory/numpy/runtests.py", line 715, in <module>
    main(argv=sys.argv[1:])
  File "/Users/yanliangz/software/numpydirectory/numpy/runtests.py", line 391, in main
    result = test(args.mode,
  File "/Users/yanliangz/software/numpydirectory/numpy/build/testenv/lib/python3.9/site-packages/numpy/_pytesttester.py", line 126, in __call__
    import pytest
  File "/Users/yanliangz/mambaforge/envs/numpy-dev/lib/python3.9/site-packages/pytest/__init__.py", line 5, in <module>
    from _pytest.assertion import register_assert_rewrite
  File "/Users/yanliangz/mambaforge/envs/numpy-dev/lib/python3.9/site-packages/_pytest/assertion/__init__.py", line 9, in <module>
    from _pytest.assertion import rewrite
  File "/Users/yanliangz/mambaforge/envs/numpy-dev/lib/python3.9/site-packages/_pytest/assertion/rewrite.py", line 30, in <module>
    import py
ModuleNotFoundError: No module named 'py'
```

Please help me fix this issue.

**Comment by melissawm** [comment]
Hi @liang3zy22, that looks like a pytest error - you should probably try reinstalling it or checking that the installation is correct.

For the documentation - can you check the development version of that page and see if it's any better? https://numpy.org/devdocs/dev/development_environment.html

We could move the virtual environment sections to before the compiling instructions, do you want to submit a PR for that?

As for the other points, I think they are fixed in the dev version of the documentation. Cheers and thanks for the report!

**Comment by liang3zy22** [comment]
Thanks for comment, @melissawm . 
I have tried the link you posted. It still has issues I listed. I will submit a PR to move the virtual environment sections.
