### ISSUE TITLE
BUG:  from numpy.core._multiarray_umath import (

### ISSUE THREAD

**Issue by qianxin-kxy** [numpy/numpy#23930]
### Describe the issue:

In the process of using antismash, I encountered this problem, which made it impossible to complete the follow-up analysis, and I searched for previous issues. Although there are some suggestions, I cannot directly use sudo, etc. because I do not have root privileges.

### Reproduce the code example:

```python
$ antismash --cpus 80 --cb-general --cb-knownclusters --cb-subclusters --asf --pfam2go --smcog-trees bl_2012_ST381_4751_1.gbk --output-dir 4751_1
```

### Error message:

```shell
(antismash) [kxy@zju antismash]$ antismash --cpus 80 --cb-general --cb-knownclusters --cb-subclusters --asf --pfam2go --smcog-trees bl_2012_ST381_4751_1.gbk --output-dir 4751_1
OpenBLAS blas_thread_init: pthread_create failed for thread 126 of 128: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 4124035 max
OpenBLAS blas_thread_init: pthread_create failed for thread 127 of 128: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 4124035 max
Traceback (most recent call last):
  File "/data/users/kxy/miniconda3/envs/antismash/bin/antismash", line 7, in <module>
    from antismash.__main__ import entrypoint
  File "/data/users/kxy/miniconda3/envs/antismash/lib/python3.7/site-packages/antismash/__init__.py", line 12, in <module>
    from antismash.main import run_antismash, get_detection_modules, \
  File "/data/users/kxy/miniconda3/envs/antismash/lib/python3.7/site-packages/antismash/main.py", line 25, in <module>
    from Bio import SeqIO
  File "/data/users/kxy/miniconda3/envs/antismash/lib/python3.7/site-packages/Bio/SeqIO/__init__.py", line 382, in <module>
    from Bio.Align import MultipleSeqAlignment
  File "/data/users/kxy/miniconda3/envs/antismash/lib/python3.7/site-packages/Bio/Align/__init__.py", line 21, in <module>
    from Bio.Align import substitution_matrices
  File "/data/users/kxy/miniconda3/envs/antismash/lib/python3.7/site-packages/Bio/Align/substitution_matrices/__init__.py", line 12, in <module>
    import numpy
  File "/data/users/kxy/miniconda3/envs/antismash/lib/python3.7/site-packages/numpy/__init__.py", line 150, in <module>
    from . import core
  File "/data/users/kxy/miniconda3/envs/antismash/lib/python3.7/site-packages/numpy/core/__init__.py", line 22, in <module>
    from . import multiarray
  File "/data/users/kxy/miniconda3/envs/antismash/lib/python3.7/site-packages/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/data/users/kxy/miniconda3/envs/antismash/lib/python3.7/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
KeyboardInterrupt
Segmentation fault (core dumped)
```

### Runtime information:

  * The Python version is: Python3.7 from "/data/users/kxy/miniconda3/envs/antismash/bin/python"
  * The NumPy version is: "1.21.6"

### Context for the issue:

Because I have performed secondary metabolite analysis on nearly 1,000 strains of bacteria, if this problem is not resolved, I will not be able to perform follow-up analysis and obtain a Ph.D.

**Comment by mattip** [comment]
OpenBLAS tries to open a thread per CPU and allocates a buffer for each thread. You are seeing 128 threads, perhaps the buffer allocations fail. OpenBLAS recognized this shortcoming and in later versions is more conservative about memory allocation at startup. You can figure out what version of OpenBLAS you are using with [`threadpoolctl'](https://pypi.org/project/threadpoolctl/). I assume since your path has `miniconda3` in it that you are using a conda environment, in which case you might be able to update your OpenBLAS version. In any case, you can limit OpenBLAS to a smaller number of threads by setting an environment variable before you start:
```
export OPENBLAS_NUM_THREADS=16
antismash --cpus 80 --cb-general ...
```

**Comment by qianxin-kxy** [comment]
### Thank you for responding!
**1.I tried this "export OPENBLAS_NUM_THREADS=16",but the issues exists**

$ antismash --cpus 80 --genefinding-tool prodigal --cb-general --cb-knownclusters --cb-subclusters --asf --pfam2go --smcog-trees bl_2012_ST381_4751_1.gbk --output-dir 4751_2
WARNING  13/06 18:48:08   Fasta header too long: renamed "NODE_2_length_354722_cov_" to "c00001_NODE_2_.."
WARNING………………
WARNING  13/06 18:48:08   Fasta header too long: renamed "NODE_53_length_1013_cov_" to "c00052_NODE_53.."
OpenBLAS blas_thread_init: pthread_create failed for thread 7 of 16: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 4124035 max
OpenBLAS blas_thread_init: pthread_create failed for thread 8 of 16: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 4124035 max
OpenBLAS blas_thread_init: pthread_create failed for thread 9 of 16: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 4124035 max
OpenBLAS blas_thread_init: pthread_create failed for thread 10 of 16: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 4124035 max
OpenBLAS blas_thread_init: pthread_create failed for thread 11 of 16: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 4124035 max
OpenBLAS blas_thread_init: pthread_create failed for thread 12 of 16: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 4124035 max
OpenBLAS blas_thread_init: pthread_create failed for thread 13 of 16: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 4124035 max
OpenBLAS blas_thread_init: pthread_create failed for thread 14 of 16: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 4124035 max
OpenBLAS blas_thread_init: pthread_create failed for thread 15 of 16: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 4124035 max
Process ForkPoolWorker-726:
Traceback (most recent call last):
  File "/data/users/kxy/miniconda3/envs/antismash/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/data/users/kxy/miniconda3/envs/antismash/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/data/users/kxy/miniconda3/envs/antismash/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/data/users/kxy/miniconda3/envs/antismash/lib/python3.7/multiprocessing/pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/data/users/kxy/miniconda3/envs/antismash/lib/python3.7/site-packages/antismash/modules/smcog_trees/trees.py", line 68, in smcog_tree_analysis
    draw_tree(input_number, output_dir, gene_id)
  File "/data/users/kxy/miniconda3/envs/antismash/lib/python3.7/site-packages/antismash/modules/smcog_trees/trees.py", line 165, in draw_tree
    fig.savefig(os.path.join(output_dir, tag + '.png'), bbox_inches='tight')
  File "/data/users/kxy/miniconda3/envs/antismash/lib/python3.7/site-packages/matplotlib/figure.py", line 3058, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/data/users/kxy/miniconda3/envs/antismash/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 2300, in print_figure
    renderer, bbox_extra_artists=bbox_extra_artists)
  File "/data/users/kxy/miniconda3/envs/antismash/lib/python3.7/site-packages/matplotlib/figure.py", line 1714, in get_tightbbox
    _bbox = TransformedBbox(_bbox, self.dpi_scale_trans.inverted())
  File "/data/users/kxy/miniconda3/envs/antismash/lib/python3.7/site-packages/matplotlib/transforms.py", line 1890, in inverted
    self._inverted = Affine2D(inv(mtx), shorthand_name=shorthand_name)
  File "<__array_function__ internals>", line 6, in inv
  File "/data/users/kxy/miniconda3/envs/antismash/lib/python3.7/site-packages/numpy/linalg/linalg.py", line 545, in inv
    ainv = _umath_linalg.inv(a, signature=signature, extobj=extobj)
KeyboardInterrupt

**2. Even I tried this "export OPENBLAS_NUM_THREADS=1", new issues present**

$ antismash --cpus 80 --cb-general --cb-knownclusters --cb-subclusters --asf --pfam2go --smcog-trees bl_2012_ST381_4751_1.gbk --output-dir 4751_3
Traceback (most recent call last):
  File "/data/users/kxy/miniconda3/envs/antismash/bin/antismash", line 10, in <module>
    sys.exit(entrypoint())
  File "/data/users/kxy/miniconda3/envs/antismash/lib/python3.7/site-packages/antismash/__main__.py", line 125, in entrypoint
    sys.exit(main(sys.argv[1:]))
  File "/data/users/kxy/miniconda3/envs/antismash/lib/python3.7/site-packages/antismash/__main__.py", line 113, in main
    antismash.run_antismash(sequence, options)
  File "/data/users/kxy/miniconda3/envs/antismash/lib/python3.7/site-packages/antismash/main.py", line 674, in run_antismash
    result = _run_antismash(sequence_file, options)
  File "/data/users/kxy/miniconda3/envs/antismash/lib/python3.7/site-packages/antismash/main.py", line 681, in _run_antismash
    _log_found_executables(options)
  File "/data/users/kxy/miniconda3/envs/antismash/lib/python3.7/site-packages/antismash/main.py", line 776, in _log_found_executables
    version = " ({})".format(version_getter())  # pylint: disable=not-callable
  File "/data/users/kxy/miniconda3/envs/antismash/lib/python3.7/site-packages/antismash/common/subprocessing/java.py", line 25, in run_java_version
    raise RuntimeError(msg % java)
RuntimeError: unexpected output from java: /data/users/kxy/miniconda3/envs/antismash/bin/java, check path

**3. I got the version of threadpoolctl by the following codes, which is the newest version shown as you list the websites, so should I downgrade the software to a specific version?**
$ pip show threadpoolctl
Name: threadpoolctl
Version: 3.1.0
Summary: threadpoolctl
Home-page: https://github.com/joblib/threadpoolctl
Author: Thomas Moreau
Author-email: thomas.moreau.2010@gmail.com
License: BSD-3-Clause
Location: /data/users/kongxiaoyang/miniconda3/envs/antismash/lib/python3.7/site-packages
Requires: 
Required-by: scikit-learn

**Comment by mattip** [comment]
Ignore threadpoolctl, it is a utility that helps you manage your threads. You don't need it since `OPENBLAS_NUM_THREADS` is doing its work. 

Apparently, you need to use `export OPENBLAS_NUM_THREADS=1`, since that gets past the problem of importing NumPy.

Using that, you get to this error, which has to do with java not NumPy.
```
RuntimeError: unexpected output from java: /data/users/kxy/miniconda3/envs/antismash/bin/java, check path
```

Is there someone around you who can help you work through this new error? As this no longer involves NumPy, we cannot really help further.
