### ISSUE TITLE
Never name your python file, numpy.py or scipy.py

### ISSUE THREAD

**Issue by ELO2023** [numpy/numpy#24136]
### Describe the issue:

I made sure Numpy was installed, I have been getting this error repeatedly: 

PS C:\Users\emili\Downloads\Python_Scripts> python numpy.py
Traceback (most recent call last):
  File "C:\Users\emili\Downloads\Python_Scripts\numpy.py", line 1, in <module>
    import numpy.random as random
  File "C:\Users\emili\Downloads\Python_Scripts\numpy.py", line 1, in <module>
    import numpy.random as random
ModuleNotFoundError: No module named 'numpy.random'; 'numpy' is not a package
PS C:\Users\emili\Downloads\Python_Scripts>

### Reproduce the code example:

```python
import numpy.random as random

def generate_random_numbers():
    """This function generates a random array of numbers."""
    return random.rand(10)

def print_random_numbers():
    """This function prints the random array of numbers."""
    random_numbers = generate_random_numbers()
    print(random_numbers)

if __name__ == '__main__':
    print_random_numbers()
```

### Error message:

```shell
PS C:\Users\emili\Downloads\Python_Scripts> python numpy.py
Traceback (most recent call last):
  File "C:\Users\emili\Downloads\Python_Scripts\numpy.py", line 1, in <module>
    import numpy.random as random
  File "C:\Users\emili\Downloads\Python_Scripts\numpy.py", line 1, in <module>
    import numpy.random as random
ModuleNotFoundError: No module named 'numpy.random'; 'numpy' is not a package
PS C:\Users\emili\Downloads\Python_Scripts>
```

### Runtime information:

 File "C:\Users\emili\Downloads\Python_Scripts\numpy.py", line 1, in <module>
    import sys, numpy; print(numpy.__version__); print(sys.version)
                             ^^^^^^^^^^^^^^^^^
AttributeError: partially initialized module 'numpy' has no attribute '__version__' (most likely due to a circular import)
PS C:\Users\emili\Downloads\Python_Scripts>

### Context for the issue:

I would really like to know what is causing this Numpy bug, I ensured my Python library paths were set in the environmental variable settings, yet numpy just won't work on PowerShell 7. Every path I can think of is set, yet Numpy still won't work, when called in my code.

**Comment by ELO2023** [comment]
Okay, it's not Numpy, maybe it's something else: PS C:\Users\emili\Downloads\Python_Scripts> python scipy.py
Traceback (most recent call last):
  File "C:\Users\emili\Downloads\Python_Scripts\scipy.py", line 1, in <module>
    import scipy.stats as stats
  File "C:\Users\emili\Downloads\Python_Scripts\scipy.py", line 1, in <module>
    import scipy.stats as stats
ModuleNotFoundError: No module named 'scipy.stats'; 'scipy' is not a package;

Numpy and Scipy are definitely installed, I can't think of a solution, can someone help me.

**Comment by ELO2023** [comment]
To whoever reads this, never name your python file, numpy.py or scipy.py, after changing the name my code finally started running.
