### ISSUE TITLE
BUG: libquadmath-96973f99.so.0.0.0: rebuild shared object with SHSTK support enabled

### ISSUE THREAD

**Issue by jurobystricky** [numpy/numpy#24221]
### Describe the issue:

We tested some Python apps  in anticipation of CET support being merged into upstream Linux kernel in the near future.
https://www.phoronix.com/news/Linux-6.4-Shadow-Stack-Coming
While testing CentOS Stream 9 with a custom kernel with shadow stack enabled and Glibc with CET support, we were not able to import "numpy". 

### Reproduce the code example:

```python
$ python3
Python 3.9.17 (main, Jun 26 2023, 00:00:00) 
[GCC 11.4.1 20230605 (Red Hat 11.4.1-2)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
Traceback (most recent call last):
...
```

### Error message:

```shell
Traceback (most recent call last):
  File "/home/bkc/.local/lib/python3.9/site-packages/numpy/core/__init__.py", line 23, in <module>
    from . import multiarray
  File "/home/bkc/.local/lib/python3.9/site-packages/numpy/core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/home/bkc/.local/lib/python3.9/site-packages/numpy/core/overrides.py", line 8, in <module>
    from numpy.core._multiarray_umath import (
ImportError: /home/bkc/.local/lib/python3.9/site-packages/numpy/core/../../numpy.libs/libquadmath-96973f99.so.0.0.0: rebuild shared object with SHSTK support enabled

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bkc/.local/lib/python3.9/site-packages/numpy/__init__.py", line 139, in <module>
    from . import core
  File "/home/bkc/.local/lib/python3.9/site-packages/numpy/core/__init__.py", line 49, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.9 from "/usr/bin/python3"
  * The NumPy version is: "1.25.1"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: /home/bkc/.local/lib/python3.9/site-packages/numpy/core/../../numpy.libs/libquadmath-96973f99.so.0.0.0: rebuild shared object with SHSTK support enabled
```

### Runtime information:

>>> import sys
>>> print(sys.version)
3.9.17 (main, Jun 26 2023, 00:00:00) 
[GCC 11.4.1 20230605 (Red Hat 11.4.1-2)]

### Context for the issue:

There is a workaround for this, setting the environmental variable:
**GLIBC_TUNABLES=glibc.cpu.x86_shstk=permissive**
will disable CET functionality and allows loading numpy shared libraries.
However, the prudent solution is to actually rebuild all numpy shared libraries with SHSTK support enabled.
Thanks.

**Comment by mattip** [comment]
> rebuild all numpy shared libraries with SHSTK 

The library in question comes from the CentOS7 distribution and is already installed in the docker image we use to build the NumPy wheels. It is [installed with gfortran](https://github.com/pypa/manylinux/blob/129380e3700b0c52f261ebba0250568e6dedec7a/docker/build_scripts/install-runtime-packages.sh#L72). Is there a RPM containing the proper gofrtran built to use SHSTK?

Is there a compilation flag needed for SHSTK?

**Comment by jurobystricky** [comment]
The gfortran command should support all the options supported by the gcc command. 
The relevant flags are: **-fcf-protection=[full|branch|return|none|check]**
https://gcc.gnu.org/onlinedocs/gcc/Instrumentation-Options.html

You can check if any is binary compiled with CET flags:

**$ readelf -n <path/to/binary> | grep SHSTK**

**Comment by mattip** [comment]
We are not compiling with gfortran, rather including in the NumPy wheel a system library from CentOS7 built by the OS distributor in an RPM. Is CentOS7/Redhat7 updating all rpms to support this? Will such libraries run unmodified on kernels without CET/ShadowStack support?

Reading the link you pointed to, I am not sure which of those alternatives enables SHSTK. I see a reference to shadow stack in the [`-fsanitize_shadow-call-stack`](https://gcc.gnu.org/onlinedocs/gcc/Instrumentation-Options.html#index-fsanitize_003dshadow-call-stack) option, but that is only for aarch64.

**Comment by jurobystricky** [comment]
The compiler flag to support CET is  **-fcf-protection**. 
https://gcc.gnu.org/onlinedocs/gcc/Instrumentation-Options.html#index-fcf-protection
The binaries compiled with the CET support run without problems with kernels with or without  CET. In fact all major Linux distros have been building/distributing their packages with CET support already for a few years. CET has been around for a few years,  it just took a long time to get the CET support into Linux kernel.

You can check if any binary is compiled with CET by yourself, for example:
<code>
$ readelf -n /usr/bin/bash | grep SHSTK
      Properties: x86 feature: IBT, SHSTK
</code>
If the numpy binaries are actually built by distro providers, I can file this issue with them.

**Comment by mattip** [comment]
Thanks for the clarifications. The libquadmath lib is copied out of the Docker image based on centos:7 used in building the `manylinux2014` wheel. The gcc tool set comes from [this line ](https://github.com/pypa/manylinux/blob/129380e3700b0c52f261ebba0250568e6dedec7a/docker/build_scripts/install-runtime-packages.sh#L99) which installs `gcc-toolset-12-gcc-gfortran`. So in order to solve this issue, we need a new build of [the RPM](https://kojihub.stream.centos.org/koji/rpminfo?rpmID=732207), which will probably not happen. That manylinux2014 tag (also known as manylinux_2_17) and centos:7 will [go end-of-life](https://github.com/mayeut/pep600_compliance) on June 30 2024. We could start building `manylinux_2_28` wheels in addition to the `manylinux2014` ones. These are based on the `almalinux:8`, and when I run the `quay.io/pypa/manylinux_2_28_x86_64` docker image I see that it supports `SHSTK`:
```
# readelf -n /usr/lib64/libquadmath.so.0.0.0 | grep SHSTK
      Properties: x86 feature: IBT, SHSTK
```

**Comment by rgommers** [comment]
Building `manylinux_2_28` wheels seems like a good idea to me. It will get us some other benefits too probably, because of fewer bugs in the newer glibc.

Do we know how urgent this is? When would we expect to see the first distro shipping this in a way that would break the latest numpy wheels?

**Comment by jurobystricky** [comment]
The user mode shadow stack support is already upstreamed in Linux kernel 6.6-rc2,

**Comment by mattip** [comment]
Apparently Fedora Rawhide [uses this rc2 kernel in its release](https://packages.fedoraproject.org/pkgs/kernel/kernel/).

**Comment by rgommers** [comment]
`numpy` 2.3.0 is the first version where we moved from `manylinux2014` to `manylinux_2_28`, so that will hopefully have solved this issue. It'd be nice if someone could confirm that.

**Comment by mattip** [comment]
Closing. Since the scipyopenblas 0.3.28 wheels, we [no longer bundle `quadlibmath`](https://github.com/MacPython/openblas-libs/pull/85#issuecomment-2282654077).

**Comment by rgommers** [comment]
> Since the scipyopenblas 0.3.28 wheels, we [no longer bundle `quadlibmath`](https://github.com/MacPython/openblas-libs/pull/85#issuecomment-2282654077).

That is not correct, that was only for Windows. We are shipping `libquadmath` on Linux in the latest release (2.3.2).

**Comment by mattip** [comment]
Sorry, I was looking at the arm64 manylinux wheels. For the x86_64 wheel, my version of readelf is showing this on ubuntu 24.04
```
$ wget https://files.pythonhosted.org/packages/8b/95/8023e87cbea31a750a6c00ff9427d65ebc5fef104a136bfa69f76266d614/numpy-2.3.2-pp311-pypy311_pp73-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl
...
$ unzip numpy-2.3.2-pp311-pypy311_pp73-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl
...
$ readelf -n numpy.libs/libquadmath-96973f99-934c22de.so.0.0.0 

Displaying notes found in: .note.gnu.build-id
  Owner                Data size 	Description
  GNU                  0x00000014	NT_GNU_BUILD_ID (unique build ID bitstring)
    Build ID: 549b4c82347785459571c79239872ad31509dcf4
```

**Comment by rgommers** [comment]
Okay, so SHSTK not used. But also, it doesn't really seem to be a problem in practice.
