### ISSUE TITLE
BUG: datetime64 returning NotImplemented with pandas' Timestamps

### ISSUE THREAD

**Issue by SrSoto** [numpy/numpy#24492]
### Describe the issue:

Comparison operations for `datetime64` class (like `__eq__`, `__ge__` and so on) are no longer compatible with Pandas' `Timestamp` object.

Previously, for example, on NumPy `1.20.3`:

```python
import sys
import numpy as np

print(np.__version__)
print(sys.version)
print(f"'__eq__' comparison return: {np.datetime64('2023-08-22').__eq__(pd.Timestamp('2023-08-22'))}")
```

**`1.20.3` output**:

```
1.20.3
3.9.7 (default, Sep 16 2021, 13:09:58) 
[GCC 7.5.0]
'__eq__' comparison return: True
```

On `1.25.2`, we will see that the comparison return is `NotImplemented`.

Beware that this does not mean that someone cannot do a `np.datetime64("2023-08-22") == pd.Timestamp("2023-08-22")` or any other operation directly with its symbol; as the `NotImplemented` return implies calling the `pd.Timestamp.__eq__` method instead. However, if someone needs to be more 'obscure', why would this functionality be lost between newer versions?

### Reproduce the code example:

```python
import sys
import numpy as np

print(np.__version__)
print(sys.version)
print(f"'__eq__' comparison return: {np.datetime64('2023-08-22').__eq__(pd.Timestamp('2023-08-22'))}")
```

### Error message:

```shell
1.25.2
3.10.8 (main, Nov 24 2022, 14:13:03) [GCC 11.2.0]
'__eq__' comparison return: NotImplemented
```

### Runtime information:

```
1.25.2
3.10.8 (main, Nov 24 2022, 14:13:03) [GCC 11.2.0]
[{'numpy_version': '1.25.2',
  'python': '3.10.8 (main, Nov 24 2022, 14:13:03) [GCC 11.2.0]',
  'uname': uname_result(system='Linux', node='sistemas-ThinkPad-T14s-Gen-2i', release='5.10.0-1044-oem', version='#46-Ubuntu SMP Wed Aug 11 09:50:57 UTC 2021', machine='x86_64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2',
                                'AVX512F',
                                'AVX512CD',
                                'AVX512_SKX',
                                'AVX512_CLX',
                                'AVX512_CNL',
                                'AVX512_ICL'],
                      'not_found': ['AVX512_KNL', 'AVX512_KNM']}},
 {'architecture': 'SkylakeX',
  'filepath': '/home/manuel.soto/anaconda3/envs/aml_trans/lib/python3.10/site-packages/numpy.libs/libopenblas64_p-r0-5007b62f.3.23.dev.so',
  'internal_api': 'openblas',
  'num_threads': 8,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.23.dev'},
 {'architecture': 'SkylakeX',
  'filepath': '/home/manuel.soto/anaconda3/envs/aml_trans/lib/python3.10/site-packages/scipy.libs/libopenblasp-r0-23e5df77.3.21.dev.so',
  'internal_api': 'openblas',
  'num_threads': 8,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.21.dev'}]
None
```

### Context for the issue:

Creating a class for timestamps that abstract from timezones and certain types incompatibilities, comparisons are done through a `getattr(obj, op)`. By updating numpy on our library `requirements.txt` is how this bug has been spotted.

Of course, workarounds like directly calling right-side `op` could be done for this `NotImplemented`, so this bug is not deadly prioritizable at all.

**Comment by esapekkasun** [comment]
I can look into this. I am new to NumPy contribution, but would like to join. And the issue looks suitable since I am familiar with NumPy and Pandas libraries and timestamps.

**Comment by mattip** [comment]
We don't assign issues, so feel free to work on this
- Please read the [developer workflow](https://numpy.org/devdocs/dev/index.html)
- Make sure you link back to this issue with text like `Relates to #24492` which will create a link here to show others you are working on the issue.

**Comment by esapekkasun** [comment]
Ok, thanks for the information. I will do that!

**Comment by esapekkasun** [comment]
Any idea how I can test this with a local build of Numpy? I managed to replicate the issue with a separate conda environment with numpy and pandas. But when I tried the same thing with a local build and executing a test script with the numpy-dev environment and `python runtests.py --python test_24492.py`, I get the following error:

```
Building, see build.log...
Build OK
Enabling display of all warnings
Traceback (most recent call last):
  File "/Users/epps/dev/numpy/runtests.py", line 715, in <module>
    main(argv=sys.argv[1:])
  File "/Users/epps/dev/numpy/runtests.py", line 228, in main
    exec(script, ns)
  File "<string>", line 3, in <module>
  File "/Users/epps/anaconda3/envs/numpy-dev/lib/python3.9/site-packages/pandas/__init__.py", line 48, in <module>
    from pandas.core.api import (
  File "/Users/epps/anaconda3/envs/numpy-dev/lib/python3.9/site-packages/pandas/core/api.py", line 47, in <module>
    from pandas.core.groupby import (
  File "/Users/epps/anaconda3/envs/numpy-dev/lib/python3.9/site-packages/pandas/core/groupby/__init__.py", line 1, in <module>
    from pandas.core.groupby.generic import (
  File "/Users/epps/anaconda3/envs/numpy-dev/lib/python3.9/site-packages/pandas/core/groupby/generic.py", line 77, in <module>
    from pandas.core.frame import DataFrame
  File "/Users/epps/anaconda3/envs/numpy-dev/lib/python3.9/site-packages/pandas/core/frame.py", line 182, in <module>
    from pandas.core.generic import NDFrame
  File "/Users/epps/anaconda3/envs/numpy-dev/lib/python3.9/site-packages/pandas/core/generic.py", line 179, in <module>
    from pandas.core.window import (
  File "/Users/epps/anaconda3/envs/numpy-dev/lib/python3.9/site-packages/pandas/core/window/__init__.py", line 1, in <module>
    from pandas.core.window.ewm import (
  File "/Users/epps/anaconda3/envs/numpy-dev/lib/python3.9/site-packages/pandas/core/window/ewm.py", line 11, in <module>
    import pandas._libs.window.aggregations as window_aggregations
  File "pandas/_libs/window/aggregations.pyx", line 54, in init pandas._libs.window.aggregations
  File "/Users/epps/dev/numpy/build/testenv/lib/python3.9/site-packages/numpy/__init__.py", line 347, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'NINF'
```

The file `test_24492.py` contains:

```
import sys
import numpy as np
import pandas as pd

print(np.__version__)
print(sys.version)
print(f"'__eq__' comparison return: {np.datetime64('2023-08-22').__eq__(pd.Timestamp('2023-08-22'))}")
```

**Comment by andyfaff** [comment]
I believe `np.NINF` is being removed in numpy 2.0.

**Comment by esapekkasun** [comment]
I see, that makes sense. I need to test my changes then with some roundabout way then. Thanks for the information!

**Comment by esapekkasun** [comment]
I temporarily added INF and NINF back for testing while developing, and now it works:

```
Building, see build.log...
Build OK
Enabling display of all warnings
2.0.0.dev0+git20230822.3032e84
3.9.17 | packaged by conda-forge | (main, Aug 10 2023, 07:05:25) 
[Clang 15.0.7 ]
'__eq__' comparison return: NotImplemented
```

**Comment by seberg** [comment]
It seems right to me for us to defer to pandas, one should always defer to the subtype/more precise version.  I am not usre why it changed, but without more reasoning why it is bad that it changed, I think it is an improvement.

**Comment by esapekkasun** [comment]
I have also not found a good solution for this yet. And I also agree that the current version is also good for this functionality. For the while being I will look for some other issue to work on.
