### ISSUE TITLE
ufuncs don't work on `recarray`

### ISSUE THREAD

**Issue by kwsp** [numpy/numpy#24585]
### Describe the issue:

`np.recarray` ufuncs don't work, even though they are documented. E.g. [`np.recarray.sum`](https://numpy.org/doc/stable/reference/generated/numpy.recarray.sum.html#numpy.recarray.sum)

### Reproduce the code example:

```python
x = np.array([(1.0, 2), (3.0, 4)], dtype=[('x', '<f8'), ('y', '<i8')])
x = x.view(np.recarray)
x.sum()  # Raises numpy.core._exceptions._UFuncNoLoopError
```

### Error message:

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\user\miniconda3\envs\oct\lib\site-packages\numpy\core\_methods.py", line 49, in _sum
    return umr_sum(a, axis, dtype, out, keepdims, initial, where)
numpy.core._exceptions._UFuncNoLoopError: ufunc 'add' did not contain a loop with signature matching types (dtype((numpy.record, [('x', '<f8'), ('y', '<i8')])), dtype((numpy.record, [('x', '<f8'), ('y', '<i8')]))) -> None
```

### Runtime information:

1.25.2
3.10.8 | packaged by conda-forge | (main, Nov 24 2022, 14:07:00) [MSC v.1916 64 bit (AMD64)]

**Comment by kwsp** [comment]
Passing an `axis` parameter doesn't work either. I'd expect the ufuncs to at least work over each field.

**Comment by rkern** [comment]
It's a common enough desire, but it doesn't really fit into the ufunc architecture. This is a missing desirable feature, but not one that is likely to ever be added. It would be good if this limitation were better documented, which is why I have switched the issue label. By and large, structured/record arrays are basically containers, and you can do math on the individual fields once you pull them out, but not math operations on all of the fields at once.

We do [document how to register new ufunc loops](https://numpy.org/doc/1.25/user/c-info.ufunc-tutorial.html#example-numpy-ufunc-with-structured-array-dtype-arguments) for individual structures, though.

**Comment by kwsp** [comment]
I understand that it doesn't fit into ufunc. So these exposed public APIs never work on any recarray? Is that a good motivation to not only remove the docs, but also remove them from the recarray methods?

**Comment by rkern** [comment]
They are inherited from `np.ndarray`. Hard to remove them, per se. They'll still exist on true `ndarray` objects with structured dtypes (which we largely recommend over using `recarray`, in any case), so the most we can really do is change the documentation.

**Comment by kwsp** [comment]
Sounds good. I'll think about the docs. We should definitely link to https://numpy.org/doc/1.25/user/c-info.ufunc-tutorial.html#example-numpy-ufunc-with-structured-array-dtype-arguments

**Comment by kwsp** [comment]
@rkern Sorry just one more question- could you very briefly explain why its hard to apply ufuncs to every attribute separately?

**Comment by rkern** [comment]
The [ufunc infrastructure](https://numpy.org/doc/stable/dev/internals.code-explanations.html#universal-functions) is based around collections of C loop functions based on the dtypes of the inputs and outputs. Given the arrays which it is passed, the ufunc will look up which C loop function to use based on what's available and execute that loop function. `np.add`, for instance, has 22 different C loop functions, one for each of the basic dtypes that have an addition operation defined on them:

```python
>>> np.add.types
['??->?',
 'bb->b',
 'BB->B',
 'hh->h',
 'HH->H',
 'ii->i',
 'II->I',
 'll->l',
 'LL->L',
 'qq->q',
 'QQ->Q',
 'ee->e',
 'ff->f',
 'dd->d',
 'gg->g',
 'FF->F',
 'DD->D',
 'GG->G',
 'Mm->M',
 'mm->m',
 'mM->M',
 'OO->O']
```

For ufuncs to operate on structured arrays (i.e. arrays with ad hoc dtypes with multiple fields), one would have to implement a C loop function for each of those fielded dtypes, explicitly. The example I linked to is one such, for one particular fielded dtype.

**Comment by seberg** [comment]
I will note that things look a bit different internally now, giving us more flexibility in adding such a new loop.  The issue is (and always has been), that you can only add one such loop for all structured dtypes.  The new machinery allows you to figure out a bit more though w.r.t. what to return exactly, etc.

One thing that nobody is working on but that is plausible would be making it easy to creat a new DType to type things more strictly and then explicitly allow this, like:
```
@something
class CoordinateDType:
    x: float64
    y: float64
```
which then could have the ability to make it very simply to say that `np.add` should just be component wise addition.  The internal machinery to do this exists very much (casting does it and is identical).  But

**Comment by InessaPawson** [comment]
A note in the structured-arrays guide and the `recarray` docstring explaining that operations such as reductions should generally be applied to individual fields would address the docs issue.

@seberg's [idea of supporting field-wise operations on structured dtypes](https://github.com/numpy/numpy/issues/24585#issuecomment-1706151509) is a separate enhancement and should be discussed in a separate issue.

**Comment by sukeyzhou** [comment]
take

**Comment by ikrommyd** [comment]
@sukeyzhou - we do not assign issues in this project, also please read our [AI policy](https://numpy.org/devdocs/dev/ai_policy.html) and the development docs before submitting a patch
