### ISSUE TITLE
BUG: f2py string optional inout argument produces `try_pyarr_from_string` error

### ISSUE THREAD

**Issue by danbeibei** [numpy/numpy#24662]
### Describe the issue:

Fortran wrapped subroutine with an argument `character*(N), optional, intent(inout)` produces `try_pyarr_from_string` error when called without the optional argument. Related to #18759 @pearu 

### Reproduce the code example:

The Fortran file to be wrapped `main.f90`:
```fortran
subroutine string_inout_optional(output)
    implicit none
    character*(32), optional, intent(inout) :: output
    if (present(output)) then
      output="output string"
    endif
end subroutine
``` 
The shell commands to wrap and execute:
```shell
f2py -c main.f90 -m optional_test
python3 -c "import optional_test; optional_test.string_inout_optional()"
``` 

### Error message:

```shell
optional_test.error is related to None
Traceback (most recent call last):
  File "<string>", line 1, in <module>
optional_test.error: try_pyarr_from_string failed
```

### I believe the problem lies here:
https://github.com/numpy/numpy/blob/54238c7be10104d506259d431e7ce81483666ade/numpy/f2py/cfuncs.py#L650C1-L651C6

With the `return 1` statement out of the if block it works fine:

```c
    if (PyArray_Check(obj)) {
        PyArrayObject *arr = (PyArrayObject *)obj;
        assert(ISCONTIGUOUS(arr));
        string buf = PyArray_DATA(arr);
        npy_intp n = len;
        if (n == -1) {
            /* Assuming null-terminated str. */
            n = strlen(str);
        }
        if (n > PyArray_NBYTES(arr)) {
            n = PyArray_NBYTES(arr);
        }
        STRINGCOPYN(buf, str, n);
    }
    return 1;
capi_fail:
    PRINTPYOBJERR(obj);
    PyErr_SetString(#modulename#_error, \"try_pyarr_from_string failed\");
    return 0;
}
```

I'm not sure if the `return 1` statement being inside the if block is a typo or if it is intended to raise the error.

### Runtime information:

```
$ python3 -c "import sys, numpy; print(numpy.__version__); print(sys.version); print(numpy.show_runtime())"
2.0.0.dev0+git20230904.70f7021
3.9.18 | packaged by conda-forge | (main, Aug 30 2023, 03:43:54) 
[GCC 12.3.0]
[{'numpy_version': '2.0.0.dev0+git20230904.70f7021',
  'python': '3.9.18 | packaged by conda-forge | (main, Aug 30 2023, '
            '03:43:54) \n'
            '[GCC 12.3.0]',
  'uname': uname_result(system='Linux', node='*******', release='4.18.0-305.30.1.el8_4.ppc64le', version='#1 SMP Wed Dec 1 10:27:01 EST 2021', machine='ppc64le')},
 {'simd_extensions': {'baseline': ['VSX', 'VSX2'],
                      'found': ['VSX3'],
                      'not_found': []}}]
None
```

### Context for the issue:

Forces us to stick with an older version of Numpy for wrapping Fortran routines while we need up to date Numpy version for other tools

**Comment by HaoZeke** [comment]
Compiling this in debug mode:
```bash
CFLAGS="-DDEBUGCFUNCS" f2py -c main.f90 -m optional_test
python3 -c "import optional_test; optional_test.string_inout_optional()"
string_from_pyobj(str='',len=32,inistr='',obj=0x557035cc7560)
try_pyarr_from_string(str='output string', len=32, obj=0x557035cc7560)
optional_test.error is related to None
debug-capi:Freeing memory.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
optional_test.error: try_pyarr_from_string failed
```

While the fix suggested causes (returning with a `-1`):
```bash
string_from_pyobj(str='',len=32,inistr='',obj=0x55e8b4e7d560)
try_pyarr_from_string(str='output string', len=32, obj=0x55e8b4e7d560)
debug-capi:Building return value.
debug-capi:Freeing memory.
```

However this doesn't tell the whole story. Consider what the routine is actually supposed to do.

```fortran
! suby.f90
    subroutine string_inout_optional(output)
        character(32), optional, intent(inout) :: output
        if (present(output)) then
            output = "output string"
        endif
    end subroutine string_inout_optional
```

With a runner:
```fortran
! main.f90
program test_string_inout
    implicit none
    character(32) :: input_string
    interface
        subroutine string_inout_optional(output)
            character(32), optional, intent(inout) :: output
        end subroutine string_inout_optional
    end interface

    ! With an input string
    input_string = "Initial String"
    print *, "Before (with string): ", input_string
    call string_inout_optional(input_string)
    print *, "After (with string): ", input_string

    print *, ""

    ! Without an empty string
    input_string = ""
    print *, "Before (empty string): ", input_string
    call string_inout_optional(input_string)
    print *, "After (empty string): ", input_string
    ! No string
    print *, "Call without arguments"
    call string_inout_optional

end program test_string_inout
```

So:
```bash
❯ gfortran main.f90 suby.f90 -o runme
❯ ./runme
 Before (with string): Initial String                  
 After (with string): output string                   
 
 Before (empty string):                                 
 After (empty string): output string                   
 Call without arguments
```

In turn this suggests that passing a string to Fortran call from Python should return a valid string, however this is not true:

```bash
python3 -c "import optional_test; a='hi'; optional_test.string_inout_optional(a); print(a)"
string_from_pyobj(str='',len=32,inistr='',obj=0x55751cfbebe8)
try_pyarr_from_string(str='output string', len=32, obj=0x55751cfbebe8)
debug-capi:Building return value.
debug-capi:Freeing memory.
hi
```

So the fix needs more work.
