### ISSUE TITLE
BUG: 'complex.h' header is not available

### ISSUE THREAD

**Issue by a-sajjad72** [numpy/numpy#24708]
### Describe the issue:

i am trying to build numpy. followed all the steps mentioned [here](https://numpy.org/devdocs/dev/index.html#development-process-summary).
when i tried to install from source using `python setup.py build_ext --inplace`. after some logs it shows the error complex.h is not available.
Python 3.10.11 
numpy : head at commit f6bf183abbb61507647aaf40b48c28525fc18e48

### Reproduce the code example:

```python
python setup.py build_ext --inplace
```

### Error message:

```shell
(virt_env) D:\CodePlayground\Python\numpy>python setup.py build_ext --inplace
Running from numpy source directory.
D:\CodePlayground\Python\numpy\setup.py:75: DeprecationWarning: 

  `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
  of the deprecation of `distutils` itself. It will be removed for
  Python >= 3.12. For older Python versions it will remain present.
  It is recommended to use `setuptools < 60.0` for those Python versions.
  For more details, see:
    https://numpy.org/devdocs/reference/distutils_status_migration.html


  import numpy.distutils.command.sdist
Cythonizing sources
Processing numpy/random\_bounded_integers.pxd.in
Processing numpy/random\bit_generator.pyx
Processing numpy/random\mtrand.pyx
Processing numpy/random\_bounded_integers.pyx.in
Processing numpy/random\_common.pyx
Processing numpy/random\_generator.pyx
Processing numpy/random\_mt19937.pyx
Processing numpy/random\_pcg64.pyx
Processing numpy/random\_philox.pyx
Processing numpy/random\_sfc64.pyx
INFO: blas_opt_info:
INFO: blas_armpl_info:
INFO: No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
INFO: customize MSVCCompiler
INFO:   libraries armpl_lp64_mp not found in ['C:\\Users\\HaLF-MenTaL\\AppData\\Local\\Programs\\Python\\Python310\\lib', 'C:\\', 'C:\\Users\\HaLF-MenTaL\\AppData\\Local\\Programs\\Python\\Python310\\libs']
INFO:   NOT AVAILABLE
INFO:
INFO: blas_mkl_info:
INFO:   libraries mkl_rt not found in ['C:\\Users\\HaLF-MenTaL\\AppData\\Local\\Programs\\Python\\Python310\\lib', 'C:\\', 'C:\\Users\\HaLF-MenTaL\\AppData\\Local\\Programs\\Python\\Python310\\libs']
INFO:   NOT AVAILABLE
INFO:
INFO: blas_ssl2_info:
INFO:   libraries fjlapackexsve not found in ['C:\\Users\\HaLF-MenTaL\\AppData\\Local\\Programs\\Python\\Python310\\lib', 'C:\\', 'C:\\Users\\HaLF-MenTaL\\AppData\\Local\\Programs\\Python\\Python310\\libs']
INFO:   NOT AVAILABLE
INFO:
INFO: blis_info:
INFO:   libraries blis not found in ['C:\\Users\\HaLF-MenTaL\\AppData\\Local\\Programs\\Python\\Python310\\lib', 'C:\\', 'C:\\Users\\HaLF-MenTaL\\AppData\\Local\\Programs\\Python\\Python310\\libs']
INFO:   NOT AVAILABLE
INFO:
INFO: openblas_info:
creating C:\Users\HALF-M~1\AppData\Local\Temp\tmpp6owp_a5\Users
creating C:\Users\HALF-M~1\AppData\Local\Temp\tmpp6owp_a5\Users\HALF-M~1
creating C:\Users\HALF-M~1\AppData\Local\Temp\tmpp6owp_a5\Users\HALF-M~1\AppData
creating C:\Users\HALF-M~1\AppData\Local\Temp\tmpp6owp_a5\Users\HALF-M~1\AppData\Local
creating C:\Users\HALF-M~1\AppData\Local\Temp\tmpp6owp_a5\Users\HALF-M~1\AppData\Local\Temp
creating C:\Users\HALF-M~1\AppData\Local\Temp\tmpp6owp_a5\Users\HALF-M~1\AppData\Local\Temp\tmpp6owp_a5
INFO: C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.37.32822\bin\HostX86\x64\cl.exe /c /nologo /O2 /W3 
/GL /DNDEBUG /MD -IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.37.32822\include -IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt /TcC:\Users\HALF-M~1\AppData\Local\Temp\tmpp6owp_a5\source.c /FoC:\Users\HALF-M~1\AppData\Local\Temp\tmpp6owp_a5\Users\HALF-M~1\AppData\Local\Temp\tmpp6owp_a5\source.obj
INFO: C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.37.32822\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /MANIFEST:EMBED,ID=1 /LIBPATH:c:/openblas/lib /LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.37.32822\lib\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.22621.0\ucrt\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\\lib\10.0.22621.0\\um\x64 libopenblas.lib C:\Users\HALF-M~1\AppData\Local\Temp\tmpp6owp_a5\Users\HALF-M~1\AppData\Local\Temp\tmpp6owp_a5\source.obj /OUT:C:\Users\HALF-M~1\AppData\Local\Temp\tmpp6owp_a5\a.out.exe
INFO:   FOUND:
INFO:     libraries = ['libopenblas', 'libopenblas']
INFO:     library_dirs = ['c:/openblas/lib']
INFO:     language = c
INFO:     define_macros = [('HAVE_CBLAS', None)]
INFO:     runtime_library_dirs = ['c:/openblas/lib']
INFO:
INFO:   FOUND:
INFO:     libraries = ['libopenblas', 'libopenblas']
INFO:     library_dirs = ['c:/openblas/lib']
INFO:     language = c
INFO:     define_macros = [('HAVE_CBLAS', None)]
INFO:     runtime_library_dirs = ['c:/openblas/lib']
INFO:
non-existing path in 'numpy\\f2py': 'backends/meson.build.template'
INFO: lapack_opt_info:
INFO: lapack_armpl_info:
INFO:   libraries armpl_lp64_mp not found in ['C:\\Users\\HaLF-MenTaL\\AppData\\Local\\Programs\\Python\\Python310\\lib', 'C:\\', 'C:\\Users\\HaLF-MenTaL\\AppData\\Local\\Programs\\Python\\Python310\\libs']
INFO:   NOT AVAILABLE
INFO:
INFO: lapack_mkl_info:
INFO:   libraries mkl_rt not found in ['C:\\Users\\HaLF-MenTaL\\AppData\\Local\\Programs\\Python\\Python310\\lib', 'C:\\', 'C:\\Users\\HaLF-MenTaL\\AppData\\Local\\Programs\\Python\\Python310\\libs']
INFO:   NOT AVAILABLE
INFO:
INFO: lapack_ssl2_info:
INFO:   libraries fjlapackexsve not found in ['C:\\Users\\HaLF-MenTaL\\AppData\\Local\\Programs\\Python\\Python310\\lib', 'C:\\', 'C:\\Users\\HaLF-MenTaL\\AppData\\Local\\Programs\\Python\\Python310\\libs']
INFO:   NOT AVAILABLE
INFO:
INFO: openblas_lapack_info:
creating C:\Users\HALF-M~1\AppData\Local\Temp\tmpo6bfgtv1\Users
creating C:\Users\HALF-M~1\AppData\Local\Temp\tmpo6bfgtv1\Users\HALF-M~1
creating C:\Users\HALF-M~1\AppData\Local\Temp\tmpo6bfgtv1\Users\HALF-M~1\AppData
creating C:\Users\HALF-M~1\AppData\Local\Temp\tmpo6bfgtv1\Users\HALF-M~1\AppData\Local
creating C:\Users\HALF-M~1\AppData\Local\Temp\tmpo6bfgtv1\Users\HALF-M~1\AppData\Local\Temp
creating C:\Users\HALF-M~1\AppData\Local\Temp\tmpo6bfgtv1\Users\HALF-M~1\AppData\Local\Temp\tmpo6bfgtv1
INFO: C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.37.32822\bin\HostX86\x64\cl.exe /c /nologo /O2 /W3 
/GL /DNDEBUG /MD -IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.37.32822\include -IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt -IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.37.32822\include -IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared -IC:\Program 
Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt /TcC:\Users\HALF-M~1\AppData\Local\Temp\tmpo6bfgtv1\source.c /FoC:\Users\HALF-M~1\AppData\Local\Temp\tmpo6bfgtv1\Users\HALF-M~1\AppData\Local\Temp\tmpo6bfgtv1\source.obj
INFO: C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.37.32822\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /MANIFEST:EMBED,ID=1 /LIBPATH:c:/openblas/lib /LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.37.32822\lib\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.22621.0\ucrt\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\\lib\10.0.22621.0\\um\x64 libopenblas.lib C:\Users\HALF-M~1\AppData\Local\Temp\tmpo6bfgtv1\Users\HALF-M~1\AppData\Local\Temp\tmpo6bfgtv1\source.obj /OUT:C:\Users\HALF-M~1\AppData\Local\Temp\tmpo6bfgtv1\a.out.exe
INFO:   FOUND:
INFO:     libraries = ['libopenblas', 'libopenblas']
INFO:     library_dirs = ['c:/openblas/lib']
INFO:     language = c
INFO:     define_macros = [('HAVE_CBLAS', None)]
INFO:     runtime_library_dirs = ['c:/openblas/lib']
INFO:
INFO:   FOUND:
INFO:     libraries = ['libopenblas', 'libopenblas']
INFO:     library_dirs = ['c:/openblas/lib']
INFO:     language = c
INFO:     define_macros = [('HAVE_CBLAS', None)]
INFO:     runtime_library_dirs = ['c:/openblas/lib']
INFO:
C:\Users\HaLF-MenTaL\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\dist.py:264: UserWarning: Unknown distribution option: 'define_macros'
  warnings.warn(msg)
C:\Users\HaLF-MenTaL\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\dist.py:530: UserWarning: Normalizing '2.0.02.0.0.dev0+git20230914.f6bf183' to '2.0.2.0.0.dev0+git20230914.f6bf183'
  warnings.warn(tmpl.format(**locals()))
running build_ext
running build_src
INFO: build_src
INFO: building py_modules sources
INFO: building library "npymath" sources
creating build
creating build\src.win-amd64-3.10
WARN: Could not locate executable g77
WARN: Could not locate executable f77
WARN: Could not locate executable ifort
WARN: Could not locate executable ifl
WARN: Could not locate executable f90
WARN: Could not locate executable DF
WARN: Could not locate executable efl
INFO: conv_template:> numpy\core\src\npymath\npy_math_internal.h
INFO:   adding 'numpy\core\src\npymath' to include_dirs.
INFO: conv_template:> numpy\core\src\npymath\ieee754.c
INFO: conv_template:> numpy\core\src\npymath\npy_math_complex.c
INFO: None - nothing done with h_files = ['numpy\\core\\src\\npymath\\npy_math_internal.h']
INFO: building library "npyrandom" sources
INFO: building extension "numpy.core._multiarray_tests" sources
INFO: conv_template:> numpy\core\src\multiarray\_multiarray_tests.c
INFO: building extension "numpy.core._multiarray_umath" sources
Traceback (most recent call last):
  File "D:\CodePlayground\Python\numpy\setup.py", line 568, in <module>
    setup_package()
  File "D:\CodePlayground\Python\numpy\setup.py", line 560, in setup_package
    setup(**metadata)
  File "D:\CodePlayground\Python\numpy\numpy\distutils\core.py", line 169, in setup
    return old_setup(**new_attr)
  File "C:\Users\HaLF-MenTaL\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\__init__.py", line 87, in setup        
    return distutils.core.setup(**attrs)
  File "C:\Users\HaLF-MenTaL\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup    return run_commands(dist)
  File "C:\Users\HaLF-MenTaL\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
    dist.run_commands()
  File "C:\Users\HaLF-MenTaL\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\dist.py", line 968, in run_commands
    self.run_command(cmd)
  File "C:\Users\HaLF-MenTaL\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\dist.py", line 1217, in run_command    
    super().run_command(command)
  File "C:\Users\HaLF-MenTaL\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
    cmd_obj.run()
  File "D:\CodePlayground\Python\numpy\numpy\distutils\command\build_ext.py", line 101, in run
    self.run_command('build_src')
  File "C:\Users\HaLF-MenTaL\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\cmd.py", line 319, in run_command
    self.distribution.run_command(command)
  File "C:\Users\HaLF-MenTaL\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\dist.py", line 1217, in run_command    
    super().run_command(command)
  File "C:\Users\HaLF-MenTaL\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
    cmd_obj.run()
  File "D:\CodePlayground\Python\numpy\numpy\distutils\command\build_src.py", line 144, in run
    self.build_sources()
  File "D:\CodePlayground\Python\numpy\numpy\distutils\command\build_src.py", line 161, in build_sources
    self.build_extension_sources(ext)
  File "D:\CodePlayground\Python\numpy\numpy\distutils\command\build_src.py", line 318, in build_extension_sources
    sources = self.generate_sources(sources, ext)
  File "D:\CodePlayground\Python\numpy\numpy\distutils\command\build_src.py", line 378, in generate_sources
    source = func(extension, build_dir)
  File "D:\CodePlayground\Python\numpy\numpy\core\setup.py", line 452, in generate_config_h
    moredefs.extend(cocache.check_complex(config_cmd, mathlibs)[0])
  File "D:\CodePlayground\Python\numpy\numpy\core\setup.py", line 64, in check_complex
    out = check_complex(*a, **kw)
  File "D:\CodePlayground\Python\numpy\numpy\core\setup.py", line 246, in check_complex
    raise SystemError("'complex.h' header is not available")
SystemError: 'complex.h' header is not available
```

### Runtime information:

sorry the numpy is not installed yet to provide such information.

**Comment by mattip** [comment]
Don't use `python setup.py build_ext --inplace`. Use `pip install -e . --no-build-isolation`

**Comment by mattip** [comment]
Sorry, I shouldn't comment at the end of a long day. I didn't mean to be abrupt. You seem to be using Visual Studio 2022, which should have `complex.h` so I wonder why the compilation fails. The failure is coming from [here](https://github.com/numpy/numpy/blob/f6bf183abbb61507647aaf40b48c28525fc18e48/numpy/core/setup.py#L244) which tries to compile a snippet of code frome [here](https://github.com/numpy/numpy/blob/main/numpy/distutils/command/config.py#L170). Apparently that fails, but I think using the newer meson build system it should work.

**Comment by mattip** [comment]
Ahh, that sequence changed 3 weeks ago in #24370, which made `complex.h` a required dependency. But I think we tested the setup.py code path in that PR, no? @lysnikolaou thoughts?

**Comment by rgommers** [comment]
Don't spend time on debugging that please, we decided to delete all `setup.py` files asap. That can happen as soon as tomorrow.

**Comment by a-sajjad72** [comment]
> Don't spend time on debugging that please, we decided to delete all `setup.py` files asap. That can happen as soon as tomorrow.

thanks.  i just got headache trying again n again. there also bug of `cblas` stuff i am reporting soon.

**Comment by rgommers** [comment]
Okay, I'll close this then.

> there also bug of `cblas` stuff i am reporting soon.

It should work fine with the Meson build (e.g. `pip install .`) if you have OpenBLAS installed.

**Comment by a-sajjad72** [comment]
> It should work fine with the Meson build (e.g. `pip install .`) if you have OpenBLAS installed.

i had alreadyt tried it. i got it from the OpenBLAS releases. but numpy require BLAS library with **`CBLAS`** support. this is the missing thing from the from all over the documentation. everywhere is written BLAS not CBLAS.

**Comment by rgommers** [comment]
Every reasonable install of OpenBLAS (and MKL, Accelerate and Netlib BLAS) does have CBLAS support. The build docs are overdue for a larger makeover and that will happen, so we can mention this. But we don't need a separate bug report for it now - this works out of the box almost everywhere and you get an informative error message otherwise.

**Comment by a-sajjad72** [comment]
> Every reasonable install of OpenBLAS (and MKL, Accelerate and Netlib BLAS) does have CBLAS support.

i am providing the error details here because you refused to receive a bug report on this issue.
@rgommers trust me i got the openblas release from github releases [OpenBLAS-0.3.24-x64.zip](https://github.com/xianyi/OpenBLAS/releases/download/v0.3.24/OpenBLAS-0.3.24-x64.zip) few minutes ago. run `pip install .`
but the error is still there. it found the openblas library (path defined in the `site.cfg`) but shows error for the `cblas`.

site.cfg
```
[openblas]
libraries = openblas
library_dirs = c:/openblas/lib
include_dirs = c:/openblas/include
runtime_library_dirs = c:/openblas/lib
```

here is the log
```
(numpy_virt_env) D:\CodePlayground\Python\numpy>pip install .
Processing d:\codeplayground\python\numpy
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [62 lines of output]
      + D:\CodePlayground\Python\numpy_virt_env\Scripts\python.exe D:\CodePlayground\Python\numpy\vendored-meson\meson\meson.py setup D:\CodePlayground\Python\numpy D:\CodePlayground\Python\numpy\.mesonpy-zoav8d9l\build -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=D:\CodePlayground\Python\numpy\.mesonpy-zoav8d9l\build\meson-python-native-file.ini
      The Meson build system
      Version: 1.2.99
      Source dir: D:\CodePlayground\Python\numpy
      Build dir: D:\CodePlayground\Python\numpy\.mesonpy-zoav8d9l\build
      Build type: native build
      Project name: NumPy
      Project version: 2.0.0.dev0+git20230914.f6bf183
      C compiler for the host machine: ccache gcc (gcc 13.1.0 "gcc (MinGW-W64 x86_64-ucrt-posix-seh, built by Brecht Sanders) 13.1.0")   
      C linker for the host machine: gcc ld.bfd 2.40
      C++ compiler for the host machine: ccache c++ (gcc 13.1.0 "c++ (MinGW-W64 x86_64-ucrt-posix-seh, built by Brecht Sanders) 13.1.0") 
      C++ linker for the host machine: c++ ld.bfd 2.40
      Cython compiler for the host machine: cython (cython 3.0.2)
      Host machine cpu family: x86_64
      Host machine cpu: x86_64
      Program python found: YES (D:\CodePlayground\Python\numpy_virt_env\Scripts\python.exe)
      Run-time dependency python found: YES 3.10
      Has header "Python.h" with dependency python: YES
      Compiler for C supports arguments -fno-strict-aliasing: YES
      Test features "SSE SSE2 SSE3" : Supported
      Test features "SSSE3" : Supported
      Test features "SSE41" : Supported
      Test features "POPCNT" : Supported
      Test features "SSE42" : Supported
      Test features "AVX" : Supported
      Test features "F16C" : Supported
      Test features "FMA3" : Supported
      Test features "AVX2" : Supported
      Test features "AVX512F" : Supported
      Test features "AVX512CD" : Supported
      Test features "AVX512_KNL" : Supported
      Test features "AVX512_KNM" : Supported
      Test features "AVX512_SKX" : Supported
      Test features "AVX512_CLX" : Supported
      Test features "AVX512_CNL" : Supported
      Test features "AVX512_ICL" : Supported
      Test features "AVX512_SPR" : Supported
      Configuring npy_cpu_dispatch_config.h using configuration
      Message:
      CPU Optimization Options
        baseline:
          Requested : min
          Enabled   : SSE SSE2 SSE3
        dispatch:
          Requested : max -xop -fma4
          Enabled   : SSSE3 SSE41 POPCNT SSE42 AVX F16C FMA3 AVX2 AVX512F AVX512CD AVX512_KNL AVX512_KNM AVX512_SKX AVX512_CLX AVX512_CNL AVX512_ICL AVX512_SPR
     
      Library m found: YES
      Did not find pkg-config by name 'pkg-config'
      Found Pkg-config: NO
      Found CMake: C:\mingw64\bin\cmake.EXE (3.26.4)
      WARNING: CMake Toolchain: Failed to determine CMake compilers state
      WARNING: CMake Toolchain: Failed to determine CMake compilers state
      Run-time dependency openblas found: NO (tried pkgconfig)
      WARNING: CMake Toolchain: Failed to determine CMake compilers state
      Run-time dependency openblas found: YES 0.3.24
      Checking if "CBLAS" with dependency OpenBLAS: links: NO
      Run-time dependency cblas found: NO (tried pkgconfig and cmake)
     
      ..\..\numpy\meson.build:189:4: ERROR: Problem encountered: No CBLAS interface detected! Install a BLAS library with CBLAS support, 
or use the `allow-noblas` build option (note, this may be up to 100x slower for some linear algebra operations).
     
      A full log can be found at D:\CodePlayground\Python\numpy\.mesonpy-zoav8d9l\build\meson-logs\meson-log.txt
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```

**Comment by rgommers** [comment]
I don't know what is going on there, it's a CMake issue. The OpenBLAS binary is definitely built with CBLAS support, the `openblas.pc` file contains:
```
openblas_config= USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER=1 NO_CBLAS= NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= generic MAX_THREADS=64
```
and the zip file also includes `openblas.pc`. If you install `pkg-config` and ensure the line `Found Pkg-config: NO` turns to YES, things will work. 

An install of CMake and OpenBLAS from the same provider is something I've tested before and worked, but it's not covered in CI and as a fallback method is very difficult to test.

**Comment by mattip** [comment]
As @rgommers pointed out, the meson build system does not use `site.cfg`, rather it needs a working pkg-config or CMake. This is somewhat documented under paragraph (3) [here](https://numpy.org/devdocs/user/building.html#prerequisites), but unfortunately the actual link to [the scipy docs](https://docs.scipy.org/doc/scipy/building/blas_lapack.html#using-pkg-config-to-detect-libraries-in-a-nonstandard-location) is broken. So in order to use the `openblas.pc` file you need to install pkg-config from choco or from conda and point PKG_CONFIG_PATH to the file or get CMake to find the corresponding CMake files. Note that due to limitations in pkg-config, you need to unzip the openblas.zip in an exact locatation, look inside the `openblas.pc` file for the path. I have not personally used CMake on windows with a NumPy build so I don't know how to add the cmake files so CMake can find them and if they require tweaking.

You are probably saying to yourself "well, that is not very friendly". You are correct. We are working on a solution that will involve creating a wheel for openblas, you can follow the progress on https://github.com/MacPython/openblas-libs/pull/87. Hopefully that will be merged and integrated into NumPy soon.

**Comment by ngoldbaum** [comment]
I think this will always happen if you fail to pass `--vsenv` to `spin build` or `meson setup` and `clang` is in your PATH. I guess numpy doesn't support clang-cl on Windows at all? We probably should have a separate issue to track that.

**Comment by ngoldbaum** [comment]
I see on CI when we test clang-cl, we create a `clang-cl-build.ini`, so this may also be happening because of mixing toolchains I guess.

**Comment by rgommers** [comment]
`clang-cl` should be supported. It depends on MSVC tools though, so you indeed should need either `--vsenv` or you should run the build in a Visual Studio Developer Command Prompt.

In this code block, `clang-cl` (but not `clang`) should hit the `get_argument_syntax() == 'msvc'` branch:

https://github.com/numpy/numpy/blob/c045306a188f19d7f919512638bd5f02724c9c7e/numpy/_core/meson.build#L159-L175

**Comment by timothycarambat** [comment]
For anyone who comes across this in the future:

On a Snapdragon X Elite device with NPU
WIndows 11, running Python 3.11.9 (ARM64)

This should fix the `pip install onnxruntime-qnn` numpy subdep crash
- Open shell and try `clang` - should say "no files" as an error.
- Open powershell and check `(Get-Command clang).Path` and see there is probably an entry for VisualStudio
- Open Environment variables
- Look at USER and SYSTEM `PATH`
- Copy entry that matches entry from step one and put somewhere safe
- Delete entry from system and user path
- Open fresh powershell and attempt to run `clang` - should error as not found
- Using a fresh shell you can now `pip install onnxruntime-qnn` or `numpy`
- You can add back ENV entries after successfull installation.

**Comment by sumanthewhiz** [comment]
> For anyone who comes across this in the future:
> 
> On a Snapdragon X Elite device with NPU WIndows 11, running Python 3.11.9 (ARM64)
> 
> This should fix the `pip install onnxruntime-qnn` numpy subdep crash
> 
> * Open shell and try `clang` - should say "no files" as an error.
> * Open powershell and check `(Get-Command clang).Path` and see there is probably an entry for VisualStudio
> * Open Environment variables
> * Look at USER and SYSTEM `PATH`
> * Copy entry that matches entry from step one and put somewhere safe
> * Delete entry from system and user path
> * Open fresh powershell and attempt to run `clang` - should error as not found
> * Using a fresh shell you can now `pip install onnxruntime-qnn` or `numpy`
> * You can add back ENV entries after successfull installation.

Thanks @timothycarambat - this helped resolve the complex float issue. However, I'm facing a new error now - "fatal error C1083: Cannot open compiler generated file: '': Invalid argument". Any idea why that might happen? I'm on the exact same architecture, Snapdragon X Elite device with NPU WIndows 11, running Python 3.13 (ARM64). Have attached the logs as well for reference.

[logs.txt](https://github.com/user-attachments/files/22420250/logs.txt)

**Comment by timothycarambat** [comment]
@sumanthewhiz I could not say. There were some updates to the drivers for the NPU recently and this could possibly be related. I have not yet had to use this library since I wrote that comment, as I mostly do C++ NPU inference. I usually just use python for quickly testing or benchmarking and have not revisited it since :/
