### ISSUE TITLE
Problem building: ERROR Backend 'mesonpy' is not available.

### ISSUE THREAD

**Issue by hzm74** [numpy/numpy#24709]
### Describe the issue:

Hello, i'm trying to build / compile numpy numpy-1.26.0rc1.
I downloaded the source.
I installed all the dependencies.
Then i went to the folder "numpy-1.26.0rc1" In terminal i did: `python3 -m build `

After that i got error:

```
`* Creating venv isolated environment...
* Installing packages in isolated environment... (Cython>=0.29.34,<3.1, colorama; os_name == "nt", pyproject-metadata >= 0.7.1, setuptools >= 60.0; python_version >= "3.12", tomli >= 1.0.0; python_version < "3.11")
* Getting build dependencies for sdist...

Traceback (most recent call last):
  File "/home/hvn/.local/lib/python3.10/site-packages/pyproject_hooks/_impl.py", line 321, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pyproject_hooks._impl.BackendUnavailable: Traceback (most recent call last):
  File "/home/hvn/.local/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
    obj = import_module(mod_path)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'mesonpy'

ERROR Backend 'mesonpy' is not available.`

What am i doing wrong?
Thnx in advanced.
```

### Reproduce the code example:

```python
python3 -m build
```

### Error message:

```shell
`* Creating venv isolated environment...
* Installing packages in isolated environment... (Cython>=0.29.34,<3.1, colorama; os_name == "nt", pyproject-metadata >= 0.7.1, setuptools >= 60.0; python_version >= "3.12", tomli >= 1.0.0; python_version < "3.11")
* Getting build dependencies for sdist...

Traceback (most recent call last):
  File "/home/hvn/.local/lib/python3.10/site-packages/pyproject_hooks/_impl.py", line 321, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pyproject_hooks._impl.BackendUnavailable: Traceback (most recent call last):
  File "/home/hvn/.local/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
    obj = import_module(mod_path)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'mesonpy'

ERROR Backend 'mesonpy' is not available.`
```

### Runtime information:

`* Creating venv isolated environment...
* Installing packages in isolated environment... (Cython>=0.29.34,<3.1, colorama; os_name == "nt", pyproject-metadata >= 0.7.1, setuptools >= 60.0; python_version >= "3.12", tomli >= 1.0.0; python_version < "3.11")
* Getting build dependencies for sdist...

Traceback (most recent call last):
  File "/home/hvn/.local/lib/python3.10/site-packages/pyproject_hooks/_impl.py", line 321, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pyproject_hooks._impl.BackendUnavailable: Traceback (most recent call last):
  File "/home/hvn/.local/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
    obj = import_module(mod_path)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'mesonpy'

ERROR Backend 'mesonpy' is not available.`

**Comment by hzm74** [comment]
Hello mattip. Thnx for replying.
I downloaded the source zip-file:  Source code (zip)

**Comment by mattip** [comment]
grr. It is a shame github provides that, it is broken. It does not include any of the submodules. You should either clone or download the sdist from [PyPI](https://pypi.org/project/numpy/1.26.0rc1/#files)

**Comment by hzm74** [comment]
Thnx again. Gonna try again when i cloned it.

**Comment by hzm74** [comment]
Hmm, cloned the repo with: `git clone https://github.com/numpy/numpy.git`
After that i did: `python3 -m build`
Again got error: 

```
Traceback (most recent call last):
  File "/home/hvn/.local/lib/python3.10/site-packages/pyproject_hooks/_impl.py", line 321, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pyproject_hooks._impl.BackendUnavailable: Traceback (most recent call last):
  File "/home/hvn/.local/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
    obj = import_module(mod_path)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'mesonpy'

ERROR Backend 'mesonpy' is not available.
```
