### ISSUE TITLE
Document generation in main fails due failed "cast" import.

### ISSUE THREAD

**Issue by charris** [numpy/numpy#24729]
There are a lot of failures related to missing `cast`, for example:
```
docstring of numpy.random.mtrand.RandomState.gamma:70: WARNING: Exception occurred in plotting numpy-random-gamma-1
 from /home/charris/Workspace/numpy.git/doc/source/reference/random/generated/numpy.random.gamma.rst:
Traceback (most recent call last):
  File "/usr/lib64/python3.11/site-packages/matplotlib/sphinxext/plot_directive.py", line 481, in _run_code
    exec(code, ns)
  File "<string>", line 10, in <module>
  File "/usr/lib64/python3.11/site-packages/scipy/special/__init__.py", line 671, in <module>
    from . import _orthogonal
  File "/usr/lib64/python3.11/site-packages/scipy/special/_orthogonal.py", line 81, in <module>
    from scipy import linalg
  File "/usr/lib64/python3.11/site-packages/scipy/__init__.py", line 200, in __getattr__
    return _importlib.import_module(f'scipy.{name}')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/scipy/linalg/__init__.py", line 199, in <module>
    from ._basic import *
  File "/usr/lib64/python3.11/site-packages/scipy/linalg/_basic.py", line 13, in <module>
    from ._decomp import _asarray_validated
  File "/usr/lib64/python3.11/site-packages/scipy/linalg/_decomp.py", line 23, in <module>
    from numpy import (array, isfinite, inexact, nonzero, iscomplexobj, cast,
ImportError: cannot import name 'cast' from 'numpy' (/home/charris/Workspace/numpy.git/build-install/usr/lib64/python3.11/site-packages/numpy/__init__.py)
```

That the import looks to be used in  matplotlib and scipy among others.

**Comment by charris** [comment]
@mtsokol Thoughts.

**Comment by mtsokol** [comment]
Hi @charris,

Thank you for pointing out! I also get the same errors when building docs. They occur because `scipy` version used for docs building doesn't have latest changes. For example, this specific `cast` was removed in https://github.com/scipy/scipy/commit/a0a3de34c471db175e5cf9b0e6c4cfb846e0b15c. Lastest `scipy` release doesn't have this commit yet. 

To get rid of this error we could switch to nightly build for `scipy` (I will try it locally) or we can wait for the next release.

**Comment by rgommers** [comment]
We already made that switch in CI. @charris if you install `scipy` and `matplotlib` from https://anaconda.org/scientific-python-nightly-wheels/ locally, things should work.

**Comment by charris** [comment]
> To get rid of this error we could switch to nightly build for scipy

That solved the problem. I'll close this.
