### ISSUE TITLE
BUG: numpy errors out when reading `#` symbol from `csv` file

### ISSUE THREAD

**Issue by arnabanimesh** [numpy/numpy#24790]
### Describe the issue:

Numpy can't process the `#` symbol in a `csv` file

### Reproduce the code example:

```python
import numpy as np
from tempfile import NamedTemporaryFile

csv = NamedTemporaryFile()
csv.write(u"""
A,#,B
0,0,0
""".encode("utf-8").strip())
csv.seek(0)
arr = np.loadtxt(csv,delimiter=",",dtype=object)
print(arr)
```

### Error message:

```shell
Traceback (most recent call last):
  File "D:\test\numpybug.py", line 10, in <module>
    df = np.loadtxt(csv,delimiter=",",dtype=object,encoding="utf-8")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Arnab\scoop\apps\python\current\Lib\site-packages\numpy\lib\npyio.py", line 1356, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Arnab\scoop\apps\python\current\Lib\site-packages\numpy\lib\npyio.py", line 999, in _read
    arr = _load_from_filelike(
          ^^^^^^^^^^^^^^^^^^^^
ValueError: the number of columns changed from 2 to 3 at row 2; use `usecols` to select a subset and avoid this error
```

### Runtime information:

1.24.3
3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 64 bit (AMD64)]
[{'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}},
 {'architecture': 'Haswell',
  'filepath': 'C:\\Users\\Arnab\\scoop\\persist\\python\\Lib\\site-packages\\numpy\\.libs\\libopenblas64__v0.3.21-gcc_10_3_0.dll',
  'internal_api': 'openblas',
  'num_threads': 20,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.21'}]
None

### Context for the issue:

Can't load CSV files into Numpy Arrays. Hence it is a major issue.

**Comment by kernel-loophole** [comment]
try to run this code 
```import numpy as np
from tempfile import NamedTemporaryFile

csv = NamedTemporaryFile()
csv.write(b"""
A,B,#
0,0,0
""".strip())
csv.seek(0)
arr = np.loadtxt(csv,delimiter=",",dtype=object)
print(arr)```
output
```
[['A' 'B' '']
 ['0' '0' '0']]```

**Comment by arnabanimesh** [comment]
@kernel-loophole Your code is running as expected on my system. What should I infer from this?
