### ISSUE TITLE
ImportError: dlopen failed: cannot locate symbol "PyExc_ValueError" on Android Termux

### ISSUE THREAD

**Issue by GalaxySnail** [numpy/numpy#24909]
### Steps to reproduce:

```shell
$ apt update
$ apt install libopenblas ninja patchelf cmake
$ python -m venv numpy
$ source numpy/bin/activate
(numpy) $ pip install git+https://github.com/numpy/numpy
```

### Error message:

```python
Python 3.11.6 (main, Oct  4 2023, 09:27:52) [Clang 14.0.7 (https://android.googlesource.com/toolchain/llvm-project 4c603efb0 on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/venv/numpy/lib/python3.11/site-packages/numpy/core/__init__.py", line 24, in <module>
    from . import multiarray
  File "/data/data/com.termux/files/home/venv/numpy/lib/python3.11/site-packages/numpy/core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/data/data/com.termux/files/home/venv/numpy/lib/python3.11/site-packages/numpy/core/overrides.py", line 8, in <module>
    from numpy.core._multiarray_umath import (
ImportError: dlopen failed: cannot locate symbol "PyExc_ValueError" referenced by "/data/data/com.termux/files/home/venv/numpy/lib/python3.11/site-packages/numpy/core/_multiarray_umath.cpython-311.so"...

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/home/venv/numpy/lib/python3.11/site-packages/numpy/__init__.py", line 114, in <module>
    from numpy.__config__ import show as show_config
  File "/data/data/com.termux/files/home/venv/numpy/lib/python3.11/site-packages/numpy/__config__.py", line 4, in <module>
    from numpy.core._multiarray_umath import (
  File "/data/data/com.termux/files/home/venv/numpy/lib/python3.11/site-packages/numpy/core/__init__.py", line 50, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.11 from "/data/data/com.termux/files/home/venv/numpy/bin/python"
  * The NumPy version is: "2.0.0.dev0+git20231012.86e1756"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: dlopen failed: cannot locate symbol "PyExc_ValueError" referenced by "/data/data/com.termux/files/home/venv/numpy/lib/python3.11/site-packages/numpy/core/_multiarray_umath.cpython-311.so"...


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/data/com.termux/files/home/venv/numpy/lib/python3.11/site-packages/numpy/__init__.py", line 119, in <module>
    raise ImportError(msg) from e
ImportError: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.
```

**Comment by romanovj** [comment]
you shoud build with
LDFLAGS=" -lm -lpython3.11"

**Comment by rgommers** [comment]
Thanks for the report @GalaxySnail and for the answer @romanovj. Is the missing `-lpython3.11` a known bug in CPython's support for Termux?

**Comment by romanovj** [comment]
@rgommers should be, same error with scipy and somo others modules

**Comment by rgommers** [comment]
Thanks 
> in CPython's support for Termux

I should have turned that around, given that Termux isn't officially supported by CPython say upstream issues. So, the Python install in Termux should be patching this.

**Comment by seberg** [comment]
Sounds like termux specific issue and nothing to do in NumPy, closing.
