### ISSUE TITLE
DOC: ndarray.reshape shape invalid keyword argument

### ISSUE THREAD

**Issue by enains** [numpy/numpy#24942]
### Issue with current documentation:

Currently, ` ndarray.reshape(shape, order='C')`  is the method signature for [ndarray.reshape](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.reshape.html) according to the documentation. However, with the setup described below, i get a `TypeError`.

`Python 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)] on win32`
`Type "help", "copyright", "credits" or "license" for more information.`
`>>> import numpy as np`
`>>> np.__version__`
`'1.26.1'`
`>>> anna_ray = np.arange(4)`
`>>> reshaped = anna_ray.reshape(shape=(2, 2))`
`Traceback (most recent call last):`
`  File "<stdin>", line 1, in <module>`
`TypeError: 'shape' is an invalid keyword argument for this function`

The function itself works.

`>>> reshaped = anna_ray.reshape((2, 2))`
`>>> reshaped`
`array([[0, 1],`
`       [2, 3]])`

`>>> reshaped = anna_ray.reshape(2, 2)`
`>>> reshaped`
`array([[0, 1],`
`       [2, 3]])`

Using the `order` keyword argument works when supplying the shape as a tuple or as separate int values. However,

`>>> reshaped = anna_ray.reshape(shape=(2, 2), order='F')`
`Traceback (most recent call last):`
`  File "<stdin>", line 1, in <module>`
`TypeError: function takes at most 1 keyword argument (2 given)`

gives a different type error suggesting that there is only one keyword argument.

Unfortunately I don't know where to look for the actual method signature and was unable to come up with anything using the `inspect` package.

### Idea or request for content:

Please make the documentation and the method signature consistent.

**Comment by Anianonymous** [comment]
Hey, @enains  Can you please assign this issue

**Comment by enains** [comment]
Hi @Anianonymous,
Unfortunately, I do not have permission to assign anyone.

**Comment by enains** [comment]
> @Anianonymous we don't assing issues, if there's no PR associated with it you can feel free to work on it.
> 
> In this case, however, shape is a positional argument (not a keyword argument) for this function/method (as noted [in the signature](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html)) so it works as expected. I am closing the issue but feel free to reopen if I misunderstood the problem. Cheers!

Hi @melissawm, 
you are referring to numpy.reshape (https://numpy.org/doc/stable/reference/generated/numpy.reshape.html), I am referring to numpy.ndarray.reshape. (https://numpy.org/doc/stable/reference/generated/numpy.ndarray.reshape.html)
The latter being a method of an ndarray, instead of a library function (if I am not mistaken).

The suggested ``newshape`` argument does not work either. That is because it is from a different function altogether.

Positional arguments can generally be addressed by their keyword.

**Comment by rossbar** [comment]
Yes, the `shape` parameter for the `ndarray.reshape` method behaves as if it's position-only. One simple fix would be to modify the signature in the docstring to indicate the current behavior. The behavior of the parameter could of course be changed, but that can be addressed separately.
