### ISSUE TITLE
ENH: Ensure that output of np.clip has the same dtype as the main array

### ISSUE THREAD

**Issue by mhvk** [numpy/numpy#24976]
### Proposed new feature or change:

(Discussed in https://github.com/numpy/numpy/pull/23912#discussion_r1365994920)

The function `np.clip` arguably has surprising casting behaviour:
```
a = np.arange(5, dtype='u1')
np.clip(a, -1, 3)
# OverflowError with NEP 50
np.clip(a, np.int64(-1), np.int64(3))
# array([0, 1, 2, 3, 3])  
# int64 dtype with NEP 50
# (before NEP 50, both examples gave int16)
```
I would naively have expected for the output dtype to always be the same as the input one. That this does not happen is because internally `np.clip` calls a ufunc: https://github.com/numpy/numpy/blob/d885b0b546cbe2ab8401622c8d4db984ec5ea31b/numpy/_core/_methods.py#L92-L101
and these treat the arguments symmetrically.

It is possible to get the output dtype by setting `out` or `dtype`, but in the current implementation that still gives either the `OverflowError` or casting errors:
```
np.clip(a, np.int64(-1), np.int64(3), out=a)  # or dtype=a.dtype
# UFuncTypeError: Cannot cast ufunc 'clip' output from dtype('int64') to dtype('uint8') with casting rule 'same_kind'
```
adding `casting="unsafe"` gives the wrong answer, because `-1` becomes `255`.

I think it should be possible to make the `np.clip` function (probably not the `ufunc`) cast the `min` and `max` to `a.dtype`, but ensure that the valid ranges are respected (i.e., negative integers would become 0 if the dtype is unsigned). This would be similar to what was done in #24915, i.e., ideally we have the behaviour of `np.clip` be identical to
```
min = -1
max = 3
out = a.copy()
out[a<min] = min
out[a>max] = max
return out
```
(which still gives an out-of-bound error for `min=-1` because of `__setitem__`, but works for `min=np.int64(-1)`)

But perhaps this is more work than is warranted.

**Comment by asmeurer** [comment]
This is also what we decided for the array API https://data-apis.org/array-api/latest/API_specification/generated/array_api.clip.html#clip

But I'm a little unclear what the ideal behavior should when the min or max has a higher range than the input. Consider

```py
>>> np.clip(np.asarray(0, dtype=np.int8), np.asarray(128, dtype=np.int16), None)
128
```

the result is a (promoted) int16. If we downcast the result back to int8, we get `-128`:

```py
>>> np.clip(np.asarray(0, dtype=np.int8), np.asarray(128, dtype=np.int16), None).astype(np.int8)
-128
```

This is also what happens with the suggested `out[a<min] = min` behavior:

```py
>>> a, min = np.asarray(0, dtype=np.int8), np.asarray(128, dtype=np.int16)
>>> out = a.copy()
>>> out[a<min] = min
>>> out
array(-128, dtype=int8)
```

Should this be considered the correct answer, or should clip avoid wrapping and instead clip, as it were, large values to `iinfo(dtype).max`?

For floats, downcasting just overflows to +/- inf, which is probably what you would want. 

Or should we reconsider the decision in the array API, and the suggestion here, to make `clip` not perform type promotion?

**Comment by mhvk** [comment]
@asmeurer - ah, never thought about the case when the minimum is larger than the largest value one can express... It might not be crazy to just error on that case...

Though perhaps we are overthinking it, and should try to fix just the python min/max weak promotion case. For that case, raising an error would be consistent with setting analogy, since that should eventually error too, at least according to the deprecation warning that is currently raised when setting an array element with an out-of-bound integer:
```
DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 256 to uint8 will fail in the future.
```

Maybe it is OK to use regular ufunc promotion when `min, max` have different `dtype` (or at least we can punt...).

**Comment by asmeurer** [comment]
Oh I see, that warning (now actually an error in NumPy 2.0) comes from setting an array with an out-of-bounds Python `int`. That's a very different thing that downcasting an array with a higher precision integer dtype. I expect that sort of thing is done all the time and isn't something NumPy would want to deprecate.

**Comment by mhvk** [comment]
Yes, indeed, it is just python integers that are treated differently, and I wondered if the easiest solution would be to extend that to `np.clip`. It seems fairly reasonable to just change dtype if one passes in multiple arrays -- e.g., `np.clip(input_u1, min_i2, max_i2)` -- and then by analogy we should do the same thing for numpy scalars.

p.s. Note that this is different from what I suggested on top!

**Comment by asmeurer** [comment]
FWIW, we decided to make this behavior unspecified in the standard. https://github.com/data-apis/array-api/pull/814

**Comment by jni** [comment]
I just want to add a voice to this thread that `np.clip` as currently implemented (numpy 2.0.0) is quite hard to use:

```
>>> np.clip(np.array([0, 255], dtype=np.uint8), 0, 4550)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jni/micromamba/envs/np2/lib/python3.12/site-packages/numpy/_core/fromnumeric.py", line 2247, in clip
    return _wrapfunc(a, 'clip', a_min, a_max, out=out, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jni/micromamba/envs/np2/lib/python3.12/site-packages/numpy/_core/fromnumeric.py", line 57, in _wrapfunc
    return bound(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/jni/micromamba/envs/np2/lib/python3.12/site-packages/numpy/_core/_methods.py", line 108, in _clip
    return um.clip(a, min, max, out=out, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OverflowError: Python integer 4550 out of bounds for uint8
```

I think most users in this scenario would expect to be able to use arrays of *any* type and Python ints and just have it work — there is nothing unsatisfiable about this expression, including keeping the input dtype.

When you start dealing with numpy scalars and so on, the story is indeed more complicated as noted in the above discussion, but the Python int scenario seems like an easy fix (as noted by @mhvk [above](https://github.com/numpy/numpy/issues/24976#issuecomment-2162171196)) that would unlock a lot of uses already.

Sorry about the noise, I expect there will be lots in this repo this coming week. 😅 Thank you all! 🙏

**Comment by asmeurer** [comment]
With the non-promoting behavior one should also be aware that you might not actually have `min <= x <= max` when `min` or `max` are float64 and `x` is float32, because of rounding in the downcast:

```py
>>> np.clip(np.asarray([0.0], dtype=np.float32), np.asarray([4.0311033624323596e-209], dtype=np.float64), np.asarray([1.0], dtype=np.float64))
array([4.03110336e-209])
>>> _.astype(np.float32)
array([0.], dtype=float32)
```

That's underflow, but the rounding could work against you in virtually any case

```py
>>> x = np.asarray([1.0], dtype=np.float32)
>>> min = np.asarray([1.00000001], dtype=np.float64)
>>> max = np.asarray([2.0], dtype=np.float64)
>>> np.clip(x, min, max).astype(np.float32)
array([1.], dtype=float32)
>>> min <= _
array([False])
```

Tbh, I'm starting to think this whole proposal is a bad idea and putting it in the standard was a mistake. Not type promoting implies downcasting, which just leads too many weird behaviors. But if we decide to keep it in the array API and change NumPy, we should figure out reasonable behavior for ints and document the float behavior.

**Comment by jni** [comment]
I don't find those examples that bad tbh. The test is not whether they are smaller than min, it is whether they are smaller than the clipped-and-rounded min. Just like I shouldn't be surprised that `0.1 + 0.2 <= 0.3` evaluates to `False`, I should not surprised by those edge cases. The only situation where I think clip should fail to do anything is when the min and max are both outside the range of the array dtype limits. ie `np.clip(np.array([9], dtype=np.uint8), 400, 500)` should be an error.

**Comment by asmeurer** [comment]
Well note that you don't get this issue at all (rounding or integer overflow) if you just do type promotion. The original argument here is that type promotion on x is surprising, but for me this shows why it is necessary. The whole point of type promotion in general is that functions can produce a result that fits within the bounds of both input dtypes.

**Comment by mhvk** [comment]
> Well note that you don't get this issue at all (rounding or integer overflow) if you just do type promotion. The original argument here is that type promotion on x is surprising, but for me this shows why it is necessary. The whole point of type promotion in general is that functions can produce a result that fits within the bounds of both input dtypes.

I think I've gotten convinced about that too - I think the actionable part of this really just is to treat python ints specially (as we do for comparisons).

**Comment by asmeurer** [comment]
Another corner case I just discovered: `clip` promotes `uint64` to `float64` (I thought uint64 -> float promotion was removed in NumPy 2.0).

```py
>>> np.clip(np.asarray(0, dtype=np.uint64), np.asarray(0), None)
np.float64(0.0)
```

**Comment by fancidev** [comment]
FWIW, in https://github.com/data-apis/array-api/pull/814#issuecomment-2430366279 I proposed the following semantics for `clip`:

> Let T be the data type of x. If there exists a value in T that is greater than or equal to min and less than or equal to max, then clip(x, min, max) returns (1) the smallest element in T that is greater than or equal to min if x < min, (2) the largest element in T that is less than or equal to max if x > max, or (3) x otherwise.
>
> In math notation, this becomes
>
> $$
> \mathrm{clip}(x,a,b):= {\arg\min}_{ t \in T\cap [a,b]} | t-x |
> $$

I think this definition is general enough to account for most (all?) corner cases of inputs. It is implementable for built-in types by first “snapping” the bounds to a representable value in T “in the right direction” and then doing the obvious min(max(…)) thing. For custom numeric types 
such as Decimal or Fraction, could just throw an error.

**Comment by jni** [comment]
Thanks @fancidev! That matches my intuition as well. Indeed, when $T \cap [a, b]$ is empty, the expression is undefined, right? ie it should raise an error, as [I proposed above](https://github.com/numpy/numpy/issues/24976#issuecomment-2195907158)?

**Comment by fancidev** [comment]
> when T ∩ [ a , b ] is empty, the expression is undefined, right?

Yes I think so.

> ie it should raise an error, as [I proposed above](https://github.com/numpy/numpy/issues/24976#issuecomment-2195907158)?

The behavior in that case could be tricky because numpy supports broadcasting of the arguments. What if some bounds are invalid and some are valid? Should it raise an error so that no result is produced at all? Or should it return `nan` (for floating point types) for those bounds that are invalid? How about integers, which don’t have a `nan`? Probably raising an error would be best.

**Comment by asmeurer** [comment]
clip has the following note:

```
    Notes
    -----
    When `a_min` is greater than `a_max`, `clip` returns an
    array in which all values are equal to `a_max`,
    as shown in the second example.
```

b < a is a special-case of T ∩ [a, b] being empty.

**Comment by fancidev** [comment]
> b < a is a special-case of T ∩ [a, b] being empty.

Indeed, and that’s a useful hint. The C++17 standard for [std::clamp](https://en.cppreference.com/w/cpp/algorithm/clamp) contains a similar note:

> If lo is greater than hi, the behavior is undefined.

A subtle difference is that in C++, v, lo, hi have the same type, so the above remark is *exhaustive* for undefined behavior. This is also the case as long as numpy performs type promotion. If numpy does not perform type promotion, then the remark becomes non-exhaustive (and thus a “special case”).

**Comment by peanutfun** [comment]
I think the docs do not make clear that the returned output might have promoted data types. The link to "Output Type Determination" does not help. I get the following confusing behavior:
```python
>>> arr = np.array([1.0, 2.0], dtype=np.float32)
>>> np.clip(arr, 1.5, 2).dtype  # Compare against scalar float, int
dtype('float32')
>>> np.clip(arr, np.array([1.5]), 1.9).dtype  # Compare against float64
dtype('float64')
>>> np.clip(arr, np.array([1]), 1.9).dtype  # Compare against int64
dtype('float64')
```
