### ISSUE TITLE
BUG: Diagonal Assigning and np.array_split's Weird Behavior on lists

### ISSUE THREAD

**Issue by Bug-Find** [numpy/numpy#25096]
### Describe the issue:

There are two groups of issues.
1. np.fill_diagonal, np.diag, and np.diagonal can cause unexpected value assigning when flipping diagonals. 

An important underlying behavior about the underlying code of np.fill_diagonal should be as I interpret in the example below:
In a wrong flipping of the diagonal of the array:
[[0, 1]
 [2, 3]],
the underlying code of numpy first assigns the value 3 to the top-left corner of the array. Then the underlying code treats the top-left corner has the value 3 rather than the original value 0 and assign 3 to the bottom-right of the array.

But if use the subscript of array instead of np.fill_diagonal, the behavior looks to be different, as in the last example in the first code group below.

2. The document of np.array_split doesn't say that the np.split doesn't allows lists, whereas np.array_split allows lists and has weird behavior on some lists.

### Reproduce the code example:

```python
# the first code group
import numpy as np
np.__version__
a = np.arange(4).reshape(2, 2)
arr = a.copy()
arr
np.fill_diagonal(arr, np.flip(np.diag(arr.copy()))) # a correct flip
arr
arr = a.copy()
arr
np.fill_diagonal(arr, np.flip(np.diag(arr))) # has a bug
arr
# If use np.diagonal instead of np.diag in the above, the result will be the same.
arr = a.copy()
arr
np.fill_diagonal(arr, np.flip(np.diagonal(arr)))
arr
# Another example on a 5 by 5 matrix
a = np.diag([1,2,3,4,5])
arr = np.fliplr(a.copy())
# a correct assigning similar to a way of assigning anti-diagonal by np.fliplr that is showed near the end of the document of np.fill_diagonal
np.fill_diagonal(np.fliplr(arr), np.diag(np.flip(np.fliplr(arr.copy()))))
arr
arr = np.fliplr(a.copy())
arr
np.fill_diagonal(np.fliplr(arr), np.diag(np.flip(np.fliplr(arr)))) # has a bug
arr
arr = np.fliplr(a.copy())
np.fill_diagonal(np.fliplr(arr), np.diagonal(np.flip(np.fliplr(arr)))) # has a bug
arr
# A similar bug on Assigning
arr = np.fliplr(a.copy())
idx = np.arange(arr.shape[0])
idx
arr[-idx-1, idx] = np.diag(np.fliplr(arr.copy())) # a correct flip
arr
arr = np.fliplr(a.copy())
arr
arr[-idx-1, idx] = np.diag(np.fliplr(arr)) # bug
arr
arr = np.fliplr(a.copy())
arr[-idx-1, idx] = np.diagonal(np.fliplr(arr)) # bug
arr

# the second code group
List = [range(4), range(4)]
np.array_split(List, 2, axis=1)
List = [[0,1,2,3], [0,1,2,3]]
np.array_split(List, 2, axis=1)
np.split(List, 2, axis=1) # as the document of np.split says, the first positional argument should be ndarray, so this code will cause error, but the error message doesn't tell users to use ndarray
import sys, numpy; print(numpy.__version__); print(sys.version)
print(numpy.show_runtime())
```

### Error message:

```shell
Traceback (most recent call last):
  File "D:\Lib\site-packages\numpy\lib\shape_base.py", line 859, in split
    len(indices_or_sections)
TypeError: object of type 'int' has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<pyshell#52>", line 1, in <module>
    np.split(List, 2, axis=1) # as the document of np.split says, the first positional argument should be ndarray, so this code will cause error, but the error message doesn't tell users to use ndarray
  File "D:\Lib\site-packages\numpy\lib\shape_base.py", line 862, in split
    N = ary.shape[axis]
AttributeError: 'list' object has no attribute 'shape'
```

### Runtime information:

1.25.2
3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 64 bit (AMD64)]
[{'numpy_version': '1.25.2',
  'python': '3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 '
            '64 bit (AMD64)]',
  'uname': uname_result(system='Windows', node='LAPTOP-G4EA37VA', release='10', version='10.0.22621', machine='AMD64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}},
 {'architecture': 'Zen',
  'filepath': 'D:\\Lib\\site-packages\\numpy\\.libs\\libopenblas64__v0.3.23-246-g3d31191b-gcc_10_3_0.dll',
  'internal_api': 'openblas',
  'num_threads': 12,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.23.dev'}]
None

**Comment by rgommers** [comment]
> In a wrong flipping of the diagonal of the array:

This bug report is invalid. You are using aliased memory here, the second input to your `fill_diagonal` call contains a view on the first array:
```python
>>> a = np.arange(4).reshape(2, 2)
>>> ix = np.flip(np.diagonal(a))
>>> ix
array([3, 0])
>>> ix.base
array([0, 1, 2, 3])
>>> np.fill_diagonal(a, ix)
>>> a
array([[3, 1],
       [2, 3]])
```

That clearly will not give the answer you want - just don't do that.

* * *

The `np.split` one can be reduced down to:
```python
>>> np.split([1, 2, 3], [1])
[array([1]), array([2, 3])]
>>> np.split([1, 2, 3], 1)
...
TypeError: object of type 'int' has no len()

During handling of the above exception, another exception occurred:
...
  File ~/code/numpy/build-install/usr/lib/python3.9/site-packages/numpy/lib/_shape_base_impl.py:878 in split
    N = ary.shape[axis]
AttributeError: 'list' object has no attribute 'shape'
```

That could use a fix indeed, the code is not handling array-likes well.

**Comment by seberg** [comment]
> This bug report is invalid.

I would say it is very much a valid bug.  `arr.flat` assignments don't protect users from aliased memory and aliased memory is a bit tricky in either case that is true.

But, almost all of NumPy *does* protect from it.  And any place like this, which doesn't should be fixed in principle)

**Comment by rgommers** [comment]
> But, almost all of NumPy _does_ protect from it. And any place like this, which doesn't should be fixed in principle.

In general I don't think that is possible to do reliably? Is it a check only for `.base`, or something else?

**Comment by seberg** [comment]
Pauli implemented a reliable solution many years ago, it is exposed in Python as `np.may_share_memory`.  Of course you are right.  In practice you do have to give up at some point and assume the arrays may have overlapping memory.

We use this in ufuncs and I think at least most indexing paths.  So at least for that part, I think it would be a good improvement (and maybe a small bug, because we do overlap detection in most places).
