### ISSUE TITLE
BUG: OMP_NUM_THREADS affect matrix dot operator result

### ISSUE THREAD

**Issue by AndrewTsao** [numpy/numpy#25100]
### Describe the issue:

numpy from version 1.19.3 onwards, if OMP_NUM_THREADS=1 is set, the matrix dot result will be inconsistent with the result when the environment variable is not set. My python environment, numpy's related configuration are as follows.

### Reproduce the code example:

```python
import os
import sys

if len(sys.argv) == 1:
    import numpy as np
    from pandas import DataFrame
    print(np.__config__.show())

    a = np.random.rand(80, 80)
    b = np.random.rand(80, 3500)
    np.save("a.npy", a)
    np.save("b.npy", b)

    c1 = a.dot(b)
    np.save("c.npy", c1)

    print("generate a, b, c, and save to a.npy, b.npy, c.npy")
    print("pass argument, limit numpy cpus: python test-dot.py 1")
else:
    N = sys.argv[1]
    print("limit numpy to use one CPU: ", N)
    os.environ["OMP_NUM_THREADS"] = N
    os.environ["OPENBLAS_NUM_THREADS"] = N
    os.environ["MKL_NUM_THREADS"] = N
    os.environ["VECLIB_MAXIMUM_THREADS"] = N
    os.environ["NUMEXPR_NUM_THREADS"] = N
    import numpy as np
    from pandas import DataFrame
    print("numpy version:", np.__version__)

    a = np.load("a.npy")
    b = np.load("b.npy")
    c1 = a.dot(b)
    c = np.load("c.npy")
    print("different elements number:", np.sum(c != c1))
    np.testing.assert_equal(c, c1)
```

### Error message:

```shell
(py38) [andi@hpc-comp01 ldb-test]$ python test-dot.py
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE41,POPCNT,SSE42,AVX,F16C,FMA3,AVX2,AVX512F,AVX512CD,AVX512_SKX,AVX512_CLX,AVX512_CNL,AVX512_ICL
    not found = AVX512_KNL,AVX512_KNM
None
generate a, b, c, and save to a.npy, b.npy, c.npy
pass argument, limit numpy cpus: python test-dot.py 1
(py38) [andi@hpc-comp01 ldb-test]$ python test-dot.py 1
limit numpy to use one CPU:  1
numpy version: 1.24.4
different elements number: 217
Traceback (most recent call last):
  File "test-dot.py", line 36, in <module>
    np.testing.assert_equal(c, c1)
  File "/home/andi/py38/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 349, in assert_equal
    return assert_array_equal(actual, desired, err_msg, verbose)
  File "/home/andi/py38/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 985, in assert_array_equal
    assert_array_compare(operator.__eq__, x, y, err_msg=err_msg,
  File "/opt/Miniconda3-3.8/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/andi/py38/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 862, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Arrays are not equal

Mismatched elements: 217 / 280000 (0.0775%)
Max absolute difference: 1.77635684e-14
Max relative difference: 9.09067129e-16
 x: array([[17.635934, 18.602557, 17.788588, ..., 18.814077, 18.096197,
        18.039201],
       [18.699419, 19.489279, 18.421037, ..., 17.458583, 20.294183,...
 y: array([[17.635934, 18.602557, 17.788588, ..., 18.814077, 18.096197,
        18.039201],
       [18.699419, 19.489279, 18.421037, ..., 17.458583, 20.294183,...
```

### Runtime information:

Python 3.8.5 (default, Sep  4 2020, 07:30:14)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> print(numpy.show_runtime())
[{'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2',
                                'AVX512F',
                                'AVX512CD',
                                'AVX512_SKX',
                                'AVX512_CLX',
                                'AVX512_CNL',
                                'AVX512_ICL'],
                      'not_found': ['AVX512_KNL', 'AVX512_KNM']}},
 {'architecture': 'Cooperlake',
  'filepath': '/home/caosw/py38/lib/python3.8/site-packages/numpy.libs/libopenblas64_p-r0-15028c96.3.21.so',
  'internal_api': 'openblas',
  'num_threads': 64,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.21'}]
None

**Comment by ngoldbaum** [comment]
This uses 1.24.4 - can you try again using 1.26? Are you installing OpenBLAS and building NumPy yourself or are you getting numpy and OpenBLAS from a wheel, anacaonda package, or system package manager?

**Comment by seberg** [comment]
Seems like nothing to see here, the errors sound like they are within numerically reasonable range.  No blas implementation attempts to guarantee consistent results across systems/settings.

If the errors seem more than numerical limits, that would be a bug, inconsistency may be annoying, but not a bug.
