### ISSUE TITLE
ImportError: Error importing numpy from its source directory

### ISSUE THREAD

**Issue by dangdinh17** [numpy/numpy#25125]
### Steps to reproduce:

I have used the older vesrion of pycharm and 3.11 of python console for my reccent project, but after i reinstalled my laptop win for some reasons and i also reinstalled newest version  for pycharm and python, but i cant not run any projects i've done before. thank you for helping me

### Error message:

```shell
Traceback (most recent call last):
  File "T:\university course\ai\project\venv\Lib\site-packages\numpy\core\__init__.py", line 24, in <module>
    from . import multiarray
  File "T:\university course\ai\project\venv\Lib\site-packages\numpy\core\multiarray.py", line 10, in <module>
    from . import overrides
  File "T:\university course\ai\project\venv\Lib\site-packages\numpy\core\overrides.py", line 8, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "T:\university course\ai\project\venv\Lib\site-packages\numpy\__init__.py", line 158, in <module>
    from numpy.__config__ import show as show_config
  File "T:\university course\ai\project\venv\Lib\site-packages\numpy\__config__.py", line 4, in <module>
    from numpy.core._multiarray_umath import (
  File "T:\university course\ai\project\venv\Lib\site-packages\numpy\core\__init__.py", line 50, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.12 from "T:\university course\ai\project\venv\Scripts\python.exe"
  * The NumPy version is: "1.26.1"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "T:\university course\ai\project\machinelearning\models.py", line 1, in <module>
    import nn
  File "T:\university course\ai\project\machinelearning\nn.py", line 1, in <module>
    import numpy as np
  File "T:\university course\ai\project\venv\Lib\site-packages\numpy\__init__.py", line 163, in <module>
    raise ImportError(msg) from e
ImportError: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.
```

**Comment by ngoldbaum** [comment]
When you update your python stack you also need to update all of your packages, including numpy.

**Comment by ngoldbaum** [comment]
In particular, I suspect you’re trying to import the numpy you had for an older version of python in python 3.11. This will not work.
