### ISSUE TITLE
OpenBSD/amd64 7.4 undefined symbols during the import

### ISSUE THREAD

**Issue by DavidAlphaFox** [numpy/numpy#25180]
### Steps to reproduce:

in the python's repl
import numpy

### Error message:

```shell
Python 3.10.13 (main, Oct  5 2023, 16:21:31) [Clang 13.0.0 ] on openbsd7
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'sscal_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'sswap_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'scopy_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'zhemm_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'izamax_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'zaxpy_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'isamax_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'snrm2_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'ssyr_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'sger_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'dsyr2k_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'zdscal_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'zgerc_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'zgeru_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'dgemm_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'dcopy_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'ztrsm_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'zgemm_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'zscal_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'ztpmv_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'zcopy_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'zswap_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'zgemv_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'dscal_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'ccopy_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'dswap_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'ddot_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'daxpy_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'idamax_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'ctrsm_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'cherk_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'cgemm_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'dtbsv_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'dgemv_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'dger_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'sgemv_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'saxpy_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'ztpsv_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'csscal_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'cher_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'drot_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'cscal_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'cswap_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'chpr_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'icamax_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'ztrmm_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'zher_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'zhpr_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'zdotc_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'sdot_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'ctrmm_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'sspmv_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'zdrot_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'ctbmv_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'caxpy_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'ctbsv_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'ztrmv_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'cdotc_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'cgemv_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'cgerc_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'ctrmv_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'strmm_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'chemm_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'cher2k_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'dzasum_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'chemv_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'cher2_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'dznrm2_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'zdotu_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'cgeru_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'dtrmm_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'dsyrk_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'strsm_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'dnrm2_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'sgemm_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'srot_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'dtrmv_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'zhpmv_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'dsyr_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'ssyr2k_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'ssyrk_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'ctpsv_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'ctpmv_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'dspmv_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'stpmv_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'stpsv_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'ssymv_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'sspr2_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'dtrsm_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'scasum_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'dtrsv_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'scnrm2_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'dasum_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'sspr_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'zher2k_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'dsymv_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'dtpmv_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'dtpsv_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'zgbmv_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'ssyr2_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'dsyr2_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'strmv_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'zhpr2_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'ztbmv_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'ztbsv_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'chbmv_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'csrot_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'zhemv_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'ztrsv_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'ctrsv_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'cdotu_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'ssbmv_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'dsymm_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'chpmv_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'dspr_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'ssymm_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'srotm_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'sasum_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'zherk_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'chpr2_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'drotm_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'zher2_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'dspr2_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'dgbmv_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'zhbmv_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'stbmv_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'stbsv_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'strsv_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'dtbmv_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'dsbmv_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'cgbmv_'
python:/usr/local/lib/liblapack.so.7.1: undefined symbol 'sgbmv_'
python:/home/david/.local/lib/python3.10/site-packages/numpy/linalg/_umath_linalg.cpython-310.so: undefined symbol 'scopy_'
python:/home/david/.local/lib/python3.10/site-packages/numpy/linalg/_umath_linalg.cpython-310.so: undefined symbol 'dcopy_'
python:/home/david/.local/lib/python3.10/site-packages/numpy/linalg/_umath_linalg.cpython-310.so: undefined symbol 'ccopy_'
python:/home/david/.local/lib/python3.10/site-packages/numpy/linalg/_umath_linalg.cpython-310.so: undefined symbol 'zcopy_'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/david/.local/lib/python3.10/site-packages/numpy/__init__.py", line 149, in <module>
    from . import lib
  File "/home/david/.local/lib/python3.10/site-packages/numpy/lib/__init__.py", line 23, in <module>
    from . import index_tricks
  File "/home/david/.local/lib/python3.10/site-packages/numpy/lib/index_tricks.py", line 12, in <module>
    import numpy.matrixlib as matrixlib
  File "/home/david/.local/lib/python3.10/site-packages/numpy/matrixlib/__init__.py", line 4, in <module>
    from . import defmatrix
  File "/home/david/.local/lib/python3.10/site-packages/numpy/matrixlib/defmatrix.py", line 12, in <module>
    from numpy.linalg import matrix_power
  File "/home/david/.local/lib/python3.10/site-packages/numpy/linalg/__init__.py", line 73, in <module>
    from . import linalg
  File "/home/david/.local/lib/python3.10/site-packages/numpy/linalg/linalg.py", line 35, in <module>
    from numpy.linalg import _umath_linalg
ImportError: Cannot load specified object
```

**Comment by seberg** [comment]
How did you install NumPy and the liblapack there?  Which NumPy version is this?

There is something wrong with your linking and liblapack, although if you build from scratch numpy should maybe have build a bad fallback version instead of this happening.

**Comment by DavidAlphaFox** [comment]
@seberg 
I use the pkg_add lapack and pip install numpy.
The numpy's version is 1.26.2.
