### ISSUE TITLE
Error "numpy" hasn't attribute "short"

### ISSUE THREAD

**Issue by alawamy** [numpy/numpy#25265]
### Steps to reproduce:

import openpyxl
import numpy
print(f"openpyxl version: {openpyxl.__version__}")
print(f"numpy version: {numpy.__version__}")

### Error message:

```shell
Traceback (most recent call last):
  File "C:\Users\hp\PycharmProjects\pythonProject9\venv\Plant Reports\Test Numpy.py", line 1, in <module>
    import openpyxl
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\openpyxl\__init__.py", line 4, in <module>
    from openpyxl.compat.numbers import NUTraceback (most recent call last):
  File "C:\Users\hp\PycharmProjects\pythonProject9\venv\Plant Reports\Test Numpy.py", line 1, in <module>
    import openpyxl
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\openpyxl\__init__.py", line 4, in <module>
    from openpyxl.compat.numbers import NUMPY
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\openpyxl\compat\__init__.py", line 3, in <module>
    from .numbers import NUMERIC_TYPES
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\openpyxl\compat\numbers.py", line 16, in <module>
    NUMERIC_TYPES = NUMERIC_TYPES + (numpy.short,
                                     ^^^^^^^^^^^
AttributeError: module 'numpy' has no attribute 'short'MPY
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\openpyxl\compat\__init__.py", line 3, in <module>
    from .numbers import NUMERIC_TYPES
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\openpyxl\compat\numbers.py", line 16, in <module>
    NUMERIC_TYPES = NUMERIC_TYPES + (numpy.short,
                                     ^^^^^^^^^^^
AttributeError: module 'numpy' has no attribute 'short'
```

**Comment by ngoldbaum** [comment]
We'll need a lot more information to help. This is likely unrelated to openpyxl, a script just doing `import numpy; numpy.short` would error in the same way.

Please tell us how you installed numpy and what numpy version you're using.

**Comment by seberg** [comment]
Closing, feel free to post updates and maybe someone has a hint.  But this is exceedingly unlikely to be a NumPy issue.  To some degree, hopefully your install is just very broken and a clean reinstal of NumPy (or maybe the whole stack) helps.

If `import numpy; numpy.short` fails in a plain Python shell ideally, not something fancy like ipython notebook or an IDE.  Then you know the install is broken.  If it doesn't fail, then you should maybe try upgrading `openpyxl` and its dependencies.
E.g. once upon a time there was a Cython issue that when the stars aligned in odd ways could lead to mutating namespaces randomly, although I wouldn't say it is likely that this is the thing going on here...

**Comment by bwiggs** [comment]
Same error with python installed via homebrew on my mac. Even the simple example given above `import numpy; numpy.short` wasnt working.

I finally remembered to run `brew doctor` which showed that numpy was unlinked. Once I linked it, the error went away. HTH
