### ISSUE TITLE
BUG: a meson bug for win11

### ISSUE THREAD

**Issue by clonne** [numpy/numpy#25506]
### Describe the issue:

for installing numpy
i see an message 'This is a Meson bug and should be reported!' from error-report

### Reproduce the code example:

```python
pip install numpy
```

### Error message:

```shell
error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 2
  ╰─> [185 lines of output]
      + C:\Program Files\Python313\python.exe C:\Users\clonn\AppData\Local\Temp\pip-install-8iam03wf\numpy_c997373bbbaf43a0ae4ebe88af9f880c\vendored-meson\meson\meson.py setup C:\Users\clonn\AppData\Local\Temp\pip-install-8iam03wf\numpy_c997373bbbaf43a0ae4ebe88af9f880c C:\Users\clonn\AppData\Local\Temp\pip-install-8iam03wf\numpy_c997373bbbaf43a0ae4ebe88af9f880c\.mesonpy-b0uebtvb\build -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=C:\Users\clonn\AppData\Local\Temp\pip-install-8iam03wf\numpy_c997373bbbaf43a0ae4ebe88af9f880c\.mesonpy-b0uebtvb\build\meson-python-native-file.ini
      Traceback (most recent call last):
        File "C:\Users\clonn\AppData\Local\Temp\pip-install-8iam03wf\numpy_c997373bbbaf43a0ae4ebe88af9f880c\vendored-meson\meson\mesonbuild\mesonmain.py", line 194, in run
          return options.run_func(options)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\clonn\AppData\Local\Temp\pip-install-8iam03wf\numpy_c997373bbbaf43a0ae4ebe88af9f880c\vendored-meson\meson\mesonbuild\msetup.py", line 358, in run
          app.generate()
        File "C:\Users\clonn\AppData\Local\Temp\pip-install-8iam03wf\numpy_c997373bbbaf43a0ae4ebe88af9f880c\vendored-meson\meson\mesonbuild\msetup.py", line 183, in generate
          return self._generate(env, capture, vslite_ctx)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\clonn\AppData\Local\Temp\pip-install-8iam03wf\numpy_c997373bbbaf43a0ae4ebe88af9f880c\vendored-meson\meson\mesonbuild\msetup.py", line 228, in _generate
          intr.run()
        File "C:\Users\clonn\AppData\Local\Temp\pip-install-8iam03wf\numpy_c997373bbbaf43a0ae4ebe88af9f880c\vendored-meson\meson\mesonbuild\interpreter\interpreter.py", line 3002, in run
          super().run()
        File "C:\Users\clonn\AppData\Local\Temp\pip-install-8iam03wf\numpy_c997373bbbaf43a0ae4ebe88af9f880c\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 164, in run
          self.evaluate_codeblock(self.ast, start=1)
        File "C:\Users\clonn\AppData\Local\Temp\pip-install-8iam03wf\numpy_c997373bbbaf43a0ae4ebe88af9f880c\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 190, in evaluate_codeblock
          raise e
        File "C:\Users\clonn\AppData\Local\Temp\pip-install-8iam03wf\numpy_c997373bbbaf43a0ae4ebe88af9f880c\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 182, in evaluate_codeblock
          self.evaluate_statement(cur)
        File "C:\Users\clonn\AppData\Local\Temp\pip-install-8iam03wf\numpy_c997373bbbaf43a0ae4ebe88af9f880c\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 196, in evaluate_statement
          return self.function_call(cur)
                 ^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\clonn\AppData\Local\Temp\pip-install-8iam03wf\numpy_c997373bbbaf43a0ae4ebe88af9f880c\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 521, in function_call
          res = func(node, func_args, kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\clonn\AppData\Local\Temp\pip-install-8iam03wf\numpy_c997373bbbaf43a0ae4ebe88af9f880c\vendored-meson\meson\mesonbuild\interpreterbase\decorators.py", line 277, in wrapper
          return f(*nargs, **wrapped_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\clonn\AppData\Local\Temp\pip-install-8iam03wf\numpy_c997373bbbaf43a0ae4ebe88af9f880c\vendored-meson\meson\mesonbuild\interpreterbase\decorators.py", line 596, in wrapper
          return f(*wrapped_args, **wrapped_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\clonn\AppData\Local\Temp\pip-install-8iam03wf\numpy_c997373bbbaf43a0ae4ebe88af9f880c\vendored-meson\meson\mesonbuild\interpreter\interpreter.py", line 2414, in func_subdir
          self.evaluate_codeblock(codeblock)
        File "C:\Users\clonn\AppData\Local\Temp\pip-install-8iam03wf\numpy_c997373bbbaf43a0ae4ebe88af9f880c\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 190, in evaluate_codeblock
          raise e
        File "C:\Users\clonn\AppData\Local\Temp\pip-install-8iam03wf\numpy_c997373bbbaf43a0ae4ebe88af9f880c\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 182, in evaluate_codeblock
          self.evaluate_statement(cur)
        File "C:\Users\clonn\AppData\Local\Temp\pip-install-8iam03wf\numpy_c997373bbbaf43a0ae4ebe88af9f880c\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 206, in evaluate_statement
          return self.evaluate_if(cur)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\clonn\AppData\Local\Temp\pip-install-8iam03wf\numpy_c997373bbbaf43a0ae4ebe88af9f880c\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 301, in evaluate_if
          self.evaluate_codeblock(i.block)
        File "C:\Users\clonn\AppData\Local\Temp\pip-install-8iam03wf\numpy_c997373bbbaf43a0ae4ebe88af9f880c\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 190, in evaluate_codeblock
          raise e
        File "C:\Users\clonn\AppData\Local\Temp\pip-install-8iam03wf\numpy_c997373bbbaf43a0ae4ebe88af9f880c\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 182, in evaluate_codeblock
          self.evaluate_statement(cur)
        File "C:\Users\clonn\AppData\Local\Temp\pip-install-8iam03wf\numpy_c997373bbbaf43a0ae4ebe88af9f880c\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 228, in evaluate_statement
          self.evaluate_foreach(cur)
        File "C:\Users\clonn\AppData\Local\Temp\pip-install-8iam03wf\numpy_c997373bbbaf43a0ae4ebe88af9f880c\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 472, in evaluate_foreach
          self.evaluate_codeblock(node.block)
        File "C:\Users\clonn\AppData\Local\Temp\pip-install-8iam03wf\numpy_c997373bbbaf43a0ae4ebe88af9f880c\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 190, in evaluate_codeblock
          raise e
        File "C:\Users\clonn\AppData\Local\Temp\pip-install-8iam03wf\numpy_c997373bbbaf43a0ae4ebe88af9f880c\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 182, in evaluate_codeblock
          self.evaluate_statement(cur)
        File "C:\Users\clonn\AppData\Local\Temp\pip-install-8iam03wf\numpy_c997373bbbaf43a0ae4ebe88af9f880c\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 206, in evaluate_statement
          return self.evaluate_if(cur)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\clonn\AppData\Local\Temp\pip-install-8iam03wf\numpy_c997373bbbaf43a0ae4ebe88af9f880c\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 306, in evaluate_if
          self.evaluate_codeblock(node.elseblock)
        File "C:\Users\clonn\AppData\Local\Temp\pip-install-8iam03wf\numpy_c997373bbbaf43a0ae4ebe88af9f880c\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 190, in evaluate_codeblock
          raise e
        File "C:\Users\clonn\AppData\Local\Temp\pip-install-8iam03wf\numpy_c997373bbbaf43a0ae4ebe88af9f880c\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 182, in evaluate_codeblock
          self.evaluate_statement(cur)
        File "C:\Users\clonn\AppData\Local\Temp\pip-install-8iam03wf\numpy_c997373bbbaf43a0ae4ebe88af9f880c\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 198, in evaluate_statement
          self.assignment(cur)
        File "C:\Users\clonn\AppData\Local\Temp\pip-install-8iam03wf\numpy_c997373bbbaf43a0ae4ebe88af9f880c\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 635, in assignment
          value = self.evaluate_statement(node.value)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\clonn\AppData\Local\Temp\pip-install-8iam03wf\numpy_c997373bbbaf43a0ae4ebe88af9f880c\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 196, in evaluate_statement
          return self.function_call(cur)
                 ^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\clonn\AppData\Local\Temp\pip-install-8iam03wf\numpy_c997373bbbaf43a0ae4ebe88af9f880c\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 521, in function_call
          res = func(node, func_args, kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\clonn\AppData\Local\Temp\pip-install-8iam03wf\numpy_c997373bbbaf43a0ae4ebe88af9f880c\vendored-meson\meson\mesonbuild\interpreterbase\decorators.py", line 826, in wrapped
          return f(*wrapped_args, **wrapped_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\clonn\AppData\Local\Temp\pip-install-8iam03wf\numpy_c997373bbbaf43a0ae4ebe88af9f880c\vendored-meson\meson\mesonbuild\interpreterbase\decorators.py", line 826, in wrapped
          return f(*wrapped_args, **wrapped_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\clonn\AppData\Local\Temp\pip-install-8iam03wf\numpy_c997373bbbaf43a0ae4ebe88af9f880c\vendored-meson\meson\mesonbuild\interpreterbase\decorators.py", line 826, in wrapped
          return f(*wrapped_args, **wrapped_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        [Previous line repeated 4 more times]
        File "C:\Users\clonn\AppData\Local\Temp\pip-install-8iam03wf\numpy_c997373bbbaf43a0ae4ebe88af9f880c\vendored-meson\meson\mesonbuild\interpreterbase\decorators.py", line 109, in wrapped
          ret = f(*wrapped_args, **wrapped_kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\clonn\AppData\Local\Temp\pip-install-8iam03wf\numpy_c997373bbbaf43a0ae4ebe88af9f880c\vendored-meson\meson\mesonbuild\interpreterbase\decorators.py", line 127, in wrapped
          return f(*wrapped_args, **wrapped_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\clonn\AppData\Local\Temp\pip-install-8iam03wf\numpy_c997373bbbaf43a0ae4ebe88af9f880c\vendored-meson\meson\mesonbuild\interpreterbase\decorators.py", line 277, in wrapper
          return f(*nargs, **wrapped_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\clonn\AppData\Local\Temp\pip-install-8iam03wf\numpy_c997373bbbaf43a0ae4ebe88af9f880c\vendored-meson\meson\mesonbuild\interpreterbase\decorators.py", line 596, in wrapper
          return f(*wrapped_args, **wrapped_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\clonn\AppData\Local\Temp\pip-install-8iam03wf\numpy_c997373bbbaf43a0ae4ebe88af9f880c\vendored-meson\meson\mesonbuild\interpreter\interpreter.py", line 1779, in func_dependency
          d = df.lookup(kwargs)
              ^^^^^^^^^^^^^^^^^
        File "C:\Users\clonn\AppData\Local\Temp\pip-install-8iam03wf\numpy_c997373bbbaf43a0ae4ebe88af9f880c\vendored-meson\meson\mesonbuild\interpreter\dependencyfallbacks.py", line 355, in lookup
          dep = func(kwargs, func_args, func_kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\clonn\AppData\Local\Temp\pip-install-8iam03wf\numpy_c997373bbbaf43a0ae4ebe88af9f880c\vendored-meson\meson\mesonbuild\interpreter\dependencyfallbacks.py", line 87, in _do_dependency
          dep = dependencies.find_external_dependency(name, self.environment, kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\clonn\AppData\Local\Temp\pip-install-8iam03wf\numpy_c997373bbbaf43a0ae4ebe88af9f880c\vendored-meson\meson\mesonbuild\dependencies\detect.py", line 124, in find_external_dependency
          d = c()
              ^^^
        File "C:\Users\clonn\AppData\Local\Temp\pip-install-8iam03wf\numpy_c997373bbbaf43a0ae4ebe88af9f880c\vendored-meson\meson\mesonbuild\dependencies\blas_lapack.py", line 497, in __init__
          super().__init__('OpenBLAS', env, kwargs, language, force_use_global_compilers)
        File "C:\Users\clonn\AppData\Local\Temp\pip-install-8iam03wf\numpy_c997373bbbaf43a0ae4ebe88af9f880c\vendored-meson\meson\mesonbuild\dependencies\cmake.py", line 137, in __init__
          CMakeDependency.class_cmakeinfo[self.for_machine] = self._get_cmake_info(cm_args)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\clonn\AppData\Local\Temp\pip-install-8iam03wf\numpy_c997373bbbaf43a0ae4ebe88af9f880c\vendored-meson\meson\mesonbuild\dependencies\cmake.py", line 185, in _get_cmake_info
          ret1, out1, err1 = self._call_cmake(cmake_opts, 'CMakePathInfo.txt')
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\clonn\AppData\Local\Temp\pip-install-8iam03wf\numpy_c997373bbbaf43a0ae4ebe88af9f880c\vendored-meson\meson\mesonbuild\dependencies\cmake.py", line 618, in _call_cmake
          build_dir = self._setup_cmake_dir(cmake_file)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\clonn\AppData\Local\Temp\pip-install-8iam03wf\numpy_c997373bbbaf43a0ae4ebe88af9f880c\vendored-meson\meson\mesonbuild\dependencies\cmake.py", line 589, in _setup_cmake_dir
          cmake_txt = importlib.resources.read_text('mesonbuild.dependencies.data', cmake_file, encoding = 'utf-8')
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'importlib.resources' has no attribute 'read_text'
      The Meson build system
      Version: 1.2.99
      Source dir: C:\Users\clonn\AppData\Local\Temp\pip-install-8iam03wf\numpy_c997373bbbaf43a0ae4ebe88af9f880c
      Build dir: C:\Users\clonn\AppData\Local\Temp\pip-install-8iam03wf\numpy_c997373bbbaf43a0ae4ebe88af9f880c\.mesonpy-b0uebtvb\build
      Build type: native build
      Project name: NumPy
      Project version: 1.26.2
      Activating VS 17.4.4
      C compiler for the host machine: cl (msvc 19.34.31937 "用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.34.31937 版")
      C linker for the host machine: link link 14.34.31937.0
      C++ compiler for the host machine: cl (msvc 19.34.31937 "用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.34.31937 版")
      C++ linker for the host machine: link link 14.34.31937.0
      Cython compiler for the host machine: cython (cython 3.0.7)
      Host machine cpu family: x86_64
      Host machine cpu: x86_64
      Program python found: YES (C:\Program Files\Python313\python.exe)
      Run-time dependency python found: YES 3.13
      Has header "Python.h" with dependency python: YES
      Compiler for C supports arguments -fno-strict-aliasing: NO
      Test features "SSE SSE2 SSE3" : Supported
      Test features "SSSE3" : Supported
      Test features "SSE41" : Supported
      Test features "POPCNT" : Supported
      Test features "SSE42" : Supported
      Test features "AVX" : Supported
      Test features "F16C" : Supported
      Test features "FMA3" : Supported
      Test features "AVX2" : Supported (cached)
      Test features "AVX512F" : Supported
      Test features "AVX512CD" : Supported (cached)
      Test features "AVX512_KNL" : disabled due to AVX512_KNL is disabled due to "msvc compiler does not support it"
      Test features "AVX512_KNM" : disabled due to AVX512_KNM is disabled due to "msvc compiler does not support it"
      Test features "AVX512_SKX" : Supported (cached)
      Test features "AVX512_CLX" : Supported
      Test features "AVX512_CNL" : Supported
      Test features "AVX512_ICL" : Supported
      Test features "AVX512_SPR" : disabled due to AVX512_SPR is disabled due to "msvc compiler does not support it"
      Configuring npy_cpu_dispatch_config.h using configuration
      Message:
      CPU Optimization Options
        baseline:
          Requested : min
          Enabled   : SSE SSE2 SSE3
        dispatch:
          Requested : max -xop -fma4
          Enabled   : SSSE3 SSE41 POPCNT SSE42 AVX F16C FMA3 AVX2 AVX512F AVX512CD AVX512_SKX AVX512_CLX AVX512_CNL AVX512_ICL

      Library m found: NO
      Fetching value of define "__MINGW32__" :
      Did not find pkg-config by name 'pkg-config'
      Found Pkg-config: NO
      Run-time dependency scipy-openblas found: NO (tried pkgconfig)
      Run-time dependency mkl found: NO (tried pkgconfig and system)
      Run-time dependency mkl found: NO (tried pkgconfig and system)
      Run-time dependency accelerate found: NO (tried system)
      Found CMake: C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.EXE (3.24.202208181)
      WARNING: CMake Toolchain: Failed to determine CMake compilers state

      ..\..\numpy\meson.build:124:13: ERROR: Unhandled python exception

          This is a Meson bug and should be reported!
      [end of output]
```

### Python and NumPy Versions:

py -> 3.13
numpy -> 1.26.2

### Runtime Environment:

win11

**Comment by rgommers** [comment]
> `pip install numpy`

You are using Python 3.13-dev here, so please do not try to install a released version from PyPI that doesn't support 3.13 - that will not work. If you build from `main`, things should work. This issue that was caused by a removal of Python API surface from `importlib.resources`, was fixed a while back.
