### ISSUE TITLE
No module named: 'numpy.core._multiarray_umath' error

### ISSUE THREAD

**Issue by rodoggyro** [numpy/numpy#25519]
### Steps to reproduce:

I'm using linux and when installing matplotlib I had to do `sudo apt-get install python3-matplotlib` this made matplotlib work but then made me get an error which can be seen below. I tried uninstalling and reinstalling using pip then uninstalling and reinstalling matplotlib.

### Error message:

```shell
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/numpy/core/__init__.py", line 17, in <module>
    from . import multiarray
  File "/usr/lib/python3/dist-packages/numpy/core/multiarray.py", line 14, in <module>
    from . import overrides
  File "/usr/lib/python3/dist-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rodoggx/Documents/Stock-Exchange/stockExchangeLibs/main.py", line 9, in <module>
    import matplotlib as mpl
  File "/usr/lib/python3/dist-packages/matplotlib/__init__.py", line 138, in <module>
    from . import cbook, rcsetup
  File "/usr/lib/python3/dist-packages/matplotlib/cbook/__init__.py", line 31, in <module>
    import numpy as np
  File "/usr/lib/python3/dist-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/usr/lib/python3/dist-packages/numpy/core/__init__.py", line 47, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.9 from "/bin/python3.9",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.17.4" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: No module named 'numpy.core._multiarray_umath'
```

### Additional information:

Using linux Ubuntu, python version 3.8.10, pip version 20.0.2

**Comment by ngoldbaum** [comment]
It's hard to say why this is happening without a little more information about how NumPy was originally installed. In particular, this could happen if you (for example) did `sudo pip install -U numpy` with the system python. That said, I'm pretty sure ubuntu doesn't let you do that anymore, but other similar shenanigans will generate similar brokenness.

Also while the error message says that this is a numpy bug, if this is happening with the numpy and matplotlib packages provided by ubuntu, this is really an ubuntu bug.
