### ISSUE TITLE
BUG: CPU detection fails in windows VM running on ARM Mac

### ISSUE THREAD

**Issue by ngoldbaum** [numpy/numpy#25604]
### Describe the issue:

When I try to build numpy in the default configuration on an ARM Mac running an ARM Windows 11 VM via qemu, I get the build error below.

Building with `spin build --clean -- -Ddisable-optimization=True` lets me build though so this isn't a showstopper for my debugging session.

### Reproduce the code example:

```python
N/A
```

### Error message:

```shell
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Nathan Goldbaum\numpy\build-install\usr\Lib\site-packages\numpy\__init__.py", line 114, in <module>
    from numpy.__config__ import show as show_config
  File "C:\Users\Nathan Goldbaum\numpy\build-install\usr\Lib\site-packages\numpy\__config__.py", line 4, in <module>
    from numpy._core._multiarray_umath import (
  File "C:\Users\Nathan Goldbaum\numpy\build-install\usr\Lib\site-packages\numpy\_core\__init__.py", line 23, in <module>
    from . import multiarray
  File "C:\Users\Nathan Goldbaum\numpy\build-install\usr\Lib\site-packages\numpy\_core\multiarray.py", line 10, in <module>
    from . import overrides
  File "C:\Users\Nathan Goldbaum\numpy\build-install\usr\Lib\site-packages\numpy\_core\overrides.py", line 8, in <module>
    from numpy._core._multiarray_umath import (
RuntimeError: NumPy was built with baseline optimizations:
(NEON NEON_FP16 NEON_VFPV4 ASIMD) but your machine doesn't support:
(NEON).
```

### Python and NumPy Versions:

python 3.12.1 installed via python.org installer, numpy main.

### Runtime Environment:

numpy doesn't install so I can't get this far.

**Comment by mattip** [comment]
Weird, I thought qemu on M1 supported NEON. Maybe this is a windows-arm64 problem? What happens if you run an aarch64 VM in qemu, do you get NEON?

**Comment by mattip** [comment]
Successfully importing NumPy with this line means these CPU features are required and found:
```
simd_extensions': {'baseline': ['NEON', 'NEON_FP16', 'NEON_VFPV4', 'ASIMD'],
```

I wonder if [`npy__cpu_init_features()`](https://github.com/numpy/numpy/blob/174ac7bc6622cfe67cc83d331ad5650269c227b8/numpy/_core/src/common/npy_cpu_features.c#L369C1-L370C1) has a branch for windows + arm64. It seems the [compiler defines macros](https://learn.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=msvc-170) differently to linux, so [this check](https://github.com/numpy/numpy/blob/174ac7bc6622cfe67cc83d331ad5650269c227b8/numpy/_core/src/common/npy_cpu_features.c#L660) might be failing. 

It is hard to get python + numpy running under the visual studio debugger to step through the code. Could you add some fprintf() debug statements and recompile to see which code is active there?
