### ISSUE TITLE
<No module named 'numpy.core._multiarray_umath'>

### ISSUE THREAD

**Issue by pengyuanwei** [numpy/numpy#25667]
### Steps to reproduce:

I'm reproducing a c++ project that calls python functions. When calling python functions, the project reports an error: No module named 'numpy.core._multiarray_umath'.

OS: Windows 11
Python version: 3.9
NumPy version: 1.26.3
Visual Studio 2022

### Error message:

```shell
Traceback (most recent call last):
  File "C:\Users\William\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\core\__init__.py", line 24, in <module>
    from . import multiarray
  File "C:\Users\William\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\core\multiarray.py", line 10, in <module>
    from . import overrides
  File "C:\Users\William\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\core\overrides.py", line 8, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\William\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\__init__.py", line 159, in <module>
    from numpy.__config__ import show as show_config
  File "C:\Users\William\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\__config__.py", line 4, in <module>
    from numpy.core._multiarray_umath import (
  File "C:\Users\William\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\core\__init__.py", line 50, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.9 from "F:\Desktop\Levitator\OpenMPD_Demo\OpenMPD_Demo\x64\TestNewSolvers.exe"
  * The NumPy version is: "1.26.3"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\Desktop\Levitator\0.libraries\bin\x64\S2M2\PathPlanner.py", line 2, in <module>
    from algs.decentralized import decentralized_algo
  File "F:\Desktop\Levitator\0.libraries\bin\x64\S2M2\algs\decentralized.py", line 1, in <module>
    from algs.xref import *
  File "F:\Desktop\Levitator\0.libraries\bin\x64\S2M2\algs\xref.py", line 4, in <module>
    import polytope as pc
  File "C:\Users\William\AppData\Local\Programs\Python\Python39\lib\site-packages\polytope\__init__.py", line 36, in <module>
    from .polytope import (
  File "C:\Users\William\AppData\Local\Programs\Python\Python39\lib\site-packages\polytope\polytope.py", line 68, in <module>
    import numpy as np
  File "C:\Users\William\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\__init__.py", line 164, in <module>
    raise ImportError(msg) from e
ImportError: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.
```

### Additional information:

I read issue #21678 and reinstalled the numpy following the suggestion, but the project still didn't work. 

I read the tip https://numpy.org/devdocs/user/troubleshooting-importerror.html#debug-build-on-windows and it looks like the error is caused by using full DEBUG mode because python39_d.lib was added into the properties of the C++ project. For recompiling the entire stack of python modules, I reinstalled the python from the official Python website and reinstalled python packages I am using, but the project still didn't work.

I also checked all paths I added in the C++ project properties and system environment variables and made sure all paths pointed to this installed python.

**Comment by mattip** [comment]
Use a non-debug python and run your project in "release with debug symbols" and not "debug" mode. It will save you from having to recompile all the python libraries from source.

**Comment by rgommers** [comment]
I think that answers the question indeed, and there's nothing further for us to do in NumPy. Hence I'll close this issue.
