### ISSUE TITLE
BUG: f2py python front end gives a fatal error when array size is given before array in agreement with fortran backend

### ISSUE THREAD

**Issue by broukema** [numpy/numpy#25728]
### Describe the issue:

SUMMARY:

A beginner using f2py will expect that if the fortran backend lists parameters including an array size and an array, in that order, then a python front end that uses the fortran backend compiled by f2py should also list the array size and array in that same order. However, doing this gives a fatal error in python. The user is required to either omit the array size or provide the two parameters in the reverse order.

REPRODUCE:

With appropriate file names:
````
gfortran bug0.f; ./a.out; f2py -c -m param_order bug0.f; python3 bug0py.py
````
gives
````
nine =         9
`````
from running the fortran main program but
````
Traceback (most recent call last):
  File "/MYDIR/bug0py.py", line 7, in <module>
    param_order.get_fact(k, j_size, j_array)
param_order.error: (shape(j_array, 0) == j_size) failed for 1st keyword j_size: get_fact:j_size=45
````
from running the python front end.

Commenting out the line `param_order.get_fact(k, j_size, j_array)` and uncommenting either of the lines
````
#param_order.get_fact(k, j_array, j_size)
#param_order.get_fact(k, j_array)
````
and doing `gfortran bug0.f; ./a.out; f2py -c -m param_order bug0.f; python3 bug0py.py` again gives 
````
nine =      9
````
from both the fortran main program and the python front end.

### Reproduce the code example:

```python
fortran:
`
      program learn_f2py
      integer :: k
      integer, dimension(3) :: j_array
      k = 55
      j_size = 3
      j_array(2) = 845
      call get_fact(k, j_size, j_array)
      end

      subroutine get_fact(k, j_size, j_array)
!f2py integer, intent(in) :: k, j_size
      integer, dimension(j_size) :: j_array
!f2py intent(in) :: j_array
! implicit typing
      nine = (k + j_array(2))/100
      write(6,'(a,i10)')'nine =',nine
      return
      end
````

python:
````
import param_order
k = 55
j_array = (45, 845, 1845) # python list object
j_size = 3

#This fails fatally:
param_order.get_fact(k, j_size, j_array)

#This works:
#param_order.get_fact(k, j_array, j_size)

#This works:
#param_order.get_fact(k, j_array)
````
```


### Error message:

```shell
`
Traceback (most recent call last):
  File "/MYDIR/bug0py.py", line 7, in <module>
    param_order.get_fact(k, j_size, j_array)
param_order.error: (shape(j_array, 0) == j_size) failed for 1st keyword j_size: get_fact:j_size=45
````
```


### Python and NumPy Versions:

````
Debian bookworm
ii  python3-numpy                                 1:1.24.2-1                              amd64
ii  python3                                       3.11.2-1+b1                             amd64
````


### Runtime Environment:

_No response_

### Context for the issue:

DISCUSSION:

This behaviour is not obvious to the beginning user and ( see https://github.com/numpy/numpy/issues/25616 ) is not documented. Apart from improved documentation, an alternative to heavy refactoring of `f2py` could be to provide a warning or error during the `f2py` compile step.

**Comment by broukema** [comment]
If you play around with a long list of arrays and array sizes as parameters on the fortran side, you should find that on the python side, as long as all the arrays are listed first (in their same order when ignoring the sizes), and all the sizes are either omitted or listed second (in their same order when ignoring the arrays themselves), then calling the function from fortran or python should work and give the same results. That's no longer a minimal working example, though.
