### ISSUE TITLE
DOC/BUILD: Documentation building failed with latest codes in local environment

### ISSUE THREAD

**Issue by liang3zy22** [numpy/numpy#25764]
I have tried to build documentation in my local machine. I have followed steps:
```
pip install -r doc_requirements.txt #requirements directory should be added
git submodule update --init
spin docs
```

 But it reported following errors:
```
RuntimeError: module compiled against ABI version 0x1000009 but this version of numpy is 0x2000000

Traceback (most recent call last):
  File "/home/yanliang/anaconda3/envs/numpy-dev/lib/python3.11/site-packages/sphinx/registry.py", line 442, in load_extension
    mod = import_module(extname)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yanliang/anaconda3/envs/numpy-dev/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/yanliang/anaconda3/envs/numpy-dev/lib/python3.11/site-packages/matplotlib/__init__.py", line 161, in <module>
    from . import _api, _version, cbook, _docstring, rcsetup
  File "/home/yanliang/anaconda3/envs/numpy-dev/lib/python3.11/site-packages/matplotlib/rcsetup.py", line 27, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "/home/yanliang/anaconda3/envs/numpy-dev/lib/python3.11/site-packages/matplotlib/colors.py", line 57, in <module>
    from matplotlib import _api, _cm, cbook, scale
  File "/home/yanliang/anaconda3/envs/numpy-dev/lib/python3.11/site-packages/matplotlib/scale.py", line 22, in <module>
    from matplotlib.ticker import (
  File "/home/yanliang/anaconda3/envs/numpy-dev/lib/python3.11/site-packages/matplotlib/ticker.py", line 143, in <module>
    from matplotlib import transforms as mtransforms
  File "/home/yanliang/anaconda3/envs/numpy-dev/lib/python3.11/site-packages/matplotlib/transforms.py", line 49, in <module>
    from matplotlib._path import (
ImportError: numpy.core.multiarray failed to import

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/yanliang/anaconda3/envs/numpy-dev/lib/python3.11/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yanliang/anaconda3/envs/numpy-dev/lib/python3.11/site-packages/sphinx/application.py", line 229, in __init__
    self.setup_extension(extension)
  File "/home/yanliang/anaconda3/envs/numpy-dev/lib/python3.11/site-packages/sphinx/application.py", line 404, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/yanliang/anaconda3/envs/numpy-dev/lib/python3.11/site-packages/sphinx/registry.py", line 445, in load_extension
    raise ExtensionError(__('Could not import extension %s') % extname,
sphinx.errors.ExtensionError: Could not import extension matplotlib.sphinxext.plot_directive (exception: numpy.core.multiarray failed to import)

```
Did I miss any steps? I have tried on x86 and macOS arm platform both. Same error.

**Comment by seberg** [comment]
No, but it is annoying right now, it should work if you install scipy and matplotlib and maybe pandas from: https://anaconda.org/scientific-python-nightly-wheels/

Matplotlib used to have issues with the MacOS wheels (i.e. only available on older versions or so), I suspect it is fixed, but I am not sure.

If it get's tedious, please feel free to open a PR, the docs are build as part of the CI (look for CircleCI build artifact).

**Comment by liang3zy22** [comment]
I have created a PR to update "how to build doc" documentation. Nightly build packages can't be installed on MacOS arm platform.
Besides, I have checked CircleCI build artifact log, can't find build doc part. Not sure where the build doc steps really is.

**Comment by charris** [comment]
Look in `.circleci/config.yml`. There are no Mac arm wheels in the nightlies? Hmm, looks like cirrus didn't run/upload last Sunday, the last Mac arm wheels are from 16 days ago.

**Comment by andyfaff** [comment]
The Cron job ran, but didn't succeed. https://cirrus-ci.com/build/5178747729477632. One of the matrix entries failed because a pytest-xdist thread crashed whilst running a test.

**Comment by charris** [comment]
I  reran the cirrus jobs and they succeeded.

**Comment by rgommers** [comment]
This was addressed with a doc note in gh-25774. That doc note is going to be outdated once 2.0.0 is out (or even before, if matplotlib/scipy have a 2.0.0rc1-compatible release), so let's not extend that further.

Problem at hand solved, so closing. Thanks @liang3zy22 & all.
