### ISSUE TITLE
NumPy runtime error when embedding Python 312 in C++ using CMake

### ISSUE THREAD

**Issue by k0T0z** [numpy/numpy#25888]
### Steps to reproduce:

Use this CMake File:

```cmake
set(SAM_ENGINE "sam_engine" CACHE STRING "SAM Engine library name.")

# Check https://cmake.org/cmake/help/latest/module/FindPython.html for more information.
find_package(Python 3.12 REQUIRED COMPONENTS Interpreter Development NumPy)

add_library(${SAM_ENGINE} SHARED STATIC
    ${SAM_ENGINE_SRC_FILES} 
)

target_link_libraries(${SAM_ENGINE} PUBLIC 
    ${Python_LIBRARIES}
)

target_include_directories(${SAM_ENGINE} PUBLIC 
    "${CMAKE_CURRENT_SOURCE_DIR}/" 
    "${Python_INCLUDE_DIRS}/" 
)
```

C++ code:

```cpp
Py_Initialize();

// Append the directory containing your Python module to sys.path
PyObject* sysPath = PySys_GetObject((char*)"path");
PyList_Append(sysPath, PyUnicode_FromString(PE_ENGINE_SCRIPTS_DIR));

PEEngine::pModule = PyImport_ImportModule("get_pe_features");
if (PEEngine::pModule == NULL) {
    std::cout << "Error: Failed to import Python module" << std::endl;
    PyErr_Print();
}
```

### Error message:

```shell
Traceback (most recent call last):
  File "C:\Users\saifs\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\core\__init__.py", line 24, in <module>
    from . import multiarray
  File "C:\Users\saifs\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\core\multiarray.py", line 10, in <module>
    from . import overrides
  File "C:\Users\saifs\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\core\overrides.py", line 8, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
```

Full error message:

```
$ ./tests/Debug/sam_engine_tests.exe --gtest_filter=PEEngineTest.TestGetPEFeatures
Note: Google Test filter = PEEngineTest.TestGetPEFeatures
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from PEEngineTest
[ RUN      ] PEEngineTest.TestGetPEFeatures
Error: Failed to import Python module
Traceback (most recent call last):
  File "C:\Users\saifs\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\core\__init__.py", line 24, in <module>
    from . import multiarray
  File "C:\Users\saifs\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\core\multiarray.py", line 10, in <module>
    from . import overrides
  File "C:\Users\saifs\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\core\overrides.py", line 8, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\saifs\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\__init__.py", line 144, in <module>
    from numpy.__config__ import show as show_config
  File "C:\Users\saifs\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\__config__.py", line 4, in <module>
    from numpy.core._multiarray_umath import (
  File "C:\Users\saifs\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\core\__init__.py", line 50, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.12 from "C:\Users\saifs\Desktop\scorpion-antimalware\.build\tests\Debug\sam_engine_tests.exe"
  * The NumPy version is: "1.26.4"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users/saifs/Desktop/scorpion-antimalware/sam-engine/PE-engine/scripts\get_pe_features.py", line 1, in <module>
    from ember import PEFeatureExtractor
  File "C:\Users\saifs\AppData\Local\Programs\Python\Python312\Lib\site-packages\ember\__init__.py", line 6, in <module>
    import numpy as np
  File "C:\Users\saifs\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\__init__.py", line 149, in <module>
    raise ImportError(msg) from e
ImportError: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.
[       OK ] PEEngineTest.TestGetPEFeatures (262 ms)
[----------] 1 test from PEEngineTest (262 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (263 ms total)
[  PASSED  ] 1 test.
```

### Additional information:

I have a Windows VM, a fresh one, and only one Python version with these packages installed:
```
Successfully installed colorama-0.4.6 ember-0.1.0 joblib-1.3.2 lief-0.14.1 lightgbm-4.3.0 numpy-1.26.4 pandas-2.2.1 python-dateutil-2.8.2 pytz-2024.1 scikit-learn-1.4.1.post1 scipy-1.12.0 six-1.16.0 threadpoolctl-3.3.0 tqdm-4.66.2 tzdata-2024.1
```

My env variables:
```
PYTHONPATH: None
PATH: C:\Users\saifs\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\saifs\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH;C:\Program Files\Git\cmd;C:\Program Files\CMake\bin;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit;C:\Qt\6.6.1\msvc2019_64\lib;C:\Qt\6.6.1\msvc2019_64\bin;C:\Program Files (x86)\googletest-distribution\bin;C:\Users\saifs\AppData\Local\Programs\Python\Python312;C:\Users\saifs\AppData\Local\Programs\Python\Python312\Scripts;C:\Users\saifs\AppData\Local\Programs\Python\Launcher;C:\Users\saifs\AppData\Local\Microsoft\WindowsApps;C:\Users\saifs\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
```

I tried everything nearly, so please can anyone suggest something?

I think it is worth noting that, my CMake command ran without any errors as well as the build process is perfectly fine. The problem occurs at runtime.

**Comment by seberg** [comment]
Closing, the website the error points to has a section on "Debug build on windows" that would seem to apply.
