### ISSUE TITLE
f2py fails on Windows - wrong path in meson

### ISSUE THREAD

**Issue by mrkwjc** [numpy/numpy#26107]
### Steps to reproduce:

Hi! I try to compile Fortran extension with f2py, but it fails with strange error. The crucial lines in output are:
```
Program C:      ools\miniforge3\envs\py12\python.exe found: NO

meson.build:11:22: ERROR: C:    ools\miniforge3\envs\py12\python.exe not found
```
It seems that "\t" is replaced with tabulator at some point, and path is not found. Is this numpy or meson bug?

### Error message:

```shell
(py12) PS C:\Users\mwojc\git\ffnet\ffnet\fortran> f2py.exe -m '_ffnet' -c 'ffnet.f'
Cannot use distutils backend with Python>=3.12, using meson backend instead.
Using meson backend
Will pass --lower to f2py
See https://numpy.org/doc/stable/f2py/buildtools/meson.html
Reading fortran codes...
        Reading file 'ffnet.f' (format:fix,strict)
Post-processing...
        Block: _ffnet
                        Block: prop
                        Block: sqerror
                        Block: grad
                        Block: recall
                        Block: diff
                        Block: func
                        Block: func2
                        Block: pikaiaff
                        Block: normcall
                        Block: normdiff
                        Block: normcall2
                        Block: normdiff2
                        Block: momentum
                        Block: rprop
                        Block: setin
                        Block: getout
                        Block: mapa
                        Block: dmapa
                        Block: vmapa
                        Block: mmapa
Applying post-processing hooks...
  character_backward_compatibility_hook
Post-processing (stage 2)...
Building modules...
    Building module "_ffnet"...
    Generating possibly empty wrappers"
    Maybe empty "_ffnet-f2pywrappers.f"
        Constructing wrapper function "prop"...
          units = prop(x,conec,units,[n,u])
    Generating possibly empty wrappers"
    Maybe empty "_ffnet-f2pywrappers.f"
        Constructing wrapper function "sqerror"...
          sqerr = sqerror(x,conec,units,inno,outno,input,targ,[n,u,i,o,p])
    Generating possibly empty wrappers"
    Maybe empty "_ffnet-f2pywrappers.f"
        Constructing wrapper function "grad"...
          xprime = grad(x,conec,bconecno,units,inno,outno,input,targ,[n,bn,u,i,o,p])
    Generating possibly empty wrappers"
    Maybe empty "_ffnet-f2pywrappers.f"
        Constructing wrapper function "recall"...
          output = recall(x,conec,units,inno,outno,input,[n,u,i,o])
    Generating possibly empty wrappers"
    Maybe empty "_ffnet-f2pywrappers.f"
        Constructing wrapper function "diff"...
          deriv = diff(x,conec,dconecno,dconecmk,units,inno,outno,input,[n,dn,u,i,o])
    Generating possibly empty wrappers"
    Maybe empty "_ffnet-f2pywrappers.f"
        Constructing wrapper function "func"...
          sqerr = func(x,conec,bconecno,units,inno,outno,input,targ,[n,bn,u,i,o,p])
    Generating possibly empty wrappers"
    Maybe empty "_ffnet-f2pywrappers.f"
        Constructing wrapper function "func2"...
          sqerr,xprime = func2(x,conec,bconecno,units,inno,outno,input,targ,[n,bn,u,i,o,p])
    Generating possibly empty wrappers"
    Maybe empty "_ffnet-f2pywrappers.f"
        Constructing wrapper function "pikaiaff"...
          isqerr = pikaiaff(x,ffn,conec,units,inno,outno,input,targ,bound1,bound2,[n,u,i,o,p])
    Generating possibly empty wrappers"
    Maybe empty "_ffnet-f2pywrappers.f"
        Constructing wrapper function "normcall"...
          output = normcall(x,conec,units,inno,outno,eni,deo,input,[n,u,i,o])
    Generating possibly empty wrappers"
    Maybe empty "_ffnet-f2pywrappers.f"
        Constructing wrapper function "normdiff"...
          deriv = normdiff(x,conec,dconecno,dconecmk,units,inno,outno,eni,ded,input,[n,dn,u,i,o])
    Generating possibly empty wrappers"
    Maybe empty "_ffnet-f2pywrappers.f"
        Constructing wrapper function "normcall2"...
          output = normcall2(x,conec,units,inno,outno,eni,deo,input,[n,u,i,o,p])
    Generating possibly empty wrappers"
    Maybe empty "_ffnet-f2pywrappers.f"
        Constructing wrapper function "normdiff2"...
          deriv = normdiff2(x,conec,dconecno,dconecmk,units,inno,outno,eni,ded,input,[n,dn,u,i,o,p])
    Generating possibly empty wrappers"
    Maybe empty "_ffnet-f2pywrappers.f"
        Constructing wrapper function "momentum"...
          x = momentum(x,conec,bconecno,units,inno,outno,input,targ,eta,moment,maxiter,[n,bn,u,i,o,p])
    Generating possibly empty wrappers"
    Maybe empty "_ffnet-f2pywrappers.f"
        Constructing wrapper function "rprop"...
          x,xmi = rprop(x,conec,bconecno,units,inno,outno,input,targ,a,b,mimin,mimax,xmi,maxiter,[n,bn,u,i,o,p])
    Generating possibly empty wrappers"
    Maybe empty "_ffnet-f2pywrappers.f"
        Constructing wrapper function "setin"...
          units = setin(input,inno,eni,units,[i,u])
    Generating possibly empty wrappers"
    Maybe empty "_ffnet-f2pywrappers.f"
        Constructing wrapper function "getout"...
          output = getout(units,outno,deo,[u,o])
    Generating possibly empty wrappers"
    Maybe empty "_ffnet-f2pywrappers.f"
                Creating wrapper for Fortran function "mapa"("mapa")...
        Constructing wrapper function "mapa"...
          mapa = mapa(f,a,b,c,d)
    Generating possibly empty wrappers"
    Maybe empty "_ffnet-f2pywrappers.f"
                Creating wrapper for Fortran function "dmapa"("dmapa")...
        Constructing wrapper function "dmapa"...
          dmapa = dmapa(f,a,b,c,d)
    Generating possibly empty wrappers"
    Maybe empty "_ffnet-f2pywrappers.f"
        Constructing wrapper function "vmapa"...
          vout = vmapa(vin,a,b,c,d,[n])
    Generating possibly empty wrappers"
    Maybe empty "_ffnet-f2pywrappers.f"
        Constructing wrapper function "mmapa"...
          mmout = mmapa(mmin,a,b,c,d,[m,n])
    Wrote C/API module "_ffnet" to file ".\_ffnetmodule.c"
    Fortran 77 wrappers are saved to ".\_ffnet-f2pywrappers.f"
The Meson build system
Version: 1.4.0
Source dir: C:\Users\mwojc\AppData\Local\Temp\tmp1axuanha
Build dir: C:\Users\mwojc\AppData\Local\Temp\tmp1axuanha\bbdir
Build type: native build
Project name: _ffnet
Project version: 0.1
Fortran compiler for the host machine: gfortran (gcc 5.3.0 "GNU Fortran (Rev5, Built by MSYS2 project) 5.3.0")
Fortran linker for the host machine: gfortran ld.bfd 2.25.1
C compiler for the host machine: cc (gcc 5.3.0 "cc (Rev5, Built by MSYS2 project) 5.3.0")
C linker for the host machine: cc ld.bfd 2.25.1
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program C:      ools\miniforge3\envs\py12\python.exe found: NO

meson.build:11:22: ERROR: C:    ools\miniforge3\envs\py12\python.exe not found

A full log can be found at C:\Users\mwojc\AppData\Local\Temp\tmp1axuanha\bbdir\meson-logs\meson-log.txt
Traceback (most recent call last):
  File "C:\tools\miniforge3\envs\py12\Scripts\f2py-script.py", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "C:\tools\miniforge3\envs\py12\Lib\site-packages\numpy\f2py\f2py2e.py", line 766, in main
    run_compile()
  File "C:\tools\miniforge3\envs\py12\Lib\site-packages\numpy\f2py\f2py2e.py", line 738, in run_compile
    builder.compile()
  File "C:\tools\miniforge3\envs\py12\Lib\site-packages\numpy\f2py\_backends\_meson.py", line 178, in compile
    self.run_meson(self.build_dir)
  File "C:\tools\miniforge3\envs\py12\Lib\site-packages\numpy\f2py\_backends\_meson.py", line 171, in run_meson
    self._run_subprocess_command(setup_command, build_dir)
  File "C:\tools\miniforge3\envs\py12\Lib\site-packages\numpy\f2py\_backends\_meson.py", line 167, in _run_subprocess_command
    subprocess.run(command, cwd=cwd, check=True)
  File "C:\tools\miniforge3\envs\py12\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['meson', 'setup', 'bbdir']' returned non-zero exit status 1.
```

**Comment by seberg** [comment]
Actually, maybe the solution is to use triple quotes everywhere strings are pasted?  Since it sounds like that behaves like [raw strings](https://mesonbuild.com/Release-notes-for-0-46-0.html#string-escape-character-sequence-update) in meson.
(I suppose that'll still fail if someone has a file which contains triple quotes :))

**Comment by Serge3leo** [comment]
I get this error too. Minimal reproduce examples: 
https://github.com/Serge3leo/numpy-f2py-240323/tree/pip-bug (pip)
https://github.com/Serge3leo/numpy-f2py-240323 (miniconda)

Workaround:
```
ff=`python -c "import numpy.f2py; print(numpy.f2py.__file__)"`
mbt=`dirname $ff`/_backends/meson.build.template

sed -e "/import('python').find_installation(/s/'\${python}', //" -i -- "$mbt"
```

Diff:
```
--- "C:\\Miniconda\\envs\\test\\Lib\\site-packages\\numpy\\f2py/_backends/meson.build.template.orig"	2024-02-06 13:27:04.925110800 +0000
+++ "C:\\Miniconda\\envs\\test\\Lib\\site-packages\\numpy\\f2py/_backends/meson.build.template"	2024-03-23 20:07:44.848754500 +0000
@@ -8,7 +8,7 @@
                           ])
 fc = meson.get_compiler('fortran')
 
-py = import('python').find_installation('${python}', pure: false)
+py = import('python').find_installation(pure: false)
 py_dep = py.dependency()
 
 incdir_numpy = run_command(py,
```
