### ISSUE TITLE
BUG: NaT is incorrectly cast inside object arrays

### ISSUE THREAD

**Issue by Wainberg** [numpy/numpy#26177]
### Describe the issue:

When `np.datetime64('NaT')` and `np.timedelta64('NaT')` appear inside arrays with `dtype=object`, they're incorrectly cast to `-9.22337204e+18` when the array is cast to floating-point types (including complex), rather than giving an error.

### Reproduce the code example:

```python
>>> import numpy as np
>>> np.array([np.datetime64('NaT'), 1], dtype=object).astype(float)
array([-9.22337204e+18,  1.00000000e+00])
>>> np.array([np.timedelta64('NaT'), 1+2j], dtype=object).astype(complex)
array([-9.22337204e+18+0.j,  1.00000000e+00+2.j])
```

### Python and NumPy Versions:

1.26.4
3.12.2 | packaged by conda-forge | (main, Feb 16 2024, 20:50:58) [GCC 12.3.0]

**Comment by kymcglyn** [comment]
"My partner (ashorkey-umich) and I are students at the University of Michigan and have been assigned to contribute to open-source projects. Would it be possible to have this issue assigned to us?"

**Comment by seberg** [comment]
No, this is arguably a bug.  But we don't assign issues, please just work on it and open a PR.

**Comment by Wainberg** [comment]
Semantically, `NaT` is similar to `nan`, so I think it should convert to `nan` when cast to float, and to `np.nan+0.j` when cast to complex (which is NumPy's representation of complex `nan`).

The other option would be to raise an error, which NumPy already does when casting to `int` (albeit with a cryptic error message that could be improved):

```python
>>> np.array([np.datetime64('NaT')], dtype=object).astype(int)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
```

**Comment by cmsxbc** [comment]
@seberg @Wainberg well, I got the point. So should the normal datetime64 in object arrays also raise an error when casting to `float` as it do in `int` ?

```Python
>>> np.array([1.0, np.datetime64('2024-01-01 11:00:00')], dtype=object).astype(int)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'datetime.datetime'
>>> int(np.datetime64('2024-01-01 11:00:00'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'datetime.datetime'
>>> float(np.datetime64('2024-01-01 11:00:00'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: float() argument must be a string or a real number, not 'datetime.datetime'
>>> 
```

**Comment by seberg** [comment]
This all works, it should just work the same: `np.array(np.nan).astype("m8[ns]")`

**Comment by seberg** [comment]
Sorry, I may have gotten it the wrong way around, and this one is the cast from timedelta (or datetime I guess) to float: but it doesn't change the fact that it makes sense to return NaN for NaT.

**Comment by Wainberg** [comment]
@cmsxbc that's a fair point. NumPy is very permissive with casting by default (i.e. with `casting='unsafe'`). `datetime64` -> `float` is always allowed:

```python
>>> np.array([np.datetime64('2024-01-01')]).astype(float)
array([19723.])
>>> np.array([np.datetime64('2024-01-01')], dtype=object).astype(float)
array([19723.])
```

and `datetime64` -> `int` is also allowed, but not for `dtype=object`:

```python
>>> np.array([np.datetime64('2024-01-01')]).astype(int)
array([19723])
>>> np.array([np.datetime64('2024-01-01')], dtype=object).astype(int)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'datetime.date'
```

Personally, I'd do the following:

1. Make `np.array([np.datetime64('NaT'), np.datetime64('2024-01-01')]).astype(float)` return `np.array([np.nan, 19723.])` rather than `np.array([-9223372036854775808, 19723.])`.
2. Allow `np.array([np.datetime64('2024-01-01')], dtype=object).astype(int)` for consistency with the other three cases. However, I would disallow `np.array([np.datetime64('NaT'), np.datetime64('2024-01-01')]).astype(int)`, for the reason that there is no integer equivalent of `NaT`, the way `np.nan` is the floating-point equivalent of `NaT`.

**Comment by Wainberg** [comment]
More broadly, I would also allow `casting=safe` to convert object-dtyped arrays to non-object-dtyped arrays as long as the underlying values stay the same, rather than always raising an error. There's currently no middle ground between not being able to cast at all, with `casting='safe'`:

```python
>>> np.array([np.datetime64('2024-01-01')], dtype=object).astype('datetime64[ns]', casting='safe')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Cannot cast array data from dtype('O') to dtype('<M8[ns]') according to the rule 'safe'
```

and allowing unsafe casts when there are mixes of e.g. datetimes and ints, with the default `casting='unsafe'`:

```python
>>> np.array([np.datetime64('2024-01-01'), 1], dtype=object).astype('datetime64[ns]')
array(['2024-01-01T00:00:00.000000000', '1970-01-01T00:00:00.000000001'],
      dtype='datetime64[ns]')
```

This is also a problem for mixes of strings and integers: `np.array(['1'], dtype=object).astype(str, casting='safe')` is disallowed, but `.astype(str)` risks converting integers to strings.

**Comment by ngoldbaum** [comment]
> More broadly, I would also allow casting=safe to convert object-dtyped arrays to non-object-dtyped arrays as long as the underlying values stay the same, rather than always raising an error.

A problem with this is that casting safety generally doesn't consider array values (this is known as value-based promotion). HIstorically numpy did that and still does to some extent but it's something we're trying to move away from rather than add more of it.

That said, object dtype is a special case.

**Comment by cmsxbc** [comment]
I have no idea what is the best choice, but I'd like to append some cases for reference.

1. for int `-9223372036854775808` will converted to `NaT`, but any other negatives will convert to the time before unix epoch.
``` Python
>>> np.array(-2**63).astype('M8[ns]')
array('NaT', dtype='datetime64[ns]')
>>> np.array(-2**63, dtype=object).astype('M8[ns]')
array('NaT', dtype='datetime64[ns]')
>>> np.array(-2**63+1, dtype=object).astype('M8[ns]')
array('1677-09-21T00:12:43.145224193', dtype='datetime64[ns]')
>>> np.array(-2**63+1).astype('M8[ns]')
array('1677-09-21T00:12:43.145224193', dtype='datetime64[ns]')
>>> (np.array(-2**63+1).astype('M8[ns]') - np.timedelta64(1)).astype(int).astype('M8[ns]')
numpy.datetime64('NaT')
```
2. for float, `float(-9223372036854775808)` will also converted to `NaT`. but object array is not possibale
```Python
>>> np.array(float(-9223372036854775808)).astype('M8[ns]')
array('NaT', dtype='datetime64[ns]')
>>> np.array(float(-9223372036854775808), dtype=object).astype('M8[ns]')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: Could not convert object to NumPy datetime
``` 
3. for generic float, there is similar behavior with int, but for more special values can be casting to `NaT`
```Python
>>> np.array(struct.unpack('!d', b'\xc3\xe0\x00\x00\x00\x00\x00\x00')[0]).astype('M8[ns]')
array('NaT', dtype='datetime64[ns]')
>>> np.array(struct.unpack('!d', b'\xca\xe0\x00\x00\x00\x00\x00\x00')[0]).astype('M8[ns]')
array('NaT', dtype='datetime64[ns]')
>>> np.array(struct.unpack('!d', b'\x1a\xe0\x00\x00\x00\x00\x00\x00')[0]).astype('M8[ns]')
array('1970-01-01T00:00:00.000000000', dtype='datetime64[ns]')
>>> (np.array(-2**63+1).astype('M8[ns]') - np.timedelta64(1)).astype(float).astype('M8[ns]')
numpy.datetime64('NaT')
```

4. Of couse, casting to another and casting back result in different thing is what `unsafe` permit. as nan does.
```Python
>>> np.array(np.nan).astype(int)
array(-9223372036854775808)
>>> np.array(np.nan).astype(int).astype(float)
array(-9.22337204e+18)
>>> np.array(np.nan, dtype=object).astype(int)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: cannot convert float NaN to integer
```

**Comment by j824h** [comment]
> Personally, I'd do the following:
> 
> 1. Make `np.array([np.datetime64('NaT'), np.datetime64('2024-01-01')]).astype(float)` return `np.array([np.nan, 19723.])` rather than `np.array([-9223372036854775808, 19723.])`.
> 2. Allow `np.array([np.datetime64('2024-01-01')], dtype=object).astype(int)` for consistency with the other three cases. However, I would disallow `np.array([np.datetime64('NaT'), np.datetime64('2024-01-01')]).astype(int)`, for the reason that there is no integer equivalent of `NaT`, the way `np.nan` is the floating-point equivalent of `NaT`.

I'm in support of this direction where NaT is converted to NaN as long as the target has NaN. This will especially help a use case in `matplotlib` where a sensible conversion of any `numbers.Number` including `timedelta64` into float seems to be assumed (#4604 still persists), although I'm not entirely sure if the registration of `timedelta64` as a subclass of `numbers.Number` was intentional. If `np.datetime64` either directly or transiting as `object` would need a similar treatment for consistency sake, it should be done.

I would be interested in contributing myself on thi.

**Comment by Hee-San** [comment]
I'd like to work on this.
I plan to open a PR that converts `NaT` to `NaN` when casting `datetime64` and `timedelta64` values to `floating-point` and `complex` types.
Casts to `integer` types and `bool` would stay unchanged.

A few people expressed interest in working on this earlier, but there has been no activity for almost two years since the last comment, so I'd like to take it over.
