### ISSUE TITLE
BUG: f2py Unable to compile a module(F77) without subroutines

### ISSUE THREAD

**Issue by xiangyi-wang** [numpy/numpy#26180]
### Describe the issue:

Unable to compile a module without subroutines using F77 . F90 has no problem

### Reproduce the code example:

```python
module constant
        !implicit none
        real,parameter::pi=3.1415926
        real,parameter::e=2.7182818
    
end module constant
```

### Error message:

```shell
/home/wxy/miniconda3/lib/python3.11/site-packages/numpy/f2py/f2py2e.py:719: VisibleDeprecationWarning: distutils has been deprecated since NumPy 1.26.xUse the Meson backend instead, or generate wrapperswithout -c and use a custom build script
  builder = build_backend(
running build
running config_cc
INFO: unifing config_cc, config, build_clib, build_ext, build commands --compiler options
running config_fc
INFO: unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
running build_src
INFO: build_src
INFO: building extension "moduledefs" sources
INFO: f2py options: []
INFO: f2py:> /tmp/tmp4la6ebee/src.linux-x86_64-3.11/moduledefsmodule.c
creating /tmp/tmp4la6ebee/src.linux-x86_64-3.11
Reading fortran codes...
        Reading file 'ModuleDefs.for' (format:fix,strict)
Line #43 in ModuleDefs.for:"      USE CSMVersion"
        analyzeline: no group yet. Creating program group with name "ModuleDefs".
Line #60 in ModuleDefs.for:"      INTEGER, PARAMETER ::     NL       = 20,  !Maximum number of soil layers     TS       = 24,  !Number of hourly time steps per day    NAPPL    = 9000,!Maximum number of applications or operations    NCOHORTS = 300, !Maximum number of cohorts    NELEM    = 3,   !Number of elements modeled (currently N & P)    NumOfDays = 1000, !Maximum days in sugarcane run (FSR)    NumOfStalks = 42, !Maximum stalks per sugarcane stubble (FSR)    EvaluateNum = 40, !Number of evaluation variables    MaxFiles = 500,   !Maximum number of output files    MaxPest = 500    !Maximum number of pest operations"
        updatevars: no name pattern found for entity='!maximum'. Skipping.
Line #60 in ModuleDefs.for:"      INTEGER, PARAMETER ::     NL       = 20,  !Maximum number of soil layers     TS       = 24,  !Number of hourly time steps per day    NAPPL    = 9000,!Maximum number of applications or operations    NCOHORTS = 300, !Maximum number of cohorts    NELEM    = 3,   !Number of elements modeled (currently N & P)    NumOfDays = 1000, !Maximum days in sugarcane run (FSR)    NumOfStalks = 42, !Maximum stalks per sugarcane stubble (FSR)    EvaluateNum = 40, !Number of evaluation variables    MaxFiles = 500,   !Maximum number of output files    MaxPest = 500    !Maximum number of pest operations"
        updatevars: no name pattern found for entity='!number'. Skipping.
Line #60 in ModuleDefs.for:"      INTEGER, PARAMETER ::     NL       = 20,  !Maximum number of soil layers     TS       = 24,  !Number of hourly time steps per day    NAPPL    = 9000,!Maximum number of applications or operations    NCOHORTS = 300, !Maximum number of cohorts    NELEM    = 3,   !Number of elements modeled (currently N & P)    NumOfDays = 1000, !Maximum days in sugarcane run (FSR)    NumOfStalks = 42, !Maximum stalks per sugarcane stubble (FSR)    EvaluateNum = 40, !Number of evaluation variables    MaxFiles = 500,   !Maximum number of output files    MaxPest = 500    !Maximum number of pest operations"
        updatevars: no name pattern found for entity='!maximum'. Skipping.
Line #60 in ModuleDefs.for:"      INTEGER, PARAMETER ::     NL       = 20,  !Maximum number of soil layers     TS       = 24,  !Number of hourly time steps per day    NAPPL    = 9000,!Maximum number of applications or operations    NCOHORTS = 300, !Maximum number of cohorts    NELEM    = 3,   !Number of elements modeled (currently N & P)    NumOfDays = 1000, !Maximum days in sugarcane run (FSR)    NumOfStalks = 42, !Maximum stalks per sugarcane stubble (FSR)    EvaluateNum = 40, !Number of evaluation variables    MaxFiles = 500,   !Maximum number of output files    MaxPest = 500    !Maximum number of pest operations"
        updatevars: no name pattern found for entity='!maximum'. Skipping.
Line #60 in ModuleDefs.for:"      INTEGER, PARAMETER ::     NL       = 20,  !Maximum number of soil layers     TS       = 24,  !Number of hourly time steps per day    NAPPL    = 9000,!Maximum number of applications or operations    NCOHORTS = 300, !Maximum number of cohorts    NELEM    = 3,   !Number of elements modeled (currently N & P)    NumOfDays = 1000, !Maximum days in sugarcane run (FSR)    NumOfStalks = 42, !Maximum stalks per sugarcane stubble (FSR)    EvaluateNum = 40, !Number of evaluation variables    MaxFiles = 500,   !Maximum number of output files    MaxPest = 500    !Maximum number of pest operations"
        updatevars: no name pattern found for entity='!number'. Skipping.
Line #60 in ModuleDefs.for:"      INTEGER, PARAMETER ::     NL       = 20,  !Maximum number of soil layers     TS       = 24,  !Number of hourly time steps per day    NAPPL    = 9000,!Maximum number of applications or operations    NCOHORTS = 300, !Maximum number of cohorts    NELEM    = 3,   !Number of elements modeled (currently N & P)    NumOfDays = 1000, !Maximum days in sugarcane run (FSR)    NumOfStalks = 42, !Maximum stalks per sugarcane stubble (FSR)    EvaluateNum = 40, !Number of evaluation variables    MaxFiles = 500,   !Maximum number of output files    MaxPest = 500    !Maximum number of pest operations"
        updatevars: could not crack entity declaration "modeled(currently n & p)numofdays=1000". Ignoring.
Line #60 in ModuleDefs.for:"      INTEGER, PARAMETER ::     NL       = 20,  !Maximum number of soil layers     TS       = 24,  !Number of hourly time steps per day    NAPPL    = 9000,!Maximum number of applications or operations    NCOHORTS = 300, !Maximum number of cohorts    NELEM    = 3,   !Number of elements modeled (currently N & P)    NumOfDays = 1000, !Maximum days in sugarcane run (FSR)    NumOfStalks = 42, !Maximum stalks per sugarcane stubble (FSR)    EvaluateNum = 40, !Number of evaluation variables    MaxFiles = 500,   !Maximum number of output files    MaxPest = 500    !Maximum number of pest operations"
        updatevars: no name pattern found for entity='!maximum'. Skipping.
Line #60 in ModuleDefs.for:"      INTEGER, PARAMETER ::     NL       = 20,  !Maximum number of soil layers     TS       = 24,  !Number of hourly time steps per day    NAPPL    = 9000,!Maximum number of applications or operations    NCOHORTS = 300, !Maximum number of cohorts    NELEM    = 3,   !Number of elements modeled (currently N & P)    NumOfDays = 1000, !Maximum days in sugarcane run (FSR)    NumOfStalks = 42, !Maximum stalks per sugarcane stubble (FSR)    EvaluateNum = 40, !Number of evaluation variables    MaxFiles = 500,   !Maximum number of output files    MaxPest = 500    !Maximum number of pest operations"
        updatevars: could not crack entity declaration "run(fsr)numofstalks=42". Ignoring.
Line #60 in ModuleDefs.for:"      INTEGER, PARAMETER ::     NL       = 20,  !Maximum number of soil layers     TS       = 24,  !Number of hourly time steps per day    NAPPL    = 9000,!Maximum number of applications or operations    NCOHORTS = 300, !Maximum number of cohorts    NELEM    = 3,   !Number of elements modeled (currently N & P)    NumOfDays = 1000, !Maximum days in sugarcane run (FSR)    NumOfStalks = 42, !Maximum stalks per sugarcane stubble (FSR)    EvaluateNum = 40, !Number of evaluation variables    MaxFiles = 500,   !Maximum number of output files    MaxPest = 500    !Maximum number of pest operations"
        updatevars: no name pattern found for entity='!maximum'. Skipping.
Line #60 in ModuleDefs.for:"      INTEGER, PARAMETER ::     NL       = 20,  !Maximum number of soil layers     TS       = 24,  !Number of hourly time steps per day    NAPPL    = 9000,!Maximum number of applications or operations    NCOHORTS = 300, !Maximum number of cohorts    NELEM    = 3,   !Number of elements modeled (currently N & P)    NumOfDays = 1000, !Maximum days in sugarcane run (FSR)    NumOfStalks = 42, !Maximum stalks per sugarcane stubble (FSR)    EvaluateNum = 40, !Number of evaluation variables    MaxFiles = 500,   !Maximum number of output files    MaxPest = 500    !Maximum number of pest operations"
        updatevars: could not crack entity declaration "stubble(fsr)evaluatenum=40". Ignoring.
Line #60 in ModuleDefs.for:"      INTEGER, PARAMETER ::     NL       = 20,  !Maximum number of soil layers     TS       = 24,  !Number of hourly time steps per day    NAPPL    = 9000,!Maximum number of applications or operations    NCOHORTS = 300, !Maximum number of cohorts    NELEM    = 3,   !Number of elements modeled (currently N & P)    NumOfDays = 1000, !Maximum days in sugarcane run (FSR)    NumOfStalks = 42, !Maximum stalks per sugarcane stubble (FSR)    EvaluateNum = 40, !Number of evaluation variables    MaxFiles = 500,   !Maximum number of output files    MaxPest = 500    !Maximum number of pest operations"
        updatevars: no name pattern found for entity='!number'. Skipping.
Line #60 in ModuleDefs.for:"      INTEGER, PARAMETER ::     NL       = 20,  !Maximum number of soil layers     TS       = 24,  !Number of hourly time steps per day    NAPPL    = 9000,!Maximum number of applications or operations    NCOHORTS = 300, !Maximum number of cohorts    NELEM    = 3,   !Number of elements modeled (currently N & P)    NumOfDays = 1000, !Maximum days in sugarcane run (FSR)    NumOfStalks = 42, !Maximum stalks per sugarcane stubble (FSR)    EvaluateNum = 40, !Number of evaluation variables    MaxFiles = 500,   !Maximum number of output files    MaxPest = 500    !Maximum number of pest operations"
        updatevars: no name pattern found for entity='!maximum'. Skipping.
Line #86 in ModuleDefs.for:"      CHARACTER(LEN=6)  LIBRARY    !library required for system calls"
        updatevars: could not crack entity declaration "library!library". Ignoring.
rmbadname1: Replacing "for" with "for_bn".
Line #109 in ModuleDefs.for:"        INTEGER   FODAT, ENDYRS  !Forecast start date and ensemble #"
        updatevars: could not crack entity declaration "endyrs!forecast". Ignoring.
Line #109 in ModuleDefs.for:"        INTEGER   FODAT, ENDYRS  !Forecast start date and ensemble #"
        updatevars: no name pattern found for entity='#'. Skipping.
Line #124 in ModuleDefs.for:"        CHARACTER (len=1) METMP !Temperature, EPIC"
        updatevars: no name pattern found for entity='!temperature'. Skipping.
Traceback (most recent call last):
  File "/home/wxy/miniconda3/bin/f2py", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/wxy/miniconda3/lib/python3.11/site-packages/numpy/f2py/f2py2e.py", line 766, in main
    run_compile()
  File "/home/wxy/miniconda3/lib/python3.11/site-packages/numpy/f2py/f2py2e.py", line 738, in run_compile
    builder.compile()
  File "/home/wxy/miniconda3/lib/python3.11/site-packages/numpy/f2py/_backends/_distutils.py", line 71, in compile
    setup(ext_modules=[ext])
  File "/home/wxy/miniconda3/lib/python3.11/site-packages/numpy/distutils/core.py", line 170, in setup
    return old_setup(**new_attr)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/wxy/miniconda3/lib/python3.11/site-packages/setuptools/__init__.py", line 107, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wxy/miniconda3/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
           ^^^^^^^^^^^^^^^^^^
  File "/home/wxy/miniconda3/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/wxy/miniconda3/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/home/wxy/miniconda3/lib/python3.11/site-packages/setuptools/dist.py", line 1234, in run_command
    super().run_command(command)
  File "/home/wxy/miniconda3/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/wxy/miniconda3/lib/python3.11/site-packages/numpy/distutils/command/build.py", line 62, in run
    old_build.run(self)
  File "/home/wxy/miniconda3/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 131, in run
    self.run_command(cmd_name)
  File "/home/wxy/miniconda3/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/wxy/miniconda3/lib/python3.11/site-packages/setuptools/dist.py", line 1234, in run_command
    super().run_command(command)
  File "/home/wxy/miniconda3/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/wxy/miniconda3/lib/python3.11/site-packages/numpy/distutils/command/build_src.py", line 144, in run
    self.build_sources()
  File "/home/wxy/miniconda3/lib/python3.11/site-packages/numpy/distutils/command/build_src.py", line 161, in build_sources
    self.build_extension_sources(ext)
  File "/home/wxy/miniconda3/lib/python3.11/site-packages/numpy/distutils/command/build_src.py", line 321, in build_extension_sources
    sources = self.f2py_sources(sources, ext)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wxy/miniconda3/lib/python3.11/site-packages/numpy/distutils/command/build_src.py", line 562, in f2py_sources
    f2py2e.run_main(f2py_options + ['--lower',
  File "/home/wxy/miniconda3/lib/python3.11/site-packages/numpy/f2py/f2py2e.py", line 463, in run_main
    postlist = callcrackfortran(files, options)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wxy/miniconda3/lib/python3.11/site-packages/numpy/f2py/f2py2e.py", line 347, in callcrackfortran
    postlist = crackfortran.crackfortran(files)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wxy/miniconda3/lib/python3.11/site-packages/numpy/f2py/crackfortran.py", line 3531, in crackfortran
    readfortrancode(files, crackline)
  File "/home/wxy/miniconda3/lib/python3.11/site-packages/numpy/f2py/crackfortran.py", line 550, in readfortrancode
    dowithline(finalline)
  File "/home/wxy/miniconda3/lib/python3.11/site-packages/numpy/f2py/crackfortran.py", line 818, in crackline
    raise Exception('crackline: groupcounter(=%s) is nonpositive. '
Exception: crackline: groupcounter(=0) is nonpositive. Check the blocks.
```

### Python and NumPy Versions:

>>> import sys, numpy; print(numpy.__version__); print(sys.version)
1.26.4
3.11.5 (main, Sep 11 2023, 13:54:46) [GCC 11.2.0]

### Runtime Environment:

WSL ubuntu 22.4

**Comment by krisrosengreen** [comment]
I'm not entirely familiar with Fortran, but I believe modules were first introduced to Fortran in Fortran 90. Perhaps that's why the issue occurs when compiling from Fortran 77?

**Comment by xiangyi-wang** [comment]
I think so. Does f2py determine language standards based on suffix names? Is there an option to set the syntax version, for example: can the. for suffix be forced to be set to f90 syntax. Many old codes are a mix of f77 and f90.

**Comment by HaoZeke** [comment]
As this is a non-standard file extension issue I'm going to close this as a wontfix. A module cannot be parsed by a F77 compiler. My suggestion here would be to do a rename to the more generic `f90` file extension..
