### ISSUE TITLE
BUG: Cannot import numpy built with Intel oneAPI compiler icx and icpx

### ISSUE THREAD

**Issue by r-devulap** [numpy/numpy#26257]
### Describe the issue:

While I can build NumPy with icx and icpx compilers, it fails at import time. 

### Reproduce the code example:

```python
import numpy as np
```

### Error message:

```shell
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/numpy/_core/__init__.py", line 23, in <module>
    from . import multiarray
  File "/usr/local/lib/python3.10/dist-packages/numpy/_core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/usr/local/lib/python3.10/dist-packages/numpy/_core/overrides.py", line 8, in <module>
    from numpy._core._multiarray_umath import (
ImportError: /usr/local/lib/python3.10/dist-packages/numpy/_core/_multiarray_umath.cpython-310-x86_64-linux-gnu.so: undefined symbol: tan8_h

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/numpy/__init__.py", line 114, in <module>
    from numpy.__config__ import show as show_config
  File "/usr/local/lib/python3.10/dist-packages/numpy/__config__.py", line 4, in <module>
    from numpy._core._multiarray_umath import (
  File "/usr/local/lib/python3.10/dist-packages/numpy/_core/__init__.py", line 49, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.10 from "/usr/bin/python3"
  * The NumPy version is: "2.1.0.dev0+git20240402.4517378"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: /usr/local/lib/python3.10/dist-packages/numpy/_core/_multiarray_umath.cpython-310-x86_64-linux-gnu.so: undefined symbol: tan8_h
```

### Python and NumPy Versions:

'3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]'

**Comment by mattip** [comment]
Related to #25044
