### ISSUE TITLE
BUG: pytest fails with `ModuleNotFoundError: No module named 'utils'`

### ISSUE THREAD

**Issue by tuhinsharma121** [numpy/numpy#26356]
### Describe the issue:

I have followed the official build commands for editable install. But pytest fails with `ModuleNotFoundError: No module named 'utils'`

### Reproduce the code example:

```python
conda env create --file environment.yml
conda activate numpy-dev
git fetch upstream --tags
pip install --editable . --no-build-isolation  --config-settings editable-verbose=true
pytest numpy
```

### Error message:

```shell
=============================================================================================== test session starts ===============================================================================================
platform darwin -- Python 3.11.9, pytest-7.4.0, pluggy-1.5.0
rootdir: /Users/tuhinsharma/Documents/Git/numpy
configfile: pytest.ini
plugins: hypothesis-6.81.1, cov-4.1.0, xdist-3.5.0
collected 51576 items / 1 error / 2 skipped                                                                                                                                                                       

===================================================================================================== ERRORS ======================================================================================================
____________________________________________________________ ERROR collecting numpy/_core/src/common/pythoncapi-compat/tests/test_pythoncapi_compat.py ____________________________________________________________
ImportError while importing test module '/Users/tuhinsharma/Documents/Git/numpy/numpy/_core/src/common/pythoncapi-compat/tests/test_pythoncapi_compat.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/anaconda3/envs/numpy-dev/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
numpy/_core/src/common/pythoncapi-compat/tests/test_pythoncapi_compat.py:24: in <module>
    from utils import run_command, command_stdout
E   ModuleNotFoundError: No module named 'utils'
============================================================================================= short test summary info =============================================================================================
ERROR numpy/_core/src/common/pythoncapi-compat/tests/test_pythoncapi_compat.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
=========================================================================================== 2 skipped, 1 error in 8.73s ===========================================================================================
```

### Python and NumPy Versions:

Python 3.11.9
-e git+ssh://git@github.com/tuhinsharma121/numpy.git@552fdd4a476c6cc99a9f985493664f7279bbff65#egg=numpy

### Runtime Environment:

>>> import numpy; print(numpy.show_runtime())

meson-python: building numpy: /opt/anaconda3/envs/numpy-dev/bin/ninja
[1/1] Generating numpy/generate-version with a custom command
Saving version to numpy/version.py
[{'numpy_version': '2.1.0.dev0+git20240421.552fdd4',
  'python': '3.11.9 | packaged by conda-forge | (main, Apr 19 2024, 18:45:13) '
            '[Clang 16.0.6 ]',
  'uname': uname_result(system='Darwin', node='tuhsharm-mac', release='23.4.0', version='Darwin Kernel Version 23.4.0: Fri Mar 15 00:11:05 PDT 2024; root:xnu-10063.101.17~1/RELEASE_X86_64', machine='x86_64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3', 'SSSE3'],
                      'found': ['SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_KNL',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}}]
None

### Context for the issue:

I want to contribute to the project. Not getting my local test work is a blocker for it.

**Comment by mattip** [comment]
Those tests are in a submodule pulled in recently, and the tests cannot work without some refactoring. I wonder why our CI does not collect these and fail. @vstinner thoughts about how to work around this? Should we delete the tests?

**Comment by ngoldbaum** [comment]
I wonder why pytest doesn’t see https://github.com/numpy/numpy/blob/3d33d5f29baa5477e1f725310f0a1f94fb723108/pytest.ini#L3

**Comment by vstinner** [comment]
> @vstinner thoughts about how to work around this? Should we delete the tests?

I'm not used to pytest configuration. Obviously, yes, removing tests solve the issue.

**Comment by mattip** [comment]
I tried the commands at the top of the issue and the problem does not reproduce for me (on a macbook with arm64 processsor).

@tuhinsharma121 could you use some of the pytest options to try to figure out why the pytest.ini is ignored? Do you have anything special in your environment? Maybe try copying the `norecursedirs` value in a `--override-ini` command line option to pytest.

**Comment by tuhinsharma121** [comment]
I pulled the latest code.

```
pytest numpy
```
works fine now.

```
pytest
```
fails with
```
============================= test session starts ==============================
platform darwin -- Python 3.11.9, pytest-8.2.0, pluggy-1.5.0
rootdir: /Users/tuhinsharma/Documents/Git/numpy
configfile: pytest.ini
plugins: cov-5.0.0, xdist-3.5.0, hypothesis-6.100.2
collected 50626 items / 3 errors / 35 skipped

==================================== ERRORS ====================================
___________ ERROR collecting vendored-meson/meson/run_single_test.py ___________
vendored-meson/meson/run_single_test.py:16: in <module>
    from run_project_tests import TestDef, load_test_json, run_test, BuildStep, test_emits_skip_msg
        T          = <module 'typing' from '/opt/anaconda3/envs/numpy-dev/lib/python3.11/typing.py'>
        __builtins__ = <builtins>
        __cached__ = '/Users/tuhinsharma/Documents/Git/numpy/vendored-meson/meson/__pycache__/run_single_test.cpython-311.pyc'
        __doc__    = 'Script for running a single project test.\n\nThis script is meant for Meson developers who want to run a single project\ntest, with all of the rules from the test.json file loaded.\n'
        __file__   = '/Users/tuhinsharma/Documents/Git/numpy/vendored-meson/meson/run_single_test.py'
        __loader__ = <_pytest.assertion.rewrite.AssertionRewritingHook object at 0x103ba3810>
        __name__   = 'run_single_test'
        __package__ = ''
        __spec__   = ModuleSpec(name='run_single_test', loader=<_pytest.assertion.rewrite.AssertionRewritingHook object at 0x103ba3810>, origin='/Users/tuhinsharma/Documents/Git/numpy/vendored-meson/meson/run_single_test.py')
        argparse   = <module 'argparse' from '/opt/anaconda3/envs/numpy-dev/lib/python3.11/argparse.py'>
        mlog       = <module 'mesonbuild.mlog' from '/Users/tuhinsharma/Documents/Git/numpy/vendored-meson/meson/mesonbuild/mlog.py'>
        pathlib    = <module 'pathlib' from '/opt/anaconda3/envs/numpy-dev/lib/python3.11/pathlib.py'>
vendored-meson/meson/run_project_tests.py:128: in <module>
    python.sanity()
        ALL_TESTS  = ['cmake', 'common', 'native', 'warning-meson', 'failing-meson', 'failing-build', ...]
        Backend    = <enum 'Backend'>
        BuildStep  = <enum 'BuildStep'>
        CancelledError = <class 'concurrent.futures._base.CancelledError'>
        ConfigurationData = <class 'mesonbuild.build.ConfigurationData'>
        ET         = <module 'xml.etree.ElementTree' from '/opt/anaconda3/envs/numpy-dev/lib/python3.11/xml/etree/ElementTree.py'>
        Enum       = <enum 'Enum'>
        MachineChoice = <enum 'MachineChoice'>
        Path       = <class 'pathlib.Path'>
        Popen_safe = <function Popen_safe at 0x111e42ac0>
        ProcessPoolExecutor = <class 'concurrent.futures.process.ProcessPoolExecutor'>
        PurePath   = <class 'pathlib.PurePath'>
        PythonExternalProgram = <class 'mesonbuild.modules.python.PythonExternalProgram'>
        StringIO   = <class '_io.StringIO'>
        T          = <module 'typing' from '/opt/anaconda3/envs/numpy-dev/lib/python3.11/typing.py'>
        TemporaryDirectoryWinProof = <class 'mesonbuild.utils.universal.TemporaryDirectoryWinProof'>
        TestResult = <class 'run_project_tests.TestResult'>
        __annotations__ = {}
        __builtins__ = <builtins>
        __cached__ = '/Users/tuhinsharma/Documents/Git/numpy/vendored-meson/meson/__pycache__/run_project_tests.cpython-311.pyc'
        __doc__    = None
        __file__   = '/Users/tuhinsharma/Documents/Git/numpy/vendored-meson/meson/run_project_tests.py'
        __loader__ = <_frozen_importlib_external.SourceFileLoader object at 0x111e93350>
        __name__   = 'run_project_tests'
        __package__ = ''
        __spec__   = ModuleSpec(name='run_project_tests', loader=<_frozen_importlib_external.SourceFileLoader object at 0x111e93350>, origin='/Users/tuhinsharma/Documents/Git/numpy/vendored-meson/meson/run_project_tests.py')
        _pathlib   = <module 'mesonbuild._pathlib' from '/Users/tuhinsharma/Documents/Git/numpy/vendored-meson/meson/mesonbuild/_pathlib.py'>
        annotations = _Feature((3, 7, 0, 'beta', 1), None, 16777216)
        argparse   = <module 'argparse' from '/opt/anaconda3/envs/numpy-dev/lib/python3.11/argparse.py'>
        backendlist = ['ninja', 'vs', 'vs2010', 'vs2012', 'vs2013', 'vs2015', ...]
        blue       = <function blue at 0x111e10b80>
        bold       = <function bold at 0x111dc2ac0>
        build      = <module 'mesonbuild.build' from '/Users/tuhinsharma/Documents/Git/numpy/vendored-meson/meson/mesonbuild/build.py'>
        collections = <module 'collections' from '/opt/anaconda3/envs/numpy-dev/lib/python3.11/collections/__init__.py'>
        compiler_from_language = <function compiler_from_language at 0x111fb2b60>
        compilers  = <module 'mesonbuild.compilers' from '/Users/tuhinsharma/Documents/Git/numpy/vendored-meson/meson/mesonbuild/compilers/__init__.py'>
        cyan       = <function cyan at 0x111e10c20>
        detect_objc_compiler = <function detect_objc_compiler at 0x111fb3880>
        detect_objcpp_compiler = <function detect_objcpp_compiler at 0x111fb3920>
        ensure_backend_detects_changes = <function ensure_backend_detects_changes at 0x1123e8360>
        environment = <module 'mesonbuild.environment' from '/Users/tuhinsharma/Documents/Git/numpy/vendored-meson/meson/mesonbuild/environment.py'>
        functools  = <module 'functools' from '/opt/anaconda3/envs/numpy-dev/lib/python3.11/functools.py'>
        get_backend_args_for_dir = <function get_backend_args_for_dir at 0x1123e80e0>
        get_backend_commands = <function get_backend_commands at 0x1123e82c0>
        get_fake_options = <function get_fake_options at 0x1123d7ce0>
        get_meson_script = <function get_meson_script at 0x1123e8040>
        green      = <function green at 0x111e10a40>
        guess_backend = <function guess_backend at 0x1122e7a60>
        importlib  = <module 'importlib' from '/opt/anaconda3/envs/numpy-dev/lib/python3.11/importlib/__init__.py'>
        itertools  = <module 'itertools' (built-in)>
        json       = <module 'json' from '/opt/anaconda3/envs/numpy-dev/lib/python3.11/json/__init__.py'>
        meson_version = '1.2.99'
        mesonlib   = <module 'mesonbuild.mesonlib' from '/Users/tuhinsharma/Documents/Git/numpy/vendored-meson/meson/mesonbuild/mesonlib.py'>
        mlog       = <module 'mesonbuild.mlog' from '/Users/tuhinsharma/Documents/Git/numpy/vendored-meson/meson/mesonbuild/mlog.py'>
        mtest      = <module 'mesonbuild.mtest' from '/Users/tuhinsharma/Documents/Git/numpy/vendored-meson/meson/mesonbuild/mtest.py'>
        multiprocessing = <module 'multiprocessing' from '/opt/anaconda3/envs/numpy-dev/lib/python3.11/multiprocessing/__init__.py'>
        normal_green = <function normal_green at 0x111e10d60>
        os         = <module 'os' (frozen)>
        python     = <PythonExternalProgram '/opt/anaconda3/envs/numpy-dev/bin/python3.11' -> ['/opt/anaconda3/envs/numpy-dev/bin/python3.11']>
        re         = <module 're' from '/opt/anaconda3/envs/numpy-dev/lib/python3.11/re/__init__.py'>
        red        = <function red at 0x111e109a0>
        run_configure = <function run_configure at 0x1123e8680>
        setup_vsenv = <function setup_vsenv at 0x111e11440>
        shlex      = <module 'shlex' from '/opt/anaconda3/envs/numpy-dev/lib/python3.11/shlex.py'>
        shutil     = <module 'shutil' from '/opt/anaconda3/envs/numpy-dev/lib/python3.11/shutil.py'>
        signal     = <module 'signal' from '/opt/anaconda3/envs/numpy-dev/lib/python3.11/signal.py'>
        subprocess = <module 'subprocess' from '/opt/anaconda3/envs/numpy-dev/lib/python3.11/subprocess.py'>
        sys        = <module 'sys' (built-in)>
        tempfile   = <module 'tempfile' from '/opt/anaconda3/envs/numpy-dev/lib/python3.11/tempfile.py'>
        time       = <module 'time' (built-in)>
        yellow     = <function yellow at 0x111e10ae0>
vendored-meson/meson/mesonbuild/modules/python.py:74: in sanity
    ret = super().sanity()
        __class__  = <class 'mesonbuild.modules.python.PythonExternalProgram'>
        self       = <PythonExternalProgram '/opt/anaconda3/envs/numpy-dev/bin/python3.11' -> ['/opt/anaconda3/envs/numpy-dev/bin/python3.11']>
        state      = None
vendored-meson/meson/mesonbuild/dependencies/python.py:118: in sanity
    context_mgr = importlib.resources.path('mesonbuild.scripts', 'python_info.py')
        importlib  = <module 'importlib' from '/opt/anaconda3/envs/numpy-dev/lib/python3.11/importlib/__init__.py'>
        self       = <PythonExternalProgram '/opt/anaconda3/envs/numpy-dev/bin/python3.11' -> ['/opt/anaconda3/envs/numpy-dev/bin/python3.11']>
/opt/anaconda3/envs/numpy-dev/lib/python3.11/importlib/resources/_legacy.py:18: in wrapper
    warnings.warn(
E   DeprecationWarning: path is deprecated. Use files() instead. Refer to https://importlib-resources.readthedocs.io/en/latest/using.html#migrating-from-legacy for migration advice.
        args       = ('mesonbuild.scripts', 'python_info.py')
        func       = <function path at 0x1032ec720>
        kwargs     = {}
_ ERROR collecting vendored-meson/meson/test cases/common/26 find program/scripts/test_subdir.py _
vendored-meson/meson/test cases/common/26 find program/scripts/test_subdir.py:3: in <module>
    exit(0)
        __builtins__ = <builtins>
        __cached__ = '/Users/tuhinsharma/Documents/Git/numpy/vendored-meson/meson/test cases/common/26 find program/scripts/__pycache__/test_subdir.cpython-311.pyc'
        __doc__    = None
        __file__   = '/Users/tuhinsharma/Documents/Git/numpy/vendored-meson/meson/test cases/common/26 find program/scripts/test_subdir.py'
        __loader__ = <_pytest.assertion.rewrite.AssertionRewritingHook object at 0x103ba3810>
        __name__   = 'test_subdir'
        __package__ = ''
        __spec__   = ModuleSpec(name='test_subdir', loader=<_pytest.assertion.rewrite.AssertionRewritingHook object at 0x103ba3810>, origin='/Users/tuhinsharma/Documents/Git/numpy/vendored-meson/meson/test cases/common/26 find program/scripts/test_subdir.py')
<frozen _sitebuiltins>:26: in __call__
    ???
E   SystemExit: 0
        code       = 0
        self       = Use exit() or Ctrl-D (i.e. EOF) to exit
_ ERROR collecting vendored-meson/meson/test cases/frameworks/1 boost/test_python_module.py _
vendored-meson/meson/test cases/frameworks/1 boost/test_python_module.py:2: in <module>
    sys.path.append(sys.argv[1])
E   IndexError: list index out of range
        __builtins__ = <builtins>
        __cached__ = '/Users/tuhinsharma/Documents/Git/numpy/vendored-meson/meson/test cases/frameworks/1 boost/__pycache__/test_python_module.cpython-311.pyc'
        __doc__    = None
        __file__   = '/Users/tuhinsharma/Documents/Git/numpy/vendored-meson/meson/test cases/frameworks/1 boost/test_python_module.py'
        __loader__ = <_pytest.assertion.rewrite.AssertionRewritingHook object at 0x103ba3810>
        __name__   = 'test_python_module'
        __package__ = ''
        __spec__   = ModuleSpec(name='test_python_module', loader=<_pytest.assertion.rewrite.AssertionRewritingHook object at 0x103ba3810>, origin='/Users/tuhinsharma/Documents/Git/numpy/vendored-meson/meson/test cases/frameworks/1 boost/test_python_module.py')
        sys        = <module 'sys' (built-in)>
=========================== short test summary info ============================
ERROR vendored-meson/meson/run_single_test.py - DeprecationWarning: path is deprecated. Use files() instead. Refer to https...
ERROR vendored-meson/meson/test cases/common/26 find program/scripts/test_subdir.py - SystemExit: 0
ERROR vendored-meson/meson/test cases/frameworks/1 boost/test_python_module.py - IndexError: list index out of range
!!!!!!!!!!!!!!!!!!! Interrupted: 3 errors during collection !!!!!!!!!!!!!!!!!!!!
======================== 35 skipped, 3 errors in 15.17s ========================
```

**Comment by tuhinsharma121** [comment]
I see the problem now. It runs fine from the terminal. But when I configure pytest from pycharm it fails with following error

```
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.0.dev0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen site>", line 626, in <module>
  File "<frozen site>", line 619, in main
  File "<frozen site>", line 558, in execsitecustomize
  File "/Users/tuhinsharma/Applications/PyCharm Professional.app/Contents/plugins/python/helpers/pycharm_matplotlib_backend/sitecustomize.py", line 43, in <module>
    import matplotlib
  File "/opt/anaconda3/envs/numpy-dev/lib/python3.11/site-packages/matplotlib/__init__.py", line 161, in <module>
    from . import _api, _version, cbook, _docstring, rcsetup
  File "/opt/anaconda3/envs/numpy-dev/lib/python3.11/site-packages/matplotlib/rcsetup.py", line 27, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "/opt/anaconda3/envs/numpy-dev/lib/python3.11/site-packages/matplotlib/colors.py", line 57, in <module>
    from matplotlib import _api, _cm, cbook, scale
  File "/opt/anaconda3/envs/numpy-dev/lib/python3.11/site-packages/matplotlib/scale.py", line 22, in <module>
    from matplotlib.ticker import (
  File "/opt/anaconda3/envs/numpy-dev/lib/python3.11/site-packages/matplotlib/ticker.py", line 143, in <module>
    from matplotlib import transforms as mtransforms
  File "/opt/anaconda3/envs/numpy-dev/lib/python3.11/site-packages/matplotlib/transforms.py", line 49, in <module>
    from matplotlib._path import (
AttributeError: _ARRAY_API not found
Launching pytest with arguments numpy --no-header --no-summary -q in /Users/tuhinsharma/Documents/Git/numpy

ImportError while loading conftest '/Users/tuhinsharma/Documents/Git/numpy/numpy/conftest.py'.
numpy/__init__.py:525: in <module>
    _core.multiarray._multiarray_umath._reload_guard()
E   UserWarning: The NumPy module was reloaded (imported a second time). This can in some cases result in small but subtle issues and is discouraged.

Process finished with exit code 4

Empty suite

Empty suite

```

It looks like pytest runner in pycharm has a dependency on matplotlib. And matplotlib is built with numpy 1.0 instead 2.0. Hence giving the error. I guess I have to wait for matplotlib to build with numpy 2.0 to use pycharm pytest runner which may take time.

**Comment by rgommers** [comment]
Please upgrade to Matplotlib 3.8.4, that is built against NumPy 2.0. 

The original issue here is resolved, so I'll close this. Thanks all.
