### ISSUE TITLE
BUG: numpy.strings.lstrip/strip/rstrip fails with nulls

### ISSUE THREAD

**Issue by lithomas1** [numpy/numpy#26390]
### Describe the issue:

When encountering a null value in numpy 2.0 StringDType'd array, we get

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/thomasli/opt/miniconda3/envs/pandas-dev/lib/python3.10/site-packages/numpy/_core/strings.py", line 881, in rstrip
    return _rstrip_whitespace(a)
ValueError: Cannot strip null values that are not strings
```

It is expected that the nulls are propagated.

### Reproduce the code example:

```python
import numpy as np
a = np.array(["a", "b", np.nan], dtype=np.dtypes.StringDType(na_object=np.nan))
np.strings.rstrip(a)
np.strings.lstrip(a)
np.strings.strip(a)
```

### Error message:

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/thomasli/opt/miniconda3/envs/pandas-dev/lib/python3.10/site-packages/numpy/_core/strings.py", line 881, in rstrip
    return _rstrip_whitespace(a)
ValueError: Cannot strip null values that are not strings

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/thomasli/opt/miniconda3/envs/pandas-dev/lib/python3.10/site-packages/numpy/_core/strings.py", line 926, in strip
    return _strip_whitespace(a)
ValueError: Cannot strip null values that are not strings

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/thomasli/opt/miniconda3/envs/pandas-dev/lib/python3.10/site-packages/numpy/_core/strings.py", line 840, in lstrip
    return _lstrip_whitespace(a)
ValueError: Cannot strip null values that are not strings
```

### Python and NumPy Versions:

2.1.0.dev0+git20240424.f8392ce

**Comment by ngoldbaum** [comment]
Updated the script to use `np.nan`, which should work. Thanks for the report.

**Comment by ngoldbaum** [comment]
Opened https://github.com/numpy/numpy/pull/26392 with a fix.

**Comment by lithomas1** [comment]
Thx for the quick fix!
