### ISSUE TITLE
BUG: <Please write a comprehensive title after the 'BUG: ' prefix>ImportError: Error importing numpy: you should not try to import numpy from its source directory; please exit the numpy source tree, and relaunch your python interpreter from there.

### ISSUE THREAD

**Issue by zp2546265641** [numpy/numpy#26451]
### Describe the issue:

i just try to use urx to control ur real robor, but when i import, "no mudule urx"problem happened.and even when i add "export PYTHONPATH=$PYTHONPATH:/home/zp/anaconda3/envs/yiye/lib/python3.9/site-packages/" to point the package road, it tells me below.

### Reproduce the code example:

```python
#! /home/zp/anaconda3/envs/yiye/bin/python
import urx
import logging

if __name__ == "__main__":
    try:
        logging.basicConfig(level=logging.INFO)
        robot = urx.Robot("192.168.0.10")
        end_effector_pose = robot.getl()
        print("末端位姿：", end_effector_pose)
    finally:
        robot.close()
```

### Error message:

```shell
Traceback (most recent call last):
  File "/home/zp/catkin_ws/devel/lib/motion_planing/test.py", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/home/zp/catkin_ws/src/motion_planing/scripts/test.py", line 2, in <module>
    import urx
ModuleNotFoundError: No module named 'urx'
(yiye) zp@zp-ros:~/catkin_ws$ export PYTHONPATH=$PYTHONPATH:/home/zp/anaconda3/envs/yiye/lib/python3.9/site-packages/
(yiye) zp@zp-ros:~/catkin_ws$ rosrun motion_planing test.py 
Traceback (most recent call last):
  File "/home/zp/anaconda3/envs/yiye/lib/python3.9/site-packages/numpy/core/__init__.py", line 24, in <module>
    from . import multiarray
  File "/home/zp/anaconda3/envs/yiye/lib/python3.9/site-packages/numpy/core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/home/zp/anaconda3/envs/yiye/lib/python3.9/site-packages/numpy/core/overrides.py", line 8, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zp/anaconda3/envs/yiye/lib/python3.9/site-packages/numpy/__init__.py", line 130, in <module>
    from numpy.__config__ import show as show_config
  File "/home/zp/anaconda3/envs/yiye/lib/python3.9/site-packages/numpy/__config__.py", line 4, in <module>
    from numpy.core._multiarray_umath import (
  File "/home/zp/anaconda3/envs/yiye/lib/python3.9/site-packages/numpy/core/__init__.py", line 50, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.8 from "/usr/bin/python3"
  * The NumPy version is: "1.26.4"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/zp/catkin_ws/devel/lib/motion_planing/test.py", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/home/zp/catkin_ws/src/motion_planing/scripts/test.py", line 2, in <module>
    import urx
  File "/home/zp/anaconda3/envs/yiye/lib/python3.9/site-packages/urx/__init__.py", line 4, in <module>
    from urx.urrobot import RobotException, URRobot  # noqa
  File "/home/zp/anaconda3/envs/yiye/lib/python3.9/site-packages/urx/urrobot.py", line 9, in <module>
    from urx import urrtmon
  File "/home/zp/anaconda3/envs/yiye/lib/python3.9/site-packages/urx/urrtmon.py", line 14, in <module>
    import numpy as np
  File "/home/zp/anaconda3/envs/yiye/lib/python3.9/site-packages/numpy/__init__.py", line 135, in <module>
    raise ImportError(msg) from e
ImportError: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.
```

### Python and NumPy Versions:

>>> print(numpy.__version__)
1.26.4
>>> print(sys.version)
3.9.19 (main, May  6 2024, 19:43:03) 
[GCC 11.2.0]

**Comment by seberg** [comment]
If you look closely, you are using the wrong python version.  The website the error returns does make a note of that problem.  The way you are modifying your Python path is clearly wrong with respect to this when using a different Python.

**Comment by zp2546265641** [comment]
> If you look closely, you are using the wrong python version. The website the error returns does make a note of that problem. The way you are modifying your Python path is clearly wrong with respect to this when using a different Python.

yes，i do not know why it refers py3.8? and how can i fix it? i just use vscode and conda create -n yiye python = 3.9, and then conda activate, and then pip install urx. and then such problem.may be i need to recreate a conda environment with another py version. i am crying!!!
