### ISSUE TITLE
BUG: np.random.seed does not accept floats

### ISSUE THREAD

**Issue by bhimabi** [numpy/numpy#26535]
### Describe the issue:

I was trying to use a float as a seed for my numpy random number generator but I got the following error saying its the wrong type. I have set my numpy seed as a float before but now its no longer working now.

### Reproduce the code example:

```python
import numpy as np

np.random.seed(0.1)
```

### Error message:

```shell
Exception has occurred: TypeError       (note: full exception trace is shown but execution is paused at: <module>)
Cannot cast scalar from dtype('float64') to dtype('int64') according to the rule 'safe'
TypeError: 'float' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "mtrand.pyx", line 4789, in numpy.random.mtrand.seed
  File "mtrand.pyx", line 250, in numpy.random.mtrand.RandomState.seed
  File "_mt19937.pyx", line 166, in numpy.random._mt19937.MT19937._legacy_seeding
  File "_mt19937.pyx", line 186, in numpy.random._mt19937.MT19937._legacy_seeding

TypeError: Cannot cast scalar from dtype('float64') to dtype('int64') according to the rule 'safe'
```
```


### Python and NumPy Versions:

Python 3.8.10 (default, Nov 22 2023, 10:22:35) 
[GCC 9.4.0]
Numpy 1.24.4

### Runtime Environment:

[{'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_KNL',
                                    'AVX512_KNM',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}},
 {'architecture': 'Haswell',
  'filepath': '/home/asubbara/venv/lib/python3.8/site-packages/numpy.libs/libopenblas64_p-r0-15028c96.3.21.so',
  'internal_api': 'openblas',
  'num_threads': 20,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.21'}]

### Context for the issue:

I use a random number to generate multiple random numbers. Each of these numbers are used as 'sub-seeds' when i run the rest of my code in parallel

**Comment by rkern** [comment]
A float has never been a documented allowable value. In those older versions, it probably implicitly converted your float to an int (i.e. treated `0.1` as `0`) and now we correctly raise an exception. I don't think we'll be changing this back.
