### ISSUE TITLE
BUG: numpy.string.expandtabs segfault with extreme tab sizes

### ISSUE THREAD

**Issue by msimacek** [numpy/numpy#26556]
### Describe the issue:

I randomly noticed that if I slightly modify the existing test `test_expandtabs_raises_overflow` in `test_strings.py`, I get a segmentation fault.

### Reproduce the code example:

```python
import numpy as np
np.strings.expandtabs(np.array("\t", dtype='S'), 2**61)
```

### Error message:

```shell
Segmentation fault
(gdb) bt
#0  __memset_avx2_unaligned_erms () at ../sysdeps/x86_64/multiarch/memset-vec-unaligned-erms.S:328
#1  0x00007f5143c9fab9 in int string_expandtabs_loop<(ENCODING)0>(PyArrayMethod_Context_tag*, char* const*, long const*, long const*, NpyAuxData_tag*) ()
   from /home/msimacek/tmp/cpython-venv/lib64/python3.12/site-packages/numpy/_core/_multiarray_umath.cpython-312-x86_64-linux-gnu.so
#2  0x00007f5143c60bed in try_trivial_single_output_loop (context=context@entry=0x7ffe7410d600, op=op@entry=0x7ffe7410cc00, order=order@entry=NPY_KEEPORDER, errormask=521)
    at ../numpy/_core/src/umath/ufunc_object.c:985
#3  0x00007f5143c6b46e in PyUFunc_GenericFunctionInternal (wheremask=<optimized out>, order=<optimized out>, casting=<optimized out>, op=0x7ffe7410cc00, operation_descrs=0x7ffe7410d000, 
    ufuncimpl=<optimized out>, ufunc=<optimized out>) at ../numpy/_core/src/umath/ufunc_object.c:2257
#4  ufunc_generic_fastcall (ufunc=<optimized out>, args=<optimized out>, len_args=<optimized out>, kwnames=<optimized out>, outer=<optimized out>) at ../numpy/_core/src/umath/ufunc_object.c:4533
#5  0x00007f515220746c in PyObject_Vectorcall () from /lib64/libpython3.12.so.1.0
#6  0x00007f515210f7c7 in _PyEval_EvalFrameDefault.cold () from /lib64/libpython3.12.so.1.0
#7  0x00007f5152278b36 in PyEval_EvalCode () from /lib64/libpython3.12.so.1.0
#8  0x00007f515229edba in run_eval_code_obj () from /lib64/libpython3.12.so.1.0
#9  0x00007f515229947e in run_mod () from /lib64/libpython3.12.so.1.0
#10 0x00007f51521defec in PyRun_InteractiveOneObjectEx () from /lib64/libpython3.12.so.1.0
#11 0x00007f51521df1ea in _PyRun_InteractiveLoopObject () from /lib64/libpython3.12.so.1.0
#12 0x00007f51521515a3 in _PyRun_AnyFileObject.cold () from /lib64/libpython3.12.so.1.0
#13 0x00007f51521df3e2 in PyRun_AnyFileExFlags () from /lib64/libpython3.12.so.1.0
#14 0x00007f51521469c0 in Py_RunMain.cold () from /lib64/libpython3.12.so.1.0
#15 0x00007f515226100c in Py_BytesMain () from /lib64/libpython3.12.so.1.0
#16 0x00007f5151e4614a in __libc_start_call_main (main=main@entry=0x55935bf81160 <main>, argc=argc@entry=1, argv=argv@entry=0x7ffe74111f78) at ../sysdeps/nptl/libc_start_call_main.h:58
#17 0x00007f5151e4620b in __libc_start_main_impl (main=0x55935bf81160 <main>, argc=1, argv=0x7ffe74111f78, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffe74111f68)
    at ../csu/libc-start.c:360
#18 0x000055935bf81095 in _start ()
```

### Python and NumPy Versions:

1.26.4
3.12.3 (main, Apr 17 2024, 00:00:00) [GCC 13.2.1 20240316 (Red Hat 13.2.1-7)]

### Context for the issue:

I'm a developer of GraalPy and I was originally trying to execute numpy's test suite on GraalPy. GraalPy has lower `sys.maxsize`, so it encounters the segfault in the aforementioned test even without modifications. We'd like to be able to run all the tests on GraalPy.

**Comment by ngoldbaum** [comment]
Ping @lysnikolaou in case you'd like to take a look.

**Comment by ngoldbaum** [comment]
Thanks for the report! I created #26589 with a fix.
