### ISSUE TITLE
`numpy.cumproduct` error on 2.0 maintenance branch for Python 3.9

### ISSUE THREAD

**Issue by fmigneault** [numpy/numpy#26781]
### Steps to reproduce:

1. Setup a Python 3.9 environment.
2. Run `pip install numpy`.
3. Check that 2.0.0 gets installed from pypi (using maintenance branch). 
4. Run some code that ends up calling `numpy.cumproduct`.

### Error message:

```shell
Traceback (most recent call last):
  File "/home/runner/work/weaver/weaver/tests/wps_restapi/test_status_codes.py", line 6, in <module>
    from tests.utils import get_test_weaver_app, setup_config_with_mongodb
  File "/home/runner/work/weaver/weaver/tests/utils.py", line 40, in <module>
    from weaver.app import main as weaver_app
  File "/home/runner/work/weaver/weaver/weaver/app.py", line 14, in <module>
    from weaver.database import get_db
  File "/home/runner/work/weaver/weaver/weaver/database/__init__.py", line 7, in <module>
    from weaver.database.mongodb import MongoDatabase
  File "/home/runner/work/weaver/weaver/weaver/database/mongodb.py", line 15, in <module>
    from weaver.store.mongodb import (
  File "/home/runner/work/weaver/weaver/weaver/store/mongodb.py", line 16, in <module>
    from weaver.datatype import Bill, Job, Process, Quote, Service, VaultFile
  File "/home/runner/work/weaver/weaver/weaver/datatype.py", line 40, in <module>
    from weaver.processes.convert import get_field, json2oas_io, normalize_ordered_io, null, ows2json, wps2json_io
  File "/home/runner/work/weaver/weaver/weaver/processes/convert.py", line 18, in <module>
    import pint
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/pint/__init__.py", line 29, in <module>
    from .registry import ApplicationRegistry, LazyRegistry, UnitRegistry
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/pint/registry.py", line 20, in <module>
    from . import facets
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/pint/facets/__init__.py", line 83, in <module>
    from .numpy import NumpyRegistry, GenericNumpyRegistry
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/pint/facets/numpy/__init__.py", line 13, in <module>
    from .registry import NumpyRegistry, GenericNumpyRegistry
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/pint/facets/numpy/registry.py", line 16, in <module>
    from .quantity import NumpyQuantity
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/pint/facets/numpy/quantity.py", line 21, in <module>
    from .numpy_func import (
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/pint/facets/numpy/numpy_func.py", line 969, in <module>
    implement_single_dimensionless_argument_func(func_str)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/pint/facets/numpy/numpy_func.py", line 958, in implement_single_dimensionless_argument_func
    func = getattr(np, func_str)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/numpy/__init__.py", line 410, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'cumproduct'
```

### Additional information:

Example error seen here: 
https://github.com/crim-ca/weaver/actions/runs/9622250362/job/26543276200

**Comment by andyfaff** [comment]
The [migration guide](https://numpy.org/devdocs/numpy_2_0_migration_guide.html#main-namespace) for np==2 outlines that you need to use `np.cumprod`, and that `np.cumproduct` is not available anymore.

**Comment by disarticulate** [comment]
curious why one wouldn't stub out cumproduct to point to cumprod, can't see how that'd bother anyone.
