### ISSUE TITLE
BUG:  issubdtype and iinfo disagree on whether timedelta is an integer

### ISSUE THREAD

**Issue by gerritholl** [numpy/numpy#26861]
### Describe the issue:

According to `np.issubdtype("m8", np.integer)`, timedelta should be considered an integer dtype.  I would expect that any integer dtype is accepted by `np.iinfo`, but not so: `np.iinfo("m8")` fails with `ValueError`.

### Reproduce the code example:

```python
import numpy as np
print(np.issubdtype("m8", np.integer))
print(np.iinfo("m8"))
```

### Error message:

```shell
True
Traceback (most recent call last):
  File "/data/gholl/checkouts/protocode/mwe/np-timedelta-int.py", line 3, in <module>
    print(np.iinfo("m8"))
          ^^^^^^^^^^^^^^
  File "/data/gholl/mambaforge/envs/npy2/lib/python3.12/site-packages/numpy/_core/getlimits.py", line 697, in __init__
    raise ValueError("Invalid integer data type %r." % (self.kind,))
ValueError: Invalid integer data type 'm'.
```

### Python and NumPy Versions:

2.0.0
3.12.4 | packaged by conda-forge | (main, Jun 17 2024, 10:23:07) [GCC 12.3.0]

### Runtime Environment:

[{'numpy_version': '2.0.0',
  'python': '3.12.4 | packaged by conda-forge | (main, Jun 17 2024, 10:23:07) '
            '[GCC 12.3.0]',
  'uname': uname_result(system='Linux', node='oflws222', release='5.3.18-150300.59.106-default', version='#1 SMP Mon Dec 12 13:16:24 UTC 2022 (774239c)', machine='x86_64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_KNL',
                                    'AVX512_KNM',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL',
                                    'AVX512_SPR']}},
 {'architecture': 'Haswell',
  'filepath': '/data/gholl/mambaforge/envs/npy2/lib/libopenblasp-r0.3.27.so',
  'internal_api': 'openblas',
  'num_threads': 8,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.27'}]

### Context for the issue:

I can deal with timedelta being integers or not.  But I think users should be able to expect that any dtype x for which `npissubdtype(x, np.integer)` holds, should also be a valid argument to `np.iinfo`.  Either the former is False and the latter a ValueError, or the former is True and the latter works, but it is unexpected for the former to be True and the latter to fail with ValueError.

**Comment by rgommers** [comment]
I think it's simply an implementation oddity that `timedelta` is registered as a subdtype of `integer`. Any datetime/timedelta dtypes are not integers, but semantically a completely different thing that just happen to be implemented based on integers. So I wouldn't expect `np.iinfo` to say anything about these dtypes. I also wouldn't call this a bug though, just a minor inconsistency that would probably be very costly to change.

**Comment by seberg** [comment]
There is a slightly deeper problem here in that for promotion purposes timedelta's are also considered signed integers.

I agree that this is a bug and we should aim to changing it.  There were some issues about it last time I had a look (I don't recall exactly).
The history of it is presumably that it was a quick way to make `timedelta64/datetime64 + integer` work via the old default "search until one can cast" promotion logic.  But all of these require special handling anyway, so the simplicity gain here is not really worth the trouble of doing the incorrect definition.

These things usually come with other more niche problems and I am not sure how big they are.  But overall, I think this needs to be changed eventually but it may not be quite simple.
