### ISSUE TITLE
Consistent Errors With Numpy Dependencies In Firebase Functions + M3 Mac

### ISSUE THREAD

**Issue by nicholasrossano** [numpy/numpy#26918]
### Steps to reproduce:

Hi, I’m developing an iOS app in SwiftUI via XCode on a MacBook Pro (M3 Max) and incorporating Firebase Functions into the project. I’ve been successfully running basic functions, but recently ran into a wall when I tried to add my functions that incorporate dependencies with numpy. The error is really consistent and I’ve tried a number of steps, listed below. The whole log of errors is listed below. It seems to be an architecture issue, but most solutions I find online seem address numpy + Apple Silicon, whereas **my issue seems specific to Numpy + Apple Silicon + Firebase Functions**. Any help would be greatly appreciated, have really hit a wall.

Steps I’ve tried:

1. Verified core Firebase Functions: I have shipped basic Cloud Functions and iterated on them consistently, so it’s not a core Firebase issue.
2. Verified Numpy on local device: I created a test script importing and using Numpy and it successfully ran.
3. Tried multiple virtual environments: I have tried the native venv environment initialized by Firebase and created my own virtual environment using Conda’s Miniforge as I’ve read it works better with the Apple Silicon architecture, but I still get the same error each time.
4. Tested different functions: The error seems to be consistent across all numpy-related dependencies. I have a few functions I was working on, and tried basic (numpy-related) test functions, and the error was consistent across, whether it used transformers or scikit or whatever else.
5. Installing and reinstalling dependencies: I have also reconfigured my requirements.txt file several times, from hard-coding versions to ranges to no versions specified and the error remains the same.
6. Other solutions I’ve tried to incorporate, though these seem tailored to getting numpy to work on the laptop itself which isn’t my issue directly:
    a. Running conda install cython pybind11 then pip install --no-binary :all: numpy as advised [here](https://github.com/numpy/numpy/issues/24961) and similarly [here](https://stackoverflow.com/questions/65336789/numpy-build-fail-in-m1-big-sur-11-1)
    b. I tried uninstalling numpy and running arch -arm64 pip install numpy as advised [here](https://stackoverflow.com/questions/71745890/incompatible-architecture-have-arm64-need-x86-64-error-while-installing)
    c. I tried to follow the [numpy.org instructions](http://numpy.org/) they linked to, but they seem fairly generic and I couldn’t resolve my issue with them.

### Error message:

```shell
[2024-07-11 18:58:08,231] ERROR in app: Exception on /__/functions.yaml [GET]
Traceback (most recent call last):
  File "/Users/nicholas/Development/project/functions/venv/lib/python3.12/site-packages/numpy/_core/__init__.py", line 23, in <module>
    from . import multiarray
  File "/Users/nicholas/Development/project/functions/venv/lib/python3.12/site-packages/numpy/_core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/Users/nicholas/Development/project/functions/venv/lib/python3.12/site-packages/numpy/_core/overrides.py", line 8, in <module>
    from numpy._core._multiarray_umath import (
ImportError: dlopen(/Users/nicholas/Development/project/functions/venv/lib/python3.12/site-packages/numpy/_core/_multiarray_umath.cpython-312-darwin.so, 0x0002): tried: '/Users/nicholas/Development/project/functions/venv/lib/python3.12/site-packages/numpy/_core/_multiarray_umath.cpython-312-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/nicholas/Development/project/functions/venv/lib/python3.12/site-packages/numpy/_core/_multiarray_umath.cpython-312-darwin.so' (no such file), '/Users/nicholas/Development/project/functions/venv/lib/python3.12/site-packages/numpy/_core/_multiarray_umath.cpython-312-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/nicholas/Development/project/functions/venv/lib/python3.12/site-packages/numpy/__init__.py", line 114, in <module>
    from numpy.__config__ import show as show_config
  File "/Users/nicholas/Development/project/functions/venv/lib/python3.12/site-packages/numpy/__config__.py", line 4, in <module>
    from numpy._core._multiarray_umath import (
  File "/Users/nicholas/Development/project/functions/venv/lib/python3.12/site-packages/numpy/_core/__init__.py", line 49, in <module>
    raise ImportError(msg)
ImportError: 
IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.
We have compiled some common reasons and troubleshooting tips at:
    https://numpy.org/devdocs/user/troubleshooting-importerror.html
Please note and check the following:
  * The Python version is: Python3.12 from "/Users/nicholas/Development/project/functions/venv/bin/python3.12"
  * The NumPy version is: "2.0.0"
and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.
Original error was: dlopen(/Users/nicholas/Development/project/functions/venv/lib/python3.12/site-packages/numpy/_core/_multiarray_umath.cpython-312-darwin.so, 0x0002): tried: '/Users/nicholas/Development/project/functions/venv/lib/python3.12/site-packages/numpy/_core/_multiarray_umath.cpython-312-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/nicholas/Development/project/functions/venv/lib/python3.12/site-packages/numpy/_core/_multiarray_umath.cpython-312-darwin.so' (no such file), '/Users/nicholas/Development/project/functions/venv/lib/python3.12/site-packages/numpy/_core/_multiarray_umath.cpython-312-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/Users/nicholas/Development/project/functions/venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicholas/Development/project/functions/venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicholas/Development/project/functions/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicholas/Development/project/functions/venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicholas/Development/project/functions/venv/lib/python3.12/site-packages/firebase_functions/private/serving.py", line 122, in get_functions_yaml
    functions = get_functions()
                ^^^^^^^^^^^^^^^
  File "/Users/nicholas/Development/project/functions/venv/lib/python3.12/site-packages/firebase_functions/private/serving.py", line 40, in get_functions
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/nicholas/Development/project/functions/main.py", line 4, in <module>
    from classify_by_topic import classify_by_topic
  File "/Users/nicholas/Development/project/functions/classify_by_topic.py", line 1, in <module>
    from transformers import pipeline
  File "/Users/nicholas/Development/project/functions/venv/lib/python3.12/site-packages/transformers/__init__.py", line 26, in <module>
    from . import dependency_versions_check
  File "/Users/nicholas/Development/project/functions/venv/lib/python3.12/site-packages/transformers/dependency_versions_check.py", line 16, in <module>
    from .utils.versions import require_version, require_version_core
  File "/Users/nicholas/Development/project/functions/venv/lib/python3.12/site-packages/transformers/utils/__init__.py", line 34, in <module>
    from .generic import (
  File "/Users/nicholas/Development/project/functions/venv/lib/python3.12/site-packages/transformers/utils/generic.py", line 29, in <module>
    import numpy as np
  File "/Users/nicholas/Development/project/functions/venv/lib/python3.12/site-packages/numpy/__init__.py", line 119, in <module>
    raise ImportError(msg) from e
ImportError: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.
127.0.0.1 - - [11/Jul/2024 18:58:08] "GET /__/functions.yaml HTTP/1.1" 500 -
127.0.0.1 - - [11/Jul/2024 18:58:08] "GET /__/quitquitquit HTTP/1.1" 200 -
/bin/sh: line 1: 26364 Terminated: 15          python3.12 "/Users/nicholas/Development/project/functions/venv/lib/python3.12/site-packages/firebase_functions/private/serving.py"
```

**Comment by seberg** [comment]
The interesting line is (snipping and breaking it for clarity).
```
Original error was:
dlopen(.../python3.12/site-packages/numpy/_core/_multiarray_umath.cpython-312-darwin.so, 0x0002):
tried:
'.../python3.12/site-packages/numpy/_core/_multiarray_umath.cpython-312-darwin.so'
    (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')),
<snip some alternative paths, not sure but not relevant.>
```

I doubt your issue is specific to Firebase Functions although I guess that might be related to having an x86 Python there.  You are cross-compiling, right?
I think it is pretty clear here about what is wrong:  The module was compiled for arm64, but the Python you are running in is an x68 binary.

So not sure how to fix that.  Making sure local and mobile Python versions have the same architecture seems like a start to me, but I am not a (cross-)compilation/build setup specialist.

**Comment by nicholasrossano** [comment]
Do Firebase Functions require x86_64 architecture / cross-compilation to deploy if using an Apple Silicon Mac - is that what it means? Within my own purposes I have no reason to cross-compile, the Python scripts aren't compiled to the app itself so Firebase is their only destination.

Below I confirmed as best I could consistency in the arm64 architecture within my own environment; specifically, I believe my Python is also arm64.

- When I run `python --version uname -m` I get `Python 3.12.4 arm64`
- And when I run `find $(python -c "import numpy; print(numpy.__path__[0])") -name "*.so"` and then `file /file/name.so` on all of those, they all look to be arm64.

```
/Users/nicholas/miniforge3/envs/ponder_env/lib/python3.10/site-packages/numpy/random/_bounded_integers.cpython-310-darwin.so
/Users/nicholas/miniforge3/envs/ponder_env/lib/python3.10/site-packages/numpy/core/_umath_tests.cpython-310-darwin.so: Mach-O 64-bit bundle arm64
/Users/nicholas/miniforge3/envs/ponder_env/lib/python3.10/site-packages/numpy/core/_multiarray_umath.cpython-310-darwin.so: Mach-O 64-bit bundle arm64
/Users/nicholas/miniforge3/envs/ponder_env/lib/python3.10/site-packages/numpy/core/_simd.cpython-310-darwin.so: Mach-O 64-bit bundle arm64
/Users/nicholas/miniforge3/envs/ponder_env/lib/python3.10/site-packages/numpy/core/_operand_flag_tests.cpython-310-darwin.so: Mach-O 64-bit bundle arm64
/Users/nicholas/miniforge3/envs/ponder_env/lib/python3.10/site-packages/numpy/core/_rational_tests.cpython-310-darwin.so: Mach-O 64-bit bundle arm64
/Users/nicholas/miniforge3/envs/ponder_env/lib/python3.10/site-packages/numpy/core/_struct_ufunc_tests.cpython-310-darwin.so: Mach-O 64-bit bundle arm64
/Users/nicholas/miniforge3/envs/ponder_env/lib/python3.10/site-packages/numpy/core/_multiarray_tests.cpython-310-darwin.so: Mach-O 64-bit bundle arm64
/Users/nicholas/miniforge3/envs/ponder_env/lib/python3.10/site-packages/numpy/linalg/lapack_lite.cpython-310-darwin.so: Mach-O 64-bit bundle arm64
/Users/nicholas/miniforge3/envs/ponder_env/lib/python3.10/site-packages/numpy/linalg/_umath_linalg.cpython-310-darwin.so: Mach-O 64-bit bundle arm64
/Users/nicholas/miniforge3/envs/ponder_env/lib/python3.10/site-packages/numpy/fft/_pocketfft_internal.cpython-310-darwin.so: Mach-O 64-bit bundle arm64
/Users/nicholas/miniforge3/envs/ponder_env/lib/python3.10/site-packages/numpy/random/_common.cpython-310-darwin.so: Mach-O 64-bit bundle arm64
/Users/nicholas/miniforge3/envs/ponder_env/lib/python3.10/site-packages/numpy/random/mtrand.cpython-310-darwin.so: Mach-O 64-bit bundle arm64
/Users/nicholas/miniforge3/envs/ponder_env/lib/python3.10/site-packages/numpy/random/_sfc64.cpython-310-darwin.so: Mach-O 64-bit bundle arm64
/Users/nicholas/miniforge3/envs/ponder_env/lib/python3.10/site-packages/numpy/random/_generator.cpython-310-darwin.so: Mach-O 64-bit bundle arm64
/Users/nicholas/miniforge3/envs/ponder_env/lib/python3.10/site-packages/numpy/random/bit_generator.cpython-310-darwin.so: Mach-O 64-bit bundle arm64
/Users/nicholas/miniforge3/envs/ponder_env/lib/python3.10/site-packages/numpy/random/_pcg64.cpython-310-darwin.so: Mach-O 64-bit bundle arm64
/Users/nicholas/miniforge3/envs/ponder_env/lib/python3.10/site-packages/numpy/random/_philox.cpython-310-darwin.so: Mach-O 64-bit bundle arm64
/Users/nicholas/miniforge3/envs/ponder_env/lib/python3.10/site-packages/numpy/random/_mt19937.cpython-310-darwin.so: Mach-O 64-bit bundle arm64
/Users/nicholas/miniforge3/envs/ponder_env/lib/python3.10/site-packages/numpy/random/_bounded_integers.cpython-310-darwin.so: Mach-O 64-bit bundle arm64
```

**Comment by nicholasrossano** [comment]
Do Firebase Functions require x86_64 architecture / cross-compilation to deploy if using an Apple Silicon Mac - is that what it means? Within my own purposes I have no reason to cross-compile, the Python scripts aren't compiled to the app itself so Firebase is their only destination.

Below I confirmed as best I could consistency in the arm64 architecture within my own environment; specifically, I believe my Python is also arm64.

- When I run `python --version uname -m` I get Python 3.12.4 arm64
- And when I run `find $(python -c "import numpy; print(numpy.__path__[0])") -name "*.so"` and then `file /file/name.so` on all of those, they all look to be arm64.

```
/Users/nicholas/miniforge3/envs/project_env/lib/python3.10/site-packages/numpy/random/_bounded_integers.cpython-310-darwin.so
/Users/nicholas/miniforge3/envs/project_env/lib/python3.10/site-packages/numpy/core/_umath_tests.cpython-310-darwin.so: Mach-O 64-bit bundle arm64
/Users/nicholas/miniforge3/envs/project_env/lib/python3.10/site-packages/numpy/core/_multiarray_umath.cpython-310-darwin.so: Mach-O 64-bit bundle arm64
/Users/nicholas/miniforge3/envs/project_env/lib/python3.10/site-packages/numpy/core/_simd.cpython-310-darwin.so: Mach-O 64-bit bundle arm64
/Users/nicholas/miniforge3/envs/project_env/lib/python3.10/site-packages/numpy/core/_operand_flag_tests.cpython-310-darwin.so: Mach-O 64-bit bundle arm64
/Users/nicholas/miniforge3/envs/project_env/lib/python3.10/site-packages/numpy/core/_rational_tests.cpython-310-darwin.so: Mach-O 64-bit bundle arm64
/Users/nicholas/miniforge3/envs/project_env/lib/python3.10/site-packages/numpy/core/_struct_ufunc_tests.cpython-310-darwin.so: Mach-O 64-bit bundle arm64
/Users/nicholas/miniforge3/envs/project_env/lib/python3.10/site-packages/numpy/core/_multiarray_tests.cpython-310-darwin.so: Mach-O 64-bit bundle arm64
/Users/nicholas/miniforge3/envs/project_env/lib/python3.10/site-packages/numpy/linalg/lapack_lite.cpython-310-darwin.so: Mach-O 64-bit bundle arm64
/Users/nicholas/miniforge3/envs/project_env/lib/python3.10/site-packages/numpy/linalg/_umath_linalg.cpython-310-darwin.so: Mach-O 64-bit bundle arm64
/Users/nicholas/miniforge3/envs/project_env/lib/python3.10/site-packages/numpy/fft/_pocketfft_internal.cpython-310-darwin.so: Mach-O 64-bit bundle arm64
/Users/nicholas/miniforge3/envs/project_env/lib/python3.10/site-packages/numpy/random/_common.cpython-310-darwin.so: Mach-O 64-bit bundle arm64
/Users/nicholas/miniforge3/envs/project_env/lib/python3.10/site-packages/numpy/random/mtrand.cpython-310-darwin.so: Mach-O 64-bit bundle arm64
/Users/nicholas/miniforge3/envs/project_env/lib/python3.10/site-packages/numpy/random/_sfc64.cpython-310-darwin.so: Mach-O 64-bit bundle arm64
/Users/nicholas/miniforge3/envs/project_env/lib/python3.10/site-packages/numpy/random/_generator.cpython-310-darwin.so: Mach-O 64-bit bundle arm64
/Users/nicholas/miniforge3/envs/project_env/lib/python3.10/site-packages/numpy/random/bit_generator.cpython-310-darwin.so: Mach-O 64-bit bundle arm64
/Users/nicholas/miniforge3/envs/project_env/lib/python3.10/site-packages/numpy/random/_pcg64.cpython-310-darwin.so: Mach-O 64-bit bundle arm64
/Users/nicholas/miniforge3/envs/project_env/lib/python3.10/site-packages/numpy/random/_philox.cpython-310-darwin.so: Mach-O 64-bit bundle arm64
/Users/nicholas/miniforge3/envs/project_env/lib/python3.10/site-packages/numpy/random/_mt19937.cpython-310-darwin.so: Mach-O 64-bit bundle arm64
/Users/nicholas/miniforge3/envs/project_env/lib/python3.10/site-packages/numpy/random/_bounded_integers.cpython-310-darwin.so: Mach-O 64-bit bundle arm64

```

**Comment by nicholasrossano** [comment]
I tried this and have now progressed to the following error(s), taking the more verbiose ones from the logs. The error seems more generic now, but it's still incredibly reproducible. I can revert to my prior commit, everything works fine; I add the new function with the numpy-related package and the errors come back. I submitted a ticket to Firebase support too but I haven't heard back.

Thank you both for your advice thus far by the way, and any other advice you're able to offer :)

```
[error] /bin/sh: line 1: 44505 Illegal instruction: 4  python3.12 "/Users/nicholas/Development/project/Functions/venv/lib/python3.12/site-packages/firebase_functions/private/serving.py"

[debug] [2024-07-12T18:40:45.995Z] Failed to call quitquitquit. This often means the server failed to start request to http://127.0.0.1:8081/__/quitquitquit failed, reason: connect ECONNREFUSED 127.0.0.1:8081 {"message":"request to http://127.0.0.1:8081/__/quitquitquit failed, reason: connect ECONNREFUSED 127.0.0.1:8081","type":"system","errno":"ECONNREFUSED","code":"ECONNREFUSED"}
[debug] [2024-07-12T18:40:46.088Z] FetchError: request to http://127.0.0.1:8081/__/functions.yaml failed, reason: socket hang up
    at ClientRequest.<anonymous> (/Users/nicholas/.nvm/versions/node/v21.0.0/lib/node_modules/firebase-tools/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:515:28)
    at ClientRequest.emit (node:domain:488:12)
    at Socket.socketOnEnd (node:_http_client:519:9)
    at Socket.emit (node:events:527:35)
    at Socket.emit (node:domain:488:12)
    at endReadableNT (node:internal/streams/readable:1409:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[error] 
[error] Error: An unexpected error has occurred.
```

**Comment by ksmasood** [comment]
@nicholasrossano were you able to resolve this issue?
