### ISSUE TITLE
BUG: The truth value of an array with more than one element is ambiguous

### ISSUE THREAD

**Issue by jikechao** [numpy/numpy#26967]
### Describe the issue:

Crash unexpected for the following simple script!

### Reproduce the code example:

```python
import numpy as np

a = np.array([np.array([1,2,3]),np.array([1,2,3,4])], dtype=object)
print(a)
np.testing.assert_allclose(a, a)
```

### Error message:

```shell
Traceback (most recent call last):
  File "/root/.local/lib/python3.12/site-packages/numpy/testing/_private/utils.py", line 815, in assert_array_compare
    val = comparison(x, y)
          ^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.12/site-packages/numpy/testing/_private/utils.py", line 1679, in compare
    return np._core.numeric.isclose(x, y, rtol=rtol, atol=atol,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.12/site-packages/numpy/_core/numeric.py", line 2417, in isclose
    result = (less_equal(abs(x-y), atol + rtol * abs(y))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/share_container/optfuzz/res/../test2.py", line 5, in <module>
    np.testing.assert_allclose(a, a)
  File "/root/.local/lib/python3.12/site-packages/numpy/testing/_private/utils.py", line 1684, in assert_allclose
    assert_array_compare(compare, actual, desired, err_msg=str(err_msg),
  File "/root/miniconda3/lib/python3.12/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.12/site-packages/numpy/testing/_private/utils.py", line 893, in assert_array_compare
    raise ValueError(msg)
ValueError: 
error during assertion:

Traceback (most recent call last):
  File "/root/.local/lib/python3.12/site-packages/numpy/testing/_private/utils.py", line 815, in assert_array_compare
    val = comparison(x, y)
          ^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.12/site-packages/numpy/testing/_private/utils.py", line 1679, in compare
    return np._core.numeric.isclose(x, y, rtol=rtol, atol=atol,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.12/site-packages/numpy/_core/numeric.py", line 2417, in isclose
    result = (less_equal(abs(x-y), atol + rtol * abs(y))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

### Python and NumPy Versions:

2.0.0
3.12.3 | packaged by Anaconda, Inc. | (main, May  6 2024, 19:46:43) [GCC 11.2.0]

**Comment by rkern** [comment]
This is the expected output. `np.less_equal()` is expecting to be able to output a single Boolean scalar for each pair of items in the comparison. When you have arrays as items, you get a so-called rich comparison on each pair of items. `abs(a[0] - a[0]) <= atol+rtol*abs(a[0])` returns an array of Booleans. Trying to reduce an array of Booleans to a single Boolean raises that `ValueError`.

It seems like you are trying to implement ragged arrays, where you want the `assert_array_allclose()` to operate on pairs of elements in the lowest arrays. numpy simply does not implement ragged arrays.
