### ISSUE TITLE
Having Numpy 1.x with Python 3.12 (?)

### ISSUE THREAD

**Issue by mahmoodn** [numpy/numpy#26976]
Hi,
I am trying to install Numpy 1.x in a conda environment running Python 3.12. However, it seems that it is not compatible with higher Python versions like 3.12. Please see the output below:

```
(base) mahmood@rtx3080:~$ conda activate numpy_1_10
(numpy_1_10) mahmood@rtx3080:~$ pip --version
pip 24.0 from /home/mahmood/miniconda3/lib/python3.12/site-packages/pip (python 3.12)
(numpy_1_10) mahmood@rtx3080:~$ python --version
Python 3.12.4
(numpy_1_10) mahmood@rtx3080:~$ pip install --force-reinstall numpy==1.18.5
Collecting numpy==1.18.5
  Downloading numpy-1.18.5.zip (5.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.4/5.4 MB 28.3 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [56 lines of output]
      Running from numpy source directory.
      <string>:461: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
      /tmp/pip-install-9elxcnkc/numpy_e1c6e83e5f514f25913c48d510e5dc3c/tools/cythonize.py:75: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        required_version = LooseVersion('0.29.14')
      /tmp/pip-install-9elxcnkc/numpy_e1c6e83e5f514f25913c48d510e5dc3c/tools/cythonize.py:77: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        if LooseVersion(cython_version) < required_version:

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          cdef sfc64_state rng_state

          def __init__(self, seed=None):
              BitGenerator.__init__(self, seed)
              self._bitgen.state = <void *>&self.rng_state
              self._bitgen.next_uint64 = &sfc64_uint64
                                         ^
      ------------------------------------------------------------

      _sfc64.pyx:90:35: Cannot assign type 'uint64_t (*)(void *) except? -1 nogil' to 'uint64_t (*)(void *) noexcept nogil'. Exception values are incompatible. Suggest adding 'noexcept' to the type of the value being assigned.
      Processing numpy/random/_bounded_integers.pxd.in
      Processing numpy/random/_sfc64.pyx
      Traceback (most recent call last):
        File "/tmp/pip-install-9elxcnkc/numpy_e1c6e83e5f514f25913c48d510e5dc3c/tools/cythonize.py", line 238, in <module>
          main()
        File "/tmp/pip-install-9elxcnkc/numpy_e1c6e83e5f514f25913c48d510e5dc3c/tools/cythonize.py", line 234, in main
          find_process_files(root_dir)
        File "/tmp/pip-install-9elxcnkc/numpy_e1c6e83e5f514f25913c48d510e5dc3c/tools/cythonize.py", line 225, in find_process_files
          process(root_dir, fromfile, tofile, function, hash_db)
        File "/tmp/pip-install-9elxcnkc/numpy_e1c6e83e5f514f25913c48d510e5dc3c/tools/cythonize.py", line 191, in process
          processor_function(fromfile, tofile)
        File "/tmp/pip-install-9elxcnkc/numpy_e1c6e83e5f514f25913c48d510e5dc3c/tools/cythonize.py", line 80, in process_pyx
          subprocess.check_call(
        File "/home/mnaderan/miniconda3/lib/python3.12/subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/home/mnaderan/miniconda3/bin/python', '-m', 'cython', '-3', '--fast-fail', '-o', '_sfc64.c', '_sfc64.pyx']' returned non-zero exit status 1.
      Cythonizing sources
      Traceback (most recent call last):
        File "/home/mahmood/miniconda3/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/mahmood/miniconda3/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/mahmood/miniconda3/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-1nanwvae/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 368, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/tmp/pip-build-env-1nanwvae/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 497, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-1nanwvae/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 488, in <module>
        File "<string>", line 469, in setup_package
        File "<string>", line 275, in generate_cython
      RuntimeError: Running cythonize failed!
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```
What is the workaround for that? I would like to work with Numpy 1.x for a project.

**Comment by rgommers** [comment]
The latest NumPy 1.x version is `1.26.4`, and it supported Python 3.12. There are wheels for `cp312` at https://pypi.org/project/numpy/1.26.4/#files.

> `pip install --force-reinstall numpy==1.18.5`

Well don't do that please, that's a really old version.

**Comment by mahmoodn** [comment]
Correct. Thank you.
