### ISSUE TITLE
BUG: tests depend on availability of fortran compiler

### ISSUE THREAD

**Issue by h-vetinari** [numpy/numpy#27045]
In numpy 2.0.1, there's a failing test in [conda-forge](https://github.com/conda-forge/numpy-feedstock/pull/321) (`f2py/tests/test_regression.py::test_gh25784`)

<details>
<summary>Logs</summary>

```
=========================== short test summary info ============================
FAILED f2py/tests/test_regression.py::test_gh25784 - RuntimeError: Running f2py failed: ['-m', 'Blah', "--f77flags='-ffixed-form -O2'", '--f90flags="-ffixed-form -Og"', '/var/folders/6f/9bq719ks5ws4blpr063kpj840000gn/T/tmpcxdbx4rs/f77fixedform.f95', '--backend', 'meson']
Using meson backend
Will pass --lower to f2py
See https://numpy.org/doc/stable/f2py/buildtools/meson.html
Reading fortran codes...
	Reading file '/var/folders/6f/9bq719ks5ws4blpr063kpj840000gn/T/tmpcxdbx4rs/f77fixedform.f95' (format:free)
Line #2 in /var/folders/6f/9bq719ks5ws4blpr063kpj840000gn/T/tmpcxdbx4rs/f77fixedform.f95:"      subroutine mwe( "
	analyzeline: No name/args pattern found for line.
Post-processing...
	Block: Blah
			Block: unknown_subroutine
Applying post-processing hooks...
  character_backward_compatibility_hook
Post-processing (stage 2)...
Building modules...
    Building module "Blah"...
    Generating possibly empty wrappers"
    Maybe empty "Blah-f2pywrappers.f"
        Constructing wrapper function "unknown_subroutine"...
          unknown_subroutine()
    Wrote C/API module "Blah" to file "./Blahmodule.c"
The Meson build system
Version: 1.5.0
Source dir: /private/var/folders/6f/9bq719ks5ws4blpr063kpj840000gn/T/tmpp3kn95v4
Build dir: /private/var/folders/6f/9bq719ks5ws4blpr063kpj840000gn/T/tmpp3kn95v4/bbdir
Build type: native build
Project name: Blah
Project version: 0.1

meson.build:1:0: ERROR: Unknown compiler(s): [['gfortran'], ['flang'], ['nvfortran'], ['pgfortran'], ['ifort'], ['ifx'], ['g95']]
The following exception(s) were encountered:
Running `gfortran --version` gave "[Errno 2] No such file or directory: 'gfortran'"
Running `gfortran -V` gave "[Errno 2] No such file or directory: 'gfortran'"
Running `flang --version` gave "[Errno 2] No such file or directory: 'flang'"
Running `flang -V` gave "[Errno 2] No such file or directory: 'flang'"
Running `nvfortran --version` gave "[Errno 2] No such file or directory: 'nvfortran'"
Running `nvfortran -V` gave "[Errno 2] No such file or directory: 'nvfortran'"
Running `pgfortran --version` gave "[Errno 2] No such file or directory: 'pgfortran'"
Running `pgfortran -V` gave "[Errno 2] No such file or directory: 'pgfortran'"
Running `ifort --version` gave "[Errno 2] No such file or directory: 'ifort'"
Running `ifort -V` gave "[Errno 2] No such file or directory: 'ifort'"
Running `ifx --version` gave "[Errno 2] No such file or directory: 'ifx'"
Running `ifx -V` gave "[Errno 2] No such file or directory: 'ifx'"
Running `g95 --version` gave "[Errno 2] No such file or directory: 'g95'"
Running `g95 -V` gave "[Errno 2] No such file or directory: 'g95'"

A full log can be found at /private/var/folders/6f/9bq719ks5ws4blpr063kpj840000gn/T/tmpp3kn95v4/bbdir/meson-logs/meson-log.txt
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "$PREFIX/lib/python3.10/site-packages/numpy/f2py/f2py2e.py", line 769, in main
    run_compile()
  File "$PREFIX/lib/python3.10/site-packages/numpy/f2py/f2py2e.py", line 741, in run_compile
    builder.compile()
  File "$PREFIX/lib/python3.10/site-packages/numpy/f2py/_backends/_meson.py", line 193, in compile
    self.run_meson(self.build_dir)
  File "$PREFIX/lib/python3.10/site-packages/numpy/f2py/_backends/_meson.py", line 186, in run_meson
    self._run_subprocess_command(setup_command, build_dir)
  File "$PREFIX/lib/python3.10/site-packages/numpy/f2py/_backends/_meson.py", line 182, in _run_subprocess_command
    subprocess.run(command, cwd=cwd, check=True)
  File "$PREFIX/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['meson', 'setup', 'bbdir']' returned non-zero exit status 1.
1 failed, 48842 passed, 2696 skipped, 70 xfailed, 9 xpassed, 12 warnings in 194.61s (0:03:14)
```

</details>

Although it wouldn't be a big issue to add the fortran-compilers as a test-dependency, the decision the last time this happened (#21621; https://github.com/conda-forge/numpy-feedstock/pull/272) was that tests should not fail in this case.

CC @HaoZeke

**Comment by h-vetinari** [comment]
FWIW, this only seems to happen on osx (though on linux we _do_ add the fortran compilers, so this might be hidden there).

**Comment by ngoldbaum** [comment]
Probably just delete `Darwin` from the `skipif` - there are other tests that skip on MacOS because it assumes only Linux has compilers.

**Comment by rgommers** [comment]
That can't be the right fix, those tests should't need a per-test skip for compilers not installed (e.g., the one right above it has no skip condition at all). They call `build_module()` in `f2py/tests/util.py`, which contains this to handle the "no Fortran compiler" situation:
```python
    try:
        backend.compile()
    except subprocess.CalledProcessError:
        pytest.skip("Failed to compile module")
```

The problem seems to be that the `CalledProcessError` that's expected, and handled in the try-except above, doesn't actually bubble up far enough. It gets turned into `RuntimeError: Running f2py failed:` somewhere along the line, while that's not the case for the test above since it actually catches `RuntimeError` inside the test. 

Those are the only two tests that use `util.build_module`, and the other tests never gets to looking for a Fortran compiler. Hence, either the way the test is written is wrong because it's not robust against the no-compiler case, or `build_module` is trying to catch the wrong exception. I don't know which one it is, because it depends on the intent with which `build_module` was written. @HaoZeke thoughts?

**Comment by seberg** [comment]
A recent PR tried to use CalledProcessError.  Should have split that part out for backport maybe, I did feel it was plausible that it doesn't always work.

Makes sense to just replace it with `Exception` or nothing as a hot-fix, although it would be nice to figure out something specific (ideally probe once if things *should* work somehow).
