### ISSUE TITLE
NumPy fails with `version 'GLIBC_2.29' not found` on CentOS 7.9.2009

### ISSUE THREAD

**Issue by hadrizi** [numpy/numpy#27133]
### Steps to reproduce:

I am deploying the project on centos 7.9.2009 which uses glibc 2.17, thus I am building NumPy from sources so it will be compiled against system's glibc. Here is the way I am doing it
```Makefile
$(PACKAGES_DIR): $(WHEELS_DIR)
	## gather all project dependencies into $(PACKAGES_DIR)
	mkdir -p $(PACKAGES_DIR)
	$(VENV_PIP) --no-cache-dir wheel --find-links $(WHEELS_DIR) --wheel-dir $(PACKAGES_DIR) $(ROOT_DIR)
	
ifeq ($(INSTALL_NUMPY_FROM_SOURCES), true)
	rm -rf $(PACKAGES_DIR)/numpy*
	cp $(WHEELS_DIR)/numpy* $(PACKAGES_DIR)
endif

$(WHEELS_DIR): $(VENV_DIR)
	## gather all dependencies found in $(LIBS_DIR)
	mkdir -p $(WHEELS_DIR)
	$(VENV_PYTHON) setup.py egg_info
	cat admin_backend.egg-info/requires.txt \
		| sed -nE 's/^([a-zA-Z0-9_-]+)[>=~]?.*$$/\1/p' \
		| xargs -I'{}' echo $(LIBS_DIR)/'{}' \
		| xargs -I'{}' sh -c '[ -d "{}" ] && echo "{}" || true' \
		| xargs $(VENV_PIP) wheel --wheel-dir $(WHEELS_DIR) --no-deps

$(VENV_DIR):
	## create venv
	$(TARGET_PYTHON_VERSION) -m venv $(VENV_DIR)
	$(VENV_PIP) install pip==$(TARGET_PIP_VERSION)
	$(VENV_PIP) install setuptools==$(TARGET_SETUPTOOLS_VERSION) wheel==$(TARGET_WHEEL_VERSION)

ifeq ($(INSTALL_NUMPY_FROM_SOURCES), true)
	wget https://github.com/cython/cython/releases/download/0.29.31/Cython-0.29.31-py2.py3-none-any.whl
	$(VENV_PIP) install Cython-0.29.31-py2.py3-none-any.whl
	git clone https://github.com/numpy/numpy.git --depth 1 --branch v$(NUMPY_VERSION) 
	cd numpy && $(VENV_PIP) wheel --wheel-dir $(WHEELS_DIR) . && cd ..
endif
```

### Error message:

```shell
Aug 07 09:16:10 hostedtest admin_backend[8235]: Traceback (most recent call last):
Aug 07 09:16:11 hostedtest admin_backend[8235]: File "/opt/project/envs/eta/admin_backend/lib/python3.10/site-packages/admin_backend/domains/account/shared/reports/metrics_postprocessor/functions.py", line 6, in <module>
Aug 07 09:16:11 hostedtest admin_backend[8235]: import pandas as pd
Aug 07 09:16:11 hostedtest admin_backend[8235]: File "/opt/project/envs/eta/admin_backend/lib/python3.10/site-packages/pandas/__init__.py", line 16, in <module>
Aug 07 09:16:11 hostedtest admin_backend[8235]: raise ImportError(
Aug 07 09:16:11 hostedtest admin_backend[8235]: ImportError: Unable to import required dependencies:
Aug 07 09:16:11 hostedtest admin_backend[8235]: numpy:
Aug 07 09:16:11 hostedtest admin_backend[8235]: IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
Aug 07 09:16:11 hostedtest admin_backend[8235]: Importing the numpy C-extensions failed. This error can happen for
Aug 07 09:16:11 hostedtest admin_backend[8235]: many reasons, often due to issues with your setup or how NumPy was
Aug 07 09:16:11 hostedtest admin_backend[8235]: installed.
Aug 07 09:16:11 hostedtest admin_backend[8235]: We have compiled some common reasons and troubleshooting tips at:
Aug 07 09:16:11 hostedtest admin_backend[8235]: 
Aug 07 09:16:11 hostedtest admin_backend[8235]: Please note and check the following:
Aug 07 09:16:11 hostedtest admin_backend[8235]: * The Python version is: Python3.10 from "/opt/project/envs/eta/admin_backend/bin/python"
Aug 07 09:16:11 hostedtest admin_backend[8235]: * The NumPy version is: "1.21.0"
Aug 07 09:16:11 hostedtest admin_backend[8235]: and make sure that they are the versions you expect.
Aug 07 09:16:11 hostedtest admin_backend[8235]: Please carefully study the documentation linked above for further help.
Aug 07 09:16:11 hostedtest admin_backend[8235]: Original error was: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /opt/project/envs/eta/admin_backend/lib/python3.10/site-packages/numpy/core/_multiarray_umath.cpython-310-x86_64-linux-gnu.so)https://numpy.org/devdocs/user/troubleshooting-importerror.html
```
```


### Additional information:

I am trying to build NumPy 1.21
There is no option to update from this centos version

**Comment by mattip** [comment]
It seems you are building on a machine with GLIBC_2.29, and then running on one with GLIBC_2.17. You should probably just use the PyPI wheels which are built for manylinux2014/glibc2.17

**Comment by hadrizi** [comment]
> It seems you are building on a machine with GLIBC_2.29, and then running on one with GLIBC_2.17. You should probably just use the PyPI wheels which are built for manylinux2014/glibc2.17

Can you please explain how can I explicitly tell pip to use them? because when I am gathering my dependencies pip downloads linux_x86_64

**Comment by ngoldbaum** [comment]
> pip downloads linux_x86_64

Isn't that what you want?

**Comment by hadrizi** [comment]
> Isn't that what you want?

Well, I guess no, since they throw the same error as I described in the issue

**Comment by mattip** [comment]
More info needed. Please copy paste text, not images.
- What does `uname -m` show on the target machine?
- What does `ldd --version` show on the target machine?
- What does `cat /etc/redhat-release` show on the target machine?
- When you run `pip install numpy==1.21` on the target machine what is the output?

**Comment by hadrizi** [comment]
> * What does `uname -m` show on the target machine?
> * What does `ldd --version` show on the target machine?
> * What does `cat /etc/redhat-release` show on the target machine?
> * When you run `pip install numpy==1.21` on the target machine what is the output?

```bash
# ldd --version
ldd (GNU libc) 2.17
```

**Comment by mattip** [comment]
I get something different, that suggests you must use 1.21.2 which is the first version to support CPython3.10.
```
$ docker run -it --rm quay.io/pypa/manylinux2014_x86_64 /bin/bash
[root@2cff2d850297 /]# cat /etc/redhat-release 
CentOS Linux release 7.9.2009 (Core)
[root@2cff2d850297 /]# /opt/python/cp310-cp310/bin/python -m venv /tmp/venv310
[root@2cff2d850297 /]# source /tmp/venv310/bin/activate
(venv310) [root@2cff2d850297 /]# pip3 install --only-binary=numpy "numpy==1.21.1"
ERROR: Could not find a version that satisfies the requirement numpy==1.21.1 \
    (from versions: 1.21.2, 1.21.3, 1.21.4, ...
ERROR: No matching distribution found for numpy==1.21
```

**Comment by mattip** [comment]
@hadrizi did you work out what is going on? I think we should close this as invalid. We don;t support numpy 1.21 anymore.

**Comment by hadrizi** [comment]
@mattip yeah, update to 1.21.2 helped and we also changed build-machine to manylinux2014 docker image, thx for the help
