### ISSUE TITLE
BUG: f2py cannot compile code with explicit openmp procedure calls

### ISSUE THREAD

**Issue by AgilentGCMS** [numpy/numpy#27163]
### Describe the issue:

I have compiled python 3.12.4 and numpy 2.0.1 with intel oneapi 2024.1 compilers on a compute cluster for multiple people to use. I have some f2py code that explicitly uses openmp library calls such as `omp_set_num_threads`. With previous versions of python, including 3.11.6, I could compile them with 
```
f2py --compiler=intelem --fcompiler=intelem -c interpolate_levels.pyf --opt='-qopenmp' -liomp5 interpolate_levels.F90
```
and they would produce perfectly working python modules. However, since everything has moved to meson now, this is no longer possible on python 3.12.4. So instead I did
```
FC=ifx CC=icx CXX=icpx f2py -c interpolate_levels.pyf --f77flags='-qopenmp' --f90flags='-qopenmp' -liomp5 interpolate_levels.F90
```
which raised errors of `undefined reference to 'omp_set_num_threads'`. This should not happen because I am supplying `-qopenmp` as a compiler option.

### Reproduce the code example:

```python
FC=ifx CC=icx CXX=icpx f2py -c interpolate_levels.pyf --f77flags='-qopenmp' --f90flags='-qopenmp' -liomp5 interpolate_levels.F90
```

### Error message:

```shell
Cannot use distutils backend with Python>=3.12, using meson backend instead.
Ignoring -m untitled.
interpolate_levels.pyf defines tm5_utils to be the modulename.
Reading fortran codes...
	Reading file 'interpolate_levels.pyf' (format:free)
Post-processing...
	Block: tm5_utils
			Block: redistrib_flux
				Block: extrapolate3D
				Block: regrid_fluxes
				Block: regrid_flux_submul
				Block: regrid_fluxes_from_grid
				Block: regrid_flux_series
			Block: precon
				Block: xc_to_x
				Block: g_to_gc
				Block: mult_M
				Block: mult_MT
			Block: indexing
				Block: findUnique
				Block: findIndex
			Block: interpolate_fields
				Block: movingAverage
				Block: dailyaverage
				Block: columnaverage
				Block: takecolumn
				Block: regriddailyfield
				Block: rebin_3d
				Block: rebin_2d
				Block: rebin
				Block: inv_rebin
				Block: inv_rebin_arr
			Block: sat_utils
				Block: errorInflation
Applying post-processing hooks...
  character_backward_compatibility_hook
Post-processing (stage 2)...
	Block: tm5_utils
		Block: unknown_interface
			Block: redistrib_flux
				Block: extrapolate3D
				Block: regrid_fluxes
				Block: regrid_flux_submul
				Block: regrid_fluxes_from_grid
				Block: regrid_flux_series
			Block: precon
				Block: xc_to_x
				Block: g_to_gc
				Block: mult_M
				Block: mult_MT
			Block: indexing
				Block: findUnique
				Block: findIndex
			Block: interpolate_fields
				Block: movingAverage
				Block: dailyaverage
				Block: columnaverage
				Block: takecolumn
				Block: regriddailyfield
				Block: rebin_3d
				Block: rebin_2d
				Block: rebin
				Block: inv_rebin
				Block: inv_rebin_arr
			Block: sat_utils
				Block: errorInflation
Building modules...
    Building module "tm5_utils"...
		Constructing F90 module support for "redistrib_flux"...
            Constructing wrapper function "redistrib_flux.extrapolate3D"...
              op_array = extrapolate3D(ip_array,yrs_predict,[num_yrs_exist,num_yrs_predict,time_dim,lat_dim,lon_dim])
            Constructing wrapper function "redistrib_flux.regrid_fluxes"...
              op_flux = regrid_fluxes(ip_lats,ip_lons,op_lats,op_lons,ip_flux,per_area,[jm_ip,im_ip,jm_op,im_op])
            Constructing wrapper function "redistrib_flux.regrid_flux_submul"...
              op_flux = regrid_flux_submul(ip_lats,ip_lons,op_lats,op_lons,ip_flux,per_area,[jm_ip,im_ip,jm_op,im_op])
            Constructing wrapper function "redistrib_flux.regrid_fluxes_from_grid"...
              op_flux = regrid_fluxes_from_grid(ip_lats,ip_lons,op_lats,op_lons,ip_flux,per_area,[jm_ip,im_ip,jm_op,im_op])
            Constructing wrapper function "redistrib_flux.regrid_flux_series"...
              op_flux,flux_totals = regrid_flux_series(ip_lats,ip_lons,op_lats,op_lons,ip_flux,per_area,[jm_ip,im_ip,jm_op,im_op,timesteps])
		Constructing F90 module support for "precon"...
            Constructing wrapper function "precon.xc_to_x"...
              x = xc_to_x(G_state,Temp_L,Hor_L,x_c,ipos,num_threads,[n_state,nt,n_hor])
            Constructing wrapper function "precon.g_to_gc"...
              g_c = g_to_gc(G_state,Temp_Lt,Hor_Lt,g,ipos,num_threads,[n_state,nt,n_hor])
            Constructing wrapper function "precon.mult_M"...
              v_out = mult_M(G_state,G_mask,Temp_L,Hor_L,v_in,num_threads,[n_block,nt,n_hor])
            Constructing wrapper function "precon.mult_MT"...
              v_out = mult_MT(G_state,G_mask,Temp_L,Hor_L,v_in,num_threads,[n_block,nt,n_hor])
		Constructing F90 module support for "indexing"...
            Constructing wrapper function "indexing.findUnique"...
              uniq_lat,uniq_lon,frequency,n_uniq = findUnique(src_lat,src_lon,tolerance,[len_source])
            Constructing wrapper function "indexing.findIndex"...
              indices_array = findIndex(source_array,seek_array,tolerance,[len_source,len_seek])
		Constructing F90 module support for "interpolate_fields"...
            Constructing wrapper function "interpolate_fields.movingAverage"...
              out_errors,num_samples = movingAverage(times,in_errors,locations,corr_time,corr_length,[num_records])
            Constructing wrapper function "interpolate_fields.dailyaverage"...
              out_mixing,out_ps = dailyaverage(isobars,in_mixing,[tm,lm_in,lats,lons])
            Constructing wrapper function "interpolate_fields.columnaverage"...
              total_column = columnaverage(mixing_ratio,isobars,averaging_kernel,averaging_kernel_pres,prior_mixing,prior_pres,doy_array,[tm,lm,nlevs,ndays])
            Constructing wrapper function "interpolate_fields.takecolumn"...
              total_column = takecolumn(mixing_ratio,isobars,averaging_kernel,averaging_kernel_pres,prior_mixing,prior_pres,[lm,nlevs])
            Constructing wrapper function "interpolate_fields.regriddailyfield"...
              out_mixing,out_ps = regriddailyfield(isobars,in_mixing,[tm,lm_in,lats,lons])
            Constructing wrapper function "interpolate_fields.rebin_3d"...
              out_mixing = rebin_3d(in_levels,in_mixing,out_levels,[lm_in,lats,lons,lm_out])
            Constructing wrapper function "interpolate_fields.rebin_2d"...
              out_mixing = rebin_2d(in_levels,in_mixing,out_levels,[lm_in,time_in,lm_out])
            Constructing wrapper function "interpolate_fields.rebin"...
              out_y_vals = rebin(in_x_grid,in_y_vals,out_x_grid,[in_levels,out_levels])
            Constructing wrapper function "interpolate_fields.inv_rebin"...
              out_y_vals,distrib_matrix = inv_rebin(in_x_grid,in_y_vals,out_x_grid,[in_levels,out_levels])
            Constructing wrapper function "interpolate_fields.inv_rebin_arr"...
              out_y_vals,distrib_matrix,ExitStatus = inv_rebin_arr(in_x_grid,in_y_vals,out_x_grid,[num_obs,in_levels,out_levels])
		Constructing F90 module support for "sat_utils"...
            Constructing wrapper function "sat_utils.errorInflation"...
              out_errors,num_samples = errorInflation(times,in_errors,locations,corr_time,corr_length,bin_choice,err_floor,[num_records])
    Wrote C/API module "tm5_utils" to file "./tm5_utilsmodule.c"
    Fortran 90 wrappers are saved to "./tm5_utils-f2pywrappers2.f90"
The Meson build system
Version: 1.5.1
Source dir: /tmp/tmpixn4q3ri
Build dir: /tmp/tmpixn4q3ri/bbdir
Build type: native build
Project name: tm5_utils
Project version: 0.1
Fortran compiler for the host machine: ifx (intel-llvm 2024.1.0 "ifx (IFX) 2024.1.0 20240308")
Fortran linker for the host machine: ifx ld.bfd 2.35.2-24
C compiler for the host machine: icx (intel-llvm 11.3.1 "Intel(R) oneAPI DPC++/C++ Compiler 2024.1.0 (2024.1.0.20240308)")
C linker for the host machine: icx ld.bfd 2.35.2-24
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program /work2/noaa/co2/sbasu/packages/python/3.12.4/bin/python found: YES (/work2/noaa/co2/sbasu/packages/python/3.12.4/bin/python)
Found pkg-config: YES (/usr/bin/pkg-config) 1.7.3
Run-time dependency python found: YES 3.12
Library quadmath found: YES
Build targets in project: 1

Found ninja-1.11.1.git.kitware.jobserver-1 at /work2/noaa/co2/sbasu/packages/python/3.12.4/bin/ninja
INFO: autodetecting backend as ninja
INFO: calculating backend command to run: /work2/noaa/co2/sbasu/packages/python/3.12.4/bin/ninja -C /tmp/tmpixn4q3ri/bbdir
ninja: Entering directory `/tmp/tmpixn4q3ri/bbdir'
[3/6] Compiling C object tm5_utils.cpython-312-x86_64-linux-gnu.so.p/tm5_utilsmodule.c.o
../tm5_utilsmodule.c:1473:9: warning: misleading indentation; statement is not part of the previous 'if' [-Wmisleading-indentation]
 1473 |         per_area = (int)PyObject_IsTrue(per_area_capi);
      |         ^
../tm5_utilsmodule.c:1467:5: note: previous statement is here
 1467 |     if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
      |     ^
1 warning generated.
[6/6] Linking target tm5_utils.cpython-312-x86_64-linux-gnu.so
FAILED: tm5_utils.cpython-312-x86_64-linux-gnu.so
icx  -o tm5_utils.cpython-312-x86_64-linux-gnu.so tm5_utils.cpython-312-x86_64-linux-gnu.so.p/interpolate_levels.F90.o tm5_utils.cpython-312-x86_64-linux-gnu.so.p/tm5_utilsmodule.c.o tm5_utils.cpython-312-x86_64-linux-gnu.so.p/tm5_utils-f2pywrappers2.f90.o tm5_utils.cpython-312-x86_64-linux-gnu.so.p/e3838bb052daf315fa49226b51f93a7020d9e0a6_.._.._f2py_src_fortranobject.c.o -Wl,--as-needed -Wl,--allow-shlib-undefined -Wl,-O1 -shared -fPIC -Wl,--start-group -lquadmath -liomp5 -lifcore -limf -Wl,--end-group
/usr/bin/ld: tm5_utils.cpython-312-x86_64-linux-gnu.so.p/interpolate_levels.F90.o: in function `precon_mp_xc_to_x_':
ifxhtc7BG.i90:(.text+0x4828): undefined reference to `omp_set_num_threads'
/usr/bin/ld: tm5_utils.cpython-312-x86_64-linux-gnu.so.p/interpolate_levels.F90.o: in function `precon_mp_g_to_gc_':
ifxhtc7BG.i90:(.text+0x4908): undefined reference to `omp_set_num_threads'
/usr/bin/ld: tm5_utils.cpython-312-x86_64-linux-gnu.so.p/interpolate_levels.F90.o: in function `precon_mp_mult_mt_':
ifxhtc7BG.i90:(.text+0x4a26): undefined reference to `omp_set_num_threads'
/usr/bin/ld: tm5_utils.cpython-312-x86_64-linux-gnu.so.p/interpolate_levels.F90.o: in function `precon_mp_mult_m_':
ifxhtc7BG.i90:(.text+0x4c36): undefined reference to `omp_set_num_threads'
/usr/bin/ld: tm5_utils.cpython-312-x86_64-linux-gnu.so: hidden symbol `omp_set_num_threads' isn't defined
/usr/bin/ld: final link failed: bad value
icx: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/work2/noaa/co2/sbasu/packages/python/3.12.4/bin/f2py", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/work2/noaa/co2/sbasu/packages/python/3.12.4/lib/python3.12/site-packages/numpy/f2py/f2py2e.py", line 769, in main
    run_compile()
  File "/work2/noaa/co2/sbasu/packages/python/3.12.4/lib/python3.12/site-packages/numpy/f2py/f2py2e.py", line 741, in run_compile
    builder.compile()
  File "/work2/noaa/co2/sbasu/packages/python/3.12.4/lib/python3.12/site-packages/numpy/f2py/_backends/_meson.py", line 193, in compile
    self.run_meson(self.build_dir)
  File "/work2/noaa/co2/sbasu/packages/python/3.12.4/lib/python3.12/site-packages/numpy/f2py/_backends/_meson.py", line 188, in run_meson
    self._run_subprocess_command(compile_command, build_dir)
  File "/work2/noaa/co2/sbasu/packages/python/3.12.4/lib/python3.12/site-packages/numpy/f2py/_backends/_meson.py", line 182, in _run_subprocess_command
    subprocess.run(command, cwd=cwd, check=True)
  File "/work2/noaa/co2/sbasu/packages/python/3.12.4/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['meson', 'compile', '-C', 'bbdir']' returned non-zero exit status 1.
```

### Python and NumPy Versions:

2.0.1
3.12.4 (main, Jul 29 2024, 10:14:44) [Clang 18.0.0 (icx 2024.1.0.20240308)]

### Runtime Environment:

[{'numpy_version': '2.0.1',
  'python': '3.12.4 (main, Jul 29 2024, 10:14:44) [Clang 18.0.0 (icx '
            '2024.1.0.20240308)]',
  'uname': uname_result(system='Linux', node='hercules-login-3.hpc.msstate.edu', release='5.14.0-162.23.1.el9_1.x86_64', version='#1 SMP PREEMPT_DYNAMIC Tue Apr 11 19:09:37 UTC 2023', machine='x86_64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2',
                                'AVX512F',
                                'AVX512CD',
                                'AVX512_SKX',
                                'AVX512_CLX',
                                'AVX512_CNL',
                                'AVX512_ICL'],
                      'not_found': ['AVX512_KNL']}},
 {'filepath': '/apps/spack-managed/gcc-11.3.1/intel-oneapi-compilers-2024.1.0-76aou5yu2oqfcz72vq7lp77bp3rqcoht/compiler/2024.1/lib/libiomp5.so',
  'internal_api': 'openmp',
  'num_threads': 160,
  'prefix': 'libiomp',
  'user_api': 'openmp',
  'version': None}]

**Comment by AgilentGCMS** [comment]
Here's a minimal working example. Put the following in `mwe_f2py.F90`,
```
module precon

implicit none

public :: xc_to_x

contains

subroutine xc_to_x(n_state, G_state, num_threads, x)

   use omp_lib

   integer, intent(in)             :: n_state, num_threads
   double precision, intent(in)    :: G_state(n_state)
   double precision, intent(out)   :: x(n_state)
   integer                         :: i

   x = 0.0

   call omp_set_num_threads(num_threads)

   !$omp parallel do schedule(guided)
   do i = 1, n_state
      x(i) = G_state(i) * G_state(n_state-i+1)
   end do
   !$omp end parallel do

end subroutine xc_to_x

end module precon
```
and the following in `mwe_f2py.pyf`,
```
python module mwe_f2py
    interface

    module precon

        subroutine xc_to_x(n_state, G_state, num_threads, x)
            integer,optional,intent(in),check(len(G_state)==n_state),depend(G_state) :: n_state=len(G_state)
            double precision,dimension(n_state),intent(in) :: G_state
            integer,intent(in) :: num_threads
            double precision,dimension(n_state),intent(out) :: x
        end subroutine xc_to_x

    end module precon

    end interface
end python module mwe_f2py
```
This compiles into a python module `mwe_f2py.cpython-311-x86_64-linux-gnu.so` with the following command under python 3.11.6,
```
f2py --compiler=intelem --fcompiler=intelem -c mwe_f2py.pyf --opt='-qopenmp' -liomp5 mwe_f2py.F90
```
However, with the new-fangled meson build system under python 3.12.4, the following command complains about undefined reference to omp_set_num_threads,
```
CFLAGS='-qopenmp' FC=ifx CC=icx CXX=icpx f2py -c mwe_f2py.pyf --f77flags='-qopenmp' --f90flags='-qopenmp' -liomp5 mwe_f2py.F90
```
So either there's a way to specify flags I'm not getting, or `f2py` got broken.

**Comment by AgilentGCMS** [comment]
I went back to python 3.11.6 and after modifying `numpy/distutils/intelccompiler.py` and `numpy/distutils/fcompiler/intel.py` to use `icx` and `ifx` to match oneapi, I was able to compile my f2py code successfully into python modules. I will keep this open since I haven't seen any documentation online as to how one would do this for python 3.12.x with meson build.

**Comment by HaoZeke** [comment]
OTOH, shouldn't this just be done by editing the `meson.build` for using `fortran_args` on the target?

**Comment by HaoZeke** [comment]
This should be working by default since https://github.com/numpy/numpy/pull/26703 in any case, could you also share the generated `meson.build` ?

**Comment by AgilentGCMS** [comment]
> CFLAGS='-qopenmp' FC=ifx CC=icx CXX=icpx f2py -c mwe_f2py.pyf --f77flags='-qopenmp' --f90flags='-qopenmp' -liomp5 mwe_f2py.F90

Where can I find this `meson.build` that is being generated? I don't see it in the folder where my `F90` and `pyf` files are. One of the joys of the meson system, I have discovered, is that it very helpfully deletes all intermediate files.

**Comment by HaoZeke** [comment]
> > CFLAGS='-qopenmp' FC=ifx CC=icx CXX=icpx f2py -c mwe_f2py.pyf --f77flags='-qopenmp' --f90flags='-qopenmp' -liomp5 mwe_f2py.F90
> 
> Where can I find this `meson.build` that is being generated? I don't see it in the folder where my `F90` and `pyf` files are. One of the joys of the meson system, I have discovered, is that it very helpfully deletes all intermediate files.

This was true before as well though, passing `--build-dir whatever` is required to keep all the generated files (including the `whatever/meson.build` file).

**Comment by AgilentGCMS** [comment]
> > > CFLAGS='-qopenmp' FC=ifx CC=icx CXX=icpx f2py -c mwe_f2py.pyf --f77flags='-qopenmp' --f90flags='-qopenmp' -liomp5 mwe_f2py.F90
> > 
> > 
> > Where can I find this `meson.build` that is being generated? I don't see it in the folder where my `F90` and `pyf` files are. One of the joys of the meson system, I have discovered, is that it very helpfully deletes all intermediate files.
> 
> This was true before as well though, passing `--build-dir whatever` is required to keep all the generated files (including the `whatever/meson.build` file).

Indeed, for `f2py` that was always the case :-) My complaint was a carryover from trying to use `meson` instead of `distutils` for compiling (other) python modules. Anyway, here's what is inside `meson.build`:
```
project('mwe_f2py',
        ['c', 'fortran'],
        version : '0.1',
        meson_version: '>= 1.1.0',
        default_options : [
                            'warning_level=1',
                            'buildtype=release'
                          ])
fc = meson.get_compiler('fortran')

py = import('python').find_installation('''/work2/noaa/co2/sbasu/packages/python/3.12.4/bin/python''', pure: false)
py_dep = py.dependency()

incdir_numpy = run_command(py,
  ['-c', 'import os; os.chdir(".."); import numpy; print(numpy.get_include())'],
  check : true
).stdout().strip()

incdir_f2py = run_command(py,
    ['-c', 'import os; os.chdir(".."); import numpy.f2py; print(numpy.f2py.get_include())'],
    check : true
).stdout().strip()

inc_np = include_directories(incdir_numpy)
np_dep = declare_dependency(include_directories: inc_np)

incdir_f2py = incdir_numpy / '..' / '..' / 'f2py' / 'src'
inc_f2py = include_directories(incdir_f2py)
fortranobject_c = incdir_f2py / 'fortranobject.c'

inc_np = include_directories(incdir_numpy, incdir_f2py)
# gh-25000
quadmath_dep = fc.find_library('quadmath', required: false)

iomp5 = declare_dependency(link_args : ['-liomp5'])


py.extension_module('mwe_f2py',
                     [
                     '''mwe_f2py.F90''',
                     '''mwe_f2pymodule.c''',
                     '''mwe_f2py-f2pywrappers2.f90''',
                     fortranobject_c
                     ],
                     include_directories: [
                     inc_np,

                     ],
                     dependencies : [
                     py_dep,
                     quadmath_dep,

                     iomp5,

                     ],
                     fortran_args: ['-qopenmp'],
                     install : true)
```
If you look at the original error, it's the C compiler invocation that is failing.

**Comment by HaoZeke** [comment]
OTOH, does adding `c_args: ['-qopenmp']` fix this? Might be worth having a way to pass `c_args` from the command line.

However, for OpenMP in particular it might be best to just pass `--dep openmp` which should solve this (or make it an upstream error [1] since it'll add `dependency('openmp')`...

[1] https://mesonbuild.com/Dependencies.html#openmp

**Comment by AgilentGCMS** [comment]
> OTOH, does adding `c_args: ['-qopenmp']` fix this? Might be worth having a way to pass `c_args` from the command line. 

Since `meson.build` is auto-generated, I do not know how to add `c_args: ['-qopenmp']`. Can you show me?

> However, for OpenMP in particular it might be best to just pass `--dep openmp` which should solve this (or make it an upstream error [1] since it'll add `dependency('openmp')`... [1] https://mesonbuild.com/Dependencies.html#openmp

You mean like this?
```
CFLAGS='-qopenmp' FC=ifx CC=icx CXX=icpx f2py --build-dir mwe_build -c mwe_f2py.pyf --f77flags='-qopenmp' --f90flags='-qopenmp' --dep openmp -liomp5 mwe_f2py.F90
```
This did not work, it still barfed with the error
```
FAILED: mwe_f2py.cpython-312-x86_64-linux-gnu.so
icx  -o mwe_f2py.cpython-312-x86_64-linux-gnu.so mwe_f2py.cpython-312-x86_64-linux-gnu.so.p/mwe_f2py.F90.o mwe_f2py.cpython-312-x86_64-linux-gnu.so.p/mwe_f2pymodule.c.o mwe_f2py.cpython-312-x86_64-linux-gnu.so.p/mwe_f2py-f2pywrappers2.f90.o mwe_f2py.cpython-312-x86_64-linux-gnu.so.p/e3838bb052daf315fa49226b51f93a7020d9e0a6_.._.._f2py_src_fortranobject.c.o -Wl,--as-needed -Wl,--allow-shlib-undefined -Wl,-O1 -shared -fPIC -qopenmp -Wl,--start-group -lquadmath -fopenmp -liomp5 -lifcore -limf -Wl,--end-group
icx: warning: Use of '-qopenmp' recommended over '-fopenmp' [-Wrecommended-option]
/usr/bin/ld: mwe_f2py.cpython-312-x86_64-linux-gnu.so.p/mwe_f2py.F90.o: in function `precon_mp_xc_to_x_':
ifxwWBjCB.i90:(.text+0x3e): undefined reference to `omp_set_num_threads'
/usr/bin/ld: mwe_f2py.cpython-312-x86_64-linux-gnu.so: hidden symbol `omp_set_num_threads' isn't defined
/usr/bin/ld: final link failed: bad value
icx: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```

**Comment by sujona** [comment]
Maybe try the meson-specific `--dep`  [flag](https://numpy.org/doc/stable/f2py/usage.html), like

`f2py <your args> --dep openmp 
`

**Comment by AgilentGCMS** [comment]
I had given up on this and gone back to python 3.11, but it seems like with everything moving on in versions, I can no longer ignore this problem. I just installed numpy 2.4.1 on python 3.14.2 with intel compilers, and `F77=ifx F90=ifx FC=ifx CC=icx CXX=icpx f2py -c mwe_f2py.pyf --opt='-qopenmp' -liomp5 mwe_f2py.F90 --dep openmp` still gives me the error
```
[7/7] Linking target mwe_f2py.cpython-314-x86_64-linux-gnu.so
FAILED: [code=1] mwe_f2py.cpython-314-x86_64-linux-gnu.so
icx  -o mwe_f2py.cpython-314-x86_64-linux-gnu.so mwe_f2py.cpython-314-x86_64-linux-gnu.so.p/mwe_f2py.F90.o mwe_f2py.cpython-314-x86_64-linux-gnu.so.p/mwe_f2pymodule.c.o mwe_f2py.cpython-314-x86_64-linux-gnu.so.p/mwe_f2py-f2pywrappers2.f90.o mwe_f2py.cpython-314-x86_64-linux-gnu.so.p/2c1ea986473d1b0775679aeedfce78978470d827_.._.._f2py_src_fortranobject.c.o -Wl,--as-needed -Wl,--allow-shlib-undefined -Wl,-O1 -shared -fPIC -Wl,--start-group -lquadmath -fopenmp -liomp5 -lifcore -limf -Wl,--end-group
icx: warning: Use of '-qopenmp' recommended over '-fopenmp' [-Wrecommended-option]
mwe_f2py.cpython-314-x86_64-linux-gnu.so.p/mwe_f2py.F90.o: In function `precon_mp_xc_to_x_':
ifx1aSkON.i90:(.text+0x3e): undefined reference to `omp_set_num_threads'
/usr/bin/ld: mwe_f2py.cpython-314-x86_64-linux-gnu.so: hidden symbol `omp_set_num_threads' isn't defined
/usr/bin/ld: final link failed: Bad value
icx: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/swbuild/sbasu1/packages/python/3.14.2/bin/f2py", line 7, in <module>
    sys.exit(main())
             ~~~~^^
  File "/swbuild/sbasu1/packages/python/3.14.2/lib/python3.14/site-packages/numpy/f2py/f2py2e.py", line 786, in main
    run_compile()
    ~~~~~~~~~~~^^
  File "/swbuild/sbasu1/packages/python/3.14.2/lib/python3.14/site-packages/numpy/f2py/f2py2e.py", line 758, in run_compile
    builder.compile()
    ~~~~~~~~~~~~~~~^^
  File "/swbuild/sbasu1/packages/python/3.14.2/lib/python3.14/site-packages/numpy/f2py/_backends/_meson.py", line 197, in compile
    self.run_meson(self.build_dir)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/swbuild/sbasu1/packages/python/3.14.2/lib/python3.14/site-packages/numpy/f2py/_backends/_meson.py", line 191, in run_meson
    self._run_subprocess_command(compile_command, build_dir)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/swbuild/sbasu1/packages/python/3.14.2/lib/python3.14/site-packages/numpy/f2py/_backends/_meson.py", line 185, in _run_subprocess_command
    subprocess.run(command, cwd=cwd, check=True)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/swbuild/sbasu1/packages/python/3.14.2/lib/python3.14/subprocess.py", line 577, in run
    raise CalledProcessError(retcode, process.args,
                             output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['meson', 'compile', '-C', 'bbdir']' returned non-zero exit status 1.
```
Is openmp in F2PY basically dead with this new-fangled meson build system?

**Comment by AgilentGCMS** [comment]
@HaoZeke Please help? I thought this would have been fixed in the 1+ years I've stayed away, but clearly not... and I'm __not__ a meson expert :-(

**Comment by HaoZeke** [comment]
Sorry, I've just recently been trying to clear my backlog of issues, but I'll try to look into this soon.

**Comment by AgilentGCMS** [comment]
Came back here to see if there's a resolution now, but no :-(
