### ISSUE TITLE
BUG: Cannot call np.average on timedelta64 array

### ISSUE THREAD

**Issue by guan404ming** [numpy/numpy#27204]
### Describe the issue:

Not sure if this is by design or actually a bug but one cannot call np.average on datetime arrays.

### Reproduce the code example:

```python
import numpy as np

a = np.array([1, 3], dtype="timedelta64[D]")
np.average(a)
```

### Error message:

```shell
Traceback (most recent call last):
  File "/Users/wesley/Downloads/im-project-test/test.py", line 4, in <module>
    np.average(a)
  File "/Users/wesley/Downloads/im-project-test/.venv/lib/python3.12/site-packages/numpy/lib/_function_base_impl.py", line 559, in average
    scl = avg_as_array.dtype.type(a.size/avg_as_array.size)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Could not convert object to NumPy timedelta
```

### Python and NumPy Versions:

2.0.1
3.12.4 (main, Jul 29 2024, 19:33:19) [Clang 14.0.0 (clang-1400.0.29.202)]

### Context for the issue:

cause by numpy/lib/function_base.py line 520

```python
if weights is None:
    avg = a.mean(axis, **keepdims_kw)
    avg_as_array = np.asanyarray(avg)
    scl = avg_as_array.dtype.type(a.size/avg_as_array.size)
```

It seems like the code is attempting to convert the result of the division (a.size / avg_as_array.size, a float) into the type of elements in avg_as_array, which could be a timedelta type. This conversion is invalid because a float can't directly convert to a timedelta.

**Comment by mfuaj** [comment]
if you are trying to find the average please use a.mean(), then you can find out the average

**Comment by jorenham** [comment]
@mfuaj `numpy.average` can be used to take the weighted average, whereas `numpy.mean` cannot.
