### ISSUE TITLE
Build fails on Tempita when Cython is installed globally with pipx

### ISSUE THREAD

**Issue by solomoncyj** [numpy/numpy#27241]
### Describe the issue:

when ninja is buliding the numpy, it spits out an error saying cython is not found

### Reproduce the code example:

```python
.
```

### Error message:

```shell
spin build
$ /home/solomoncyj/.local/share/pipx/venvs/spin/bin/python vendored-meson/meson/meson.py setup build --prefix=/usr
The Meson build system
Version: 1.4.99
Source dir: /home/solomoncyj/Downloads/numpy
Build dir: /home/solomoncyj/Downloads/numpy/build
Build type: native build
Project name: NumPy
Project version: 2.2.0.dev0+git20240817.d60444f
C compiler for the host machine: /usr/lib64/ccache/clang (clang 18.1.6 "clang version 18.1.6 (Fedora 18.1.6-3.fc40)")
C linker for the host machine: /usr/lib64/ccache/clang ld.bfd 2.41-37
C++ compiler for the host machine: /usr/lib64/ccache/clang++ (clang 18.1.6 "clang version 18.1.6 (Fedora 18.1.6-3.fc40)")
C++ linker for the host machine: /usr/lib64/ccache/clang++ ld.bfd 2.41-37
Cython compiler for the host machine: cython (cython 3.1.0)
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program python3 found: YES (/home/solomoncyj/.local/share/pipx/venvs/spin/bin/python)
Found pkg-config: YES (/usr/bin/pkg-config) 2.1.1
Run-time dependency python found: YES 3.12
Has header "Python.h" with dependency python-3.12: YES 
Compiler for C supports arguments -fno-strict-aliasing: YES 
Compiler for C supports arguments -ftrapping-math: YES 
Test features "SSE SSE2 SSE3" : Supported 
Test features "SSSE3" : Supported 
Test features "SSE41" : Supported 
Test features "POPCNT" : Supported 
Test features "SSE42" : Supported 
Test features "AVX" : Supported 
Test features "F16C" : Supported 
Test features "FMA3" : Supported 
Test features "AVX2" : Supported 
Test features "AVX512F" : Supported 
Test features "AVX512CD" : Supported 
Test features "AVX512_KNL" : Supported 
Test features "AVX512_KNM" : Unsupported due to Arguments "-msse, -msse2, -msse3, -mssse3, -msse4.1, -mpopcnt, -msse4.2, -mavx, -mf16c, -mfma, -mavx2, -maes, -mpclmul, -mbmi, -mbmi2, -mno-mmx, -mavx512f, -mavx512cd, -mavx512er, -mavx512pf, -mavx5124fmaps, -mavx5124vnniw, -mavx512vpopcntdq" are not supported
Test features "AVX512_SKX" : Supported 
Test features "AVX512_CLX" : Supported 
Test features "AVX512_CNL" : Supported 
Test features "AVX512_ICL" : Supported 
Test features "AVX512_SPR" : Unsupported due to Compiler fails against the test code of "AVX512_SPR"
Configuring npy_cpu_dispatch_config.h using configuration
Message: 
CPU Optimization Options
  baseline:
    Requested : min
    Enabled   : SSE SSE2 SSE3
  dispatch:
    Requested : max -xop -fma4
    Enabled   : SSSE3 SSE41 POPCNT SSE42 AVX F16C FMA3 AVX2 AVX512F AVX512CD AVX512_KNL AVX512_SKX AVX512_CLX AVX512_CNL AVX512_ICL

Library m found: YES
Run-time dependency scipy-openblas found: NO (tried pkgconfig)
Run-time dependency mkl found: NO (tried pkgconfig and system)
Run-time dependency mkl found: NO (tried pkgconfig and system)
Found CMake: /usr/bin/cmake (3.28.2)
WARNING: CMake Toolchain: Failed to determine CMake compilers state
Run-time dependency openblas found: NO (tried pkgconfig, pkgconfig, pkgconfig, system and cmake)
Run-time dependency flexiblas found: NO (tried pkgconfig and cmake)
Run-time dependency blis found: NO (tried pkgconfig and cmake)
Run-time dependency blas found: NO (tried pkgconfig and system)
Run-time dependency mkl found: NO (tried pkgconfig and system)
Run-time dependency openblas found: NO (tried pkgconfig, pkgconfig, pkgconfig, system and cmake)
Run-time dependency flexiblas found: NO (tried pkgconfig and cmake)
Run-time dependency lapack found: NO (tried pkgconfig and system)
Checking if "Check atomic builtins without -latomic" : links: NO 
Library atomic found: YES
Checking if "Check atomic builtins with -latomic" with dependency -latomic: links: NO 
Program _build_utils/process_src_template.py found: YES (/home/solomoncyj/.local/share/pipx/venvs/spin/bin/python /home/solomoncyj/Downloads/numpy/numpy/_build_utils/process_src_template.py)
Program _build_utils/tempita.py found: YES (/home/solomoncyj/.local/share/pipx/venvs/spin/bin/python /home/solomoncyj/Downloads/numpy/numpy/_build_utils/tempita.py)
Configuring __config__.py using configuration
numpy/meson.build:440: WARNING: The variable(s) 'BLAS_INCLUDEDIR', 'BLAS_LIBDIR', 'BLAS_OPENBLAS_CONFIG', 'BLAS_PCFILEDIR', 'BLAS_TYPE_NAME', 'BLAS_VERSION', 'LAPACK_INCLUDEDIR', 'LAPACK_LIBDIR', 'LAPACK_OPENBLAS_CONFIG', 'LAPACK_PCFILEDIR', 'LAPACK_TYPE_NAME', 'LAPACK_VERSION' in the input file 'numpy/__config__.py.in' are not present in the given configuration data.
Checking for size of "short" : 2 
Checking for size of "int" : 4 
Checking for size of "long" : 8 
Checking for size of "long long" : 8 
Checking for size of "float" : 4 
Checking for size of "double" : 8 
Checking for size of "long double" : 16 
Checking for size of "size_t" : 8 
Checking for size of "size_t" : 8 (cached)
Checking for size of "wchar_t" : 4 
Checking for size of "off_t" : 8 
Checking for size of "Py_intptr_t" with dependency python-3.12: 8 
Checking for size of "PY_LONG_LONG" with dependency python-3.12: 8 
Has header "complex.h" : YES 
Checking for type "complex float" : YES 
Checking for size of "complex float" : 8 
Checking for type "complex double" : YES 
Checking for size of "complex double" : 16 
Checking for type "complex long double" : YES 
Checking for size of "complex long double" : 32 
Checking for function "sin" with dependency -lm: YES 
Checking for function "cos" with dependency -lm: YES 
Checking for function "tan" with dependency -lm: YES 
Checking for function "sinh" with dependency -lm: YES 
Checking for function "cosh" with dependency -lm: YES 
Checking for function "tanh" with dependency -lm: YES 
Checking for function "fabs" with dependency -lm: YES 
Checking for function "floor" with dependency -lm: YES 
Checking for function "ceil" with dependency -lm: YES 
Checking for function "sqrt" with dependency -lm: YES 
Checking for function "log10" with dependency -lm: YES 
Checking for function "log" with dependency -lm: YES 
Checking for function "exp" with dependency -lm: YES 
Checking for function "asin" with dependency -lm: YES 
Checking for function "acos" with dependency -lm: YES 
Checking for function "atan" with dependency -lm: YES 
Checking for function "fmod" with dependency -lm: YES 
Checking for function "modf" with dependency -lm: YES 
Checking for function "frexp" with dependency -lm: YES 
Checking for function "ldexp" with dependency -lm: YES 
Checking for function "expm1" with dependency -lm: YES 
Checking for function "log1p" with dependency -lm: YES 
Checking for function "acosh" with dependency -lm: YES 
Checking for function "asinh" with dependency -lm: YES 
Checking for function "atanh" with dependency -lm: YES 
Checking for function "rint" with dependency -lm: YES 
Checking for function "trunc" with dependency -lm: YES 
Checking for function "exp2" with dependency -lm: YES 
Checking for function "copysign" with dependency -lm: YES 
Checking for function "nextafter" with dependency -lm: YES 
Checking for function "cbrt" with dependency -lm: YES 
Checking for function "log2" with dependency -lm: YES 
Checking for function "pow" with dependency -lm: YES 
Checking for function "hypot" with dependency -lm: YES 
Checking for function "atan2" with dependency -lm: YES 
Checking for function "csin" with dependency -lm: YES 
Checking for function "csinh" with dependency -lm: YES 
Checking for function "ccos" with dependency -lm: YES 
Checking for function "ccosh" with dependency -lm: YES 
Checking for function "ctan" with dependency -lm: YES 
Checking for function "ctanh" with dependency -lm: YES 
Checking for function "creal" with dependency -lm: YES 
Checking for function "cimag" with dependency -lm: YES 
Checking for function "conj" with dependency -lm: YES 
Checking for function "strtoll" : YES 
Checking for function "strtoull" : YES 
Checking for function "cabs" with dependency -lm: YES 
Checking for function "cabsf" with dependency -lm: YES 
Checking for function "cabsl" with dependency -lm: YES 
Checking for function "cacos" with dependency -lm: YES 
Checking for function "cacosf" with dependency -lm: YES 
Checking for function "cacosl" with dependency -lm: YES 
Checking for function "cacosh" with dependency -lm: YES 
Checking for function "cacoshf" with dependency -lm: YES 
Checking for function "cacoshl" with dependency -lm: YES 
Checking for function "carg" with dependency -lm: YES 
Checking for function "cargf" with dependency -lm: YES 
Checking for function "cargl" with dependency -lm: YES 
Checking for function "casin" with dependency -lm: YES 
Checking for function "casinf" with dependency -lm: YES 
Checking for function "casinl" with dependency -lm: YES 
Checking for function "casinh" with dependency -lm: YES 
Checking for function "casinhf" with dependency -lm: YES 
Checking for function "casinhl" with dependency -lm: YES 
Checking for function "catan" with dependency -lm: YES 
Checking for function "catanf" with dependency -lm: YES 
Checking for function "catanl" with dependency -lm: YES 
Checking for function "catanh" with dependency -lm: YES 
Checking for function "catanhf" with dependency -lm: YES 
Checking for function "catanhl" with dependency -lm: YES 
Checking for function "cexp" with dependency -lm: YES 
Checking for function "cexpf" with dependency -lm: YES 
Checking for function "cexpl" with dependency -lm: YES 
Checking for function "clog" with dependency -lm: YES 
Checking for function "clogf" with dependency -lm: YES 
Checking for function "clogl" with dependency -lm: YES 
Checking for function "cpow" with dependency -lm: YES 
Checking for function "cpowf" with dependency -lm: YES 
Checking for function "cpowl" with dependency -lm: YES 
Checking for function "csqrt" with dependency -lm: YES 
Checking for function "csqrtf" with dependency -lm: YES 
Checking for function "csqrtl" with dependency -lm: YES 
Checking for function "csin" with dependency -lm: YES (cached)
Checking for function "csinf" with dependency -lm: YES 
Checking for function "csinl" with dependency -lm: YES 
Checking for function "csinh" with dependency -lm: YES (cached)
Checking for function "csinhf" with dependency -lm: YES 
Checking for function "csinhl" with dependency -lm: YES 
Checking for function "ccos" with dependency -lm: YES (cached)
Checking for function "ccosf" with dependency -lm: YES 
Checking for function "ccosl" with dependency -lm: YES 
Checking for function "ccosh" with dependency -lm: YES (cached)
Checking for function "ccoshf" with dependency -lm: YES 
Checking for function "ccoshl" with dependency -lm: YES 
Checking for function "ctan" with dependency -lm: YES (cached)
Checking for function "ctanf" with dependency -lm: YES 
Checking for function "ctanl" with dependency -lm: YES 
Checking for function "ctanh" with dependency -lm: YES (cached)
Checking for function "ctanhf" with dependency -lm: YES 
Checking for function "ctanhl" with dependency -lm: YES 
Checking for function "isfinite" with dependency -lm: YES 
Header "Python.h" has symbol "isfinite" with dependency python-3.12: YES 
Checking for function "isinf" with dependency -lm: YES 
Header "Python.h" has symbol "isinf" with dependency python-3.12: YES 
Checking for function "isnan" with dependency -lm: YES 
Header "Python.h" has symbol "isnan" with dependency python-3.12: YES 
Checking for function "signbit" with dependency -lm: YES 
Header "Python.h" has symbol "signbit" with dependency python-3.12: YES 
Checking if "thread_local" compiles: NO 
Checking if "_Thread_local" compiles: YES 
Checking if "__thread" compiles: YES 
Checking if "__declspec(thread)" compiles: NO 
Checking for function "fallocate" : YES 
Header "Python.h" has symbol "HAVE_FTELLO" with dependency python-3.12: YES 
Header "Python.h" has symbol "HAVE_FSEEKO" with dependency python-3.12: YES 
Checking for function "backtrace" : YES 
Checking for function "madvise" : YES 
Has header "features.h" : YES 
Has header "xlocale.h" : NO 
Has header "dlfcn.h" : YES 
Has header "execinfo.h" : YES 
Has header "libunwind.h" : NO 
Has header "sys/mman.h" : YES 
Checking for function "strtold_l" : YES 
Compiler for C supports arguments -O3: YES 
Has header "endian.h" : YES 
Has header "sys/endian.h" : NO 
Compiler for C supports function attribute visibility:hidden: YES 
Configuring config.h using configuration
Configuring _numpyconfig.h using configuration
Configuring npymath.ini using configuration
Configuring mlib.ini using configuration
Configuring numpy.pc using configuration
Generating multi-targets for "_umath_tests.dispatch.h" 
  Enabled targets: AVX2, SSE41, baseline
Generating multi-targets for "argfunc.dispatch.h" 
  Enabled targets: AVX512_SKX, AVX2, SSE42, baseline
Generating multi-targets for "x86_simd_argsort.dispatch.h" 
  Enabled targets: AVX512_SKX, AVX2
Generating multi-targets for "x86_simd_qsort.dispatch.h" 
  Enabled targets: AVX512_SKX, AVX2
Generating multi-targets for "x86_simd_qsort_16bit.dispatch.h" 
  Enabled targets: AVX512_ICL
Generating multi-targets for "highway_qsort.dispatch.h" 
  Enabled targets: 
Generating multi-targets for "highway_qsort_16bit.dispatch.h" 
  Enabled targets: 
Generating multi-targets for "loops_arithm_fp.dispatch.h" 
  Enabled targets: AVX2, baseline
Generating multi-targets for "loops_arithmetic.dispatch.h" 
  Enabled targets: AVX512_SKX, AVX512F, AVX2, SSE41, baseline
Generating multi-targets for "loops_comparison.dispatch.h" 
  Enabled targets: AVX512_SKX, AVX512F, AVX2, SSE42, baseline
Generating multi-targets for "loops_exponent_log.dispatch.h" 
  Enabled targets: AVX512_SKX, AVX512F, AVX2, baseline
Generating multi-targets for "loops_hyperbolic.dispatch.h" 
  Enabled targets: AVX512_SKX, AVX2, baseline
Generating multi-targets for "loops_logical.dispatch.h" 
  Enabled targets: AVX512_SKX, AVX2, baseline
Generating multi-targets for "loops_minmax.dispatch.h" 
  Enabled targets: AVX512_SKX, AVX2, baseline
Generating multi-targets for "loops_modulo.dispatch.h" 
  Enabled targets: baseline
Generating multi-targets for "loops_trigonometric.dispatch.h" 
  Enabled targets: AVX512_SKX, AVX2, baseline
Generating multi-targets for "loops_umath_fp.dispatch.h" 
  Enabled targets: AVX512_SKX, baseline
Generating multi-targets for "loops_unary.dispatch.h" 
  Enabled targets: AVX512_SKX, AVX2, baseline
Generating multi-targets for "loops_unary_fp.dispatch.h" 
  Enabled targets: SSE41, baseline
Generating multi-targets for "loops_unary_fp_le.dispatch.h" 
  Enabled targets: SSE41, baseline
Generating multi-targets for "loops_unary_complex.dispatch.h" 
  Enabled targets: AVX512F, AVX2, baseline
Generating multi-targets for "loops_autovec.dispatch.h" 
  Enabled targets: AVX2, baseline
Generating multi-targets for "_simd.dispatch.h" 
  Enabled targets: SSE42, AVX2, FMA3, AVX512F, AVX512_SKX, baseline
Build targets in project: 104

NumPy 2.2.0.dev0+git20240817.d60444f

  User defined options
    prefix: /usr

Found ninja-1.13.0.git at /usr/local/bin/ninja
$ /home/solomoncyj/.local/share/pipx/venvs/spin/bin/python vendored-meson/meson/meson.py compile -C build
INFO: autodetecting backend as ninja
INFO: calculating backend command to run: /usr/local/bin/ninja -C /home/solomoncyj/Downloads/numpy/build
ninja: Entering directory `/home/solomoncyj/Downloads/numpy/build'
[178/593] Generating numpy/random/_bounded_integer_pxd with a custom command
FAILED: numpy/random/_bounded_integers.pxd 
/home/solomoncyj/.local/share/pipx/venvs/spin/bin/python /home/solomoncyj/Downloads/numpy/numpy/_build_utils/tempita.py ../numpy/random/_bounded_integers.pxd.in -o numpy/random/_bounded_integers.pxd
Traceback (most recent call last):
  File "/home/solomoncyj/Downloads/numpy/numpy/_build_utils/tempita.py", line 6, in <module>
    from Cython import Tempita as tempita
ModuleNotFoundError: No module named 'Cython'
[181/593] Generating numpy/random/_bounded_integer_pyx with a custom command
FAILED: numpy/random/_bounded_integers.pyx 
/home/solomoncyj/.local/share/pipx/venvs/spin/bin/python /home/solomoncyj/Downloads/numpy/numpy/_build_utils/tempita.py ../numpy/random/_bounded_integers.pyx.in -o numpy/random/_bounded_integers.pyx
Traceback (most recent call last):
  File "/home/solomoncyj/Downloads/numpy/numpy/_build_utils/tempita.py", line 6, in <module>
    from Cython import Tempita as tempita
ModuleNotFoundError: No module named 'Cython'
[183/593] Copying file numpy/random/_generator.pyx
ninja: build stopped: subcommand failed.
```

### Python and NumPy Versions:

3.12.4 (main, Jun  7 2024, 00:00:00) [GCC 14.1.1 20240607 (Red Hat 14.1.1-5)]

**Comment by mattip** [comment]
I don't know what `pin` is. How did you set up your virtual environment? Did you install the prerequisites for building, as specified in the `pyproject.toml` file?

**Comment by solomoncyj** [comment]
> I don't know what `pin` is. How did you set up your virtual environment? Did you install the prerequisites for building, as specified in the `pyproject.toml` file?

sory its spin

**Comment by mattip** [comment]
Could you explain a little more how you are setting things up? Are you using a virtual environment? Best would be the entire history of commands you used to build NumPy.

**Comment by solomoncyj** [comment]
```
sudo dnf in python3 pip git clang clang++ ninja
export CC=$(which clang)
export CXX=$(which clang++)
pip install pipx
pipx install spin
git clone https://github.com/cython/cython
cd cython
pipx install .
git clone https://github.com/mesonbuild/meson
cd ../meson
pipx install .
git clone https://github.com/numpy/numpy
cd ../numpy
spin install
```

**Comment by rgommers** [comment]
The reason for this behavior is that Meson only looks for a `cython` executable (i.e., it treats it like a compiler), while the NumPy build expects Cython inside the active build environment (if not, we get `from Cython import Tempita as tempita`).

This is not quite a bug I'd say, but also this is fixable, and we should do that to make things more robust. It basically requires copying what I did for SciPy to vendor `Tempita` (see https://github.com/scipy/scipy/pull/20572), since it's not actually a public part of Cython.

**Comment by twdhwfh** [comment]
Checking for function "sin" with dependency -Im:

YES

Checking for function "cos" with dependency

-Im: YES Checking for function "tan" with dependency -Im:

YES

Checking for function "sinh" with dependency

-Im: YES

Checking for function "cosh" with dependency

-Im: YES Checking for function "tanh" with dependency

-Im: YES

Checking for function "fabs" with dependency

-Im: YES

Checking for function "floor" with dependency

-Im: YES

Checking for function "ceil" with dependency -Im:

YES

Checking for function "sqrt" with dependency

-Im: YES

Checking for function "log10" with dependency

-Im: YES Checking for function "log" with dependency -Im:

YES Checking for function "exp" with dependency -Im:

YES Checking for function "asin" with dependency

-Im: YES Checking for function "acos" with dependency

-Im: YES

Checking for function "atan" with dependency

-Im: YES Checking for function "fmod" with dependency

-Im: YES Checking for function "modf" with dependency

-Im: YES

Checking for function "frexp" with dependency

-Im: YES

Checking for function "Idexp" with dependency

-Im: YES

Checking for function "expm1" with dependency

-Im: YES Checking for function "log1p" with dependency

-Im: YES

Checking for function "acosh" with dependency

-Im: YES

Checking for function "asinh" with dependency

-Im: YES

Checking for function "atanh" with dependency

-Im: YES

Checking for function "rint" with dependency -Im:

YES Checking for function "trunc" with dependency

-Im: YES

Checking for function "exp2" with dependency

-Im: YES

Checking for function "copysign" with -Im: YES

dependency

Checking for function "nextafter" with

dependency-Im: YES Checking for function "cbrt" with dependency

-Im: YES

Checking for function "log2" with dependency

-Im: YES Checking for function "pow" with dependency

-Im: YES Checking for function "hypot" with dependency

-Im: YES

Checking for function "atan2" with dependency

-Im: YES

Checking for function "csin" with dependency

-Im: NO

../numpy/_core/meson.build:202:4: ERROR: Problem encountered: Function 'csin' not found

A full log can be found at /data/data/ ru.iiec.pydroid3/cache/pip-install-avsy677r/

numpy_c5cf903d9f1242c59d4426dd899 a32af/.mesonpy-44f7pngy/meson-logs/

meson-log.txt [end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.

error: metadata-generation-failed

x Encountered error while generating package

metadata. See above for output.

note: This is an issue with the package mentioned

above, not pip.

hint: See above for details.

**Comment by mattip** [comment]
@twdhwfh I hid your comment. If you have something to contribute to the discussion, we can re-display your comment.
