### ISSUE TITLE
BUG: ModuleNotFoundError: No module named 'distutils.msvccompiler' on Linux

### ISSUE THREAD

**Issue by PinkPandaKatie** [numpy/numpy#27405]
### Describe the issue:

The module `numpy/distutils/command/config.py` unconditionally imports `numpy.distutils.mingw32ccompiler`, which unconditionally imports `distutilis.msvccompiler`. This module is not present on Linux, for obvious reasons.

The only function that `config.py` imports from `mingw32ccompiler` is `get_manifest`, which it only calls if `self.compiler.compiler_type == 'mingw32'`, which is plausible if cross compiling, I guess.

The only function that `mingw32ccompiler` imports from `distutils.msvccompiler` is `get_build_version` as `get_build_msvc_version`. `mingw32ccompiler.generate_manifest`,` calls this function, and is perfectly capable of handling if it returns `None`, indicating that MSVC is not installed.

The solution is as simple as catching `ImportError` when attempting to import `distutils.msvccompiler` and providing a stub for `get_build_msvc_version` which returns `None`:

```
try:
    from distutils.msvccompiler import get_build_version as get_build_msvc_version
except ImportError:
    def get_build_msvc_version():
        return None
```

I'll have a PR for this in just a few minutes.

### Reproduce the code example:

```python
import numpy.distutils.core
```

### Error message:

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/numpy/distutils/core.py", line 24, in <module>
    from numpy.distutils.command import config, config_compiler, \
  File "/usr/lib/python3/dist-packages/numpy/distutils/command/config.py", line 19, in <module>
    from numpy.distutils.mingw32ccompiler import generate_manifest
  File "/usr/lib/python3/dist-packages/numpy/distutils/mingw32ccompiler.py", line 30, in <module>
    from distutils.msvccompiler import get_build_version as get_build_msvc_version
ModuleNotFoundError: No module named 'distutils.msvccompiler'
```

### Python and NumPy Versions:

1.21.5
3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0]

### Context for the issue:

I found this while creating a `setup.py` which uses `Cython.Build.cythonize` to auto-build a Cython module. The module itself doesn't even use numpy, but since it is installed, there is some hook which Cython picks up on which causes it to pull in `numpy.distutils.core`, which leads to the given error.

**Comment by mattip** [comment]
`numpy.distutils` is deprecated, and unfortunately setuptools keeps removing things needed to keep it working. I think they removed this in version 74. See the similar python-cffi/cffi#117. The solution is for cython to avoid using numpy.distutils, not to patch the deprecated module. This sounds familiar, and indeed I submitted https://github.com/cython/cython/pull/5620, which was merged over a year ago. Please update your versin of cython.

**Comment by v-49** [comment]
This problem is also encountered today, with some projects specifying older versions.

**Comment by lpdink** [comment]
@mattip Same error on `pip wheel --no-cache-dir --use-pep517 "numba (==0.51.2)"`. `Python 3.10.9` `setuptools 73.0.1`. I have no idea about this error, could you please tell me how to install this version of numba?

**Comment by the-star-sea** [comment]
also meet one and it is a disaster for me

**Comment by mattip** [comment]
Anyone chiming in here: please include what version of cython you are using.

**Comment by krystophny** [comment]
I want to add here that the reason for this bug is likely that `f2py` hardcodes the deprecated `distutils` backend for `python<3.12`. I can reproduce it on both, Linux and MacOS by using `setuptools>=74` on `python3.11`. 

Why this is relevant: Debian stable and some other distros still rely on `python3.11` which has end-of-life in 2027-10, and users update their packages via `pip` in a `venv`.

Proposed fix: In `f2py`, check `setuptools` version in addition to Python version, and set `meson` backend for `setuptools>=74` in any case.

```
Traceback (most recent call last):
  File "/Users/ert/code.mac/.venv/bin/f2py-f90wrap", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/ert/code.mac/.venv/lib/python3.11/site-packages/f90wrap/scripts/f2py_f90wrap.py", line 219, in main
    numpy.f2py.main()
  File "/Users/ert/code.mac/.venv/lib/python3.11/site-packages/numpy/f2py/f2py2e.py", line 770, in main
    run_compile()
  File "/Users/ert/code.mac/.venv/lib/python3.11/site-packages/numpy/f2py/f2py2e.py", line 594, in run_compile
    build_backend = f2py_build_generator(backend_key)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ert/code.mac/.venv/lib/python3.11/site-packages/numpy/f2py/_backends/__init__.py", line 6, in f2py_build_generator
    from ._distutils import DistutilsBackend
  File "/Users/ert/code.mac/.venv/lib/python3.11/site-packages/numpy/f2py/_backends/_distutils.py", line 3, in <module>
    from numpy.distutils.core import setup, Extension
  File "/Users/ert/code.mac/.venv/lib/python3.11/site-packages/numpy/distutils/core.py", line 24, in <module>
    from numpy.distutils.command import config, config_compiler, \
  File "/Users/ert/code.mac/.venv/lib/python3.11/site-packages/numpy/distutils/command/config.py", line 19, in <module>
    from numpy.distutils.mingw32ccompiler import generate_manifest
  File "/Users/ert/code.mac/.venv/lib/python3.11/site-packages/numpy/distutils/mingw32ccompiler.py", line 27, in <module>
    from distutils.msvccompiler import get_build_version as get_build_msvc_version
ModuleNotFoundError: No module named 'distutils.msvccompiler'
make: *** [f2py] Error 1
```

**Comment by charris** [comment]
The core problem was the setuptools version. `distutils.msvccompiler` wasn't the only module that went missing in setuptools, but it was the most visible.

**Comment by krystophny** [comment]
Yes. We are still dealing with legacy code supporting Python 3.8-3.10 and I solved this now in a very generic way also for older numpy versions by setting the environment variable SETUPTOOLS_USE_DISTUTILS=1 . For a setup.py that works with both old and new versions see https://gist.github.com/krystophny/7a0e15050b3575dbac2054af62e7fccb
