### ISSUE TITLE
BUG: make f2py an optional sub-module again

### ISSUE THREAD

**Issue by opoplawski** [numpy/numpy#28016]
### Describe the issue:

Fedora has long packaged numpy with f2py as an optional component.  With numpy 1.26.4 without f2py present, you were able to do:
```
from numpy import *
```
without any errors.  Now however:

### Reproduce the code example:

```python
from numpy import *
```

### Error message:

```shell
Traceback (most recent call last):
  File "<python-input-0>", line 1, in <module>
    from numpy import *
  File "/usr/lib64/python3.13/site-packages/numpy/__init__.py", line 361, in __getattr__
    import numpy.f2py as f2py
ModuleNotFoundError: No module named 'numpy.f2py'
```

### Python and NumPy Versions:

2.2.0
3.13.0 (main, Oct  8 2024, 00:00:00) [GCC 14.2.1 20240912 (Red Hat 14.2.1-4)]

### Context for the issue:

See also the discussion in https://bugzilla.redhat.com/show_bug.cgi?id=2332307

We would like to be able to keep f2py optional as only limited modules make use of it and it brings in a dependency on the python development environment.  Thank you for your consideration.

**Comment by rgommers** [comment]
Thanks for the report @opoplawski. I relabeled the issue - I wouldn't say it's a bug, since splitting `numpy` into parts like that is not a thing that is supported nor seems very reasonable to do. If any distro does something like that, they're usually responsible for not breaking anything else - and that includes `from numpy import *`. So it seems pretty clear cut that this is a Fedora bug.

That said, let's consider the issue in more detail and see if we're willing to help, or if Fedora should choose between carrying its own patch or undoing the splitting off of `numpy.f2py`.

**Comment by rgommers** [comment]
For the record, the reasoning in the upstream bug report seems wrong to me - `f2py` can be used to transpile C code without any other dependencies. Saying that it is unusable without a compiler can also be said of `numpy.distutils`, or of `cython`, etc. - it doesn't seem all that useful to make such a claim.

In general, the correct thing to do for transpilers seems to be to not make them depend on a particular compiler, but leave that to the user of the package - that way they can ensure they are using it with their compiler of choice, rather than forcing one on them.

**Comment by rgommers** [comment]
The whole of `numpy/__init__.py` was reworked for numpy 2.0. The reasoning of what's included/excluded is given here:

https://github.com/numpy/numpy/blob/f36fa72c2c0d8efb2d17662cb9ddb846b6a9cf24/numpy/__init__.py#L244-L252

Basically: all public submodules are included, except for two that give warnings because of being deprecated or experimental.

Patching `f2py` out of that should fix the problem.

**Comment by HaoZeke** [comment]
IMO the patch should be at a Fedora level, just because NumPy is not meant to be used in split package form, and there might be other issues with this in the long run..

**Comment by rgommers** [comment]
That patch seems reasonable to me, not sure you can do much better.

> For now at least I think fedora will just make sure the f2py is always installed with numpy.

That is better than the patch. Of course that's still worse than just discarding the split package completely, since it sounds like you'll do it by declaring a dependency between the split packages, which then makes `numpy` in Fedora depend on a Fortran compiler, which isn't really desirable.
