### ISSUE TITLE
BUG: Functions in 'core.fromnumeric' are abusing homonym attributes of foreign objects

### ISSUE THREAD

**Issue by miccoli** [numpy/numpy#28024]
Since there is a well defined [interoperability protocol](https://numpy.org/doc/stable/user/basics.interoperability.html#operating-on-foreign-objects-without-converting) I was assuming that it is safe to call numpy functions on foreign objects, until I discovered this strange behaviour:
```python
>>> import numpy as np
>>> class Kls: pass
...
>>> a = Kls()
>>> a.mean = None
>>> np.mean(a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/miccoli/work/uvenv/bigdata/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py", line 3858, in mean
    return mean(axis=axis, dtype=dtype, out=out, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not callable
>>> a.mean = lambda : 0
>>> np.mean(a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/miccoli/work/uvenv/bigdata/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py", line 3858, in mean
    return mean(axis=axis, dtype=dtype, out=out, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: <lambda>() got an unexpected keyword argument 'axis'
```

So if `np.mean(a)` discovers that `a` has a `mean` attribute, it blindly assumes that it is a method with the same semantics and signature of `np.mean`.

*This is crazy!* numpy does not owns the `mean` method and in fact other libraries implemented it in different ways:
```python
>>> import polars as pl
>>> a = pl.Series([0, 1, 2])
>>> np.mean(a) #broken
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/miccoli/work/uvenv/bigdata/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py", line 3858, in mean
    return mean(axis=axis, dtype=dtype, out=out, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Series.mean() got an unexpected keyword argument 'axis'
>>> np.mean(np.asarray(a)) #works
np.float64(1.0)
```

The details of this specific case can be found in

<details>

https://github.com/numpy/numpy/blob/b81068c02fea0b31de768058ffb94a878aa485fc/numpy/_core/fromnumeric.py#L3852-L3861

</details>

but unfortunately this same (broken?) behaviour is common to most functions in <https://github.com/numpy/numpy/blob/b81068c02fea0b31de768058ffb94a878aa485fc/numpy/_core/fromnumeric.py>

**Comment by eendebakpt** [comment]
The behaviour was added a long time ago, commit https://github.com/numpy/numpy/commit/67940c3d69c51bae3561695693020ced3d9d470a in 2006. That probably means that for backwards compatibility reasons we cannot change this behaviour. 

Maybe we could change the implementation so that if an object has `__array_function__` or `__array_ufunc__` those are tried first. That still leaves the issue that numpy will call `a.mean()` for `a=Kls()` in the example above.

**Comment by miccoli** [comment]
@seberg :
> As a work-around, polars could ask to never be handled by NumPy by adding the new protocols and simply raising an informative error that suggests to either use `to_numpy()` or use the polars function.

Actually polars Series implement both `__array__` and `__array_ufunc__`: but as noted by @eendebakpt the homonym attribute is tried first. (BTW I noticed this problem because `__array_ufunc__` is implemented only partially: pola-rs/polars#20303 and I would like to open a PR to fix that issue.)

I suppose that the legacy behaviour of 67940c3 was meant not for foreign objects but for `ndarray` subclasses, or at least back in 2006 it was sensible to assume that all foreign libraries would try to mimic the numpy API.

All this said, while there is no doubt that in 2025 the current behaviour is not desiderable, I agree that simply disabling homonym method delegation could be very disruptive. However at least some mitigation steps should be taken. I would suggest (not in order of importance, and with reference only to `np.mean` but of course this should be extended to all relevant functions):

- check `callable(a.mean)`
- try to delegate to `__array_ufunc__` first (is this possible? technically `np.mean` is *not* a ufunc)
- plan a deprecation cycle
- find out which foreign libraries implement the numpy `a.mean` API on their objects to assess how changes here would affect users.

**Comment by eendebakpt** [comment]
Also see the interesting discussion https://discuss.python.org/t/math-exp-and-math-log-delegate-to-exp-and-log-methods/73495/44 where the same issue is signaled. @ngoldbaum

**Comment by seberg** [comment]
> Actually polars Series implement both __array__ and __array_ufunc__

Not really, `__array_function__` is tried first.

**Comment by seberg** [comment]
@eendebakpt that is a different issue, it is about what object ufuncs should use as elentwise function when there is no obvioius Python operator to use.

**Comment by miccoli** [comment]
> > Actually polars Series implement both **array** and **array_ufunc**
> 
> Not really, `__array_function__` is tried first.

I see: for `np.mean(a)` the order is
1. `a.__array_function__`
2. `a.mean`
3. `a.__array_ufunc__`

while for `np.sin(a)` we have
1. `a.__array_ufunc__`
2. `a.sin`

This actually means that for shadowing its own methods from numpy, a class should implement both `__array_function__` and `__array_ufunc__`... sorry I missed this point, which is actually explained in [NEP 18](https://numpy.org/neps/nep-0018-array-function-protocol.html#nep-18-a-dispatch-mechanism-for-numpy-s-high-level-array-functions)

**Comment by miccoli** [comment]
Thanks for the discussion, now the situation is much more clear to me. I will try to summarise what I found out, and add a final concern at the end of this comment. Please let me know if there is still some inaccuracy in my understanding.

I will limit the discussion on what can be done from a pure python implementation.

- First of all there is a clear path to opt-in or opt-out implementing *both* `__array_ufunc__` and `__array_function__`: control on the return value is complete for both ufuncs and not-ufuncs.

- If `__array_ufunc__` is missing, ufuncs will try the array interface, `__array__`, and as a last resort the homonym method, i.e. `np.sin(a)` will return `a.sin()` (possibly wrapped by `__array_wrap__` if defined).

- If `__array_function__` is missing, non-ufuncs will **first** try the homonym method and then go down, very aggressively, the path of computing via `__array__`.

Of course we all can agree that it is bad practice to assume that if a foreign object implements a `mean` method, this should strictly adhere to the numpy API (with its `(axis, type, out)` args). However I agree that since the ship has long sailed, reverting this could be very difficult and disruptive.

What I think should still be open to discussion is the fact that `np.mean(a)` will try **first** `a.mean` even if `__array__` is implemented, as demonstrate by the following snippet

```python
class Kls:
    def __array__(self):
        return np.array((1, 2, 3))

    @property
    def mean(self):
        return 2


a = Kls()
m = a.mean  # m == 2
m = np.mean(np.asarray(a))  # m == np.float64(2.0)
m = np.mean(a)  # raises "TypeError: 'int' object is not callable"
```

**Comment by seberg** [comment]
> will try first `a.mean` even if `__array__` is

Hmmm, I doubt that this changes the situation much (w.r.t how disruptive the change would be).
In the end, won't many/most of the problematic objects (e.g. pandas dataframe, or even torch tensors) already have an `__array__` attribute, but still return their own type for `np.mean()` right now?
(IIRC, `np.asarray(torch)` raises an error, which is also disruptive, but maybe more desirable.)

I wonder if we could nudge libraries towards implementing `__array_function__`.  Although, I am not sure that is quite convenient enough for having _partial_ support.

Could there be a (very slow) deprecation path for this?  Right now, I am not sure...

**Comment by miccoli** [comment]
Unfortunately we are here at a dead end: there is no doubt how full numpy iteroperability should be implemented, and this is detailed clearly in the docs.

However, according to the docs at [1. Using arbitrary objects in NumPy](https://numpy.org/doc/stable/user/basics.interoperability.html#using-arbitrary-objects-in-numpy) also *partial* interoperability is possible, by implementing only the `__array__` method.

My point here is that given this class
```python
class Kls:
    def __array__(self, dtype=None, copy=None):
        if copy is False:
            raise ValueError("`copy=False` isn't supported. A copy is always created.")
        return np.array((1, 2, 3), dtype=dtype)

    @property
    def mean(self):
        return 2
```
the fact that `np.mean(Kls())` raises is a numpy bug, not a downstream one.

Is this bug unfixable? OK, then at least a warning in the docs should be added that for legacy compatibility, there are numpy functions that can circumvent the `__array__` method

**Comment by seberg** [comment]
Fair, the docs can note that these attributes are used currently.  Is this the spefici use-case?  It may be plausible to test for the attribute being callable.

**Comment by miccoli** [comment]
> Fair, the docs can note that these attributes are used currently. Is this the spefic use-case?

No, this was just for demonstration. I noticed this behaviour when calling numpy functions on polars dataframes and series, which claim numpy interoperability.

>  It may be plausible to test for the attribute being callable.

I will watch this thread, and if there is no other comments on this, I hope to find time (first months of 2025) for opening a PR that

1. adds a test for the attribute being `callable`;  
2. adds a note in the docs about the legacy delegation on methods with the same name; the new docs should also nudge developers to consider also the implementation of `__array_ufunc__` and `__array_function__` for best user experience and making downstream code future-proof;
3. adds unit tests to check if the new claims in docs are accurate.

A different point, on which I have no opinion right now, is when to start a (slow) deprecation path that forbids delegation to same name attributes, and forces the use of `__array_ufunc__` and `__array_function__` protocols.
