### ISSUE TITLE
Float-to-int data type coercion fails with opaque AttributeError when some magic number is exceeded

### ISSUE THREAD

**Issue by brianthelion** [numpy/numpy#3409]
On vanilla 1.7.1 from Ubuntu Raring sources:

```python
[GCC 4.7.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> numpy.__version__
'1.7.1'
>>> X = numpy.zeros(1,dtype=int)
>>> numpy.iinfo(int).max
9223372036854775807
>>> X[0] = 9223372036854775807
>>> X[0] = 9223372036854775808
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OverflowError: Python int too large to convert to C long
>>> # so far so good
...
>>> X[0] = numpy.array([9223372036854775807-512],dtype=float)
>>> X[0] = numpy.array([9223372036854775807-511],dtype=float)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: setting an array element with a sequence.
>>> # WTF?!
```

The "magic number" is the system's maximum int64 value minus 512. Weird.

**Comment by seberg** [comment]
Just gonna close this, the errors are now chained (so you see why it fails) a bit better (sure, you don't see the float -> int part, but how much can you expect...).

As to the whole "sequence" thing, there is a deprecation warning to make that fail earlier anyway.
