### ISSUE TITLE
BUG: str and repr special methods blow up memory usage

### ISSUE THREAD

**Issue by cpelley** [numpy/numpy#3544]
```Python
>>> arr = np.zeros([43200, 21600], dtype=np.int8)
>>> z = np.ma.masked_values(arr, 0)
>>> print z
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/sci/lib/python2.7/site-packages/numpy/ma/core.py", line 3530, in __str__
    res = self._data.astype("|O8")
MemoryError
```

Calculated memory usage:
(43200*21600.*8) + (43200*21600)
8398080000.0 bits --> 0.9776651859283 GB

**Comment by saimn** [comment]
Following #6732 I also see a huge memory peak when printing a masked array, and the worse is that this memory is then lost, even if the array is dereferenced.
```python
In [1]: import ipython_memory_usage.ipython_memory_usage as imu

In [2]: import numpy as np

In [3]: imu.start_watching_memory()
In [3] used 10.5586 MiB RAM in 4.25s, peaked 0.00 MiB above current, total RAM usage 35.71 MiB

In [4]: a = np.zeros((10000, 10000))
In [4] used 0.0312 MiB RAM in 0.11s, peaked 0.00 MiB above current, total RAM usage 35.74 MiB

In [5]: a[:] = 1
In [5] used 763.0000 MiB RAM in 0.21s, peaked 0.00 MiB above current, total RAM usage 798.74 MiB

In [6]: m = np.ma.MaskedArray(data=a, mask=np.ma.nomask, dtype=float, copy=False)
In [6] used 0.0000 MiB RAM in 0.11s, peaked 0.00 MiB above current, total RAM usage 798.74 MiB

In [7]: m
Out[7]: 
masked_array(data =
 [[ 1.  1.  1. ...,  1.  1.  1.]
 [ 1.  1.  1. ...,  1.  1.  1.]
 [ 1.  1.  1. ...,  1.  1.  1.]
 ..., 
 [ 1.  1.  1. ...,  1.  1.  1.]
 [ 1.  1.  1. ...,  1.  1.  1.]
 [ 1.  1.  1. ...,  1.  1.  1.]],
             mask =
 False,
       fill_value = 1e+20)
In [7] used 0.0664 MiB RAM in 0.11s, peaked 0.00 MiB above current, total RAM usage 798.81 MiB

In [8]: m = np.ma.MaskedArray(data=a, mask=False, dtype=float, copy=False)
In [8] used 95.4336 MiB RAM in 10.31s, peaked 1525.52 MiB above current, total RAM usage 894.24 MiB

In [11]: m
Out[11]: 
masked_array(data =
 [[1.0 1.0 1.0 ..., 1.0 1.0 1.0]
 [1.0 1.0 1.0 ..., 1.0 1.0 1.0]
 [1.0 1.0 1.0 ..., 1.0 1.0 1.0]
 ..., 
 [1.0 1.0 1.0 ..., 1.0 1.0 1.0]
 [1.0 1.0 1.0 ..., 1.0 1.0 1.0]
 [1.0 1.0 1.0 ..., 1.0 1.0 1.0]],
             mask =
 [[False False False ..., False False False]
 [False False False ..., False False False]
 [False False False ..., False False False]
 ..., 
 [False False False ..., False False False]
 [False False False ..., False False False]
 [False False False ..., False False False]],
       fill_value = 1e+20)
In [11] used 2343.6602 MiB RAM in 2.03s, peaked 762.87 MiB above current, total RAM usage 3237.91 MiB

In [12]: m
Out[12]: 
masked_array(data =
 [[1.0 1.0 1.0 ..., 1.0 1.0 1.0]
 [1.0 1.0 1.0 ..., 1.0 1.0 1.0]
 [1.0 1.0 1.0 ..., 1.0 1.0 1.0]
 ..., 
 [1.0 1.0 1.0 ..., 1.0 1.0 1.0]
 [1.0 1.0 1.0 ..., 1.0 1.0 1.0]
 [1.0 1.0 1.0 ..., 1.0 1.0 1.0]],
             mask =
 [[False False False ..., False False False]
 [False False False ..., False False False]
 [False False False ..., False False False]
 ..., 
 [False False False ..., False False False]
 [False False False ..., False False False]
 [False False False ..., False False False]],
       fill_value = 1e+20)
In [12] used 0.0156 MiB RAM in 2.02s, peaked 762.94 MiB above current, total RAM usage 3237.92 MiB

In [13]: m.shape
Out[13]: (10000, 10000)
In [13] used 0.0117 MiB RAM in 0.19s, peaked 0.00 MiB above current, total RAM usage 3237.93 MiB

In [14]: m = np.ma.MaskedArray(data=a, mask=np.ma.nomask, dtype=float, copy=False)
In [14] used 0.0039 MiB RAM in 0.18s, peaked 0.00 MiB above current, total RAM usage 3237.94 MiB

In [15]: m
Out[15]: 
masked_array(data =
 [[ 1.  1.  1. ...,  1.  1.  1.]
 [ 1.  1.  1. ...,  1.  1.  1.]
 [ 1.  1.  1. ...,  1.  1.  1.]
 ..., 
 [ 1.  1.  1. ...,  1.  1.  1.]
 [ 1.  1.  1. ...,  1.  1.  1.]
 [ 1.  1.  1. ...,  1.  1.  1.]],
             mask =
 False,
       fill_value = 1e+20)
In [15] used 0.0000 MiB RAM in 0.18s, peaked 0.00 MiB above current, total RAM usage 3237.94 MiB
```

**Comment by saimn** [comment]
Can be closed I think, since #6748 was merged.

**Comment by cpelley** [comment]
Hi @saimn, thanks for your PR.  Testing now.

**Comment by cpelley** [comment]
Confirmed, thanks again @saimn
