### ISSUE TITLE
Test failures on Numpy master + 2.7 (tp_compare didn't return -1 or -2 for exception)

### ISSUE THREAD

**Issue by pv** [numpy/numpy#3778]
I get two test failures with Numpy at 135443768 on Python2.7 with Ubuntu 13.04. Python3.3 is Ok. Interestingly, these do not show up on Travis:

```
======================================================================
ERROR: test_multiarray.TestNewBufferProtocol.test_roundtrip
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pauli/.local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/pauli/prj/scipy/numpy/dist/linux/lib/python2.7/site-packages/numpy/core/tests/test_multiarray.py", line 3214, in test_roundtrip
    assert_raises(ValueError, self._check_roundtrip, x)
  File "/home/pauli/prj/scipy/numpy/dist/linux/lib/python2.7/site-packages/numpy/testing/utils.py", line 1020, in assert_raises
    return nose.tools.assert_raises(*args,**kwargs)
  File "/usr/lib/python2.7/unittest/case.py", line 476, in assertRaises
    callableObj(*args, **kwargs)
  File "/home/pauli/prj/scipy/numpy/dist/linux/lib/python2.7/site-packages/numpy/core/tests/test_multiarray.py", line 3148, in _check_roundtrip
    y = np.asarray(x)
RuntimeWarning: tp_compare didn't return -1 or -2 for exception

======================================================================
ERROR: test_big_arrays (test_io.TestSavezLoad)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pauli/prj/scipy/numpy/dist/linux/lib/python2.7/site-packages/numpy/testing/decorators.py", line 146, in skipper_func
    return f(*args, **kwargs)
  File "/home/pauli/prj/scipy/numpy/dist/linux/lib/python2.7/site-packages/numpy/lib/tests/test_io.py", line 151, in test_big_arrays
    a = np.empty(L, dtype=np.uint8)
MemoryError
```

Requires running tests with `numpy.test(raise_warnings="develop")`. The `tp_compare` error is probably a sign of botched exception handling.

**Comment by charris** [comment]
Hmm, I see a differenct error now.
```
ERROR: test_big_arrays (test_io.TestSavezLoad)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/charris/.local/lib/python2.7/site-packages/numpy/testing/decorators.py", line 147, in skipper_func
    return f(*args, **kwargs)
  File "/home/charris/.local/lib/python2.7/site-packages/numpy/lib/tests/test_io.py", line 200, in test_big_arrays
    npfile = np.load(tmp)
  File "/home/charris/.local/lib/python2.7/site-packages/numpy/lib/npyio.py", line 392, in load
    fid.seek(-N, 1)  # back-up
IOError: [Errno 22] Invalid argument
```

**Comment by mattip** [comment]
All tests pass, please reopen if needed
