### ISSUE TITLE
Bug in resize of structured array (with initial size = 0)

### ISSUE THREAD

**Issue by rougier** [numpy/numpy#4185]
I've tried to resize a record array that was first empty (on purpose, I need it):
```
V = np.zeros(0, dtype=[('a', np.float32, 1)])
print V.dtype
print np.resize(V,2)
```
and I got the following error (while it's working for regular array).
```
Traceback (most recent call last):
 File "test_resize.py", line 10, in <module>
   print np.resize(V,2)
 File "/usr/locaL/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 1053, in resize
   if not Na: return mu.zeros(new_shape, a.dtype.char)
TypeError: Empty data-type
```
Tested on numpy 1.8.0, python 2.7.6, osx 10.9.1 and confirmed by another user.

Full script:
```
V = np.zeros(0, dtype=np.float32)
print V.dtype
print np.resize(V,2)

V = np.zeros(0, dtype=[('a', np.float32, 1)])
print V.dtype
print np.resize(V,2)
```

**Comment by eric-wieser** [comment]
Works fine on 1.14:
```
In [31]: V = np.zeros(0, dtype=[('a', np.float32, 1)])

In [32]: np.resize(V, 2)
Out[32]: array([(0.,), (0.,)], dtype=[('a', '<f4')])
```
