### ISSUE TITLE
problem with np.partition of np.matrix

### ISSUE THREAD

**Issue by argriffing** [numpy/numpy#4308]
copypasting a comment from @empeeu  https://github.com/numpy/numpy/issues/4301#issuecomment-35223028
# 

This actually seems to be a problem with partition.

```
>>> np.median(a, axis=0)
matrix([[ 0.,  1.,  2.]])
>>> np.median(a, axis=1)
matrix([[ 1.]])
>>> np.partition(a, 1, axis=1)
matrix([[0, 1, 2]])
>>> np.partition(a, 1, axis=None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 619, in partition
    a.partition(kth, axis=axis, kind=kind, order=order)
ValueError: kth(=1) out of bounds (1)
>>> np.partition(np.array(a), kth, axis=None)
array([0, 1, 2])
```

median just so happens to use partition as part of its calculation.

**Comment by mattip** [comment]
No longer reproduces, and np.matrix is deprecated. Closing.
```
$ python3.12
Python 3.12.3 (main, Jul 15 2026, 23:46:41) [GCC 13.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>> import numpy as np                                                                                 
>>> np.__version__                                                                                     
'2.6.0.dev0+git20260816.c452636'                                                                       
>>> a = np.matrix([[0, 1, 2]])                                                                         
>>> np.partition(a, 1, axis=None)                                                                      
matrix([[0, 1, 2]])   
```
