### ISSUE TITLE
numpy.ma.core.mvoid.__repr__ and __str__ fail on structured arrays with vector members

### ISSUE THREAD

**Issue by gerritholl** [numpy/numpy#4478]
`numpy.ma.core.mvoid.__repr__` (and `.__str__`) are unable to handle structured arrays with vector members.  See below, tested against the latest git revision:

```
$ python3.3
Python 3.3.2+ (default, Feb 28 2014, 00:52:16) 
[GCC 4.8.1] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> import numpy, numpy.ma
>>> M = numpy.ma.masked_array([((3,4), (4,5,6)), ((7,8), (9,10,11))], dtype=[("A", "<f4", 2), ("B", "<f4", 3)], mask=[((True, False), (False, False, False)), ((False, False), (False, False, False))])
>>> M[0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gerrit/venv/python-3.3-bleed/lib/python3.3/site-packages/numpy/ma/core.py", line 5635, in __repr__
    if not any(m):
  File "/home/gerrit/venv/python-3.3-bleed/lib/python3.3/site-packages/numpy/ma/core.py", line 6025, in __call__
    return method(MaskedArray(a), *args, **params)
  File "/home/gerrit/venv/python-3.3-bleed/lib/python3.3/site-packages/numpy/ma/core.py", line 4302, in any
    d = self.filled(False).any(axis=axis).view(type(self))
  File "/home/gerrit/venv/python-3.3-bleed/lib/python3.3/site-packages/numpy/core/_methods.py", line 33, in _any
    keepdims=keepdims)
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

It fails only on display:

```
>>> aa = M[0]
>>> aa
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gerrit/venv/python-3.3-bleed/lib/python3.3/site-packages/numpy/ma/core.py", line 5635, in __repr__
    if not any(m):
  File "/home/gerrit/venv/python-3.3-bleed/lib/python3.3/site-packages/numpy/ma/core.py", line 6025, in __call__
    return method(MaskedArray(a), *args, **params)
  File "/home/gerrit/venv/python-3.3-bleed/lib/python3.3/site-packages/numpy/ma/core.py", line 4302, in any
    d = self.filled(False).any(axis=axis).view(type(self))
  File "/home/gerrit/venv/python-3.3-bleed/lib/python3.3/site-packages/numpy/core/_methods.py", line 33, in _any
    keepdims=keepdims)
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

so the bug is in `numpy.ma.core.mvoid.__repr__` and its twin brother `numpy.ma.core.mvoid.__str__`.  'numpy.ma.core.MaskedArray.__repr__' has no problem:

```
>>> M[0:1]
masked_array(data = [([3.0, 4.0], [4.0, 5.0, 6.0])],
             mask = [([False, False], [False, False, False])],
       fill_value = ([1.0000000200408773e+20, 1.0000000200408773e+20], [1.0000000200408773e+20, 1.0000000200408773e+20, 1.0000000200408773e+20]),
            dtype = [('A', '<f4', (2,)), ('B', '<f4', (3,))])
```

This is against the latest git revision at the time of writing:

```
>>> import numpy.version
>>> numpy.version.version
'1.9.0.dev-a2177a2'
```

**Comment by gerritholl** [comment]
One of the recent numpy.ma-related fixes has also fixed this one.
