### ISSUE TITLE
ma.sum() does not support keepdims argument

### ISSUE THREAD

**Issue by abalkin** [numpy/numpy#4537]
```
>>> np.sum([1, 2], keepdims=True)
array([3])
>>> ma.sum([1, 2], keepdims=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "numpy/ma/core.py", line 6025, in __call__
    return method(MaskedArray(a), *args, **params)
TypeError: sum() got an unexpected keyword argument 'keepdims'
```

**Comment by seberg** [comment]
Fixed in master.

**Comment by AvlWx2014** [comment]
I'm just running in to this issue with np.ma.mean(). Was that method fixed as part of this effort?
