### ISSUE TITLE
r_[array_of_objects,…] working when adding scalar but failing with object

### ISSUE THREAD

**Issue by lebigot** [numpy/numpy#4559]
`r_[]` works when adding a scalar to an array of objects:

```
>>> class C(object): pass

>>> arr = numpy.full(3, C(), dtype=object)
>>> r_[arr, 42]
array([<__main__.C object at 0x10b08ce50>,
       <__main__.C object at 0x10b08ce50>,
       <__main__.C object at 0x10b08ce50>, 42], dtype=object)
```

However, when adding another object, it fails:

```
>>> r_[arr, C()]
Traceback (most recent call last):
  File "<ipython-input-48-d064e63ae830>", line 1, in <module>
    r_[arr, C()]
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/lib/index_tricks.py", line 326, in __getitem__
    res = _nx.concatenate(tuple(objs), axis=self.axis)
ValueError: all the input arrays must have same number of dimensions
```

This is unexpected.

**Comment by eric-wieser** [comment]
Fixed in #10207
