### ISSUE TITLE
[abrt] numpy-f2py: capi_maps.py:378:getpydocsign:KeyError: 'void'

### ISSUE THREAD

**Issue by opoplawski** [numpy/numpy#4645]
Reported in Fedora here: https://bugzilla.redhat.com/show_bug.cgi?id=1091994

```
This always happens when running "make python" after checking out this
repository:
https://github.com/Ithanil/quaternions-fortran03.git

Version-Release number of selected component:
numpy-f2py-1.8.0-4.fc20

Additional info:
reporter:       libreport-2.2.2
cmdline:        /usr/bin/python /usr/bin/f2py -m quaternions quaternions.F03
executable:     /usr/bin/f2py
kernel:         3.13.10-200.fc20.x86_64
runlevel:       N 5
type:           Python
uid:            1000

Truncated backtrace:
capi_maps.py:378:getpydocsign:KeyError: 'void'

Traceback (most recent call last):
  File "/usr/bin/f2py", line 24, in <module>
    main()
  File "/usr/lib64/python2.7/site-packages/numpy/f2py/f2py2e.py", line 596, in
main
    run_main(sys.argv[1:])
  File "/usr/lib64/python2.7/site-packages/numpy/f2py/f2py2e.py", line 388, in
run_main
    ret=buildmodules(postlist)
  File "/usr/lib64/python2.7/site-packages/numpy/f2py/f2py2e.py", line 335, in
buildmodules
    dict_append(ret[mnames[i]], rules.buildmodule(modules[i], um))
  File "/usr/lib64/python2.7/site-packages/numpy/f2py/rules.py", line 1209, in
buildmodule
    mr, wrap = f90mod_rules.buildhooks(m)
  File "/usr/lib64/python2.7/site-packages/numpy/f2py/f90mod_rules.py", line
178, in buildhooks
    api, wrap=rules.buildapi(b)
  File "/usr/lib64/python2.7/site-packages/numpy/f2py/rules.py", line 1339, in
buildapi
    vrd=routsign2map(rout)
  File "/usr/lib64/python2.7/site-packages/numpy/f2py/capi_maps.py", line 601,
in routsign2map
    ret['pydocsign'], ret['pydocsignout']=getpydocsign(a, rout)
  File "/usr/lib64/python2.7/site-packages/numpy/f2py/capi_maps.py", line 353,
in getpydocsign
    return getpydocsign(af, var['vars'][af])
  File "/usr/lib64/python2.7/site-packages/numpy/f2py/capi_maps.py", line 378,
in getpydocsign
    sig='%s : %s %s%s'%(a, opt, c2py_map[ctype], init)
KeyError: 'void'

Local variables in innermost frame:
opt: ''
a: 'newDefaultQuaternion'
out_a: 'newDefaultQuaternion'
k: 'out=newDefaultQuaternion'
ctype: 'void'
init: ''
sigout: 'newDefaultQuaternion'
sig: 'newDefaultQuaternion'
var: {'typespec': 'type', 'intent': ['out', 'out=newDefaultQuaternion'],
'typename': 'quaternion'}
```

**Comment by HaoZeke** [comment]
This is a special case of the more general problem (not supporting derived types). When derived type support lands this shouldn't be an issue anymore.

**Comment by bilderbuchi** [comment]
> This is a special case of the more general problem (not supporting derived types). When derived type support lands this shouldn't be an issue anymore.

@HaoZeke @pearu is support for derived types being tracked anywhere? I could not find an issue for that?

cf. #15157

**Comment by HaoZeke** [comment]
> > This is a special case of the more general problem (not supporting derived types). When derived type support lands this shouldn't be an issue anymore.
> 
> @HaoZeke @pearu is support for derived types being tracked anywhere? I could not find an issue for that? Or is that #15157?

There's this draft PR: https://github.com/numpy/numpy/pull/20770

Along with an old repo for brainstorming: https://github.com/HaoZeke/f2py_derived_nep

I will probably get the draft in sometime (almost forgot) and the remaining issues can be handled in followups.

**Comment by bilderbuchi** [comment]
Thank you! In my defense (😅) I stand surprised that my original search term `derived type f2py` did not show that issue (because f2py occurs only in the label, not the issue text. Learned something new  :D
