### ISSUE TITLE
Maximum recursion depth exceeded error with Intel compiler

### ISSUE THREAD

**Issue by sebp** [numpy/numpy#4657]
Trying to build numpy 1.8.1 using Intel compiler results in RuntimeError: maximum recursion depth exceeded while calling a Python object

Setup:
- Fedora 20
- Python 3.3.2
- Intel Parallel Studio XE 2013 SP1 Update 2
- Compiling takes place in an virutalenv environment

site.cfg contains
```
[mkl]
library_dirs = /opt/intel/mkl/lib/intel64/
include_dirs = /opt/intel/mkl/include/
mkl_libs = mkl_rt
lapack_libs =
```

Output of the command python setup.py config --compiler=intelem --fcompiler=intelem

```
Running from numpy source directory.
/usr/lib64/python3.3/distutils/dist.py:257: UserWarning: Unknown distribution option: 'test_suite'
  warnings.warn(msg)
F2PY Version 2
blas_opt_info:
blas_mkl_info:
  FOUND:
    include_dirs = ['/opt/intel/mkl/include/']
    library_dirs = ['/opt/intel/mkl/lib/intel64/']
    define_macros = [('SCIPY_MKL_H', None)]
    libraries = ['mkl_rt', 'pthread']

  FOUND:
    include_dirs = ['/opt/intel/mkl/include/']
    library_dirs = ['/opt/intel/mkl/lib/intel64/']
    define_macros = [('SCIPY_MKL_H', None)]
    libraries = ['mkl_rt', 'pthread']

non-existing path in 'numpy/lib': 'benchmarks'
lapack_opt_info:
openblas_info:
  libraries  not found in ['/opt/learning/lib', '/usr/local/lib64', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']
  NOT AVAILABLE

lapack_mkl_info:
mkl_info:
  FOUND:
    include_dirs = ['/opt/intel/mkl/include/']
    library_dirs = ['/opt/intel/mkl/lib/intel64/']
    define_macros = [('SCIPY_MKL_H', None)]
    libraries = ['mkl_rt', 'pthread']

  FOUND:
    include_dirs = ['/opt/intel/mkl/include/']
    library_dirs = ['/opt/intel/mkl/lib/intel64/']
    define_macros = [('SCIPY_MKL_H', None)]
    libraries = ['mkl_rt', 'pthread']

  FOUND:
    include_dirs = ['/opt/intel/mkl/include/']
    library_dirs = ['/opt/intel/mkl/lib/intel64/']
    define_macros = [('SCIPY_MKL_H', None)]
    libraries = ['mkl_rt', 'pthread']

/usr/lib64/python3.3/distutils/dist.py:257: UserWarning: Unknown distribution option: 'define_macros'
  warnings.warn(msg)
running config
```

Output of command python setup.py build --compiler=intelem --fcompiler=intelem

```
running build
running config_cc
unifing config_cc, config, build_clib, build_ext, build commands --compiler options
running config_fc
unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
running build_src
build_src
building py_modules sources
building library "npymath" sources
Found executable /opt/intel/composer_xe_2013_sp1.2.144/bin/intel64/icc
customize IntelEM64TFCompiler
Found executable /opt/intel/composer_xe_2013_sp1.2.144/bin/intel64/ifort
customize IntelEM64TFCompiler using config
C compiler: icc -m64 -fPIC

compile options: '-Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/mul
tiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -Inumpy/core/include -I/usr/include/python3.3m -c'
icc: _configtest.c
Running from numpy source directory.
/usr/lib64/python3.3/distutils/dist.py:257: UserWarning: Unknown distribution option: 'test_suite'
  warnings.warn(msg)
/usr/lib64/python3.3/distutils/dist.py:257: UserWarning: Unknown distribution option: 'define_macros'
  warnings.warn(msg)
Traceback (most recent call last):
  File "setup.py", line 239, in <module>
    setup_package()
  File "setup.py", line 231, in setup_package
    setup(**metadata)
  File "/home/poelsterl/Downloads/packages/numpy-1.8.1/numpy/distutils/core.py", line 169, in setup
    return old_setup(**new_attr)
  File "/usr/lib64/python3.3/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib64/python3.3/distutils/dist.py", line 929, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python3.3/distutils/dist.py", line 948, in run_command
    cmd_obj.run()
  File "/home/poelsterl/Downloads/packages/numpy-1.8.1/numpy/distutils/command/build.py", line 39, in run
    old_build.run(self)
  File "/usr/lib64/python3.3/distutils/command/build.py", line 126, in run
    self.run_command(cmd_name)
  File "/usr/lib64/python3.3/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python3.3/distutils/dist.py", line 948, in run_command
    cmd_obj.run()
  File "/home/poelsterl/Downloads/packages/numpy-1.8.1/numpy/distutils/command/build_src.py", line 153, in run
    self.build_sources()
  File "/home/poelsterl/Downloads/packages/numpy-1.8.1/numpy/distutils/command/build_src.py", line 164, in build_sources
    self.build_library_sources(*libname_info)
  File "/home/poelsterl/Downloads/packages/numpy-1.8.1/numpy/distutils/command/build_src.py", line 299, in build_library_sources
    sources = self.generate_sources(sources, (lib_name, build_info))
  File "/home/poelsterl/Downloads/packages/numpy-1.8.1/numpy/distutils/command/build_src.py", line 386, in generate_sources
    source = func(extension, build_dir)
  File "numpy/core/setup.py", line 683, in get_mathlib_info
    mlibs = check_mathlib(config_cmd)
  File "numpy/core/setup.py", line 375, in check_mathlib
    if config_cmd.check_func("exp", libraries=libs, decl=True, call=True):
  File "/home/poelsterl/Downloads/packages/numpy-1.8.1/numpy/distutils/command/config.py", line 330, in check_func
    libraries, library_dirs)
  File "/usr/lib64/python3.3/distutils/command/config.py", line 246, in try_link
    libraries, library_dirs, lang)
  File "/home/poelsterl/Downloads/packages/numpy-1.8.1/numpy/distutils/command/config.py", line 150, in _link
    libraries, library_dirs, lang))
File "/home/poelsterl/Downloads/packages/numpy-1.8.1/numpy/distutils/command/config.py", line 90, in _wrap_method
    ret = mth(*((self,)+args))
  File "/usr/lib64/python3.3/distutils/command/config.py", line 143, in _link
    target_lang=lang)
  File "/usr/lib64/python3.3/distutils/ccompiler.py", line 734, in link_executable
    debug, extra_preargs, extra_postargs, None, target_lang)
  File "/usr/lib64/python3.3/distutils/unixccompiler.py", line 163, in link
    runtime_library_dirs)
  File "/usr/lib64/python3.3/distutils/unixccompiler.py", line 87, in _fix_lib_args
    runtime_library_dirs)
  File "/usr/lib64/python3.3/distutils/unixccompiler.py", line 87, in _fix_lib_args
    runtime_library_dirs)
  File "/usr/lib64/python3.3/distutils/unixccompiler.py", line 87, in _fix_lib_args
    runtime_library_dirs)
  File "/usr/lib64/python3.3/distutils/unixccompiler.py", line 87, in _fix_lib_args
    runtime_library_dirs)
...
```

**Comment by rgommers** [comment]
No follow-up, and we've had many reports of successful builds with the latest Intel compilers. So closing.
