### ISSUE TITLE
masked arrays with subfields throws ValueError on accessing array elements

### ISSUE THREAD

**Issue by stephentu** [numpy/numpy#4846]
Consider the following program:

```python
import numpy as np
import numpy.ma as ma
if __name__ == '__main__':
    # works
    Y = ma.array(np.array([(1,2)], dtype=[('',int),('',float)]), mask=[(True, False)])
    print Y[0]

    # breaks
    Y = ma.array(np.array([(1,[2,3])], dtype=[('',int),('',float,(2,))]), mask=[(True, (False, True))])
    print Y[0]
```

The 2nd construction of the array Y tries to create a numpy array from the mask, which doesn't quite work:

```
(venv)stephentu@fender sandbox3$ python -m pdb test.py 
> /home/stephentu/sandbox3/test.py(1)<module>()
-> import numpy as np
(Pdb) r
(--, 2.0)
--Return--
> /home/stephentu/sandbox3/test.py(11)<module>()->None
-> print Y[0]
(Pdb) 
ValueError: 'setting an array element with a sequence.'
> <string>(1)<module>()->None
(Pdb) 
--Return--
> <string>(1)<module>()->None
(Pdb) 
Traceback (most recent call last):
  File "/usr/lib64/python2.7/pdb.py", line 1314, in main
    pdb._runscript(mainpyfile)
  File "/usr/lib64/python2.7/pdb.py", line 1233, in _runscript
    self.run(statement)
  File "/usr/lib64/python2.7/bdb.py", line 400, in run
    exec cmd in globals, locals
  File "<string>", line 1, in <module>
  File "test.py", line 11, in <module>
    print Y[0]
  File "/usr/lib/python2.7/site-packages/numpy/ma/core.py", line 5614, in __str__
    if (not any(m)):
  File "/usr/lib/python2.7/site-packages/numpy/ma/core.py", line 6020, in __call__
    return method(MaskedArray(a), *args, **params)
  File "/usr/lib/python2.7/site-packages/numpy/ma/core.py", line 2637, in __new__
    _data = np.array(data, dtype=dtype, copy=copy, subok=True, ndmin=ndmin)
ValueError: setting an array element with a sequence.
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /usr/lib/python2.7/site-packages/numpy/ma/core.py(2637)__new__()
-> _data = np.array(data, dtype=dtype, copy=copy, subok=True, ndmin=ndmin)
(Pdb) p data
(True, array([False,  True], dtype=bool))
```

Is there a workaround for the time being? Thanks!

**Comment by eric-wieser** [comment]
This seems to work just fine on 1.11.1

**Comment by eric-wieser** [comment]
Works on master too. But there's still a bug in `Y[0,...]`, which I've moved to #8684
