### ISSUE TITLE
test failures when building win32 binaries with mingw based on gcc 4.8

### ISSUE THREAD

**Issue by juliantaylor** [numpy/numpy#4909]
our current win32 binaries are built with mingw based on gcc 3.4.1 and succeed all their tests.
When one builds with mingw based on gcc 4.8 (via the binaries from the official mingw site) or with mingw64 one gets a few test failures probably related to accuracy of the libm math functions:

```
======================================================================
FAIL: test_umath.TestComplexFunctions.test_loss_of_precision(<class 'numpy.compl
ex128'>,)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\nose-1.3.0-py3.4.egg\nose\case.py", line 1
98, in runTest
    self.test(*self.arg)
  File "C:\Python34\lib\site-packages\numpy\core\tests\test_umath.py", line 1372
, in check_loss_of_precision
    check(x_series, 2*eps)
  File "C:\Python34\lib\site-packages\numpy\core\tests\test_umath.py", line 1343
, in check
    'arcsinh'))
  File "C:\Python34\lib\site-packages\numpy\testing\utils.py", line 53, in asser
t_
    raise AssertionError(smsg)
AssertionError: (143, 1.6419571116474256e-08, 8.2097855180762735e-09, 'arcsinh')


======================================================================
FAIL: test_umath.TestComplexFunctions.test_loss_of_precision_longcomplex
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\nose-1.3.0-py3.4.egg\nose\case.py", line 1
98, in runTest
    self.test(*self.arg)
  File "C:\Python34\lib\site-packages\numpy\testing\decorators.py", line 215, in
 knownfailer
    return f(*args, **kwargs)
  File "C:\Python34\lib\site-packages\numpy\core\tests\test_umath.py", line 1419
, in test_loss_of_precision_longcomplex
    self.check_loss_of_precision(np.longcomplex)
  File "C:\Python34\lib\site-packages\numpy\core\tests\test_umath.py", line 1370
, in check_loss_of_precision
    check(x_series, 50*eps)
  File "C:\Python34\lib\site-packages\numpy\core\tests\test_umath.py", line 1343
, in check
    'arcsinh'))
  File "C:\Python34\lib\site-packages\numpy\testing\utils.py", line 53, in asser
t_
    raise AssertionError(smsg)
AssertionError: (143, 1.6419571116474256e-08, 8.2097855180762735e-09, 'arcsinh')


======================================================================
FAIL: test_random.TestThread.test_normal
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\nose-1.3.0-py3.4.egg\nose\case.py", line 1
98, in runTest
    self.test(*self.arg)
  File "C:\Python34\lib\site-packages\numpy\random\tests\test_random.py", line 6
91, in test_normal
    self.check_function(gen_random, sz=(10000,))
  File "C:\Python34\lib\site-packages\numpy\random\tests\test_random.py", line 6
86, in check_function
    np.testing.assert_array_equal(out1, out2)
  File "C:\Python34\lib\site-packages\numpy\testing\utils.py", line 737, in asse
rt_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "C:\Python34\lib\site-packages\numpy\testing\utils.py", line 663, in asse
rt_array_compare
    raise AssertionError(msg)
AssertionError:
Arrays are not equal

(mismatch 42.83%)
 x: array([[ 1.764052,  0.400157,  0.978738, ...,  0.516872, -0.032921,
         1.298111]])
 y: array([[ 1.764052,  0.400157,  0.978738, ...,  0.516872, -0.032921,
         1.298111]])

----------------------------------------------------------------------
```

the last one is especially worrying as the results should be exactly the same, but they are to about 40% different by about one ulp.
The issue does not occur when one only runs the random testsuite and not everything.
I don't know what is happening here, could it be rounding mode changes that are somehow sticky to a thread?
But to my knowledge numpy does not change the rounding mode anywere.
I have also updated the atlas version used using carls binaries from here: https://nipy.bic.berkeley.edu/scipy_installers/atlas_builds/
maybe it now plays around with rounding mode?

**Comment by charris** [comment]
Is this still a problem with current Numpy wheels?

**Comment by carlkl** [comment]
The pypi numpy wheels (non-MKL ) are build with MSVC now not with mingw32 or mingw-w64.

**Comment by carlkl** [comment]
I forgot to mention https://github.com/numpy/numpy/pull/9574, as 32bit MSVC tends to change the FPU control word under certain circumstances. AFAIK this behaviour is now handled with https://github.com/numpy/numpy/pull/9580

**Comment by charris** [comment]
@juliantaylor  Can this be closed?

**Comment by carlkl** [comment]
@juliantaylor, this issue is outdated as PYPI numpy is build by MSVC with OpenBLAS and should be closed IMHO.

**Comment by rgommers** [comment]
yes this isn't really relevant anymore I think, let's close.
