### ISSUE TITLE
FAIL:test_umath.test_spacing on OpenBSD/amd64 and numpy 1.9.0rc1

### ISSUE THREAD

**Issue by didickman** [numpy/numpy#5019]
On OpenBSD/amd64 I get one regress failure. The full test suite output is at the bottom.

I simplified the test to:
```
import numpy as np

one = np.longdouble(1)
eps = np.finfo(np.longdouble).eps
inf = np.longdouble(np.inf)
with np.errstate(invalid='ignore'):
        np.spacing(one) == eps
```

The value of the last line is False. But strangely, if you remove the "inf = np.longdouble(np.inf)" line, the value of the last line is True.

```
======================================================================
FAIL: test_umath.test_spacingl
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/usr/ports/pobj/py-numpy-1.9.0rc1/fake-amd64/usr/local/lib/python2.7/site-packages/numpy/testing/decorators.py", line 215, in knownfailer
    return f(*args, **kwargs)
  File "/usr/ports/pobj/py-numpy-1.9.0rc1/fake-amd64/usr/local/lib/python2.7/site-packages/numpy/core/tests/test_umath.py", line 1554, in test_spacingl
    return _test_spacing(np.longdouble)
  File "/usr/ports/pobj/py-numpy-1.9.0rc1/fake-amd64/usr/local/lib/python2.7/site-packages/numpy/core/tests/test_umath.py", line 1539, in _test_spacing
    assert_(np.spacing(one) == eps)
  File "/usr/ports/pobj/py-numpy-1.9.0rc1/fake-amd64/usr/local/lib/python2.7/site-packages/numpy/testing/utils.py", line 53, in assert_
    raise AssertionError(smsg)
AssertionError

----------------------------------------------------------------------
Ran 5527 tests in 55.320s

FAILED (KNOWNFAIL=5, SKIP=21, failures=1)
Running unit tests for numpy
NumPy version 1.9.0rc1
NumPy is installed in /usr/ports/pobj/py-numpy-1.9.0rc1/fake-amd64/usr/local/lib/python2.7/site-packages/numpy
Python version 2.7.8 (default, Aug 20 2014, 06:33:09) [GCC 4.2.1 20070719 ]
nose version 1.3.3
```

**Comment by shadchin** [comment]
This issue can be closed. Issue in __builtin_isinf() GCC 4.2.1 on OpenBSD/amd64. The solution to this problem is to switch the native implementation isinf()

**Comment by eric-wieser** [comment]
@shadchin: Can you link to an upstream bug?

**Comment by shadchin** [comment]
I can show my mails from internal chanal
```
Hi,

when working on updating NumPy I found bug in __builtin_isinf(X) on amd64
if X is long double

test.c
-----------------------------------
int main() {
    long double one = 1.0L;
    double inf = 1.0/0.0;
    int i1, i2;
    i1 = __builtin_isinf(inf);
    i2 = __builtin_isinf(one);
    printf("%d %d\n", i1, i2);
    return 0;
}
-----------------------------------

% cc -O0 test.c -o test
% ./test
1 1
(but should have "1 0")

Shortly:
* __builtin_isinf() used our isinf(3)
* our isinf(3) load X from %xmm0
* but __builtin_isinf(for longdouble X) save X on stack, it don't used %xmm0
* and when isinf(3) is called, X is loaded from %xmm0, not from stack
  (in other words, previous double value)

I looked code gcc, but I realized that this is not my level.
Who can help to fix it? ;-)
```
and
```
> > Shortly:
> > * __builtin_isinf() used our isinf(3)
> > * our isinf(3) load X from %xmm0
> > * but __builtin_isinf(for longdouble X) save X on stack, it don't used %xmm0
> > * and when isinf(3) is called, X is loaded from %xmm0, not from stack
> >   (in other words, previous double value)
> 
> Where did you look at __builtin_isinf() and saw that one uses the stack
> and the other xmm0, in the disassembly?

Take this test.c:

int main() {
    long double one = 1.0L;
    int i;
    i = __builtin_isinf(one);
    return 0;
}

cc -O0 -S test.c

test.s:
        movabsq $-9223372036854775808, %rax
        movl    $16383, %edx
        movq    %rax, -32(%rbp)
        movl    %edx, -24(%rbp)
        movq    -32(%rbp), %rax
        movl    -24(%rbp), %edx
        movq    %rax, (%rsp)      <---
        movl    %edx, 8(%rsp)     <--- put X on stack
        movl    $0, %eax
        call    isinf@PLT
        movl    %eax, -12(%rbp)
        movl    $0, %eax
        leave
        ret


from our libc:
0000000000000000 <__isinf>:
   0:   f2 0f 11 44 24 e8       movsd  %xmm0,0xffffffffffffffe8(%rsp)   <--- get X from %xmm0
   6:   8b 44 24 ec             mov    0xffffffffffffffec(%rsp),%eax
   a:   31 d2                   xor    %edx,%edx
   c:   25 ff ff ff 7f          and    $0x7fffffff,%eax
  11:   3d 00 00 f0 7f          cmp    $0x7ff00000,%eax
  16:   75 0a                   jne    22 <__isinf+0x22>
  18:   31 d2                   xor    %edx,%edx
  1a:   83 7c 24 e8 00          cmpl   $0x0,0xffffffffffffffe8(%rsp)
  1f:   0f 94 c2                sete   %dl
  22:   89 d0                   mov    %edx,%eax
  24:   c3                      retq   
```
