### ISSUE TITLE
mingw-w64 builds of numpy.

### ISSUE THREAD

**Issue by Alexpux** [numpy/numpy#5194]
Hi everyone!
I'm maintainer of MSYS2 project. We provide builds of different open source software for Windows using mingw-w64 toolchains. What we provide:
https://github.com/Alexpux/MINGW-packages

We also provide our own Python builds (builded with mingw-w64) and numpy for both 32 and 64 bit platforms. Many users successfully use it.
I'm read your wiki:
https://github.com/numpy/numpy/wiki/Mingw-static-toolchain
https://github.com/numpy/numpy/wiki/Mingw-w64-faq

As we build our own Python - we don't have any limitations with needing statically linked extensions.
To build numpy I'm write small patch that enable 64-bit building and remove functionality for creating import library from MS Python DLL.
Running numpy testsuite for our 64-bit builds are good. For example, 64-bit python-3.4.2:
```
     Ran 5465 tests in 44.226s
     OK (KNOWNFAIL=10, SKIP=17)
```
But we have some failures with numpy testsuite for 32-bit.
```
======================================================================
FAIL: test_fft (test_fftpack.TestFFTThreadSafe)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\msys64\mingw32\lib\python3.4\site-packages\numpy\fft\tests\test_fftpack.py", line 59, in test_fft
    self._test_mtsame(np.fft.fft, a)
  File "c:\msys64\mingw32\lib\python3.4\site-packages\numpy\fft\tests\test_fftpack.py", line 55, in _test_mtsame
    'Function returned wrong value in multithreaded context')
  File "c:\msys64\mingw32\lib\python3.4\site-packages\numpy\testing\utils.py", line 739, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "c:\msys64\mingw32\lib\python3.4\site-packages\numpy\testing\utils.py", line 665, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Arrays are not equal
Function returned wrong value in multithreaded context
(mismatch 1.0%)
 x: array([[ 200.+0.j,    0.+0.j,    0.+0.j, ...,    0.+0.j,    0.+0.j,
           0.+0.j],
       [ 200.+0.j,    0.+0.j,    0.+0.j, ...,    0.+0.j,    0.+0.j,...
 y: array([[ 200.+0.j,    0.+0.j,    0.+0.j, ...,    0.+0.j,    0.+0.j,
           0.+0.j],
       [ 200.+0.j,    0.+0.j,    0.+0.j, ...,    0.+0.j,    0.+0.j,...

======================================================================
FAIL: test_ifft (test_fftpack.TestFFTThreadSafe)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\msys64\mingw32\lib\python3.4\site-packages\numpy\fft\tests\test_fftpack.py", line 63, in test_ifft
    self._test_mtsame(np.fft.ifft, a)
  File "c:\msys64\mingw32\lib\python3.4\site-packages\numpy\fft\tests\test_fftpack.py", line 55, in _test_mtsame
    'Function returned wrong value in multithreaded context')
  File "c:\msys64\mingw32\lib\python3.4\site-packages\numpy\testing\utils.py", line 739, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "c:\msys64\mingw32\lib\python3.4\site-packages\numpy\testing\utils.py", line 665, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Arrays are not equal
Function returned wrong value in multithreaded context
(mismatch 1.0%)
 x: array([[ 1.+0.j,  0.+0.j,  0.+0.j, ...,  0.+0.j,  0.+0.j,  0.+0.j],
       [ 1.+0.j,  0.+0.j,  0.+0.j, ...,  0.+0.j,  0.+0.j,  0.+0.j],
       [ 1.+0.j,  0.+0.j,  0.+0.j, ...,  0.+0.j,  0.+0.j,  0.+0.j],...
 y: array([[ 1.+0.j,  0.+0.j,  0.+0.j, ...,  0.+0.j,  0.+0.j,  0.+0.j],
       [ 1.+0.j,  0.+0.j,  0.+0.j, ...,  0.+0.j,  0.+0.j,  0.+0.j],
       [ 1.+0.j,  0.+0.j,  0.+0.j, ...,  0.+0.j,  0.+0.j,  0.+0.j],...

======================================================================
FAIL: test_irfft (test_fftpack.TestFFTThreadSafe)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\msys64\mingw32\lib\python3.4\site-packages\numpy\fft\tests\test_fftpack.py", line 71, in test_irfft
    self._test_mtsame(np.fft.irfft, a)
  File "c:\msys64\mingw32\lib\python3.4\site-packages\numpy\fft\tests\test_fftpack.py", line 55, in _test_mtsame
    'Function returned wrong value in multithreaded context')
  File "c:\msys64\mingw32\lib\python3.4\site-packages\numpy\testing\utils.py", line 739, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "c:\msys64\mingw32\lib\python3.4\site-packages\numpy\testing\utils.py", line 665, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Arrays are not equal
Function returned wrong value in multithreaded context
(mismatch 49.74874371859296%)
 x: array([[  1.000000e+00,   0.000000e+00,  -1.513028e-15, ...,
          0.000000e+00,  -1.513028e-15,   0.000000e+00],
       [  1.000000e+00,   0.000000e+00,  -1.513028e-15, ...,...
 y: array([[  1.000000e+00,   0.000000e+00,  -1.542765e-15, ...,
          0.000000e+00,  -1.542765e-15,   0.000000e+00],
       [  1.000000e+00,   0.000000e+00,  -1.542765e-15, ...,...

======================================================================
FAIL: test_rfft (test_fftpack.TestFFTThreadSafe)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\msys64\mingw32\lib\python3.4\site-packages\numpy\fft\tests\test_fftpack.py", line 67, in test_rfft
    self._test_mtsame(np.fft.rfft, a)
  File "c:\msys64\mingw32\lib\python3.4\site-packages\numpy\fft\tests\test_fftpack.py", line 55, in _test_mtsame
    'Function returned wrong value in multithreaded context')
  File "c:\msys64\mingw32\lib\python3.4\site-packages\numpy\testing\utils.py", line 739, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "c:\msys64\mingw32\lib\python3.4\site-packages\numpy\testing\utils.py", line 665, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Arrays are not equal
Function returned wrong value in multithreaded context
(mismatch 7.920792079207928%)
 x: array([[ 200.+0.j,    0.+0.j,    0.+0.j, ...,    0.+0.j,    0.+0.j,
           0.+0.j],
       [ 200.+0.j,    0.+0.j,    0.+0.j, ...,    0.+0.j,    0.+0.j,...
 y: array([[ 200.+0.j,    0.+0.j,    0.+0.j, ...,    0.+0.j,    0.+0.j,
           0.+0.j],
       [ 200.+0.j,    0.+0.j,    0.+0.j, ...,    0.+0.j,    0.+0.j,...

----------------------------------------------------------------------
Ran 5473 tests in 44.678s

FAILED (KNOWNFAIL=10, SKIP=17, failures=4)
```

Can someone help to find real problem with it?
Two days ago we have 13 failures but we fix 9 of them in mingw-w64 runtime.

Regards,
Alexey.

**Comment by charris** [comment]
I'm going to close this as outdated. Please reopen if you think there is more to be said.
