### ISSUE TITLE
the error message for accidentally irregular arrays is confusing

### ISSUE THREAD

**Issue by argriffing** [numpy/numpy#5303]
Someone using my code reported this error message, and I would have been able to track down the problem more quickly if the message had been more informative, maybe like `ValueError: setting an irregularly shaped array with a non-object dtype` instead of `ValueError: setting an array element with a sequence.`

```
>>> import numpy as np
>>> np.array([[0, 1], [2]]).dtype
dtype('O')
>>> np.array([[0, 1], [2]], dtype=int).dtype
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: setting an array element with a sequence.
```

**Comment by argriffing** [comment]
Here's a similar [report](http://mail.scipy.org/pipermail/numpy-discussion/attachments/20150105/47f400e3/attachment-0001.html) on the mailing list, where someone is getting weird bug reports from users who accidentally make irregular arrays.

**Comment by njsmith** [comment]
Anyone want to put together a patch?

**Comment by argriffing** [comment]
> I also think we should seriously consider implementing https://github.com/numpy/numpy/issues/5353 (don't create object arrays unless `dtype=object` is explicitly specified) and making it so `np.ndarray` only treats list objects specially, with tuples and other sequence types being treats as array elements instead. 

A similar question again on the mailing list http://mail.scipy.org/pipermail/numpy-discussion/2015-February/072240.html, regarding over-coercion of arrays of tuples into high dimensional arrays.

**Comment by njsmith** [comment]
@agriffing: I think we have a pretty good pile of evidence that there's a
problem here now :-). Any interest in having a go at a making a solution?

On Mon, Feb 9, 2015 at 8:38 AM, argriffing <notifications@github.com> wrote:

> I also think we should seriously consider implementing #5353
> <https://github.com/numpy/numpy/issues/5353> (don't create object arrays
> unless dtype=object is explicitly specified) and making it so np.ndarray
> only treats list objects specially, with tuples and other sequence types
> being treats as array elements instead.
>
> A similar question again on the mailing list
> http://mail.scipy.org/pipermail/numpy-discussion/2015-February/072240.html,
> regarding over-coercion of arrays of tuples into high dimensional arrays.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numpy/numpy/issues/5303#issuecomment-73541097>.
>



-- 
Nathaniel J. Smith -- http://vorpus.org

**Comment by toddrjen** [comment]
>  and making it so np.ndarray only treats list objects specially, with tuples and other sequence types being treats as array elements instead.

As an alternative (or supplement), might it be possible to have a function that explicitly creates object dtype arrays without converting subsequences?  There could be an optional parameter to determine how many dimensions the array should have (which defaults to 1), with it automatically drilling down into subsequences until it reaches that level (and will raise an exception if the shapes don't match up to that level).

**Comment by wackywendell** [comment]
One more use-case: [`ad`](http://pythonhosted.org/ad/), for use with automatic differentiation. I don't think it requires any "clever handling" of mismatched lists, though.

**Comment by njsmith** [comment]
From glancing at the docs I'm 99% sure ad will be fine if we fix this bug. It might need a little more tweaking to live in a world where we fixed #5353 (the no object arrays without explicit request bug), but I'm not sure: generally an object can always opt in to being converted to an array in whatever way it likes, so it would only be objects that aren't designed to be used with numpy that would be affected.

**Comment by wackywendell** [comment]
@njsmith Yes, I completely agree; thanks for checking on that too. I just thought it wouldn't hurt to add another example.

**Comment by amueller** [comment]
Stupid question, but the handling of object arrays is somewhat unrelated to the error message business, right? I expect fixing the explicit passing of ``dtype=object`` doesn't do anything for the ``np.array([[0, 1], [2]], dtype=int)`` case. I just opened and closed #6584, not sure if it deserves it's own issue. Maybe close this and have #5353 and #6584? not sure.

**Comment by WarrenWeckesser** [comment]
Not that any more evidence of the potential confusion of the automatic conversion is needed at this point, but some of y'all might find it interesting.  The somewhat surprising behavior described in the stackoverflow question http://stackoverflow.com/questions/38817357/randomly-select-item-from-list-of-lists-gives-valueerror#38817508 is a consequence of the "automagic" conversion to an object array.

**Comment by mattip** [comment]
Reopening, since #13913 did not correctly handle the corner case `np.array([1, np.array([5])], dtype=int)`. A correct fix would add that to a test, and fix `discover_dimensions` so it does not set `is_object` in this case, then redoing #13913

**Comment by Light--** [comment]
How to fix this?

```
Traceback (most recent call last):
...
    test_set_x.set_value(framesArr, borrow=True)
  File "/home/user/.local/lib/python2.7/site-packages/theano/gpuarray/type.py", line 672, in set_value
    self.container.value = value
  File "/home/user/.local/lib/python2.7/site-packages/theano/gof/link.py", line 477, in __set__
    **kwargs)
  File "/home/user/.local/lib/python2.7/site-packages/theano/gpuarray/type.py", line 266, in filter_inplace
    converted_data = theano._asarray(data, self.dtype)
  File "/home/user/.local/lib/python2.7/site-packages/theano/misc/safe_asarray.py", line 34, in _asarray
    rval = np.asarray(a, dtype=dtype, order=order)
  File "/usr/local/lib/python2.7/dist-packages/numpy-1.11.2-py2.7-linux-x86_64.egg/numpy/core/numeric.py", line 482, in asarray
    return array(a, dtype, copy=False, order=order)

```

**Comment by mattip** [comment]
@Light-- please open a new issue, and describe why you think this is a problem with NumPy. Maybe it is an issue with theano, or some other package you are using? What is `a`, `dtype`, 'order' in the call to `np.asarray(a, dtype=dtype, order=order)`?

**Comment by wackywendell** [comment]
@seberg - thanks for the followup; indeed, that error message is much clearer!
