### ISSUE TITLE
Failure in array() with complex 1-element array in list

### ISSUE THREAD

**Issue by pv** [numpy/numpy#5537]
Spotted on stackoverflow: this fails with a somewhat mysterious error:
```
import numpy as np
print(np.__version__)
# 1.10.0.dev+75eeb75     # similar behavior on Numpy 1.8.2 too
np.array([0, np.array([0.6+1j])])
# Traceback (most recent call last):
#   File "<stdin>", line 1, in <module>
# TypeError: can't convert complex to float
np.array([0, np.array([0.6+1j])], dtype=complex)
# Traceback (most recent call last):
#   File "<stdin>", line 1, in <module>
# TypeError: can't convert complex to float
```

**Comment by seberg** [comment]
I disagree, the expected result should be "Setting an array element with a sequence", but you are right, if someone would finally implement `__complex__` we would actually get what you said, and I will have to live with it probably ;).
