### ISSUE TITLE
Loading object arrays from npz files fails on Python 2.6

### ISSUE THREAD

**Issue by pv** [numpy/numpy#5643]
At 1.10.0.dev0+7ad33a2 on Python 2.6 (Pythons >= 2.7 all work)

```
$ python2.6 runtests.py -g --python
Building, see build.log...
Build OK
Python 2.6.8 (default, Aug  6 2013, 15:33:04) 
[GCC 4.7.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> import numpy as np; np.savez('out.npz', x=np.array([None], dtype=object)); np.load('out.npz')['x']
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/mnt/data/pauli/prj/scipy/numpy/build/testenv/lib/python2.6/site-packages/numpy/lib/npyio.py", line 259, in __getitem__
    return format.read_array(bytes)
  File "/mnt/data/pauli/prj/scipy/numpy/build/testenv/lib/python2.6/site-packages/numpy/lib/format.py", line 615, in read_array
    array = pickle.load(fp)
UnpicklingError: could not find MARK
```

git bisect indicates cfae0143b4
Not sure if this is worth fixing, given that it only affects Python 2.6

**Comment by charris** [comment]
Curious. What is it about 2.6 that doesn't work?

**Comment by bsipocz** [comment]
Please close.
Python 2.6 is not supported any more and according to the report above this didn't affect newer versions.

**Comment by mattip** [comment]
Closing. Please reopen if the problem reappears
