### ISSUE TITLE
place has different casting rules for datetime64

### ISSUE THREAD

**Issue by evanpw** [numpy/numpy#5730]
I can put an integer into a datetime array directly (`__setitem__`), or with putmask, but it fails with a ValueError if I try with place.

```
>>> x = np.array(np.arange(0, 1000, 100), dtype='datetime64[ns]')
>>> mask = np.array([False] * 9 + [True])
>>> 
>>> x[mask] = 0
>>> np.putmask(x, mask, 0)
>>> np.place(x, mask, 0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/numpy/lib/function_base.py", line 1361, in place
    return _insert(arr, mask, vals)
ValueError: Converting an integer to a NumPy datetime requires a specified unit
```

**Comment by WarrenWeckesser** [comment]
This appears to have changed since the issue was created.  Now `place` does not generate an exception:
```
In [1]: import numpy as np

In [2]: np.__version__
Out[2]: '1.22.0.dev0+1223.g00dce9825'

In [3]: x = np.array(np.arange(0, 1000, 100), dtype='datetime64[ns]')

In [4]: mask = np.array([False] * 9 + [True])

In [5]: x[mask] = 0

In [6]: np.putmask(x, mask, 0)

In [7]: np.place(x, mask, 0)

In [8]: x
Out[8]: 
array(['1970-01-01T00:00:00.000000000', '1970-01-01T00:00:00.000000100',
       '1970-01-01T00:00:00.000000200', '1970-01-01T00:00:00.000000300',
       '1970-01-01T00:00:00.000000400', '1970-01-01T00:00:00.000000500',
       '1970-01-01T00:00:00.000000600', '1970-01-01T00:00:00.000000700',
       '1970-01-01T00:00:00.000000800', '1970-01-01T00:00:00.000000000'],
      dtype='datetime64[ns]')

```

Close?  (Or should they all, in fact, raise an exception?)

**Comment by WarrenWeckesser** [comment]
Looks like it has been possible to assign a plain integer to an array of `datetime64` or `timedelta64` for forever.  Closing.
