### ISSUE TITLE
numpy.ma.allequal raises MaskError on structured arrays

### ISSUE THREAD

**Issue by estansifer** [numpy/numpy#5776]
Minimal example code:

    In [1]: import numpy as np
    In [2]: import numpy.ma as ma
    In [3]: import numpy.version
    In [4]: numpy.version.full_version
    Out[4]: '1.9.2'
    In [5]: x = np.zeros((2,), dtype = [('a', int), ('b', int)])
    In [6]: y = ma.array(x)
    In [7]: ma.allequal(y, y)
    ---------------------------------------------------------------------------
    MaskError                                 Traceback (most recent call last)
    <ipython-input-7-5ad9932e8937> in <module>()
    ----> 1 ma.allequal(y, y)
    
    /usr/lib64/python3.4/site-packages/numpy/ma/core.py in allequal(a, b, fill_value)
       6924         y = getdata(b)
       6925         d = umath.equal(x, y)
    -> 6926         dm = array(d, mask=m, copy=False)
       6927         return dm.filled(True).all(None)
       6928     else:
    
    /usr/lib64/python3.4/site-packages/numpy/ma/core.py in array(data, dtype, copy, order, mask, fill_value, keep_mask, hard_mask, shrink, subok, ndmin)
       5881     return MaskedArray(data, mask=mask, dtype=dtype, copy=copy, subok=subok,
       5882                        keep_mask=keep_mask, hard_mask=hard_mask,
    -> 5883                        fill_value=fill_value, ndmin=ndmin, shrink=shrink)
       5884 array.__doc__ = masked_array.__doc__
       5885 

    /usr/lib64/python3.4/site-packages/numpy/ma/core.py in __new__(cls, data, mask, dtype, copy, subok, ndmin, fill_value, keep_mask, hard_mask, shrink, **options)
       2722                     msg = "Mask and data not compatible: data size is %i, " + \
       2723                           "mask size is %i."
    -> 2724                     raise MaskError(msg % (nd, nm))
       2725                 copy = True
       2726             # Set the mask to the new value
    
    MaskError: Mask and data not compatible: data size is 1, mask size is 2.

Python 3.4.3
NumPy 1.9.2

Thanks!

**Comment by OmerJog** [comment]
I'm getting:
`TypeError: ufunc 'equal' did not contain a loop with signature matching types dtype([('a', '<i8'), ('b', '<i8')]) dtype([('a', '<i8'), ('b', '<i8')]) dtype('bool')
`

**Comment by pafonta** [comment]
Hello,

I confirm that `numpy.ma.allequal(...)` fails when:

1. values are strings,
2. both arrays don't have masked values,
3. `dtype` is different from `"object"`.

Tested on Numpy 1.21.2.

Error:
```
UFuncTypeError: ufunc 'equal' did not contain a loop with signature matching types (dtype('<U1'), dtype('<U1')) -> dtype('bool')
```

Reproduce:
```python
# Adding dtype="object" make it work.
x = np.array(["a", "b"])
y = np.array(["a", "b"])

x_masked = np.ma.masked_equal(x, None)
y_masked = np.ma.masked_equal(y, None)

np.ma.allequal(x_masked, y_masked)
```

**Comment by fengluoqiuwu** [comment]
While running the code in `2.2.0.dev0+git20241024.88a6a00` with `Python3.12.7`, I get the following result:
```python
>>> x = np.zeros((2,), dtype = [('a', int), ('b', int)])
>>> y = ma.array(x)
>>> ma.allequal(y, y)
Traceback (most recent call last):
  File "C:\Users\Eden_\Desktop\Coder\MachineLearning\my_numpy\numpy\.venv\Lib\site-packages\IPython\core\interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-27-b101ae1e2482>", line 1, in <module>
    ma.allequal(y, y)
  File "C:\Users\Eden_\Desktop\Coder\MachineLearning\my_numpy\numpy\numpy\ma\core.py", line 8471, in allequal
    d = umath.equal(x, y)
```
I will look into it and try to fix it.
