### ISSUE TITLE
Discrepancy in numpy.round depending on output type

### ISSUE THREAD

**Issue by pitrou** [numpy/numpy#5777]
When the exact result is representable in the output type, there shouldn't be any error such in the int32 case below:

```
>>> arr = np.array([-3.0, -2.5, -2.35, -1.5, 1.5, 2.45, 2.5, 2.55]) * 10
>>> out = np.zeros_like(arr)
>>> np.round(arr, -1, out=out)
array([-30., -20., -20., -20.,  20.,  20.,  20.,  30.])
>>> out = np.zeros_like(arr).astype(np.int32)
>>> np.round(arr, -1, out=out)
array([-30, -20, -20, -10,  10,  20,  20,  20], dtype=int32)
```

**Comment by njsmith** [comment]
Huh, that does look weird and wrong. (For those like me having trouble
seeing the issue -- notice that the 4th output value and others are
radically different in the two cases.) I have no idea why this would happen.

**Comment by pitrou** [comment]
Another more explicit example perhaps:

```
>>> arr = np.array([15., 25., 32.5, 35, 37.5])
>>> out = np.zeros_like(arr).astype(np.int32)
>>> np.round(arr, -1, out)
array([10, 20, 30, 30, 30], dtype=int32)
>>> np.round(arr, -1)
array([ 20.,  20.,  30.,  40.,  40.])
```

The normal behaviour of np.round() is to use "round half to even" . But when an integer array is passed as output, it seems to switch to "round towards zero": notice how 37.5 is rounded to 30 (rather than 40).

**Comment by jaimefrio** [comment]
What numpy version? This is what I get with your example...

```
>>> np.__version__
'1.10.0.dev-0625671'
>>> arr = np.array([15., 25., 32.5, 35, 37.5])
>>> out = np.zeros_like(arr).astype(np.int32)
>>> np.round(arr, -1, out)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\python27\lib\site-packages\numpy\core\fromnumeric.py", line 2692, in
round_
    return round(decimals, out)
TypeError: ufunc 'true_divide' output (typecode 'd') could not be coerced to pro
vided output parameter (typecode 'l') according to the casting rule ''same_kind''
```

**Comment by pitrou** [comment]
1.9.2 here.

**Comment by seberg** [comment]
Seems like the example raises an error for the past 6 years, so closing.
