### ISSUE TITLE
Numpy datetime array pickling/unpickling fails for array constructed from byte string 

### ISSUE THREAD

**Issue by frensjan** [numpy/numpy#5883]
I'm working with Apache Spark to communicate arrays of various datatypes to Pyspark, amongst which timestamps. The timestamps are communicated from Java to python as a byte strings from the raw 64 bit longs representing milliseconds since the unix epoch. These are loaded as numpy arrays with `np.frombuffer(...)`. The initial communication between Java and Python works just fine.

The issues is when these numpy arrays are communicated to another Python process. I think I've managed to isolate the issue to pickling by numpy of the array.

I can successfully pickle and unpickle a datetime array:

``` python
>>> a = np.array(['2015-05-16T12:03:49.669+0200', '2015-05-16T12:04:11.266+0200', '2015-05-16T12:05:19.237+0200'], dtype='datetime64[ms]')
>>> pickle.loads(pickle.dumps(a))
array(['2015-05-16T12:03:49.669+0200', '2015-05-16T12:04:11.266+0200',
       '2015-05-16T12:05:19.237+0200'], dtype='datetime64[ms]')
```

I think the construction of the array from a byte string with `np.frombuffer(...)` isn't really the issue:

``` python
>>> b = np.frombuffer(bytearray(b'\x00\x00\x01M\\.\x06%\x00\x00\x01M\\.Z\x82\x00\x00\x01M\\/d\x05'), '>M8[ms]')
>>> b
array(['2015-05-16T12:03:49.669+0200', '2015-05-16T12:04:11.266+0200',
       '2015-05-16T12:05:19.237+0200'], dtype='datetime64[ms]')
```

However pickling and then unpickling again doesn't:

``` python
>>> unpickled = pickle.loads(pickle.dumps(b))
>>> unpickled
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/frens-jan/Workspaces/tgho/experiments/tsdb/pyspark-cassandra/venv/lib/python2.7/site-packages/numpy/core/numeric.py", line 1653, in array_repr
    ', ', "array(")
  File "/home/frens-jan/Workspaces/tgho/experiments/tsdb/pyspark-cassandra/venv/lib/python2.7/site-packages/numpy/core/arrayprint.py", line 454, in array2string
    separator, prefix, formatter=formatter)
  File "/home/frens-jan/Workspaces/tgho/experiments/tsdb/pyspark-cassandra/venv/lib/python2.7/site-packages/numpy/core/arrayprint.py", line 328, in _array2string
    _summaryEdgeItems, summary_insert)[:-1]
  File "/home/frens-jan/Workspaces/tgho/experiments/tsdb/pyspark-cassandra/venv/lib/python2.7/site-packages/numpy/core/arrayprint.py", line 497, in _formatArray
    word = format_function(a[-i]) + separator
  File "/home/frens-jan/Workspaces/tgho/experiments/tsdb/pyspark-cassandra/venv/lib/python2.7/site-packages/numpy/core/arrayprint.py", line 741, in __call__
    casting=self.casting)
TypeError: Invalid datetime unit "generic" in metadata
```

Inspecting the `dtype` of the array shows that the type maybe wrong:

``` python
>>> unpickled.dtype
dtype('<M8')
```

The dissected pickle looks like:

``` python
>>> pickletools.dis(pickle.dumps(b))
    0: c    GLOBAL     'numpy.core.multiarray _reconstruct'
   36: p    PUT        0
   39: (    MARK
   40: c        GLOBAL     'numpy ndarray'
   55: p        PUT        1
   58: (        MARK
   59: I            INT        0
   62: t            TUPLE      (MARK at 58)
   63: p        PUT        2
   66: S        STRING     'b'
   71: p        PUT        3
   74: t        TUPLE      (MARK at 39)
   75: p    PUT        4
   78: R    REDUCE
   79: p    PUT        5
   82: (    MARK
   83: I        INT        1
   86: (        MARK
   87: I            INT        3
   90: t            TUPLE      (MARK at 86)
   91: p        PUT        6
   94: c        GLOBAL     'numpy dtype'
  107: p        PUT        7
  110: (        MARK
  111: S            STRING     'M8'
  117: p            PUT        8
  120: I            INT        0
  123: I            INT        1
  126: t            TUPLE      (MARK at 110)
  127: p        PUT        9
  130: R        REDUCE
  131: p        PUT        10
  135: (        MARK
  136: I            INT        4
  139: S            STRING     '>'
  144: p            PUT        11
  148: N            NONE
  149: N            NONE
  150: N            NONE
  151: I            INT        -1
  155: I            INT        -1
  159: I            INT        0
  162: (            MARK
  163: (                MARK
  164: d                    DICT       (MARK at 163)
  165: p                PUT        12
  169: (                MARK
  170: S                    STRING     'ms'
  176: p                    PUT        13
  180: I                    INT        1
  183: I                    INT        1
  186: I                    INT        1
  189: t                    TUPLE      (MARK at 169)
  190: p                PUT        14
  194: t                TUPLE      (MARK at 162)
  195: p            PUT        15
  199: t            TUPLE      (MARK at 135)
  200: p        PUT        16
  204: b        BUILD
  205: I        INT        False
  209: S        STRING     '\x00\x00\x01M\\.\x06%\x00\x00\x01M\\.Z\x82\x00\x00\x01M\\/d\x05'
  276: p        PUT        17
  280: t        TUPLE      (MARK at 82)
  281: p    PUT        18
  285: b    BUILD
  286: .    STOP
highest protocol among opcodes = 0
```

I'm no pickle expert, but I _do_ see `>` indicating the byte order  and `ms` indicating the milliseconds interpretation of the longs. Also the string seems to be exactly with the byte string with which the array was created via `np.frombuffer(...)`.

I'm running 64 bit Fedora 21. I'm using python 2.7.8 for this and numpy version 1.9.2 (git revision 762c6f15bf57506e21239a4dd68192e4da6014f7).

**Comment by frensjan** [comment]
When comparing to the pickle of the correct array (the one constructed from data strings) this is the diff:
```diff
37c37
<   139: S            STRING     '<'
---
>   139: S            STRING     '>'
63c63
<   209: S        STRING     '%\x06.\\M\x01\x00\x00\x82Z.\\M\x01\x00\x00\x05d/\\M\x01\x00\x00'
---
>   209: S        STRING     '\x00\x00\x01M\\.\x06%\x00\x00\x01M\\.Z\x82\x00\x00\x01M\\/d\x05'
```

On my machine the array is in little-endian order by default, in contrast to the data from Java which has everything in network / big-endian order.

**Comment by frensjan** [comment]
Things just work fine if I change the byte order and swap the bytes, e.g.:
```python
>>> b = np.frombuffer(bytearray(b'\x00\x00\x01M\\.\x06%\x00\x00\x01M\\.Z\x82\x00\x00\x01M\\/d\x05'), '>M8[ms]')
>>> b = b.byteswap().newbyteorder('<')
>>> unpickled = pickle.loads(pickle.dumps(b))
>>> unpickled
array(['2015-05-16T12:03:49.669+0200', '2015-05-16T12:04:11.266+0200',
       '2015-05-16T12:05:19.237+0200'], dtype='datetime64[ms]')
>>> unpickled.dtype
dtype('<M8[ms]')
```

But I don't think that the byte order should be prohibitive for pickling / unpickling to work.

**Comment by seberg** [comment]
Seems like it, thanks for the note.
