### ISSUE TITLE
numpy.maximum / numpy.minimum fail quietly on sparse matrices

### ISSUE THREAD

**Issue by mosco** [numpy/numpy#5894]
As I understand, the numpy.maximum and numpy.minimum functions do not support sparse arrays. However, they fail _quietly_, producing erroneous output when given a scipy.sparse.dok_matrix:

```
>>> import numpy
>>> from scipy.sparse import dok_matrix
>>> numpy.maximum(dok_matrix([[1,0]]), dok_matrix([[0,1]])).toarray()
75: array([[0, 1]])
```

When given a scipy.sparse.csr_matrix, these functions fail with an exception, but the error is not clear:

```
>>> import numpy
>>> from scipy.sparse import csr_matrix
>>> numpy.maximum(csr_matrix([[1,0]]), csr_matrix([[0,1]])).toarray()
Traceback (most recent call last):
  File "<pyshell#169>", line 1, in <module>
    numpy.maximum(csr_matrix([[1,0]]), csr_matrix([[0,1]])).toarray()
  File "/home/amitmo/virtualenv/local/lib/python2.7/site-packages/scipy/sparse/base.py", line 183, in __bool__
    raise ValueError("The truth value of an array with more than one "
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all().
>>> 
```

I think an exception should be raised if the data type is not supported.

**Comment by argriffing** [comment]
I'm not completely sure, but this is possibly fixed after https://github.com/scipy/scipy/pull/3296.  What scipy version are you using?

**Comment by mosco** [comment]
Version 0.15.1

**Comment by argriffing** [comment]
> Version 0.15.1

That's strange, it seems like version 0.15.1 should have it.
https://github.com/scipy/scipy/blob/maintenance/0.15.x/scipy/sparse/base.py#L227

Works for me with newer versions:
```python
>>> import numpy as np
>>> from scipy.sparse import dok_matrix
>>> a = dok_matrix([[1, 0]])
>>> b = dok_matrix([[0, 1]])
>>> import scipy
>>> scipy.__version__
'0.17.0.dev0+fb23da7'
>>> np.__version__
'1.10.0.dev0+9ceb5cd'
>>> np.maximum(a, b)
<1x2 sparse matrix of type '<type 'numpy.int64'>'
        with 2 stored elements in Compressed Sparse Row format>
>>> np.maximum(a, b).A
array([[1, 1]])
>>> np.minimum(a, b).A
array([[0, 0]])
>>> np.maximum(a.tocsr(), b.tocsr()).A
array([[1, 1]])
>>> np.minimum(a.tocsr(), b.tocsr()).A
array([[0, 0]])
>>> np.minimum(a.tocsr(), b.tocsr()).toarray()
array([[0, 0]])
```

**Comment by pv** [comment]
Numpy dev version is needed for ufunc overrides to work; the feature was
not included in 1.9 due to Numpy interaction with Python binops being
historically essentially broken (array_priority etc.), and questions
arose on how to best fix this at the same time as fixing ufunc behavior.

**Comment by seberg** [comment]
Since we have array ufunc now working, sparse minmimum/maximum should really be fine (it seems it was almost good in 2015), and we will not go through other odd things to make strange array likes work better probably.

**Comment by seberg** [comment]
Oh, hmmm, sorry, just tried, and it still has the same result. But it does seem like nowadays at least it would have to be considered a problem with sparse and not with scipy.

**Comment by pv** [comment]
@seberg: the array semantics enforced by array_ufunc for multiplication
iiuc are a problem with that.

**Comment by seberg** [comment]
Oh right, it cannot take that path at all, well, not sure it is a serious issue, but will just reopen it.

**Comment by bensdm** [comment]
Hi, any update on this?

**Comment by SimZhou** [comment]
It is 2020 now and still got this issue. 

scipy.__version__: 1.4.1
numpy.__version__: 1.18.1

**Comment by thirschbuechler** [comment]
the outputs seem to be the same now, still non-working however
**python** 3.8.10
**scipy** 1.8.0
**numpy** 1.22.3

```
/home/user/.local/lib/python3.8/site-packages/scipy/sparse/_compressed.py:311: SparseEfficiencyWarning: Comparing sparse matrices using >= and <= is inefficient, using <, >, or !=, instead.
  warn("Comparing sparse matrices using >= and <= is inefficient, "
Traceback (most recent call last):
  File "/home/user/test2.py", line 3, in <module>
    numpy.maximum(dok_matrix([[1,0]]), dok_matrix([[0,1]])).toarray()
  File "/home/user/.local/lib/python3.8/site-packages/scipy/sparse/_base.py", line 337, in __bool__
    raise ValueError("The truth value of an array with more than one "
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all().
```


```
/home/user/.local/lib/python3.8/site-packages/scipy/sparse/_compressed.py:311: SparseEfficiencyWarning: Comparing sparse matrices using >= and <= is inefficient, using <, >, or !=, instead.
  warn("Comparing sparse matrices using >= and <= is inefficient, "
Traceback (most recent call last):
  File "/home/user/test.py", line 3, in <module>
    numpy.maximum(csr_matrix([[1,0]]), csr_matrix([[0,1]])).toarray()
  File "/home/user/.local/lib/python3.8/site-packages/scipy/sparse/_base.py", line 337, in __bool__
    raise ValueError("The truth value of an array with more than one "
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all().



```
