### ISSUE TITLE
KeyError when constructing an array with a dict-like class instance.

### ISSUE THREAD

**Issue by santegoeds** [numpy/numpy#6021]
Numpy version 1.9.2, Python version 2.7.3

See test-case below.  I would have expected the same behaviour as when using a `dict`.  Removing the `__iter__` method prevents the error.

``` Python
import numpy as np

class DictLike(object):

    def __init__(self, *a, **kw):
        self._container = dict(*a, **kw)

    def __iter__(self):
        return self._container.__iter__()

    def __getitem__(self, name):
        return self._container.__getitem__(name)

    def __len__(self):
        return self._container.__len__()


a = np.array([DictLike(a=1)])
```

```
$ python x.py
Traceback (most recent call last):
  File "x.py", line 18, in <module>
    a = np.array([DictLike(a=1)])
  File "x.py", line 12, in __getitem__
    return self._container.__getitem__(name)
KeyError: 0
```

**Comment by eric-wieser** [comment]
This is inherited from the builtin `PySequence_Check`:
```
int
PySequence_Check(PyObject *s)
{
    if (PyDict_Check(s))
        return 0;
    return s != NULL && s->ob_type->tp_as_sequence &&
        s->ob_type->tp_as_sequence->sq_item != NULL;
}
```

**Comment by seberg** [comment]
Works now via `list(DictLike(a=1))` which succeeds, but not "dictlike".  NumPy uses `PySequence_Check` at last now, so subclass dict, if you want it to behave like a dict (which is also not great what NumPy does).

So closing.
