### ISSUE TITLE
BUG: ix_ modifies input arrays

### ISSUE THREAD

**Issue by rgommers** [numpy/numpy#6062]
Regression that was introduced in gh-5805. Discovered when running Scipy tests against numpy master:

    ======================================================================
    ERROR: test_qhull.TestUtilities.test_more_barycentric_transforms
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
      File "/Users/rgommers/Code/bldscipy/scipy/spatial/tests/test_qhull.py", line 310, in test_more_barycentric_transforms
        grid = np.c_[list(map(np.ravel, np.broadcast_arrays(*np.ix_(*([x]*ndim)))))].T
      File "/Users/rgommers/Code/numpy/numpy/lib/index_tricks.py", line 77, in ix_
        raise ValueError("Cross index must be 1 dimensional")
    ValueError: Cross index must be 1 dimensional

A simple way to reproduce the issue:

    >>> x = np.linspace(0, 1, num=5)
    >>> np.ix_(*([x] * 4))
    Traceback (most recent call last):
      File "<ipython-input-6-b0c751ea5a84>", line 1, in <module>
    np.ix_(*([x] * 4))
      File "/Users/rgommers/Code/numpy/numpy/lib/index_tricks.py", line 77, in ix_
        raise ValueError("Cross index must be 1 dimensional")
    ValueError: Cross index must be 1 dimensional

    >>> x.shape
    (5, 1, 1, 1)

Solution is simply to make a copy when constructing output arrays.

**Comment by njsmith** [comment]
This looks like it could be a reasonable issue to give someone who shows up at the sprints today wanting to get a taste of numpy development...

**Comment by rgommers** [comment]
Indeed, good idea.
