### ISSUE TITLE
3 out of 5 numpy imports do not work

### ISSUE THREAD

**Issue by maynardGK** [numpy/numpy#6068]
I have Python installed in (at least) 5 places in my system.  All but two do not accept a numpy
installation.  
 # 1. windows (64-bit system) registered Python27/ - works

~~~~
D:\cmd>python -c "import numpy; print numpy.get_include()"
e:\Python27\lib\site-packages\numpy\core\include

D:\cmd>
~~~~

 # 2. CYGWIN64 python 2.7.10 / numpy 1.7 OR 1.9 - does not work

~~~~
$ python -c "import numpy; print numpy.get_include()"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/numpy/__init__.py", line 137, in <module>
    import add_newdocs
  File "/usr/lib/python2.7/site-packages/numpy/add_newdocs.py", line 9, in <module>
    from numpy.lib import add_newdoc
  File "/usr/lib/python2.7/site-packages/numpy/lib/__init__.py", line 13, in <module>
    from polynomial import *
  File "/usr/lib/python2.7/site-packages/numpy/lib/polynomial.py", line 17, in <module>
    from numpy.linalg import eigvals, lstsq, inv
  File "/usr/lib/python2.7/site-packages/numpy/linalg/__init__.py", line 48, in <module>
    from linalg import *
  File "/usr/lib/python2.7/site-packages/numpy/linalg/linalg.py", line 23, in <module>
    from numpy.linalg import lapack_lite
ImportError: No such file or directory
~~~~

 # 3. MSYS2  - does not work

~~~~
greg@Homerw7 MSYS ~
$ python -c "import numpy"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/numpy/__init__.py", line 170, in <module>
    from . import add_newdocs
  File "/usr/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/usr/lib/python2.7/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/usr/lib/python2.7/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/usr/lib/python2.7/site-packages/numpy/core/__init__.py", line 6, in <module>
    from . import multiarray
ImportError: No such file or directory
~~~~

.# 4. MSYS2/Mingw32 python 2.7.9 - does not work
.# 5. MSYS2/Mingw64 python 2.7.9 - works:

~~~~
greg@Homerw7 MINGW64 ~
$ python -c "import numpy; print numpy.get_include()"
C:/msys64/mingw64/lib/python2.7/site-packages/numpy/core/include
C:/msys64/mingw64/lib/python2.7/site-packages/numpy/core/__init__.py:6: Warning: Numpy built 
with MINGW-W64 on Windows 64 bits is experimental, and only available for
testing. You are advised not to use it for production.

CRASHES ARE TO BE EXPECTED - PLEASE REPORT THEM TO NUMPY DEVELOPERS
  from . import multiarray

greg@Homerw7 MINGW64 ~
$ python --version
Python 2.7.9
~~~~

**Comment by njsmith** [comment]
It sounds like your installations are broken and missing files. I'm not sure what to tell you beyond that. cygwin/msys2 are not things that we support ourselves, so there's not much we can do -- I'd suggest getting in touch with whoever provided these python builds and asking them for assistance. Good luck!
