### ISSUE TITLE
random.choice doesn't allow float128 probs

### ISSUE THREAD

**Issue by argriffing** [numpy/numpy#6132]
I think this is due to the `same_kind` casting in numpy 1.10, and I don't know whether this is considered a bug.
```python
>>> import numpy as np
>>> probs = np.array([0.4, 0.4, 0.2], dtype=np.float128)
>>> np.random.choice([1, 2, 3], p=probs)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mtrand.pyx", line 1087, in mtrand.RandomState.choice (numpy/random/mtrand/mtrand.c:11331)
TypeError: Cannot cast array data from dtype('float128') to dtype('float64') according to the rule 'safe'
```

**Comment by charris** [comment]
`"same_kind"` would work, it is `"safe"` that is failing. Since `double` is specified  `"same_kind"` should work. For that routine we could use `long double` as the type, which would be platform specific but would be platform specific. I think specifying `same_kind` would be an adequate solution.

**Comment by ron819** [comment]
Is this still an issue? Open since 2015 with no comments.

**Comment by mattip** [comment]
@ron819 it is relatively simple to run the code at the top of the issue to determine this is still not solved

**Comment by bashtage** [comment]
Consensus in #18835 is that implicit conversion of unsafe types to float64 is a bad idea, and so raising is the right course.

**Comment by bashtage** [comment]
Correctly implementing this within the current implementation of `choice` would first require `Generator.random` to support `longdouble` random values (or any other extended precision type that is supported). The current implementation only support float32 and float64.
