### ISSUE TITLE
assert_allclose no longer works with ndarray subclasses that use units

### ISSUE THREAD

**Issue by ngoldbaum** [numpy/numpy#6196]
This can be seen from the following test script:

```python
from numpy.testing import assert_allclose
from yt.units import g

three_grams = 3*g

assert_allclose(three_grams, 3*g, atol=1)
```

`g` in this context is an instance of `YTArray`, a subclass of `ndarray` that uses a sympy-powered unit system. Under NumPy 1.9.2, this runs without error. Under NumPy 1.10b1, I get the following traceback:

```
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    assert_allclose(three_grams, 3*g)
  File "/Users/goldbaum/Documents/numpy-test/numpy-test/lib/python2.7/site-packages/numpy/testing/utils.py", line 1347, in assert_allclose
    verbose=verbose, header=header)
  File "/Users/goldbaum/Documents/numpy-test/numpy-test/lib/python2.7/site-packages/numpy/testing/utils.py", line 716, in assert_array_compare
    raise ValueError(msg)
ValueError:
error during assertion:

Traceback (most recent call last):
  File "/Users/goldbaum/Documents/numpy-test/numpy-test/lib/python2.7/site-packages/numpy/testing/utils.py", line 689, in assert_array_compare
    val = safe_comparison(x, y)
  File "/Users/goldbaum/Documents/numpy-test/numpy-test/lib/python2.7/site-packages/numpy/testing/utils.py", line 636, in safe_comparison
    return comparison(*args, **kwargs)
  File "/Users/goldbaum/Documents/numpy-test/numpy-test/lib/python2.7/site-packages/numpy/testing/utils.py", line 1342, in compare
    equal_nan=equal_nan)
  File "/Users/goldbaum/Documents/numpy-test/numpy-test/lib/python2.7/site-packages/numpy/core/numeric.py", line 2349, in isclose
    return within_tol(x, y, atol, rtol)
  File "/Users/goldbaum/Documents/numpy-test/numpy-test/lib/python2.7/site-packages/numpy/core/numeric.py", line 2332, in within_tol
    result = less_equal(abs(x-y), atol + rtol * abs(y))
  File "/Users/goldbaum/Documents/yt-test/yt/units/yt_array.py", line 731, in __radd__
    lo = sanitize_units_add(self, left_object, "addition")
  File "/Users/goldbaum/Documents/yt-test/yt/units/yt_array.py", line 134, in sanitize_units_add
    raise YTUnitOperationError(op_string, inp.units, dimensionless)
YTUnitOperationError: The addition operator for YTArrays with units (g) and (1) is not well defined.


Not equal to tolerance rtol=1e-07, atol=0
 x: YTQuantity(3.0)
 y: YTQuantity(3.0)
```

FWIW, this isn't isolated to `YTArray`, I get the same traceback if I use `from astropy.units import g`. One small difference: in yt this fails with `atol=0` (the default) but astropy is ok with it due to a difference in the way we treat zero in our respective unit systems.  For yt it would be particularly annoying to update our test suite to adapt to this by making sure `atol` has units attached to it everywhere we use assert_allclose, particularly since it's sometimes used indirectly.

Looking at the NumPy source, it seems the `compare` function used in `assert_allclose` has changed since NumPy 1.9.2. Would it be possible to revert to the old implementation, or generalize the one used here so it doesn't break unit consistency (in this case, subtracting a scalar without units from a quantity passed in with units)?

**Comment by mhvk** [comment]
@ngoldbaum - I don't know how it is for `yt`, but for `astropy`, the old `assert_allclose` was actually a problem, in that, effectively, it simply ignored `ndarray` subclasses.  Hence, 
`assert_allclose(3.*u.g, 3.*u.kg)` would happily pass. Personally, I prefer the code failing for all quantities than giving such incorrect results. I do not see how to make it work correctly generally without one actually passing in `atol=1*g`.

Note that since this is useful functionality, we ended up defining our own `assert_quantity_allclose` for our test scripts. See https://github.com/astropy/astropy/blob/master/astropy/tests/helper.py#L599

**Comment by ngoldbaum** [comment]
@mhvk thanks for the link, that's useful. I will likely adapt that logic...

**Comment by ngoldbaum** [comment]
Closing this, see https://bitbucket.org/yt_analysis/yt/pull-requests/1696/add-assert_allclose_units-like/diff
