### ISSUE TITLE
Scipy 0.16.0 test failure with maintenance/1.10.x

### ISSUE THREAD

**Issue by cgohlke** [numpy/numpy#6270]
On Windows using numpy+mkl, I get a scipy test failure with numpy maintenance/1.10.x because `np.histogram` returns different results for numpy 1.9.2 and 1.10.x:

```
======================================================================
FAIL: test_weighting (test_stats.TestHistogram)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python34\lib\site-packages\scipy\stats\tests\test_stats.py", line 892, in test_weighting
    decimal=2)
  File "X:\Python34\lib\site-packages\numpy\testing\utils.py", line 886, in assert_array_almost_equal
    precision=decimal)
  File "X:\Python34\lib\site-packages\numpy\testing\utils.py", line 708, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Arrays are not almost equal to 2 decimals

(mismatch 40.0%)
 x: array([   4. ,    0. ,    4.5,   -0.9,    0. ,    0.3,  110.2,    0. ,
          0. ,   42. ])
 y: array([   4. ,    0. ,    4.5,   -0.9,    0.3,    0. ,    7. ,  103.2,
          0. ,   42. ])
```
Standalone code:
```
import numpy as np
a = np.array([0.2, 0.3, 0.4, 0.5, 0.5, 0.6, 0.7, 0.8, 0.9, 1.1, 1.2])
weights = np.array([1.00000000e+00,  3.00000000e+00, 4.50000000e+00,
                    1.00000000e-01, -1.00000000e+00, 0.00000000e+00,
                    3.00000000e-01,  7.00000000e+00, 1.03200000e+02,
                    2.00000000e+00,  4.00000000e+01])
hist, bin_edges = np.histogram(a, bins=10, range=(0.2, 1.2), weights=weights)
print(hist)
```
numpy 1.9.2:
```
[   4.     0.     4.5   -0.9    0.     0.3  110.2    0.     0.    42. ]
```
numpy 1.10.x:
```
[   4.     0.     4.5   -0.9    0.3    0.     7.   103.2    0.    42. ]
```

**Comment by charris** [comment]
This is a known problem and the consensus is that the test needs fixing. See #6120 and https://github.com/scipy/scipy/issues/5173.
