### ISSUE TITLE
Support for Decimal in numpy.percentile

### ISSUE THREAD

**Issue by reupen** [numpy/numpy#6339]
It would be great if `numpy.percentile` supported Decimal. Most numpy functions I've tried are fine with `numpy.array`s containing `Decimal`s, but not numpy.percentile.

```python
from decimal import Decimal
import numpy as np
In[81]: x = np.array([[Decimal(1), Decimal(2)], [Decimal(1), Decimal(2)]])
In[82]: x
Out[82]: 
array([[Decimal('1'), Decimal('2')],
       [Decimal('1'), Decimal('2')]], dtype=object)
In[84]: np.min(x, axis=1)
Out[84]: array([Decimal('1'), Decimal('1')], dtype=object)
In[85]: np.median(x, axis=1)
Out[85]: array([Decimal('1.5'), Decimal('1.5')], dtype=object)
In[87]: np.std(x, axis=1)
Out[87]: array([Decimal('0.5'), Decimal('0.5')], dtype=object)
In[88]: np.mean(x, axis=1)
Out[88]: array([Decimal('1.5'), Decimal('1.5')], dtype=object)
In[86]: np.percentile(x, [50], axis=1)  # or np.percentile(x, [Decimal(50)], axis=1)
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\IPython\core\interactiveshell.py", line 3035, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-86-734677e766a8>", line 1, in <module>
    np.percentile(x, [50], axis=1)
  File "C:\Python34\lib\site-packages\numpy\lib\function_base.py", line 3054, in percentile
    interpolation=interpolation)
  File "C:\Python34\lib\site-packages\numpy\lib\function_base.py", line 2803, in _ureduce
    r = func(a, **kwargs)
  File "C:\Python34\lib\site-packages\numpy\lib\function_base.py", line 3143, in _percentile
    x1 = take(ap, indices_below, axis=axis) * weights_below
TypeError: unsupported operand type(s) for *: 'decimal.Decimal' and 'float'
In[14]: y = np.array([[1, 2], [1, 2]])
In[17]: np.percentile(y, [50], axis=1)  # this is fine, as expected
Out[17]: array([[ 1.5,  1.5]])
```

I'm using Python 3.4.3 and numpy 1.9.3.

Thanks

**Comment by shoyer** [comment]
Percentile actually works with decimals as long as you change the `interpolation` parameter from `midpoint`:
```
In [14]: np.percentile(x, [50], axis=1, interpolation='lower')
Out[14]: array([[Decimal('1'), Decimal('1')]], dtype=object)
```

**Comment by charris** [comment]
Hmm, that suggests a floating number somewhere. If it can be replaced by division `*/2` that might fix it.

**Comment by shoyer** [comment]
Here's the offending line. Not quite sure how to fix it, though: https://github.com/numpy/numpy/blob/37ece45df248ec514b08bd8d2164a1b68eea6bc8/numpy/lib/function_base.py#L3525

**Comment by charris** [comment]
The problem is here
```
weights_above = indices - indices_below
```
Indices is floating, so the weights are also. This could be fixed for midpoint by adding above and below and dividing by 2. I'm trying to think of a more universal way to treat the weights...

**Comment by charris** [comment]
`linear` will have the same problem.

**Comment by charris** [comment]
I suppose one could convert the weights to approximat rationals ;)

**Comment by wKavey** [comment]
Has anyone discovered a fix for this? I am still having the same issue and `interpolated = 'lower'` doesnt really work in my situation.
