### ISSUE TITLE
Error in broadcasting stride_tricks array

### ISSUE THREAD

**Issue by matthew-brett** [numpy/numpy#6491]
We hit a new test failure when testing against numpy 1.10.1 : https://github.com/nipy/nibabel/pull/358

The test failure boils down to this:

```
import numpy as np

shape = (2,)
strides = [0]
tricky_scalar = np.lib.stride_tricks.as_strided(np.array(0), shape, strides)
other = np.zeros((1,))
first, second = np.broadcast_arrays(tricky_scalar, other)
```

On Linux (not OSX) I get the following error, for numpy 1.10.1:

```
Traceback (most recent call last):
  File "broadcast_bug.py", line 7, in <module>
    first, second = np.broadcast_arrays(tricky_scalar, other)
  File "/home/mb312/.virtualenvs/test/local/lib/python2.7/site-packages/numpy/lib/stride_tricks.py", line 200, in broadcast_arrays
    for array in args]
  File "/home/mb312/.virtualenvs/test/local/lib/python2.7/site-packages/numpy/lib/stride_tricks.py", line 70, in _broadcast_to
    result.flags.writeable = True
ValueError: cannot set WRITEABLE flag to True of this array
```

There is no error for the same code on numpy 1.9.3.

I think this is the same issue, arising in scipy: https://github.com/scipy/scipy/pull/5374#issuecomment-148775998

**Comment by shoyer** [comment]
Hmm. I wrote the offending line of code, so I can take a look at this.

**Comment by charris** [comment]
@shoyer Any progress?

**Comment by shoyer** [comment]
just put up a patch in #6556
