### ISSUE TITLE
Build numpy for Python3.5: get_mathlib_info raise RuntimeError("Broken toolchain: cannot link a simple C program")

### ISSUE THREAD

**Issue by suokunlong** [numpy/numpy#6617]
I installed python3.5 using the installer from python official website, then trying to install numpy, but get the following error (I have Visual Studio 2015 installed).

```
pip3.5 install numpy
Collecting numpy
  Using cached numpy-1.10.1.tar.gz
Installing collected packages: numpy
  Running setup.py install for numpy
    Complete output from command d:\local\python3.5\python.exe -c "import setuptools, tokenize;__file__='C:\\Users\\SUOKUN~1\\AppData\\Local\\Temp\\pip-build-yevxt05r\\numpy\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\SUOKUN~1\AppData\Local\Temp\pip-5_a5vpkk-record\install-record.txt --single-version-externally-managed --compile:
    blas_opt_info:
    blas_mkl_info:
      libraries mkl,vml,guide not found in ['d:\\local\\python3.5\\lib', 'C:\\', 'd:\\local\\python3.5\\libs']
      NOT AVAILABLE

    openblas_info:
      libraries openblas not found in ['d:\\local\\python3.5\\lib', 'C:\\', 'd:\\local\\python3.5\\libs']
      NOT AVAILABLE

    atlas_3_10_blas_threads_info:
    Setting PTATLAS=ATLAS
      libraries tatlas not found in ['d:\\local\\python3.5\\lib', 'C:\\', 'd:\\local\\python3.5\\libs']
      NOT AVAILABLE

    atlas_3_10_blas_info:
      libraries satlas not found in ['d:\\local\\python3.5\\lib', 'C:\\', 'd:\\local\\python3.5\\libs']
      NOT AVAILABLE

    atlas_blas_threads_info:
    Setting PTATLAS=ATLAS
      libraries ptf77blas,ptcblas,atlas not found in ['d:\\local\\python3.5\\lib', 'C:\\', 'd:\\local\\python3.5\\libs']
      NOT AVAILABLE

    atlas_blas_info:
      libraries f77blas,cblas,atlas not found in ['d:\\local\\python3.5\\lib', 'C:\\', 'd:\\local\\python3.5\\libs']
      NOT AVAILABLE

    blas_info:
      libraries blas not found in ['d:\\local\\python3.5\\lib', 'C:\\', 'd:\\local\\python3.5\\libs']
      NOT AVAILABLE

    blas_src_info:
      NOT AVAILABLE

      NOT AVAILABLE

    non-existing path in 'numpy\\distutils': 'site.cfg'
    F2PY Version 2
    lapack_opt_info:
    openblas_lapack_info:
      libraries openblas not found in ['d:\\local\\python3.5\\lib', 'C:\\', 'd:\\local\\python3.5\\libs']
      NOT AVAILABLE

    lapack_mkl_info:
    mkl_info:
      libraries mkl,vml,guide not found in ['d:\\local\\python3.5\\lib', 'C:\\', 'd:\\local\\python3.5\\libs']
      NOT AVAILABLE

      NOT AVAILABLE

    atlas_3_10_threads_info:
    Setting PTATLAS=ATLAS
      libraries tatlas,tatlas not found in d:\local\python3.5\lib
      libraries lapack_atlas not found in d:\local\python3.5\lib
      libraries tatlas,tatlas not found in C:\
      libraries lapack_atlas not found in C:\
      libraries tatlas,tatlas not found in d:\local\python3.5\libs
      libraries lapack_atlas not found in d:\local\python3.5\libs
    <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
      NOT AVAILABLE

    atlas_3_10_info:
      libraries satlas,satlas not found in d:\local\python3.5\lib
      libraries lapack_atlas not found in d:\local\python3.5\lib
      libraries satlas,satlas not found in C:\
      libraries lapack_atlas not found in C:\
      libraries satlas,satlas not found in d:\local\python3.5\libs
      libraries lapack_atlas not found in d:\local\python3.5\libs
    <class 'numpy.distutils.system_info.atlas_3_10_info'>
      NOT AVAILABLE

    atlas_threads_info:
    Setting PTATLAS=ATLAS
      libraries ptf77blas,ptcblas,atlas not found in d:\local\python3.5\lib
      libraries lapack_atlas not found in d:\local\python3.5\lib
      libraries ptf77blas,ptcblas,atlas not found in C:\
      libraries lapack_atlas not found in C:\
      libraries ptf77blas,ptcblas,atlas not found in d:\local\python3.5\libs
      libraries lapack_atlas not found in d:\local\python3.5\libs
    <class 'numpy.distutils.system_info.atlas_threads_info'>
      NOT AVAILABLE

    atlas_info:
      libraries f77blas,cblas,atlas not found in d:\local\python3.5\lib
      libraries lapack_atlas not found in d:\local\python3.5\lib
      libraries f77blas,cblas,atlas not found in C:\
      libraries lapack_atlas not found in C:\
      libraries f77blas,cblas,atlas not found in d:\local\python3.5\libs
      libraries lapack_atlas not found in d:\local\python3.5\libs
    <class 'numpy.distutils.system_info.atlas_info'>
      NOT AVAILABLE

    lapack_info:
      libraries lapack not found in ['d:\\local\\python3.5\\lib', 'C:\\', 'd:\\local\\python3.5\\libs']
      NOT AVAILABLE

    lapack_src_info:
      NOT AVAILABLE

      NOT AVAILABLE

    running install
    running build
    running config_cc
    unifing config_cc, config, build_clib, build_ext, build commands --compiler options
    running config_fc
    unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
    running build_src
    build_src
    building py_modules sources
    creating build
    creating build\src.win32-3.5
    creating build\src.win32-3.5\numpy
    creating build\src.win32-3.5\numpy\distutils
    building library "npymath" sources
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize GnuFCompiler
    Could not locate executable g77
    Could not locate executable f77
    customize IntelVisualFCompiler
    Could not locate executable ifort
    Could not locate executable ifl
    customize AbsoftFCompiler
    Could not locate executable f90
    customize CompaqVisualFCompiler
    Could not locate executable DF
    customize IntelItaniumVisualFCompiler
    Could not locate executable efl
    customize Gnu95FCompiler
    Could not locate executable gfortran
    Could not locate executable f95
    customize G95FCompiler
    Could not locate executable g95
    customize IntelEM64VisualFCompiler
    customize IntelEM64TFCompiler
    Could not locate executable efort
    Could not locate executable efc
    don't know how to compile Fortran code on platform 'nt'
    C:\Program Files\Microsoft Visual Studio 14.0\VC\BIN\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Inumpy\core\src\private -Inumpy\core\src -Inumpy\core -Inumpy\core\src\npymath -Inumpy\core\src\multiarray -Inumpy\core\src\umath -Inumpy\core\src\npysort -Id:\local\python3.5\include -Id:\local\python3.5\include -I"C:\Program Files\Microsoft Visual Studio 14.0\VC\INCLUDE" -I"C:\Program Files\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" -I"C:\Program Files\Windows Kits\NETFXSDK\4.6\include\um" /Tc_configtest.c /Fo_configtest.obj
    Found executable C:\Program Files\Microsoft Visual Studio 14.0\VC\BIN\cl.exe
    Running from numpy source directory.
    C:\Users\SUOKUN~1\AppData\Local\Temp\pip-build-yevxt05r\numpy\numpy\distutils\system_info.py:1651: UserWarning:
        Atlas (http://math-atlas.sourceforge.net/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [atlas]) or by setting
        the ATLAS environment variable.
      warnings.warn(AtlasNotFoundError.__doc__)
    C:\Users\SUOKUN~1\AppData\Local\Temp\pip-build-yevxt05r\numpy\numpy\distutils\system_info.py:1660: UserWarning:
        Blas (http://www.netlib.org/blas/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [blas]) or by setting
        the BLAS environment variable.
      warnings.warn(BlasNotFoundError.__doc__)
    C:\Users\SUOKUN~1\AppData\Local\Temp\pip-build-yevxt05r\numpy\numpy\distutils\system_info.py:1663: UserWarning:
        Blas (http://www.netlib.org/blas/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [blas_src]) or by setting
        the BLAS_SRC environment variable.
      warnings.warn(BlasSrcNotFoundError.__doc__)
    C:\Users\SUOKUN~1\AppData\Local\Temp\pip-build-yevxt05r\numpy\numpy\distutils\system_info.py:1552: UserWarning:
        Atlas (http://math-atlas.sourceforge.net/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [atlas]) or by setting
        the ATLAS environment variable.
      warnings.warn(AtlasNotFoundError.__doc__)
    C:\Users\SUOKUN~1\AppData\Local\Temp\pip-build-yevxt05r\numpy\numpy\distutils\system_info.py:1563: UserWarning:
        Lapack (http://www.netlib.org/lapack/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [lapack]) or by setting
        the LAPACK environment variable.
      warnings.warn(LapackNotFoundError.__doc__)
    C:\Users\SUOKUN~1\AppData\Local\Temp\pip-build-yevxt05r\numpy\numpy\distutils\system_info.py:1566: UserWarning:
        Lapack (http://www.netlib.org/lapack/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [lapack_src]) or by setting
        the LAPACK_SRC environment variable.
      warnings.warn(LapackSrcNotFoundError.__doc__)
    d:\local\python3.5\lib\distutils\dist.py:261: UserWarning: Unknown distribution option: 'define_macros'
      warnings.warn(msg)
    C:\Program Files\Microsoft Visual Studio 14.0\VC\BIN\link.exe /nologo /INCREMENTAL:NO /LTCG /MANIFEST:EMBED,ID=1 /LIBPATH:"C:\Program Files\Microsoft Visual Studio 14.0\VC\LIB" /LIBPATH:"C:\Program Files\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB" /LIBPATH:"C:\Program Files\Windows Kits\NETFXSDK\4.6\lib\um\x86" _configtest.obj /OUT:_configtest.exe
    Found executable C:\Program Files\Microsoft Visual Studio 14.0\VC\BIN\link.exe
    failure.
    removing: _configtest.c _configtest.obj
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\SUOKUN~1\AppData\Local\Temp\pip-build-yevxt05r\numpy\setup.py", line 264, in <module>
        setup_package()
      File "C:\Users\SUOKUN~1\AppData\Local\Temp\pip-build-yevxt05r\numpy\setup.py", line 256, in setup_package
        setup(**metadata)
      File "C:\Users\SUOKUN~1\AppData\Local\Temp\pip-build-yevxt05r\numpy\numpy\distutils\core.py", line 169, in setup
        return old_setup(**new_attr)
      File "d:\local\python3.5\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "d:\local\python3.5\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "d:\local\python3.5\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\SUOKUN~1\AppData\Local\Temp\pip-build-yevxt05r\numpy\numpy\distutils\command\install.py", line 62, in run
        r = self.setuptools_run()
      File "C:\Users\SUOKUN~1\AppData\Local\Temp\pip-build-yevxt05r\numpy\numpy\distutils\command\install.py", line 36, in setuptools_run
        return distutils_install.run(self)
      File "d:\local\python3.5\lib\distutils\command\install.py", line 539, in run
        self.run_command('build')
      File "d:\local\python3.5\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "d:\local\python3.5\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\SUOKUN~1\AppData\Local\Temp\pip-build-yevxt05r\numpy\numpy\distutils\command\build.py", line 47, in run
        old_build.run(self)
      File "d:\local\python3.5\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "d:\local\python3.5\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "d:\local\python3.5\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\SUOKUN~1\AppData\Local\Temp\pip-build-yevxt05r\numpy\numpy\distutils\command\build_src.py", line 153, in run
        self.build_sources()
      File "C:\Users\SUOKUN~1\AppData\Local\Temp\pip-build-yevxt05r\numpy\numpy\distutils\command\build_src.py", line 164, in build_sources
        self.build_library_sources(*libname_info)
      File "C:\Users\SUOKUN~1\AppData\Local\Temp\pip-build-yevxt05r\numpy\numpy\distutils\command\build_src.py", line 299, in build_library_sources
        sources = self.generate_sources(sources, (lib_name, build_info))
      File "C:\Users\SUOKUN~1\AppData\Local\Temp\pip-build-yevxt05r\numpy\numpy\distutils\command\build_src.py", line 386, in generate_sources
        source = func(extension, build_dir)
      File "numpy\core\setup.py", line 669, in get_mathlib_info
        raise RuntimeError("Broken toolchain: cannot link a simple C program")
    RuntimeError: Broken toolchain: cannot link a simple C program

    ----------------------------------------
Command "d:\local\python3.5\python.exe -c "import setuptools, tokenize;__file__='C:\\Users\\SUOKUN~1\\AppData\\Local\\Temp\\pip-build-yevxt05r\\numpy\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\SUOKUN~1\AppData\Local\Temp\pip-5_a5vpkk-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\SUOKUN~1\AppData\Local\Temp\pip-build-yevxt05r\numpy

```

**Comment by rgommers** [comment]
This us some kind of user path issue or was fixed in the meantime; there's no problem building numpy with MSVC 2015 anymore.
