### ISSUE TITLE
recfunctions.merge_arrays fails to merge some arrays with standard field names

### ISSUE THREAD

**Issue by andsok75** [numpy/numpy#6743]
The following 

```
import numpy
import numpy.lib.recfunctions
a=numpy.zeros(3,numpy.dtype([('x', 'f8'), ('y', 'f8')]))
b=numpy.zeros(3,numpy.dtype([('f0', 'f8')]))
numpy.lib.recfunctions.merge_arrays( (a,b ), usemask=False )
```

yields

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-69-015ef99f22fa> in <module>()
----> 1 numpy.lib.recfunctions.merge_arrays( (a,b ), usemask=False )

/usr/lib/python2.7/dist-packages/numpy/lib/recfunctions.pyc in merge_arrays(seqarrays, fill_value, flatten, usemask, asrecarray)
    411     maxlength = max(sizes)
    412     # Get the dtype of the output (flattening if needed)
--> 413     newdtype = zip_descr(seqarrays, flatten=flatten)
    414     # Initialize the sequences for data and mask
    415     seqdata = []

/usr/lib/python2.7/dist-packages/numpy/lib/recfunctions.pyc in zip_descr(seqarrays, flatten)
    186             else:
    187                 newdtype.extend(current.descr)
--> 188     return np.dtype(newdtype).descr
    189 
    190 

ValueError: two fields with the same name
```

The problem is that merge_arrays essentially flattens an array if it has only one field, which could lead to conflicts in some cases, e.g.
* two single-field arrays with identical field names
* second array has one field 'f0' while first array has more than one field
* first array has one field 'f1' while second array has more than one field

**Comment by mattip** [comment]
2019-08-28 can reproduce, although now the error message is
```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "<__array_function__ internals>", line 6, in merge_arrays
  File "/pypy_stuff/numpy/build/testenv/lib/python3.5/site-packages/numpy/lib/recfunctions.py", line 463, in merge_arrays
    newdtype = _zip_dtype(seqarrays, flatten=flatten)
  File "/pypy_stuff/numpy/build/testenv/lib/python3.5/site-packages/numpy/lib/recfunctions.py", line 223, in _zip_dtype
    return np.dtype(newdtype)
ValueError: field 'f0' occurs more than once
```
