### ISSUE TITLE
Broken tests on Python 3.6-dev (nightly): module 'inspect' has no attribute 'getargspec'

### ISSUE THREAD

**Issue by ogrisel** [numpy/numpy#6764]
While trying to run the continuous integration of numpy with `python: nightly` in travis I found the following test failures caused by the use of a introspection API deprecated since Python 3.4 if I am not mistaken:

```
======================================================================
ERROR: test suite for <module 'test_array_from_pyobj' from '/home/travis/build/ogrisel/numpy/venv-for-wheel/lib/python3.6/site-packages/numpy/f2py/tests/test_array_from_pyobj.py'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/ogrisel/numpy/venv-for-wheel/lib/python3.6/site-packages/nose/suite.py", line 210, in run
    self.setUp()
  File "/home/travis/build/ogrisel/numpy/venv-for-wheel/lib/python3.6/site-packages/nose/suite.py", line 293, in setUp
    self.setupContext(ancestor)
  File "/home/travis/build/ogrisel/numpy/venv-for-wheel/lib/python3.6/site-packages/nose/suite.py", line 316, in setupContext
    try_run(context, names)
  File "/home/travis/build/ogrisel/numpy/venv-for-wheel/lib/python3.6/site-packages/nose/util.py", line 453, in try_run
    inspect.getargspec(func)
AttributeError: module 'inspect' has no attribute 'getargspec'

======================================================================
ERROR: test suite for <module 'test__datasource' from '/home/travis/build/ogrisel/numpy/venv-for-wheel/lib/python3.6/site-packages/numpy/lib/tests/test__datasource.py'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/ogrisel/numpy/venv-for-wheel/lib/python3.6/site-packages/nose/suite.py", line 210, in run
    self.setUp()
  File "/home/travis/build/ogrisel/numpy/venv-for-wheel/lib/python3.6/site-packages/nose/suite.py", line 293, in setUp
    self.setupContext(ancestor)
  File "/home/travis/build/ogrisel/numpy/venv-for-wheel/lib/python3.6/site-packages/nose/suite.py", line 316, in setupContext
    try_run(context, names)
  File "/home/travis/build/ogrisel/numpy/venv-for-wheel/lib/python3.6/site-packages/nose/util.py", line 453, in try_run
    inspect.getargspec(func)
AttributeError: module 'inspect' has no attribute 'getargspec'

======================================================================
ERROR: test suite for <module 'test_format' from '/home/travis/build/ogrisel/numpy/venv-for-wheel/lib/python3.6/site-packages/numpy/lib/tests/test_format.py'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/ogrisel/numpy/venv-for-wheel/lib/python3.6/site-packages/nose/suite.py", line 210, in run
    self.setUp()
  File "/home/travis/build/ogrisel/numpy/venv-for-wheel/lib/python3.6/site-packages/nose/suite.py", line 293, in setUp
    self.setupContext(ancestor)
  File "/home/travis/build/ogrisel/numpy/venv-for-wheel/lib/python3.6/site-packages/nose/suite.py", line 316, in setupContext
    try_run(context, names)
  File "/home/travis/build/ogrisel/numpy/venv-for-wheel/lib/python3.6/site-packages/nose/util.py", line 453, in try_run
    inspect.getargspec(func)
AttributeError: module 'inspect' has no attribute 'getargspec'
----------------------------------------------------------------------
```

**Comment by njsmith** [comment]
I think this is a bug in nose, not numpy?

**Comment by charris** [comment]
Yep, numpy has its own version of `getargspec` in `numpy/compat/_inspect.py`.

**Comment by ogrisel** [comment]
Indeed i had not  properly read the traceback properly. Sorry for the noise.
