### ISSUE TITLE
Test failure for 1.104 on Centos 5

### ISSUE THREAD

**Issue by cournape** [numpy/numpy#6973]
I see one failure w/ the latest numpy:

```
======================================================================
FAIL: test_umath.TestComplexFunctions.test_branch_cuts(<ufunc 'arccosh'>, [-1, 0.5], [1j, 1j], 1, -1, True)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vagrant/src/buildsystem-git/build/master-env/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/vagrant/src/buildsystem-git/build/master-env/lib/python2.7/site-packages/numpy/core/tests/test_umath.py", line 1748, in _check_branch_cut
    assert_(np.all(np.absolute(y0.imag - yp.imag) < atol), (y0, yp))
  File "/home/vagrant/src/buildsystem-git/build/master-env/lib/python2.7/site-packages/numpy/testing/utils.py", line 53, in assert_
    raise AssertionError(smsg)
AssertionError: (array([  0.00000000e+00+3.14159265j,   1.11022302e-16-1.04719755j]), array([  4.71216091e-07+3.14159218j,   1.28119737e-13+1.04719755j]))
```

On Centos 5.8, gcc 4.4, python 2.7.6  (built w/ MKL, but I doubt that's related).

**Comment by charris** [comment]
See #6063. The problem isn't new, but the test is.
