### ISSUE TITLE
lambdify on sympy.Min does not work with NumPy(Copied from sympy issue)

### ISSUE THREAD

**Issue by Shekharrajak** [numpy/numpy#6984]
IPython console for SymPy 0.7.7.dev (Python 3.4.3-64-bit) (ground types: python)

These commands were executed:
```
>>> from __future__ import division
>>> from sympy import *
>>> x, y, z, t = symbols('x y z t')
>>> k, m, n = symbols('k m n', integer=True)
>>> f, g, h = symbols('f g h', cls=Function)
>>> init_printing()

Documentation can be found at http://docs.sympy.org/dev

In [1]: import numpy as np

In [2]: np.__version__
Out[2]: '1.10.1'

In [3]: m = Min(x, y, z)

In [4]: l = lambdify([x,y,z], m)

In [5]: l(1, 2, 3)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/home/bjorn/.local/lib/python3.4/site-packages/numpy/core/fromnumeric.py in amin(a, axis, out, keepdims)
   2341         try:
-> 2342             amin = a.min
   2343         except AttributeError:

AttributeError: 'int' object has no attribute 'min'

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
<ipython-input-5-c33036198c2b> in <module>()
----> 1 l(1, 2, 3)

/home/bjorn/.local/lib/python3.4/site-packages/numpy/__init__.py in <lambda>(_Dummy_18, _Dummy_19, _Dummy_20)

/home/bjorn/.local/lib/python3.4/site-packages/numpy/core/fromnumeric.py in amin(a, axis, out, keepdims)
   2343         except AttributeError:
   2344             return _methods._amin(a, axis=axis,
-> 2345                                   out=out, keepdims=keepdims)
   2346         # NOTE: Dropping the keepdims parameter
   2347         return amin(axis=axis, out=out)

/home/bjorn/.local/lib/python3.4/site-packages/numpy/core/_methods.py in _amin(a, axis, out, keepdims)
     27 
     28 def _amin(a, axis=None, out=None, keepdims=False):
---> 29     return umr_minimum(a, axis, None, out, keepdims)
     30 
     31 def _sum(a, axis=None, dtype=None, out=None, keepdims=False):

TypeError: output must be an array
```
whereas using SymPy module for lambdify does work:
```
In [6]: l = lambdify([x,y,z], m, modules=['sympy'])

In [7]: l(1, 2, 3)
Out[7]: 1
```
[Original issue](https://github.com/sympy/sympy/issues/10375)

**Comment by pv** [comment]
The lambdify function in sympy appears to assume `numpy.min` behaves similarly as `min()`.
This is not the case, and should be taken into account in `lambdify`.

**Comment by Shekharrajak** [comment]
Yeah @pv  , there is mapping also Min is sympy in [this line](https://github.com/sympy/sympy/blob/master/sympy/utilities/lambdify.py#L82) 
but still we get this error
```
_methods.py", line 29, in _amin
    return umr_minimum(a, axis, None, out, keepdims)
TypeError: output must be an array

```
I also try with `min` instead of `amin`,but same error.
Can you find any correction needed in lambdify.py in sympy in that translation?

**Comment by matthew-brett** [comment]
I think @pv is saying that `np.min` (also `np.amin`) has a different call signature to `Min`.  Specifically, `Min(a, b, c)` returns the min of `a, b, c` whereas the equivalent call to `np.min` would be `np.min([a, b, c])` (note the values over which to take the min are passed as the sequence in the first argument).  So you'd need to somehow tell `lambdify` to make this translation in the input arguments.

**Comment by Shekharrajak** [comment]
```
>>> m = np.min([3, 2, 1])
>>> m
1
>>> m = np.amin([3, 2, 1])
>>> m
1
>>> m = np.amin([x, y, z])
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/root/local/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 2349, in amin
    out=out, keepdims=keepdims)
  File "/root/local/lib/python2.7/site-packages/numpy/core/_methods.py", line 29, in _amin
    return umr_minimum(a, axis, None, out, keepdims)
  File "/root/sympy/sympy/core/relational.py", line 202, in __nonzero__
    raise TypeError("cannot determine truth value of Relational")
TypeError: cannot determine truth value of Relational
>>> m = np.min([x, y, z])
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/root/local/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 2349, in amin
    out=out, keepdims=keepdims)
  File "/root/local/lib/python2.7/site-packages/numpy/core/_methods.py", line 29, in _amin
    return umr_minimum(a, axis, None, out, keepdims)
  File "/root/sympy/sympy/core/relational.py", line 202, in __nonzero__
    raise TypeError("cannot determine truth value of Relational")
TypeError: cannot determine truth value of Relational
```
What we need to do if we want to use `m` as function for `lambdify` and `x,y,z` as argument ?

**Comment by matthew-brett** [comment]
I think this one's a Sympy question.   With just a quick look at the lambdify code, I don't think there's currently a way to write a custom wrapper round a - for example - numpy function, which is what you have to do here.   So, I think this will need a small rewrite to the lambdify code to allow that.  I suppose the wrapper would be something like:

```
def np_Min(*args):
    return np.min(args)
```

But the right place for that discussion is the Sympy list...

**Comment by matthew-brett** [comment]
Not sure what `x, y, z` are in your example, but again - I don't think numpy can be expected to handle specialized Sympy symbol comparisons, so I'd suggest Sympy list again.

**Comment by Shekharrajak** [comment]
`x,y,z ` are just symbols ,that can take any value.Thanks @matthew-brett for your reply.I will try to implement this.

**Comment by bernwo** [comment]
Any news on this?

**Comment by seberg** [comment]
The issue is closed here, you should probably open one at SymPy first if it still is a problem.
