### ISSUE TITLE
Test failures on AppVeyor

### ISSUE THREAD

**Issue by jakirkham** [numpy/numpy#6991]
Seems to be primarily Python 3.x. Architecture where failures appear is somewhat variable.

    ======================================================================
    FAIL: test_double (test_numeric.TestBoolCmp)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "C:\Py\lib\site-packages\numpy\core\tests\test_numeric.py", line 313, in test_double
        assert_array_equal(np.signbit(self.signd[i:]), self.ed[i:])
      File "C:\Py\lib\site-packages\numpy\testing\utils.py", line 807, in assert_array_equal
        verbose=verbose, header='Arrays are not equal')
      File "C:\Py\lib\site-packages\numpy\testing\utils.py", line 733, in assert_array_compare
        raise AssertionError(msg)
    AssertionError: 
    Arrays are not equal
     
    (mismatch 0.78125%)
     x: array([False, False, False, False,  True, False, False, False, False,
            True, False, False,  True,  True, False, False, False, False,
            True, False,  True, False,  True, False, False,  True,  True,...
     y: array([False, False, False, False,  True, False, False, False, False,
            True, False, False,  True,  True, False, False, False, False,
            True, False,  True, False,  True, False, False,  True,  True,...
     
    ======================================================================
    FAIL: test_generic (test_type_check.TestIsneginf)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "C:\Py\lib\site-packages\numpy\lib\tests\test_type_check.py", line 265, in test_generic
        assert_(vals[0] == 1)
      File "C:\Py\lib\site-packages\numpy\testing\utils.py", line 71, in assert_
        raise AssertionError(smsg)
    AssertionError
     
    ======================================================================
    FAIL: test_generic (test_type_check.TestIsposinf)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "C:\Py\lib\site-packages\numpy\lib\tests\test_type_check.py", line 255, in test_generic
        assert_(vals[0] == 0)
      File "C:\Py\lib\site-packages\numpy\testing\utils.py", line 71, in assert_
        raise AssertionError(smsg)
    AssertionError
     
    ======================================================================
    FAIL: test_generic (test_type_check.TestNanToNum)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "C:\Py\lib\site-packages\numpy\lib\tests\test_type_check.py", line 275, in test_generic
        assert_all(vals[0] < -1e10) and assert_all(np.isfinite(vals[0]))
      File "C:\Py\lib\site-packages\numpy\lib\tests\test_type_check.py", line 15, in assert_all
        assert_(np.all(x), x)
      File "C:\Py\lib\site-packages\numpy\testing\utils.py", line 71, in assert_
        raise AssertionError(smsg)
    AssertionError: False
     
    ----------------------------------------------------------------------

**Comment by jakirkham** [comment]
This started occurring 10 Jan. Am suspicious that this ( https://github.com/numpy/numpy/pull/6980 ) has something to do with it.

**Comment by jakirkham** [comment]
@juliantaylor, do you have any idea what is going on here?

**Comment by jakirkham** [comment]
See this PR ( https://github.com/numpy/numpy/pull/6993 ) that @charris put together, which demonstrates this.

**Comment by jakirkham** [comment]
Fixed by https://github.com/numpy/numpy/pull/6994
