### ISSUE TITLE
tests fail on arm(v7a) (glibc)

### ISSUE THREAD

**Issue by ZeroChaos-** [numpy/numpy#7188]
here is the log snippit of the failure, please let me know what else you need:

```
======================================================================
FAIL: test_numeric.TestRequire.test_require_each('A', 'c16', array([[ 0.,  0.],
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/var/tmp/portage/dev-python/numpy-1.10.4/work/numpy-1.10.4-python3_4/build/test/lib/numpy/core/tests/test_numeric.py", line 2135, in set_and_check_flag
    assert_(b.flags[flag])
  File "/var/tmp/portage/dev-python/numpy-1.10.4/work/numpy-1.10.4-python3_4/build/test/lib/numpy/testing/utils.py", line 53, in assert_
    raise AssertionError(smsg)
AssertionError

======================================================================
FAIL: test_numeric.TestRequire.test_require_each('ALIGNED', 'c16', array([[ 0.,  0.],
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/var/tmp/portage/dev-python/numpy-1.10.4/work/numpy-1.10.4-python3_4/build/test/lib/numpy/core/tests/test_numeric.py", line 2135, in set_and_check_flag
    assert_(b.flags[flag])
  File "/var/tmp/portage/dev-python/numpy-1.10.4/work/numpy-1.10.4-python3_4/build/test/lib/numpy/testing/utils.py", line 53, in assert_
    raise AssertionError(smsg)
AssertionError

======================================================================
FAIL: test_numeric.TestRequire.test_require_each('A', 'c16', array([[0, 0],
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/var/tmp/portage/dev-python/numpy-1.10.4/work/numpy-1.10.4-python3_4/build/test/lib/numpy/core/tests/test_numeric.py", line 2135, in set_and_check_flag
    assert_(b.flags[flag])
  File "/var/tmp/portage/dev-python/numpy-1.10.4/work/numpy-1.10.4-python3_4/build/test/lib/numpy/testing/utils.py", line 53, in assert_
    raise AssertionError(smsg)
AssertionError

======================================================================
FAIL: test_numeric.TestRequire.test_require_each('ALIGNED', 'c16', array([[0, 0],
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/var/tmp/portage/dev-python/numpy-1.10.4/work/numpy-1.10.4-python3_4/build/test/lib/numpy/core/tests/test_numeric.py", line 2135, in set_and_check_flag
    assert_(b.flags[flag])
  File "/var/tmp/portage/dev-python/numpy-1.10.4/work/numpy-1.10.4-python3_4/build/test/lib/numpy/testing/utils.py", line 53, in assert_
    raise AssertionError(smsg)
AssertionError

----------------------------------------------------------------------
Ran 6089 tests in 467.392s

FAILED (KNOWNFAIL=4, SKIP=4, failures=4)
Running unit tests for numpy
NumPy version 1.10.4
NumPy relaxed strides checking option: False
NumPy is installed in /var/tmp/portage/dev-python/numpy-1.10.4/work/numpy-1.10.4-python3_4/build/test/lib/numpy
Python version 3.4.3 (default, Jan  4 2016, 03:02:50) [GCC 4.7.4]
nose version 1.3.7
```

**Comment by klpanagi** [comment]
I investigate the same error while testing **numpy-1.12.0.dev** installation on jetson-tk1 (cortexA15-armv7).

```bash
NumPy version 1.12.0.dev0+4c415d2
NumPy relaxed strides checking option: True
NumPy is installed in /home/cyanms/.local/lib/python2.7/site-packages/numpy-1.12.0.dev0+4c415d2-py2.7-linux-armv7l.egg/numpy
Python version 2.7.6 (default, Jun 22 2015, 18:31:26) [GCC 4.8.2]
nose version 1.3.7
```

numpy was previously compiled against **OpenBLAS**

**Comment by mattip** [comment]
Closing, we now test arm on CI. If there is a case where a certain combination of compiler and hardware causes a failure please open a new issue with all the details
