### ISSUE TITLE
Numpy 1.11.0 release

### ISSUE THREAD

**Issue by charris** [numpy/numpy#7316]
Christoph Gohlke reports the following test errors for Numpy 1.11.0rc1 on Windows.

> all numpy+MKL builds succeed. Selftests are OK except for the following.

> On all 32-bit platforms:

> ======================================================================
ERROR: test_zeros_big (test_multiarray.TestCreation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python27\lib\site-packages\numpy\core\tests\test_multiarray.py", line 594, in test_zeros_big
    d = np.zeros((30 * 1024**2,), dtype=dt)
MemoryError

> On Python 2.6, 64-bit:
 >======================================================================
FAIL: test_double (test_numeric.TestBoolCmp)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python26-x64\lib\site-packages\numpy\core\tests\test_numeric.py", line 415, in test_double
    assert_array_equal(np.signbit(self.signd[i:]), self.ed[i:])
  File "X:\Python26-x64\lib\site-packages\numpy\testing\utils.py", line 807, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "X:\Python26-x64\lib\site-packages\numpy\testing\utils.py", line 733, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Arrays are not equal

Not sure where that is coming from

>(mismatch 12.5%)
 x: array([False, False, False, False,  True, False, False, False, False,
       False, False, False,  True,  True, False, False, False, False,
        True, False,  True, False,  True, False, False,  True,  True,...
 y: array([False, False, False, False,  True, False, False, False, False,
        True, False, False,  True,  True, False, False, False, False,
        True, False,  True, False,  True, False, False,  True,  True,...

>======================================================================
FAIL: test_float (test_numeric.TestBoolCmp)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python26-x64\lib\site-packages\numpy\core\tests\test_numeric.py", line 389, in test_float
    assert_array_equal(np.signbit(self.signf[i:]), self.ef[i:])
  File "X:\Python26-x64\lib\site-packages\numpy\testing\utils.py", line 807, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "X:\Python26-x64\lib\site-packages\numpy\testing\utils.py", line 733, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Arrays are not equal

>(mismatch 4.296875%)
 x: array([False, False, False, False, False, False, False, False,  True,
       False, False, False, False, False, False, False, False,  True,
       False, False, False, False, False, False,  True,  True, False,...
 y: array([False, False, False, False, False, False, False, False,  True,
       False, False, False, False, False, False, False, False,  True,
       False, False, False, False, False, False,  True,  True, False,...

@juliantaylor This looks like yours. I'm not clear on why this only shows up for 2.6, maybe the windows compiler version?

**Comment by charris** [comment]
@juliantaylor I think the fix for the 2.6 failures is to revert the vectorization for Numpy 1.11. Python 2.6 goes away for 1.12.

**Comment by charris** [comment]
These have been addressed by #7337, #7331, and #7324.
