### ISSUE TITLE
Can't save .npy file when array's field contains Chinese

### ISSUE THREAD

**Issue by Macer3** [numpy/numpy#7391]
It seem's numpy can't save .npy file when array's fields contains Chinese

``` python
import numpy as np
f=np.array([(1,3,3),
               (1, 2, [1,2]), 
               (1, 3, {1:2, 3:3, 4:34}), 
               (1, 2, 'ss')], 
              dtype=([('int', int), ('整形', int), ('对象', np.object_)]))
f['整形']    # It work's well with field contains Chinese
#->  array([  3,   2, 324,   2]) 
np.save('f.npy',f)  # But can't save it
```

I got following An error:

```
Traceback (most recent call last):
  File "<ipython-input-5-d9dd063afc64>", line 1, in <module>
    np.save('f.npy',f)  # But can't save it
  File ".../numpy/lib/npyio.py", line 491, in save
    pickle_kwargs=pickle_kwargs)
  File ".../numpy/lib/format.py", line 555, in write_array
    version)
  File ".../numpy/lib/format.py", line 314, in _write_array_header
    header = asbytes(_filter_header(header))
  File ".../numpy/compat/py3k.py", line 31, in asbytes
    return str(s).encode('latin1')
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 29-30: ordinal not in range(256)
```

Then I try

``` python
f.dtype.names=('a','b','c')
np.save('f.npy',f)
```

Everything turns OK

Numpy Version = '1.10.4'
Python 3.4.4
win7

**Comment by mattip** [comment]
Still relevant on 1.16.3, the `latin-1` encoding needs to be relaxed

**Comment by eric-wieser** [comment]
I think to do that we need to create a V3 npy format that uses unicode encoding
