### ISSUE TITLE
polyfit should return nan values on nan input values

### ISSUE THREAD

**Issue by mrclary** [numpy/numpy#7644]
With numpy version <= 1.9.2 polyfit behaved correctly, as follows:

    In [1]: np.polyfit([1, 10], [np.nan,  np.nan], 1)
    Out[1]: array([ nan,  nan])

But for version >=1.9.3, polyfit raises the following error:

    In [1]: np.polyfit([1, 10], [np.nan, np.nan], 1)
    ---------------------------------------------------------------------------
    ValueError                                Traceback (most recent call last)
    <ipython-input-3-bf0d5d071f08> in <module>()
    ----> 1 np.polyfit([1, 10], [np.nan, np.nan], 1)
    
    /Users/rclary/anaconda/lib/python2.7/site-packages/numpy/lib/polynomial.pyc in polyfit(x, y, deg, rcond, full, w, cov)
        580     scale = NX.sqrt((lhs*lhs).sum(axis=0))
        581     lhs /= scale
    --> 582     c, resids, rank, s = lstsq(lhs, rhs, rcond)
        583     c = (c.T/scale).T  # broadcast scale coefficients
        584 
    
    /Users/rclary/anaconda/lib/python2.7/site-packages/numpy/linalg/linalg.pyc in lstsq(a, b, rcond)
       1865         work = zeros((lwork,), t)
       1866         results = lapack_routine(m, n, n_rhs, a, m, bstar, ldb, s, rcond,
    -> 1867                                  0, work, lwork, iwork, 0)
       1868     if results['info'] > 0:
       1869         raise LinAlgError('SVD did not converge in Linear Least Squares')
    
    ValueError: On entry to DGELSD parameter number 6 had an illegal value

**Comment by simongibbons** [comment]
Strange, when running that snippet on numpy 1.11.0 I get the array of nan's out rather than the ValueError.

I guess there is a possibility that this could be more which version of LAPACK you're using dependent than anything else.

**Comment by mrclary** [comment]
@simongibbons I think you are correct. After reading your comment I performed the same test on a MacPorts install of numpy 1.10.4 (compiled on my local computer) with positive results. The Anaconda installs of numpy >=1.9.3 (compiled by Anaconda, Intel MKL library, I believe) produce the error. I will file a bug report with Anaconda.

**Comment by ajoros** [comment]
Has anyone had any luck with this error? I am using Numpy 1.11.0 as still receive: 

```
Traceback (most recent call last):
  File "ModelEvaluation_modular.py", line 771, in <module>
    statdict, labelMOS = model_data_call(domainsarr, Initializedarr, rootmodel,StationID,flag)
  File "ModelEvaluation_modular.py", line 375, in model_data_call
    fit = np.polyfit(varob, varmo, 1)
  File "/share/apps/gnu/Miniconda-3.7.0/lib/python2.7/site-packages/numpy/lib/polynomial.py", line 589, in polyfit
    c, resids, rank, s = lstsq(lhs, rhs, rcond)
  File "/share/apps/gnu/Miniconda-3.7.0/lib/python2.7/site-packages/numpy/linalg/linalg.py", line 1919, in lstsq
    0, work, lwork, iwork, 0)
ValueError: On entry to DGELSD parameter number 6 had an illegal value
```

**Comment by mrclary** [comment]
@ajoros I'm not aware of any progress on correcting this issue. I've filed a bug with Anaconda [here](https://github.com/ContinuumIO/anaconda-issues/issues/804). However, until then, I've setup another conda environment that does not use the Intel math kernel library. The details are [here](https://docs.continuum.io/mkl-optimizations/) under "Uninstalling MKL".

**Comment by ajoros** [comment]
This solved the issue:
http://stackoverflow.com/questions/13675912/python-programming-numpy-polyfit-saying-nan

**Comment by doc78** [comment]
I struggled with the same behavior even without having NaN values! I tried many solution found on internet but nothing worked! Finally what worked for me was just to NOT use plt.show() when using polyfit! Strange thing, but in my case I was using matplotlib to plot a graph before using polyfit. Avoiding to call matplotlib solved the problem. Maybe a bug in numpy? My numpy version is 1.19.2.

Did anybody try other solutions?
