### ISSUE TITLE
AttributeError: module 'numpy.core.multiarray' has no attribute 'MAY_SHARE_BOUNDS'

### ISSUE THREAD

**Issue by netlab-bilgin** [numpy/numpy#7725]
Getting the following error with Numpy version 1.11.0 and Python version Python 3.5.1 :: Anaconda 4.0.0 (32-bit) with 'import pandas as pd' and 'import numpy': 

`AttributeError: module 'numpy.core.multiarray' has no attribute 'MAY_SHARE_BOUNDS'`

Had to downgrade numpy version 1.10.4; now numpy works fine. 

The traceback is from PyCharm, but the error is also present in the python shell as well:

```

Traceback (most recent call last):
  File "D:\Apps\Anaconda2\lib\site-packages\IPython\core\interactiveshell.py", line 2885, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-4bc307327564>", line 1, in <module>
    import pandas as pd
  File "C:\Program Files\JetBrains\PyCharm 2016.1.4\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\Apps\Anaconda2\lib\site-packages\pandas\__init__.py", line 13, in <module>
    __import__(dependency)
  File "C:\Program Files\JetBrains\PyCharm 2016.1.4\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\Apps\Anaconda2\lib\site-packages\numpy\__init__.py", line 180, in <module>
    from . import add_newdocs
  File "C:\Program Files\JetBrains\PyCharm 2016.1.4\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Program Files\JetBrains\PyCharm 2016.1.4\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\Apps\Anaconda2\lib\site-packages\numpy\add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "C:\Program Files\JetBrains\PyCharm 2016.1.4\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\Apps\Anaconda2\lib\site-packages\numpy\lib\__init__.py", line 8, in <module>
    from .type_check import *
  File "C:\Program Files\JetBrains\PyCharm 2016.1.4\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\Apps\Anaconda2\lib\site-packages\numpy\lib\type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "C:\Program Files\JetBrains\PyCharm 2016.1.4\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Program Files\JetBrains\PyCharm 2016.1.4\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\Apps\Anaconda2\lib\site-packages\numpy\core\__init__.py", line 25, in <module>
    from . import numeric
  File "C:\Program Files\JetBrains\PyCharm 2016.1.4\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Program Files\JetBrains\PyCharm 2016.1.4\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\Apps\Anaconda2\lib\site-packages\numpy\core\numeric.py", line 73, in <module>
    MAY_SHARE_BOUNDS = multiarray.MAY_SHARE_BOUNDS
AttributeError: module 'numpy.core.multiarray' has no attribute 'MAY_SHARE_BOUNDS'

```

**Comment by charris** [comment]
I can't reproduce this with python3.5 on 64 bit linux. I suspect there is something wrong with the installation/anaconda or something really odd about windows.

**Comment by rgommers** [comment]
Anaconda 4.0.0 has been out for a while, so it's a bit hard to believe that ``import numpy`` would fail. Either way, this doesn't look like a Numpy bug - the Anaconda issue tracker is here https://github.com/Anaconda-Platform/support/issues

**Comment by rgommers** [comment]
Closing because not a Numpy issue
