### ISSUE TITLE
Unable to build numpy on Ubuntu 14.04 with icc compiler 

### ISSUE THREAD

**Issue by winash12** [numpy/numpy#7758]
I followed these instructions - http://bryanwweber.com/writing/personal/2014/01/11/installing-numpy-scipy-on-ubuntu-12.04.3-from-scratch-source-with-intel-compilers/

and I still get this error - 

Traceback (most recent call last):
  File "/usr/local/bin/cython", line 9, in <module>
    load_entry_point('Cython==0.24', 'console_scripts', 'cython')()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python3.4/dist-packages/Cython/Compiler/Main.py", line 28, in <module>
    from .Scanning import PyrexScanner, FileSourceDescriptor
ImportError: /usr/local/lib/python3.4/dist-packages/Cython/Compiler/Scanning.cpython-34m.so: undefined symbol: __intel_sse2_strchr
Processing numpy/random/mtrand/mtrand.pyx
Traceback (most recent call last):
  File "/home/aswin/libPython/numpy/tools/cythonize.py", line 199, in <module>
    main()
  File "/home/aswin/libPython/numpy/tools/cythonize.py", line 195, in main
    find_process_files(root_dir)
  File "/home/aswin/libPython/numpy/tools/cythonize.py", line 187, in find_process_files
    process(cur_dir, fromfile, tofile, function, hash_db)
  File "/home/aswin/libPython/numpy/tools/cythonize.py", line 161, in process
    processor_function(fromfile, tofile)
  File "/home/aswin/libPython/numpy/tools/cythonize.py", line 72, in process_pyx
    raise Exception('Cython failed')
Exception: Cython failed
Running from numpy source directory.
Cythonizing sources
Traceback (most recent call last):
  File "setup.py", line 390, in <module>
    setup_package()
  File "setup.py", line 373, in setup_package
    generate_cython()
  File "setup.py", line 211, in generate_cython
    raise RuntimeError("Running cythonize failed!")
RuntimeError: Running cythonize failed!

When I run cython -version I get this. So I need to rebuild cython obviously for intel compiler. Any suggestions ?

Traceback (most recent call last):
  File "/usr/local/bin/cython", line 9, in <module>
    load_entry_point('Cython==0.24', 'console_scripts', 'cython')()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python3.4/dist-packages/Cython/Compiler/Main.py", line 28, in <module>
    from .Scanning import PyrexScanner, FileSourceDescriptor
ImportError: /usr/local/lib/python3.4/dist-packages/Cython/Compiler/Scanning.cpython-34m.so: undefined symbol: __intel_sse2_strchr

**Comment by rgommers** [comment]
A quick search on ``undefined symbol: __intel_sse2_strchr`` shows that this happens for other libraries besides numpy, and is OpenMP related. I'm not sure about the rest of the accuracy of the linked blog post, but removing ``-openmp`` from the ``intelem`` flags may resolve your issue.

**Comment by winash12** [comment]
Ralf - thanks for your response. You mean remove -openmp from intelcompiler.py correct ?

**Comment by rgommers** [comment]
correct

**Comment by winash12** [comment]
I removed that and I still get the same error. My cython is broken 

When I run /usr/local/bin/cython -version I get this error - Should I open an issue under cython or can we continue the discussion here ? 
Traceback (most recent call last):
  File "/usr/local/bin/cython", line 9, in <module>
    load_entry_point('Cython==0.24', 'console_scripts', 'cython')()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python3.4/dist-packages/Cython/Compiler/Main.py", line 28, in <module>
    from .Scanning import PyrexScanner, FileSourceDescriptor
ImportError: /usr/local/lib/python3.4/dist-packages/Cython/Compiler/Scanning.cpython-34m.so: undefined symbol: __intel_sse2_strchr

**Comment by rgommers** [comment]
> When I run /usr/local/bin/cython -version I get this error - Should I open an issue under cython or can we continue the discussion here? 

I don't have any experience with building Cython itself with ``icc``, so best to move this over to the Cython list or issue tracker.
