### ISSUE TITLE
test about numpy is failed."ImportError: cannot import name fib2" etc.

### ISSUE THREAD

**Issue by yechaochen** [numpy/numpy#7775]
In my machine, I have installed anaconda(64-bit) and installed following packages with apt-get:
apt-get install gfortran
apt-get install libopenblas-dev
apt-get install liblapack-dev
apt-get install libatlas-base-dev
apt-get install python-numpy
apt-get install python-scipy
apt-get install python-sklearn

I have removed the python-numpy and python-scipy. And I updated numpy version to the 1.11.0, the lastest version.
I run the command `python -c "import numpy;numpy.test()"`. But the test is failed and the output is:

> ERROR: Failure: ImportError (cannot import name fib2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/deeper/anaconda/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/deeper/anaconda/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/deeper/anaconda/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/deeper/anaconda/lib/python2.7/site-packages/numpy/distutils/tests/f2py_ext/tests/test_fib2.py", line 4, in <module>
    from f2py_ext import fib2
ImportError: cannot import name fib2

======================================================================
ERROR: Failure: ImportError (cannot import name foo)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/deeper/anaconda/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/deeper/anaconda/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/deeper/anaconda/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/deeper/anaconda/lib/python2.7/site-packages/numpy/distutils/tests/f2py_f90_ext/tests/test_foo.py", line 4, in <module>
    from f2py_f90_ext import foo
ImportError: cannot import name foo

======================================================================
ERROR: Failure: ImportError (cannot import name fib3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/deeper/anaconda/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/deeper/anaconda/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/deeper/anaconda/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/deeper/anaconda/lib/python2.7/site-packages/numpy/distutils/tests/gen_ext/tests/test_fib3.py", line 3, in <module>
    from gen_ext import fib3
ImportError: cannot import name fib3

======================================================================
ERROR: Failure: ImportError (No module named primes)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/deeper/anaconda/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/deeper/anaconda/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/deeper/anaconda/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/deeper/anaconda/lib/python2.7/site-packages/numpy/distutils/tests/pyrex_ext/tests/test_primes.py", line 4, in <module>
    from pyrex_ext.primes import primes
ImportError: No module named primes

======================================================================
ERROR: Failure: ImportError (cannot import name example)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/deeper/anaconda/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/deeper/anaconda/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/deeper/anaconda/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/deeper/anaconda/lib/python2.7/site-packages/numpy/distutils/tests/swig_ext/tests/test_example.py", line 4, in <module>
    from swig_ext import example
ImportError: cannot import name example

======================================================================
ERROR: Failure: ImportError (cannot import name example2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/deeper/anaconda/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/deeper/anaconda/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/deeper/anaconda/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/deeper/anaconda/lib/python2.7/site-packages/numpy/distutils/tests/swig_ext/tests/test_example2.py", line 4, in <module>
    from swig_ext import example2
ImportError: cannot import name example2

======================================================================
ERROR: test_rfft (test_fft.TestFFT1D)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/deeper/anaconda/lib/python2.7/site-packages/numpy/fft/tests/test_fft.py", line 72, in test_rfft
    x = np.fft.rfft([0, 1+5j, 0+7j, -3j])
  File "/home/deeper/anaconda/lib/python2.7/site-packages/numpy/fft/fftpack.py", line 365, in rfft
    a = array(a, copy=True, dtype=float)
TypeError: can't convert complex to float

----------------------------------------------------------------------
Ran 7434 tests in 137.686s

FAILED (KNOWNFAIL=6, SKIP=11, errors=7)

Can anyone tell me how to fix it!

**Comment by rgommers** [comment]
Those test files are left over from an older numpy install. In numpy 1.11.0 those files don't exist anymore under ``numpy/distutils/tests/``, and same for ``test_fft.py``. So just delete them manually and you'll be good to go.

**Comment by yechaochen** [comment]
@rgommers Can you tell me what and where I should delete manually.I'm a green hand in ubuntu and the machine is belong to my teacher.

**Comment by yechaochen** [comment]
@rgommers And I try the numpy.test in vmware.I have installed anaconda and run apt-get to installed the following packages:gfortran,libopenblas-dev,liblapack-dev,libatlas-base-dev. 
I have finded the version of numpy is 1.10.1 and I run the command `python -c "import numpy;numpy.test()"`. But there is also an error:"TypeError: can't convert complex to float" 
I have no way to solve it.

**Comment by seberg** [comment]
Maybe check what `import numpy; print(numpy.__file__)` gives you and check that folder. There is something messed up with your install and/or an old zombie install which has nothing to do with numpy as such.

**Comment by seberg** [comment]
It would be nice if you can direct further questions to the mailing list or such, since this is not a numpy issue.

**Comment by rgommers** [comment]
@yechaochen the tracebacks for the failing tests show in which files the tests are defined. So for the first one: ``/home/deeper/anaconda/lib/python2.7/site-packages/numpy/distutils/tests/f2py_ext/tests/test_fib2.py``. For the last one ``/home/deeper/anaconda/lib/python2.7/site-packages/numpy/fft/tests/test_fft.py``.

If that sounds too fiddly, you can also just delete all of ``/home/deeper/anaconda/lib/python2.7/site-packages/numpy`` and reinstall numpy.

**Comment by yechaochen** [comment]
@seberg The output of `import numpy; print(numpy.__file__)` is `/home/deeper/anaconda/lib/python2.7/site-packages/numpy/__init__.pyc`.
