### ISSUE TITLE
building numpy on OSX python 3.5 with incorrect module names

### ISSUE THREAD

**Issue by yiakwy** [numpy/numpy#7802]
I detected that when people try to build numpy on python 3.5, incorrect module names will prevent them to import numpy:

```python
multiarray_tests.cpython-35m-darwin.so
multiarray.cpython-35m-darwin.so
```
while it should be 
```python
multiarray_tests.so
multiarray.so
```

People will not be able to find the module with incorrect names.

I am on OSX, and use python3.5, 3.4, 2.7, 2.6.

**Comment by matthew-brett** [comment]
I believe those module names are correct for Python 3.5, but your module names are correct for Python 2.x.   Can you give a specific example of the import errors you are getting?

**Comment by yiakwy** [comment]
Yes. Import error is "cannot import name 'multiarray' " however once I removed "cpython-35m-darwin" another error occured "cannot import name 'umath' "
while umath module name is also of "cpython-35m-darwin".

**Comment by matthew-brett** [comment]
Here is me importing numpy in Python 3.5:

```
>>> import numpy as np
>>> np.core.multiarray
<module 'numpy.core.multiarray' from '/Users/mb312/.virtualenvs/test3/lib/python3.5/site-packages/numpy/core/multiarray.cpython-35m-darwin.so'>
```

I wonder whether you are somehow trying to import numpy modules for Python 3.5 from Python 2.7.

**Comment by yiakwy** [comment]
```python
Python 3.5.0a1 (v3.5.0a1:5d4b6a57d5fd, Feb  7 2015, 18:38:46) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/numpy/__init__.py", line 180, in <module>
    from . import add_newdocs
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/numpy/core/__init__.py", line 14, in <module>
    from . import multiarray
ImportError: cannot import name 'multiarray'
```

**Comment by matthew-brett** [comment]
I can't explain the error.   I notice you have an old alpha version of Python 3.5 - have you tried upgrading to the latest Python.org 3.5?

**Comment by yiakwy** [comment]
I see, I will try it later. Thx for helping

**Comment by rgommers** [comment]
Those are the correct names, so closing. @yiakwy feel free to continue the discussion here if you need more help.

**Comment by yiakwy** [comment]
I will upgraded to py 3.5 later, currently I switch to 2.7

2016-07-06 3:48 GMT+08:00 Ralf Gommers <notifications@github.com>:
