### ISSUE TITLE
numpy.set_printoptions accepts a dict as argument, then silently fails

### ISSUE THREAD

**Issue by JJL-ITU** [numpy/numpy#7852]
I just mentioned this issue on the Numpy mailing list. So far, there is agreement that what I am reporting here is unwanted behavior, a bug and not a feature.

The following minimal code has been tried on Python 3.4 and 3.5, with Numpy 1.8 and Numpy 1.11, respectively.  I want to temporarily change the way that a Numpy array is printed, then change it back to the defaults.

import numpy as np

`a = np.random.random((4,3))
print(a, "\n")
opt = np.get_printoptions()
np.set_printoptions(precision = 3, suppress = True)
print(a, "\n")
np.set_printoptions(opt)
print(a, "\n\nDone.\n")`

Here is the traceback:

`Traceback (most recent call last):
  File "set_printoptions test.py", line 11, in <module>
    print(a, "\n\nDone.\n")
  File "/usr/lib/python3/dist-packages/numpy/core/numeric.py", line 1615, in array_str
    return array2string(a, max_line_width, precision, suppress_small, ' ', "", str)
  File "/usr/lib/python3/dist-packages/numpy/core/arrayprint.py", line 454, in array2string
    separator, prefix, formatter=formatter)
  File "/usr/lib/python3/dist-packages/numpy/core/arrayprint.py", line 328, in _array2string
    _summaryEdgeItems, summary_insert)[:-1]
  File "/usr/lib/python3/dist-packages/numpy/core/arrayprint.py", line 523, in _formatArray
    summary_insert)
  File "/usr/lib/python3/dist-packages/numpy/core/arrayprint.py", line 497, in _formatArray
    word = format_function(a[-i]) + separator
  File "/usr/lib/python3/dist-packages/numpy/core/arrayprint.py", line 616, in __call__
    s = self.format % x
AttributeError: 'FloatFormat' object has no attribute 'format'`

My bug is on the second to last line, which should read:

`np.set_printoptions(**opt)`

This would unpack the dictionary, opt, which was retrieved earlier in the program with the call to get_printoptions().

However: no one has identified a legitimate reason that set_printoptions() would ever make use of a packed dictionary as a single argument. I propose that a TypeError be raised in this case.  Currently, the Numpy formatter is silently destroyed by supplying a bad argument to set_printoptions().  You don't discover this fact until the next time you attempt to print an array, when an AttributeError is raised.

**Comment by theultimatecrouton** [comment]
I get the same result, and am happy to implement this (raising a TypeError)

**Comment by JJL-ITU** [comment]
Thanks for your efforts!

**Comment by theultimatecrouton** [comment]
No worries :)
