### ISSUE TITLE
Tests failing on NetBSD

### ISSUE THREAD

**Issue by krytarowski** [numpy/numpy#7867]
OS information:

```
$ uname -rms
NetBSD 7.99.33 amd64
chieftec$ g95 --version
G95 (GCC 4.1.2 (g95 0.93!) Jul 24 2016)
Copyright (C) 2002-2008 Free Software Foundation, Inc.

G95 comes with NO WARRANTY, to the extent permitted by law.
You may redistribute copies of G95
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING
chieftec$ gcc --version
gcc (nb1 20160606) 5.4.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

```

Result of running tests:

```
$ make test
=> Bootstrap dependency digest>=20010302: found digest-20160304
===> Testing for py27-numpy-1.11.1
Running unit tests for numpy
NumPy version 1.11.1
NumPy relaxed strides checking option: False
NumPy is installed in /tmp/pkgsrc-tmp/local/py-numpy/work/.destdir/usr/pkg/lib/python2.7/site-packages/numpy
Python version 2.7.12 (default, Jul 23 2016, 23:05:41) [GCC 5.4.0]
nose version 1.3.7
...............................S.............................................................................................................................................S.....................................................................................................................................................................................................................KKK............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................S................................................................................................................................................................................................................................................................................................K........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................FFFFFFF..........FFFFFFF.......FFK............................F..................................................................................................K...SK.S.......S.............................................................................................................................................................................................................................................................................................................................................................................................................................................................E..................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................S..................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................S..................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
======================================================================
ERROR: test_callback.TestF77Callback.test_string_callback
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/pkg/lib/python2.7/site-packages/nose/case.py", line 381, in setUp
    try_run(self.inst, ('setup', 'setUp'))
  File "/usr/pkg/lib/python2.7/site-packages/nose/util.py", line 471, in try_run
    return func()
  File "/tmp/pkgsrc-tmp/local/py-numpy/work/.destdir/usr/pkg/lib/python2.7/site-packages/numpy/f2py/tests/util.py", line 353, in setUp
    module_name=self.module_name)
  File "/tmp/pkgsrc-tmp/local/py-numpy/work/.destdir/usr/pkg/lib/python2.7/site-packages/numpy/f2py/tests/util.py", line 78, in wrapper
    memo[key] = func(*a, **kw)
  File "/tmp/pkgsrc-tmp/local/py-numpy/work/.destdir/usr/pkg/lib/python2.7/site-packages/numpy/f2py/tests/util.py", line 166, in build_code
    module_name=module_name)
  File "/tmp/pkgsrc-tmp/local/py-numpy/work/.destdir/usr/pkg/lib/python2.7/site-packages/numpy/f2py/tests/util.py", line 78, in wrapper
    memo[key] = func(*a, **kw)
  File "/tmp/pkgsrc-tmp/local/py-numpy/work/.destdir/usr/pkg/lib/python2.7/site-packages/numpy/f2py/tests/util.py", line 140, in build_module
    % (cmd[4:], asstr(out)))
RuntimeError: Running f2py failed: ['-m', '_test_ext_module_5403', '/tmp/tmpddZm0v/tmpVkZrEd.f']
running build
running config_cc
unifing config_cc, config, build_clib, build_ext, build commands --compiler options
running config_fc
unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
running build_src
build_src
building extension "_test_ext_module_5403" sources
f2py options: []
f2py:> /tmp/tmpg08clg/src.netbsd-7.99.33-amd64-2.7/_test_ext_module_5403module.c
creating /tmp/tmpg08clg/src.netbsd-7.99.33-amd64-2.7
appenddecl: "intent" not implemented.
Reading fortran codes...
        Reading file '/tmp/tmpddZm0v/tmpVkZrEd.f' (format:fix,strict)
Line #22 in /tmp/tmpddZm0v/tmpVkZrEd.f:"       intent(callback) fun"
        analyzeline: missing __user__ module (could be nothing)
Line #22 in /tmp/tmpddZm0v/tmpVkZrEd.f:"       intent(callback) fun"
        analyzeline: appending intent(callback) fun to t2 arguments
Post-processing...
        Block: _test_ext_module_5403
                        Block: t
                                        Block: fun
                        Block: func
                        Block: func0
                        Block: t2
                                        Block: fun
                        Block: string_callback
                                        Block: callback
Post-processing (stage 2)...
Building modules...
        Constructing call-back function "cb_fun_in_t__user__routines"
          def fun(): return a
        Constructing call-back function "cb_fun_in_t2__user__routines"
          def fun(): return a
        Constructing call-back function "cb_callback_in_string_callback__user__routines"
          def callback(r): return a
        Building module "_test_ext_module_5403"...
                Constructing wrapper function "t"...
                  a = t(fun,[fun_extra_args])
                Constructing wrapper function "func"...
                  a = func(a)
                Constructing wrapper function "func0"...
                  a = func0()
                Constructing wrapper function "t2"...
                  a = t2(fun,[fun_extra_args])
                Constructing wrapper function "string_callback"...
                  a = string_callback(callback,[callback_extra_args])
        Wrote C/API module "_test_ext_module_5403" to file "/tmp/tmpg08clg/src.netbsd-7.99.33-amd64-2.7/_test_ext_module_5403module.c"
  adding '/tmp/tmpg08clg/src.netbsd-7.99.33-amd64-2.7/fortranobject.c' to sources.
  adding '/tmp/tmpg08clg/src.netbsd-7.99.33-amd64-2.7' to include_dirs.
copying /tmp/pkgsrc-tmp/local/py-numpy/work/.destdir/usr/pkg/lib/python2.7/site-packages/numpy/f2py/src/fortranobject.c -> /tmp/tmpg08clg/src.netbsd-7.99.33-amd64-2.7
copying /tmp/pkgsrc-tmp/local/py-numpy/work/.destdir/usr/pkg/lib/python2.7/site-packages/numpy/f2py/src/fortranobject.h -> /tmp/tmpg08clg/src.netbsd-7.99.33-amd64-2.7
build_src: building npy-pkg config files
running build_ext
customize UnixCCompiler
customize UnixCCompiler using build_ext
customize GnuFCompiler
Found executable /tmp/pkgsrc-tmp/local/py-numpy/work/.wrapper/bin/g77
gnu: no Fortran 90 compiler found
gnu: no Fortran 90 compiler found
customize Gnu95FCompiler
Found executable /tmp/pkgsrc-tmp/local/py-numpy/work/.wrapper/bin/gfortran
customize Gnu95FCompiler
customize Gnu95FCompiler using build_ext
building '_test_ext_module_5403' extension
compiling C sources
C compiler: gcc -fno-strict-aliasing -O2 -g -ggdb -DHAVE_DB_185_H -pthread -I/usr/include -I/usr/pkg/include -DNDEBUG -O2 -g -ggdb -DHAVE_DB_185_H -pthread -I/usr/include -I/usr/pkg/include -fPIC

creating /tmp/tmpg08clg/tmp
creating /tmp/tmpg08clg/tmp/tmpg08clg
creating /tmp/tmpg08clg/tmp/tmpg08clg/src.netbsd-7.99.33-amd64-2.7
compile options: '-I/tmp/tmpg08clg/src.netbsd-7.99.33-amd64-2.7 -I/tmp/pkgsrc-tmp/local/py-numpy/work/.destdir/usr/pkg/lib/python2.7/site-packages/numpy/core/include -I/usr/pkg/include/python2.7 -c'
gcc: /tmp/tmpg08clg/src.netbsd-7.99.33-amd64-2.7/_test_ext_module_5403module.c
In file included from /tmp/pkgsrc-tmp/local/py-numpy/work/.destdir/usr/pkg/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1777:0,
                 from /tmp/pkgsrc-tmp/local/py-numpy/work/.destdir/usr/pkg/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                 from /tmp/pkgsrc-tmp/local/py-numpy/work/.destdir/usr/pkg/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from /tmp/tmpg08clg/src.netbsd-7.99.33-amd64-2.7/fortranobject.h:13,
                 from /tmp/tmpg08clg/src.netbsd-7.99.33-amd64-2.7/_test_ext_module_5403module.c:18:
/tmp/pkgsrc-tmp/local/py-numpy/work/.destdir/usr/pkg/lib/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
gcc: /tmp/tmpg08clg/src.netbsd-7.99.33-amd64-2.7/fortranobject.c
In file included from /tmp/pkgsrc-tmp/local/py-numpy/work/.destdir/usr/pkg/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1777:0,
                 from /tmp/pkgsrc-tmp/local/py-numpy/work/.destdir/usr/pkg/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                 from /tmp/pkgsrc-tmp/local/py-numpy/work/.destdir/usr/pkg/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from /tmp/tmpg08clg/src.netbsd-7.99.33-amd64-2.7/fortranobject.h:13,
                 from /tmp/tmpg08clg/src.netbsd-7.99.33-amd64-2.7/fortranobject.c:2:
/tmp/pkgsrc-tmp/local/py-numpy/work/.destdir/usr/pkg/lib/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
compiling Fortran sources
Fortran f77 compiler: /tmp/pkgsrc-tmp/local/py-numpy/work/.wrapper/bin/gfortran -Wall -g -ffixed-form -fno-second-underscore -fPIC -O3 -funroll-loops
Fortran f90 compiler: /tmp/pkgsrc-tmp/local/py-numpy/work/.wrapper/bin/gfortran -Wall -g -fno-second-underscore -fPIC -O3 -funroll-loops
Fortran fix compiler: /tmp/pkgsrc-tmp/local/py-numpy/work/.wrapper/bin/gfortran -Wall -g -ffixed-form -fno-second-underscore -Wall -g -fno-second-underscore -fPIC -O3 -funroll-loops
creating /tmp/tmpg08clg/tmp/tmpddZm0v
compile options: '-I/tmp/tmpg08clg/src.netbsd-7.99.33-amd64-2.7 -I/tmp/pkgsrc-tmp/local/py-numpy/work/.destdir/usr/pkg/lib/python2.7/site-packages/numpy/core/include -I/usr/pkg/include/python2.7 -c'
gfortran:f77: /tmp/tmpddZm0v/tmpVkZrEd.f
/tmp/pkgsrc-tmp/local/py-numpy/work/.wrapper/bin/gfortran -Wall -g -shared  -Wall -g -shared  -shared /tmp/tmpg08clg/tmp/tmpg08clg/src.netbsd-7.99.33-amd64-2.7/_test_ext_module_5403module.o /tmp/tmpg08clg/tmp/tmpg08clg/src.netbsd-7.99.33-amd64-2.7/fortranobject.o /tmp/tmpg08clg/tmp/tmpddZm0v/tmpVkZrEd.o -L/usr/pkg/bin/../lib/gcc-lib/x86_64--netbsd/4.1.2 -L/usr/pkg/lib -lpython2.7 -lgfortran -o ./_test_ext_module_5403.so
ld: cannot find -lgfortran
ld: cannot find -lgfortran
error: Command "/tmp/pkgsrc-tmp/local/py-numpy/work/.wrapper/bin/gfortran -Wall -g -shared  -Wall -g -shared  -shared /tmp/tmpg08clg/tmp/tmpg08clg/src.netbsd-7.99.33-amd64-2.7/_test_ext_module_5403module.o /tmp/tmpg08clg/tmp/tmpg08clg/src.netbsd-7.99.33-amd64-2.7/fortranobject.o /tmp/tmpg08clg/tmp/tmpddZm0v/tmpVkZrEd.o -L/usr/pkg/bin/../lib/gcc-lib/x86_64--netbsd/4.1.2 -L/usr/pkg/lib -lpython2.7 -lgfortran -o ./_test_ext_module_5403.so" failed with exit status 1


======================================================================
FAIL: test_umath.TestComplexFunctions.test_branch_cuts(<ufunc 'sqrt'>, -0.5, 1j, 1, -1, True)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/pkg/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/tmp/pkgsrc-tmp/local/py-numpy/work/.destdir/usr/pkg/lib/python2.7/site-packages/numpy/core/tests/test_umath.py", line 1889, in _check_branch_cut
    assert_(np.all(np.absolute(y0[ji].imag - ym.imag*im_sign) < atol), (y0[ji], ym))
  File "/tmp/pkgsrc-tmp/local/py-numpy/work/.destdir/usr/pkg/lib/python2.7/site-packages/numpy/testing/utils.py", line 75, in assert_
    raise AssertionError(smsg)
AssertionError: (array([ 0.+0.70710678j]), array([ 0.+0.70710678j]))

======================================================================
FAIL: test_umath.TestComplexFunctions.test_branch_cuts(<ufunc 'arcsin'>, [-2, 2], [1j, 1j], 1, -1, True)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/pkg/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/tmp/pkgsrc-tmp/local/py-numpy/work/.destdir/usr/pkg/lib/python2.7/site-packages/numpy/core/tests/test_umath.py", line 1869, in _check_branch_cut
    assert_(np.all(np.absolute(y0.imag - yp.imag) < atol), (y0, yp))
  File "/tmp/pkgsrc-tmp/local/py-numpy/work/.destdir/usr/pkg/lib/python2.7/site-packages/numpy/testing/utils.py", line 75, in assert_
    raise AssertionError(smsg)
AssertionError: (array([-1.57079633+1.3169579j,  1.57079633-1.3169579j]), array([-1.57079633+1.3169579j,  1.57079633+1.3169579j]))

======================================================================
FAIL: test_umath.TestComplexFunctions.test_branch_cuts(<ufunc 'arccos'>, [-2, 2], [1j, 1j], 1, -1, True)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/pkg/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/tmp/pkgsrc-tmp/local/py-numpy/work/.destdir/usr/pkg/lib/python2.7/site-packages/numpy/core/tests/test_umath.py", line 1869, in _check_branch_cut
    assert_(np.all(np.absolute(y0.imag - yp.imag) < atol), (y0, yp))
  File "/tmp/pkgsrc-tmp/local/py-numpy/work/.destdir/usr/pkg/lib/python2.7/site-packages/numpy/testing/utils.py", line 75, in assert_
    raise AssertionError(smsg)
AssertionError: (array([ 3.14159265-1.3169579j,  0.00000000+1.3169579j]), array([  3.14159265e+00-1.3169579j,   2.56239474e-13-1.3169579j]))

======================================================================
FAIL: test_umath.TestComplexFunctions.test_branch_cuts(<ufunc 'arctan'>, [-2j, 2j], [1, 1], -1, 1, True)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/pkg/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/tmp/pkgsrc-tmp/local/py-numpy/work/.destdir/usr/pkg/lib/python2.7/site-packages/numpy/core/tests/test_umath.py", line 1868, in _check_branch_cut
    assert_(np.all(np.absolute(y0.real - yp.real) < atol), (y0, yp))
  File "/tmp/pkgsrc-tmp/local/py-numpy/work/.destdir/usr/pkg/lib/python2.7/site-packages/numpy/testing/utils.py", line 75, in assert_
    raise AssertionError(smsg)
AssertionError: (array([ -1.57079633e+000 -5.49306144e-001j,
         1.79769313e+308 +1.79769313e+308j]), array([ 1.57079633-0.54930614j,  1.57079633+0.54930614j]))

======================================================================
FAIL: test_umath.TestComplexFunctions.test_branch_cuts(<ufunc 'arcsinh'>, [-2j, 2j], [1, 1], -1, 1, True)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/pkg/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/tmp/pkgsrc-tmp/local/py-numpy/work/.destdir/usr/pkg/lib/python2.7/site-packages/numpy/core/tests/test_umath.py", line 1868, in _check_branch_cut
    assert_(np.all(np.absolute(y0.real - yp.real) < atol), (y0, yp))
  File "/tmp/pkgsrc-tmp/local/py-numpy/work/.destdir/usr/pkg/lib/python2.7/site-packages/numpy/testing/utils.py", line 75, in assert_
    raise AssertionError(smsg)
AssertionError: (array([-1.3169579-1.57079633j,  1.3169579+1.57079633j]), array([ 1.3169579-1.57079633j,  1.3169579+1.57079633j]))

======================================================================
FAIL: test_umath.TestComplexFunctions.test_branch_cuts(<ufunc 'arccosh'>, [-1, 0.5], [1j, 1j], 1, -1, True)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/pkg/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/tmp/pkgsrc-tmp/local/py-numpy/work/.destdir/usr/pkg/lib/python2.7/site-packages/numpy/core/tests/test_umath.py", line 1889, in _check_branch_cut
    assert_(np.all(np.absolute(y0[ji].imag - ym.imag*im_sign) < atol), (y0[ji], ym))
  File "/tmp/pkgsrc-tmp/local/py-numpy/work/.destdir/usr/pkg/lib/python2.7/site-packages/numpy/testing/utils.py", line 75, in assert_
    raise AssertionError(smsg)
AssertionError: (array([  0.00000000e+00+3.14159265j,  -1.11022302e-16+1.04719755j]), array([  0.00000000e+00+3.14159265j,  -1.11022302e-16+1.04719755j]))

======================================================================
FAIL: test_umath.TestComplexFunctions.test_branch_cuts(<ufunc 'arctanh'>, [-2, 2], [1j, 1j], 1, -1, True)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/pkg/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/tmp/pkgsrc-tmp/local/py-numpy/work/.destdir/usr/pkg/lib/python2.7/site-packages/numpy/core/tests/test_umath.py", line 1868, in _check_branch_cut
    assert_(np.all(np.absolute(y0.real - yp.real) < atol), (y0, yp))
  File "/tmp/pkgsrc-tmp/local/py-numpy/work/.destdir/usr/pkg/lib/python2.7/site-packages/numpy/testing/utils.py", line 75, in assert_
    raise AssertionError(smsg)
AssertionError: (array([ -5.49306144e-001 -1.57079633e+000j,
         1.79769313e+308 -1.79769313e+308j]), array([-0.54930614+1.57079633j,  0.54930614+1.57079633j]))

======================================================================
FAIL: test_umath.TestComplexFunctions.test_branch_cuts_complex64(<ufunc 'sqrt'>, -0.5, 1j, 1, -1, True, <type 'numpy.complex64'>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/pkg/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/tmp/pkgsrc-tmp/local/py-numpy/work/.destdir/usr/pkg/lib/python2.7/site-packages/numpy/core/tests/test_umath.py", line 1889, in _check_branch_cut
    assert_(np.all(np.absolute(y0[ji].imag - ym.imag*im_sign) < atol), (y0[ji], ym))
  File "/tmp/pkgsrc-tmp/local/py-numpy/work/.destdir/usr/pkg/lib/python2.7/site-packages/numpy/testing/utils.py", line 75, in assert_
    raise AssertionError(smsg)
AssertionError: (array([ 0.+0.70710677j], dtype=complex64), array([ 0.+0.70710677j], dtype=complex64))

======================================================================
FAIL: test_umath.TestComplexFunctions.test_branch_cuts_complex64(<ufunc 'arcsin'>, [-2, 2], [1j, 1j], 1, -1, True, <type 'numpy.complex64'>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/pkg/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/tmp/pkgsrc-tmp/local/py-numpy/work/.destdir/usr/pkg/lib/python2.7/site-packages/numpy/core/tests/test_umath.py", line 1869, in _check_branch_cut
    assert_(np.all(np.absolute(y0.imag - yp.imag) < atol), (y0, yp))
  File "/tmp/pkgsrc-tmp/local/py-numpy/work/.destdir/usr/pkg/lib/python2.7/site-packages/numpy/testing/utils.py", line 75, in assert_
    raise AssertionError(smsg)
AssertionError: (array([-1.57079637+1.31695783j,  1.57079637-1.31695795j], dtype=complex64), array([-1.57078254+1.31695783j,  1.57078254+1.31695783j], dtype=complex64))

======================================================================
FAIL: test_umath.TestComplexFunctions.test_branch_cuts_complex64(<ufunc 'arccos'>, [-2, 2], [1j, 1j], 1, -1, True, <type 'numpy.complex64'>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/pkg/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/tmp/pkgsrc-tmp/local/py-numpy/work/.destdir/usr/pkg/lib/python2.7/site-packages/numpy/core/tests/test_umath.py", line 1869, in _check_branch_cut
    assert_(np.all(np.absolute(y0.imag - yp.imag) < atol), (y0, yp))
  File "/tmp/pkgsrc-tmp/local/py-numpy/work/.destdir/usr/pkg/lib/python2.7/site-packages/numpy/testing/utils.py", line 75, in assert_
    raise AssertionError(smsg)
AssertionError: (array([ 3.14159274-1.31695783j,  0.00000000+1.31695795j], dtype=complex64), array([  3.14157891e+00-1.31695783j,   1.38282776e-05-1.31695783j], dtype=complex64))

======================================================================
FAIL: test_umath.TestComplexFunctions.test_branch_cuts_complex64(<ufunc 'arctan'>, [-2j, 2j], [1, 1], -1, 1, True, <type 'numpy.complex64'>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/pkg/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/tmp/pkgsrc-tmp/local/py-numpy/work/.destdir/usr/pkg/lib/python2.7/site-packages/numpy/core/tests/test_umath.py", line 1868, in _check_branch_cut
    assert_(np.all(np.absolute(y0.real - yp.real) < atol), (y0, yp))
  File "/tmp/pkgsrc-tmp/local/py-numpy/work/.destdir/usr/pkg/lib/python2.7/site-packages/numpy/testing/utils.py", line 75, in assert_
    raise AssertionError(smsg)
AssertionError: (array([ -1.57079625e+00 -5.49306154e-01j,   3.40282347e+38 +3.40282347e+38j], dtype=complex64), array([ 1.57078838-0.54930615j,  1.57078838+0.54930615j], dtype=complex64))

======================================================================
FAIL: test_umath.TestComplexFunctions.test_branch_cuts_complex64(<ufunc 'arcsinh'>, [-2j, 2j], [1, 1], -1, 1, True, <type 'numpy.complex64'>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/pkg/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/tmp/pkgsrc-tmp/local/py-numpy/work/.destdir/usr/pkg/lib/python2.7/site-packages/numpy/core/tests/test_umath.py", line 1868, in _check_branch_cut
    assert_(np.all(np.absolute(y0.real - yp.real) < atol), (y0, yp))
  File "/tmp/pkgsrc-tmp/local/py-numpy/work/.destdir/usr/pkg/lib/python2.7/site-packages/numpy/testing/utils.py", line 75, in assert_
    raise AssertionError(smsg)
AssertionError: (array([-1.31695795-1.57079637j,  1.31695783+1.57079637j], dtype=complex64), array([ 1.31695783-1.57078254j,  1.31695783+1.57078254j], dtype=complex64))

======================================================================
FAIL: test_umath.TestComplexFunctions.test_branch_cuts_complex64(<ufunc 'arccosh'>, [-1, 0.5], [1j, 1j], 1, -1, True, <type 'numpy.complex64'>)
----------------------------------------------------------------------
  File "/tmp/pkgsrc-tmp/local/py-numpy/work/.destdir/usr/pkg/lib/python2.7/site-packages/numpy/testing/utils.py", line 75, in assert_
    raise AssertionError(smsg)
AssertionError: (array([ 0.+3.14159274j,  0.+1.04719758j], dtype=complex64), array([ 0.+3.14159274j,  0.+1.04719758j], dtype=complex64))

======================================================================
FAIL: test_umath.TestComplexFunctions.test_branch_cuts_complex64(<ufunc 'arctanh'>, [-2, 2], [1j, 1j], 1, -1, True, <type 'numpy.complex64'>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/pkg/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/tmp/pkgsrc-tmp/local/py-numpy/work/.destdir/usr/pkg/lib/python2.7/site-packages/numpy/core/tests/test_umath.py", line 1868, in _check_branch_cut
    assert_(np.all(np.absolute(y0.real - yp.real) < atol), (y0, yp))
  File "/tmp/pkgsrc-tmp/local/py-numpy/work/.destdir/usr/pkg/lib/python2.7/site-packages/numpy/testing/utils.py", line 75, in assert_
    raise AssertionError(smsg)
AssertionError: (array([ -5.49306154e-01 -1.57079625e+00j,   3.40282347e+38 -3.40282347e+38j], dtype=complex64), array([-0.54930615+1.57078838j,  0.54930615+1.57078838j], dtype=complex64))

======================================================================
FAIL: test_umath.TestComplexFunctions.test_loss_of_precision(<type 'numpy.complex64'>,)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/pkg/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/tmp/pkgsrc-tmp/local/py-numpy/work/.destdir/usr/pkg/lib/python2.7/site-packages/numpy/core/tests/test_umath.py", line 1755, in check_loss_of_precision
    check(x_series, 2.1*eps)
  File "/tmp/pkgsrc-tmp/local/py-numpy/work/.destdir/usr/pkg/lib/python2.7/site-packages/numpy/core/tests/test_umath.py", line 1726, in check
    'arcsinh'))
  File "/tmp/pkgsrc-tmp/local/py-numpy/work/.destdir/usr/pkg/lib/python2.7/site-packages/numpy/testing/utils.py", line 75, in assert_
    raise AssertionError(smsg)
AssertionError: (0, 9.9999997e-21, inf, 'arcsinh')

======================================================================
FAIL: test_umath.TestComplexFunctions.test_loss_of_precision(<type 'numpy.complex128'>,)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/pkg/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/tmp/pkgsrc-tmp/local/py-numpy/work/.destdir/usr/pkg/lib/python2.7/site-packages/numpy/core/tests/test_umath.py", line 1755, in check_loss_of_precision
    check(x_series, 2.1*eps)
  File "/tmp/pkgsrc-tmp/local/py-numpy/work/.destdir/usr/pkg/lib/python2.7/site-packages/numpy/core/tests/test_umath.py", line 1726, in check
    'arcsinh'))
  File "/tmp/pkgsrc-tmp/local/py-numpy/work/.destdir/usr/pkg/lib/python2.7/site-packages/numpy/testing/utils.py", line 75, in assert_
    raise AssertionError(smsg)
AssertionError: (0, 1.0000000000000001e-20, inf, 'arcsinh')

======================================================================
FAIL: test_ldexp_overflow (test_umath.TestLdexp)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/pkgsrc-tmp/local/py-numpy/work/.destdir/usr/pkg/lib/python2.7/site-packages/numpy/core/tests/test_umath.py", line 750, in test_ldexp_overflow
    assert_equal(ncu.ldexp(2., imax), np.inf)
  File "/tmp/pkgsrc-tmp/local/py-numpy/work/.destdir/usr/pkg/lib/python2.7/site-packages/numpy/testing/utils.py", line 367, in assert_equal
    raise AssertionError(msg)
AssertionError: 
Items are not equal:
 ACTUAL: 0.0
 DESIRED: inf

----------------------------------------------------------------------
Ran 6115 tests in 66.806s

FAILED (KNOWNFAIL=7, SKIP=8, errors=1, failures=17)
```

Let me know how I can help to squash the issues.

**Comment by krytarowski** [comment]
Should gfortran be used over g95?

**Comment by charris** [comment]
> Should gfortran be used over g95?
Numpy only needs fortran to test for f2py and I don't see any related failures. Many of the branch cut errors look like precision, it would be could if you could determine just how big the differences are. Some of the remainder are probably legitimate, but we should clear out the easy bits first.

**Comment by krytarowski** [comment]
```
RuntimeError: Running f2py failed: ['-m', '_test_ext_module_5403', '/tmp/tmpddZm0v/tmpVkZrEd.f']
```

This one is false positive, we rename f2py to f2py${PYVERSSUFFIX} (e.g. "f2py2.7"). I will fix it locally.

**Comment by charris** [comment]
Hmm, that should be OK, we check for
```
f2py_cmds = ('f2py', 'f2py' + major, 'f2py' + major + '.' + minor)
```
There may be an error elsewhere.

**Comment by charris** [comment]
@krytarowski It may be that the file is installed but not in the default paths.

**Comment by krytarowski** [comment]
Fixed in NetBSD's libm.
