### ISSUE TITLE
ImportError: libopenblasp: cannot read file data

### ISSUE THREAD

**Issue by cancan101** [numpy/numpy#7962]
When trying to import numpy:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/numpy/__init__.py", line 180, in <module>
    from . import add_newdocs
  File "/usr/local/lib/python2.7/dist-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/__init__.py", line 14, in <module>
    from . import multiarray
ImportError: /usr/local/lib/python2.7/dist-packages/numpy/core/../.libs/libopenblasp-r0-39a31c03.2.18.so: cannot read file data
```

However the file does exist:
```
ls -al /usr/local/lib/python2.7/dist-packages/numpy/core/../.libs/libopenblasp-r0-39a31c03.2.18.so
-rwxr-xr-x 1 root staff 33554432 Aug 12 19:03 /usr/local/lib/python2.7/dist-packages/numpy/core/../.libs/libopenblasp-r0-39a31c03.2.18.so
```

```
# file  /usr/local/lib/python2.7/dist-packages/numpy/core/../.libs/libopenblasp-r0-39a31c03.2.18.so
/usr/local/lib/python2.7/dist-packages/numpy/core/../.libs/libopenblasp-r0-39a31c03.2.18.so: ELF 64-bit LSB  shared object, x86-64, version 1 (SYSV), statically linked, stripped
```

**Comment by charris** [comment]
Hmm, this is the first report of this. Did you install with pip? On what platform are you running?

**Comment by cancan101** [comment]
This was as part of the tensorflow Docker image. It had been installing through apt-get and then using pip. I remove the apt-get install and rebuilt the image and the problem went away.
