### ISSUE TITLE
In-place addition (and other operations) of masked array invoke extra casting check

### ISSUE THREAD

**Issue by jjhelmus** [numpy/numpy#7991]
In-place addition and other in-place operations on masked arrays where the mask is not nomask results in an ufunc casting rule check which is not performed when the operation is performed normally (not in-place) or on a normal ndarray.

Example

``` Python
>>> import numpy as np
>>> x = np.ma.array([0, 1, 2], dtype='uint8', mask=False)
>>> x += 4
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jhelmus/anaconda/lib/python3.5/site-packages/numpy/ma/core.py", line 4025, in __iadd__
    getdata(other)))
TypeError: Cannot cast ufunc add output from dtype('int64') to dtype('uint8') with casting rule 'same_kind'
>>> # Not in place
>>> x = x + 4
>>> # on a normal ndarray
>>> x = np.array([0, 1, 2], dtype='uint8')
>>> x += 4
```

**Comment by jjhelmus** [comment]
I believe this issue can be fixed by casting the value to be added to the dtype of the data array, although I do not know if this behavior would be consistent with how ndarray perform in-place operations.

Specifically the current implementation of `MaskedArray.__iadd__`:

``` Python
    def __iadd__(self, other):
        """
        Add other to self in-place.
        """
        m = getmask(other)
        if self._mask is nomask:
            if m is not nomask and m.any():
                self._mask = make_mask_none(self.shape, self.dtype)
                self._mask += m
        else:
            if m is not nomask:
                self._mask += m
        self._data.__iadd__(np.where(self._mask, self.dtype.type(0),
                                     getdata(other)))
        return self
```

Could be modified as follows:

``` Python
       ... 
       self._data.__iadd__(np.where(self._mask, self.dtype.type(0),
                                     getdata(other).astype(self.dtype)))
        return self
```

**Comment by seberg** [comment]
Its a bit trickier. If you just cast the other one, you will do a forced cast, which will create the same error in the other but in the opposite direction. We want an error if `4` was in fact `4.`, this would remove the error there.

On option might be to use:
```
np.add(self._data, other, where=self.mask, out=self._data)
```
but I am a bit unsure about possible complications due some weird cases like subclasses or some such.

The `np.result_type` hack should work (instead of using plain `self.dtype`).

**Comment by jjhelmus** [comment]
Yes indeed, I though that the explicit casting was too simple.  The `np.add `option appears to work when the mask is inverted (a False value in the mask indicates the value should be used):

``` Python
np.add(self._data, other, where=~self.mask, out=self._data)
```

as does casting the getdata return using `np.result_type`.  Both changes do not appear to break the current unit tests.  If either method preferred?  Should I submit a PR suggesting one of these changes for discussion?

**Comment by seberg** [comment]
I think for that `np.add` thing not to work there would have to be some impressively weird subclass of ndarray in `np._data` going on, but on the other hand, I am not sure how the result type thing could possibly change any unrelated behaviour.
