### ISSUE TITLE
File contains no section headers, site.cfg

### ISSUE THREAD

**Issue by GeorgeXia1828** [numpy/numpy#8154]
I am using python setup.py to install numpy

my site.cfg is:
 [openblas]
 libraries = openblas
 library_dirs = /data3/rd/wanghongyu/MyBin/openblas/lib
 include_dirs = /data3/rd/wanghongyu/MyBin/openblas/include 

> [rd@idc01-rank-gpu-01 numpy-1.9.2]$ python setup.py build
Running from numpy source directory.
Cythonizing sources
numpy/random/mtrand/mtrand.pyx has not changed
/data3/rd/wanghongyu/MyBin/python/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'test_suite'
  warnings.warn(msg)
non-existing path in 'numpy/f2py': 'docs'
non-existing path in 'numpy/f2py': 'f2py.1'
F2PY Version 2
Traceback (most recent call last):
  File "setup.py", line 251, in <module>
    setup_package()
  File "setup.py", line 243, in setup_package
    setup(**metadata)
  File "/data3/rd/wanghongyu/PKG/numpy-1.9.2/numpy/distutils/core.py", line 135, in setup
    config = configuration()
  File "setup.py", line 148, in configuration
    config.add_subpackage('numpy')
  File "/data3/rd/wanghongyu/PKG/numpy-1.9.2/numpy/distutils/misc_util.py", line 966, in add_subpackage
    caller_level = 2)
  File "/data3/rd/wanghongyu/PKG/numpy-1.9.2/numpy/distutils/misc_util.py", line 935, in get_subpackage
    caller_level = caller_level + 1)
  File "/data3/rd/wanghongyu/PKG/numpy-1.9.2/numpy/distutils/misc_util.py", line 872, in _get_configuration_from_setup_py
    config = setup_module.configuration(*args)
  File "numpy/setup.py", line 11, in configuration
    config.add_subpackage('core')
  File "/data3/rd/wanghongyu/PKG/numpy-1.9.2/numpy/distutils/misc_util.py", line 966, in add_subpackage
    caller_level = 2)
  File "/data3/rd/wanghongyu/PKG/numpy-1.9.2/numpy/distutils/misc_util.py", line 935, in get_subpackage
    caller_level = caller_level + 1)
  File "/data3/rd/wanghongyu/PKG/numpy-1.9.2/numpy/distutils/misc_util.py", line 872, in _get_configuration_from_setup_py
    config = setup_module.configuration(*args)
  File "numpy/core/setup.py", line 952, in configuration
    blas_info = get_info('blas_opt', 0)
  File "/data3/rd/wanghongyu/PKG/numpy-1.9.2/numpy/distutils/system_info.py", line 369, in get_info
    return cl().get_info(notfound_action)
  File "/data3/rd/wanghongyu/PKG/numpy-1.9.2/numpy/distutils/system_info.py", line 479, in __init__
    self.parse_config_files()
  File "/data3/rd/wanghongyu/PKG/numpy-1.9.2/numpy/distutils/system_info.py", line 486, in parse_config_files
    self.cp.read(self.files)
  File "/data3/rd/wanghongyu/MyBin/python/lib/python2.7/ConfigParser.py", line 305, in read
    self._read(fp, filename)
  File "/data3/rd/wanghongyu/MyBin/python/lib/python2.7/ConfigParser.py", line 512, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
ConfigParser.MissingSectionHeaderError: File contains no section headers.
file: /data3/rd/wanghongyu/PKG/numpy-1.9.2/site.cfg, line: 101
' [openblas]\n'

> [rd@idc01-rank-gpu-01 numpy-1.9.2]$ uname -a
Linux idc01-rank-gpu-01 2.6.32-431.el6.x86_64 #1 SMP Sun Nov 10 22:19:54 EST 2013 x86_64 x86_64 x86_64 GNU/Linux

what should I do to write a correct site.cfg? thanks in advance!

**Comment by yahuvi** [comment]
I have a same problem.How do you solve this problem？

**Comment by eric-wieser** [comment]
Looks like the issue is a space at the start of the line, `' [openblas]\n'`
