### ISSUE TITLE
Test failures on Python 3.6.0b2

### ISSUE THREAD

**Issue by charris** [numpy/numpy#8176]
They seem to result from nesting `warnings.catch_warnings` and `suppress_warnings`. The problem is new in 3.6 and may be either be a Python bug, or something we are doing in `suppress_warnings` that we shouldn't.
```
FAIL: test_deprecations.TestComparisonDeprecations.test_array_richcompare_legacy_weirdness
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/charris/.local/lib/python3.6/site-packages/nose-1.3.6-py3.6.egg/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/charris/Workspace/numpy.git/build/testenv/lib/python3.6/site-packages/numpy/core/tests/test_deprecations.py", line 371, in test_array_richcompare_legacy_weirdness
    assert_warns(FutureWarning, lambda: np.arange(2) == "a")
  File "/home/charris/Workspace/numpy.git/build/testenv/lib/python3.6/site-packages/numpy/testing/utils.py", line 1723, in assert_warns
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/contextlib.py", line 89, in __exit__
    next(self.gen)
  File "/home/charris/Workspace/numpy.git/build/testenv/lib/python3.6/site-packages/numpy/testing/utils.py", line 1680, in _assert_warns_context
    raise AssertionError("No warning raised" + name_str)
AssertionError: No warning raised when calling <lambda>

======================================================================
FAIL: test_deprecations.TestComparisonDeprecations.test_none_comparison
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/charris/.local/lib/python3.6/site-packages/nose-1.3.6-py3.6.egg/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/charris/Workspace/numpy.git/build/testenv/lib/python3.6/site-packages/numpy/core/tests/test_deprecations.py", line 315, in test_none_comparison
    assert_warns(FutureWarning, operator.eq, np.arange(3), None)
  File "/home/charris/Workspace/numpy.git/build/testenv/lib/python3.6/site-packages/numpy/testing/utils.py", line 1723, in assert_warns
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/contextlib.py", line 89, in __exit__
    next(self.gen)
  File "/home/charris/Workspace/numpy.git/build/testenv/lib/python3.6/site-packages/numpy/testing/utils.py", line 1680, in _assert_warns_context
    raise AssertionError("No warning raised" + name_str)
AssertionError: No warning raised when calling eq

======================================================================
FAIL: test_deprecations.TestComparisonDeprecations.test_void_dtype_equality_failures
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/charris/.local/lib/python3.6/site-packages/nose-1.3.6-py3.6.egg/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/charris/Workspace/numpy.git/build/testenv/lib/python3.6/site-packages/numpy/core/tests/test_deprecations.py", line 359, in test_void_dtype_equality_failures
    assert_warns(FutureWarning, lambda: struct1 == 1)
  File "/home/charris/Workspace/numpy.git/build/testenv/lib/python3.6/site-packages/numpy/testing/utils.py", line 1723, in assert_warns
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/contextlib.py", line 89, in __exit__
    next(self.gen)
  File "/home/charris/Workspace/numpy.git/build/testenv/lib/python3.6/site-packages/numpy/testing/utils.py", line 1680, in _assert_warns_context
    raise AssertionError("No warning raised" + name_str)
AssertionError: No warning raised when calling <lambda>

======================================================================
FAIL: test_deprecations.TestIdentityComparisonDeprecations.test_identity_equality_mismatch
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/charris/.local/lib/python3.6/site-packages/nose-1.3.6-py3.6.egg/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/charris/Workspace/numpy.git/build/testenv/lib/python3.6/site-packages/numpy/core/tests/test_deprecations.py", line 415, in test_identity_equality_mismatch
    assert_warns(FutureWarning, np.equal, a, a)
  File "/home/charris/Workspace/numpy.git/build/testenv/lib/python3.6/site-packages/numpy/testing/utils.py", line 1723, in assert_warns
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/contextlib.py", line 89, in __exit__
    next(self.gen)
  File "/home/charris/Workspace/numpy.git/build/testenv/lib/python3.6/site-packages/numpy/testing/utils.py", line 1680, in _assert_warns_context
    raise AssertionError("No warning raised" + name_str)
AssertionError: No warning raised when calling equal

======================================================================
FAIL: test_deprecations.TestRankDeprecation.test
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/charris/.local/lib/python3.6/site-packages/nose-1.3.6-py3.6.egg/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/charris/Workspace/numpy.git/build/testenv/lib/python3.6/site-packages/numpy/core/tests/test_deprecations.py", line 272, in test
    assert_warns(np.VisibleDeprecationWarning, np.rank, a)
  File "/home/charris/Workspace/numpy.git/build/testenv/lib/python3.6/site-packages/numpy/testing/utils.py", line 1723, in assert_warns
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/contextlib.py", line 89, in __exit__
    next(self.gen)
  File "/home/charris/Workspace/numpy.git/build/testenv/lib/python3.6/site-packages/numpy/testing/utils.py", line 1680, in _assert_warns_context
    raise AssertionError("No warning raised" + name_str)
AssertionError: No warning raised when calling rank

======================================================================
FAIL: test_utils.test_suppress_warnings_decorate_no_record
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/charris/.local/lib/python3.6/site-packages/nose-1.3.6-py3.6.egg/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/charris/Workspace/numpy.git/build/testenv/lib/python3.6/site-packages/numpy/testing/tests/test_utils.py", line 945, in test_suppress_warnings_decorate_no_record
    assert_(len(w) == 1)
  File "/home/charris/Workspace/numpy.git/build/testenv/lib/python3.6/site-packages/numpy/testing/utils.py", line 90, in assert_
    raise AssertionError(smsg)
AssertionError

----------------------------------------------------------------------
```

**Comment by charris** [comment]
@seberg Could you take a look at this?

**Comment by seberg** [comment]
Have to install the new python. One reason could be if warning classes changed their inheritance scheme. But that is only a wild guessfrom the last failure there, if RuntimeWarning is now a subclass of UserWarning this would be expected.

**Comment by seberg** [comment]
Nope, thats not it.

**Comment by seberg** [comment]
OK, can't reproduce the minimal example, so going to be a bit more annoying likely. (just suppress warnings without numpy outside test suit). Or is there some chance of threading going on?
