### ISSUE TITLE
multivariate_normal sample fails for large matrix

### ISSUE THREAD

**Issue by Horta** [numpy/numpy#8261]
```python
from numpy.random import RandomState

s = RandomState(0)

N = 50000
m = s.randn(N)
G = s.randn(N, 100)
K = G.dot(G.T)

u = s.multivariate_normal(m, K)
```

prints ``init_dgesdd failed init``.

# Additional information

```bash
> python --version
Python 3.5.2 :: Anaconda 4.2.0 (64-bit)
> python -c "import numpy; print(numpy.__version__)"
1.11.1
> python -c "import scipy; print(scipy.__version__)"
0.18.1
```

**Comment by Horta** [comment]
The following also fails:

```python
from numpy.random import RandomState
from numpy.linalg import svd

s = RandomState(0)

N = 50000
m = s.randn(N)
G = s.randn(N, 100)
K = G.dot(G.T)

U, S, V = svd(K, full_matrices=True)
```

**Comment by Horta** [comment]
The following fails by trowing an exception:

```python
from numpy.random import RandomState
from scipy.linalg import svd

s = RandomState(0)

N = 50000
m = s.randn(N)
G = s.randn(N, 100)
K = G.dot(G.T)

U, S, V = svd(K, full_matrices=True)
```

```
Traceback (most recent call last):
  File "bug.py", line 11, in <module>
    U, S, V = svd(K, full_matrices=True)
  File "/nfs/software/stegle/users/horta/conda-envs/exp2/lib/python3.5/site-packages/scipy/linalg/decomp_svd.py", line 112, in svd
    compute_uv=compute_uv, full_matrices=full_matrices)
  File "/nfs/software/stegle/users/horta/conda-envs/exp2/lib/python3.5/site-packages/scipy/linalg/lapack.py", line 488, in _compute_lwork
    raise ValueError("Too large work array required -- computation cannot "
ValueError: Too large work array required -- computation cannot be performed with standard 32-bit LAPACK.
```

**Comment by pv** [comment]
The last message tells what is the problem. The matrix is too large for 
32-bit LAPACK to compute svd.

**Comment by Horta** [comment]
Shouldn't it be a bug? As I'm using 64 bit machine...

**Comment by pv** [comment]
LAPACK is typically compiled with 32-bit integers. I don't know if any 
linux distribution offers 64-bit lapack as a package (e.g. ubuntu does not).
.
But Numpy should raise exception for failed LAPACK init, not just print 
error messages.

**Comment by pv** [comment]
Numpy also does not currently support lapack64: gh-5906
