### ISSUE TITLE
[f2py] Impossible for two fortran functions to use the same python callback function

### ISSUE THREAD

**Issue by MarkWieczorek** [numpy/numpy#8288]
I have written a very simple program python program that calls a fortran routine, and then this fortran routine calls a python callcack function: https://github.com/MarkWieczorek/callback_test 

Everything works as expected. However, once I add a second fortran routine that makes use of the same python callback function, f2py can not even compile the code, complaining that the callback function is being redefined. I am certain that there must be a way to do this, but I can not figure it out.

Here are the two fortran routines, which call the python function `pyfunc`:
```
subroutine routine()
    integer i
    external pyfunc
    i=1
    print*, "In ROUTINE"
    call pyfunc(i) ! This will be defined to raise a Python exception
    print*, "Called PYFUNC. Shouldn't be here!"
    return
end subroutine routine

subroutine routine2()
    integer i
    external pyfunc
    i=2
    print*, "In ROUTINE2"
    call pyfunc(i) ! This will be defined to raise a Python exception
    print*, "Called PYFUNC. Shouldn't be here!"
    return
end subroutine routine2
```
and here is the python signature file
```
python module callback_test
    interface
        subroutine routine()
            intent(callback,hide) pyfunc
            external pyfunc
            integer i
            call pyfunc(i)
        end subroutine routine

!        subroutine routine2()
!            intent(callback,hide) pyfunc
!            external pyfunc
!            integer i
!            call pyfunc(i)
!        end subroutine routine2
    end interface
end python module callback_test
```
Compiling
```
python3 -m numpy.f2py -c signature.pyf subroutine.f95
```
and then running
```
import callback_test
def f(status): raise Exception(status)
callback_test.pyfunc = f
callback_test.routine()
```
gives the output
```
 In ROUTINE
capi_return is NULL
Call-back cb_pyfunc_in_routine__user__routines failed.
Traceback (most recent call last):
  File "script.py", line 4, in <module>
    callback_test.routine()
  File "script.py", line 2, in f
    def f(status): raise Exception(status)
Exception: 1
```
However, if I remove the comments from the above signature file, I get the error
```
/usr/local/lib/python3.5/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: "Using deprecated NumPy API, disable it by "          "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
#warning "Using deprecated NumPy API, disable it by " \
 ^
/var/folders/9v/k2l3cpqs1wn56ktkr4l5zncr0000gn/T/tmp886anvls/src.macosx-10.11-x86_64-3.5/callback_testmodule.c:327:13: error: redefinition of 'pyfunc_'
extern void F_FUNC(pyfunc,PYFUNC) (int *i_cb_capi) {
            ^
/var/folders/9v/k2l3cpqs1wn56ktkr4l5zncr0000gn/T/tmp886anvls/src.macosx-10.11-x86_64-3.5/callback_testmodule.c:87:21: note: expanded from macro 'F_FUNC'
#define F_FUNC(f,F) f##_
                    ^
<scratch space>:122:1: note: expanded from here
pyfunc_
^
/var/folders/9v/k2l3cpqs1wn56ktkr4l5zncr0000gn/T/tmp886anvls/src.macosx-10.11-x86_64-3.5/callback_testmodule.c:229:13: note: previous definition is here
extern void F_FUNC(pyfunc,PYFUNC) (int *i_cb_capi) {
            ^
/var/folders/9v/k2l3cpqs1wn56ktkr4l5zncr0000gn/T/tmp886anvls/src.macosx-10.11-x86_64-3.5/callback_testmodule.c:87:21: note: expanded from macro 'F_FUNC'
#define F_FUNC(f,F) f##_
                    ^
<scratch space>:121:1: note: expanded from here
pyfunc_
^
1 warning and 1 error generated.
```
Any advice would be appreciated. I tried defining a python module `__user__routines`, but was not able to get this to work at all.

**Comment by tjfulle** [comment]
@MarkWieczorek, I do this often to send Python logging.info, logging.warning, etc functions in to my Fortran subroutines for logging purposes.  I believe what is missing is defining a module (in the `.pyf` File) with the callback functions defined and then `use`ing that module in the module you defined.  Something like

```fortran 
python module my__callback__funs
  interface my_callback_funs
        subroutine pyfunc(i)
            intent(callback) pyfunc
            integer :: i 
        end subroutine pyfunc
  end interface my_callback_funs
end python module my__callback__funs
python module callback_test
    interface
        subroutine routine()
            use my__callback__funs
            intent(callback) pyfunc
            external pyfunc
        end subroutine routine

        subroutine routine2()
             use my__callback__funs
             intent(callback) pyfunc
             external pyfunc
          end subroutine routine2
    end interface
end python module callback_test
```

I removed the `hide` attribute from the callback and removed the actual call to `pyfunc` - having assumed it would occur in the fortran subroutine.  I only did that since that has been the use case I use that I know works. 

I use this interface file regularly that defines multiple callbacks: https://github.com/tjfulle/matmodlab/blob/master/matmodlab/materials/src/umat.pyf
