### ISSUE TITLE
Test failures building up on PPC

### ISSUE THREAD

**Issue by matthew-brett** [numpy/numpy#8298]
On a Debian big-endian PPC machine, currently:

```
======================================================================
ERROR: test_denormal_numbers (test_function_base.TestLinspace)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/buildslave/debian-ppc-64/numpy-py2_7-debian-ppc/build/venv/local/lib/python2.7/site-packages/numpy-1.13.0.dev0_ce6d3ff-py2.7-linux-ppc64.egg/numpy/core/tests/test_function_base.py", line 305, in test_denormal_numbers
    stop = finfo(dt).tiny * finfo(dt).resolution
  File "/home/buildslave/debian-ppc-64/numpy-py2_7-debian-ppc/build/venv/local/lib/python2.7/site-packages/numpy-1.13.0.dev0_ce6d3ff-py2.7-linux-ppc64.egg/numpy/core/getlimits.py", line 124, in __new__
    obj = object.__new__(cls)._init(dtype)
  File "/home/buildslave/debian-ppc-64/numpy-py2_7-debian-ppc/build/venv/local/lib/python2.7/site-packages/numpy-1.13.0.dev0_ce6d3ff-py2.7-linux-ppc64.egg/numpy/core/getlimits.py", line 154, in _init
    'numpy %s precision floating point number' % precname)
  File "/home/buildslave/debian-ppc-64/numpy-py2_7-debian-ppc/build/venv/local/lib/python2.7/site-packages/numpy-1.13.0.dev0_ce6d3ff-py2.7-linux-ppc64.egg/numpy/core/machar.py", line 114, in __init__
    self._do_init(float_conv, int_conv, float_to_float, float_to_str, title)
  File "/home/buildslave/debian-ppc-64/numpy-py2_7-debian-ppc/build/venv/local/lib/python2.7/site-packages/numpy-1.13.0.dev0_ce6d3ff-py2.7-linux-ppc64.egg/numpy/core/machar.py", line 127, in _do_init
    a = a + a
RuntimeWarning: overflow encountered in add

======================================================================
ERROR: test_singleton (test_getlimits.TestLongdouble)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/buildslave/debian-ppc-64/numpy-py2_7-debian-ppc/build/venv/local/lib/python2.7/site-packages/numpy-1.13.0.dev0_ce6d3ff-py2.7-linux-ppc64.egg/numpy/core/tests/test_getlimits.py", line 41, in test_singleton
    ftype = finfo(longdouble)
  File "/home/buildslave/debian-ppc-64/numpy-py2_7-debian-ppc/build/venv/local/lib/python2.7/site-packages/numpy-1.13.0.dev0_ce6d3ff-py2.7-linux-ppc64.egg/numpy/core/getlimits.py", line 124, in __new__
    obj = object.__new__(cls)._init(dtype)
  File "/home/buildslave/debian-ppc-64/numpy-py2_7-debian-ppc/build/venv/local/lib/python2.7/site-packages/numpy-1.13.0.dev0_ce6d3ff-py2.7-linux-ppc64.egg/numpy/core/getlimits.py", line 154, in _init
    'numpy %s precision floating point number' % precname)
  File "/home/buildslave/debian-ppc-64/numpy-py2_7-debian-ppc/build/venv/local/lib/python2.7/site-packages/numpy-1.13.0.dev0_ce6d3ff-py2.7-linux-ppc64.egg/numpy/core/machar.py", line 114, in __init__
    self._do_init(float_conv, int_conv, float_to_float, float_to_str, title)
  File "/home/buildslave/debian-ppc-64/numpy-py2_7-debian-ppc/build/venv/local/lib/python2.7/site-packages/numpy-1.13.0.dev0_ce6d3ff-py2.7-linux-ppc64.egg/numpy/core/machar.py", line 127, in _do_init
    a = a + a
RuntimeWarning: overflow encountered in add

======================================================================
ERROR: Failure: RuntimeWarning (overflow encountered in add)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/buildslave/debian-ppc-64/numpy-py2_7-debian-ppc/build/venv/local/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/buildslave/debian-ppc-64/numpy-py2_7-debian-ppc/build/venv/local/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/buildslave/debian-ppc-64/numpy-py2_7-debian-ppc/build/venv/local/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/buildslave/debian-ppc-64/numpy-py2_7-debian-ppc/build/venv/local/lib/python2.7/site-packages/numpy-1.13.0.dev0_ce6d3ff-py2.7-linux-ppc64.egg/numpy/core/tests/test_longdouble.py", line 13, in <module>
    longdouble_longer_than_double = (np.finfo(np.longdouble).eps
  File "/home/buildslave/debian-ppc-64/numpy-py2_7-debian-ppc/build/venv/local/lib/python2.7/site-packages/numpy-1.13.0.dev0_ce6d3ff-py2.7-linux-ppc64.egg/numpy/core/getlimits.py", line 124, in __new__
    obj = object.__new__(cls)._init(dtype)
  File "/home/buildslave/debian-ppc-64/numpy-py2_7-debian-ppc/build/venv/local/lib/python2.7/site-packages/numpy-1.13.0.dev0_ce6d3ff-py2.7-linux-ppc64.egg/numpy/core/getlimits.py", line 154, in _init
    'numpy %s precision floating point number' % precname)
  File "/home/buildslave/debian-ppc-64/numpy-py2_7-debian-ppc/build/venv/local/lib/python2.7/site-packages/numpy-1.13.0.dev0_ce6d3ff-py2.7-linux-ppc64.egg/numpy/core/machar.py", line 114, in __init__
    self._do_init(float_conv, int_conv, float_to_float, float_to_str, title)
  File "/home/buildslave/debian-ppc-64/numpy-py2_7-debian-ppc/build/venv/local/lib/python2.7/site-packages/numpy-1.13.0.dev0_ce6d3ff-py2.7-linux-ppc64.egg/numpy/core/machar.py", line 127, in _do_init
    a = a + a
RuntimeWarning: overflow encountered in add

======================================================================
ERROR: Failure: RuntimeWarning (overflow encountered in add)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/buildslave/debian-ppc-64/numpy-py2_7-debian-ppc/build/venv/local/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/buildslave/debian-ppc-64/numpy-py2_7-debian-ppc/build/venv/local/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/buildslave/debian-ppc-64/numpy-py2_7-debian-ppc/build/venv/local/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/buildslave/debian-ppc-64/numpy-py2_7-debian-ppc/build/venv/local/lib/python2.7/site-packages/numpy-1.13.0.dev0_ce6d3ff-py2.7-linux-ppc64.egg/numpy/core/tests/test_umath.py", line 1752, in <module>
    class TestComplexFunctions(object):
  File "/home/buildslave/debian-ppc-64/numpy-py2_7-debian-ppc/build/venv/local/lib/python2.7/site-packages/numpy-1.13.0.dev0_ce6d3ff-py2.7-linux-ppc64.egg/numpy/core/tests/test_umath.py", line 1936, in TestComplexFunctions
    @dec.knownfailureif(is_longdouble_finfo_bogus(), "Bogus long double finfo")
  File "/home/buildslave/debian-ppc-64/numpy-py2_7-debian-ppc/build/venv/local/lib/python2.7/site-packages/numpy-1.13.0.dev0_ce6d3ff-py2.7-linux-ppc64.egg/numpy/core/tests/test_umath.py", line 1748, in is_longdouble_finfo_bogus
    info = np.finfo(np.longcomplex)
  File "/home/buildslave/debian-ppc-64/numpy-py2_7-debian-ppc/build/venv/local/lib/python2.7/site-packages/numpy-1.13.0.dev0_ce6d3ff-py2.7-linux-ppc64.egg/numpy/core/getlimits.py", line 124, in __new__
    obj = object.__new__(cls)._init(dtype)
  File "/home/buildslave/debian-ppc-64/numpy-py2_7-debian-ppc/build/venv/local/lib/python2.7/site-packages/numpy-1.13.0.dev0_ce6d3ff-py2.7-linux-ppc64.egg/numpy/core/getlimits.py", line 154, in _init
    'numpy %s precision floating point number' % precname)
  File "/home/buildslave/debian-ppc-64/numpy-py2_7-debian-ppc/build/venv/local/lib/python2.7/site-packages/numpy-1.13.0.dev0_ce6d3ff-py2.7-linux-ppc64.egg/numpy/core/machar.py", line 114, in __init__
    self._do_init(float_conv, int_conv, float_to_float, float_to_str, title)
  File "/home/buildslave/debian-ppc-64/numpy-py2_7-debian-ppc/build/venv/local/lib/python2.7/site-packages/numpy-1.13.0.dev0_ce6d3ff-py2.7-linux-ppc64.egg/numpy/core/machar.py", line 127, in _do_init
    a = a + a
RuntimeWarning: overflow encountered in add

======================================================================
FAIL: test_structure_format (test_arrayprint.TestArray2String)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/buildslave/debian-ppc-64/numpy-py2_7-debian-ppc/build/venv/local/lib/python2.7/site-packages/numpy-1.13.0.dev0_ce6d3ff-py2.7-linux-ppc64.egg/numpy/core/tests/test_arrayprint.py", line 129, in test_structure_format
    "('NaT',) ('NaT',) ('NaT',)]")
  File "/home/buildslave/debian-ppc-64/numpy-py2_7-debian-ppc/build/venv/local/lib/python2.7/site-packages/numpy-1.13.0.dev0_ce6d3ff-py2.7-linux-ppc64.egg/numpy/testing/utils.py", line 404, in assert_equal
    raise AssertionError(msg)
AssertionError: 
Items are not equal:
 ACTUAL: "[('1970-01-01T00:00:00',) ('1970-01-01T00:00:00',) ('1970-01-01T00:00:00',)\n ('1970-01-01T00:00:00',) ('1970-01-01T00:00:00',)\n ('-292277022589-02-15T11:44:00',) ('-292277022589-02-15T11:44:00',)\n ('-292277022589-02-15T11:44:00',) ('-292277022589-02-15T11:44:00',)\n ('-292277022589-02-15T11:44:00',)]"
 DESIRED: "[('1970-01-01T00:00:00',) ('1970-01-01T00:00:00',) ('1970-01-01T00:00:00',)\n ('1970-01-01T00:00:00',) ('1970-01-01T00:00:00',) ('NaT',) ('NaT',)\n ('NaT',) ('NaT',) ('NaT',)]"
```

http://nipy.bic.berkeley.edu/builders/numpy-py2.7-debian-ppc/builds/647/steps/shell_5/logs/stdio

Can give access to the machine if anyone needs it.

**Comment by charris** [comment]
@matthew-brett Is this problem solved, or improved, by #8504.

**Comment by matthew-brett** [comment]
Current failures here : http://nipy.bic.berkeley.edu/builders/numpy-py2.7-debian-ppc/builds/716/steps/shell_5/logs/stdio

```
======================================================================
ERROR: test_dot_out_mem_overlap (test_multiarray.TestMethods)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/buildslave/debian-ppc-64/numpy-py2_7-debian-ppc/build/venv/local/lib/python2.7/site-packages/numpy-1.13.0.dev0_a611932-py2.7-linux-ppc64.egg/numpy/core/tests/test_multiarray.py", line 2340, in test_dot_out_mem_overlap
    x = np.dot(a, b, out=b)
ValueError: output array is not acceptable (must have the right type, nr dimensions, and be a C-Array)

======================================================================
FAIL: test_structure_format (test_arrayprint.TestArray2String)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/buildslave/debian-ppc-64/numpy-py2_7-debian-ppc/build/venv/local/lib/python2.7/site-packages/numpy-1.13.0.dev0_a611932-py2.7-linux-ppc64.egg/numpy/core/tests/test_arrayprint.py", line 128, in test_structure_format
    "('NaT',) ('NaT',) ('NaT',)]")
  File "/home/buildslave/debian-ppc-64/numpy-py2_7-debian-ppc/build/venv/local/lib/python2.7/site-packages/numpy-1.13.0.dev0_a611932-py2.7-linux-ppc64.egg/numpy/testing/utils.py", line 404, in assert_equal
    raise AssertionError(msg)
AssertionError: 
Items are not equal:
 ACTUAL: "[('1970-01-01T00:00:00',) ('1970-01-01T00:00:00',) ('1970-01-01T00:00:00',)\n ('1970-01-01T00:00:00',) ('1970-01-01T00:00:00',)\n ('-292277022589-02-15T11:44:00',) ('-292277022589-02-15T11:44:00',)\n ('-292277022589-02-15T11:44:00',) ('-292277022589-02-15T11:44:00',)\n ('-292277022589-02-15T11:44:00',)]"
 DESIRED: "[('1970-01-01T00:00:00',) ('1970-01-01T00:00:00',) ('1970-01-01T00:00:00',)\n ('1970-01-01T00:00:00',) ('1970-01-01T00:00:00',) ('NaT',) ('NaT',)\n ('NaT',) ('NaT',) ('NaT',)]"

======================================================================
FAIL: test_denormal_numbers (test_function_base.TestLinspace)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/buildslave/debian-ppc-64/numpy-py2_7-debian-ppc/build/venv/local/lib/python2.7/site-packages/numpy-1.13.0.dev0_a611932-py2.7-linux-ppc64.egg/numpy/core/tests/test_function_base.py", line 306, in test_denormal_numbers
    assert_(any(linspace(0, stop, 10, endpoint=False, dtype=dt)))
  File "/home/buildslave/debian-ppc-64/numpy-py2_7-debian-ppc/build/venv/local/lib/python2.7/site-packages/numpy-1.13.0.dev0_a611932-py2.7-linux-ppc64.egg/numpy/testing/utils.py", line 90, in assert_
    raise AssertionError(smsg)
AssertionError

======================================================================
FAIL: test_longdouble.test_repr_roundtrip
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/buildslave/debian-ppc-64/numpy-py2_7-debian-ppc/build/venv/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/buildslave/debian-ppc-64/numpy-py2_7-debian-ppc/build/venv/local/lib/python2.7/site-packages/numpy-1.13.0.dev0_a611932-py2.7-linux-ppc64.egg/numpy/core/tests/test_longdouble.py", line 35, in test_repr_roundtrip
    "repr was %s" % repr(o))
  File "/home/buildslave/debian-ppc-64/numpy-py2_7-debian-ppc/build/venv/local/lib/python2.7/site-packages/numpy-1.13.0.dev0_a611932-py2.7-linux-ppc64.egg/numpy/testing/utils.py", line 404, in assert_equal
    raise AssertionError(msg)
AssertionError: 
Items are not equal: repr was 1.0
 ACTUAL: 1.0
 DESIRED: 1.0

======================================================================
FAIL: test_umath.TestComplexFunctions.test_loss_of_precision_longcomplex
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/buildslave/debian-ppc-64/numpy-py2_7-debian-ppc/build/venv/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/buildslave/debian-ppc-64/numpy-py2_7-debian-ppc/build/venv/local/lib/python2.7/site-packages/numpy-1.13.0.dev0_a611932-py2.7-linux-ppc64.egg/numpy/testing/decorators.py", line 217, in knownfailer
    return f(*args, **kwargs)
  File "/home/buildslave/debian-ppc-64/numpy-py2_7-debian-ppc/build/venv/local/lib/python2.7/site-packages/numpy-1.13.0.dev0_a611932-py2.7-linux-ppc64.egg/numpy/core/tests/test_umath.py", line 1981, in test_loss_of_precision_longcomplex
    self.check_loss_of_precision(np.longcomplex)
  File "/home/buildslave/debian-ppc-64/numpy-py2_7-debian-ppc/build/venv/local/lib/python2.7/site-packages/numpy-1.13.0.dev0_a611932-py2.7-linux-ppc64.egg/numpy/core/tests/test_umath.py", line 1932, in check_loss_of_precision
    check(x_series, 50*eps)
  File "/home/buildslave/debian-ppc-64/numpy-py2_7-debian-ppc/build/venv/local/lib/python2.7/site-packages/numpy-1.13.0.dev0_a611932-py2.7-linux-ppc64.egg/numpy/core/tests/test_umath.py", line 1905, in check
    'arcsinh'))
  File "/home/buildslave/debian-ppc-64/numpy-py2_7-debian-ppc/build/venv/local/lib/python2.7/site-packages/numpy-1.13.0.dev0_a611932-py2.7-linux-ppc64.egg/numpy/testing/utils.py", line 90, in assert_
    raise AssertionError(smsg)
AssertionError: (131, 1.5498743198116924955e-09, 4.0035173453530728024e-19, 'arcsinh')
```

So, the errors of form `a = a + a ; RuntimeWarning: overflow encountered in add` are fixed with #8504 but there are three new errors coming from somewhere.

**Comment by charris** [comment]
Hmm, the IBM doc said that double double didn't support denormals, overflow, or underflow and had incomplete support for inf, and nan. So some of those tests should probably be skipped. the overlap test is new in 1.13, not sure why it is a problem.

**Comment by charris** [comment]
Loss of precision is probably a library problem, might want to take a look at the test, maybe it should be changed/skipped.

**Comment by charris** [comment]
What library version do you have? Note that we don't have a double double fallback function for 'arcsinh'. If you skip that function, others may show up as errors.

**Comment by matthew-brett** [comment]
`test_structure_format` is due to #8325.

**Comment by matthew-brett** [comment]
Closing in favor of individual issues / PRs:

* #7940 ;
* #8325 ;
* #8564 ;
* #8565 ;
* #8566 .
