### ISSUE TITLE
Test errors from inplace power operator

### ISSUE THREAD

**Issue by rgommers** [numpy/numpy#8307]
They're new, likely due to gh-8231. It doesn't happen on all platforms, this is on OS X with Python 3.5:

    In [1]: x = np.arange(3)

    In [2]: x **= 4

    In [3]: x = np.arange(3, dtype=np.longdouble)

    In [4]: x **= 4
    /Library/Frameworks/Python.framework/Versions/3.5/bin/ipython:1: RuntimeWarning: divide by zero encountered in power
      #!/Library/Frameworks/Python.framework/Versions/3.5/bin/python3.5

The 4 test errors:

    ======================================================================
    ERROR: test_linalg.TestNormDouble.test_vector_return_type
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
        self.test(*self.arg)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/numpy/linalg/tests/test_linalg.py", line 882, in test_vector_return_type
        an = norm(at, 4)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/numpy/linalg/linalg.py", line 2224, in norm
        absx **= ord
    RuntimeWarning: divide by zero encountered in power

    ======================================================================
    ERROR: test_linalg.TestNormInt64.test_vector_return_type
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
        self.test(*self.arg)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/numpy/linalg/tests/test_linalg.py", line 882, in test_vector_return_type
        an = norm(at, 4)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/numpy/linalg/linalg.py", line 2224, in norm
        absx **= ord
    RuntimeWarning: divide by zero encountered in power

    ======================================================================
    ERROR: test_linalg.TestNormSingle.test_vector_return_type
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
        self.test(*self.arg)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/numpy/linalg/tests/test_linalg.py", line 882, in test_vector_return_type
        an = norm(at, 4)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/numpy/linalg/linalg.py", line 2224, in norm
        absx **= ord
    RuntimeWarning: divide by zero encountered in power

    ======================================================================
    ERROR: test_linalg.TestNorm_NonSystematic.test_longdouble_norm
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
        self.test(*self.arg)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/numpy/linalg/tests/test_linalg.py", line 1116, in test_longdouble_norm
        old_assert_almost_equal(norm(x, ord=3), 12.65, decimal=2)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/numpy/linalg/linalg.py", line 2224, in norm
        absx **= ord
    RuntimeWarning: divide by zero encountered in power

**Comment by charris** [comment]
That is a very strange bug, especially if it is OS X specific. Are the actual results correct? If so, I'd suspect a bug in a library, there should be no divisions.

**Comment by charris** [comment]
Ralf, can you check that the ufunc itself works without warnings? I'd like to determine if this is specific to the inplace operator.

**Comment by rgommers** [comment]
It's not:

    In [9]: x = np.arange(3, dtype=np.longdouble)

    In [10]: np.power(x, 4)
    /Library/Frameworks/Python.framework/Versions/3.5/bin/ipython:1: RuntimeWarning: divide by zero encountered in power
      #!/Library/Frameworks/Python.framework/Versions/3.5/bin/python3.5
    Out[10]: array([ 0.0,  1.0,  16.0], dtype=float128)

It's specific to ``float128`` though.

**Comment by charris** [comment]
So it is located in the `powl` function. The remaining question is: ours or theirs? Do you have a local build so that you can grep for 'HAVE_POWL' in the `config.h` file?

**Comment by charris** [comment]
And our fallback version of `powl` simply calls the double version. Are you are using the PyPI wheel?

**Comment by charris** [comment]
So I think it is the Mac `powl` function. That can be verified by blacklisting it in `numpy/core/src/private/config.h`.

**Comment by rgommers** [comment]
> Do you have a local build so that you can grep for 'HAVE_POWL' in the `config.h` file?
 
   $ grin HAVE_POWL
    ./numpy/core/include/numpy/config.h:
    114 : #define HAVE_POWL 1

> Are you are using the PyPI wheel?

No, a local build of recent master. Checked PyPI wheel for 1.11.2 - has the same issue.

> So I think it is the Mac ``powl`` function. That can be verified by blacklisting it in ``numpy/core/src/private/config.h``.

That fixes it.

Weird issue though, ``NPY_OS_DARWIN`` seems to be undefined. This:

    $ git diff
    diff --git a/numpy/core/src/private/npy_config.h b/numpy/core/src/private/npy_config.h
    index 5f8aa3b..950a2f9 100644
    --- a/numpy/core/src/private/npy_config.h
    +++ b/numpy/core/src/private/npy_config.h
    @@ -69,6 +69,9 @@
     #endif
     #endif /* defined(_MSC_VER) && defined(__INTEL_COMPILER) */
     
    +#if defined(HAVE_POWL) && defined(NPY_OS_DARWIN)
    +#undef HAVE_POWL
    +#endif
     
does not help, but without ``&& defined(NPY_OS_DARWIN)`` it fixes the problem. ``NPY_OS_DARWIN`` is only used in one other place (``npy_fpmath.h``), which also deals with ``longdouble``.

**Comment by charris** [comment]
Any idea why we didn't detect this earlier? Perhaps Sebastian's work to make sure warnings are cleared correctly is responsible.

**Comment by rgommers** [comment]
Not sure, but that sounds like a plausible explanation.

**Comment by charris** [comment]
And the error didn't show up on the wheel builds because it was a release. Hmm..., we really need to start testing on the Mac platform. IIRC, we cannot do both on travis.

**Comment by pv** [comment]
iirc travis does support osx hosts for open source, so maybe add one in the matrix?

**Comment by matthew-brett** [comment]
Yes, I think travis-ci quietly enabled this feature for open-source accounts a few months ago.  See https://github.com/scikit-image/scikit-image/blob/master/.travis.yml#L52 for an example.

**Comment by rgommers** [comment]
Yes should work: https://docs.travis-ci.com/user/multi-os/#Python-example-(unsupported-languages)
