### ISSUE TITLE
flatiter object behavior

### ISSUE THREAD

**Issue by godaygo** [numpy/numpy#8406]
The [documentation](https://docs.scipy.org/doc/numpy/reference/generated/numpy.flatiter.html) about flatiter object says that:
1. It allows iterating over the array as if it were a 1-D array, either in a for-loop or by calling its next method.
2. The iterator can also be indexed using basic slicing or advanced indexing.  

And there is nothing said about some restrictions. In [manual](https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html#flat-iterator-indexing) I found: 

> This iterator object can also be indexed using basic slicing or advanced indexing as long as the selection object is not a tuple. This should be clear from the fact that x.flat is a 1-dimensional view.

So it seems to me that there is some inconsistency in behavior:
```python
 In[1]: arr = np.arange(10)
 In[2]: arr[1, 2]
Out[2]: IndexError: too many indices for array      
```
but for flatiter, I get an Exception that makes no sense for me:
```python
 In[3]: arr.flat[1, 2]
Out[3]: IndexError: unsupported iterator index
```
Also for 1D array this code is valid:
```python
 In[4]: arr[(1, 2),]
Out[4]: array([1, 2])
```
but for flatiter I again get this incomprehensible error:
```python
 In[4]: arr.flat[(1, 2),]
Out[4]: IndexError: unsupported iterator index
```
Is it the implementation choice?

-----
And for some other stupid attempts array raises some meaningful Exception:
```python
 In[5]: arr[{1,  2}]
Out[5]: IndexError: only integers, slices (`:`), ellipsis (`...`), 
        numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```
but flatiter says something like *"I'm Groot"*
```python
 In[6]: arr.flat[{1, 2}]
Out[6]: IndexError: unsupported iterator index
```

**Comment by seberg** [comment]
Well as you mentioned, apparently the flat iterator does not support multi dimensional indices (meaning tuples), so that `arr.flat[whatever,]` or `arr.flat[(1,)]` is all rejected based on the "no-tuples" rule. Sure, you could allow tuples with exactly one element in principle, but it seams mostly only that indexing has a nicer error reporting?

**Comment by godaygo** [comment]
@seberg I want to say, that if `arr[(1, 2),]` is valid, why arr.flat[(1, 2),] is not? Really, it's silly issue, only some for some pedantic consistency. But, if there is a plan to deprecate `list` as indices, this case matters. 
Also one more odd thing, I get segfault with `arr.flat[()]= number`.

**Comment by seberg** [comment]
Yeah, I agree, it would be correct to allow tuples with a single item (and just extract the item) for the flat iterator, the segfault is bad of course. Just thought that it does say "as long as the selection object is not a tuple", which describes all that you are saying in some case.

**Comment by mattip** [comment]
All these are now fixed. Closing.
```
>>> arr = np.arange(10)
>>> arr[1, 2]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
>>> arr.flat[1, 2]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: too many indices for flat iterator: flat iterator is 1-dimensional, but 2 were indexed
>>> arr[(1, 2),]
array([1, 2])
>>> arr.flat[(1, 2),]
array([1, 2])
>>> arr.flat[()]= 12
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: Assigning to a flat iterator with a 0-D index is not supported
>>> 

```
