### ISSUE TITLE
np.array_repr fails on np.matrix objects

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#8442]
Cause of #5875:

```python
>>> np.array_repr(np.eye(2).view(np.matrix))
Traceback (most recent call last):
  File "<pyshell#52>", line 1, in <module>
    np.array_repr(np.matrix(np.eye(2)))
  File "C:\Program Files\Python 3.5\lib\site-packages\numpy\core\numeric.py", line 1807, in array_repr
    ', ', "array(")
  File "C:\Program Files\Python 3.5\lib\site-packages\numpy\core\arrayprint.py", line 447, in array2string
    separator, prefix, formatter=formatter)
  File "C:\Program Files\Python 3.5\lib\site-packages\numpy\core\arrayprint.py", line 325, in _array2string
    _summaryEdgeItems, summary_insert)[:-1]
  File "C:\Program Files\Python 3.5\lib\site-packages\numpy\core\arrayprint.py", line 519, in _formatArray
    summary_insert)
  File "C:\Program Files\Python 3.5\lib\site-packages\numpy\core\arrayprint.py", line 496, in _formatArray
    word = format_function(a[-1])
  File "C:\Program Files\Python 3.5\lib\site-packages\numpy\core\arrayprint.py", line 598, in __call__
    if isnan(x):
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

Spot the `x[i].shape == x.shape[1:]` fallacy...

**Comment by charris** [comment]
At some point we should deprecate matrices and be done with them. After all, the most likely users are newbies and they should be encouraged to use Python 3.5 and later now that there is the `@` operator.

**Comment by njsmith** [comment]
We had consensus way-back-when to at least add a big warning to the docs, though I don't think it ever happened.

At this point we might well be able to add an actual `DeprecationWarning`, though I don't think we can set a schedule for removing them. Maybe we should try.

**Comment by eric-wieser** [comment]
> At some point we should deprecate matrices and be done with them.

After yet another matrix corner case, I had an angry search of issues in the hope that there was one titled "Finally deprecate np.matrix`

**Comment by eric-wieser** [comment]
Linked issue can probably be closed in favor of this one, anyway

**Comment by njsmith** [comment]
Ugh, @rgommers is right, I forgot about `scipy.sparse`.
