### ISSUE TITLE
Getting ValueError while building development setup in windows 10

### ISSUE THREAD

**Issue by rishikksh20** [numpy/numpy#8485]
After cloning the repo in local system
``` 
git clone https://github.com/numpy/numpy.git
```
Creating virtual environment in Anaconda with configuration:
```
Python:                3.5.2
OS:                      Windows 10 pro
OpenBlas:            OpenBLAS-v0.2.14-Win64-int32
MingW :              mingw-w64-5.4.0
cython :               0.25.2
libpython:            2.0
setuptools:           27.2.0
vs2015_runtime : 14.0.25123

``` 
Running following command : 
```
(C:\Anaconda3\envs\numpy-dev) C:\Open_Source\PYTHON\numpy>python setup.py build --fcompiler=gnu95
```

**Log**:
```
Running from numpy source directory.
Cythonizing sources
numpy/random\mtrand\randint_helpers.pxi.in has not changed
numpy/random\mtrand\mtrand.pyx has not changed
blas_opt_info:
blas_mkl_info:
  libraries mkl_rt not found in ['C:\\Anaconda3\\envs\\numpy-dev\\lib', 'C:\\', 'C:\\Anaconda3\\envs\\numpy-dev\\libs']
  NOT AVAILABLE

blis_info:
  libraries blis not found in ['C:\\Anaconda3\\envs\\numpy-dev\\lib', 'C:\\', 'C:\\Anaconda3\\envs\\numpy-dev\\libs']
  NOT AVAILABLE

openblas_info:
  FOUND:
    libraries = ['openblas', 'openblas']
    library_dirs = ['C:\\toolkits\\OpenBLAS-v0.2.14-Win64-int32\\lib']
    define_macros = [('HAVE_CBLAS', None)]
    language = c
    runtime_library_dirs = ['C:\\toolkits\\OpenBLAS-v0.2.14-Win64-int32\\lib']

  FOUND:
    libraries = ['openblas', 'openblas']
    library_dirs = ['C:\\toolkits\\OpenBLAS-v0.2.14-Win64-int32\\lib']
    define_macros = [('HAVE_CBLAS', None)]
    language = c
    runtime_library_dirs = ['C:\\toolkits\\OpenBLAS-v0.2.14-Win64-int32\\lib']

F2PY Version 2
lapack_opt_info:
lapack_mkl_info:
  libraries mkl_rt not found in ['C:\\Anaconda3\\envs\\numpy-dev\\lib', 'C:\\', 'C:\\Anaconda3\\envs\\numpy-dev\\libs']
  NOT AVAILABLE

openblas_lapack_info:
No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
customize MSVCCompiler
creating C:\Users\RISHIK~1\AppData\Local\Temp\tmpcyk46mpo\Users
creating C:\Users\RISHIK~1\AppData\Local\Temp\tmpcyk46mpo\Users\RISHIK~1
creating C:\Users\RISHIK~1\AppData\Local\Temp\tmpcyk46mpo\Users\RISHIK~1\AppData
creating C:\Users\RISHIK~1\AppData\Local\Temp\tmpcyk46mpo\Users\RISHIK~1\AppData\Local
creating C:\Users\RISHIK~1\AppData\Local\Temp\tmpcyk46mpo\Users\RISHIK~1\AppData\Local\Temp
creating C:\Users\RISHIK~1\AppData\Local\Temp\tmpcyk46mpo\Users\RISHIK~1\AppData\Local\Temp\tmpcyk46mpo
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -I"C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt" /TcC:\Users\RISHIK~1\AppData\Local\Temp\tmpcyk46mpo\source.c /FoC:\Users\RISHIK~1\AppData\Local\Temp\tmpcyk46mpo\Users\RISHIK~1\AppData\Local\Temp\tmpcyk46mpo\source.obj
Found executable C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\cl.exe
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\link.exe /nologo /INCREMENTAL:NO /LTCG /MANIFEST:EMBED,ID=1 /LIBPATH:C:\toolkits\OpenBLAS-v0.2.14-Win64-int32\lib /LIBPATH:"C:\Program Files (x86)\Windows Kits\10\Lib\10.0.10240.0\ucrt\x64" /LIBPATH:"C:\Program Files (x86)\Windows Kits\10\Lib\10.0.10240.0\um\x64" openblas.lib C:\Users\RISHIK~1\AppData\Local\Temp\tmpcyk46mpo\Users\RISHIK~1\AppData\Local\Temp\tmpcyk46mpo\source.obj /OUT:C:\Users\RISHIK~1\AppData\Local\Temp\tmpcyk46mpo\a.out.exe
Found executable C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\link.exe
LINK : fatal error LNK1181: cannot open input file 'openblas.lib'
  NOT AVAILABLE

atlas_3_10_threads_info:
Setting PTATLAS=ATLAS
  libraries tatlas,tatlas not found in C:\Anaconda3\envs\numpy-dev\lib
  libraries lapack_atlas not found in C:\Anaconda3\envs\numpy-dev\lib
  libraries tatlas,tatlas not found in C:\
  libraries lapack_atlas not found in C:\
  libraries tatlas,tatlas not found in C:\Anaconda3\envs\numpy-dev\libs
  libraries lapack_atlas not found in C:\Anaconda3\envs\numpy-dev\libs
<class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
  NOT AVAILABLE

atlas_3_10_info:
  libraries satlas,satlas not found in C:\Anaconda3\envs\numpy-dev\lib
  libraries lapack_atlas not found in C:\Anaconda3\envs\numpy-dev\lib
  libraries satlas,satlas not found in C:\
  libraries lapack_atlas not found in C:\
  libraries satlas,satlas not found in C:\Anaconda3\envs\numpy-dev\libs
  libraries lapack_atlas not found in C:\Anaconda3\envs\numpy-dev\libs
<class 'numpy.distutils.system_info.atlas_3_10_info'>
  NOT AVAILABLE

atlas_threads_info:
Setting PTATLAS=ATLAS
  libraries ptf77blas,ptcblas,atlas not found in C:\Anaconda3\envs\numpy-dev\lib
  libraries lapack_atlas not found in C:\Anaconda3\envs\numpy-dev\lib
  libraries ptf77blas,ptcblas,atlas not found in C:\
  libraries lapack_atlas not found in C:\
  libraries ptf77blas,ptcblas,atlas not found in C:\Anaconda3\envs\numpy-dev\libs
  libraries lapack_atlas not found in C:\Anaconda3\envs\numpy-dev\libs
<class 'numpy.distutils.system_info.atlas_threads_info'>
  NOT AVAILABLE

atlas_info:
  libraries f77blas,cblas,atlas not found in C:\Anaconda3\envs\numpy-dev\lib
  libraries lapack_atlas not found in C:\Anaconda3\envs\numpy-dev\lib
  libraries f77blas,cblas,atlas not found in C:\
  libraries lapack_atlas not found in C:\
  libraries f77blas,cblas,atlas not found in C:\Anaconda3\envs\numpy-dev\libs
  libraries lapack_atlas not found in C:\Anaconda3\envs\numpy-dev\libs
<class 'numpy.distutils.system_info.atlas_info'>
  NOT AVAILABLE

C:\Open_Source\PYTHON\numpy\numpy\distutils\system_info.py:572: UserWarning:
    Atlas (http://math-atlas.sourceforge.net/) libraries not found.
    Directories to search for the libraries can be specified in the
    numpy/distutils/site.cfg file (section [atlas]) or by setting
    the ATLAS environment variable.
  self.calc_info()
lapack_info:
  libraries lapack not found in ['C:\\Anaconda3\\envs\\numpy-dev\\lib', 'C:\\', 'C:\\Anaconda3\\envs\\numpy-dev\\libs']
  NOT AVAILABLE

C:\Open_Source\PYTHON\numpy\numpy\distutils\system_info.py:572: UserWarning:
    Lapack (http://www.netlib.org/lapack/) libraries not found.
    Directories to search for the libraries can be specified in the
    numpy/distutils/site.cfg file (section [lapack]) or by setting
    the LAPACK environment variable.
  self.calc_info()
lapack_src_info:
  NOT AVAILABLE

C:\Open_Source\PYTHON\numpy\numpy\distutils\system_info.py:572: UserWarning:
    Lapack (http://www.netlib.org/lapack/) sources not found.
    Directories to search for the sources can be specified in the
    numpy/distutils/site.cfg file (section [lapack_src]) or by setting
    the LAPACK_SRC environment variable.
  self.calc_info()
  NOT AVAILABLE

C:\Anaconda3\envs\numpy-dev\lib\distutils\dist.py:261: UserWarning: Unknown distribution option: 'define_macros'
  warnings.warn(msg)
running build
running config_cc
unifing config_cc, config, build_clib, build_ext, build commands --compiler options
running config_fc
unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
running build_src
build_src
building py_modules sources
building library "npymath" sources
Looking for python35.dll
customize Gnu95FCompiler
Found executable C:\toolkits\mingw-w64-5.4.0\mingw64\bin\gfortran.exe
Found executable C:\toolkits\mingw-w64-5.4.0\mingw64\bin\gfortran.exe
customize Gnu95FCompiler using config
Traceback (most recent call last):
  File "setup.py", line 391, in <module>
    setup_package()
  File "setup.py", line 383, in setup_package
    setup(**metadata)
  File "C:\Open_Source\PYTHON\numpy\numpy\distutils\core.py", line 169, in setup
    return old_setup(**new_attr)
  File "C:\Anaconda3\envs\numpy-dev\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Anaconda3\envs\numpy-dev\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Anaconda3\envs\numpy-dev\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Open_Source\PYTHON\numpy\numpy\distutils\command\build.py", line 47, in run
    old_build.run(self)
  File "C:\Anaconda3\envs\numpy-dev\lib\distutils\command\build.py", line 135, in run
    self.run_command(cmd_name)
  File "C:\Anaconda3\envs\numpy-dev\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Anaconda3\envs\numpy-dev\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Open_Source\PYTHON\numpy\numpy\distutils\command\build_src.py", line 148, in run
    self.build_sources()
  File "C:\Open_Source\PYTHON\numpy\numpy\distutils\command\build_src.py", line 159, in build_sources
    self.build_library_sources(*libname_info)
  File "C:\Open_Source\PYTHON\numpy\numpy\distutils\command\build_src.py", line 294, in build_library_sources
    sources = self.generate_sources(sources, (lib_name, build_info))
  File "C:\Open_Source\PYTHON\numpy\numpy\distutils\command\build_src.py", line 377, in generate_sources
    source = func(extension, build_dir)
  File "numpy\core\setup.py", line 663, in get_mathlib_info
    st = config_cmd.try_link('int main(void) { return 0;}')
  File "C:\Anaconda3\envs\numpy-dev\lib\distutils\command\config.py", line 246, in try_link
    libraries, library_dirs, lang)
  File "C:\Open_Source\PYTHON\numpy\numpy\distutils\command\config.py", line 152, in _link
    generate_manifest(self)
  File "C:\Open_Source\PYTHON\numpy\numpy\distutils\mingw32ccompiler.py", line 593, in generate_manifest
    check_embedded_msvcr_match_linked(msver)
  File "C:\Open_Source\PYTHON\numpy\numpy\distutils\mingw32ccompiler.py", line 572, in check_embedded_msvcr_match_linked
    "(%d)" % (int(msver), maj))
ValueError: Discrepancy between linked msvcr (14) and the one about to be embedded (140)
```
Basically I am trying to create a numpy development environment in my PC. So, I follow the instruction as per scipy guidelines here: 
https://docs.scipy.org/doc/numpy-dev/user/building.html#basic-installation

**Comment by rgommers** [comment]
You cannot use MinGW with Python 3.5 or up, it doesn't support the new MSVC runtime.

If you just want to build numpy, then use the free (or pro) MSVC 2015. If you also need to compile Fortran, then either pay $$ for Intel Fortran to use with MSVC, or go back to Python 3.4 and use MingwPy or mingw-w64.
