### ISSUE TITLE
Crash in packbits(..., axis=1)

### ISSUE THREAD

**Issue by pv** [numpy/numpy#8637]
This script crashes in current master (86bf869ef):
```
import numpy as np
x = np.ones((200, 1000), dtype=bool)
np.packbits(x, axis=1)
```
Seems to have been introduced in d25e7332ab1579aa71  gh-8326

Backtrace (crashes elsewhere, probably memory corruption):
```
*** Error in `/usr/bin/python': double free or corruption (!prev): 0x0000555555c21650 ***
(gdb) bt
#0  0x00007ffff6d3891f in raise () from /lib64/libc.so.6
#1  0x00007ffff6d3a51a in abort () from /lib64/libc.so.6
#2  0x00007ffff6d7c200 in __libc_message () from /lib64/libc.so.6
#3  0x00007ffff6d8588a in _int_free () from /lib64/libc.so.6
#4  0x00007ffff6d892bc in free () from /lib64/libc.so.6
#5  0x00007fffedd39b9c in PyDataMem_FREE (ptr=0x555555c21650) at numpy/core/src/multiarray/alloc.c:213
#6  0x00007fffedd39891 in _npy_free_cache (p=0x555555c21650, nelem=25000, msz=1024, cache=0x7fffee16cc00 <datacache>, dealloc=0x7fffedd39b84 <PyDataMem_FREE>)
    at numpy/core/src/multiarray/alloc.c:59
#7  0x00007fffedd3999f in npy_free_cache (p=0x555555c21650, sz=25000) at numpy/core/src/multiarray/alloc.c:94
#8  0x00007fffedd3ad0d in array_dealloc (self=0x7fffee3944e0) at numpy/core/src/multiarray/arrayobject.c:425
#9  0x00007ffff7add09f in PyEval_EvalFrameEx () from /lib64/libpython2.7.so.1.0
#10 0x00007ffff7addadc in PyEval_EvalCodeEx () from /lib64/libpython2.7.so.1.0
...
```

**Comment by juliantaylor** [comment]
hm a change added for readability later added an off by one error ...
