### ISSUE TITLE
`test_warning_calls` error on Python 3.6

### ISSUE THREAD

**Issue by matthew-brett** [numpy/numpy#8687]
As of today, the daily numpy wheel builds show the following error on master for all Python 3.6 builds:

```
======================================================================
ERROR: test_warnings.test_warning_calls
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/venv/lib/python3.6/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/venv/lib/python3.6/site-packages/numpy/tests/test_warnings.py", line 81, in test_warning_calls
    tree = ast.parse(file.read())
  File "/opt/cp36m/lib/python3.6/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1675
SyntaxError: invalid escape sequence \m
```

https://travis-ci.org/MacPython/numpy-wheels/builds/204888912

This is testing commit 5f5ccecbf .  I see that the usual travis-ci builds tested the same commit without error : https://travis-ci.org/numpy/numpy/builds/204805650 .  Any thoughts?

**Comment by charris** [comment]
Indeed, there are two new instances
```
file:  numpy/core/code_generators/genapi.py
line:  472 :  invalid escape sequence \d

file:  numpy/lib/function_base.py
line:  1675 :  invalid escape sequence \m
```
I need to add that script to a test...
