### ISSUE TITLE
import numpy error: undefined symbol: zgelsd_

### ISSUE THREAD

**Issue by MichaelLiang12** [numpy/numpy#8697]
**System info: ubuntu 14.04, python3.4, numpy1.11.3**

**I installed numpy using sudo apt-get install python3-numpy, but when I try to import numpy, it went wrong as follows:**

import numpy Traceback (most recent call last):

File "", line 1, in

File "/usr/local/lib/python3.4/dist-packages/numpy/init.py", line 142, in from . import add_newdocs

File "/usr/local/lib/python3.4/dist-packages/numpy/add_newdocs.py", line 13, in from numpy.lib import add_newdoc

File "/usr/local/lib/python3.4/dist-packages/numpy/lib/init.py", line 18, in from .polynomial import *

File "/usr/local/lib/python3.4/dist-packages/numpy/lib/polynomial.py", line 20, in from numpy.linalg import eigvals, lstsq, inv

File "/usr/local/lib/python3.4/dist-packages/numpy/linalg/init.py", line 51, in from .linalg import *

File "/usr/local/lib/python3.4/dist-packages/numpy/linalg/linalg.py", line 29, in from numpy.linalg import lapack_lite, _umath_linalg

**ImportError: /usr/local/lib/python3.4/dist-packages/numpy/linalg/lapack_lite.cpython-34m.so: undefined symbol: zgelsd_**

What's wrong with my installation?

**Comment by juliantaylor** [comment]
you are using a broken non apt installation, see the `/usr/local/` in the path
the package is located in `/usr/lib`
delete your local installation and the packaged one should work.

**Comment by MichaelLiang12** [comment]
Thank you, your answer has solve my problem on Python3.4. However, I tried to install **python3.5** this morning. After installation, when I tried to **import numpy**. It has a different traceback as follows:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/numpy/__init__.py", line 153, in <module>
    from . import add_newdocs
  File "/usr/lib/python3/dist-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/usr/lib/python3/dist-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/usr/lib/python3/dist-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/usr/lib/python3/dist-packages/numpy/core/__init__.py", line 6, in <module>
    from . import multiarray
**ImportError: cannot import name 'multiarray'**

Could help me solve this problem? Thank you!

**Comment by MichaelLiang12** [comment]
What's more, when I was install **tensorflow** on Python3.4, it **updates numpy to 1.12.0 automatically**. Then the same problem "**undefined symbol: zgelsd_**' came again. What's wrong with my Python?

**Comment by MichaelLiang12** [comment]
@juliantaylor  I still cannot fix numpy. Could you give me more advice. See  [https://github.com/numpy/numpy/issues/8697](url) for more detail

**Comment by juliantaylor** [comment]
installing liblapack-dev before installing numpy might help
or `pip install --only-binary wheel numpy` to use a prebuilt binary.

**Comment by eric-wieser** [comment]
Shouldn't need liblapack given we bundle lapack_lite

**Comment by MichaelLiang12** [comment]
@juliantaylor Thank you, any way. It didn't solve my problem. At last, I turned to install Anaconda and succeeded in installing tensorflow.
