### ISSUE TITLE
NaN should become NaT when assigned to datetime64

### ISSUE THREAD

**Issue by gerritholl** [numpy/numpy#8780]
When an array has dtype `datetime64`, setting to `NaN` should convert to `NaT`.  Currently, it fails with ValueError:

```
In [49]: x = numpy.zeros(dtype="M8[s]", shape=5)
In [51]: x[2] = numpy.nan
…
ValueError: Could not convert object to NumPy datetime
```

The instruction `= numpy.nan` is not ambiguous in any way.  When setting all the values of a structured dtype with floats and datetime types to nan it is much easier if we don't need to separately handle the case for nat.

**Comment by charris** [comment]
That sounds correct to me. How are floats converted in general?

**Comment by tylerjereddy** [comment]
@charris They aren't:

The following attempts also fail with the same `ValueError` reported above:

```Python
x[2] = 2.5
x = np.array([1.2, 3.5], dtype='M8[s]')
# also for generic case:
x = np.array([1.2, 3.5], dtype=np.datetime64)
```

**Comment by tylerjereddy** [comment]
So, I assume this is a request for enhanced NaN / NaT handling, not trying to sensibly handle arbitrary float input to `np.datetime64`. Integers are handled by adding to the unix epoch it seems.

**Comment by eric-wieser** [comment]
Taking a step back here - is there any reason why we _should_ support using `np.nan` here, given that in general we don't support floats?

**Comment by tylerjereddy** [comment]
I don't have a strong view here -- just trying to chip away at open issues related to dtype things; do feel free to propose that we simply go with wontfix and close my PR or raise a different exception if you prefer.

**Comment by eric-wieser** [comment]
Worth noting the assignment works just fine if you use custom casting rules
```python
In [4]: x = np.zeros(dtype="M8[s]", shape=5)

In [5]: x[2] = np.nan
Traceback (most recent call last):
  File "<ipython-input-5-6c5795fab603>", line 1, in <module>
    x[2] = np.nan
ValueError: Could not convert object to NumPy datetime


In [6]: np.copyto(x[2,...], np.nan)
Traceback (most recent call last):
  File "<ipython-input-6-317f333b4fc9>", line 1, in <module>
    np.copyto(x[2,...], np.nan)
TypeError: Cannot cast scalar from dtype('float64') to dtype('<M8[s]') according to the rule 'same_kind'


In [7]: np.copyto(x[2,...], np.nan, casting='unsafe')

In [8]: x
Out[8]:
array(['1970-01-01T00:00:00', '1970-01-01T00:00:00',
                       'NaT', '1970-01-01T00:00:00',
       '1970-01-01T00:00:00'], dtype='datetime64[s]')
```

It's a shame the error message isn't better.

**Comment by tylerjereddy** [comment]
There's a [comment suggesting the correct behavior](https://github.com/numpy/numpy/pull/11851#issuecomment-429646796) in the linked PR I've now closed, and the title of this issue is now apparently the behavior we don't want to allow.

If there's consensus on that, someone is free to make a new PR with the error handling / behavior enforcement when trying to do this kind of assignment.

**Comment by hameerabbasi** [comment]
I agree that we shouldn't have more cases of value-based casting.
