### ISSUE TITLE
AssertionError: Not equal to tolerance rtol=0.001, atol=1e-06

### ISSUE THREAD

**Issue by sandipmgiri** [numpy/numpy#8908]
I'm getting the following error when trying to run the bazel tests in Tensorflow (on ubuntu-ppc64le:16.04 as well as on RHEL-ppc64le-7.3):

```
$ bazel test tensorflowcompilertestsbinary_ops_test_cpu 



`FAIL: testFloatOps (__main__.BinaryOpsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/68a62076e91007a7908bc42a32e4cff9/execroot/tensorflow/bazel-out/local-opt/bin/tensorflow/compiler/tests/binary_ops_test_cpu.runfiles/org_tensorflow/tensorflow/compiler/tests/binary_ops_test.py", line 60, in testFloatOps
    [1.5, -1.5, -0.2142857, 2, float("inf")], dtype=dtype))
  File "/root/.cache/bazel/_bazel_root/68a62076e91007a7908bc42a32e4cff9/execroot/tensorflow/bazel-out/local-opt/bin/tensorflow/compiler/tests/binary_ops_test_cpu.runfiles/org_tensorflow/tensorflow/compiler/tests/binary_ops_test.py", line 45, in _testBinary
    equality_test(result, expected, rtol=1e-3)
  File "/root/.cache/bazel/_bazel_root/68a62076e91007a7908bc42a32e4cff9/execroot/tensorflow/bazel-out/local-opt/bin/tensorflow/compiler/tests/binary_ops_test_cpu.runfiles/org_tensorflow/tensorflow/python/framework/test_util.py", line 485, in assertAllClose
    np.testing.assert_allclose(a, b, rtol=rtol, atol=atol)
  File "/usr/lib64/python2.7/site-packages/numpy/testing/utils.py", line 1411, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "/usr/lib64/python2.7/site-packages/numpy/testing/utils.py", line 754, in assert_array_compare
    chk_same_position(x_isnan, y_isnan, hasval='nan')
  File "/usr/lib64/python2.7/site-packages/numpy/testing/utils.py", line 735, in chk_same_position
    raise AssertionError(msg)
AssertionError:
Not equal to tolerance rtol=0.001, atol=1e-06

x and y nan location mismatch:
 x: array([ 1.5     , -1.5     , -0.214286,  2.      ,       nan], dtype=float32)
 y: array([ 1.5     , -1.5     , -0.214286,  2.      ,       inf], dtype=float32)

----------------------------------------------------------------------
Ran 5 tests in 0.998s

FAILED (failures=1)
not close where =  (array([4]),)
not close lhs =  [ nan]
not close rhs =  [ inf]
not close dif =  [ nan]
not close tol =  [ inf]
dtype = float32, shape = (5,)`
```

Any solution/suggestion ?

**Comment by MSeifert04** [comment]
Is this a numpy or tensorflow problem?

**Comment by sandipmgiri** [comment]
Not sure but looks like this is a numpy related issue.

Also mentioned here - https://github.com/ContinuumIO/anaconda-issues/issues/658
(This is really something the numpy developers have to fix)

Thanks!

**Comment by eric-wieser** [comment]
I see nothing here that points to a `numpy` bug right now - the entire relevent stack trace is within tensorflow code.

Can you elaborate on what this test is doing? Can you produce a testcase that causes it without importing tensorflow?

**Comment by eric-wieser** [comment]
Seems like the minimal testcase is:
```python
from tensorflow.python.ops import gen_math_ops

def test_op(f):
    dtype = np.float32
    a = np.array([3, 3, -1.5, -8, 44], dtype=dtype)
    b = np.array([2, -2, 7, -4, 0], dtype=dtype)
    actual = f(a, b)
    expected = np.array([1.5, -1.5, -0.2142857, 2, float("inf")], dtype=dtype))
    assert_equal(actual, expected)

test_op(np.divide)
test_op(gen_math_ops._real_div)
```

Does this fail? Do both tests fail, or just the second one?

**Comment by njsmith** [comment]
I don't see any relationship between this issue and https://github.com/ContinuumIO/anaconda-issues/issues/658. My guess is that this is a tensorflow bug triggered by running on ppc64le, which upstream probably doesn't test on. But Eric's questions are good ones.

**Comment by sandipmgiri** [comment]
Hi @eric-wieser, sorry for the delay. Both the tests are failing for me. Thanks!

**Comment by eric-wieser** [comment]
@sandipmgiri: Can you post the failure message for both cases?

**Comment by sandipmgiri** [comment]
```
`>>> np.__version__
'1.12.1'
`
```

```
`>>> np.array([44], np.float32) / np.array([0], np.float32)
array([ inf], dtype=float32)
`
```

I don't think there is any difference in failures for both the tests, PFA.  
[gen_math_ops._real_div.txt](https://github.com/numpy/numpy/files/919579/gen_math_ops._real_div.txt)
[np.divide.txt](https://github.com/numpy/numpy/files/919580/np.divide.txt)

**Comment by eric-wieser** [comment]
Wait, why is there a tensorflow traceback in a standalone numpy test I gave you?

**Comment by sandipmgiri** [comment]
Initially I was getting the following error in your code :

```
bash-4.2# python test.py

test.py:14: RuntimeWarning: divide by zero encountered in divide
  actual = f(a, b)
Traceback (most recent call last):
  File "test.py", line 18, in <module>
    test_op(np.divide)
  File "test.py", line 16, in test_op
    assert_equal(actual, expected)
NameError: global name 'assert_equal' is not defined
```
`
So I made minor changes  as below :

```
import numpy as np
from tensorflow.python.ops import gen_math_ops

def test_op(f):
    dtype = np.float32
    a = np.array([3, 3, -1.5, -8, 44], dtype=dtype)
    b = np.array([2, -2, 7, -4, 0], dtype=dtype)
    actual = f(a, b)
    expected = np.array([1.5, -1.5, -0.2142857, 2, float("inf")], dtype=dtype)
    np.testing.assert_equal(actual, expected)

test_op(np.divide)
test_op(gen_math_ops._real_div)
```

Output for test_op(np.divide) :

```
bash-4.2# python test.py

test.py:12: RuntimeWarning: divide by zero encountered in divide
  actual = f(a, b)
Traceback (most recent call last):
  File "test.py", line 16, in <module>
    test_op(np.divide)
  File "test.py", line 14, in test_op
    np.testing.assert_equal(actual, expected)
  File "/usr/lib64/python2.7/site-packages/numpy/testing/utils.py", line 361, in assert_equal
    return assert_array_equal(actual, desired, err_msg, verbose)
  File "/usr/lib64/python2.7/site-packages/numpy/testing/utils.py", line 871, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/usr/lib64/python2.7/site-packages/numpy/testing/utils.py", line 796, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Arrays are not equal

(mismatch 25.0%)
 x: array([ 1.5     , -1.5     , -0.214286,  2.      ,       inf], dtype=float32)
 y: array([ 1.5     , -1.5     , -0.214286,  2.      ,       inf], dtype=float32)
```

And for test_op(gen_math_ops._real_div) :

```
bash-4.2# python test.py
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    test_op(gen_math_ops._real_div)
  File "test.py", line 11, in test_op
    np.testing.assert_equal(actual, expected)
  File "/usr/lib64/python2.7/site-packages/numpy/testing/utils.py", line 361, in assert_equal
    return assert_array_equal(actual, desired, err_msg, verbose)
  File "/usr/lib64/python2.7/site-packages/numpy/testing/utils.py", line 871, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/usr/lib64/python2.7/site-packages/numpy/testing/utils.py", line 796, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Arrays are not equal

(mismatch 100.0%)
 x: array(<tf.Tensor 'RealDiv:0' shape=(5,) dtype=float32>, dtype=object)
 y: array([ 1.5     , -1.5     , -0.214286,  2.      ,       inf], dtype=float32)
```

**Comment by eric-wieser** [comment]
Are you sure that first output is correct? Those arrays look the same to me - also, 25% is a strange fraction of 5 elements.

**Comment by sandipmgiri** [comment]
Yes, I am sure @eric-wieser that output is correct.

**Comment by eric-wieser** [comment]
Ah, that should have been `assert_allclose`.

Either way, it looks like:
* that test case doesn't test the right thing in tensorflow
* there is no bug in numpy

**Comment by sandipmgiri** [comment]
Closing this issue as there is no bug in numpy.
