### ISSUE TITLE
os.path.join failure during installation

### ISSUE THREAD

**Issue by adamjstewart** [numpy/numpy#9289]
I'm trying to install numpy from source and I'm hitting a weird error message that I've never seen before:
```
running install_clib
customize UnixCCompiler
Traceback (most recent call last):
  File "setup.py", line 391, in <module>
    setup_package()
  File "setup.py", line 383, in setup_package
    setup(**metadata)
  File "/tmp/ajstewart/spack-stage/spack-stage-JHCgYI/numpy-1.12.1/numpy/distutils/core.py", line 169, in setup
    return old_setup(**new_attr)
  File "/blues/gpfs/home/ajstewart/spack/opt/spack/linux-centos7-x86_64/gcc-7.1.0/python-2.7.13-qtrdup642rbar2ju33q7tffswry7hcun/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/blues/gpfs/home/ajstewart/spack/opt/spack/linux-centos7-x86_64/gcc-7.1.0/python-2.7.13-qtrdup642rbar2ju33q7tffswry7hcun/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/blues/gpfs/home/ajstewart/spack/opt/spack/linux-centos7-x86_64/gcc-7.1.0/python-2.7.13-qtrdup642rbar2ju33q7tffswry7hcun/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/tmp/ajstewart/spack-stage/spack-stage-JHCgYI/numpy-1.12.1/numpy/distutils/command/install.py", line 62, in run
    r = self.setuptools_run()
  File "/tmp/ajstewart/spack-stage/spack-stage-JHCgYI/numpy-1.12.1/numpy/distutils/command/install.py", line 36, in setuptools_run
    return distutils_install.run(self)
  File "/blues/gpfs/home/ajstewart/spack/opt/spack/linux-centos7-x86_64/gcc-7.1.0/python-2.7.13-qtrdup642rbar2ju33q7tffswry7hcun/lib/python2.7/distutils/command/install.py", line 575, in run
    self.run_command(cmd_name)
  File "/blues/gpfs/home/ajstewart/spack/opt/spack/linux-centos7-x86_64/gcc-7.1.0/python-2.7.13-qtrdup642rbar2ju33q7tffswry7hcun/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/blues/gpfs/home/ajstewart/spack/opt/spack/linux-centos7-x86_64/gcc-7.1.0/python-2.7.13-qtrdup642rbar2ju33q7tffswry7hcun/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/tmp/ajstewart/spack-stage/spack-stage-JHCgYI/numpy-1.12.1/numpy/distutils/command/install_data.py", line 19, in run
    self.run_command('install_clib')
  File "/blues/gpfs/home/ajstewart/spack/opt/spack/linux-centos7-x86_64/gcc-7.1.0/python-2.7.13-qtrdup642rbar2ju33q7tffswry7hcun/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/blues/gpfs/home/ajstewart/spack/opt/spack/linux-centos7-x86_64/gcc-7.1.0/python-2.7.13-qtrdup642rbar2ju33q7tffswry7hcun/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/tmp/ajstewart/spack-stage/spack-stage-JHCgYI/numpy-1.12.1/numpy/distutils/command/install_clib.py", line 34, in run
    source = os.path.join(build_dir, name)
  File "/blues/gpfs/home/ajstewart/spack/opt/spack/linux-centos7-x86_64/gcc-7.1.0/python-2.7.13-qtrdup642rbar2ju33q7tffswry7hcun/lib/python2.7/posixpath.py", line 70, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'
```
Has anyone ever seen this before?

**Comment by adamjstewart** [comment]
I think I figured out the problem. I was trying to run:
```
$ python setup.py build
$ python setup.py install --skip-build
```
Apparently `--skip-build` does not do what I thought it does...

**Comment by adamjstewart** [comment]
Or maybe `--skip-build` does work the way I think and for some reason it's only broken for numpy? I'm not sure.
