### ISSUE TITLE
Symbol not found: __PyTraceMalloc_Track in Python 3.6

### ISSUE THREAD

**Issue by timjstewart** [numpy/numpy#9318]
When I install numpy under Python 3.6 and then try to import numpy, I get a runtime error:

`Symbol not found: __PyTraceMalloc_Track`

**Operating System**

```
  System Version:	OS X 10.10.5 (14F2411)
  Kernel Version:	Darwin 14.5.0
```

**Python Version**

```
$ python --version
Python 3.6.0a0
```
**Brew config output**

```
$ brew config
HOMEBREW_VERSION: 1.2.3
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: ed9942fbd1ec4243f0a92ab8f9b2411c8b1fb091
Last commit: 2 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 477a3e639d68ea9c0bdd8ae8806e4e3d5be56131
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p481
Clang: 7.0 build 700
Git: 2.13.2 => /usr/local/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.26.0/bin/perl
Python: /Users/me/tmp/np/venv/bin/python => /usr/local/Cellar/python3/HEAD/Frameworks/Python.framework/Versions/3.6/bin/python3.6
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.1_1/bin/ruby
Java: 9, 1.8.0_73, 1.8.0_51, 1.8.0_25, 1.6.0_65-b14-468
macOS: 10.10.5-x86_64
Xcode: 7.2.1
CLT: 7.2.0.0.1.1447826929
X11: 2.7.11 => /opt/X11
```

**Terminal output from installing numpy**

```
$ mkdir np
$ cd np
$ python3.6 -m venv venv
$ source venv/bin/activate
$ pip install --upgrade pip
Collecting pip
  Using cached pip-9.0.1-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 7.1.2
    Uninstalling pip-7.1.2:
      Successfully uninstalled pip-7.1.2
Successfully installed pip-9.0.1
$ pip install numpy
Collecting numpy
  Using cached numpy-1.13.0-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Installing collected packages: numpy
Successfully installed numpy-1.13.0
$ python -c 'import numpy'
Traceback (most recent call last):
  File "/Users/me/tmp/np/venv/lib/python3.6/site-packages/numpy/core/__init__.py", line 16, in <module>
    from . import multiarray
ImportError: dlopen(/Users/me/tmp/np/venv/lib/python3.6/site-packages/numpy/core/multiarray.cpython-36m-darwin.so, 2): Symbol not found: __PyTraceMalloc_Track
  Referenced from: /Users/me/tmp/np/venv/lib/python3.6/site-packages/numpy/core/multiarray.cpython-36m-darwin.so
  Expected in: flat namespace
 in /Users/me/tmp/np/venv/lib/python3.6/site-packages/numpy/core/multiarray.cpython-36m-darwin.so

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/me/tmp/np/venv/lib/python3.6/site-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/Users/me/tmp/np/venv/lib/python3.6/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/Users/me/tmp/np/venv/lib/python3.6/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/Users/me/tmp/np/venv/lib/python3.6/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/Users/me/tmp/np/venv/lib/python3.6/site-packages/numpy/core/__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError: 
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: dlopen(/Users/me/tmp/np/venv/lib/python3.6/site-packages/numpy/core/multiarray.cpython-36m-darwin.so, 2): Symbol not found: __PyTraceMalloc_Track
  Referenced from: /Users/me/tmp/np/venv/lib/python3.6/site-packages/numpy/core/multiarray.cpython-36m-darwin.so
  Expected in: flat namespace
 in /Users/me/tmp/np/venv/lib/python3.6/site-packages/numpy/core/multiarray.cpython-36m-darwin.so
```

**Comment by juliantaylor** [comment]
please update your python, you are using an alpha version.

**Comment by timjstewart** [comment]
@juliantaylor thanks for your help!  Running the following fixed my problem:

`brew install python3 --devel`
