### ISSUE TITLE
mkdtemp function is not available on py27/appveyor

### ISSUE THREAD

**Issue by xoviat** [numpy/numpy#9455]
traceback:

```
Replacing crashed slave gw35
[gw36] node down: Traceback (most recent call last):
  File "c:\python27-x64\lib\site-packages\execnet\gateway_base.py", line 1072, in executetask
    do_exec(co, loc)  # noqa
  File "<string>", line 1, in do_exec
  File "<remote exec>", line 180, in <module>
  File "<remote exec>", line 152, in remote_initconfig
  File "c:\python27-x64\lib\site-packages\_pytest\config.py", line 13, in <module>
    import _pytest._code
  File "c:\python27-x64\lib\site-packages\_pytest\_code\__init__.py", line 3, in <module>
    from .code import Code  # noqa
  File "c:\python27-x64\lib\site-packages\_pytest\_code\code.py", line 6, in <module>
    from _pytest.compat import _PY2, _PY3, PY35, safe_str
  File "c:\python27-x64\lib\site-packages\_pytest\compat.py", line 286, in <module>
    from py.io import TextIO as CaptureIO
  File "c:\python27-x64\lib\site-packages\py\_apipkg.py", line 125, in __makeattr
    result = importobj(modpath, attrname)
  File "c:\python27-x64\lib\site-packages\py\_apipkg.py", line 48, in importobj
    module = __import__(modpath, None, None, ['__doc__'])
  File "c:\python27-x64\lib\site-packages\py\_io\capture.py", line 4, in <module>
    import tempfile
  File "c:\python27-x64\lib\tempfile.py", line 32, in <module>
    import io as _io
  File "C:\Python27-x64\lib\site-packages\scipy\io\__init__.py", line 97, in <module>
    from .matlab import loadmat, savemat, whosmat, byteordercodes
  File "C:\Python27-x64\lib\site-packages\scipy\io\matlab\__init__.py", line 13, in <module>
    from .mio import loadmat, savemat, whosmat
  File "C:\Python27-x64\lib\site-packages\scipy\io\matlab\mio.py", line 8, in <module>
    import numpy as np
  File "c:\python27-x64\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import add_newdocs
  File "c:\python27-x64\lib\site-packages\numpy\add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "c:\python27-x64\lib\site-packages\numpy\lib\__init__.py", line 8, in <module>
    from .type_check import *
  File "c:\python27-x64\lib\site-packages\numpy\lib\type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "c:\python27-x64\lib\site-packages\numpy\core\__init__.py", line 74, in <module>
    from numpy.testing.nosetester import _numpy_tester
  File "c:\python27-x64\lib\site-packages\numpy\testing\__init__.py", line 12, in <module>
    from . import decorators as dec
  File "c:\python27-x64\lib\site-packages\numpy\testing\decorators.py", line 20, in <module>
    from .utils import SkipTest, assert_warns
  File "c:\python27-x64\lib\site-packages\numpy\testing\utils.py", line 15, in <module>
    from tempfile import mkdtemp, mkstemp
ImportError: cannot import name mkdtemp
Replacing crashed slave gw36
[gw37] node down: Traceback (most recen
```

I have no idea why this is happening because the function appears in the py27 documentation. It only occurs on py27 and apparently this is not the first time that this issue has been experienced.

**Comment by pv** [comment]
That tempfile import works on linux. Does it work on that specific py27 installation?

**Comment by pv** [comment]
Actually the problem appears to be this:
```
File "c:\python27-x64\lib\tempfile.py", line 32, in <module>
    import io as _io
File "C:\Python27-x64\lib\site-packages\scipy\io\__init__.py", line 97, in <module>
    from .matlab import loadmat, savemat, whosmat, byteordercodes
```
so it's as if the import paths are messed up. If so, this issue is unrelated to numpy.

**Comment by xoviat** [comment]
Good catch.
