### ISSUE TITLE
Fail to install Scipy

### ISSUE THREAD

**Issue by SriramSudharsan** [numpy/numpy#9504]
When i try to install Scipy Package in Visual Studio Virtual Environment, i get the below error, this is after updating Python to 3.6.2 as 3.6.0 was having issues with Numpy packages (raised https://github.com/numpy/numpy/issues/9501 ), not sure how many Packages are not supported for this version.
```
----- Installing 'scipy' -----
Collecting scipy
  Using cached scipy-0.19.1.tar.gz
Installing collected packages: scipy
  Running setup.py install for scipy: started
    Running setup.py install for scipy: finished with status 'error'
    Complete output from command "C:\Users\Sriram Sudharsan\documents\visual studio 2017\Projects\My App\My App\env\Scripts\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\SRIRAM~1\\AppData\\Local\\Temp\\pip-build-85riyz0u\\scipy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\SRIRAM~1\AppData\Local\Temp\pip-ablehnfo-record\install-record.txt --single-version-externally-managed --compile --install-headers "C:\Users\Sriram Sudharsan\documents\visual studio 2017\Projects\My App\My App\env\include\site\python3.6\scipy":
    
    Note: if you need reliable uninstall behavior, then install
    with pip instead of using `setup.py install`:
    
      - `pip install .`       (from a git repo or downloaded source
                               release)
      - `pip install scipy`   (last SciPy release on PyPI)
    
    
    lapack_opt_info:
    lapack_mkl_info:
      libraries mkl_rt not found in ['C:\\Users\\Sriram Sudharsan\\documents\\visual studio 2017\\Projects\\My App\\My App\\env\\lib', 'C:\\']
      NOT AVAILABLE
    
    openblas_lapack_info:
      libraries openblas not found in ['C:\\Users\\Sriram Sudharsan\\documents\\visual studio 2017\\Projects\\My App\\My App\\env\\lib', 'C:\\']
      NOT AVAILABLE
    
    atlas_3_10_threads_info:
    Setting PTATLAS=ATLAS
    C:\Users\Sriram Sudharsan\documents\visual studio 2017\Projects\My App\My App\env\lib\site-packages\numpy\distutils\system_info.py:1051: UserWarning: Specified path C:\projects\numpy-wheels\windows-wheel-builder\atlas-builds\atlas-3.10.1-sse2-32\lib is invalid.
      pre_dirs = system_info.get_paths(self, section, key)
    <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
      NOT AVAILABLE
    
    atlas_3_10_info:
    <class 'numpy.distutils.system_info.atlas_3_10_info'>
      NOT AVAILABLE
    
    atlas_threads_info:
    Setting PTATLAS=ATLAS
    <class 'numpy.distutils.system_info.atlas_threads_info'>
      NOT AVAILABLE
    
    atlas_info:
    <class 'numpy.distutils.system_info.atlas_info'>
      NOT AVAILABLE
    
    C:\Users\Sriram Sudharsan\documents\visual studio 2017\Projects\My App\My App\env\lib\site-packages\numpy\distutils\system_info.py:572: UserWarning:
        Atlas (http://math-atlas.sourceforge.net/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [atlas]) or by setting
        the ATLAS environment variable.
      self.calc_info()
    lapack_info:
      libraries lapack not found in ['C:\\Users\\Sriram Sudharsan\\documents\\visual studio 2017\\Projects\\My App\\My App\\env\\lib', 'C:\\']
      NOT AVAILABLE
    
    C:\Users\Sriram Sudharsan\documents\visual studio 2017\Projects\My App\My App\env\lib\site-packages\numpy\distutils\system_info.py:572: UserWarning:
        Lapack (http://www.netlib.org/lapack/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [lapack]) or by setting
        the LAPACK environment variable.
      self.calc_info()
    lapack_src_info:
      NOT AVAILABLE
    
    C:\Users\Sriram Sudharsan\documents\visual studio 2017\Projects\My App\My App\env\lib\site-packages\numpy\distutils\system_info.py:572: UserWarning:
        Lapack (http://www.netlib.org/lapack/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [lapack_src]) or by setting
        the LAPACK_SRC environment variable.
      self.calc_info()
      NOT AVAILABLE
    
    Running from scipy source directory.
    non-existing path in 'scipy\\integrate': 'quadpack.h'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\SRIRAM~1\AppData\Local\Temp\pip-build-85riyz0u\scipy\setup.py", line 416, in <module>
        setup_package()
      File "C:\Users\SRIRAM~1\AppData\Local\Temp\pip-build-85riyz0u\scipy\setup.py", line 412, in setup_package
        setup(**metadata)
      File "C:\Users\Sriram Sudharsan\documents\visual studio 2017\Projects\My App\My App\env\lib\site-packages\numpy\distutils\core.py", line 135, in setup
        config = configuration()
      File "C:\Users\SRIRAM~1\AppData\Local\Temp\pip-build-85riyz0u\scipy\setup.py", line 336, in configuration
        config.add_subpackage('scipy')
      File "C:\Users\Sriram Sudharsan\documents\visual studio 2017\Projects\My App\My App\env\lib\site-packages\numpy\distutils\misc_util.py", line 1029, in add_subpackage
        caller_level = 2)
      File "C:\Users\Sriram Sudharsan\documents\visual studio 2017\Projects\My App\My App\env\lib\site-packages\numpy\distutils\misc_util.py", line 998, in get_subpackage
        caller_level = caller_level + 1)
      File "C:\Users\Sriram Sudharsan\documents\visual studio 2017\Projects\My App\My App\env\lib\site-packages\numpy\distutils\misc_util.py", line 935, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scipy\setup.py", line 15, in configuration
        config.add_subpackage('linalg')
      File "C:\Users\Sriram Sudharsan\documents\visual studio 2017\Projects\My App\My App\env\lib\site-packages\numpy\distutils\misc_util.py", line 1029, in add_subpackage
        caller_level = 2)
      File "C:\Users\Sriram Sudharsan\documents\visual studio 2017\Projects\My App\My App\env\lib\site-packages\numpy\distutils\misc_util.py", line 998, in get_subpackage
        caller_level = caller_level + 1)
      File "C:\Users\Sriram Sudharsan\documents\visual studio 2017\Projects\My App\My App\env\lib\site-packages\numpy\distutils\misc_util.py", line 935, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scipy\linalg\setup.py", line 20, in configuration
        raise NotFoundError('no lapack/blas resources found')
    numpy.distutils.system_info.NotFoundError: no lapack/blas resources found
    
    ----------------------------------------
Command ""C:\Users\Sriram Sudharsan\documents\visual studio 2017\Projects\My App\My App\env\Scripts\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\SRIRAM~1\\AppData\\Local\\Temp\\pip-build-85riyz0u\\scipy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\SRIRAM~1\AppData\Local\Temp\pip-ablehnfo-record\install-record.txt --single-version-externally-managed --compile --install-headers "C:\Users\Sriram Sudharsan\documents\visual studio 2017\Projects\My App\My App\env\include\site\python3.6\scipy"" failed with error code 1 in C:\Users\SRIRAM~1\AppData\Local\Temp\pip-build-85riyz0u\scipy\
----- Failed to install 'scipy' -----
```

**Comment by SriramSudharsan** [comment]
I tried with Visual Studio pip install scipy from PyPI
![image](https://user-images.githubusercontent.com/30468090/28821089-125a00f0-76ac-11e7-9deb-961de82d0584.png)
