### ISSUE TITLE
Something about np.vectorize

### ISSUE THREAD

**Issue by 631068264** [numpy/numpy#9546]
I use numpy (1.12.0) and Python2.7
```
class GAME_ORIGINAL(BaseStrategy):
    _strategy_name_format = "game_{run_period}_{signal_type}"
    ma_period = [3, 5, 8, 10, 12, 30, 35, 40, 45, 50]

    def __init__(self, bar_table_format, run_period):
        super(GAME_ORIGINAL, self).__init__(bar_table_format, run_period)

    def _run(self, bar):
        ema_func = lambda period: util.indicator.EMA(self.close, period)
        np_ema = np.vectorize(ema_func)
        self.ma_period = np.array(self.ma_period)
        result = np_ema(self.ma_period)
        print result
```

And get an error
```
Traceback (most recent call last):
  File "/Users/wyx/bitcoin_workspace/fibo-strategy/base/strategy.py", line 59, in run
    self._run(bar)
  File "/Users/wyx/bitcoin_workspace/fibo-strategy/strategy/base_strategy.py", line 734, in _run
    result = np_ema(self.ma_period)
  File "/Users/wyx/bitcoin_workspace/fibo-strategy/.env/lib/python2.7/site-packages/numpy/lib/function_base.py", line 2576, in __call__
    return self._vectorize_call(func=func, args=vargs)
  File "/Users/wyx/bitcoin_workspace/fibo-strategy/.env/lib/python2.7/site-packages/numpy/lib/function_base.py", line 2655, in _vectorize_call
    res = array(outputs, copy=False, subok=True, dtype=otypes[0])
ValueError: setting an array element with a sequence.
```

**Comment by 631068264** [comment]
I use `map`  is OK, but I think `np.vectorize` can speed up.

**Comment by ExpHP** [comment]
What does util.indicator.EMA return?  Try `np.vectorize(ema_func, otypes=[object])`.

Per the python sequence protocol, anything with a `__len__` and a `__getitem__` that accepts integers will be regarded as a sequence by numpy unless it knows ahead of time that it is working with an array of objects.

```python3
import numpy as np
class Oops:
  def __len__(self):
    return 1
  def __getitem__(self, i):
    if i == 0: return 1
    else: raise IndexError

np.vectorize((lambda x: Oops()))([1])
```

```
Traceback (most recent call last):
  File "oops.py", line 9, in <module>
    np.vectorize((lambda x: Oops()))([1])
  File "/usr/lib/python3.6/site-packages/numpy/lib/function_base.py", line 2734, in __call__
    return self._vectorize_call(func=func, args=vargs)
  File "/usr/lib/python3.6/site-packages/numpy/lib/function_base.py", line 2813, in _vectorize_call
    res = array(outputs, copy=False, subok=True, dtype=otypes[0])
ValueError: setting an array element with a sequence.
```

---

> I use map is OK, but I think np.vectorize can speed up.

I wouldn't count on it.

`numpy` is for number crunching.  It is not going to speed up the execution of arbitrary python code, and in fact, all of the type checking and conversions it needs to do will tend to make things worse.
