### ISSUE TITLE
TypeError: list indices must be integers, not tuple

### ISSUE THREAD

**Issue by JiankaiSun-SJTU-MVIG-training** [numpy/numpy#9548]
Operating system: Ubuntu 16.04 x64
numpy version: '1.13.1'
python version: Python 2.7.13 |Continuum Analytics, Inc.| (default, Dec 20 2016, 23:09:15) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2

I have a file `run2.py`:
```
import tensorflow as tf
from tensorflow.contrib.distributions import Normal, kl_divergence
import numpy as np
import matplotlib.pyplot as plt
import opensim as osim
import sys
from osim.env import *
from osim.http.client import Client
import argparse
import math

# Command line parameters
parser = argparse.ArgumentParser(description='Train or test neural net motor controller')
parser.add_argument('--train', dest='train', action='store_true', default=True)
parser.add_argument('--test', dest='train', action='store_false', default=True)
parser.add_argument('--steps', dest='steps', action='store', default=10000, type=int)
parser.add_argument('--visualize', dest='visualize', action='store_true', default=False)
parser.add_argument('--model', dest='model', action='store', default="example.h5f")
parser.add_argument('--token', dest='token', action='store', required=False)
args = parser.parse_args()

EP_MAX = 1000
EP_LEN = 200
GAMMA = 0.9
A_LR = 0.0001
C_LR = 0.0002
BATCH = 32
A_UPDATE_STEPS = 10
C_UPDATE_STEPS = 10
METHOD = [
    dict(name='kl_pen', kl_target=0.01, lam=0.5),   # KL penalty
    dict(name='clip', epsilon=0.2),                 # Clipped surrogate objective, find this is better
][1]        # choose the method for optimization


class PPO(object):

    def __init__(self, s_dim, a_dim,):
        self.a_dim = a_dim
        self.s_dim = s_dim
        self.sess = tf.Session()

        self.tfs = tf.placeholder(tf.float32, [None, s_dim], 'state')

        # critic
        with tf.variable_scope('critic'):
            l1 = tf.layers.dense(self.tfs, 100, tf.nn.relu)
            self.v = tf.layers.dense(l1, 1)
            self.tfdc_r = tf.placeholder(tf.float32, [None, 1], 'discounted_r')
            self.advantage = self.tfdc_r - self.v
            self.closs = tf.reduce_mean(tf.square(self.advantage))
            self.ctrain_op = tf.train.AdamOptimizer(C_LR).minimize(self.closs)

        # actor
        pi, pi_params = self._build_anet('pi', trainable=True)
        oldpi, oldpi_params = self._build_anet('oldpi', trainable=False)
        self.sample_op = tf.squeeze(pi.sample(1), axis=0)       # choosing action
        with tf.variable_scope('update_oldpi'):
            self.update_oldpi_op = [oldp.assign(p) for p, oldp in zip(pi_params, oldpi_params)]

        self.tfa = tf.placeholder(tf.float32, [None, a_dim], 'action')
        self.tfadv = tf.placeholder(tf.float32, [None, 1], 'advantage')
        with tf.variable_scope('surrogate'):
            # ratio = tf.exp(pi.log_prob(self.tfa) - oldpi.log_prob(self.tfa))
            ratio = pi.prob(self.tfa) / oldpi.prob(self.tfa)
            surr = ratio * self.tfadv
        if METHOD['name'] == 'kl_pen':
            self.tflam = tf.placeholder(tf.float32, None, 'lambda')
            with tf.variable_scope('loss'):
                kl = tf.stop_gradient(kl_divergence(oldpi, pi))
                self.kl_mean = tf.reduce_mean(kl)
                self.aloss = -(tf.reduce_mean(surr - self.tflam * kl))
        else:   # clipping method, find this is better
            with tf.variable_scope('loss'):
                self.aloss = -tf.reduce_mean(tf.minimum(
                    surr,
                    tf.clip_by_value(ratio, 1.-METHOD['epsilon'], 1.+METHOD['epsilon'])*self.tfadv))

        with tf.variable_scope('atrain'):
            self.atrain_op = tf.train.AdamOptimizer(A_LR).minimize(self.aloss)

        tf.summary.FileWriter("log/", self.sess.graph)

        self.sess.run(tf.global_variables_initializer())

    def update(self, s, a, r, m=20, b=10):
        self.sess.run(self.update_oldpi_op)
        adv = self.sess.run(self.advantage, {self.tfs: s, self.tfdc_r: r})
        # adv = (adv - adv.mean())/(adv.std()+1e-6)     # sometimes helpful

        # update actor
        if METHOD['name'] == 'kl_pen':
            for _ in range(m):
                _, kl = self.sess.run(
                    [self.atrain_op, self.kl_mean],
                    {self.tfs: s, self.tfa: a, self.tfadv: adv, self.tflam: METHOD['lam']})
                if kl > 4*METHOD['kl_target']:  # this in in google's paper
                    break
            if kl < METHOD['kl_target'] / 1.5:  # adaptive lambda, this is in OpenAI's paper
                METHOD['lam'] /= 2
            elif kl > METHOD['kl_target'] * 1.5:
                METHOD['lam'] *= 2
            METHOD['lam'] = np.clip(METHOD['lam'], 1e-4, 10)    # some time explode, this is my method
        else:   # clipping method, find this is better (OpenAI's paper)
            [self.sess.run(self.atrain_op, {self.tfs: s, self.tfa: a, self.tfadv: adv}) for _ in range(m)]

        # update critic
        [self.sess.run(self.ctrain_op, {self.tfs: s, self.tfdc_r: r}) for _ in range(b)]

    def _build_anet(self, name, trainable):
        with tf.variable_scope(name):
            l1 = tf.layers.dense(self.tfs, 100, tf.nn.relu, trainable=trainable)
            mu = 2 * tf.layers.dense(l1, self.a_dim, tf.nn.tanh, trainable=trainable)
            sigma = tf.layers.dense(l1, self.a_dim, tf.nn.softplus, trainable=trainable)
            norm_dist = Normal(loc=mu, scale=sigma)
        params = tf.get_collection(tf.GraphKeys.GLOBAL_VARIABLES, scope=name)
        return norm_dist, params

    def choose_action(self, s):
        s = s[np.newaxis, :]
        a = self.sess.run(self.sample_op, {self.tfs: s})[0]
        return np.clip(a, -2, 2)

    def get_v(self, s):
        if s.ndim < 2: s = s[np.newaxis, :]
        return self.sess.run(self.v, {self.tfs: s})[0, 0]

# Load walking environment
env = RunEnv(args.visualize)

a_dim = env.action_space.shape[0]
s_dim = env.observation_space.shape[0]


ppo = PPO(s_dim=s_dim, a_dim=a_dim)
all_ep_r = []

for ep in range(EP_MAX):
    s = env.reset()
    print(s)
    s = np.asarray(s)

    print(s)

    print('type(s)', type(s))
    print(np.shape(s))
    buffer_s, buffer_a, buffer_r = [], [], []
    ep_r = 0
    for t in range(1, EP_LEN):    # one episode
        a = ppo.choose_action(s)
        s_, r, done, _ = env.step(a)
        buffer_s.append(s)
        buffer_a.append(a)
        buffer_r.append((r+8)/8)    # normalize reward, find to be useful
        s = s_
        ep_r += r

        # update ppo
        if t % (BATCH-1) == 0 or t == EP_LEN-1:
            v_s_ = ppo.get_v(s_)
            discounted_r = []
            for r in buffer_r[::-1]:
                v_s_ = r + GAMMA * v_s_
                discounted_r.append(v_s_)
            discounted_r.reverse()

            bs, ba, br = np.vstack(buffer_s), np.vstack(buffer_a), np.array(discounted_r)[:, np.newaxis]
            buffer_s, buffer_a, buffer_r = [], [], []
            ppo.update(bs, ba, br, m=A_UPDATE_STEPS, b=C_UPDATE_STEPS)
    if ep == 0: all_ep_r.append(ep_r)
    else: all_ep_r.append(all_ep_r[-1]*0.9 + ep_r*0.1)
    print(
        'Ep: %i' % ep,
        "|Ep_r: %i" % ep_r,
        ("|Lam: %.4f" % METHOD['lam']) if METHOD['name'] == 'kl_pen' else '',
    )

plt.plot(np.arange(len(all_ep_r)), all_ep_r)
plt.xlabel('Episode');plt.ylabel('Moving averaged episode reward');plt.show()
```
I think all the dependencies are satisfied. When I run this file in Pycharm Console. There are errors:
```
/home/jack/Applications/anaconda3/envs/opensim-rl/bin/python /home/jack/Applications/opensim/run2.py
Updating Model file from 30000 to latest format...
Loaded model gait9dof18musc_Thelen_BigSpheres.osim from file /home/jack/Applications/anaconda3/envs/opensim-rl/lib/python2.7/site-packages/osim/env/../models/gait9dof18musc.osim
2017-08-12 20:56:11.792837: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-08-12 20:56:11.792856: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-08-12 20:56:11.792860: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-08-12 20:56:11.792863: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-08-12 20:56:11.792866: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
[-0.05, 0.0, 0.91, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.06973405523475405, 0.9707656285552124, 0.0, 0.0, 0.007169537779780744, 1.5365721883823606, 0.0, 0.91, -0.09650084892621281, 0.9964310485677471, 0.007987580127344573, -0.027441466796053905, 0.007987580127344573, -0.027441466796053905, -0.11968333174236659, 0.022952398528571172, -0.11968333174236659, 0.022952398528571172, 1, 1, 100, 0, 0]
[ -5.00000000e-02   0.00000000e+00   9.10000000e-01   0.00000000e+00
   0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00   0.00000000e+00  -6.97340552e-02   9.70765629e-01
   0.00000000e+00   0.00000000e+00   7.16953778e-03   1.53657219e+00
   0.00000000e+00   9.10000000e-01  -9.65008489e-02   9.96431049e-01
   7.98758013e-03  -2.74414668e-02   7.98758013e-03  -2.74414668e-02
  -1.19683332e-01   2.29523985e-02  -1.19683332e-01   2.29523985e-02
   1.00000000e+00   1.00000000e+00   1.00000000e+02   0.00000000e+00
   0.00000000e+00]
('type(s)', <type 'numpy.ndarray'>)
(41,)
Traceback (most recent call last):
  File "/home/jack/Applications/opensim/run2.py", line 150, in <module>
    a = ppo.choose_action(s)
  File "/home/jack/Applications/opensim/run2.py", line 120, in choose_action
    s = s[np.newaxis, :]
TypeError: list indices must be integers, not tuple
```
I have already convert the list  `s = env.reset()` to np.array by using `s = np.asarray(s)`. Why there are still errors about `s = s[np.newaxis, :]`? Is it a bug? Thank you!

**Comment by MSeifert04** [comment]
you know that you replace inside the loop? See the `s = s_` line. Given the exception it's likely that `s_` is a list.

**Comment by JiankaiSun-SJTU-MVIG-training** [comment]
Thank you! @MSeifert04
