### ISSUE TITLE
test_warning_calls "invalid escape sequence \s" on Python 3.6 daily wheel builds.

### ISSUE THREAD

**Issue by matthew-brett** [numpy/numpy#9551]
New errors today (13 August), for Linux and OSX:

```
======================================================================
ERROR: numpy.tests.test_warnings.test_warning_calls
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/venv/lib/python3.6/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/venv/lib/python3.6/site-packages/numpy/tests/test_warnings.py", line 79, in test_warning_calls
    tree = ast.parse(file.read())
  File "/usr/lib/python3.6/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 184
SyntaxError: invalid escape sequence \s
```

https://travis-ci.org/MacPython/numpy-wheels/jobs/264023630
https://travis-ci.org/MacPython/numpy-wheels/jobs/264023631
https://travis-ci.org/MacPython/numpy-wheels/jobs/264023635

**Comment by charris** [comment]
Was worried about that, the problem is
```
file:  numpy/doc/basics.py
line:  184 :  invalid escape sequence \s
```
Came from documentation fixes. Probably need a raw string, although I would prefer making the files genuine rst.

**Comment by charris** [comment]
I should add that check to the tests...
