### ISSUE TITLE
numpy 1.13.1 is incompatible with the current Python `master` branch

### ISSUE THREAD

**Issue by BanzaiMan** [numpy/numpy#9578]
With the current `master` branch, installing numpy (1.13.1) with `pip` fails. https://travis-ci.org/travis-ci/cpython-builder/jobs/265270801#L4793-L4805.

I am using Ubuntu Trusty (on Travis CI, as you can see from above).

```
    gcc: numpy/random/mtrand/mtrand.c
    numpy/random/mtrand/mtrand.c: In function ‘__Pyx_PyCFunction_FastCall’:
    numpy/random/mtrand/mtrand.c:44374:5: error: too many arguments to function ‘(struct PyObject * (*)(struct PyObject *, struct PyObject **, Py_ssize_t))meth’
         return (*((__Pyx_PyCFunctionFast)meth)) (self, args, nargs, NULL);
         ^
    numpy/random/mtrand/mtrand.c: In function ‘__Pyx_PyCFunction_FastCall’:
    numpy/random/mtrand/mtrand.c:44374:5: error: too many arguments to function ‘(struct PyObject * (*)(struct PyObject *, struct PyObject **, Py_ssize_t))meth’
         return (*((__Pyx_PyCFunctionFast)meth)) (self, args, nargs, NULL);
         ^
    error: Command "gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -fPIC -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -Inumpy/core/include -Ibuild/src.linux-x86_64-3.7/numpy/core/include/numpy -Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/opt/python/3.7-dev/include/python3.7m -Ibuild/src.linux-x86_64-3.7/numpy/core/src/private -Ibuild/src.linux-x86_64-3.7/numpy/core/src/npymath -Ibuild/src.linux-x86_64-3.7/numpy/core/src/private -Ibuild/src.linux-x86_64-3.7/numpy/core/src/npymath -Ibuild/src.linux-x86_64-3.7/numpy/core/src/private -Ibuild/src.linux-x86_64-3.7/numpy/core/src/npymath -c numpy/random/mtrand/mtrand.c -o build/temp.linux-x86_64-3.7/numpy/random/mtrand/mtrand.o -MMD -MF build/temp.linux-x86_64-3.7/numpy/random/mtrand/mtrand.o.d" failed with exit status 1
    
    ----------------------------------------
Command "/home/travis/virtualenv/python3.7-dev/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-edymr0nz/numpy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-w8dfy3f5-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/travis/virtualenv/python3.7-dev/include/site/python3.7/numpy" failed with error code 1 in /tmp/pip-build-edymr0nz/numpy/
```

I tried compiling from source as well, but I could not quite figure out how to do that in this setup. (I'm using python-build to build the Python archive for Travis CI.)

I've disabled numpy for now for the `3.7-dev` (a.k.a. `nightly`) builds, so that, if you choose to do so, you can use

```yaml
language: python

python: 3.7-dev
```

in your `.travis.yml` to test against this build.

**Comment by charris** [comment]
Known issue with cython. If you want to test against 3.7 you will need to clone the repo and build from source with the latest cython release.

**Comment by charris** [comment]
Note that this will also be fixed in Numpy 1.13.2, but we are waiting for Python 3.6.2 to show up on the build machines with a fix for the Python 3.6.0, 3.6.1 incompatibility.

**Comment by tacaswell** [comment]
Reading the tea-leaves of who is asking the question, does this mean the nightly env on travis is going to come with numpy pre-installed ?

**Comment by BanzaiMan** [comment]
@tacaswell Unfortunately not, since the released numpy version is incompatible with `nightly`. `3.6-dev` is, so it comes with numpy pre-installed.

**Comment by tacaswell** [comment]
As a consumer of the nightly env, I would be happy with numpy master + cpython master (particularly for Matplotlib testing).

**Comment by BanzaiMan** [comment]
@charris Could you tell me how to build from source, then?

README on this repo is very scant, and the instructions on https://www.scipy.org/scipylib/building/linux.html is a bit…shall I say…dense.

I tried this function:

```bash
function install_numpy_from_source() {
  pushd $HOME/build
  git clone https://github.com/numpy/numpy.git numpy/numpy
  pushd numpy/numpy
  $HOME/virtualenv/$VIRTENV_VERSION/bin/python setup.py build
  $HOME/virtualenv/$VIRTENV_VERSION/bin/python setup.py install
  popd
  popd
}
```

You can assume that `$HOME/virtualenv/$VIRTENV_VERSION/bin/python` is the `python` binary built from the `master` branch of https://github.com/python/cpython.git.

This fails with the first `build` task:

```
~/build ~/build/travis-ci/cpython-builder
Cloning into 'numpy/numpy'...
remote: Counting objects: 124176, done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 124176 (delta 0), reused 2 (delta 0), pack-reused 124167
Receiving objects: 100% (124176/124176), 49.41 MiB | 19.29 MiB/s, done.
Resolving deltas: 100% (98200/98200), done.
~/build/numpy/numpy ~/build ~/build/travis-ci/cpython-builder
Running from numpy source directory.
Cythonizing sources
Processing numpy/random/mtrand/randint_helpers.pxi.in
Processing numpy/random/mtrand/mtrand.pyx
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'Cython'
Traceback (most recent call last):
  File "/home/travis/build/numpy/numpy/tools/cythonize.py", line 70, in process_pyx
    r = subprocess.call(['cython'] + flags + ["-o", tofile, fromfile])
  File "/opt/python/3.7-dev/lib/python3.7/subprocess.py", line 269, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/opt/python/3.7-dev/lib/python3.7/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/opt/python/3.7-dev/lib/python3.7/subprocess.py", line 1332, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'cython'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/build/numpy/numpy/tools/cythonize.py", line 220, in <module>
    main()
  File "/home/travis/build/numpy/numpy/tools/cythonize.py", line 216, in main
    find_process_files(root_dir)
  File "/home/travis/build/numpy/numpy/tools/cythonize.py", line 208, in find_process_files
    process(cur_dir, fromfile, tofile, function, hash_db)
  File "/home/travis/build/numpy/numpy/tools/cythonize.py", line 167, in process
    processor_function(fromfile, tofile)
  File "/home/travis/build/numpy/numpy/tools/cythonize.py", line 81, in process_pyx
    raise Exception('Cython failed')
Exception: Cython failed
Traceback (most recent call last):
  File "setup.py", line 393, in <module>
    setup_package()
  File "setup.py", line 376, in setup_package
    generate_cython()
  File "setup.py", line 212, in generate_cython
    raise RuntimeError("Running cythonize failed!")
RuntimeError: Running cythonize failed!
```

**Comment by BanzaiMan** [comment]
Looks like 

```
  $HOME/virtualenv/$VIRTENV_VERSION/bin/pip install nose pytz cython
```

does the trick.

**Comment by seberg** [comment]
@BanzaiMan yes, that should be fine if the cython is already fixed (which it probably is), you can also run `pip install .` instead of `python setup.py install` I am not sure if the downside of not using pip matters here.

**Comment by BanzaiMan** [comment]
@tacaswell Once https://travis-ci.org/travis-ci/cpython-builder/builds/265614770 passes, numpy (`master`) is available on Python `nightly` (a.k.a. `3.7-dev`) on Travis CI.

**Comment by seberg** [comment]
Very cool! Now we can fail other peoples test suits even faster :)!
