### ISSUE TITLE
import failed: lapack_lite.so: undefined symbol: zungqr_

### ISSUE THREAD

**Issue by ysh329** [numpy/numpy#9597]
## Env.
- RasberryPi, ARM Cortex-A53
- Linux raspberrypi 4.9.35-v7+ #1014 SMP

## Error Message
```shell
yuanshuai@raspberrypi:~ $ python -m numpy
/usr/bin/python: /usr/local/lib/python2.7/dist-packages/numpy/linalg/lapack_lite.so: undefined symbol: zungqr_; 'numpy' is a package and cannot be directly executed
yuanshuai@raspberrypi:~ $ python -c "import numpy"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/usr/local/lib/python2.7/dist-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/__init__.py", line 19, in <module>
    from .polynomial import *
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/polynomial.py", line 20, in <module>
    from numpy.linalg import eigvals, lstsq, inv
  File "/usr/local/lib/python2.7/dist-packages/numpy/linalg/__init__.py", line 51, in <module>
    from .linalg import *
  File "/usr/local/lib/python2.7/dist-packages/numpy/linalg/linalg.py", line 30, in <module>
    from numpy.linalg import lapack_lite, _umath_linalg
ImportError: /usr/local/lib/python2.7/dist-packages/numpy/linalg/lapack_lite.so: undefined symbol: zungqr_
```

**Comment by eric-wieser** [comment]
Which numpy version?

**Comment by ysh329** [comment]
@eric-wieser 
```shell
ysh329@raspberrypi:~ $ pip show numpy
---
Name: numpy
Version: 1.13.1
Location: /usr/local/lib/python2.7/dist-packages
Requires: 
```

**Comment by eric-wieser** [comment]
How did you install numpy? If you install 1.12 instead (by the same method), does the problem go away? 1.13 did overhaul lapack_lite, and it's possible something was missed.

**Comment by ysh329** [comment]
I installed `numpy` using `pip install -U numpy` :rofl:

**Comment by ysh329** [comment]
After degrading `numpy` version to 1.12, I fixed this issue as below:
```shell
yuanshuai@raspberrypi:~ $ python
Python 2.7.9 (default, Sep 17 2016, 20:26:04) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tvm
Loading runtime library /home/yuanshuai/code/tvm/lib/libtvm_runtime.so... exec only
>>> import numpy as np
>>> 
```

**Comment by eric-wieser** [comment]
Please don't close the issue just because it's ok in an old version!

Can you try upgrading again to 1.13, and checking the problem is still there? If so, you've found a bug that we need to fix

**Comment by ysh329** [comment]
@eric-wieser I re-installed using `sudo -H pip install -U numpy` and checked again! Now it's okay as below ! Thanks a lot!
```Shell
yuanshuai@raspberrypi:~ $ python
Python 2.7.9 (default, Sep 17 2016, 20:26:04) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> import tvm
Loading runtime library /home/yuanshuai/code/tvm/lib/libtvm_runtime.so... exec only
>>> exit()
yuanshuai@raspberrypi:~ $ pip show numpy
---
Name: numpy
Version: 1.13.1
Location: /usr/local/lib/python2.7/dist-packages
Requires:
```
