### ISSUE TITLE
Failure importing NumPy 1.13.1 with Python 2.7.

### ISSUE THREAD

**Issue by buddha314** [numpy/numpy#9670]
Fresh install of numpy from both pip and conda.

```
 python
Python 2.7.13 |Continuum Analytics, Inc.| (default, Dec 20 2016, 23:05:08) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import numpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/numpy/__init__.py", line 142, in <module>
  File "/usr/local/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
  File "/usr/local/lib/python2.7/site-packages/numpy/lib/__init__.py", line 8, in <module>
  File "/usr/local/lib/python2.7/site-packages/numpy/lib/type_check.py", line 11, in <module>
  File "/usr/local/lib/python2.7/site-packages/numpy/core/__init__.py", line 24, in <module>
ImportError: 
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.
```

**Comment by bashtage** [comment]
Is your anaconda installed to usr/local/lib?   You might have path problems.

**Comment by buddha314** [comment]
Apparently not

```
which conda
/Users/buddha/miniconda2/bin/conda
```

**Comment by bashtage** [comment]
Are you sure numpy is installed in your conda environment?  It is funding the wrong numpy.   What does conda list show?

**Comment by buddha314** [comment]
```
conda list
# packages in environment at /Users/buddha/miniconda2:
#
argparse                  1.4.0                     <pip>
asn1crypto                0.22.0                   py27_0  
cffi                      1.9.1                    py27_0  
conda                     4.3.25                   py27_0  
conda-env                 2.6.0                         0  
cryptography              1.8.1                    py27_0  
enum34                    1.1.6                    py27_0  
idna                      2.2                      py27_0  
ipaddress                 1.0.18                   py27_0  
mkl                       2017.0.3                      0  
mpi4py                    2.0.0                     <pip>
numpy                     1.13.1                    <pip>
numpy                     1.13.1                   py27_0  
openssl                   1.0.2l                        0  
packaging                 16.8                     py27_0  
pandas                    0.20.3                    <pip>
petsc                     3.7.6                     <pip>
petsc4py                  3.7.0                     <pip>
pip                       9.0.1                    py27_1  
pyasn1                    0.1.9                    py27_0  
pycosat                   0.6.1                    py27_1  
pycparser                 2.17                     py27_0  
pyopenssl                 17.0.0                   py27_0  
pyparsing                 2.2.0                    py27_0  
python                    2.7.13                        0  
python-dateutil           2.6.1                     <pip>
pytz                      2017.2                    <pip>
pyzmq                     16.0.2                    <pip>
readline                  6.2                           2  
requests                  2.12.4                   py27_0  
ruamel_yaml               0.11.14                  py27_1  
scikit-learn              0.19.0                    <pip>
scipy                     0.19.1                    <pip>
setuptools                27.2.0                   py27_0  
six                       1.10.0                   py27_0  
sklearn                   0.0                       <pip>
sqlite                    3.13.0                        0  
tk                        8.5.18                        0  
wheel                     0.29.0                   py27_0  
yaml                      0.1.6                         0  
zlib                      1.2.8                         3 
```

**Comment by bashtage** [comment]
I wouldn't pip install to conda. conda install numpy-f or blow away
Anaconda and start over.

**Comment by buddha314** [comment]
I hope I followed you correctly:

```
conda install -f numpy
Fetching package metadata .........
Solving package specifications: .

Package plan for installation in environment /Users/buddha/miniconda2:

The following NEW packages will be INSTALLED:

    numpy: 1.13.1-py27_0

Proceed ([y]/n)? y

macbuddha:test buddha$ python 
Python 2.7.13 |Continuum Analytics, Inc.| (default, Dec 20 2016, 23:05:08) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import numpy as np
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/numpy/__init__.py", line 142, in <module>
  File "/usr/local/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
  File "/usr/local/lib/python2.7/site-packages/numpy/lib/__init__.py", line 8, in <module>
  File "/usr/local/lib/python2.7/site-packages/numpy/lib/type_check.py", line 11, in <module>
  File "/usr/local/lib/python2.7/site-packages/numpy/core/__init__.py", line 24, in <module>
ImportError: 
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.
```

**Comment by njsmith** [comment]
You seem to have a broken numpy installation stuck into a system-wide directory, and for some reason the conda python is finding it before it finds the conda numpy.

Maybe `sudo pip uninstall numpy` (and then go forth and never use `sudo pip` again).

**Comment by buddha314** [comment]
Apparently, numpy has been installed by pip, conda and brew.  I have run all the uninstall methods and I still have it 

```
python
Python 2.7.13 |Continuum Analytics, Inc.| (default, Dec 20 2016, 23:05:08) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import numpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/numpy/__init__.py", line 142, in <module>
  File "/usr/local/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
  File "/usr/local/lib/python2.7/site-packages/numpy/lib/__init__.py", line 8, in <module>
  File "/usr/local/lib/python2.7/site-packages/numpy/lib/type_check.py", line 11, in <module>
  File "/usr/local/lib/python2.7/site-packages/numpy/core/__init__.py", line 24, in <module>
ImportError: 
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.
```

I don't know who put it there (clearly, I would never do anything so stupid) so I can't figure out how to remove it.

**Comment by njsmith** [comment]
I guess you're down to `sudo rm -rf /usr/local/lib/python2.7/site-packages/numpy*`

**Comment by buddha314** [comment]
Hard times call for hard measures.

```
 rm -rf /usr/local/lib/python2.7/site-packages/numpy
macbuddha:~ buddha$ ls /usr/local/lib/python2.7/site-packages/numpy
ls: /usr/local/lib/python2.7/site-packages/numpy: No such file or directory
macbuddha:~ buddha$ python 
Python 2.7.13 |Continuum Analytics, Inc.| (default, Dec 20 2016, 23:05:08) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import numpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named numpy
>>> 
macbuddha:~ buddha$ conda install numpy
Fetching package metadata .........
Solving package specifications: .

Package plan for installation in environment /Users/buddha/miniconda2:

The following NEW packages will be INSTALLED:

    numpy: 1.13.1-py27_0

Proceed ([y]/n)? y

macbuddha:~ buddha$ python
Python 2.7.13 |Continuum Analytics, Inc.| (default, Dec 20 2016, 23:05:08) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import numpy
 %% MAGIC HAPPENS %%
```

Thanks for your help.  Can't believe I had to go nuclear.
