### ISSUE TITLE
test_varstd_specialcases fails on win32 Python < 3.6

### ISSUE THREAD

**Issue by ghost** [numpy/numpy#9671]
We're looking at this test here:

https://github.com/xoviat/numpy/blob/917652ab0ebc7dfcba5b87902829658fff754730/numpy/ma/tests/test_core.py#L3613

**Comment by pv** [comment]
Traceback from log: https://ci.appveyor.com/project/charris/numpy/build/1.0.6743/job/b9ro4kpqo4h29ljf
```
======================================================================
ERROR: numpy.ma.tests.test_core.TestMaskedArrayMathMethods.test_varstd_specialcases
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python34-x64\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Python34-x64\lib\site-packages\numpy\testing\nose_tools\utils.py", line 2227, in new_func
    return func(*args, **kwargs)
  File "C:\Python34-x64\lib\site-packages\numpy\ma\tests\test_core.py", line 3625, in test_varstd_specialcases
    method(out=nout)
  File "C:\Python34-x64\lib\site-packages\numpy\ma\core.py", line 5212, in std
    np.power(out, 0.5, out=out, casting='unsafe')
RuntimeWarning: invalid value encountered in power
----------------------------------------------------------------------
```

**Comment by WarrenWeckesser** [comment]
Old issue, probably not reproducible, based on a version of Python that is no longer supported.  Closing.
