### ISSUE TITLE
python3 -c 'import numpy; numpy.test()' Failed

### ISSUE THREAD

**Issue by ivankrut856** [numpy/numpy#9706]
python3 -c 'import numpy; numpy.test()' Failed with FAILED (KNOWNFAIL=7, SKIP=18, failures=3). 
Ubuntu 16.04.2 LTS 
NumPy version 1.13.1
NumPy relaxed strides checking option: True
NumPy is installed in /usr/local/lib/python3.5/dist-packages/numpy
Python version 3.5.2 (default, Nov 17 2016, 17:05:23) [GCC 5.4.0 20160609]
nose version 1.3.7

**Comment by eric-wieser** [comment]
Can you tell us which tests failed?

**Comment by ivankrut856** [comment]
FAIL: test_umath.test_nextafter_0

**Comment by ivankrut856** [comment]
FAIL: test_denormal_numbers (test_function_base.TestLinspace)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/numpy/core/tests/test_function_base.py", line 306, in test_denormal_numbers
    assert_(any(linspace(0, stop, 10, endpoint=False, dtype=ftype)))
  File "/usr/local/lib/python3.5/dist-packages/numpy/testing/utils.py", line 92, in assert_
    raise AssertionError(smsg)
AssertionError

======================================================================
FAIL: test_umath.TestComplexFunctions.test_loss_of_precision_longcomplex
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/usr/local/lib/python3.5/dist-packages/numpy/testing/decorators.py", line 217, in knownfailer
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/numpy/core/tests/test_umath.py", line 2383, in test_loss_of_precision_longcomplex
    self.check_loss_of_precision(np.longcomplex)
  File "/usr/local/lib/python3.5/dist-packages/numpy/core/tests/test_umath.py", line 2334, in check_loss_of_precision
    check(x_series, 50*eps)
  File "/usr/local/lib/python3.5/dist-packages/numpy/core/tests/test_umath.py", line 2307, in check
    'arcsinh'))
  File "/usr/local/lib/python3.5/dist-packages/numpy/testing/utils.py", line 92, in assert_
    raise AssertionError(smsg)
AssertionError: (119, 1.4629556339639322701e-10, 1.1102230246251565404e-16, 'arcsinh')

======================================================================
FAIL: test_umath.test_nextafter_0
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/usr/local/lib/python3.5/dist-packages/numpy/core/tests/test_umath.py", line 2512, in test_nextafter_0
    assert_(0. < direction * np.nextafter(t(0), t(direction)) < tiny)
  File "/usr/local/lib/python3.5/dist-packages/numpy/testing/utils.py", line 92, in assert_
    raise AssertionError(smsg)
AssertionError

----------------------------------------------------------------------

**Comment by matthew-brett** [comment]
What platform are you running on?

```
uname -a
```

**Comment by ivankrut856** [comment]
Please, dont tell me there is big value that it's WSL, but not original Ubuntu
Linux DESKTOP-TREV09J 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by matthew-brett** [comment]
I'm afraid so - see : https://github.com/numpy/numpy/issues/8726 and https://github.com/Microsoft/BashOnWindows/issues/1748 and https://github.com/Microsoft/BashOnWindows/issues/830

**Comment by ivankrut856** [comment]
Ok, thanks for info

**Comment by njsmith** [comment]
The good news is that it doesn't matter unless you're using `longdouble`, which you probably aren't (and isn't terribly useful anyway).
