### ISSUE TITLE
csv output for recarrays

### ISSUE THREAD

**Issue by iiSeymour** [numpy/numpy#9907]
You can read a csv with `numpy.genfromtxt` to get a `recarray` however there appears to be no convenient method for writing a `recarray` back out to csv.

**Comment by bashtage** [comment]
An easy method is to use pandas. 

```python
import pandas as pd
pd.DataFrame.from_records(records).to_csv('records.csv')
```

**Comment by iiSeymour** [comment]
@bashtage I was actually switching some code from `pandas` to `numpy` because of `pandas` [thread-safety](http://pandas-docs.github.io/pandas-docs-travis/gotchas.html#thread-safety) when I noticed that csv writing is not available for a `recarray`.

**Comment by bashtage** [comment]
There is also `rec2csv` https://matplotlib.org/api/mlab_api.html#matplotlib.mlab.rec2csv .  Is Pandas not safe for this op? I wouldn't suspect that you would be sharing anything when outputting to csv (and would probably hold the GIL).

**Comment by iiSeymour** [comment]
I just tried out `rec2csv` on simple example and it's throwing exceptions.

```
>>> import numpy as np
>>> from matplotlib.mlab import rec2csv
>>> rec = np.genfromtxt('a.txt', dtype=None, names=True)
>>> rec2csv(rec, 'a.csv', delimiter=',')                                                                
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../venv/lib/python3.5/site-packages/matplotlib/mlab.py", line 3283, in rec2csv
    writer.writerow(header)
TypeError: a bytes-like object is required, not 'str'
```
Without header: 

```
>>> rec2csv(rec, 'a.csv', delimiter=',',  withheader=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../.venv/lib/python3.5/site-packages/matplotlib/mlab.py", line 3301, in rec2csv
    in zip(funcs, row, rowmask, mvals)])
TypeError: a bytes-like object is required, not 'str'
```

Besides the crashing, I'm not using `matplotlib` in the project so having it as an extra dependency just for csv writing is kind of odd.

Is writing a `recarray` to csv something numpy would consider?
