### ISSUE TITLE
einsum works differently for square and rectangular matrices with same indicing 

### ISSUE THREAD

**Issue by spraharsh** [numpy/numpy#9927]
I checked this on numpy version 1.11.3 and 1.12.1.

einsum seems to be switching indices when dealing with a square matrix. the problem is best seen when running this code

```python
i = 2
multiplier = np.arange(1, i+1)
l = np.einsum('ij,i->ij', np.ones((i, i+1)), multiplier)
r = np.einsum('ij,i->ij', np.ones((i, i)), multiplier)
print(l)
print(r)
l2 = np.einsum('ij,j->ij', np.ones((i, i+1)), multiplier)
```

I end up getting this result

```
[[ 1.  1.  1.]
 [ 2.  2.  2.]]
[[ 1.  1.]
 [ 2.  2.]]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/praharsh/Dropbox/workfolder/reproduce-3/bugfixer.py", line 11, in <module>
    l2 = np.einsum('ij,j->ij', np.ones((i, i+1)), multiplier)
ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (2,3)->(2,3) (2,)->(2) 
```

However the summation rules should be independent of the array dimensions. it is clear that the multiplication is wrong for the square matrix

**Comment by spraharsh** [comment]
ouch, I think I misread my output
