### ISSUE TITLE
Inconsistent file extension behaviour between np.save and np.load, no np.loadz

### ISSUE THREAD

**Issue by chrisjbillington** [numpy/numpy#9929]
When you save some arrays using `np.save()`, the extension `.npy` is automatically appended, but when you load with `np.load()`, the extension is not automatically appended.

```python
import numpy as np
x = np.linspace(0,10,10)

np.save('foo', x)
assert np.load('foo') == x
```

```
Traceback (most recent call last):
  File "77.py", line 5, in <module>
    assert np.load('foo') == x
  File "/home/cjb7/anaconda3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 370, in load
    fid = open(file, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'foo'
```

I understand that there are multiple formats, `.npy` and `.npz`, and so whilst `np.save()` and `np.savez()` know what the extension should be, `np.load()` does not, and it is not programmed to guess or try both.

Perhaps there should be a `np.loadz()`, then `np.load()` and `np.loadz()` would be able to append file extensions. I don't see the utility in there being only one `load()` function as there is presently. `np.load()`  returns a different object type depending on whether a `.npy` or `.npz` file is being loaded, and so one must know which one is dealing with already when one calls the function - and therefore one wold know which function to call. I actually assumed there would be a `loadz` function and had to google to discover that `np.load()` is indeed handling both formats, so if it is intended as a simplification I think it actually leads to slightly more confusion on-net.

**Comment by asrvsn** [comment]
+1. There's no reason to append a `.npy` extension at all, in my opinion. `.load()` composed with `.save()` should be the identity function.
