### ISSUE TITLE
numpy meshgrid error

### ISSUE THREAD

**Issue by auroua** [numpy/numpy#9943]
I use meshgrid to generate some 2-d points, but sometimes calls this function raise the following error:
```
Exception ignored in: <generator object broadcast_arrays.<locals>.<genexpr> at 0x7fd41712b570>
Traceback (most recent call last):
  File "/usr/software/anaconda3/lib/python3.6/site-packages/numpy/lib/stride_tricks.py", line 251, in <genexpr>
    if all(array.shape == shape for array in args):
SystemError: error return without exception set
Exception ignored in: <generator object broadcast_arrays.<locals>.<genexpr> at 0x7fd41712b518>
Traceback (most recent call last):
  File "/usr/software/anaconda3/lib/python3.6/site-packages/numpy/lib/stride_tricks.py", line 251, in <genexpr>
    if all(array.shape == shape for array in args):
SystemError: error return without exception set
Exception ignored in: <generator object broadcast_arrays.<locals>.<genexpr> at 0x7fd41712b678>
Traceback (most recent call last):
  File "/usr/software/anaconda3/lib/python3.6/site-packages/numpy/lib/stride_tricks.py", line 251, in <genexpr>
    if all(array.shape == shape for array in args):
SystemError: error return without exception set
```
My code is like this:
```
  shift_x = np.arange(0, width) * feat_stride    # feat_stride=16  
  shift_y = np.arange(0, height) * feat_stride
  shift_x, shift_y = np.meshgrid(shift_x, shift_y)
```
The above error is not reported everytime I run the code.
How to avoid this error.
My numpy version is `1.13.3`.

**Comment by bashtage** [comment]
I cant' reproduce this.  What type are your variables?  (`type(width)`, etc.)

```python
width=10
height=10
import numpy as np
feat_stride=16
shift_x = np.arange(0, width) * feat_stride    # feat_stride=16  
shift_y = np.arange(0, height) * feat_stride
shift_x, shift_y = np.meshgrid(shift_x, shift_y)

shift_x
Out[2]: 
array([[  0,  16,  32,  48,  64,  80,  96, 112, 128, 144],
       [  0,  16,  32,  48,  64,  80,  96, 112, 128, 144],
       [  0,  16,  32,  48,  64,  80,  96, 112, 128, 144],
       [  0,  16,  32,  48,  64,  80,  96, 112, 128, 144],
       [  0,  16,  32,  48,  64,  80,  96, 112, 128, 144],
       [  0,  16,  32,  48,  64,  80,  96, 112, 128, 144],
       [  0,  16,  32,  48,  64,  80,  96, 112, 128, 144],
       [  0,  16,  32,  48,  64,  80,  96, 112, 128, 144],
       [  0,  16,  32,  48,  64,  80,  96, 112, 128, 144],
       [  0,  16,  32,  48,  64,  80,  96, 112, 128, 144]])
```

**Comment by auroua** [comment]
This is a numpy function and called by tensorflow. This error is reported  when the code execut at the `meshgrid` line. When I run the same code on another computer which numpy's version is `1.13.1`, and no error reported.

**Comment by bashtage** [comment]
If you directly run in the example I placed above in  1.13.3 do you see the error?  Sounds like it should be reported to tensorflow.

**Comment by auroua** [comment]
If I directly run this example, no error reported.
