### ISSUE TITLE
Einsum ellipsis broadcasting restriction

### ISSUE THREAD

**Issue by bgavran** [numpy/numpy#9984]
When trying to sum over axes using the ellipsis notation, numpy throws an error.
Minimum code for replication:

```
>>> import numpy as np
>>> a = np.random.rand(2, 3, 5)
>>> np.einsum("...i->i", a)
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda/lib/python3.6/site-packages/numpy/core/einsumfunc.py", line 948, in einsum
    return c_einsum(*operands, **kwargs)
ValueError: output had too few broadcast dimensions
```
As far as I can tell, when ellipsis is both in the result and the argument, the thing works. 
But what would be the preferred way of summing across all axes except the last (or the last few) usin einsum, when the number of axes isn't known beforehand?

I've found a [similar issue](https://github.com/numpy/numpy/pull/4099) from 4 years ago which deals with a similar broadcasting restriction, but nothing more.

Using numpy 1.13.3 and Python 3.6

**Comment by shoyer** [comment]
> But what would be the preferred way of summing across all axes except the last (or the last few) usin einsum, when the number of axes isn't known beforehand?

This doesn't really fit the broadcasting model of NumPy's (generalized) ufuncs, so I'm not surprised this isn't supported. Probably your best bet is to generate the einsum indices dynamically.

**Comment by shoyer** [comment]
That said, this does seem unambiguous, so I would not be opposed to adding support for this to einsum.

**Comment by bgavran** [comment]
>  Probably your best bet is to generate the einsum indices dynamically.

Right, but that breaks the elegance einsum is trying to offer over all the other operations, from a strictly mathematical point of view.

My understanding is that the same way a letter represents a label for an axis, "..." should represent a label for zero or more axes. It needs to match the same axes when its repeated and we can just remove it from the result to implicitly sum over the corresponding axes.

What would be the starting point for the implementation of this functionality?

**Comment by mhvk** [comment]
This doesn't seem logical use of `einsum` - I'd rather just use `sum` directly, as in `a.sum(axis=tuple(a for a in range(a.ndim-1)))` (happily, the `.sum` doesn't do anything for an empty axis tuple, so this does what you'd want).

**Comment by bgavran** [comment]
Thanks for the answer!

While it is possible to use a specialized operation in many of the use cases of einsum, isn't that ignoring the whole purpose of einsum?

Excuse me if I'm missing something obvious. For example, lets say that np.einsum("ij->ji", x) is broken.
@mhvk, isn't your argument just like saying that it shouldn't be fixed and that one should use np.transpose, which behaves exactly in the same way and does what I want?
And it's true, it does, but it completely misses the point. All einsum's operations can be done in some other way, but the beauty of it is that it provides a unified interface one can use.

**Comment by mhvk** [comment]
My argument is that einsum is not broken. It is meant for Einstein notation summation, with an extension for standard numpy broadcasting behaviour. Your use case doesn't fit that: you're summing over dimensions that you do not label. Since there is in fact a good way to do what you want, there seems to be little reason to expand einsum to be something that its name does not suggest (though one could argue it might be useful to document my suggested work-around).

Anyway, I realize the types of argument that appeal to a clean and clear API, with a name that makes sense, are in the eye of the beholder. Really what my comment means is that I do not think it is a good idea and thus am not interested in doing work for it or reviewing it; others may feel differently.

**Comment by eric-wieser** [comment]
>  I'd rather just use sum directly, as in `a.sum(axis=tuple(a for a in range(a.ndim-1)))`

Note that this doesn't cover a case like matrix multiplication followed by summing, which the proposal would allow as `einsum('...ij,...jk->ik')`. Yes, you can write it as `einsum('ij,jk->ik').sum(...)`, but that does large intermediate allocations and is slower (than allocating the einsum letters in a loop).

**Comment by rsokl** [comment]
Is there any reason why `einsum` doesn't generate the indices dynamically internally, as suggested by @shoyer ? There is already an internal numpy function that makes this trivial.

```python
import numpy as np
from numpy.core.einsumfunc import _parse_einsum_input
def my_einsum(*operands):
    operands = _parse_einsum_input(operands)
    return np.einsum("->".join(operands[:-1]), *operands[-1])
```
```python
>>> a = np.random.rand(2, 3, 5)
>>> my_einsum("...i->i", a).shape
(5,)
```
```python
>>> x = np.random.rand(1, 2, 3)
>>> y = np.random.rand(5, 3, 6)
>>> my_einsum('...ij,...jk->ik', x, y).shape
(2, 6)
```


In my mind, this is an elegant and natural thing for einsum to do.
