### ISSUE TITLE
Wrong output while using geomspace with dtype=int keyword argument

### ISSUE THREAD

**Issue by ashwinvis** [numpy/numpy#9987]
# System details
 - system                : Linux
 - kernel                 : 4.9.0-4-amd64
 - distro                  : debian 9.2 
 - CC                      : gcc (Debian 6.3.0-18) 6.3.0 20170516
 - BLAS/LAPACK    : atlas

# Test case

## Code
```python
import numpy as np
gp1 = np.geomspace(2, 8, 3, dtype=int)
gp2 = np.geomspace(2, 8, 3)
np.testing.assert_equal(gp1, gp2)
```

## Traceback
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/scratch/avmo/opt/fluidmeta3/lib/python3.5/site-packages/numpy/testing/utils.py", line 343, in assert_equal
    return assert_array_equal(actual, desired, err_msg, verbose)
  File "/scratch/avmo/opt/fluidmeta3/lib/python3.5/site-packages/numpy/testing/utils.py", line 854, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/scratch/avmo/opt/fluidmeta3/lib/python3.5/site-packages/numpy/testing/utils.py", line 778, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

(mismatch 66.66666666666666%)
 x: array([2, 3, 7])
 y: array([ 2.,  4.,  8.])

```

I would have expected an output like `[2, 4 ,8]` and not `[2, 3, 7]`.

**Comment by ashwinvis** [comment]
`logspace` behaves correctly though:

```python
>>> np.logspace(1, 3, 3, base=2, dtype=int)
array([2, 4, 8])
>>> np.logspace(1, 3, 3, base=2)
array([ 2.,  4.,  8.])

```

**Comment by ashwinvis** [comment]
Turns out the reason is `geomspace` is not double-precision precise as `logspace`. It is not related to the use of `dtype` at all, it just reveals the bug.

```python
>>> import numpy as np
>>> np.set_printoptions(precision=16)
>>> np.geomspace(2, 8, 3, dtype=int)
array([2, 3, 7])
>>> np.geomspace(2, 8, 3)
array([ 2.                ,  3.9999999999999991,  7.9999999999999991])
>>> np.logspace(1, 3, 3, base=2)
array([ 2.,  4.,  8.])
```

**Comment by endolith** [comment]
You saw the discussion on https://github.com/numpy/numpy/pull/7268#issuecomment-193436758 ?

**Comment by ashwinvis** [comment]
I did. I agree that, rounding is not an option, and casting into a dtype is the right thing to do.

However, there is some room for improvement if `logspace` can accurately calculate the geometric progression as integers. I think part of the problem lies in geomspace using `base=10` to generate the geometric progression, and not the "common ratio" of the geometric progression, [here](https://github.com/numpy/numpy/blob/master/numpy/core/function_base.py#L356). I checked it by introducing this change:

```diff
diff --git a/numpy/core/function_base.py b/numpy/core/function_base.py
index 82de1a3..5673941 100644
--- a/numpy/core/function_base.py
+++ b/numpy/core/function_base.py
@@ -350,9 +350,9 @@ def geomspace(start, stop, num=50, endpoint=True, dtype=None):
         start = start + 0j
         stop = stop + 0j
 
-    log_start = _nx.log10(start)
-    log_stop = _nx.log10(stop)
+    log_start = 1.
+    log_stop = _nx.log10(stop) / _nx.log10(start)
     result = out_sign * logspace(log_start, log_stop, num=num,
-                                 endpoint=endpoint, base=10.0, dtype=dtype)
+                                 endpoint=endpoint, base=start, dtype=dtype)
 
     return result.astype(dtype)
```

However, I don't have a solution yet. This will break when the argument `start=1` and result in division by zero.

**Comment by ashwinvis** [comment]
I got it. Will send a PR soon!

**Comment by endolith** [comment]
Yeah I chose `base=10` so that it was exact for common cases like 10, 100, 1000, but couldn't think of how to make it accurate for other cases at the same time.

**Comment by eric-wieser** [comment]
We should probably add a warning to the docs that asking for an int dtype simply does a cast, and may lose precision.

**Comment by ashwinvis** [comment]
And also a runtime warning if `dtype` keyword argument is specified with `int` or its variants?

**Comment by eric-wieser** [comment]
I don't think so - warnings are intended for signalling unexpected runtime behavior, not for telling users to check they actually read the docs.
